- packages/material-ui/src/InputBase/InputBase.js
> [InputBase] Fix cursor on disabled state

- docs/src/pages/utils/popover/AnchorPlayground.js
the copied code doesn't work because missing the closing tag.
Closes #13025
> [docs] Add closing tag in the Popover snippet

- packages/material-ui-docs/src/MarkdownElement/MarkdownElement.js
> [docs] Fewer

- packages/material-ui/src/TextField/TextField.js
Updated the code as discussed and it seems to have solved the problem.
Closes #13076
> [TextField] Ensure labelWidth is set

- docs/src/pages/getting-started/supported-components/supported-components.md
> [docs] Mark Text fields variants as supported

- docs/src/pages/demos/steppers/SwipeableTextMobileStepper.js
SwipeableView is made to auto play the content which make it more interactive.
> [docs] Update SwipeableTextMobileStepper in demos with AutoPlay

- .firebaserc
- babel.config.js
- docs/src/pages/demos/app-bar/PrimarySearchAppBar.js
- docs/src/pages/demos/app-bar/SearchAppBar.js
- docs/src/pages/page-layout-examples/page-layout-examples.md
- pages/index.js
- yarn.lock
The `InputBase` component was built as a starting block for any style override. Better start from it for the app bar search.
Closes #13086
Closes #13085
> [docs] Use the InputBase component for the AppBar demo

- packages/material-ui/src/FormControl/FormControl.js
- packages/material-ui/src/Select/Select.test.js
- pages/api/form-control.md
This PR addresses issue #12197. I noticed the error in that issue and was not sure if it was still being worked on. I would be happy to make any changes to this PR based on feedback.
Closes #12197
> [docs] Warn about the number of inputs allowed in a FormControl

- docs/notifications.json
- docs/src/modules/components/MarkdownDocs.js
- docs/src/modules/components/withRoot.js
> [docs] Repurpose page edit button as Chinese l10n call-to-action

- docs/notifications.json
Push had failed on updating with @xiaoyu-tamu's suggested wording, and I hadn't noticed.
> [docs] Better wording for Chinese notification

- docs/notifications.json
> [docs] Fix the notifications

- docs/src/modules/components/Link.js
- docs/src/pages/demos/snackbars/snackbars.md
- docs/src/pages/demos/tables/tables.md
> [docs] Link the related projects where it's relevant

- packages/material-ui/src/InputBase/Textarea.js
> [Textarea] Merge style with calculated height

- README.md
- docs/notifications.json
- docs/src/modules/components/MarkdownDocs.js
> [docs] Add a translation badge to readme, and update URLs

- docs/src/modules/components/AppTableOfContents.js
- docs/src/modules/components/MarkdownDocs.js
- docs/src/modules/components/withRoot.js
- packages/material-ui-docs/src/MarkdownElement/MarkdownElement.js
I have noticed them looking into a i18n issue.
> [docs] Minor simplifications

- docs/src/modules/components/withRoot.js
> [docs] Defer l18n

- docs/src/pages/page-layout-examples/PageLayoutExamples.js
- docs/src/pages/page-layout-examples/album/Album.js
- docs/src/pages/page-layout-examples/blog/Blog.js
- docs/src/pages/page-layout-examples/blog/Markdown.js
- docs/src/pages/page-layout-examples/checkout/AddressForm.js
- docs/src/pages/page-layout-examples/checkout/Checkout.js
- docs/src/pages/page-layout-examples/checkout/PaymentForm.js
- docs/src/pages/page-layout-examples/checkout/Review.js
- docs/src/pages/page-layout-examples/dashboard/Dashboard.js
- docs/src/pages/page-layout-examples/pricing/Pricing.js
- docs/src/pages/page-layout-examples/sign-in/SignIn.js
- examples/cdn/index.html
- examples/create-react-app-with-flow/src/pages/index.js
- examples/create-react-app-with-jss/src/pages/index.js
- examples/create-react-app-with-typescript/src/pages/index.tsx
- examples/create-react-app/src/pages/index.js
- examples/gatsby/src/pages/index.js
- examples/nextjs/pages/about.js
- examples/nextjs/pages/index.js
- examples/parcel/src/pages/index.js
- examples/ssr/App.js
Merge __after__ 3.2.0 is released
Revert "[docs] Use typography v1 in examples (#13073)"
This reverts commit da311100dbb7cc84341765593dda4fcb2bc1b7bb.
> [docs] Use typography v2 in examples

- docs/src/pages/discover-more/related-projects/related-projects.md
> [docs] Add formik-material-ui

- examples/create-react-app-with-jss/package.json
- examples/create-react-app/package.json
See CompuIves/codesandbox-client#1174
> [examples] Fix codesandbox throwing Invalid comparator

- .tidelift.yml
> [test] Tidelift - skip checking nomnom & os-locale

- BACKERS.md
- GOVERNANCE.md
- README.md
- docs/_redirects
- docs/src/modules/components/Carbon.js
- docs/src/modules/components/CodeFund.js
- docs/src/modules/components/HomeBackers.js
- docs/src/modules/components/MarkdownDocs.js
- docs/src/pages/customization/overrides/DynamicThemeNesting.js
- docs/src/pages/page-layout-examples/blog/Blog.js
- docs/src/pages/page-layout-examples/checkout/Checkout.js
- docs/src/pages/page-layout-examples/pricing/Pricing.js
- docs/src/pages/page-layout-examples/sign-in/SignIn.js
- examples/cdn/index.html
- examples/create-react-app-with-typescript/src/pages/index.tsx
- packages/material-ui/src/Button/Button.test.js
- packages/material-ui/test/typescript/components.spec.tsx
- test/regressions/tests/Button/MaterialV1Buttons.js
We need to set the bar pretty high, so people can safely copy & paste us.
> [docs] Keep working on the SEO issues

- docs/src/pages/demos/autocomplete/IntegrationDownshift.js
> [Autocomplete] Fix the Portal Downshift demo

- packages/material-ui/src/Switch/Switch.js
Hi,
This is for fixing #13121. I had explained as detailed as I could in the [issue](https://github.com/mui-org/material-ui/issues/13121). As a back-end guy, I learned something in this code change. 😅
BTW, this is just my 2nd PR on GitHub, please guide me if I'm not doing right.
Thank you!
Closes #13121
> [Switch] Fix stacking context

- packages/material-ui/src/Radio/Radio.js
- packages/material-ui/src/RadioGroup/RadioGroup.js
- packages/material-ui/src/Switch/Switch.js
- packages/material-ui/src/internal/SwitchBase.d.ts
- packages/material-ui/src/internal/SwitchBase.js
- pages/api/radio-group.md
- pages/api/radio.md
- pages/api/switch.md
Changes to have the components accept number & bool on the value prop, as specified in issue. Closes #12919.
> [Radio][Switch] Accept number & bool as value

- docs/src/pages/demos/steppers/CustomizedStepper.js
- packages/material-ui/src/Step/Step.d.ts
- packages/material-ui/src/Step/Step.js
- packages/material-ui/src/Step/Step.test.js
- packages/material-ui/src/StepConnector/StepConnector.js
- packages/material-ui/src/StepLabel/StepLabel.js
- packages/material-ui/src/Stepper/Stepper.js
- packages/material-ui/src/Stepper/Stepper.test.js
> [Stepper] Forward state properties to StepConnector

- packages/material-ui/src/Step/Step.d.ts
- packages/material-ui/src/Step/Step.js
- packages/material-ui/src/StepLabel/StepLabel.js
- packages/material-ui/src/Stepper/Stepper.js
- packages/material-ui/src/Stepper/Stepper.test.js
I probably was too greedy :). Only revert the bad parts of #13130 and keep the good ones.
@nikhilem Here is the fix ❤️
> [Stepper] We were too greedy, revert

- packages/material-ui/src/Table/Table.js
- pages/api/table.md
Fix a typo in the content that tables normally take
> [docs] Fix a typo in the content that Table normally takes

- packages/material-ui/src/Tab/Tab.js
> [Tabs] Fix IE 11 styling

- docs/src/pages/demos/lists/CheckboxListSecondary.js
Apologies about the two seperate PRs - I was being lazy & using githubs built in editor, but didn't release you can't edit two files on the same automatically generated patch branch 😕
> [docs] Remove usage of non-existent `listItem` jss class (CheckboxListSecondary)

- docs/src/pages/demos/lists/CheckboxList.js
Apologies about the two seperate PRs - I was being lazy & using githubs built in editor, but didn't release you can't edit two files on the same automatically generated patch branch 😕
> [docs] Remove usage of non-existent `listItem` jss class (CheckboxList)

- examples/create-react-app-with-flow/.gitignore
- examples/create-react-app-with-jss/.gitignore
- examples/create-react-app/.gitignore
- examples/gatsby/.gitignore
- examples/nextjs/.gitignore
- examples/parcel/.gitignore
- examples/ssr/.gitignore
I added some more files that should be ignored, like `node_modules` or `.env` files ...
> [examples] Extend the .gitignore files

- docs/src/pages/guides/right-to-left/right-to-left.md
> [docs] Update RTL Guide to be more clear

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
Checklist includes common mistakes when opening PRs especially concerning this repo.
@mui-org/core-contributors Let me know if you have other things that you have to repeat often during review or other things that might be useful for the template.
> [docs] Add checklist to PR template

- packages/material-ui/src/InputBase/InputBase.d.ts
> [InputBase] Add 'renderPrefix' and 'onFilled' signatures

- docs/src/pages/demos/tabs/NavTabs.js
- docs/src/pages/demos/tabs/tabs.md
- packages/material-ui/src/Tab/Tab.js
- pages/demos/tabs.js
- test/regressions/tests/Tabs/SimpleTabs.js
> [Tabs] Center text within tabs

- docs/src/pages/demos/tables/tables.md
- docs/src/pages/getting-started/installation/installation.md
- docs/src/pages/layout/breakpoints/breakpoints.md
> [docs] Some improvements

- packages/material-ui/src/Modal/Modal.js
Simplicity!
Closes #13306
Closes #11964
> [Modal] Restore the focus as fast as possible

- docs/src/modules/components/Ad.js
- docs/src/modules/components/AppSearch.js
- docs/src/modules/components/CodeFund.js
> [docs] Fix ad display

- packages/material-ui/.size-snapshot.json
- packages/material-ui/src/NativeSelect/NativeSelect.js
> [core] Fix NativeSelect's height in FF and Edge

- packages/material-ui/src/StepLabel/StepLabel.js
**Before**
**After**
Can be noticed in https://www.onepixel.com/order/cart.
> [Stepper] Fix visual issue on IE11

- docs/src/pages/demos/cards/RecipeReviewCard.js
> [docs] Correct title attribute for Paella recipe card

- .github/PULL_REQUEST_TEMPLATE.md
One more click might improve the review experience.
> [docs] CONTRIBUTING is not read by default

- packages/material-ui/src/TablePagination/TablePagination.js
- packages/material-ui/src/TablePaginationActions/TablePaginationActions.js
Closes #13334, add inherit color in IconButton components in TablePaginationActions
> [TablePagination] Better color inheritance

- docs/src/pages/style/icons/icons.md
[docs] icons.md: Add import statement to the Icon tag.
> [docs] Let user know where <Icon /> coming from

- docs/src/modules/components/Ad.js
- docs/src/modules/components/AppTableOfContents.js
- docs/src/modules/components/Carbon.js
- docs/src/modules/components/CodeFund.js
- docs/src/modules/components/MarkdownDocs.js
- docs/src/pages/demos/tabs/tabs.md
- docs/src/pages/premium-themes/premium-themes.md
> [docs] Better i18n capability

- .size-limit.js
- docs/src/pages/demos/autocomplete/IntegrationReactSelect.js
Closes https://github.com/mui-org/material-ui/issues/13406
- [ x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui-org/material-ui/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
> [Autocomplete] Fix react-select input overflow

- packages/material-ui/src/Menu/Menu.test.js
- test/regressions/tests/Menu/LongMenu.js
**The test:**
Follow up after #13419 for #13416.
> [Menu] Add a visual regression test

- packages/material-ui/src/NativeSelect/NativeSelect.js
Removed moz-focusring CSS, Fixes #13262.
> [Select] Fix focused text colour

- docs/src/pages/demos/tooltips/InteractiveTooltips.js
> [docs] Update misspelled "Interactive" in Tooltip Demo

- CONTRIBUTING.md
hopefully some wording changes to slightly clarify things
> [docs] Update CONTRIBUTING.md

- docs/src/pages/demos/menus/TypographyMenu.js
- docs/src/pages/demos/menus/menus.md
- packages/material-ui/src/MenuItem/MenuItem.js
- pages/demos/menus.js
> [docs] Add Typography example for MenuItem

- packages/material-ui/src/OutlinedInput/NotchedOutline.js
> [OutlinedInput] Remove Firefox workaround

- packages/material-ui/src/FilledInput/FilledInput.js
- packages/material-ui/src/Input/Input.js
- packages/material-ui/src/OutlinedInput/NotchedOutline.js
- packages/material-ui/src/OutlinedInput/OutlinedInput.js
Fixes #13446 
Before fix
After fix
> [TextField] Fix style focus issue on mobile

- docs/src/pages/page-layout-examples/dashboard/Dashboard.js
- docs/src/pages/page-layout-examples/sign-in/SignIn.js
Updating to most recent naming convention for how classes extends components
> [docs] Save one component in the demo

- package.json
- packages/material-ui/.size-snapshot.json
- packages/material-ui/scripts/rollup.config.js
- yarn.lock
> [core] Fix the CDN release

- docs/src/pages/demos/tooltips/SimpleTooltips.js
> [docs] Remove redundant text

- .size-limit.js
- README.md
- crowdin.yml
- docs/src/modules/components/Ad.js
- docs/src/modules/components/AppFrame.js
- docs/src/modules/components/Demo.js
- docs/src/modules/components/GoogleAnalytics.js
- docs/src/modules/components/MarkdownDocs.js
- docs/src/pages/premium-themes/PremiumThemes.js
- docs/src/pages/style/color/ColorTool.js
- Homepage warning
- Invalid cache i18n badge
- Remove layout markdows from the translation
- Reduce CodeFund display
- Fix W3C HTML5 errors
- Track more events
> [docs] Misc of fixes

- docs/src/modules/utils/generateMarkdown.js
> [core] Pass import filename through normalizePath function

- docs/src/modules/components/AppFrame.js
- docs/src/modules/components/withRoot.js
- docs/src/modules/redux/themeReducer.js
- docs/src/modules/styles/getPageContext.js
- docs/src/modules/styles/themeInitialState.js
- docs/src/pages/style/color/ColorTool.js
> [docs] Add cookie for persistant colors

- CHANGELOG.md
- packages/material-ui-benchmark/src/benchmark.js
- packages/material-ui-styles/src/withStyles.js
> [core] Update the benchmark

- packages/material-ui/src/Button/Button.js
- pages/api/button.md
> [Button] Move deprecated variants at the end of the list

- docs/static/_redirects
> [docs] Add redirect rule for moved page layout examples

- packages/material-ui/src/TablePagination/TablePagination.d.ts
> [TablePagination] Improve TypeScript definition

- docs/src/pages/layout/grid/grid.md
> [docs] Improve Grid limitation description

- docs/src/pages/customization/overrides/overrides.md
- docs/src/pages/customization/themes/themes-zh.md
- docs/src/pages/customization/themes/themes.md
- packages/material-ui-docs/src/MarkdownElement/MarkdownElement.js
This PR makes a minor typo in Theme docs
> [docs] Fix theme menu link

- .size-limit.js
- docs/notifications.json
- docs/src/modules/components/DemoFrame.js
- packages/material-ui/src/Modal/Modal.js
- packages/material-ui/src/Modal/ModalManager.js
- packages/material-ui/src/Modal/ModalManager.test.js
Solves https://github.com/mui-org/material-ui/issues/10000#issuecomment-438751261.
cc @stephen099
> [Modal] Fix the close jump on Windows

- docs/src/pages/demos/steppers/CustomizedStepper.js
- docs/src/pages/demos/steppers/HorizontalLinearStepper.js
- docs/src/pages/demos/steppers/HorizontalNonLinearAlternativeLabelStepper.js
- docs/src/pages/demos/steppers/HorizontalNonLinearStepper.js
- docs/src/pages/demos/steppers/HorizontalNonLinearStepperWithError.js
- docs/src/pages/demos/steppers/VerticalLinearStepper.js
> [docs] Change &quote; to &apos;

- docs/src/pages/getting-started/installation/installation-zh.md
- docs/src/pages/getting-started/installation/installation.md
> [docs] Fix typo in URL

- docs/src/modules/components/Demo.js
- docs/src/modules/components/MarkdownDocs.js
- docs/src/modules/utils/helpers.js
- docs/src/modules/utils/helpers.test.js
- docs/src/pages/css-in-js/advanced/advanced.md
- docs/src/pages/css-in-js/basics/basics.md
- [docs] Add support for changing react version in codesandbox demos
- [docs] Change styles Hook API codesandbox to use next version of react and react-dom
Fixes #13680
Not sure if the demoOptions key should be `react` or `reactVersion`
> [docs] Add support for changing react version in codesandbox demos

- CHANGELOG.md
Extended the short description of the chang and simply c&p the explanation from #13574.
> [CHANGELOG] Add deprecation notice for Divider

- packages/material-ui/src/Tooltip/Tooltip.js
- packages/material-ui/src/Tooltip/Tooltip.test.js
> [Tooltip] Hide native title when disableHoverListener is true

- packages/material-ui/src/index.d.ts
- packages/material-ui/src/styles/overrides.d.ts
This PR closes #13703.
It's not my intention to take anyone's credit, just throwing this out there :wave:
> [Fab] Add Fab type declaration to index and theme

- docs/src/pages/demos/tables/CustomPaginationActionsTable.js
- packages/material-ui/src/TablePagination/TablePagination.js
> [TablePagination] Support native selection

- docs/src/modules/components/DemoFrame.js
> [docs] Fix concurrency with Frame demos

- packages/material-ui/src/LinearProgress/LinearProgress.js
- pages/api/linear-progress.md
Fixes #13712.
Removed the bar2determinate styling from the code and updated the component API docs.
> [LinearProgress] Remove dead code

- packages/material-ui/src/FormControl/FormControl.spec.tsx
Closes #13744
~Waiting for #13755~
> [typescript] Add test case for FormControl type limitations

- packages/material-ui/src/Popover/Popover.js
- packages/material-ui/src/Popover/Popover.test.js
Solves https://github.com/mui-org/material-ui/pull/13675#issuecomment-442859853.
> [Popover] Handle resize close concurrency issue

- packages/material-ui/src/List/List.spec.tsx
Adds test for #13744.
Issue should stay open so that it appears on github milestones.
> [typescript] Add test case for List type limitations

- packages/material-ui/src/Tooltip/Tooltip.js
- packages/material-ui/src/Tooltip/Tooltip.test.js
Closes https://github.com/mui-org/material-ui/issues/13756
> [Tooltip] Supress warning if button is disabled and title is empty

- docs/src/pages/getting-started/installation/installation.md
- docs/src/pages/getting-started/usage/usage.md
The link tags either need a closing tags or to self close or else React won't compile.
> [docs] Link tags HTML vs JSX

- docs/src/pages/demos/menus/menus.md
> [docs] Missing text in docs

- packages/material-ui/src/Modal/Modal.test.js
- packages/material-ui/src/Modal/ModalManager.js
> [Modal] Handle modal mount interruption

- docs/src/pages/demos/buttons/IconLabelButtons.js
> [docs] Fix KeyboardIcon import name

- packages/material-ui/src/BottomNavigationAction/BottomNavigationAction.js
Closes https://github.com/mui-org/material-ui/issues/13787
> [BottomNavigation] Improve action padding

- BACKERS.md
- docs/src/pages/css-in-js/basics/basics.md
- packages/material-ui-styles/src/ThemeProvider.js
- packages/material-ui-styles/src/withStyles.js
- packages/material-ui/src/styles/withStyles.js
> [docs] Add more details regarding installation of material-ui/styles

- docs/src/pages/customization/overrides/overrides-zh.md
- docs/src/pages/customization/overrides/overrides.md
- docs/src/pages/customization/themes/themes-zh.md
- docs/src/pages/customization/themes/themes.md
> [docs] Fix broken link anchor

- docs/src/modules/components/AppSearch.js
Closes https://github.com/mui-org/material-ui/issues/13870
> [docs] Fix search suggestions on dark mode

- packages/material-ui/src/Tabs/Tabs.js
> [Tabs] Correct typo in error message

- docs/src/pages/premium-themes/onepirate/modules/views/ProductHowItWorks.js
- packages/material-ui/src/Button/Button.js
- packages/material-ui/src/Dialog/Dialog.js
- packages/material-ui/src/Typography/Typography.js
Just for consistency. The prefix was missing at some places.
> [core] Prefix the errors with Material-UI

- packages/material-ui/src/Tooltip/Tooltip.d.ts
- packages/material-ui/src/Tooltip/Tooltip.js
- pages/api/tooltip.md
Fix this issue: https://codesandbox.io/s/m3840qxwkx
**actual behavior**: The icon button flicker
**expected behavior**: The icon button shouldn't flicker
> [Tooltip] Fix hover display issue

- packages/material-ui/src/Slide/Slide.js
Closes https://github.com/mui-org/material-ui/issues/13906
> [Slide] Remove direction from being passed on to children

- docs/src/pages/demos/text-fields/FormattedInputs.js
- docs/src/pages/demos/text-fields/text-fields.md
- packages/material-ui/src/InputBase/InputBase.js
- test/utils/createDOM.js
> [Input] Check custom input inputRef implementation

- docs/src/pages/demos/text-fields/CustomizedInputBase.js
- docs/src/pages/demos/text-fields/GoogleMapsInspiredSearch.js
- docs/src/pages/demos/text-fields/text-fields.md
- pages/demos/text-fields.js
> [TextField] Add Solo Field demo

- docs/src/pages/demos/text-fields/text-fields.md
> [TextField] Reword solo textfield documentation

- .size-limit.js
- docs/src/pages/demos/autocomplete/IntegrationReactSelect.js
Closes https://github.com/mui-org/material-ui/issues/13890
> [Autocomplete] Update react-select demo to have isClearable set to true

- .size-limit.js
- docs/src/modules/utils/helpers.js
- docs/src/modules/utils/helpers.test.js
- docs/src/pages/demos/pickers/MaterialUIPickers.js
Closes https://github.com/mui-org/material-ui/issues/13951
> [docs] Fix material-ui-pickers codesandbox demo

- packages/material-ui/src/Tab/Tab.js
- packages/material-ui/src/Tab/Tab.test.js
- pages/api/tab.md
Closes https://github.com/mui-org/material-ui/issues/13903.
> [Tab] Remove font size change logic

- .size-limit.js
- docs/src/pages/demos/buttons/ButtonSizes.js
- packages/material-ui/src/Fab/Fab.js
Closes https://github.com/mui-org/material-ui/issues/13891
> [Fab] Add styles to make size property work with extended property

- packages/material-ui/src/CardHeader/CardHeader.js
This fixes a minor visual issue I found in v3.7.0. See https://github.com/mui-org/material-ui/pull/13788#issuecomment-449584092 for information
> [CardHeader] Change action element to have a fixed right margin

- docs/src/modules/components/AppTableOfContents.js
- docs/src/pages/guides/interoperability/StyledComponents.js
- docs/src/pages/guides/interoperability/StyledComponentsDeep.js
- docs/src/pages/guides/interoperability/StyledComponentsPriority.js
- docs/src/pages/guides/interoperability/StyledComponentsTheme.js
- docs/src/pages/guides/interoperability/interoperability.md
- package.json
- packages/material-ui-benchmark/package.json
- pages/getting-started/installation.js
- pages/premium-themes.js
Using styled-components? You can leverage all the CSS helpers Material-UI has.
> [docs] Theme usage with styled-components

- docs/src/pages/demos/buttons/FloatingActionButtonZoom.hooks.js
- docs/src/pages/demos/buttons/FloatingActionButtonZoom.js
- docs/src/pages/demos/tabs/NavTabs.hooks.js
- test/regressions/tests/Tabs/SimpleTabs.js
> [docs] Fix fullWidth deprecation warnings

- packages/material-ui-system/src/responsivePropType.js
- packages/material-ui-system/src/spacing.js
- packages/material-ui-system/src/style.js
Follow-up on #13632. The issue was raised by @eps1lon.
> [system] Fix responsivePropType typo

- packages/material-ui-system/README.md
> [docs] Update URL for @material-ui/system

- docs/src/modules/utils/generateMarkdown.js
- pages/api/tabs.md
Fixes the markdown generator 
https://material-ui.com/api/tabs/
Before
After
> [core] Fix multiline deprecatedPropType

- docs/src/modules/components/DemoFrame.js
> [docs] Fix demo iframe styling in Firefox

- packages/material-ui-docs/package.json
- packages/material-ui-icons/package.json
- packages/material-ui-lab/package.json
- packages/material-ui-styles/package.json
- packages/material-ui-utils/package.json
- packages/material-ui/package.json
- yarn.lock
This should help with package deduplication.
> [core] Relax @babel/runtime version to ^7.2.0

- docs/src/pages/discover-more/showcase/Showcase.js
> [docs] Add GovX to Showcase, move Onepixel

- docs/src/pages/system/api/api.md
- docs/src/pages/system/sizing/sizing.md
Adjusting the docs according to: 
https://github.com/mui-org/material-ui/blob/master/packages/material-ui-system/src/sizing.js#L43
> [docs] Correct API typos

- README.md
- docs/src/pages/discover-more/showcase/Showcase.js
> [docs] Add Tidelift security link to README

- docs/src/pages/premium-themes/onepirate/ForgotPassword.js
> [themes] Fix typo on Onepirate Forgot Password page

- docs/src/modules/components/Demo.js
> [docs] Fix deprecated Typography variants warning in demos

- packages/material-ui-styles/package.json
> [styles] Add missing dependency hoist-non-react-statics

- docs/src/modules/components/AppTableOfContents.js
- docs/src/pages/demos/tooltips/tooltips.md
> [docs] Update Tooltip info on prop spread

- docs/src/pages/getting-started/example-projects/example-projects.md
A new section, as discussed at #14097, to include the example https://github.com/alexanmtz/material-sense about more advanced project examples.
Close #14097
> [docs] Update example projects with Material Sense

- BACKERS.md
- README.md
- docs/src/modules/components/HomeBackers.js
> [docs] Add Yakaz to homepage, backers & readme

- packages/material-ui/src/CircularProgress/CircularProgress.js
Closes https://github.com/mui-org/material-ui/issues/14192
> [CircularProgress] Fix animation jumps on indeterminate variant

- packages/material-ui/src/InputBase/Textarea.js
Closes https://github.com/mui-org/material-ui/issues/14181
> [Textarea] Fix line height visibility issue on SSR

- docs/src/pages/utils/transitions/SimpleFade.js
Closes https://github.com/mui-org/material-ui/issues/14199
> [docs] Fix fade transition visual bug on codesandbox

- docs/src/pages/system/sizing/Values.js
- docs/src/pages/system/sizing/sizing.md
- packages/material-ui-system/src/sizing.js
> [system] Add fractions support

- docs/src/pages/discover-more/related-projects/related-projects.md
> [Docs] Fix grammar in related-projects.md

- docs/src/pages/guides/server-rendering/server-rendering.md
> [styles] Document the right react-jss version for legacy style modules

- docs/src/pages/discover-more/showcase/Showcase.js
Hello from Bethesda.net and thank you for featuring our app! We'd like to update the title of the application to Bethesda.net -- Bethesda Game Studios represents a subset of our organization.
> [docs] Correct Bethesda.net title in app list

- packages/material-ui-lab/src/SpeedDial/SpeedDial.d.ts
- packages/material-ui/src/Dialog/Dialog.d.ts
- packages/material-ui/src/Popover/Popover.d.ts
- packages/material-ui/src/Snackbar/Snackbar.d.ts
- packages/material-ui/src/Tooltip/Tooltip.d.ts
> [Dialog] Add missing PaperComponent property in the definition

- docs/src/pages/layout/use-media-query/use-media-query.md
I just found what I'd believe to be a spelling mistake... Even though I like the concept of Ponyfilling things!
> [docs] Change ponyfill to polyfill in use-media-query.md

- docs/src/pages/customization/css-in-js/css-in-js.md
> [docs] Update jss.createStyleSheet link URL

- docs/notifications.json
- docs/src/modules/components/AppFrame.js
- docs/src/modules/components/AppSearch.js
- docs/src/modules/components/AppWrapper.js
- docs/src/modules/components/GoogleAnalytics.js
- docs/src/modules/components/Link.js
- docs/src/modules/components/MarkdownLinks.js
- docs/src/modules/components/Notifications.js
- docs/src/pages/layout/use-media-query/use-media-query.md
- docs/src/pages/premium-themes/tweeper/theme/tweeper/components/badge.js
- pages/_app.js
> [docs] Notification by locale

- .size-limit.js
- packages/material-ui/src/Dialog/Dialog.js
- packages/material-ui/src/Dialog/Dialog.test.js
> [Dialog] Check target has not changed before closing

- packages/material-ui/src/GridListTileBar/GridListTileBar.d.ts
Closes #14274
- [ X ] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui-org/material-ui/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
> [GridListTileBar] Add missing titleWrap key

- docs/src/pages/demos/pickers/pickers.md
> [Pickers] Promote material-ui-pickers

- packages/material-ui/src/LinearProgress/LinearProgress.d.ts
This pull request removes dead code forgotten in #13712
> [LinearProgress] Remove dead bar2Determinate CSS class

- packages/material-ui/src/Select/SelectInput.js
> [Select] Help automated UI testing

- packages/material-ui-styles/src/mergeClasses.js
- packages/material-ui/src/styles/mergeClasses.js
- packages/material-ui/src/styles/withStyles.test.js
```jsx
<AppBar classes="fsefs" />
```
> [styles] Better warning message

- docs/notifications.json
- docs/src/modules/components/AppFrame.js
- docs/src/modules/components/AppWrapper.js
- docs/src/modules/constants.js
- docs/src/modules/utils/generateMarkdown.js
> [docs] Support 8 languages

- docs/src/pages/demos/pickers/pickers-ru.md
The biggest issue in russian translation here - that the work `picker` doesn't have an alternative in russian language. Especially for programmers we are saying `pickers`  with an ugly russian accent. :D
> Translate pickers demo page in russian

- docs/scripts/buildIcons.js
- docs/src/pages/demos/progress/DelayingAppearance.hooks.js
- docs/src/pages/demos/progress/DelayingAppearance.js
- packages/material-ui/src/ButtonBase/TouchRipple.js
- packages/material-ui/src/Modal/Modal.test.js
- packages/material-ui/src/Portal/Portal.js
- packages/material-ui/src/Portal/Portal.test.js
- packages/material-ui/src/Tooltip/Tooltip.js
> [Portal] Fix onRendered being called before child componentDidUpdate

- docs/src/modules/components/AppFrame.js
- docs/src/modules/components/MarkdownDocs.js
- docs/src/modules/components/Tidelift.js
- docs/src/pages/customization/default-theme/DefaultTheme.js
- Enable some languages where we have translations
- Fix a key React warning
- Load the right language markdown
> [docs] Fix i18n logic

- docs/src/pages/discover-more/showcase/Showcase.js
- docs/src/pages/discover-more/showcase/appList.js
- docs/src/pages/discover-more/showcase/showcase.md
> [docs] Add sorting to Showcase

- packages/material-ui/src/ListItem/ListItem.d.ts
> [ListItem] Add alignItems prop to ListItem.d.ts

- packages/material-ui/src/useMediaQuery/unstable_useMediaQuery.d.ts
> [useMediaQuery] Fix typings for options object

- .size-limit.js
- docs/src/pages/demos/selects/CustomizedSelects.js
- packages/material-ui/src/NativeSelect/NativeSelect.js
> [NativeSelect] Fix option background for dark theme

- docs/src/pages/demos/buttons/OutlinedButtons.js
- packages/material-ui/src/Button/Button.js
- packages/material-ui/src/Button/Button.test.js
> [Button] Add color inherit to outlined variant of button component

- docs/src/pages/demos/progress/CircularDeterminate.hooks.js
- docs/src/pages/demos/progress/CircularStatic.hooks.js
- docs/src/pages/demos/progress/LinearBuffer.hooks.js
- docs/src/pages/demos/progress/LinearDeterminate.hooks.js
Spotted these while looking at hook demos.
> [docs] Minor Hook Demo fixes

- docs/src/pages/demos/menus/menus.md
> [MenuItem] Improve note about using ellipsis

- packages/material-ui/src/Tabs/Tabs.js
Fixes #14375 with these changes. Tested on the demo pages.
> [Tabs] Fix scrollbar appearing briefly on scroller

- docs/src/pages/guides/composition/composition.md
> [docs] Revise the wrapping components guide wording

- docs/src/pages/layout/use-media-query/use-media-query.md
> [docs] Update use-media-query.md

- .size-limit.js
- docs/src/pages/demos/dialogs/dialogs.md
- docs/src/sw.js
- docs/static/_redirects
- packages/material-ui-lab/scripts/copy-files.js
- packages/material-ui-styles/scripts/copy-files.js
- packages/material-ui/scripts/copy-files.js
- Reduce size-limit
- Fix SW cache issue
- Fix small typo
- Add typings
- Fix some SEO issue
> [docs] Fix the SW cache between updates

- CHANGELOG.md
> [CHANGELOG] Prepare v3.9.2

- packages/material-ui/src/Box/Box.d.ts
- packages/material-ui/src/Box/index.d.ts
https://material-ui.com/utils/box/#box-unstable
> [Box] Add typings

- packages/material-ui/src/Dialog/Dialog.d.ts
- packages/material-ui/src/Dialog/Dialog.js
- pages/api/dialog.md
> [Dialog] Fix inconsistencies with scroll="body"

- docs/notifications.json
> [docs] Add analytics to language notifications

- README.md
- docs/src/pages/lab/breadcrumbs/breadcrumbs.md
- docs/src/pages/utils/modal/modal.md
- examples/cdn-next/README.md
- examples/cdn-next/index.html
- examples/cdn-next/package.json
- examples/create-react-app-with-flow/README.md
- examples/create-react-app-with-jss/README.md
- examples/create-react-app-with-typescript/README.md
- examples/create-react-app/README.md
- examples/gatsby/README.md
- examples/nextjs-hooks-with-typescript/README.md
- examples/nextjs-hooks/README.md
- examples/nextjs/README.md
- examples/parcel/README.md
- examples/ssr/README.md
- packages/material-ui/src/styles/createMuiTheme.js
- packages/material-ui/test/umd/run.js
- pages/api/link.md
- pages/api/typography.md
> [theme] Improve the state warning

- docs/src/modules/components/AppFrame.js
- docs/src/modules/components/AppSearch.js
- docs/src/modules/components/Demo.js
- docs/src/modules/components/MarkdownDocs.js
- docs/src/modules/utils/compose.js
- docs/src/pages/layout/hidden/BreakpointDown.js
- docs/src/pages/layout/hidden/BreakpointOnly.js
- docs/src/pages/layout/hidden/BreakpointUp.js
- docs/src/pages/layout/hidden/GridIntegration.js
- docs/src/pages/premium-themes/onepirate/ForgotPassword.js
- docs/src/pages/premium-themes/onepirate/SignIn.js
- docs/src/pages/premium-themes/onepirate/SignUp.js
- docs/src/pages/premium-themes/onepirate/modules/views/AppFooter.js
- docs/src/pages/style/color/ColorTool.js
https://github.com/mui-org/material-ui/pull/14413#issuecomment-460697323
> [docs] Remove recompose/compose

- packages/material-ui/src/ListItem/ListItem.js
> [ListItem] Improve phrasing of error message

- docs/src/pages/customization/overrides/overrides.md
> [docs] Improve overrides.md wording

- packages/material-ui/src/Select/SelectInput.js
- packages/material-ui/src/Select/SelectInput.test.js
> [Select] Open select when focused with enter

- docs/src/modules/components/AppSearch.js
- docs/src/modules/components/AppWrapper.js
- docs/src/modules/styles/getPageContext.js
- docs/src/pages/style/icons/FontAwesome.js
- pages/_app.js
- pages/_document.js
*Credits to @oliviertassinari for proposing the changes*.
> [docs] Fix broken font-awesome icons in documentation

- docs/src/pages/utils/popper/MinimalPopper.hooks.js
- docs/src/pages/utils/popper/MinimalPopper.js
- docs/src/pages/utils/popper/SimplePopper.hooks.js
- docs/src/pages/utils/popper/popper.md
Following @kitze's [tweet](https://twitter.com/thekitze/status/1093808808177090560).
> [Popper] Add hook API demo

- docs/src/modules/components/Ad.js
- docs/src/modules/components/Demo.js
- docs/src/modules/components/HomeBackers.js
- docs/src/modules/components/HomeFooter.js
- docs/src/modules/components/HomeSteps.js
- docs/src/modules/components/MarkdownDocs.js
- docs/src/pages/customization/default-theme/DefaultTheme.js
- docs/src/pages/discover-more/showcase/Showcase.js
- docs/src/pages/getting-started/page-layout-examples/PageLayoutExamples.js
- docs/src/pages/premium-themes/PremiumThemes.js
- docs/src/pages/premium-themes/onepirate/ForgotPassword.js
- docs/src/pages/premium-themes/onepirate/SignIn.js
- docs/src/pages/premium-themes/onepirate/modules/views/AppFooter.js
- docs/src/pages/style/color/ColorTool.js
> [docs] Standardise compose util usage

- docs/src/pages/demos/breadcrumbs/CollapsedBreadcrumbs.js
- docs/src/pages/demos/breadcrumbs/CustomSeparator.js
- docs/src/pages/demos/breadcrumbs/CustomizedBreadcrumbs.js
- docs/src/pages/demos/breadcrumbs/IconBreadcrumbs.js
- docs/src/pages/demos/breadcrumbs/RouterBreadcrumbs.js
- docs/src/pages/demos/breadcrumbs/SimpleBreadcrumbs.js
Simple typo fix. Closes #14480
> [Breadcrumbs] Fix wrong aria label property

- docs/src/modules/redux/optionsReducer.js
> [docs] Fall back to English if translation missing

- docs/src/pages/getting-started/installation/installation.md
Added yarn command to add @material-ui/icons as well.
> [docs] yarn command to add @material-ui/icons

- packages/material-ui-styles/src/index.d.ts
- packages/material-ui-styles/src/index.spec.tsx
> [styles] Type ThemeProvider and getThemeProps generic

- docs/src/modules/components/AppFrame.js
- docs/src/pages/utils/modal/modal.md
- docs/src/pages/utils/portal/portal.md
> [docs] Enable es, fr, pt & ru

- docs/src/pages/demos/steppers/HorizontalNonLinearStepper.hooks.js
Fix back button going forward in hooks' demo.
> [docs] Fix Horizontal Non-linear Stepper demo

- docs/src/modules/components/EditPage.js
> [docs] Update the branch for Crowdin

- docs/src/modules/utils/getDemoConfig.js
- docs/src/modules/utils/helpers.js
Fix hooks codesandbox and resolves issue https://github.com/mui-org/material-ui/issues/14491
Closes #14491
> [docs] Fix hooks codesandbox broken

- .github/ISSUE_TEMPLATE/3.support.md
- .github/ISSUE_TEMPLATE/4.support-us.md
- GOVERNANCE.md
- README.md
- SUPPORT.md
- docs/notifications.json
- docs/src/pages/discover-more/community/community.md
- docs/src/pages/getting-started/faq/faq.md
> [docs] Change Gitter to Spectrum

- docs/src/pages/lab/breadcrumbs/SimpleBreadcrumbs.js
> [docs] Fix typo in simple breadcrumbs example

- CONTRIBUTING.md
Sparked by https://github.com/mui-org/material-ui/issues/13277#issuecomment-464569348.
> [docs] Add sections about translation contributions

- packages/material-ui-styles/src/makeStyles.js
- packages/material-ui-styles/src/makeStyles.test.js
- packages/material-ui-styles/src/useTheme.js
Help with https://github.com/gatsbyjs/gatsby/issues/8237
> [styles] Add react-hot-loader support

- docs/src/modules/components/AppFrame.js
- docs/src/modules/components/AppSearch.js
- docs/src/modules/components/AppWrapper.js
- docs/src/modules/components/EditPage.js
- docs/src/modules/components/MarkdownDocs.js
- docs/src/modules/constants.js
- docs/src/modules/utils/generateMarkdown.js
- docs/src/pages/css-in-js/basics/basics.md
- docs/src/pages/discover-more/team/Team.js
- docs/src/pages/discover-more/team/team.md
- docs/src/pages/getting-started/learn/learn.md
- docs/src/pages/getting-started/page-layout-examples/page-layout-examples.md
> [docs] Update the Team

- docs/src/modules/components/MarkdownLinks.js
> [docs] Solve Firefox middle click issue

- packages/material-ui/package.json
- yarn.lock
> [core] Solve Babel dependency issue

- docs/src/pages/demos/dialogs/ScrollDialog.hooks.js
- docs/src/pages/demos/dialogs/ScrollDialog.js
Add extra content to ScrollDialog demo so that it's scrollable on 4k displays
- [*] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui-org/material-ui/blob/next/CONTRIBUTING.md#submitting-a-pull-request).
Closes #14611
> [docs] Update ScrollDialog Demo for 4k

- docs/src/pages/css-in-js/advanced/advanced.md
- docs/src/pages/customization/css-in-js/css-in-js.md
The hash link was minorly different from the actual intended value.
Please note also that the link immediately following the changed one is broken and there did not appear to be a similar URL with which to replace it.
- [+] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui-org/material-ui/blob/next/CONTRIBUTING.md#submitting-a-pull-request).
> [docs] Fix broken hash link in css-in-js

- docs/src/pages/layout/grid/grid.md
> [docs] Improve Grid limitations description

- .circleci/config.yml
- package.json
General effort to remove some complexity from `.circleci/config.yml` and speedup build times. Commits are atomic.
Changes:
- Don't use offline cache anymore  
- use *-browsers docker image instead of apt install
- Move docs:api to test_build 
- Use 2.1 commands
> [ci] Speedup and cleanup

- packages/material-ui/src/Tabs/Tabs.d.ts
> [Tabs] Fix variant missing in Tabs.d.ts

- docs/src/pages/demos/autocomplete/IntegrationAutosuggest.js
- docs/src/pages/demos/autocomplete/IntegrationDownshift.hooks.js
- docs/src/pages/demos/autocomplete/IntegrationDownshift.js
- docs/src/pages/demos/autocomplete/IntegrationReactSelect.hooks.js
- docs/src/pages/demos/autocomplete/IntegrationReactSelect.js
> [Autocomplete] Improve demo

- docs/src/pages/getting-started/usage/usage.md
> [docs] A grammar modification suggestion

- packages/material-ui/src/ButtonBase/focusVisible.js
- packages/material-ui/src/ListItem/ListItem.js
- packages/material-ui/src/MenuItem/MenuItem.js
Fix #14673 
* Revert change for ListItem in #14212
* Add button focus style in MenuItem
> [ListItem] Fix listItem focus

- .yarnrc
> [core] Fix .yarnrc syntax

- docs/src/modules/components/AppTableOfContents.js
- docs/src/modules/components/MarkdownDocs.js
- docs/src/pages/guides/interoperability/interoperability.md
- packages/material-ui-docs/src/MarkdownElement/MarkdownElement.js
- packages/material-ui-docs/src/MarkdownElement/textToHash.js
- packages/material-ui-docs/src/MarkdownElement/textToHash.test.js
Follow-up on #14632, the remote repository was removed, I can't push the changes.
@mbrookes, I have added the onClick logic back and removed the hash logic to fix the go back navigation issue with Chrome. Let me know.
> [docs] Generate unique hash

- docs/src/modules/components/HomeBackers.js
- docs/src/modules/components/HomeFooter.js
- packages/material-ui-lab/src/Container/Container.js
- packages/material-ui-lab/src/Container/Container.test.js
- packages/material-ui/src/Dialog/Dialog.js
- pages/index.js
I have tried to use this unpublished component in an isolated project unsuccessfully. This should fix two runtime exceptions.
I'm removing the spacing from the computation of the max width. I hope it simplifies the logic, like the one we have in the Dialog. The spacing can be managed independently.
> [Container] Fix two exceptions

- docs/src/pages/demos/drawers/SwipeableTemporaryDrawer.hooks.js
- docs/src/pages/demos/drawers/SwipeableTemporaryDrawer.js
- docs/src/pages/demos/drawers/TemporaryDrawer.hooks.js
- docs/src/pages/demos/drawers/TemporaryDrawer.js
> [docs] Fix Drawer demos accessibility

- packages/material-ui/src/CssBaseline/CssBaseline.js
> [CssBaseline] Apply body2 styling to the body element

- docs/src/pages/guides/testing/testing.md
> [docs] before() is Mocha; beforeEach() is Jest

- babel.config.js
- package.json
> [docs] Fix IE 11 build

- docs/src/pages/customization/css-in-js/css-in-js.md
The links to http://cssinjs.org/jss-api/ were directing to 404. Link was missing an s
> [docs] Update link to http://cssinjs.org/jss-api/

- packages/material-ui/test/umd/run.js
- test/karma.conf.js
Fix build fails like this one:
https://circleci.com/gh/mui-org/material-ui/76815
> [test] Disable the user sandbox security feature

- docs/src/modules/components/Notifications.js
- docs/src/pages/demos/app-bar/PrimarySearchAppBar.js
- docs/src/pages/demos/app-bar/PrimarySearchAppBar.tsx
- next.config.js
- Disable i18n documentation generation for pull requests (follow-up on #14806).
> 10:48:29 PM: 231 new files to upload
Instead of +1,000 files.
- Fix the demo spacing
> [docs] Speed-up pull requests build

- docs/src/modules/components/AppWrapper.js
- docs/src/pages/guides/server-rendering/server-rendering.md
- examples/create-react-app-next/src/index.js
- examples/create-react-app-with-flow/src/index.js
- examples/create-react-app-with-jss/src/index.js
- examples/create-react-app/src/index.js
- examples/gatsby-next/plugins/gatsby-plugin-material-ui/gatsby-browser.js
- examples/gatsby/src/withRoot.js
- examples/nextjs-next/pages/_app.js
- examples/ssr-next/.babelrc
- examples/ssr-next/.gitignore
- examples/ssr-next/App.js
- examples/ssr-next/README.md
- examples/ssr-next/client.js
- examples/ssr-next/package.json
- examples/ssr-next/server.js
- examples/ssr-next/webpack.config.js
- examples/ssr/README.md
- examples/ssr/client.js
- packages/material-ui-benchmark/src/server.js
> [docs] Add ssr-next example

- docs/src/modules/components/Head.js
> [docs] Add Algolia metadata

- CHANGELOG.md
- docs/src/pages/guides/migration-v3/migration-v3.md
See https://github.com/mui-org/material-ui/pull/14795#pullrequestreview-212223353
> [docs] Add missing breaking changes from #14795

- docs/scripts/formattedTSDemos.js
- docs/src/pages/demos/buttons/ButtonBases.js
- docs/src/pages/demos/buttons/ContainedButtons.js
- docs/src/pages/demos/buttons/OutlinedButtons.js
- docs/src/pages/demos/buttons/TextButtons.js
- docs/src/pages/demos/text-fields/ComposedTextField.js
- docs/src/pages/demos/text-fields/CustomizedInputs.js
- docs/src/pages/demos/text-fields/FilledInputAdornments.js
- docs/src/pages/demos/text-fields/FilledTextFields.js
- docs/src/pages/demos/text-fields/InputAdornments.js
- docs/src/pages/demos/text-fields/InputWithIcon.js
- docs/src/pages/demos/text-fields/Inputs.js
- docs/src/pages/demos/text-fields/OutlinedInputAdornments.js
- docs/src/pages/demos/text-fields/OutlinedTextFields.js
- docs/src/pages/demos/text-fields/TextFieldMargins.js
- docs/src/pages/demos/text-fields/TextFields.js
> [docs] Fix babel generator extra line

- packages/material-ui/package.json
- packages/material-ui/src/styles/withStyles.d.ts
- yarn.lock
- Remove the parameter from `WithStylesOptions` type:
```diff
-const options: WithStylesOptions<ClassKey>
+const options: WithStylesOptions;
```
Closes https://github.com/mui-org/material-ui/issues/14608
> [core] Stop using @types/jss

- packages/babel-plugin-unwrap-createStyles/README.md
- packages/babel-plugin-unwrap-createStyles/package.json
- packages/babel-plugin-unwrap-createStyles/src/unwrapCreateStyles.js
- packages/babel-plugin-unwrap-createStyles/test/__fixtures__/styles/code.js
- packages/babel-plugin-unwrap-createStyles/test/__fixtures__/styles/output.js
> [core] Babel plugin unwrap createStyles now handle material-ui/styles package

- docs/notifications.json
> [docs] Remove survey notification

- packages/material-ui-styles/src/withStyles/withStyles.js
- packages/material-ui-styles/src/withStyles/withStyles.test.js
- packages/material-ui-styles/src/withTheme/withTheme.js
- packages/material-ui-styles/src/withTheme/withTheme.test.js
- packages/material-ui-utils/src/chainPropTypes.test.js
- packages/material-ui/src/ExpansionPanel/ExpansionPanel.js
- packages/material-ui/src/ExpansionPanel/ExpansionPanel.test.js
- packages/material-ui/src/Menu/Menu.test.js
- packages/material-ui/src/Popover/Popover.js
- packages/material-ui/src/Popover/Popover.test.js
- packages/material-ui/src/Popper/Popper.js
- packages/material-ui/src/Popper/Popper.test.js
- packages/material-ui/src/Tooltip/Tooltip.js
- packages/material-ui/src/Tooltip/Tooltip.test.js
- packages/material-ui/test/integration/Menu.test.js
- packages/material-ui/test/integration/NestedMenu.test.js
- packages/material-ui/test/integration/fixtures/menus/NestedMenu.js
- packages/material-ui/test/integration/fixtures/menus/SimpleMenu.js
> [Popover][Popper] Warn when `anchorEl` is invalid

- docs/src/pages/demos/progress/CustomizedProgress.js
- packages/material-ui/src/LinearProgress/LinearProgress.js
- packages/material-ui/src/LinearProgress/LinearProgress.test.js
> [LinearProgress] Improve customization capability

- package.json
- pages/demos/autocomplete.js
- pages/demos/avatars.js
- pages/demos/badges.js
- pages/demos/bottom-navigation.js
- pages/demos/breadcrumbs.js
- pages/demos/cards.js
- pages/demos/chips.js
- pages/demos/dialogs.js
- pages/demos/dividers.js
- pages/demos/drawers.js
- pages/demos/expansion-panels.js
- pages/demos/grid-list.js
- pages/demos/paper.js
- pages/demos/pickers.js
- pages/demos/progress.js
- pages/demos/selection-controls.js
- pages/demos/selects.js
- pages/demos/snackbars.js
- pages/demos/steppers.js
- pages/demos/tables.js
- pages/demos/tabs.js
- pages/demos/tooltips.js
- adds `yarn docs:typescript:check` for easier TS demo workflow 
- enables display of TS for all demos
> [docs] Prepare full TypeScript demos

- packages/material-ui/src/Menu/Menu.js
- packages/material-ui/src/Popover/Popover.js
> [Popover] Fix PaperProps classname concat

- docs/notifications.json
> [docs] Add survey results notification

- pages/blog/2019-developer-survey-results.md
...and take advantage of the PR to add some additional commentary.
> [docs] Fix internal links in the developer survey

- package.json
- yarn.lock
Try to solve https://github.com/mui-org/material-ui/pull/14911#issuecomment-473691146.
> [docs] Fix docs build regression

- docs/src/modules/constants.js
> [docs] Enable German

- docs/src/pages/discover-more/related-projects/related-projects.md
Hi,
I added a new library to related projects. Thanks
> [docs] Add react-basket to related projects

- docs/src/pages/discover-more/languages/languages.md
- packages/material-ui/src/BottomNavigation/BottomNavigation.js
- packages/material-ui/src/BottomNavigationAction/BottomNavigationAction.js
- packages/material-ui/src/BottomNavigationAction/BottomNavigationAction.test.js
- packages/material-ui/src/Breadcrumbs/Breadcrumbs.js
- packages/material-ui/src/Breadcrumbs/Breadcrumbs.test.js
- packages/material-ui/src/Chip/Chip.js
- packages/material-ui/src/Chip/Chip.test.js
- packages/material-ui/src/Collapse/Collapse.js
- packages/material-ui/src/CssBaseline/CssBaseline.js
- packages/material-ui/src/CssBaseline/CssBaseline.test.js
- packages/material-ui/src/Dialog/Dialog.js
- packages/material-ui/src/Dialog/Dialog.test.js
- packages/material-ui/src/Drawer/Drawer.js
- packages/material-ui/src/Drawer/Drawer.test.js
- packages/material-ui/src/ExpansionPanel/ExpansionPanel.js
- packages/material-ui/src/ExpansionPanel/ExpansionPanel.test.js
- packages/material-ui/src/ExpansionPanelSummary/ExpansionPanelSummary.js
- packages/material-ui/src/ExpansionPanelSummary/ExpansionPanelSummary.test.js
- packages/material-ui/src/GridListTile/GridListTile.js
- packages/material-ui/src/GridListTile/GridListTile.test.js
- packages/material-ui/src/MobileStepper/MobileStepper.js
The commits in this PR are primarily focused on refactoring the components, and making sure the components still work in the browser without console errors. I made no effort to get the tests to pass. (Okay, that's a lie, I tried and failed for the first one, so didn't bother after that!)
Since a lot of this was done by rote, I'm anticipating "you're doing it all wrong" type feedback, which is absolutely fine. Equally, if anyone would like to weigh in and push some fixes for the tests, that would be great. Between feedback on the code, and some example tests, it should give us a good basis for converting the rest of the components.
I worked through the components alphabetically, with the exception of ButtonBase, which was too gnarly to tackle in this experimental PR. Thought I'd leave that …
> [core] Refactor a subset of components from classes to functions

- docs/src/pages/demos/buttons/FloatingActionButtonZoom.hooks.js
- docs/src/pages/demos/drawers/MiniDrawer.js
- docs/src/pages/demos/drawers/PersistentDrawerLeft.js
- docs/src/pages/demos/drawers/PersistentDrawerRight.js
- docs/src/pages/demos/drawers/ResponsiveDrawer.js
- docs/src/pages/demos/selects/MultipleSelect.js
- docs/src/pages/demos/steppers/DotsMobileStepper.js
- docs/src/pages/demos/steppers/ProgressMobileStepper.js
- docs/src/pages/demos/steppers/SwipeableTextMobileStepper.js
- docs/src/pages/demos/steppers/TextMobileStepper.js
- docs/src/pages/demos/tables/CustomPaginationActionsTable.js
- docs/src/pages/demos/tabs/FullWidthTabs.js
- packages/material-ui/src/internal/animate.test.js
You can't edit these demos on codesandbox, they fail.
> [docs] Take advantage of the default theme

- docs/src/pages/css-in-js/advanced/Theming.js
- docs/src/pages/css-in-js/advanced/UseTheme.js
- docs/src/pages/css-in-js/advanced/WithTheme.js
- docs/src/pages/css-in-js/advanced/advanced.md
- docs/src/pages/css-in-js/basics/AdaptingHOC.js
- docs/src/pages/css-in-js/basics/AdaptingHook.js
- docs/src/pages/css-in-js/basics/AdaptingStyledComponents.js
- docs/src/pages/css-in-js/basics/basics.md
- pages/_document.js
> [docs] Improve the styles interpolation documentation

- docs/src/pages/getting-started/usage/usage.md
> [docs] Grammar fix

- docs/src/pages/demos/avatars/IconAvatars.tsx
- docs/src/pages/demos/avatars/ImageAvatars.tsx
- docs/src/pages/demos/avatars/LetterAvatars.tsx
Adding typescript demos to avatars for #14897. 
Code style based on #14535
> [docs] Enable avatar ts demos

- docs/src/pages/demos/paper/PaperSheet.tsx
> [docs] Add PaperSheet TypeScript demo

- docs/src/pages/demos/bottom-navigation/LabelBottomNavigation.tsx
- docs/src/pages/demos/bottom-navigation/SimpleBottomNavigation.tsx
> [docs] BottomNavigation TypeScript docs

- docs/src/pages/demos/badges/BadgeMax.tsx
Add BadgeMax typescript demo for https://github.com/mui-org/material-ui/issues/14897
By the way, this is my very first PR to this project :heart: so just let me know if there's something I missed, cheers :metal:
> [docs] Add Badge Typescript demo for Maximum Value

- docs/README.md
> [docs] Add note to docs README regarding translations

- packages/material-ui/src/Box/Box.d.ts
> [Box] Improve TypeScript definitions

- packages/material-ui-lab/src/ToggleButtonGroup/ToggleButtonGroup.js
- packages/material-ui-lab/src/ToggleButtonGroup/ToggleButtonGroup.test.js
> [ToggleButtonGroup] Convert to function component

- packages/material-ui/src/Fade/Fade.js
- packages/material-ui/src/Fade/Fade.test.js
> [Fade] Convert to function component

- docs/src/pages/demos/badges/BadgeMax.js
- docs/src/pages/demos/badges/BadgeMax.tsx
This pull request aims at demonstrating how the demos can be migrated to the hooks API.
> [docs] Migrate one demo to the hooks

- packages/material-ui-benchmark/src/styles.js
- packages/material-ui-styles/src/styled/styled.js
- packages/material-ui-styles/src/styled/styled.test.js
One slice of #14999.
- Add forwardRef
- Remove one component in React tree
> [styles] Use the hook directly in styled()

- packages/material-ui/src/SwipeableDrawer/SwipeArea.js
- packages/material-ui/src/SwipeableDrawer/SwipeableDrawer.js
- packages/material-ui/src/SwipeableDrawer/SwipeableDrawer.test.js
Same as #15038, but for _next_. Fixes #15035.
> [SwipeableDrawer] Ignore open swipe if it didn't start on the swipe area

- packages/material-ui/src/ExpansionPanelSummary/ExpansionPanelSummary.js
- packages/material-ui/src/ExpansionPanelSummary/ExpansionPanelSummary.test.js
Everything must be converted! 😁
> [ExpansionPanelSummary] Convert to function component

- docs/src/pages/demos/chips/ChipsArray.js
- docs/src/pages/demos/chips/ChipsArray.tsx
Add Chips Array Typescript demo for #14897
> [docs] Add Chip TypeScript demo for Chip array

- docs/src/pages/demos/tabs/CustomizedTabs.js
Closes https://github.com/mui-org/material-ui/issues/15060
@oliviertassinari I couldn't find any other problematic examples that are related to this issue.
> [docs] Fix CustomizedTabs demo 

- packages/material-ui/src/Button/Button.d.ts
- packages/material-ui/src/Fab/Fab.d.ts
> [Button] Narrow type for `type` prop

- docs/src/pages/css-in-js/api/api.md
- packages/material-ui-styles/src/styled/styled.d.ts
- packages/material-ui-styles/test/index.spec.tsx
> [styled] Correct doc and typings for styled with theme

- packages/material-ui/src/Popover/Popover.js
- packages/material-ui/src/Popover/Popover.test.js
- packages/material-ui/src/Popper/Popper.js
- packages/material-ui/src/Popper/Popper.test.js
- packages/material-ui/src/internal/animate.test.js
> [Popover] Add warning to Popover if anchorRef is not visible

- docs/src/pages/demos/avatars/IconAvatars.js
- docs/src/pages/demos/avatars/IconAvatars.tsx
- docs/src/pages/demos/avatars/ImageAvatars.js
- docs/src/pages/demos/avatars/ImageAvatars.tsx
- docs/src/pages/demos/avatars/LetterAvatars.js
- docs/src/pages/demos/avatars/LetterAvatars.tsx
This PR is related to  #15032.
> [docs] Migrate Avatar demo page to the hooks

- docs/src/pages/utils/portal/SimplePortal.js
- docs/src/pages/utils/portal/SimplePortal.tsx
- pages/utils/portal.js
- [ x ] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui-org/material-ui/blob/next/CONTRIBUTING.md#submitting-a-pull-request).
> [docs] SimplePortal example using Hooks

- docs/src/pages/demos/app-bar/BottomAppBar.js
- docs/src/pages/demos/app-bar/BottomAppBar.tsx
- docs/src/pages/demos/app-bar/ButtonAppBar.js
- docs/src/pages/demos/app-bar/ButtonAppBar.tsx
- docs/src/pages/demos/app-bar/DenseAppBar.js
- docs/src/pages/demos/app-bar/DenseAppBar.tsx
- docs/src/pages/demos/app-bar/SearchAppBar.js
- docs/src/pages/demos/app-bar/SearchAppBar.tsx
Description
This PR migrates the doc's app bar page to hooks. Relates to #15032.
> [docs] Migrate docs' App Bar page to hooks

- docs/src/pages/demos/selection-controls/CustomizedSwitches.js
- packages/material-ui/src/FormControlLabel/FormControlLabel.d.ts
Though the changes are minimal, do let me know if anything is required to keep it in sync with your coding philosophies.
Thank you!
> [Switch] Add demo for labels on both sides

- packages/material-ui/src/Zoom/Zoom.js
- packages/material-ui/src/Zoom/Zoom.test.js
> [Zoom] Convert to function component

- packages/material-ui-styles/src/ServerStyleSheets/ServerStyleSheets.d.ts
> [styles] fix types of ServerStyleSheets.collect

- docs/src/modules/components/Ad.js
- docs/src/modules/components/AdCarbon.js
- docs/src/modules/components/AdCodeFund.js
- docs/src/modules/components/MarkdownDocs.js
- docs/src/pages/demos/pickers/pickers.md
- docs/src/pages/demos/tabs/CustomizedTabs.js
- docs/src/pages/demos/tabs/CustomizedTabs.tsx
- docs/src/pages/guides/interoperability/interoperability.md
- docs/src/pages/premium-themes/paperbase/Paperbase.js
- packages/material-ui/src/Container/Container.js
- packages/material-ui/src/Container/Container.test.js
I have updated all the links of the section of the documentation. The demos are leveraging the `injectFirst` flag. It's much simpler!
@eps1lon lucky boy, I have also batched small changes into this pull requets 🎁, with different commits 🎉.
>  [docs] Update Style Library Interoperability + Container forwardRef

- packages/material-ui/src/Grow/Grow.js
- packages/material-ui/src/Grow/Grow.test.js
> [Grow] Convert to function component

- docs/src/pages/demos/cards/ImgMediaCard.js
- docs/src/pages/demos/cards/cards.md
- packages/material-ui/src/CardMedia/CardMedia.js
> [CardMedia] Move object-fit to the core

- docs/src/pages/customization/overrides/overrides.md
- docs/src/pages/guides/api/api.md
- docs/src/pages/layout/hidden/hidden.md
Done from github ui but there are more
https://next--material-ui.netlify.com/getting-started/faq/#how-can-i-access-the-dom-element- was not working
> [docs] Fix anchor link

- packages/material-ui/src/Select/SelectInput.js
according to discussion in https://github.com/mui-org/material-ui/issues/15085
i've made changes. All tests success.
Closes #15085
> [Select] Trigger the open callbacks even when uncontrolled 

- packages/material-ui/src/TablePagination/TablePaginationActions.js
> [TablePaginationActions] Convert to function component

- docs/src/pages/demos/selects/CustomizedSelects.js
This PR converts the customized select class component to using hooks instead.
> [docs] Convert customized select component to use hooks

- docs/src/modules/utils/generateMarkdown.js
- docs/src/pages/utils/no-ssr/FrameDeferring.js
- docs/src/pages/utils/no-ssr/no-ssr.md
- packages/material-ui/src/NoSsr/NoSsr.js
- packages/material-ui/src/NoSsr/NoSsr.test.js
- pages/api/no-ssr.md
> [NoSsr] Convert to function component

- packages/material-ui-styles/src/ThemeProvider/ThemeProvider.js
- packages/material-ui-styles/src/ThemeProvider/ThemeProvider.test.js
Changes discussed with @oliviertassinari and @eps1lon in #15186 
Closes #15186
> [styles] Memoize theme to prevent re-rendering

- BACKERS.md
- README.md
- docs/src/modules/components/AppTableOfContents.js
- docs/src/modules/components/Demo.js
- docs/src/modules/components/HomeQuickWord.js
- docs/src/modules/components/MarkdownElement.js
- docs/src/modules/components/backers.md
- docs/src/pages/getting-started/learn/learn.md
- package.json
- pages/_document.js
- yarn.lock
---
It also batches a couple of small issues. I have used the following tools:
- [Lighthouse](https://developers.google.com/web/tools/lighthouse/)
- [Screaming Frog SEO Spider](https://www.screamingfrog.co.uk/)
- [W3C Validator](https://validator.w3.org/)
> [docs] Link 'React Material-UI Cookbook'

- packages/material-ui/src/internal/SwitchBase.js
- packages/material-ui/src/internal/SwitchBase.test.js
> [SwitchBase] Convert to function component

- babel.config.js
- docs/src/modules/redux/initRedux.js
Solve a pain point when looking at #15183.
> [docs] Fix the docs in dev mode for IE 11

- docs/src/pages/discover-more/showcase/Showcase.js
Fixes https://github.com/mui-org/material-ui/issues/15244
I tested the fix provided by @oliviertassinari along with @joshwooding (see the issue).
The layout is now stable when changing the "Sort by" option.
> [docs] Fix layout glitch when changing sort-by in showcases

- packages/material-ui/src/Tabs/ScrollbarSize.js
- packages/material-ui/src/Tabs/ScrollbarSize.test.js
> [ScrollbarSize] Convert to function component

- docs/src/pages/style/color/color.md
> [docs] Slight grammar changes to color.md

- docs/src/pages/demos/drawers/MiniDrawer.tsx
- docs/src/pages/demos/drawers/PermanentDrawerLeft.tsx
- docs/src/pages/demos/drawers/PermanentDrawerRight.tsx
- docs/src/pages/demos/drawers/PersistentDrawerLeft.tsx
- docs/src/pages/demos/drawers/PersistentDrawerRight.tsx
- docs/src/pages/demos/drawers/ResponsiveDrawer.tsx
- docs/src/pages/demos/drawers/SwipeableTemporaryDrawer.tsx
- docs/src/pages/demos/drawers/TemporaryDrawer.tsx
Add TypeScript demos for each of the existing Drawer demos for #14897
This is my first PR here 😄, let me know if there's anything I missed 🤙 .
> [docs] Add most Drawer TypeScript demos

- packages/material-ui/src/ButtonBase/ButtonBase.test.js
- packages/material-ui/src/Chip/Chip.js
- packages/material-ui/src/MenuList/MenuList.js
- packages/material-ui/src/RadioGroup/RadioGroup.js
Batches some minor changes related to refs:
- use common fork ref implementation
- remove redundant test
> [core] Ref cleanup

- docs/src/pages/css-in-js/basics/basics.md
Solves this issue https://github.com/mui-org/material-ui/issues/14416#issuecomment-469902431
> [docs] Make using the Migration bootstrap clearer

- packages/material-ui/src/Fade/Fade.test.js
- packages/material-ui/src/Grow/Grow.test.js
- packages/material-ui/src/Zoom/Zoom.test.js
Updates tests for Fade, Grow and Zoom.
> [Transition] Update transition tests

- packages/material-ui/src/Tab/Tab.d.ts
> [Tab] Remove outdated classes from the definitions

- docs/src/pages/versions/StableVersions.js
> [docs] Update version filter

- docs/src/pages/css-in-js/api/api.md
- packages/material-ui-styles/src/ServerStyleSheets/ServerStyleSheets.js
> [docs] Improve ServerStyleSheets documentation

- examples/create-react-app-with-reason-react/README.md
- examples/reason/README.md
It adds a new example that integrates reason-react, material-ui and create-react app
> [example] Add Reason example

- docs/src/pages/getting-started/faq/faq.md
Improve the disable animation and transition FAQ answer. 
Closes #15164
> [docs] update FAQ doc

- docs/src/pages/system/basics/CssProp.tsx
- docs/src/pages/system/basics/Demo.tsx
- docs/src/pages/system/basics/Emotion.tsx
- docs/src/pages/system/basics/JSS.tsx
- docs/src/pages/system/basics/RealWorld.tsx
- docs/src/pages/system/basics/StyledComponents.tsx
- docs/src/pages/system/basics/Variant.tsx
- packages/material-ui-system/src/index.d.ts
- packages/material-ui-system/src/index.spec.tsx
- tsconfig.json
Closes #14605.
I never used `styled-components` with style functions. Typing expierence is not very smooth since the style functions are so overloaded.
> [system] Add types

- packages/material-ui/src/Container/Container.d.ts
> [Container] Add component prop for TypeScript 

- docs/src/pages/demos/tables/MaterialTableDemo.js
- docs/src/pages/demos/tables/ReactVirtualizedTable.js
- docs/src/pages/demos/tables/tables.md
- next.config.js
- package.json
- yarn.lock
I was discussing with @mbrn of material-table and @gregnb of mui-datatables. We agreed on the following order 🥇🥈🥉.
Thank you guys for these great projects 😍!
> [docs] Promote material-table

- CHANGELOG.md
- docs/src/pages/guides/migration-v3/migration-v3.md
> [docs] Document Tooltip breaking changes

- docs/src/pages/demos/tables/MaterialTableDemo.js
I changed demo component as class based component. So i can manage state with table's edit functions.
> [docs] material-table demo: persist the changes

- docs/src/pages/demos/lists/InteractiveList.tsx
> [docs] Add Interactive List TypeScript demos

- packages/material-ui/src/Drawer/Drawer.test.js
- packages/material-ui/src/FormControl/FormControl.js
- packages/material-ui/src/Slide/Slide.js
- packages/material-ui/src/Zoom/Zoom.js
- pages/api/form-control.md
> [core] Fix the CI fail

- packages/material-ui/src/Popper/Popper.js
- packages/material-ui/src/Popper/Popper.test.js
> [Popper] Convert to function component

- packages/material-ui/src/InputBase/Textarea.js
- packages/material-ui/src/InputBase/Textarea.test.js
I'm reintroducing the double textareas.
Closes #15435
> [Textarea] Fix cursor jump

- docs/src/pages/utils/modal/SimpleModal.js
Closes #15346
https://deploy-preview-15462--material-ui.netlify.com/utils/modal/
> [docs] Fix modal demo jumping on cursor move

- docs/src/pages/demos/menus/menus.md
> [docs] Small grammar fix for Menu

- docs/src/pages/demos/paper/PaperSheet.js
- docs/src/pages/demos/paper/PaperSheet.tsx
> [docs] Migrate Paper demos to hooks

- docs/src/pages/demos/tables/DenseTable.js
- docs/src/pages/demos/tables/DenseTable.tsx
- docs/src/pages/demos/tables/SimpleTable.js
- docs/src/pages/demos/tables/SimpleTable.tsx
- docs/src/pages/demos/tables/SpanningTable.js
- docs/src/pages/demos/tables/SpanningTable.tsx
> [docs] Migrate Table demos to hooks

- docs/src/pages/demos/lists/AlignItemsList.js
- docs/src/pages/demos/lists/AlignItemsList.tsx
- docs/src/pages/demos/lists/FolderList.js
- docs/src/pages/demos/lists/FolderList.tsx
- docs/src/pages/demos/lists/InsetList.js
- docs/src/pages/demos/lists/InsetList.tsx
- docs/src/pages/demos/lists/PinnedSubheaderList.js
- docs/src/pages/demos/lists/PinnedSubheaderList.tsx
- docs/src/pages/demos/lists/SimpleList.js
- docs/src/pages/demos/lists/SimpleList.tsx
> [docs] Migrate List demos to hooks

- .size-limit.js
- BACKERS.md
- docs/src/modules/components/AppContent.js
- docs/src/modules/components/AppDrawer.js
- docs/src/modules/components/AppFrame.js
- docs/src/modules/components/AppTableOfContents.js
- docs/src/modules/components/HomeBackers.js
- docs/src/modules/components/Tidelift.js
- pages/index.js
> [docs] Link v4 in the documentation of v3

- packages/material-ui/src/Fade/Fade.d.ts
- packages/material-ui/src/Grow/Grow.d.ts
- packages/material-ui/src/Slide/Slide.d.ts
- packages/material-ui/src/Zoom/Zoom.d.ts
> [core] Add ref prop to transition components

- docs/src/pages/demos/dialogs/DraggableDialog.js
- docs/src/pages/demos/dialogs/DraggableDialog.tsx
- Added missing props for Draggable Dialog Component
- Refactoring Draggable Dialog Component to hooks: `docs/src/pages/demos/dialogs/DraggableDialog.tsx`
Closes #15544
> [docs] Fix Draggable Dialog interactions with the content

- docs/src/pages/demos/badges/badges.md
- docs/src/pages/demos/breadcrumbs/breadcrumbs.md
- docs/src/pages/demos/buttons/buttons.md
- docs/src/pages/demos/dialogs/dialogs.md
- docs/src/pages/demos/expansion-panels/expansion-panels.md
- docs/src/pages/demos/menus/menus.md
- docs/src/pages/demos/progress/progress.md
- docs/src/pages/demos/selects/selects.md
- docs/src/pages/demos/snackbars/snackbars.md
- docs/src/pages/demos/steppers/steppers.md
- docs/src/pages/demos/switches/CustomizedSwitches.js
- docs/src/pages/demos/switches/CustomizedSwitches.tsx
- docs/src/pages/demos/switches/switches.md
- docs/src/pages/demos/tables/tables.md
- docs/src/pages/demos/tabs/tabs.md
- docs/src/pages/demos/text-fields/text-fields.md
- docs/src/pages/demos/tooltips/tooltips.md
- docs/src/pages/lab/slider/CustomizedSlider.js
- docs/src/pages/lab/slider/CustomizedSlider.tsx
- docs/src/pages/lab/slider/slider.md
> [docs] Simplify wording for customization demo descriptions

- packages/material-ui/src/Menu/Menu.d.ts
> [Menu] Add 'variant' prop TypeScript declaration

- packages/material-ui/src/Badge/Badge.d.ts
- packages/material-ui/src/Badge/Badge.js
- packages/material-ui/src/Badge/Badge.test.js
> [core] Handle undefined badgeContent rendering empty bubble

- docs/src/pages/style/typography/TypographyTheme.js
> [docs] Fix typography demo in dark mode

- docs/src/pages/premium-themes/premium-themes.md
> [docs] Fix plural spelling

- docs/src/pages/css-in-js/basics/basics.md
> [docs] Fix the adapting makeStyles based on props example syntax

- docs/src/pages/system/basics/CssProp.tsx
- packages/material-ui-system/src/index.d.ts
- packages/material-ui-system/src/index.spec.tsx
Closes #15564 (based on)
I added some more tests to make it more obvious what is happening. Might be an issue that can be fixed by switching to typescript 3.4.
/cc @merceyz
> [system] Fix css function rejecting certain prop types

- docs/src/modules/components/AppDrawer.js
- docs/src/modules/components/Link.js
Cherry-pick from #15636 including a fix for a strict mode warning. Shows how much we need the findDOMNode fallback.
> [docs] Fix some dev-only warnings

- docs/src/pages/components/dialogs/dialogs.md
- docs/src/pages/components/icons/icons.md
- docs/src/pages/components/progress/progress.md
- docs/src/pages/components/selects/selects.md
- docs/src/pages/components/snackbars/snackbars.md
> [docs] Fix few grammar issues

- docs/src/pages/guides/migration-v3/migration-v3.md
- packages/material-ui/src/styles/MuiThemeProvider.d.ts
- packages/material-ui/src/styles/index.d.ts
Solve https://github.com/mui-org/material-ui/issues/15536#issuecomment-490514902
> [styles] Keep MuiThemeProvider for backward compatibility

- docs/src/modules/components/EditPage.js
- docs/src/modules/components/MarkdownDocs.js
> [docs] Link edit page button to github editor

- README.md
> [docs] Fix dead David DM badges in README

- docs/src/modules/components/Ad.js
- docs/src/modules/components/AdCarbon.js
- docs/src/modules/components/AdCodeFund.js
- docs/src/modules/components/AppContent.js
- docs/src/modules/components/AppTheme.js
- docs/src/modules/components/Demo.js
- docs/src/modules/components/HomeFooter.js
- docs/src/modules/components/HomeSteps.js
- docs/src/modules/components/MarkdownDocs.js
- docs/src/modules/components/MarkdownElement.js
- docs/src/modules/styles/getTheme.js
- docs/src/pages/discover-more/team/Team.js
- docs/src/pages/getting-started/page-layout-examples/blog/Markdown.js
- docs/src/pages/getting-started/page-layout-examples/checkout/AddressForm.js
- docs/src/pages/getting-started/page-layout-examples/sign-in/SignIn.js
- docs/src/pages/getting-started/page-layout-examples/sticky-footer/StickyFooter.js
> [docs] Add next page link

- CHANGELOG.md
- docs/src/pages/guides/migration-v3/migration-v3-de.md
- docs/src/pages/guides/migration-v3/migration-v3-es.md
- docs/src/pages/guides/migration-v3/migration-v3-fr.md
- docs/src/pages/guides/migration-v3/migration-v3-ja.md
- docs/src/pages/guides/migration-v3/migration-v3-pt.md
- docs/src/pages/guides/migration-v3/migration-v3-ru.md
- docs/src/pages/guides/migration-v3/migration-v3-zh.md
- docs/src/pages/guides/migration-v3/migration-v3.md
> [docs] Fix a typo

- docs/src/pages/customization/palette/palette.md
> [docs] Fix "enebles" typo on Palette page

- docs/src/pages/components/app-bar/app-bar.md
> Fix typo and formatting in app-bar docs

- packages/material-ui/src/ClickAwayListener/ClickAwayListener.js
- packages/material-ui/src/ClickAwayListener/ClickAwayListener.test.js
- packages/material-ui/src/Snackbar/Snackbar.test.js
- pages/api/click-away-listener.md
> [ClickAwayListener] Fix scrollbar interaction

- packages/material-ui-lab/src/SpeedDial/SpeedDial.js
- packages/material-ui-lab/src/SpeedDial/SpeedDial.test.js
- pages/api/speed-dial.md
> [SpeedDial] Convert to function component

- docs/src/modules/components/AdCodeFund.js
- docs/src/modules/components/MarkdownElement.js
- docs/src/pages/getting-started/page-layout-examples/blog/Blog.js
- packages/material-ui/src/CssBaseline/CssBaseline.js
This is a common problem I see repeatedly in people projects.
**Before**
**After**
> [CssBaseline] Fix wrong default font weight

- CHANGELOG.md
Follow up on https://github.com/mui-org/material-ui/pull/15743#issuecomment-493732257 which seemed to have been forgotten.
> [docs] Add ClickAwayListener breaking change

- docs/src/pages/guides/testing/testing.md
> [docs] Fix some gramma in testing doc

- docs/src/pages/guides/right-to-left/right-to-left.md
> [docs] Fix some gramma in right to left doc

- docs/src/pages/components/icons/icons.md
> [docs] Reference the article with it's full name in icon doc

- examples/gatsby/package.json
> [example]  Update gatsby-plugin-material-ui dependency

- README.md
> [docs] Fixes typo in README

- docs/notifications.json
- docs/src/modules/components/Ad.js
- pages/blog/material-ui-v4-is-out.md
- Link the blog post
- Fix ![](https://trello-attachments.s3.amazonaws.com/56351dda29d36cd846840aee/5ce1991f1ad5d77562bff3c2/9dba2181a1c8aad78baee5c873d4b65f/Capture_d%E2%80%99e%CC%81cran_2019-05-19_a%CC%80_13.56.45.png)
- Focus on Chinese translations.
> [docs] Hide the Ad fallback to Google

- docs/src/pages/getting-started/installation/installation.md
> [docs] Update Installation.md for v4.0.0

- packages/material-ui/src/ListItemText/ListItemText.d.ts
> [ListItemText] Update classes type definitions

- docs/src/pages/styles/advanced/advanced.md
> [docs] Fix typo in styles advanced guide 

- docs/src/pages/components/dialogs/dialogs.md
- [+] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui-org/material-ui/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
Fixes #13344
> [docs] Add Transitions header in the dialogs page

- SECURITY.md
> [docs] Add SECURITY.md

- pages/blog/material-ui-v4-is-out.md
> [docs] Update the v4 blog post

- docs/src/modules/utils/getDemoConfig.js
- docs/src/modules/utils/helpers.js
- docs/src/modules/utils/helpers.test.js
- examples/create-react-app-with-typescript/package.json
* Include preflight check in cra-ts
* Use default tsconfig in codesandbox demos
* Include latest typescript version in codesandbox
* Switch from next to latest mui versions in codesandbox
> [docs] Minor improvements to codesandbox demos and examples

- docs/src/pages/guides/composition/composition.md
> [docs] Fix Link import

- docs/src/pages/customization/typography/typography.md
> [docs] Global at rule is called font-face

- docs/src/pages/styles/api/api.md
> [docs] Fix Boolan -> Boolean

- packages/material-ui/src/TablePagination/TablePagination.d.ts
- packages/material-ui/src/TablePagination/TablePagination.spec.tsx
> [TablePagination] Fix classes type

- docs/src/pages/guides/migration-v3/migration-v3.md
Remove `alpha` which indicates that this doc was written before the final v4 was released.
> [docs] v4 Migration doc slight clean up

- packages/material-ui/src/Popover/Popover.js
- packages/material-ui/src/Popover/Popover.test.js
- pages/api/popover.md
> [Popover] Convert to function component

- docs/src/pages/guides/migration-v3/migration-v3.md
- packages/material-ui/src/styles/createSpacing.js
- packages/material-ui/src/styles/createSpacing.test.js
> [theme] Return default value for spacing when no args provided

- packages/material-ui/src/BottomNavigationAction/BottomNavigationAction.d.ts
- packages/material-ui/src/CardActionArea/CardActionArea.d.ts
- packages/material-ui/src/ExpansionPanelSummary/ExpansionPanelSummary.d.ts
- packages/material-ui/src/StepButton/StepButton.d.ts
- packages/material-ui/src/TableSortLabel/TableSortLabel.d.ts
- packages/material-ui/src/Tabs/TabScrollButton.d.ts
> [core] Migrate extend ButtonBaseProps typings

- packages/material-ui/src/Radio/RadioButtonIcon.js
Closes mui-org/material-ui#15945
> [Radio] Fix dot misalignment in IE11

- docs/src/pages/getting-started/page-layout-examples/sign-up/SignUp.js
> [docs] SignIn -> SignUp typo

- packages/material-ui/src/index.d.ts
- packages/material-ui/src/index.js
This issue closes https://github.com/mui-org/material-ui/issues/15870
> [core] Export useMediaQuery & useScrollTrigger in index.js

- docs/src/pages/getting-started/page-layout-examples/pricing/Pricing.js
> [docs] Fix a typo within pricing page layout example

- docs/src/pages/premium-themes/onepirate/modules/theme.js
> [example] Fix theme palette value

- docs/src/pages/styles/advanced/advanced.md
- docs/src/pages/styles/basics/basics.md
> [docs] Fix broken JSS links

- packages/material-ui-system/src/index.d.ts
> [system] Fix typing for flexDirection prop

- .github/FUNDING.yml
> [docs] Update FUNDING.yml with Tidelift string

- docs/src/pages/components/hidden/BreakpointDown.tsx
- docs/src/pages/components/hidden/BreakpointOnly.tsx
- docs/src/pages/components/hidden/BreakpointUp.tsx
- docs/src/pages/components/hidden/GridIntegration.tsx
* Added typescript version and migrated hidden demos to hooks
Closes #15954
> [docs] Migrate Hidden demos to hooks

- examples/create-react-app/src/App.js
- examples/parcel/src/App.js
- examples/preact/src/App.js
- examples/ssr/package.json
- examples/ssr/server.js
Not working on my windows machine so I updated it with cross-env and updated the package json to work for windows.
> [example] Fix ssr example to work on Windows

- docs/src/pages/guides/migration-v3/migration-v3.md
> [docs] Fix syntax error in v3 migration guide

- packages/material-ui/src/LinearProgress/LinearProgress.js
> [LinearProgress] Fix direction issue in RTL

- docs/src/pages/guides/minimizing-bundle-size/minimizing-bundle-size.md
> [docs] Fix bundle doc typos

- CODE_OF_CONDUCT.md
- GOVERNANCE.md
- README.md
- docs/src/pages/styles/api/api.md
- examples/preact/config/jest/cssTransform.js
- examples/preact/config/jest/fileTransform.js
- modules/waterfall/Batcher.js
- packages/material-ui-icons/fixtures/game-icons/README.md
- packages/material-ui/src/styles/createTypography.js
- pages/index.js
- test/README.md
It is better to use https rather that http. So I hope these change converts all the http to https.
> [docs] change http to https

- packages/material-ui/src/Snackbar/Snackbar.js
> [Snackbar] Fix wrong event call

- docs/src/pages/guides/migration-v3/migration-v3.md
> [docs] Remove duplicate link to migration helper

- docs/src/modules/components/Demo.js
- docs/src/modules/components/DemoSandboxed.js
- docs/src/pages/customization/components/GlobalCssOverride.js
- docs/src/pages/customization/components/GlobalCssOverride.tsx
- docs/src/pages/customization/components/GlobalThemeOverride.js
- docs/src/pages/customization/components/GlobalThemeOverride.tsx
- docs/src/pages/customization/components/ThemeVariables.js
- docs/src/pages/customization/components/ThemeVariables.tsx
- docs/src/pages/customization/components/components.md
- docs/src/pages/customization/typography/TypographyTheme.js
- docs/src/pages/customization/typography/TypographyTheme.tsx
> [docs] Add global override demos

- docs/src/pages/components/chips/ChipsArray.js
- docs/src/pages/components/chips/ChipsArray.tsx
First PR here :)
Fixing a small mistake in the examples where state was being mutated so the `ChipsArray`component wasn't updating on chip removal.
Closes #16079
> [docs] Fix chip array removal

- docs/src/pages/customization/themes/themes.md
> [docs] Minor typo correction in breakpoints' docs

- docs/src/modules/components/Demo.js
- docs/src/modules/components/DemoSandboxed.js
Fixes propTypes warning and perf regression from #16067 by converting `Demo` to a function component (for `useMemo` which has much cleaner API than some memoize-one)
> [docs] Fix some warnings/regressions 

- packages/material-ui/src/Tab/Tab.js
- pages/api/tab.md
`textColor` was missing in Props
> [Tab] Improve the textColor description

- docs/src/pages/css-in-js/basics/AdaptingHook.tsx
- docs/src/pages/styles/basics/AdaptingHook.js
- docs/src/pages/styles/basics/AdaptingHook.tsx
* Added typescript version of `styles/basics/AdaptingHook`
Follow-up to #15546
> [docs] Add typescript version of AdaptingHook

- packages/material-ui/src/SwipeableDrawer/SwipeableDrawer.js
- packages/material-ui/src/SwipeableDrawer/SwipeableDrawer.test.js
> [SwipeableDrawer] Convert to function component

- packages/material-ui-system/src/display.js
- packages/material-ui-system/src/index.d.ts
> [system] Add overflow, textOverflow, whiteSpace properties

- docs/src/pages/components/buttons/ButtonRouter.tsx
- docs/src/pages/components/links/LinkRouter.tsx
Omit is defined in `@material-ui/types` So imported from that package.
> [docs] import Omit Type from @material-ui/types

- docs/src/pages/components/typography/typography.md
In #16036 support for font weight 700 was added. So corrected the docs accordingly.
> [docs] Add 700 font weight support

- .editorconfig
- .github/support.yml
- SUPPORT.md
- docs/src/pages/components/icons/icons.md
- docs/src/pages/guides/server-rendering/server-rendering.md
- packages/material-ui-icons/builder.md
- packages/material-ui/src/ButtonBase/ButtonBase.test.js
> [docs] Change http to https part 2

- docs/src/pages/guides/interoperability/interoperability.md
should we either set it to WIP or delete it? so that readers won't get confused.
> [docs] Remove `CSS to MUI webpack Loader`

- docs/src/pages/guides/migration-v3/migration-v3.md
I made the title casing consistent with other pages in the "guides" section.
> [docs] Fix small typos in v3->v4 migration guide

- packages/material-ui/src/Grid/Grid.js
This isn't a valid link anymore. So removed it.
> [core] Remove bootstrap v4-alpha

- azure-pipelines.yml
Quick follow-up on #16182 
Matches https://github.com/mui-org/material-ui/blob/151d2f965cf0787a9daf21eb40cf41d734fe7e43/.circleci/config.yml#L200-L203
> [ci] Run azure on master

- docs/src/pages/system/display/Block.js
- docs/src/pages/system/display/Hiding.js
- docs/src/pages/system/display/Inline.js
- docs/src/pages/system/display/Overflow.js
- docs/src/pages/system/display/Print.js
- docs/src/pages/system/display/TextOverflow.js
- docs/src/pages/system/display/WhiteSpace.js
- docs/src/pages/system/display/display.md
In #16129 overflow, textOverflow, whiteSpace was added in system But was not in the docs. So added them in the docs also
> [docs] Add docs for Overflow, TextOverflow, WhiteSpace

- packages/material-ui/src/Select/SelectInput.js
Closes: #16185
This is my first PR. Please tell me if there is something wrong.
> [Select] Fix autowidth not working with open controlled 

- package.json
- yarn.lock
> [docs] Fix IE 11 rendering issue on the pickers page

- docs/src/pages/system/display/Visibility.js
- docs/src/pages/system/display/display.md
- packages/material-ui-system/src/display.js
- packages/material-ui-system/src/index.d.ts
Added visibility property to display. It is very handy in many situations.
> [system] Add visibility property to display

- docs/src/modules/components/AppWrapper.js
Fixes a performance regression introduced in #16197
~In development render duration for the most expensive commit went from 360ms to 30ms. Will see how this affected production speed (thanks to #15282).~
The low value is observed by switching back to a variant that was already loaded.
The remaining issue is either caused by the fact that the TS variant is currently a separate piece of code or that we should lazily render the highlighted ocde. Ideally the rendered demo wouldn't update/mount at all when switching the code variant.
> [docs] Improve code variant switch perf

- packages/material-ui/src/ButtonBase/ButtonBase.js
- packages/material-ui/src/ButtonBase/ButtonBase.test.js
> [ButtonBase] Fix dragging issue

- packages/material-ui/src/Snackbar/Snackbar.d.ts
> [Snackbar] Fix type definition of autoHideDuration prop

- azure-pipelines.yml
TODO:
- ~[ ] Explore if docs:build is faster if using prebuilt packages~ cant get it to work. Hopefully this gets resolved with webpacks config.resolve.alias
> [ci] Build packages in parallel for size snapshot

- examples/nextjs-with-typescript/pages/_document.tsx
- examples/nextjs/pages/_document.js
> [examples] Fix the styled-jsx integration of the Next.js examples

- docs/src/pages/styles/advanced/advanced.md
- [x ] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui-org/material-ui/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
> [docs] Fix code example

- docs/src/pages/getting-started/example-projects/example-projects.md
Updated example project page to indicate that Material Sense is only on v3
> [docs] Material Sense is only using v3

- dangerfile.js
> [ci] Fix a typo emooji -> emoji

- docs/src/pages/components/modal/modal.md
- packages/material-ui/src/Modal/Modal.js
The bundle size of the Modal is going from 6,689 B to 5,100 B 😍🔥 (-23.47%)
Demo: https://deploy-preview-16254--material-ui.netlify.com/components/modal/.
Related to #15231
> [Modal] Migrate to hooks

- examples/nextjs-with-typescript/README.md
- examples/nextjs/README.md
> [example] Hooks are standards now, no need to mention it

- packages/material-ui/src/Select/SelectInput.js
- packages/material-ui/src/Select/SelectInput.test.js
Closes #16270
- [ x ] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui-org/material-ui/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
> [Select] Fix forward ref logic

- packages/material-ui/src/index.js
> [core] Add missing exports from styles in core

- docs/src/pages/getting-started/faq/faq.md
> [docs] Fix link to Button API in FAQ

- docs/src/pages/guides/composition/composition.md
- docs/src/pages/guides/typescript/typescript.md
> [docs] Fix typo in TypeScript doc

- docs/src/pages/guides/testing/testing.md
- prioritize mount over shallow
- add custom theme example to mount
Closes #11864
> [docs] Update testing guide

- packages/material-ui/src/TableCell/TableCell.js
- pages/api/table-cell.md
> [docs] [TableCell] Fix padding and size property descriptions

- docs/src/pages/guides/interoperability/interoperability.md
> [docs] Fix typo in interoperability guide

- docs/src/pages/customization/components/components.md
> [docs] Fix typo in customizing components

- docs/src/modules/components/Demo.js
- docs/src/pages/components/pickers/pickers.md
- docs/translations/translations.json
- reduce jargon used (Pickers -> Date/Time inputs; Open drawer -> Open main navigation)
- add spacing between demo code and content (there was no visual separation in dark mode)
> [docs] Minor improvements

- packages/material-ui-lab/src/Slider/Slider.js
- packages/material-ui/src/ButtonBase/ButtonBase.js
- packages/material-ui/src/ClickAwayListener/ClickAwayListener.js
- packages/material-ui/src/Modal/Modal.js
- packages/material-ui/src/utils/index.js
- packages/material-ui/src/utils/useEventCallback.js
> [ClickAwayListener] Don't miss any click away events

- packages/material-ui/src/Tabs/Tabs.js
- packages/material-ui/src/utils/ownerWindow.js
See https://github.com/mui-org/material-ui/pull/16427#discussion_r300698248 for reference.
>  [Tabs] Use the correct window reference

- packages/material-ui/src/Slide/Slide.js
- packages/material-ui/src/Slide/Slide.test.js
Close [16499](https://github.com/mui-org/material-ui/issues/16499)
> [Slide] Remove gutter

- docs/src/pages/components/drawers/drawers.md
Ref: https://github.com/mui-org/material-ui/pull/16516#discussion_r301649159
> [docs] Add sidebar alias to Drawer demo description

- examples/nextjs-with-typescript/global.d.ts
- examples/nextjs-with-typescript/next-env.d.ts
- examples/nextjs-with-typescript/next.config.js
- examples/nextjs-with-typescript/package.json
- examples/nextjs-with-typescript/pages/_app.tsx
- examples/nextjs-with-typescript/pages/_document.tsx
- examples/nextjs-with-typescript/src/Link.tsx
- examples/nextjs-with-typescript/src/ProTip.tsx
- examples/nextjs-with-typescript/tsconfig.json
- examples/nextjs/pages/_document.js
a redo of https://github.com/mui-org/material-ui/pull/15587
The PR had drifted too much since I opened that PR.
Closes #16517
> [examples] Update to support Next.js v9

- docs/src/pages/guides/migration-v3/migration-v3.md
Hi 👋 
This is my very first pull request ever to an open source project!
I have followed the contributing guide but if I have made any mistakes please let me know.
Sorry for the super small change, hopefully I can make more meaningful contributions soon :)
To everyone that contributes here, congrats on the outstanding work! This project rocks!
> [docs] Fix typo: change lakes to lacks

- packages/material-ui-codemod/README.md
> [docs] Fix dead link

- docs/src/pages/components/lists/AlignItemsList.js
- docs/src/pages/components/lists/AlignItemsList.tsx
- docs/src/pages/components/lists/lists.md
- [ ✔ ] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui-org/material-ui/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- Changed the "Align list items" title from _Sentence case_ to _Title Case_ to match other titles
- Changed duplicate Avatar alt, two were marked as "Remy Sharp"
> [docs] Remove duplicate alts

- docs/src/pages/components/autocomplete/IntegrationReactSelect.js
- docs/src/pages/components/autocomplete/IntegrationReactSelect.tsx
Look for documentation @ https://react-select.com/components
> [Autocomplete] Use placeholder prop

- packages/material-ui/src/Modal/ModalManager.js
- packages/material-ui/src/Modal/ModalManager.test.js
Fixes https://github.com/mui-org/material-ui/issues/16537
> [Modal] Use computed key to restore style

- examples/nextjs-with-typescript/src/Link.tsx
> [docs] Use LinkProps from next in examples

- docs/src/pages/guides/migration-v3/migration-v3.md
- Adds `Slider` info to migration-v3 doc
> [docs] Update migration v3 guide, slider in core

- docs/src/pages/components/portal/portal.md
> [docs] Update typo in docs - portals

- docs/src/modules/utils/generateMarkdown.js
- docs/src/modules/utils/parseTest.js
- packages/material-ui/src/ButtonBase/TouchRipple.js
- packages/material-ui/src/ButtonBase/TouchRipple.test.js
- packages/material-ui/src/ButtonGroup/ButtonGroup.test.js
- pages/api/touch-ripple.md
Last component conversion for #15231
> [TouchRipple] Convert to function component

- package.json
Fixed `docs:typescript:check` which I broke in #16413
> [docs] Fix docs:typescript:check

- packages/material-ui/src/styles/createSpacing.d.ts
- packages/material-ui/src/styles/createSpacing.spec.ts
> [core] Fix type definition for createMuiTheme SpacingOptions

- package.json
- yarn.lock
- Upgraded `babel-plugin-optimize-clsx`
Has some new features that produces faster and smaller code (~200 bytes parsed)
> [core] Upgrade babel-plugin-optimize-clsx

- packages/material-ui/src/Step/Step.d.ts
> [Step] Add `completed` class key to TypeScript definitions

- examples/nextjs-with-typescript/pages/about.tsx
- examples/nextjs-with-typescript/pages/index.tsx
- examples/nextjs/pages/about.js
- examples/nextjs/pages/index.js
update string msg in about.tsx
> [examples] Remove version next version from the description

- docs/next.config.js
Currently displaying 4.1.2 (should be 4.2.1).
> [docs] Display correct version of Material-UI

- README.md
Ref: https://github.com/mui-org/material-ui/pull/16679#discussion_r306771227
> [docs] Fix dependabot badge

- docs/src/pages/components/modal/modal.md
> [docs] Fix Typo in modal.md

- docs/src/modules/components/ThemeContext.js
Closes #16749
[It wasn't me :)](https://github.com/mui-org/material-ui/pull/16410/files#diff-a9bfd3b20356185917a5d9742820590bL28)
> [docs] Fix reset colors crashing app

- docs/src/pages/components/tables/EnhancedTable.js
- docs/src/pages/components/tables/EnhancedTable.tsx
A workaround for #16760
Closes #16760
> [docs] Workaround to describe aria-sort

- docs/src/pages/components/steppers/CustomizedSteppers.js
- docs/src/pages/components/steppers/CustomizedSteppers.tsx
- docs/src/pages/components/steppers/steppers.md
- packages/material-ui/src/Step/Step.js
The new example
The baseline
The target (from Qonto)
> [Stepper] Add cutomization example

- docs/pages/api/tree-item.md
- docs/pages/api/tree-view.md
> [docs] Update treeview related API docs

- docs/src/pages/components/box/box.md
- docs/src/pages/guides/migration-v3/migration-v3.md
> [docs] Small fix for box.md and migration.md

- packages/material-ui/src/index.d.ts
> [TextareaAutosize] Add missing export for TextareaAutosize

- docs/pages/api/checkbox.md
- docs/pages/api/radio.md
- docs/pages/api/switch.md
- packages/material-ui/src/Checkbox/Checkbox.js
- packages/material-ui/src/Radio/Radio.js
- packages/material-ui/src/Switch/Switch.js
> [Radio][Switch][Checkbox] Document the `required` prop

- docs/src/pages/components/tooltips/CustomizedTooltips.js
- docs/src/pages/components/tooltips/CustomizedTooltips.tsx
> [Tooltip] Fix tooltips's demo arrow dimensions

- packages/material-ui/src/Grow/Grow.js
- packages/material-ui/src/transitions/utils.js
> [Transition] Change the default behavior, 0ms duration if prop missing

- docs/next.config.js
Fixed building the docs on windows. Broke in #16046
> [docs] Fix build on windows

- docs/src/pages/getting-started/supported-platforms/supported-platforms.md
> [docs] Add react compatibility in supported platforms

- docs/src/pages/getting-started/learn/learn.md
@oliviertassinari Based on our discussion, I am opening this PR. Let me know if there are any changes needed.
Thanks
Deeksha
> [docs] Add Material-UI with React course in learning

- docs/src/pages/customization/components/components.md
"You can adjusting the..." should be "You can adjust the...".
[X] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui-org/material-ui/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
> [docs] Fix grammatical error in components docs

- packages/material-ui/src/CssBaseline/CssBaseline.js
It will be a black screen unless your setup actually takes the entire content, probably we don't want that.
> [CssBaseline] Add backdrop base styles

- packages/material-ui/src/Collapse/Collapse.js
- packages/material-ui/src/Collapse/Collapse.test.js
- packages/material-ui/src/Fade/Fade.js
- packages/material-ui/src/Grow/Grow.js
- packages/material-ui/src/Menu/Menu.js
- packages/material-ui/src/Menu/Menu.test.js
- packages/material-ui/src/Popover/Popover.js
- packages/material-ui/src/Slide/Slide.js
- packages/material-ui/src/Zoom/Zoom.js
> [Transition] Forward isAppearing to onEnter, onEntering, onEntered

- docs/src/pages/customization/default-theme/default-theme.md
As discussed in https://github.com/mui-org/material-ui/pull/16920.
> [docs] Hide header in DefaultTheme demo

- packages/material-ui/src/TextareaAutosize/TextareaAutosize.js
> [Textfield] Add left property to prevent scrollbars on IE 11

- packages/material-ui/src/FormControl/FormControl.js
- packages/material-ui/src/FormControl/useFormControl.d.ts
- packages/material-ui/src/InputBase/InputBase.js
- packages/material-ui/src/InputBase/InputBase.test.js
> [FormControl] Warn if rendered mulitple inputs

- docs/pages/api/textarea-autosize.md
- packages/material-ui/src/TextareaAutosize/TextareaAutosize.js
> [TextareaAutosize] Update spelling in props (umber to number)

- docs/src/pages/getting-started/example-projects/example-projects.md
Adjust feature list for v2.0 of RMUIF (https://github.com/Phoqe/react-material-ui-firebase/tree/dialog-host)
> [docs] Adjust React + Material-UI + Firebase for v2.0

- packages/material-ui/src/index.js
> [TextareaAutosize] Export component in barrel index.js

- docs/package.json
- package.json
- yarn.lock
substituted system's cp command with cpy-cli in yarn: docs:export script
fixes https://github.com/mui-org/material-ui/issues/16998
> [core] yarn docs:export support for Windows 

- packages/material-ui/src/Tooltip/Tooltip.js
> [Tooltip] Fix word wrapping

- docs/src/pages/guides/minimizing-bundle-size/minimizing-bundle-size.md
> [docs] Improve instructions for Babel import plugins

- docs/src/pages/components/popper/ScrollPlayground.js
> [Tooltip] Improve arrow demo

- docs/pages/api/card-header.md
- packages/material-ui/src/CardHeader/CardHeader.js
> [CardHeader] Remove mention of children from API docs

- docs/src/pages/components/tree-view/CustomizedTreeView.js
- docs/src/pages/components/tree-view/CustomizedTreeView.tsx
- docs/src/pages/components/tree-view/FileSystemNavigator.js
- docs/src/pages/components/tree-view/FileSystemNavigator.tsx
- packages/material-ui-lab/src/TreeItem/TreeItem.js
- packages/material-ui-lab/src/TreeItem/TreeItem.test.js
> [TreeView] Lazy render the tree items

- docs/src/pages/guides/migration-v3/migration-v3.md
> [docs] Migration guide to v4: include change to dense Lists

- docs/src/pages/components/modal/ServerModal.js
- docs/src/pages/components/modal/ServerModal.tsx
- docs/src/pages/components/modal/SimpleModal.js
- docs/src/pages/components/modal/SimpleModal.tsx
- docs/src/pages/components/modal/SpringModal.js
- docs/src/pages/components/modal/SpringModal.tsx
- docs/src/pages/components/modal/TransitionsModal.js
- docs/src/pages/components/modal/TransitionsModal.tsx
- docs/src/pages/components/modal/modal.md
Motivated by https://twitter.com/kentcdodds/status/1122901172174639104.
> [Modal] Add transition documentation

- docs/src/pages/guides/right-to-left/right-to-left.md
- packages/material-ui-styles/src/getStylesCreator/getStylesCreator.js
- packages/material-ui-styles/src/makeStyles/makeStyles.js
- packages/material-ui-styles/src/makeStyles/makeStyles.test.js
- packages/material-ui-styles/src/withStyles/withStyles.test.js
It took me a long while to figure out what's wrong!
Related #10823
Closes #16094
> [styles] Better support right-to-left

- packages/material-ui/src/Drawer/Drawer.js
> [Drawer] Fix ref forwarding when variant="persistent"

- docs/src/pages/components/modal/SpringModal.js
- docs/src/pages/components/modal/SpringModal.tsx
Fixes #17098 
@oliviertassinari
> [docs] Fix typo in modal demo

- packages/material-ui/src/MenuItem/MenuItem.d.ts
> [MenuItem] Add missing dense classkey

- docs/pages/api/button-group.md
- packages/material-ui/src/ButtonGroup/ButtonGroup.js
> [ButtonGroup] Fix border color when disabled and contained

- docs/src/modules/utils/helpers.js
- docs/src/modules/utils/helpers.test.js
Closes #17049 
@oliviertassinari 
Hey, Let me know if this needs more changes!
Thanks :)
> [docs] Fix edit dependencies extraction 

- packages/material-ui/src/Popover/Popover.js
- packages/material-ui/src/Popper/Popper.js
> [Popover] Fix anchorEl positioning within popup window

- docs/src/pages/components/icons/icons.md
> Fix page rendering on Crowdin

- examples/nextjs-with-typescript/pages/_app.tsx
- examples/nextjs/pages/_app.js
Hi all!
I love material-ui and found some warnings this PR shows:
Regards,
> [examples] Fix warnings Container in _app.js with Next.js 

- examples/nextjs-with-typescript/pages/_app.tsx
- examples/nextjs-with-typescript/pages/about.tsx
- examples/nextjs-with-typescript/pages/index.tsx
- examples/nextjs-with-typescript/src/Link.tsx
- examples/nextjs/pages/_app.js
- examples/nextjs/pages/about.js
- examples/nextjs/src/Link.js
introduced by https://github.com/zeit/next.js/pull/8231
> [examples] Fix warning in next.js example

- packages/material-ui/src/Menu/Menu.d.ts
Fixes #17202 
Hey @oliviertassinari !
Let me know if this needs any changes! Thanks! =)
> [Menu] Include 'list' in class key

- docs/src/pages/components/icons/icons.md
(Though I might have done something wrong since it's saying can't automatically merge.)
> [docs] Minor Update to remove "n°" notations

- docs/src/pages/guides/typescript/typescript.md
> [docs] Require less strict tsconfig

- docs/src/pages/components/buttons/buttons.md
> [Button] Fix typo in demo text

- packages/material-ui/src/ButtonBase/TouchRipple.js
- packages/material-ui/src/CardActionArea/CardActionArea.js
> [CardActionArea] Fix 'border-radius'

- docs/src/pages/components/slider/CustomizedSlider.js
- docs/src/pages/components/slider/CustomizedSlider.tsx
- docs/src/pages/components/switches/CustomizedSwitches.js
- docs/src/pages/components/switches/CustomizedSwitches.tsx
> [docs] Improve style of the demos

- packages/material-ui/src/Button/Button.js
i guess this is self explanatory :)
> [Button] Remove code leftover from < v4

- docs/pages/api/badge.md
- docs/src/pages/components/badges/BadgeAlignment.js
- docs/src/pages/components/badges/BadgeAlignment.tsx
- docs/src/pages/components/badges/BadgeMax.js
- docs/src/pages/components/badges/BadgeMax.tsx
- docs/src/pages/components/badges/BadgeOverlap.js
- docs/src/pages/components/badges/BadgeOverlap.tsx
- docs/src/pages/components/badges/BadgeVisibility.js
- docs/src/pages/components/badges/BadgeVisibility.tsx
- docs/src/pages/components/badges/CustomizedBadges.js
- docs/src/pages/components/badges/CustomizedBadges.tsx
- docs/src/pages/components/badges/DotBadge.js
- docs/src/pages/components/badges/DotBadge.tsx
- docs/src/pages/components/badges/badges.md
- packages/material-ui/src/Badge/Badge.d.ts
- packages/material-ui/src/Badge/Badge.js
- packages/material-ui/src/Popover/Popover.d.ts
- packages/material-ui/src/Snackbar/Snackbar.d.ts
Add badge alignment properties to the `Badge` component.
Fixes #12219
Fixes #17067
Fixes #16249 (won't fix)
Fixes #14445
Fixes #13695
> [Badge] Add alignment options to badges

- docs/src/pages/components/badges/CustomizedBadges.js
- docs/src/pages/components/badges/CustomizedBadges.tsx
- packages/material-ui/src/Badge/Badge.js
Also tidy up the first customization demo
> [Badge] Improve shape of 2 digit badge

- packages/material-ui/src/Modal/ModalManager.js
Might be a breaking change when using the manager directly...
> [core] Fix typo contaniners -> containers

- docs/src/pages/components/buttons/ButtonRouter.tsx
- docs/src/pages/components/links/LinkRouter.tsx
- packages/material-ui/src/Button/Button.spec.tsx
Resolves https://github.com/mui-org/material-ui/pull/15193#discussion_r272129134
> [docs] Remove unnecessary any cast

- docs/src/pages/components/toggle-button/ToggleButtons.js
- docs/src/pages/components/toggle-button/toggle-button.md
- packages/material-ui-lab/src/ToggleButton/ToggleButton.js
- packages/material-ui-lab/src/ToggleButtonGroup/ToggleButtonGroup.js
> [ToggleButton] Improve accessibility

- docs/src/pages/components/snackbars/snackbars.md
> [docs] Improve grammar in snackbars

- CHANGELOG.md
Change `@material-ui/core` to `@v4.4.0`.
> [docs] Fix CHANGELOG.md

- packages/material-ui/src/TextareaAutosize/TextareaAutosize.js
- packages/material-ui/src/TextareaAutosize/TextareaAutosize.test.js
Fixes #17289 
@oliviertassinari
> [TextareaAutosize] Show scrollbar when rowsMax is exceeded

- docs/src/pages/discover-more/related-projects/related-projects.md
> [docs] Add tubular-react in related project

- docs/src/pages/discover-more/related-projects/related-projects.md
A follow up on https://github.com/szmslab/material-ui-flat-pagination/issues/12.
> [docs] Add material-ui-flat-pagination to related projects

- docs/src/pages/customization/color/ColorTool.js
Changes made: 
- Updated the check for valid `hex string`
- Added check for valid `rgb string`
Closes #17072
> [docs] Fix color tool crash

- docs/src/pages/components/tables/tables.md
- [ X] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui-org/material-ui/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
> [docs] Add tubular-react to tables related projects

- packages/material-ui/src/internal/SwitchBase.js
> [Radio] Add zIndex to SwitchBase

- docs/src/pages/components/tooltips/tooltips.md
> [docs] Add a note in disabled tooltip

- packages/material-ui-lab/src/SpeedDialIcon/SpeedDialIcon.js
- packages/material-ui/src/TablePagination/TablePagination.js
- packages/material-ui/src/test-utils/describeConformance.js
> [TablePagination] Merge root classes properly

- ROADMAP.md
- docs/src/pages/getting-started/support/support.md
Follow-up on https://github.com/mui-org/material-ui/pull/17437#discussion_r326142091 from @mbrookes and @eps1lon feedback
> [docs] Remove Access to premium modules from the support page

- docs/src/pages/customization/density/density.md
Changed from petential to potential.
> [docs] Spelling mistake

- docs/src/pages/components/popper/popper.md
> [docs] Fix Popper demo link typo

- docs/src/pages/system/flexbox/flexbox.md
> [Box] Fix demo item name

- docs/src/pages/discover-more/languages/Languages.js
> [docs] Fix english language link

- ROADMAP.md
- docs/pages/blog/august-2019-update.md
- docs/src/modules/components/AppFrame.js
- docs/src/modules/components/MarkdownElement.js
- docs/src/pages/components/breadcrumbs/CustomizedBreadcrumbs.js
- docs/src/pages/components/breadcrumbs/CustomizedBreadcrumbs.tsx
- docs/src/pages/components/breadcrumbs/breadcrumbs.md
- docs/src/pages/components/checkboxes/checkboxes.md
- docs/src/pages/components/dialogs/dialogs.md
- docs/src/pages/components/expansion-panels/expansion-panels.md
- docs/src/pages/components/links/links.md
- docs/src/pages/components/modal/modal.md
- docs/src/pages/components/radio-buttons/radio-buttons.md
- docs/src/pages/components/rating/rating.md
- docs/src/pages/components/slider/slider.md
- docs/src/pages/components/switches/switches.md
- docs/src/pages/components/text-fields/text-fields.md
- docs/src/pages/discover-more/related-projects/related-projects.md
- docs/src/pages/getting-started/support/support.md
- docs/src/pages/versions/versions.md
- [docs] Fix IE 11 rendering 8e641cf
- [docs] Iron the support details 8d9f159
- [Breadcrumb] Use the icon prop instead of the avatar 123096f
- [docs] Update the related projects list 481dd3c
- [docs] Link WAI-ARIA when possible f82a9a7
> [docs] Batch small fixes

- SUPPORT.md
Remove this currently broken file in favor of already present `/docs/src/pages/getting-started/support/support.md`
> [docs] Remove already moved SUPPORT.md file

- docs/src/pages/getting-started/templates/blog/Blog.js
> [docs] Remove an un-used className in template Blog

- examples/create-react-app/package.json
> [examples] Fix CRA start script

- docs/src/pages/styles/advanced/advanced.md
Closes https://github.com/mui-org/material-ui/issues/17566
As discussed on the issue - this makes the docs a little more explicit.
> [docs] Improve CSP nonce docs

- CONTRIBUTING.md
Merge branch structure and getting started into "Git workflow" and move to top.
I wasn't perfectly satisfied with https://github.com/mui-org/material-ui/pull/17562 so I made an alternative version :).
Give your thoughts.
Edit @eps1lon:
[Preview rendered text](https://github.com/croraf/material-ui/blob/contributing-3/CONTRIBUTING.md)
> [docs] Improve Contributing.md

- README.md
- docs/src/pages/getting-started/faq/faq.md
> [docs] Improve contributing guidelines

- docs/src/pages/components/dialogs/CustomizedDialogs.js
- docs/src/pages/components/dialogs/CustomizedDialogs.tsx
> [Dialog] Forward the id in example

- packages/material-ui/src/Button/Button.js
> [Button] Fix duplicate class names

- packages/material-ui/src/Avatar/Avatar.js
> [Avatar] Allow to set src and children

- package.json
- yarn.lock
Frequent test_browser runs seem to timeout more. Testing if this improves next sunday using https://github.com/karma-runner/karma-browserstack-launcher/issues/152
> [test] Fix test_browser timing out

- docs/pages/api/toggle-button-group.md
- docs/pages/api/toggle-button.md
- packages/material-ui-lab/src/ToggleButton/ToggleButton.test.js
- packages/material-ui-lab/src/ToggleButtonGroup/ToggleButtonGroup.test.js
* one more test in strict mode
* button and group tested to conform (describeConformance used)
* ground work for #17203
> [test] Use testing-library for ToggleButton* tests

- docs/src/pages/versions/versions.md
> [docs] Fix typo in versions.md

- packages/material-ui/src/Popper/Popper.js
- packages/material-ui/src/Popper/Popper.test.js
This PR address the `placement` argument not being updated as described in issue
Closes #17309
> [Popper] Fix placement update logic

- docs/src/pages/guides/interoperability/EmotionCSS.js
- docs/src/pages/guides/interoperability/EmotionCSS.tsx
- docs/src/pages/guides/interoperability/StyledComponentsDeep.js
- docs/src/pages/guides/interoperability/StyledComponentsDeep.tsx
- docs/src/pages/guides/interoperability/StyledComponentsPortal.js
- docs/src/pages/guides/interoperability/StyledComponentsPortal.tsx
```yarn docs:typescript:check``` and ```yarn docs:typescript:formatted```
> [docs] Add TS demos for guides/interoperability

- packages/material-ui/src/AppBar/AppBar.js
i did what was mentioned here.elevation seems to work with position="static" now
Closes #7994
> [AppBar] Fix display of elevation with position static

- docs/pages/api/button-group.md
- docs/pages/api/button.md
- docs/pages/api/drawer.md
- docs/pages/api/linear-progress.md
- docs/pages/api/speed-dial-icon.md
- docs/pages/api/step-label.md
- packages/material-ui-lab/src/SpeedDialIcon/SpeedDialIcon.js
- packages/material-ui/src/Button/Button.js
- packages/material-ui/src/ButtonGroup/ButtonGroup.js
- packages/material-ui/src/Drawer/Drawer.js
- packages/material-ui/src/LinearProgress/LinearProgress.js
- packages/material-ui/src/StepLabel/StepLabel.js
> [docs] Fix typo and improve consistency

- packages/material-ui/src/BottomNavigationAction/BottomNavigationAction.test.js
> [BottomNavigationAction] Test in StrictMode

- .codesandbox/ci.json
- package.json
This was not opened as a PR to be sure draft state doesn't interfere. Probably want to await initial feedback response.
Explainer: https://twitter.com/codesandbox/status/1181184975460282368
Edit: Waiting to be whitelisted.
> [test] Add codesandbox CI config

- packages/material-ui/src/Popper/Popper.js
Hey @oliviertassinari  I opened another PR for
[Tooltip] Tooltip misaligned when using 100vh and CssBaseline
Closes #17774
> [Popper] Revert position fix

- docs/src/pages/customization/breakpoints/WithWidth.js
- docs/src/pages/customization/breakpoints/WithWidth.tsx
Add one of the missing TS demos for mui-org/material-ui#14897
> [docs] Add TS demo for WithWidth

- packages/material-ui/src/Modal/Modal.js
> [Modal] Fix tabIndex customization

- packages/material-ui/src/TableCell/TableCell.js
> [Table] Fix sticky header interaction with checkboxes

- docs/src/pages/premium-themes/paperbase/Header.js
- docs/src/pages/premium-themes/paperbase/Header.tsx
> [docs] Fix typo in Paperbase theme

- docs/pages/api/table-cell.md
- packages/material-ui/src/TableCell/TableCell.js
Improved docs:
colSpan: Specifies the number of columns a cell should span.
> [docs] Improve TabelCell description

- docs/src/pages/guides/minimizing-bundle-size/minimizing-bundle-size.md
> [docs] Fix a typo while reading the doc :)

- packages/material-ui/src/Switch/Switch.js
> [Switch] Fix hover style on mobile

- docs/pages/api/avatar.md
- packages/material-ui/src/Avatar/Avatar.js
- packages/material-ui/src/Avatar/Avatar.test.js
> [Avatar] Revert #17694, correct the API docs, add tests

- test/karma.tests.js
- test/utils/performance.js
Linked issues are closed and locally tests passed.
> [test] Use Performance implementation of vendors

- docs/src/pages/components/tooltips/tooltips.md
> [docs] Add warning disabled button in safari

- packages/material-ui-lab/src/SpeedDial/SpeedDial.js
> [SpeedDial] Fix fab items alignment

- packages/material-ui/src/Button/Button.js
> [Button] Fix horizontal padding on small button with icon

- packages/material-ui-lab/src/Autocomplete/Autocomplete.test.js
- packages/material-ui-lab/src/useAutocomplete/useAutocomplete.js
> [Autocomplete] Fix multiple blur/focus crash

- packages/material-ui/src/FormControl/FormControl.js
- packages/material-ui/src/InputBase/InputBase.test.js
> [TextField] Fix typo in FromControl warning

- packages/material-ui/src/OutlinedInput/NotchedOutline.js
- packages/material-ui/src/OutlinedInput/OutlinedInput.js
> [OutlinedInput] Simplify customizations

- packages/material-ui-lab/src/Autocomplete/Autocomplete.js
Take care of it as I think that it's important to get the Autocomplete is a workable state, at least for the main use cases.
We might have observed an interesting behavior. It's not the first time that I notice that the more an issue has people interested in it, the less likely somebody will take on a pull request if the solution is simple.
Closes #18082
> [Autocomplete] Fix display in modal

- docs/pages/api/autocomplete.md
- docs/src/pages/components/autocomplete/Playground.js
- docs/src/pages/components/autocomplete/Playground.tsx
- packages/material-ui-lab/src/Autocomplete/Autocomplete.d.ts
- packages/material-ui-lab/src/Autocomplete/Autocomplete.js
- packages/material-ui-lab/src/Autocomplete/Autocomplete.test.js
> [Autocomplete] Add disabled prop

- packages/material-ui-benchmark/package.json
- yarn.lock
Closes #18218. I don't know why I added it in the first place.
> [core] Remove nodemod

- packages/material-ui/src/Select/Select.js
- packages/material-ui/src/Select/Select.test.js
Closes #18255
Regression introduced in #17892
> [Select] Fix id not being present when native

- docs/src/pages/components/tables/CustomPaginationActionsTable.js
- docs/src/pages/components/tables/CustomPaginationActionsTable.tsx
> [docs] Fix show all rows in table pagination

- packages/material-ui-lab/src/useAutocomplete/useAutocomplete.d.ts
- packages/material-ui-lab/src/useAutocomplete/useAutocomplete.js
> [useAutocomplete] Fix missing inputValue 

- packages/material-ui/src/ButtonGroup/ButtonGroup.d.ts
> [ButtonGroup] Fix typings for disabled classes property

- packages/material-ui-lab/src/useAutocomplete/useAutocomplete.js
> [useAutocomplete] Handle Opera fullscreen mode

- docs/src/modules/components/DiamondSponsors.js
- docs/src/pages/components/rating/HoverRating.js
- docs/src/pages/components/rating/HoverRating.tsx
- docs/src/pages/components/rating/SimpleRating.js
- docs/src/pages/components/rating/SimpleRating.tsx
- packages/material-ui-lab/src/Rating/Rating.js
> [Rating] Add random name when none is provided

- docs/pages/api/speed-dial-action.md
- packages/material-ui-lab/src/SpeedDialAction/SpeedDialAction.js
> [SpeedDial] Fix crash when using custom style in FabProps

- packages/material-ui-lab/src/useAutocomplete/useAutocomplete.js
> [Autocomplete] Fix usage of Home/End keys

- docs/src/pages/components/autocomplete/autocomplete.md
> [docs] Fix typo in autocomplete docs

- docs/src/pages/components/app-bar/app-bar.md
> [docs] Fix grammar in app-bar.md

- .github/PULL_REQUEST_TEMPLATE.md
I followed the link in the template for my first PR and it was broken - this should fix it!
> [GitHub] Fix fragment on link in PR template

- packages/material-ui-lab/src/Autocomplete/Autocomplete.test.js
> [Autocomplete] Fix typo in test

- packages/material-ui/src/styles/createMuiTheme.test.js
Corresponding pull request for #18541  - fixed ineffective test
Closes #18541
> [test] Improve merging tests for createMuiTheme

- docs/src/pages/components/skeleton/Variants.js
- docs/src/pages/components/skeleton/Variants.tsx
- docs/src/pages/components/skeleton/YouTube.js
- docs/src/pages/components/skeleton/YouTube.tsx
- docs/src/pages/components/skeleton/skeleton.md
- packages/material-ui-lab/src/Skeleton/Skeleton.js
Replace non-breakable space representation by properly recognizable one.
Fixes #18547
> [Skeleton] Fix non-breakable space

- docs/src/pages/components/popper/ScrollPlayground.js
> [docs] Fix bug in Popper component's Scroll playground example

- packages/material-ui-lab/src/Autocomplete/Autocomplete.js
> [Autocomplete] Show loading text when there are no options

- packages/material-ui-lab/src/Autocomplete/Autocomplete.test.js
- packages/material-ui-lab/src/useAutocomplete/useAutocomplete.js
> [Autocomplete] Only trigger onInputChange when the value changes

- packages/material-ui-lab/src/useAutocomplete/useAutocomplete.js
- [x ] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui-org/material-ui/blob/master/CONTRIBUTING.md#sending-a-pull-request).
Close #18574
> [Autocomplete] Only call .focus() when necessary 

- packages/material-ui-lab/src/Autocomplete/Autocomplete.js
> [Autocomplete] Fix CSS specificity issue

- docs/src/pages/guides/migration-v3/migration-v3.md
- [docs] Update v3 migration guide for ExpansionPanel#CollapseProps
This is related to PR #14617.
- [docs] Update v3 migration guide for ExpansionPanel#expanded
This is related to PR #15368.
> [docs] Update v3 migration guide for ExpansionPanel

- .dependabot/config.yml
> [core] Ignore url-loader >= 3 updates

- packages/material-ui/src/styles/props.d.ts
> [Container] Add missing default theme props Type

- packages/material-ui-lab/src/Autocomplete/Autocomplete.js
> [Autocomplete] Prevent tag overflow

- packages/material-ui/src/TablePagination/TablePagination.js
> [TablePagination] Fix responsive display issue

- docs/src/pages/guides/localization/localization.md
- packages/material-ui/src/locale/index.d.ts
- packages/material-ui/src/locale/index.js
> [l10n] Add Polish translation

- packages/material-ui/src/styles/createTypography.js
Closes #18659 using [this proposed diff](https://github.com/mui-org/material-ui/issues/18659#issuecomment-561114790).
> [Typography] Adapt lineHeight for h1-h5

- docs/src/modules/components/HomeSteps.js
> [docs] Revert hiding duplicate link

- packages/material-ui/src/NativeSelect/NativeSelect.js
> [Select] Fix incorrect auto-sizing of native select

- docs/src/pages/components/slider/CustomizedSlider.js
- docs/src/pages/components/slider/CustomizedSlider.tsx
- packages/material-ui-lab/src/Autocomplete/Autocomplete.d.ts
- packages/material-ui-lab/src/Autocomplete/Autocomplete.js
- packages/material-ui/src/Popper/Popper.js
- packages/material-ui/src/Tooltip/Tooltip.js
> [Popper] Fix position when changing state or updated

- docs/pages/api/input-base.md
- docs/pages/api/textarea-autosize.md
- docs/src/pages/components/textarea-autosize/MinHeightTextarea.js
- docs/src/pages/components/textarea-autosize/MinHeightTextarea.tsx
- packages/material-ui/src/InputBase/InputBase.js
- packages/material-ui/src/TextareaAutosize/TextareaAutosize.d.ts
- packages/material-ui/src/TextareaAutosize/TextareaAutosize.js
Closes https://github.com/mui-org/material-ui/issues/18314
> [TextareaAutosize] Add rowsMin prop

- docs/src/pages/guides/localization/localization.md
- packages/material-ui/src/locale/index.d.ts
- packages/material-ui/src/locale/index.js
> [l10n] Add Romanian (roRO) locale

- docs/src/pages/guides/localization/localization.md
- packages/material-ui/src/locale/index.d.ts
- packages/material-ui/src/locale/index.js
> [l10n] Add Ukrainian (uk-UA) locale

- packages/material-ui/src/Popover/Popover.js
> [Popover] Fix bug open animation

- packages/material-ui-lab/src/TreeItem/TreeItem.js
- packages/material-ui-lab/src/TreeItem/TreeItem.test.js
> [TreeView] Support input in item child

- docs/src/pages/guides/localization/localization.md
> [l10n] Fix Czech BCP47 in documentation

- packages/material-ui-lab/src/Autocomplete/Autocomplete.js
> [Autocomplete] Pass ListboxProps

- modules/waterfall/Batcher.js
- Change URL from https://caolan.github.io/async/docs.html#cargo to https://caolan.github.io/async/v3/docs.html#cargo
> [chore] Fix url address in modules/waterrfall/Batcher.js file

- docs/src/pages/components/menus/MenuPopupState.tsx
> [docs] Add TS demo for MenuPopupState

- docs/src/pages/components/toggle-button/toggle-button.md
> [docs] Fix typo in toggle-button.md

- docs/src/pages/customization/palette/palette.md
- [x ] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui-org/material-ui/blob/master/CONTRIBUTING.md#sending-a-pull-request).
> [docs] Fix syntax error in palette customization example

- packages/material-ui-lab/src/Autocomplete/Autocomplete.js
> [Autocomplete] Fix option height border-box

- docs/src/pages/guides/typescript/typescript.md
Discussion can be found at #18991
Closes #18991
> [docs] Clarify not all components have 'component' prop

- packages/material-ui/src/Popover/Popover.js
- packages/material-ui/src/Popover/Popover.test.js
- packages/material-ui/src/Slide/Slide.js
- packages/material-ui/src/Tabs/ScrollbarSize.js
Closes #10595
Apply the same patch as #18813.
> [Popover] Fix position when changing state or updated

- packages/material-ui-lab/src/useAutocomplete/useAutocomplete.js
> [Autocomplete] Warn when mixing uncontrolled and controlled

- packages/material-ui-lab/src/Rating/Rating.js
- [ v ] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui-org/material-ui/blob/master/CONTRIBUTING.md#sending-a-pull-request).
Closes #18939
> [Rating] Fix hover state stuck

- docs/pages/api/rating.md
- docs/src/pages/components/rating/CustomizedRatings.js
- docs/src/pages/components/rating/CustomizedRatings.tsx
- docs/src/pages/components/rating/HalfRating.js
- docs/src/pages/components/rating/HalfRating.tsx
- docs/src/pages/components/rating/HoverRating.js
- docs/src/pages/components/rating/HoverRating.tsx
- docs/src/pages/components/rating/RatingSize.js
- docs/src/pages/components/rating/RatingSize.tsx
- docs/src/pages/components/rating/rating.md
- packages/material-ui-lab/src/Rating/Rating.d.ts
- packages/material-ui-lab/src/Rating/Rating.js
- packages/material-ui-lab/src/Rating/Rating.test.js
- Add `defaultValue` prop
- Fix a regression after #19071: half rating selection, tooltip hover
- Fix a regression after #19004: half rating hover
- Apply @mbrookes's suggestion on disabled inputs.
> [Rating] Add default value prop

- docs/src/pages/guides/localization/localization.md
- packages/material-ui/src/locale/index.d.ts
- packages/material-ui/src/locale/index.js
Add Bulgarian translation ( bg-BG )
> [l10n] Add Bulgarian (pg-BG) locale

- packages/material-ui/src/locale/index.js
Also fixed starts/star translation logic, that was swapped. CC @Angelk90 who originally added this.
> [l10n] Improve it-IT locale

- docs/src/modules/components/useMarkdownDocs.js
- docs/src/modules/constants.js
- docs/src/modules/utils/generateMarkdown.js
> [docs] Fix "Edit this page" link

- docs/src/pages/components/chips/ChipsPlayground.js
> [docs] Fix a tiny mistake in Chips playground

- docs/src/pages/guides/interoperability/interoperability.md
Glamor section does not exist any more
> [docs] Remove Glamor link

- docs/src/pages/customization/typography/typography.md
Improves typography documentation to show use case with interplay with `CssBaseline`.
Resolves #18901
> [docs] Improve typography documentation

- packages/material-ui-lab/src/useAutocomplete/useAutocomplete.js
> [Autocomplete] Extend support to textarea

- docs/src/pages/components/switches/switches.md
Fixed broken link for suggested use of Checkboxes
> [docs] Fix link in switches.md

- docs/src/pages/components/tables/AcccessibleTable.js
- docs/src/pages/components/tables/AcccessibleTable.tsx
Resolves #19302
I could only find "bare bones" and "bare-bones" uses. And it also seems to me that the word "structure" is excessive here.
> [docs] Fix typo in the accessible table demo

- docs/src/pages/components/autocomplete/CustomizedHook.js
- docs/src/pages/components/autocomplete/CustomizedHook.tsx
> [Autocomplete] Polish CustomizedHook demo

- examples/nextjs-with-typescript/package.json
Fail to compile without this dependency
> [example] Add @types/node dependency

- packages/material-ui/src/OutlinedInput/NotchedOutline.js
> [OutlinedInput] Prevent overriding legend display styles

- packages/material-ui/src/FormHelperText/FormHelperText.js
> [TextField] Reduce helper text height to match spec

- docs/src/pages/components/buttons/TextButtons.js
- docs/src/pages/components/buttons/TextButtons.tsx
- docs/src/pages/components/buttons/buttons.md
All the other link buttons on the page are set to primary color, now so is this one.
> [docs] Increase button variant demos consistency

- docs/pages/api/autocomplete.md
- packages/material-ui-lab/src/Autocomplete/Autocomplete.js
> [docs] Fix typo in Autocomplete CSS API

- packages/material-ui/src/OutlinedInput/NotchedOutline.js
> [TextField] Handle leaky global styles of Bootstrap

- docs/src/pages/components/grid/InteractiveGrid.js
- docs/src/pages/components/grid/InteractiveGrid.tsx
- docs/types/docs.d.ts
Ref: https://github.com/mui-org/material-ui/issues/19113#issuecomment-580966632
> [docs] Remove `@ts-ignore` usage

- docs/src/pages/guides/localization/localization.md
- packages/material-ui/src/locale/index.d.ts
- packages/material-ui/src/locale/index.js
[l10n] Add Icelandic (is-IS) locale
> [l10n] Add Icelandic (is-IS) locale

- docs/src/pages/guides/localization/localization.md
- packages/material-ui/src/locale/index.d.ts
- packages/material-ui/src/locale/index.js
> [l10n] Add Hungarian (hu-HU) locale

- CONTRIBUTING.md
> [docs] Update link to example for adding a new demo

- docs/src/pages/components/tree-view/RecursiveTreeView.js
- docs/src/pages/components/tree-view/RecursiveTreeView.tsx
- docs/src/pages/components/tree-view/tree-view.md
> [TreeView] Add recursive demo

- docs/src/pages/discover-more/related-projects/related-projects.md
Data Driven Form is an open source library for rendering and managing forms using data schemas.
Please see:
[Documentation](https://data-driven-forms.org/)
[GitHub repo](https://github.com/data-driven-forms/react-forms)
[Introduction article](https://medium.com/javascript-in-plain-english/data-driven-approach-to-forms-with-react-c69fd4ea7923)
> [docs] Add Data Driven Forms to the list of libraries

- packages/material-ui/src/SwipeableDrawer/SwipeableDrawer.js
Commited suggested changes from issue
Closes #18977.
> [SwipeableDrawer] Improve Preact support

- azure-pipelines.yml
Fixing ` Artifact canaries already exists for build 7018.`
> [ci] Update publish pipeline task

- docs/src/pages/customization/components/components.md
> [docs] Fix broken link to jss-nested plugin

- docs/src/pages/getting-started/supported-platforms/supported-platforms.md
- [v] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui-org/material-ui/blob/master/CONTRIBUTING.md#sending-a-pull-request).
> [docs] Fix typo on supported-platforms.md

- packages/material-ui/test/typescript/components.spec.tsx
> [test] Fix defaultProps overriding props

- docs/src/pages/guides/localization/localization.md
- packages/material-ui/src/locale/index.d.ts
- packages/material-ui/src/locale/index.js
> [l10n] Add Hebrew (he-IL) locale

- packages/material-ui/src/TextField/TextField.js
- packages/material-ui/src/TextField/TextField.test.js
> [TextField] Fix outlined render gap if label = empty string

- docs/src/pages/discover-more/related-projects/related-projects.md
> [docs] Fix Sketch link

- docs/src/pages/system/flexbox/FlexDirection.js
- docs/src/pages/system/flexbox/FlexDirection.tsx
For better comprehension of the doc
> [docs] Flexbox: update item number

- docs/src/pages/system/flexbox/AlignSelf.js
- docs/src/pages/system/flexbox/AlignSelf.tsx
- docs/src/pages/system/flexbox/FlexWrap.js
- docs/src/pages/system/flexbox/FlexWrap.tsx
Add en element for show the effect of wraping on all screen size
> [docs] Flexbox, add element for show the good effect

- docs/src/pages/getting-started/support/support.md
> [docs] Remove premium support offerings

- .github/workflows/scripts.yml
Tested on https://github.com/eps1lon/material-ui-playroom/pull/206 which triggered https://github.com/mui-org/material-ui/actions/runs/51492035 whose dispatch triggered https://github.com/eps1lon/mui-scripts-incubator/runs/492744818?check_suite_focus=true
> [ci] Fix incorre pr number for experimental scripts

- packages/material-ui/src/FormControl/FormControl.js
Reverts mui-org/material-ui#19547
Closes #19677
> [TextField] Minimize usage of z-index

- docs/src/pages/components/checkboxes/CheckboxLabels.js
- docs/src/pages/components/checkboxes/CheckboxLabels.tsx
- docs/src/pages/components/checkboxes/CheckboxesGroup.js
- docs/src/pages/components/checkboxes/CheckboxesGroup.tsx
Simplify onChange callbacks of the Checkbox component examples.
> [docs] Simplify checkbox examples

- packages/material-ui/src/Grid/Grid.js
> [Grid] Fix row-reverse typo

- docs/src/pages/components/autocomplete/autocomplete.md
> [docs] Fix grammar in autocomplete doc

- packages/material-ui/src/styles/createPalette.d.ts
> [core] Add missing properties to TypeAction

- scripts/prettier.js
> [core] Add spacing after prettier command

- azure-pipelines.yml
~Don't know if this works.~
Looks good. Merging and then we'll see if rebased PRs run.
> [ci] Fix azure not running

- docs/next.config.js
For the same reason why we don't want an eslint error to crash and prevent iterations. This is a follow-up on the Next v9 upgrade.
*implemented in https://github.com/zeit/next.js/pull/9138, motivated by https://github.com/zeit/next.js/issues/7687.*
> [core] Improve the DX when iterating on components

- package.json
> [core] Fix docs:api cleaning the wrong directory

- docs/src/pages/components/backdrop/backdrop.md
Update inconsistency between use of the word Overlay and Backdrop
> [docs] Fix wording in backdrop.md

- docs/src/pages/getting-started/templates/album/README.md
- docs/src/pages/getting-started/templates/blog/README.md
- docs/src/pages/getting-started/templates/checkout/README.md
- docs/src/pages/getting-started/templates/dashboard/README.md
- docs/src/pages/getting-started/templates/pricing/README.md
- docs/src/pages/getting-started/templates/sign-in-side/README.md
- docs/src/pages/getting-started/templates/sign-in/README.md
- docs/src/pages/getting-started/templates/sign-up/README.md
- docs/src/pages/getting-started/templates/sticky-footer/README.md
> [docs] Add demo link

- docs/src/pages/components/chips/ChipsPlayground.js
- docs/src/pages/components/popover/AnchorPlayground.js
> [docs] Fix popover anchor playground crash

- packages/material-ui-lab/src/TreeItem/TreeItem.js
- packages/material-ui-lab/src/TreeItem/TreeItem.test.js
> [TreeView] fix inconsistent focus for programmatically focused tree item #20141

- .github/workflows/maintenance.yml
10 times after 3 minutes wait (up from 5 times after 2 minutes). Very likely that some PRs just stay in UNKNOWN for ever. If this grace period isn't enough I just switch skip the early exit and retry just the UNKNOWN PRs.
> [ci] Retry mergable state for 30 minutes

- docs/src/pages/components/icons/icons.md
> [docs] Fix grammer: a -> they

- packages/material-ui-lab/src/TreeItem/TreeItem.js
- packages/material-ui-lab/src/TreeItem/TreeItem.test.js
> [TreeView] Allow TreeItem to have conditional child

- README.md
- docs/src/modules/components/Ad.js
- docs/src/pages/discover-more/backers/backers.md
- docs/src/pages/getting-started/support/support.md
- docs/src/pages/landing/QuickWord.js
- docs/src/pages/landing/backers.md
@oliviertassinari Tidelift is automatically tracking leads now and it seems that some of your UTM parameters haven't been updated (and some others were updated incorrectly). Here is a PR that fixes everything I could find.
As for the incorrect UTM param updates, I talked with the team about them and Amy from our marketing  team would love to schedule some time with you to walk through how they work. If you'd like, I can set this up.
> [docs] Fix Tidelift UTM parameters

- packages/material-ui/src/Select/Select.test.js
- packages/material-ui/src/Select/SelectInput.js
Fix #20351, thanks oliviertassinari 😄
Edit: Force pushes are changing the git author stuff (work laptop and all that)
> [Select] onChange fired with current value

- docs/src/pages/components/text-fields/FormattedInputs.js
- docs/src/pages/components/text-fields/FormattedInputs.tsx
> [docs] Fix masked text field bug

- packages/material-ui/src/styles/index.d.ts
> [styles] Export ThemeProviderProps in core

- packages/material-ui/src/Select/Select.test.js
> [Select] onChange fired with current value test

- docs/pages/_document.js
- examples/nextjs-with-typescript/pages/_document.tsx
- examples/nextjs/pages/_document.js
Fixes https://github.com/zeit/next.js/issues/9041
> [examples] Fix next.js AMP support

- docs/src/pages/components/text-fields/MultilineTextFields.js
- docs/src/pages/components/text-fields/MultilineTextFields.tsx
- packages/material-ui/src/InputBase/InputBase.test.js
- test/regressions/tests/Textarea/Textarea.js
> [TextareaAutosize] Update rows/rowMax to use number for better clarity
