mui/material-ui

- packages/material-ui/src/locale/index.js
I added more strings for `fa-IR` locale and fix number string for `labelDisplayedRows`  in `MuiTablePagination` and `getLabelText`  in `MuiRating`.
Thanks!
> [l10n] Improve persian (fa-IR) locale

- packages/material-ui/src/Popper/Popper.d.ts
This is a follow-up to #20342.
Similar to #20443.
> [Popper] Fix support for TypeScript 3.2

- docs/src/pages/components/autocomplete/autocomplete.md
> [docs] Fix filerOption typo in autocomplete

- docs/src/pages/components/container/container.md
> [docs] Fix small typo in Container

- docs/src/pages/getting-started/support/support.md
- [ Yes ] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui-org/material-ui/blob/master/CONTRIBUTING.md#sending-a-pull-request).
> [docs] Fix punctuation and english grammar

- packages/material-ui-lab/src/Autocomplete/Autocomplete.test.js
- packages/material-ui-lab/src/useAutocomplete/useAutocomplete.js
> [Autocomplete] Fix autoHighlight behavior

- docs/README.md
> [docs] Fix command to start docs server

- docs/src/pages/components/popover/PopoverPopupState.tsx
- docs/src/pages/components/popper/PopperPopupState.tsx
> [docs] Add TypeScript demo for PopoverPopupState

- docs/pages/api-docs/toggle-button-group.md
- packages/material-ui-lab/src/ToggleButtonGroup/ToggleButtonGroup.d.ts
- packages/material-ui-lab/src/ToggleButtonGroup/ToggleButtonGroup.js
> [ToggleButton] Document how values are compared

- packages/material-ui/src/locale/index.js
> [l10n] Improve az-AZ locale

- packages/material-ui/src/locale/index.js
> [l10n] Improve bg-BG locale

- packages/material-ui/src/locale/index.js
Update ptPT locale with new keys.
Ref #20656
> [I10n] Improve pt-PT locale

- packages/material-ui/src/locale/index.js
> [I10n] Improve ro-RO locale

- packages/material-ui/src/locale/index.js
> [l10n] Improve et-EE locale

- docs/src/pages/guides/right-to-left/right-to-left.md
> [docs] Add "Persian" to the list of RTL languages

- packages/material-ui/src/useScrollTrigger/useScrollTrigger.js
- scripts/sizeSnapshot/webpack.config.js
Fixes https://github.com/mui-org/material-ui/issues/20676
> [useScrollTrigger] Fix out of sync trigger

- docs/package.json
- packages/material-ui/package.json
- yarn.lock
> [core] Bump `@material-ui/react-transition-group`

- examples/gatsby/README.md
> [docs] English fix: fewer boilerplate -> less boilerplate

- packages/material-ui/src/NativeSelect/NativeSelect.js
> [Select] Fix height inconsistency between input and select

- docs/src/pages/guides/localization/localization.md
> [docs] Fix "Find the source" link in localization.md 

- packages/material-ui/src/locale/index.ts
I have translated the missing spanish keys as per https://github.com/mui-org/material-ui/issues/20738#issuecomment-619159799
> [l10n] Improve es-ES locale

- docs/src/pages/components/tables/CollapsibleTable.js
- docs/src/pages/components/tables/CollapsibleTable.tsx
- docs/src/pages/components/tables/tables.md
This is based on #4476.
Screenshot of the new example:
> [docs] Add collapsible table demo

- docs/src/pages/getting-started/page-layout-examples/PageLayoutExamples.js
This PR fixes the broken source code links on the below page:
https://v3.material-ui.com/getting-started/page-layout-examples/
> [docs] Fix broken source code links

- docs/src/pages/styles/api/api.md
> [docs] Fix incorrect signature of createStyles

- docs/src/pages/components/tables/CustomPaginationActionsTable.js
- docs/src/pages/components/tables/CustomPaginationActionsTable.tsx
> [docs] Fix header and row shift on pagination click

- packages/material-ui-lab/src/Autocomplete/Autocomplete.js
- packages/material-ui-lab/src/Autocomplete/Autocomplete.test.js
> [Autocomplete] Fix support for limitTags={0}

- packages/material-ui-styles/src/makeStyles/indexCounter.js
> [styles] Fix wording in indexCounter comment

- packages/material-ui-codemod/src/v0.15.0/import-path.test.js
- packages/material-ui-codemod/src/v1.0.0/color-imports.test.js
- packages/material-ui-codemod/src/v1.0.0/import-path.test.js
- packages/material-ui-codemod/src/v1.0.0/svg-icon-imports.test.js
- packages/material-ui-codemod/src/v4.0.0/optimal-imports.test.js
- packages/material-ui-codemod/src/v4.0.0/theme-spacing-api.test.js
- packages/material-ui-codemod/src/v4.0.0/top-level-imports.test.js
- packages/material-ui-icons/builder.test.js
- packages/material-ui-styles/src/makeStyles/makeStyles.test.js
- packages/material-ui-styles/src/withTheme/withTheme.test.js
- packages/material-ui/src/Hidden/HiddenJs.test.js
- packages/material-ui/src/Menu/Menu.test.js
- packages/material-ui/src/MobileStepper/MobileStepper.test.js
- packages/material-ui/src/styles/createTypography.test.js
- packages/material-ui/src/styles/responsiveFontSizes.test.js
- packages/material-ui/src/utils/index.test.js
- packages/material-ui/src/utils/requirePropFactory.test.js
- scripts/listChangedFiles.test.js
Follow-up on #20799.
- [X ] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui-org/material-ui/blob/master/CONTRIBUTING.md#sending-a-pull-request).
> [test] Replace all assert with expect

- docs/src/pages/components/autocomplete/Virtualize.js
- docs/src/pages/components/autocomplete/Virtualize.tsx
> [docs] Fix groups name in autocomplete virtualization example

- docs/pages/index.js
> [docs] Remove redirection to v0 (#17637)

- docs/src/pages/guides/localization/localization.md
- packages/material-ui/src/locale/index.ts
> [l10n] Add Hindi (hi-IN) locale

- packages/material-ui-lab/src/Autocomplete/Autocomplete.test.js
- packages/material-ui-lab/src/useAutocomplete/useAutocomplete.js
Fix [20588#issuecomment-624260696 ](https://github.com/mui-org/material-ui/issues/20588#issuecomment-624260696)
- [ X] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui-org/material-ui/blob/master/CONTRIBUTING.md#sending-a-pull-request).
> [Autocomplete] Fix onHighlightChange when filtering

- packages/material-ui/src/Tabs/ScrollbarSize.js
> [core] Fix typo in internal ScrollbarSize

- packages/material-ui-lab/src/Autocomplete/Autocomplete.test.js
> [core] Fix typo in test description

- packages/material-ui/src/TableBody/TableBody.test.js
- packages/material-ui/src/TableCell/TableCell.test.js
- packages/material-ui/src/TableFooter/TableFooter.test.js
- packages/material-ui/src/TableHead/TableHead.test.js
- packages/material-ui/src/TablePagination/TablePagination.test.js
- packages/material-ui/src/TableRow/TableRow.test.js
- packages/material-ui/src/TableSortLabel/TableSortLabel.test.js
- [ X] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui-org/material-ui/blob/master/CONTRIBUTING.md#sending-a-pull-request).
> [test] Migrate all Table components to testing-library

- packages/material-ui/src/Popper/Popper.js
- packages/material-ui/src/Popper/Popper.test.js
What do you think about the correction?
By the way we need a test case?
Closes #20917
> [Popper] Fix keepMounted visibility

- packages/material-ui-lab/src/TabPanel/TabPanel.js
- packages/material-ui-lab/src/TabPanel/TabPanel.test.js
> [TabPanel] Allow flow content

- packages/material-ui/src/Select/Select.test.js
- packages/material-ui/src/Select/SelectInput.js
> [Select] Fix possible crash when clicking on the label

- packages/material-ui-lab/src/TreeView/TreeView.test.js
Test for https://github.com/mui-org/material-ui/issues/20832
> [test] Add test for undesired behavior of TreeView

- docs/src/pages/styles/basics/HigherOrderComponent.js
- docs/src/pages/styles/basics/HigherOrderComponent.tsx
The class component here is not a higher order component but a simple class component. HOC is actually what withStyles(styles) yields. Let's not confuse people.
> [docs] Reduce confusion around higher order component

- docs/src/pages/components/snackbars/PositionedSnackbar.js
- docs/src/pages/components/snackbars/PositionedSnackbar.tsx
- docs/src/pages/components/snackbars/snackbars.md
> [Snackbar] Explain how to place the snackbar

- docs/src/pages/landing/Quotes.js
> [docs] Add new twitter quotes to the homepage

- docs/src/pages/components/css-baseline/css-baseline.md
- docs/src/pages/customization/globals/globals.md
> [docs] Show font smoothing override

- docs/src/pages/components/modal/modal.md
Small typo fix in modal accessibility description.
> [docs] Fix typo in Modal accessibility description

- packages/material-ui/src/locale/index.ts
> [l10n] Add new keys to Finnish (fi-FI) locale

- packages/material-ui-lab/src/SpeedDialAction/SpeedDialAction.test.js
- packages/material-ui-styles/src/ThemeProvider/ThemeProvider.test.js
- packages/material-ui/src/ListItemText/ListItemText.test.js
- packages/material-ui/src/Radio/Radio.test.js
- packages/material-ui/src/Snackbar/Snackbar.test.js
- packages/material-ui/src/StepIcon/StepIcon.test.js
- packages/material-ui/src/Tabs/ScrollbarSize.test.js
- packages/material-ui/src/TextareaAutosize/TextareaAutosize.test.js
Migrating tests is a satisfying task :P
> [test] Migrate some tests to testing-library

- packages/material-ui/src/Popper/Popper.js
Fix [#21102](https://github.com/mui-org/material-ui/issues/21102)
> [Popper] Remove duplicate handleOpen call from effect

- .circleci/config.yml
- scripts/react-next.diff
Patch has conflicts on master.
> [test] Fix react next patch

- packages/material-ui-lab/src/Autocomplete/Autocomplete.test.js
- packages/material-ui-lab/src/useAutocomplete/useAutocomplete.js
> [Autocomplete] Fix autoHighlight for dynamic options

- docs/src/pages/getting-started/templates/checkout/AddressForm.js
- docs/src/pages/getting-started/templates/checkout/PaymentForm.js
Apply correct autocomplete attributes.
For reference: https://developers.google.com/web/updates/2015/06/checkout-faster-with-autofill
> [docs] Fix autocomplete attributes

- docs/src/modules/components/Ad.js
- docs/src/modules/components/MarkdownElement.js
Might be more instances where we set fixed font sizes. These are the ones I noticed.
> [docs] Improve text based sizing for larger font scales

- docs/src/pages/components/radio-buttons/radio-buttons.md
[Often requested](https://stackoverflow.com/questions/33680157/how-can-i-get-input-radio-elements-to-horizontally-align-in-react-material-ui).
> [docs] Mention laying out radio buttons horizontally

- packages/material-ui-lab/src/Autocomplete/Autocomplete.test.js
- packages/material-ui-lab/src/useAutocomplete/useAutocomplete.js
> [Autocomplete] Improve getOptionLabel usage warning

- CONTRIBUTING.md
Per https://stackoverflow.com/a/5697856
> `git push -u <remote> HEAD` will push the current branch
> to a branch of the same name on `<remote>`
> (and also set up tracking so you can do `git push` after that).
> [docs] Simplify CONTRIBUTING.md

- packages/material-ui/src/Tooltip/Tooltip.js
> [Tooltip] Improve arrow customization

- packages/material-ui/src/StepButton/StepButton.js
Closes https://github.com/mui-org/material-ui/issues/21208
> [Stepper] Add focus ripple to StepButton

- packages/material-ui/src/InputBase/InputBase.js
> [TextField] Fix missing autofill events

- packages/material-ui/src/locale/index.ts
> [l10n] Improve Ukrainian translation

- packages/material-ui/src/CircularProgress/CircularProgress.js
Closes https://github.com/mui-org/material-ui/issues/5735
> [CircularProgress] Fix IE 11 wobbling 

- packages/material-ui-lab/src/PaginationItem/PaginationItem.js
> [Pagination] Fix selected item style

- docs/pages/api-docs/native-select.md
- docs/pages/api-docs/select.md
- packages/material-ui/src/NativeSelect/NativeSelect.js
- packages/material-ui/src/Select/Select.test.js
- packages/material-ui/src/Select/SelectInput.js
- packages/material-ui/src/TextField/TextField.test.js
> [Select] Improve native validation, autofill, and testability

- docs/src/pages/discover-more/showcase/appList.js
Hi! I'm an author of builderbook.org. We have updated our homepage, and I'd like to see if we can update it on your showcase. I've changed the text in the PR.
Could we also update the snapshot? I've attached a new one here.
> [docs] Update builderbook.org showcase

- docs/src/pages/components/material-icons/SearchIcons.js
- packages/material-ui/src/Popper/Popper.test.js
- packages/material-ui/src/Select/Select.test.js
I didn't see a lot of small "holes" this week:
- [test] Wording consistency 10c17ab
- [test] Typo in test description 4f881ce
- [test] Remove dead code 25cccf9
- [docs] Track icon usage 5aa93fdc4
> [core] Batch small changes

- docs/pages/api-docs/card-media.md
- docs/pages/api-docs/chip.md
- docs/pages/api-docs/container.md
- packages/material-ui/src/CardActionArea/CardActionArea.js
- packages/material-ui/src/CardContent/CardContent.d.ts
- packages/material-ui/src/CardContent/CardContent.js
- packages/material-ui/src/CardHeader/CardHeader.d.ts
- packages/material-ui/src/CardHeader/CardHeader.js
- packages/material-ui/src/CardMedia/CardMedia.d.ts
- packages/material-ui/src/CardMedia/CardMedia.js
- packages/material-ui/src/Chip/Chip.d.ts
- packages/material-ui/src/Chip/Chip.js
- packages/material-ui/src/Container/Container.d.ts
- packages/material-ui/src/Container/Container.js
- packages/material-ui/src/ExpansionPanel/ExpansionPanel.d.ts
- packages/material-ui/src/Tooltip/Tooltip.d.ts
- scripts/generateProptypes.ts
core components starting with `C`
> [docs] Move more prop docs into IntelliSense

- docs/src/pages/components/tables/tables.md
^ I see no reason to test the code after this change, as I've only changed the phrasing of an existing line in the docs.
> [docs] Correct the name of a prop in the Table docs

- docs/src/modules/components/MarkdownElement.js
- docs/src/modules/utils/parseMarkdown.js
Closes #21385
Preview: http://deploy-preview-21386--material-ui.netlify.app/components/alert/#api
> [docs] Always consider code as left-to-right

- CONTRIBUTING.md
- packages/material-ui/src/Step/Step.js
- packages/material-ui/src/Stepper/Stepper.js
- packages/material-ui/src/Stepper/Stepper.test.js
Hello! This is a fix for https://github.com/mui-org/material-ui/issues/21325  
@oliviertassinari I followed your suggestion on fixing this issue. But I had to rewrite a couple of tests to make them green again.
Closes #21325
> [Stepper] Always pass state props to connector

- packages/material-ui-lab/src/Autocomplete/Autocomplete.test.js
- packages/material-ui-lab/src/useAutocomplete/useAutocomplete.js
> [Autocomplete] Prevent default event for disabled options

- packages/material-ui/src/StepButton/StepButton.test.js
Uses @testing-library/react over enzyme
> [test] Use testing-library in StepButton

- docs/src/modules/components/AppDrawer.js
- docs/src/modules/components/AppFooter.js
> [docs] Fix version in localized urls

- test/regressions/index.js
Unclear why vrtest doesn't throw on undefined test cases.
> [test] Ignore empty vrtests

- packages/material-ui/src/FilledInput/FilledInput.js
> [TextField] Fix FilledInput disable hover style when disabled

- docs/src/pages/components/autocomplete/GitHubLabel.js
- docs/src/pages/components/autocomplete/GitHubLabel.tsx
- packages/material-ui-lab/src/Autocomplete/Autocomplete.test.js
- packages/material-ui-lab/src/useAutocomplete/useAutocomplete.js
> [Autocomplete] Fix support for renderTags={() => null}

- docs/src/pages/production-error/index.md
- docs/translations/translations.json
- [X ] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui-org/material-ui/blob/master/CONTRIBUTING.md#sending-a-pull-request).
Some changes.
- production-error - Grammar error
- translations.json - Entry for translations
> [docs] Entry for translations and fix grammar error

- docs/src/pages/components/tables/tables.md
- scripts/listChangedFiles.js
We'll probably start seeing unclean merges for PRs that are based on commits prior to prettier changes. We should keep an eye on the base of PRs that are currently open.
> [core] Misc prettier changes

- packages/material-ui/src/locale/index.ts
> [I10n] Improve Russian translation

- docs/src/pages/styles/advanced/advanced.md
Following up on documentation update proposed in https://github.com/mui-org/material-ui/issues/19938
> [docs] Add CSP support section to docs

- scripts/react-next.diff
- scripts/use-react-dist-tag.js
Forward porting ##21482 to `next`.
> [core] Fix react next patch and prevent regression

- docs/pages/customization/transitions.js
- docs/src/pages.js
- docs/src/pages/customization/theming/theming.md
- docs/src/pages/customization/transitions/TransitionHover.js
- docs/src/pages/customization/transitions/TransitionHover.tsx
- docs/src/pages/customization/transitions/transitions.md
Docs page: https://deploy-preview-21456--material-ui.netlify.app/customization/transitions/
Closes https://github.com/mui-org/material-ui/issues/16928
> [docs] Add transitions customization page

- docs/src/pages/components/autocomplete/autocomplete.md
Accidentally broken in https://github.com/mui-org/material-ui/commit/23cc51630329e2e6f0ecfd15432e8639d4ce9b8a
> [docs] Fix broken "customizations" anchor link

- docs/src/pages/components/use-media-query/use-media-query.md
- docs/src/pages/customization/breakpoints/breakpoints.md
> [docs] Improve docs for useMediaQuery and breakpoint

- docs/src/pages/components/grid/grid.md
In order to understand your two first examples I had to consult another site. I find it a pity that the original source of truth for Material-UI is not self-explanatory.
> [docs] Add more details about breakpoint widths

- packages/material-ui/src/locale/index.ts
Preview https://deploy-preview-21493--material-ui.netlify.app/guides/localization/#example
> [i18n] Improve zh-CN, add zh-TW

- docs/src/pages/components/tree-view/CustomizedTreeView.js
- docs/src/pages/components/tree-view/CustomizedTreeView.tsx
- packages/material-ui-lab/src/TreeItem/TreeItem.js
Wanted this as a separate PR than functionality changes so it doesn't get lost.
> [TreeView] Minor styling changes

- packages/material-ui/src/locale/index.ts
> [l10n] Fix TypeScript version support

- packages/material-ui/src/locale/index.ts
> [l10n] Translate additional csCZ and skSK

- yarn.lock
Uses:
- https://github.com/babel/babel/releases/tag/v7.10.4
> Bump `@babel/*` packages

- .github/CODEOWNERS
- CHANGELOG.md
- docs/src/modules/components/Ad.js
- docs/src/modules/components/AppSearch.js
- docs/src/pages/components/autocomplete/autocomplete.md
- docs/src/pages/components/pagination/pagination.md
- docs/src/pages/getting-started/learn/learn.md
- docs/src/pages/guides/migration-v4/migration-v4.md
- packages/material-ui/src/Slider/Slider.js
- packages/material-ui/src/Unstable_TrapFocus/Unstable_TrapFocus.js
- [docs] Fix ChangeEvent typo bcf0bd3: Thanks @TrySound for the report.
- [core] Clear codeowner ff07d23: I have noticed that @dimitropoulos was included in pull requests he should have been into. I suspect it happens when we change the base of a pull request from master to next. Because the Alert component is quite stable, I think that it's simpler to manually assign in our case.
- [docs] Fix Autocomlete formatting in Crowdin 667f165: It's broken: https://github.com/mui-org/material-ui/blob/master/docs/src/pages/components/autocomplete/autocomplete-zh.md#autocompleteautofill.
- [docs] Remove potential confusion 101cedc: We don't advertise for Sketch or Figma per say.
- [core] Rollout `event` vs `nativeEvent` 8dcda27: this direction was decided in …
> [docs] Batch small changes

- docs/src/pages/getting-started/faq/faq.md
- examples/nextjs-with-typescript/README.md
- examples/nextjs/README.md
This PR adds troubleshooting for Next.js examples, which takes me a lot of time to found out what I've missed. I think this troubleshooting will save time for people who run into the same issue in the feature.
BTW, I'm not sure which branch sure I set as the target branch. Currently, I use `next` as the target branch, but I can change this PR to merge into the `master` if you want.
> [examples] Include troubleshooting for next.js

- packages/material-ui-lab/src/Autocomplete/Autocomplete.test.js
- packages/material-ui-lab/src/TreeView/descendants.js
- test/karma.tests.js
We should run lab in a browser as well to anticipate integration into core. Also required when JSDOM in insufficient.
> [test] Run lab unit tests in browser

- packages/material-ui/src/Unstable_TrapFocus/Unstable_TrapFocus.js
- packages/material-ui/src/Unstable_TrapFocus/Unstable_TrapFocus.test.js
> [TrapFocus] Fix disableAutoFocus prop

- CONTRIBUTING.md
PRs against `master` should be rare enough that I don't think we need to explain it in detail. We can't cover all cases in CONTRIBUTING anyway. Documenting the default workflow should be enough.
> [docs] Recommend default branch

- docs/src/pages/components/switches/CustomizedSwitches.js
- docs/src/pages/components/switches/CustomizedSwitches.tsx
Fixes #21715 
Small fix of ripple color for Custom Switches.
> [docs] Fix custom switch ripple color

- docs/src/pages/components/timeline/CustomizedTimeline.js
- docs/src/pages/components/timeline/CustomizedTimeline.tsx
Updated customized timeline demo as discussed in #21735:
- Removed Paper
- Vertically Centered content
- ~~Renamed CustomizedTimeline to ComplexTimeline~~
Closes #21735
> [docs] Improve customized timeline demo

- packages/material-ui-lab/package.json
- packages/material-ui-lab/src/TabContext/TabContext.test.js
- packages/material-ui-lab/src/TabList/TabList.test.js
- packages/material-ui-lab/src/TabPanel/TabPanel.test.js
- packages/material-ui-lab/tsconfig.test.json
- packages/material-ui/src/test-utils/describeConformance.js
- test/utils/createClientRender.js
Caught by typechecking tests for the experimental Tabs API.
> [test] Allow container + hydrate in render

- docs/src/pages/discover-more/showcase/appList.js
Just corrected the text from [this pull request](https://github.com/mui-org/material-ui/pull/21637).
> [docs] Fix text from showcase

- packages/material-ui/src/styles/createBreakpoints.js
- packages/material-ui/src/styles/createBreakpoints.test.js
- packages/material-ui/src/withWidth/withWidth.js
Fixed CSS Media Queries for custom breakpoints.
Resolves #21745
> [theme] Fix custom breakpoint in CSS Media Queries

- docs/src/modules/components/Ad.js
- docs/src/modules/components/AdCarbon.js
- docs/src/modules/components/AdDisplay.js
- docs/src/modules/components/AdInHouse.js
- docs/src/modules/components/AdManager.js
- docs/src/modules/components/AdReadthedocs.js
- docs/src/modules/components/Demo.js
- docs/src/modules/components/DiamondSponsors.js
- docs/src/modules/components/ad.styles.js
Since CodeFund shutdown, EthicalAds powered by readthedocs.io seems to be a lead worth exploring: https://www.similarweb.com/website/readthedocs.io.
> [docs] Add ethicalads.io

- docs/src/modules/components/AppDrawerNavItem.js
> [docs] Fix nav color

- docs/translations/translations-es.json
Fixing a translation mistake :)
> [docs] Fix Spanish translation

- packages/material-ui-styles/src/withStyles/withStyles.test.js
This makes it easier to fix these tests for `react@next`.
Remove some shared variables from the tests which reduces indirection. The more isolated tests are the better.
> [test] Use testing-library in withStyles

- docs/src/pages/getting-started/example-projects/example-projects.md
Just a PR for updating the meta info for the RMUIF example project.
> [docs] Change RMUIF info to new version

- packages/material-ui-lab/src/SpeedDial/SpeedDial.test.js
- packages/material-ui-lab/src/SpeedDialAction/SpeedDialAction.test.js
- packages/material-ui-lab/src/TreeItem/TreeItem.test.js
- packages/material-ui-lab/src/TreeView/TreeView.test.js
- packages/material-ui/src/Accordion/Accordion.test.js
- packages/material-ui/src/Backdrop/Backdrop.test.js
- packages/material-ui/src/Dialog/Dialog.test.js
- packages/material-ui/src/Drawer/Drawer.test.js
- packages/material-ui/src/Menu/Menu.test.js
- packages/material-ui/src/Modal/Modal.test.js
- packages/material-ui/src/Popover/Popover.test.js
- packages/material-ui/src/Popper/Popper.test.js
- packages/material-ui/src/Select/Select.test.js
- packages/material-ui/src/Snackbar/Snackbar.test.js
- packages/material-ui/src/StepContent/StepContent.test.js
- packages/material-ui/src/Stepper/Stepper.test.js
- packages/material-ui/src/Tooltip/Tooltip.test.js
- packages/material-ui/test/integration/Menu.test.js
- packages/material-ui/test/integration/NestedMenu.test.js
- packages/material-ui/test/integration/Select.test.js
Enabled where enabling it didn't require too much work. The rest can be handled over time.
> [test] Enable more StrictMode tests

- framer/scripts/buildFramer.js
> [framer] Refactor as switch

- docs/src/pages/components/text-fields/text-fields.md
- docs/src/pages/discover-more/related-projects/related-projects.md
> [docs] Link react-hook-form

- packages/material-ui-lab/src/AvatarGroup/AvatarGroup.js
> [Avatar] Fix group size

- CONTRIBUTING.md
Increase visibility of https://twitter.com/MuiContrib
> [docs] Mention @MuiContrib in CONTRIBUTING

- README.md
- docs/src/pages/discover-more/backers/backers.md
- docs/src/pages/landing/QuickWord.js
- docs/src/pages/landing/backers.md
I am an engineer at Text-Em-All (formerly Call-Em-All) and I updated the url and html attributes to reflect our new company name 😎.
> [docs] Update gold sponsor to Text-Em-All (formerly Call-Em-All)

- docs/src/pages/customization/breakpoints/breakpoints.md
- [x ] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui-org/material-ui/blob/next/CONTRIBUTING.md#sending-a-pull-request).
Closes #21892
> [docs] Improve documentation of theme.breakpoints

- docs/src/pages/components/tree-view/ControlledTreeView.js
- docs/src/pages/components/tree-view/ControlledTreeView.tsx
- docs/src/pages/components/tree-view/tree-view.md
> [docs] Add expand all and select all  to controlled tree demo

- docs/src/pages/components/snackbars/CustomizedSnackbars.js
- docs/src/pages/components/snackbars/CustomizedSnackbars.tsx
- [x ] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui-org/material-ui/blob/next/CONTRIBUTING.md#sending-a-pull-request).
close #21821
> [docs] Fix custom Snackbar width on mobile

- docs/src/pages/components/autocomplete/autocomplete.md
> [docs] Autocomplete is not showing options even though they exist

- packages/material-ui/src/Icon/Icon.js
> [Icon] Hide name placeholder while "Material Icons" font is loading

- packages/material-ui/src/ClickAwayListener/ClickAwayListener.js
- packages/material-ui/src/Dialog/Dialog.js
> [Dialog] Fix body scrollbar close behavior

- docs/src/pages/guides/localization/localization.md
- packages/material-ui/src/locale/index.ts
> [l10n] Add Greek (el-GR) locale

- docs/package.json
- docs/webpackBaseConfig.js
- yarn.lock
Closes #21940
~Trying to find out if this is even used anymore~ Doesn't look like it's used anymore
> [test] Drop css-loader

- .eslintignore
- .eslintrc.js
- framer/Material-UI.framerfx/code/BottomNavigation.tsx
- framer/Material-UI.framerfx/code/Icon.tsx
- framer/Material-UI.framerfx/code/ListItem.tsx
- framer/scripts/buildFramer.js
- framer/scripts/templates/bottom_navigation.txt
- framer/scripts/templates/icon.txt
- framer/scripts/templates/list_item.txt
Especially important since a lot of code is auto-generated. Linting is a good smoke test before having to go through importing the package into framer (which requires macOS).
> [test] Lint framer workspace

- docs/pages/api-docs/text-field.md
- docs/pages/api-docs/textarea-autosize.md
- docs/src/pages/components/text-fields/text-fields.md
- docs/src/pages/guides/migration-v4/migration-v4.md
- framer/Material-UI.framerfx/code/TextField.tsx
- framer/scripts/framerConfig.js
- packages/material-ui/src/InputBase/InputBase.js
- packages/material-ui/src/TextField/TextField.d.ts
- packages/material-ui/src/TextField/TextField.js
- packages/material-ui/src/TextareaAutosize/TextareaAutosize.d.ts
- packages/material-ui/src/TextareaAutosize/TextareaAutosize.js
- packages/material-ui/src/TextareaAutosize/TextareaAutosize.test.js
> [TextField] Better isolate static textarea behavior to dynamic one

- docs/src/pages/getting-started/example-projects/example-projects.md
- docs/src/pages/guides/server-rendering/server-rendering.md
> [docs] Add visibility to TypeScript examples

- docs/public/_redirects
- packages/material-ui-styles/src/makeStyles/makeStyles.js
- packages/material-ui-styles/src/useThemeVariants/useThemeVariants.test.js
- packages/material-ui/src/Button/Button.d.ts
- packages/material-ui/src/Button/Button.test.js
This PR is doing some cleanups on the custom variants work, before we start enabling that API to other components.
> [Button] Improved variant type names & cleanup tests

- docs/src/pages/components/dialogs/DraggableDialog.js
- docs/src/pages/components/dialogs/DraggableDialog.tsx
> [docs] Improve draggable dialog demo wording

- docs/pages/api-docs/toggle-button.md
- packages/material-ui-lab/src/ToggleButton/ToggleButton.d.ts
- packages/material-ui-lab/src/ToggleButton/ToggleButton.js
> [docs] Add 'size' prop to ToggleButton API docs

- docs/src/pages/components/floating-action-button/FloatingActionButtonZoom.js
- docs/src/pages/components/floating-action-button/FloatingActionButtonZoom.tsx
- docs/src/pages/components/tabs/FullWidthTabs.js
- docs/src/pages/components/tabs/FullWidthTabs.tsx
- docs/src/pages/components/tabs/NavTabs.js
- docs/src/pages/components/tabs/NavTabs.tsx
- docs/src/pages/components/tabs/ScrollableTabsButtonAuto.js
- docs/src/pages/components/tabs/ScrollableTabsButtonAuto.tsx
- docs/src/pages/components/tabs/ScrollableTabsButtonForce.js
- docs/src/pages/components/tabs/ScrollableTabsButtonForce.tsx
- docs/src/pages/components/tabs/ScrollableTabsButtonPrevent.js
- docs/src/pages/components/tabs/ScrollableTabsButtonPrevent.tsx
- docs/src/pages/components/tabs/SimpleTabs.js
- docs/src/pages/components/tabs/SimpleTabs.tsx
- docs/src/pages/components/tabs/TabsWrappedLabel.js
- docs/src/pages/components/tabs/TabsWrappedLabel.tsx
- docs/src/pages/components/tabs/VerticalTabs.js
- docs/src/pages/components/tabs/VerticalTabs.tsx
Avoid using any type in Tabs examples.
> [docs] Avoid using any type in Tabs examples

- package.json
- packages/material-ui-lab/src/Autocomplete/Autocomplete.test.js
- packages/material-ui-styles/src/ThemeProvider/ThemeProvider.test.js
- packages/material-ui-styles/src/makeStyles/makeStyles.test.js
- packages/material-ui-styles/src/useThemeVariants/useThemeVariants.test.js
- packages/material-ui/src/Breadcrumbs/Breadcrumbs.test.js
- packages/material-ui/src/ClickAwayListener/ClickAwayListener.test.js
- packages/material-ui/src/Drawer/Drawer.test.js
- packages/material-ui/src/Modal/Modal.test.js
- packages/material-ui/src/Popover/Popover.test.js
- packages/material-ui/src/Select/Select.test.js
- packages/material-ui/src/Tabs/Tabs.test.js
- packages/material-ui/src/TextareaAutosize/TextareaAutosize.test.js
- packages/material-ui/src/Tooltip/Tooltip.test.js
- packages/material-ui/src/Unstable_TrapFocus/Unstable_TrapFocus.js
- packages/material-ui/src/Unstable_TrapFocus/Unstable_TrapFocus.test.js
- packages/material-ui/src/internal/SwitchBase.test.js
- packages/material-ui/src/useMediaQuery/useMediaQuery.test.js
- packages/material-ui/src/utils/focusVisible.test.js
- packages/material-ui/test/integration/Select.test.js
- yarn.lock
If you leave a big "REVERT ME LATER" you better do it. Reverts https://github.com/mui-org/material-ui/pull/22105/commits/990bbea72457420cc62dffcf330fb1549231e9e0
> [test] Remove react@next patch

- docs/pages/api-docs/avatar.md
- framer/Material-UI.framerfx/code/Avatar.tsx
- framer/scripts/framerConfig.js
- packages/material-ui-styles/src/makeStyles/makeStyles.js
- packages/material-ui/src/Avatar/Avatar.d.ts
- packages/material-ui/src/Avatar/Avatar.js
> [Avatar] Custom variant

- README.md
Hi,
Thanks for signing up for our open source program! We hope you’ve found it valuable. 
Open source projects like yours power the world of tech, and we’re honored to be helping you. We’ve benefitted from hundreds of open source projects, and now's our time to give back.
I have added BrowserStack Logo under “Testing powered by” heading to the Readme
This helps us reach more open source developers like you, ones who can use BrowserStack’s infrastructure for free and build great products.
Naineet Patel
BrowserStack DevRel
> [docs] Add the services that support us in readme

- docs/pages/api-docs/divider.md
- packages/material-ui-styles/src/makeStyles/makeStyles.js
- packages/material-ui/src/Divider/Divider.d.ts
- packages/material-ui/src/Divider/Divider.js
One of https://github.com/mui-org/material-ui/issues/21749
> [Divider] Custom variant

- packages/eslint-plugin-material-ui/src/rules/rules-of-use-theme-variants.js
> [test] Lint fix the custom rules plugin for useThemeVariants

- docs/pages/api-docs/fab.md
- docs/pages/api-docs/input-adornment.md
- docs/pages/api-docs/list-item-avatar.md
- docs/pages/api-docs/popper.md
- packages/material-ui-styles/src/StylesProvider/StylesProvider.js
- packages/material-ui-styles/src/ThemeProvider/ThemeProvider.js
- packages/material-ui/src/Container/Container.d.ts
- packages/material-ui/src/Container/Container.js
- packages/material-ui/src/Fab/Fab.d.ts
- packages/material-ui/src/Fab/Fab.js
- packages/material-ui/src/InputAdornment/InputAdornment.d.ts
- packages/material-ui/src/InputAdornment/InputAdornment.js
- packages/material-ui/src/ListItemAvatar/ListItemAvatar.d.ts
- packages/material-ui/src/ListItemAvatar/ListItemAvatar.js
- packages/material-ui/src/Popper/Popper.d.ts
- packages/material-ui/src/Popper/Popper.js
> [core] Change children to be optional

- packages/material-ui/src/Accordion/Accordion.test.js
- test/utils/setupJSDOM.js
Resolves https://github.com/mui-org/core-plus-pickers/pull/5#discussion_r470456017
@dmtrKovalenko You might want to cherry-pick 4c21217d6a96a4429127698968d218bc64fd7f32 since the current state can be very frustrating.
> [test] Prevent swallowing errors during setup

- docs/pages/api-docs/toolbar.md
- packages/material-ui-styles/src/makeStyles/makeStyles.js
- packages/material-ui/src/Toolbar/Toolbar.d.ts
- packages/material-ui/src/Toolbar/Toolbar.js
One of https://github.com/mui-org/material-ui/issues/21749
> [Toolbar] Custom varaint

- docs/pages/api-docs/skeleton.md
- packages/material-ui-lab/src/Skeleton/Skeleton.d.ts
- packages/material-ui-lab/src/Skeleton/Skeleton.js
- packages/material-ui-styles/src/makeStyles/makeStyles.js
One of https://github.com/mui-org/material-ui/issues/21749
> [Skeleton] Custom variant

- packages/material-ui-lab/src/Autocomplete/Autocomplete.js
- packages/material-ui/src/FilledInput/FilledInput.js
- packages/material-ui/src/InputBase/InputBase.js
- packages/material-ui/src/NativeSelect/NativeSelect.js
- packages/material-ui/src/OutlinedInput/OutlinedInput.js
Resolves #22104 , under advisement of @joshwooding
> [TextField] Remove line-height reset

- packages/material-ui/src/Slider/Slider.test.js
- packages/material-ui/src/StepButton/StepButton.test.js
- packages/material-ui/src/SwipeableDrawer/SwipeableDrawer.js
- packages/material-ui/src/SwipeableDrawer/SwipeableDrawer.test.js
> [SwipeableDrawer] Fix prevented inner scroll

- packages/material-ui/src/Unstable_TrapFocus/Unstable_TrapFocus.js
Backport of https://github.com/mui-org/material-ui/pull/22262
> [TrapFocus] Prevent possible crash in React 17

- docs/src/pages/components/dialogs/ConfirmationDialog.js
- docs/src/pages/components/dialogs/ConfirmationDialog.tsx
- docs/src/pages/components/snackbars/ConsecutiveSnackbars.js
- docs/src/pages/components/snackbars/ConsecutiveSnackbars.tsx
> [docs] Fix use of removed transition onE* props

- packages/material-ui/src/locale/index.ts
Add missing / fix Japanese translations.
> [l10n] Improve ja-JP locale

- packages/material-ui/src/locale/index.ts
> [l10n] Improve th-TH locale

- packages/material-ui/src/Unstable_TrapFocus/Unstable_TrapFocus.test.js
Should've been part of #22124 .
> [test] Enable tests that weren't working in JSDOM

- packages/material-ui/src/DialogTitle/DialogTitle.test.js
Replaces enzyme for react-testing-library in the `<DialogTitle />`
> [DialogTitle] Use react-testing-library

- docs/public/_redirects
A first page https://material-ui.com/components/data-grid/pagination/ 😱
Export to code sandbox will be solved with #22346 and https://github.com/mui-org/material-ui-x/pull/168
> [docs] Forward x data-grid

- docs/src/pages/discover-more/showcase/appList.js
- docs/src/pages/discover-more/showcase/showcase.md
- docs/src/pages/landing/Users.js
> [docs] Update showcase instructions

- docs/src/pages/styles/basics/basics.md
^ Kind of? This just PR just addresses a small typo.
> [docs] Improve styles basics.md section

- packages/material-ui/src/Modal/ModalManager.d.ts
- packages/material-ui/src/Modal/ModalManager.ts
- packages/material-ui/src/utils/getScrollbarSize.ts
- packages/material-ui/src/utils/ownerDocument.d.ts
- packages/material-ui/src/utils/ownerDocument.js
- packages/material-ui/src/utils/ownerDocument.ts
- packages/material-ui/src/utils/ownerWindow.d.ts
- packages/material-ui/src/utils/ownerWindow.ts
Closes https://github.com/mui-org/material-ui/issues/22449
Includes some runtime changes that became apparent with types. Need to be careful.
> [Modal] Convert ModalManager to TypeScript

- packages/material-ui/src/SwipeableDrawer/SwipeableDrawer.js
Solution proposed by @oliviertassinari !
Fix #22493 
[*] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui-org/material-ui/blob/next/CONTRIBUTING.md#sending-a-pull-request).
> [SwipeableDrawer] Avoid blocking events

- docs/src/pages/guides/migration-v4/migration-v4.md
- packages/material-ui/src/styles/adaptV4Theme.js
- packages/material-ui/src/styles/adaptV4Theme.test.js
- packages/material-ui/src/styles/createPalette.d.ts
- packages/material-ui/src/styles/createPalette.js
- [theme] Remove `theme.palette.text.hint`.
> [theme] Remove palette.text.hint key

- docs/src/pages/components/switches/switches.md
- [x ] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui-org/material-ui/blob/next/CONTRIBUTING.md#sending-a-pull-request).
> [docs] Fix typo, extra 'you'

- packages/material-ui/src/StepIcon/StepIcon.js
- packages/material-ui/src/StepIcon/StepIcon.test.js
the StepIcon className is not worked by inner render doesn't pass that into className.
> [StepIcon] Add className in render SvgIcon

- docs/src/pages/components/autocomplete/CustomizedHook.js
- docs/src/pages/components/autocomplete/CustomizedHook.tsx
> [docs] Customized hook at Autocomplete issue in dark mode

- .circleci/config.yml
- .github/workflows/maintenance.yml
- azure-pipelines.yml
Backport of #22624 and [`7da8eea` (#22065)](https://github.com/mui-org/material-ui/pull/22065/commits/7da8eea44b758a972e5f754afbec8320ad1e2646)
> [test] Only run on push for master/next

- docs/next.config.js
- docs/public/_redirects
- docs/src/pages.js
> [docs] configuring redirects for MUI X

- docs/src/pages/components/app-bar/MenuAppBar.js
- docs/src/pages/components/app-bar/MenuAppBar.tsx
just minor tweaks to make it look more practical for users.
if you accept this one I can make these changes to all of the Demo HighlitedCode.
> [docs] Reduce indirections

- docs/src/pages/discover-more/related-projects/related-projects.md
Added [UI Schema](https://github.com/ui-schema/ui-schema) in related projects.
IDE removed trailing whitespaces at other entries.
> [docs] Add ui-schema in related projects

- docs/src/pages/getting-started/templates/dashboard/Dashboard.js
- docs/src/pages/getting-started/templates/dashboard/Dashboard.tsx
Refactor of methods "handleDrawerOpen" and "handleDrawerClose" into only one.
> [docs] Improve Dashboard template

- packages/material-ui/src/styles/createSpacing.d.ts
- packages/material-ui/test/typescript/styles.spec.tsx
> [theme] Fix createSpacing.d.ts definition

- packages/material-ui/src/MobileStepper/MobileStepper.js
- packages/material-ui/src/StepIcon/StepIcon.js
- packages/material-ui/src/StepLabel/StepLabel.js
Solution proposed by @oliviertassinari 
Closes #22266
> [Stepper] Add slight transition

- crowdin.yml
Towards resolving #22649 (and future) CI issues
> [test] Skip CI for crowdin commits

- docs/pages/api-docs/slider-styled.md
- packages/material-ui-lab/src/SliderStyled/SliderStyled.js
- scripts/generateProptypes.ts
> [docs] Add props from Unstyled component to Styled API page

- docs/src/pages/components/autocomplete/GitHubLabel.js
- docs/src/pages/components/autocomplete/GitHubLabel.tsx
> [Autocomplete] Update GitHub customization example

- packages/material-ui-lab/src/useAutocomplete/useAutocomplete.d.ts
> [useAutocomplete] Fix getXProps functions type

- CONTRIBUTING.md
Made the Point - 4 in (## Sending a Pull Request) more user-friendly by making it more elaborative.
Following change is proposed by me for CONTRIBUTING.md :-
{4. Install the dependencies using npm or yarn as shown below:
//for npm
npm  install <dependency>
//for yarn
yarn install <dependency>
}
> [docs] CONTRIBUTING.md only yarn is supported

- packages/material-ui-lab/src/ToggleButtonGroup/ToggleButtonGroup.js
> [ToggleButtonGroup] Match component name and render function name

- docs/src/pages/guides/typescript/typescript.md
- [X ] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui-org/material-ui/blob/next/CONTRIBUTING.md#sending-a-pull-request).
> [docs] Fix typo in guides/typescript

- babel.config.js
- docs/babel.config.js
- docs/package.json
- package.json
- yarn.lock
> [core] Drop babel-plugin-transform-dev-warning

- packages/material-ui/src/TextField/TextField.js
> [TextField] Pass minRows to InputComponent

- CHANGELOG.md
- docs/src/pages/components/rating/rating.md
- packages/eslint-plugin-material-ui/src/rules/rules-of-use-theme-variants.test.js
- packages/material-ui-lab/src/SliderUnstyled/SliderUnstyled.js
- packages/material-ui-styles/src/createGenerateClassName/createGenerateClassName.js
- packages/material-ui-styles/src/makeStyles/makeStyles.spec.tsx
- packages/material-ui/src/Breadcrumbs/Breadcrumbs.test.js
- packages/material-ui/src/InputBase/InputBase.test.js
- packages/material-ui/src/Slider/Slider.js
- packages/material-ui/src/utils/scrollLeft.js
- packages/material-ui/src/utils/useIsFocusVisible.js
- packages/material-ui/test/integration/NestedMenu.test.js
This pull request fixes a variety of typos throughout the repository.
> [docs] Fix various typos

- packages/material-ui/src/IconButton/IconButton.js
Closes #22804 
@croraf please check if it fulfills the requirement. Thanks!
> [IconButton] Improve warning against non root onClick listeners

- docs/src/pages/components/icons/CreateSvgIcon.js
- docs/src/pages/components/icons/CreateSvgIcon.tsx
- docs/src/pages/components/icons/icons.md
https://github.com/mui-org/material-ui/pull/22780/files/96812f89ccc314306000f6192d2f020522808fc8#r498975225
> [docs] Document createSvgIcon()

- packages/material-ui-lab/src/ToggleButtonGroup/ToggleButtonGroup.js
- packages/material-ui/src/ToggleButton/ToggleButton.js
- packages/material-ui/src/ToggleButtonGroup/ToggleButtonGroup.js
> [ToggleButton] Fix vertical double border

- docs/src/pages/landing/Steps.js
Added @emotion/core and @emotion/styled
> [docs] Include peer deps in installation steps

- docs/src/pages/components/progress/progress.md
- packages/material-ui/src/CircularProgress/CircularProgress.js
> [CircularProgress] Drop IE11 wobbly workaround

- packages/material-ui/src/Slide/Slide.test.js
> [test] Migrate Slide to react-testing-library

- packages/material-ui/src/Zoom/Zoom.test.js
> [test] Migrate Zoom to react-testing-library

- packages/material-ui/src/Container/Container.test.js
> [test] Migrate Container to react-testing-library

- packages/material-ui-styles/src/useTheme/useTheme.test.js
- packages/material-ui-styles/src/withTheme/withTheme.test.js
> [test] Migrate useTheme,withTheme to react-testing-library

- packages/material-ui/src/Backdrop/Backdrop.test.js
I don't have a lot of experience with the library, and I couldn't find a similar test in the other PRs.
I hope I did fine.
#22911
> [test] Migrate Backdrop to react-testing-library

- packages/material-ui/src/SpeedDial/SpeedDial.js
- packages/material-ui/src/SpeedDial/SpeedDial.test.js
- test/karma.conf.js
> [SpeedDial] Fix keyboard navigation when uncontrolled

- docs/src/pages/components/tooltips/AnchorElTooltips.js
- docs/src/pages/components/tooltips/AnchorElTooltips.tsx
- packages/material-ui/src/Box/Box.d.ts
> [Box] Add types for `ref` 

- packages/material-ui/src/List/List.test.js
> [test] Migrate List to react-testing-library

- docs/src/pages/components/buttons/LoadingButtons.js
- docs/src/pages/components/buttons/LoadingButtons.tsx
- docs/src/pages/components/buttons/LoadingButtonsTransition.js
- docs/src/pages/components/buttons/LoadingButtonsTransition.tsx
- packages/material-ui-lab/src/LoadingButton/LoadingButton.test.js
With potential changes coming to fix #22845 we might as well codify current behavior in tests. Also makes the current demos interactive so that people can actually use the component.
https://deploy-preview-22878--material-ui.netlify.app/components/buttons/#loading-buttons
> [docs] Document LoadingButton behavior

- examples/create-react-app/package.json
- examples/create-react-app/public/index.html
- examples/create-react-app/src/App.js
> [docs] Improve CRA example

- packages/material-ui/src/SpeedDialIcon/SpeedDialIcon.test.js
-  [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui-org/material-ui/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).
Related to #22911
> [test] Migrate SpeedDialIcon to react-testing-library

- packages/material-ui/src/CssBaseline/CssBaseline.test.js
- packages/material-ui/src/RadioGroup/RadioGroup.test.js
> [test] Migrate RadioGroup to react-testing-library

- packages/material-ui/src/MobileStepper/MobileStepper.test.js
> [test] Migrate MobileStepper to react-testing-library

- .eslintignore
- .eslintrc.js
- scripts/prettier.js
This opportunity was found in https://github.com/mui-org/material-ui-x/pull/407#discussion_r500970242 with @dtassone
> [core] Also format dot files & folders

- docs/src/modules/utils/getJsxPreview.js
- docs/src/pages/components/slider-styled/ContinuousSlider.js
- docs/src/pages/components/slider-styled/ContinuousSlider.tsx
- docs/src/pages/components/slider-styled/CustomizedSlider.js
- docs/src/pages/components/slider-styled/CustomizedSlider.tsx
- docs/src/pages/components/slider-styled/DiscreteSlider.js
- docs/src/pages/components/slider-styled/DiscreteSlider.tsx
- docs/src/pages/components/slider-styled/DiscreteSliderLabel.js
- docs/src/pages/components/slider-styled/DiscreteSliderLabel.tsx
- docs/src/pages/components/slider-styled/DiscreteSliderMarks.js
- docs/src/pages/components/slider-styled/DiscreteSliderMarks.tsx
- docs/src/pages/components/slider-styled/DiscreteSliderSteps.js
- docs/src/pages/components/slider-styled/DiscreteSliderSteps.tsx
- docs/src/pages/components/slider-styled/DiscreteSliderValues.js
- docs/src/pages/components/slider-styled/DiscreteSliderValues.tsx
- docs/src/pages/components/slider-styled/InputSlider.js
- docs/src/pages/components/slider-styled/InputSlider.tsx
- docs/src/pages/components/slider-styled/RangeSlider.js
- docs/src/pages/components/slider-styled/RangeSlider.tsx
- docs/src/pages/components/slider-styled/TrackFalseSlider.js
- docs/src/pages/components/slider-styled/TrackFalseSlider.tsx
- docs/src/pages/components/slider-styled/TrackInvertedSlider.js
- docs/src/pages/components/slider-styled/TrackInvertedSlider.tsx
- docs/src/pages/components/slider-styled/UnstyledSlider.js
- docs/src/pages/components/slider-styled/UnstyledSlider.tsx
- docs/src/pages/components/slider-styled/VerticalSlider.js
- docs/src/pages/components/slider-styled/VerticalSlider.tsx
- packages/material-ui/src/styles/experimentalStyled.d.ts
> [docs] Slider demos clean up

- scripts/react-next.diff
Fix https://app.circleci.com/pipelines/github/mui-org/material-ui/23944/workflows/04265535-d974-4503-8153-f9a1452bd88b/jobs/186121
> [core] Fix react-next test

- packages/material-ui/src/IconButton/IconButton.test.js
I have tried to follow other merged PRs for this issue #22911
I hope this was useful.
> [test] Migrate IconButton to react-testing-library

- README.md
> [docs] Move outdated versions into a collapsible section

- packages/material-ui/src/SpeedDial/SpeedDial.d.ts
- packages/material-ui/src/SpeedDial/SpeedDial.js
- packages/material-ui/src/SpeedDialAction/SpeedDialAction.d.ts
- packages/material-ui/src/SpeedDialAction/SpeedDialAction.js
- packages/material-ui/src/SpeedDialIcon/SpeedDialIcon.d.ts
- packages/material-ui/src/SpeedDialIcon/SpeedDialIcon.js
- packages/material-ui/src/index.d.ts
- packages/material-ui/src/index.js
- packages/material-ui/src/styles/components.d.ts
Solve https://github.com/mui-org/material-ui/pull/22651#issuecomment-707640283
> [theme] Add missing types for theme overrides

- docs/src/pages/components/slider-styled/ContinuousSlider.js
- docs/src/pages/components/slider-styled/ContinuousSlider.tsx
- docs/src/pages/components/slider/ContinuousSlider.js
- docs/src/pages/components/slider/ContinuousSlider.tsx
> [docs] Fix vertical alignment of Slider demo

- packages/material-ui/src/SpeedDial/SpeedDial.test.js
- Migrated Speed Dial to use React Testing Library.
Relates to #22911
> [test] Migrate SpeedDial to react-testing-library

- packages/material-ui/src/CardActionArea/CardActionArea.js
Closes https://github.com/mui-org/material-ui/issues/23061
> [Card] Fix action area hover style on touch devices

- docs/src/pages/discover-more/related-projects/related-projects.md
> [docs] Add react-admin in related projects page

- docs/src/pages/components/links/Links.js
- docs/src/pages/components/links/Links.tsx
- docs/src/pages/components/links/UnderlineLink.js
- docs/src/pages/components/links/UnderlineLink.tsx
- docs/src/pages/components/links/links.md
Add a demo for the link underline property.
> [docs] Add demo for Link underline

- examples/nextjs/package.json
- examples/nextjs/pages/_app.js
- examples/nextjs/pages/_document.js
- examples/nextjs/pages/about.js
- examples/nextjs/pages/index.js
Everything worked without needing to do any updates in the project (except the dependencies). Development mode works as expected, and the production build works with both enable and disabled Javascript.
> [examples] Updated nextjs example projec to use @material-ui/* next

- packages/material-ui/src/CardHeader/CardHeader.test.js
- packages/material-ui/src/ListItemText/ListItemText.test.js
- packages/material-ui/src/SpeedDialAction/SpeedDialAction.test.js
Noticed during local experiments which failed. Still worthwhile to get this in.
> [test] Move some work out of evaluation phase

- docs/src/pages/components/autocomplete/autocomplete.md
Update Autocomplete component documentation for Issue
Closes #22443
> [Autocomplete] Improve the documentation on autocomplete/autofill

- yarn.lock
Using
- https://github.com/babel/babel/releases/tag/v7.12.0
- https://github.com/babel/babel/releases/tag/v7.12.1
- https://github.com/babel/babel/releases/tag/v7.12.2
- https://github.com/babel/babel/releases/tag/v7.12.3
> Bump @babel/* to 7.12.3

- examples/nextjs-with-typescript/package.json
- examples/nextjs-with-typescript/pages/_app.tsx
- examples/nextjs-with-typescript/pages/_document.tsx
- examples/nextjs-with-typescript/pages/about.tsx
- examples/nextjs-with-typescript/pages/index.tsx
> [examples] Updated nextjs-typescript example to use @material-ui/core@next

- examples/cdn/index.html
- examples/cdn/package.json
> [examples] Update cdn example to use @material-ui/core@next

- docs/src/pages/components/steppers/steppers.md
- [*] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui-org/material-ui/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).
IT ⇾ It
> [docs] Fix typo in steppers

- docs/src/pages/guides/interoperability/interoperability.md
This PR fixes a small typo I've noticed while reading the docs.
> [docs] Fix typo on interoperability page

- docs/src/pages/guides/localization/localization.md
- packages/material-ui/src/locale/index.ts
Please let me know if I need to fix any issue or anything. Thanks!
> [l10n] Add Kazakh (kz-KZ) locale

- packages/material-ui/src/Rating/Rating.js
> [Rating] Ensure hover and click are in sync

- docs/src/pages/components/cards/ActionAreaCard.js
- docs/src/pages/components/cards/ActionAreaCard.tsx
- docs/src/pages/components/cards/ImgMediaCard.js
- docs/src/pages/components/cards/ImgMediaCard.tsx
- docs/src/pages/components/cards/MediaCard.js
- docs/src/pages/components/cards/MediaCard.tsx
- docs/src/pages/components/cards/MultiActionAreaCard.js
- docs/src/pages/components/cards/MultiActionAreaCard.tsx
- docs/src/pages/components/cards/cards.md
fixes #23085
My documentation writing skills could use a lot of improvement so please let me know whether there's anything you'd change :)
> [docs] Better document CardActionArea

- CONTRIBUTING.md
> [docs] Fix a few typos and add comma

- docs/src/pages/guides/composition/composition.md
added a list of components with the component prop to the composition.md file 
at /docs/src/pages/guides/composition/composition.md
Issue  #22001
> [docs] Make it clearer that custom router is supported

- packages/material-ui/src/LinearProgress/LinearProgress.js
Fixed https://github.com/mui-org/material-ui/issues/23204
> [LinearProgress] Fix Safari's bug during composition of different paint

- README.md
> [docs] Fix typo in `README.md`

- docs/src/pages/guides/migration-v4/migration-v4.md
- packages/material-ui/src/AppBar/AppBar.js
- [AppBar] Remove z-index when position static and relative
---
Closes #17842
> [AppBar] Remove z-index when position="static" 

- docs/src/pages/landing/Quotes.js
> [docs] Update homepage quotes

- test/cli.js
1. fix "yarn enoent" in windows
1. throw when no files matches
1. Fix gitignore not working on windows
> [test] Fix various issues with the new cli on windows

- docs/src/pages/customization/transitions/transitions.md
> [docs] Mention delay instead of transition twice

- packages/material-ui/src/Box/styleFunction.js
- packages/material-ui/src/Box/styleFunction.test.js
Fixes https://github.com/mui-org/material-ui/issues/16528 
Changes are taken from https://github.com/mui-org/material-ui/pull/17995
> [system] Merge breakpoints in correct order

- packages/material-ui/src/Tooltip/Tooltip.js
- packages/material-ui/src/Tooltip/Tooltip.test.js
- [ x ] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui-org/material-ui/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).
Closes #23450
> [Tooltip] Unexpected behaviour onOpen/onClose

- docs/src/pages/discover-more/roadmap/roadmap.md
| Name                       | Status |
| :------------------------- | ------ |
| Big Calendar               | ⏳⭐️     |
| Carousel                   | ⏳      |
| Charts                     | ⏳⭐️     |
| Color Picker               | ⏳⭐️     |
| Date Picker                | 🧪      |
| Date Range Picker          | 🧪⭐     |
| Dropdown                   | ⏳      |
| Dropzone                   | ⏳      |
| File Upload                | ⏳      |
| Gantt Chart                | ⏳⭐️     |
| Gauge                      | ⏳⭐️     |
| Image                      | ⏳      |
| Masonry                    | ⏳⭐️     |
| Navbar                     | ⏳      |
| NProgress                  | ⏳      |
| Nested Menu                | 🛠      |
| Numeric Input              | ⏳      |
| Pivot Grid                 | …
> [docs] Update new components in the roadmap

- scripts/sizeSnapshot/webpack.config.js
Size tracking for individual components got lost in #23382
> [core] Fix tracked component size regression

- docs/src/pages/system/typography/Variant.js
- docs/src/pages/system/typography/Variant.tsx
- docs/src/pages/system/typography/typography.md
> [docs] Add docs for typography in system

- packages/material-ui/src/CircularProgress/CircularProgress.d.ts
- packages/material-ui/src/CircularProgress/CircularProgress.js
- packages/material-ui/src/CircularProgress/CircularProgress.test.js
- packages/material-ui/src/LinearProgress/LinearProgress.d.ts
- packages/material-ui/src/LinearProgress/LinearProgress.js
- packages/material-ui/src/LinearProgress/LinearProgress.test.js
> [CircularProgress][LinearProgress] Change components from div to span

- docs/pages/guides/pickers-migration.js
- docs/src/pages.ts
- docs/src/pages/guides/pickers-migration/pickers-migration.md
- docs/translations/translations.json
> [docs] Create pickers migration guide

- docs/src/pages/guides/pickers-migration/pickers-migration.md
https://github.com/mui-org/material-ui-pickers/releases lists some of the breaking changes that were done. However, there are many that we will likely break again, so I think that it will be simpler to have this list based on the *pain*. In this case, I have faced the pain in https://github.com/mui-org/material-ui-pickers/issues/2159 for something that is common, so I document it. I hope other developers will do the same.
> [DatePicker] Found one prop that was renamed

- benchmark/browser/README.md
- benchmark/browser/scenarios/box-chakra-ui/index.js
- benchmark/package.json
- yarn.lock
Solve the following warnings when installing the dependencies:
> [benchmark] Update dependencies with latest

- docs/pages/api-docs/timeline-item.md
- packages/material-ui-lab/src/TimelineItem/TimelineItem.d.ts
- packages/material-ui-lab/src/TimelineItem/TimelineItem.js
> [docs] Improve classes descriptions

- packages/material-ui-system/src/index.d.ts
- packages/material-ui-system/src/index.spec.tsx
Closes https://github.com/mui-org/material-ui/issues/16379
> [system] Fix transform return value to support CSSObject

- docs/pages/performance/system.js
- packages/material-ui-system/src/compose.js
- packages/material-ui/src/styles/experimentalStyled.js
Skip runtime computation when possible
> [styles] Small performance gain

- packages/material-ui/src/locale/index.ts
> [l10n] Update Korean (ko-KR) locale

- README.md
- docs/src/pages/discover-more/backers/backers.md
- docs/src/pages/landing/backers.md
Minor issue I found when experimenting with axe-core.
> [docs] Fix link name for canadacasino

- packages/material-ui/package.json
- packages/material-ui/tsconfig.build.json
1. Fix https://github.com/mui-org/material-ui/pull/23793#issuecomment-736795457
1. Revert all the changes to the tsconfig properties done in 41d6a360e0fb245dd74549445539c6218a9dc737.
> [core] Fully clear composite TypeScript project state

- CONTRIBUTING.md
> [CONTRIBUTING] Document using codesandbox-ci

- examples/create-react-app-with-styled-components/README.md
> [examples] Fix installation instructions

- docs/src/pages/guides/localization/Locales.js
- docs/src/pages/guides/localization/Locales.tsx
> [docs] Make stable width of localization example 

- docs/src/pages/components/tables/StickyHeadTable.js
- docs/src/pages/components/tables/StickyHeadTable.tsx
> [docs] Fix StickyHeaderTable round borders

- docs/src/pages/system/basics/BreakpointsAsObject.js
- docs/src/pages/system/basics/BreakpointsAsObject.tsx
- docs/src/pages/system/basics/basics.md
> [docs] Fix breakpoints typos

- test/tsconfig.json
Enables IntelliSense in regression tests.
> [test] Include type path mappings in language server

- vercel.json
1. moved environment variables to settings
Allows more features and is recommended.
Once we fully switched we can re-introduce them into source-control
1. prevent comments from vercel on individual deployed commits
Didn't need it in netlify
1. ~Build all locales anytime~ Building like netlify for now
~Negligible gain and prevents integration issues like https://github.com/mui-org/material-ui/pull/23581~
> [docs] Add Vercel deploy config

- docs/src/pages/components/date-time-picker/date-time-picker.md
> [docs] Fix typo in date picker dayjs adapter name

- docs/translations/api-docs/select/select.json
- packages/material-ui/src/Select/Select.d.ts
- packages/material-ui/src/Select/Select.js
> [Select] Fix description, value is not required

- docs/src/pages/components/badges/BadgeAlignment.js
- docs/src/pages/components/badges/BadgeMax.js
- docs/src/pages/components/badges/BadgeMax.tsx
- docs/src/pages/components/badges/BadgeOverlap.js
- docs/src/pages/components/badges/BadgeOverlap.tsx
- docs/src/pages/components/badges/BadgeVisibility.js
- docs/src/pages/components/badges/BadgeVisibility.tsx
- docs/src/pages/components/badges/DotBadge.js
- docs/src/pages/components/badges/DotBadge.tsx
- docs/src/pages/components/badges/ShowZeroBadge.js
- docs/src/pages/components/badges/ShowZeroBadge.tsx
- docs/src/pages/components/badges/SimpleBadge.js
- docs/src/pages/components/badges/SimpleBadge.tsx
> [docs] Update Badge examples to use Box instead of makeStyles

- docs/src/pages/components/text-fields/TextFieldHiddenLabel.js
- docs/src/pages/components/text-fields/TextFieldHiddenLabel.tsx
- docs/src/pages/components/text-fields/text-fields.md
> [TextField] Add documentation for hidden label

- docs/src/pages/components/grid/NestedGrid.js
- docs/src/pages/components/grid/NestedGrid.tsx
- docs/src/pages/components/grid/grid.md
The issue was already provided with a solution, but no one was willing to make a pull request.
Fix #23598
> [Grid] Improve support for nested grid

- packages/material-ui/src/InputBase/InputBase.js
> [TextField] Fix the color leak of the textbox

- docs/src/pages/system/basics/Demo.js
- docs/src/pages/system/basics/Demo.tsx
- docs/src/pages/system/basics/Why.js
- docs/src/pages/system/basics/Why.tsx
- docs/src/pages/system/basics/basics.md
We forgot to update these occurrences in #23635.
> [docs] Prefer system shorthands

- packages/material-ui/src/SwipeableDrawer/SwipeableDrawer.js
Some of the variable names are no longer accurate. Updated them to avoid future confusion which slowed down work significantly during #23906
> [SwipeableDrawer] Refactor internals

- packages/material-ui-envinfo/package.json
- packages/material-ui-envinfo/scripts/build.js
Resolves https://github.com/mui-org/material-ui/pull/23886#discussion_r541937297
> [core] Add macOS support to envinfo build script

- .circleci/config.yml
- scripts/react-next.diff
Just updating the patch so that it can be applied. No actual changes.
>  [test] Update react next patch

- docs/src/modules/components/AppSettingsDrawer.js
- docs/src/pages/customization/color/ColorDemo.js
- docs/src/pages/customization/color/ColorTool.js
https://github.com/mui-org/material-ui/pull/23926#issuecomment-743247559
Before
After
> [docs] Improve color demo snippet spacing

- docs/src/pages/guides/interoperability/interoperability.md
- docs/src/pages/guides/migration-v4/migration-v4.md
This PR updates the interoperability guide and migration regarding the instruction on the CSS injection.
> [docs] Update the CSS injection guide

- docs/translations/api-docs/collapse/collapse.json
- packages/material-ui/src/Collapse/Collapse.d.ts
- packages/material-ui/src/Collapse/Collapse.js
> [docs] Fix collapse API docs description of 'hidden' style condition

- docs/pages/api-docs/collapse.md
- packages/material-ui/src/Collapse/Collapse.d.ts
- packages/material-ui/src/Collapse/Collapse.js
- packages/material-ui/src/Collapse/Collapse.test.js
> [Collapse] Deprecate classes.container

- packages/material-ui-system/src/index.d.ts
- packages/material-ui/src/Box/Box.spec.tsx
Closes https://github.com/mui-org/material-ui/issues/24076
> [system] Fix sx prop typings to support grid gap props

- docs/pages/api-docs/fab.md
- framer/Material-UI.framerfx/code/Fab.tsx
- packages/material-ui/src/Fab/Fab.d.ts
- packages/material-ui/src/Fab/Fab.js
> [Fab] Deprecate variant="round"

- packages/material-ui-styles/src/propsToClassKey/propsToClassKey.js
- packages/material-ui-styles/src/propsToClassKey/propsToClassKey.test.js
Added fix for supporting non string props in the generation of the key.
> [styles] Fix for supporting non string props

- docs/src/pages/components/typography/typography.md
Quick update to the documentation since Fontsource has migrated over to [scoped packages](https://github.com/fontsource/fontsource/blob/master/CHANGELOG.md#40x).
Cheers.
> [docs] Update Fontsource install instructions

- docs/src/modules/components/AppNavDrawer.js
- docs/src/pages/components/drawers/drawers-de.md
- docs/src/pages/components/drawers/drawers-es.md
- docs/src/pages/components/drawers/drawers-fr.md
- docs/src/pages/components/drawers/drawers-ja.md
- docs/src/pages/components/drawers/drawers-pt.md
- docs/src/pages/components/drawers/drawers-ru.md
- docs/src/pages/components/drawers/drawers-zh.md
- docs/src/pages/components/drawers/drawers.md
> [docs] Replace process.browser with typeof navigator

- CHANGELOG.md
> [CHANGELOG] Prepare v5.0.0-alpha.21

- CHANGELOG.md
> [CHANGELOG] Update v5.0.0-alpha.21 

- docs/pages/api-docs/autocomplete.json
- packages/material-ui/src/Autocomplete/Autocomplete.js
- packages/material-ui/src/Autocomplete/Autocomplete.test.js
> [Autocomplete] Warn when value is invalid

- docs/src/modules/utils/helpers.js
> [docs] Fix codesandbox datagrid demo

- packages/material-ui-unstyled/src/BadgeUnstyled/badgeUnstyledClasses.d.ts
- packages/material-ui-unstyled/src/SliderUnstyled/sliderUnstyledClasses.d.ts
- packages/material-ui-unstyled/src/generateUtilityClasses/generateUtilityClasses.d.ts
- packages/material-ui/src/Avatar/Avatar.js
- packages/material-ui/src/Avatar/avatarClasses.d.ts
- packages/material-ui/src/Button/Button.js
- packages/material-ui/src/Button/buttonClasses.d.ts
- packages/material-ui/src/ButtonBase/ButtonBase.js
- packages/material-ui/src/ButtonBase/buttonBaseClasses.d.ts
- packages/material-ui/src/ButtonBase/buttonBaseClasses.js
- packages/material-ui/src/ButtonBase/touchRippleClasses.d.ts
- packages/material-ui/src/ButtonBase/touchRippleClasses.js
- packages/material-ui/src/Typography/Typography.js
Found and extracted from #24227.
> [styles] Improve the classes structure

- packages/material-ui-unstyled/src/BadgeUnstyled/BadgeUnstyled.js
- packages/material-ui-unstyled/src/SliderUnstyled/SliderUnstyled.js
- packages/material-ui/src/Avatar/Avatar.js
- packages/material-ui/src/Badge/Badge.js
- packages/material-ui/src/Button/Button.js
- packages/material-ui/src/ButtonBase/ButtonBase.js
This comment https://github.com/mui-org/material-ui/pull/24227#discussion_r550972499 made me realize we have more bugs like this.
> [styles] Fix classes logic

- packages/material-ui/src/PaginationItem/PaginationItem.js
> [Pagination] Fix className forwarding when type is ellipsis

- CHANGELOG.md
> [docs] Document emotion migration breaking changes

- packages/material-ui/src/styles/experimentalStyled.d.ts
Should've been included in #24192
> [styled] Remove unused type parameters from StyledOptions

- CHANGELOG.md
> [CHANGELOG] Prepare v5.0.0-alpha.22

- packages/material-ui/src/Container/Container.js
> [Container] Fix disableGutters style not applied

- CONTRIBUTING.md
> [docs] Update CONTRIBUTING being accepted

- packages/material-ui-lab/src/MonthPicker/MonthPicker.test.tsx
- packages/material-ui-lab/src/MonthPicker/PickersMonth.tsx
> [DatePicker] Fix out of range month selection

- docs/src/pages/components/buttons/IconLabelButtons.js
- docs/src/pages/components/buttons/IconLabelButtons.tsx
- docs/src/pages/components/buttons/buttons.md
- test/regressions/tests/Button/IconLabelButtons.js
> [docs] Simplify icon button docs

- docs/src/modules/branding/BrandingFooter.tsx
- docs/src/modules/branding/BrandingNewsletter.tsx
- docs/src/modules/components/AdCarbon.js
https://deploy-preview-24322--material-ui.netlify.app/branding/about/
Steps:
1.
2.
3.
4.
> [website] Add newsletter

- packages/material-ui/src/SwipeableDrawer/SwipeableDrawer.js
- packages/material-ui/src/SwipeableDrawer/SwipeableDrawer.test.js
Fix suggested by @oliviertassinari for the issue
Closes #24031
> [SwipeableDrawer] Fix overflow scroll computation logic

- docs/src/pages/guides/right-to-left/right-to-left.md
> [docs] Update right to left compatibility plugin version

- .github/workflows/issue-mark-duplicate.yml
ref: https://github.com/mui-org/material-ui/pull/24311#issuecomment-758031798
> [core] Update issues helper version

- docs/src/modules/branding/BrandingFooter.tsx
- docs/src/modules/branding/BrandingNewsletter.tsx
- docs/src/modules/branding/BrandingRoot.tsx
I have noticed this looking closer at the value used in the Sketch file.
> [website] Improve typography theme

- .circleci/config.yml
- scripts/use-typescript-dist-tag.js
Helps confirming claims made in https://github.com/mui-org/material-ui/issues/24112#issuecomment-758219070
Confirmed https://github.com/mui-org/material-ui/issues/24112#issuecomment-758219070: https://app.circleci.com/pipelines/github/mui-org/material-ui/34050/workflows/861b9ce6-4157-442d-925c-e09f67a21790/jobs/213656/parallel-runs/0/steps/0-110
> [test] Test declaration files in TS nightly

- packages/material-ui-lab/src/DateRangePicker/makeDateRangePicker.tsx
- packages/material-ui-lab/src/internal/pickers/Picker/makePickerWithState.tsx
- packages/material-ui/src/styles/index.d.ts
- packages/material-ui/src/styles/index.js
- packages/material-ui/src/styles/useThemeProps.d.ts
- packages/material-ui/src/styles/useThemeProps.spec.ts
Closes https://github.com/mui-org/material-ui/issues/24307
> [styles] Define useThemeProps as unstable and fix TS issues

- packages/material-ui/src/locale/index.ts
> [l10n] Improve German translation

- README.md
- docs/src/pages/system/basics/basics.md
- packages/material-ui-icons/package.json
- packages/material-ui-lab/package.json
- packages/material-ui-styled-engine-sc/package.json
- packages/material-ui-styled-engine/package.json
- packages/material-ui-system/package.json
- packages/material-ui-types/package.json
- packages/material-ui-unstyled/package.json
- packages/material-ui-utils/package.json
- packages/material-ui/package.json
A continuation of https://github.com/mui-org/material-ui/pull/24224#commitcomment-45599092
https://www.npmjs.com/search?q=material-ui
> [docs] Improve packages description

- packages/material-ui/src/ButtonBase/TouchRipple.js
- packages/material-ui/src/styles/experimentalStyled.js
- test/utils/describeConformance.js
- test/utils/describeConformanceV5.js
Closes https://github.com/mui-org/material-ui/issues/24373
> [core] Do not forward classes prop by default in experimentalStyled

- docs/src/pages/components/steppers/VerticalLinearStepper.js
- docs/src/pages/components/steppers/VerticalLinearStepper.tsx
> [docs] Fix label bug in stepper vertical demo

- docs/pages/api-docs/avatar-group.json
- docs/translations/api-docs/avatar-group/avatar-group.json
- packages/material-ui/src/AvatarGroup/AvatarGroup.d.ts
- packages/material-ui/src/AvatarGroup/AvatarGroup.js
- packages/material-ui/src/AvatarGroup/AvatarGroup.test.js
- packages/material-ui/src/AvatarGroup/avatarGroupClasses.d.ts
- packages/material-ui/src/AvatarGroup/avatarGroupClasses.js
- packages/material-ui/src/AvatarGroup/index.d.ts
- packages/material-ui/src/AvatarGroup/index.js
> [Avatar] Migrate AvatarGroup to emotion

- packages/material-ui/src/AvatarGroup/AvatarGroup.test.js
Fixed regression after https://github.com/mui-org/material-ui/pull/24506
> [test] Fix AvatarGroup failing test

- packages/material-ui/src/NativeSelect/NativeSelect.js
i have added the comment to explain the padding added and followed the instructions, thank you for this create Matrial-ui
please check my pull request on issue #24453
@oliviertassinari 
Closes #24453
> [docs] Add comment explaining specificity bump on Select

- packages/material-ui/src/ButtonBase/ButtonBase.js
- packages/material-ui/src/styles/createMuiTheme.js
> [core] Improve pseudo classes overrides error

- docs/pages/branding/about.tsx
- docs/src/modules/branding/BrandingBeginToday.tsx
- docs/src/modules/branding/BrandingCard.tsx
- docs/src/modules/branding/BrandingDiscoverMore.tsx
- docs/src/modules/branding/BrandingFooter.tsx
- docs/src/modules/branding/BrandingLogo.tsx
- docs/src/modules/branding/BrandingPersona.tsx
https://deploy-preview-24553--material-ui.netlify.app/branding/about/
> [website] Team

- docs/pages/api-docs/card.json
- docs/translations/api-docs/card/card.json
- packages/material-ui/src/Card/Card.d.ts
- packages/material-ui/src/Card/Card.js
- packages/material-ui/src/Card/Card.test.js
- packages/material-ui/src/Card/cardClasses.d.ts
- packages/material-ui/src/Card/cardClasses.js
- packages/material-ui/src/Card/index.d.ts
- packages/material-ui/src/Card/index.js
> [Card] Migrate to emotion

- docs/src/pages/components/text-fields/InputAdornments.js
- docs/src/pages/components/text-fields/InputAdornments.tsx
- packages/material-ui/src/OutlinedInput/NotchedOutline.js
- packages/material-ui/src/OutlinedInput/NotchedOutline.test.js
A quick follow-up after #24563, prepare the breaking change: #22799.
> [TextField] Prepare removal of labelWidth prop

- docs/pages/api-docs/table.json
- docs/translations/api-docs/table/table.json
- packages/material-ui/src/Table/Table.d.ts
- packages/material-ui/src/Table/Table.js
- packages/material-ui/src/Table/Table.test.js
- packages/material-ui/src/Table/index.d.ts
- packages/material-ui/src/Table/index.js
- packages/material-ui/src/Table/tableClasses.d.ts
- packages/material-ui/src/Table/tableClasses.js
> [Table] Migrate to emotion

- docs/pages/api-docs/table-container.json
- docs/translations/api-docs/table-container/table-container.json
- packages/material-ui/src/TableContainer/TableContainer.d.ts
- packages/material-ui/src/TableContainer/TableContainer.js
- packages/material-ui/src/TableContainer/TableContainer.test.js
- packages/material-ui/src/TableContainer/index.d.ts
- packages/material-ui/src/TableContainer/index.js
- packages/material-ui/src/TableContainer/tableContainerClasses.d.ts
- packages/material-ui/src/TableContainer/tableContainerClasses.js
> [Table] Migrate TableContainer to emotion

- docs/src/pages/guides/migration-v4/migration-v4.md
Correct import path change missed in #23974
Simplify the example
> [docs] Update Typography in migration guide

- docs/pages/api-docs/dialog-content.json
- docs/translations/api-docs/dialog-content/dialog-content.json
- packages/material-ui/src/DialogContent/DialogContent.d.ts
- packages/material-ui/src/DialogContent/DialogContent.js
- packages/material-ui/src/DialogContent/DialogContent.test.js
- packages/material-ui/src/DialogContent/dialogContentClasses.d.ts
- packages/material-ui/src/DialogContent/dialogContentClasses.js
- packages/material-ui/src/DialogContent/index.d.ts
- packages/material-ui/src/DialogContent/index.js
> [Dialog] Migrate DialogContent to emotion

- test/utils/describeConformanceV5.js
> [test] Conformance to handle wrapped elements

- packages/material-ui/src/Link/Link.js
> [Link] Fix CSS prefix property casing with emotion

- docs/src/pages/getting-started/templates/dashboard/Chart.js
- docs/src/pages/getting-started/templates/dashboard/Chart.tsx
I have seen https://www.argos-ci.com/mui-org/material-ui/builds/7475 a couple of times. Hope it will solve it once for all.
> [test] Avoid visual flakiness

- packages/material-ui/src/OverridableComponent.d.ts
Addresses a checklist item from the breaking changes section in #20012.
> [core] Remove deprecated SimplifiedPropsOf/Simplify types

- docs/src/pages/components/css-baseline/css-baseline.md
https://github.com/mui-org/material-ui/blob/next/packages/material-ui/src/CssBaseline/CssBaseline.js#L26
> [docs] Fix CssBaseline typography description

- docs/pages/api-docs/table-row.json
- docs/translations/api-docs/table-row/table-row.json
- packages/material-ui/src/TableRow/TableRow.d.ts
- packages/material-ui/src/TableRow/TableRow.js
- packages/material-ui/src/TableRow/TableRow.test.js
- packages/material-ui/src/TableRow/index.d.ts
- packages/material-ui/src/TableRow/index.js
- packages/material-ui/src/TableRow/tableRowClasses.d.ts
- packages/material-ui/src/TableRow/tableRowClasses.js
- packages/material-ui/test/integration/TableRow.test.js
#24405
rebase next after #24679
> [Table] Migrate TableRow to emotion

- docs/pages/api-docs/form-group.json
- docs/translations/api-docs/form-group/form-group.json
- packages/material-ui/src/FormGroup/FormGroup.d.ts
- packages/material-ui/src/FormGroup/FormGroup.js
- packages/material-ui/src/FormGroup/FormGroup.test.js
- packages/material-ui/src/FormGroup/formGroupClasses.d.ts
- packages/material-ui/src/FormGroup/formGroupClasses.js
- packages/material-ui/src/FormGroup/index.d.ts
- packages/material-ui/src/FormGroup/index.js
> [TextField] Migrate FormGroup to emotion

- .circleci/config.yml
- docs/scripts/buildApi.ts
- package.json
- yarn.lock
Includes:
- [7.12.15](https://github.com/babel/babel/releases/tag/v7.12.15)
- [7.12.14](https://github.com/babel/babel/releases/tag/v7.12.14)
- [7.12.13](https://github.com/babel/babel/releases/tag/v7.12.13)
- [7.12.12](https://github.com/babel/babel/releases/tag/v7.12.12)
- [7.12.11](https://github.com/babel/babel/releases/tag/v7.12.11)
- [7.12.10](https://github.com/babel/babel/releases/tag/v7.12.10)
> Bump @babel/* to 7.12.15

- docs/pages/api-docs/year-picker.js
- docs/pages/api-docs/year-picker.json
- docs/src/pagesApi.js
- docs/translations/api-docs/year-picker/year-picker-de.json
- docs/translations/api-docs/year-picker/year-picker-es.json
- docs/translations/api-docs/year-picker/year-picker-fr.json
- docs/translations/api-docs/year-picker/year-picker-ja.json
- docs/translations/api-docs/year-picker/year-picker-pt.json
- docs/translations/api-docs/year-picker/year-picker-ru.json
- docs/translations/api-docs/year-picker/year-picker-zh.json
- docs/translations/api-docs/year-picker/year-picker.json
- packages/material-ui-lab/src/YearPicker/YearPicker.tsx
> [Pickers] Enable YearPicker documentation

- docs/pages/api-docs/button-group.json
- docs/translations/api-docs/button-group/button-group.json
- packages/material-ui/src/ButtonGroup/ButtonGroup.d.ts
- packages/material-ui/src/ButtonGroup/ButtonGroup.js
- packages/material-ui/src/ButtonGroup/ButtonGroup.test.js
- packages/material-ui/src/ButtonGroup/buttonGroupClasses.d.ts
- packages/material-ui/src/ButtonGroup/buttonGroupClasses.js
- packages/material-ui/src/ButtonGroup/index.d.ts
- packages/material-ui/src/ButtonGroup/index.js
> [ButtonGroup] Migrate ButtonGroup to emotion

- docs/pages/api-docs/table-head.json
- docs/translations/api-docs/table-head/table-head.json
- packages/material-ui/src/TableHead/TableHead.d.ts
- packages/material-ui/src/TableHead/TableHead.js
- packages/material-ui/src/TableHead/TableHead.test.js
- packages/material-ui/src/TableHead/index.d.ts
- packages/material-ui/src/TableHead/index.js
- packages/material-ui/src/TableHead/tableHeadClasses.d.ts
- packages/material-ui/src/TableHead/tableHeadClasses.js
#24405
rebase next after #24679
> [Table] Migrate TableHead to emotion

- docs/pages/api-docs/table-footer.json
- docs/translations/api-docs/table-footer/table-footer.json
- packages/material-ui/src/TableFooter/TableFooter.d.ts
- packages/material-ui/src/TableFooter/TableFooter.js
- packages/material-ui/src/TableFooter/TableFooter.test.js
- packages/material-ui/src/TableFooter/index.d.ts
- packages/material-ui/src/TableFooter/index.js
- packages/material-ui/src/TableFooter/tableFooterClasses.d.ts
- packages/material-ui/src/TableFooter/tableFooterClasses.js
> [Table] Migrate TableFooter to emotion

- packages/material-ui/src/Autocomplete/Autocomplete.js
One case I have forgotten in #24705.
> [core] Prefer return over throw in chainPropTypes

- test/karma.conf.js
> [core] Fix name of Safari target

- packages/material-ui/src/CircularProgress/CircularProgress.js
Leverage the same approach as with #24652.
> [CircularProgress] Make source easier to read

- yarn.lock
Includes 
- [7.12.16](https://github.com/babel/babel/releases/tag/v7.12.16)
> Bump @babel/* to 7.12.16

- .circleci/config.yml
- scripts/react-next.diff
Became outdated in https://github.com/mui-org/material-ui/pull/24873
> [test] Update react next patch

- packages/material-ui-lab/src/Autocomplete/Autocomplete.d.ts
- packages/material-ui-lab/src/useAutocomplete/index.d.ts
- packages/material-ui/src/Autocomplete/Autocomplete.d.ts
- packages/material-ui/src/Autocomplete/Autocomplete.spec.tsx
- packages/material-ui/src/useAutocomplete/useAutocomplete.d.ts
- packages/material-ui/src/useAutocomplete/useAutocomplete.spec.ts
> [Autocomplete] Fix the return type of AutocompleteGetTagProps

- .github/workflows/ci.yml
- scripts/releaseTag.js
We might not catch these bugs in our dev CI but having it run on all 3 major platforms might help in the future.
Review with whitespace changes hidden is advised.
> [core] Fix release:tag pushing to first push remote

- packages/material-ui/src/Switch/Switch.js
This PR fixes #24944. 
**Changes in light mode:**
**Changes in dark mode:**
> [Switch] Update to follow current MD guidelines

- docs/pages/company/careers.js
- docs/pages/company/lead-designer.js
- docs/src/modules/components/AppFooter.js
- docs/src/pages/company/careers/careers.md
- docs/src/pages/company/jobs/jobs.md
- docs/src/pages/company/lead-designer/lead-designer.md
- docs/src/pages/company/software-engineer/software-engineer.md
https://deploy-preview-24948--material-ui.netlify.app/company/careers/
Update the careers page to share more information about us as well as our current needs/open roles. We have 3 open positions. After that, I think that we will need to look for structuring more of the team, probably more Q3 2021 (internally or externally): product lead and tech lead.
> [website] Update Careers page

- examples/create-react-app-with-styled-components/README.md
- examples/create-react-app-with-typescript/README.md
- examples/create-react-app/README.md
- examples/gatsby-theme/README.md
- examples/gatsby/README.md
- examples/nextjs-with-typescript/README.md
- examples/nextjs/README.md
- examples/preact/README.md
- examples/ssr/README.md
> [examples] Fix code sandbox link GitHub branch

- packages/material-ui-system/src/borders.js
- packages/material-ui-system/src/grid.js
- packages/material-ui-system/src/grid.test.js
Found working on a quick POC: https://codesandbox.io/s/quizzical-visvesvaraya-blhtp?file=/src/App.js:0-701
> [system] Fix gap, rowGap, columnGap, borderRadius reponsive support

- yarn.lock
Includes:
- [7.12.18](https://github.com/babel/babel/releases/tag/v7.12.18)
- [7.12.17](https://github.com/babel/babel/releases/tag/v7.12.17)
> Bump @babel/* to 7.12.18

- docs/src/pages/company/careers/careers.md
- packages/material-ui/src/styles/createPalette.js
Change secondary text opacity as part of [#24947](https://github.com/mui-org/material-ui/issues/24947)
[PR #25046](https://github.com/mui-org/material-ui/pull/25046) addresses changes to the FilledInput
> [theme] Update theme.palette.text.secondary to match the spec

- packages/material-ui/src/Dialog/Dialog.js
- packages/material-ui/src/Drawer/Drawer.js
This is a follow-up after #24857 by @povilass.
> [core] Remove need to reinject backdrop

- docs/src/pages/components/lists/GutterlessList.js
- docs/src/pages/components/lists/GutterlessList.tsx
- docs/src/pages/components/text-fields/InputWithIcon.js
- docs/src/pages/components/text-fields/InputWithIcon.tsx
- packages/material-ui/src/InputAdornment/InputAdornment.js
- packages/material-ui/src/ListItemIcon/ListItemIcon.js
- [x ] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui-org/material-ui/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).
Closes #25000
> [TextField] Fix input adornment color

- docs/src/pages/getting-started/learn/learn.md
We updated the link to our first book that teaches Material UI, and we wrote a second book that also teaches Material UI. Thanks for reviewing!
> [docs] Improve description of builderbook

- docs/pages/api-docs/app-bar.json
- docs/pages/api-docs/circular-progress.json
- docs/pages/api-docs/linear-progress.json
- framer/Material-UI.framerfx/code/CircularProgress.tsx
- framer/Material-UI.framerfx/code/LinearProgress.tsx
- framer/scripts/framerConfig.js
- packages/material-ui/src/AppBar/AppBar.d.ts
- packages/material-ui/src/AppBar/AppBar.js
- packages/material-ui/src/CircularProgress/CircularProgress.d.ts
- packages/material-ui/src/CircularProgress/CircularProgress.js
- packages/material-ui/src/LinearProgress/LinearProgress.d.ts
- packages/material-ui/src/LinearProgress/LinearProgress.js
- packages/material-ui/test/typescript/moduleAugmentation/appBarProps.spec.tsx
- packages/material-ui/test/typescript/moduleAugmentation/appBarProps.tsconfig.json
- packages/material-ui/test/typescript/moduleAugmentation/progressProps.spec.tsx
- packages/material-ui/test/typescript/moduleAugmentation/progressProps.tsconfig.json
> [AppBar][CircularProgress][LinearProgress] Support custom colors

- packages/material-ui-utils/src/visuallyHidden.ts
> [system] Fix behavior of visuallyHidden when used with `sx` prop

- docs/pages/api-docs/step-connector.json
- docs/translations/api-docs/step-connector/step-connector.json
- packages/material-ui/src/StepConnector/StepConnector.d.ts
- packages/material-ui/src/StepConnector/StepConnector.js
- packages/material-ui/src/StepConnector/StepConnector.test.js
- packages/material-ui/src/StepConnector/index.d.ts
- packages/material-ui/src/StepConnector/index.js
- packages/material-ui/src/StepConnector/stepConnectorClasses.d.ts
- packages/material-ui/src/StepConnector/stepConnectorClasses.js
- packages/material-ui/src/Stepper/Stepper.test.js
- test/utils/describeConformanceV5.js
> [Stepper] Migrate StepConnector to emotion

- docs/pages/api-docs/linear-progress.json
- docs/translations/api-docs/linear-progress/linear-progress.json
- framer/scripts/framerConfig.js
- packages/material-ui/src/LinearProgress/LinearProgress.d.ts
- packages/material-ui/src/LinearProgress/LinearProgress.js
- packages/material-ui/src/LinearProgress/LinearProgress.test.js
- packages/material-ui/src/LinearProgress/index.d.ts
- packages/material-ui/src/LinearProgress/index.js
- packages/material-ui/src/LinearProgress/linearProgressClasses.d.ts
- packages/material-ui/src/LinearProgress/linearProgressClasses.js
> [LinearProgress] Migrate to emotion

- docs/pages/api-docs/dialog.json
- docs/translations/api-docs/dialog/dialog.json
- packages/material-ui/src/Dialog/Dialog.d.ts
- packages/material-ui/src/Dialog/Dialog.js
- packages/material-ui/src/Dialog/Dialog.test.js
- packages/material-ui/src/Dialog/dialogClasses.d.ts
- packages/material-ui/src/Dialog/dialogClasses.js
- packages/material-ui/src/Dialog/index.d.ts
- packages/material-ui/src/Dialog/index.js
> [Dialog] Migrate Dialog to emotion

- docs/src/pages/components/paper/SimplePaper.js
- docs/src/pages/components/paper/SimplePaper.tsx
- docs/src/pages/components/paper/Variants.js
- docs/src/pages/components/paper/Variants.tsx
The following demos of the Paper component were migrated:
> [docs] Migrate Paper demos to emotion

- docs/src/pages/guides/composition/Composition.js
- packages/typescript-to-proptypes/src/injector.ts
- packages/typescript-to-proptypes/test/code-order/options.ts
- packages/typescript-to-proptypes/test/propTypes-casting/input.tsx
- packages/typescript-to-proptypes/test/propTypes-casting/options.ts
- packages/typescript-to-proptypes/test/propTypes-casting/output.js
- packages/typescript-to-proptypes/test/reconcile-prop-types/options.ts
Check [`d15dbd6` (#25193)](https://github.com/mui-org/material-ui/pull/25193/commits/d15dbd695a715d68b6d4c6758f8e3b50ee349ae0) for an example.
> [ttp] Remove .propTypes when the props are empty

- packages/material-ui/src/CircularProgress/CircularProgress.js
> [CircularProgress] Fix animation when disableShrink={true}

- docs/pages/api-docs/step-icon.json
- docs/translations/api-docs/step-icon/step-icon.json
- packages/material-ui/src/StepIcon/StepIcon.d.ts
- packages/material-ui/src/StepIcon/StepIcon.js
- packages/material-ui/src/StepIcon/StepIcon.test.js
- packages/material-ui/src/StepIcon/index.d.ts
- packages/material-ui/src/StepIcon/index.js
- packages/material-ui/src/StepIcon/stepIconClasses.d.ts
- packages/material-ui/src/StepIcon/stepIconClasses.js
- packages/material-ui/src/StepLabel/StepLabel.test.js
> [Stepper] Migrate StepIcon to emotion

- docs/src/pages.js
This is a follow up on this PR https://github.com/mui-org/material-ui-x/pull/1147
> [docs] Add the new demo page

- test/utils/describeConformance.js
1. Clearer assertion errors if a test fails
2. Fix some typings (deferred migration to TS for now due to time constraints)
> [test] Minor improvements to `describeConformance`

- docs/src/pages/components/toggle-button/ToggleButtonNotEmpty.js
- docs/src/pages/components/toggle-button/ToggleButtonNotEmpty.tsx
The following demos of the Toggle Button component were migrated:
> [docs] Migrate Toggle Button to emotion

- docs/pages/api-docs/text-field.json
- docs/translations/api-docs/text-field/text-field.json
- framer/Material-UI.framerfx/code/TextField.tsx
- framer/scripts/framerConfig.js
- packages/material-ui/src/TextField/TextField.d.ts
- packages/material-ui/src/TextField/TextField.js
- packages/material-ui/src/TextField/TextField.test.js
- packages/material-ui/src/TextField/index.js
- packages/material-ui/src/TextField/textFieldClasses.d.ts
- packages/material-ui/src/TextField/textFieldClasses.js
> [TextField] Migrate to emotion

- docs/pages/api-docs/menu.json
- docs/translations/api-docs/menu/menu.json
- packages/material-ui/src/Menu/Menu.d.ts
- packages/material-ui/src/Menu/Menu.js
- packages/material-ui/src/Menu/Menu.test.js
- packages/material-ui/src/Menu/index.d.ts
- packages/material-ui/src/Menu/menuClasses.js
- packages/material-ui/src/Modal/Modal.test.js
- packages/material-ui/src/Popover/Popover.test.js
A continuation of #25264 with improvements
> [Menu] Migrate to emotion, polish

- docs/next.config.js
- docs/src/modules/components/ApiPage.js
- docs/src/modules/components/AppFrame.js
- docs/src/modules/components/EditPage.js
- docs/src/modules/components/MarkdownDocs.js
- docs/src/modules/constants.js
- docs/src/modules/utils/helpers.js
- docs/src/modules/utils/helpers.test.js
This changes behavior when people use the components in webpack 4 without setting the environment variables. However, I do believe this would be a mistake anyway. In webpack 5 it'll throw anyway.
> [docs] Consolidate environment variables into next.config

- docs/src/pages/guides/migration-v4/migration-v4.md
little typo
- [ x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui-org/material-ui/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).
> [doc] Fix typo in migration-v4.md

- packages/material-ui/src/NativeSelect/NativeSelect.js
> [Select] Fix focus background when variant="outlined"

- docs/src/pages/components/icons/icons.md
- docs/src/pages/components/material-icons/material-icons.md
- docs/src/pages/getting-started/installation/installation.md
- packages/material-ui-icons/README.md
New version of PR https://github.com/mui-org/material-ui/pull/25408 now pointing towards next
> [docs] Update icon link to fonts.google.com

- docs/pages/api-docs/button-group.json
- packages/material-ui/src/ButtonGroup/ButtonGroup.d.ts
- packages/material-ui/src/ButtonGroup/ButtonGroup.js
> [ButtonGroup] Support custom colors

- packages/material-ui/src/InputBase/InputBase.js
- packages/material-ui/src/OutlinedInput/OutlinedInput.js
- test/regressions/tests/TextField/MultilineTextField.js
> [TextField] Size small for multiline

- docs/src/modules/components/DemoSandboxed.js
- docs/src/pages/components/drawers/ResponsiveDrawer.js
- docs/src/pages/components/drawers/ResponsiveDrawer.tsx
- packages/material-ui/src/Drawer/Drawer.js
This PR is aiming to fix: #25217 
Implement proposed changes by @oliviertassinari 
Many thanks for the suggestion!
> [Drawer] Fix RTL support

- docs/package.json
- docs/src/modules/components/AppNavDrawerItem.js
- docs/src/modules/components/DemoSandboxed.js
- docs/src/modules/utils/StyledEngineProvider.js
- yarn.lock
This PR is aiming to fix: #25336
Add proposed solution by @oliviertassinari 
This is the follow up PR of the previous #25453
> [docs] Support RTL with styled components

- docs/pages/api-docs/snackbar.json
- docs/src/modules/utils/generatePropTypeDescription.ts
- packages/material-ui/src/Snackbar/Snackbar.js
- packages/typescript-to-proptypes/src/generator.ts
- packages/typescript-to-proptypes/test/injector/should-include-filename-based/output.js
> [Snackbar] Fix prop type error for 'key' prop

- docs/src/pages/components/dividers/VerticalDividerMiddle.js
- docs/src/pages/components/dividers/VerticalDividerMiddle.tsx
- docs/src/pages/components/dividers/VerticalDividers.js
- docs/src/pages/components/dividers/VerticalDividers.tsx
- docs/src/pages/components/dividers/dividers.md
- packages/material-ui/src/Divider/Divider.js
- packages/material-ui/src/Divider/Divider.test.js
> [Divider] Support middle variant with vertical orientation

- packages/material-ui/src/Stack/Stack.js
- packages/material-ui/src/Stack/Stack.test.js
Sorry for not looking through your contributing guide just yet - this is just something I've noticed while looking at your implementation and changed this directly from GitHub interface.
I'd like to first validate if this is the correct change and if yes then I will do all the chores to make this mergeable later.
cc @souporserious
> [Stack] Fix the :not selector

- docs/public/_redirects
> [core] Update the codesandbox issue templates

- docs/src/pages/components/click-away-listener/ClickAway.js
- docs/src/pages/components/click-away-listener/ClickAway.tsx
- docs/src/pages/components/click-away-listener/LeadingClickAway.js
- docs/src/pages/components/click-away-listener/LeadingClickAway.tsx
- docs/src/pages/components/click-away-listener/PortalClickAway.js
- docs/src/pages/components/click-away-listener/PortalClickAway.tsx
> [docs] Migrate ClickAwayListener demos to emotion

- docs/src/pages/premium-themes/onepirate/modules/form/FormButton.js
- packages/typescript-to-proptypes/package.json
- packages/typescript-to-proptypes/src/parser.ts
- scripts/generateProptypes.ts
- yarn.lock
10month old backlog resolved: https://stackoverflow.com/questions/61933695/typescript-compiler-api-get-get-type-of-mapped-property
> [core] Use latest TypeScript in typescript-to-proptypes

- docs/pages/api-docs/stack.json
- docs/translations/api-docs/stack/stack.json
- packages/material-ui/src/Stack/Stack.js
This pull request aims to fix: #25492
> [Stack] Add component prop

- docs/pages/api-docs/dialog.json
- docs/src/pages/components/modal/ServerModal.js
- docs/src/pages/components/modal/ServerModal.tsx
- docs/translations/api-docs/dialog/dialog.json
- packages/material-ui/src/Backdrop/Backdrop.js
- packages/material-ui/src/Dialog/Dialog.js
- packages/material-ui/src/Modal/Modal.js
This pull request aims to deliver a fix #25519
I have used the proposed solution of @oliviertassinari
> [Backdrop] Remove z-index: -1

- docs/pages/api-docs/stepper.json
- docs/translations/api-docs/stepper/stepper.json
- packages/material-ui/src/Stepper/Stepper.d.ts
- packages/material-ui/src/Stepper/Stepper.js
- packages/material-ui/src/Stepper/Stepper.test.js
- packages/material-ui/src/Stepper/index.d.ts
- packages/material-ui/src/Stepper/index.js
- packages/material-ui/src/Stepper/stepperClasses.d.ts
- packages/material-ui/src/Stepper/stepperClasses.js
> [Stepper] Migrate Stepper to emotion

- packages/material-ui/src/Autocomplete/Autocomplete.spec.tsx
This pull request aims to fix: #25502
> [Autocomplete] Fix TypeScript wrapper example

- packages/material-ui/src/Tooltip/Tooltip.js
This PR aims to fix the following Fix #25465
Thank you for the provided solution @oliviertassinari
> [Tooltip] Fix forwarded classes

- docs/src/pages/components/skeleton/SkeletonColor.js
- docs/src/pages/components/skeleton/SkeletonColor.tsx
- docs/src/pages/components/skeleton/skeleton.md
> [docs] Document changing skeleton color

- docs/src/pages/components/tables/tables.md
> [docs] Fix typo in data grid

- docs/src/pages/discover-more/roadmap/roadmap.md
> [docs] Fix spelling error in roadmap.md file

- docs/pages/api-docs/toggle-button-group.json
- docs/pages/api-docs/toggle-button.json
- docs/src/modules/components/AppSettingsDrawer.js
- docs/src/pages/components/toggle-button/ToggleButtons.js
- docs/src/pages/components/toggle-button/ToggleButtons.tsx
- docs/translations/api-docs/toggle-button-group/toggle-button-group.json
- docs/translations/api-docs/toggle-button/toggle-button.json
- packages/material-ui/src/ToggleButton/ToggleButton.d.ts
- packages/material-ui/src/ToggleButton/ToggleButton.js
- packages/material-ui/src/ToggleButtonGroup/ToggleButtonGroup.d.ts
- packages/material-ui/src/ToggleButtonGroup/ToggleButtonGroup.js
> [ToggleButton] Add fullWidth prop

- docs/pages/api-docs/pagination-item.json
- docs/translations/api-docs/pagination-item/pagination-item.json
- packages/material-ui/src/PaginationItem/PaginationItem.d.ts
- packages/material-ui/src/PaginationItem/PaginationItem.js
- packages/material-ui/src/PaginationItem/PaginationItem.test.js
- packages/material-ui/src/PaginationItem/paginationItemClasses.js
> [Pagination] Allow to differentiate more item types

- docs/src/pages/components/textarea-autosize/EmptyTextarea.js
- docs/src/pages/components/textarea-autosize/EmptyTextarea.tsx
- docs/src/pages/components/textarea-autosize/MaxHeightTextarea.js
- docs/src/pages/components/textarea-autosize/MaxHeightTextarea.tsx
- docs/src/pages/components/textarea-autosize/MinHeightTextarea.js
- docs/src/pages/components/textarea-autosize/MinHeightTextarea.tsx
- packages/material-ui/src/TextareaAutosize/TextareaAutosize.js
- packages/material-ui/src/TextareaAutosize/TextareaAutosize.test.js
> [TextareaAutosize] Fix resizing bug on Firefox

- docs/pages/api-docs/timeline-connector.json
- docs/translations/api-docs/timeline-connector/timeline-connector.json
- packages/material-ui-lab/src/TimelineConnector/TimelineConnector.d.ts
- packages/material-ui-lab/src/TimelineConnector/TimelineConnector.js
- packages/material-ui-lab/src/TimelineConnector/TimelineConnector.test.js
- packages/material-ui-lab/src/TimelineConnector/index.d.ts
- packages/material-ui-lab/src/TimelineConnector/index.js
- packages/material-ui-lab/src/TimelineConnector/timelineConnectorClasses.d.ts
- packages/material-ui-lab/src/TimelineConnector/timelineConnectorClasses.js
> [Timeline] Migrate TimelineConnector to emotion

- docs/src/modules/components/AppNavDrawer.js
My bad. I have review #25619 too quickly.
> [docs] Fix useLayoutEffect warning

- docs/src/pages/guides/migration-v4/migration-v4.md
> [docs] Fix typo in v4 migration doc

- packages/material-ui-lab/src/TimelineOppositeContent/TimelineOppositeContent.d.ts
- packages/material-ui/src/FilledInput/FilledInput.d.ts
- packages/material-ui/src/Icon/Icon.d.ts
- packages/material-ui/src/Input/Input.d.ts
- packages/material-ui/src/ListItemSecondaryAction/ListItemSecondaryAction.d.ts
- packages/material-ui/src/NativeSelect/NativeSelect.d.ts
- packages/material-ui/src/OutlinedInput/OutlinedInput.d.ts
- packages/material-ui/src/Select/Select.d.ts
- packages/material-ui/src/SpeedDialIcon/SpeedDialIcon.d.ts
- packages/material-ui/src/StepLabel/StepLabel.d.ts
- packages/material-ui/src/SvgIcon/SvgIcon.d.ts
> [typescript] Add muiName to declarations

- docs/pages/api-docs/linear-progress.json
- docs/src/pages/components/progress/LinearColor.js
- docs/src/pages/components/progress/LinearColor.tsx
- docs/src/pages/components/progress/LinearIndeterminate.js
- docs/src/pages/components/progress/LinearIndeterminate.tsx
- docs/src/pages/components/progress/progress.md
- packages/material-ui/src/LinearProgress/LinearProgress.js
- test/regressions/fixtures/LinearProgress/DeterminateLinearProgress.js
Also added Linear Color section to docs
Closes #25568
> [LinearProgress] Add color="inherit" support

- packages/material-ui/src/TextField/index.d.ts
> [TextField] Add textFieldClasses export to type declarations

- CHANGELOG.md
I knew something was off about https://github.com/mui-org/material-ui/pull/25731
> [docs] Add package headings to 5.0.0-alpha.30 changelog

- scripts/releaseChangelog.js
> [core] Document token permissions of release:changelog

- packages/material-ui-styled-engine/src/GlobalStyles/GlobalStyles.d.ts
Related to https://github.com/mui-org/material-ui/issues/25208
> [styled-engine] Improve GlobalStyles props

- packages/material-ui/src/Rating/Rating.js
- packages/material-ui/src/Rating/Rating.test.js
- test/e2e/fixtures/Rating/BasicRating.tsx
- test/e2e/index.test.ts
Fix #25533 
Preview: https://deploy-preview-25645--material-ui.netlify.app/components/rating/
> [Rating] Allow clearing ratings with arrow keys

- docs/src/pages/system/spacing/HorizontalCentering.js
- docs/src/pages/system/spacing/HorizontalCentering.tsx
- docs/src/pages/system/spacing/spacing.md
> [docs] Fix Horizontally centered demo

- docs/src/pages/components/avatars/BackgroundLetterAvatars.js
- docs/src/pages/components/avatars/BackgroundLetterAvatars.tsx
- docs/src/pages/components/avatars/avatars.md
- packages/material-ui/src/Avatar/Avatar.js
Closes #12700
Preview https://deploy-preview-25789--material-ui.netlify.app/components/avatars/#letter-avatars
> [Avatar] backgroundColor from string

- packages/material-ui/src/styles/colorManipulator.js
- packages/material-ui/src/styles/colorManipulator.test.js
> [core] Fix rgba to hex conversion

- docs/src/pages/components/buttons/buttons.md
- docs/src/pages/components/tabs/tabs.md
- docs/src/pages/guides/routing/ListRouter.js
- docs/src/pages/guides/routing/ListRouter.tsx
- docs/src/pages/guides/routing/TabRouter.js
- docs/src/pages/guides/routing/TabsRouter.js
- docs/src/pages/guides/routing/TabsRouter.tsx
- docs/src/pages/guides/routing/routing.md
Closes #18811
Preview: https://deploy-preview-25827--material-ui.netlify.app/guides/routing/#tabs
> [Tabs] Add demo for routing with Tabs

- docs/src/pages/guides/pickers-migration/pickers-migration.md
> [docs] Improve pickers migration docs from v3

- docs/src/modules/components/Ad.js
- docs/src/modules/components/AdCarbon.js
- docs/src/modules/components/AdGuest.js
- docs/src/modules/components/AdManager.js
Closes #25828. I have seen this happen multiple times in the past but could never figure out how to reliably reproduce the bug, until today.
Preview: https://deploy-preview-25831--material-ui.netlify.app/components/alert/
> [docs] Fix ad duplication

- docs/pages/api-docs/timeline-dot.json
- docs/translations/api-docs/timeline-dot/timeline-dot.json
- packages/material-ui-lab/src/TimelineDot/TimelineDot.d.ts
- packages/material-ui-lab/src/TimelineDot/TimelineDot.js
- packages/material-ui-lab/src/TimelineDot/TimelineDot.test.js
- packages/material-ui-lab/src/TimelineDot/index.d.ts
- packages/material-ui-lab/src/TimelineDot/index.js
- packages/material-ui-lab/src/TimelineDot/timelineDotClasses.d.ts
- packages/material-ui-lab/src/TimelineDot/timelineDotClasses.js
> [Timeline] Migrate TimelineDot to emotion

- docs/src/pages/components/backdrop/backdrop.md
- docs/src/pages/components/badges/badges.md
- docs/src/pages/components/modal/modal.md
- docs/src/pages/components/portal/portal.md
- docs/src/pages/components/slider/slider.md
- docs/src/pages/components/trap-focus/trap-focus.md
> [docs] Add unstyled section to all components coming with the package

- docs/src/pages/guides/localization/localization.md
- packages/material-ui/src/locale/index.ts
> [l10n] Add Bengali (bnBD) locale

- docs/src/pages/guides/migration-v4/migration-v4.md
- packages/material-ui/src/ButtonBase/ButtonBase.d.ts
- packages/material-ui/src/ButtonBase/ButtonBase.js
Part of #20012
```diff
-<ButtonBase buttonRef={ref} />
+<ButtonBase ref={ref} />
-<Button buttonRef={ref} />
+<Button ref={ref} />
```
> [ButtonBase] Remove buttonRef prop

- packages/material-ui/src/ButtonBase/ButtonBase.js
> [ButtonBase] Add warning for buttonRef removal

- packages/material-ui/src/ClickAwayListener/ClickAwayListener.test.js
- test/utils/fireDiscreteEvent.js
Test for https://github.com/mui-org/material-ui/issues/25578
> [test] Add current behavior of inverleaving elements on mousedown

- packages/material-ui/src/Select/SelectInput.js
> [Select] Fix classes leaking on the DOM

- docs/translations/api-docs/typography/typography.json
- packages/material-ui/src/Typography/Typography.d.ts
- packages/material-ui/src/Typography/Typography.js
I was looking at the docs and that one seems to be incorrect.
> [docs] Fix Typography api docs for `paragraph` prop

- docs/src/pages/guides/typescript/typescript.md
Follow-up to https://github.com/mui-org/material-ui/pull/24795
> [docs] Update minimum required TypeScript version

- packages/material-ui/src/Stack/Stack.js
- packages/material-ui/src/Stack/Stack.test.js
> [Stack] Fix support of spacing falsy values

- docs/src/pages/components/chips/BasicChips.js
- docs/src/pages/components/chips/BasicChips.tsx
Happened to notice this when reading the <Chip /> docs page.
> [docs] Fix minor typo

- packages/material-ui-lab/src/YearPicker/YearPicker.test.tsx
Caused by merging outdated https://github.com/mui-org/material-ui/pull/25928
> [test] Remove duplicate property

- packages/material-ui/src/styles/createBreakpoints.d.ts
- packages/material-ui/src/styles/createBreakpoints.js
- packages/material-ui/src/styles/createBreakpoints.test.js
> [theme] Add warning for theme.breakpoints.width deprecation

- docs/src/pages/components/timeline/CustomizedTimeline.js
- docs/src/pages/components/timeline/CustomizedTimeline.tsx
Preview: https://deploy-preview-26036--material-ui.netlify.app/components/timeline/#customized-timeline
> [docs] Migrate Timeline demos to emotion

- docs/src/pages/components/date-picker/date-picker.md
- docs/src/pages/components/date-range-picker/date-range-picker.md
- docs/src/pages/components/date-time-picker/date-time-picker.md
- docs/src/pages/components/time-picker/time-picker.md
It's understandable which version is used when if you think about it. But without being familiar with media queries and pointers it can be a considerable mental effort when learning. So let's be explicit about it and also link what `pointer: fine` is.
> [docs] Explicitly describe how the media query affects the rendered version

- docs/src/pages/components/dialogs/ConfirmationDialog.js
- docs/src/pages/components/dialogs/ConfirmationDialog.tsx
- docs/src/pages/components/dialogs/CustomizedDialogs.js
- docs/src/pages/components/dialogs/CustomizedDialogs.tsx
- docs/src/pages/components/dialogs/FullScreenDialog.js
- docs/src/pages/components/dialogs/FullScreenDialog.tsx
- docs/src/pages/components/dialogs/MaxWidthDialog.js
- docs/src/pages/components/dialogs/MaxWidthDialog.tsx
- docs/src/pages/components/dialogs/SimpleDialog.js
- docs/src/pages/components/dialogs/SimpleDialog.tsx
Preview https://deploy-preview-26162--material-ui.netlify.app/components/dialogs/
> [docs] Migrate Dialog demos to emotion

- docs/pages/_app.js
Closes #23874
Preview: https://deploy-preview-26193--material-ui.netlify.app
> [docs] Fix Workbox that are causing infinite loading of site

- examples/nextjs-with-typescript/pages/_document.tsx
- examples/nextjs/pages/_document.js
- examples/ssr/server.js
> [examples] Fix dynamic global styles & global styles leak in the ssr examples

- docs/src/pages.ts
- docs/src/pages/components/drawers/drawers.md
- docs/src/pages/customization/breakpoints/breakpoints.md
- docs/src/pages/guides/responsive-ui/responsive-ui.md
- docs/translations/translations.json
I realized that there are still remains of the extinct component Hidden 😄
> [docs] Remove remnants Hidden component

- packages/material-ui-styled-engine-sc/package.json
- packages/material-ui-styled-engine-sc/src/GlobalStyles/GlobalStyles.test.js
- packages/material-ui-styled-engine-sc/src/index.js
- packages/material-ui-styled-engine-sc/src/styled.test.js
- packages/material-ui-styled-engine/src/index.js
- packages/material-ui-styled-engine/src/styled.test.js
- packages/material-ui/src/NativeSelect/NativeSelect.test.js
- packages/material-ui/src/StepContent/StepContent.js
- packages/material-ui/src/TablePagination/TablePagination.js
> [styled-engine] Fix styled-components not supporting empty style

- docs/src/pages/components/buttons/BasicButtons.js
- docs/src/pages/components/buttons/BasicButtons.tsx
- docs/src/pages/components/buttons/ButtonSizes.js
- docs/src/pages/components/buttons/ButtonSizes.tsx
- docs/src/pages/components/buttons/ColorButtons.js
- docs/src/pages/components/buttons/ColorButtons.tsx
- docs/src/pages/components/buttons/ContainedButtons.js
- docs/src/pages/components/buttons/ContainedButtons.tsx
- docs/src/pages/components/buttons/CustomizedButtons.js
- docs/src/pages/components/buttons/CustomizedButtons.tsx
- docs/src/pages/components/buttons/IconLabelButtons.js
- docs/src/pages/components/buttons/IconLabelButtons.tsx
- docs/src/pages/components/buttons/LoadingButtons.js
- docs/src/pages/components/buttons/LoadingButtons.tsx
- docs/src/pages/components/buttons/LoadingButtonsTransition.js
- docs/src/pages/components/buttons/LoadingButtonsTransition.tsx
- docs/src/pages/components/buttons/OutlinedButtons.js
- docs/src/pages/components/buttons/OutlinedButtons.tsx
- docs/src/pages/components/buttons/TextButtons.js
- docs/src/pages/components/buttons/TextButtons.tsx
- docs/src/pages/components/buttons/buttons.md
- docs/src/pages/components/text-fields/BasicTextFields.js
- docs/src/pages/components/text-fields/BasicTextFields.tsx
- docs/src/pages/components/text-fields/text-fields.md
- docs/src/pages/customization/palette/CustomColor.js
- docs/src/pages/customization/palette/CustomColor.tsx
- docs/src/pages/customization/palette/palette.md
Fix #26150
Preview: https://deploy-preview-26184--material-ui.netlify.app/components/buttons/
> [docs] Improve documentation for Buttons

- docs/src/pages/premium-themes/paperbase/Paperbase.js
- docs/src/pages/premium-themes/paperbase/Paperbase.tsx
- docs/src/pages/styles/api/api.md
- docs/src/pages/styles/basics/basics.md
- packages/material-ui-docs/src/NProgressBar/NProgressBar.js
- packages/material-ui/test/typescript/hoc-interop.spec.tsx
- test/regressions/TestViewer.js
- test/regressions/fixtures/Input/InputLabels.js
- test/regressions/fixtures/Input/Inputs.js
- test/regressions/fixtures/Menu/LongMenu.js
- test/regressions/fixtures/SpeedDial/Directions.js
- test/regressions/fixtures/Table/DenseCheckboxTable.js
- test/regressions/fixtures/Tooltip/PositionedTooltips.js
Removes various dependencies to `@material-ui/core/styles`'s `withStyles`.
> [core] Remove `withStyles` dependencies from `@material-ui/core/styles`

- packages/material-ui/src/Breadcrumbs/BreadcrumbCollapsed.js
- packages/material-ui/src/ButtonBase/TouchRipple.js
- packages/material-ui/src/OutlinedInput/NotchedOutline.js
- packages/material-ui/src/Radio/RadioButtonIcon.js
- packages/material-ui/src/SwipeableDrawer/SwipeArea.js
- packages/material-ui/src/internal/SwitchBase.js
> [core] Skip sx prop in internal components

- docs/pages/company/software-engineer-intern.js
- docs/src/pages/company/careers/careers.md
- docs/src/pages/company/software-engineer-intern/software-engineer-intern.md
Adding a new careers page for interns. I tried to follow the template we have for the other roles.
> [website] Add careers page for intern

- packages/material-ui-styled-engine-sc/src/index.js
- packages/material-ui-styled-engine-sc/src/styled.test.js
Fixes https://github.com/mui-org/material-ui/issues/26338
> [styled-engine] Fix styled() util to respect `options`

- CHANGELOG.md
- docs/src/pages/guides/migration-v4/migration-v4.md
https://github.com/mui-org/material-ui/pull/26135#issuecomment-842658407
> [docs] Clarify migration from Hidden

- packages/material-ui/src/ButtonBase/ButtonBase.js
- packages/material-ui/src/ButtonBase/ButtonBase.test.js
Modify the logic for some checks to the `role` prop of ButtonBase.
Fixes: #26253
> [ButtonBase] Fix role="button" attribute

- docs/src/pages/guides/styled-engine/styled-engine.md
> [docs] Fix grammar for style library page

- docs/src/pages/getting-started/templates/sign-in-side/SignInSide.js
- docs/src/pages/getting-started/templates/sign-in-side/SignInSide.tsx
- docs/src/pages/getting-started/templates/sign-in/SignIn.js
- docs/src/pages/getting-started/templates/sign-in/SignIn.tsx
- docs/src/pages/getting-started/templates/sign-up/SignUp.js
- docs/src/pages/getting-started/templates/sign-up/SignUp.tsx
> [template] Demo how to retreive value

- .circleci/config.yml
This reverts commit 5e6dee93deb8c93b246f0b6b0875b861a210488f.
It's incompatible with our nightly workflow.
> Revert "[core] Leverage CircleCI workspaces for jobs after checkout"

- docs/src/pages/company/careers/careers.md
and hide the "Senior Software Engineer" position. We should have enough bandwidth to build now. What we will be short of is: building right (e.g. feature, API, design), guide users, and marketing the value we create.
> [website] Add open application section

- docs/src/pages/system/basics/basics.md
- packages/material-ui-system/README.md
> [docs] Update system installation 

- packages/material-ui/src/TabScrollButton/TabScrollButton.js
- packages/material-ui/src/Tabs/Tabs.test.js
- test/regressions/fixtures/Tabs/RTLVerticalTabs.js
originate from https://github.com/mui-org/material-ui/pull/26470#discussion_r641442696, separate to this PR.
- fix the bug and add test
Preview: https://deploy-preview-26527--material-ui.netlify.app/components/tabs/#vertical-tabs
> [Tabs] Fix arrow rotation in vertical & RTL

- docs/src/pages/components/use-media-query/use-media-query.md
Unless I'm mistaken, I wanted to fix the small typo here.
> [docs] Fix typo sx !== xs

- docs/src/pages/getting-started/templates/checkout/Checkout.js
- docs/src/pages/getting-started/templates/checkout/Checkout.tsx
- docs/src/pages/getting-started/templates/checkout/Review.js
- docs/src/pages/getting-started/templates/checkout/Review.tsx
- docs/src/pages/getting-started/templates/dashboard/Dashboard.js
- docs/src/pages/getting-started/templates/dashboard/Dashboard.tsx
- docs/src/pages/getting-started/templates/pricing/Pricing.js
- docs/src/pages/getting-started/templates/pricing/Pricing.tsx
One of #16947
https://deploy-preview-26604--material-ui.netlify.app/getting-started/templates/
> [docs] Migrate templates to emotion

- packages/material-ui-system/src/createTheme/createBreakpoints.d.ts
- packages/material-ui/src/styles/index.d.ts
> [theme] Fix missing exported Breakpoints types

- docs/src/pages/premium-themes/paperbase/Content.js
- docs/src/pages/premium-themes/paperbase/Content.tsx
- docs/src/pages/premium-themes/paperbase/Header.js
- docs/src/pages/premium-themes/paperbase/Header.tsx
- docs/src/pages/premium-themes/paperbase/Navigator.js
- docs/src/pages/premium-themes/paperbase/Navigator.tsx
- docs/src/pages/premium-themes/paperbase/Paperbase.js
- docs/src/pages/premium-themes/paperbase/Paperbase.tsx
One of #16947
https://deploy-preview-26658--material-ui.netlify.app/premium-themes/paperbase/
> [docs] Migrate paperbase premium template to emotion

- docs/src/pages/premium-themes/paperbase/Content.js
- docs/src/pages/premium-themes/paperbase/Content.tsx
- docs/src/pages/premium-themes/paperbase/Header.tsx
- docs/src/pages/premium-themes/paperbase/Navigator.js
- docs/src/pages/premium-themes/paperbase/Navigator.tsx
- docs/src/pages/premium-themes/paperbase/Paperbase.js
- docs/src/pages/premium-themes/paperbase/Paperbase.tsx
A quick polish on top of #26658
- Add `ListItemButton`
- Remove Box that was added because sx wasn't available on core components
- Update the design to be closer to Firebase
Preview: https://deploy-preview-26711--material-ui.netlify.app/premium-themes/paperbase/
> [docs] Improve Paperbase demo

- babel.config.js
- yarn.lock
Includes 
- https://github.com/babel/babel/releases/tag/v7.14.5
- https://github.com/babel/babel/releases/tag/v7.14.4
- https://github.com/babel/babel/releases/tag/v7.14.3
- https://github.com/babel/babel/releases/tag/v7.14.2
- https://github.com/babel/babel/releases/tag/v7.14.1
- https://github.com/babel/babel/releases/tag/v7.14.0
> Bump @babel/* to 7.14.5

- docs/src/pages/premium-themes/onepirate/modules/components/Paper.js
- docs/src/pages/premium-themes/onepirate/modules/components/Paper.tsx
- docs/src/pages/premium-themes/onepirate/modules/components/Toolbar.js
- docs/src/pages/premium-themes/onepirate/modules/components/Toolbar.tsx
- docs/src/pages/premium-themes/onepirate/modules/views/AppAppBar.js
- docs/src/pages/premium-themes/onepirate/modules/views/AppAppBar.tsx
- docs/src/pages/premium-themes/onepirate/modules/views/AppForm.js
- docs/src/pages/premium-themes/onepirate/modules/views/AppForm.tsx
- docs/src/pages/premium-themes/onepirate/modules/views/ProductCategories.js
- docs/src/pages/premium-themes/onepirate/modules/views/ProductCategories.tsx
- docs/src/pages/premium-themes/onepirate/modules/views/ProductHero.js
- docs/src/pages/premium-themes/onepirate/modules/views/ProductHero.tsx
- docs/src/pages/premium-themes/onepirate/modules/views/ProductHeroLayout.js
- docs/src/pages/premium-themes/onepirate/modules/views/ProductHeroLayout.tsx
This is a second part of the migration
One of #16947
Preview https://deploy-preview-26707--material-ui.netlify.app/premium-themes/onepirate/
> [docs] Migrate onepirate premium template to emotion part2

- packages/material-ui-lab/src/DesktopDatePicker/DesktopDatePickerKeyboard.test.tsx
- packages/material-ui-lab/src/StaticDateRangePicker/StaticDateRangePicker.test.tsx
- test/utils/mochaHooks.test.js
Commit descriptions include the test failures due to flakiness
> [test] Reduce flakiness

- docs/src/pages/guides/migration-v4/migration-v4.md
> [docs] Fix documentation for upgrading to v5

- docs/src/pages/components/autocomplete/autocomplete.md
> [docs] Improve grammar of autocomplete/autofill section

- docs/src/pages/guides/localization/localization.md
- packages/material-ui/src/locale/index.ts
Sinhala is among the 100 most used languages (68th) in the world. This PR was inspired by [this invitation to submit PRs for new languages](https://material-ui.com/guides/localization/#supported-locales)
> [l10n] Add sinhalese (siLK) locale

- docs/src/pages/customization/typography/typography-de.md
- docs/src/pages/customization/typography/typography-es.md
- docs/src/pages/customization/typography/typography-fr.md
- docs/src/pages/customization/typography/typography-ja.md
- docs/src/pages/customization/typography/typography-pt.md
- docs/src/pages/customization/typography/typography-ru.md
- docs/src/pages/customization/typography/typography-zh.md
- docs/src/pages/customization/typography/typography.md
- test/regressions/fixtures/Alert/MultilineAlertWithAction.js
> [docs] Fix misspelling of the word Typography

- docs/pages/api-docs/dialog.json
- packages/material-ui/src/Dialog/Dialog.js
Caused by merging outdated https://github.com/mui-org/material-ui/pull/26836
> [core] Fix merge conflict

- packages/material-ui/src/Popover/Popover.test.js
Part of https://github.com/mui-org/material-ui/issues/13394
> [test] Convert Popover tests to testing-library

- docs/src/pages/system/the-sx-prop/the-sx-prop.md
The missing bites from https://github.com/mui-org/material-ui/pull/26769#pullrequestreview-688603264. They would be detected by our SEO crawler.
> [docs] Fix 301 links

- packages/material-ui-lab/src/TabPanel/TabPanel.test.tsx
- test/utils/createClientRender.tsx
- test/utils/describeConformanceV5.js
> [test] Add types to describeConformanceV5

- docs/next.config.js
Forgot to revert before merging #26774
> [docs] Export all locales

- packages/material-ui/src/Hidden/HiddenCss.test.js
> [test] Convert HiddenCSS tests to testing-library

- docs/packages/markdown/loader.js
In dev we'll still build both versions so that devs can decide with which language version they want to work. For production the demos will be equivalent anyway so we can just build the version that requires less transpilation (the JS version).
Saves 40s fresh build time on my machine. Marginal bundle size  improvements
> [docs] Only bundle one version of the demos in production

- docs/next.config.js
I think this polyfill became obsolete with https://github.com/mui-org/material-ui/pull/24635
> [docs] Remove unused fs polyfill

- docs/pages/components/hidden.js
> [docs] Fix import source of hidden component

- .github/workflows/ci.yml
- README.md
- scripts/releaseChangelog.js
> [core] Migrate remaining mentions of Dependabot to Renovate

- examples/gatsby-theme/src/pages/about.js
> [examples] Remove forgotten StyledEngineProvider

- docs/pages/api-docs/toggle-button.json
- packages/material-ui/src/ToggleButton/ToggleButton.js
The update to the API introduced in #27046 is wrong
> [ToggleButton] Fix the api page

- docs/src/pages/styles/api/api.md
> [docs] Fix syntax error in /styles/api markdown

- docs/src/pages/styles/basics/basics.md
> [docs] fix theme context example code

- docs/pages/system/the-sx-prop.js
Preview: https://deploy-preview-27202--material-ui.netlify.app/system/the-sx-prop/
> [docs] Fix the link for the sx props page

- docs/pages/api-docs/button-group.json
- docs/pages/api-docs/toggle-button-group.json
- packages/material-ui/src/ButtonGroup/ButtonGroup.d.ts
- packages/material-ui/src/ButtonGroup/ButtonGroup.js
- packages/material-ui/src/ToggleButtonGroup/ToggleButtonGroup.d.ts
- packages/material-ui/src/ToggleButtonGroup/ToggleButtonGroup.js
I have tried my best to avoid such problems #27164 , but I still hope to have a more careful check.
> [ButtonGroup] Add color palette types

- examples/cdn/README.md
- examples/cdn/index.html
A quick follow-up on #27053, I was curious if we didn't have more cases like this.
> [examples] Fix CDN warning

- docs/pages/index.tsx
- docs/src/pages/landing/QuickWord.js
Reduces the cumulative layout shift to 0.002 (was 0.003).
> [docs] Reduce layout shift on landing page

- packages/material-ui/src/PaginationItem/PaginationItem.js
> Allow :hover effect on previous/next button

- packages/material-ui/src/Accordion/Accordion.js
- packages/material-ui/src/Collapse/Collapse.js
> [Accordion, Collapse] Fix failed proptype error

- packages/material-ui-codemod/README.md
Closes https://github.com/mui-org/material-ui/issues/27253
> [codemod] Improve README.md

- docs/src/pages/components/text-fields/InputAdornments.js
- docs/src/pages/components/text-fields/InputAdornments.tsx
- docs/src/pages/guides/migration-v4/migration-v4.md
- test/regressions/fixtures/TextField/FilledHiddenLabelInputAdornment.js
> [docs] Use actual symbol of kilogram

- docs/src/pages/system/the-sx-prop/the-sx-prop.md
Don't mind me - just fixing a typo in the word typography 😄 
Edited directly in the web GitHub Markdown editor. Hope it's ok for this PR. Have a great weekend!
> [docs] Fix typo in the word typography

- packages/material-ui-lab/src/internal/pickers/date-utils.test.ts
- packages/material-ui-lab/src/internal/pickers/date-utils.ts
(disabled) tests and code comments did not match the implementation.
> [pickers] Fallback to today if all possible dates are disabled

- docs/src/pages/guides/migration-v4/migration-v4.md
improve migration docs from #27289
> [docs] Add `makeStyles` explanation in troubleshooting

- docs/src/pages/components/drawers/MiniDrawer.js
- docs/src/pages/components/drawers/MiniDrawer.tsx
Following this [issue](https://github.com/mui-org/material-ui/issues/27007) I created , here follows the pull request.
Please check the issue because I explain in detail the issue and the solution there.
Closes https://github.com/mui-org/material-ui/issues/27007
> [docs] Remove horizontal scrollbar in MiniDrawer

- docs/src/pages/guides/migration-v4/migration-v4.md
Fixes https://github.com/mui-org/material-ui/issues/27344
> [docs] Update migration guide to have a section on nested classes

- docs/src/modules/components/AppFrame.js
- docs/src/modules/components/AppSearch.js
> [docs] Fix app bar regression

- docs/src/pages/components/transitions/transitions.md
close #27318 
Preview: https://deploy-preview-27319--material-ui.netlify.app/components/transitions/
> [docs] Update `Transitions` page

- docs/pages/api-docs/filled-input.json
- docs/pages/api-docs/input.json
- docs/pages/api-docs/outlined-input.json
- docs/translations/api-docs/filled-input/filled-input.json
- docs/translations/api-docs/input/input.json
- docs/translations/api-docs/outlined-input/outlined-input.json
- packages/material-ui/src/FilledInput/FilledInput.js
- packages/material-ui/src/FilledInput/FilledInput.test.js
- packages/material-ui/src/Input/Input.js
- packages/material-ui/src/Input/Input.test.js
- packages/material-ui/src/OutlinedInput/OutlinedInput.js
- packages/material-ui/src/OutlinedInput/OutlinedInput.test.js
Fixes bug found in https://github.com/mui-org/material-ui/pull/27150
> [Input] Merge `componentsProps` correctly

- packages/material-ui/src/Autocomplete/Autocomplete.test.js
- packages/material-ui/src/useAutocomplete/useAutocomplete.js
> [Autocomplete] Update input value when the input changes

- packages/material-ui/src/Dialog/Dialog.js
> [Dialog] Fix override paper styles

- docs/src/pages/guides/migration-v4/migration-v4.md
- docs/src/pages/styles/advanced/advanced.md
- docs/src/pages/styles/api/api.md
> [docs] Fix wrong import path in @material-ui/styles section

- docs/src/pages/components/popper/ScrollPlayground.js
Fixes  #27301
Preview: https://deploy-preview-27339--material-ui.netlify.app/components/popper/#scroll-playground
> [docs] Display Popper arrow correctly 

- docs/pages/api-docs/grid-list-tile-bar.md
- docs/pages/api-docs/grid-list-tile.md
- packages/material-ui/src/GridListTile/GridListTile.d.ts
- packages/material-ui/src/GridListTile/GridListTile.js
- packages/material-ui/src/GridListTileBar/GridListTileBar.d.ts
- packages/material-ui/src/GridListTileBar/GridListTileBar.js
Closes https://github.com/mui-org/material-ui/issues/27497
> [ImageList] Fix deprecation warnings 

- docs/src/pages/customization/how-to-customize/DynamicThemeNesting.tsx
> [docs] Remove unnecessary generic argument

- docs/pages/branding/about.tsx
- docs/src/pages/discover-more/team/Team.js
https://stackoverflow.com/tags/material-ui/topusers
> [docs] Add Ryan to Community contributors for SO contributions

- docs/src/pages/guides/server-rendering/server-rendering.md
- examples/ssr/client.js
- examples/ssr/createEmotionCache.js
- examples/ssr/getCache.js
- examples/ssr/server.js
> [docs] Improve SSR configuration with emotion

- docs/src/pages/guides/localization/localization.md
- packages/material-ui/src/locale/index.ts
> [l10n] Add Arabic Sudan (ar-SD) locale

- docs/src/pages/components/transfer-list/transfer-list.md
Closes #27579, we will be able to collect more feedback with the badge, hopefully.
> [docs] Add badges to Transfer List

- packages/material-ui-lab/src/themeAugmentation/components.d.ts
- packages/material-ui/src/styles/components.d.ts
Closes [#27409](https://github.com/mui-org/material-ui/issues/27409)
> [theme] Add missed variants in Components interface

- packages/material-ui-styled-engine/src/StyledEngineProvider/StyledEngineProvider.js
[ref](https://github.com/mui-org/material-ui/pull/27671#issuecomment-896011379)
> [StyledEngineProvider] Remove unnecessary emotion cache export

- docs/next-env.d.ts
Commits the change from running `yarn docs:dev` after https://github.com/mui-org/material-ui/pull/27718
> [core] Remove diff when running yarn docs:dev

- docs/src/pages/components/box/box.md
- [ x ] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui-org/material-ui/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).
> [docs] Fix sentence to be more grammatically correct

- docs/src/pages/components/accordion/accordion.md
- docs/src/pages/components/badges/badges.md
- docs/src/pages/components/breadcrumbs/breadcrumbs.md
- docs/src/pages/components/buttons/buttons.md
- docs/src/pages/components/checkboxes/checkboxes.md
- docs/src/pages/components/dialogs/dialogs.md
- docs/src/pages/components/menus/menus.md
- docs/src/pages/components/progress/progress.md
- docs/src/pages/components/radio-buttons/radio-buttons.md
- docs/src/pages/components/rating/rating.md
- docs/src/pages/components/selects/selects.md
- docs/src/pages/components/slider/slider.md
- docs/src/pages/components/snackbars/snackbars.md
- docs/src/pages/components/steppers/steppers.md
- docs/src/pages/components/switches/switches.md
- docs/src/pages/components/tables/tables.md
- docs/src/pages/components/tabs/tabs.md
- docs/src/pages/components/text-fields/text-fields.md
- docs/src/pages/components/timeline/timeline.md
- docs/src/pages/components/toggle-button/toggle-button.md
- docs/src/pages/components/tooltips/tooltips.md
Leverage https://github.com/mui-org/material-ui/pull/27694/files#diff-91ca752bb9132735cc644b6fac0ea644299070892c897642b9ec791af4230ca1R107 into the other occurrences.
> [docs] One line per sentence

- docs/src/pages/guides/migration-v4/migration-v4.md
Act on https://github.com/mui-org/material-ui/pull/23607#issuecomment-899043763
> [docs] Improve the Modal onClose migration

- docs/src/components/header/HeaderNavDropdown.tsx
- docs/src/components/home/DesignSystemComponents.tsx
- docs/src/modules/branding/BrandingDiscoverMore.tsx
- docs/src/pages/components/steppers/TextMobileStepper.js
- docs/src/pages/components/steppers/TextMobileStepper.tsx
- docs/src/pages/premium-themes/onepirate/modules/components/TextField.js
- docs/src/pages/premium-themes/onepirate/modules/components/TextField.tsx
- docs/src/pages/premium-themes/onepirate/modules/components/Typography.js
- docs/src/pages/premium-themes/onepirate/modules/components/Typography.tsx
- packages/material-ui/src/ButtonBase/ButtonBase.test.js
> [core] Fix typos in repository

- packages/material-ui/src/ButtonBase/TouchRipple.js
> [core] Fix typo in code comment

- docs/src/pages/components/dialogs/dialogs.md
Changed the word from "aide" to "aid"
> [docs] Fix typo on "Customized dialogs" section

- README.md
> [docs] Improve README.md

- docs/src/pages/components/buttons/buttons.md
Dialogs and Modal windows are similar, we don't need to list all the instances where button are relevant.
> [docs] A few examples is enough

- docs/src/pages/guides/localization/localization.md
- packages/material-ui/src/locale/index.ts
> [I10n] Add Khmer (kh-KH) locale support

- docs/src/pages/components/selects/MultipleSelectChip.js
- docs/src/pages/components/selects/MultipleSelectChip.tsx
First I thought about using `Stack` to simplify the demo, but that component doesn't handle wrapping.
Still, I think this makes the code a bit easier :slightly_smiling_face:
> [docs] Simplify Select Chip demo styling

- docs/src/components/home/HeroEnd.tsx
- docs/src/layouts/AppFooter.tsx
A quick follow-up on #27838. I didn't try to solve the case where the text and the button wraps, I have ignored these cases: error of approximation 😁.
It looks great on HEAD https://www.webpagetest.org/video/compare.php?tests=210823_BiDcHH_b1bc464b30336c4cfad8414215b60a70,210823_AiDcXW_57feede5378569b12bb3fd70242c65ff,210823_AiDcQ1_4c8a4774e325928618765bbed9f516db,210823_AiDc1G_4010deeaeacdf8aeaba648910d9a105c,210823_AiDcFX_3f04c0f32a1e4b8e0dc662f844b5055f
> [website] Polish homepage

- packages/material-ui/src/Autocomplete/Autocomplete.js
- packages/material-ui/src/Autocomplete/Autocomplete.test.js
A follow up to this: https://github.com/mui-org/material-ui/pull/27925#discussion_r694976707
> [Autocomplete] Update warning for `value` prop

- docs/src/pages/customization/how-to-customize/how-to-customize.md
> [docs] Fix typo '.MuiOutinedInput' -> '.MuiOutlinedInput'

- docs/src/components/pricing/FAQ.tsx
- docs/src/pages/getting-started/support/support.md
To complement https://github.com/mui-org/material-ui-x/pull/2468
Preview: https://deploy-preview-27999--material-ui.netlify.app/getting-started/support/
> [docs] Improve the support expectations for developers

- docs/src/pages/components/floating-action-button/FloatingActionButtonExtendedSize.js
- docs/src/pages/components/floating-action-button/FloatingActionButtonExtendedSize.tsx
- docs/src/pages/components/floating-action-button/FloatingActionButtonSize.js
- docs/src/pages/components/floating-action-button/FloatingActionButtonSize.tsx
- docs/src/pages/components/floating-action-button/FloatingActionButtons.js
- docs/src/pages/components/floating-action-button/FloatingActionButtons.tsx
- docs/src/pages/components/text-fields/InputWithIcon.js
- docs/src/pages/components/text-fields/InputWithIcon.tsx
Fixes #27973
Preview: https://deploy-preview-28033--material-ui.netlify.app/components/floating-action-button/
> [docs] Fix Fab demo overflow on mobile

- docs/pages/api-docs/toggle-button-group.json
- docs/translations/api-docs/toggle-button-group/toggle-button-group.json
- packages/material-ui/src/ToggleButtonGroup/ToggleButtonGroup.d.ts
- packages/material-ui/src/ToggleButtonGroup/ToggleButtonGroup.js
- packages/material-ui/src/ToggleButtonGroup/ToggleButtonGroup.test.js
- packages/material-ui/src/ToggleButtonGroup/toggleButtonGroupClasses.ts
> [ToggleButtonGroup] Add "disabled" prop

- docs/src/pages/guides/migration-v4/migration-v4.md
> [docs] Fix migration guide typo

- packages/material-ui-codemod/README.md
> [docs] Fix wrong package name in codemod

- docs/pages/branding/design-kits.tsx
- docs/pages/branding/templates.tsx
- docs/src/components/productDesignKit/DesignKitDemo.tsx
- docs/src/components/productDesignKit/DesignKitFAQ.tsx
- docs/src/components/productDesignKit/DesignKitHero.tsx
- docs/src/components/productDesignKit/DesignKitValues.tsx
- docs/src/components/productTemplate/TemplateDemo.tsx
- docs/src/components/productTemplate/TemplateHero.tsx
> [website] Polish design-kits & templates

- test/karma.conf.js
Previous logic did not work for renvoate PRs e.g. https://app.circleci.com/pipelines/github/mui-org/material-ui/51777/workflows/0384cd66-c6e7-48f4-b7ea-df4c66242ffd/jobs/292584
> [core] Fix PR detection mechanism for upstream PRs

- docs/pages/index.tsx
Converted title and CTA to white and increased size of CTA based on issue #28071 
Closes #28071
> [docs] Improve legibility of CTA on landing page

- packages/material-ui-unstyled/tsconfig.json
> [core] Remove unused include

- docs/src/pages/components/autocomplete/Virtualize.js
- docs/src/pages/components/autocomplete/Virtualize.tsx
Fix https://github.com/mui-org/material-ui/pull/27340#issuecomment-912545019
> [Autocomplete] Fix virtualization regression

- scripts/sizeSnapshot/create.js
- scripts/sizeSnapshot/webpack.config.js
Manly revolves around ensuring that it's clear that the entry names are IDs to ensure tracking over time.
Also updated what peer dependencies we have (date libraries from the pickers).
> [core] Misc bundle size tracking improvements

- docs/src/pages/components/buttons/UnstyledButtonCustom.tsx.preview
- docs/src/pages/customization/dark-mode/DarkThemeWithCustomPalette.tsx.preview
- docs/src/pages/customization/dark-mode/ToggleColorMode.tsx.preview
Forgot to update https://github.com/mui-org/material-ui/pull/28215
> [docs] Update previews

- docs/src/pages/guides/migration-v4/migration-v4.md
> [docs] Fix some outdated migration guide

- docs/src/pages/guides/migration-v4/migration-v4.md
Fixes a few typos in the migration example for `makeStyles`.
> docs: Fixes makeStyles migration example

- docs/src/pages/customization/theming/theming.md
> [docs] How to compose theme in steps

- docs/src/pages/customization/typography/typography.md
> [docs] Fix quotes in font-face literal

- docs/src/pages/customization/transitions/TransitionHover.js
- docs/src/pages/customization/transitions/TransitionHover.tsx
- docs/src/pages/customization/transitions/TransitionHover.tsx.preview
> [docs] Fix typo in transition docs

- .circleci/config.yml
- CONTRIBUTING.md
- scripts/prettier.js
Things that didn't have a `#default-branch-switch`
> [core] Various updates to what we consider the default branch

- scripts/listChangedFiles.js
To make CI pass short-term with minimal changes.
> [core] Consider v4.x as the base

- docs/src/pages/guides/migration-v4/migration-v4.md
> [Docs] Fix typo in v4 to v5 migration guide

- docs/src/pages/components/hidden/hidden.md
- docs/src/pages/styles/api/api.md
Report moz.com reported issues:
- description missing
- short title
> [website] Fix SEO issues reported by moz.com

- CONTRIBUTING.md
> [docs] Fix CONTRIBUTING to point out to master as targeted branch

- docs/src/modules/components/AppFrame.js
- docs/src/modules/components/AppNavDrawerItem.js
A few issues I have noticed on https://validator.w3.org/nu/?doc=https%3A%2F%2Fmui.com%2Fcomponents%2Fbuttons%2F
> [docs] Fix html compliance

- scripts/listChangedFiles.test.js
More leftover default branch switching
> [test] Run listChangedFiles against master

- docs/src/pages/components/popper/SpringPopper.js
- docs/src/pages/components/popper/SpringPopper.tsx
- docs/src/pages/components/popper/TransitionsPopper.js
- docs/src/pages/components/popper/TransitionsPopper.tsx
Closes https://github.com/mui-org/material-ui/issues/28503
> [docs] Fix missing exit animation for transition Poppers

- scripts/releaseChangelog.js
> [core] Fix release:changelog base branch

- examples/create-react-app-with-styled-components-typescript/package.json
- examples/create-react-app-with-styled-components/package.json
- examples/create-react-app-with-typescript/package.json
- examples/create-react-app/package.json
- examples/gatsby/package.json
- examples/nextjs-with-styled-components-typescript/package.json
- examples/nextjs-with-typescript/package.json
- examples/nextjs/package.json
- examples/preact/package.json
- examples/ssr/package.json
> [docs] Update examples to use `latest` mui

- docs/src/components/showcase/PlayerCard.tsx
- docs/src/modules/components/AppSearch.js
- fix demo ui in safari
- reduce spacing in search to see more result at initial
<table>
<thead>
<tr>
<th>Before</th>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
---
> [website] Batch fixes

- docs/src/components/pricing/EarlyBird.tsx
- docs/src/components/pricing/PricingTable.tsx
- Adding a **_Buy now_** button to the Early Bird box.
- Adding a _*Early bird special_ disclaimer to the $186 price on the Pro plan.
[Deploy preview →](https://deploy-preview-28406--material-ui.netlify.app/pricing/)
> [website] Iteration on the pricing page

- docs/src/pages/customization/theme-components/theme-components.md
> [docs] Fix color in example

- docs/src/pages/premium-themes/onepirate/modules/form/validation.js
- docs/src/pages/premium-themes/onepirate/modules/form/validation.ts
Update to support Unicode email addresses.
> [docs] Polish email validation logic

- packages/mui-system/src/Box/Box.spec.tsx
- packages/mui-system/src/styleFunctionSx/styleFunctionSx.d.ts
- packages/mui-system/src/styleFunctionSx/styleFunctionSx.test.js
Fixes https://github.com/mui-org/material-ui/issues/28523
> [system] Fix types to support theme callbacks on pseudo and nested selectors

- docs/src/pages/components/date-range-picker/date-range-picker.md
Removed duplicate line in date-ranger-picker.md file
> [docs] Removed duplicate line in date-ranger-picker.md file

- .github/renovate.json
- list all packages from https://github.com/cssinjs/jss/tree/master/packages
- Add `MUI-X` group matching `@mui/x-*`
> [core] Improve Renovate groups

- README.md
- docs/src/pages/discover-more/changelog/changelog.md
- Reference the correct CHANGELOG for v4 - https://github.com/mui-org/material-ui/commit/f471b15b930b94c8e379e0240df45078e4a34398
- Update the README to announce v5 and add a link to the v4 docs - https://github.com/mui-org/material-ui/commit/c4a665a13c53854bed3173d2a92d3e29332122ff
> [v4] Batch fixes

- docs/pages/versions.js
> [docs] Fix versions page

- docs/src/pages/components/chips/ClickeableAndDeleteableChips.js
- docs/src/pages/components/chips/ClickeableAndDeleteableChips.tsx
- docs/src/pages/components/chips/ClickeableAndDeleteableChips.tsx.preview
- docs/src/pages/components/chips/DeleteableChips.js
- docs/src/pages/components/chips/DeleteableChips.tsx
- docs/src/pages/components/chips/DeleteableChips.tsx.preview
- docs/src/pages/components/chips/chips.md
> [docs] Fix typo in chip documentation 

- docs/src/pages/guides/styled-engine/styled-engine.md
> [docs] Fix typo in /guides/styled-engine

- docs/src/pages/versions/versions.md
| ------- | ----- |
| <img height="300" src="https://user-images.githubusercontent.com/25351744/135310953-a76f7d55-ad6e-4ede-8f36-506285780038.png"> | <img height="300" src="https://user-images.githubusercontent.com/25351744/135422334-2d629acb-4502-4a51-b9ec-e3ca1d649ee6.png"> |
Closes #28677
> [docs] Update v5 status in release schedule

- docs/src/pages/system/box/box.md
> [docs] Fix typo in system/box documentation

- framer/Material-UI.framerfx/package.json
- package.json
To prevent error when doing release.
```bash
lerna ERR! 
lerna ERR! lerna ENOENT: no such file or directory, open '/Users/siriwatknp/Personal-Repos/material-ui/framer/Material-UI.framerfx/build/package.json'
error Command failed with exit code 1.
```
**Ref**: https://mui-org.slack.com/archives/C0170JAM7ML/p1632313083002800
> [core] Neglect framer from release flow

- packages/mui-styled-engine-sc/src/index.js
Closes https://github.com/mui-org/material-ui/issues/28364
Code sandbox: https://codesandbox.io/s/usage-forked-tu7kl?file=/index.js
> [@mui/styled-engine-sc] Do not allow styled-components' APIs on mui `styled` function

- README.md
- Match example to codesandbox live demo
- Update ID link to FAQ
---
> [docs] Match example to codesandbox demo and update ID link

- docs/src/components/home/DesignKits.tsx
- docs/src/components/home/StoreTemplatesBanner.tsx
- docs/src/components/pricing/WhatToExpect.tsx
- docs/src/components/productCore/CoreHeroEnd.tsx
- packages/mui-codemod/README.md
- packages/mui-system/src/breakpoints.js
- packages/mui-system/src/createTheme/createBreakpoints.js
Stuff I have noticed in the last 4 weeks.
> [docs] Fix small typos

- .github/renovate.json
This is a follow-up on [this internal comment](https://mui-org.slack.com/archives/G011VC970AW/p1635617184025700?thread_ts=1635594587.024000&cid=G011VC970AW)
> [core] Settle on MUI X for the official name

- docs/tsconfig.json
> [core] Commit new nextjs 12 tsconfig

- docs/src/modules/components/AppSearch.js
> [docs] Fix warnings in AppSearch

- packages/mui-material/src/styles/createPalette.js
main: #ED6C02
light: #ff9800
dark: #e65100
> [core] Convert a named color to lowercase

- docs/src/modules/utils/generatePropDescription.ts
> [core] Handle RecordType and FieldType in generatePropDescription.ts

- packages/mui-joy/src/styles/CssVarsProvider.test.tsx
- packages/mui-joy/src/styles/styled.test.tsx
Fixes https://app.circleci.com/jobs/github/mui-org/material-ui/312033
Browser run: https://app.circleci.com/pipelines/github/mui-org/material-ui/54574/workflows/8d02f99c-3236-43c6-94d7-63eb76d1ed72
1. Use longhand properties instead of shorthand properties such as `border-radius`
1. Adjust `font-weight` depending on browser
1. adjust `font-family` computation depending on browser
> [test] Fix browser tests

- packages/mui-material/src/OutlinedInput/NotchedOutline.js
Closes https://github.com/mui-org/material-ui/issues/19463
> [TextField] Fix bootstrap, normalize.css, sanitize.css conflicts

- docs/pages/blog/benny-joo-joining.js
- docs/pages/blog/benny-joo-joining.md
Preview: https://deploy-preview-29499--material-ui.netlify.app/blog/benny-joo-joining/
> [website] Benny Joo joining MUI

- test/utils/createRenderer.tsx
Broke in https://github.com/mui-org/material-ui/pull/29471
> [test] Restore StrictMode by default

- docs/pages/api-docs/native-select.json
- docs/pages/api-docs/select.json
- docs/translations/api-docs/native-select/native-select.json
- docs/translations/api-docs/select/select.json
- packages/mui-material/src/NativeSelect/NativeSelectInput.js
- packages/mui-material/src/NativeSelect/NativeSelectInput.test.js
- packages/mui-material/src/NativeSelect/nativeSelectClasses.ts
- packages/mui-material/src/Select/Select.test.js
- packages/mui-material/src/Select/SelectInput.js
- packages/mui-material/src/Select/selectClasses.ts
Fix https://github.com/mui-org/material-ui/issues/29439
> [Select][NativeSelect] Add `multiple` class

- docs/src/pages/customization/theming/theming.md
close #29504
Preview: https://deploy-preview-29573--material-ui.netlify.app/customization/theming/#theme-provider
> [docs] Update `ThemeProvider` API link

- packages/mui-material/src/locale/index.ts
I've updated the Dutch locale since I noticed there were some translations missing.
> [l10n] Improved Dutch (nl-NL) locale

- docs/pages/pricing.tsx
- docs/src/components/pricing/FAQ.tsx
- docs/src/components/pricing/HeroPricing.tsx
- docs/src/components/pricing/PricingList.tsx
- docs/src/components/pricing/PricingTable.tsx
The only one that might make it in time is the grouping feature with @flaviendelangle. But even if it does happen, we are not ready yet to package it in the Premium plan. So 2022.
Preview: https://deploy-preview-29430--material-ui.netlify.app/pricing/
> [website] Fix premium plan release date

- docs/pages/_app.js
- docs/src/modules/components/AppFrame.js
- docs/src/modules/components/AppSearch.js
- docs/src/modules/components/GoogleAnalytics.js
- docs/src/modules/components/MarkdownLinks.js
- docs/src/modules/utils/helpers.ts
- docs/src/pages.ts
Fix https://github.com/mui-org/material-ui/pull/29483#issuecomment-965897922
To reproduce:
1. Go to master
2. Go to http://0.0.0.0:3000/zh/components/buttons/
3. Search for alert
4. Click or press enter
5. Boom, the page do a hard reload
> [docs] Fix Search navigation

- packages/material-ui/src/locale/index.ts
> add norwegian locale

- docs/src/pages/components/autocomplete/autocomplete.md
> [docs] Update autocomplete.md

- packages/mui-lab/src/MonthPicker/MonthPicker.tsx
- packages/mui-lab/src/MonthPicker/PickersMonth.tsx
- packages/mui-lab/src/YearPicker/PickersYear.tsx
This pull request fixes the Month Selection of DatePicker as mentioned in this issue (#29369).
old:
new:
> [DatePicker] MonthPicker style (#29369)

- docs/packages/markdown/parseMarkdown.js
- docs/packages/markdown/parseMarkdown.test.js
- docs/pages/blog/mui-core-v5.md
See https://github.com/mui-org/material-ui/pull/29590#discussion_r747577591 for context.
> [blog] Support many authors in markdown pages

- docs/src/layouts/AppHeader.tsx
- docs/src/modules/components/AppSearch.js
Deploy preview: https://deploy-preview-29640--material-ui.netlify.app/
> [website] Add GitHub icon button to the navbar

- docs/pages/blog/benny-joo-joining.md
A number of small issues, wrong year, missing social network card, duplicated word, etc.
> [blog] Polish the Benny Joo joins MUI post

- packages/mui-codemod/src/v5.0.0/jss-to-styled.js
- packages/mui-codemod/src/v5.0.0/jss-to-styled.test.js
- packages/mui-codemod/src/v5.0.0/jss-to-styled.test/multipleWithStyles.actual.js
- packages/mui-codemod/src/v5.0.0/jss-to-styled.test/multipleWithStyles.expected.js
close #29363
It's hard to review the implementation, so focusing on the test files should be enough.
> [codemod] Fix `jss-to-styled` to support multiple withStyles

- packages/mui-material/src/Box/Box.spec.tsx
- packages/mui-system/src/createBox.js
Fixes https://github.com/mui-org/material-ui/issues/29775
> [Box] Fix `sx` prop runtime issue when used as function

- .circleci/config.yml
Follow-up to https://github.com/mui-org/material-ui/pull/29876 which had a faulty detection of PR vs Push runs.
> [core] Fix PR run detection in test_bundle_size_monitor

- packages/mui-codemod/src/util/propsToObject.js
- packages/mui-codemod/src/v5.0.0/box-sx-prop.js
- packages/mui-codemod/src/v5.0.0/box-sx-prop.test.js
- packages/mui-codemod/src/v5.0.0/box-sx-prop.test/alias-actual.js
- packages/mui-codemod/src/v5.0.0/box-sx-prop.test/alias-expected.js
> [codemod] Fix alias import for `box-sx-prop`

- docs/src/pages/components/snackbars/snackbars.md
- docs/src/pages/components/trap-focus/trap-focus.md
A minor detail https://github.com/mui-org/material-ui/pull/29850/files#r757107140.
> [docs] Fix key display

- docs/src/pages/guides/classname-generator/classname-generator.md
AFAIK when using `git diff`, the whole content should be offset by one char. This first char is one three values:
- `one space`: no line change
- `-`: line removed
- `+`: line added
> [docs] Improve git diff format

- docs/src/layouts/AppFooter.tsx
> [website] LinkedIn slug change

- docs/src/pages/guides/migration-v4/migration-v4.md
> [docs] Clarify comment in migration doc

- packages/mui-material/src/GlobalStyles/GlobalStyles.d.ts
- packages/mui-material/src/GlobalStyles/GlobalStyles.spec.tsx
- packages/mui-styled-engine/src/GlobalStyles/GlobalStyles.d.ts
Fixes https://github.com/mui-org/material-ui/issues/30035
> [GlobalStyles] Fix `theme` type 

- docs/src/pages/components/grid/InteractiveGrid.js
- docs/src/pages/components/grid/InteractiveGrid.tsx
Closes https://github.com/mui-org/material-ui/issues/30110 :)
Deploy preview: https://deploy-preview-30117--material-ui.netlify.app/components/grid/#interactive
> [docs] Fix justifyContent option in the Grid interactive demo

- docs/src/pages/customization/theming/theming.md
Reported by a contributor at https://github.com/mui-org/material-ui/issues/30004#issuecomment-985203080
Before: https://mui.com/customization/theming/#custom-variables
After: https://deploy-preview-30100--material-ui.netlify.app/customization/theming/#custom-variables
> [docs] Fix link on "Custom variables" section in the Theming page

- packages/mui-icons-material/builder.md
> [icons] Correct location of icon download folder

- docs/translations/api-docs/badge/badge.json
- packages/mui-base/src/BadgeUnstyled/BadgeUnstyled.js
- packages/mui-base/src/BadgeUnstyled/BadgeUnstyled.test.js
- packages/mui-material/src/Badge/Badge.js
I will introduce the hook in a follow up PR, it would be easier for review.
> [BadgeUnstyled] Make it conformant with other base components

- docs/src/modules/components/AppFrame.js
Don't show nprogress bar when page transition is instant
Fixes https://github.com/mui-org/material-ui/pull/30075#issuecomment-987268449
Preview: https://deploy-preview-30087--material-ui.netlify.app/
> [docs] Don't run nprogress on shallow routing

- packages/mui-material/src/Select/Select.test.js
- packages/mui-material/src/Select/SelectInput.js
Simply to solve that error initial state was added.
> [core] Improve Select multiple logic

- package.json
As far as I know, the version of the docs reads from root package JSON.
> [core] update root package version

- docs/src/pages/customization/breakpoints/MediaQuery.js
- docs/src/pages/customization/breakpoints/MediaQuery.tsx
- docs/src/pages/customization/breakpoints/MediaQuery.tsx.preview
Rendered colors were not matching the description (purple was shown in place of red)
Fixes #30215
> [docs] Correct colors in breakpoints documentation

- packages/mui-system/src/cssVars/createCssVarsProvider.js
Follow-up on https://github.com/mui-org/material-ui/pull/29946/files#r758273640
> [system] Use `useEnhancedEffect` to prevent flicker

- docs/src/pages/components/accordion/accordion.md
The current description describes a different component.
> [docs] Improve the description of the Accordion

- docs/scripts/formattedTSDemos.js
> [core] Update `docs:typescript:formatted` to support new structure

- docs/src/pages/components/selects/MultipleSelect.js
- docs/src/pages/components/selects/MultipleSelect.tsx
- docs/src/pages/components/selects/MultipleSelectCheckmarks.js
- docs/src/pages/components/selects/MultipleSelectCheckmarks.tsx
- docs/src/pages/components/selects/MultipleSelectChip.js
- docs/src/pages/components/selects/MultipleSelectChip.tsx
- docs/src/pages/components/selects/MultipleSelectPlaceholder.js
- docs/src/pages/components/selects/MultipleSelectPlaceholder.tsx
Remove an extra word from the code comments in the Select component documentation.
> [docs] Remove extra word in Select component code example comments

- examples/nextjs-with-typescript/src/pages/_document.tsx
- examples/nextjs-with-typescript/src/utils/createEmotionCache.ts
- examples/nextjs/pages/_document.js
- examples/nextjs/src/createEmotionCache.js
Just added a comment in the next.js examples to add the prepend option if using cssmodules as per #29648
> [docs] Add cssmodule injection order comments to Nextjs example

- docs/pages/careers.tsx
- docs/public/_redirects
- docs/src/modules/components/Link.tsx
- docs/src/pages/getting-started/faq/faq.md
- docs/src/pages/guides/routing/routing.md
- framer/Material-UI.framerfx/README.md
- packages/mui-codemod/README.md
- packages/mui-codemod/src/v1.0.0/svg-icon-imports.js
We are exploring having help from an SEO agency. digitalmarketingagency.com had a look at our domain and found a few issues.
> [website] Fix SEO issues

- docs/src/modules/components/AppFrame.js
- docs/src/modules/components/AppNavDrawer.js
- docs/src/modules/components/DemoToolbar.js
> [core] Fix warning in dev mode

- docs/src/pages/components/breadcrumbs/breadcrumbs.md
> [docs] Fix Breadcrumb description

- packages/mui-material/src/locale/index.ts
> [i18n]: improve viVN locale

- .github/workflows/close-incomplete-inactive.yml
Same as https://github.com/mui-org/material-ui-x/pull/3029, we tried it, it seems to work great.
> [core] Automatically close issues that are incomplete and inactive

- docs/pages/about.tsx
> [docs] Location change of Sebastian

- README.md
Seems like a simple typo / fat finger
> Remove extra </p> from header of README.md

- docs/src/pages/guides/migration-v4/migration-v4.md
> [docs] Add missing quote in migration docs

- packages/mui-lab/README.md
Fixes https://github.com/mui-org/material-ui/issues/30520
> [docs] Adding peer dependencies explanation on @mui/lab README.md

- docs/src/modules/components/ComponentLinkHeader.js
Fix https://github.com/mui-org/material-ui-x/pull/3606#issuecomment-1011288687
https://deploy-preview-30593--material-ui.netlify.app/components/buttons/
> [docs] Fix integration with MUI X

- .github/renovate.json
Same as https://github.com/mui-org/material-ui-x/pull/3645. I have listed upgrading node in https://github.com/mui-org/material-ui/issues/30660.
Closes #30645
> [core] Renovate should not try to update node

- framer/Material-UI.framerfx/package.json
- packages/mui-base/package.json
- packages/mui-docs/package.json
- packages/mui-icons-material/package.json
- packages/mui-joy/package.json
- packages/mui-lab/package.json
- packages/mui-material-next/package.json
- packages/mui-material/package.json
- packages/mui-private-theming/package.json
- packages/mui-styled-engine/package.json
- packages/mui-styles/package.json
- packages/mui-system/package.json
- packages/mui-utils/package.json
Same as #29283, the root cause was already fixed in #29303.
> [core] Revert changes to peer dependencies

- package.json
Fixed incorrect version number
> [core] Correct version in package.json

- docs/src/modules/components/AppNavDrawer.js
- docs/src/modules/components/AppNavDrawerItem.js
- docs/src/pages.ts
Tested this branch with https://github.com/mui-org/material-ui-x/pull/3515.
> [docs] Update doc structure for X components

- docs/src/pages/components/app-bar/ResponsiveAppBar.js
- docs/src/pages/components/app-bar/ResponsiveAppBar.tsx
> [docs] Close user menu on click in ResponsiveAppBar demo

- docs/src/pages/guides/migration-v4/migration-v4.md
https://deploy-preview-30616--material-ui.netlify.app/guides/migration-v4/#typography
> [docs] Add a missing bracket in the migration-v4 guide

- docs/src/route.ts
> [docs] Use new URLs when `enable_redirects` is true

- packages/mui-base/src/SliderUnstyled/useSlider.ts
> [SliderUnstyled] Improve typings on some internal utils

- docs/pages/blog.tsx
- docs/src/components/home/StartToday.tsx
- docs/src/featureToggle.js
- docs/src/modules/components/TopLayoutBlog.js
Enable the blog index page to release https://github.com/mui-org/material-ui/pull/30598.
The changes is cherry-pick from https://github.com/mui-org/material-ui/pull/30668
---
> [blog] Enable blog index

- docs/src/pages/guides/migration-v4/migration-v4.md
A little mistake for tss-react useStyles() import
> [docs] Update migration-v4.md

- packages/mui-material/src/FormHelperText/FormHelperText.js
- packages/mui-material/src/InputAdornment/InputAdornment.js
- packages/mui-material/src/OutlinedInput/NotchedOutline.js
- packages/mui-material/src/Select/SelectInput.js
> [TextField] Remove usage of dangerouslySetInnerHTML

- docs/src/pages/components/popper/ScrollPlayground.js
> [docs] Fix typo in the Popper ScrollPlayground demo

- docs/translations/translations.json
> [docs] Fix typo in ad fallback

- scripts/releaseChangelog.js
- scripts/testBuiltTypes.js
I am trying to learn how other big repositories/organisations do releases, coverage, translations, and was reading through the scripts folder to see how mui is doing it and found some typos along the way.
> [core] Fix typos in comments for scripts

- docs/src/pages/guides/interoperability/interoperability.md
> [docs] Improve the interoperability guide

- packages/mui-lab/src/TreeView/TreeView.js
- packages/mui-lab/src/TreeView/TreeView.test.js
Closes https://github.com/mui-org/material-ui/issues/30758
> [TreeView] Select node when key `Enter` is pressed

- .github/workflows/support-stackoverflow.yml
To match with https://github.com/mui-org/material-ui-x/pull/3680
> [core] Clarify the label, to match with MUI X

- docs/notifications.json
- docs/src/modules/components/Notifications.js
> [docs] Hotfix notification <b>

- test/utils/components.js
* `test/utils/components.js` lenght → **length**
> [test] Fix typo

- docs/pages/careers.tsx
https://deploy-preview-30867--material-ui.netlify.app/careers/
> [website] Closing the Developer Advocate role

- docs/src/pages/guides/typescript/typescript.md
Related to https://github.com/mui-org/material-ui-x/issues/479#issuecomment-1017241464. The minimum configuration is recommended, not required.
> [docs] Clarify the minimum configuration for TypeScript

- docs/packages/markdown/loader.js
- docs/packages/markdown/parseMarkdown.js
Preview: https://deploy-preview-30923--material-ui.netlify.app/getting-started/installation/
Steps to reproduce:
- go to https://mui.com/getting-started/installation/
- click "Edit this page" button at the top of the page
- see "Page not found" on GitHub
> [docs] Fix broken URL in "Edit this page" button

- docs/data/material/discover-more/roadmap/roadmap.md
Noticed it in deploy preview: https://deploy-preview-30924--material-ui.netlify.app/discover-more/roadmap/
It's not on production yet.
Before:
After:
> [docs] Fix broken roadmap table

- docs/pages/_app.js
- docs/src/modules/components/AppSettingsDrawer.js
Closes #30816
This is a regression from the redesign of the docs in v5.
> [docs] Fix force redirection to a different locale

- packages/mui-material/src/styles/index.d.ts
> [Typescript] Added TypeText declaration to the exports file

- docs/src/components/banner/AppFrameBanner.tsx
- docs/src/components/banner/AppHeaderBanner.tsx
- docs/src/components/banner/TableOfContentsBanner.tsx
- docs/src/featureToggle.js
- docs/src/modules/brandingTheme.ts
- docs/src/modules/components/AppFrame.js
Focusing on the Designer, Full-stack Engineer, and React Support Engineer roles.
- https://deploy-preview-31076--material-ui.netlify.app/
- https://deploy-preview-31076--material-ui.netlify.app/getting-started/example-projects/
> [website] Add banner for promoting priority open roles

- docs/src/components/home/ValueProposition.tsx
A real tiny PR to fix a grammar mistake.
> [website] Fix a grammar mistake

- docs/data/material/components/chips/chips.md
> [docs] Fix small typo in chips.md

- docs/data/material/getting-started/support/support.md
- docs/src/modules/components/Demo.js
- docs/src/pages/versions/versions.md
Closes https://github.com/mui/material-ui/issues/30778.
Took the liberty to remove what each version was mainly about (previously under the parenthesis) just because it looks cleaner and maybe there wasn't a strong need to explain that in there.
https://deploy-preview-31029--material-ui.netlify.app/versions/#supported-versions
> [docs] Update on the support page to account for v4 LTS support
