docs/pages/api-docs/divider.md
docs/src/pages/components/dividers/DividerText.js
docs/src/pages/components/dividers/DividerText.tsx
docs/src/pages/components/dividers/VerticalDividerText.js
docs/src/pages/components/dividers/VerticalDividerText.tsx
docs/src/pages/components/dividers/dividers.md
packages/material-ui/src/Divider/Divider.d.ts
packages/material-ui/src/Divider/Divider.js
packages/material-ui/src/Divider/Divider.test.js

This PR adds a feature to add text in Divider
Closes #21820

[Divider] Add text in divider

---

packages/material-ui/src/Tabs/Tabs.js
packages/material-ui/src/Tabs/Tabs.test.js

Closes #21854
**New behaviour:** Using the TAB key it is now possible to focus on the first tab of a Tab List with no active tabs. 
This improves accessibility through easier keyboard navigation.

[Tabs] Improve focus management on list with no active tabs

---

packages/material-ui/src/Tooltip/Tooltip.d.ts
packages/material-ui/src/Tooltip/Tooltip.js
packages/material-ui/src/Tooltip/Tooltip.test.js

Closes https://github.com/mui-org/material-ui/issues/17279
Meets "dismissable" in [WCAG 2.1 1.4.13](https://www.w3.org/TR/WCAG21/#content-on-hover-or-focus):
> A mechanism is available to dismiss the additional content without moving pointer hover or keyboard focus, unless the additional content communicates an input error or does not obscure or replace other content;
by listening to a global "Escape" keydown. This is similar to [SCR39](https://www.w3.org/WAI/WCAG21/Techniques/client-side-script/SCR39).
Follow-up:
To fully meet 1.4.13 we have to work on "hoverable" first which should also be explained in the docs.

[Tooltip] Meet dismissable WCAG criterion

---

packages/material-ui/src/Breadcrumbs/Breadcrumbs.js

Relying on the internal DOM structure can be brittle and subject to change (#22366). We can express the same intent with a ref on the targetted container.
While at it I did some testing with NVDA how this behavior affects user. My concern was that this could be disorienting since you only get the name of the newly focused link announced but not its context. However, neither focusing the `<ol>` or `<nav>` caused any announcement at all so I guess the current behavior is a decent approximation.
Generally it'd be interesting to look at accessible, expandable lists or how buttons controlling their parents should work.

[Breadcrumbs] More robust focus capture

---

packages/material-ui/src/Tab/Tab.js
packages/material-ui/src/Tabs/Tabs.test.js

[x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui-org/material-ui/blob/next/CONTRIBUTING.md#sending-a-pull-request).
Closes #22378

[Tabs] Don't fire onChange if current value

---

.gitattributes

An alternative to https://github.com/mui-org/material-ui/pull/22188. After this, we should be in much better shape, the stats and breakdown seem to match, more or less reality:
```
$ github-linguist
75.27%  JavaScript
24.71%  TypeScript
0.02%   HTML
```
I will be done with this problem.

[icons] Label them as vendored for GitHub

---

docs/package.json
docs/scripts/formattedTSDemos.js
docs/src/pages/premium-themes/onepirate/ForgotPassword.js
docs/src/pages/premium-themes/onepirate/ForgotPassword.tsx
docs/src/pages/premium-themes/onepirate/SignIn.js
docs/src/pages/premium-themes/onepirate/SignIn.tsx
docs/src/pages/premium-themes/onepirate/SignUp.js
docs/src/pages/premium-themes/onepirate/SignUp.tsx
docs/src/pages/premium-themes/onepirate/modules/components/AppBar.js
docs/src/pages/premium-themes/onepirate/modules/components/AppBar.tsx
docs/src/pages/premium-themes/onepirate/modules/components/Button.js
docs/src/pages/premium-themes/onepirate/modules/components/Button.tsx
docs/src/pages/premium-themes/onepirate/modules/components/Markdown.js
docs/src/pages/premium-themes/onepirate/modules/components/Markdown.tsx
docs/src/pages/premium-themes/onepirate/modules/components/Paper.js
docs/src/pages/premium-themes/onepirate/modules/components/Paper.tsx
docs/src/pages/premium-themes/onepirate/modules/components/Snackbar.js
docs/src/pages/premium-themes/onepirate/modules/components/Snackbar.tsx
docs/src/pages/premium-themes/onepirate/modules/components/TextField.js
docs/src/pages/premium-themes/onepirate/modules/components/TextField.tsx
docs/src/pages/premium-themes/onepirate/modules/components/Typography.js
docs/src/pages/premium-themes/onepirate/modules/components/Typography.tsx
docs/src/pages/premium-themes/onepirate/modules/form/validation.ts
docs/src/pages/premium-themes/onepirate/modules/theme.js
yarn.lock

Caught some regressions from #22295
Also reverted to `import * as React`

[docs] Transpile demo .ts files

---

docs/src/pages/guides/migration-v4/migration-v4.md
packages/material-ui/src/styles/adaptV4Theme.js
packages/material-ui/src/styles/adaptV4Theme.test.js

This PR adds the `theme.mixins.gutters()` which was removed with https://github.com/mui-org/material-ui/pull/22109 inside the `adaptV4Theme`,

[theme] Add theme.mixins.gutters() in adaptV4Theme

---

docs/src/pages/components/typography/typography.md

[Fontsource](https://github.com/fontsource/fontsource) went through a [breaking change](https://github.com/fontsource/fontsource/blob/master/CHANGELOG.md) to make the library more versatile for international users.
This update aims to clean up all the old documentation to be more reflective of that and easier to understand for the reader. Also, the repository moved to an org so the main link was edited to not waste a redirect.

[docs] Update Fontsource installation instructions

---

packages/material-ui/src/TextField/TextField.js

- [X ] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui-org/material-ui/blob/next/CONTRIBUTING.md#sending-a-pull-request).
The prop is only forwarded to the `FormControl` component, so no need to catch it. 
This should also be done on the `next` branch. Haven't found a section in the docs which explains to which branches (that is master or next) the new commits should land. Perhaps non-critical and new features should land only on `next`.

[TextField] Remove excessive catching of hiddenLabel prop

---

packages/material-ui/src/AccordionDetails/AccordionDetails.test.js
packages/material-ui/src/FormGroup/FormGroup.test.js
packages/material-ui/src/Icon/Icon.test.js
packages/material-ui/src/Paper/Paper.test.js

Replaces enzyme for react-testing-library in the `<AccordionDetails />` , `<FormGroup />`, `<Icon />`, `<Paper />`

[test] Migrate more components to react-testing-library

---

packages/material-ui/src/utils/useEventCallback.d.ts

- `useEventCallback` takes one function argument and returns a function of the same type.
- `Cancelable` is not used here. 
[useEventCallback.js](https://github.com/mui-org/material-ui/blob/next/packages/material-ui/src/utils/useEventCallback.js)

[core] Fix useEventCallback type

---

docs/src/modules/utils/helpers.js
docs/src/modules/utils/helpers.test.js

Working on this page: https://material-ui-x.netlify.app/components/data-grid/pagination/.

[docs] Improve export to CodeSandbox

---

examples/nextjs/src/Link.js

Forwarding replace prop to NextLink to override the default history push.
Relevant snippet from https://nextjs.org/docs/api-reference/next/link
`replace - Replace the current history state instead of adding a new url into the stack. Defaults to false`

[docs] Improve next.js example

---

docs/pages/api-docs/modal.md
docs/pages/api-docs/portal.md
docs/src/pages/guides/migration-v4/migration-v4.md
packages/material-ui/src/Modal/Modal.d.ts
packages/material-ui/src/Modal/Modal.js
packages/material-ui/src/Modal/Modal.test.js
packages/material-ui/src/Portal/Portal.d.ts
packages/material-ui/src/Portal/Portal.js
packages/material-ui/src/Portal/Portal.test.js

- [core] Remove `onRendered` from Modal and Portal
Depending on your use case either use a [callback ref](https://reactjs.org/docs/refs-and-the-dom.html#callback-refs) on the child element or an effect hook in the child component.
Planned removal (see #20012) and https://github.com/mui-org/material-ui/pull/16262#discussion_r294750748 for context.
We haven't had any use case internally and for app code callback refs and effect hooks exist.

[core] Remove onRendered from Modal and Portal

---

docs/src/pages/components/menus/ContextMenu.js
docs/src/pages/components/menus/ContextMenu.tsx

Closes #19145
[new contextmenu demo](https://deploy-preview-22463--material-ui.netlify.app/components/menus/#context-menu)
Closer to how native context menus behave in chrome 84 with ubuntu 18.04. It's missing that right click on a contextmenu item acts like a click but I couldn't make it work. Might require more involved work.
Simplified types along the way.

[docs] Close context menu if repeated

---

docs/package.json
yarn.lock

Fixes [GHSA-ccrp-c664-8p4j](https://github.com/advisories/GHSA-ccrp-c664-8p4j) for which dependabot could not create an automatic update. The update should've been trivial. I went ahead and reported the issue to GitHub.

[docs] Bump markdown-to-jsx

---

.circleci/config.yml
azure-pipelines.yml
packages/material-ui/scripts/rollup.config.js
scripts/react-next.diff
scripts/sizeSnapshot/webpack.config.js

Since this is on track to become the default in Babel 8 we should try it out periodically. Since it's only available in React 17 we can use existing scripts. I extended running with `react@next` to our azure pipeline which is responsible for bundle size tracking. 
~I'm mostly interested in the bundle size overhead due to effectively bundling two APIs for creating React elements.~ Since we also consider `react` as external (effectively ignoring it in the bundle size output) we should apply to `react/jsx-runtime`. Once we tree-shake the actual `react` module (e.g. `import { useMemo } from 'react'` we should include `react` and `react/jsx-runtime`.
[Babel announcement](https://babeljs.io/blog/2020/03/16/7.9.0#a-new-jsx-transform-11154-https-githubcom-babel-babel-pull-11154)

[core] Try out new JSX transform where available

---

packages/material-ui/src/Paper/Paper.js
packages/material-ui/src/Paper/Paper.test.js

Fix https://github.com/mui-org/material-ui/issues/20064

[Paper] Display elevation warning when rendering

---

docs/src/pages/landing/Users.js

[docs] Change "Let Us Know" button URL

---

packages/material-ui/src/Paper/Paper.test.js
packages/material-ui/src/styles/createMuiTheme.js

Resolves https://github.com/mui-org/material-ui/pull/22494#discussion_r484047502

[core] Remove references to other objects from created theme

---

docs/src/pages/components/autocomplete/GoogleMaps.tsx

Hi all
Copying the demo into our project was causing issues with the newest typescript version.
We were receiving: 
```bash
Failed to compile.
./src/components/placesAutoComplete.tsx
Syntax error: Cannot read property 'map' of undefined (0:undefined)
```
By separating the interfaces, we were able to resolve this issue and successfully build our project.
Keep up the great work Material-UI team! You guys are awesome!

[Autocomplete] Fix interfaces in the Google Maps demo

---

packages/material-ui-lab/src/Skeleton/Skeleton.js
packages/material-ui/src/styles/createSpacing.d.ts
packages/material-ui/src/styles/createSpacing.test.js
packages/material-ui/src/styles/index.js
packages/material-ui/src/styles/shape.d.ts

Minor tweaks to the createMuiTheme TypeScript declarations to allow non-"px" (string) values to border-radius and when using an array of spacing values.
Thanks!

[theme] Allow spacing and border radius with CSS unit

---

docs/src/modules/components/AppSearch.js
packages/material-ui/src/Unstable_TrapFocus/Unstable_TrapFocus.js
packages/material-ui/src/Unstable_TrapFocus/Unstable_TrapFocus.test.js

Apply https://github.com/mui-org/material-ui/pull/22376#discussion_r478378143. I have tested it in IE 11.
For reference: https://github.com/facebook/react/blob/90d212d326d8bb8f5ee414801db37e688d585712/packages/react-dom/src/events/SyntheticEvent.js#L281.

[core] Remove usage of deprecated .keyCode

---

docs/pages/api-docs/accordion-summary.md
docs/src/pages/guides/migration-v4/migration-v4.md
packages/material-ui/src/AccordionSummary/AccordionSummary.d.ts
packages/material-ui/src/AccordionSummary/AccordionSummary.js
packages/material-ui/src/AccordionSummary/AccordionSummary.test.js

This approach is already used in: PaginationItem, Button, ListItem. Hopefully, it will avoid bugs and is more bundle size efficient
- [Accordion] Rename `focus` to `focusVisible` for consistency:
```diff
<Accordion
classes={{
-    focused: 'custom-focus-visible-classname',
+    focusVisible: 'custom-focus-visible-classname',
}}
/>
```
---

[Accordion] Normalize focusVisible logic

---

packages/material-ui-lab/src/ToggleButton/ToggleButton.js
packages/material-ui/src/Button/Button.js
packages/material-ui/src/Fab/Fab.js

I think that the underlying issue was solved with:
https://github.com/mui-org/material-ui/blob/ad558cb69c227976be1b6be60d291daf9504a22f/packages/material-ui/src/ButtonBase/ButtonBase.js#L38-L39
It's one less aspect to worry about when making overrides.

[Button] Remove dead code

---

docs/src/modules/components/Demo.js
docs/src/modules/components/MarkdownDocs.js

Ads are meant to sustain the MIT licensed code. I don't think that it makes sense to keep them for code released under a paid commercial license. This change allows https://github.com/mui-org/material-ui-x to disable ads, where relevant.
Usage example:
```diff
diff --git a/docs/pages/components/alert.js b/docs/pages/components/alert.js
index caeeb16f23..54f9f2bec9 100644
--- a/docs/pages/components/alert.js
+++ b/docs/pages/components/alert.js
@@ -11,7 +11,7 @@ const requireRaw = require.context(
);
export default function Page({ demos, docs }) {
-  return <MarkdownDocs demos={demos} docs={docs} requireDemo={requireDemo} />;
+  return <MarkdownDocs demos={demos} docs={docs} disableAd requireDemo={requireDemo} />;
}
Page.getInitialProps = () => {
diff --git …
```

[docs] Option to disable ads

---

docs/public/_redirects

For https://github.com/mui-org/material-ui-x/pull/266/files#diff-0b8d9dbd68e750b2c3a43bf565c6b70aR33. Create an indirection so we can later change the destination URL.

[docs] Add redirection for links published on npm

---

packages/material-ui-lab/src/Rating/Rating.js
packages/material-ui/src/Chip/Chip.js
packages/material-ui/src/Tab/Tab.js

Part of #22532 & #19343
I've found this code snippet, what should I do with it? https://github.com/mui-org/material-ui/blob/next/packages/material-ui/src/InputBase/InputBase.js#L20
Where does `0.42` come from?

[theme] Using disabled opacity from the theme

---

packages/material-ui-lab/src/Rating/Rating.js

When experimenting with customization I found these styles to be problematic. I couldn't determine how they're used since the docs don't show a visual difference. They might be helpful for some customizations but if they're not necessary for the default usage and not required for any documented use case we might as well get rid of them. They can always be restored with customization.
If they're required we should document it.

[Rating] Explain some styles in code comments

---

package.json
packages/material-ui-lab/src/Rating/Rating.test.js
test/karma.tests.js
yarn.lock

Codifies current behavior of `Rating` in native `<form>` elements in tests. Includes documentation how `Rating` behaves different to a native `<input />`.
I think we should specify at some point how this component should behave in a form at which point we can leverage this test suite.
In the end I'd like to extend this to a form integration test suite similar to our [`describeConformance` 
helper](https://github.com/mui-org/material-ui/blob/40ecac1a4ec826b8300ac4f8c0ec5d93f0c09acd/test/utils/describeConformance.js). Forms are fairly common in web development so ensuring a good integration story should be a priority. 
See also https://github.com/mui-org/material-ui/issues/15585. It's not about maintaining form integration but being directly aware of it.

[Rating] Add form integration test suite

---

docs/pages/api-docs/rating.md
docs/src/pages/components/rating/SimpleRating.js
docs/src/pages/components/rating/SimpleRating.tsx
packages/material-ui-lab/src/Rating/Rating.d.ts
packages/material-ui-lab/src/Rating/Rating.js
packages/material-ui-lab/src/Rating/Rating.test.js

**BREAKING CHANGE:**
Customization of pristine label
```diff
-input:focus + .MuiRating-pristine {
+.MuiRating-labelEmptyValueActive {
top: 0;
bottom: 0;
position: absolute;
outline: 1px solid #999;
width: 100%;
}
```
Preliminary change which isn't required for this change but aids communication of intent: Replace `pristine` with `empty value`.
Pristine is an existing term in forms and means "untouched" or "unchanged". Right now keep using a class named `pristine` even if the user has interacted with the input. This can be confusing.
Actual change:
We usually try to use class names for styling. This allows easier customization via `classes` API and reduces specificity wars. However, previously styling of the Rating when no rating was given required a combination of class name, sibling and …

[Rating] Simpler customization of active "no value" styles

---

docs/next.config.js
docs/src/modules/utils/getDemoConfig.js
docs/src/modules/utils/helpers.js
docs/src/modules/utils/helpers.test.js

When creating a codesandbox from a demo in a netlify deploy preview i.e. deployed PRs we'll now use the packages built from the same PR. Before you would always create demos using the latest published version on NPM. 
I could've used this a couple of times in the past when doing extensive manual testing i.e. manual e2e testing. Our capabilities are already limited for local testing but you could always work around it. It's more a convenience functionality when reviewing PRs.
Downside: 
- deploy preview behaves different than actual published docs
- can be confusing when docs deploy finishes before codesandbox
Alternative:
Leave original functionality untouched but add an extra button in the "misc menu" for creating the demo using codesandbox deploys.

[docs] Use codesandbox deploy for demos created from deploy previews

---

.circleci/config.yml
.github/workflows/maintenance.yml
azure-pipelines.yml

This is safer since we only ever added one new branch as a long-living branch while it's much more likely to accidentally push a new, large branch to the `upstream` remote (this repository). 
We don't cancel older pipelines if new commits are pushed to branches on this repo (so that we know that merging these commits produce a green build). We previously ignored known branches but #22620 and #22618  used a different naming scheme and queued hundreds of pipeline runs. Maybe we can cancel these via API.
For future self:
- cancel jobs on a branch script: https://gist.github.com/eps1lon/9c822429bffb5db5a3f221dd00fea842
- workflows can still be considered running even if all underlying jobs are cancelled.

[test] Only run on push for master/next

---

packages/material-ui/src/Tabs/Tabs.js
packages/material-ui/src/Tabs/Tabs.test.js

Change scrolling behaviours for tabs to scroll by the width of visible elements as per @mnajdova and @oliviertassinari instructions.
Closes #22592

[Tabs] Only scroll the visible tabs

---

docs/src/pages/components/autocomplete/autocomplete.md

Closes #20068.
Basically implements the suggested documentation updates detailed in this comment: https://github.com/mui-org/material-ui/issues/20068#issuecomment-600915331

[docs] Add additional context to Autocomplete asynchronous documentation

---

packages/material-ui-lab/src/Rating/Rating.js
packages/material-ui-lab/src/Rating/Rating.test.js

Reverts behavior introduced by https://github.com/mui-org/material-ui/pull/22606. Since native radios/checkboxes don't support readonly either (as well as our Radio/Checkbox component) we should work on this with a more holistic approach based off of real-world use cases. See https://github.com/mui-org/material-ui/issues/17043.
Reworked the test suite based on the fact that `name` is optional and codified current behavior of `<Rating readOnly />` in tests.

[Rating] Treat read-only as image

---

docs/src/pages/components/icons/icons.md
packages/material-ui-lab/src/Autocomplete/Autocomplete.test.js
packages/material-ui-lab/src/Pagination/Pagination.test.js
packages/material-ui-lab/src/SpeedDialIcon/SpeedDialIcon.test.js
packages/material-ui/src/Avatar/Avatar.test.js
packages/material-ui/src/Breadcrumbs/Breadcrumbs.test.js
packages/material-ui/src/Checkbox/Checkbox.test.js
packages/material-ui/src/Chip/Chip.test.js
packages/material-ui/src/MobileStepper/MobileStepper.test.js
packages/material-ui/src/Radio/Radio.test.js
packages/material-ui/src/StepIcon/StepIcon.test.js
packages/material-ui/src/StepLabel/StepLabel.test.js
packages/material-ui/src/TabScrollButton/TabScrollButton.test.js
packages/material-ui/src/TableSortLabel/TableSortLabel.test.js
packages/material-ui/src/Tabs/Tabs.test.js
packages/material-ui/src/utils/createSvgIcon.js

Closes #22622
Replaces the `data-mui-test` attribute on icons with a `data-testid` attribute.
The `yarn run test` command seemed to pass locally after modifying various assertions that relied on the `data-mui-test` attribute to instead rely on the `data-testid` attribute

[icons] Expose a data-test-id attribute on all svg icons

---

.circleci/config.yml

Branch filters are not as granular as with azure. We can't differentiate between pull requests and pushes with the branch name. Only PRs from other remotes follow the `pull/*` branch naming scheme.
The current `only` **and** old `ignore` didn't make sense since it would've prevented **any** CircleCI run (which we currently see on dependabot PRs). 
CircleCI should still auto-cancel builds on any branch but the default branch. If we continue to see large queues for the `l10n_*` branches then we should contact support.
Ideally we want:
- build every commit for `master` and `next`
- build the latest commit for open PRs
So `l10n_next` would only build once a PR is open and auto-cancel on new commits. This is how azure pipelines and netlify deploys work so I don't understand why CircleCI works …

[test] Run CircleCI anytime

---

packages/material-ui/src/TabScrollButton/TabScrollButton.d.ts

I have MUI used as a peerDependency in a project and getting this error when trying to compile my library: 
```
ERROR in [at-loader] ./node_modules/@material-ui/core/TabScrollButton/TabScrollButton.d.ts:5:11 
TS2709: Cannot use namespace 'StandardProps' as a type.
```
As far as I understand when StandardProps is excluded from "outside" module for compiler it looks like a namespace with a value in it and it cannot expand it and use. Replacing it with a local reference (like the rest of the modules do) fixes this problem.

[Tabs] Fix TabScrollButton using absolute path

---

docs/public/_redirects
docs/src/pages/components/grid/grid.md

This has been a point of concern early on in the development of the data grid. Historically, in the previous generation of enterprise UI components, the term "grid" was used as a shorthand for data grid. However, in Material-UI, we use it with a meaning closer to a layout grid.

[docs] Avoid confusion between layout grid and data grid

---

docs/src/modules/components/Demo.js
docs/src/pages/components/buttons/ButtonBase.js
docs/src/pages/components/buttons/ButtonBase.tsx
docs/src/pages/components/dialogs/ResponsiveDialog.js
docs/src/pages/components/dialogs/ResponsiveDialog.tsx
docs/src/pages/components/dialogs/dialogs.md
docs/src/pages/components/snackbars/FabIntegrationSnackbar.js
docs/src/pages/components/snackbars/FabIntegrationSnackbar.tsx
docs/src/pages/customization/breakpoints/MediaQuery.js
docs/src/pages/customization/breakpoints/MediaQuery.tsx
docs/src/pages/customization/breakpoints/breakpoints.md
docs/src/pages/guides/migration-v4/migration-v4.md
docs/src/pages/premium-themes/onepirate/modules/views/ProductCategories.js
docs/src/pages/premium-themes/onepirate/modules/views/ProductCategories.tsx
packages/material-ui/src/Tabs/Tabs.js
packages/material-ui/src/styles/createBreakpoints.js
packages/material-ui/src/styles/createBreakpoints.test.js

Closes https://github.com/mui-org/material-ui/issues/13448 Part of https://github.com/mui-org/material-ui/issues/20012
There are also usages of `breakpoints.down()` & `breakpoints.between()` in Dialog and HiddenCss, but I believe these should not be changed. The reasons are - the `Dialog` invokes the `down()` method with number which behavior is not changed; `HiddenCss` is following the new convention.
Seems like this is the first change that will actually require implementing `createMuiThemeV4` utility instead of adapter, as we need to change the theme after it has been created. Should we start with this change as part of this PR? I would say yes if we want to fully say, we will support the v4 theme structure under deprecation in v5

[theme] Improve breakpoints definitions

---

packages/material-ui-lab/package.json
packages/material-ui-lab/src/Alert/Alert.js
packages/material-ui-lab/src/Pagination/Pagination.js
packages/material-ui-lab/src/PaginationItem/PaginationItem.js
packages/material-ui-lab/src/Skeleton/Skeleton.js
packages/material-ui-lab/src/TimelineDot/TimelineDot.js
packages/material-ui/src/styles/index.js

Fixes using undeclared dependencies in `@material-ui/lab`:
---

[lab] Fix transitive dependencies in @material-ui/lab

---

packages/material-ui-lab/src/Autocomplete/Autocomplete.test.js
packages/material-ui-lab/src/useAutocomplete/useAutocomplete.js
packages/material-ui-lab/src/useAutocomplete/useAutocomplete.test.js

I also added a sanity test for filtering without error on an empty option set
fix #22302

[Autocomplete] Fix accessibility issue with empty option set

---

docs/src/pages/components/autocomplete/GitHubLabel.tsx
docs/src/pages/components/tree-view/ControlledTreeView.tsx
framer/Material-UI.framerfx/code/Tabs.tsx
framer/scripts/templates/tabs.txt
packages/material-ui-lab/src/Rating/Rating.d.ts
packages/material-ui-lab/src/SliderStyled/SliderStyled.spec.tsx
packages/material-ui-lab/src/TreeView/TreeView.d.ts
packages/material-ui-lab/src/useAutocomplete/useAutocomplete.d.ts
packages/material-ui/src/Accordion/Accordion.spec.tsx
packages/material-ui/src/BottomNavigation/BottomNavigation.spec.tsx
packages/material-ui/src/FormControlLabel/FormControlLabel.d.ts
packages/material-ui/src/Select/Select.d.ts
packages/material-ui/src/Select/SelectInput.d.ts
packages/material-ui/src/Slider/Slider.spec.tsx
packages/material-ui/src/Tabs/Tabs.spec.tsx

Follow-up on #21552.
```diff
-<Component onX={(event: React.ChangeEvent<{}>) => {}} />
+<Component onX={(event: React.SyntheticEvent) => {}} />
```
for:
- `AutoComplete` (`onChange`, `onHighlightChange`, `onOpen`)
- `FormControlLabel` (`onChange`)
- `Rating` (`onChange`)
- `Select` (`onClose`, `onOpen`)
- `TreeView` (`onNodeFocus`, `onNodeToggle`)

[core] Replace ChangeEvent<{}> with SyntheticEvent

---

docs/src/modules/components/Head.js
docs/src/pages/getting-started/usage/usage-de.md
docs/src/pages/getting-started/usage/usage-es.md
docs/src/pages/getting-started/usage/usage-fr.md
docs/src/pages/getting-started/usage/usage-ja.md
docs/src/pages/getting-started/usage/usage-pt.md
docs/src/pages/getting-started/usage/usage-ru.md
docs/src/pages/getting-started/usage/usage-zh.md
docs/src/pages/getting-started/usage/usage.md
examples/cdn/index.html
examples/create-react-app-with-typescript/public/index.html
examples/create-react-app/public/index.html
examples/gatsby/plugins/gatsby-plugin-top-layout/TopLayout.js
examples/nextjs-with-typescript/pages/_app.tsx
examples/nextjs/pages/_app.js
examples/preact/public/index.html
examples/ssr/server.js
test/regressions/debug.html

This PR is in response to issue #22714, in which `minimum-scale` for the viewport can be an accessibility issue. This PR removes `minimum-scale` from all of the documentation and examples.
Closes #22714

[docs] Remove minimum-scale from meta viewport in docs

---

CHANGELOG.md
docs/src/pages/customization/spacing/spacing.md
docs/src/pages/guides/migration-v4/migration-v4.md

A continuation of the discussion on https://github.com/mui-org/material-ui/commit/bc4582572e4126b58cde67a4f357089b33ac5b8d#r42461020. From what I understand, our best option is to no support the previous case. Happy to consider alternatives.

[docs] Remove wrong migration instruction

---

docs/src/modules/components/Demo.js

Since #17831 the current Tooltip placement means tooltips will cover the demos. This is especially annoying if you get the source hint when first visiting the docs but tooltips hiding content is annoying generally. The space to the bottom fits a tooltip perfectly though it can hide potential ads and the source. In the case of ads I think visible demos are more important demos. For source code we only cover the first import line which is almost always the `react` import.
Aside: Bonus points for consistent formatting

[docs] Prevent toolbar tooltips overlapping demos

---

packages/material-ui/src/styles/cssUtils.js
packages/material-ui/src/styles/cssUtils.test.js

[theme] convertLength does not work for fromUnit !== 'px'

---

docs/next.config.js
docs/package.json
docs/src/pages/components/progress/CircularIntegration.js
docs/src/pages/components/progress/CircularIntegration.tsx
docs/src/pages/components/progress/DelayingAppearance.js
docs/src/pages/components/progress/DelayingAppearance.tsx
docs/src/pages/components/tables/DataTable.js
docs/src/pages/components/tables/DataTable.tsx
docs/src/pages/components/tables/tables.md
yarn.lock

The new demo: https://deploy-preview-22697--material-ui.netlify.app/components/tables/#data-table.
Made to help with https://github.com/mui-org/material-ui-x/pull/339 works.
Here, we used the package published on codesandbox-ci. cc @dtassone.

[docs] Add live demo with DataGrid

---

docs/src/modules/utils/helpers.js
docs/src/modules/utils/helpers.test.js

[docs] Add emotion dependencies in codesandbox examples

---

docs/pages/api-docs/slider-styled.md
docs/pages/api-docs/slider-unstyled.md
docs/pages/api-docs/slider.md
docs/src/pages/components/slider-styled/slider-styled.md
packages/material-ui-lab/src/SliderStyled/SliderStyled.d.ts
packages/material-ui-lab/src/SliderUnstyled/SliderUnstyled.d.ts
packages/material-ui/src/Slider/Slider.d.ts

We reference demos of a particula demo by manually declaring used components in front-matter blocks in the markdown pages.
The actual fix is just a one-liner: https://github.com/mui-org/material-ui/pull/22738/files#diff-b8af1751c5b229efa71dc077a7de41af. The rest is auto-generated.

[docs] Reference experimental slider demos correctly

---

packages/material-ui/src/Rating/Rating.test.js

We have a bunch of tests that fail in the CI on the same test:
> Rating - should select the empty input if value is null
After a ssh on the CI and using the default reporter, I get:
As it turns out the tests are close to the 2,000 ms timeout. In the above screenshot, we run at 1,871ms.
In my local environment, the tests run much faster <50ms. If you add console.time on the different steps of the test, you will find (for one run):
- render: 5ms
- getByRole: 105ms
- querySelector: 0.2ms
The following change should fix the flakiness of the CI. The alternatives are to increase the timeout for all the tests or to upgrade the machines we use (to have more resources).

[test] Solve 2000ms timeout

---

docs/src/modules/components/AppDrawer.js
docs/src/modules/components/AppFrame.js

Alternate to the perf improvements of #22780.
Profiler marked the `AppDrawer` as expensive (30ms render duration is very slow). `renderNavItems` created a fairly big _tree_ of elements (the nav) which took almost all of the render duration of `AppDrawer`. Luckily we can memoize that tree fairly easily.
A single run show performance increase from 70ms down to 30ms when opening the drawer with 6x CPU throttling.
Before
After

[docs] Improve perf when opening the drawer

---

packages/material-ui/src/Popper/Popper.js
packages/material-ui/src/Popper/Popper.test.js

[Popper] Use placement viewport instead of window 

---

docs/src/pages/components/autocomplete/CustomInputAutocomplete.js
docs/src/pages/components/autocomplete/CustomInputAutocomplete.tsx
packages/material-ui-lab/src/Autocomplete/Autocomplete.d.ts
packages/material-ui-lab/src/Autocomplete/Autocomplete.spec.tsx
packages/material-ui-lab/src/useAutocomplete/useAutocomplete.d.ts

Removes need of `@ts-expect-error` introduce in #22711 by building on top of #22749

[Autocomplete] Restrict component props in `renderInput`

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
docs/README.md
docs/src/modules/components/AppFooter.js
docs/src/modules/constants.js
docs/src/pages/customization/default-theme/default-theme.md
docs/src/pages/customization/globals/globals.md
docs/src/pages/customization/z-index/z-index.md
docs/src/pages/discover-more/changelog/changelog.md
docs/src/pages/discover-more/team/team.md
docs/src/pages/guides/localization/localization.md
docs/src/pages/guides/migration-v4/migration-v4.md
docs/src/pages/guides/minimizing-bundle-size/minimizing-bundle-size.md
docs/src/pages/guides/testing/testing.md
docs/src/pages/styles/advanced/advanced.md
docs/src/pages/styles/basics/basics.md
packages/material-ui/src/CssBaseline/CssBaseline.spec.tsx
test/README.md

1.  Use `blob/HEAD` instead of `blob/$CURRENT_DEFAULT_BRANCH` where we really only want the latest working version for dev-users.
2. Mark `blob/next` as `#default-branch-switch` where we need to do it manually when the link is deployed permanently and end-user facing.
3. Use permalinks for internal examples.

[docs] Reduce risk of 404 when changing the default branch

---

docs/next.config.js
docs/src/modules/utils/parseMarkdown.js
docs/src/modules/utils/parseMarkdown.test.js

In crowdin PRs we should deploy all locales for testing. This would've prevented current deploy failures due to #22752.
Specifically, #22752 introduced page descriptions (`<p class="description" />`) that had whitespace around the text ([`docs/src/pages/components/rating/rating-zh.md`](https://github.com/mui-org/material-ui/blob/c04bdacdf9fae388f0ef4894ac3783037ceb670f/docs/src/pages/components/rating/rating-zh.md#L10-L11)). If that whitespace included newlines they couldn't be easily matched. Luckily ES 5 introduced the "dotall" flag (`s`) for that exact use case which is available as of node 8.10. The matched text is trimmed to retain the previous behavior.

[docs] More robust description matcher

---

docs/src/pages/system/api/api.md

In my group's project we found that if we use, e.g. `paddingX`, it leaves the reader with no great way to find documentation if they're unfamiliar with the longhand syntax.

[docs] Add longhand system API props to docs

---

docs/next.config.js

We have some components that are duplicated, there is both a .tsx and .js version. I believe that in these cases, we should bundle the .tsx version, not the .jsx version. You can try the implications when loading http://0.0.0.0:3000/premium-themes/onepirate/forgot-password/ and editing the JS and TS version of `docs/src/pages/premium-themes/onepirate/ForgotPassword` to see what happens.

[docs] Resolve .tsx first

---

CHANGELOG.md
docs/src/pages/customization/palette/palette.md
docs/src/pages/guides/migration-v4/migration-v4.md
packages/material-ui-lab/src/SliderStyled/SliderStyled.js

[docs] Fix type vs. mode and capitalization of createMuiTheme

---

docs/src/modules/components/AppDrawer.js
docs/src/modules/components/AppDrawerNavItem.js
docs/src/modules/components/Link.js
docs/src/pages.js

It was an opportunity to work on 3 problems at the same time:
The warning was present on all the pages and was buried all the other issues (x81)
https://validator.w3.org/nu/?doc=https%3A%2F%2Fnext.material-ui.com%2Fcomponents%2Fslider-styled
There are still 3 issues related to navigation (edit page, previous page, and next page) but that's for another day.
It's closer to the Material Design specification https://material.io/components/navigation-drawer. I also wanted the design to better support more levels of nesting and more items.
**Before**
**After**
I have used the following as inspiration too:
- https://stripe.com/docs/api/accounts
- https://tailwindcss.com/docs/upgrading-to-v1
- https://next.vuetifyjs.com/en/styles/content/
- https://mail.google.com
- …

[docs] Improve the left side-nav

---

packages/material-ui/src/index.d.ts
packages/material-ui/src/index.js

Closes #22877 
update export statement to easy access skeleton as mention in the issue.

[Skeleton] Importing with named export

---

docs/pages/api-docs/form-control.md
packages/material-ui/src/FormControl/FormControl.d.ts
packages/material-ui/src/FormControl/FormControl.js
packages/material-ui/src/InputBase/InputBase.test.js

[docs] Improve FormControl duplication warning

---

docs/src/pages/guides/composition/composition.md
packages/material-ui/src/SpeedDialAction/SpeedDialAction.test.js
packages/material-ui/src/Tooltip/Tooltip.js
packages/material-ui/src/Tooltip/Tooltip.test.js

[Tooltip] Improve docs and warning for custom children

---

docs/src/pages/components/switches/CustomizedSwitches.js
docs/src/pages/components/switches/CustomizedSwitches.tsx
packages/material-ui/src/Button/Button.js
packages/material-ui/src/Fab/Fab.js

I have noticed the wrong synchronization in the transition looking at #22878.
**Before**
**After**

[Button] Improve loading transition

---

packages/material-ui/src/utils/scrollLeft.js

Chrome 85 introduced a bug with how scrollLeft is computed for RTL. This was fixed in the original source of this module -- https://github.com/alitaheri/normalize-scroll-left/pull/6. The bug has been open for ~29 days, so not clear if it will be fixed anytime soon - https://bugs.chromium.org/p/chromium/issues/detail?id=1123301. This particular fix is backwards/forwards compatible according to the original PR. 
Example of bug's impact: This bug is actually causing the RTL implementation of Scrollable Tabs to be broken in production when using a right-to-left language: https://material-ui.com/components/tabs/#scrollable-tabs
A better longterm fix would be to actually import https://github.com/alitaheri/normalize-scroll-left as a dependency, but I didn't go that route since I wasn't sure if …

[Tabs] Fix RTL scrollbar with Chrome 85

---

packages/material-ui/src/Button/Button.js
packages/material-ui/src/Button/Button.test.js
packages/material-ui/src/ButtonBase/ButtonBase.test.js

You can observe the issue on https://validator.w3.org/nu/?doc=https%3A%2F%2Fnext--material-ui.netlify.app%2Fcomponents%2Fslider-styled%2F.
The first error (2.) originates from:
https://github.com/mui-org/material-ui/blob/4824c9e08dd665e2f2b1b04465a67101daca87a1/docs/src/modules/components/EditPage.js#L17-L32
The change fixes the three occurrences.
A bit related to #21924. I had a look [at Bootstrap](https://getbootstrap.com/docs/4.5/components/buttons/), they transition the same 4 CSS properties.

[Button] Fix invalid type value

---

docs/src/pages/components/grid/grid.md

As in https://github.com/mui-org/material-ui/issues/18225#issuecomment-550437836 and https://github.com/mui-org/material-ui/issues/18225#issuecomment-550482809
Closes #18225

[Grid] Clarify document about direction column limitation

---

packages/material-ui-lab/src/SliderStyled/SliderStyled.js

Noticed this when working on the new Slider spec.
Before:
After:

[SliderStyled] Fix mark label alignment on coarse pointer devices

---

docs/pages/api-docs/accordion-summary.md
docs/src/pages/guides/migration-v4/migration-v4.md
packages/material-ui/src/AccordionSummary/AccordionSummary.d.ts
packages/material-ui/src/AccordionSummary/AccordionSummary.js
packages/material-ui/src/AccordionSummary/AccordionSummary.test.js

- [Accordion] Remove `IconButtonProps` prop from AccordionSummary.
The component renders a `<div>` element instead of an IconButton.
The prop is no longer necessary.
---
As per https://github.com/mui-org/material-ui/issues/22804#issuecomment-701046569
---------------
@oliviertassinari 
> However for this demo: https://next.material-ui.com/components/accordion/#additional-actions, we likely want it.
I don't see that this demo is relevant to this change. This demo talks about interactive elements put in the children of the `AccordionSummary` not in the `iconElement`.
---------------------
I think the wrapping element around `iconElement` should still be present, but it's only function will be to fix the `iconElement` to the right and to rotate it around "z-axis" (top/bot), so I removed the …

[Accordion] Replace IconButton wrapper with div

---

yarn.lock

Uses:
- https://github.com/babel/babel/releases/tag/v7.10.5
- https://github.com/babel/babel/releases/tag/v7.11.1
- https://github.com/babel/babel/releases/tag/v7.11.2
- https://github.com/babel/babel/releases/tag/v7.11.3
- https://github.com/babel/babel/releases/tag/v7.11.4
- https://github.com/babel/babel/releases/tag/v7.11.5
- https://github.com/babel/babel/releases/tag/v7.11.6
Also fixes a missing peer warning from `babel-plugin-tester`

Bump @babel/* to 7.11.6

---

packages/material-ui-utils/src/elementAcceptingRef.test.tsx
packages/material-ui-utils/src/elementTypeAcceptingRef.test.tsx
scripts/react-next.diff

Directly applies #22800 and #22890. I've seen these tests failing in our current pipeline during #22814.

[test] Apply lazy forwardRef fix

---

docs/src/modules/components/AppSearch.js

Closes #22901
For non-SSR language, internal search fall back to English.
in Japanese (non-SSR)
in Chinese (SSR)

[docs] For non-SSR language, internal search fall back to English

---

packages/material-ui/src/Tabs/TabIndicator.test.js

[test] Migrate TabIndicator to react-testing-library

---

packages/material-ui/src/Select/Select.d.ts
packages/material-ui/src/Select/Select.spec.tsx
packages/material-ui/src/Select/SelectInput.d.ts

It adds the opportunity to type the value of the Select component.

[Select] Add generic support for value

---

packages/material-ui/src/Autocomplete/Autocomplete.test.js

Removes indirection of having to look up what props are set (motivated by having to check out what `openOnFocus` is supposed to do in #20286). It's apparent from the current state of the test suite that these props aren't actually default props anymore.

[test] Autocomplete drop "defaultProps" pattern

---

packages/material-ui/src/NativeSelect/NativeSelectInput.test.js
packages/material-ui/src/Tabs/TabIndicator.test.js

Replaces enzyme for react-testing-library in the `<NativeSelectInput/>`
#22911

[test] Migrate NativeSelectInput to react-testing-library

---

packages/material-ui/src/Fade/Fade.test.js

[test] Migrate Fade to react-testing-library

---

packages/material-ui/src/Grow/Grow.test.js

[test] Migrate Grow to react-testing-library

---

packages/material-ui/src/CssBaseline/CssBaseline.test.js

[test] Migrate CssBaseline to react-testing-library

---

.codesandbox/ci.json
examples/create-react-app-with-typescript/package.json

1. Replace bare react template with our issue template
The react template isn't useful since you manually add the versions. Might as well start out with react.new
1. Use `HEAD` instead of `master`
Continuation of #22801

[test] Use appropriate templates for csb CI

---

docs/src/modules/components/Demo.js
docs/src/modules/utils/getDemoConfig.js

Includes the demo name in the codesandbox and page title. Also includes the currently used docs language for more accurate repros.
Note that this only works when the sandbox is opened in a new window. The integrated view has a non-descriptive UUID-like title. Possibly due to https://github.com/codesandbox/codesandbox-client/issues/4983.

[docs] Use demo name as codesandbox name

---

packages/material-ui/src/Autocomplete/Autocomplete.js
packages/material-ui/src/useAutocomplete/useAutocomplete.js

Closes #22705
I've implemented the solution from @oliviertassinari, I've checked it in IE11 and works fine now.

[Autocomplete] Fix virtualization example in IE 11

---

azure-pipelines.yml

The cached size of `docs/.next/cache` in azure pipelines is now at 3GB (takes 2min to restore) while a fresh build only creates a cache of 23MB.
The issue is that ever time yarn.lock changed it fell back to any previous cache. Since nextjs does not remove any cache files the cache only ever increased. 
There might be an argument to be made that nextjs should remove every untouched cache file but that's hard to tell without knowing how they cache their files.
Completely clearing it when `yarn.lock` changes is a good enough approximation of "clear it occasionally".

[test] Prevent nextjs build cache to grow indefinitely

---

packages/material-ui/src/TextField/TextField.test.js

[test] Migrate TextField to react-testing-library

---

packages/material-ui/src/Grow/Grow.test.js
packages/material-ui/src/ImageListItem/ImageListItem.test.js
packages/material-ui/src/MenuList/MenuList.test.js

- [ X] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui-org/material-ui/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).
#22911
I've also notice that I miss a `mount` function at `Grow`, so i include it in this pr

[test] Migrate MenuList and ImageListItem to react-testing-library

---

packages/material-ui/src/NativeSelect/NativeSelect.test.js

This pull request migrates the unit tests of the NativeSelect component to use React Testing Library.
#22911

[test] Migrate NativeSelect to react-testing-library

---

packages/material-ui/src/Fab/Fab.test.js

I migrated the last old tests to rtl.
#22911

[test] Migrate Fab to react-testing-library

---

docs/src/pages/system/basics/Emotion.js
docs/src/pages/system/basics/Emotion.tsx
docs/src/pages/system/basics/basics.md

[docs] Box & system cleanup

---

docs/src/pages/components/tree-view/BarTreeView.js
docs/src/pages/components/tree-view/BarTreeView.tsx

[TreeView] Use `alpha` color utility instead of deprecated `fade`

---

docs/src/pages/components/material-icons/SearchIcons.js

I have found the issue opening the page inside VSCode. The light mosaic in a dark theme was really ugly.
**Before**
**After**
**Before**
**After**

[docs] Improve icon preview color contrast

---

docs/src/pages/components/tree-view/tree-view.md
packages/material-ui-lab/src/TreeView/TreeView.js
packages/material-ui/src/utils/useEnhancedEffect.d.ts

[TreeView] Fix bundle size link and refactor array spreads

---

package.json
scripts/sizeSnapshot/webpack.config.js
yarn.lock

Resolves https://github.com/mui-org/material-ui/pull/22814#issuecomment-707362641
`yarn docs:dev` broke during work on https://github.com/mui-org/material-ui/pull/22814 when trying to track the modern bundle. We didn't used to track `/es` anyway. 
Don't mind the bundle size changes. They're noise from different chunking which results in changes of module concatenation.

[docs] Fix docs:dev

---

docs/src/pages/guides/localization/localization.md
packages/material-ui/src/locale/index.ts

Hello,
This PR adds support for Arabic localization https://material-ui.com/guides/localization/#localization
According to https://en.wikipedia.org/wiki/List_of_languages_by_number_of_native_speakers, Arabic is spoken by 280 millions.

[l10n] Add Arabic (ar_EG) locale

---

.mocharc.js
package.json
test/karma.conf.js
yarn.lock

Reverts the reporter part of #22924.
Unclear what the problem is but let's get this out of the way.

[test] Use dot reporter in CI

---

packages/material-ui/src/Autocomplete/Autocomplete.test.js
packages/material-ui/src/useAutocomplete/useAutocomplete.js

[Autocomplete] Fix autoHighlight synchronization

---

docs/src/pages/components/lists/AlignItemsList.js
docs/src/pages/components/lists/AlignItemsList.tsx
docs/src/pages/components/lists/SwitchListSecondary.js
docs/src/pages/components/lists/SwitchListSecondary.tsx
docs/src/pages/components/lists/VirtualizedList.js
docs/src/pages/components/lists/VirtualizedList.tsx

Avoid future cases like #23013

[docs] Don't suggest putting a Switch inside a ListItemSecondaryAction

---

docs/src/pages/styles/api/api.md

ThemeOptions contain "palette" instead of "color"
- [&check;] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui-org/material-ui/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

[docs] Change color to palette

---

packages/material-ui/src/ButtonBase/ButtonBase.test.js

[test] Migrate ButtonBase to react-testing-library

---

packages/material-ui-lab/src/SliderStyled/SliderStyled.test.js
packages/material-ui/src/ButtonBase/TouchRipple.test.js
packages/material-ui/src/Fade/Fade.test.js
packages/material-ui/src/ImageList/ImageList.test.js
packages/material-ui/src/styles/experimentalStyled.test.js
test/utils/initMatchers.ts

Examples:
`expect(element).toHaveInlineStyle({ width: '200px' })`
`expect(element).toHaveComputedStyle({ backgroundColor: 'rgb(255, 0, 0)' })`
Existing solutions for custom style matchers like `expect(style).to.have.property` and `expect(style.getPropertyValue('width')).to.equal('200px')` have a couple of downsides:
1. poor failure messages (too verbose for `property` or not descriptive for `to.equal` (which is bad in general without a message).
1. provide little explanation why they're failing (JSDOM being the common problem)
The new matcher 
1. has a concise syntax (just match against a property bag)
1. has a descriptive message (what is mismatching? what is the actual value? what is the expected value? From which element is the style taken?)
1. explains why something might be failing …

[test] Introduce toHaveInlineStyle and toHaveComputedStyle matcher

---

packages/material-ui/src/styles/experimentalStyled.test.js
test/utils/setupJSDOM.js

Should be reviewed without whitespace diff.
1. ~Get rid of "You have illegal escape sequence in your template literal" console message~
Leaving a FIXME
1. console.(warn|error) outside of if `it()` now throws
I don't know anymore if this was intentional or not. 
1. Move work in `experimentalStyled.test` into `before`
Tests should be side-effect free i.e. don't execute any code. 
If they do you'll have a hard time locating the issue. 
It also slows down the overall test suite when doing `--grep` because test runners have to evaluate the full test suite. But this is more of a "death-by-thousand-cuts" scenario

[test] Throw on console.(error|warn) outside of test

---

packages/material-ui-lab/src/AvatarGroup/AvatarGroup.js
test/karma.tests.js
test/utils/mochaHooks.js
test/utils/setupJSDOM.js

Should be safe now that we've dropped Safari < 13. Will start failing the test suite if we go back to Safari 10.
Polyfills root-level hooks for karma-mocha. We use dependency injection for `mocha` in the browser. Their browser build is not importable and from the issues I looked at in their repo (https://github.com/mochajs/mocha/issues/4278,  https://github.com/mochajs/mocha/issues/2448) they insist that this is fine.
Examples: 
- [test:unit](https://app.circleci.com/pipelines/github/mui-org/material-ui/24191/workflows/2563e702-c81d-495b-af0b-d571281f6e1a/jobs/186889)
- [test:browser](https://app.circleci.com/pipelines/github/mui-org/material-ui/24191/workflows/2563e702-c81d-495b-af0b-d571281f6e1a/jobs/186891)

[test] Enable failing unexpected console warn|error in browser tests

---

docs/src/pages/components/tooltips/tooltips.md

- [*] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui-org/material-ui/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).
Crowdin issue: https://crowdin.com/translate/material-ui-docs/3380/en-zhcn?filter=basic&value=17#q=140834

[docs] Fix wrong variable characters in tooltips

---

packages/material-ui/src/Autocomplete/Autocomplete.test.js
packages/material-ui/src/useAutocomplete/useAutocomplete.js

Closes: https://github.com/mui-org/material-ui/issues/23044
This fix tested on macOS/Chrome, Safari by local build.

[Autocomplete] Ignore keydown event until IME is confirmed

---

packages/material-ui/src/SwipeableDrawer/SwipeableDrawer.js

This PR removes dependency between `swipeAreaWidth` prop and the ready-for-dragging signal of drawer related to 
Closes #23037

[SwipeableDrawer] Decorrelate swipeAreaWidth and initial jumping amount

---

.browserslistrc
docs/src/pages/getting-started/supported-platforms/supported-platforms.md
docs/src/pages/guides/migration-v4/migration-v4.md
test/karma.conf.js

Seems like I forgot `ios_safari 12.2` in #22814. The other changes are due to new version releases (mainly Firefox ESR moving to 78).
[Safari 12 sits at 2% global usage](https://caniuse.com/usage-table). But other than IE 11 where we argue that this browser is mostly used in corporate enviornments (with an LTS license) iOS Safari 12 is used by actual people that would need to buy a new phone in order to upgrade to Safari 13. So I don't think the usage stats can solely be used as justification to drop it.
The unfortunate part is that this won't allow an all-in usage of PointerEvent. But we'll get there eventually.
The good part is that ImageList should function perfectly well in iOS Safari 12 looking at [`gap`](https://caniuse.com/mdn-css_properties_gap_grid_context) and …

[core] Add support for iOS Safari 12

---

packages/material-ui/test/integration/TableRow.test.js

[test] migrate TableRow tests to react-testing-library

---

packages/material-ui/src/Tooltip/Tooltip.js
packages/material-ui/src/Tooltip/Tooltip.test.js

Would've been funny if some component actually implemented `handleMouseMove`

[Tooltip] Fix followCursor preventing onMouseMove on children

---

examples/gatsby-theme/gatsby-config.js
examples/gatsby-theme/package.json
examples/gatsby-theme/src/pages/about.js
examples/gatsby-theme/src/pages/index.js

This PR updates the gatsby-theme example project to use `next` version of @material-ui/* packages. It adds the @emotion/* packages and the `gatsby-plugin-emotion` plugin.

[examples] Update gatsby-theme example to use @material-ui/* next 

---

packages/material-ui/src/Tooltip/Tooltip.js
packages/material-ui/src/Tooltip/Tooltip.test.js

Review by commit helps understand the refactoring process.
We're currently (sometimes) composing user-event handlers in the Tooltip event handlers. The current implementation is hard to parse (e.g. when coming back to the component after some time) and doesn't follow existing patterns.
I refactored it in a couple of steps:
1. Ignore event types in behavioral handlers (like `handleEnter` and `handleLeave`)
1. Actually handle events in `on*` props instead of handling behavior
1. compose handlers where appropriate (i.e. when overriding props in e.g. `children.props`) otherwise simply assign (e.g in `interactiveWrapperListeners`)
The only behavior that changed is the order of events for focus events (https://github.com/mui-org/material-ui/pull/23092/commits/cdbad40055504dfc3e769108833d3013b42e …

[Tooltip] Refactor event handling

---

docs/src/pages/components/tables/ColumnGroupingTable.js
docs/src/pages/components/tables/ColumnGroupingTable.tsx
docs/src/pages/components/tables/tables-pt.md
docs/src/pages/components/tables/tables.md

Fixes #23090 
This update adds additional information about how to enable multiple sticky headers using `stickyHeader`.
Portuguese documentation has also been updated accordingly.

[docs] Improve docs for Table sticky column grouping

---

packages/material-ui/src/Avatar/Avatar.test.js
packages/material-ui/src/CardHeader/CardHeader.test.js
packages/material-ui/src/Chip/Chip.test.js
packages/material-ui/src/CircularProgress/CircularProgress.test.js
packages/material-ui/src/Collapse/Collapse.test.js
packages/material-ui/src/CssBaseline/CssBaseline.test.js
packages/material-ui/src/Modal/Modal.test.js
packages/material-ui/src/Rating/Rating.test.js
packages/material-ui/src/Select/Select.test.js
packages/material-ui/test/integration/TableCell.test.js

Migrated TableCell integration tests to React Testing Library.
Relates to #22911

[test] Migrate TableCell test to react-testing-library

---

packages/material-ui-utils/src/elementAcceptingRef.ts
packages/material-ui-utils/src/elementTypeAcceptingRef.ts

Getting this in before https://github.com/facebook/react/issues/20047 and v5 because we're affected by this warning as well: `/components/tooltips` already triggers this warning. 
Tested locally since we don't have a clean environment for node i.e. server rendering.
Related to #23070

[utils] Don't warn about non-ref-forwarding components on the server

---

packages/material-ui-utils/src/chainPropTypes.ts
packages/material-ui-utils/src/chainpropTypes.spec.tsx
packages/material-ui/src/Box/Box.spec.tsx
packages/material-ui/src/Grid/Grid.spec.tsx

Without the fix the new reproduction fail:
I have first seen the issue in https://github.com/mui-org/material-ui-x/pull/455.
I have used https://github.com/DefinitelyTyped/DefinitelyTyped/blob/47120459d29b508f334db2957c1a962eb193d356/types/airbnb-prop-types/index.d.ts#L44 as inspiration for the solution.

[utils] Fix types of chainPropTypes

---

README.md
docs/src/pages/discover-more/showcase/appList.js

[docs] Fix casing typo

---

docs/src/pages/components/buttons/ButtonSizes.js
docs/src/pages/components/buttons/ButtonSizes.tsx

This PR removes unused selector "extendedIcon" from the "Buttons -> Sizes" example.
See https://material-ui.com/components/buttons/#sizes
This selector is not used anywhere in the example.

[docs] Remove unused style selectors `extendedIcon`

---

docs/src/pages/getting-started/example-projects/example-projects.md
examples/reason/README.md

Based on the popularity https://www.similarweb.com/website/reasonml.github.io/?competitors=reactjs.org 
we are removing the reason example project that we had for v4. If somebody migrates it to v5, we may add it again.

[examples] Remove reason example project

---

packages/material-ui/src/CardHeader/CardHeader.js

I noticed the avatar is not properly aligned with the title when using an icon (it was fine if I used the Avatar component to wrap the icon). Inspecting the element I noticed the flex properties being set but the display wasn't set to flex. Changing this fixed the issue.

[Card] Use flex display for CardHeader.avatar

---

scripts/build.js
scripts/copy-files.js
scripts/sizeSnapshot/webpack.config.js

Affected packages:
- `@material-ui/icons`
- `@material-ui/system`
- `@material-ui/utils`
I had some assumptions about our packages that don't hold for all `@material-ui/*` packages. In a perfect world these would hold since it makes easier to work with them (as maintainer and, more importantly, app dev) but we have adjust for the way people consume Material-UI today.
This is not the ideal fix for #23120 but I'd rather get a working™ fix out soon as possible so that we can cut a release.
1. [x] Get deploy of new bundles
1. [X] Create test fixture covering (tracked in #23166)
Closes #23120

[core] Fix bundles for packages without subpackages

---

.github/workflows/maintenance.yml
azure-pipelines.yml
dangerfile.js

1. Comment before the size-snapshot is ready
That way the actual conversation isn't interrupted and it's easier to find the reported bundle size.
Especially on PRs that target the build setup (and fail on the first pushes) you sometimes find the comment very low in the conversation.
Ideally we'd always have the very first comment be the bundle size changes. This change should improve it by commenting immediately after `yarn install` is done (1-2minutes after opening).
1. Always include the link 
We don't report changes of docs pages but these are sometimes the target of a PR (e.g. #23108)

[core] Improve bundle size comment

---

packages/material-ui-styled-engine/package.json

`Error: @material-ui/styled-engine tried to access @babel/runtime, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.`

[styled] Add @babel/runtime dependency

---

docs/src/pages/components/dialogs/dialogs.md
docs/src/pages/components/drawers/drawers.md
docs/src/pages/components/modal/KeepMountedModal.js
docs/src/pages/components/modal/KeepMountedModal.tsx
docs/src/pages/components/modal/modal.md
test/regressions/index.js

Closes https://github.com/mui-org/material-ui/issues/21987.
I did not add a `Performance` section as mentioned in the discussion in the issue, but rather, simply added some guidance in the `Temporary drawer` section.
Happy to move this around and adjust as needed (like adding an explicit demo).

[docs] Add Performance section for Modal

---

docs/src/pages/components/menus/PositionedMenu.js
docs/src/pages/components/menus/PositionedMenu.tsx
docs/src/pages/components/menus/menus.md

Closes https://github.com/mui-org/material-ui/issues/20755 by adding a `PositionedMenu` `Menu` component example to the documentation

[docs] Add Menu component example with explicit positioning prop values

---

packages/material-ui/src/Container/Container.js
packages/material-ui/src/styles/createBreakpoints.js

When setting breakpoints in different units (like for example `em`) the media-query/breakpoints get created properly and they use the units defined.
However, the Container component is still using no units at all (defaults to pixels) which makes everything break apart.
This PR should fix it, but I've found out another bug on the ThemeProvider which I may need help with. The units set are not showing up on it at `theme.breakpoints.unit` so on the generated CSS it shows up like `undefined`:
On the React DevTools the Theme provider doesn't show units defined...
If I manually set `unit: "em"` under breakpoints through the DevTools, it magically works after that!
So basically some tweaks need to be made to the ThemeProvider to make it work, but I can't find where (need some guidance).

[Container] Fix support of custom breakpoint units

---

packages/material-ui/src/Select/SelectInput.js

I believe this should close [#23201](https://github.com/mui-org/material-ui/issues/23201). Let me know if you have any other suggestions.

[Select] Fix SelectDisplayProps className concat

---

docs/src/pages/components/slider-styled/ContinuousSlider.js
docs/src/pages/components/slider-styled/ContinuousSlider.tsx
docs/src/pages/components/slider-styled/DiscreteSlider.js
docs/src/pages/components/slider-styled/DiscreteSlider.tsx
docs/src/pages/components/slider-styled/DiscreteSliderLabel.js
docs/src/pages/components/slider-styled/DiscreteSliderLabel.tsx
docs/src/pages/components/slider-styled/DiscreteSliderMarks.js
docs/src/pages/components/slider-styled/DiscreteSliderMarks.tsx
docs/src/pages/components/slider-styled/DiscreteSliderSteps.js
docs/src/pages/components/slider-styled/DiscreteSliderSteps.tsx
docs/src/pages/components/slider-styled/DiscreteSliderValues.js
docs/src/pages/components/slider-styled/DiscreteSliderValues.tsx
docs/src/pages/components/slider-styled/InputSlider.js
docs/src/pages/components/slider-styled/InputSlider.tsx
docs/src/pages/components/slider-styled/NonLinearSlider.js
docs/src/pages/components/slider-styled/NonLinearSlider.tsx
docs/src/pages/components/slider-styled/RangeSlider.js
docs/src/pages/components/slider-styled/RangeSlider.tsx
docs/src/pages/components/slider-styled/TrackFalseSlider.js
docs/src/pages/components/slider-styled/TrackFalseSlider.tsx
docs/src/pages/components/slider-styled/TrackInvertedSlider.js
docs/src/pages/components/slider-styled/TrackInvertedSlider.tsx
docs/src/pages/components/slider-styled/VerticalSlider.js
docs/src/pages/components/slider-styled/VerticalSlider.tsx

This PR simply replaces Box system props usages on the Slider docs page which will be used as a base for converting other components to the new styled engine.

[docs] Use Box sx prop on all Slider examples

---

packages/material-ui/src/Tooltip/Tooltip.js

This fixed to Tooltip hover. Now the mouse can move between Button and Tooltip, but the Tooltip disappears when mouse cursor is beyond the Tooltip
Related to https://github.com/mui-org/material-ui/issues/23232#issuecomment-715991707

[Tooltip] Remove excess spacing

---

packages/material-ui/src/Radio/RadioButtonIcon.js

Added `scale(1)` to `RadioButtonUncheckedIcon` which centres the dot on Safari different screen sizes and on window zoom. 
Resolves #19846

[Radio] Fix dot misalignment in Safari

---

docs/pages/api-docs/fade.md
docs/pages/api-docs/grow.md
docs/pages/api-docs/slide.md
docs/pages/api-docs/zoom.md
packages/material-ui/src/Fade/Fade.d.ts
packages/material-ui/src/Fade/Fade.js
packages/material-ui/src/Grow/Grow.d.ts
packages/material-ui/src/Grow/Grow.js
packages/material-ui/src/Slide/Slide.d.ts
packages/material-ui/src/Slide/Slide.js
packages/material-ui/src/Zoom/Zoom.d.ts
packages/material-ui/src/Zoom/Zoom.js

- Bug fix: Setting `appear={undefined}` on a transition component would set the transition component's `appear` to `false`. This now sets it to `true`, matching the behavior of omitting the prop
----
Document the default value of the `appear` prop on transition components.
This resolves #22162

[Transition] Document default appear value

---

docs/pages/api-docs/autocomplete.md
packages/material-ui/src/Autocomplete/Autocomplete.d.ts
packages/material-ui/src/Autocomplete/Autocomplete.js
packages/material-ui/src/Autocomplete/Autocomplete.test.js

Closes #22166
Problem:
If the user clicks on the right of the 'combobox' text inside of the textfield which is close button area, options isn't displayed.
Solution: 
As follwing as 8d9d11c, it is solved simply by adding `dirty` condition to render clear icon button. 
```javascript
const hasClearIcon = !disableClearable && !disabled && dirty;
```

[Autocomplete] Fix unclickable area between text input and endAdornment

---

packages/material-ui-system/src/index.d.ts
packages/material-ui-system/src/spacing.js
packages/material-ui/src/styles/createSpacing.d.ts
packages/material-ui/src/styles/createSpacing.test.ts
packages/material-ui/src/styles/createSpacing.ts

This resolves #21278. The change gives more control to the developers that choose to provide a function to the unit.
When passing a function to `createSpacing`, only number arguments were passed to the function, while strings were not.
Before:
```js
const spacing = createSpacing((factor) => `${0.25 * factor}rem`);
expect(spacing(1, 'auto', 2, 3)).to.equal('0.25rem auto 0.5rem 0.75rem');
```
After:
With this PR we pass the strings to the function and expect the function to handle them:
```js
spacing = createSpacing((factor) =>
typeof factor === 'string' ? factor : `${0.25 * factor}rem`,
);
expect(spacing(1, 'auto', 2, 3)).to.equal('0.25rem auto 0.5rem 0.75rem');
```

[theme] Fix spacing string arguments

---

packages/material-ui/src/Icon/Icon.js

Make the Icons avoid Google Chrome translation since it make it stop showing the Icon.
Resolves #23236 
Resources:
- https://stackoverflow.com/questions/9628507/how-can-i-tell-google-translate-to-not-translate-a-section-of-a-website
- https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/translate
Related to #22719

[Icon] Disable translation, e.g Google Translate

---

test/karma.conf.js

Safari 12 is fairly flaky in `test_browser` (feels like >50% failure, probably around 10%) so let's try Safari 13 instead.
This makes Safari 12 effectively our new IE 11 (on which we don't test either) so let's hope we don't break it too often.

[test] Run with Safari 13

---

packages/material-ui/src/Avatar/Avatar.js

According to the [HTMLImageElement API](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/srcset) the correct property is `srcset`, not `srcSet`... and it cannot be `undefined`, otherwise it will trigger the `onerror` event.

[Avatar] Fix usage of srcset property

---

packages/material-ui-styled-engine-sc/src/index.js
packages/material-ui/src/styles/experimentalStyled.js
packages/material-ui/src/styles/experimentalStyled.test.js

Assuming that `@emotion/styled` and `@material-ui/core/styles#experimentalStyled` implement the same API the added test fails unexpectedly.
Comparison between emotion and styled-engine: https://codesandbox.io/s/experimentalstyled-dynamic-styling-ubozu
Aside but not as severe: `styled.div` is not available. Only `styled()`.

[styled-engine] Fix tagged template syntax with multiple expressions

---

packages/material-ui/package.json

[core] Fix implicit transitive 'csstype' dependency

---

docs/src/pages/components/tables/CustomPaginationActionsTable.js
docs/src/pages/components/tables/CustomPaginationActionsTable.tsx
docs/src/pages/components/tables/EnhancedTable.js
docs/src/pages/components/tables/EnhancedTable.tsx

Preview: https://deploy-preview-23280--material-ui.netlify.app/components/tables/#custom-pagination-options
* Fix text when selecting table all option
Related to #23277
Closes #23282

[Table] Fix empty row logic when displaying all

---

test/utils/mochaHooks.js

Mocha makes use of console error for watchmode for notifications in the terminal which resulted in "unexpected console.error calls" errors being thrown on subsequent watchmode runs.
By restoring the console methods we now get to see these messages and don't throw on unrelated errors.

[test] Fix unexpected console warn/error spy swallowing unrelated messages 

---

docs/pages/_app.js
docs/src/modules/components/AppFrame.js

This seems to solve the problem of not respecting a visitor's docs language setting on subsequent visits. There's another issue with the browser constantly reloading a 404 page when the browser language is set, but I haven't tried to resolve that here.

[docs] Fix language cookie

---

packages/material-ui/src/ButtonBase/ButtonBase.test.js
test/utils/createClientRender.js

In watchmode these files are re-evaluate so every run wraps the composed `fireEvent` again.
With 5 re-reruns
Before (see 4x the `keyDown` stackframe in addition to 1 Function.keyDown frame):
After (1 stackframe for Function.keyDown):

[test] Prevent growing call stack in custom keyDown/keyUp

---

.circleci/config.yml
.eslintrc.js
packages/material-ui/src/ClickAwayListener/ClickAwayListener.js
packages/material-ui/src/ClickAwayListener/ClickAwayListener.test.js
packages/material-ui/src/Snackbar/Snackbar.test.js
scripts/react-next.diff

Backport of #23315
Closes #23215 (magic comment for codesandbox)

[ClickAwayListener] Fix mounting behavior in Portals in React 17

---

.mocharc.js
test/cli.js

- reduce boot times (stable and experimental CLIs)
This was noticeable in "old" repositories that accumulated a lot of ignored files. I got a 8s bootstrap time reduction in watchmode since it went from watching ~60k files to ~10k files.
- Add `--inspect-brk` to `yarn t`
Works exactly like `node --inspect-brk` but by adding the flag to our CLI we can control where the debugger should start. `node --inspect-brk test/cli.js` would not debug the tests.

[test] Improve test debugging

---

packages/material-ui/src/InputBase/InputBase.js

this PR is created base on an issue https://github.com/mui-org/material-ui/issues/23332
it fixes the opacity of disable color on the safari browser.
Closes #23332

[TextField] Fix disabled color in Safari 

---

docs/public/_redirects

The current setup doesn't work. There is an infinite redirection loop.
Related to https://github.com/mui-org/material-ui-x/issues/499

[docs] Fix the Netlify proxy for localization of X

---

packages/material-ui/src/Box/Box.test.js

This PR adds necessary tests to ensure that the bug https://github.com/mui-org/material-ui/issues/16995 won't happen again. We are testing that the rules in the generated CSS corresponds with the correct expected CSS depending on the order of the properties defined on the `Box` component
Closes #16995

[test] Make sure system properties are in the same order when generating CSS

---

docs/src/modules/components/AppFrame.js
docs/src/modules/constants.js

Aim to fix the links on https://material-ui-x.netlify.app/components/data-grid/pagination/ that don't work.
e.g.

[docs] Allow to host code in a different repo

---

docs/src/pages/customization/palette/palette.md

Change one more instance of `palette.type` to `palette.mode` in the Palette examples, following on from #22844

[docs] Fix usage of palette.type instead of palette.mode in docs

---

docs/src/pages/guides/migration-v4/migration-v4.md

* Fix use of `theme.palette.type` instead of `theme.palette.mode`
* Combine changes to `theme.palette.mode` and `theme.palette.text.hint` into a single example diff, showing the correct changes.

[docs] Improve migration guide for theme.palette

---

packages/material-ui/src/styles/createTypography.d.ts

The Typography interface, the type returned by createTypography, doesn't
contain the property htmlFontSize. This property is always present in
the object returned by createTypography. As a result of htmlFontSize not
existing on the Typography interface, the htmlFontSize property does not
exist on the Theme type returned by createMuiTheme either.
This fix moves the htmlFontSize from FontStyleOptions back into
FontStyle where it previously existed (see: https://github.com/mui-org/material-ui/pull/11456)
By moving to FontStyle, the htmlFontSize property is now present on
Typography and Theme, as well as on TypographyOptions and ThemeOptions.

[theme] Add htmlFontSize to Typography interface

---

packages/material-ui/src/StepLabel/StepLabel.js

This is a PR for issue #23392 .   The StepLabel icon prop was not being used at all. Now the icon prop, if provided, will override whatever was passed via the StepContext.  I'm applying the fix proposed by @oliviertassinari.
Closes #23392.

[Stepper] Fix the icon prop support in StepLabel

---

docs/src/pages/components/css-baseline/css-baseline.md
packages/material-ui/src/CssBaseline/CssBaseline.js

Closes #22594
Preview: https://deploy-preview-23407--material-ui.netlify.app/

[CssBaseline] Add dark mode scrollbar support

---

docs/src/modules/components/AppDrawerNavItem.js

Reverts the redesign of links in #22780 until #23444 is resolved.
The new styling of the nav items make them indistinguishable from disabled items. This is especially noticeable on top level links like "premium themes" and "blog". It doesn't really make sense to go against an existing design system.
[`next`](https://5f989306fe4fc800073aa58a--material-ui.netlify.app/):
It's less noticeable on dark themes but the general issue exists there as well.
The argument for the redesign was that it's closer to the drawer in material.io but it was not specified why that is desired. Especially because it's simply used as an inspiration from a site that is black and white and therefore is not suited to copy only certain features. Maybe material.io is never using disabled items and can therefore …

[docs] Avoid confusing nav items with disabled items

---

packages/material-ui/src/Box/Box.test.js
test/utils/initMatchers.ts

Closes #23417
Style assertions should not be branched by browsers unless the visuals are actually different.
If we write these tests often we can use some library that expands shorthand properties. Most of them are very old and not very consumer friendly so I'm waiting with adding them.

[test] Prefer longhand properties

---

docs/src/pages/components/tables/EnhancedTable.js
docs/src/pages/components/tables/EnhancedTable.tsx
docs/src/pages/components/tooltips/SimpleTooltips.js
docs/src/pages/components/tooltips/SimpleTooltips.tsx

These became redundant with #22729

[docs] Remove redundant aria-label when wrapped in Tooltip

---

docs/public/_redirects

Noticed some 404s in mui-scripts-incubator. Considering ExpansionPanel also has redirects and Grid is way more popular we should redirect them as well. At least until we have a proper 404 page.

[docs] Redirect legacy GridList pages to ImageList

---

packages/material-ui-system/src/spacing.js
packages/material-ui-system/src/spacing.test.js

Adds warning when some spacing key is used in non integer value, but the `theme.spacing` is defined as array. Added tests case that illustrates the scenario.
Closes https://github.com/mui-org/material-ui/issues/23187

[system] Warn for spacing when non integer value is used with theme.spacing array

---

packages/material-ui/src/Autocomplete/Autocomplete.test.js

The test frequently timed out. Increasing the threshold until further investigation. If it also times out with 4s it's more likely to be caused by implementation.

[test] Increase timeout threshold for slow Firefox tests

---

examples/cdn/README.md
examples/create-react-app-with-typescript/README.md
examples/create-react-app/README.md
examples/gatsby-theme/README.md
examples/gatsby/README.md
examples/nextjs-with-typescript/README.md
examples/nextjs/README.md
examples/preact/README.md
examples/ssr/README.md

Most of the examples' installation instructions didn't reference the correct download URL for the *next* branch. This PR fixes it.
First reported in #22450.

[docs] Fix examples download URLs to match the correct branch name

---

test/regressions/index.js

With #22692 we now have visual regression tests relying on `Date` which means they produce different output depending on the time they're run.
Using `sinon#useFakeTimers` to run the tests with the same (mocked) time. This also mocks all other timer related things so the tests should be even "more stable" though we haven't had any timer related flakyness. But it could still mean that we run less timer related stuff (e.g. passive effects?).
We'll see if this works. Otherwise I'll just stub the `Date` constructor.

[test] Use fake timers in visual regression tests

---

packages/material-ui-lab/src/DatePicker/DatePickerKeyboard.test.tsx
packages/material-ui-lab/src/DatePicker/DatePickerLocalization.test.tsx

- https://app.circleci.com/pipelines/github/mui-org/material-ui/26324/workflows/6a9f040c-75f0-4420-b12a-c8c4ef4caa48/jobs/194193
- https://app.circleci.com/pipelines/github/mui-org/material-ui/26326/workflows/e97d412d-c696-4100-99fd-c5cd5d621c4d/jobs/194203
#23475 might solve the root issue, until then, optimize for stability.

[DatePicker] Skip flaky tests

---

.eslintignore
scripts/prettier.js
test/cli.js

`globby`'s patterns don't work the same as gitignore patterns so we have to map them accordingly.
Loosely based off of https://github.com/sindresorhus/globby/blob/52d02bb9d776a898097dbe76400d9dd8bfeca7e9/gitignore.js#L26-L46

[core] Fix skipped ignore patterns

---

.circleci/config.yml
packages/material-ui-lab/src/ClockPicker/ClockPickerStandalone.test.tsx
packages/material-ui-lab/src/DatePicker/DatePicker.test.tsx
packages/material-ui-lab/src/DatePicker/DatePickerKeyboard.test.tsx
packages/material-ui-lab/src/DatePicker/DatePickerLocalization.test.tsx
packages/material-ui-lab/src/DateRangePicker/DateRangePicker.test.tsx
packages/material-ui-lab/src/DateRangePicker/date-range-manager.test.ts
packages/material-ui-lab/src/DateRangePickerDay/DateRangePickerDay.test.tsx
packages/material-ui-lab/src/DateTimePicker/DateTimePicker.test.tsx
packages/material-ui-lab/src/DayPicker/DayPicker.test.tsx
packages/material-ui-lab/src/MonthPicker/MonthPicker.test.tsx
packages/material-ui-lab/src/PickersDay/PickersDay.test.tsx
packages/material-ui-lab/src/TimePicker/TimePicker.test.tsx
packages/material-ui-lab/src/YearPicker/YearPicker.test.tsx
packages/material-ui-lab/src/internal/pickers/date-utils.test.ts
packages/material-ui-lab/src/internal/pickers/test-utils.tsx
test/karma.conf.js

In Safari `new Date('2018-01-01T00:00:00.000')` is the same as `new Date('2018-01-01T00:00:00.000Z')` i.e. the default timezone is GMT not the local timezone. GMT is assumed because the date uses ISO 8601 format. Oddly enough, Safari is the only browser in our roster spec compliant here. But the first date should use the local timezone because `date.getFullYear()` returns the value in the current timezone.
MDN actually warns about this and says relying on Date.parse is discouraged:
> Note: Parsing of date strings with the Date constructor (and Date.parse, they are equivalent) is strongly discouraged due to browser differences and inconsistencies.
--https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date
Periodically runs the datepicker tests that were …

[test] Use adapter instead of native Date

---

docs/src/pages/components/autocomplete/ComboBox.js
docs/src/pages/components/autocomplete/ComboBox.tsx
packages/material-ui/src/Autocomplete/Autocomplete.js

By using the `Popper` we can use `<Autocomplete disablePortal />` in a flex container and resolve the misleading naming issue i.e. `disablePortal` now only disables the portal instead of disabling the Popper.
`disablePortal` is important for a11y on VO
Other minor fixes:
1. Avoid role in label
The UI already communicates what kind of interactions are allowed. We don't need to repeat that in the label.
It's especially annoying with screen readers which announced "combobox combobox"
Preview: https://deploy-preview-23263--material-ui.netlify.app/components/autocomplete/
Closes #23471

[Autocomplete] Use Popper with when disablePortal

---

docs/src/modules/components/MarkdownLinks.js

With Chrome 86, Ubuntu 20.04:
1. right-click link
1. left-click outside of opened context menu
Behavior with native `<a />`: context menu is dismissed
Behavior in https://next--material-ui.netlify.app/: context menu is dismissed and link that was previously right clicked is opened
The current implementation uses `document.activeElement` as the link target (assuming that the link target becomes the activeElement upon activation). However, the link target becomes the active element on mousedown (any button) not on click. So if the click event is interrupted (context menu) the next click will target the link for which the event was actually interrupted.
Fixed it by finding the first parent `<a />` of the click target and using that. Also gets rid of potential platform inconsistencies from …

[docs] Fix links being opened when dismissing context menus

---

packages/material-ui-lab/src/DateRangePicker/DateRangePicker.test.tsx
packages/material-ui/src/Backdrop/Backdrop.js
packages/material-ui/src/Backdrop/Backdrop.test.js
packages/material-ui/src/Dialog/Dialog.js
packages/material-ui/src/Dialog/Dialog.test.js
packages/material-ui/src/Menu/Menu.js
packages/material-ui/src/Menu/Menu.test.js
packages/material-ui/src/Modal/Modal.js
packages/material-ui/src/Modal/SimpleBackdrop.js
packages/material-ui/src/Popover/Popover.js
packages/material-ui/src/Popover/Popover.test.js
packages/material-ui/test/integration/Menu.test.js
test/utils/initMatchers.ts

Only targets /core for now which doesn't need `data-mui-test` anymore. We can use `data-testid` in tests instead.
Part of #23488

[test] Remove data-mui-test from tests

---

docs/src/pages/system/basics/BreakpointsAsArray.js
docs/src/pages/system/basics/Why.js
docs/src/pages/system/basics/Why.tsx
docs/src/pages/system/basics/basics.md
docs/src/pages/system/display/Overflow.js
docs/src/pages/system/flexbox/AlignSelf.js
docs/src/pages/system/palette/BackgroundColor.js
docs/src/pages/system/sizing/Values.js
docs/src/pages/system/sizing/Width.js
docs/src/pages/system/spacing/HorizontalCentering.js
docs/src/pages/system/typography/FontFamily.js
docs/src/pages/system/typography/TextAlignment.js
prettier.config.js

These changes help make the point that the `sx` prop allows a denser vertical spacing. They don't introduce a scrollbar in the docs. They would if I had use 100 or more.
---
#23294 was slightly rushed. I'm aware of 3 other follow-up changes that are coming:
- @mbrookes that was planning to revamp the wordings
- @mnajdova that was planning to act on the feedback to improve the description of `/system/properties/`
- The need to remove the orphan demos.

[docs] Improve formatting of the system

---

docs/src/pages/system/basics/Demo.js
docs/src/pages/system/basics/Demo.tsx

Most  likely not the best solution but better than documenting images with layout shiift. That's a gap a dedicated `Image` component could solve (https://github.com/mui-org/material-ui/issues/22470).

[docs] Prevent layout jumps from img loading in system demo

---

packages/material-ui-lab/package.json

[lab] Fix build

---

docs/next.config.js
docs/scripts/i18n.js
docs/src/modules/components/AppDrawer.js
docs/src/modules/components/Link.js
docs/src/modules/components/PageContext.js
docs/src/modules/utils/find.js
docs/src/pages.ts
package.json

Deploy with all locales (for routing testing): https://5fb41a5e69a49d000885d0cb--material-ui.netlify.app/
Currently navigating to `/api` pages from within the docs triggers a full page reload.
I assumed that `rewrites` was working for client-side routing since that was nextjs maintainers explicitly told us. But [`rewrites` don't have any effect on `next export`](https://err.sh/next.js/export-no-custom-routes). We can achieve the same effect with `Link#as` it seems. 
Used the opportunity to type-check the parts that I worked on.

[docs] Fix /api client-side routing

---

.circleci/config.yml
packages/material-ui-lab/src/DatePicker/DatePicker.test.tsx
packages/material-ui-lab/src/DatePicker/DatePickerKeyboard.test.tsx
packages/material-ui-lab/src/DatePicker/DatePickerLocalization.test.tsx
packages/material-ui-lab/src/DateTimePicker/DateTimePicker.test.tsx
packages/material-ui-lab/src/DayPicker/DayPicker.test.tsx

These tests did not fail during the experiment (https://github.com/mui-org/material-ui/pull/23475). All failures on the experimental pipeline were due to other tests (e.g. ["checkMaskIsValid"](https://app.circleci.com/pipelines/github/mui-org/material-ui/26775/workflows/0b1a4c14-a94d-448f-8932-3d0ca6a4d7eb/jobs/195587) or ["should use hysteresis with the enterDelay:"](https://app.circleci.com/pipelines/github/mui-org/material-ui/26921/workflows/582eb550-3760-4765-8d5a-8d25ef651e01/jobs/196111).). I'll investigate the unrelated failures in a separate PRs.
I'm leaving the `test-gate` parameter in the CircleCI config to signal how we would run tests to the codebase that should only run under certain conditions (e.g. with feature flags, React experimental, periodically etc).

[test] Enable experimental-timezone tests

---

packages/material-ui-lab/src/internal/pickers/text-field-helper.ts

false-positive was observed periodically during https://github.com/mui-org/material-ui/pull/23475 (e.g. https://app.circleci.com/pipelines/github/mui-org/material-ui/26775/workflows/0b1a4c14-a94d-448f-8932-3d0ca6a4d7eb/jobs/195587).
The underlying issue is the same that required https://github.com/mui-org/material-ui/pull/23475: Safari assumes UTC if the timezone is omitted in iso 8601 date formats. We're fixing it by deferring to the date adapters. This means that date-fns still has this false positive until `@date-io/date-fns#date` uses `date-fns#parseISO` under the hood (or rather fixes the Safari quirk). See https://github.com/dmtrKovalenko/date-io/issues/479#issuecomment-725394784

[DatePicker] Fix false-positive when validating mask in Safari

---

docs/public/_redirects
packages/material-ui/src/withMobileDialog/withMobileDialog.js
packages/material-ui/src/withMobileDialog/withMobileDialog.test.js

Follow up for #23202 
Signed-off-by: Reece Dunham <me@rdil.rocks>

[Dialog] Add deprecation warning for withMobileDialog

---

package.json
scripts/listChangedFiles.js
scripts/pushArgos.js

https://github.com/argos-ci/argos/issues/429#issuecomment-727181730, this will allows us to scale up the number of screenshots we can send to Argos per build. Heroku force a 30s timeout. It's complementary to #23500. I start with 2, it should be enough to avoid timeouts. It takes about the same amount of time to upload the screenshots.

[test] Create chunks for Argos

---

docs/src/pages/components/slider/CustomizedSlider.js
docs/src/pages/components/slider/CustomizedSlider.tsx

As recommended in the issue #18679 I've removed controlled example from the docs.
Closes #18679.

[docs] Remove controlled Tooltip example in Slider

---

packages/material-ui/src/Select/Select.test.js
packages/material-ui/src/Select/SelectInput.js

This is an attempt to close [#21441](https://github.com/mui-org/material-ui/issues/21441). I used the second proposed solution from [#21441 (comment)](https://github.com/mui-org/material-ui/issues/21441#issuecomment-685940576).
There was quite a bit of discussion about the best solution. The motivation for this pull request is described as the third possibility in [#21441 (comment)](https://github.com/mui-org/material-ui/issues/21441#issuecomment-689497020). 
Note, when using the proposed solution, I received an error in `yarn lint` that `103:22  error  Expected to return a value at the end of arrow function`, so I modified the solution as follows:
```diff
diff --git a/packages/material-ui/src/Select/SelectInput.js b/packages/material-ui/src/Select/SelectInput.js
index …
```

[Select] Replace displayNode state with displayRef for ref value 

---

docs/pages/_app.js
docs/pages/api-docs/icon.md
docs/src/pages/components/icons/FontAwesomeIcon.js
docs/src/pages/components/icons/FontAwesomeIcon.tsx
docs/src/pages/components/icons/Icons.js
docs/src/pages/components/icons/Icons.tsx
docs/src/pages/components/icons/TwoToneIcons.js
docs/src/pages/components/icons/TwoToneIcons.tsx
docs/src/pages/components/icons/icons.md
framer/Material-UI.framerfx/code/Icon.tsx
packages/material-ui/src/Icon/Icon.d.ts
packages/material-ui/src/Icon/Icon.js
packages/material-ui/src/Icon/Icon.test.js

The `Icon` component always adds the `material-icons` class to the element; however, per the docs, you may use other icon fonts with this component so always having this base class doesn't make sense in all cases. Best case scenario, the class is ignored but if someone is mixing two icon fonts (material-icons + some other), this may cause issues.
Also, [now that the different Material Icon variants can be used via icon font](https://stackoverflow.com/questions/50303454/how-to-use-the-new-material-design-icon-themes-outlined-rounded-two-tone-and), it would be convenient to be able to swap out `material-icons` for `material-icons-round`, for example.

[Icon] Allow customizing the 'material-icons' base class name

---

package.json
packages/material-ui-styles/src/makeStyles/makeStyles.d.ts
packages/material-ui-styles/src/makeStyles/makeStyles.spec.tsx
packages/material-ui-utils/src/deepmerge.ts
packages/material-ui/src/styles/makeStyles.d.ts
yarn.lock

1. [core] Don't bail on monorepo typescript task
Right now we're exiting on the very first error.
This is not in line with other test-like tasks we have (e.g. `yarn lint` or `yarn test:unit`).
It also hid a more severe issue https://github.com/mui-org/material-ui/issues/23627.
1. [styles] Fix useStyles requiring props in TS 4.1
> docs: src/pages/components/drawers/PersistentDrawerLeft.tsx(88,19): error TS2554: Expected 1 arguments, but got 0.
-- https://app.circleci.com/pipelines/github/mui-org/material-ui/27542/workflows/e3a4c4a4-19dc-4c38-84d9-044fc34a6fd3/jobs/197844
1. [utils] Fix deepmerge return type for falsy inputs
> @material-ui/core: ../material-ui-utils/src/deepmerge.ts(2,3): error TS2322: Type 'unknown' is not assignable to type 'boolean'.
-- …

[core] Add support for TypeScript 4.1

---

docs/src/pages/guides/migration-v4/migration-v4.md

Fixes the Box section title under https://next.material-ui.com/guides/migration-v4
Before:
After:
Only happens on the English guide preview, in other languages, the markdown preview for the Box section looks ok
This is my first PR here, so just let me know if I did something wrong while fixing it or while opening the PR.
- [ x ] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui-org/material-ui/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

[docs] Fix the Box section title on migration-v4 guide

---

package.json
packages/material-ui-styles/src/makeStyles/makeStyles.d.ts
packages/material-ui-styles/src/makeStyles/makeStyles.spec.tsx
packages/material-ui/src/styles/makeStyles.d.ts

This PR adds cherry picks support for TypeScript 4.1 #23633 fixing #23627 in version 4.
Thanks to @eps1lon for creating the original PR.

[styles] Add support for TypeScript 4.1

---

docs/src/pages/system/basics/Demo.js
docs/src/pages/system/basics/Demo.tsx
packages/material-ui/src/Box/Box.d.ts
packages/material-ui/src/Box/Box.js
packages/material-ui/src/Box/Box.spec.tsx

Fixes ts issue with Box not respecting the props of the component used under the `component` prop. Examples:
```jsx
<Box 
component={Paper} 
minHeight={320} // <Box /> prop
square // <Paper /> prop throws
/>
```
```jsx
<Box 
component="img" 
src="HTTP://material-ui.com" // img prop throws
alt="Material-UI" // img prop throws
/>
```
Closes https://github.com/mui-org/material-ui/issues/16843

[Box] Fix TypeScript issue when component prop is used

---

packages/material-ui/src/locale/index.ts

Hey there! Just a translation of the "more than" phrase for the Portuguese locales. 
(figured it would be no problem to bundle them in one PR as they are the same; do let me know otherwise!)

[l10n] Translate 'more than' in pt locales

---

package.json
packages/material-ui/src/Divider/Divider.test.js
test/cli.js
test/karma.conf.js
test/utils/createClientRender.js
test/utils/createMount.js
test/utils/mochaHooks.js
yarn.lock

1. `test:karma`: More ergonomic approach to running `test:karma` with specified browsers
```diff
-`yarn test:karma --browsers BrowserStack_Chrome,ChromeHeadlessNoSandBox,BrowserStack_Safari,BrowserStack_Firefox,BrowserStack_Firefox`
+`yarn test:karma --browsers chrome,chromeHeadless,safari,firefox,edge`
1. `t` (experimental cli): Fix shorthand for `--bail` (`-b`) and `--inspect-brk` (`-d`)
Both used `-b`.
1. Explicitly throw if `createClientRender` or `createMount` are mistakenly called in test hooks
This is not problematic right now as far as I can tell but any potential `before` hook called from within `createClientRender` would be dropped if `createClientRender` is called within a `before` hook.
Only `Divider.test` violated this.
1. `t`: Allow testing in production environment. 
Does …
```

[test] Misc improvements to experimental and browser test runner

---

packages/material-ui-styles/src/mergeClasses/mergeClasses.d.ts
packages/material-ui-styles/src/mergeClasses/mergeClasses.test.js

The types for `mergeClasses` didn't quite match its implementation. In particular, `newClasses` and `Component` are optional, and the values in `newClasses` should also be allowed to be optional.
This showed up in practice when you are using the `classes` prop directly from a `StyledComponentProps<ClassKey>` interface which is a `undefined | Partial<ClassNameMap<ClassKey>>` so if set, all of the props in `classes` are optional.

[styles] Update mergeClasses types to more closely match its implementation

---

packages/material-ui/src/Autocomplete/Autocomplete.test.js
packages/material-ui/src/useAutocomplete/useAutocomplete.js

- Check every change of `filteredOptions` and execute `onHighlightChange` only when the highlighted option is changed
- Fix highlighted index "force reset" when input value is `null`(highlighted index should be calculated properly even if input value is `null`)
- Checking `filteredOptions.length === 0` to check highlight change is not enough if `filteredOptions` is changed asynchronously.
- Resetting highlighted index without considering if it should stay breaks the UX.
Closes #22170

[Autocomplete] Make highlight change work better

---

docs/src/pages/guides/migration-v4/migration-v4.md
packages/material-ui/src/Tab/Tab.js
packages/material-ui/src/Tabs/Tabs.test.js

It looks like the first `[theme.breakpoints.up('sm')]` was being overwritten by the second `theme.breakpoints.up('sm')`, therefore the intended increased padding on `sm` and bigger screens did not take effect.
(Note that I am not sure whether we actually want the padding or whether the Material Design spec has changed over the years and the padding should be different. However, the current state is clearly a bug)

[Tabs] Remove duplicate styles

---

benchmark/browser/README.md
benchmark/browser/scripts/benchmark.js
docs/src/pages/system/basics/basics.md

Use https://necolas.github.io/react-native-web/benchmarks/ as inspiration:
- Display the standard deviation
- Increase the number of runs from 10 to 15
- Create a test case array for simplicity
- Turn into % display to be more CPU agnostic (help with collaboration)
```
noop (baseline):
04.59 ±00.10ms
React primitives:
44.05 ±02.19ms
React components:
126 ±8%
Styled Material-UI:
174 ±6%
Styled emotion:
163 ±6%
Styled SC:
191 ±5%
makeStyles:
168 ±6%
Box Baseline:
180 ±4%
Box Material-UI:
377 ±6%
Box Theme-UI:
316 ±6%
Box Chakra-UI:
269 ±9%
styled-components Box + @material-ui/system:
358 ±8%
styled-components Box + styled-system:
307 ±9%
```
@mnajdova Could you run the script locally and commit the printed output in the markdown so we can evaluate if it's stable or not (on this PR)?

[benchmark] Improve printed results

---

packages/material-ui/src/styles/experimentalStyled.d.ts
packages/material-ui/src/styles/experimentalStyled.js
packages/material-ui/src/styles/experimentalStyled.test.js

This PR adds an option for making the `sx` prop optional as part of the `experimentalStyled` utility. This could unblock developers to customize the behavior of the resolver for the `sx` prop, depending on their needs. A simple example of how it could be used can be found here - https://codesandbox.io/s/confident-bush-346hb?file=/src/App.js (the value for the `m` prop is always the negative value of the resolved one).
Discussion around this issue can be found here - https://github.com/mui-org/material-ui/issues/23496

[experimentalStyled] Make sx style fn optional

---

patches/argos-cli+0.3.0.patch

If `.json()` failed then the body is already used and we can't flush it again e.g. by using `.text()`. So just flush it once and then manually pipe it to JSON.parse or the error handler.
Previous failure: https://app.circleci.com/pipelines/github/mui-org/material-ui/28253/workflows/bf0933ce-ae1a-447e-975c-94305cad4b3a/jobs/199676
Closes #23725

[core] Fix error handling on upload

---

test/regressions/TestViewer.js

Still experiencing flaky tests when a single tests loads some additional web fonts.
So we're now leveraging [`FontFaceSet`](https://developer.mozilla.org/en-US/docs/Web/API/FontFaceSet) and listen to `loading` and `loadingdone` events. In these events we flip the ready state depending on `document.fonts.status`. Hopefully this resolves the last issues.
It's an experimental feature but [shipped by browsers supported by `playwright`](https://caniuse.com/?search=FontFaceSet).

[test] Stay busy until document.fonts is ready

---

packages/material-ui-styles/src/StylesProvider/StylesProvider.test.js
packages/material-ui-styles/src/ThemeProvider/ThemeProvider.test.js
packages/material-ui-styles/src/createGenerateClassName/createGenerateClassName.test.js
packages/material-ui-unstyled/src/SliderUnstyled/SliderUnstyled.test.js
packages/material-ui-utils/src/useIsFocusVisible.test.js
packages/material-ui/src/Button/Button.test.js
packages/material-ui/src/ButtonBase/ButtonBase.test.js
packages/material-ui/src/Fab/Fab.test.js
packages/material-ui/src/Portal/Portal.test.js
packages/material-ui/src/Slider/Slider.test.js
packages/material-ui/src/Tabs/Tabs.test.js
packages/material-ui/src/TextareaAutosize/TextareaAutosize.test.js
packages/material-ui/src/ToggleButton/ToggleButton.test.js
packages/material-ui/src/useMediaQuery/useMediaQuery.test.js
packages/material-ui/src/useScrollTrigger/useScrollTrigger.test.js
packages/material-ui/test/integration/MenuList.test.js

1. Remove unused skip conditions
Became obsolete with https://github.com/mui-org/material-ui/pull/22814
1. [test] Prefer skip() over return
This can be abused up until adding a test becomes a balancing act. For example, in SwipeableDrawer where we return in the middle of the test file (not touching that test for now because it seems too brittle). This is the old problem of "optimizing for the current test suite". A test suite needs to scale and every addition needs to start from a clean slate. And a change to existing tests should not affect existing one.
By using skip() we can also better monitor which tests are skipped across environments. This was only possible implicitly. Now we have an explicit signal in test runners.

[test] Cleanup skipped tests

---

packages/material-ui-lab/src/DateRangePicker/DateRangePicker.test.tsx
packages/material-ui-lab/src/internal/pickers/date-utils.ts
packages/material-ui-lab/src/internal/pickers/test-utils.tsx

The test is the first one I have written for MUI. The test checks that a range of one day is accepted. 
I hope I introduced the new test according to your conventions. Feedback is of course appreciated!
Fixes #23603 
Fixes https://github.com/mui-org/material-ui-pickers/issues/1759

[DateRangePicker] Allow same date selection

---

packages/material-ui/src/Autocomplete/Autocomplete.test.js

This opportunity was found in #23487. These two tests are interesting in what happens when the user press <kbd>Enter</kbd> and more specifically if the event bubble up to a potential parent `<form>` element to trigger the submit. By refactoring the test, we avoid early returns like: https://github.com/mui-org/material-ui/blob/dfc94e03d391384155cbdd1a0e3b0fe16e2e1042/packages/material-ui/src/useAutocomplete/useAutocomplete.js#L731

[Autocomplete] Better isolate test case

---

docs/pages/_document.js
docs/src/pages/components/timeline/CustomizedTimeline.js
docs/src/pages/components/timeline/CustomizedTimeline.tsx
docs/src/pages/components/timeline/timeline.md
docs/src/pages/versions/versions.md

- Fix double h1 by this demo: https://next.material-ui.com/components/timeline/#customized-timeline
- Fix double // on the canonical link of https://next.material-ui.com/components/timeline/#customized-timeline
- Fix missing leading / on the canonical link of https://next.material-ui.com/components/timeline/#customized-timeline

[docs] Improve SEO structure

---

packages/material-ui/src/Select/Select.test.js
packages/material-ui/src/Select/SelectInput.js

Add disabled attribute to the input element, when disabled prop is true and select is disabled.
The disabled attribute is used to make the control non-interactive and to prevent its value from being submitted.
Closes #23693

[Select] Add disabled attribute in input element when disabled

---

packages/material-ui/src/internal/SwitchBase.js
packages/material-ui/src/internal/SwitchBase.test.js

Checks whether the default behaviour is prevented, if yes, restricts the state change of the checkbox element.
`preventDefault` should restrict the default behaviour of the input element and stop the element from updating.
Related issue(s)/PR(s)
Closes #23709

[Switch] Add preventDefault check for state change

---

docs/src/pages/components/autocomplete/autocomplete.md
packages/material-ui/src/Autocomplete/Autocomplete.test.js
packages/material-ui/src/SwipeableDrawer/SwipeableDrawer.js
packages/material-ui/src/useAutocomplete/useAutocomplete.js

[Autocomplete] Add ability to override key down events handlers

---

docs/src/modules/components/AppSettingsDrawer.js

Higher contrast, and use primary color for selected state:

[docs] Improve settings toggle button styling

---

CONTRIBUTING.md

[CONTRIBUTING] Move instructions for starting the docs earlier in the file

---

docs/pages/api-docs/slider.md
docs/src/modules/utils/parseTest.ts
packages/material-ui/src/Slider/Slider.d.ts
packages/material-ui/src/Slider/Slider.test.js
test/utils/describeConformance.js
test/utils/describeConformanceV5.js
test/utils/index.js

This PR adds a conformance test suite for v5. It is used in the Slider tests.

[test] Add conformance test suite for v5

---

docs/package.json
docs/pages/_app.js
docs/src/modules/components/AppSettingsDrawer.js
docs/src/modules/utils/RtlContext.js
docs/src/modules/utils/StyledEngineProvider.js
yarn.lock

This PR fixes two issues with RTL:
1. since 11 emotion is compatible with v2 of the stylist plugin rtl, so it has been updated in the dependencies of the docs
2. Refactored the docs to depend on the `theme.direction` prop, rather than a new rtl context.

[docs] Fix rtl not working

---

docs/src/modules/components/MarkdownElement.js

Preview: https://deploy-preview-23819--material-ui.netlify.app/components/breadcrumbs/#api
Current: Preview: https://next--material-ui.netlify.app/components/breadcrumbs/#api
Current color of links within markdown became outdated at some point (see existing comment). Also restores visual consistency of links in the docs.

[docs] Fix color contrast of code within links

---

docs/pages/_app.js
docs/pages/_document.js

This PR fixes duplicated classes generated for the components that use emotion as styled engine.
The styles are identical. I couldn't find any other solution, this is the only relevant discussion I stable apon https://github.com/emotion-js/emotion/issues/1061, but we already use the `CacheProvider` for the ltr/rtl styles generated.

[docs] Fix duplicated styles generated from emotion

---

docs/src/modules/components/MarkdownDocs.js

Fixed source github links to open url based on lib version.
When a github link from any pages in docs is clicked, it is showing 404 message.
Closes #23406

[docs] Fix source on Github links

---

test/regressions/index.js

The skipped tests breaks the visual regression tests frequently. It uses fontawesome which kicks of cascading network requests. These are hard to await since we have to know ahead of time which request kicks of other ones we have to await.
Skipping the test since it's mainly concerned with fontawesome anyway. If this test becomes more important we can try out some retry logic if the test kicked of some requests during execution which we didn't await before taking the screenshot.

[test] Skip tests with cascading network requests

---

docs/src/pages/components/breadcrumbs/IconBreadcrumbs.js
docs/src/pages/components/breadcrumbs/IconBreadcrumbs.tsx

Put icons and text on the same baseline when increasing the default font size.
To see the difference you have to increase the default font size in your browser (Chrome: Settings > Appearance > Font Size). On "Large" it's already misaligned.
Preview: https://deploy-preview-23818--material-ui.netlify.app//components/breadcrumbs/#breadcrumbs-with-icons
Current: https://next--material-ui.netlify.app/components/breadcrumbs/#breadcrumbs-with-icons

[docs] Fix icon alignment in /components/breadcrumbs

---

docs/src/modules/utils/getDemoConfig.js
docs/src/modules/utils/helpers.js
docs/src/modules/utils/helpers.test.js

The objective of this pull request is to get the same great DX of #22616 but for Material-UI X. Over the last few weeks, I have found myself going to the codesandbox-ci UI to get the published package many times. The workflow is especially useful when reviewing.
Once the changes are merged, I will cherry-pick it to `master` and complete the integration on https://github.com/mui-org/material-ui-x/pull/613.

[docs] Allow codesandbox deploy for demos in X

---

docs/src/pages/components/use-media-query/use-media-query.md
packages/material-ui/src/useMediaQuery/useMediaQuery.js
packages/material-ui/src/useMediaQuery/useMediaQuery.test.js

Closes #21142 
I added the `useEnhancedEffect` function as recommended to solve the problem we see in this [demo](https://codesandbox.io/s/material-demo-w3xyj?file=/demo.tsx)
Also, I added the documentation suggested to the demo page to make it more clear.
I modified these files: 
`/material-ui/packages/material-ui/src/useMediaQuery/useMediaQuery.js`
`/docs/src/pages/components/use-media-query/use-media-query.md b/docs/src/pages/components/use-media-query/use-media-query.md`

[useMediaQuery] Fix a false return at the first call

---

packages/material-ui-utils/macros/MuiError.macro.js
packages/material-ui-utils/src/capitalize.test.js
packages/material-ui/src/styles/colorManipulator.test.js
packages/material-ui/src/styles/createPalette.test.js
packages/material-ui/src/styles/responsiveFontSizes.test.js
test/utils/initMatchers.ts

some errors thrown from `createPalette` where throwing with `_formatMuiErrorMessage is undefined` in node (or rather when transpiling to commonJS).
Fixed by following https://babeljs.io/docs/en/babel-helper-module-imports.html#examples.
Discovered when running tests in production. I also added a custom matcher for thrown `MuiError` which should be preferred. We're not enforcing this right now since I don't know where this prod-testing experiment is going. So far it uncovered at least one bug.

[utils] Fix minified errors throwing with _formatMuiErrorMessage

---

packages/material-ui/src/Popper/Popper.test.js

Review on per-commit advised since it includes some test refactorings that improve debugging the affected tests.
Small test refactoring that revealed some faulty test description. Specifically, we had a test that said Popper would flip the placement when the popper reached the edge. However, the given placemenent was not flipped on update because it didn't render anything. Since we now render an actual DOM element (so that we don't need to spy on the render calls) popper actually flips the placement as intended in browser tests.

[test] Make Popper tests StrictMode agnostic

---

docs/src/pages/components/material-icons/SearchIcons.js
docs/translations/translations.json

[docs] Copy icons to clipboard

---

packages/material-ui-icons/builder.js
scripts/copy-files.js

`Fs-extra` package deprecated the `exists` function.
Closes #23847
Thanks!

[core] Replace fs-extra deprecated function (exists)

---

docs/src/pages/components/autocomplete/CustomizedHook.tsx
docs/src/pages/components/autocomplete/UseAutocomplete.tsx
packages/material-ui/src/useAutocomplete/useAutocomplete.d.ts

Question about this:
I had to update the demos to fix type errors caused by the type definition change.  The current demos aren't explicit about the fact that `groupedOptions` changes shape when `groupBy` is provided; And their behavior will actually break without explanation if you do provide `groupBy` to `useAutocomplete` ([Demo](https://codesandbox.io/s/material-ui-issue-forked-6bidf?file=/src/Demo.tsx)).  With the type definition change, you do get type errors now if you don't handle the union type on `groupedOptions`, which is good, but I think it would be of benefit to add a bit more explanation of that behavior to the demos, as it seems a bit unexpected to me.  I'm happy to do that, I'm just wondering what form you think would be appropriate.  Would just a comment do? Would you …

[Autocomplete] Fix useAutocomplete groupedOptions type

---

.github/ISSUE_TEMPLATE/1.bug.md
packages/material-ui-envinfo/README.md
packages/material-ui-envinfo/index.js
packages/material-ui-envinfo/package.json

Reduces work required when opening an issue and provides better environment information by leveraging [`envinfo`](https://www.npmjs.com/package/envinfo):
(Currently only works if you've checked out this branch and ran `yarn`. Once this is merged and published it works as advertised.)
```bash
$ npx @material-ui/envinfo
System:
OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
Binaries:
Node: 12.20.0 - ~/.nvm/versions/node/v12.20.0/bin/node
Yarn: 1.22.4 - /usr/bin/yarn
npm: 6.14.8 - ~/.nvm/versions/node/v12.20.0/bin/npm
Browsers:
Chrome: 87.0.4280.66
Firefox: 83.0
npmPackages:
@emotion/react: ^11.0.0 => 11.1.1
@emotion/styled: ^11.0.0 => 11.0.0
@material-ui/codemod:  5.0.0-alpha.17
@material-ui/core:  5.0.0-alpha.18
@material-ui/docs:  5.0.0-alpha.1
@material-ui/envinfo:  1.0.0 …
```

[envinfo] Ask for output from envinfo in issues

---

docs/src/modules/utils/StyledEngineProvider.js

This PR adds the `prepend` option to the emotion caches that we use in the docs, to allow emotion's styles to be injected first, which will allow JSS overrides. The need of this has been discovered, by the argos differences in https://github.com/mui-org/material-ui/pull/23841 - once we converted the `Typography` component, which is widely used, we need to allow JSS (`makeStyles`) to override the styles for it.

[docs] Add prepend option on emotion caches to allow JSS style overrides

---

docs/src/pages/components/autocomplete/UseAutocomplete.js
packages/material-ui/src/Autocomplete/Autocomplete.test.js
packages/material-ui/src/useAutocomplete/useAutocomplete.js
scripts/react-next.diff

Closses #23572
Fixes the console error following Oliver's suggestion.
I modified:
/Users/nsl-intern/material-ui/packages/material-ui/src/useAutocomplete/useAutocomplete.js
Made some tests to make sure it worked in:
/Users/nsl-intern/material-ui/docs/src/pages/components/autocomplete/UseAutocomplete.js

[Autocomplete] Improve DX/UX when getOptionLabel is not configured correctly

---

.circleci/config.yml
azure-pipelines.yml
benchmark/browser/README.md
benchmark/browser/scripts/benchmark.js

So that every member can update/inspect the results.
Example run: https://dev.azure.com/mui-org/Material-UI/_build/results?buildId=19952&view=results
How to run:
1. Click on the "Details" link of the azure pipelines check of a GitHub PR
1. Continue to the build on dev.azure.com
1. "Run new"
1. Variables
1. Use `benchmark` for `command`
1. Run
1. The result will be available as a pipeline artifact
<details>
<summary>why CircleCI is not viable</summary>
Might prevent dependabot from automatically merging. If that happens I'll try a different approach (e.g. webhooks, uncommenting lines in the CI config etc.)
Update: Yep, CircleCI approvals are not viable for github: https://ideas.circleci.com/cloud-feature-requests/p/show-overall-all-checks-have-passed-status-in-github-even-on-builds-with-inc …

[test] Run benchmarks in Azure Pipelines when approved

---

packages/material-ui/src/Grid/Grid.js

[Grid] Remove side effects when direction="column" and xs={} is used 

---

yarn.lock

Tried to fix an unactionable install warning but looks like an actual false positive.
<details>
<summary>Failed attempt at fixing install warnings</summary>
It's used by `dtslint` and its dependency tree caused an unactionable warning on `yarn install`:
> 0.0.36-580e30b90a5fb43cc6fa3bc60037dacb2227dc03-integrity/node_modules/@definitelytyped/typescript-versions" as pattern ["@definitelytyped/typescript-versions@^0.0.36","@definitelytyped/typescript-versions@^0.0.36"]. This could result in non-deterministic behavior, skipping
Fixed by clearing the lockfile entry for `dts-critic` and running `yarn` i.e. regenerating its lockfile entry.
</details>

Bump dts-critic to 3.3.4

---

packages/material-ui/src/Slider/Slider.test.js
test/utils/describeConformanceV5.js

[test] Add conformance tests for testing the `theme.components` options for the v5 components

---

.github/ISSUE_TEMPLATE/1.bug.md
packages/material-ui-envinfo/envinfo.test.js

Full info takes up quite a bit of screen real estate which is mostly too much considering it's rarely the cause of the issue. Wrapping it in `<details />` might help. Let's see if it's clear where to paste the info.
Also emphasizes that we sometimes need to know which particular browser is used.

[core] Improve envinfo instructions

---

.gitattributes

Right now we allow checking out files with CR/LF. This means that every script dealing with newlines has to consider both cases. This oftentimes leads to blocking windows developers if changes are made by unix devs because they don't have to consider CR/LF. Windows devs do because CI runs on unix.
Additionally, prettier already defaults to LF so if you check out a file, change it, run prettier, you already re-format the whole file creating large, potentially confusing diffs.
**for windows devs**:
After this PR is merged and you've updated your branch with the changes you probably need to update your newlines. **COMMIT OR STASH CHANGES BEFORE YOU DO OR THE PROGRESS IN YOUR WORKING TREE IS LOST**
```bash
$ git rm --cached -r .
$ git reset --hard
```
I'm not updating scripts dealing with …

[core] Force LF for text files

---

packages/material-ui/src/Badge/Badge.test.js

[core] Fix failing CI on HEAD

---

docs/next.config.js

Didn't need any code changes to fix it. I'm leaving the change to vercel in regardless to get a feel of how much slower exporting every locale is. Actual analysis of the issue below.
production deploys are currently failing for `next` (e.g. https://app.netlify.com/sites/material-ui/deploys/5fd31f0b071ca50007de7b01). Opening to notify that we're aware of the issue.
Broken when merging https://github.com/mui-org/material-ui/pull/23745. Shortly after it another PR was merged skipping the netlify deploy so https://app.netlify.com/sites/material-ui/deploys/5fd2552ee192c200082e8622 is the first one failing even though it's unrelated.
Figuring out:
1. [x] why is it not failing on PRs even though it fails with the english locale
1. [x] Netlify only issue? 
Looks like a caching issue. Notice how …

[docs] Fix production deploy

---

docs/scripts/buildApi.ts
docs/translations/api-docs/badge/badge.json
docs/translations/api-docs/slider/slider.json

This PR improves the API description for the `sx` prop by linking it's docs page.

[docs] Add link to the sx docs page in the API description

---

docs/src/pages/system/basics/basics.md

We've received multiple times question regarding why we decided to go with one prop vs more props regarding the system's `sx` prop. This section hopefully, will help to make that information more visible.

[docs] Add API tradeoff section for the sx prop

---

CHANGELOG.md
docs/src/pages/components/icons/icons.md
docs/src/pages/components/tables/EnhancedTable.js
docs/src/pages/components/tables/EnhancedTable.tsx
docs/src/pages/system/screen-readers/VisuallyHiddenUsage.js
docs/src/pages/system/screen-readers/VisuallyHiddenUsage.tsx
packages/material-ui-system/src/index.d.ts
packages/material-ui-system/src/index.js
packages/material-ui-utils/src/index.ts
packages/material-ui-utils/src/visuallyHidden.ts
packages/material-ui/src/Rating/Rating.js

Only applies if you've installed `@material-ui/system@5.0.0-alpha.1`
```diff
-import { visuallyHidden } from '@material-ui/system';
+import { visuallyHidden } from '@material-ui/utils';
```
Cherry-picked from https://github.com/mui-org/material-ui/pull/23902 so that we know what's going on.
I went ahead an removed it directly from the system. It was only added during this alpha which is the whole point of an alpha: iterate on the API.
Not adding this to the v5 milestone or else it'll be considered a breaking change from v4 to v5. It's only a breaking change between alphas.

[system] Remove visuallyHidden and move to /utils

---

packages/material-ui/src/Badge/Badge.js
packages/material-ui/src/Slider/Slider.js
packages/material-ui/src/styles/experimentalStyled.d.ts
packages/material-ui/src/styles/experimentalStyled.js
packages/material-ui/src/styles/experimentalStyled.test.js

This PR aims to resolve https://github.com/mui-org/material-ui/pull/23745#discussion_r537590851 by providing `name` and `slot` as options in the `experimentalStyled` utility.
Here is the output of both the generated HTML and the React tree.
Previously:
Now:
Previously:
Now:

[experimentalStyled] Add name and slot options 

---

packages/material-ui-system/src/style.js
packages/material-ui-system/src/style.test.js

Fixed the bug where transform was not fired if a theme was provided. Similarly, added tests to test this. Tests were provided from the changes in this thread (https://github.com/akomm/material-ui/blob/a4a394ff5420d29311ce1edef2bf20b51b507954/packages/material-ui-system/src/style.test.js)
And the change to style.js was provided in the issue discussion.
Fixes #23496

[system] Fix transform not firing when theme provided

---

docs/src/pages/guides/migration-v4/migration-v4.md
packages/material-ui/src/CssBaseline/CssBaseline.js

- [CssBaseline] The `body` font size has changed from `theme.typography.body2` (`0.875rem`) to `theme.typography.body1` (`1rem`).
To return to the previous size, you can override it in the theme:
```js
const theme = createMuiTheme({
typography: {
body1: {
fontSize: '0.875rem',
},
},
});
```
(Note that this will also affect use of the Typography component with the default `body1` variant).
---
Closes #17100
Part of #20012

[CssBaseline] Change body font size to body1 (1rem)

---

packages/material-ui-lab/src/DatePicker/DatePicker.tsx
packages/material-ui-lab/src/DateRangePicker/DateRangePicker.tsx
packages/material-ui-lab/src/DateTimePicker/DateTimePicker.tsx
packages/material-ui-lab/src/DesktopDatePicker/DesktopDatePicker.tsx
packages/material-ui-lab/src/DesktopDateRangePicker/DesktopDateRangePicker.tsx
packages/material-ui-lab/src/DesktopDateTimePicker/DesktopDateTimePicker.tsx
packages/material-ui-lab/src/DesktopTimePicker/DesktopTimePicker.tsx
packages/material-ui-lab/src/MobileDatePicker/MobileDatePicker.tsx
packages/material-ui-lab/src/MobileDateRangePicker/MobileDateRangePicker.tsx
packages/material-ui-lab/src/MobileDateTimePicker/MobileDateTimePicker.tsx
packages/material-ui-lab/src/MobileTimePicker/MobileTimePicker.tsx
packages/material-ui-lab/src/StaticDatePicker/StaticDatePicker.tsx
packages/material-ui-lab/src/StaticDateRangePicker/StaticDateRangePicker.tsx
packages/material-ui-lab/src/StaticDateTimePicker/StaticDateTimePicker.tsx
packages/material-ui-lab/src/StaticTimePicker/StaticTimePicker.tsx
packages/material-ui-lab/src/TimePicker/TimePicker.tsx
packages/typescript-to-proptypes/src/injector.ts

Following the same convention eslint is using with their directives:
- prefix with package name
- followed by instruction
Makes it easier to search for directives of a particular package. Right now it's not apparent what directives are available from typescript-to-proptypes.

[core] Use consistent naming scheme for ttp annotations

---

scripts/sizeSnapshot/webpack.config.js

Ideally we would track individual component. Though we should look at the time this adds to CI if we've got a bit more components. 
For now tracking the package size is more of a smoke test to verify that the package is built properly and we're not pulling in something big.
Update: 6.14 kB seems fine.

[core] Track size of /unstyled

---

docs/src/modules/components/AppSearch.js

Shortcut CTRL + K for accessing search bar was added and issue with active element gets fixed.
Fixes #23804 
https://deploy-preview-23959--material-ui.netlify.app/getting-started/installation/

[docs] Add a shortcut to access the search bar

---

docs/translations/api-docs/badge-unstyled/badge-unstyled.json
docs/translations/api-docs/badge/badge.json
packages/material-ui-unstyled/src/BadgeUnstyled/BadgeUnstyled.d.ts
packages/material-ui/src/Badge/Badge.d.ts

All classes are applied to the `badge` not `root`.

[Badge] Fix the classes description to reflect the correct component

---

docs/src/modules/components/DemoToolbar.js

I got the idea for this change during a user-interview this week. The user was frustrating about having to click each time to display the correct file. In hindsight, it does seem obvious. Here is the change after opening a demo in Codesandbox:
**Before** 
**After**

[docs] Show a better file on codesandbox

---

packages/material-ui/src/Skeleton/Skeleton.js

Fix https://github.com/mui-org/material-ui/issues/24050
Before:
https://user-images.githubusercontent.com/53095479/102693785-bacaad00-4225-11eb-9f23-a41963c41b73.mov
After:
https://user-images.githubusercontent.com/53095479/102705915-5e06db00-4295-11eb-9c63-35001aa2a6f4.mov

[Skeleton] Fix Circle border radius on Safari

---

package.json
yarn.lock

Includes:
- https://github.com/babel/babel/releases/tag/v7.12.4
- https://github.com/babel/babel/releases/tag/v7.12.5
- https://github.com/babel/babel/releases/tag/v7.12.6
- https://github.com/babel/babel/releases/tag/v7.12.7
- https://github.com/babel/babel/releases/tag/v7.12.8
- https://github.com/babel/babel/releases/tag/v7.12.9
- https://github.com/babel/babel/releases/tag/v7.12.10
- https://github.com/babel/babel/releases/tag/v7.12.11

Bump @babel/* packages to 7.12.11

---

docs/pages/versions.js
docs/src/pages/versions/ReleasedVersions.js
docs/src/pages/versions/versions.md

Problems with v5:
- Release note link is broken
- Documentation link is broken
- v5 is not a stable release
https://material-ui.com/versions/
The solution:

[docs] Improve displayed versions

---

docs/package.json
docs/src/pages/components/transitions/TransitionGroupExample.js
docs/src/pages/components/transitions/TransitionGroupExample.tsx
docs/src/pages/components/transitions/transitions.md

Closes #24042
Deploy preview: https://5fde13885f4de40007494b4e--material-ui.netlify.app/components/transitions/#animate-components-mounting-and-unmounting

[docs] Animate component's mounting and unmounting

---

docs/pages/api-docs/collapse.md
docs/src/pages/components/transitions/SimpleCollapse.js
docs/src/pages/components/transitions/SimpleCollapse.tsx
docs/src/pages/components/transitions/transitions.md
packages/material-ui/src/Collapse/Collapse.d.ts
packages/material-ui/src/Collapse/Collapse.js
packages/material-ui/src/Collapse/Collapse.test.js

[Collapse] Deprecate collapsedHeight

---

docs/pages/api-docs/modal.md
docs/pages/api-docs/portal.md
packages/material-ui/src/Modal/Modal.d.ts
packages/material-ui/src/Modal/Modal.js
packages/material-ui/src/Modal/Modal.test.js
packages/material-ui/src/Portal/Portal.d.ts
packages/material-ui/src/Portal/Portal.js
packages/material-ui/src/Portal/Portal.test.js

[Modal][Portal] Deprecate onRendered

---

docs/src/pages/guides/migration-v4/migration-v4.md
packages/material-ui-system/src/grid.js
packages/material-ui-system/src/index.d.ts

The following properties were renamed because they are considered deprecated CSS properties:
1. `gridGap` to `gap`
2. `gridColumnGap` to `columnGap`
3. `gridRowGap` to `rowGap`
```diff
-<Box gridGap="10px">
+<Box sx={{ gap: '10px' }}>
```
```diff
-<Box gridColumnGap="10px" gridRowGap="20px">
+<Box sx={{ columnGap: '10px', rowGap: '20px' }}>
```

[system] Replace grid gap properties

---

packages/material-ui-lab/src/TreeItem/TreeItem.js
packages/material-ui-lab/src/TreeItem/TreeItem.test.js

Add prevent scroll when DOM tree is focused, which disables scroll to view of the focused element.
`preventScroll` should restrict scroll, hence preventing scroll jump
Closes #24096

[TreeView] Add preventScroll for tree focus

---

docs/src/modules/components/AppFrame.js

Fixes the warning:
```
Warning: Failed prop type: Invalid prop `disableDrawer` supplied to `AppFrame`, expected a ReactNode.
in AppFrame (at withStyles.js:72)
in WithStyles(AppFrame) (at TopLayoutCompany.js:30)
in TopLayoutCompany (at withStyles.js:72)
in WithStyles(TopLayoutCompany) (at jobs.js:14)
in Page (at _app.js:348)
in Context.Provider (at StyledEngineProvider.js:28)
in Context.Provider
in Context.Provider
in ae (at StyledEngineProvider.js:27)
in StyledEngineProvider (at _app.js:325)
in Context.Provider (at ThemeContext.js:249)
in Context.Provider (at ThemeProvider.js:11)
in InnerThemeProvider (at ThemeProvider.js:33)
in Context.Provider (at ThemeProvider.js:64)
in ThemeProvider (at ThemeProvider.js:32)
in ThemeProvider (at ThemeContext.js:248)
in ThemeProvider (at _app.js:324)
in …
```

[docs] Fix warning about wrong prop type

---

packages/material-ui-lab/src/DatePicker/DatePicker.tsx
packages/material-ui-lab/src/DateRangePicker/DateRangePicker.tsx
packages/material-ui-lab/src/DateTimePicker/DateTimePicker.tsx
packages/material-ui-lab/src/MobileDatePicker/MobileDatePicker.tsx
packages/material-ui-lab/src/MobileDateRangePicker/MobileDateRangePicker.tsx
packages/material-ui-lab/src/MobileDateTimePicker/MobileDateTimePicker.tsx
packages/material-ui-lab/src/MobileTimePicker/MobileTimePicker.tsx
packages/material-ui-lab/src/MonthPicker/PickersMonth.tsx
packages/material-ui-lab/src/TimePicker/TimePicker.tsx
packages/material-ui-lab/src/internal/pickers/PickersModalDialog.tsx
packages/material-ui-lab/src/internal/pickers/PickersPopper.tsx

Apply the same tradeoff as the Dialog and Drawer components, hide the outline. Also, take the opportunity to "clean" the component.
Closes #23532.

[DatePicker] Hide outline on container

---

docs/pages/api-docs/avatar.json
packages/material-ui/src/Avatar/Avatar.js
packages/material-ui/src/Avatar/Avatar.test.js
packages/material-ui/src/Avatar/avatarClasses.d.ts
packages/material-ui/src/Avatar/avatarClasses.js
packages/material-ui/src/Avatar/index.d.ts
packages/material-ui/src/Avatar/index.js
packages/material-ui/src/Button/Button.js

It took me about 1 hour without knowing exactly what I was doing, I tried to copy the changes in #24107 😆 . We have about 150 components to migrate. So in theory, the migration effort could take about 1 month.
Proposals improvements, to solve pains I have faced during the effort: 
1. Reduce the need to change theme import paths
```diff
const AvatarRoot = experimentalStyled(
'div',
{},
{
name: 'Avatar',
slot: 'Root',
overridesResolver,
},
-)((props) => ({
+)(({ theme, styleProps }) => ({
```
This would have saved me some time to rename the props. I also think that it's easier to ready and more aligned with what we [document](https://next.material-ui.com/guides/interoperability/).
2. Reduce prop name renaming, make it easier to navigate the code:
```diff
<AvatarRoot
as={Component}
- …
```

[Avatar] Migrate to emotion

---

examples/nextjs-with-typescript/README.md
examples/nextjs-with-typescript/src/Link.tsx
examples/nextjs/README.md
examples/nextjs/src/Link.js
packages/material-ui/src/ButtonBase/ButtonBase.js

This PR attempts to improve the integration with Next.JS, improving the Link component, updating the examples and removing unwanted type errors logged in the console or linted by TypeScript.
- Update Next.js examples
- Update prop-types for consistency between `MuiButtonBase` and `MuiLink`
- Add note on both readme about Object URL support and how to use `NextLinkComposed`
Closes #24106

[Link] Improve integration with Next.js

---

packages/material-ui-unstyled/src/BadgeUnstyled/BadgeUnstyled.js
packages/material-ui-unstyled/src/SliderUnstyled/SliderUnstyled.js
packages/material-ui/src/Avatar/Avatar.js
packages/material-ui/src/Badge/Badge.js
packages/material-ui/src/Button/Button.js
packages/material-ui/src/ButtonBase/ButtonBase.js
packages/material-ui/src/Slider/Slider.js
packages/material-ui/src/Typography/Typography.js

This PR applies some refactorings on the  styled()` components proposed in https://github.com/mui-org/material-ui/pull/24114
1. Reduce the need to change theme import paths when migrating the components from `withStyles` to `styled`. This should allow a faster migration. 
```diff
const AvatarRoot = experimentalStyled(
'div',
{},
{
name: 'Avatar',
slot: 'Root',
overridesResolver,
},
-)((props) => ({
+)(({ theme, styleProps }) => ({
```
2. Reduce prop name renaming, make it easier to navigate the code:
```diff
<AvatarRoot
as={Component}
-     styleProps={stateAndProps}
+     styleProps={styleProps}
className={clsx(classes.root, className)}
ref={ref}
```
```diff
-const useAvatarClasses = (props) => {
- const { classes = {}, variant, colorDefault } = props;
+const useAvatarClasses = …
```

[core] Refactor styled() components to ease out the migration process 

---

test/karma.tests.js

Adds:
- `@material-ui/styled-engine`
- `@material-ui/styled-engine-sc`
- `@material-ui/system`
- `@material-ui/unstyled` (cherry-pick from https://github.com/mui-org/material-ui/pull/23902)
Anything DOM related should run in a browser especially if it affects styles.

[test] Add more packages to browser test suite

---

tsconfig.json

Hopefully this removes the "To enable project-wide JavaScript/TypeScript language features, exclude large folders with source files that you do not work on." warning in VSCode.
Seems to be a common misconfiguration: https://github.com/microsoft/TypeScript/wiki/Performance#misconfigured-include-and-exclude

[core] Reduce number of files included in language server

---

azure-pipelines.yml

We don't need `node_modules/.cache` when submitting the initial comment so we can defer the download saving 10-15s.
I planned some additional cloning speed-ups by switching to [treeless clones](https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/). This isn't possible in any of our CI providers (Azure, CircleCI) without forking their checkout command. This isn't worth it IMO for a couple of seconds. Shallow clones are not viable since various tasks rely on the commit history.

[core] Reduce response time of initial PR bot comment

---

packages/material-ui-lab/src/internal/pickers/PickersToolbarText.tsx

Closes #24174
This fixes the immediate issue regarding ToolbarText taking in a variant, such as h3, and creating an h3 element. This causes issues with accessibility. This automatically sets component as span, but can be overridden by props being passed over. I added an optional component prop type, I am not sure if this is necessary due to it already having the TypographyProps, but the documentation had mentioned adding prop types when new props (like component) are added.
One question posed, but not addressed, is allowing headings to be injected. The link mentioned at https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/datepicker-dialog.html holds a heading within the modal of their date picker because it is a heading for their modal. I believe this is a secondary issue, one …

[DatePicker] Fix accessibility issue with heading

---

packages/material-ui/src/Skeleton/Skeleton.d.ts

Skeleton used to declare `div` but it's actually `span` at runtime. The issue was that the generic parameter `D` was unused.
This particular issue was detected by @typescript-eslint/* 4.11.1. It uncovered a series of other issues that we'll fix in separate PRs. I want these type changes focused for changelog and in case they break something.

[Skeleton] Fix default TypeScript component type

---

.circleci/config.yml
package.json
scripts/testBuiltTypes.js

Monitors progress in fixing https://github.com/mui-org/material-ui/issues/24112 by:
- diffing generated declaration files against the ones on `next`
- logging files that still have faulty imports
The fixes for https://github.com/mui-org/material-ui/issues/24112 are useful regardless of https://github.com/mui-org/material-ui/issues/24112. Since they have different rationales (have two more fixes locally that are different than https://github.com/mui-org/material-ui/pull/24158) I'll file them as separate PRs.  Should also help debug potential breakage.

[core] Monitor progress of fixing type imports

---

packages/material-ui-lab/src/ClockPicker/Clock.tsx
packages/material-ui-lab/src/ClockPicker/ClockPicker.tsx

The given time and getClockLabelText could be passed assuming different date types since they didn't use the same type parameter. The name was identical but the type could be different because on shadowed the other.
This particular issue was detected by `@typescript-eslint/*` 4.11.1. It uncovered a series of other issues that we'll fix in separate PRs. I want these type changes focused for changelog and in case they break something.

[TimePicker] Prevent conflicting type parameter in `ClockProps#getClockLabelText`

---

packages/material-ui/src/styles/experimentalStyled.d.ts

The generic parameter of `MuiStyledOptions` was unused.
This particular issue was detected by `@typescript-eslint/*` 4.11.1. It uncovered a series of other issues that we'll fix in separate PRs. I want these type changes focused for changelog and in case they break something.

[core] Remove unused generics from experimentalStyled

---

.eslintrc.js
packages/material-ui-lab/src/PickersDay/PickersDay.tsx
packages/material-ui-lab/src/Timeline/Timeline.tsx
packages/material-ui-lab/src/internal/pickers/hooks/useViews.tsx
packages/material-ui-lab/src/internal/pickers/typings/helpers.ts
packages/material-ui-styles/src/withStyles/withStyles.test.js
packages/material-ui-styles/src/withTheme/withTheme.test.js

Closes #24146
Import one level deep to reduce the amount of JavaScript sent to the client in development.
In modern tooling, tree-shaking is only enabled in production. Not all developers have a fast computer. The change aims to reduce the amount of JavaScript loaded. The pain is growing as we add more modules to `@material-ui/core`.
I couldn't find any other cases like this in the codebase. Here is the impact when including [this demo](https://next.material-ui.com/components/date-picker/#basic-usage) (and only) with a high-end computer:
**Before**
**After**
I would call this a quick-win, a low effort: -200ms improvement in DX. It's not making a fundamental difference but doesn't cost much to accept it 🤷‍♂️. My biggest fear is about making it possible to grow `@material-ui/core` in size …

[DatePicker] Nested imports for better DX

---

.github/workflows/issue-mark-duplicate.yml

HI, @oliviertassinari I saw that when you deal with duplicate issue, like https://github.com/mui-org/material-ui/issues/24153 has some operations.
I think this GitHub Actions will help you.
The function implemented by the current configuration is: when you enter `Duplicate of #24153` or `/d #24153`, the system will ~automatically remove all labels,~ add `duplicate`, and close the issue at the same time.
This Actions also supports more parameters:
| Param | Desc  | Type | Required |
| -- | -- | -- | -- |
| actions | Action type | string | ✔ |
| token | - | string | ✔ |
| duplicate-command | Simple commands can be set, such as: `/d` | string | ✖ |
| duplicate-labels | Add additional labels to this issue | string | ✖ |
| labels | Replace the labels of the issue | string | ✖ |
| contents | …

[core] Create issue mark duplicate

---

docs/src/pages/styles/basics/basics.md

One of the links in the file is broken as mentioned in issue #24209.
This has been fixed here, in accordance with this comment: https://github.com/mui-org/material-ui/issues/24209#issuecomment-752951876
Closes #24209.

[docs] Fix broken benchmark link

---

docs/pages/api-docs/avatar.json
docs/pages/api-docs/button-base.json
docs/pages/api-docs/button.json
docs/pages/api-docs/typography.json
docs/translations/api-docs/avatar/avatar.json
docs/translations/api-docs/button-base/button-base.json
docs/translations/api-docs/button/button.json
docs/translations/api-docs/typography/typography.json
framer/scripts/framerConfig.js
packages/material-ui/src/Avatar/Avatar.d.ts
packages/material-ui/src/Avatar/Avatar.js
packages/material-ui/src/Button/Button.d.ts
packages/material-ui/src/Button/Button.js
packages/material-ui/src/ButtonBase/ButtonBase.d.ts
packages/material-ui/src/ButtonBase/ButtonBase.js
packages/material-ui/src/Typography/Typography.d.ts
packages/material-ui/src/Typography/Typography.js

The PR adds the missing types for the `sx` prop on the components migrated to emotion

[core] Add missing sx typings on the components migrated to emotion

---

docs/src/pages/components/badges/UnstyledBadge.js
docs/src/pages/components/badges/UnstyledBadge.tsx
packages/material-ui/src/styles/experimentalStyled.d.ts
packages/material-ui/src/styles/experimentalStyled.spec.tsx

With this PR the `experimentalStyled()` adds automatically the sx prop in the component's props interface

[styled] Fix missing types for sx prop

---

docs/src/pages/components/selects/selects.md

Add in some information on how to resize the select component.  I couldn't find this information and was going to start adding in custom styles until I foud the size prop, so I hope this can also help others.

[Select] Improve description on how it extends the Input components

---

packages/material-ui-lab/src/DateRangePicker/DateRangePickerViewMobile.tsx
packages/material-ui-lab/src/DayPicker/DayPicker.test.tsx
packages/material-ui-lab/src/DayPicker/PickersCalendarHeader.tsx

When you use the DatePicker and you select the year to be displayed only, the current month is shown with the year.
Closes #24195
Updated `PickersCalendarHeader` to show nothing in the case of displaying the year only.

[DatePicker] Fix year only view, hide the current month 

---

packages/material-ui/src/styles/experimentalStyled.d.ts
packages/material-ui/src/styles/experimentalStyled.spec.tsx

This fixed the TS issue when component cannot be used without providing `theme` props, or adding empty props object in the generic.
I also update the typings based on the types in emotion@11

[styled] Support components without theme

---

.github/workflows/ci.yml
packages/material-ui-envinfo/scripts/build.js

Also sets up a specialized workflow for testing that dev-only scripts run across all platforms.
Proof of concept:
- [macOS failure](https://github.com/mui-org/material-ui/runs/1627655738?check_suite_focus=true)
- [windows failure](https://github.com/mui-org/material-ui/runs/1627655738?check_suite_focus=true)

[core] Platform agnostic build script for envinfo

---

.eslintrc.js
packages/material-ui/src/Autocomplete/Autocomplete.test.js
packages/material-ui/src/useAutocomplete/useAutocomplete.js
packages/material-ui/src/useAutocomplete/useAutocomplete.test.js

I switched the key from index to the getOptionLabel function in order for a11y to appropriately read dropdown labels
Closes #24198

[Autocomplete] Fix VoiceOver not reading the correct activedescendant

---

scripts/copy-files.js

Related to #24206. Using the fs utils leads to unexpected outcomes when running on Windows.

[core] Fix generation of package.json

---

packages/material-ui/src/Badge/Badge.d.ts
packages/material-ui/src/Button/Button.d.ts
packages/material-ui/src/ButtonBase/ButtonBase.d.ts
packages/material-ui/src/Slider/Slider.d.ts
packages/material-ui/src/Typography/Typography.d.ts

Types that are in the same package should be imported with a relative path. Found and extracted from #24227.

[core] Fix relative import of types

---

scripts/testBuiltTypes.js

```diff
-packages/material-ui-lab/build/DatePicker/DatePicker.d.ts possibly imports types that are unreachable once published.
+packages/material-ui-lab/build/DatePicker/DatePicker.d.ts possibly imports types 17 times that are unreachable once published.
```
Helps better with progress tracking since some changes don't fix a file completely.

[test] More granular progress tracking of relative type imports

---

packages/material-ui/src/Button/Button.js

`disableElevation` is no longer working correctly since #24107. 
You can see the issue with https://codesandbox.io/s/containedbuttons-material-demo-forked-n4mnq?file=/demo.tsx and a mobile phone. It's related to `'@media (hover: none)': {`.
The fix is to move `styleProps.disableElevation` into it's own block. I have seen the issue working on #24095. I have also used the opportunity to restore the previous convention in the order of the styles: DOM order.

[Button] Fix disableElevation regression

---

docs/src/modules/components/DemoSandboxed.js

The problem was raised in https://github.com/mui-org/material-ui/issues/24097#issuecomment-750911353 and can be seen on:
https://next--material-ui.netlify.app/components/drawers/#persistent-drawer
It's a blocker to merge #24227 as the container only makes sense for a top-level layout, all the demos use an iframe.
Preview: https://deploy-preview-24232--material-ui.netlify.app/components/drawers/#persistent-drawer

[docs] Fix iframe demos with emotion

---

docs/pages/api-docs/container.json
docs/translations/api-docs/container/container.json
packages/material-ui/src/Avatar/Avatar.d.ts
packages/material-ui/src/Container/Container.d.ts
packages/material-ui/src/Container/Container.js
packages/material-ui/src/Container/Container.test.js
packages/material-ui/src/Container/containerClasses.d.ts
packages/material-ui/src/Container/containerClasses.js

I was working on #24095 but need to use the `sx` prop on a Container.

[Container] Migrate to emotion

---

packages/material-ui-lab/src/DateRangePicker/DateRangePickerView.tsx
packages/material-ui-lab/src/internal/pickers/Picker/Picker.tsx
packages/material-ui-lab/src/internal/pickers/Picker/SharedPickerProps.tsx

**TypeScript BREAKING CHANGE**
```diff
-PickerProps<View, InputValue, DateValue>
+PickerProps<View, DateValue>
```
The second type parameter was unused.
The linter detected unused type parameters in `SharedPickerProps`. I then discovered that we have two types with the same name in the codebase so I just removed one and inlined its properties where it was used. When we re-discover the purpose of the removed type we can document it.
I suspect `Picker/SharedPickerProps.tsx` should be named `Picker/utils.tsx` but we'll see once I dig more into the types. Next step will be figuring out what the difference is between `SharedPickerProps` and `AllSharedPickerProps` and why `|SharedPickerProps| > |AllSharedPickerProps|`<sup>1</sup>. In my mind you usually find `|AllSomeInterface| > …

[DatePicker] Remove unused type parameters

---

.circleci/config.yml
docs/pages/blog/2020-q3-update.md
docs/src/pages/components/tables/ReactVirtualizedTable.tsx
docs/src/pages/components/use-media-query/UseWidth.tsx
docs/src/pages/customization/breakpoints/WithWidth.tsx
docs/src/pages/customization/breakpoints/breakpoints.md
docs/src/pages/customization/palette/palette.md
docs/src/pages/customization/theme-components/GlobalThemeVariants.tsx
docs/src/pages/customization/theme-components/theme-components.md
docs/src/pages/customization/theming/CustomStyles.tsx
docs/src/pages/customization/typography/typography.md
docs/src/pages/guides/right-to-left/RtlOptOut.tsx
docs/src/pages/guides/typescript/typescript.md
docs/src/pages/system/basics/basics.md
packages/material-ui/package.json
packages/material-ui/scripts/testModuleAugmentation.js
packages/material-ui/src/styles/createMuiTheme.d.ts
packages/material-ui/src/styles/index.d.ts
packages/material-ui/test/typescript/moduleAugmentation/breakpointsOverrides.spec.ts
packages/material-ui/test/typescript/moduleAugmentation/breakpointsOverrides.tsconfig.json
packages/material-ui/test/typescript/moduleAugmentation/paletteColors.spec.ts
packages/material-ui/test/typescript/moduleAugmentation/paletteColors.tsconfig.json
packages/material-ui/test/typescript/moduleAugmentation/themeComponents.spec.ts
packages/material-ui/test/typescript/moduleAugmentation/themeComponents.tsconfig.json
packages/material-ui/test/typescript/moduleAugmentation/typographyVariants.spec.tsx
packages/material-ui/test/typescript/moduleAugmentation/typographyVariants.tsconfig.json
packages/material-ui/tsconfig.json

1. Use public paths in module augmentation
2. Test documented module augmentation /cc @mnajdova 
We have a notion of what we consider "public paths". However, this does not apply to type imports which makes it harder to teach ("ok here, but not ok there"). Since we already make types public by documenting that the paths are public we might as well export them directly which means we can simplify how we teach public paths.
The existing patterns continue to work but are more likely to break during refactoring. The patterns we now document are tested in CI and therefore a lot more robust.
1. does not slow down `test:unit`
1. Allows parallel testing (which we haven't set up for `mocha`)
1. can be included in test suite that runs with TypeScript nightlies

[core] Support public paths in module augmentation 

---

docs/src/pages/components/drawers/SwipeableBleedingDrawer.js
docs/src/pages/components/drawers/SwipeableEdgeDrawer.js
docs/src/pages/components/drawers/SwipeableEdgeDrawer.tsx
docs/src/pages/components/drawers/drawers.md

A new demo is added to the Material UI documentation to render the Swipeable Bleeding Drawer component or function Closes #24097

[SwipeableDrawer] Add bleeding demo

---

packages/material-ui-lab/src/ClockPicker/Clock.tsx

Add pointer for cursor when mouse over event happens on the clock element.
The cursor should indicate clickable on the clock.
Closes #24170

[TimePicker] Add pointer cursor for clock in desktop

---

packages/material-ui-lab/src/DatePicker/DatePicker.tsx
packages/material-ui-lab/src/DateRangePicker/DateRangePicker.tsx
packages/material-ui-lab/src/DateRangePicker/makeDateRangePicker.tsx
packages/material-ui-lab/src/DateTimePicker/DateTimePicker.tsx
packages/material-ui-lab/src/DesktopDatePicker/DesktopDatePicker.tsx
packages/material-ui-lab/src/DesktopDateRangePicker/DesktopDateRangePicker.tsx
packages/material-ui-lab/src/DesktopDateTimePicker/DesktopDateTimePicker.tsx
packages/material-ui-lab/src/DesktopTimePicker/DesktopTimePicker.tsx
packages/material-ui-lab/src/MobileDatePicker/MobileDatePicker.tsx
packages/material-ui-lab/src/MobileDateRangePicker/MobileDateRangePicker.tsx
packages/material-ui-lab/src/MobileDateTimePicker/MobileDateTimePicker.tsx
packages/material-ui-lab/src/MobileTimePicker/MobileTimePicker.tsx
packages/material-ui-lab/src/StaticDatePicker/StaticDatePicker.tsx
packages/material-ui-lab/src/StaticDateRangePicker/StaticDateRangePicker.tsx
packages/material-ui-lab/src/StaticDateTimePicker/StaticDateTimePicker.tsx
packages/material-ui-lab/src/StaticTimePicker/StaticTimePicker.tsx
packages/material-ui-lab/src/TimePicker/TimePicker.tsx
packages/material-ui-lab/src/internal/pickers/Picker/makePickerWithState.tsx
packages/material-ui-lab/src/internal/pickers/wrappers/Wrapper.tsx

All the wrapper components currently implement `SomeWrapperProps & PrivateWrapperProps` props. In some places we need to extract the `SomeWrapperProps` from these component types.
Currently we're doing this by comparing their props interface (- `PrivateWrapperProps` to a known list of interfaces and return the first known interface that extends it.
However, this approach is flawed if multiple interfaces implement the same property. In that case the first compared interface wins ([minimal illustration of the issue](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQdwAdjFlAXlnAApTABuyVrwhh0Abzpw4orEwBccAEYQIAGxxM6AXwbNW7TnABiqkWLiTpuABbA1AE0pMA-Iux4YAOg-4AchAOWFJwBKpucKgwfEwA5vS6jCxsHLhcAELIUOYSIbb2TnIRvt4lAUH00kpZikwAriBKbAkMMACeYFwAqkzAAI51WDkAPDkAfHA …

[DatePicker] Simplify ExtendWrapper type

---

docs/src/pages/guides/composition/composition.md

[docs] Change Link example from JS to TS

---

.github/workflows/issue-labeled.yml

HI, @oliviertassinari 
Last time, when you type `Duplicate of #xx`, it will add the `duplicate` label automatically.
And I found that you often need to manually remove these 2 labels, so I added this. It will only remove these 2 labels if the issue has these 2 labels or one of them and has no effect on others. If there are any omissions labels, you can tell me.

[core] Create issue labeled

---

docs/src/pages/components/steppers/steppers.md

[docs] Add example perfomance Stepper vertical

---

.github/workflows/ci.yml
.github/workflows/maintenance.yml

Ported behavior of azure pipelines and CircleCI to GitHub actions. Now I just need to cancel ~1300 jobs in the queue :grimacing: 
Update:
Cancelling queued runs of l10nbot with https://gist.github.com/eps1lon/9c822429bffb5db5a3f221dd00fea842#file-cancel-gh-actions-js

[test] Skip expensive GitHub actions on l10nbot commits

---

docs/src/modules/components/AppSearch.js

Before:
After:
Update: 
```diff
-CtrlK
+Ctrl+K
```
Rationale: https://github.com/mui-org/material-ui/pull/24296#issuecomment-755992971

[docs] Focus docs search input when the shortcut is clicked

---

packages/material-ui/src/FormLabel/FormLabel.js
packages/material-ui/src/FormLabel/FormLabel.test.js
packages/material-ui/src/OutlinedInput/OutlinedInput.js

Add error color for form input with secondary color when focused.
It will add error color and override focused color with error color for focused form input.
Closes #24261

[Textfield] Add error color for form input with secondary color

---

.circleci/config.yml

Noticed in https://github.com/mui-org/material-ui/pull/24298 that we compared against older declaration files: https://app.circleci.com/pipelines/github/mui-org/material-ui/32797/workflows/0d6cea67-a1a7-4282-a56b-405a6560eb38/jobs/211262/parallel-runs/0/steps/0-111
CircleCI isn't saving the cache if it already exists so we need to force it by using the `.Revision` placeholder as an approximation for "declaration files changed".
The diff is still not accurate for outdated branches since we compare against the latest commit on `next`. But this task has a very narrow use case so this limitation should be fine.

[test] Persist new declaration files in CI cache

---

docs/src/pages/components/pickers/DateAndTimePickers.js
docs/src/pages/components/pickers/DateAndTimePickers.tsx
docs/src/pages/components/pickers/DatePickers.js
docs/src/pages/components/pickers/DatePickers.tsx
docs/src/pages/components/pickers/TimePickers.js
docs/src/pages/components/pickers/TimePickers.tsx
docs/src/pages/components/pickers/pickers.md

I noticed the AM/PM bit of this datetime-local date picker is clipped with the current width (see [here](https://material-ui.com/components/pickers/#date-time-pickers) in the documentation site).  This one was easy enough to reproduce and model a fix for using the linked CodeSandbox so that's how I checked this fix.

[docs] Widen example datetime-local picker so it's not clipped

---

packages/material-ui/src/Avatar/Avatar.js
packages/material-ui/src/Avatar/Avatar.test.js
packages/material-ui/src/Badge/Badge.js
packages/material-ui/src/Button/Button.js
packages/material-ui/src/Button/Button.test.js
packages/material-ui/src/ButtonBase/ButtonBase.js
packages/material-ui/src/Slider/Slider.js
packages/material-ui/src/Slider/Slider.test.js
packages/material-ui/src/Typography/Typography.js
packages/material-ui/src/Typography/Typography.test.js
test/utils/describeConformanceV5.js

I have found this bug trying to customize the small and large variant of the button in #24095 for this spec:
See this reproduction for the issue: https://codesandbox.io/s/globalthemevariants-material-demo-forked-rexjl?file=/demo.tsx
```jsx
import { createMuiTheme, ThemeProvider } from "@material-ui/core/styles";
import Button from "@material-ui/core/Button";
const theme = createMuiTheme({
components: {
MuiButton: {
styleOverrides: {
sizeSmall: {
backgroundColor: "red"
}
}
}
}
});
export default function GlobalThemeVariants() {
return (
<ThemeProvider theme={theme}>
<Button variant="contained" size="small">
Small
</Button>
</ThemeProvider>
);
}
```
Once we apply the patch of this pull request: https://codesandbox.io/s/globalthemevariants-material-demo-forked- …

[styles] Fix resolution of default props

---

docs/src/pages/components/autocomplete/FreeSoloCreateOption.js
docs/src/pages/components/autocomplete/FreeSoloCreateOption.tsx

I noticed some unideal UX when copying the example from the docs for my Autocomplete component.  For the free solo with user input, I think if the user enters something that matches one of the existing options, it makes sense to hide the `Add "thing"` option.

[docs] Do not show 'Add' if user input matches existing option

---

packages/material-ui/src/locale/index.ts

The change was left with "más de" as there is a difference between "más" and "mas".
"más" is an adverb of quantity, while "mas" is used to express an idea
Fix #24300
*Preview*

[Table] Fix "more than" translation in es-ES

---

packages/material-ui-lab/src/internal/pickers/date-utils.ts
packages/material-ui-lab/src/internal/pickers/hooks/usePickerState.ts

We were passing the full props object to `parsePickerInputValue` when we only ever needed the value. Removed this unnecessary coupling so that it's more apparent when we actually need to run the effect that re-computes this. 
This revealed that the reason for disabling `react/exhaustive-dependencies` was outdated. It only served micro-optimization because, right now, every call site of `usePickerState` passed a stable `valueManager` so using it as a dependency was extraneous. However, this might break in the future so we need to be aware of it.
In the end we probably don't need the effect anyway (https://github.com/mui-org/material-ui/pull/24315) but in order to reason about the code I need to trim all the unnecessary parts.

[lab] Reduce coupling of parsing picker input value and props

---

.mocharc.js
packages/material-ui/test/integration/MenuList.test.js

The changes are motivated by the performance issue Circle CI has had since Friday, *test_unit-1* takes 6-7 minutes to run. It's x2 slower than usual. This leads to our slower tests to timeout 50% of the time.
Under normal conditions, the test in my env runs in 1min and in the CI, in about 2-3 minutes, hence the factor of x3. From what I recall, I don't have the faster machine in the team, I hope the 1s as the max timeout is enough for everybody. We might need to adjust it.
I have used this opportunity to remove the usage of a `setTimeout(500ms)` in a test case.

[test] Compensate for Circle CI's low performance

---

docs/src/modules/branding/AppSearch.tsx
docs/src/modules/components/AppSearch.js

This change was made to help more clearly show the keybind required to trigger the search functionality in the next version of the Documentation.

[docs] Sync AppSearch.tsx with AppSearch.js

---

docs/pages/branding/about.tsx
docs/src/modules/branding/BrandingDiscoverMore.tsx

https://deploy-preview-24327--material-ui.netlify.app/branding/about/
A new block

[website] Add Discover more

---

packages/material-ui-lab/src/DatePicker/DatePicker.test.tsx
packages/material-ui-lab/src/DatePicker/DatePickerKeyboard.test.tsx
packages/material-ui-lab/src/DateRangePicker/DateRangePicker.test.tsx
packages/material-ui-lab/src/DateTimePicker/DateTimePicker.test.tsx
packages/material-ui-lab/src/TimePicker/TimePicker.test.tsx
packages/material-ui-lab/src/YearPicker/YearPicker.test.tsx
packages/material-ui-styles/src/withStyles/withStyles.test.js
packages/material-ui/src/Menu/Menu.test.js
packages/material-ui/src/SpeedDial/SpeedDial.test.js

Generally, `expect(*)` should always receive the "bare" object i.e. not include any property access. The reason being that in case of a mismatch you want to see actionable debug information from the matcher. Otherwise you almost always end up logging the actual value anyway once it fails. The exception to this rule is if you don't have useful matchers to use.
`expect(sinonSpy.calledWith(value)).to.equal(true)` is problematic for two reasons:
- you don't see the actual value once it fails
- you don't know which call it is or how often the spy was called at all
Specifically, `DateTimePicker.test` `allows to select full date end-to-end` was failing after internal refactoring (https://github.com/mui-org/material-ui/pull/24367). It didn't provide actionable information that revealed that the …

[test] Move callback args to right side of assertion

---

.circleci/config.yml
.github/workflows/ci.yml
azure-pipelines.yml

Either cache the binaries or simply skip their download entirely if we know they're not needed (GH actions, Azure pipelines).
The downloads might contribute to a high variance in the install command ([4min 30s](https://app.circleci.com/pipelines/github/mui-org/material-ui/32926/workflows/0455010b-4d02-4a22-a4f3-4c17fd56b019/jobs/211628/parallel-runs/0/steps/0-105) vs. [1min 30s](https://app.circleci.com/pipelines/github/mui-org/material-ui/33144/workflows/257ad232-24c7-4e30-8e16-4f30814c867a/jobs/212292/parallel-runs/0/steps/0-105)) 
[Can't have a conditional `restore_cache`](https://app.circleci.com/pipelines/github/mui-org/material-ui/33150/workflows/9050d966-db67-492b-8255-ce59f5c94249/jobs/212321/parallel-runs/0/steps/0-105)

[test] Reduce download times of playwright binaries

---

.circleci/config.yml
packages/material-ui-lab/package.json
packages/material-ui-utils/package.json
packages/material-ui/package.json
scripts/buildTypes.js

Rewrites `import()` types from `material-ui/src` and `material-ui-styles/src` to their corresponding bare imports specifiers (`@material-ui/core` and `@material-ui/styles`). 
These are hardcoded at the moment to be careful with what we rewrite. I hope that this isn't something we have to maintain long-term.
This PR doesn't confirm that the created paths are correct but we now prevent publishing importing from source by switching https://github.com/mui-org/material-ui/pull/24188 from log to failure.
Changes: https://app.circleci.com/pipelines/github/mui-org/material-ui/33261/workflows/1bdc104f-9827-43bc-b987-2dbeb3e46fbf/jobs/212685/parallel-runs/0/steps/0-112
Closes #24112

[lab] Fix import paths in generated declaration files

---

netlify.toml

I'm guessing that downloading browser binaries caused https://app.netlify.com/sites/material-ui/deploys/5ffe3b6482a4970007159301
Seems to have an effect considering the install time went down.
Install time on this PR: 63s (https://app.netlify.com/sites/material-ui/deploys/5ffe84e42fdb7b0008a94c07)
Install time on next: 80-87s (sampled from the last 3 runs on next: https://app.netlify.com/sites/material-ui/deploys/5ffe878e255f010007a5696e, https://app.netlify.com/sites/material-ui/deploys/5ffe864f12c7d70007a378c3, https://app.netlify.com/sites/material-ui/deploys/5ffe3634a3ae5700077c2f96)

[core] Skip downloading browser binaries when building docs

---

.github/workflows/ci.yml
.github/workflows/maintenance.yml

Investigating https://github.com/mui-org/material-ui/pull/24303#issuecomment-759205364
Next time `Sync translations` are committed we'll see what the `actor` is. Unclear why the approach works for me (`github.actor != 'eps1lon'`) but not `l10nbot`
Using `actor` equality works: https://github.com/mui-org/material-ui/actions/runs/481976947
Using `actor` inequality with me works: https://github.com/mui-org/material-ui/actions/runs/481976947

[test] Debug expensive GH actions still runing for l10nbot

---

docs/pages/api-docs/paper.json
docs/translations/api-docs/paper/paper.json
framer/scripts/framerConfig.js
packages/material-ui/src/MobileStepper/MobileStepper.test.js
packages/material-ui/src/Paper/Paper.d.ts
packages/material-ui/src/Paper/Paper.js
packages/material-ui/src/Paper/Paper.test.js
packages/material-ui/src/Paper/index.d.ts
packages/material-ui/src/Paper/index.js
packages/material-ui/src/Paper/paperClasses.d.ts
packages/material-ui/src/Paper/paperClasses.js

[Paper] Migrate to emotion

---

CHANGELOG.md

[CHANGELOG] Prepare v5.0.0-alpha.23

---

packages/material-ui/package.json
scripts/buildTypes.js

- don't generate declaration files in `test_types` (were previously only built for `/core`)
We already generate them in our GitHub `CI` workflow and `codesandbox/ci` task.
When they fail, they fail because of an incorrect build setup. If they fail because of the type-checker, the prior type-checking already failed. So they don't add anything to `test_types` with regards to type-checking.
- Use `-b` flag when generating declaration files
This is required to build referenced projects. It's working with `-p` right now (probably due to the order in which we build) but broke https://github.com/mui-org/material-ui/pull/24396.

[core] Normalize generating declaration files

---

packages/material-ui-lab/src/internal/pickers/hooks/usePickerState.ts
packages/material-ui-lab/src/internal/pickers/hooks/useUtils.ts

Based on https://github.com/mui-org/material-ui/pull/24366 ([diff](https://github.com/eps1lon/material-ui/compare/test/drop-calledWith...eps1lon:fix/lab-pickers-on-change))
I [originally misidentified that `usePickerState` needs `getDerivedStateFromProps`](https://github.com/mui-org/material-ui/pull/24315/commits/9dd7afc8ccbf40ea1f8865aa02d58be395ba92b8?file-filters%5B%5D=.ts#diff-e02e96ce7f2b6008184ad7ab79b7e9edd19601b3f28a5f11e6d43c26854a2dc1). I believe now that `usePickerState` implements the draft pattern but the previous implementation used `useEffect`. However, that pattern can be implemented without needing to commit twice. The React docs go over this in more detail: https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html#recap (look for usage of "draft").
We …

[lab] Reflect draft pattern of picker value in implementation

---

docs/pages/api-docs/filled-input.json
docs/pages/api-docs/input.json
docs/pages/api-docs/outlined-input.json
docs/pages/api-docs/text-field.json
docs/scripts/buildApi.ts
docs/src/modules/utils/defaultPropsHandler.js
docs/types/react-docgen.d.ts
packages/material-ui/src/TextField/TextField.d.ts
packages/material-ui/src/TextField/TextField.js
scripts/generateProptypes.ts

Adds default value to API docs for:
- `TextField#margin`
- `Input#inputProps`
- `FilledInput#inputProps`
- `OutlinedInput#inputProps`
These were previously ignored because the props was not implemented in the documented component but in the extended component. We do force the documentation sometimes in `yarn proptypes` with `useExternalDocumentation` so we need to account for that in our default props handler.

[docs] Document default values of external props

---

docs/src/pages/components/grid/AutoGrid.js
docs/src/pages/components/grid/AutoGrid.tsx
docs/src/pages/components/grid/grid.md
docs/src/pages/components/transfer-list/SelectAllTransferList.js
docs/src/pages/components/transfer-list/SelectAllTransferList.tsx
docs/src/pages/components/transfer-list/TransferList.js
docs/src/pages/components/transfer-list/TransferList.tsx
docs/src/pages/components/transfer-list/transfer-list.md
packages/material-ui/src/Grid/Grid.js
packages/material-ui/src/Grid/Grid.test.js
test/regressions/tests/Grid/StressGrid.js
test/regressions/tests/Grid/StressNestedGrid.js

Fixes #24272
This PR is to be a way to implement what  #24299  does without creating a new prop.

[Grid] Fix horizontal scrollbar and nested dimensions

---

packages/material-ui-lab/src/DateRangePicker/DateRangePickerInput.tsx

Remove leaky variant for Textfield input prop in DateRangePickerInput component.
It will prevent overriding variant prop for Textfield input.
Closes #24166

[DateRangePicker] Remove variant prop override for Textfield

---

docs/pages/_app.js
docs/src/modules/utils/getDemoConfig.js
docs/src/pages/guides/interoperability/interoperability.md
docs/src/pages/guides/migration-v4/migration-v4.md
packages/material-ui-styled-engine-sc/src/StyledEngineProvider/StyledEngineProvider.d.ts
packages/material-ui-styled-engine-sc/src/StyledEngineProvider/StyledEngineProvider.js
packages/material-ui-styled-engine-sc/src/StyledEngineProvider/index.d.ts
packages/material-ui-styled-engine-sc/src/StyledEngineProvider/index.js
packages/material-ui-styled-engine-sc/src/StylesProvider/StylesProvider.d.ts
packages/material-ui-styled-engine-sc/src/StylesProvider/index.d.ts
packages/material-ui-styled-engine-sc/src/StylesProvider/index.js
packages/material-ui-styled-engine-sc/src/index.d.ts
packages/material-ui-styled-engine-sc/src/index.js
packages/material-ui-styled-engine/src/StyledEngineProvider/StyledEngineProvider.d.ts
packages/material-ui-styled-engine/src/StyledEngineProvider/StyledEngineProvider.js
packages/material-ui-styled-engine/src/StyledEngineProvider/index.d.ts
packages/material-ui-styled-engine/src/StyledEngineProvider/index.js
packages/material-ui-styled-engine/src/StylesProvider/StylesProvider.d.ts
packages/material-ui-styled-engine/src/StylesProvider/index.d.ts
packages/material-ui-styled-engine/src/StylesProvider/index.js
packages/material-ui-styled-engine/src/index.d.ts
packages/material-ui-styled-engine/src/index.js
packages/material-ui/src/StyledEngineProvider/index.d.ts
packages/material-ui/src/StyledEngineProvider/index.js
packages/material-ui/src/index.d.ts
packages/material-ui/src/index.js
test/regressions/TestViewer.js

- [styled-engine] Clear the confusion between the JSS and emotion/sc API
```diff
-import { StylesProvider } from '@material-ui/core';
+import StyledEngineProvider from '@material-ui/core/StyledEngineProvider';
```
or 
```diff
-import { StylesProvider } from '@material-ui/core';
+import { StyledEngineProvider } from '@material-ui/core';
```
---
With https://github.com/mui-org/material-ui/pull/23934 we have introduced `StylesProvider` component that has the `injectFirst` option to allow emotion styles to be injected first. We re-exported this component from `@mateiral-ui/core`. However, as we already have component `StylesProvider` which is exported from `@material-ui/core/styles`, there was lots of confusion around what's the difference and which one is the correct one. There was …

[styled-engine] Rename StylesProvider to StyledEngineProvider

---

docs/src/modules/components/AppNavDrawer.js

The bug: 
https://user-images.githubusercontent.com/3165635/104627217-08a4ca80-5697-11eb-911c-6ccd49020340.mp4
The origin: https://github.com/mui-org/material-ui/pull/15409/files#diff-e33c632b2237fb5233ca8600034cf02952cfaa668c9d6a5d08d5252891059d9dR59 @mbrookes Do you remember the issue this line was meant to fix?
Compare the loading UX between these two:
- HEAD: https://next.material-ui.com/components/alert/#variants
- PR: https://deploy-preview-24418--material-ui.netlify.app/components/alert/#variants

[docs] Fix scroll shift

---

docs/pages/api-docs/app-bar.json
docs/translations/api-docs/app-bar/app-bar.json
packages/material-ui/src/AppBar/AppBar.d.ts
packages/material-ui/src/AppBar/AppBar.js
packages/material-ui/src/AppBar/AppBar.test.js
packages/material-ui/src/AppBar/appBarClasses.d.ts
packages/material-ui/src/AppBar/appBarClasses.js
packages/material-ui/src/AppBar/index.d.ts
packages/material-ui/src/AppBar/index.js

One of https://github.com/mui-org/material-ui/issues/24405

[AppBar] Migrate to emotion

---

docs/pages/api-docs/checkbox.json
docs/pages/api-docs/switch.json
docs/translations/api-docs/checkbox/checkbox.json
docs/translations/api-docs/switch/switch.json
framer/Material-UI.framerfx/code/Checkbox.tsx
framer/Material-UI.framerfx/code/Switch.tsx
packages/material-ui/src/Checkbox/Checkbox.js
packages/material-ui/src/Switch/Switch.js
packages/material-ui/src/internal/SwitchBase.d.ts
scripts/generateProptypes.ts

Adds proptype for native checkbox prop defaultChecked. Generates docs for defaultChecked prop for Switch and Checkbox components.
Does prop validation for defaultChecked prop in Checkbox component.
Closes #24426

[Checkbox][Switch] Document defaultChecked

---

yarn.lock

Dependabot tries to bump that in all PRs leading to duplicate packages. Doing it manually here to resolve every affected PR.
[Changelog](https://github.com/webpack/webpack/releases/tag/v4.46.0)

Bump webpack to 4.46.0

---

packages/material-ui/src/Avatar/Avatar.js
packages/material-ui/src/Button/Button.js

So far we've been passing styleProps on the slots that actually use these props in the styled functions. However, I belive it's better for consistency to send them to all slots, as future changes to the styled function won't require changes like this.

[core] Pass styleProps on all slots in the styled() components

---

packages/material-ui/src/ButtonBase/TouchRipple.test.js
test/utils/describeConformanceV5.js

Inspired by https://github.com/mui-org/material-ui/pull/24448#discussion_r559097653
Some components does not support any styling props, so testing if the variants work does not make sense. However, so far we had the option to only disable all `theme.components` related test, not just one of them. This PR splits this tests to allow that scenario.

[test] Split tests in describeConformanceV5 to isolate them

---

docs/scripts/buildApi.ts
docs/src/modules/utils/parseTest.ts

We used `exactPropType = ` as an indicator for non spreadable props. From now on we will use this only as fallback and use parsing of `describeConformance` as the source of truth. 
This is less brittle (current "marker" relies on formatting and isn't tested when `describeConformance` isn't used) and will be required for API documentation of `*Picker` components.

[docs] Compute spreadable from tests

---

docs/pages/api-docs/svg-icon.json
docs/translations/api-docs/svg-icon/svg-icon.json
packages/material-ui/src/ButtonBase/TouchRipple.test.js
packages/material-ui/src/SvgIcon/SvgIcon.d.ts
packages/material-ui/src/SvgIcon/SvgIcon.js
packages/material-ui/src/SvgIcon/SvgIcon.test.js
packages/material-ui/src/SvgIcon/index.d.ts
packages/material-ui/src/SvgIcon/index.js
packages/material-ui/src/SvgIcon/svgIconClasses.d.ts
packages/material-ui/src/SvgIcon/svgIconClasses.js
test/utils/describeConformance.js
test/utils/describeConformanceV5.js

One iteration on #24405. Took 31 min

[SvgIcon] Migrate to emotion

---

packages/material-ui/src/Alert/Alert.js
packages/material-ui/src/AlertTitle/AlertTitle.js
packages/material-ui/src/AppBar/AppBar.js
packages/material-ui/src/AvatarGroup/AvatarGroup.js

I overlooked in the reviews, that people were spreading `other`, not `props` on the `styleProps`. `styleProps` should contain all props with defaults, not just a subset of it, so that we can avoid int he future issues for some props not being passed to the styled funciton.

[core] Fix styleProps to always contain all props

---

docs/pages/api-docs/collapse.json
docs/translations/api-docs/collapse/collapse.json
packages/material-ui/src/Collapse/Collapse.d.ts
packages/material-ui/src/Collapse/Collapse.js
packages/material-ui/src/Collapse/Collapse.test.js
packages/material-ui/src/Collapse/collapseClasses.d.ts
packages/material-ui/src/Collapse/collapseClasses.js
packages/material-ui/src/Collapse/index.d.ts
packages/material-ui/src/Collapse/index.js
packages/material-ui/src/StepContent/StepContent.test.js

This PR migrates the `Collapse` component for v5 as a part of #24405.
**Notice:** this is my very first pull request to this repository.  If I have made any mistakes, please do not hesitate to let me know and I will fix it right away!  Feel free to give any and all critique -- I'm a big girl, I can handle it.  😛 
_This contribution, and all other contributions I make to Material UI, are performed under [Gooborg Studios, LLC](https://www.gooborg.com) on behalf of [Fox and Geese, LLC](https://github.com/foxandgeese).  Both companies agree to surrender all contributions under MUI's MIT license._

[Collapse] Migrate to emotion

---

docs/pages/api-docs/icon.json
docs/translations/api-docs/icon/icon.json
framer/Material-UI.framerfx/code/Icon.tsx
framer/scripts/framerConfig.js
packages/material-ui/src/Icon/Icon.d.ts
packages/material-ui/src/Icon/Icon.js
packages/material-ui/src/Icon/Icon.test.js
packages/material-ui/src/Icon/iconClasses.d.ts
packages/material-ui/src/Icon/iconClasses.js
packages/material-ui/src/Icon/index.d.ts
packages/material-ui/src/Icon/index.js
packages/material-ui/src/SvgIcon/SvgIcon.js

This PR migrates the `Icon` component to emotion, with code heavily based upon #24506.  Part of #24405.

[Icon] Migrate to emotion

---

docs/pages/api-docs/grid.json
docs/src/pages/components/grid/InteractiveGrid.tsx
docs/src/pages/components/grid/grid.md
docs/src/pages/guides/migration-v4/migration-v4.md
docs/translations/api-docs/grid/grid.json
packages/material-ui-system/src/index.d.ts
packages/material-ui/src/Box/Box.d.ts
packages/material-ui/src/Grid/Grid.d.ts
packages/material-ui/src/Grid/Grid.js
packages/material-ui/src/Grid/Grid.test.js
packages/material-ui/src/Grid/gridClasses.d.ts
packages/material-ui/src/Grid/gridClasses.js

The props: `alignItems` `alignContent` and `justifyContent` and their `classes` and style overrides keys were removed: "align-items-xs-center", "align-items-xs-flex-start", "align-items-xs-flex-end", "align-items-xs-baseline", "align-content-xs-center", "align-content-xs-flex-start", "align-content-xs-flex-end", "align-content-xs-space-between", "align-content-xs-space-around", "justify-content-xs-center", "justify-content-xs-flex-end", "justify-content-xs-space-between", "justify-content-xs-space-around" and "justify-content-xs-space-evenly". These props are now considered part of the system, not on the `Grid` component itself. If you still wish to add overrides for them, you can use the `theme.components.MuiGrid.variants` options. For example
```diff
const theme = createMuiTheme({ …
```

[Grid] Add system props

---

docs/next.config.js
docs/src/modules/components/ApiPage.js
docs/src/modules/components/AppTableOfContents.js
docs/src/modules/components/PageContext.js

current `next`: https://60083a7d297f240007fb4a7f--material-ui.netlify.app/api/accordion/
PR (with all locales): https://60084e9dc1b516000793d8ec--material-ui.netlify.app/api/accordion/

[docs] Fix ToC on /api pages linking to api-docs

---

docs/src/modules/components/ApiPage.js

The table of contents entry for `Component name` on `/api/*` pages is currently not translated.
The issue was that we didn't decide on whether to name the hash `component-name` or `componentName` and ended up passing around different formats (and sometimes converting it back again)
Note that the link is still wrong since it links to `/api-docs` which is fixed in https://github.com/mui-org/material-ui/pull/24515
current `next`: https://60083a7d297f240007fb4a7f--material-ui.netlify.app/ru/api/accordion/
PR: https://deploy-preview-24517--material-ui.netlify.app/api/accordion/

[docs] Fix ToC "Component name" fragment link on /api/*

---

packages/material-ui-system/src/spacing.js
packages/material-ui-system/src/spacing.test.js

Closes #24519. It's targetting `master` because it fixes an issue with a third-party dependency we have no control over: Chrome and it throws an exception. I will apply it to `next` too afterward.

[system] Fix handling of null-ish values

---

docs/pages/branding/about.tsx
docs/src/modules/branding/BrandingBeginToday.tsx
docs/src/modules/branding/BrandingFooter.tsx
docs/src/modules/branding/BrandingRoot.tsx

Review link https://deploy-preview-24521--material-ui.netlify.app/branding/about/

[website] Add Join Us block

---

packages/material-ui-lab/src/PickersDay/PickersDay.tsx

- [DatePicker] Remove the `.MuiPickersDay-dayLabel` node, customizations can be applied on `.MuiPickersDay-root` directly.
---
resolves #24162. For context, the div was added in https://github.com/mui-org/material-ui-pickers/pull/1416.

[DatePicker] Remove unnecessary wrapping dom node

---

docs/pages/api-docs/link.json
docs/translations/api-docs/link/link.json
packages/material-ui/src/Link/Link.d.ts
packages/material-ui/src/Link/Link.js
packages/material-ui/src/Link/Link.test.js
packages/material-ui/src/Link/index.d.ts
packages/material-ui/src/Link/index.js
packages/material-ui/src/Link/linkClasses.d.ts
packages/material-ui/src/Link/linkClasses.js

[Link] Migrate to emotion

---

docs/pages/api-docs/autocomplete.json
docs/pages/api-docs/backdrop.json
docs/pages/api-docs/badge.json
docs/pages/api-docs/click-away-listener.json
docs/pages/api-docs/dialog.json
docs/pages/api-docs/form-control-label.json
docs/pages/api-docs/menu.json
docs/pages/api-docs/mobile-stepper.json
docs/pages/api-docs/modal.json
docs/pages/api-docs/popover.json
docs/pages/api-docs/popper.json
docs/pages/api-docs/slider.json
docs/pages/api-docs/swipeable-drawer.json
docs/pages/api-docs/tab-context.json
docs/pages/api-docs/tab-panel.json
docs/pages/api-docs/tab-scroll-button.json
docs/pages/api-docs/table-pagination.json
docs/pages/api-docs/toggle-button.json
docs/pages/api-docs/tooltip.json
docs/pages/api-docs/tree-item.json
docs/pages/api-docs/unstable-trap-focus.json
docs/scripts/buildApi.ts
docs/src/modules/components/ApiPage.js

Props in /api/* are now sorted by required first and then by their name. 
What props are required is the most important information on how to use a component. Scrolling through the list is error prone and time consuming.
~Sorting on the frontend to not invalidate translated props descriptions.~ Double checked after vague statements from Olivier that order of props is based on `pages/api-docs->props` not `translations/api-docs->propDescriptions`.
Example: /api/modal
[current `next`](https://60096848cd37fd0007cbd089--material-ui.netlify.app/api/modal/#props)
[PR](https://deploy-preview-24526--material-ui.netlify.app/api/modal/#props)

[docs] List required props first in /api/*

---

docs/pages/api-docs/accordion-details.json
docs/translations/api-docs/accordion-details/accordion-details.json
packages/material-ui/src/AccordionDetails/AccordionDetails.d.ts
packages/material-ui/src/AccordionDetails/AccordionDetails.js
packages/material-ui/src/AccordionDetails/AccordionDetails.test.js
packages/material-ui/src/AccordionDetails/accordionDetailsClasses.d.ts
packages/material-ui/src/AccordionDetails/accordionDetailsClasses.js
packages/material-ui/src/AccordionDetails/index.d.ts
packages/material-ui/src/AccordionDetails/index.js

This PR migrates the `AccordionDetails` component to the new emotion format as a part of #24405.

[Accordion] Migrate AccordionDetails to emotion

---

docs/pages/api-docs/accordion-actions.json
docs/translations/api-docs/accordion-actions/accordion-actions.json
packages/material-ui/src/AccordionActions/AccordionActions.d.ts
packages/material-ui/src/AccordionActions/AccordionActions.js
packages/material-ui/src/AccordionActions/AccordionActions.test.js
packages/material-ui/src/AccordionActions/accordionActionsClasses.d.ts
packages/material-ui/src/AccordionActions/accordionActionsClasses.js
packages/material-ui/src/AccordionActions/index.d.ts
packages/material-ui/src/AccordionActions/index.js

This PR migrates the `AccordionActions` component to the new emotion format as a part of #24405.

[Accordion] Migrate AccordionActions to emotion

---

packages/material-ui-lab/src/DesktopDatePicker/DesktopDatePicker.test.tsx
packages/material-ui-lab/src/internal/pickers/test-utils.tsx

- reduce work to arrange test
- drop `openDesktopPicker`
It was used inconsistently. Introduce `UncontrolledOpenDesktopDatePicker` instead which does the same thing but leads to less work to do. `openDesktopPicker` was only used to arrange anyway.
- Added a test for opening which was only tested implicitly.

[test] Simplify DatePicker tests

---

docs/src/modules/components/Link.tsx
examples/nextjs-with-typescript/src/Link.tsx
examples/nextjs/src/Link.js

I have found that Link component in nextjs example was ignoring the `locale` prop.

[examples] Add `locale` prop to the Nextjs Link component

---

packages/material-ui/src/internal/SwitchBase.d.ts
packages/material-ui/src/internal/SwitchBase.js
packages/material-ui/src/internal/SwitchBase.test.js
packages/material-ui/src/internal/switchBaseClasses.d.ts
packages/material-ui/src/internal/switchBaseClasses.js
test/utils/describeConformanceV5.js

This PR migrates the `SwitchBase` component to the new emotion format as a part of #24405.  Additionally, since we're here, this fixes a typo in the component's TypeScript definition for the classes (`inpit` -> `input`).

[Switch] Migrate SwitchBase to emotion

---

docs/pages/api-docs/card-actions.json
docs/translations/api-docs/card-actions/card-actions.json
packages/material-ui/package.json
packages/material-ui/src/CardActions/CardActions.d.ts
packages/material-ui/src/CardActions/CardActions.js
packages/material-ui/src/CardActions/CardActions.test.js
packages/material-ui/src/CardActions/cardActionsClasses.d.ts
packages/material-ui/src/CardActions/cardActionsClasses.js
packages/material-ui/src/CardActions/index.d.ts
packages/material-ui/src/CardActions/index.js

One of #24405
💡 In which scenario should `disableSpacing` work? doing the migration I realized that it does not work, this came from before.

[Card] Migrate CardActions to emotion

---

docs/pages/api-docs/accordion-summary.json
docs/pages/api-docs/accordion.json
docs/src/pages/components/accordion/BasicAccordion.js
docs/src/pages/components/accordion/BasicAccordion.tsx
docs/src/pages/components/accordion/ControlledAccordions.js
docs/src/pages/components/accordion/ControlledAccordions.tsx
docs/src/pages/components/accordion/CustomizedAccordions.js
docs/src/pages/components/accordion/CustomizedAccordions.tsx
docs/src/pages/components/accordion/accordion.md
docs/translations/api-docs/accordion-summary/accordion-summary.json
docs/translations/api-docs/accordion/accordion.json
packages/material-ui/src/Accordion/Accordion.d.ts
packages/material-ui/src/Accordion/Accordion.js
packages/material-ui/src/Accordion/AccordionContext.js
packages/material-ui/src/Accordion/accordionClasses.d.ts
packages/material-ui/src/Accordion/accordionClasses.js
packages/material-ui/src/AccordionSummary/AccordionSummary.d.ts
packages/material-ui/src/AccordionSummary/AccordionSummary.js
packages/material-ui/src/AccordionSummary/accordionSummaryClasses.d.ts
packages/material-ui/src/AccordionSummary/accordionSummaryClasses.js
packages/material-ui/src/FormHelperText/FormHelperText.js

resolves #24492 
I've added the `disableGutters` prop to the `AccordionSummary` and `AccordionDetails` Components.

[Accordion] Allow to disable gutter/spacing

---

docs/pages/api-docs/card-content.json
docs/translations/api-docs/card-content/card-content.json
packages/material-ui/src/CardContent/CardContent.d.ts
packages/material-ui/src/CardContent/CardContent.js
packages/material-ui/src/CardContent/CardContent.test.js
packages/material-ui/src/CardContent/cardContentClasses.d.ts
packages/material-ui/src/CardContent/cardContentClasses.js
packages/material-ui/src/CardContent/index.d.ts
packages/material-ui/src/CardContent/index.js

[Card] Migrate CardContent to emotion

---

packages/material-ui/src/CardActions/index.d.ts
packages/material-ui/src/CardActions/index.js
packages/material-ui/src/CardContent/index.js

I didn't rebase the different Card PRs for migrating to emotion, so I didn't catch this error.

[CardActions] Fix wrong classes export name

---

docs/pages/api-docs/bottom-navigation-action.json
docs/pages/api-docs/bottom-navigation.json
docs/translations/api-docs/bottom-navigation-action/bottom-navigation-action.json
docs/translations/api-docs/bottom-navigation/bottom-navigation.json
framer/scripts/framerConfig.js
packages/material-ui/src/BottomNavigation/BottomNavigation.d.ts
packages/material-ui/src/BottomNavigation/BottomNavigation.js
packages/material-ui/src/BottomNavigation/BottomNavigation.test.js
packages/material-ui/src/BottomNavigation/bottomNavigationClasses.d.ts
packages/material-ui/src/BottomNavigation/bottomNavigationClasses.js
packages/material-ui/src/BottomNavigation/index.d.ts
packages/material-ui/src/BottomNavigation/index.js
packages/material-ui/src/BottomNavigationAction/BottomNavigationAction.d.ts
packages/material-ui/src/BottomNavigationAction/BottomNavigationAction.js
packages/material-ui/src/BottomNavigationAction/BottomNavigationAction.test.js
packages/material-ui/src/BottomNavigationAction/bottomNavigationActionClasses.d.ts
packages/material-ui/src/BottomNavigationAction/bottomNavigationActionClasses.js
packages/material-ui/src/BottomNavigationAction/index.d.ts
packages/material-ui/src/BottomNavigationAction/index.js

This PR migrates the `BottomNavigation` and `BottomNavigationAction` components to the new emotion format as a part of #24405.
Notice: there's actually quite a number of failing builds for this one, such as with the docs generation.  Hoping to get some feedback on how to resolve said issues.

[BottomNavigation] Migrate to emotion

---

docs/pages/api-docs/list-item-secondary-action.json
docs/translations/api-docs/list-item-secondary-action/list-item-secondary-action.json
framer/Material-UI.framerfx/code/ListItem.tsx
packages/material-ui/src/ListItemSecondaryAction/ListItemSecondaryAction.d.ts
packages/material-ui/src/ListItemSecondaryAction/ListItemSecondaryAction.js
packages/material-ui/src/ListItemSecondaryAction/ListItemSecondaryAction.test.js
packages/material-ui/src/ListItemSecondaryAction/listItemSecondaryActionClasses.d.ts
packages/material-ui/src/ListItemSecondaryAction/listItemSecondaryActionClasses.js

This PR migrates the`ListItemSecondaryAction` component to the new emotion format as a part of #24405.

[List] Migrate ListItemSecondaryAction to emotion

---

packages/material-ui/src/Hidden/HiddenCss.js

[Hidden] Fix unsupported props warning when sx prop is used

---

docs/pages/api-docs/toolbar.json
docs/translations/api-docs/toolbar/toolbar.json
packages/material-ui/src/Toolbar/Toolbar.d.ts
packages/material-ui/src/Toolbar/Toolbar.js
packages/material-ui/src/Toolbar/Toolbar.test.js
packages/material-ui/src/Toolbar/index.d.ts
packages/material-ui/src/Toolbar/index.js
packages/material-ui/src/Toolbar/toolbarClasses.d.ts
packages/material-ui/src/Toolbar/toolbarClasses.js

MIgrates `Toolbar` to emotion #24405 
This PR may need some help with the testing as I was not able to get it working.
Was curious if I could get pointed in the right direction.

[Toolbar] Migrate to emotion

---

docs/pages/api-docs/dialog-actions.json
docs/translations/api-docs/dialog-actions/dialog-actions.json
packages/material-ui/src/DialogActions/DialogActions.d.ts
packages/material-ui/src/DialogActions/DialogActions.js
packages/material-ui/src/DialogActions/DialogActions.test.js
packages/material-ui/src/DialogActions/dialogActionsClasses.d.ts
packages/material-ui/src/DialogActions/dialogActionsClasses.js
packages/material-ui/src/DialogActions/index.d.ts
packages/material-ui/src/DialogActions/index.js

[Dialog] Migrate DialogActions to emotion

---

.codesandbox/ci.json
package.json

Fixes https://ci.codesandbox.io/status/mui-org/material-ui/pr/24565/builds/95546
Note: This doesn't fix the more common "EACCES: permission denied, mkdir '/tmp/output/@material-ui'" (e.g. https://ci.codesandbox.io/status/mui-org/material-ui/pr/24628/builds/95578).

[core] Skip downloading browser binaries in codesandbox/ci

---

scripts/releaseTag.js

Tested originally it without having the `material-ui-docs` remote. Noticed when going through the release workflow.

[core] Fix release:tag pushing to material-ui-docs

---

docs/src/pages/components/date-picker/SubComponentsPickers.js
docs/src/pages/components/date-picker/SubComponentsPickers.tsx
docs/src/pages/components/date-picker/date-picker.md
packages/material-ui-lab/src/DateRangePicker/DateRangePicker.tsx
packages/material-ui-lab/src/DateRangePicker/DateRangePickerViewDesktop.tsx
packages/material-ui-lab/src/DateRangePicker/DateRangePickerViewMobile.tsx
packages/material-ui-lab/src/DateRangePickerDay/DateRangePickerDay.tsx
packages/material-ui-lab/src/DayPicker/DayPicker.test.tsx
packages/material-ui-lab/src/DayPicker/PickersCalendar.tsx
packages/material-ui-lab/src/DesktopDateRangePicker/DesktopDateRangePicker.tsx
packages/material-ui-lab/src/MobileDateRangePicker/MobileDateRangePicker.tsx
packages/material-ui-lab/src/StaticDateRangePicker/StaticDateRangePicker.test.tsx
packages/material-ui-lab/src/StaticDateRangePicker/StaticDateRangePicker.tsx

[pickers] Fix role attribute

---

docs/pages/api-docs/image-list.json
docs/translations/api-docs/image-list/image-list.json
packages/material-ui/src/ImageList/ImageList.d.ts
packages/material-ui/src/ImageList/ImageList.js
packages/material-ui/src/ImageList/ImageList.test.js
packages/material-ui/src/ImageList/imageListClasses.d.ts
packages/material-ui/src/ImageList/imageListClasses.js
packages/material-ui/src/ImageList/index.d.ts
packages/material-ui/src/ImageList/index.js

This PR migrates the`ImageList` component to the new emotion format as a part of #24405.

[ImageList] Migrate to emotion

---

docs/pages/api-docs/dialog-title.json
docs/translations/api-docs/dialog-title/dialog-title.json
packages/material-ui/src/DialogTitle/DialogTitle.d.ts
packages/material-ui/src/DialogTitle/DialogTitle.js
packages/material-ui/src/DialogTitle/DialogTitle.test.js
packages/material-ui/src/DialogTitle/dialogTitleClasses.d.ts
packages/material-ui/src/DialogTitle/dialogTitleClasses.js
packages/material-ui/src/DialogTitle/index.d.ts
packages/material-ui/src/DialogTitle/index.js

[Dialog] Migrate DialogTitle to emotion

---

docs/pages/api-docs/image-list-item.json
docs/translations/api-docs/image-list-item/image-list-item.json
packages/material-ui/src/ImageListItem/ImageListItem.d.ts
packages/material-ui/src/ImageListItem/ImageListItem.js
packages/material-ui/src/ImageListItem/ImageListItem.test.js
packages/material-ui/src/ImageListItem/imageListItemClasses.d.ts
packages/material-ui/src/ImageListItem/imageListItemClasses.js
packages/material-ui/src/ImageListItem/index.d.ts
packages/material-ui/src/ImageListItem/index.js

This PR migrates the `ImageListItem` component to the new emotion format as a part of #24405.
Because `classes` props was not in `ImageListItem.d.ts`, it was delete by running `yarn proptypes`. Should I fix this here?

[ImageList] Migrate ImageListItem to emotion

---

docs/pages/api-docs/card-media.json
docs/translations/api-docs/card-media/card-media.json
packages/material-ui/src/CardMedia/CardMedia.d.ts
packages/material-ui/src/CardMedia/CardMedia.js
packages/material-ui/src/CardMedia/CardMedia.test.js
packages/material-ui/src/CardMedia/cardMediaClasses.d.ts
packages/material-ui/src/CardMedia/cardMediaClasses.js
packages/material-ui/src/CardMedia/index.d.ts
packages/material-ui/src/CardMedia/index.js

[Card] Migrate CardMedia to emotion

---

docs/pages/api-docs/card-header.json
docs/translations/api-docs/card-header/card-header.json
packages/material-ui/src/CardHeader/CardHeader.d.ts
packages/material-ui/src/CardHeader/CardHeader.js
packages/material-ui/src/CardHeader/CardHeader.test.js
packages/material-ui/src/CardHeader/cardHeaderClasses.d.ts
packages/material-ui/src/CardHeader/cardHeaderClasses.js
packages/material-ui/src/CardHeader/index.d.ts
packages/material-ui/src/CardHeader/index.js

[Card] Migrate CardHeader to emotion

---

docs/pages/api-docs/fab.json
docs/translations/api-docs/fab/fab.json
framer/scripts/framerConfig.js
packages/material-ui/src/Fab/Fab.d.ts
packages/material-ui/src/Fab/Fab.js
packages/material-ui/src/Fab/Fab.test.js
packages/material-ui/src/Fab/fabClasses.d.ts
packages/material-ui/src/Fab/fabClasses.js
packages/material-ui/src/Fab/index.d.ts
packages/material-ui/src/Fab/index.js
packages/material-ui/src/SpeedDialAction/SpeedDialAction.test.js

[Fab] Migrate to emotion

---

docs/pages/api-docs/list-item-icon.json
docs/translations/api-docs/list-item-icon/list-item-icon.json
packages/material-ui/src/ListItemIcon/ListItemIcon.d.ts
packages/material-ui/src/ListItemIcon/ListItemIcon.js
packages/material-ui/src/ListItemIcon/ListItemIcon.test.js
packages/material-ui/src/ListItemIcon/index.d.ts
packages/material-ui/src/ListItemIcon/index.js
packages/material-ui/src/ListItemIcon/listItemIconClasses.d.ts
packages/material-ui/src/ListItemIcon/listItemIconClasses.js

[List] Migrate ListItemIcon to emotion

---

.dependabot/config.yml
.eslintrc.js
docs/babel.config.js
docs/next.config.js
docs/package.json
docs/scripts/buildApi.ts
docs/src/modules/utils/findPages.js
docs/src/pages.ts
docs/src/pagesApi.js
package.json
yarn.lock

We're currently computing all the available pages in `/api` at runtime. Since we rely on the filesystem, we're using `babel-preval` to compute the api pages at transpile time. However, transpiled files are cached and we cannot invalidate that the cache for a particular file. This leads to netlify deploys failing on a cache hit when pages changed (e.g. in https://github.com/mui-org/material-ui/pull/24626: https://app.netlify.com/sites/material-ui/deploys/60103453834bf5000813eeee).
Invalidating just `babel-preval` is currently not possible (https://github.com/kentcdodds/babel-plugin-preval/issues/19).
We're now hardcoding /api pages just like any other page. This reduces complexity of what is considered a page. Since we already require committing `yarn docs:api` changes, we can leverage …

[core] Fix `next` using stale pages

---

docs/pages/api-docs/card-action-area.json
docs/translations/api-docs/card-action-area/card-action-area.json
packages/material-ui/src/CardActionArea/CardActionArea.d.ts
packages/material-ui/src/CardActionArea/CardActionArea.js
packages/material-ui/src/CardActionArea/CardActionArea.test.js
packages/material-ui/src/CardActionArea/cardActionAreaClasses.d.ts
packages/material-ui/src/CardActionArea/cardActionAreaClasses.js
packages/material-ui/src/CardActionArea/index.d.ts
packages/material-ui/src/CardActionArea/index.js

[Card] Migrate CardActionArea to emotion

---

docs/pages/api-docs/circular-progress.json
docs/translations/api-docs/circular-progress/circular-progress.json
framer/scripts/framerConfig.js
packages/material-ui/src/CircularProgress/CircularProgress.d.ts
packages/material-ui/src/CircularProgress/CircularProgress.js
packages/material-ui/src/CircularProgress/CircularProgress.test.js
packages/material-ui/src/CircularProgress/circularProgressClasses.d.ts
packages/material-ui/src/CircularProgress/circularProgressClasses.js
packages/material-ui/src/CircularProgress/index.d.ts
packages/material-ui/src/CircularProgress/index.js

#24405 
Lol still not perfect.

[CircularProgress] Migrate to emotion

---

docs/pages/api-docs/image-list-item-bar.json
docs/translations/api-docs/image-list-item-bar/image-list-item-bar.json
packages/material-ui/src/ImageListItemBar/ImageListItemBar.d.ts
packages/material-ui/src/ImageListItemBar/ImageListItemBar.js
packages/material-ui/src/ImageListItemBar/ImageListItemBar.test.js
packages/material-ui/src/ImageListItemBar/imageListItemBarClasses.d.ts
packages/material-ui/src/ImageListItemBar/imageListItemBarClasses.js

This PR migrates the `ImageListItemBar` component to the new emotion format as a part of #24405.

[ImageList] Migrate ImageListItemBar to emotion

---

docs/pages/api-docs/input.json
docs/translations/api-docs/input/input.json
packages/material-ui/src/Autocomplete/Autocomplete.js
packages/material-ui/src/Input/Input.d.ts
packages/material-ui/src/Input/Input.js
packages/material-ui/src/Input/Input.test.js
packages/material-ui/src/Input/index.d.ts
packages/material-ui/src/Input/index.js
packages/material-ui/src/Input/inputClasses.d.ts
packages/material-ui/src/Input/inputClasses.js
packages/material-ui/src/NativeSelect/NativeSelect.test.js
packages/material-ui/src/TextField/TextField.test.js

This PR migrates the Input component to the new emotion format as a part of #24405.
Followed input variant pattern found here: https://github.com/mui-org/material-ui/pull/24634

[TextField] Migrate Input component to emotion

---

docs/pages/api-docs/tab.json
docs/translations/api-docs/tab/tab.json
packages/material-ui/src/Tab/Tab.d.ts
packages/material-ui/src/Tab/Tab.js
packages/material-ui/src/Tab/Tab.test.js
packages/material-ui/src/Tab/index.d.ts
packages/material-ui/src/Tab/index.js
packages/material-ui/src/Tab/tabClasses.d.ts
packages/material-ui/src/Tab/tabClasses.js

[Tabs] Migrate Tab to emotion

---

docs/translations/api-docs/chip/chip-de.json
docs/translations/api-docs/chip/chip-es.json
docs/translations/api-docs/chip/chip-fr.json
docs/translations/api-docs/chip/chip-ja.json
docs/translations/api-docs/chip/chip-pt.json
docs/translations/api-docs/chip/chip-ru.json
docs/translations/api-docs/chip/chip-zh.json
docs/translations/api-docs/chip/chip.json
packages/material-ui/src/Chip/Chip.d.ts
packages/material-ui/src/Chip/Chip.js

[docs] Clarifying the documentation about Chip behavior

---

docs/pages/api-docs/form-control.json
docs/translations/api-docs/form-control/form-control.json
packages/material-ui/src/FormControl/FormControl.d.ts
packages/material-ui/src/FormControl/FormControl.js
packages/material-ui/src/FormControl/FormControl.test.js
packages/material-ui/src/FormControl/formControlClasses.d.ts
packages/material-ui/src/FormControl/formControlClasses.js

This PR migrates the FormControl component to the new emotion format as a part of #24405.

[TextField] Migrate FormControl to emotion

---

docs/pages/api-docs/tab-scroll-button.json
docs/translations/api-docs/tab-scroll-button/tab-scroll-button.json
packages/material-ui/src/TabScrollButton/TabScrollButton.d.ts
packages/material-ui/src/TabScrollButton/TabScrollButton.js
packages/material-ui/src/TabScrollButton/TabScrollButton.test.js
packages/material-ui/src/TabScrollButton/index.d.ts
packages/material-ui/src/TabScrollButton/index.js
packages/material-ui/src/TabScrollButton/tabScrollButtonClasses.d.ts
packages/material-ui/src/TabScrollButton/tabScrollButtonClasses.js

[Tab] Migrate TabScrollButton to emotion

---

test/utils/describeConformanceV5.js

[tests] Skip JSDOM in style related conformance tests

---

packages/material-ui-styled-engine-sc/src/GlobalStyles/GlobalStyles.js
packages/material-ui-styled-engine-sc/src/GlobalStyles/GlobalStyles.test.js
packages/material-ui-styled-engine/src/GlobalStyles/GlobalStyles.js
packages/material-ui-styled-engine/src/GlobalStyles/GlobalStyles.test.js

Fixes the following issue found in https://github.com/mui-org/material-ui/pull/24489#issuecomment-769059791

[styled-engine] Fix GlobalStyles not to throw when no theme is available

---

docs/src/pages/components/date-picker/BasicDatePicker.js
docs/src/pages/components/date-picker/BasicDatePicker.tsx
docs/src/pages/components/date-picker/CustomDay.js
docs/src/pages/components/date-picker/CustomDay.tsx
docs/src/pages/components/date-picker/LocalizedDatePicker.js
docs/src/pages/components/date-picker/LocalizedDatePicker.tsx
docs/src/pages/components/date-picker/ResponsiveDatePickers.js
docs/src/pages/components/date-picker/ResponsiveDatePickers.tsx
docs/src/pages/components/date-picker/ServerRequestDatePicker.js
docs/src/pages/components/date-picker/ServerRequestDatePicker.tsx
docs/src/pages/components/date-picker/date-picker.md
packages/material-ui-lab/src/MobileDatePicker/MobileDatePicker.test.tsx
packages/material-ui-lab/src/internal/pickers/PickersModalDialog.tsx
packages/material-ui-lab/src/internal/pickers/hooks/usePickerState.ts
packages/material-ui-lab/src/internal/pickers/hooks/useUtils.ts

When clicking on the "Today" button in MobileDate[Time]Picker, the returned value is always the same => the moment at which the component was first mounted.
Example: https://codesandbox.io/s/62sdn
- Load the page
- Open the DateTimePicker
- Click on the "Now" button
- Wait for 5 sec
- Open the DateTimePicker
- Click on the "Now" button
- **The date has not changed at all, because the useNow() always return the same value**
The "Now" value should represent the current time when the user click the button, and not the time when the component was first mounted.
Somehow, removing the useReft fix the issue, i suspect some hook cache magic being used somewhere in React, but i don't know enough about the Hook implementation so...
Here is a sandbox using the fix proposed in the PR: …

[Pickers] Fix `showTodayButton` not returning the current time

---

packages/material-ui/src/Paper/Paper.js
packages/material-ui/src/Paper/Paper.test.js

- include what can be done to fix this warning
- include used `elevation` value to find the warning easier

[Paper] Improve warning on invalid combinations of variant and elevation

---

docs/pages/api-docs/toggle-button.json
docs/translations/api-docs/toggle-button/toggle-button.json
packages/material-ui/src/ToggleButton/ToggleButton.d.ts
packages/material-ui/src/ToggleButton/ToggleButton.js
packages/material-ui/src/ToggleButton/ToggleButton.test.js
packages/material-ui/src/ToggleButton/index.d.ts
packages/material-ui/src/ToggleButton/index.js
packages/material-ui/src/ToggleButton/toggleButtonClasses.d.ts
packages/material-ui/src/ToggleButton/toggleButtonClasses.js

[ToggleButton] Migrate to emotion

---

docs/pages/api-docs/step.json
docs/translations/api-docs/step/step.json
packages/material-ui/src/Step/Step.d.ts
packages/material-ui/src/Step/Step.js
packages/material-ui/src/Step/Step.test.js
packages/material-ui/src/Step/index.d.ts
packages/material-ui/src/Step/index.js
packages/material-ui/src/Step/stepClasses.d.ts
packages/material-ui/src/Step/stepClasses.js
packages/material-ui/src/Stepper/Stepper.test.js

[Step] Migrate to emotion

---

packages/material-ui-lab/src/ClockPicker/ClockPicker.tsx
packages/material-ui-lab/src/DateRangePicker/DateRangePicker.tsx
packages/material-ui-lab/src/DateRangePicker/DateRangePickerInput.tsx
packages/material-ui-lab/src/DateRangePicker/DateRangePickerToolbar.tsx
packages/material-ui-lab/src/DateRangePicker/DateRangePickerViewDesktop.tsx
packages/material-ui-lab/src/DayPicker/PickersFadeTransitionGroup.tsx
packages/material-ui-lab/src/DesktopDateRangePicker/DesktopDateRangePicker.test.tsx
packages/material-ui-lab/src/DesktopDateRangePicker/DesktopDateRangePicker.tsx
packages/material-ui-lab/src/MobileDateRangePicker/MobileDateRangePicker.tsx
packages/material-ui-lab/src/YearPicker/YearPicker.tsx

As asked by @eps1lon in #24705. I'm moving the changes into a dedicated PR. It's somewhat a breaking change.
The motivation: enforce a constraint we have defined for the components, the name of the file should match, the import, the stylesheets, the default props, etc.

[Pickers] Fix more name inconsistencies

---

packages/material-ui/src/Card/Card.js
packages/material-ui/src/Card/Card.test.js

#24667 introduces a warning when using a card outlined. I have added a test to catch the issue as well as fixed the default prop logic. Now, developers, when changing the default elevation of the Paper, don't need to customize the Card too. 
http://0.0.0.0:3000/components/cards/

[Card] Use the default elevation

---

packages/material-ui/src/Typography/Typography.js

During the migration of Typography to emotion we added a new class that I believe only has downsides: `alignInherit`. It adds noise (the important signal is MuiTypography-h1) in the DOM without helping with customizability.
I have also change the position of the `useUtilityClasses` method to match the source template.

[Typography] Remove align inherit noise

---

packages/material-ui-lab/src/DesktopDatePicker/DesktopDatePicker.test.tsx
packages/material-ui-lab/src/DesktopDateRangePicker/DesktopDateRangePicker.test.tsx
packages/material-ui-lab/src/DesktopDateTimePicker/DesktopDateTimePicker.test.tsx
packages/material-ui-lab/src/DesktopTimePicker/DesktopTimePicker.test.tsx
packages/material-ui-lab/src/internal/pickers/PickersPopper.tsx

The pickers currently rely on click-focus behavior to detect "click-away". However, this is platform dependant behavior and relies on the container being focusable which we want to avoid in the future anyway.
We're now using a stripped-down variant of ClickAwayListener. We can't use this component directly due to how we pass props via cloneElement.
A shared hook might make more sense in the long run but we can work with a much simpler variant in PickersPopper so I'm waiting a bit more. Especially considering how complicated this logic is in React right now.
The main UX difference right now compared to https://github.com/mui-org/material-ui/pull/24444 (which also fixes the missing click-away logic) is observable when clicking on the button that opens the picker. On #24444 the datepicker …

[Pickers] Dismiss on clickaway when using the desktop variant

---

docs/src/modules/components/AppContainer.js

This is a bit of an experiment how we can reconcile grids in Material design with system-adjustable font settings.
Right now we're restricting `<main>` to a pixel based max-width. This works fine with the default font settings. However, browsers can change the default font settings. Increasing the font size to "Large" in chrome (20px) leads to a cramped props tables in /api:
By making the max-width based on `ch` we give every font setting the same amount of characters per line (up until the screen is no longer big  enough).
Preview: https://deploy-preview-24531--material-ui.netlify.app/api/text-field/
In the end, it might be interesting if we could make breakpoints based on `ch` entirely. This is just an incomplete fix for our specific problem in props tables.

[docs] Make <main> responsive to font size

---

packages/material-ui/src/Dialog/Dialog.js
packages/material-ui/src/Dialog/Dialog.test.js

Role attribute does not support multiple values. The values `none` and `presentation` have the exact same meaning. `presentation` is more widely supported currently.
This was surfaces while running `jest-axe` against a private repo that is using `material-ui`. The rule that failed is
https://dequeuniversity.com/rules/axe/4.1/aria-roles?application=RuleDescription

[Dialog] Convert role `none presentation` to `presentation`

---

docs/src/pages/components/time-picker/BasicTimePicker.js
docs/src/pages/components/time-picker/BasicTimePicker.tsx
docs/src/pages/components/time-picker/LocalizedTimePicker.js
docs/src/pages/components/time-picker/LocalizedTimePicker.tsx
docs/src/pages/components/time-picker/ResponsiveTimePickers.js
docs/src/pages/components/time-picker/ResponsiveTimePickers.tsx
docs/src/pages/components/time-picker/SecondsTimePicker.js
docs/src/pages/components/time-picker/SecondsTimePicker.tsx
docs/src/pages/components/time-picker/TimeValidationTimePicker.js
docs/src/pages/components/time-picker/TimeValidationTimePicker.tsx
docs/src/pages/components/time-picker/time-picker.md

Preview: http://deploy-preview-24739--material-ui.netlify.app/components/time-picker/ (modelled after [/components/date-picker](https://next--material-ui.netlify.app/components/date-picker/)
- basic example for TimePicker no longer includes `ampm` usage
I guess in general we want to ensure that the very first/"basic" demo displays the JSX inline.
Though I would not enforce this explicitly but implicitly by keeping the demo small (as few chars as possible).
- basic example for TimePicker uses no value as a default (following the other 3 picker basic demos)
- use default TextField variant (`outlined`) (was `standard`)

[docs] Follow similar demo pattern for date and time pickers

---

docs/src/pages/components/tabs/CustomizedTabs.tsx
packages/material-ui-types/index.d.ts

Will affect all higher-order components. `withStyles` and `styled` will likely cause breakage.
Change is necessary to be forwards compatible with the removal of implicit children and it avoids overly strict type-checking when using `typeof ComponentDecoratedWithWithStyles`. This would previously require `.propTypes` to match as well.

[types] Remove implicit children from PropInjector

---

packages/material-ui-lab/src/ClockPicker/ClockPicker.tsx
packages/material-ui-lab/src/DatePicker/DatePicker.tsx
packages/material-ui-lab/src/DateRangePicker/DateRangePicker.tsx
packages/material-ui-lab/src/DateRangePicker/makeDateRangePicker.tsx
packages/material-ui-lab/src/DateRangePickerDay/DateRangePickerDay.tsx
packages/material-ui-lab/src/DateTimePicker/DateTimePicker.tsx
packages/material-ui-lab/src/DayPicker/DayPicker.tsx
packages/material-ui-lab/src/DesktopDatePicker/DesktopDatePicker.tsx
packages/material-ui-lab/src/DesktopDateRangePicker/DesktopDateRangePicker.tsx
packages/material-ui-lab/src/DesktopDateTimePicker/DesktopDateTimePicker.tsx
packages/material-ui-lab/src/DesktopTimePicker/DesktopTimePicker.tsx
packages/material-ui-lab/src/LocalizationProvider/LocalizationProvider.tsx
packages/material-ui-lab/src/MobileDatePicker/MobileDatePicker.tsx
packages/material-ui-lab/src/MobileDateRangePicker/MobileDateRangePicker.tsx
packages/material-ui-lab/src/MobileDateTimePicker/MobileDateTimePicker.tsx
packages/material-ui-lab/src/MobileTimePicker/MobileTimePicker.tsx
packages/material-ui-lab/src/MonthPicker/MonthPicker.tsx
packages/material-ui-lab/src/PickersCalendarSkeleton/PickersCalendarSkeleton.tsx
packages/material-ui-lab/src/PickersDay/PickersDay.tsx
packages/material-ui-lab/src/StaticDatePicker/StaticDatePicker.tsx
packages/material-ui-lab/src/StaticDateRangePicker/StaticDateRangePicker.tsx
packages/material-ui-lab/src/StaticDateTimePicker/StaticDateTimePicker.tsx
packages/material-ui-lab/src/StaticTimePicker/StaticTimePicker.tsx
packages/material-ui-lab/src/TimePicker/TimePicker.tsx
packages/material-ui-lab/src/Timeline/Timeline.tsx
packages/material-ui-lab/src/YearPicker/YearPicker.tsx
packages/material-ui/src/ClickAwayListener/ClickAwayListener.tsx
packages/typescript-to-proptypes/src/generator.ts
packages/typescript-to-proptypes/src/injector.ts
scripts/generateProptypes.ts

`(Component as any).propTypes` is not recognized by `react-docgen`. 
Update: Considering the bundle size reduction it's probably also not recognized by `babel-plugin-transform-react-remove-prop-types`
Update: .propTypes were not removed before: https://unpkg.com/browse/@material-ui/lab@5.0.0-alpha.24/ClockPicker/ClockPicker
We can achieve sounder types with `Component.propTypes = {} as any` by adjusting the type of `Component`. .propTypes and Props types need to match exactly which breaks down when .propTypes need the actual runtime or we didn't resolve a big object (e.g. `classes`).

[core] Disable type-checking of .propTypes

---

.circleci/config.yml

Allows triggering a pipeline (e.g. via CircleCI API) with a specific `react-dist-tag` e.g.
```json
{
"branch": "next",
"parameters": {
"react-dist-tag": "next",
"workflow": "profile"
}
}
```
Previously the above API payload would result in https://app.circleci.com/pipelines/github/mui-org/material-ui/37601/workflows/046681f0-3760-45a3-a4b0-f719c8a6c327/jobs/222354

[test] Allow setting react-dist-tag via pipeline parameter

---

packages/material-ui/src/InputAdornment/InputAdornment.js
packages/material-ui/src/InputAdornment/InputAdornment.test.js
test/regressions/tests/TextField/BaselineAlignTextField.js

Adds a span html element as child node inside input adornment.
Fixes to have the correct vertical alignment baseline for input adornment.
Closes #24706

[TextField] Improve baseline alignment with start adornment

---

packages/material-ui/src/Popper/Popper.js

[Popper] Use ownerDocument of anchorEl

---

CONTRIBUTING.md

The heading and contents do not currently rightly reflect docs site to be the playground for making changes in core components apart from docs. This should hopefully be more clearer.

[docs] Add information about local dev environment

---

packages/material-ui/src/styles/createPalette.js

[docs] Fix typo in the error message generated by createMuiTheme

---

docs/src/pages/getting-started/templates/album/Album.js
docs/src/pages/getting-started/templates/album/Album.tsx
docs/src/pages/getting-started/templates/blog/Footer.js
docs/src/pages/getting-started/templates/blog/Footer.tsx
docs/src/pages/getting-started/templates/checkout/Checkout.js
docs/src/pages/getting-started/templates/checkout/Checkout.tsx
docs/src/pages/premium-themes/paperbase/Paperbase.js
docs/src/pages/premium-themes/paperbase/Paperbase.tsx
examples/cdn/index.html
examples/create-react-app-with-styled-components/src/App.js
examples/create-react-app-with-styled-components/src/ProTip.js
examples/create-react-app-with-typescript/src/App.tsx
examples/create-react-app-with-typescript/src/ProTip.tsx
examples/create-react-app/src/App.js
examples/create-react-app/src/ProTip.js
examples/gatsby-theme/src/components/Copyright.js
examples/gatsby-theme/src/components/ProTip.js
examples/gatsby/src/components/Copyright.js
examples/gatsby/src/components/ProTip.js
examples/nextjs-with-typescript/src/Copyright.tsx
examples/nextjs-with-typescript/src/ProTip.tsx
examples/nextjs/src/Copyright.js
examples/nextjs/src/ProTip.js
examples/preact/src/Copyright.js
examples/preact/src/ProTip.js
examples/ssr/App.js
examples/ssr/ProTip.js

Edit by @oliviertassinari
#24496 removes the inconsistency of the value accepted by the Typography `color` prop. The changes update the examples. These examples are important as they serve as a baseline for developers learning the library.
In the future, we will need to:
- Migrate all the codebase from `color="textSecondary"` to `color="text.secondary"`
- Add a depreciation for the older API along the lifecycle of v5 stable
- Consider providing a codemod for making the migration
- Agree on when to use the flat props over the `sx`. So far, we have added the flat props because of the strong demand from developers. However, we haven't yet agreed on a standard.

[examples] Align more with the v5 recommended approach

---

docs/pages/api-docs/table-body.json
docs/translations/api-docs/table-body/table-body.json
packages/material-ui/src/TableBody/TableBody.d.ts
packages/material-ui/src/TableBody/TableBody.js
packages/material-ui/src/TableBody/TableBody.test.js
packages/material-ui/src/TableBody/index.d.ts
packages/material-ui/src/TableBody/index.js
packages/material-ui/src/TableBody/tableBodyClasses.d.ts
packages/material-ui/src/TableBody/tableBodyClasses.js

[Table] Migrate TableBody to emotion

---

docs/src/pages/guides/migration-v4/migration-v4.md
docs/src/pages/system/grid/Gap.js
docs/src/pages/system/grid/Gap.tsx
docs/src/pages/system/grid/GridAutoColumns.js
docs/src/pages/system/grid/GridAutoColumns.tsx
docs/src/pages/system/grid/GridAutoFlow.js
docs/src/pages/system/grid/GridAutoFlow.tsx
docs/src/pages/system/grid/GridAutoRows.js
docs/src/pages/system/grid/GridAutoRows.tsx
docs/src/pages/system/grid/GridTemplateAreas.js
docs/src/pages/system/grid/GridTemplateAreas.tsx
docs/src/pages/system/grid/RowAndColumnGap.js
docs/src/pages/system/grid/RowAndColumnGap.tsx
docs/src/pages/system/grid/grid.md
packages/material-ui-system/src/borders.js
packages/material-ui-system/src/borders.test.js
packages/material-ui-system/src/grid.js
packages/material-ui-system/src/grid.test.js

- [system] Use spacing unit in `gap`, `rowGap`, and `columnGap`. If you were using a number previously, you need to mention the px to bypass the new transformation with `theme.spacing`. 
```diff
<Box
- gap={2}
+ gap="2px"
>
```
---
After the change, `<Box gap={1}>` behaves like `<Grid spacing={1}>`.
Fix #24773

[system] Use spacing unit in gap, row-gap, and column-gap

---

.github/workflows/ci.yml

We're already running it for `pull_request` events.
- dev CI is run for `push` + `pull_request` of this branch since I deliberately pushed it to `upstream` instead of my own fork

[test] Don't run dev CI for dependabot pushes

---

packages/material-ui/src/Tooltip/Tooltip.test.js

No need to test it with `<Input />`. If it would be important it should be part of the integration test suite.
The goal is to reduce the number of style tags in the DOM which speeds up style computation in JSDOM.

[test] Isolate Tooltip tests more

---

docs/translations/api-docs/date-picker/date-picker.json
docs/translations/api-docs/desktop-date-picker/desktop-date-picker.json
docs/translations/api-docs/desktop-time-picker/desktop-time-picker.json
docs/translations/api-docs/mobile-date-picker/mobile-date-picker.json
docs/translations/api-docs/mobile-time-picker/mobile-time-picker.json
docs/translations/api-docs/static-date-picker/static-date-picker.json
docs/translations/api-docs/static-time-picker/static-time-picker.json
docs/translations/api-docs/time-picker/time-picker.json
packages/material-ui-lab/src/DatePicker/DatePicker.tsx
packages/material-ui-lab/src/DateRangePicker/DateRangePicker.tsx
packages/material-ui-lab/src/DateTimePicker/DateTimePicker.tsx
packages/material-ui-lab/src/DesktopDatePicker/DesktopDatePicker.tsx
packages/material-ui-lab/src/DesktopDateRangePicker/DesktopDateRangePicker.tsx
packages/material-ui-lab/src/DesktopDateTimePicker/DesktopDateTimePicker.tsx
packages/material-ui-lab/src/DesktopTimePicker/DesktopTimePicker.tsx
packages/material-ui-lab/src/MobileDatePicker/MobileDatePicker.tsx
packages/material-ui-lab/src/MobileDateRangePicker/MobileDateRangePicker.tsx
packages/material-ui-lab/src/MobileDateTimePicker/MobileDateTimePicker.tsx
packages/material-ui-lab/src/MobileTimePicker/MobileTimePicker.tsx
packages/material-ui-lab/src/StaticDatePicker/StaticDatePicker.tsx
packages/material-ui-lab/src/StaticDateRangePicker/StaticDateRangePicker.tsx
packages/material-ui-lab/src/StaticDateTimePicker/StaticDateTimePicker.tsx
packages/material-ui-lab/src/StaticTimePicker/StaticTimePicker.tsx
packages/material-ui-lab/src/TimePicker/TimePicker.tsx
packages/material-ui-lab/src/internal/pickers/PureDateInput.tsx

The wording seems non-sensical to me at the moment. But I'm not bothering with it for now until we have an actual demo.
Revealed in https://github.com/mui-org/material-ui/pull/24835
[current `next`](https://6021ded8b2baf900070b63de--material-ui.netlify.app/api/desktop-date-picker/#:~:text=Can%20be%20used%20to%20override%20generate%20from%20format.%20(e.g.%20//__%20__:%20or%20//__%20__:%20_M).) vs [this PR](http://deploy-preview-24842--material-ui.netlify.app/api/desktop-date-picker)

[docs] Fix formatting of `mask` prop description

---

packages/material-ui/src/Avatar/Avatar.test.js
packages/material-ui/src/ButtonBase/Ripple.test.js
test/utils/createClientRender.js

WARNING: We no longer allow `render` in `before` or `beforeEach` hooks. It was always problematic since it lead to bloated tests or tests that could not be run in isolation.
Emotion caches the created rules i.e. retains `<style>` elements after unmounting. While I would generally consider this leaky behavior, they haven't seen any reports that this affects performance so it seems ok to do in a browser: https://github.com/emotion-js/emotion/issues/488.
However, in a test we generally want each test to be as isolated as possible and specifically for JSDOM we want to keep the number of CSS rules in the DOM as low as possible since `getComputedStyles` iterates over each rule.
Did two runs of `CI=true yarn test:unit` in `next` and this PR. `next` clocked in at **125s and 131s** while this PR …

[test] Clear emotion cache between tests

---

.circleci/config.yml

Started inspecting `yarn cache dir` in https://github.com/mui-org/material-ui/pull/24843 and it [turns out it's `~/.yarn/cache/v6`](https://app.circleci.com/pipelines/github/mui-org/material-ui/37807/workflows/a4d5e213-08d2-4459-834b-1e57a19a6789/jobs/223338/parallel-runs/0/steps/0-111) while we're saving and restoring `~/.yarn/cache/v4`.
We're now explicitly restoring and saving the same folder we pass to `yarn install --cache-folder` following the [documented example for "Caching dependencies" in CircleCI](https://circleci.com/docs/2.0/caching/#yarn-node).
Cleared the existing cache explicitly to have a clean slate.
install with the old workflow: https://circleci.com/api/v1.1/project/github/mui-org/material-ui/223338/output/107/0?file=true&allocation-id=6022615d6e280926e352902f-0-build%2 …

[core] save/restore actual  yarn cache folder

---

docs/src/pages/components/date-picker/CustomDay.js
docs/src/pages/components/date-picker/CustomDay.tsx
docs/src/pages/components/date-time-picker/BasicDateTimePicker.js
docs/src/pages/components/date-time-picker/BasicDateTimePicker.tsx

Fixed onChange handlers for DatePiker examples mentioned in #24169
Closes #24169

[Pickers] Fix useState related console warnings in examples

---

test/regressions/.mocharc.js

Take into account flaky cases like https://app.circleci.com/pipelines/github/mui-org/material-ui/37825/workflows/31dd01a6-6f4f-4c73-86ce-f28e6292730f/jobs/223444. 
I have seen this one a couple of times. I think that we can assume that the main value of the timeout here is to 1. help debug when we forget the done() call 2. avoid making ridiculously slow async tasks.

[test] Increase timeout to 4000ms for screenshots

---

docs/src/pages/components/material-icons/synonyms.js

When you search "unread" in icons you find a closed envelope (Markunread), but when you search "read" you don't find its opposite e.g. an open envelope.
This additional synonym will fix this behaviour by adding the read synonym to its counterpart, the open envelope.

[docs] Add read synonym to drafts

---

test/karma.conf.js

A follow-up on #24801, add 60s to the current timeout value (5min). I hope it's just enough to avoid the timeout to trigger in most of the cases:
An example of a build failing: https://app.circleci.com/jobs/github/mui-org/material-ui/223286?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
It could be interesting to look at why Firefox is a lot slower.

[test] Increase BrowserStack timeout to 6min

---

packages/material-ui/test/integration/PopperChildrenLayout.test.js

Tests for https://github.com/mui-org/material-ui/pull/24760.
"<Popper /> children layout integration in TransitionComponent ${name} focus during passive effects do not scroll" is a minimal repro for https://github.com/mui-org/material-ui/issues/23899
Opening as a separate PR to get full CI run (especially interested in cross-browser behavior). In the end I want to be able to easily revert a fix. The problem is quite complicated so I want to enforce the separation of behavior and implementation.

[test] Add current behavior of focus during mount in Popper

---

package.json
test/package.json
test/tsconfig.json
test/utils/mochaHooks.js

First version only has a dedicated task for type-checking utils. Over time we'll consolidate dependencies to make it clearer what utils you should import from where (e.g. `fireEvent` from `@testing-library/react` or `test/utils`?).

[test] Initial workspace definition

---

docs/public/_redirects

The URL was changed to support v4 and v5 at the same time, this a requirement for mui-org/material-ui-x. It's not something we need to worry about much in this repository.
In https://github.com/mui-org/material-ui/issues/21801#issuecomment-778042700, I have noticed that some of our templates/habits haven't been updated. I have personally been sharing a number of 404 links too in the past. Now, considering that we will also need to change the templates and habits once we move to v5 stable, I propose that we aim to use the HEAD version */r/issue-template* as much as possible. I will update my saved replies if approved.

[core] Support /r/issue-template back

---

.eslintrc.js
docs/src/pages/premium-themes/onepirate/modules/components/Paper.js
docs/src/pages/premium-themes/onepirate/modules/components/Paper.tsx
docs/src/pages/premium-themes/onepirate/modules/components/TextField.js
docs/src/pages/premium-themes/onepirate/modules/components/TextField.tsx
docs/src/pages/premium-themes/onepirate/modules/components/Typography.js
docs/src/pages/premium-themes/onepirate/modules/components/Typography.tsx
packages/material-ui-unstyled/src/SliderUnstyled/SliderUnstyled.js
packages/material-ui/src/Tooltip/Tooltip.js
packages/material-ui/src/internal/SwitchBase.test.js

Re-enable the following lint rules:
- `dot-notation`
- `no-implied-eval`
- `no-throw-literal`
Noticed during https://github.com/mui-org/material-ui/pull/24810 that we have disabled some type-aware lint rules for "performance considerations". I suspect this actually refers to the required type checking not because the rules themselves are slow.
If they were in fact only disabled to avoid type-ware linting, we should enable their type-unaware counterparts. The typescript-eslint repo says these versions "don't work with typescript" but it's unclear what they mean: do these versions have false-negatives or false-positives<sup>1</sup>? False positives would be fine since we don't expect linting to catch every error anyway. false-negatives would be more problematic but I haven't seen …

[test] Enable type-unaware versions of disabled typed-aware lint rules

---

test/utils/mochaHooks.js
test/utils/mochaHooks.test.js

Adds an experimental poylfill for https://github.com/facebook/react/issues/19416. Experimental in the sense of "let's see if deduping this hides important information".
TL;DR; of https://github.com/facebook/react/issues/19416: We get closer to "one warning per action required".
Summary of  https://github.com/facebook/react/issues/19416:
When we get the warning for "missing act" we usually just want to find out which expression we have to wrap in act(). In that case we only need the stack once. Right now we get a warning per effect which is redundant.
Ideally we would dedupe them by update but I suspect this will get a lot harder with timers. Deduping consecutive of a single component name is a good enough heuristic for now. It would produce a single warning if we get two unrelated but …

[test] Dedupe missing act warnings by component name

---

package.json
packages/material-ui/src/ButtonBase/TouchRipple.js
packages/material-ui/src/CircularProgress/CircularProgress.js

I didn't enable `stylelint` in the CI for the source folder yet. We don't have a lot of CSS, mostly JavaScript templates. I'm not sure we want to pay the runtime cost in the CI 😬. I mean, we could wait for the pain to grow. At least, we have IDE warnings assuming the stylelint extension plugin was installed.

[core] Fix a few stylelint error

---

docs/package.json

This line was meant to workaround https://github.com/kentcdodds/babel-plugin-preval/issues/19, a problem we do no longer have since the dependency was removed.

[core] Remove dead code in docs:dev

---

scripts/listChangedFiles.js
scripts/listChangedFiles.test.js

Motivated by improving the test I discovered that the logic is not desireable one of the git commands returned no files. It would return `['']` instead of `[]` due to `''.split('\n')` returning `['']`.
The test isn't linear but faster since we no longer calculate the difference but derive it from 3 assertions.

[core] listChangedFiles returns an empty list with no changed files

---

docs/pages/api-docs/table-cell.json
docs/pages/performance/table-emotion.js
docs/translations/api-docs/table-cell/table-cell.json
packages/material-ui/src/CardMedia/CardMedia.d.ts
packages/material-ui/src/Checkbox/Checkbox.d.ts
packages/material-ui/src/CircularProgress/CircularProgress.d.ts
packages/material-ui/src/ImageListItem/ImageListItem.d.ts
packages/material-ui/src/ImageListItemBar/ImageListItemBar.d.ts
packages/material-ui/src/ListItemText/ListItemText.d.ts
packages/material-ui/src/Step/Step.d.ts
packages/material-ui/src/Tab/Tab.d.ts
packages/material-ui/src/TabScrollButton/TabScrollButton.d.ts
packages/material-ui/src/Table/Table.d.ts
packages/material-ui/src/TableBody/TableBody.d.ts
packages/material-ui/src/TableCell/TableCell.d.ts
packages/material-ui/src/TableCell/TableCell.js
packages/material-ui/src/TableCell/TableCell.test.js
packages/material-ui/src/TableCell/index.d.ts
packages/material-ui/src/TableCell/index.js
packages/material-ui/src/TableCell/tableCellClasses.d.ts
packages/material-ui/src/TableCell/tableCellClasses.js
packages/material-ui/src/TableContainer/TableContainer.d.ts
packages/material-ui/src/TableFooter/TableFooter.d.ts
packages/material-ui/src/TableHead/TableHead.d.ts
packages/material-ui/src/TableRow/TableRow.d.ts
packages/material-ui/test/integration/TableCell.test.js

[Table] Migrate TableCell to emotion

---

benchmark/browser/scenarios/table-cell/index.js
benchmark/browser/scripts/benchmark.js
docs/pages/performance/table-component.js
docs/pages/performance/table-emotion.js
docs/pages/performance/table-hook.js
docs/pages/performance/table-mui.js
docs/pages/performance/table-raw.js
docs/pages/performance/table-styled-components.js
packages/material-ui-styles/src/getThemeProps/getThemeProps.js
packages/material-ui/src/Modal/Modal.js
packages/material-ui/src/SwipeableDrawer/SwipeableDrawer.js
packages/material-ui/src/styles/useThemeProps.js
packages/material-ui/src/withWidth/withWidth.js
packages/typescript-to-proptypes/test/getThemeProps/input.js
packages/typescript-to-proptypes/test/getThemeProps/output.js

Instead of blindly cloning the incoming props, we now only do it if there is a matching item in the theme. I have added a benchmark too. It doesn't seem to make a huge difference. But at least it's sound.
- v4 - Table: 81.40 ±00.54ms
- HEAD - Table: 99.50 ±00.72ms
- PR - Table: 99.80 ±01.47ms

[core] Only clone props if needed

---

docs/src/modules/components/AppSettingsDrawer.js

To reproduce the issue:
1. Open https://next.material-ui.com/getting-started/installation/
2. Open the "Settings" panel, set the *dark* mode
3. Reload
4. Open the "Settings" panel, set the *system* mode
5. Reload 💥 (it's still in dark mode)
This bug has been bugging me for some time, finally dedicate time to fix it.

[docs] Fix prefers-color-scheme switch

---

.circleci/config.yml

With more concurrency we can use more jobs for longer running tasks. Lintint is on a similar level as JSDOM testing and browser testing so a separate job makes sense.

[core] Extract linting into separate CI job

---

azure-pipelines.yml
scripts/sizeSnapshot/create.js

I feel like we rarely ever use this unless we specifically look into reducing size. In these cases we can now compare the logs of netlify deploys since next started logging the size of each individual page. And we could always look at the size in browser devtools anyway.
Seeing differences down to a single byte is not that useful to begin with for whole pages (while it's definitely interesting for a package). Considering this tracking costs us ~10minutes of pipeline time and `sizeSnapshot` is now our bottleneck I think we should drop it.

[core] Disable page size tracking

---

.circleci/config.yml
package.json

Fixes https://app.circleci.com/pipelines/github/mui-org/material-ui/37989/workflows/a381c496-224f-42ef-ad3e-6a13dde8db6a/jobs/224216/parallel-runs/0/steps/0-110
Exit code 137 usually means the process ran out of memory. [Node has a default memory limit of 512 MB](https://medium.com/@vuongtran/how-to-solve-process-out-of-memory-in-node-js-5f0de8f8464c) while the [default docker containers has 4 GB of RAM](https://circleci.com/docs/2.0/configuration-reference/#docker-executor). This means that we're testing these limits when running >= 8 node processes. `yarn lerna run --parallel typescript` currently runs 12 parallel tasks so it's likely that `yarn lerna` runs out of memory.
We're now limiting type-checking to 7 concurrent tasks which should give us ample room. Locally I didn't notice much …

[core] Prevent out-of-memory when type-checking in CI

---

.circleci/config.yml

So far, `test_regressions` has been a dependency of the 4 other steps to
1. stay in the 4 runs free concurrency limit of Circle CI 
2. to not put too much pressure on Argos CI
None of these two concerns seem relevant anymore.
We have upgraded to performant build with CircleCI (x4 -> x80).
A new Argos-CI worker **cost nothing**: $7/month, we could have x10 more workers. One worker can handle more than 1 image/s, easily 2m screenshots/month (60 * 60 * 24 * 30). More workers are mostly to absorb more parallelism, to have faster builds.
The CircleCI build now runs in ~8min instead of ~11min. The slowest tasks seem to be Netlify or Azure now.

[test] Run more tests at the same time

---

test/karma.conf.js

Help debug runs in BrowserStack
- top is the proposal
- bottom is current
It seems that we have an issue with BrowserStack. It looks like it's not able to handle the pressure CircleCI puts on him. I couldn't find any option to set a max concurrence on a CircleCI workflow. This change should help debug the issue we currently have. It seems that after 3-4 concurrent builds trying to access BrowserStack, things go sideways: never-ending builds, timeout, etc.

[test] Link CircleCI URL in BS

---

packages/material-ui/src/SwipeableDrawer/SwipeableDrawer.js

Apply the same fix as in https://github.com/oliviertassinari/react-swipeable-views/pull/614.
`scrollTop`, `scrollLeft` might not be an integer https://github.com/oliviertassinari/react-swipeable-views/pull/614#discussion_r463814843, when it's not, it can make the `areNotAtEnd` to fail, not handling the swipe events correctly.

[SwipeableDrawer] Fix detection of native scroll container

---

docs/pages/api-docs/autocomplete.json
docs/src/pages/components/autocomplete/GitHubLabel.js
docs/src/pages/components/autocomplete/GitHubLabel.tsx
docs/translations/api-docs/autocomplete/autocomplete.json
packages/material-ui/src/Autocomplete/Autocomplete.d.ts
packages/material-ui/src/Autocomplete/Autocomplete.js
packages/material-ui/src/Autocomplete/Autocomplete.test.js
packages/material-ui/src/Autocomplete/autocompleteClasses.d.ts
packages/material-ui/src/Autocomplete/autocompleteClasses.js
packages/material-ui/src/Autocomplete/index.d.ts
packages/material-ui/src/Autocomplete/index.js

#24405
Have some failing tests due to:
Using `first-child` instead of `first-of-type`. Says first-child not save in SSR. Just not sure how you would like this handled. 
~~The other is to do with the icon classes test. `hasPopupIcon` and `hasClearIcon`~~

[Autocomplete] Migrate to emotion

---

docs/src/pages/components/modal/BasicModal.js
docs/src/pages/components/modal/BasicModal.tsx
docs/src/pages/components/modal/NestedModal.js
docs/src/pages/components/modal/NestedModal.tsx
docs/src/pages/components/modal/SimpleModal.js
docs/src/pages/components/modal/SimpleModal.tsx
docs/src/pages/components/modal/modal.md

Separated out nested modal demo from the simple modal demo.
Fixes #23903 
Please verify text, because english is not my primary lang.

[docs] Separate simple and nested modal demos

---

test/utils/mochaHooks.js
test/utils/mochaHooks.test.js

Higher-order components don't match `\w+` e.g. `WithStyles(ForwardRef(Foo))`. For example, in https://app.circleci.com/pipelines/github/mui-org/material-ui/38098/workflows/515c0f2f-1cd9-4760-ae83-474fa95b51b9/jobs/224949/parallel-runs/0/steps/0-108 not all act warnings where as deduped as the could be using the "dedupe by component name" heuristic.

[test] Dedupe missing act warnings for HoC

---

.circleci/config.yml
test/regressions/index.test.js

First follow-up to from https://github.com/mui-org/material-ui/pull/24844
1. Fix playwright cache miss when we actually used it
1. Skip browser download when we don't need it
1. use playwright version in cache hash instead of lockfile
This is actually how it's recommended. It should reduce the overall number of cache misses.
> [...] cache this location in your CI configuration, against a hash of the Playwright version.
-- https://playwright.dev/docs/ci#directories-to-cache
1. Name save/restore cache tasks (we have two caches and identifying the relevant steps became confusing)
Due to https://github.com/microsoft/playwright/issues/5372 we can't save the cache once in `checkout` since restore and save will mismatch. We have to store the cache in the same container as we populate it. I think …

[core] Fix cache miss when using playwright docker images

---

test/karma.conf.js

When running `yarn test:karma` locally compilation on rebuild should now be dramatically faster in the best case scenario (minimal number of files changed).
The initial build is still "slow". Though I did some quick testing locally and re-building went from 20s to <1s when changing a test file.
Following the recommendation in https://webpack.js.org/configuration/devtool/#devtool for `eval-source-map`:
> Recommended choice for development builds with high quality SourceMaps.

[test] Reduce compile time of test:karma in watchmode drastically

---

test/karma.conf.js

- The problem I'm trying to fix: https://app.circleci.com/pipelines/github/mui-org/material-ui/37981/workflows/933e76b5-fa9c-4b6d-a5d6-3b2d9ef1d2f7/jobs/224165
- Leads on the solution I could find:
- https://github.com/karma-runner/karma-browserstack-launcher/issues/30 "Use higher default pollingTimeout"
- https://www.browserstack.com/docs/automate/api-reference/selenium/introduction#rest-api-projects "You can make up to 1600 API requests per 5 minutes per user"
- the config https://github.com/karma-runner/karma-browserstack-launcher/blob/4547fd7660fa47721f8ec43808b369c7aa077c0b/index.js#L83

[test] Avoid Rate Limit Exceeded

---

packages/material-ui-lab/src/DayPicker/DayPicker.tsx
packages/material-ui-lab/src/StaticDatePicker/StaticDatePickerKeyboard.test.tsx
packages/material-ui-lab/src/internal/pickers/PickersArrowSwitcher.tsx
packages/material-ui/src/ClickAwayListener/ClickAwayListener.test.js
packages/material-ui/src/SpeedDial/SpeedDial.test.js
packages/material-ui/src/Tooltip/Tooltip.test.js
scripts/listChangedFiles.test.js

1. increase timeout for listChangedFiles
Timed out fairly often but it's unclear why this is slow in tests. Added monitoring for future investigation
1. Fix https://app.circleci.com/pipelines/github/mui-org/material-ui/38098/workflows/515c0f2f-1cd9-4760-ae83-474fa95b51b9/jobs/224949/parallel-runs/0/steps/0-108
`StaticDatePicker` uses `Fade` in its tree so if the test was slow those scheduled updates got executed resulting in unwrapped act. 
We're now just not advancing the timers relevant for these updates since we don't care about the updates in those tests.
1. speed up a Tooltip test which had redundant assertions
We already have tests for checking role+a11y tree inclusion. `onClose` is an equivalent assertion if the role+a11y tests pass.
1. Fix …

[test] Improve various timer related issues

---

packages/material-ui/src/FormControl/FormControl.js
packages/material-ui/src/FormControl/FormControl.test.js

Fix the pain point raised by @ameem91 in #24777. The TextField focused state is about DOM focus, the TextField focused prop is about the active view, the notions are different, the branch is not correct.
If we feel a test case is needed, happy to provide one.

[TextField] Fix focused={true} disabled={true} infinite render

---

docs/pages/versions.js

**Before**
> TypeError: branches.map is not a function
https://app.netlify.com/teams/mui-org/builds/602cf181598034000877dc3b
**After**

[docs] Improve error message when GitHub API fail

---

packages/material-ui/src/Skeleton/Skeleton.js
packages/material-ui/src/Skeleton/Skeleton.test.js
packages/material-ui/src/styles/components.d.ts

Fixes #24959.
The Skeleton component doesn't pick up global theme `styleOverrides`; this PR fixes the issue.

[Skeleton] Fix global theme customization 

---

docs/pages/api-docs/outlined-input.json
docs/translations/api-docs/outlined-input/outlined-input.json
packages/material-ui/src/Autocomplete/Autocomplete.js
packages/material-ui/src/Breadcrumbs/BreadcrumbCollapsed.js
packages/material-ui/src/Checkbox/Checkbox.js
packages/material-ui/src/Input/Input.js
packages/material-ui/src/InputLabel/InputLabel.js
packages/material-ui/src/OutlinedInput/NotchedOutline.js
packages/material-ui/src/OutlinedInput/NotchedOutline.test.js
packages/material-ui/src/OutlinedInput/OutlinedInput.d.ts
packages/material-ui/src/OutlinedInput/OutlinedInput.js
packages/material-ui/src/OutlinedInput/OutlinedInput.test.js
packages/material-ui/src/OutlinedInput/index.d.ts
packages/material-ui/src/OutlinedInput/index.js
packages/material-ui/src/OutlinedInput/outlinedInputClasses.d.ts
packages/material-ui/src/OutlinedInput/outlinedInputClasses.js
packages/material-ui/src/TextField/TextField.test.js
packages/material-ui/src/internal/SwitchBase.js

This PR migrates the OutlinedInput component to the new emotion format as a part of #24405.

[TextField] Migrate OutlinedInput to emotion

---

docs/pages/api-docs/list-item.json
docs/pages/api-docs/menu-item.json
docs/src/pages/components/menus/MenuListComposition.js
docs/src/pages/components/menus/MenuListComposition.tsx
docs/translations/api-docs/list-item/list-item.json
docs/translations/api-docs/menu-item/menu-item.json
framer/scripts/framerConfig.js
packages/material-ui/src/ListItem/ListItem.d.ts
packages/material-ui/src/ListItem/ListItem.js
packages/material-ui/src/MenuItem/MenuItem.d.ts
packages/material-ui/src/MenuItem/MenuItem.js
packages/material-ui/src/MenuItem/MenuItem.test.js
packages/material-ui/src/MenuItem/index.d.ts
packages/material-ui/src/MenuItem/index.js
packages/material-ui/src/MenuItem/menuItemClasses.d.ts
packages/material-ui/src/MenuItem/menuItemClasses.js

This PR migrates the `MenuItem` component  to the new emotion format as a part of #24405.

[Menu] Migrate MenuItem to emotion

---

docs/pages/api-docs/toggle-button-group.json
docs/src/pages/components/toggle-button/CustomizedDividers.js
docs/src/pages/components/toggle-button/CustomizedDividers.tsx
docs/translations/api-docs/toggle-button-group/toggle-button-group.json
packages/material-ui/src/ToggleButtonGroup/ToggleButtonGroup.d.ts
packages/material-ui/src/ToggleButtonGroup/ToggleButtonGroup.js
packages/material-ui/src/ToggleButtonGroup/ToggleButtonGroup.test.js
packages/material-ui/src/ToggleButtonGroup/index.d.ts
packages/material-ui/src/ToggleButtonGroup/index.js
packages/material-ui/src/ToggleButtonGroup/toggleButtonGroupClasses.d.ts
packages/material-ui/src/ToggleButtonGroup/toggleButtonGroupClasses.js

[ToggleButton] Migrate ToggleButtonGroup to emotion

---

docs/pages/api-docs/switch.json
docs/translations/api-docs/switch/switch.json
framer/scripts/framerConfig.js
packages/material-ui/src/Switch/Switch.d.ts
packages/material-ui/src/Switch/Switch.js
packages/material-ui/src/Switch/Switch.test.js
packages/material-ui/src/Switch/index.d.ts
packages/material-ui/src/Switch/index.js
packages/material-ui/src/Switch/switchClasses.d.ts
packages/material-ui/src/Switch/switchClasses.js

[Switch] Migrate to emotion

---

.circleci/config.yml

codecov status checks have been missing on our commits and it's unclear why. Opened https://community.codecov.io/t/github-checks-missing/2579. 
Meanwhile I'm trying to be as default as possible assuming that the more options we use, the more likely it is we trigger bugs. We were also told that we no longer need the option anyway so this is a good opportunity to verify that claim (https://github.com/codecov/codecov-bash/issues/134).

[core] Fix missing codecov report

---

packages/material-ui/src/ClickAwayListener/ClickAwayListener.test.js
scripts/react-next.diff
test/utils/fireDiscreteEvent.js
test/utils/index.js

1. cherry-pick discrete event helper from https://github.com/mui-org/material-ui/pull/24981
2. add a test motivated by a different approach for "arming" the clickawaylistener
The approach is used in https://github.com/mui-org/material-ui/pull/24981 but might not work if earlier events for mounting are chosen. 
This is especially interesting if one decides to mount the ClickAwayListener on mousedown (e.g. for `<select />` implementations) where the timer approach will break down as well.

[test] Test with ClickAwayListener mount on onClickCapture

---

CONTRIBUTING.md
test/README.md

a11y tree exclusion is part of tests. I think we just forgot it when updating the testing docs.
Also added a note why test:unit might pass locally but fail in CI.
Hopefully resolves some confusion in https://github.com/mui-org/material-ui/pull/20591#issuecomment-780854819

[test] Move a11y tree exclusion to appropriate document

---

packages/material-ui-lab/src/DesktopTimePicker/DesktopTimePicker.test.tsx
packages/material-ui-lab/src/internal/pickers/PickersPopper.tsx

Closes https://github.com/mui-org/material-ui/issues/24874
We're hitting https://github.com/facebook/react/issues/20074 again. 
Trying a different fix than the one in ClickAwayListener. In the lab we can experiment a bit more. Getting rid of the timers would make this logic easier to follow 
I think I didn't fully grasp the implications of that bug since I thought https://github.com/facebook/react/issues/20074 only had implications for components **inside** a Portal. But that's not true since it'll flush all effects in a React root (all roots?) not just in a particular subtree of a component.
- [test_unit fail](https://app.circleci.com/pipelines/github/mui-org/material-ui/38202/workflows/73660994-7dbe-400c-a8e1-bfb8b709632e/jobs/225523)
- [test_browser …

[pickers] Fix picker components not opening on click in React 17

---

packages/material-ui-lab/src/DatePicker/DatePicker.tsx
packages/material-ui-lab/src/DateTimePicker/DateTimePicker.tsx
packages/material-ui-lab/src/DateTimePicker/DateTimePickerToolbar.tsx
packages/material-ui-lab/src/DesktopDatePicker/DesktopDatePicker.tsx
packages/material-ui-lab/src/DesktopDateTimePicker/DesktopDateTimePicker.tsx
packages/material-ui-lab/src/DesktopTimePicker/DesktopTimePicker.tsx
packages/material-ui-lab/src/MobileDatePicker/MobileDatePicker.tsx
packages/material-ui-lab/src/MobileDateTimePicker/MobileDateTimePicker.tsx
packages/material-ui-lab/src/MobileTimePicker/MobileTimePicker.tsx
packages/material-ui-lab/src/StaticDatePicker/StaticDatePicker.tsx
packages/material-ui-lab/src/StaticDateTimePicker/StaticDateTimePicker.tsx
packages/material-ui-lab/src/StaticTimePicker/StaticTimePicker.tsx
packages/material-ui-lab/src/TimePicker/TimePicker.tsx
packages/material-ui-lab/src/TimePicker/TimePickerToolbar.tsx
packages/material-ui-lab/src/internal/pickers/KeyboardDateInput.tsx
packages/material-ui-lab/src/internal/pickers/Picker/makePickerWithState.tsx
packages/material-ui-lab/src/internal/pickers/hooks/useMaskedInput.tsx

Edit @oliviertassinari, won't fix. Instead, use this as an opportunity to clean more code in the pickers. It still feels like there is lot of work. The level of indirection with all the wrappers is frightening. 
---
Timepicker/datepicker placeholder overrides didn't work on the text field.  This is because the masked input was directly putting the placeholder on the input, rather than passing it through text field props.  By adding it as a text field prop we can now override it in the renderInput function on pickers.
```jsx
<TimePicker
renderInput={props => (
<TextField
{...props}
helperText="override works today"
placeholder="override now works due to this pr"
/>
)}
label={'Label'}
// No longer uses this as placeholder if placeholder is overriden in renderInput
inputFormat={'h:mm a'}
/> …
```

[Pickers] Clean up code

---

packages/material-ui/src/FormLabel/FormLabel.js
packages/material-ui/src/InputLabel/InputLabel.js
packages/material-ui/src/OutlinedInput/NotchedOutline.js

Add Ellipsis to InputLabel
Add maxWidth to NotchedOutline
Fixes #12255

[TextField] Fix label wrap, display an ellipsis instead

---

.yarnrc

<details><summary>changelog</summary>
>## 1.22.10 (and prior)
>
>- Tweak the preinstall check to not cause errors when Node is installed as root (as a downside, it won't run at all on Windows, which should be an acceptable tradeoff): https://github.com/yarnpkg/yarn/issues/8358
>
>## 1.22.7
>
>This release doesn't change anything and was caused by a publish issue.
>
>## 1.22.6
>
>- Running `yarn init` with the `-2` flag won't print the `set version` output anymore.
>
>- A new preinstall check will ensure that `npm install -g yarn` works even under [Corepack](https://github.com/arcanis/corepack). It doesn't have any effect on other setups.
>
>## 1.22.5
>
>- Headers won't be printed when calling `yarn init` with the `-2` flag
>
>  [**Maël Nison**](https://twitter.com/arcanis)
>
>- Files with …

Bump yarn to 1.22.10

---

packages/material-ui-lab/src/DesktopDatePicker/DesktopDatePicker.test.tsx
packages/material-ui-lab/src/PickersDay/PickersDay.tsx

Closes https://github.com/mui-org/material-ui/pull/24444
Closes https://github.com/mui-org/material-ui/issues/23899
Attempted to fix this in Popper itself but this is quite complicated: https://github.com/mui-org/material-ui/pull/24760
Preview: https://deploy-preview-25010--material-ui.netlify.app/components/date-picker/#main-content

[pickers] Fix scroll-jump when opening with a selected value

---

docs/pages/api-docs/form-control-label.json
docs/translations/api-docs/form-control-label/form-control-label.json
packages/material-ui/src/FormControl/FormControl.test.js
packages/material-ui/src/FormControl/index.d.ts
packages/material-ui/src/FormControl/index.js
packages/material-ui/src/FormControlLabel/FormControlLabel.d.ts
packages/material-ui/src/FormControlLabel/FormControlLabel.js
packages/material-ui/src/FormControlLabel/FormControlLabel.test.js
packages/material-ui/src/FormControlLabel/formControlLabelClasses.d.ts
packages/material-ui/src/FormControlLabel/formControlLabelClasses.js
packages/material-ui/src/FormControlLabel/index.d.ts
packages/material-ui/src/FormControlLabel/index.js
packages/material-ui/src/FormHelperText/FormHelperText.test.js

Took it from this list -> https://github.com/mui-org/material-ui/issues/24405
Seems like it wasn't picked up yet.

[TextField] Migrate FormControlLabel to emotion

---

scripts/sizeSnapshot/webpack.config.js

Motivated by #24857. I was eager to see if the Modal still had a low bundle size footprint. My main concern with tracking the size of the unstyled components is that it makes the CI slower. But I guess it's fine.

[test] Track bundle size of unstyled components

---

examples/create-react-app-with-styled-components/README.md

Closes #25019 I've added a working example in codesandbox with `styled-componetns` as an engine.

[docs] Add codesandbox example for styled-components

---

test/karma.conf.js

- Apply `pollingTimeout` in the right place https://github.com/karma-runner/karma/blob/a14a24ef81348b29daf70e0ea8406588fdd01f19/test/client/karma.conf.js#L157. I could still see requests being rate limited. It was definitely not working. From this weekend: https://app.circleci.com/pipelines/github/mui-org/material-ui/38379/workflows/fd8828d1-742b-4c3e-8642-2de896135298/jobs/226555
- Set `browserNoActivityTimeout` to the recommended default: https://github.com/karma-runner/karma/blob/a14a24ef81348b29daf70e0ea8406588fdd01f19/test/client/karma.conf.js#L129. We don't need the value to be this long. If after 3 minutes, there is no activity, we can likely conclude it has crashed and stop the worker. This is the default @eps1lon reported in …

[test] Improve BrowserStack configuration

---

packages/material-ui/src/Paper/Paper.d.ts
packages/material-ui/src/Paper/Paper.spec.tsx
packages/material-ui/test/typescript/components.spec.tsx

Added the OverridableComponent to Paper.
It solves the TypeScript issue here: #21154

[Paper] Fix type support of overridable component

---

docs/src/pages/company/careers/careers.md
packages/material-ui/src/FilledInput/FilledInput.js
packages/material-ui/src/styles/createPalette.js

Update opacity for light backgroundColor in FilledInput
Update opacity in palette
Fixes [#249247](https://github.com/mui-org/material-ui/issues/24947)

[TextField] Fix FilledInput AA contrast issue

---

packages/material-ui/src/Button/Button.js
packages/material-ui/src/Button/Button.test.js

Fixes classes not getting added to button element.
Forwards classes from Button component prop to ButtonBase component.
Closes #25011

[Button] Fix forward classes to ButtonBase

---

docs/src/pages/components/alert/ActionAlerts.js
docs/src/pages/components/alert/ActionAlerts.tsx
docs/src/pages/components/alert/BasicAlerts.js
docs/src/pages/components/alert/BasicAlerts.tsx
docs/src/pages/components/alert/DescriptionAlerts.js
docs/src/pages/components/alert/DescriptionAlerts.tsx
docs/src/pages/components/alert/FilledAlerts.js
docs/src/pages/components/alert/FilledAlerts.tsx
docs/src/pages/components/alert/IconAlerts.js
docs/src/pages/components/alert/IconAlerts.tsx
docs/src/pages/components/alert/OutlinedAlerts.js
docs/src/pages/components/alert/OutlinedAlerts.tsx
docs/src/pages/components/alert/TransitionAlerts.js
docs/src/pages/components/alert/TransitionAlerts.tsx

[docs] Migrate Alert demos to emotion

---

.circleci/config.yml

Fixes https://app.circleci.com/pipelines/github/mui-org/material-ui/38504/workflows/d60da495-321b-4828-848b-ff9692f5cb59/jobs/227381
New image is missing Roboto fonts (see https://www.argos-ci.com/mui-org/material-ui/builds/553). Pinning to the working version to unblock work.
Between `next` and newer runs the docker image changed. The change probably includes https://github.com/microsoft/playwright/pull/5429.

[core] Pin playwright image to known working version

---

.circleci/config.yml
docs/pages/api-docs/form-control.json
docs/pages/api-docs/text-field.json
docs/src/pages/components/text-fields/CustomizedInputBase.js
docs/src/pages/components/text-fields/CustomizedInputBase.tsx
docs/src/pages/components/text-fields/CustomizedInputs.js
docs/src/pages/components/text-fields/CustomizedInputs.tsx
framer/Material-UI.framerfx/code/TextField.tsx
framer/scripts/framerConfig.js
packages/material-ui/src/FilledInput/FilledInput.js
packages/material-ui/src/FormControl/FormControl.d.ts
packages/material-ui/src/FormControl/FormControl.js
packages/material-ui/src/FormLabel/FormLabel.js
packages/material-ui/src/Input/Input.js
packages/material-ui/src/InputBase/InputBase.d.ts
packages/material-ui/src/TextField/TextField.d.ts
packages/material-ui/src/TextField/TextField.js
packages/material-ui/src/styles/components.d.ts
packages/material-ui/test/typescript/moduleAugmentation/textFieldCustomProps.spec.tsx
packages/material-ui/test/typescript/moduleAugmentation/textFieldCustomProps.tsconfig.json

One chunk of #13875 for TextField

[TextField] Support custom color and size

---

docs/pages/api-docs/snackbar-content.json
docs/translations/api-docs/snackbar-content/snackbar-content.json
framer/Material-UI.framerfx/code/SnackbarContent.tsx
framer/scripts/framerConfig.js
packages/material-ui/src/AccordionDetails/AccordionDetails.js
packages/material-ui/src/SnackbarContent/SnackbarContent.d.ts
packages/material-ui/src/SnackbarContent/SnackbarContent.js
packages/material-ui/src/SnackbarContent/SnackbarContent.test.js
packages/material-ui/src/SnackbarContent/index.d.ts
packages/material-ui/src/SnackbarContent/index.js
packages/material-ui/src/SnackbarContent/snackbarContentClasses.d.ts
packages/material-ui/src/SnackbarContent/snackbarContentClasses.js

My first contribution to #24405.

[Snackbar] Migrate SnackbarContent to emotion

---

docs/src/pages/components/autocomplete/Virtualize.js
docs/src/pages/components/autocomplete/Virtualize.tsx
packages/material-ui/src/Autocomplete/Autocomplete.js

This one is impossible to miss: open https://next--material-ui.netlify.app/components/autocomplete/#virtualization, it's crazy slow. I have found this looking at #25096. It was broken in #24696, we didn't release it yet.

[Autocomplete] Fix ListboxComponent slot regression

---

packages/material-ui/src/Autocomplete/Autocomplete.js

Implement fix for click on no-option text when AutoComplete component is opened based on the suggestion of
Closes #24781

[Autocomplete] Prevent closing on no-option text click

---

yarn.lock

Includes
- [7.13.0](https://github.com/babel/babel/releases/tag/v7.13.0)
- [7.13.1](https://github.com/babel/babel/releases/tag/v7.13.1)
- [7.13.2](https://github.com/babel/babel/releases/tag/v7.13.2)
- [7.13.3](https://github.com/babel/babel/releases/tag/v7.13.3)
- [7.13.4](https://github.com/babel/babel/releases/tag/v7.13.4)
- [7.13.5](https://github.com/babel/babel/releases/tag/v7.13.5)
- [7.13.6](https://github.com/babel/babel/releases/tag/v7.13.6)
- [7.13.7](https://github.com/babel/babel/releases/tag/v7.13.7)
- [7.13.8](https://github.com/babel/babel/releases/tag/v7.13.8)

Bump @babel/* to 7.13.8

---

docs/public/static/error-codes.json
package.json
packages/material-ui-styles/src/propsToClassKey/propsToClassKey.js
packages/material-ui/package.json

1. Make sure we extract error codes for all packages
2. use `capitalize` from utils in `propsToClassKey`
3. Update the message for existing error codes since it was just a formatting change. Generally, error messages should be additive since they're relevant to older contexts not current ones.

[styles] Use capitalize from utils

---

packages/material-ui-icons/builder.js
packages/material-ui-icons/builder.test.js

Review without whitespace diff advised. Modernization described in each commit message.
Motivated by failing tests when bumping svgo that did not offer any hint what was wrong.
Test plan

[core] Modernize icons `builder:src`

---

docs/pages/api-docs/pagination-item.json
docs/pages/api-docs/pagination.json
docs/translations/api-docs/pagination-item/pagination-item.json
docs/translations/api-docs/pagination/pagination.json
packages/material-ui/src/Autocomplete/Autocomplete.js
packages/material-ui/src/Pagination/Pagination.d.ts
packages/material-ui/src/Pagination/Pagination.js
packages/material-ui/src/Pagination/Pagination.test.js
packages/material-ui/src/Pagination/index.d.ts
packages/material-ui/src/Pagination/index.js
packages/material-ui/src/Pagination/paginationClasses.d.ts
packages/material-ui/src/Pagination/paginationClasses.js
packages/material-ui/src/PaginationItem/PaginationItem.d.ts
packages/material-ui/src/PaginationItem/PaginationItem.js
packages/material-ui/src/PaginationItem/PaginationItem.test.js
packages/material-ui/src/PaginationItem/index.d.ts
packages/material-ui/src/PaginationItem/index.js
packages/material-ui/src/PaginationItem/paginationItemClasses.d.ts
packages/material-ui/src/PaginationItem/paginationItemClasses.js
packages/material-ui/src/ToggleButton/ToggleButton.js
packages/material-ui/src/ToggleButtonGroup/ToggleButtonGroup.js

[Pagination] Migrate Pagination and PaginationItem to emotion

---

packages/material-ui/src/Tooltip/Tooltip.test.js
packages/material-ui/src/styles/experimentalStyled.js
packages/material-ui/src/styles/experimentalStyled.test.js
test/utils/describeConformanceV5.js

[styled] Fix override logic to support component without root

---

packages/material-ui/src/TableCell/TableCell.js
packages/material-ui/src/TableCell/TableCell.test.js
packages/material-ui/test/integration/TableCell.test.js

Remove default role assignment logic from ``TableCell`` component.
Fix #21470

[Table] Remove default role logic in TableCell

---

docs/src/pages/components/buttons/ButtonSizes.js
docs/src/pages/components/buttons/ButtonSizes.tsx
docs/src/pages/components/buttons/ContainedButtons.js
docs/src/pages/components/buttons/ContainedButtons.tsx
docs/src/pages/components/buttons/IconButtons.js
docs/src/pages/components/buttons/IconButtons.tsx
docs/src/pages/components/buttons/IconLabelButtons.js
docs/src/pages/components/buttons/IconLabelButtons.tsx
docs/src/pages/components/buttons/LoadingButtons.js
docs/src/pages/components/buttons/LoadingButtons.tsx
docs/src/pages/components/buttons/LoadingButtonsTransition.js
docs/src/pages/components/buttons/LoadingButtonsTransition.tsx
docs/src/pages/components/buttons/OutlinedButtons.js
docs/src/pages/components/buttons/OutlinedButtons.tsx
docs/src/pages/components/buttons/TextButtons.js
docs/src/pages/components/buttons/TextButtons.tsx
docs/src/pages/components/buttons/UploadButtons.js
docs/src/pages/components/buttons/UploadButtons.tsx

The following demos of the `Button` component were migrated:

[docs] Migrate Button demos to emotion

---

docs/pages/api-docs/drawer.json
docs/translations/api-docs/drawer/drawer.json
packages/material-ui/src/Drawer/Drawer.d.ts
packages/material-ui/src/Drawer/Drawer.js
packages/material-ui/src/Drawer/Drawer.test.js
packages/material-ui/src/Drawer/drawerClasses.d.ts
packages/material-ui/src/Drawer/drawerClasses.js
packages/material-ui/src/Drawer/index.d.ts
packages/material-ui/src/Drawer/index.js

#24405
I have 4 test failing still....
First 2 I am not sure how they are related to `Drawer`
The second 2 I will try and work out. I am a little rusty with these conversions lol.
However, the code has been changed so a good start I think.

[Drawer] Migrate to emotion

---

test/regressions/index.test.js
test/regressions/manual/README.md
test/regressions/manual/icons/AllIcons.js

Requires capturing the full element. Considering the code comment this leaks into subsequent tests but I checked older puppeteer PRs and they claimed the viewport would be restored. ~Maybe this was fixed?~ Seems like this was fixed or we didn't do this initially to reduce changes when switching from vrtest to playwright.
All the changes look like a win to me. Though not approving until I get a second review.
Aside:
1. Don't time out when using the [playwright inspector](https://playwright.dev/docs/inspector/)

[test] Add (manual) visual regression test for icons

---

packages/material-ui/src/useAutocomplete/useAutocomplete.d.ts
packages/material-ui/src/useAutocomplete/useAutocomplete.spec.ts

This PR is aiming to fix: #24639
- Enable Autocomplete component to use const types
- Add test for typing
**Additional information**
There is two possible solution to address this:
``ReadonlyArray<T>`` and ``T[] | Readonly<T[]>``
I took the former, but happy to change it to to latter if it is more aligned with the the project directives.

[Autocomplete] Support readonly type for the options

---

docs/src/pages/components/dividers/InsetDividers.js
docs/src/pages/components/dividers/InsetDividers.tsx
docs/src/pages/components/dividers/ListDividers.js
docs/src/pages/components/dividers/ListDividers.tsx
docs/src/pages/components/dividers/MiddleDividers.js
docs/src/pages/components/dividers/MiddleDividers.tsx
docs/src/pages/components/dividers/SubheaderDividers.js
docs/src/pages/components/dividers/SubheaderDividers.tsx
docs/src/pages/components/dividers/VerticalDividers.js
docs/src/pages/components/dividers/VerticalDividers.tsx

The following demos of the `Button` component were migrated:

[docs] Migrate Divider demos to emotion

---

packages/material-ui-lab/src/internal/pickers/KeyboardDateInput.tsx
packages/material-ui-lab/src/internal/pickers/Picker/makePickerWithState.tsx
packages/material-ui-lab/src/internal/pickers/PureDateInput.tsx
packages/material-ui-lab/src/internal/pickers/wrappers/WrapperProps.ts

Internal change only. If this change affects your code, please open an issue.
Opened another can of worms in https://github.com/mui-org/material-ui/pull/25172: refs in pickers.

[pickers][internal] Use React.forwardRef instead of forwardedRef prop

---

docs/pages/api-docs/radio.json
docs/src/pages/components/radio-buttons/RadioButtons.js
docs/src/pages/components/radio-buttons/RadioButtons.tsx
docs/translations/api-docs/radio/radio.json
framer/Material-UI.framerfx/code/Radio.tsx
framer/scripts/framerConfig.js
packages/material-ui/src/Radio/Radio.d.ts
packages/material-ui/src/Radio/Radio.js
packages/material-ui/src/Radio/Radio.test.js
packages/material-ui/src/Radio/index.d.ts
packages/material-ui/src/Radio/index.js
packages/material-ui/src/Radio/radioClasses.d.ts
packages/material-ui/src/Radio/radioClasses.js

[Radio] Migrate to emotion

---

docs/src/pages/components/bottom-navigation/FixedBottomNavigation.js
docs/src/pages/components/bottom-navigation/FixedBottomNavigation.tsx
docs/src/pages/components/bottom-navigation/LabelBottomNavigation.js
docs/src/pages/components/bottom-navigation/LabelBottomNavigation.tsx
docs/src/pages/components/bottom-navigation/SimpleBottomNavigation.js
docs/src/pages/components/bottom-navigation/SimpleBottomNavigation.tsx

The following demos of the Bottom Navigation component were migrated:

[docs] Migrate Bottom Navigation demos to emotion

---

docs/src/pages/components/dividers/MiddleDividers.js
docs/src/pages/components/dividers/MiddleDividers.tsx
docs/src/pages/components/pagination/BasicPagination.js
docs/src/pages/components/pagination/BasicPagination.tsx
docs/src/pages/components/pagination/PaginationButtons.js
docs/src/pages/components/pagination/PaginationButtons.tsx
docs/src/pages/components/pagination/PaginationControlled.js
docs/src/pages/components/pagination/PaginationControlled.tsx
docs/src/pages/components/pagination/PaginationOutlined.js
docs/src/pages/components/pagination/PaginationOutlined.tsx
docs/src/pages/components/pagination/PaginationRanges.js
docs/src/pages/components/pagination/PaginationRanges.tsx
docs/src/pages/components/pagination/PaginationRounded.js
docs/src/pages/components/pagination/PaginationRounded.tsx
docs/src/pages/components/pagination/PaginationSize.js
docs/src/pages/components/pagination/PaginationSize.tsx
docs/src/pages/components/pagination/UsePagination.js
docs/src/pages/components/pagination/UsePagination.tsx

The following demos of the Pagination component were migrated:

[docs] Migrate Pagination demos to emotion

---

docs/pages/api-docs/speed-dial-action.json
docs/pages/api-docs/speed-dial-icon.json
docs/pages/api-docs/speed-dial.json
docs/translations/api-docs/speed-dial-action/speed-dial-action.json
docs/translations/api-docs/speed-dial-icon/speed-dial-icon.json
docs/translations/api-docs/speed-dial/speed-dial.json
packages/material-ui/src/SpeedDial/SpeedDial.d.ts
packages/material-ui/src/SpeedDial/SpeedDial.js
packages/material-ui/src/SpeedDial/SpeedDial.test.js
packages/material-ui/src/SpeedDial/index.d.ts
packages/material-ui/src/SpeedDial/index.js
packages/material-ui/src/SpeedDial/speedDialClasses.d.ts
packages/material-ui/src/SpeedDial/speedDialClasses.js
packages/material-ui/src/SpeedDialAction/SpeedDialAction.d.ts
packages/material-ui/src/SpeedDialAction/SpeedDialAction.js
packages/material-ui/src/SpeedDialAction/SpeedDialAction.test.js
packages/material-ui/src/SpeedDialAction/index.d.ts
packages/material-ui/src/SpeedDialAction/index.js
packages/material-ui/src/SpeedDialAction/speedDialActionClasses.d.ts
packages/material-ui/src/SpeedDialAction/speedDialActionClasses.js
packages/material-ui/src/SpeedDialIcon/SpeedDialIcon.d.ts
packages/material-ui/src/SpeedDialIcon/SpeedDialIcon.js
packages/material-ui/src/SpeedDialIcon/SpeedDialIcon.test.js
packages/material-ui/src/SpeedDialIcon/index.d.ts
packages/material-ui/src/SpeedDialIcon/index.js
packages/material-ui/src/SpeedDialIcon/speedDialIconClasses.d.ts
packages/material-ui/src/SpeedDialIcon/speedDialIconClasses.js

This PR migrates `SpeedDial`, `SpeedDialIcon` and `SpeedDialAction` from #24405.

[SpeedDial] Migrate to emotion

---

docs/src/pages/components/typography/Types.js
docs/src/pages/components/typography/Types.tsx
docs/src/pages/components/typography/TypographyTheme.js
docs/src/pages/components/typography/TypographyTheme.tsx

The following demos of the Typography component were migrated:

[docs] Migrate Typography demos to emotion

---

docs/src/pages/components/tables/EnhancedTable.js
docs/src/pages/components/tables/EnhancedTable.tsx
packages/material-ui/src/TableRow/TableRow.js

[Table] Use primary cover over secondary for selected state

---

docs/pages/api-docs/global-styles.js
docs/pages/api-docs/global-styles.json
docs/src/pages/customization/how-to-customize/how-to-customize.md
docs/src/pagesApi.js
docs/translations/api-docs/global-styles/global-styles-de.json
docs/translations/api-docs/global-styles/global-styles-es.json
docs/translations/api-docs/global-styles/global-styles-fr.json
docs/translations/api-docs/global-styles/global-styles-ja.json
docs/translations/api-docs/global-styles/global-styles-pt.json
docs/translations/api-docs/global-styles/global-styles-ru.json
docs/translations/api-docs/global-styles/global-styles-zh.json
docs/translations/api-docs/global-styles/global-styles.json
packages/material-ui/src/GlobalStyles/GlobalStyles.d.ts
packages/material-ui/src/GlobalStyles/GlobalStyles.js

[docs] Add GlobalStyles API

---

docs/src/pages/components/container/FixedContainer.js
docs/src/pages/components/container/FixedContainer.tsx
docs/src/pages/components/container/SimpleContainer.js
docs/src/pages/components/container/SimpleContainer.tsx

The following demos of the Paper component were migrated:

[docs] Migrate Container demos to emotion

---

docs/src/pages/components/buttons/ContainedButtons.js
docs/src/pages/components/buttons/ContainedButtons.tsx
docs/src/pages/components/buttons/IconLabelButtons.js
docs/src/pages/components/buttons/IconLabelButtons.tsx
docs/src/pages/components/buttons/LoadingButtons.js
docs/src/pages/components/buttons/LoadingButtons.tsx
docs/src/pages/components/buttons/OutlinedButtons.js
docs/src/pages/components/buttons/OutlinedButtons.tsx
docs/src/pages/components/buttons/TextButtons.js
docs/src/pages/components/buttons/TextButtons.tsx
docs/src/pages/components/buttons/UploadButtons.js
docs/src/pages/components/buttons/UploadButtons.tsx
docs/src/pages/components/skeleton/Animations.js
docs/src/pages/components/skeleton/Animations.tsx
docs/src/pages/components/skeleton/Facebook.js
docs/src/pages/components/skeleton/Facebook.tsx
docs/src/pages/components/skeleton/SkeletonChildren.js
docs/src/pages/components/skeleton/SkeletonChildren.tsx
docs/src/pages/components/skeleton/Variants.js
docs/src/pages/components/skeleton/Variants.tsx

The following demos of the Skeleton component were migrated:

[docs] Migrate Skeleton demos to emotion

---

docs/scripts/buildApi.ts
docs/src/modules/utils/generatePropTypeDescription.ts

By observing files, we have found that `generatePropTypeDescription` and several other functions have been duplicated at path `path1: docs/scripts/buildApi.ts` but at the path of `path2: docs/src/modules/utils/generatePropTypeDescription.ts`, we have a separate file with all of these functions. So I've decided to delete from `path1` all duplicate functions and import them from `path2`.
More: [discussion link](https://github.com/mui-org/material-ui/issues/25151#issuecomment-789075494)

[docs] Remove dead generatePropTypeDescription method

---

docs/pages/api-docs/step-content.json
docs/translations/api-docs/step-content/step-content.json
packages/material-ui/src/StepContent/StepContent.d.ts
packages/material-ui/src/StepContent/StepContent.js
packages/material-ui/src/StepContent/StepContent.test.js
packages/material-ui/src/StepContent/index.d.ts
packages/material-ui/src/StepContent/index.js
packages/material-ui/src/StepContent/stepContentClasses.d.ts
packages/material-ui/src/StepContent/stepContentClasses.js
packages/material-ui/src/Stepper/Stepper.test.js

[Stepper] Migrate StepContent to emotion

---

packages/typescript-to-proptypes/test/typescript-to-proptypes.test.ts

4s is not enough on slower CI machines.

[test] Increase ttp setup timeout

---

package.json
test/utils/createClientRender.tsx
tslint.json
yarn.lock

The file had a couple of mistakes and incomplete typings. These cannot be all fixed with `@ts-check`.
TODO:
- https://app.circleci.com/pipelines/github/mui-org/material-ui/38971/workflows/b0a64ca2-3a67-4195-9397-6f2bf7604747/jobs/230223
- https://mui-dashboard.netlify.app/test-profile/230223

[test] Convert createClientRender to TypeScript

---

docs/src/pages/components/transfer-list/SelectAllTransferList.js
docs/src/pages/components/transfer-list/SelectAllTransferList.tsx
docs/src/pages/components/transfer-list/TransferList.js
docs/src/pages/components/transfer-list/TransferList.tsx

The following demos of the Transfer List component were migrated:

[docs] Migrate Transfer List demos to emotion

---

docs/src/pages/components/rating/BasicRating.js
docs/src/pages/components/rating/BasicRating.tsx
docs/src/pages/components/rating/CustomizedRating.js
docs/src/pages/components/rating/CustomizedRating.tsx
docs/src/pages/components/rating/HalfRating.js
docs/src/pages/components/rating/HalfRating.tsx
docs/src/pages/components/rating/HoverRating.js
docs/src/pages/components/rating/HoverRating.tsx
docs/src/pages/components/rating/RatingSize.js
docs/src/pages/components/rating/RatingSize.tsx
docs/src/pages/components/rating/TextRating.js
docs/src/pages/components/rating/TextRating.tsx

The following demos of the Rating component were migrated:

[docs] Migrate Rating demos to emotion

---

docs/src/pages/components/floating-action-button/FloatingActionButtonExtendedSize.js
docs/src/pages/components/floating-action-button/FloatingActionButtonExtendedSize.tsx
docs/src/pages/components/floating-action-button/FloatingActionButtonSize.js
docs/src/pages/components/floating-action-button/FloatingActionButtonSize.tsx
docs/src/pages/components/floating-action-button/FloatingActionButtonZoom.js
docs/src/pages/components/floating-action-button/FloatingActionButtonZoom.tsx
docs/src/pages/components/floating-action-button/FloatingActionButtons.js
docs/src/pages/components/floating-action-button/FloatingActionButtons.tsx
docs/src/pages/components/floating-action-button/floating-action-button.md
packages/material-ui/src/Fab/Fab.test.js

The following demos of the Fab component were migrated:

[docs] Migrate Fab demos to emotion

---

docs/pages/api-docs/popover.json
docs/translations/api-docs/popover/popover.json
packages/material-ui/src/Popover/Popover.d.ts
packages/material-ui/src/Popover/Popover.js
packages/material-ui/src/Popover/Popover.test.js
packages/material-ui/src/Popover/index.js
packages/material-ui/src/Popover/popoverClasses.d.ts
packages/material-ui/src/Popover/popoverClasses.js

[Popover] Migrate to emotion

---

docs/src/modules/branding/BrandingPersona.tsx
docs/src/pages/components/dividers/MiddleDividers.js
docs/src/pages/components/dividers/MiddleDividers.tsx
docs/src/pages/components/menus/BasicMenu.js
docs/src/pages/components/menus/BasicMenu.tsx
docs/src/pages/components/menus/ContextMenu.js
docs/src/pages/components/menus/ContextMenu.tsx
docs/src/pages/components/menus/CustomizedMenus.js
docs/src/pages/components/menus/CustomizedMenus.tsx
docs/src/pages/components/menus/FadeMenu.js
docs/src/pages/components/menus/FadeMenu.tsx
docs/src/pages/components/menus/LongMenu.js
docs/src/pages/components/menus/LongMenu.tsx
docs/src/pages/components/menus/MenuListComposition.js
docs/src/pages/components/menus/MenuListComposition.tsx
docs/src/pages/components/menus/MenuPopupState.js
docs/src/pages/components/menus/MenuPopupState.tsx
docs/src/pages/components/menus/PositionedMenu.js
docs/src/pages/components/menus/PositionedMenu.tsx
docs/src/pages/components/menus/SimpleListMenu.js
docs/src/pages/components/menus/SimpleListMenu.tsx
docs/src/pages/components/menus/SimpleMenu.js
docs/src/pages/components/menus/TypographyMenu.js
docs/src/pages/components/menus/TypographyMenu.tsx
docs/src/pages/components/menus/menus.md

Menu buttons require an aria-expanded attribute that signals to screenreader whether the menu is currently open or not
This PR adds the missing attribute to the SimpleMenu example code
(see docs: https://www.w3.org/TR/wai-aria-practices/examples/menu-button/menu-button-links.html)

[docs] Improve accessibility of the basic menu demo

---

docs/src/pages/components/chips/Chips.js
docs/src/pages/components/chips/Chips.tsx
docs/src/pages/components/chips/ChipsArray.js
docs/src/pages/components/chips/ChipsArray.tsx
docs/src/pages/components/chips/OutlinedChips.js
docs/src/pages/components/chips/OutlinedChips.tsx
docs/src/pages/components/chips/SmallChips.js
docs/src/pages/components/chips/SmallChips.tsx
docs/src/pages/components/chips/SmallOutlinedChips.js
docs/src/pages/components/chips/SmallOutlinedChips.tsx

The following demos of the Chip component were migrated:

[docs] Migrate Chip demos to emotion

---

docs/pages/api-docs/dialog-content-text.json
docs/translations/api-docs/dialog-content-text/dialog-content-text.json
packages/material-ui/src/DialogContentText/DialogContentText.d.ts
packages/material-ui/src/DialogContentText/DialogContentText.js
packages/material-ui/src/DialogContentText/DialogContentText.test.js
packages/material-ui/src/DialogContentText/dialogContentTextClasses.d.ts
packages/material-ui/src/DialogContentText/dialogContentTextClasses.js
packages/material-ui/src/DialogContentText/index.js

[Dialog] Migrate DialogContentText to emotion

---

docs/src/pages/components/lists/AlignItemsList.js
docs/src/pages/components/lists/AlignItemsList.tsx
docs/src/pages/components/lists/CheckboxList.js
docs/src/pages/components/lists/CheckboxList.tsx
docs/src/pages/components/lists/CheckboxListSecondary.js
docs/src/pages/components/lists/CheckboxListSecondary.tsx
docs/src/pages/components/lists/FolderList.js
docs/src/pages/components/lists/FolderList.tsx
docs/src/pages/components/lists/GutterlessList.js
docs/src/pages/components/lists/GutterlessList.tsx
docs/src/pages/components/lists/InsetList.js
docs/src/pages/components/lists/InsetList.tsx
docs/src/pages/components/lists/InteractiveList.js
docs/src/pages/components/lists/InteractiveList.tsx
docs/src/pages/components/lists/NestedList.js
docs/src/pages/components/lists/NestedList.tsx
docs/src/pages/components/lists/PinnedSubheaderList.js
docs/src/pages/components/lists/PinnedSubheaderList.tsx
docs/src/pages/components/lists/SelectedListItem.js
docs/src/pages/components/lists/SelectedListItem.tsx
docs/src/pages/components/lists/SimpleList.js
docs/src/pages/components/lists/SimpleList.tsx
docs/src/pages/components/lists/SwitchListSecondary.js
docs/src/pages/components/lists/SwitchListSecondary.tsx
docs/src/pages/components/lists/VirtualizedList.js
docs/src/pages/components/lists/VirtualizedList.tsx

The following demos of the List component were migrated:

[docs] Migrate List demos to emotion

---

packages/material-ui/src/Tooltip/Tooltip.js

I have found this regression having a quick look at #25215.
To reproduce, you can:
- open https://next.material-ui.com/components/tooltips/#positioned-tooltips
- keyboard focus the bottom-start case, the tooltip should open
- scroll the page up until the tooltip swap its placement
**Before**
**After**

[Tooltip] Fix placement regression

---

docs/pages/api-docs/collapse.json
docs/pages/api-docs/fade.json
docs/pages/api-docs/grow.json
docs/pages/api-docs/slide.json
docs/pages/api-docs/zoom.json
docs/translations/api-docs/collapse/collapse.json
docs/translations/api-docs/fade/fade.json
docs/translations/api-docs/grow/grow.json
docs/translations/api-docs/slide/slide.json
docs/translations/api-docs/zoom/zoom.json
packages/material-ui/src/Collapse/Collapse.d.ts
packages/material-ui/src/Collapse/Collapse.js
packages/material-ui/src/Fade/Fade.d.ts
packages/material-ui/src/Fade/Fade.js
packages/material-ui/src/Grow/Grow.d.ts
packages/material-ui/src/Grow/Grow.js
packages/material-ui/src/Slide/Slide.d.ts
packages/material-ui/src/Slide/Slide.js
packages/material-ui/src/Slide/Slide.test.js
packages/material-ui/src/Zoom/Zoom.d.ts
packages/material-ui/src/Zoom/Zoom.js
packages/material-ui/src/transitions/transition.d.ts
packages/material-ui/src/transitions/utils.js

- Add easing (transition timing function) property to transition components to be able override the default style on enter and leave animations, similar to how timeout is set up.
```js
<Zoom 
easing={{
enter: 'cubic-bezier(0.71, 0.11, 0.35, 1.28)',
exit: 'cubic-bezier(1,.18,.74,1.03)',
}}
>
```
- Update type definitions and related API docs
Fix #24980

[Transition] Add easing prop to override default timing function

---

packages/material-ui/src/Autocomplete/Autocomplete.js
packages/material-ui/src/Autocomplete/Autocomplete.test.js

- [ x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui-org/material-ui/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).
Fix #25147

[Autocomplete] Fix styleOverrides support

---

packages/material-ui/src/Dialog/Dialog.js

Fixes a small typo I found in the `Dialog` component.

[Dialog] Fix typo

---

docs/src/pages/getting-started/supported-platforms/supported-platforms.md

Preview: https://deploy-preview-25262--material-ui.netlify.app/getting-started/supported-platforms/#browser
This is a follow-up after #25222. Since the last time, we talk about the support policy of IE 11 in #14420, this happened: [Next.js issues with IE 11](https://github.com/vercel/next.js/issues?q=is%3Aissue+is%3Aopen+IE+11). Iterating on issues with IE 11 has become very painful. Our development environment crash when loaded in IE 11. While the cost of working on IE 11 has increased by a large amount, the value is also continually going down.
It seems that we have reached a point where the opportunity cost for improving the support of IE 11 will very rarely outweigh the value of the alternative problems we can spend time on. 
Hence, I'm taking the time to upgrade the documentation to …

[docs] Bring clarity about the IE 11 support policy: it's partial

---

docs/src/pages/components/image-list/CustomImageList.js
docs/src/pages/components/image-list/CustomImageList.tsx
docs/src/pages/components/image-list/MasonryImageList.js
docs/src/pages/components/image-list/MasonryImageList.tsx
docs/src/pages/components/image-list/QuiltedImageList.js
docs/src/pages/components/image-list/QuiltedImageList.tsx
docs/src/pages/components/image-list/StandardImageList.js
docs/src/pages/components/image-list/StandardImageList.tsx
docs/src/pages/components/image-list/TitlebarBelowImageList.js
docs/src/pages/components/image-list/TitlebarBelowImageList.tsx
docs/src/pages/components/image-list/TitlebarBelowMasonryImageList.js
docs/src/pages/components/image-list/TitlebarBelowMasonryImageList.tsx
docs/src/pages/components/image-list/TitlebarImageList.js
docs/src/pages/components/image-list/TitlebarImageList.tsx
docs/src/pages/components/image-list/WovenImageList.js
docs/src/pages/components/image-list/WovenImageList.tsx

The following demos of the Image List component were migrated:

[docs] Migrate Image List to emotion

---

docs/scripts/buildApi.ts
scripts/generateProptypes.ts
scripts/jsonlint.js
tsconfig.json

Requires node 12
`Promise.all` resolves once any promise rejects. `Promise.allSettled` resolves after all promises have either resolved or rejected i.e. settled. `Promise.all` is like running the test suite with `--bail` which is not always desired. 
For `yarn proptypes` this will lead to only the failed Component creating an empty file (under certain circumstances). Before, it would leave the whole repo in an inconsistent state even though just one component failed.

[core] Use Promise.allSettled over .all where appropriate

---

packages/material-ui/src/SpeedDial/SpeedDial.js
packages/material-ui/src/SpeedDial/SpeedDial.test.js
packages/material-ui/src/SpeedDialAction/SpeedDialAction.js
test/utils/fireDiscreteEvent.js

Fixes #25215.
This PR also fixes the tooltip placement when the `direction` prop is left or right.
Before:
After:

[SpeedDial] Reset tooltip state when the speed dial is closed

---

docs/src/pages/components/links/Links.js
docs/src/pages/components/links/Links.tsx
docs/src/pages/components/links/UnderlineLink.js
docs/src/pages/components/links/UnderlineLink.tsx

The following demos of the Links component were migrated:

[docs] Migrate Links to emotion

---

docs/src/pages/components/grid/AutoGrid.js
docs/src/pages/components/grid/AutoGrid.tsx
docs/src/pages/components/grid/AutoGridNoWrap.js
docs/src/pages/components/grid/AutoGridNoWrap.tsx
docs/src/pages/components/grid/CSSGrid.js
docs/src/pages/components/grid/CSSGrid.tsx
docs/src/pages/components/grid/CenteredGrid.js
docs/src/pages/components/grid/CenteredGrid.tsx
docs/src/pages/components/grid/ComplexGrid.js
docs/src/pages/components/grid/ComplexGrid.tsx
docs/src/pages/components/grid/FullWidthGrid.js
docs/src/pages/components/grid/FullWidthGrid.tsx
docs/src/pages/components/grid/InteractiveGrid.js
docs/src/pages/components/grid/InteractiveGrid.tsx
docs/src/pages/components/grid/NestedGrid.js
docs/src/pages/components/grid/NestedGrid.tsx
docs/src/pages/components/grid/SpacingGrid.js
docs/src/pages/components/grid/SpacingGrid.tsx

The following demos of the Grid component were migrated:

[docs] Migrate Grid to emotion

---

docs/src/pages/components/app-bar/BackToTop.js
docs/src/pages/components/app-bar/BackToTop.tsx
docs/src/pages/components/app-bar/BottomAppBar.js
docs/src/pages/components/app-bar/BottomAppBar.tsx
docs/src/pages/components/app-bar/ButtonAppBar.js
docs/src/pages/components/app-bar/ButtonAppBar.tsx
docs/src/pages/components/app-bar/DenseAppBar.js
docs/src/pages/components/app-bar/DenseAppBar.tsx
docs/src/pages/components/app-bar/MenuAppBar.js
docs/src/pages/components/app-bar/MenuAppBar.tsx
docs/src/pages/components/app-bar/PrimarySearchAppBar.js
docs/src/pages/components/app-bar/PrimarySearchAppBar.tsx
docs/src/pages/components/app-bar/ProminentAppBar.js
docs/src/pages/components/app-bar/ProminentAppBar.tsx
docs/src/pages/components/app-bar/SearchAppBar.js
docs/src/pages/components/app-bar/SearchAppBar.tsx
docs/src/pages/components/app-bar/app-bar.md

[docs] Migrate AppBar demos to emotion

---

docs/pages/api-docs/autocomplete.json
docs/pages/api-docs/breadcrumbs.json
docs/pages/api-docs/drawer.json
docs/pages/api-docs/image-list-item.json
docs/pages/api-docs/image-list.json
docs/pages/api-docs/mobile-stepper.json
docs/pages/api-docs/pagination-item.json
docs/pages/api-docs/pagination.json
docs/pages/api-docs/paper.json
docs/pages/api-docs/popover.json
docs/pages/api-docs/step.json
docs/pages/api-docs/stepper.json
docs/pages/api-docs/table-pagination.json
docs/src/modules/utils/generatePropTypeDescription.ts
packages/material-ui/src/Autocomplete/Autocomplete.js
packages/material-ui/src/Breadcrumbs/Breadcrumbs.js
packages/material-ui/src/Drawer/Drawer.js
packages/material-ui/src/ImageList/ImageList.js
packages/material-ui/src/ImageListItem/ImageListItem.js
packages/material-ui/src/MobileStepper/MobileStepper.js
packages/material-ui/src/Pagination/Pagination.js
packages/material-ui/src/PaginationItem/PaginationItem.d.ts
packages/material-ui/src/PaginationItem/PaginationItem.js
packages/material-ui/src/Paper/Paper.js
packages/material-ui/src/Popover/Popover.js
packages/material-ui/src/Step/Step.js
packages/material-ui/src/Stepper/Stepper.js
packages/material-ui/src/TablePagination/TablePagination.js

As we have successfully integrated our custom propType in Pagination component on ['count'](https://github.com/mui-org/material-ui/pull/25224) prop, so we have decided to move forward and change the ones, who have a strong preference to be an 'integer' type. So we have [discussed](https://github.com/mui-org/material-ui/pull/25224#issuecomment-794504745) changing, several components props' types for proper validating. 
CodeSandbox Link: https://codesandbox.io/s/create-react-app-bsix2?file=/src/App.js
Closes #25327

[docs] Refine the used prop-type to discriminate number from integer

---

docs/pages/api-docs/input-adornment.json
docs/translations/api-docs/input-adornment/input-adornment.json
packages/material-ui/src/ButtonGroup/ButtonGroup.js
packages/material-ui/src/InputAdornment/InputAdornment.d.ts
packages/material-ui/src/InputAdornment/InputAdornment.js
packages/material-ui/src/InputAdornment/InputAdornment.test.js
packages/material-ui/src/InputAdornment/index.d.ts
packages/material-ui/src/InputAdornment/index.js
packages/material-ui/src/InputAdornment/inputAdornmentClasses.d.ts
packages/material-ui/src/InputAdornment/inputAdornmentClasses.js

[TextField] Migrate InputAdornment to emotion

---

docs/src/pages/components/speed-dial/BasicSpeedDial.js
docs/src/pages/components/speed-dial/BasicSpeedDial.tsx
docs/src/pages/components/speed-dial/ControlledOpenSpeedDial.js
docs/src/pages/components/speed-dial/ControlledOpenSpeedDial.tsx
docs/src/pages/components/speed-dial/OpenIconSpeedDial.js
docs/src/pages/components/speed-dial/OpenIconSpeedDial.tsx
docs/src/pages/components/speed-dial/PlaygroundSpeedDial.js
docs/src/pages/components/speed-dial/PlaygroundSpeedDial.tsx
docs/src/pages/components/speed-dial/SpeedDialTooltipOpen.js
docs/src/pages/components/speed-dial/SpeedDialTooltipOpen.tsx
docs/src/pages/components/speed-dial/speed-dial.md

The following demos of the Speed Dial component were migrated:

[docs] Migrate SpeedDial to emotion

---

docs/pages/api-docs/menu.json
docs/translations/api-docs/menu/menu.json
packages/material-ui/src/Menu/Menu.d.ts
packages/material-ui/src/Menu/Menu.js
packages/material-ui/src/Menu/Menu.test.js
packages/material-ui/src/Menu/index.js
packages/material-ui/src/Menu/menuClasses.d.ts
packages/material-ui/src/Menu/menuClasses.js

[Menu] Migrate to emotion

---

docs/next.config.js
docs/package.json
package.json
yarn.lock

In next 10 webpack is bundled so `resolutions` does not have any effect. This can result in a mismatch between `webpack.DefinePlugin` and the webpack version used by next. We can use their 1st class API for environment variables instead.

[docs] Use `env` next config over DefinePlugin

---

packages/material-ui-lab/src/DatePicker/DatePicker.tsx
packages/material-ui-lab/src/DateRangePicker/makeDateRangePicker.tsx
packages/material-ui-lab/src/DateTimePicker/DateTimePicker.tsx
packages/material-ui-lab/src/DesktopDatePicker/DesktopDatePicker.tsx
packages/material-ui-lab/src/DesktopDateTimePicker/DesktopDateTimePicker.tsx
packages/material-ui-lab/src/DesktopTimePicker/DesktopTimePicker.tsx
packages/material-ui-lab/src/MobileDatePicker/MobileDatePicker.tsx
packages/material-ui-lab/src/MobileDateTimePicker/MobileDateTimePicker.tsx
packages/material-ui-lab/src/MobileTimePicker/MobileTimePicker.tsx
packages/material-ui-lab/src/StaticDatePicker/StaticDatePicker.tsx
packages/material-ui-lab/src/StaticDateTimePicker/StaticDateTimePicker.tsx
packages/material-ui-lab/src/StaticTimePicker/StaticTimePicker.tsx
packages/material-ui-lab/src/TimePicker/TimePicker.tsx
packages/material-ui-lab/src/internal/pickers/wrappers/DesktopTooltipWrapper.tsx
packages/material-ui-lab/src/internal/pickers/wrappers/DesktopWrapper.tsx
packages/material-ui-lab/src/internal/pickers/wrappers/MobileWrapper.tsx
packages/material-ui-lab/src/internal/pickers/wrappers/ResponsiveWrapper.tsx
packages/material-ui-lab/src/internal/pickers/wrappers/StaticWrapper.tsx
packages/material-ui-lab/src/internal/pickers/wrappers/Wrapper.tsx
packages/material-ui-lab/src/internal/pickers/wrappers/WrapperProps.ts

Turns out we don't need these concrete wrapper components (e.g. `DesktopTimePickerWrapper`). 
Once we inlined `makeDateRangePicker` we can reduce the rest of the wrapper utility types.

[pickers] Simplify internals of *Wrapper components

---

packages/material-ui-utils/src/useControlled.d.ts

useControlled returns a pair: value and function to update value. And useControlled is using React.useState. The function from useControlled is a simple wrapper around the function from useState. Since useState hook allows to update state by passing a function as an argument (prevState: T => T) useControlled hook should allow to do so.

[utils] Allow functional updates in TypeScript declaration of useControlled

---

packages/material-ui/src/Radio/RadioButtonIcon.js

This has been broken for a while, already in v4 https://validator.w3.org/nu/?doc=https%3A%2F%2Fmaterial-ui.com%2Fcomponents%2Fradio-buttons%2F

[Radio] Fix html structure

---

docs/src/pages/components/avatars/BadgeAvatars.js
docs/src/pages/components/avatars/BadgeAvatars.tsx
docs/src/pages/components/avatars/FallbackAvatars.js
docs/src/pages/components/avatars/FallbackAvatars.tsx
docs/src/pages/components/avatars/IconAvatars.js
docs/src/pages/components/avatars/IconAvatars.tsx
docs/src/pages/components/avatars/ImageAvatars.js
docs/src/pages/components/avatars/ImageAvatars.tsx
docs/src/pages/components/avatars/LetterAvatars.js
docs/src/pages/components/avatars/LetterAvatars.tsx
docs/src/pages/components/avatars/SizeAvatars.js
docs/src/pages/components/avatars/SizeAvatars.tsx
docs/src/pages/components/avatars/VariantAvatars.js
docs/src/pages/components/avatars/VariantAvatars.tsx

The following demos of the Avatar component were migrated:

[docs] Migrate Avatar demos to emotion

---

babel.config.js
benchmark/browser/README.md
benchmark/browser/webpack.config.js

My assumption that `mode: 'production'` sets `NODE_ENV` to `'production'` in `babel-loader` was wrong. We didn't actually use the babel aliases at all an instead reliead on webpack `resolve.alias`.
But we do want to run in production.
Test Plan:
- run: https://dev.azure.com/mui-org/Material-UI/_build/results?buildId=25140&view=logs&j=9ef21fd1-5d60-5fa4-f8b2-6dc79e173863&t=9ef21fd1-5d60-5fa4-f8b2-6dc79e173863
- changed results: [`26e85fa` (#25402)](https://github.com/mui-org/material-ui/pull/25402/commits/26e85fa314850f22bd0a4df95d07919c61264f70)
- run: https://dev.azure.com/mui-org/Material-UI/_build/results?buildId=25142&view=logs&j=9ef21fd1-5d60-5fa4-f8b2-6dc79e173863
- changed results: [`b874ba8` (#25402)](https://github.com/mui-org/material-ui/pull/25402/commits/b874ba8dfcf7487f8ced28f …

[benchmark] Set intended environment

---

babel.config.js
test/utils/mochaHooks.test.js

Generally we want to test as similar as possible to production environments to make debugging easier. I moved some babel plugins into the default plugins to make testing more similar to prod. I don't think we've ever had a problem but let's be safe.
`date-mui-test` will ultimately be removed as well. Though it's used fairly often in pickers so I want to take a gradual approach or rather do it while refactoring the pickers.

[test] Transpile more similar to prod bundle

---

azure-pipelines.yml
test/utils/initMatchers.test.js

Requires https://github.com/mui-org/material-ui/pull/25402
Missed some in https://github.com/mui-org/material-ui/pull/25306

[core] Bump missed node versions

---

docs/src/pages/components/radio-buttons/ColorRadioButtons.js
docs/src/pages/components/radio-buttons/ColorRadioButtons.tsx
docs/src/pages/components/radio-buttons/ControlledRadioButtonsGroup.js
docs/src/pages/components/radio-buttons/ControlledRadioButtonsGroup.tsx
docs/src/pages/components/radio-buttons/CustomizedRadios.js
docs/src/pages/components/radio-buttons/CustomizedRadios.tsx
docs/src/pages/components/radio-buttons/ErrorRadios.js
docs/src/pages/components/radio-buttons/ErrorRadios.tsx
docs/src/pages/components/radio-buttons/FormControlLabelPlacement.js
docs/src/pages/components/radio-buttons/FormControlLabelPlacement.tsx
docs/src/pages/components/radio-buttons/RadioButtons.js
docs/src/pages/components/radio-buttons/RadioButtons.tsx
docs/src/pages/components/radio-buttons/RadioButtonsGroup.tsx
docs/src/pages/components/radio-buttons/RowRadioButtonsGroup.js
docs/src/pages/components/radio-buttons/RowRadioButtonsGroup.tsx
docs/src/pages/components/radio-buttons/SizeRadioButtons.js
docs/src/pages/components/radio-buttons/SizeRadioButtons.tsx
docs/src/pages/components/radio-buttons/UseRadioGroup.js
docs/src/pages/components/radio-buttons/UseRadioGroup.tsx
docs/src/pages/components/radio-buttons/radio-buttons.md

The following demos of the Radio component were migrated:

[docs] Migrate Radio demos to emotion

---

docs/src/pages/components/checkboxes/CheckboxLabels.js
docs/src/pages/components/checkboxes/CheckboxLabels.tsx
docs/src/pages/components/checkboxes/Checkboxes.js
docs/src/pages/components/checkboxes/Checkboxes.tsx
docs/src/pages/components/checkboxes/CheckboxesGroup.js
docs/src/pages/components/checkboxes/CheckboxesGroup.tsx
docs/src/pages/components/checkboxes/ColorCheckboxes.js
docs/src/pages/components/checkboxes/ColorCheckboxes.tsx
docs/src/pages/components/checkboxes/ControlledCheckbox.js
docs/src/pages/components/checkboxes/ControlledCheckbox.tsx
docs/src/pages/components/checkboxes/CustomizedCheckbox.js
docs/src/pages/components/checkboxes/CustomizedCheckbox.tsx
docs/src/pages/components/checkboxes/FormControlLabelPosition.js
docs/src/pages/components/checkboxes/FormControlLabelPosition.tsx
docs/src/pages/components/checkboxes/IconCheckboxes.js
docs/src/pages/components/checkboxes/IconCheckboxes.tsx
docs/src/pages/components/checkboxes/IndeterminateCheckbox.js
docs/src/pages/components/checkboxes/IndeterminateCheckbox.tsx
docs/src/pages/components/checkboxes/SizeCheckboxes.js
docs/src/pages/components/checkboxes/SizeCheckboxes.tsx
docs/src/pages/components/checkboxes/checkboxes.md

The following demos of the Checkbox component were migrated:

[docs] Migrate Checkbox demos to emotion

---

docs/src/pages/components/autocomplete/CustomizedHook.js
docs/src/pages/components/autocomplete/CustomizedHook.tsx
packages/material-ui/src/useAutocomplete/useAutocomplete.js
packages/material-ui/src/useAutocomplete/useAutocomplete.test.js

This fixes a problem that seems to occur if a state change for a component causes React to re-render the component, removing an input ref for which the autocomplete attempts to alter focus. In that case, there is a null no-method error for one of these two lines.
JS is not my forte, but the solution in the linked issue works, and requires less wrestling with contingent order of operations. Perhaps there's a way to guarantee this hook has access to a current inputRef, but is anything truly lost by not highlighting something that no longer exists?
Fix #25273
Verifies inputRef.current is non-null before modifying its attributes

[Autocomplete] Warn when the input didn't resolve in time

---

packages/material-ui/src/TableRow/TableRow.js

Use the same hover UI implementation between Table and DataTable. The latter seems to do it better https://material.io/design/interaction/states.html#selected.

[Table] Consistency with DataTable

---

packages/material-ui/src/TablePagination/TablePagination.js
packages/material-ui/src/TablePagination/TablePagination.test.js

The `Select` control which appears after `Rows per page:` shows the current amount of rows per page (value, for example `10`).
When clicking on the value, a list with all of the possible options appears (option, for example `5`, `10`, `20`, etc.).
Previously, both the value and the options each had their text as the key.
This resulted in duplicated key usage, as the value `10` with key `10` has the same key as the option `10` with key `10`.
By prefixing the value with `value-` and the option with `option-`, the keys are guaranteed to be unique.

[Table] Fix duplicated keys in TablePagination rows per page

---

packages/material-ui/src/AppBar/AppBar.d.ts
packages/material-ui/src/AppBar/AppBar.js
packages/material-ui/src/Paper/Paper.d.ts
packages/material-ui/src/Paper/Paper.spec.tsx

Looks like we don't need to use `component` prop directly anymore, since `OverridableComponent` is used in this pull request: https://github.com/mui-org/material-ui/pull/25059.
Otherwise, typescript `No overload matches this call` error occurs. Here's [codesandbox](https://codesandbox.io/s/thirsty-yonath-wdpox?file=/src/App.tsx:68-160) live example.

[Paper] Fix component prop type error

---

docs/pages/api-docs/step-label.json
docs/translations/api-docs/step-label/step-label.json
packages/material-ui/src/Step/Step.test.js
packages/material-ui/src/StepButton/StepButton.test.js
packages/material-ui/src/StepLabel/StepLabel.d.ts
packages/material-ui/src/StepLabel/StepLabel.js
packages/material-ui/src/StepLabel/StepLabel.test.js
packages/material-ui/src/StepLabel/index.d.ts
packages/material-ui/src/StepLabel/index.js
packages/material-ui/src/StepLabel/stepLabelClasses.d.ts
packages/material-ui/src/StepLabel/stepLabelClasses.js

[Stepper] Migrate StepLabel to emotion

---

docs/translations/api-docs/tooltip/tooltip.json
packages/material-ui/src/Tooltip/Tooltip.d.ts
packages/material-ui/src/Tooltip/Tooltip.js

Old comment said that it disables `focus` events when in fact it disables `focus-visible` events.
Closes #25283

[Tooltip] Make `disableFocusListener` prop comment clearer

---

packages/material-ui-lab/src/DateRangePicker/DateRangePicker.tsx
packages/material-ui-lab/src/DateRangePicker/makeDateRangePicker.tsx
packages/material-ui-lab/src/DesktopDateRangePicker/DesktopDateRangePicker.tsx
packages/material-ui-lab/src/MobileDateRangePicker/MobileDateRangePicker.tsx
packages/material-ui-lab/src/StaticDateRangePicker/StaticDateRangePicker.tsx

When we create a module we want to be able to move the implementation as much around as possible. Making a piece of code part of the public API goes against that. So if nobody needs a piece of code, keep it internally. **We** don't know if an abstraction is "correct" when writing a piece of code.

[internal][pickers] Follow "private by default" in makeDateRangePicker

---

packages/material-ui-utils/src/useForkRef.d.ts
packages/material-ui-utils/src/useForkRef.ts

We handle `useForkRef(null, null)` at runtime but rejected it in the types.

[utils] Fix useForkRef typings rejecting nullish

---

docs/scripts/buildApi.ts
scripts/generateProptypes.ts

`yarn proptypes --verbose` is invalid.
https://github.com/mui-org/material-ui/pull/25315 was incomplete since I didn't consider that the result is put into a separate box.
Simplified `yarn proptypes` along the way. The existing separation into fail-pass is sufficient for similar scripts.

[core] Fix allSettled usage

---

babel.config.js
framer/Material-UI.framerfx/package.json
packages/material-ui-docs/package.json
packages/material-ui-icons/package.json
packages/material-ui-lab/package.json
packages/material-ui-styled-engine/package.json
packages/material-ui-styles/package.json
packages/material-ui-system/package.json
packages/material-ui-unstyled/package.json
packages/material-ui-utils/package.json
packages/material-ui/package.json
yarn.lock

Official support for React 16 is discontinued.
Note that for now you can still use the library with React ^16.14.0.
This changes simplifies development for us a lot since we no longer have to consider certain behavior for two versions. This became especially problematic for event behavior when using the DOM.
Bundle size changes are expected since we're using the new jsx runtime.
Follow-up to https://github.com/mui-org/material-ui/pull/25416

[core] Drop support for React 16

---

packages/material-ui-lab/src/DayPicker/PickersCalendar.tsx
packages/material-ui-lab/src/DayPicker/PickersCalendarHeader.tsx
packages/material-ui-lab/src/DayPicker/PickersFadeTransitionGroup.tsx
packages/material-ui-lab/src/DayPicker/PickersSlideTransition.tsx
packages/material-ui-lab/src/DayPicker/useCalendarState.tsx
packages/material-ui-lab/src/MonthPicker/MonthPicker.tsx
packages/material-ui-lab/src/PickersDay/PickersDay.tsx
packages/material-ui-lab/src/YearPicker/PickersYear.tsx
packages/material-ui-lab/src/YearPicker/YearPicker.tsx
packages/material-ui-lab/src/internal/pickers/Picker/Picker.tsx
packages/material-ui-lab/src/internal/pickers/Picker/SharedPickerProps.tsx
packages/material-ui-lab/src/internal/pickers/PureDateInput.tsx
packages/material-ui-lab/src/internal/pickers/date-utils.ts
packages/material-ui-lab/src/internal/pickers/hooks/useMaskedInput.tsx
packages/material-ui-lab/src/internal/pickers/hooks/usePickerState.ts
packages/material-ui-lab/src/internal/pickers/hooks/useViews.tsx
packages/material-ui-lab/src/internal/pickers/typings/BasePicker.tsx
packages/material-ui-lab/src/internal/pickers/wrappers/DesktopTooltipWrapper.tsx
packages/material-ui-lab/src/internal/pickers/wrappers/Wrapper.tsx
packages/material-ui-lab/src/internal/pickers/wrappers/WrapperProps.ts

Properties are sorted ascending, case insensitive unless they "obviously" belong together. Then we sort them in the order that makes "sense" e.g. `minDate < maxDate` (sorting numerically) or `disablePast < disableFuture` (sorting temporally).
This should help find a specific property in an interface.

[pickers][internal] Sort properties

---

packages/material-ui/src/Tabs/Tabs.js
packages/material-ui/src/Tabs/Tabs.test.js

- [ x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui-org/material-ui/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).
close: #25314

[Tabs] Don't animate scroll on first render

---

docs/pages/_document.js
docs/src/pages/components/icons/CreateSvgIcon.js
docs/src/pages/components/icons/CreateSvgIcon.tsx
docs/src/pages/components/icons/FontAwesomeIcon.js
docs/src/pages/components/icons/FontAwesomeIcon.tsx
docs/src/pages/components/icons/FontAwesomeIconSize.js
docs/src/pages/components/icons/FontAwesomeIconSize.tsx
docs/src/pages/components/icons/FontAwesomeSvgIconDemo.js
docs/src/pages/components/icons/FontAwesomeSvgIconDemo.tsx
docs/src/pages/components/icons/Icons.js
docs/src/pages/components/icons/Icons.tsx
docs/src/pages/components/icons/SvgIconsColor.js
docs/src/pages/components/icons/SvgIconsColor.tsx
docs/src/pages/components/icons/SvgIconsSize.js
docs/src/pages/components/icons/SvgIconsSize.tsx
docs/src/pages/components/icons/SvgMaterialIcons.js
docs/src/pages/components/icons/SvgMaterialIcons.tsx
docs/src/pages/components/icons/icons.md

The following demos of the Icons component were migrated:

[docs] Migrate Icons demos to emotion

---

test/e2e/index.test.ts

Fixes https://app.circleci.com/pipelines/github/mui-org/material-ui/39638/workflows/d07cf743-eb36-4a71-b6a3-74400199ac2c/jobs/234518
We start server and runner concurrently but we didn't actually wait on the server. The regression suite did not have problems with this. Probably because starting the headful browser was enough time for the server to start.

[test] Wait on e2e server to start before starting runner

---

.eslintrc.js
packages/eslint-plugin-material-ui/src/index.js
packages/eslint-plugin-material-ui/src/rules/mui-name-matches-component-name.js
packages/eslint-plugin-material-ui/src/rules/mui-name-matches-component-name.test.js
packages/material-ui-lab/src/DatePicker/DatePicker.tsx
packages/material-ui-lab/src/DesktopDateTimePicker/DesktopDateTimePicker.tsx
packages/material-ui-lab/src/StaticDatePicker/StaticDatePicker.tsx
packages/material-ui-lab/src/StaticDateRangePicker/StaticDateRangePicker.tsx
packages/material-ui/src/styles/useThemeProps.spec.ts

The name in the theme for setting default props for the `StaticDateRangePicker` is now `MuiStaticDateRangePicker` (was `MuiPickersDateRangePicker`).
Added a lint rule to guard against future mistakes. This also makes sure that their display name (if not manually overridden) is consistent.
Part of the changes are cleaning up after https://github.com/mui-org/material-ui/pull/25172

[StaticDateRangePicker] Fix inconsistent name for theme props

---

docs/src/pages/components/stack/DividerStack.js
docs/src/pages/components/stack/DividerStack.tsx

**Before**
**After**
The fix is documented in https://next.material-ui.com/components/dividers/#vertical-divider.

[docs] Fix Stack divider demo

---

docs/src/pages/components/transitions/SimpleCollapse.js
docs/src/pages/components/transitions/SimpleCollapse.tsx
docs/src/pages/components/transitions/SimpleFade.js
docs/src/pages/components/transitions/SimpleFade.tsx
docs/src/pages/components/transitions/SimpleGrow.js
docs/src/pages/components/transitions/SimpleGrow.tsx
docs/src/pages/components/transitions/SimpleSlide.js
docs/src/pages/components/transitions/SimpleSlide.tsx
docs/src/pages/components/transitions/SimpleZoom.js
docs/src/pages/components/transitions/SimpleZoom.tsx

The following demos of the Transitions components were migrated:

[docs] Migrate Transitions demos to emotion

---

docs/src/pages/getting-started/installation/installation.md
docs/src/pages/getting-started/supported-platforms/supported-platforms.md
docs/src/pages/guides/migration-v4/migration-v4.md

I forgot about it during the review of #25464. It went back to me this afternoon, for some reasons, in the 🏊‍♂️ 🤷‍♂️.

[docs] Cover change of React support

---

docs/src/pages/components/date-picker/CustomDay.js
docs/src/pages/components/date-picker/CustomDay.tsx
packages/material-ui-lab/src/DateRangePicker/DateRangePicker.tsx
packages/material-ui-lab/src/DateRangePicker/DateRangePickerViewDesktop.tsx
packages/material-ui-lab/src/DayPicker/PickersCalendar.tsx
packages/material-ui-lab/src/DesktopDateRangePicker/DesktopDateRangePicker.tsx
packages/material-ui-lab/src/MobileDatePicker/MobileDatePicker.test.tsx
packages/material-ui-lab/src/MobileDateRangePicker/MobileDateRangePicker.tsx
packages/material-ui-lab/src/StaticDateRangePicker/StaticDateRangePicker.tsx

Fixes https://github.com/mui-org/material-ui/issues/24865
I followed the advice in the issue - will verify on my work macbook tomorrow (tests are failing on windows for plethora of reasons) if the issue is really fixed on a rollup build.

[DateRangePicker] Fix props naming in DatePicker components

---

docs/src/pages/components/no-ssr/FrameDeferring.js
docs/src/pages/components/no-ssr/FrameDeferring.tsx
docs/src/pages/components/no-ssr/SimpleNoSsr.js
docs/src/pages/components/no-ssr/SimpleNoSsr.tsx
docs/src/pages/components/no-ssr/no-ssr.md

[docs] Migrate NoSSR demos to emotion

---

docs/src/pages/components/portal/SimplePortal.js
docs/src/pages/components/portal/SimplePortal.tsx

[docs] Migrate Portal demos to emotion

---

docs/pages/api-docs/grid.json
docs/pages/api-docs/stack.json
docs/src/pages/components/grid/SpacingGrid.js
docs/src/pages/components/grid/SpacingGrid.tsx
docs/src/pages/components/grid/grid.md
docs/src/pages/components/stack/InteractiveStack.js
docs/src/pages/components/stack/InteractiveStack.tsx
docs/src/pages/components/stack/stack.md
packages/material-ui/src/Grid/Grid.d.ts
packages/material-ui/src/Grid/Grid.js
packages/material-ui/src/Grid/Grid.test.js
packages/material-ui/src/Stack/Stack.d.ts
packages/material-ui/src/Stack/Stack.js

Resolves #16481.
* I was originally planning on using something like:
``` javascript
expect(() => {
render(<Grid container spacing={1.5} />);
}).not.toWarnDev();
```
as a regression test, but I couldn't get it to fail with the original code. When running the test I would see `Warning: Failed prop type: Invalid prop spacing of value 1.5 supplied to ForwardRef(Grid), expected one of [0,1,2,3,4,5,6,7,8,9,10].` printed to the console, but the test would pass. I don't understand why and would be curious for others' thoughts.
* I wasn't sure how much to test. I tested that the class was added and that the child has 1.5 * 8px padding in the appropriate places. I could see myself basically cloning the gutter test for 1.5 or not adding this test at all. Up to you. The test would have passed before …

[Grid] Support decimal spacing

---

packages/material-ui/src/SpeedDial/SpeedDial.js
packages/material-ui/src/SpeedDial/SpeedDial.test.js

[SpeedDial] Call focus on escape

---

docs/pages/api-docs/step-button.json
docs/translations/api-docs/step-button/step-button.json
packages/material-ui/src/Step/Step.test.js
packages/material-ui/src/StepButton/StepButton.d.ts
packages/material-ui/src/StepButton/StepButton.js
packages/material-ui/src/StepButton/StepButton.test.js
packages/material-ui/src/StepButton/index.d.ts
packages/material-ui/src/StepButton/index.js
packages/material-ui/src/StepButton/stepButtonClasses.d.ts
packages/material-ui/src/StepButton/stepButtonClasses.js

[Stepper] Migrate StepButton to emotion

---

docs/src/pages/components/autocomplete/Asynchronous.js
docs/src/pages/components/autocomplete/Asynchronous.tsx

[Autocomplete] Fix Async demo in docs

---

docs/src/pages/components/lists/PinnedSubheaderList.js
docs/src/pages/components/lists/PinnedSubheaderList.tsx
docs/src/pages/components/lists/lists.md
docs/src/pages/components/tables/tables.md
packages/material-ui/src/ListSubheader/ListSubheader.js

- Add check for breakpoint use sticky background from paper
- Filter out onClick
Related to #18200

[List] Remove background inheritance of ListSubheader

---

docs/src/modules/branding/BrandingRoot.tsx
docs/src/pages/customization/palette/palette.md
docs/src/pages/customization/theming/CustomStyles.js
docs/src/pages/customization/theming/CustomStyles.tsx
docs/src/pages/customization/theming/theming.md
docs/src/pages/guides/typescript/typescript.md

The current theme customization documentation seems incomplete and does not give enough information to users on properly customizing the theme and other props within it. Especially the module augmentation piece doesn't specify specific module names and caused a lot of frustration for me personally (and there might be others who might be feeling the same pain). I have provided a more complete example, with specific extension points as sample for users to theme customization.

[docs] Improve coverage of TypeScript theme augmentation

---

packages/material-ui/src/Avatar/Avatar.js
packages/material-ui/src/Avatar/Avatar.test.js

This PR removes the circle variant deprecation warning, as suggested by @oliviertassinari in https://github.com/mui-org/material-ui/issues/24864.

[Avatar] Remove circle variant deprecation

---

docs/src/modules/components/MarkdownElement.js

Fixes #25550.
Styles taken from GitHub "Default Dark" theme.
Preview: https://deploy-preview-25551--material-ui.netlify.app/components/trap-focus/

[docs] Fix <kbd> style in dark mode

---

docs/src/pages/components/menus/CustomizedMenus.js
docs/src/pages/components/menus/CustomizedMenus.tsx
docs/src/pages/components/menus/SimpleListMenu.js
docs/src/pages/components/menus/SimpleListMenu.tsx

[docs] Migrate Menu demos to emotion

---

docs/pages/branding/about.tsx
docs/pages/branding/pricing.tsx
docs/src/modules/branding/BrandingRoot.tsx
docs/src/modules/branding/UnderlinedText.tsx

The bug I went after:
Adding a max-width creates more constraints and reduces the intensity of the layout change once the font loads.

[website] Fix layout shift and improve purpose

---

docs/src/pages/components/snackbars/CustomizedSnackbars.tsx
docs/src/pages/premium-themes/onepirate/modules/views/AppAppBar.js
packages/material-ui-lab/src/internal/pickers/PickersPopper.tsx
packages/material-ui/src/AppBar/AppBar.d.ts
packages/material-ui/src/AppBar/AppBar.js
packages/material-ui/src/AppBar/AppBar.spec.tsx
packages/material-ui/src/Paper/Paper.d.ts
packages/material-ui/test/typescript/components.spec.tsx

Added the OverridableComponent to AppBar.
Can somebody help me to understand why proptypes generator insistently removes `component` prop and `@default` annotation from js file? It's not easy to understand how `typescript-to-proptypes` and `generateProptypes.ts` works, so I gave up.

[AppBar] Fix type support of overridable component

---

packages/material-ui/src/Select/Select.test.js
packages/material-ui/src/Select/SelectInput.js

A follow-up on #25532. How the solution work is explained in https://github.com/mui-org/material-ui/pull/25532#issuecomment-808922387.
Closes #18200 (duplicates: #18390, #22274)
A simplified reproduction:
1. Open https://codesandbox.io/s/basicselect-material-demo-forked-h08b1
2. Open the select
3. Click the divider
4. 💥 warning in the console
cc @tanmoyopenroot

[Select] Fix selection of non-options

---

docs/src/pages/customization/how-to-customize/DynamicCSS.tsx
docs/src/pages/customization/how-to-customize/how-to-customize.md

Fixes https://github.com/mui-org/material-ui/issues/24862
Adds a section on how the props of the styled component created with `experimentalStyled()` can be typed.

[docs] Add note for typescript on the styled() customization guide

---

docs/src/pages/guides/right-to-left/right-to-left.md

Updating the right-to-left language guide to reflect that adding `dir="rtl"` to the `<body>` element is only one solution for configuring RTL for native components. You can also wrap them in a lower-level div, as long as it is the parent of all your UI components. This is helpful because `<body>` is often defined as a template outside the scope of a React app, whereas a `<div>` that wraps the entire application can be easily controlled from an application component like a language switching toggle.

[docs] Provide an alternative to right-to-left

---

docs/src/modules/components/AppNavDrawer.js

Fix #25560
Preview: https://deploy-preview-25619--material-ui.netlify.app/components/alert/

[docs] Fix side nav scroll position

---

docs/pages/api-docs/mobile-stepper.json
docs/translations/api-docs/mobile-stepper/mobile-stepper.json
packages/material-ui/src/MobileStepper/MobileStepper.d.ts
packages/material-ui/src/MobileStepper/MobileStepper.js
packages/material-ui/src/MobileStepper/MobileStepper.test.js
packages/material-ui/src/MobileStepper/index.d.ts
packages/material-ui/src/MobileStepper/index.js
packages/material-ui/src/MobileStepper/mobileStepperClasses.d.ts
packages/material-ui/src/MobileStepper/mobileStepperClasses.js

[Stepper] Migrate MobileStepper to emotion

---

docs/src/pages/components/checkboxes/checkboxes.md
docs/src/pages/components/switches/switches.md

the text said `value` but the actual prop is `checked` and the example uses `checked`.  if this is incorrect, then we should update the example code instead to use `value` instead of what it uses now, `checked`.

[docs] Fix typo in switches.md doc

---

docs/src/pages/components/popover/AnchorPlayground.js
docs/src/pages/components/popover/BasicPopover.js
docs/src/pages/components/popover/BasicPopover.tsx
docs/src/pages/components/popover/MouseOverPopover.js
docs/src/pages/components/popover/MouseOverPopover.tsx
docs/src/pages/components/popover/PopoverPopupState.js
docs/src/pages/components/popover/PopoverPopupState.tsx
docs/src/pages/components/popover/popover.md

[docs] Migrate Popover demos to emotion

---

packages/material-ui-codemod/README.md

This MR seeks to add documentation to mui-codemod's readme to add support for typescript projects. Currently the provided examples only work on javascript projects
Closes #23610

[docs] Cover TypeScript commands in codemod readme

---

packages/material-ui-styles/src/getStylesCreator/getStylesCreator.js
packages/material-ui-styles/src/makeStyles/makeStyles.test.js

[styles] Outdated warning message

---

packages/material-ui/src/InputBase/InputBase.js

[InputBase] Fix autofill typo

---

docs/pages/api-docs/tab-panel.json
docs/translations/api-docs/tab-panel/tab-panel.json
packages/material-ui-lab/src/TabPanel/TabPanel.d.ts
packages/material-ui-lab/src/TabPanel/TabPanel.js
packages/material-ui-lab/src/TabPanel/TabPanel.test.tsx
packages/material-ui-lab/src/TabPanel/index.js
packages/material-ui-lab/src/TabPanel/tabPanelClasses.d.ts
packages/material-ui-lab/src/TabPanel/tabPanelClasses.js

Because TabPanel is a lab component, I have imported `experimentalStyled` and `useThemeProps` as follows:
```
import {
experimentalStyled,
unstable_useThemeProps as useThemeProps,
} from '@material-ui/core/styles';
```
Let me know if this is the correct way.

[TabPanel] Migrate to emotion

---

docs/pages/api-docs/timeline-separator.json
docs/translations/api-docs/timeline-separator/timeline-separator.json
packages/material-ui-lab/src/TimelineSeparator/TimelineSeparator.d.ts
packages/material-ui-lab/src/TimelineSeparator/TimelineSeparator.js
packages/material-ui-lab/src/TimelineSeparator/TimelineSeparator.test.js
packages/material-ui-lab/src/TimelineSeparator/index.d.ts
packages/material-ui-lab/src/TimelineSeparator/index.js
packages/material-ui-lab/src/TimelineSeparator/timelineSeparatorClasses.d.ts
packages/material-ui-lab/src/TimelineSeparator/timelineSeparatorClasses.js

[Timeline] Migrate TimelineSeparator to emotion

---

package.json
yarn.lock

Forgot to update in https://github.com/mui-org/material-ui/pull/25416

[core] Ensure react-is uses v17

---

packages/material-ui-unstyled/package.json

This is a continuation of #23805 (same solution). I had to remove this file in order to make [v5.0.0-alpha.29](https://github.com/mui-org/material-ui/releases/tag/) happen. In HEAD `yarn release:build` is failing for me with:
```
@material-ui/unstyled: buildTypes
@material-ui/unstyled: Builds a project with a fix for
@material-ui/unstyled: https://github.com/microsoft/TypeScript/issues/39117
@material-ui/unstyled: Options:
@material-ui/unstyled:   --help  Show help                                                    [boolean]
@material-ui/unstyled: Error: Unable to find declaration files in '/Users/oliviertassinari/material-ui/packages/material-ui-unstyled/build'
@material-ui/unstyled:     at Object.main [as handler] (/Users/oliviertassinari/material-ui/scripts/buildTypes.js:49:11) …
```

[core] Fix build step for unstyled package

---

packages/material-ui-lab/src/DatePicker/DatePicker.spec.tsx
packages/material-ui-lab/tsconfig.json

We probably excluded the spec files during https://github.com/mui-org/material-ui/pull/22692 to unblock. Should've left a TODO or at least an explainer.

[test] Test types of .spec lab files

---

packages/material-ui-lab/src/TabPanel/TabPanel.d.ts
packages/material-ui-lab/src/TabPanel/TabPanel.test.tsx
packages/material-ui-lab/src/TabPanel/index.d.ts
packages/material-ui-lab/src/TimelineConnector/TimelineConnector.d.ts
packages/material-ui-lab/src/TimelineConnector/TimelineConnector.test.js
packages/material-ui-lab/src/TimelineSeparator/TimelineSeparator.d.ts
packages/material-ui-lab/src/TimelineSeparator/TimelineSeparator.test.js

Corresponds to [comment #25666](https://github.com/mui-org/material-ui/pull/25666#discussion_r610015819) and [comment #25666](https://github.com/mui-org/material-ui/pull/25666#discussion_r610016937)

[test] Use public api in lab

---

docs/src/pages/components/speed-dial/PlaygroundSpeedDial.tsx
packages/material-ui/src/SpeedDialAction/SpeedDialAction.js
packages/material-ui/src/SpeedDialAction/SpeedDialAction.test.js

Fixes https://github.com/mui-org/material-ui/issues/19205

[SpeedDial] Fix broken aria reference issue

---

docs/pages/api-docs/tree-view.json
docs/translations/api-docs/tree-view/tree-view.json
packages/material-ui-lab/src/TreeView/TreeView.d.ts
packages/material-ui-lab/src/TreeView/TreeView.js
packages/material-ui-lab/src/TreeView/TreeView.test.js
packages/material-ui-lab/src/TreeView/index.d.ts
packages/material-ui-lab/src/TreeView/index.js
packages/material-ui-lab/src/TreeView/treeViewClasses.d.ts
packages/material-ui-lab/src/TreeView/treeViewClasses.js

[TreeView] Migrate to emotion

---

packages/material-ui/src/TableSortLabel/TableSortLabel.js

Handle https://github.com/mui-org/material-ui/pull/25638#pullrequestreview-629333833. The main advantage of this change is to make customizations easier.

[Table] Remove legacy fix for JSS

---

docs/scripts/buildApi.ts
package.json

Required for https://github.com/mui-org/material-ui/pull/25679
Initial version just removed `docs/translations/api-docs` in `docs:api`. However, `docs:api` relies on the existence of directories in `docs/translations/api-docs` to determine the merging strategy. We can't just clean `docs/translations/api-docs` for that reason but have to use the difference between the components for which we currently create api-docs and the directories that are existing during that process.

[docs] Ensure old api-docs translations are cleaned

---

packages/material-ui/src/Popover/index.d.ts

[Popover] Add popoverClasses export to type declarations

---

docs/package.json
yarn.lock

Done to ensure the fix implemented in https://github.com/styled-components/stylis-plugin-rtl/pull/21 is pulled in.
~Fixes https://github.com/mui-org/material-ui/issues/24899~

[docs] Bump stylis-plugin-rtl requirement

---

packages/material-ui/src/Autocomplete/Autocomplete.js
test/regressions/fixtures/Autocomplete/StandardAutocomplete.js

I have noticed the issue looking into #25657.
v4 (OK):
https://material-ui.com/components/autocomplete/#playground
HEAD (KO):
https://next.material-ui.com/components/autocomplete/#playground
The visual regression should confirm the fix work (bring us back to v4). Regarding why the regression has happened. It's related to a recent change of the `<input>` `line-height` in the InputBase component to account for fonts with long descended and ascender characters. It's not related to emotion.

[Autocomplete] Fix text field standard visual regression

---

docs/src/modules/components/ThemeContext.js
docs/src/pages/guides/migration-v4/migration-v4.md
packages/material-ui/src/styles/createPalette.js

Closes #24440
Hello, forgive me but I am trying to find the best way to solve this issue. Seems simple enough (just changed the default background to white. But would it also make sense to change the default paper background too? I ended up just following the comment [https://github.com/mui-org/material-ui/issues/24440#issuecomment-761281899](here) to do my part. Please let me know if I can be of more assistance. Thank you.
From looking through the docs, I found this and used it as a reference to assume this would be all that would be needed.

[theme] Change default bgColor to white in light mode

---

packages/material-ui-lab/src/TimePicker/TimePickerToolbar.tsx
packages/material-ui-lab/src/internal/pickers/PickersToolbar.tsx

The time picker toolbar used the calendar icon instead of the clock icon for the button to switch away from the text input view, which was confusing. This replaces the icon on the time picker as well as the aria label to match the actual use of the component.
Steps to reproduce:
Insert a TimePicker
Open TimePicker in mobile mode
Click the pen icon to go to the keyboard edit view
The icon to return to the clock view is a calendar. This is confusing.

[TimePicker] Use clock icon when editing in mobile mode

---

packages/material-ui/src/Rating/Rating.js
test/regressions/fixtures/Rating/FocusVisibleRating.js
test/regressions/index.js
test/regressions/index.test.js

Two recent regressions in https://github.com/mui-org/material-ui/pull/25588/files. The outline is working again:
1. 
2.

[Rating] Fix focus visible regression

---

docs/src/pages/components/autocomplete/autocomplete.md

I have found this working on https://github.com/mui-org/material-ui-x/issues/1403. The docs doesn't match the tests:
https://github.com/mui-org/material-ui/blob/7c3d3bb204e26c8f016f99bf50b070d054123f79/packages/material-ui/src/Autocomplete/Autocomplete.test.js#L2199

[docs] Fix autocommplete disable event value

---

docs/src/pages/components/progress/CircularColor.js
docs/src/pages/components/progress/CircularColor.tsx
docs/src/pages/components/progress/CircularIndeterminate.js
docs/src/pages/components/progress/CircularIndeterminate.tsx
docs/src/pages/components/progress/LinearColor.js
docs/src/pages/components/progress/LinearColor.tsx
docs/src/pages/components/progress/progress.md

A follow-up on #25641 to bring parity in the documentation between circular and linear progress.
Preview: https://deploy-preview-25736--material-ui.netlify.app/components/progress/#circular-color

[docs] Document circular progress inherit

---

packages/material-ui/src/InputAdornment/InputAdornment.js
test/regressions/fixtures/TextField/FilledHiddenLabelInputAdornment.js

Fixes regression from https://github.com/mui-org/material-ui/pull/25279
Previously:
https://codesandbox.io/s/textfieldhiddenlabel-material-demo-forked-hc7mt?file=/demo.js
Now:
https://codesandbox.io/s/textfieldhiddenlabel-material-demo-forked-83oyo?file=/demo.js

[TextField] Fix InputAdornment classes

---

packages/material-ui-lab/src/DateRangePickerDay/DateRangePickerDay.tsx
packages/material-ui-lab/src/themeAugmentation/components.d.ts
packages/material-ui-lab/src/themeAugmentation/overrides.d.ts
packages/material-ui-lab/src/themeAugmentation/props.d.ts

'MuiDateRangePickerDay' key is missing in `overrides.d.ts`, so added one.
Please let me know if this PR need further work. Thanks!

[DateRangePicker] Add DateRangePickerDay to theme augmentation list

---

packages/material-ui/src/Snackbar/Snackbar.js

- [x ] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui-org/material-ui/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).
Fixes #25737
Preview: https://deploy-preview-25739--material-ui.netlify.app/components/snackbars/

[Snackbar] Fix hidden overlay blocking interactions regression

---

packages/material-ui/src/locale/index.ts

We use 開 rather than 开 as 'open' in Traditional Chinese.
In Taiwan we usually use 載入中/讀取中 rather than 加載中. Even though languages do affect each other.

[l10n] zhTW refinement

---

packages/material-ui/src/Autocomplete/Autocomplete.test.js
packages/material-ui/src/ButtonBase/ButtonBase.js
packages/material-ui/src/ButtonBase/ButtonBase.test.js
packages/material-ui/src/ButtonBase/TouchRipple.js
packages/material-ui/src/ButtonBase/TouchRipple.test.js
packages/material-ui/src/Checkbox/Checkbox.test.js
packages/material-ui/src/Chip/Chip.test.js
packages/material-ui/src/Select/Select.test.js
packages/material-ui/src/Select/SelectInput.js
packages/material-ui/src/Slider/Slider.test.js
packages/material-ui/src/SpeedDial/SpeedDial.js
packages/material-ui/src/SwipeableDrawer/SwipeableDrawer.test.js
packages/material-ui/src/Tabs/Tabs.test.js
packages/material-ui/src/Tooltip/Tooltip.js
packages/material-ui/src/internal/SwitchBase.test.js
packages/material-ui/test/integration/PopperChildrenLayout.test.js

[`event.persist()` is a noop in React 17](https://reactjs.org/blog/2020/08/10/react-v17-rc.html#no-event-pooling) so we might as well get rid of it to simplify code.
PR consists of two parts:
1. Removal of event.persist
2. Removal of implicitly persisting event properties in tests
This reduces indirection for which we sometimes added comments, sometimes we didn't. We can skip the comments and use actual code now.
Note that preact doesn't pool events to begin with so this won't break compat.

[core] Don't call noop event.persist()

---

packages/material-ui/src/StepContent/StepContent.js
packages/material-ui/src/StepIcon/StepIcon.js
packages/material-ui/src/StepLabel/StepLabel.js

Non `Root` & `Container` slots should not have `overrideResolver` defined, their overrides can be defined under the root component's style overrides definition.

[core] Remove incorrect overridesResolver usages

---

packages/material-ui/src/Avatar/Avatar.js

onerror and onload may fire before attaching to the events, so it makes sense to attach to them before settings the `image.src`.
this issue can appear specifically with cached images.

[Avatar] Fix onload event not firing when img cached

---

packages/material-ui/src/NativeSelect/NativeSelect.test.js
packages/material-ui/src/NativeSelect/NativeSelectInput.js
packages/material-ui/src/Select/Select.test.js
packages/material-ui/src/Select/SelectInput.js

Follow up after https://github.com/mui-org/material-ui/pull/25777 for the `Select` components

[Select] Fix overrides for slots

---

packages/material-ui/src/Box/Box.js
packages/material-ui/src/Box/Box.test.js

This PR adds the `MuiBox-root` class on the `Box` component to allow customization by selecting all Box instances. More for the motivation can be found here https://github.com/mui-org/material-ui/issues/25759#issuecomment-819503863

[Box] Add utility mui class

---

packages/material-ui-lab/src/CalendarPicker/CalendarPicker.tsx
packages/material-ui-lab/src/CalendarPicker/PickersCalendarHeader.tsx
packages/material-ui-lab/src/CalendarPicker/shared.ts

Follow-up to https://github.com/mui-org/material-ui/pull/25810.
No more mention of `daypicker` in the repo (aside from stale translation files).

[internal][pickers] Rename DayPickerView to CalendarPickerView

---

packages/material-ui/src/NativeSelect/NativeSelect.js
packages/material-ui/src/NativeSelect/NativeSelect.test.js
packages/material-ui/src/Select/Select.js
packages/material-ui/src/Select/Select.test.js

[Select] Fix className overwritten

---

packages/material-ui-lab/src/DesktopDatePicker/DesktopDatePickerKeyboard.test.tsx
packages/material-ui-lab/src/DesktopDateRangePicker/DesktopDateRangePicker.test.tsx
packages/material-ui-lab/src/DesktopDateTimePicker/DesktopDateTimePicker.test.tsx
packages/material-ui-lab/src/DesktopTimePicker/DesktopTimePicker.test.tsx
packages/material-ui-lab/src/internal/pickers/PickersPopper.tsx
packages/material-ui-lab/src/internal/pickers/hooks/useIsLandscape.tsx
packages/material-ui-lab/src/internal/pickers/hooks/useKeyDown.ts

Affects desktop variants of the pickers. Should not cause any change in behavior.
Main goal is to trim down picker-specific utils.

[Pickers] Use passive effect to attach close-on-escape listener

---

docs/pages/api-docs/date-picker.json
docs/pages/api-docs/date-time-picker.json
docs/pages/api-docs/desktop-date-picker.json
docs/pages/api-docs/desktop-date-time-picker.json
docs/pages/api-docs/desktop-time-picker.json
docs/pages/api-docs/mobile-date-picker.json
docs/pages/api-docs/mobile-date-time-picker.json
docs/pages/api-docs/mobile-time-picker.json
docs/pages/api-docs/static-date-picker.json
docs/pages/api-docs/static-date-time-picker.json
docs/pages/api-docs/static-time-picker.json
docs/pages/api-docs/time-picker.json
packages/material-ui-lab/src/CalendarPicker/CalendarPicker.tsx
packages/material-ui-lab/src/DatePicker/DatePicker.tsx
packages/material-ui-lab/src/DateTimePicker/DateTimePicker.tsx
packages/material-ui-lab/src/DesktopDatePicker/DesktopDatePicker.tsx
packages/material-ui-lab/src/DesktopDateTimePicker/DesktopDateTimePicker.tsx
packages/material-ui-lab/src/DesktopTimePicker/DesktopTimePicker.tsx
packages/material-ui-lab/src/MobileDatePicker/MobileDatePicker.tsx
packages/material-ui-lab/src/MobileDateTimePicker/MobileDateTimePicker.tsx
packages/material-ui-lab/src/MobileTimePicker/MobileTimePicker.tsx
packages/material-ui-lab/src/StaticDatePicker/StaticDatePicker.tsx
packages/material-ui-lab/src/StaticDateTimePicker/StaticDateTimePicker.tsx
packages/material-ui-lab/src/StaticTimePicker/StaticTimePicker.tsx
packages/material-ui-lab/src/TimePicker/TimePicker.tsx
packages/material-ui-lab/src/internal/pickers/Picker/Picker.tsx
packages/material-ui-lab/src/internal/pickers/Picker/SharedPickerProps.tsx
packages/material-ui-lab/src/internal/pickers/hooks/useViews.tsx
packages/material-ui-lab/src/internal/pickers/typings/BasePicker.tsx

Was only accessible from within `CalendarPickerProps` but not the actual component. In this state it only complicates the types and is in many scenarios unsound anyway.
Removed the internal `WithViewProps` as well. Just more indirection that doesn't accomplish anything. It even resulted in too wide types documentation.

[Pickers] Remove `TView` generic in CalendarPicker

---

docs/pages/api-docs/timeline-opposite-content.json
docs/translations/api-docs/timeline-opposite-content/timeline-opposite-content.json
packages/material-ui-lab/src/TimelineOppositeContent/TimelineOppositeContent.d.ts
packages/material-ui-lab/src/TimelineOppositeContent/TimelineOppositeContent.js
packages/material-ui-lab/src/TimelineOppositeContent/TimelineOppositeContent.test.js
packages/material-ui-lab/src/TimelineOppositeContent/TimelineOppositeContentClasses.d.ts
packages/material-ui-lab/src/TimelineOppositeContent/index.d.ts
packages/material-ui-lab/src/TimelineOppositeContent/index.js
packages/material-ui-lab/src/TimelineOppositeContent/timelineOppositeContentClasses.js

[Timeline] Migrate TimelineOppositeContent to emotion

---

packages/material-ui-lab/src/TimelineDot/TimelineDot.d.ts
packages/material-ui-types/index.d.ts
packages/material-ui/src/Alert/Alert.d.ts
packages/material-ui/src/AppBar/AppBar.d.ts
packages/material-ui/src/Avatar/Avatar.d.ts
packages/material-ui/src/AvatarGroup/AvatarGroup.d.ts
packages/material-ui/src/Badge/Badge.d.ts
packages/material-ui/src/Button/Button.d.ts
packages/material-ui/src/ButtonGroup/ButtonGroup.d.ts
packages/material-ui/src/Chip/Chip.d.ts
packages/material-ui/src/CircularProgress/CircularProgress.d.ts
packages/material-ui/src/Divider/Divider.d.ts
packages/material-ui/src/Fab/Fab.d.ts
packages/material-ui/src/FormControl/FormControl.d.ts
packages/material-ui/src/ImageList/ImageList.d.ts
packages/material-ui/src/InputBase/InputBase.d.ts
packages/material-ui/src/LinearProgress/LinearProgress.d.ts
packages/material-ui/src/Pagination/Pagination.d.ts
packages/material-ui/src/PaginationItem/PaginationItem.d.ts
packages/material-ui/src/Paper/Paper.d.ts
packages/material-ui/src/Skeleton/Skeleton.d.ts
packages/material-ui/src/TextField/TextField.d.ts
packages/material-ui/src/Toolbar/Toolbar.d.ts
packages/material-ui/src/Typography/Typography.d.ts
packages/material-ui/src/styles/createBreakpoints.d.ts

- [types] Reduce boilerplate with the OverridableStringUnion helper
```diff
import { OverridableStringUnion } from '@material-ui/types';
interface VariantOverrides {}
-type Variant = OverridableStringUnion<Record<'foo' | 'bar', true>, VariantOverrides>
+type Variant = OverridableStringUnion<'foo' | 'bar', VariantOverrides>
```
The intent is to reduce the number of exported types as well as improving the abstraction (easier to read).

[core] Remove unused public types

---

docs/pages/api-docs/unstable-trap-focus.json
docs/src/pages/components/trap-focus/BasicTrapFocus.js
docs/src/pages/components/trap-focus/BasicTrapFocus.tsx
docs/src/pages/components/trap-focus/DisableEnforceFocus.js
docs/src/pages/components/trap-focus/DisableEnforceFocus.tsx
docs/src/pages/components/trap-focus/LazyTrapFocus.js
docs/src/pages/components/trap-focus/LazyTrapFocus.tsx
docs/src/pages/components/trap-focus/PortalTrapFocus.js
docs/src/pages/components/trap-focus/PortalTrapFocus.tsx
docs/src/pages/components/trap-focus/trap-focus.md
docs/translations/api-docs/unstable-trap-focus/unstable-trap-focus.json
packages/material-ui-unstyled/src/ModalUnstyled/ModalUnstyled.js
packages/material-ui-unstyled/src/Unstable_TrapFocus/Unstable_TrapFocus.d.ts
packages/material-ui-unstyled/src/Unstable_TrapFocus/Unstable_TrapFocus.js
packages/material-ui-unstyled/src/Unstable_TrapFocus/Unstable_TrapFocus.test.js

Closes #25528
Preview: https://deploy-preview-25784--material-ui.netlify.app/components/trap-focus/

[TrapFocus] Make isEnabled and getDoc optional

---

docs/pages/api-docs/popover.json
docs/src/modules/components/DemoToolbar.js
docs/src/pages/components/menus/CustomizedMenus.js
docs/src/pages/components/menus/CustomizedMenus.tsx
docs/src/pages/components/menus/PositionedMenu.js
docs/src/pages/components/menus/PositionedMenu.tsx
docs/src/pages/components/menus/menus.md
docs/src/pages/guides/migration-v4/migration-v4.md
docs/translations/api-docs/menu/menu.json
docs/translations/api-docs/popover/popover.json
packages/material-ui/src/Menu/Menu.d.ts
packages/material-ui/src/Menu/Menu.js
packages/material-ui/src/Menu/Menu.test.js
packages/material-ui/src/Popover/Popover.d.ts
packages/material-ui/src/Popover/Popover.js
packages/material-ui/src/Popover/Popover.test.js

- [Popover] Remove the `getContentAnchorEl` prop to simplify the positioning logic.
- [Menu] The `selectedMenu` variant will not vertically align the selected item with the anchor anymore.
---
Part of #20012.

[Popover] Remove getContentAnchorEl prop

---

docs/src/modules/components/AppNavDrawerItem.js

The usage of the `paddingInlineStart` CSS property is [flooding](https://validator.w3.org/nu/?doc=https%3A%2F%2Fnext.material-ui.com%2Fcomponents%2Faccordion%2F) all the other errors, #25669 was hard to spot. This the only occurrence of a direction-aware CSS property we have in the codebase. The change didn't seem to cost much, it's unclear when validator will solve the root issue. My hope is that it will help us catch other issues on the pages.
I have opened https://github.com/validator/validator/issues/1134 upstream, which is probably the most important part.
---
Edit, this PR now focuses on remove usages of inline-style: https://github.com/mui-org/material-ui/issues/19938#issuecomment-645893048.

[docs] Remove inline-style

---

packages/material-ui/src/Accordion/Accordion.js
packages/material-ui/src/Accordion/Accordion.test.js
packages/material-ui/src/AccordionActions/AccordionActions.js
packages/material-ui/src/AccordionDetails/AccordionDetails.js
packages/material-ui/src/AccordionSummary/AccordionSummary.js
packages/material-ui/src/Alert/Alert.js
packages/material-ui/src/AlertTitle/AlertTitle.js
packages/material-ui/src/AppBar/AppBar.js
packages/material-ui/src/Autocomplete/Autocomplete.js
packages/material-ui/src/Autocomplete/Autocomplete.test.js
packages/material-ui/src/Avatar/Avatar.js
packages/material-ui/src/AvatarGroup/AvatarGroup.js
packages/material-ui/src/AvatarGroup/AvatarGroup.test.js

This PR updates the components starting with `A` to use `overridesResolver` per slot component. (need to somehow batch the changes in few PRs, otherwise the PR would be too big).
I am disabling the `testDeepOverrides` as we no longer support it. In some cases we still need to define the overrides on the root, for example in the `AvatarGroup`, when we are just applying the classes on a component down the tree, which is not created by a `styled()` utility.
---
I've done some preliminary benchmark in https://github.com/mui-org/material-ui/pull/25850 and seems like perf are great with this approach.

[core] Update slot components to use overridesResolver part 1

---

packages/material-ui/src/SpeedDialAction/SpeedDialAction.js
packages/material-ui/src/styles/experimentalStyled.js
packages/material-ui/src/styles/experimentalStyled.test.js

Now that we are adding `overridesResolver` for every slot, we need to not resolve variants for non root slots, unless specified otherwise with the `skipVariantsResolver` option.
The issue surfaced in https://github.com/mui-org/material-ui/pull/25864, see https://www.argos-ci.com/mui-org/material-ui/builds/2358

[styled-engine] Skip variants resolver for non root slots by default

---

packages/material-ui/src/Container/Container.js

Fixes the issues with creating invalid CSS:
```css     
@media (min-width: falsepx) {
.css-2bi4m2-MuiContainer-root {
max-width:undefinedpx;
}
}
```
Issue was spotted here https://validator.w3.org/nu/?doc=https%3A%2F%2Fnext.material-ui.com%2Fcomponents%2Falert%2F%23main-content#interactive

[Container] Fix maxWidth="false" resulting in incorrect css

---

docs/src/modules/components/ApiPage.js
docs/src/modules/utils/parseMarkdown.js

Preview:  
https://deploy-preview-25861--material-ui.netlify.app/components/buttons/
https://deploy-preview-25861--material-ui.netlify.app/api/button/
These were visible on hover but not exposed to the a11y tree. Visible elements should be exposed to the a11y tree.
Used this opportunity to get rid of an empty anchor element which is unneccessary.
Closes https://github.com/mui-org/material-ui/pull/25832
Clicking a header link in nvda:
`next`: "empty"; "clickable heading level 2"
https://github.com/mui-org/material-ui/pull/25861 (this PR): "contained buttons, visited link, heading level 2"; "heading level 2 contained buttons visited link contained buttons"
https://github.com/mui-org/material-ui/pull/25832:  "contained buttons, visited link, heading level 2"; "heading level 2 clickable" …

[docs] Expose heading links in a11y tree

---

packages/material-ui/src/Button/Button.js
packages/material-ui/src/Checkbox/Checkbox.js
packages/material-ui/src/DialogContentText/DialogContentText.js
packages/material-ui/src/Drawer/Drawer.js
packages/material-ui/src/FilledInput/FilledInput.js
packages/material-ui/src/Input/Input.js
packages/material-ui/src/InputLabel/InputLabel.js
packages/material-ui/src/Menu/Menu.js
packages/material-ui/src/MenuItem/MenuItem.js
packages/material-ui/src/OutlinedInput/OutlinedInput.js
packages/material-ui/src/Radio/Radio.js
packages/material-ui/src/styles/experimentalStyled.js

Fixes issue spotted here https://validator.w3.org/nu/?doc=https%3A%2F%2Fnext.material-ui.com%2Fcomponents%2Falert%2F%23main-content#interactive
The `classes` are being blocked for `Root`, but forwarded on other slot. However, on this component the `Docked` slot is used as root, so we need to block them.

[Drawer] Fix classes forwarded to DOM node for docked drawer

---

docs/pages/api-docs/timeline.json
docs/translations/api-docs/timeline/timeline.json
packages/material-ui-lab/src/Timeline/Timeline.test.tsx
packages/material-ui-lab/src/Timeline/Timeline.tsx
packages/material-ui-lab/src/Timeline/index.tsx
packages/material-ui-lab/src/Timeline/timelineClasses.ts
packages/material-ui-unstyled/src/composeClasses/composeClasses.ts
packages/material-ui/src/styles/experimentalStyled.d.ts

[Timeline] Migrate Timeline to emotion

---

packages/material-ui/src/Backdrop/Backdrop.js
packages/material-ui/src/Badge/Badge.js
packages/material-ui/src/Badge/Badge.test.js
packages/material-ui/src/BottomNavigation/BottomNavigation.js
packages/material-ui/src/BottomNavigationAction/BottomNavigationAction.js
packages/material-ui/src/Breadcrumbs/Breadcrumbs.js
packages/material-ui/src/Button/Button.js
packages/material-ui/src/ButtonBase/ButtonBase.js
packages/material-ui/src/ButtonGroup/ButtonGroup.js
packages/material-ui/src/ButtonGroup/ButtonGroup.test.js
packages/material-ui/src/styles/experimentalStyled.js

Updates component starting with `B` to use the `overridesResolver` on the slots components
Part 1: #25853

[core] Update slot components to use overridesResolver part 2

---

packages/material-ui/src/Card/Card.js
packages/material-ui/src/CardActionArea/CardActionArea.js
packages/material-ui/src/CardActions/CardActions.js
packages/material-ui/src/CardContent/CardContent.js
packages/material-ui/src/CardHeader/CardHeader.js
packages/material-ui/src/CardMedia/CardMedia.js
packages/material-ui/src/Checkbox/Checkbox.js
packages/material-ui/src/Chip/Chip.js
packages/material-ui/src/CircularProgress/CircularProgress.js
packages/material-ui/src/Collapse/Collapse.js
packages/material-ui/src/Container/Container.js
packages/material-ui/src/Dialog/Dialog.js
packages/material-ui/src/DialogActions/DialogActions.js
packages/material-ui/src/DialogContent/DialogContent.js
packages/material-ui/src/DialogContentText/DialogContentText.js
packages/material-ui/src/DialogTitle/DialogTitle.js
packages/material-ui/src/Divider/Divider.js
packages/material-ui/src/Drawer/Drawer.js

Updates component starting with `[C-D]` to use the `overridesResolver` on the slots components
Part 1: #25853
Part 2: #25864

[core] Update slot components to use overridesResolver part 3

---

docs/pages/_app.js
docs/pages/_document.js
docs/src/modules/utils/StyledEngineProvider.js

As per emotoin's documentation, the cache should be re-created per request (see the note https://emotion.sh/docs/ssr#extractcritical). So far we've been reusing the same cache instance, which was leading to global styles leaking on different pages. 
Preview: https://deploy-preview-25855--material-ui.netlify.app/components/grid/#interactive

[docs] Fix global styles leaking on different pages

---

packages/material-ui/src/Fab/Fab.js
packages/material-ui/src/FilledInput/FilledInput.js
packages/material-ui/src/FormControl/FormControl.js
packages/material-ui/src/FormControlLabel/FormControlLabel.js
packages/material-ui/src/FormGroup/FormGroup.js
packages/material-ui/src/FormHelperText/FormHelperText.js
packages/material-ui/src/FormLabel/FormLabel.js
packages/material-ui/src/Grid/Grid.js
packages/material-ui/src/Icon/Icon.js
packages/material-ui/src/IconButton/IconButton.js
packages/material-ui/src/ImageList/ImageList.js
packages/material-ui/src/ImageListItem/ImageListItem.js
packages/material-ui/src/ImageListItemBar/ImageListItemBar.js
packages/material-ui/src/Input/Input.js
packages/material-ui/src/InputBase/InputBase.js
packages/material-ui/src/InputLabel/InputLabel.js
packages/material-ui/src/ListItemText/ListItemText.test.js
packages/material-ui/src/OutlinedInput/OutlinedInput.js

Updates component starting with `[E-I]` + `OutlinedInput` to use the `overridesResolver` on the slots components
Part 1: #25853
Part 2: #25864
Part 3: #25881

[core] Update slot components to use overridesResolver part 4

---

packages/material-ui/src/LinearProgress/LinearProgress.js
packages/material-ui/src/Link/Link.js
packages/material-ui/src/List/List.js
packages/material-ui/src/ListItem/ListItem.js
packages/material-ui/src/ListItemAvatar/ListItemAvatar.js
packages/material-ui/src/ListItemIcon/ListItemIcon.js
packages/material-ui/src/ListItemSecondaryAction/ListItemSecondaryAction.js
packages/material-ui/src/ListItemText/ListItemText.js
packages/material-ui/src/ListItemText/ListItemText.test.js
packages/material-ui/src/ListSubheader/ListSubheader.js
packages/material-ui/src/Menu/Menu.js
packages/material-ui/src/MenuItem/MenuItem.js
packages/material-ui/src/MobileStepper/MobileStepper.js
packages/material-ui/src/Modal/Modal.js
packages/material-ui/src/NativeSelect/NativeSelectInput.js

Updates component starting with `[J-O]` to use the `overridesResolver` on the slots components
Part 1: #25853
Part 2: #25864
Part 3: #25881
Part 4: #25884

[core] Update slot components to use overridesResolver part 5

---

scripts/build.js
scripts/copy-files.js

We should've verified these entries to begin with (happy-path fallacy). 
Can't wait to use `exports` field and get rid of all the aliasing and path shenanigans.

[system] Add missing `main` entry for styleFunctionSx

---

docs/scripts/buildApi.ts
packages/material-ui-unstyled/src/BadgeUnstyled/BadgeUnstyled.d.ts

We already list them explicitly so let's not try to be too clever about it in `yarn docs:api`.

[docs] Explicitly list demos of unstyled components

---

packages/material-ui/src/Pagination/Pagination.js
packages/material-ui/src/PaginationItem/PaginationItem.js
packages/material-ui/src/Paper/Paper.js
packages/material-ui/src/Popover/Popover.js
packages/material-ui/src/Radio/Radio.js
packages/material-ui/src/Rating/Rating.js
packages/material-ui/src/ScopedCssBaseline/ScopedCssBaseline.js
packages/material-ui/src/Select/SelectInput.js
packages/material-ui/src/Skeleton/Skeleton.js
packages/material-ui/src/Slider/Slider.js
packages/material-ui/src/Snackbar/Snackbar.js
packages/material-ui/src/SnackbarContent/SnackbarContent.js
packages/material-ui/src/SpeedDial/SpeedDial.js
packages/material-ui/src/SpeedDialAction/SpeedDialAction.js
packages/material-ui/src/SpeedDialIcon/SpeedDialIcon.js
packages/material-ui/src/Step/Step.js
packages/material-ui/src/StepButton/StepButton.js
packages/material-ui/src/StepConnector/StepConnector.js
packages/material-ui/src/StepContent/StepContent.js
packages/material-ui/src/StepIcon/StepIcon.js
packages/material-ui/src/StepLabel/StepLabel.js
packages/material-ui/src/Stepper/Stepper.js
packages/material-ui/src/SvgIcon/SvgIcon.js
packages/material-ui/src/Switch/Switch.js

Updates component starting with `[P-S]` to use the `overridesResolver` on the slots components
Part 1: #25853
Part 2: #25864
Part 3: #25881
Part 4: #25884
Part 5: #25887

[core] Update slot components to use overridesResolver part 6

---

docs/translations/api-docs/slider-unstyled/slider-unstyled.json
docs/translations/api-docs/slider/slider.json
packages/material-ui-unstyled/src/SliderUnstyled/SliderUnstyled.d.ts

Fixes the descriptions for the `trackFalse` and `trackInverted` classes. They were always applied on the `root` element, but the description is incorrect.
v4: https://github.com/mui-org/material-ui/blob/master/packages/material-ui/src/Slider/Slider.js#L685
v5: https://github.com/mui-org/material-ui/blob/next/packages/material-ui-unstyled/src/SliderUnstyled/SliderUnstyled.js#L165

[docs] Fix Slider's classes wrong description

---

packages/material-ui/src/Tab/Tab.js
packages/material-ui/src/TabScrollButton/TabScrollButton.js
packages/material-ui/src/Table/Table.js
packages/material-ui/src/TableBody/TableBody.js
packages/material-ui/src/TableCell/TableCell.js
packages/material-ui/src/TableContainer/TableContainer.js
packages/material-ui/src/TableFooter/TableFooter.js
packages/material-ui/src/TableHead/TableHead.js
packages/material-ui/src/TableRow/TableRow.js
packages/material-ui/src/TableSortLabel/TableSortLabel.js
packages/material-ui/src/TextField/TextField.js
packages/material-ui/src/ToggleButton/ToggleButton.js
packages/material-ui/src/ToggleButtonGroup/ToggleButtonGroup.js
packages/material-ui/src/Toolbar/Toolbar.js
packages/material-ui/src/Tooltip/Tooltip.js
packages/material-ui/src/Typography/Typography.js

Updates component starting with `[T-Z]` to use the `overridesResolver` on the slots components
Part 1: #25853
Part 2: #25864
Part 3: #25881
Part 4: #25884
Part 5: #25887
Part 6: #25892

[core] Update slot components to use overridesResolver part 7

---

packages/material-ui-lab/src/TabPanel/TabPanel.js
packages/material-ui-lab/src/TimelineConnector/TimelineConnector.js
packages/material-ui-lab/src/TimelineContent/TimelineContent.js
packages/material-ui-lab/src/TimelineDot/TimelineDot.js
packages/material-ui-lab/src/TimelineItem/TimelineItem.js
packages/material-ui-lab/src/TimelineOppositeContent/TimelineOppositeContent.js
packages/material-ui-lab/src/TimelineSeparator/TimelineSeparator.js
packages/material-ui-lab/src/TreeView/TreeView.js

Updates all components in the lab which are migrated to emotion to use the overridesResolver on the slots components.

[lab] Update slot components to use overridesResolver

---

docs/src/modules/branding/ComparisonTable.tsx
packages/material-ui/src/styles/colorManipulator.d.ts
packages/material-ui/src/styles/colorManipulator.js

Part of #20012 
The deprecation warning is already in the v4-deprecations branch: https://github.com/mui-org/material-ui/commit/6db7fb2fe09b60a3137df0211e3c29d7dc53abfa: https://next.material-ui.com/guides/migration-v4/#styles.

[theme] Remove fade color helper

---

docs/pages/api-docs/input-adornment.json
docs/src/pages/guides/migration-v4/migration-v4.md
packages/material-ui/src/InputAdornment/InputAdornment.d.ts
packages/material-ui/src/InputAdornment/InputAdornment.js

[TextField] Make the `position` prop required in InputAdornment

---

packages/material-ui/src/Autocomplete/Autocomplete.js

Remove superfluous parentheses in tagSize className, e.g. it gave
```
"MuiAutocomplete-tag MuiAutocomplete-tagSizeMedium)"
```
as className property in getTagProps, notice the closing parantheses after `tagSizeMedium`**)** .

[Autocomplete] Fix tagSize class typo

---

docs/pages/api-docs/input-adornment.md
packages/material-ui/src/InputAdornment/InputAdornment.js
packages/material-ui/src/InputAdornment/InputAdornment.test.js

A warning for #25891. This prop is already required for TypeScript users, but the `propTypes` definition was not matching it.

[TextField] Add `isRequired` to position prop in InputAdornment

---

docs/src/pages/guides/migration-v4/migration-v4.md
packages/material-ui/src/styles/createTypography.js

The `theme.typography.round` helper was removed because it was no longer used. If you need it, use the function below:
```js
function round(value) {
return Math.round(value * 1e5) / 1e5;
}
```
Part of #20012.

[theme] Remove theme.typography.round helper

---

docs/pages/api-docs/rating.json
packages/material-ui/src/Rating/Rating.d.ts
packages/material-ui/src/Rating/Rating.js

[Rating] Support custom sizes
