mui/material-ui

docs/src/app/components/pages/components/dialog.jsx, src/dialog.jsx
As discussed in #2420 and #2428..
@subjectix @oliviertassinari
=> [Dialog] Add overlayStyle property

src/drop-down-menu.jsx
Continuation of #1300.
@oliviertassinari Please review.
=> [DropDownMenu] Bubble keyboard events

src/checkbox.jsx
Continuation of #1403.
@oliviertassinari Please take a look.
=> [Checkbox] Update state when 'checked' props change

src/popover/popover.jsx
=> [Popover] change children from object to node

src/app-bar.jsx, src/flat-button.jsx, src/styles/theme-manager.js
Transparent background, and alpha overlays for hover and ripple, to better match Material-Design spec.
Addresses #2467 & #1937.
=> Adjust FlatButton background, hover and ripple colors

CHANGELOG.md, docs/package.json, package.json
@hai-cea @oliviertassinari Please take a look at this.
=> Prepare the 0.14.0-rc2 release

src/styles/index.js
=> Add ZIndex to styles/index.

src/clearfix.jsx
@oliviertassinari Take a look. it's just implementation detail :grin:
=> [ClearFix] Simplify component

docs/src/app/components/Badge/README.md
Correct "it's" to possessive form "its". No other changes made.
=> Correct minor grammatical error in Badge README.md

.npmignore
I noticed this by looking at my node_modules folder.
That makes the download faster.
=> [npm] Remove unnecessary files from the npm package

karma.conf.js, test/checkbox-spec.js, test/date-picker/calendar-spec.js, test/dialog-spec.js, test/drop-down-menu-spec.js, test/mixin-context-pure-spec.js
Solve
```
ERROR: 'Warning: require('react/addons') is deprecated. Access using require('react-addons-{addon}') instead.'
ERROR: 'Warning: "menuItems" property of "DropDownMenu" has been deprecated.
Instead, use composability.'
```
=> [Test] Fix warnings

src/DropDownMenu/DropDownMenu.jsx
This fixed a regression caused from migrating to the new Menu components
Closes #2588.
@oliviertassinari Take a look and merge. thanks
=> [DrowDownMenu] Fix regression

src/DropDownMenu/DropDownMenu.jsx
Fixing https://github.com/callemall/material-ui/issues/2604
=> [DropDownMenu] Fixed inconsistent style bug

src/lists/list-item.jsx
Fix https://github.com/callemall/material-ui/issues/2522, https://github.com/callemall/material-ui/issues/2481 and https://github.com/callemall/material-ui/pull/2525
=> [ListItem] Fix box-sizing: border-box

src/circular-progress.jsx
Remove the margins of the circular progress wrapper
fixes #2647
=> Fix circular progress alignment

CHANGELOG.md, ROADMAP.md, docs/native/package.json, docs/package.json, package.json
@hai-cea @oliviertassinari Take a look please.
I also didn't want to document the new way to use theme-manager (or rather getMuiTheme function), we have introduce too many changes with this. That one can wait until we answer some questions regarding how to handling theming.
=> Prepare the 0.14.0 Release

src/table/table.jsx
Found a similar styling issue to  https://github.com/callemall/material-ui/issues/2604 with the Table.
=> [Table] Fixed inconsistent table styling bug

src/app-bar.jsx
=> Update app-bar to support the iconStyle prop of iconButton

src/select-field.jsx
Add prop hintStyle for SelectField
=> Add hintStyle for SelectField

src/time-picker/time-picker.jsx
Closes #2732 
@oliviertassinari Take a look and merge :grin: :grin:
=> [TimePicker] Remove deprecation warning

docs/src/app/components/pages/components/auto-complete.jsx
Here are few documents about the basic usage of AutoComplete.
More will be added as they become stable.
Long time no see, a bit overwhelmed in the past few weeks. I am going to start fixing some bugs too.
=> added some basic doc for AutoComplete

src/SelectField/SelectField.jsx
This was my fault. Sorry :grin: 
labelStyle has nothing to do with composiblity. it's the label shown on the TextField not the menu.
=> [SelectField] Remove false deprecation

examples/browserify-gulp-example/.babelrc, examples/browserify-gulp-example/gulp/tasks/browserify.js, examples/browserify-gulp-example/package.json
=> [Examples] Upgrade to babel 6 for browserify

docs/src/app/components/app-left-nav.jsx, docs/src/app/components/pages/components/SelectField/ExampleCustomLabel.jsx, docs/src/app/components/pages/components/SelectField/ExampleDisabled.jsx, docs/src/app/components/pages/components/SelectField/ExampleError.jsx, docs/src/app/components/pages/components/SelectField/ExampleFloatingLabel.jsx, docs/src/app/components/pages/components/SelectField/ExampleSimple.jsx
Fix https://github.com/callemall/material-ui/issues/2803.
=> [Docs] Use the regular path for the import

docs/src/app/components/pages/components/auto-complete.jsx, docs/src/app/components/raw-code/auto-complete-code.txt, src/auto-complete.jsx
added filter for #2386 and a filter generator that compare string distance
ex:
```
<AutoComplete filter={AutoComplete.CaseInsensitiveFilter} />
```
=> added 2 filter for text matching

src/snackbar.jsx
Fix https://github.com/callemall/material-ui/issues/2811.
=> [Docs] Document Snackbar autoHideDuration(reason) parameter

docs/src/app/components/pages/components/popover.jsx
=> [Docs] Fixed default props in Popover

docs/package.json, docs/src/.babelrc, package.json
Fix https://github.com/callemall/material-ui/issues/2845.
I have tested the fix on two of my project, it should be good :+1:.
=> [Docs] Fix IE production website

.eslintrc, src/TextField/TextFieldHint.jsx, src/TextField/TextFieldLabel.jsx, src/TextField/TextFieldUnderline.jsx, src/app-bar.jsx, src/divider.jsx, src/slider.jsx
I have also fixed the JSDoc syntax.
=> [Docs] Always use the same wording for the style

docs/src/app/components/master.jsx, docs/src/app/components/pages/customization/themes.jsx
Fix https://github.com/callemall/material-ui/issues/2901.
Browsing the examples, I realize that the dark theme is far from beeing perfect :grin:.
=> [Docs] Spread the theme to the all documentation

src/lists/list-item.jsx, test/lists/list-item-spec.js
Added in className to _createDisabledElement in list-item.jsx so a class can still be assigned even if the list item is disabled.
=> Issue #2723: ListItem when disabled className is not returned

docs/src/app/components/app-left-nav.jsx
=> [Docs] Flatten side menu ListItem props.

docs/src/app/components/pages/components/FlatButton/ExampleComplex.jsx, docs/src/app/components/pages/components/FlatButton/Page.jsx, docs/src/app/components/pages/components/FloatingActionButton/ExampleSimple.jsx, docs/src/app/components/pages/components/RadioButton/Page.jsx, docs/src/app/components/pages/components/RaisedButton/ExampleComplex.jsx, docs/src/app/components/pages/components/RaisedButton/ExampleSimple.jsx, docs/src/app/components/pages/components/RaisedButton/Page.jsx, src/flat-button.jsx, src/floating-action-button.jsx, src/radio-button.jsx, src/raised-button.jsx
=> [Docs] FlatButton, FAB - document linkButton & href, RaisedButton, RadioButton - Add title & description to examples

src/lists/list-item.jsx, test/lists/list-item-spec.js
* Added additionalProps to return when creating a listItem with a checkbox 
* Added tests to prevent regression
this fixes #2723
=> [ListItem] When checkbox className is not returned

docs/src/app/components/pages/components/FontIcon/ExampleIcons.jsx, docs/src/app/components/pages/components/FontIcon/Page.jsx, docs/src/app/components/pages/components/FontIcon/README.md, docs/src/app/components/pages/components/Slider/Page.jsx, docs/src/app/components/pages/components/Snackbar/ExampleAction.jsx, docs/src/app/components/pages/components/Snackbar/ExampleSimple.jsx, docs/src/app/components/pages/components/Snackbar/ExampleTwice.jsx, docs/src/app/components/pages/components/Snackbar/Page.jsx, docs/src/app/components/pages/components/SvgIcon/ExampleSimple.jsx, docs/src/app/components/pages/components/SvgIcon/Page.jsx, docs/src/app/components/pages/components/SvgIcon/README.md, src/snackbar.jsx, src/svg-icon.jsx
=> [Docs] Slider, Snackbar, SvgIcon - Add title & description to examples. FontIcon - cleanup README & Examples.

src/enhanced-button.jsx
Signed-off-by: Junliang Huang <i@jhuang.me>
=> [EnhancedButton] Make keyup event respect disableKeyboardFocus

docs/src/app/components/pages/components/TextField/Page.jsx, docs/src/app/components/pages/components/TimePicker/ExampleComplex.jsx, docs/src/app/components/pages/components/TimePicker/ExampleSimple.jsx, docs/src/app/components/pages/components/TimePicker/Page.jsx
=> [Docs] TextField, TimePicker - Add title & description to examples.

.eslintrc, test/lists/list-item-spec.js
Related to https://github.com/callemall/material-ui/issues/2903.
=> [eslint] enforce react/jsx-equals-spacing

docs/src/app/components/pages/discover-more/Showcase.jsx
Use the landing page, rather than the login page to be consistent with the other two examples. There's a Material UI screenshot further down the page.
=> [Docs] Showcase - Update Syncano URL

CHANGELOG.md, ROADMAP.md, docs/package.json, examples/browserify-gulp-example/package.json, examples/webpack-example/package.json, package.json
@oliviertassinari @newoga @mbrookes @hai-cea Take a look please. Thanks.
~~Please note that this is not final, as some other issues must be fixed first. But since this is a big release, I just made the PR for reviewing.~~
=> Prepare the 0.14.3 release

.npmignore
Resovles #3077
Signed-off-by: Neil Gabbadon <neil.gabbadon@emikra.com>
=> [Core] Adds src to .npmignore

src/hoc/selectable-enhance.js
=> [List] Auto-expand SelectableList

docs/src/app/components/pages/customization/themes.jsx
=> [Docs] Themes - fix code examples.

docs/src/app/app-routes.jsx, docs/src/app/components/app-left-nav.jsx, docs/src/app/components/pages/discover-more/RelatedProjects.jsx, docs/src/app/components/pages/discover-more/related-projects.md
Fix https://github.com/callemall/material-ui/issues/2873 and https://github.com/callemall/material-ui/pull/3097.
=> [Docs] Add a Related project section

CONTRIBUTING.md, docs/README.md, docs/src/app/app.native.js, docs/src/app/components/app-left-nav.jsx, docs/src/app/components/pages/components/SvgIcon/README.md, docs/src/app/components/pages/discover-more/community.md, docs/src/app/components/pages/discover-more/showcase.md, docs/src/app/components/pages/get-started/prerequisites.md, docs/src/app/components/pages/get-started/serverRendering.md, docs/src/app/components/pages/home.jsx, docs/src/www/index.html, examples/browserify-gulp-example/src/www/index.html, examples/webpack-example/src/www/index.html, icon-builder/build.js, src/styles/auto-prefix.js
A trivial change, but brand is king! :)
=> [Docs] Change 'Material UI' to 'Material-UI'

src/raised-button.jsx
=> [Docs] RaisedButton - Fix  prop docs

src/enhanced-button.jsx
Closes #3091.
This PR fixes the vertical alignment issue for both Flat button and Raised button.
[New contributor here. Please guide me through if I am missing something]
=> [Buttons] Fixing the vertical alignment issue.

docs/src/app/components/pages/components/FlatButton/ExampleComplex.jsx, docs/src/app/components/pages/components/RaisedButton/ExampleComplex.jsx, src/flat-button.jsx, src/raised-button.jsx
Fix https://github.com/callemall/material-ui/issues/1958 and https://github.com/callemall/material-ui/issues/3114.
=> [RaisedButton][FlatButton] Fix the default value of labelPosition

src/flat-button.jsx, src/raised-button.jsx
=> [Docs] RaisedButton - consistent component prop docs

src/styles/auto-prefix.js, src/styles/getMuiTheme.js, src/styles/transformers/autoprefixer.js, src/utils/styles.js, test/prepareStyles.spec.js
This is a continuation of https://github.com/callemall/material-ui/pull/3112.
@justinabrahms This is a regression and high priority IMHO.
I have added some tests. Can you have a look?
I feel like we have merged too many PR without tests and it's the right moment to enforce that
every new feature or bug fixes has his own test.
=> [Style] Fix the prefixer tool regression

docs/src/app/components/pages/get-started/installation.md
This (hopefully) fix the original issue brought up by #3172.
=> [doc] Add usage of `onTouchTap()`

src/menus/icon-menu.jsx
I have forgotten to check the default value of this property https://github.com/callemall/material-ui/pull/3108/files#diff-57ca0ef69b8c77c46a17425170ccfd8cL250. Rooky mistake.
=> [IconMenu] Add some logic removed by mistake

src/dialog.jsx
This file is a little confusing with 3 components in it. We should probably split it up after the directory change.
=> [Dialog] Remove style-propable mixin

docs/src/app/components/pages/components/Menu/README.md, docs/src/app/components/pages/components/Popover/ExampleAnimation.jsx, docs/src/app/components/pages/components/Popover/ExampleConfigurable.jsx, docs/src/app/components/pages/components/Popover/ExampleSimple.jsx, docs/src/app/components/pages/components/Popover/Page.jsx, docs/src/app/components/pages/components/Popover/README.md, src/menus/menu.jsx
=> [Menu] Deprecate built in `animated`

CHANGELOG.md, src/floating-action-button.jsx, src/raised-button.jsx
This is in reference to #2310. So I guess all of the Button component are Composable now
=> [FloatingActionButton] Fix Floating Action Button className issue

docs/src/app/components/pages/components/DatePicker/ExampleDisableDates.jsx, docs/src/app/components/pages/components/DatePicker/Page.jsx
=> [Docs] DatePicker - Add disabled dates example

src/TextField/TextField.jsx
add textareaStyle
needed to be able to change the style of textarea in the EnhancedTextArea
=> [TextField] Add textareaStyle property

src/TextField/TextFieldHint.jsx, src/TextField/TextFieldLabel.jsx, src/TextField/TextFieldUnderline.jsx, src/radio-button.jsx, src/ripples/circle-ripple.jsx, src/ripples/focus-ripple.jsx, src/ripples/touch-ripple.jsx
This is in reference to #2973. @mbrookes let me know if I forgot something or if there's any mistake. :sweat_smile:
=> [Docs] Hide internal properties

docs/src/app/components/pages/components/AutoComplete/ExampleFilters.jsx, docs/src/app/components/pages/components/AutoComplete/Page.jsx, src/auto-complete.jsx
Added `maxSearchResult` property in `AutoComplete` to control number of search result to be shown
=> [AutoComplete] Added maxSearchResults property

package.json, src/enhanced-textarea.jsx
- add shadowStyle
- fix textareaStyle due to StylePropable changes
- add position:relative to the root element
- resize on window resize
=> [EnhancedTextArea] various style fixes

src/lists/list-item.jsx, src/styles/getMuiTheme.js
This is in reference to #2490.  @mbrookes I guess this is a good way :grin:
=> [ListItem] Fix: secondaryTextColor hardcode

src/buttons/flat-button-label.jsx
=> [Button] Fix setting theme

docs/src/app/components/pages/components/AutoComplete/ExampleFilters.jsx, docs/src/app/components/pages/components/AutoComplete/ExampleSimple.jsx, docs/src/app/components/pages/components/AutoComplete/Page.jsx
=> [AutoComplete] Add maxSearchResults property

src/toggle.jsx
This fixes the styling issue raised in #3255. ([comment](https://github.com/callemall/material-ui/pull/3255#issuecomment-182847685))
=> [Toggle] Fixes styling issue

docs/src/app/components/pages/components/Card/ExampleControlled.jsx, docs/src/app/components/pages/components/Card/Page.jsx, docs/src/app/components/pages/components/Card/README.md, src/card/card.jsx
=> [Card] support for controlled expansion

docs/src/app/components/AppLeftNav.jsx, docs/src/app/components/CodeExample/CodeBlock.jsx, docs/src/app/components/ComponentDoc.jsx, docs/src/app/components/ComponentInfo.jsx, docs/src/app/components/FullWidthSection.jsx, docs/src/app/components/MarkdownElement.jsx, docs/src/app/components/MobileTearSheet.jsx, docs/src/app/components/master.jsx, docs/src/app/components/pages/HomeFeature.jsx, docs/src/app/components/pages/customization/colors.jsx, docs/src/app/components/pages/customization/themes.jsx, docs/src/app/components/pages/home.jsx
Hopefully this wasn't too much for a single PR. Let me know, we can also postpone this if we need to until other PRs impacting docs are merged first.
=> [Docs] Remove style propable mixin

CHANGELOG.md, src/left-nav.jsx
Hello, this is fixed version of #2678 
Closes #2678.
=> [LeftNav] Move `className`  and `style` to the root element

ROADMAP.md, docs/src/app/components/pages/customization/themes.md
This is the cleanup after the chages introduced in #3267
@mbrookes I made the changes you mentioned in your comments take a look and see if this is alright.
=> [Theme] Improve clarity of the doc page

src/auto-complete.jsx
I'm working on fixing the `blur`, `focus` call hell. I have noticed that they are called 6 times at each keydown and that's not working on cordova android.
=> [AutoComplete] Remove style-propable mixin

docs/src/app/components/pages/components/FlatButton/ExampleComplex.jsx, docs/src/app/components/pages/components/RaisedButton/ExampleComplex.jsx
=> [Docs] Fix Choose an Image example

src/app-bar.jsx, src/date-picker/calendar-year.jsx, src/enhanced-button.jsx, src/lists/list-item.jsx, src/menus/menu-item.jsx, src/overlay.jsx, src/styles/getMuiTheme.js, src/tooltip.jsx
@oliviertassinari @newoga @alitaheri I will add remaining once you guys review it. Just bit confused that I'm doing it correctly :grin:
=> [Core] Migrate color to muiTheme

src/menus/icon-menu.jsx
=> [IconMenu] enable useLayerForClickAway

.travis.yml, package.json
=> [tests] Add support for codecov

src/raised-button.jsx
@oliviertassinari I'm confused with opacity. is it good idea to make opacityPrimary and opactiySecondary? Also should I change other components that uses the rippleColor and opacity?
in reference to #3353
=> [RaisedButton] Customizable ripple effect style

src/TextField/TextField.jsx, src/date-picker/day-button.jsx, src/date-picker/year-button.jsx, src/dialog.jsx, src/enhanced-button.jsx, src/overlay.jsx, src/paper.jsx, src/toolbar/toolbar.jsx
Fix https://github.com/callemall/material-ui/issues/3410
Before:
After:
=> [Style] Fix tap highlight color

src/checkbox.jsx
=> [Checkbox] disabled style error fix

src/styles/getMuiTheme.js
Put the list of components in getMuiTheme in alphabetical order.
=> [getMuiTheme] chore(alphabetize-components): Arrange MUI Theme components

src/styles/index.js
This was a regression introduced in #2825
=> Fix Colors import regression

src/card/card.jsx
=> [Card] overflow removed

src/icon-button.jsx
Closes #2945 
@alitaheri @newoga have a look guys
=> [IconButton] Fix tooltip for disabled component

src/dialog.jsx
=> [Dialog] fix overflow.

docs/src/www/index.html, examples/browserify-gulp-example/src/www/index.html, examples/webpack-example/src/www/index.html
Fix https://github.com/callemall/material-ui/issues/3431.
I have no idea how to see if the GPU rasterization is enable on my android. Anyone?
=> [Docs] Enable GPU rasterization

src/svg-icon.jsx
onMouseEnter and onMouseLeave was only fired when props hoverColor was set
=> [SvgIcon] Fix behavior for onMouseEnter and onMouseLeave

test/unit/AppBar.spec.js
Initial work by @pradel from #3445
=> [Tests] Add unit tests for AppBar

test/unit/GridList.spec.js
Initial work by @pradel from #3445
=> [Tests] Add unit tests for GridList

test/unit/SvgIcon.spec.js
Initial work by @pradel from #3445
=> [Tests] Add unit tests for SvgIcon

test/unit/FontIcon.spec.js
Initial work by @pradel from #3445
=> [Tests] Add unit tests for FontIcon

src/left-nav.jsx
Following #3415 I added a zDepth prop to be able to change the zDepth of the embedded Paper.
=> [LeftNav] add a configurable zDepth

CHANGELOG.md, docs/package.json, examples/browserify-gulp-example/package.json, examples/webpack-example/package.json, package.json
@oliviertassinari @newoga @mbrookes @hai-cea 
These are the changes made to master since the last release, there are many :fearful: :fearful:
Hopefully I didn't miss any credit. Please review carefully, there might be many bad wording and stuff.
Also I didn't touch the version info of examples and the docs since i think we should avoid updating them before the actual release. But that's open to discussion. thanks everyone for your great efforts :+1: :+1: This release makes me so happy :heart_eyes: :heart_eyes:
=> Prepare the 0.15.0-alpha.1 release

examples/webpack-example/README.md, examples/webpack-example/webpack-dev-server.config.js
=> [Webpack] Include 'host' parameter in webpack config

docs/src/app/components/pages/components/DatePicker/ExampleInternational.jsx, docs/src/app/components/pages/components/DatePicker/Page.jsx, src/date-picker/date-picker-dialog.jsx, src/date-picker/date-picker.jsx
=> [DatePicker] Deprecate `wordings` with `cancelLabel` and `okLabel`

docs/src/app/components/pages/components/FlatButton/ExampleIcon.jsx, docs/src/app/components/pages/components/FlatButton/Page.jsx, src/flat-button.jsx
Hello,
fixed flat button icon styling without label
fixed flat button icon styling without label, but with **link** #3456;
added doc example of flat button without label, but with icon;
=> [FlatButton] Fix for icon styling when no label provided

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
First pass. Edits & corrections appreciated. 
(Please note that since we haven't added the template yet, this PR doesn't conform. :smirk:)
Closes #3370.
=> [Github] Issue & PR templates

src/app-canvas.jsx
Fix https://github.com/callemall/material-ui/issues/3536.
=> [AppCanvas] Remove mergeStyles

docs/src/app/components/pages/components/RaisedButton/ExampleIcon.jsx, docs/src/app/components/pages/components/RaisedButton/Page.jsx, src/raised-button.jsx
Fix for icon styling when no label provided.
Fix label is left aligned when linkButton is true.
Fixes #3468, fixes #3456.
=> [RaisedButton] Fix styling issues

src/flat-button.jsx
=> [FlatButton] Fix icon alignment when no label provided

docs/src/app/components/pages/components/TextField/ExampleControlled.jsx, docs/src/app/components/pages/components/TextField/ExampleDisabled.jsx, docs/src/app/components/pages/components/TextField/ExampleSimple.jsx, src/TextField/TextField.jsx, src/enhanced-switch.jsx, src/utils/index.js, src/utils/unique-id.js
Fix https://github.com/callemall/material-ui/issues/3533.
=> [Core] Remove uniqueId utils

test/unit/FlatButton.spec.js
Unit test for the flat button.
If it looks a little thin, it is because most of the unit testing for buttons takes place in the `<EnhancedButton />` unit test that I have a PR open for (still needs reviewing): https://github.com/callemall/material-ui/pull/3512
=> [FlatButton] added FlatButton unit test

src/flat-button.jsx
@newoga you know the name, you know the number
=> [FlatButton] Fixes regression introduced by #3529

test/unit/Divider.spec.js
=> [Divider] Add unit test

ROADMAP.md
=> [ROADMAP] Remove checkmarks, correct some links

ROADMAP.md
=> [ROADMAP] Use bullet list for Future, further corrections

src/card/card.jsx
=> [Card] Add callback signature to property docs

src/DropDownMenu/DropDownMenu.jsx, src/date-picker/date-picker-inline.jsx
Closes https://github.com/callemall/material-ui/pull/2557.
=> [DatePicker] Use popover for the inline mode

src/table/table-body.jsx, src/table/table-row.jsx
Fixes #1783, as mentioned in the comments
=> [TableRow] [TableRowColumn] Propagate events

docs/src/app/components/pages/discover-more/related-projects.md
This changes the tense of the sentence for clarity.
=> [Docs] Grammar change for related-projects.md

docs/src/app/components/pages/components/Card/ExampleControlled.jsx, docs/src/app/components/pages/components/Dialog/ExampleCustomWidth.jsx, docs/src/app/components/pages/components/Dialog/ExampleDialogDatePicker.jsx, docs/src/app/components/pages/components/Dialog/ExampleModal.jsx, docs/src/app/components/pages/components/Dialog/ExampleSimple.jsx, src/date-picker/date-picker-dialog.jsx, src/time-picker/time-picker-dialog.jsx
The regression were introduced by
- https://github.com/callemall/material-ui/pull/3563
- https://github.com/callemall/material-ui/pull/3513
=> [Core] Fix regression introduces by latest PR

src/time-picker/time-display.jsx
Closes https://github.com/callemall/material-ui/pull/3302.
=> [TimePicker] Remove a useless div element

src/date-picker/calendar.jsx, src/date-picker/date-display.jsx
Closes https://github.com/callemall/material-ui/pull/3325. Thanks @CameronFletcher92 for the initial finding.
=> [DatePicker] Fix cursor pointer of the header

docs/src/app/components/pages/components/DatePicker/ExampleToggle.jsx
=> [DatePicker] Fix docs ranged example options width

CHANGELOG.md, docs/src/app/components/pages/components/Menu/ExampleDisable.jsx, docs/src/app/components/pages/components/Menu/ExampleIcons.jsx, docs/src/app/components/pages/components/Menu/ExampleNested.jsx, docs/src/app/components/pages/components/Menu/ExampleSecondary.jsx, docs/src/app/components/pages/components/Menu/ExampleSimple.jsx, src/menus/menu.jsx
The `Paper` component was unnecessary given that `Menu` is used wrapped in other components
that contain `Paper`, such as `Popover`.
=> [Menu] Remove Paper

src/checkbox.jsx
=> [Checkbox] Add callback signatures to property docs

src/auto-complete.jsx
Fixed PR for https://github.com/callemall/material-ui/pull/3015
=> [AutoComplete] set canAutoPosition to false for PopOver

src/DropDownMenu/DropDownMenu.jsx
=> [DropDownMenu] Add callback signatures to property docs

src/tabs/tab.jsx
=> [Tab] Style prop is not functional

README.md, docs/src/app/components/master.jsx, docs/src/app/components/pages/home.jsx
Also, fixed word wrapping in footer.
=> [Docs] Change CallEmAll links to point to our careers page

src/auto-complete.jsx
Fix TypeError: undefined is not a function in Safara < 9,
and other unsupported browsers
Closes #3270.
=> [AutoComplete] Polyfill for String.prototype.includes()

src/enhanced-switch.jsx
This is part of an attempt to clean up the internal components, break them down, make them more efficient, etc. 
I decided to start from these as they seemed like blackbox to me. So I'm going to increase their quality, make the declarative, as stateless as possible, performant and clean.
@callemall/material-ui Would like your opinion on how this looks like.
=> [EnhancedSwitch] Tidy up

src/card/card-actions.jsx, src/card/card-header.jsx, src/card/card-media.jsx, src/card/card-text.jsx, src/card/card-title.jsx, src/card/card.jsx
Added properties description for card subcomponents.
@mbrookes have a look. 
References #2996
=> [Card] Document card subcomponent properties

src/icon-button.jsx
This is a part of #2861, I'm breaking that PR down as much as i can.
@callemall/material-ui Merge if you agree we should expose this. :grin:
=> [IconButton] Expose disableTouchRipple

package.json, src/snackbar.jsx, test/unit/Snackbar.spec.js
=> [Snackbar] Make on request close optional

src/floating-action-button.jsx
=> [FloatingActionButton] Add callback signatures to docs

src/font-icon.jsx
=> [FontIcon] Add callback signatures to docs

CONTRIBUTING.md, docs/webpack-dev-server.config.js, package.json
I accidentally included this change in a previous PR, and it was received with much tribulation!  
It didn't seem appropriate to merge it as part of an unrelated change, so here it is for real this time, in it's own, _very_ special PR. :tada: :balloon:
=> [Docs] Kill eslint preloader

package.json, src/lists/list-item.jsx
- fix  a type in listitem
- fix the inline-style-prefixer (it was failing with ListItem with the previous version)
=> [ListItem] Fix the variable name

docs/src/app/components/pages/components/Stepper/HorizontalLinearStepper.jsx, docs/src/app/components/pages/components/Stepper/Page.jsx, docs/src/app/components/pages/components/Stepper/VerticalLinearStepper.jsx, docs/src/app/components/pages/components/Stepper/VerticalLinearStepperWithOptionalStep.jsx, docs/src/app/components/pages/components/Stepper/VerticalNonLinearStepper.jsx
Update the Stepper example text to use slightly more real-world examples.
The Vertical stepper with optional step uses icons for the step labels. Alignment is suboptimal but gives a reference to improve the Stepper component later.
=> [Stepper] Update example text

CHANGELOG.md, docs/package.json, examples/browserify-gulp-example/package.json, examples/webpack-example/package.json, package.json
@callemall/material-ui Guys take a look
=> Prepare the 0.15.0-alpha.2 release

src/menus/icon-menu.jsx
Noticed this while reviewing #3732.
=> [IcomMenu] Use destructured `onKeyboardFocus` property

docs/src/app/components/pages/components/IconButton/ExampleSize.jsx, docs/src/app/components/pages/components/IconButton/Page.jsx
This closes callemall/material-ui#3061
=> [IconButton] Added IconButton size example

src/left-nav.jsx
=> [LeftNav] add callback signature; improve other prop docs

src/LinearProgress/LinearProgress.jsx
- [+] PR has tests / docs demo, and is linted (it's linted, but there are no tests / docs).
- [+] Commit and PR titles begin with [ComponentName], and are in imperative form: "[Component] Fix leaky abstraction".
- [+] Description explains the issue / use-case resolved, and auto-closes the related issue(s) (http://tr.im/vFqem) (see the issue description).
Fixes #3762
=> [LinearProgress] Prevent LinearProgress components from sharing state

src/List/List.js, src/List/ListItem.js
Hey, a bigger one for #3096.
I wasn't sure about how to represent the `this` argument in [`onNestedListToggle`](https://github.com/theosherry/material-ui/blob/8877fa728b4e1e9c591652671769280f69da0e7a/src/lists/list-item.jsx#L114), so let me know if there's a better way.
=> [List, ListItem] add callback signatures to docs; improve other props

docs/src/app/components/pages/components/TimePicker/ExampleSimple.js, docs/src/app/components/pages/components/TimePicker/Page.js, src/TimePicker/TimePicker.js
This PR adds a disabled property to TimePicker component like the one implemented for DatePicker.
Closes #3777.
=> [TimePicker] Add disabled property with example

src/Popover/Popover.js
=> [Popover] improve callback signature and other props in docs

src/AutoComplete/AutoComplete.js, src/CircularProgress/CircularProgress.js, src/IconMenu/IconMenu.js, src/RaisedButton/RaisedButton.js, src/internal/Overlay.js
This is removing some conflicting code. I have also discovered that 60 lines of the `RaisedButton` were *disabled* :scream:.
=> [Core] Fix issues with the code base so we can run the ES6 codemod

examples/browserify-gulp-example/README.md, examples/browserify-gulp-example/package.json, examples/browserify-gulp-example/src/.eslintrc, examples/browserify-gulp-example/src/app/Main.js, examples/webpack-example/README.md, examples/webpack-example/package.json, examples/webpack-example/src/app/Main.js, examples/webpack-example/webpack-dev-server.config.js, examples/webpack-example/webpack-production.config.js, package.json
Also bump some package versions, and fix a typo.
Closes #3846.
=> Add npm run lint script to examples

src/AutoComplete/AutoComplete.js
Follow this [thread](https://github.com/callemall/material-ui/pull/3858#issuecomment-204728587). Consistency is more important here
=> [AutoComplete] Stay coherent with the code base

README.md
React 1.0 will never happen so I adjusted the comment a little bit :)
=> Adjust notes about React-Tap-Event-Plugin in README

src/IconButton/IconButton.js
=> [IconButton] Fix tooltip on hover

CONTRIBUTING.md
`repositiry` should be `repository`
=> [Docs] Fix misspelling in CONTRIBUTING.md

src/List/ListItem.js
Fixes #3173
See https://github.com/callemall/material-ui/pull/3174#issuecomment-194152711
=> [ListItem] Fix duplicate prepareStyles with primaryText element

.eslintrc.yaml, docs/src/app/app.js, docs/src/app/components/ComponentDoc.js, docs/src/app/components/pages/HomeFeature.js, src/Card/Card.js, src/Dialog/Dialog.js, src/DropDownMenu/DropDownMenu.js, src/FlatButton/FlatButton.js, src/FloatingActionButton/FloatingActionButton.js, src/IconMenu/IconMenu.js, src/List/ListItem.js, src/Menu/Menu.js, src/MenuItem/MenuItem.js, src/Popover/PopoverAnimationDefault.js, src/Popover/PopoverAnimationVertical.js, src/RaisedButton/RaisedButton.js, src/TextField/EnhancedTextarea.js, src/internal/AutoLockScrolling.js, src/internal/CircleRipple.js, src/internal/EnhancedButton.js, src/internal/EnhancedSwitch.js, src/internal/TouchRipple.js, src/utils/childUtils.js, test/browser/theming-v12-spec.js
Makes the comment spacing more consistent and follow the React source code / Airbnb js convention.
=> [eslint] Enforce spaced-comment

src/RaisedButton/RaisedButton.js
=> [RaisedButton] Fix for Uncaught TypeError when tabbing onto button

src/Toggle/Toggle.js
=> [Docs] Add label PropType to Toggle for documentation

src/RaisedButton/RaisedButton.js
Hey, for #3096. I wasn't sure about some of the props here; I tried to use the best prop description wordings from the `FlatButton` and `FloatingActionButton` doc pages.
=> [RaisedButton] Add callback signatures to docs; improve other props.

.travis.yml, package.json, packages/material-ui-codemod/README.md, packages/material-ui-codemod/package.json, packages/material-ui-codemod/test.js, packages/material-ui-codemod/transforms/v0.15.0/import-path.js, packages/material-ui-codemod/transforms/v0.15.0/import-path.spec.js, packages/material-ui-codemod/transforms/v0.15.0/import-path.spec/actual.js, packages/material-ui-codemod/transforms/v0.15.0/import-path.spec/expected.js
[react-codemod](https://github.com/reactjs/react-codemod) was a great source of inspiration for this PR.
Thanks @cpojer for this amazing `jscodeshift` package.
I have been using the `import-path.js` script successfully on my code base.
=> [Core] Add a new codemod package

src/List/ListItem.js, src/styles/getMuiTheme.js
Related to #3899 
Replaced the color of the rightIcon in ListItem from `grey400` to `grey600` to match the color of the previous rightIcon
=> [ListItem] : Change color of rightIcon in the ListItem

docs/src/app/components/pages/components/Dialog/ExampleScrollable.js, docs/src/app/components/pages/components/Dialog/Page.js, src/Dialog/Dialog.js
Add border to title and actions of Dialog to follow material design guidelines.
Also add an exemple of a scrollable dialog (look like this now).
=> [Dialog] Add border to title and actions when content is scrollable

README.md, docs/src/app/components/pages/get-started/installation.md, docs/src/app/components/pages/get-started/usage.md
Fixes #4030.
Documents our new usage requirements due to theming changes in v15.
=> [Docs] Update usage docs with muiTheme instructions

src/Dialog/Dialog.js
=> [Dialog] merge title style when title it a node

CHANGELOG.md, docs/package.json, examples/browserify-gulp-example/package.json, examples/webpack-example/package.json, package.json
@callemall/material-ui This is ready, please review thanks :+1:
=> Prepare the 0.15.0-beta.2 release

docs/package.json
That's useful when using a mobile phone.
=> [Docs] Set a falsy host so we can access the docs from a remote ip

docs/src/app/components/pages/customization/themes.md
Docs listed the old import path. Fixed.
Closes #4094.
=> [Docs] Update colorManipulator imports

CONTRIBUTING.md, test/README.md
=> [Tests] Add basic README for test setup

.eslintrc.js, src/RefreshIndicator/RefreshIndicator.js, src/Slider/Slider.js, src/TimePicker/Clock.js, src/TimePicker/ClockMinutes.js
=> [eslint] Enforce jsx-first-prop-new-line

codecov.yml
Removes all the PR comments/status checks.
=> [Codecov] Explicitly disable status checks and comments in codecov.yml

src/Card/CardHeader.js
This PR contains a commit extracted from the Chip PR to update the Card Header avatar prop description.
=> [CardHeader] Standardise `avatar` prop description

docs/src/app/components/pages/discover-more/Showcase.js
=> [Docs] Fix showcase links click

CHANGELOG.md, README.md, docs/package.json, examples/browserify-gulp-example/package.json, examples/webpack-example/package.json, package.json
@callemall/material-ui This is ready to be merged. Take a look please :grin:
=> Prepare the 0.15.0 release

package.json, src/DatePicker/Calendar.js, src/DatePicker/DatePickerDialog.js, src/Dialog/Dialog.js, src/Drawer/Drawer.js, src/Popover/Popover.js, src/TextField/EnhancedTextarea.js, src/TimePicker/TimePickerDialog.js, src/internal/EnhancedSwitch.js, src/utils/withWidth.js
I have done a new release of [`<EventListener />`](https://github.com/oliviertassinari/react-event-listener) with more tests and some new features.
That shouldn't have any impact here.
=> [Core] Upgrade EventListener dependency

packages/material-ui-codemod/modules/v0.15.0/import-path.js, packages/material-ui-codemod/package.json
Fix https://github.com/callemall/material-ui/issues/4194.
=> [Codemod] Fix wrong mapping for the TableHeaderColumn

docs/src/app/components/pages/customization/themes.md
Notices some regressions in the Theme page that came up in a discussion in gitter.
=> [Docs] Fix Themes page broken link

docs/src/app/components/pages/components/Stepper/GranularControlStepper.js, docs/src/app/components/pages/components/Stepper/HorizontalNonLinearStepper.js, docs/src/app/components/pages/customization/InlineStyles.js
Fix typos in docs. No issue to close.
=> [Docs] Fix typos

src/TimePicker/Clock.js, src/TimePicker/TimeDisplay.js, src/TimePicker/TimePickerDialog.js
Remove some dead code I have noticed looking at the source code.
=> [TimePicker] Remove some dead code

docs/src/app/components/pages/get-started/usage.md
=> [Docs] Fix typo in getting started usage

docs/src/app/components/CodeExample/index.js, docs/src/app/components/pages/components/Stepper/Page.js, docs/src/app/components/pages/components/Stepper/VerticalLinearStepper.js, docs/src/app/components/pages/components/Stepper/VerticalNonLinearStepper.js
=> [Stepper] Fix vertical stepper on mobile

src/AutoComplete/AutoComplete.js, src/AutoComplete/AutoComplete.spec.js
Fix https://github.com/callemall/material-ui/issues/4195.
=> [AutoComplete] Fix filter property leaking

src/DatePicker/DatePickerDialog.js
=> [DatePicker]Fix the issue about onDismiss function will fire by handleTouchTapOk

src/List/ListItem.js, src/Menu/Menu.js, src/MenuItem/MenuItem.js
Closes #4362
This includes fixes for the following components:
Menu
Menuitem
Listitem
=> [Listitem][Menu][Menuitem] Fix theme not propagating on update

src/Snackbar/Snackbar.js, src/Snackbar/Snackbar.spec.js
Close https://github.com/callemall/material-ui/pull/4325.
=> [Snackbar] Add a new test and fix it

src/index.js
MuiThemeProvider is a public component, so it was conspicuous by its absence.
=> [MuiThemeProvider] Add to index

examples/browserify-gulp-example/src/www/index.html, examples/webpack-example/src/www/index.html
Google Fonts now recommends forcing https instead of detecting the protocol as shown on their site.
https://www.google.com/fonts#UsePlace:use/Collection:Roboto:400,300,500
=> [Examples] Update Google Fonts

package.json, src/Popover/Popover.js, src/styles/getMuiTheme.js, src/styles/themeManager.js
Using the modular lodash builds is worse when the consumer is using lodash. Using it in this way gives the same benefits as the modular builds.
=> [Core] Move to the normal lodash.

src/Avatar/Avatar.js
@mbrookes Any idea why this property was added in the first place?
=> [Avatar] Fix a layout regression

src/utils/withWidth.js
This is a simple hack. No change current behavior.
=> [withWidth] Accept width optional parameter

README.md
=> [README] Add a code coverage badge

docs/src/app/components/pages/customization/Themes.js
Closes https://github.com/callemall/material-ui/issues/4238.
=> [Docs] Fix layout broken for Themes example

.eslintrc.js, package.json
Each rule is detailed here https://github.com/lo1tuma/eslint-plugin-mocha/tree/master/docs/rules.
E.g. for @nathanmarks, that would warn if we left a debugging `only`.
=> [eslint] Add a mocha plugin to enforce good practices

src/internal/RenderToLayer.js
=> [RenderToLayer] Cleanup

src/styles/getMuiTheme.js
Looks like this one slipped through the cracks when we tackled all these a long time ago! :)
=> [Badge] Fixed incorrect color usage (primary/accent were swapped)

src/DropDownMenu/DropDownMenu.js, src/IconMenu/IconMenu.js
=> [IconMenu][DropDownMenu] Add an animated property

src/DatePicker/Calendar.js
Resolves: https://github.com/callemall/material-ui/pull/4454#discussion-diff-66521529
=> [DatePicker] Fix weekTitleDayStyle

src/DatePicker/CalendarYear.js
=> [DatePicker] Fix year overflow

docs/webpack-production.config.js
=> [Documentation] fixed webpack production build

docs/gh-pages-build.js, docs/webpack-production.config.js, examples/browserify-gulp-example/README.md, examples/browserify-gulp-example/gulp/tasks/browserify.js, examples/webpack-example/src/app/Main.js, examples/webpack-example/webpack-production.config.js
Fixes spelling mistakes in comments.
=> [Docs][Examples] Fix comment spelling mistakes

src/Slider/Slider.js, src/Snackbar/Snackbar.js
We use the `...other` name convention everywhere else.
=> [React] Fix minor spread inconsistency

src/internal/RenderToLayer.js, test/integration/RenderToLayer/RenderToLayer.spec.js
Closes https://github.com/callemall/material-ui/issues/4373.
Closes https://github.com/callemall/material-ui/pull/4534.
E.g.
=> [RenderToLayer] Fix an internal issue with React

src/AppBar/AppBar.js
Address this [comment](https://github.com/callemall/material-ui/commit/14014cfb251540622386e3db6746a4198947f04f#commitcomment-17949228).
=> [AppBar] Improve props checking to be more resilient

docs/src/app/components/pages/customization/themes.md
=> [docs/themes.md] fix typo 'muTheme' -> 'muiTheme'

src/SvgIcon/SvgIcon.js, src/styles/getMuiTheme.js
=> [SvgIcon] Add themeable color

docs/src/app/components/pages/components/SelectField/ExampleLongMenu.js, src/Chip/Chip.js, src/Menu/Menu.js, src/RaisedButton/RaisedButton.js, src/Snackbar/Snackbar.js, src/Stepper/Step.js, src/Stepper/Step.spec.js, src/Stepper/StepButton.js, src/Stepper/StepContent.js, src/Stepper/StepContent.spec.js, src/Stepper/StepLabel.js, src/TextField/EnhancedTextarea.js, src/TextField/TextField.js, src/Toolbar/ToolbarGroup.js, src/internal/CircleRipple.js, src/internal/EnhancedButton.js, src/internal/EnhancedButton.spec.js, src/internal/EnhancedSwitch.js, src/internal/ExpandTransitionChild.js, src/internal/ScaleInChild.js, test/integration/fixtures/VerticalLinearStepper.js, test/integration/stepper/verticalStepper.spec.js
Continuation of #4603 
There's still a few more left though!
=> [Core] Update several components to fix invalid props being passed

docs/src/app/components/AppNavDrawer.js
[AppNavDrawer] Links added to components in Menu
Closes #2720
Update of #3953
=> [AppNavDrawer] Links added to components in Menu

docs/src/app/components/pages/discover-more/related-projects.md
=> [Docs] Add a related project: react material ui notifications

src/SvgIcon/SvgIcon.js
=> [SvgIcon] Fix typo in src/SvgIvon/SvgIcon.js

src/DatePicker/DateDisplay.js, src/Table/Table.js, src/Table/TableBody.js, src/TextField/EnhancedTextarea.js, src/TimePicker/Clock.js, src/TimePicker/ClockPointer.js, src/TimePicker/TimePicker.js
=> [IE] Move state props access into componentWillMount for IE9/10

src/TextField/EnhancedTextarea.js, src/TextField/TextField.js
Continuation of #4620.
@oephrosinin @emohedano Thanks for starting it.
Closes #4620
Closes #4276
Closes #4331
=> [TextField] Fix multi-line overflow

CHANGELOG.md
=> Update changelog for 0.15.2

src/Checkbox/Checkbox.js, src/Checkbox/Checkbox.spec.js, src/RadioButton/RadioButton.js, src/Toggle/Toggle.js, src/internal/EnhancedSwitch.js
Continuation of #4654. @Evilcat325 Could you have a look? Thanks!
I have quite struggled with this fix, not an easy one.
- I have added a failing test and the fix
- I have done some cleanups
Closes #2983
Closes #4654
=> [EnhancedSwitched] Fix asynchronisity issues

src/MenuItem/MenuItem.js
[MenuItem] Added pointer cursor to menu items. Closes #4700
=> [MenuItem] Added pointer cursor to menu items

src/IconMenu/IconMenu.js, src/List/MakeSelectable.js, src/MenuItem/MenuItem.js, src/Toggle/Toggle.js
For some of the remaining warnings. I have noticed that some will require to introduce breaking changes to be fixed. We might just not fix them at all as migrating to the `next` branch.
Closes #4681
Closes #4694
=> [React] Fix more unknown properties warnings

CHANGELOG.md, docs/src/app/components/pages/components/CircularProgress/ExampleDeterminate.js, docs/src/app/components/pages/components/CircularProgress/ExampleSimple.js, src/CircularProgress/CircularProgress.js
Resolves #4340
- Change meaning of "size" attribute: it's now the component's diameter
in pixels.
- Add "thickness" attribute: line thickness is no longer a multiple of diameter
but an independent parameter (defaults to an absolute value).
- Remove margins around the component.
=> [CircularProgress] Update component API (breaking change)

src/Menu/Menu.js
=> [Menu] TypeError: key is undefined #4733

src/Dialog/Dialog.js, src/Drawer/Drawer.js, src/RefreshIndicator/RefreshIndicator.js, src/Snackbar/Snackbar.js, src/TextField/TextFieldLabel.js, src/internal/EnhancedButton.js, src/internal/SlideInChild.js, src/internal/Tooltip.js
=> [IE9] Switch from translate3d to translate for compatibility

ROADMAP.md
This is the first iteration for #4205. I have removed addressed issues.
@mpontikes please have a look and merge if you are happy with it.
The next iteration would be to add the issues currently addressed in the `next` branch.
I'm gonna need @nathanmarks help for this one. Or we could rely on the `milestone` system and just explain the core idea behind what we are working one.
=> [ROADMAP] Remove addressed issues

docs/site/src/demos/paper/PaperSheet.js, docs/site/src/demos/paper/paper.md
=> [Paper] Add component demo, closes #4777

docs/api/IconButton/IconButton.md, src/IconButton/IconButton.js
=> [IconButton] Fix mistake in props documentation

docs/api/Button/Button.md, docs/api/Progress/CircularProgress.md, docs/api/Table/Table.md, docs/api/Table/TableBody.md, docs/api/Table/TableCell.md, docs/api/Table/TableHead.md, docs/api/Table/TableRow.md, docs/api/Table/TableSortLabel.md, docs/api/transitions/Slide.md, docs/site/src/components/MarkdownElement.js, docs/site/src/demos/tables/EnhancedTable.js, scripts/generate-docs-markdown.js, src/Button/Button.js, src/Table/Table.js, src/Table/TableBody.js, src/Table/TableCell.js, src/Table/TableHead.js, src/Table/TableRow.js, src/Table/TableSortLabel.js, src/index.js, src/styles/theme.js
=> [Table] Finish documenting new table

.travis.yml, docs/api/Checkbox/Checkbox.md, docs/site/src/demos/selection-controls/Checkboxes.js, docs/site/src/index.js, src/Checkbox/Checkbox.js, src/Checkbox/Checkbox.spec.js
=> [Checkbox] Finish next port

src/AutoComplete/AutoComplete.js, src/AutoComplete/AutoComplete.spec.js, test/integration/AutoComplete/AutoComplete.spec.js, test/utils/dom.js
=> [AutoComplete] Call onNewRequest once the animation is done

ROADMAP.md
@callemall/material-ui Please have a look at it. Any feedback welcomed!
Closes #4205.
=> [ROADMAP] Update to what the core team is working on

src/transitions/Collapse.js, src/transitions/Collapse.spec.js
=> [Collapse] Fix double animation in safari

src/GridList/GridTile.js
It's not a complex PR, just fixed a simple issue with rtl.
=> [GridList] Fixed rtl problem.

CHANGELOG.md, docs/package.json
=> [CHANGELOG] Upgrade for the v0.15.3 release

src/Ripple/Ripple.js, src/Ripple/Ripple.spec.js
=> [Ripple] Working on optimizations and UX

src/Slider/Slider.js, src/Slider/Slider.spec.js
Fixes https://github.com/callemall/material-ui/issues/3619 and related https://github.com/callemall/material-ui/issues/4812 following @marcuswhit's suggested fix.
=> [Slider] Fix bug with Slider percent not updating when max prop changes

CHANGELOG.md, docs/src/app/AppRoutes.js, docs/src/app/components/AppNavDrawer.js, docs/src/app/components/pages/components/BottomNavigation/ExampleSimple.js, docs/src/app/components/pages/components/BottomNavigation/Page.js, docs/src/app/components/pages/components/BottomNavigation/README.md, src/BottomNavigation/BottomNavigation.js, src/BottomNavigation/BottomNavigation.spec.js, src/BottomNavigation/BottomNavigationItem.js, src/BottomNavigation/index.js, src/styles/getMuiTheme.js
Fixes #3712.
I wanted to get the ball rolling on this component. There's still plenty left to add, but at least with this PR we'll have one style of bottom navigation available.
=> [BottomNavigation] Initial implementation

docs/src/app/components/pages/components/BottomNavigation/ExampleSimple.js, src/BottomNavigation/BottomNavigation.js, src/BottomNavigation/BottomNavigation.spec.js, src/BottomNavigation/BottomNavigationItem.js, src/BottomNavigation/BottomNavigationItem.spec.js
@jacksonrayhamilton I have done some improvements to the component.
- Add missing prefixes
- Add missing support for svg icons
- Fix issue with overriding properties
- Removing regular DOM properties to the documentation (`className` and `style`)
- Improving the test coverage
- Using a syntax closer to the `next` branch
=> [BottomNavigation] Makes us closer to the next branch

src/styles/getMuiTheme.js
[DatePicker] Changed background color for year selection to make unselected year visible in dark theme. Closes #4939
=> [DatePicker] Changed background color for year selection

src/Popover/PopoverAnimationDefault.js
=> [PopoverAnimationDefault] update component name to reflect file name

scripts/run-travis-tests.sh
=> [core] shorten coveralls command

.travis.yml, scripts/run-travis-tests.sh, src/Menu/Menu.js, src/Menu/Menu.spec.js, src/Menu/MenuList.js, src/Menu/MenuList.spec.js
=> [Menu][MenuList] Split out the menu list functionality 

src/BottomNavigation/index.js, src/index.js
Fixing https://github.com/callemall/material-ui/issues/4969 by adding BottomNavigation and BottomNavigationItem to index.
Note: this is my first time working with these exports and I only mostly understand how they work, so please take a second to glance over and make sure I didn't do anything dumb... :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/callemall/material-ui/4980)
=> [BottomNavigation] Add the main component and it's Item to index

docs/site/src/demos/progress/Circular.js, docs/site/webpack.dev.server.js, src/Drawer/Drawer.js, src/Progress/CircularProgress.js
I still have to address an issue with iOS:
=> [CircularProgress] Improve the animation

src/IconMenu/IconMenu.js
@joeadcock I have added a warning to help debug this issue in `DEV` mode.
Thanks for raising it.
Closes #4934.
=> [IconMenu] Warn when not providing an IconButton to iconButtonElement

docs/src/app/AppRoutes.js, docs/src/app/app.js
The following links are relevant.
https://github.com/reactjs/react-router/commit/b213022bf0429e72f7c9a838ad71048cce41e997
https://github.com/reactjs/react-router/commit/0bfb31fd5da99d5f66253d883e618df225767a0b
=> [docs] Fix 404 links

docs/src/app/components/pages/components/Checkbox/ExampleSimple.js, src/Checkbox/Checkbox.js
I have changed a bit the transition durations so we can use icons of different shapes.
@atoko Could you have a look?
@brandonmp I have added an example for your specific use case.
Closes #4948.
Closes #4997.
=> [Checkbox] Tweak the transition to allow different shapes

src/Table/TableRowColumn.js
[TableRowColumn] Tooltip visible with TableRowColumn. Changed `overflow` to `visible` for `tooltip` to be shown inside the `table`. Closes #4671
=> [TableRowColumn] Tooltip visible with TableRowColumn

src/List/NestedList.js, src/List/NestedList.spec.js
Thanks @zhangjunah for raising this issue.
Closes #5007.
Closes #5008.
=> [NestedList] Prevent rendering the children when the nested list is hidden

CHANGELOG.md, docs/src/app/components/AppNavDrawer.js, docs/src/app/components/pages/components/List/ExampleSelectable.js, src/List/index.js, src/List/makeSelectable.js, src/index.js, test/integration/List/selectableList.spec.js
=> [List] Rename MakeSelectable to makeSelectable

src/TimePicker/ClockNumber.js, src/internal/TouchRipple.js, src/styles/getMuiTheme.spec.js, src/utils/rtl.js, src/utils/rtl.spec.js
@denistakeda @aahan96 Can you have a look at this PR? Thanks.
Closes #5021.
Closes #5020.
Closes #5001.
Closes #4320.
=> [RTL] Add a new directionInvariant property

src/RefreshIndicator/RefreshIndicator.js
The PR is linted, but doesn't contain tests as I don't know how are you testing your components and I've never tested react components before.
This is for fixing issue #5034
=> [RefreshIndicator] Passing other props to the root element, fixes #5034

src/RaisedButton/RaisedButton.js
=> [RaisedButton] Fixes #5065, Warning: Unknown props on <button>

README.md
Updated the link for "Override individual component styles via the style prop" . . . old link took you nowhere.
=> README.md updated broken link

docs/src/app/components/pages/discover-more/Showcase.js
It's been a pleasure to work with material-ui, thanks for the great work!
=> [doc] Add reference to admin-on-rest in showcase section

docs/src/app/components/pages/components/DatePicker/ExampleInternational.js, src/DatePicker/Calendar.js, src/DatePicker/CalendarMonth.js, src/DatePicker/CalendarYear.js, src/DatePicker/CalendarYear.spec.js, src/DatePicker/DateDisplay.js, src/DatePicker/DateDisplay.spec.js, src/DatePicker/DayButton.js, src/DatePicker/DayButton.spec.js, src/DatePicker/YearButton.js, src/DatePicker/dateUtils.js
=> [DatePicker] Improve the i18n support

src/TimePicker/ClockPointer.js
=> [TimePicker] Fix clock pointer mark off centre of pointer line

docs/src/app/components/pages/get-started/server-rendering.md
=> [docs] Update the server-rendering section

src/Chip/Chip.spec.js, src/FontIcon/FontIcon.spec.js, src/SvgIcon/SvgIcon.spec.js, src/Tabs/Tabs.js, src/Tabs/Tabs.spec.js
Add a failing test fixed by #4635.
=> [Tabs] Add a test following the latest fix

docs/src/app/components/pages/components/Divider/Page.js
=> [Divider] Typo fix for Divider's page

src/TimePicker/TimePickerDialog.js, src/TimePicker/TimePickerDialog.spec.js
Closes https://github.com/callemall/material-ui/issues/5211.
=> [TimePickerDialog] fix #5211 invalid call to onDismiss

docs/src/app/components/pages/discover-more/related-projects.md
Yet another composed component from us. :smiley:
=> [Docs] Add material-auto-rotating-carousel to related projects

src/AppBar/AppBar.js, src/AppBar/AppBar.spec.js
=> [AppBar] Fix onTouchTap handler

CHANGELOG.md, package.json
=> [release] Prepare v0.16.0-rc2

.eslintrc.js, docs/site/src/components/AppRouter.js, docs/site/src/demos/tables/BasicTable.js, docs/site/src/demos/tables/EnhancedTable.js, docs/site/src/utils/helpers.js, src/Dialog/DialogContent.js, src/Dialog/DialogTitle.js, src/List/ListItemSecondaryAction.spec.js, src/List/ListItemText.js, src/Ripple/Ripple.spec.js, src/TextField/TextField.spec.js, src/internal/ButtonBase.js, src/internal/ButtonBase.spec.js, src/internal/Modal.spec.js, src/internal/Popover.spec.js, src/internal/Portal.spec.js, src/internal/SwitchBase.spec.js, src/internal/modalManager.js, src/styles/breakpoints.js, src/styles/palette.js, src/styles/theme.js, src/transitions/Collapse.spec.js, src/transitions/Fade.js, src/utils/helpers.js, test/integration/Menu.test.js, test/integration/MenuList.test.js, test/integration/RadioGroup.test.js, test/integration/fixtures/perf/TimeWaster.js
A new *eslint* iteration above the AirBnb guidelines.
=> [eslint] reduce the gap with the airbnb convention

docs/site/src/components/AppDrawer.js, test/README.md, test/cli.js, test/index.js, test/mocha.js, test/mocha.watch.js
Address https://github.com/callemall/material-ui/pull/5269#issuecomment-250579140.
=> [test] Improve the solution

docs/src/app/components/pages/components/RefreshIndicator/ExampleLoading.js, docs/src/app/components/pages/components/RefreshIndicator/ExampleReady.js, docs/src/app/components/pages/discover-more/related-projects.md, package.json, src/List/ListItem.js, src/List/makeSelectable.js, src/Popover/PopoverAnimationVertical.js, src/Tabs/Tabs.js
Remove the `lodash` dev dependency following #5308.
Also fix the build as raised by #5302.
=> [npm] Remove the lodash dev dependency

docs/src/app/components/pages/components/GridList/ExampleSimple.js, docs/src/app/components/pages/components/GridList/ExampleSingleLine.js, docs/src/app/components/pages/components/GridList/Page.js
Thanks @sottar.
Closes #5258.
Closes #5300.
=> [docs] Add an One line example for GridLists

src/FloatingActionButton/FloatingActionButton.js
=> [FloatingActionButton] set touch flag in handleTouchEnd

src/TextField/TextField.js, src/TextField/TextField.spec.js
=> [TextField] Fix a failing test with the controlled behavior

src/RefreshIndicator/RefreshIndicator.js
Fix a regression introduced by #5054.
Closes #5299.
=> [RefreshIndicator] - Fix Unknown props react warning 

src/IconMenu/IconMenu.js
Small fix, but it took me longer than it should have to figure out
that this error was related to the IconMenu element.
=> [IconMenu] Updating error message for IconButton

docs/src/app/components/pages/components/SelectField/ExampleCustomLabel.js, docs/src/app/components/pages/components/SelectField/ExampleError.js, docs/src/app/components/pages/components/SelectField/ExampleFloatingLabel.js, docs/src/app/components/pages/components/SelectField/ExampleLongMenu.js, docs/src/app/components/pages/components/SelectField/ExampleNullable.js, docs/src/app/components/pages/components/SelectField/ExampleSimple.js, docs/src/app/components/pages/components/SelectField/Page.js, src/MenuItem/MenuItem.js, src/MenuItem/MenuItem.spec.js
Continuation of #5302.
@jpetitcolas Thanks for the original PR.
Closes #5302.
=> [MenuItem] Add min-height to MenuItem to allow null options in SelectItem

src/FloatingActionButton/FloatingActionButton.js, src/FloatingActionButton/FloatingActionButton.spec.js
@ashl1 The regression was introduced by #5246.
=> [FloatingActionButton] Fix a regression on the children property

docs/src/app/components/pages/customization/themes.md, src/styles/index.js
I have also removed some examples directly using the context.
It's still considered an advanced feature of React.
The community advises making it an **implementation detail**.
It's what I'm doing here.
Closes #5004.
=> [docs] Document the muiThemeable HOC

.eslintignore, .travis.yml, README.md, circle.yml, docs/site/src/demos/tables/EnhancedTable.js, package.json, src/Button/Button.js, test/e2e/docs/dialogs.js, test/e2e/docs/home.js, test/regressions/test.js
This means we can access artifacts and therefore screenshots more easily.
=> Use circleCI for next branch

src/Popover/Popover.js, src/Popover/Popover.spec.js, src/Popover/PopoverAnimationDefault.js, src/Popover/PopoverAnimationVertical.js
@nathancahill Thanks for the original PR.
I have added some tests and fixes some issues.
Closes #5337.
=> [Popover] Add missing animated=false

src/DropDownMenu/DropDownMenu.js, src/DropDownMenu/DropDownMenu.spec.js
@smcguinness Thanks for the original PR
This is a simple continuation
Closes #5397
=> [DropDownMenu] Fix usage of null child

src/utils/withWidth.js, src/utils/withWidth.spec.js
Fix the SSR [issue](https://github.com/callemall/material-ui/pull/5154#discussion_r83549688) raised by @Brian-Gaffney.
Thanks @neoziro for the idea.
=> [withWidth] Fix the SSR reconciliation

src/TextField/EnhancedTextarea.js, src/TextField/TextField.js
I'm not really happy with this fix.
The implementation has taken some wrong decisions.
Anyway, it's much better in the `next` branch.
Closes #5410.
=> [TextField] Fix leaking appearance property on a div

CHANGELOG.md, ROADMAP.md, docs/package.json
=> [release] prepare v0.16.1

src/Stepper/Stepper.js, src/Stepper/Stepper.spec.js
This is a continuation of #5407.
Thanks @bennyhobart for raising this point!
Closes #5407.
=> [Stepper] Fix children count method

src/Toolbar/ToolbarTitle.js
Fixes #5333 
Happy #hacktoberfest!
=> [ToolbarTitle] Take font family from base theme

src/AppBar/AppBar.js, src/DatePicker/dateUtils.js, src/FloatingActionButton/FloatingActionButton.js, src/Popover/Popover.js, src/RadioButton/RadioButtonGroup.js, src/Stepper/StepContent.js, src/Tabs/Tabs.js, src/TextField/TextField.js, src/internal/EnhancedSwitch.js, src/utils/callOnce.js
This component used to support invalid `anchorEl` property.
I have checked #3806, that change seems to be fine.
=> [Popover] Fix support for invalid anchorEl

src/GridList/GridList.js, src/GridList/GridList.spec.js
This is a continuation of #5051.
I'm following @nathanmarks comment regarding allowing `'auto'`.
Closes #5051.
Closes #4492.
=> [GridList] Add the support for cellHeight="auto"

docs/src/app/components/pages/components/FloatingActionButton/ExampleSimple.js, docs/src/app/components/pages/components/FloatingActionButton/Page.js, src/FloatingActionButton/FloatingActionButton.js, src/FloatingActionButton/FloatingActionButton.spec.js, src/utils/childUtils.js
=> [FloatingActionButton] Fix regression with n children

src/TextField/TextField.js
Closes #5381. See discussion in that bug.
=> [TextField] Fix floatingLabelFocusStyle when floatingLabelFixed is true

src/List/ListItem.js, src/List/ListItem.spec.js
=> [ListItem] Fix an issue with the controlled behavior

src/Toolbar/ToolbarGroup.js, src/Toolbar/ToolbarSeparator.js
This is a continuation of #5442.
It's following the same approach than on the `next` branch.
Thanks @colllin for raising this point.
Closes #5442.
=> [ToolbarGroup] Fix vertical alignment

src/internal/modalManager.js, src/internal/modalManager.spec.js, test/utils/dom.js
Solving
> ReferenceError: window is not defined
at createModalManager (/Users/oliviertassinari/SplitMe/node_modules/material-ui-build-next/src/internal/modalManager.js:26:15)
at Object.<anonymous> (/Users/oliviertassinari/SplitMe/node_modules/material-ui-build-next/src/internal/Modal.js:23:22)
=> [Dialog] Fix an issue with the SSR

src/AutoComplete/AutoComplete.js, src/AutoComplete/AutoComplete.spec.js
=> [AutoComplete] Fire onUpdateInput when an item from the dropdown is selected

src/Table/Table.js
Table silently omits components that it does not expect. This PR adds warning, so developer can be aware what's happening without need to check source code of the Table component.
=> [Table] Warning on rendering attempt of unsupported child

docs/src/app/components/pages/components/GridList/ExampleSingleLine.js, src/GridList/GridTile.js, src/GridList/GridTile.spec.js
This is a continuation of #5317.
Thanks @sottar for it!
Closes #5317
=> [GridTitle] Add a titleStyle property

.eslintignore, flow/interfaces/mocha.js, flow/stubs/url-loader.js, package.json, packages/material-ui-codemod/test.js, test/cli.js, test/mocha.js, test/regressions/runTest.js, test/selenium.js, test/utils/createShallowWithContext.js
=> [eslint] Lint more files

docs/site/src/demos/dialogs/AlertDialog.js, docs/site/src/demos/dialogs/AlertDialogSlide.js, src/Dialog/Dialog.js, src/Dialog/Dialog.spec.js
Fix the examples on the docs site.
=> [Dialog] add a paperClassName property

package.json
=> include `react-tap-event-plugin@^2.0.0` for `react@^15.4.0`

src/List/ListItem.js
Set `touch` flag to `true` on `handleTouchEnd` to fix hover on touch devices.
=> [ListItem] Fix hover on touch devices

docs/src/app/components/pages/components/AutoComplete/Page.js
=> [docs] fix typo with sentence for AutoComplete

src/List/makeSelectable.js
=> [makeSelectable] Fix missing check for existence of `onChange` 

docs/api/TextField/TextField.md, docs/site/src/demos/text-fields/RequiredTextField.js, docs/site/src/demos/text-fields/text-fields.md, docs/site/webpack.dev.config.js, src/TextField/TextField.js, src/TextField/TextField.spec.js, test/regressions/site/package.json, test/regressions/site/src/tests/TextField/TextFieldRequired.js, test/regressions/site/webpack.dev.config.js
=> [TextField] Improve the required feature

docs/site/package.json, docs/site/webpack.dev.config.js, docs/site/webpack.prod.config.js
@bochen2014 I'm taking most of your changes into `next`.
Any plan to keep http://material-ui-next.azurewebsites.net up to date with the current HEAD?
That's quite engaging for users and that allow everybody to follow our progress 🐴 .
Close #5352.
=> [docs] Makes it run locally on windows box

docs/site/src/demos/lists/FolderList.js, docs/site/src/demos/lists/SimpleList.js, docs/site/src/demos/lists/lists.md
Some example to docs for List component. Showing how to use multi line ListItem.
=> [Docs] Add more examples to list

src/SelectField/SelectField.js
=> [SelectField] Add listStyle prop

src/IconMenu/IconMenu.js
=> [IconMenu] Add listStyle prop

src/DropDownMenu/DropDownMenu.js, src/DropDownMenu/DropDownMenu.spec.js
This is a continuation of #4378.
Thanks @liesislukas for the original PR.
Fix #4377
Fix #4378
=> [DropDownMenu] Add an onClose callback property

src/TextField/TextField.js, src/TextField/TextField.spec.js, src/TextField/TextFieldUnderline.js
This is a continuation of #4756.
Thanks @andrewdormi for the PR.
Fix #4756.
=> [TextField] Fix errorStyle priority

src/AutoComplete/AutoComplete.js, src/AutoComplete/AutoComplete.spec.js
This is a continuation of #5294.
Thanks @alexprice91 for the original PR.
Fix #5294.
=> [AutoComplete] Add an onClose callback property

docs/site/src/demos/dialogs/ConfirmationDialog.js
Set the maxHeight so that the last `ListItem` is truncated to give a vissual cue that the list is scrollable.
=> [next][Dialog] Adjust Confirmation Dialog maxHeight

src/List/List.js
=> [List] Edit padding in styles object.

src/TextField/TextField.js, src/TextField/TextField.spec.js, src/TextField/TextFieldLabel.js
This is a continuation of #5641
Thanks @rockad for the original PR
Fix #5641.
=> [TextField] Add a floatingLabelShrinkStyle property

docs/site/src/demos/tables/EnhancedTable.js
Not important, just an exercise in getting my head back into JS & React!
The refactor is in two parts: the first to move the column data in to an array, the second to follow the existing code style and use a function create the object keys. (Not totally convinced the latter is of benefit in terms of either readability or conciseness.\0
=> [next][docs][Table] Refactor Enhanced example header

src/LinearProgress/LinearProgress.js
Updated the prop description for the `color` prop. It was previously using the description for `mode`
=> [Docs] Fix Linear Progress Prop Documentation

package.json
Fixes #5679, commit ac18a75b0d20f4f1b3991364c20d76a57c5c0d89 removed needed dependency.
=> [next][package.json] add back the necessary jss-preset-default

src/AutoComplete/AutoComplete.js, src/AutoComplete/AutoComplete.spec.js
=> [AutoComplete] Fix the controlled behavior

src/Stepper/StepLabel.js
As discussed with @nathanmarks, it would be better to use the `border-box`.
Fix #4263.
=> [StepLabel] Address a box model issue

src/TextField/TextFieldLabel.js
Removal of this style was missed in the refactoring to LabelBase.
=> [TextFieldLabel] remove dead style

.flowconfig, docs/site/package.json, docs/site/src/demos/tabs/BasicTabs.js, docs/site/src/demos/tabs/CenteredTabs.js, docs/site/src/demos/tabs/FullWidthTabs.js, docs/site/src/demos/tabs/IconLabelTabs.js, docs/site/src/demos/tabs/IconTabs.js, docs/site/src/demos/tabs/tabs.md, docs/site/src/pages/Home.js
=> [docs] Improve the demos of the Tabs component

docs/src/app/components/pages/discover-more/related-projects.md
=> [docs] Add link to babel-plugin-material-ui

CONTRIBUTING.md
Fix small typo on CONTRIBUTING.md
=> Fix CONTRIBUTING typo

docs/src/app/components/pages/get-started/required-knowledge.md
=> [Docs] Remove extra quotation mark

docs/src/app/components/pages/get-started/required-knowledge.md
"quick and brief introduction" - either would be fine, both is redundant and unnecessary. 😆
=> [Docs] Remove redundant words.

docs/site/src/demos/dividers/InsetDividers.js, docs/site/src/demos/dividers/ListDividers.js, docs/site/src/demos/dividers/dividers.md
=> [Docs] Add dividers docs

src/utils/iOSHelpers.spec.js
=> [iOSHelpers] Fix typo in the iOSHelpers.spec.js.

src/utils/withWidth.spec.js
=> [withWidth] Fix typo in the withWidth.spec.js

docs/src/app/components/pages/discover-more/related-projects.md
=> [Docs] Added payment components to related-projects.md

docs/site/package.json, docs/site/src/components/AppDrawer.js, docs/site/src/components/AppDrawerNavItem.js, docs/site/src/components/AppFrame.js, docs/site/src/components/Demo.js, docs/site/src/components/MarkdownDocs.js, docs/site/src/components/MarkdownElement.js, docs/site/src/pages/Home.js
Fixing minor issues I have noticed after working on Doctolib-UI during 3 days.
It's 100% base on the `next` documentation implementation. That's working great for us.
Good work @nathanmarks  👏 .
=> [docs] Cleanup some minor stuff after building Doctolib-UI

src/FlatButton/FlatButton.js, src/FloatingActionButton/FloatingActionButton.js, src/IconButton/IconButton.js, src/RaisedButton/RaisedButton.js, src/Tabs/Tabs.js, src/internal/EnhancedButton.js
The regression was introduced by #5868. The ripples were no longer showing up on the Tabs component.
=> [Tabs] Fix a regression

docs/site/src/pages/layout/responsive-ui/GuttersLayout.js, src/Layout/Layout.js
=> [Layout] Remove the false value from behing valid

src/Layout/Layout.js, src/Layout/Layout.spec.js
Fixes https://github.com/callemall/material-ui/issues/5925#issuecomment-272525865
=> [Layout] Fix the xs size

src/DropDownMenu/DropDownMenu.js, src/DropDownMenu/DropDownMenu.spec.js, src/SelectField/SelectField.js
This is a continuation of #4966
Thanks @caesay for the original PR.
It would be awesome if you could have a look at it, same for @petermikitsh.
Closes #4966.
Closes #5498.
=> [DropDownMenu] Add keyboard accessibility

src/Table/Table.js
=> [Table] remove useless padding

src/Stepper/StepLabel.js
=> [Stepper] Add font family from base theme

docs/api/Card/CardHeader.md, docs/api/Chip/Chip.md, docs/api/Input/Input.md, docs/api/Text/Text.md, docs/api/TextField/TextField.md, docs/api/TextField/TextFieldLabel.md, docs/site/src/components/AppDrawerNavItem.js, docs/site/src/components/AppFrame.js, docs/site/src/demos/tables/EnhancedTable.js, src/Card/CardHeader.js, src/Chip/Chip.js, src/Input/Input.js, src/Ripple/TouchRipple.js, src/Text/Text.js, src/TextField/TextField.js, src/TextField/TextFieldLabel.js, test/regressions/site/src/TestViewer.js
=> [core] Add missing default proptypes

docs/src/app/components/pages/discover-more/related-projects.md
Added our rating component, composed with IconButtons, to the related projects page.
[Material UI Rating](https://github.com/TeamWertarbyte/material-ui-rating)
A demo is available via [storybook](https://teamwertarbyte.github.io/material-ui-rating/)
```shell
npm i --save material-ui-rating
```
```js
import { Rating } from 'material-ui-rating'
// ...
render() {
return(
<div>
<Rating
value={3}
max={5}
onChange={(value) => console.log(`Rated with value ${value}`)}
/>
</div>
)
}
```
|Name            |Type        |Default     |Description
|----------------|------------|------------|--------------------------------
|max             | `number`   | 5          | The max value of the rating bar.
|onChange*       | `function` |            | Fired when a value is clicked.
|style           | `object` …
=> [Docs] Added rating component to related-projects.md

docs/site/src/demos/dialogs/FullScreenDialog.js, docs/site/src/demos/dialogs/dialogs.md, src/Dialog/Dialog.js, src/Dialog/Dialog.spec.js, src/svg-icons/close.js
Add a fullscreen prop to dialog https://material.io/guidelines/components/dialogs.html#dialogs-full-screen-dialogs.
=> [Dialog] Add fullscreen prop

docs/api/Layout/Layout.md, docs/api/Text/Text.md, scripts/generate-docs-markdown.js, src/Layout/Layout.js
=> [Layout] Improve the docs generation

src/DropDownMenu/DropDownMenu.js, src/DropDownMenu/DropDownMenu.spec.js
=> [DropDownMenu] Allow custom FontIcon child

CHANGELOG.md, package.json
I have seen many people trying to install `material-ui@next` in order to test out the `next` branch.
I think that it's time to do our first beta release.
=> [npm] v1.0.0-beta.1

src/Layout/Layout.js
We can't assume anything about the box-sizing approach used by our users.
I'm using the `content-box` on my app, while the documentation is using the `border-box` model.
=> [Layout] Explicit the box-sizing dependency

src/Table/TableBody.js
=> [Table] Fix typo in the documentation

docs/src/app/components/pages/components/Divider/Page.js
=> [Docs] fix typo for the Divider's page.

src/utils/customPropTypes.js
=> [propTypes] remove stringOrNumber

docs/site/src/demos/paper/PaperSheet.js, docs/site/src/demos/tables/BasicTable.js, docs/site/src/demos/tables/EnhancedTable.js, src/AppBar/AppBar.js, src/AppBar/AppBar.spec.js, src/Card/Card.js, src/Card/Card.spec.js, src/Dialog/Dialog.js, src/Drawer/Drawer.js, src/Paper/Paper.js, src/Paper/Paper.spec.js, src/internal/Popover.js, src/internal/Popover.spec.js, test/regressions/site/src/tests/Dialog/AlertDialog.js, test/regressions/site/src/tests/Menu/SimpleMenuList.js
=> [Paper] renamed zDepth -> elevation everywhere

docs/api/Badge/Badge.md, src/Badge/Badge.js
[docs] added simple example in the Badge API
=> [docs] add simple example in the Badge API

src/AppBar/index.js, src/Badge/index.js, src/Divider/index.js, src/Drawer/index.js, src/IconButton/index.js, src/Layout/index.js, src/Paper/index.js, src/index.js, src/index.spec.js, src/styles/index.js
Added missing exports to get a complete UMD-bundle. Not sure about the SVG-icons though. Any ideas / wishes about that? Should they be top-level exports, or e. g. sub "styles"?
=> add exports to index.js for inclusion in webpack bundle

src/Divider/Divider.js
=> [Divider] Remove dead code

docs/site/src/demos/buttons/FlatButtons.js, docs/site/src/demos/buttons/FloatingActionButtons.js, docs/site/src/demos/buttons/IconButtons.js, docs/site/src/demos/buttons/RaisedButtons.js, docs/site/src/demos/chips/Chips.js, docs/site/src/demos/chips/ChipsArray.js, docs/site/src/demos/dialogs/FullScreenDialog.js, docs/site/src/demos/tabs/BasicTabs.js, docs/site/src/demos/tabs/CenteredTabs.js, docs/site/src/demos/tabs/DisabledTabs.js, docs/site/src/demos/tabs/FullWidthTabs.js, docs/site/src/demos/tabs/IconLabelTabs.js, docs/site/src/demos/tabs/IconTabs.js, src/Form/FormGroup.js
Fix some screen where the UI seems broken on small screen.
=> [docs] Improve the user experience on mobile

src/Progress/LinearProgress.js, src/Progress/LinearProgress.spec.js
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-valuenow_attribute
=> [LinearProgress] Add an accessibility property

src/FloatingActionButton/FloatingActionButton.js
=> [docs] Add onTouchTap documentation for FloatingActionButton

src/RaisedButton/RaisedButton.js
=> [docs] Add onTouchTap documentation for RaisedButton

src/styles/transitions.js
=> [Styles] Fix typos in styles/transitions pointed out in issue

packages/icon-builder/copy-files.js
Name consistent with parent library (material-ui).
=> [svg-icons] Change target package name

src/FlatButton/FlatButton.js
=> [docs] Update documentation for containerElement in FlatButton

package.json, test/karma.conf.js, yarn.lock
This is a continuation of #6226.
Closes #1333.
=> [test] Integration of test suite to run on BrowserStack

docs/customization/api.md, docs/customization/composition.md, docs/site/src/components/AppRouter.js, docs/site/src/components/MarkdownElement.js
=> [docs] Add an API section

docs/api/Avatar/Avatar.md, docs/api/Button/Button.md, docs/api/Dialog/Dialog.md, docs/api/Drawer/Drawer.md, docs/api/Input/Input.md, docs/api/Layout/Layout.md, docs/api/List/List.md, docs/api/List/ListItem.md, docs/api/Menu/Menu.md, docs/api/Menu/MenuItem.md, docs/api/Progress/LinearProgress.md, docs/api/Tabs/TabIndicator.md, docs/api/Tabs/Tabs.md, docs/api/Text/Text.md, docs/api/TextField/TextField.md, docs/api/transitions/Collapse.md, docs/api/transitions/Fade.md, docs/api/transitions/Slide.md, scripts/generate-docs-markdown.js, src/Avatar/Avatar.js, src/Button/Button.js, src/Input/Input.js, src/Layout/Layout.js, src/List/List.js, src/List/ListItem.js, src/Menu/MenuItem.js, src/Text/Text.js, src/internal/ButtonBase.js
Close to the react-bootstrap [validator](https://github.com/react-bootstrap/react-prop-types/blob/master/src/elementType.js). We now take advantage of [React.isValidElement](https://github.com/facebook/react/blob/master/src/isomorphic/classic/types/ReactPropTypes.js#L290).
=> [docs] Normalize the container property

webpack.config.js
Fix js extension while.
https://unpkg.com/material-ui@1.0.0-alpha.6/dist/
The files are missing a dot.
=> Add correct extension

src/Ripple/Ripple.js, src/Ripple/Ripple.spec.js, src/Ripple/TouchRipple.js, src/Ripple/TouchRipple.spec.js
=> [Ripple] Improve the animation

src/styles/colors.js
=> [color] Add blueGrey color

docs/site/src/pages/style/typography/typography.md
=> [Docs] Fix typo

docs/site/src/pages/style/color/Color.js, docs/site/src/pages/style/color/color.md, docs/site/src/pages/style/icons/Icons.js
- Some small changes following #6254.
- Remove dead code
- Simplify logic
- Increase consistency
- Make it more usable/responsive
=> [docs] Small changes on the Color

src/Paper/Paper.js
=> [Paper] Minor Code cleanup

src/Toolbar/ToolbarTitle.js
@alecdwm Thanks for the original PR.
Closes #6276.
Closes #5175.
=> [Toolbar] Allow node to be used in text property

src/Button/Button.js
This is what `FlatButton` looks like of we follow the spec more closely. 
Closes #6293 
Replaces #6294
=> [Button] Use faded text color for hover state

test/README.md
=> [test] Add more details on the test suite

src/Drawer/Drawer.js, src/Drawer/Drawer.spec.js, test/index.js, test/utils/consoleError.js
- Added test coverage for the <Drawer/> width propType as well.
- The purpose of this PR is to address and close Issue #6304
=> [Drawer] Allowing percentages width

packages/icon-builder/.gitignore, packages/icon-builder/build/README.md, packages/icon-builder/copy-files.js, packages/icon-builder/package.json
Transpile ES2015 icons
~~Include `src` in built package~~
Add README
Add a .gitignore
=> [SvgIcons] Update build

src/styles/breakpoints.js, src/styles/breakpoints.spec.js
=> [style] Expose the between breakpoints helper

src/Dialog/Dialog.spec.js
=> [Dialog] Test transition prop not a function

src/IconButton/IconButton.spec.js
Testing of Icon Children is important as they have a specific class choosing mechanism
=> [IconButton] Add test for rendering Icon children

src/Ripple/TouchRipple.spec.js
=> [TouchRipple] Add tests for edge cases

src/GridList/GridTile.js
Added `subtitleStyle` property to GridTile.
=> [GridTile] Add support `subtitleStyle`.

docs/src/app/components/pages/discover-more/related-projects.md
=> [Docs] Add Electrode to related projects

docs/src/pages/component-demos/cards/cards.md
The issue was raised by @JeremyIglehart. Thanks!
=> [docs] Link to the Collapse documentation

src/Input/Input.spec.js
=> [Input] Add tests for componentDidMount()

docs/src/app/components/pages/components/AutoComplete/ExampleMenuProps.js, docs/src/app/components/pages/components/AutoComplete/Page.js, src/AutoComplete/AutoComplete.js
=> [AutoComplete] Add menuItemStyle as propType

docs/src/components/MarkdownDocs.js, docs/src/components/MarkdownElement.js
=> [docs] Add a 'edit this page' button

docs/src/components/AppDrawer.js, docs/webpack.dev.config.js, docs/webpack.prod.config.js, docs/webpackBaseConfig.js
=> [docs] Display the current version

src/styles/MuiThemeProvider.spec.js
=> [MuiThemeProvider] Add test for for componentWillUpdate

package.json, scripts/run-circle-tests.sh, yarn.lock
It's an early attempt of integrating the service.
Builds will appears here https://www.argos-ci.com/callemall/material-ui.
=> [test] Add argos-ci

docs/src/components/AppDrawer.js
Inspired by [React](https://facebook.github.io/react/).
=> [docs] Link version number to release notes

src/Menu/Menu.js, src/Menu/Menu.spec.js
=> [Menu] Add tests for handleEnter()

src/styles/transitions.spec.js
=> [transitions] Add test coverage for getAutoHeightDuration

README.md
Caption broke on this commit 9f8abc52780fb0a405c8100cd1726b8336544704
=> Fixed broken README caption

.github/ISSUE_TEMPLATE.md
Previously linked webpackbin locked in "live" mode, and also had an extraneous `iconClassNameRight` prop in `AppBar` & duplicate html `lang` attribute.
=> [github] Update ISSUE_TEMPLATE webpackbin

circle.yml, scripts/run-circle-tests.sh
PR motivated by #6502. That's doing [the job](https://www.argos-ci.com/callemall/material-ui/builds/2142):
=> [test] Makes sure argos run even if diff fails

src/utils/helpers.spec.js
=> [utils] Add test coverage for throttle

docs/package.json, docs/src/app/components/pages/components/DatePicker/ExampleInternational.js, docs/webpack-dev-server.config.js, docs/webpack-production.config.js, src/DatePicker/Calendar.js, src/DatePicker/CalendarMonth.js, src/DatePicker/CalendarYear.js, src/DatePicker/CalendarYear.spec.js, src/DatePicker/DatePicker.js, src/DatePicker/DatePickerDialog.js, src/DatePicker/YearButton.js, src/DatePicker/dateUtils.js
Fixes #5485
I tried to minimize the impact on the main repository and moved all the needed logic into another dependency. This might even pave the way for other calendar systems to be implemented too.
=> [DatePicker] Customizable calendar system

src/internal/Modal.spec.js
=> [Modal] Add test coverage for `handleDocumentKeyUp()`

package.json, test/README.md
=> [package.json] Add test:unit:grep

src/internal/Popover.spec.js
=> [Popover] Add test coverage for `handleRequestTimeout()`

.babelrc, docs/package.json, docs/src/index.js, docs/yarn.lock, package.json, yarn.lock
=> [core] Remove one babel transform as require the Symbol polyfill

src/transitions/Collapse.spec.js
=> [Collapse] Add test coverage for wrapper ref

src/transitions/Collapse.spec.js
=> [Collapse] Add test coverage for `handleEntered()`

src/transitions/Collapse.spec.js
=> [Collapse] Add test coverage for `handleEntering()`

CONTRIBUTING.md
=> [CONTRIBUTING] Update with git clone --depth 1 + other tweaks

docs/package.json
=> [docs] Upgrade react-docgen

docs/src/components/App.js
@oliviertassinari @foreggs
Can you test that this fixes the next docs theme toggling?
resolves #6644
=> [docs] Fix theme toggling

src/internal/modalManager.spec.js
=> [ModalManager] Add test coverage for removal of non-exiting modal

README.md
=> Fix the example "Usage" to match new Button component

src/Radio/Radio.js
=> [Radio] Change checked color to primary.

package.json, yarn.lock
=> [test] Upgrade argos version

src/Stepper/Stepper.js
=> [Stepper] Allow single Step child

src/Table/TableBody.js
=> [Table] Fix selection when prescan is turned off

CHANGELOG.md
=> [CHANGELOG] Prepare v0.18.0

docs/index.html, docs/package.json, docs/src/components/App.js, docs/src/components/AppDrawer.js, docs/src/components/AppFrame.js, docs/src/components/AppSearch.js, docs/src/components/Link.js, docs/src/components/MarkdownElement.js, docs/yarn.lock
=> [docs] Add a search bar

docs/src/pages/component-api/Layout/Layout.md, src/Layout/Layout.js, src/Layout/Layout.spec.js
---
Closes #6726
- Exposes most `<Hidden/>` props on `<Layout/>` for ease of use
- Delegates to `<Hidden/>` if any pertinent props are present
=> Layout hidden

docs/src/components/AppContent.js, docs/src/components/AppRouter.js, docs/src/components/Link.js, docs/src/components/MarkdownElement.js
It should help with the indexation of the documentation for the search.
@maxiloc An alternative solution to what we discussed.
=> [docs] Generate a summary of each section

docs/src/pages/component-api/Typography/Typography.md, src/Typography/Typography.js
Convert typography to flow type.
=> [Typography] flow type

.babelrc
=> [coverage] removed the flow plugins as they were not needed

src/internal/ButtonBase.spec.js
=> [ButtonBase] Add test coverage for instance.focus

src/internal/ButtonBase.js, src/internal/ButtonBase.spec.js
=> [ButtonBase] Add test coverage for handleFocus

.eslintrc.js, src/internal/Transition.js
This is an alternative to and closes #6840 PR.
I started with @agamrafaeli's code and changed prop types to flow.
---
=> [Transition] flow proptypes

.gitmodules
Add [Razzle Material UI Styled Example](https://github.com/kireerik/razzle-material-ui-styled-example) as a submodule to the examples.
=> Add Razzle Styled Example

docs/src/pages/style/Types.js, src/styles/typography.js
This is the first step toward upgrading to `jss@7.0.0` cc @kof, having a value undefined breaks inside the `toCSS` method of JSS. I'm glad it's failing, that issue would have been submarine for months otherwise 🐟 .
=> [Typography] Add missing style

src/Card/Card.js, src/Card/CardExpandable.js, src/Card/CardHeader.js, test/integration/Card/Card.spec.js
=> [Card] Add iconStyle property to CardHeader

src/DropDownMenu/DropDownMenu.js, src/SelectField/SelectField.js
=> [DropDownMenu] Add child argument to selectionRenderer

.eslintrc.js, docs/src/components/AppDrawer.js, docs/src/pages/style/Color.js, packages/material-ui-icons/build.js, src/internal/SwitchBase.spec.js, src/utils/keyboardFocus.js
Remove `no-use-before-define` override.
=> [core] Fit closer to airbnb

src/Drawer/Drawer.js
=> [Drawer] fix for server side rendering

src/DatePicker/DatePickerDialog.js
This reverts commit be4b6fbdb90a270e6b064b405545b6f228e63bb1.
Closes #6915.
=> Revert "[DatePicker] Call dismiss when handleTouchTapOk triggers (#6764)

src/internal/ButtonBase.js, src/internal/withSwitchLabel.js
Fix 
@owencm Thanks for the tip you shared in your [latest talk](https://www.youtube.com/watch?list=PLOU2XLYxmsIKC8eODk_RNCWv3fBcLvMMy&v=mmq-KVeO-uU).
=> [Switch] Remove the blue flash of death

docs/src/pages/component-api/TextField/TextField.md, docs/src/pages/customization/api.md, src/TextField/TextField.js, src/TextField/TextField.spec.js
=> [TextField] Fix the inputClassName property

docs/src/pages/customization/themes.md
There's a few other stylistic rewordings that are more preferential that I could make (if you'd like), but here I've filled in a few missing words, replaced others, and corrected grammar in some places. 
Thanks for the project!
=> [Documentation] Fix grammar/verbiage on customization/themes page

docs/src/app/components/pages/components/TimePicker/ExampleStep.js, docs/src/app/components/pages/components/TimePicker/Page.js, src/TimePicker/Clock.js, src/TimePicker/ClockMinutes.js, src/TimePicker/TimePicker.js, src/TimePicker/TimePickerDialog.js
I needed to round the time picker to 5 minutes and thought this could be useful to other people.
I'm not sure if I've chosen the most intuitive naming so feel free to suggest something else.
=> [TimePicker] Add minutes step prop

src/Form/FormControl.js, src/Form/FormControl.spec.js
Add missing test of @PutziSan PR.
Closes #6940
=> [FormControl] Fix onFocus and onBlur events override

src/Progress/CircularProgress.js
Fixes https://github.com/callemall/material-ui/issues/4747
=> [CircularProgress] make it start and finish from top

package.json, yarn.lock
```sh
i  identified `circle` environment
```
=> [core] Simplify argos integration

docs/src/pages/style/color.md
=> Change text for link

docs/src/pages/layout/basics.md
=> Suggested text changes

circle.yml, docker-compose.yml
=> [test] Upgrade the docker versions

docs/yarn.lock, src/internal/ButtonBase.js, yarn.lock
=> [Button] Formatting

src/Table/TableRow.js
Fixes https://github.com/callemall/material-ui/issues/6262
=> [TableRow] Fix persistent background when clicked

src/Form/FormControl.js, src/Form/FormControl.spec.js, src/Input/Input.js, src/Input/Input.spec.js
@kybarg Following this PR #6566.
=> [TextField] Fix broken isDirty logic

docs/src/pages/customization/css-in-js.md
https://github.com/callemall/material-ui/issues/7005
=> [docs] Add an example with a decorator

docs/src/app/components/pages/components/Card/ExampleControlled.js, docs/src/app/components/pages/components/Card/ExampleWithAvatar.js
=> [Card] Add alt property for img tag

docs/src/pages/getting-started/usage.md
"Hello World." That just seemed embarrassing ;p
=> Update usage.md "Hello World" :|

README.md
Adds a link to the alpha docs in the alpha read me, to my knowledge it's not publicly listed anywhere ¯\_(ツ)_/¯
=> Adds link to the temporary alpha docs

src/internal/ExpandTransition.js
=> [Stepper] Add expandTransitionChildStyle property

docs/src/pages/customization/overrides.md, docs/src/pages/customization/themes.md
=> [docs] Improve the documentation on the classes property

docs/src/pages/component-api/Avatar/Avatar.md, src/Avatar/Avatar.js, src/Avatar/Avatar.spec.js
=> [Avatar] Add a imgProps property

docs/src/pages/component-demos/lists/CheckboxList.js, docs/src/pages/component-demos/lists/CheckboxListSecondary.js, docs/src/pages/component-demos/lists/InteractiveList.js, docs/src/pages/layout/grid/GuttersGrid.js, docs/src/pages/layout/grid/InteractiveGrid.js, src/MobileStepper/MobileStepper.js
=> [core] Simplify the array logic

docs/src/pages/component-api/Form/FormControl.md, docs/src/pages/component-demos/text-fields/TextFields.js, src/Form/FormControl.js, src/Form/FormHelperText.js, src/Input/Input.js, src/Input/InputLabel.js
=> [TextField] Add a marginForm property

src/styles/MuiThemeProvider.js
Following @Airblader feedback.
=> [MuiThemeProvider] Small eslint fix

docs/src/pages/component-api/Input/Input.md, docs/src/pages/component-api/Tabs/Tab.md, docs/src/utils/prism.js, src/Input/Input.js, src/Tabs/Tab.js, src/Tabs/Tab.spec.js
=> [core] Remove some no longer needed properties

.eslintrc.js
It's following the same approach as the react repository. Git is already handling the linebreak logic in order to simplify contributions between platforms.
Close #7053
=> [core] Disable linebreak-style rule

src/Input/Input.js, src/Input/Input.spec.js
=> [TextField] Better support number value type

docs/src/pages/component-api/Checkbox/LabelCheckbox.md, docs/src/pages/component-api/Radio/LabelRadio.md, docs/src/pages/component-api/Switch/LabelSwitch.md, src/Checkbox/Checkbox.js, src/Checkbox/Checkbox.spec.js, src/Checkbox/LabelCheckbox.js, src/Checkbox/index.js, src/Radio/LabelRadio.js, src/Radio/Radio.js, src/Radio/Radio.spec.js, src/Radio/index.js, src/Switch/LabelSwitch.js, src/Switch/Switch.spec.js, src/Switch/index.js, src/index.js, src/internal/withSwitchLabel.js, src/internal/withSwitchLabel.spec.js
=> [docs] Document the Label wrappers

docs/src/components/AppDrawerNavItem.js, docs/src/pages/component-api/Checkbox/Checkbox.md, docs/src/pages/component-api/Radio/Radio.md, docs/src/pages/component-api/Switch/Switch.md, docs/src/pages/component-demos/lists/CheckboxList.js, src/Button/Button.js, src/Button/Button.spec.js, src/Checkbox/Checkbox.js, src/IconButton/IconButton.js, src/IconButton/IconButton.spec.js, src/Menu/MenuItem.js, src/Menu/MenuItem.spec.js, src/Radio/Radio.js, src/Switch/Switch.js, src/Table/TableSortLabel.js, src/internal/ButtonBase.js, test/integration/fixtures/menus/SimpleMenu.js, test/regressions/tests/List/PrimaryActionCheckboxListItem.js
=> [ButtonBase] Normalize ripple to disableRipple

docs/src/app/components/pages/discover-more/Showcase.js
=> 'Humorista' Showcase App No Longer Working - Removed From Showcase

.codecov.yml, docs/src/utils/prism.js, src/Input/Textarea.spec.js, src/List/ListItemAvatar.spec.js, src/internal/withSwitchLabel.spec.js, src/utils/customPropTypes.js, src/utils/customPropTypes.spec.js
Aims for 99% of test coverage, maybe 99.99% one day… cc @salper.
=> [test] Four nines

docs/src/pages/component-api/MobileStepper/MobileStepper.md, docs/src/pages/component-demos/stepper/TextMobileStepper.js, docs/src/pages/component-demos/stepper/stepper.md, src/MobileStepper/MobileStepper.js
=> [MobileStepper] Improvements

docs/src/components/AppRouter.js, docs/src/pages/layout/css-in-js.md, docs/src/pages/layout/css-in-js/MediaQuery.js
I thought this information might save someone else the 10 minutes I spent searching around for how to do this. I'm assuming breakpoints is a public API as it's mentioned on the theme page.
Not sure what my commit message should begin with but if you let me know I'll change it and force push.
=> [docs] Info on how to use the breakpoints attribute in the theme

docs/src/components/AppRouter.js, docs/src/pages/component-api/Form/FormControl.md, docs/src/pages/component-api/Toolbar/Toolbar.md, docs/src/pages/component-api/Typography/Typography.md, docs/src/pages/component-demos/buttons/RaisedButtons.js, docs/src/pages/getting-started/supported-browsers.md, docs/src/pages/guides/minimizing-bundle-size.md, docs/src/pages/layout/css-in-js.md, docs/src/pages/layout/css-in-js/MediaQuery.js, docs/webpack.dev.config.js, src/AppBar/AppBar.js, src/Form/FormControl.js, src/Input/Input.js, src/MobileStepper/MobileStepper.js, src/TextField/TextField.js, src/Toolbar/Toolbar.js, src/Typography/Typography.js
I have never mixed so many concerns in a single PR, but that's much easier that way for me 👼 
But that's small changes, nothing fundamental.
- [Typography] Expose a headlineMapping property
- [Typography] Add a accent color variation
- [FormControl] Fix wording
- [Toolbar] Simplify breakpoint logic
- [Button] Fix upload button demo
- [TextField] Forward the placeholder
- [MobileStepper] Fix the wordings
- [AppBar] Use a header instead of a div DOM element
- [docs] We don't require any polyfill
- [docs] Exposes the 3 Babel plugins available for minimising the bundle size
- [docs] Fix MATERIAL_UI_PORT not fully supported
=> [core] Some improvements

src/Paper/Paper.js, src/Paper/Paper.spec.js, src/utils/helpers.js
I have missed that component in a previous iteration.
=> [Paper] Use normalized root over paper className

docs/package.json, docs/yarn.lock, package.json, yarn.lock
=> [docs] Upgrade to webpack v3

.circleci/config.yml
Let's use the workflow of CircleCI. The test needs 3 min to complete instead of 5min.
=> [core] x2 speed up on the build

docs/src/pages/component-demos/app-bar/SimpleAppBar.js, docs/src/pages/component-demos/tabs/BasicTabs.js, docs/src/pages/component-demos/tabs/BasicTabsWrappedLabel.js, docs/src/pages/component-demos/tabs/FullWidthTabs.js, docs/src/pages/component-demos/tabs/ScrollableTabsButtonAuto.js, docs/src/pages/component-demos/tabs/ScrollableTabsButtonForce.js, docs/src/pages/component-demos/tabs/ScrollableTabsButtonPrevent.js, src/AppBar/AppBar.js, src/Form/FormControl.js, src/Tabs/Tab.js, src/styles/palette.js
- Consistent display mode for the TextField and the Input component
- Clean the `theme.palette.background` key usage
=> [core] Some fixes

.circleci/config.yml
That's good enough now 02:42. The visual regression tests are the slowest part now.
=> [test] Even faster CI build

docs/src/components/AppRouter.js, docs/src/pages/getting-started/supported-platforms.md
=> [docs] Add supported server section

src/styles/index.js, src/styles/mixins.js, src/styles/shadows.js, src/styles/spacing.js, src/styles/theme.js, src/styles/transitions.js, src/styles/typography.js, src/styles/zIndex.js
=> [styles] Export more functions

docs/src/pages/component-api/AppBar/AppBar.md, docs/src/pages/component-api/Drawer/Drawer.md, docs/src/pages/component-api/Input/Input.md, docs/src/pages/component-api/Snackbar/Snackbar.md, docs/src/pages/component-api/Tabs/Tab.md, docs/src/pages/component-api/Tabs/TabIndicator.md, docs/src/pages/component-api/Tabs/Tabs.md, docs/src/pages/component-demos/tabs/CenteredTabs.js, docs/src/pages/component-demos/tabs/DisabledTabs.js, docs/src/pages/component-demos/tabs/FullWidthTabs.js, docs/src/pages/component-demos/tabs/IconLabelTabs.js, docs/src/pages/component-demos/tabs/IconTabs.js, docs/src/pages/component-demos/tabs/ScrollableTabsButtonAuto.js, docs/src/pages/component-demos/tabs/ScrollableTabsButtonForce.js, src/Tabs/Tab.js, src/Tabs/Tab.spec.js, src/Tabs/TabIndicator.js, src/Tabs/Tabs.js
=> [Tabs] Add a primary color and update the docs

src/Paper/Paper.js
=> [Paper] properties circle has typo misspelling (circlular should be circular)

src/utils/autoprefixer.spec.js
update to correct issues detailed in https://github.com/callemall/material-ui/issues/7264
=> [tests] correct values expected by autoprefixer

.babelrc, .circleci/config.yml, src/Card/CardContent.spec.js, src/Card/CardHeader.spec.js, src/Card/CardMedia.spec.js, src/List/ListItemSecondaryAction.spec.js, src/test-utils/createShallow.js, src/test-utils/until.js, src/test-utils/until.spec.js
[The pain point](https://github.com/acdlite/recompose/blob/master/src/packages/recompose/isReferentiallyTransparentFunctionComponent.js)
Closes #7271
=> [test] Should get coverage

docs/src/app/components/AppNavDrawer.js, docs/src/app/components/Master.js
=> [docs] Promote the v1.0.0-alpha

docs/src/app/components/Master.js
=> [docs] Fix v1 promo styling

docs/src/pages/style/icons.md, src/svg-icons/README.md
=> [docs] Improve the documentation regarding material.io/icons

docs/src/pages/component-demos/lists/SimpleList.js, src/internal/ButtonBase.js
=> [ButtonBase] Use color inherit by default

src/Avatar/Avatar.js
=> [Avatar] Avoid shrink

docs/src/pages/style/color.md
Using the correct path of colors variables :
=> BAD : material-ui/styles/colors
=> GOOD : material-ui/colors
=> [docs] Fix the path of imported colors

src/Progress/CircularProgress.js, src/Progress/LinearProgress.js, src/Progress/LinearProgress.spec.js
=> [LinearProgress] Improve perf and clean

CONTRIBUTING.md
Change all references of 'next' branch to
'v1-alpha'.
Fix #7370
=>  [docs] Update CONTRIBUTING.md with v1-alpha branch

docs/src/pages/component-api/Input/Input.md, docs/src/pages/component-api/TextField/TextField.md, docs/src/pages/component-demos/text-fields/TextFields.js, package.json, src/Input/Input.js, src/TextField/TextField.js, yarn.lock
=> [TextField] Address autoComplete issue

docs/src/pages/component-api/Dialog/Dialog.md, docs/src/pages/component-api/Menu/Menu.md, docs/src/pages/component-api/Snackbar/Snackbar.md, docs/src/pages/component-api/transitions/Fade.md, package.json, test/mocha.opts, test/utils/dom.js
Avoid code duplication for now with https://github.com/rstacruz/jsdom-global/blob/master/index.js.
=> [test] Remove jsdom-global for now

src/Menu/MenuItem.js, src/Menu/MenuItem.spec.js
=> [Menu] Add ripple

packages/material-ui-icons/builder.js, packages/material-ui-icons/builder.md, packages/material-ui-icons/package.json, packages/material-ui-icons/test/index.js, packages/material-ui-icons/yarn.lock
=> [icons] Upgrade the dependencies

docs/src/pages/style/color.md, src/Avatar/Avatar.js, src/List/ListItemText.js
Tiny fix.
Changed
```
import { red, orange } from 'material-ui/styles/colors';
```
to
```
import { red, orange } from 'material-ui/colors';
```
=> [Docs] Color import correction

.circleci/config.yml, package.json, yarn.lock
Following https://twitter.com/gpblv/status/886917219296436227
=> [core] Fix circleci

src/internal/Portal.js
=> [Portal] Fix Portal not removing layer correctly on React 16

src/IconButton/IconButton.js, src/Switch/Switch.js
=> [IconButton] Remove z-index

docs/src/pages/component-api/IconButton/IconButton.md, docs/src/pages/component-api/List/List.md, docs/src/pages/component-api/List/ListItem.md, docs/src/pages/component-demos/buttons/IconButtons.js, src/IconButton/IconButton.js
=> IconButton: add the missing primary color

src/Toolbar/Toolbar.js
=> [Toolbar] Follow the spec more closely

docs/src/app/components/pages/components/Avatar/README.md
=> docs: fix typo in Avatar readme

src/Dialog/Dialog.js
Closes #7448 
I put extra marginLeft and MarginRight for xs and sm.
=> [Dialog] Fix Dialog margin

docs/src/pages/getting-started/supported-components.md
=> [docs] Mark items on the supported components page as done

docs/src/pages/component-demos/text-fields/TextFields.js, docs/src/pages/component-demos/text-fields/text-fields.md, src/Input/Textarea.js, src/Input/Textarea.spec.js, yarn.lock
Closes #7288
Closes #7490
Closes #7465
=> [TextField] Fix multiline issue

docs/src/pages/getting-started/examples.md, examples/next.js/README.md
Complement of #7485, cc @akshaynaik404
=> [docs] Add next.js example

docs/src/pages/component-demos/dialogs/FullScreenDialog.js, docs/src/pages/customization/themes.md, src/styles/withTheme.spec.js
=> [docs] Some fixes after the latest upgrade

docs/src/app/components/pages/components/Checkbox/ExampleSimple.js, src/internal/EnhancedSwitch.js
Fixes callemall/material-ui#7261
=> [EnhancedSwitch] Fix checked prop

src/styles/createStyleSheet.js, src/styles/withStyles.spec.js
=> [core] Better themingEnabled logic

ROADMAP.md
- Reflect branch changes from v1-alpha --> v1-beta
- Reflect completed status of beta milestone
=> [docs] Update ROADMAP

src/Popover/Popover.js
=> [Popover] Fix unknown "scrollableContainer" prop warning

docs/package.json, docs/yarn.lock, package.json, src/internal/Portal.js
=> [core] Support react@16.0.0-beta.1

README.md, docs/src/pages/customization/overrides.md, docs/src/pages/getting-started/usage.md, examples/.eslintrc.js, src/styles/MuiThemeProvider.spec.js, src/styles/createGenerateClassName.js, src/styles/createGenerateClassName.spec.js, src/styles/withStyles.js
- Following https://github.com/cssinjs/jss/issues/546 feedback, we use base 10 over base 36
- Following https://github.com/cssinjs/jss/issues/547 feedback, we are one step closer to react-jss
- Fix #7571
=> [core] Small fixes of the styling solution

docs/src/pages/component-demos/menus/LongMenu.js, docs/src/pages/component-demos/menus/menus.md, src/Form/FormControlLabel.js, src/Menu/Menu.js, src/internal/Backdrop.js, src/internal/ButtonBase.js, src/internal/Popover.js, test/integration/fixtures/menus/SimpleMenu.js
=> [ios] Fix some style issue with Safari iOS

src/Drawer/Drawer.js
=> [Drawer] Fix docked not inheriting props (#7589)

docs/src/components/MarkdownElement.js, docs/src/pages/Home.js, docs/src/pages/component-api/Avatar/Avatar.md, docs/src/pages/component-api/Progress/LinearProgress.md, docs/src/pages/component-api/styles/MuiThemeProvider.md, src/Avatar/Avatar.js
- Light/dark mode on the home
- Display table correctly on mobile
=> [docs] Fix small issues I have noticed

docs/index.html, docs/src/components/ApiMenuComponents.js, docs/src/components/AppFrame.js, docs/src/components/MarkdownDocs.js, docs/src/pages/component-demos/buttons/FloatingActionButtons.js, docs/src/pages/component-demos/menus/LongMenu.js, docs/src/pages/component-demos/menus/SimpleMenu.js, docs/src/pages/component-demos/text-fields/ComposedTextField.js, docs/src/pages/component-demos/text-fields/Inputs.js, docs/src/pages/component-demos/text-fields/TextFieldMargins.js
Chrome 60 introduced a new audit tool. It's really useful to spot issues.
=> [docs] Fix audit issues

docs/src/components/AppDrawer.js, src/Drawer/Drawer.js
=> [Drawer] Fix docker warning

src/internal/Modal.js
=> [Drawer] Fix Chrome regression

src/styles/withStyles.js
Thanks @UchihaVeha @Tonvengo @kybarg for raising that issue.
> Uncaught (in promise) TypeError: Cannot read property 'get' of undefined
at withStyles.js:298
at Array.reduce (<anonymous>)
at ProxyComponent.render (withStyles.js:296)
at ProxyComponent.render (createPrototypeProxy.js:44)
=> [style] Fix HMR issue with react-hot-loader

docs/src/pages/customization/overrides.md
Fix up a bunch of English language usage issues and try to provide more clarity
=> [Docs] Fix language issues for clarity

docs/index.html, docs/src/components/App.js, docs/src/pages/customization/overrides.md, package.json, yarn.lock
=> [docs] Show how to use the insertionPoint

docs/src/pages/component-demos/tables/EnhancedTable.js, src/internal/Portal.js, src/internal/Portal.spec.js, src/internal/modalManager.js
Closes #7628 
Closes #7655 
Closes #7664
=> Fixes in the subway

src/Card/Card.js, src/Card/Card.spec.js
=> [Card] allow overflow - important for content such as autosuggest.

src/Tabs/Tab.js
=> [Tabs] Fix full width issue

src/Button/Button.js
=> [Button] Disable the hover effect on touch devices

docs/src/pages/component-demos/cards/MediaControlCard.js, docs/src/pages/component-demos/cards/RecipeReviewCard.js, docs/src/pages/component-demos/cards/SimpleMediaCard.js, docs/src/pages/component-demos/cards/cards.md, src/Card/Card.js, src/Card/Card.spec.js, src/Card/CardMedia.js, src/Card/CardMedia.spec.js
...also some rename in the demo file to better line up with docs headings.
=> [Card] remove overflow, change CardMedia implementation as background, update demos

docs/src/pages/component-demos/autocomplete/autocomplete.md, src/Menu/Menu.js
=> [docs] Fix broken menu on the autocomplete page

src/transitions/Collapse.js, src/transitions/Fade.js, src/transitions/Slide.js
=> [flow] flow type transitions Slide, Fade, Collapse (fixes)

docs/src/pages/component-demos/selection-controls/Checkboxes.js, docs/src/pages/component-demos/selection-controls/RadioButtonsGroup.js, src/Form/FormControl.js, src/Form/FormControlLabel.js, src/Form/FormControlLabel.spec.js, src/Form/FormLabel.js
=> [Radio] Fix accessibility issue

docs/src/pages/discover-more/related-projects.md
Material-UI data grid details: https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-grid-material-ui/README.md
=> [docs] Add the 'data grid for Material-UI' reference

docs/src/pages/component-api/transitions/Slide.md, src/transitions/Slide.js
=> [Slide] Remove Slide offset property from src and docs

docs/src/pages/component-demos/tables/tables.md
=> [docs] Advanced table

.circleci/config.yml
I find the CI too slow right now. Should win 1 min with this change.
=> [core] Better usage of the CI 🚀

docs/src/pages/demos/text-fields/TextFields.js, src/Input/Input.js
=> [TextField] Fix placeholder issue

ROADMAP.md, docs/src/modules/components/withRoot.js, pages/discover-more/roadmap.js
=> [docs] Add a ROADMAP page

docs/scripts/buildApi.js, docs/src/modules/utils/generateMarkdown.js, pages/api/app-bar.md, pages/api/bottom-navigation-button.md, pages/api/button.md, pages/api/card-header.md, pages/api/card.md, pages/api/icon-button.md, pages/api/mobile-stepper.md, pages/api/tab.md, pages/api/text-field.md, src/AppBar/AppBar.js, src/BottomNavigation/BottomNavigationButton.js, src/Button/Button.js, src/Card/Card.js, src/Card/CardHeader.js, src/GridList/GridListTile.js, src/IconButton/IconButton.js, src/MobileStepper/MobileStepper.js, src/Tabs/Tab.js, src/TextField/TextField.js
Simple and efficient.
Closes #3172.
=> [docs] Show inherited components

.eslintignore, docs/scripts/buildApi.js, docs/src/modules/components/MarkdownDocs.js, docs/src/modules/utils/find.js, docs/src/modules/utils/findPages.js, docs/src/pages/demos/tables/tables.md, next.config.js, test/regressions/index.js
=> [docs] Small fixes after the next.js refactorization

src/BottomNavigation/BottomNavigationButton.d.ts, src/Dialog/withResponsiveFullScreen.d.ts, src/styles/withStyles.d.ts, src/utils/withWidth.d.ts, test/typescript/components.spec.tsx, test/typescript/styles.spec.tsx
This patch solves the following issues:
Closes #7826
Closes #7830
Closes #7889
---
=> [typings] Fixes/improvements for withWith/withStyle + BottomNavigationButton

src/List/ListItemIcon.js
=> [ListItemIcon] icon should not shrink fixes #7915

docs/src/pages/demos/buttons/FlatButtons.js
Couldn't figure out how to fix a couple eslint prettier errors.
=> [docs] Show an example with the data- pattern

src/Dialog/withResponsiveFullScreen.js
=> [withResponsiveFullScreen] missed type import

src/Menu/Menu.d.ts, src/Popover/Popover.d.ts, src/Popover/index.d.ts
Update to match #7927 (fixes import paths)
=> [typings] Update typings to popover changes

docs/src/modules/utils/find.js
=> [docs] Fix docs build on Windows

docs/src/modules/components/AppDrawer.js, docs/src/modules/components/withRoot.js
=> [docs] Better support IE11

src/Input/InputLabel.js, src/Input/InputLabel.spec.js, test/regressions/tests/TextField/TextFieldMargin.js
=> [TextField] Fix label position with dense margins

docs/src/modules/components/AppWrapper.js, docs/src/modules/styles/getContext.js, examples/nextjs/components/withRoot.js, examples/nextjs/pages/_document.js, examples/nextjs/styles/getContext.js, pages/_document.js
Take advantage of https://github.com/zeit/next.js/pull/2010
@kof First clean SSR with JSS and next.js 🎉 .
=> [SSR] Remove the singleton hack ✨

src/AutoComplete/AutoComplete.js, src/AutoComplete/AutoComplete.spec.js
=> [AutoComplete] Fix bug where controlled component behaves uncontrolled.

docs/src/pages/customization/themes.md, src/Dialog/withResponsiveFullScreen.d.ts, src/Drawer/Drawer.d.ts, src/Grid/Grid.d.ts, src/Hidden/Hidden.d.ts, src/Hidden/HiddenJs.d.ts, src/Typography/Typography.d.ts, src/transitions/Collapse.d.ts, src/transitions/Fade.d.ts, src/transitions/Grow.d.ts, src/transitions/Slide.d.ts, src/utils/withWidth.d.ts
=> [core] Fix some issues after the latest release

src/styles/MuiThemeProvider.d.ts, src/styles/createMixins.d.ts, src/styles/createMuiTheme.d.ts, src/styles/createTypography.d.ts, src/styles/index.d.ts, src/styles/withStyles.d.ts, src/styles/withTheme.d.ts, test/typescript/styles.spec.tsx
Adjust typings to refactoring of `styles/*`.
Closes #7969
---
=> [typescript] Adjust typings to refactoring in `styles`.

pages/api/paper.md
=> Removed typo

src/Menu/MenuItem.js
=> [docs] Add missing inheritance pragma to MenuItem. Fixes #7981

test/typescript/components.spec.tsx
Add typings test for `<Grid>`.
Ref #7986
=> [typescript] Add test for Grid.

src/colors/amber.d.ts, src/colors/blue.d.ts, src/colors/blueGrey.d.ts, src/colors/brown.d.ts, src/colors/common.d.ts, src/colors/cyan.d.ts, src/colors/deepOrange.d.ts, src/colors/deepPurple.d.ts, src/colors/green.d.ts, src/colors/grey.d.ts, src/colors/indigo.d.ts, src/colors/lightBlue.d.ts, src/colors/lightGreen.d.ts, src/colors/lime.d.ts, src/colors/orange.d.ts, src/colors/pink.d.ts, src/colors/purple.d.ts, src/colors/red.d.ts, src/colors/teal.d.ts, src/colors/yellow.d.ts, test/typescript/colors.ts
This PR fixes #7986, I added a TypeScript test case, it fails without the PR and passes with it.
Thanks for the official TypeScript support!
=> [TypeScript] Fix color exporting

docs/src/pages/guides/server-rendering.md
=> [docs] Fix SSR palette creation section

docs/src/modules/components/AppDrawerNavItem.js, docs/src/pages/demos/lists/NestedList.js, docs/src/pages/demos/lists/lists.md, pages/demos/lists.js
=> [docs] Add a NestedList example

ROADMAP.md, docs/src/modules/components/MarkdownDocs.js, pages/discover-more/roadmap.js
=> [docs] Fix ROADMAP page issues

docs/src/pages/customization/themes.md
=> [docs] 🚑 Fix broken link

examples/create-react-app/README.md
=> [examples] Fix typo in extraction path

src/Card/CardMedia.d.ts
=> [typescript] Add `image` to CardMediaProps

src/Popover/Popover.js
=> [Popover] Pass transitionDuration to Grow.

src/styles/withTheme.d.ts
=> [typings] Fix typings of withTheme

package.json, pages/api/menu-item.md, pages/api/paper.md, yarn.lock
=> Update react-docgen and generate api docs

src/Drawer/Drawer.d.ts, src/Grid/Grid.d.ts, src/Menu/Menu.d.ts, src/TextField/TextField.d.ts, test/typescript/components.spec.tsx
=> [typescript] Allow to pass stylings props via component props.

test/typescript/styles.spec.tsx
=> [typescript] Add example for using withStyle/Theme together

.github/ISSUE_TEMPLATE.md
Added the codesandbox.io template.
=> issue_template formatting, punctuation, and codesandox.io template

docs/src/pages/demos/drawers/MiniDrawer.js
fixes horizontal scrolling of collapsed mini variant
Closes #8109
=> [Drawer] Fix for mini variant drawer can be scrolled horizontally when collapsed

CHANGELOG.md
Takes #8074 feedback into account.
=> [docs] Makes the sections bolder

src/ButtonBase/ButtonBase.d.ts, src/Chip/Chip.d.ts, src/Radio/Radio.d.ts, src/Switch/Switch.d.ts, src/internal/SwitchBase.d.ts
=> fix ts tabindex to use number

src/Drawer/Drawer.js, src/Drawer/Drawer.spec.js
=> [Drawer] Fix delegation of the className

docs/src/pages/demos/tabs/BasicTabs.js, src/BottomNavigation/BottomNavigationButton.js, src/Button/Button.js, src/ButtonBase/ButtonBase.js, src/IconButton/IconButton.js, src/List/ListItem.js, src/SvgIcon/SvgIcon.js, src/Tabs/Tab.js
=> [ButtonBase] Make the button and a behavior the same way

docs/src/pages/customization/api.md, docs/src/pages/demos/progress/CircularIndeterminate.js, src/Progress/LinearProgress.js
=> [LinearProgress] Fix loop

src/Card/CardMedia.js
I think that this could be a good default behavior.
=> [Card] Add `backgroundPosition: 'center'` to CardMedia

docs/src/pages/demos/drawers/MiniDrawer.js, docs/src/pages/demos/drawers/PermanentDrawer.js, docs/src/pages/demos/drawers/PersistentDrawer.js, src/Toolbar/Toolbar.js, src/styles/createMixins.js
This enables the drawer header to stay aligned with the appbar in all circumstances.
=> [Toolbar] Add a toolbar mixins 💄

src/Radio/RadioGroup.js, src/Radio/RadioGroup.spec.js
=> [Radio] Accept invalid children

src/styles/createMuiTheme.js, src/styles/createMuiTheme.spec.js
=> [theme] Extend createMuiTheme behavior

src/AppBar/AppBar.js
=> Height of AppBar shall not shrink

src/Select/SelectInput.js, src/Select/SelectInput.spec.js
=> [Select] Allow invalid children

docs/src/modules/components/AppFrame.js, docs/src/modules/components/AppSearch.js, docs/src/modules/components/Demo.js, docs/src/modules/components/MarkdownDocs.js, pages/api/input.md, pages/api/popover.md, pages/api/select.md, src/Select/Select.js
=> [docs] Some fixes

src/BottomNavigation/BottomNavigationButton.js, src/BottomNavigation/BottomNavigationButton.spec.js, src/Tabs/Tab.js, src/Tabs/Tab.spec.js
=> [ButtonBase] Wrong layout with Safari

docs/src/modules/utils/generateMarkdown.js
Tiny typo that drives me nuts 😄
=> Fix typo in markdown generation

src/Tooltip/Tooltip.js
Closes [#8212](https://github.com/callemall/material-ui/issues/8212)
=> [Tooltip] Add fontFamily to component

docs/src/modules/components/Demo.js, test/regressions/index.js, test/regressions/tests/Tooltip/PositionedTooltips.js
=> [Tooltip] Add a visual regression test

src/Menu/Menu.js, src/Menu/Menu.spec.js, src/Select/SelectInput.js, src/internal/Modal.js, test/integration/Menu.spec.js, test/integration/Select.spec.js, test/integration/fixtures/select/SelectAndDialog.js
=> [Menu] Support Modal nesting

docs/src/pages/demos/lists/CheckboxList.js, docs/src/pages/demos/lists/CheckboxListSecondary.js, docs/src/pages/demos/lists/SwitchListSecondary.js, pages/api/list-item.md, pages/api/snackbar-content.md, pages/api/toolbar.md, src/List/ListItem.js, src/Snackbar/SnackbarContent.js
=> [ListItem] Add some spacing for ListItemSecondaryAction

docs/src/pages/demos/drawers/TemporaryDrawer.js, src/Divider/Divider.js
=> [Drawer] Improve the Temporary demo

docs/src/config.js, docs/src/modules/components/AppFrame.js, docs/src/modules/components/AppWrapper.js, docs/src/modules/components/withRoot.js, pages/_document.js
Should help us get a better understanding of how the components are used. It can also help us get insight on documentation issues.
=> [docs] Add google analytics

docs/src/app/components/Carbon.js, docs/src/www/index.html
=> [docs] Add analytics

pages/api/button-base.md, src/ButtonBase/ButtonBase.d.ts, src/ButtonBase/ButtonBase.js, src/ButtonBase/ButtonBase.spec.js, src/utils/keyboardFocus.js
=> [ButtonBase] Better support of the component property

docs/src/modules/components/Demo.js, docs/src/pages/demos/tooltips/SimpleTooltips.js, docs/src/pages/demos/tooltips/tooltips.md, flow-typed/npm/enzyme_v2.3.x.js, src/Tooltip/Tooltip.js, src/Tooltip/Tooltip.spec.js
- Get rid of one extra div tag 🎉 
- Fix max height issue
- Fix overlapping positionning issue
- Add a show/hide tooltip in the documentation
- Add an absolutly positionned example (closes #8240)
=> [Tooltip] Fix core issues with the component

src/Snackbar/Snackbar.js
Thanks @myxious for the tips.
Revert #8096
Closes #8251
=> [Snackbar] Only use the needed space

src/Tooltip/Tooltip.d.ts
Fixes [#8259](https://github.com/callemall/material-ui/issues/8259)
=> Fix prop name typo

src/Tooltip/Tooltip.d.ts
Found this error when testing.
=> Fix typo in propTypes

src/Tooltip/Tooltip.js
=> [Tooltip] Fixes tooltip overlaps and prevents clicking on element belows

docs/src/pages/guides/testing.md
Minor fixes for run-ons and punctuation!
=> [docs] Minor grammatical fixes

docs/src/pages/getting-started/supported-components.md
See https://github.com/callemall/material-ui/pull/7909
=> Tooltips are supported now

src/styles/createBreakpoints.d.ts
=> [typescript] Fix Typescript definitions for BreakpointsOptions

src/Avatar/Avatar.d.ts
TS is now complaining about style not being defined in the Avatar component
=> [typescript] Fix for Avatar.d.ts not having a style property definition

src/List/ListItem.js
=> Correcting typo in ListItem docs

src/Form/FormControl.d.ts
=> Fix missing attribute

src/index.d.ts, test/typescript/components.spec.tsx
=> Revert removal of className from StyledComponentProps

ROADMAP.md, docs/src/modules/components/MarkdownElement.js, docs/src/modules/components/withRoot.js, docs/src/modules/utils/prism.js, docs/src/pages/guides/migration-v0.x.md, pages/guides/migration-v0.x.js
=> [docs] Add small migration guide, to be continued

.circleci/config.yml
=> [core] Add TypeScript in the CI

src/Menu/MenuItem.js
Submitted after discussion in #8288
This should allow you to use the `dense` prop on `MenuItem`.
=> [MenuItem] Fix dense mode

docs/src/pages/demos/selects/SimpleSelect.js
Found a simple typo in the docs
=> Changing type 'Alignement' to Alignment

package.json, scripts/copy-files.js
https://github.com/webpack/webpack/blob/65dfc1580780ea1acfb2b2c4a7c4dbf65ecaacc9/examples/side-effects/README.md
=> [core] Help Webpack doing dead code elimination

src/styles/createGenerateClassName.js, src/styles/createGenerateClassName.spec.js, test/karma.conf.js
=> [styles] Add a new defensive warning

docs/src/pages/demos/selects/selects.md, docs/src/pages/demos/text-fields/TextFields.js, docs/src/pages/demos/text-fields/text-fields.md, pages/api/input.md, pages/api/text-field.md, src/Input/Input.js, src/TextField/TextField.d.ts, src/TextField/TextField.js, src/TextField/TextField.spec.js, test/README.md
=> [TextField] Add a select mode

src/Input/Input.js
As discussed in https://github.com/callemall/material-ui/issues/8331
=> [Input] Add underline padding at all times

.eslintignore, docs/src/pages/demos/tables/EnhancedTable.js
I think that having a scrollable table is a more appropriate solution. Closes #6633
=> [Table] Fix scroll display

docs/src/pages/discover-more/showcase.md
Updated the showcase file with a project that I created that uses material ui. I think its the best material design implementation in the world
=> Update showcase.md with my project

src/Table/TableCell.js, src/Table/TableCell.spec.js, src/utils/requirePropFalseFactory.d.ts, src/utils/requirePropFalseFactory.js, src/utils/requirePropFalseFactory.spec.js
Warns when invalid combinations of flags are used. 
Lot less sure about this PR - particularly the naming of requirePropsFalse and whether it should really have an array as a parameter or if some other approach should be taken.
=> [Table] Enhance PropType checks for TableCell

docs/src/modules/components/withRoot.js, docs/src/pages/guides/comparison.md, pages/guides/comparison.js
I really liked what [vuejs has been doing](https://vuejs.org/v2/guide/comparison.html#React) on this documentation. It's a nice proxy to explain the tradeoffs taken.
=> [docs] Add a comparison section

src/Drawer/Drawer.js
=> [Drawer] Add border anchor right

CHANGELOG.md
@oliviertassinari @pelotom please check for typos and comprehensibility :)
=> [changelog] Add info for withStyles BC

src/styles/withStyles.d.ts
=> Document withStyles overloads

src/TextField/TextField.d.ts
=> [typescript] Correct typings of TextField's onChange

docs/src/pages/demos/selects/selects.md
=> [docs] Misspelling on Select demo page

docs/src/pages/getting-started/supported-components.md
=> [docs] Fix redirections in Supported Components

docs/src/pages/demos/pickers/DateAndTimePickers.js, docs/src/pages/demos/pickers/TimePickers.js, yarn.lock
=> [docs] Fix the pickers step example

pages/api/menu-list.md, pages/api/table-pagination.md, pages/api/table-sort-label.md, src/Menu/MenuList.js, src/Table/TablePagination.js, src/Table/TableSortLabel.js
=> [docs] Add missing inheritances

src/styles/createBreakpoints.d.ts, src/styles/createMixins.d.ts, src/styles/createMuiTheme.d.ts, src/styles/createPalette.d.ts, src/styles/createTypography.d.ts
The TypeScript type definition of `createPalette` does not conform to the actual JavaScript code. I corrected the definition accordingly.
=> [typescript] Correct type definition for Theme creation

src/test-utils/createShallow.d.ts
Super small patch to make `createShallow` more useful.
=> [typescript] Improve `createShallow` typings.

next.config.js
=> [fix] typo in next.config.js

package.json, yarn.lock
=> [core] Upgrade prettier

src/Badge/Badge.spec.js, src/Form/FormControlLabel.spec.js, src/Hidden/HiddenJs.spec.js, src/Input/InputLabel.spec.js, src/Menu/MenuList.spec.js, src/Table/TableCell.spec.js, src/Table/TableRow.spec.js, src/Tabs/Tab.spec.js, src/Tabs/TabScrollButton.spec.js, src/internal/Modal.spec.js, src/internal/SwitchBase.spec.js, test/integration/MenuList.spec.js
The main blocker for upgrading to v3 seems to be the portal handling.
=> [test] Prepare enzyme v3 upgrade

src/internal/Tooltip.js, src/styles/getMuiTheme.js
Move tooltip opacity default into mui theme
=> [IconButton -> Tooltip] Allow customize tooltip opacity (non-v1)

package.json, yarn.lock
=> [core] Update react-transition-group for react@16

src/Input/Input.js
=> [Input] Fix wrong CSS property

packages/material-ui-icons/package.json
=> [material-ui-icons] Update peer dependency to react 16

docs/src/pages/demos/tables/EnhancedTable.js, src/transitions/Slide.js, src/transitions/Slide.spec.js
Closes #8323
@patrickml Thanks for the suggested solution!
=> [Slider] Fix IE11 issue

docs/src/pages/demos/tables/EnhancedTable.js, src/Table/TableCell.js, src/Tooltip/Tooltip.js, src/Tooltip/Tooltip.spec.js
=> [Tooltip] Fix usage with table head

yarn.lock
=> [core] Update jsdom to v11.3.0

src/Tabs/Tabs.js, src/Tabs/Tabs.spec.js
=> [Tabs] Support empty children

docs/src/modules/components/AppFrame.js, docs/src/pages/demos/drawers/PermanentDrawer.js, docs/src/pages/demos/drawers/ResponsiveDrawer.js, docs/src/pages/demos/drawers/TemporaryDrawer.js, docs/src/pages/demos/drawers/drawers.md, pages/demos/drawers.js
=> [docs] Add a Responsive Drawer example

src/ButtonBase/ButtonBase.js
Fixes #8216. I tested it on Canary 63.0.3230.0.
=> [ButtonBase] Fix borderRadius for Chrome 63

docs/src/pages/style/Color.js
Closes #8512
1. Add `themeInherit` to the `styles`
2. Add `classes.themeInherit` to the className of `<li>`
3. Add fontWeight inheritance to `colorValue`
=> [docs] Fix color palette demo

package.json, yarn.lock
=> [core] Upgrade to mocha@v4

docs/src/pages/getting-started/installation.md, src/Table/TablePagination.js, src/test-utils/createMount.js, src/test-utils/createShallow.js
- Broken link on the docs @AlexandreBlanchet #PM
- Dead code in the TablePagination @joonarahko #8520
- Imperfect context forwarding @SergeyAlexeev #8518
=> [misc] Fix small issues reported by users

packages/material-ui-icons/create-typings.js
=> [typscript] Adjust icon typings to change introduces in #8366
