docs/translations/api-docs/autocomplete/autocomplete.json, packages/material-ui/src/Autocomplete/Autocomplete.js, packages/material-ui/src/useAutocomplete/useAutocomplete.d.ts
=> [docs] Grammar correction in autocomplete API

packages/material-ui-lab/src/internal/pickers/Picker/Picker.tsx
`TView` was always `AllAvailableViews` so we can remove that type argument.
=> [internal][Picker] Remove unused TView type argument

packages/material-ui-lab/src/TimelineItem/TimelineItem.js
* Uses nth-of-type instead of nth-child to target alternating timeline item elements
* Fixes issues where DOM element location matters, for example when emotion is
inserting Server Side Rendered content into the DOM outside of the component's hierarchy
Closes #25875
=> [Timeline] Remove use of nth-child in favor of nth-of-type

packages/material-ui/src/styles/createTypography.js
=> [theme] Add warning for theme.typography.round deprecation

docs/src/pages/guides/migration-v4/migration-v4.md, packages/material-ui/src/styles/createBreakpoints.d.ts, packages/material-ui/src/styles/createBreakpoints.js, packages/material-ui/src/styles/createBreakpoints.test.js
- [theme] Remove theme.breakpoints.width helper.
It's redundant.
```diff
-theme.breakpoints.width('md')
+theme.breakpoints.values.md
```
---
Part of #20012.
=> [theme] Remove theme.breakpoints.width helper

packages/material-ui-lab/src/DatePicker/DatePicker.tsx, packages/material-ui-lab/src/DateTimePicker/DateTimePicker.tsx, packages/material-ui-lab/src/DesktopDatePicker/DesktopDatePicker.tsx, packages/material-ui-lab/src/DesktopDateTimePicker/DesktopDateTimePicker.tsx, packages/material-ui-lab/src/DesktopTimePicker/DesktopTimePicker.tsx, packages/material-ui-lab/src/MobileDatePicker/MobileDatePicker.tsx, packages/material-ui-lab/src/MobileDateTimePicker/MobileDateTimePicker.tsx, packages/material-ui-lab/src/MobileTimePicker/MobileTimePicker.tsx, packages/material-ui-lab/src/StaticDatePicker/StaticDatePicker.tsx, packages/material-ui-lab/src/StaticDateTimePicker/StaticDateTimePicker.tsx, packages/material-ui-lab/src/StaticTimePicker/StaticTimePicker.tsx, packages/material-ui-lab/src/TimePicker/TimePicker.tsx
Review on a per-commit basis advised.
The goal is to get rid of `BasePickerProps` which currently lives completely decoupled from its implementation. Though it previously leaked through `AllSharedPickerProps` into all picker implementations.
We can isolate its usage while at the same time resolving some naming issues regarding `All*Props` vs `*Props`. I've only applied it to the TimePicker for now in detail. The other pickers will be handled in a single commit. But in order to show that this refactoring is sound I did every step in a single commit.
=> [internal][pickers] Entangle what *Props vs All*Props means

packages/material-ui-lab/src/LoadingButton/LoadingButton.test.js, packages/material-ui/src/AppBar/AppBar.d.ts, packages/material-ui/src/AppBar/AppBar.test.js, packages/material-ui/src/Button/Button.d.ts, packages/material-ui/src/Card/Card.d.ts, packages/material-ui/src/Card/Card.test.tsx, packages/material-ui/src/Link/Link.d.ts, packages/material-ui/src/Link/Link.test.js, packages/material-ui/src/MenuItem/MenuItem.d.ts, packages/material-ui/src/MenuItem/MenuItem.test.js
These classes had no effect at runtime. They're still accepted by the type-checker (excess properties are accept in most cases anyway) but at least they're no longer suggested by IntelliSense.
Components affected:
- AppBar
- Card
- Link
- LoadingButton
- MenuItem
Noticed during https://github.com/mui-org/material-ui/pull/25754
=> [core] Fix various too wide `classes` types

docs/pages/api-docs/table-cell.json, docs/pages/api-docs/table.json, docs/src/pages/components/tables/EnhancedTable.js, docs/src/pages/components/tables/EnhancedTable.tsx, docs/src/pages/guides/migration-v4/migration-v4.md, packages/material-ui/src/Table/Table.d.ts, packages/material-ui/src/Table/Table.js, packages/material-ui/src/Table/Table.test.js, packages/material-ui/src/TableCell/TableCell.js, packages/material-ui/src/TableCell/TableCell.test.js
```diff
-<Table padding="default" />
-<TableCell padding="default" />
+<Table padding="normal" />
+<TableCell padding="normal" />
```
---
Part of #20012.
=>  [Table] Rename padding="default" to padding="normal"

packages/material-ui-lab/src/internal/pickers/hooks/useIsLandscape.tsx, packages/material-ui-lab/src/internal/pickers/hooks/useOpenState.ts, packages/material-ui-lab/src/internal/pickers/hooks/usePickerState.ts
=> [internal][pickers] Inline some BasePickerProps usages

packages/material-ui/src/FormControl/FormControl.js
We didn't use to apply this class name in v4. Proof: https://github.com/mui-org/material-ui/blob/10d331b63486086b581099c9cae6d7578f49103c/packages/material-ui/src/FormControl/FormControl.js#L189
and it doesn't seem to fill a purpose, so I went on removing it. The DOM feels heavy with all these class names, it makes it more challenging to read the dev tools output.
=> [TextField] Reduce spam of class names

docs/pages/api-docs/switch.json, packages/material-ui-lab/src/CalendarPicker/CalendarPicker.test.tsx, packages/material-ui-lab/src/CalendarPickerSkeleton/CalendarPickerSkeleton.test.tsx, packages/material-ui-lab/src/DateRangePickerDay/DateRangePickerDay.test.tsx, packages/material-ui-lab/src/LoadingButton/LoadingButton.test.js, packages/material-ui-lab/src/MonthPicker/MonthPicker.test.tsx, packages/material-ui-lab/src/PickersDay/PickersDay.test.tsx, packages/material-ui-lab/src/TabList/TabList.test.js, packages/material-ui-lab/src/TreeItem/TreeItem.test.js, packages/material-ui-lab/src/YearPicker/YearPicker.test.tsx, packages/material-ui-unstyled/src/BackdropUnstyled/BackdropUnstyled.test.js, packages/material-ui-unstyled/src/BadgeUnstyled/BadgeUnstyled.test.js, packages/material-ui-unstyled/src/ModalUnstyled/ModalUnstyled.test.js, packages/material-ui-unstyled/src/SliderUnstyled/SliderUnstyled.test.js, packages/material-ui/src/Menu/Menu.test.js, packages/material-ui/src/Modal/Modal.test.js, packages/material-ui/src/Popover/Popover.test.js, packages/material-ui/src/Switch/Switch.js, packages/material-ui/src/Switch/Switch.test.js, test/utils/describeConformance.js
This is a follow-up on https://github.com/mui-org/material-ui/pull/25776#issuecomment-821132005. Take the following case:
```js
import Switch from "@material-ui/core/Switch";
import Box from "@material-ui/core/Box";
export default function BasicSwitches() {
return (
<Box
sx={{
"& .MuiSwitch-root": {
border: "1px solid red"
}
}}
>
<Switch sx={{ bgcolor: "yellow" }} />
</Box>
);
}
```
**Actual**
https://codesandbox.io/s/basicswitches-material-demo-forked-k1xpw?file=/demo.tsx:0-347
**Expected**:
I have also used the opportunity to write a test case that would cover all the components. I had to use react-testing-library instead of enzyme.
=> [core] Ensure props spreading works as expected

docs/pages/api-docs/table-cell.md, docs/pages/api-docs/table.md, docs/src/pages/components/tables/EnhancedTable.js, docs/src/pages/components/tables/EnhancedTable.tsx, packages/material-ui/src/Table/Table.d.ts, packages/material-ui/src/Table/Table.js, packages/material-ui/src/Table/Table.test.js, packages/material-ui/src/TableCell/TableCell.d.ts, packages/material-ui/src/TableCell/TableCell.js, packages/material-ui/src/TableCell/TableCell.test.js, scripts/generateProptypes.ts
=> [Table] Deprecate padding="default"

packages/material-ui-lab/package.json, packages/material-ui-styles/package.json, packages/material-ui/package.json
Fixes https://github.com/mui-org/material-ui/issues/25165
Will do a release today. The next v5 release should bump `@material-ui/types` to v6.
Deprecating `@material-ui/types@5.1.7` would not help since existing alpha releases depend on that package without issues. I don't think deprecating the core release is helpful either. It's not a critical fixed after all.
=> [types] Ensure Omit type exists

packages/material-ui-lab/src/TreeItem/TreeItem.test.js
This broke the build on next after I merged https://github.com/mui-org/material-ui/pull/25835 because of a merge with https://github.com/mui-org/material-ui/pull/25939.
=> [test] Fix duplicate key in TreeItem test

docs/pages/api-docs/date-range-picker-day.json, docs/scripts/buildApi.ts, packages/material-ui-lab/src/DateRangePickerDay/DateRangePickerDay.tsx
~`updateStylesDefinition()` is always called twice but once is enough. I have noticed this inefficiency when diving into https://github.com/mui-org/material-ui/pull/25928#discussion_r619600334. I didn't benchmark the performance win.~
~I have used this as an opportunity to isolate what's for legacy components (JSS), so we can more easily remove the code later on.~
Fix `DateRangePickerDay` classes extraction.
=> [docs] Avoid extracting classes twice

docs/pages/api-docs/year-picker.json, docs/translations/api-docs/year-picker/year-picker.json, packages/material-ui-lab/src/Timeline/Timeline.tsx, packages/material-ui-lab/src/YearPicker/YearPicker.test.tsx, packages/material-ui-lab/src/YearPicker/YearPicker.tsx, packages/material-ui-lab/src/YearPicker/index.ts, packages/material-ui-lab/src/YearPicker/yearPickerClasses.ts, packages/material-ui/src/styles/experimentalStyled.d.ts
=> [DatePicker] Migrate YearPicker to emotion

docs/translations/api-docs/date-range-picker/date-range-picker.json, docs/translations/api-docs/desktop-date-range-picker/desktop-date-range-picker.json, docs/translations/api-docs/mobile-date-range-picker/mobile-date-range-picker.json, docs/translations/api-docs/static-date-range-picker/static-date-range-picker.json, packages/material-ui-lab/src/DatePicker/DatePicker.tsx, packages/material-ui-lab/src/DateRangePicker/DateRangePicker.tsx, packages/material-ui-lab/src/DateRangePicker/DateRangePickerInput.tsx, packages/material-ui-lab/src/DateRangePicker/RangeTypes.ts, packages/material-ui-lab/src/DateTimePicker/DateTimePicker.tsx, packages/material-ui-lab/src/DateTimePicker/date-time-utils.ts, packages/material-ui-lab/src/DesktopDateRangePicker/DesktopDateRangePicker.tsx, packages/material-ui-lab/src/MobileDateRangePicker/MobileDateRangePicker.tsx, packages/material-ui-lab/src/StaticDateRangePicker/StaticDateRangePicker.tsx, packages/material-ui-lab/src/TimePicker/TimePicker.tsx, packages/material-ui-lab/src/internal/pickers/Picker/SharedPickerProps.tsx, packages/material-ui-lab/src/internal/pickers/PureDateInput.tsx, packages/material-ui-lab/src/internal/pickers/constants/prop-types.ts, packages/material-ui-lab/src/internal/pickers/date-utils.ts, packages/material-ui-lab/src/internal/pickers/hooks/date-helpers-hooks.tsx, packages/material-ui-lab/src/internal/pickers/hooks/useUtils.ts, packages/material-ui-lab/src/internal/pickers/hooks/useValidation.ts, packages/material-ui-lab/src/internal/pickers/text-field-helper.ts, packages/material-ui-lab/src/internal/pickers/time-utils.ts
They were just not helping. 
I think the goal is now clear that we want to move interface and implementation closer together. Looking at all interfaces and then creating the minimal amount of types is just not  helpful.
=> [internal][pickers] Remove `AllSharedPickerProps` and `AllSharedDateRangePickerProps`

packages/material-ui-lab/src/internal/pickers/hooks/useMaskedInput.tsx
The re-computation of state in `useEffect` was suspicious to me. 
It seems to me that the "input value" (named `innerInputValue`) was supposed to be what the user inputs. The implementation made sure that this value is reset if the actual date value changed. But only if the textbox isn't focused to avoid interrupting the user while typing. This created some weird states where outside value updates were dropped during input or when the textbox was still focused but the user is idle.
This requires some logic that leads to tearing (state updates in useEffect). The new implementation is a bit more verbose but is hopefully clearer in its intent. It's probably better to re-implement this by controlling the `rawValue` in `usePickerState` and then deciding whether we want to expose controlled vs …
=> [pickers] Ensure input value is reset in the same commit as the value

docs/src/pages/guides/migration-v4/migration-v4.md, docs/src/pages/styles/api/api.md, packages/material-ui-styles/src/withStyles/withStyles.d.ts, packages/material-ui-styles/src/withStyles/withStyles.js, packages/material-ui-styles/src/withTheme/withTheme.d.ts, packages/material-ui-styles/src/withTheme/withTheme.js, packages/material-ui-styles/src/withTheme/withTheme.test.js, packages/material-ui-styles/test/styles.spec.tsx, packages/material-ui/src/styles/withTheme.d.ts, packages/material-ui/src/withWidth/withWidth.d.ts
**BREAKING CHANGES**
- **withStyles**
Replace the `innerRef` prop with the `ref` prop. Refs are now automatically forwarded to the inner component.
```diff
import * as React from 'react';
import { withStyles } from '@material-ui/core/styles';
const MyComponent = withStyles({
root: {
backgroundColor: 'red',
},
})(({ classes }) => <div className={classes.root} />);
function MyOtherComponent(props) {
const ref = React.useRef();
- return <MyComponent innerRef={ref} />;
+ return <MyComponent ref={ref} />;
}
```
- **withTheme**
Replace the `innerRef` prop with the `ref` prop. Refs are now automatically forwarded to the inner component.
```diff
import * as React from 'react';
import { withTheme  } from '@material-ui/core/styles';
const MyComponent = withTheme(({ theme }) => …
```
=> [core] Remove deprecated `innerRef` prop

packages/material-ui-lab/src/DesktopDateRangePicker/DesktopDateRangePicker.test.tsx, packages/material-ui-lab/src/PickersDay/PickersDay.tsx, packages/material-ui-lab/src/internal/pickers/PickersArrowSwitcher.tsx
`aria-hidden` was applied to elements which should have `visibility: hidden`. These elements are already excluded from the a11y tree. If they are visible then they should be part of the a11y tree.
=> [pickers] Remove redundant aria-hidden

packages/material-ui-lab/src/internal/pickers/Picker/Picker.tsx
Seems fishy that we toggled it in the next commit. Suspecting some animation related requirement.
=> [pickers] Toggle mobile keyboard view in the same commit as the view changes

packages/material-ui-lab/src/DatePicker/DatePicker.tsx, packages/material-ui-lab/src/DatePicker/shared.ts, packages/material-ui-lab/src/DateRangePicker/DateRangePicker.tsx, packages/material-ui-lab/src/DateTimePicker/DateTimePicker.tsx, packages/material-ui-lab/src/DesktopDatePicker/DesktopDatePicker.tsx, packages/material-ui-lab/src/DesktopDateRangePicker/DesktopDateRangePicker.tsx, packages/material-ui-lab/src/DesktopDateTimePicker/DesktopDateTimePicker.tsx, packages/material-ui-lab/src/DesktopTimePicker/DesktopTimePicker.tsx, packages/material-ui-lab/src/MobileDatePicker/MobileDatePicker.tsx, packages/material-ui-lab/src/MobileDateRangePicker/MobileDateRangePicker.tsx, packages/material-ui-lab/src/MobileDateTimePicker/MobileDateTimePicker.tsx, packages/material-ui-lab/src/MobileTimePicker/MobileTimePicker.tsx, packages/material-ui-lab/src/StaticDatePicker/StaticDatePicker.tsx, packages/material-ui-lab/src/StaticDateRangePicker/StaticDateRangePicker.tsx, packages/material-ui-lab/src/StaticDateTimePicker/StaticDateTimePicker.tsx, packages/material-ui-lab/src/StaticTimePicker/StaticTimePicker.tsx, packages/material-ui-lab/src/TimePicker/TimePicker.tsx, packages/material-ui-lab/src/internal/pickers/hooks/usePickerState.ts
Every implementation provides a default value for `inputFormat`. The current invariant would therefore only validate our own implementation and we generally don't do this. Especially since `usePickerState` does not use the  `inputFormat`.
=> [internal][pickers] Don't validate inputFormat in production

docs/pages/api-docs/static-date-picker.json, docs/pages/api-docs/static-date-range-picker.json, docs/pages/api-docs/static-date-time-picker.json, docs/pages/api-docs/static-time-picker.json, packages/material-ui-lab/src/StaticDatePicker/StaticDatePicker.tsx, packages/material-ui-lab/src/StaticDateRangePicker/StaticDateRangePicker.tsx, packages/material-ui-lab/src/StaticDateTimePicker/StaticDateTimePicker.tsx, packages/material-ui-lab/src/StaticTimePicker/StaticTimePicker.tsx, packages/material-ui-lab/src/internal/pickers/wrappers/StaticWrapper.tsx
The input components are unused in the static variants. This is now clear after all the inlining work. The input props are also unused but this requires refactoring of `Picker` (which is the goal). But we can reduce the amount of work we have to do to better compose `Picker` in smaller steps that can live on their own.
Savings are minimal probably because we bundle them in some other way. Once all these refactorings are done, the bundle should be much smaller.
=> [pickers] Remove unused components from static variants

packages/material-ui-lab/src/DatePicker/DatePicker.tsx, packages/material-ui-lab/src/DateTimePicker/DateTimePicker.tsx, packages/material-ui-lab/src/TimePicker/TimePicker.tsx
Merged https://github.com/mui-org/material-ui/pull/26052 without https://github.com/mui-org/material-ui/pull/26053 in mind.
=> [internal][pickers] Minimal types for defaultizing in useInterceptProps

benchmark/browser/utils/index.js, benchmark/browser/webpack.config.js, package.json, test/karma.conf.profile.js, test/utils/createClientRender.tsx, yarn.lock
It's been removed in https://github.com/facebook/react/pull/20037 so let's drop it as well. Compat testing with `react@next` is more important than tracing interactions. Edit: Too late for it to be pre-emptive. Already broke: https://app.circleci.com/pipelines/github/mui-org/material-ui/41292/workflows/23024986-c4d2-42ec-9eb6-852507c803b8/jobs/246993
We can re-implement it for most (if not all) updates with a stack based approach anyway. Mainly because the updates we track are all sync anyway. I'm not even sure we trace more than one interaction anyway.
test-profile of this PR: https://mui-dashboard.netlify.app/test-profile/247033
=> [test] Remove scheduler/tracing

docs/src/pages/components/date-picker/FormPropsDatePickers.js, docs/src/pages/components/date-picker/FormPropsDatePickers.tsx, docs/src/pages/components/date-picker/date-picker.md, docs/src/pages/components/date-range-picker/FormPropsDateRangePickers.js, docs/src/pages/components/date-range-picker/FormPropsDateRangePickers.tsx, docs/src/pages/components/date-range-picker/date-range-picker.md, docs/src/pages/components/date-time-picker/FormPropsDateTimePickers.js, docs/src/pages/components/date-time-picker/FormPropsDateTimePickers.tsx, docs/src/pages/components/date-time-picker/date-time-picker.md, docs/src/pages/components/time-picker/FormPropsTimePickers.js, docs/src/pages/components/time-picker/FormPropsTimePickers.tsx, docs/src/pages/components/time-picker/time-picker.md, packages/material-ui-lab/src/DesktopDatePicker/DesktopDatePicker.test.tsx, packages/material-ui-lab/src/DesktopDateTimePicker/DesktopDateTimePicker.test.tsx, packages/material-ui-lab/src/DesktopTimePicker/DesktopTimePicker.test.tsx
1. added demos
- https://deploy-preview-26056--material-ui.netlify.app/components/date-picker/#form-props
- https://deploy-preview-26056--material-ui.netlify.app/components/time-picker/#form-props
- https://deploy-preview-26056--material-ui.netlify.app/components/date-time-picker/#form-props
- https://deploy-preview-26056--material-ui.netlify.app/components/date-range-picker/#form-props
2. added tests
Used as a baseline for https://github.com/mui-org/material-ui/pull/26055
=> [pickers] Document readonly/disabled pickers

packages/material-ui/src/Radio/RadioButtonIcon.js
Seems like this is the last component from `@material-ui/core` that uses the `withStyles` API.
=> [Radio] Migrate RadioButtonIcon to emotion

packages/material-ui-lab/src/DesktopDatePicker/DesktopDatePicker.tsx, packages/material-ui-lab/src/DesktopDateRangePicker/DesktopDateRangePicker.tsx, packages/material-ui-lab/src/DesktopDateTimePicker/DesktopDateTimePicker.tsx, packages/material-ui-lab/src/DesktopTimePicker/DesktopTimePicker.tsx, packages/material-ui-lab/src/MobileDatePicker/MobileDatePicker.tsx, packages/material-ui-lab/src/MobileDateRangePicker/MobileDateRangePicker.tsx, packages/material-ui-lab/src/MobileDateTimePicker/MobileDateTimePicker.tsx, packages/material-ui-lab/src/MobileTimePicker/MobileTimePicker.tsx, packages/material-ui-lab/src/internal/pickers/wrappers/DesktopTooltipWrapper.tsx, packages/material-ui-lab/src/internal/pickers/wrappers/DesktopWrapper.tsx, packages/material-ui-lab/src/internal/pickers/wrappers/MobileWrapper.tsx, packages/material-ui-lab/src/internal/pickers/wrappers/ResponsiveWrapper.tsx, packages/material-ui-lab/src/internal/pickers/wrappers/WrapperProps.ts
Same approach as https://github.com/mui-org/material-ui/pull/26052.
Used the opportunity to
1. get rid of some (implied) `React.FunctionComponent` usages
1. Remove unmaintained .propTypes
1. order props
=> [pickers] Remove unused components from mobile and desktop variants

packages/material-ui/src/Tabs/Tabs.js, packages/material-ui/src/Tabs/Tabs.test.js
Fixes #25923 
Preview: https://deploy-preview-26061--material-ui.netlify.app/components/tabs/#disabled-tab
=> [Tabs] Fix keyboard traversal over disabled tabs

packages/material-ui/src/SwipeableDrawer/SwipeArea.js
While trying to remove the dependency to `withStyles`, I noticed that this private component wasn't migrated to emotion.
=> [SwipeableDrawer] Migrate SwipeArea to emotion

docs/next.config.js, docs/src/modules/components/Demo.js, docs/src/modules/components/DemoToolbar.js
https://user-images.githubusercontent.com/12292047/116673275-7bfeed80-a9a3-11eb-88d9-451aac5512ba.mp4
Preview: http://deploy-preview-26065--material-ui.netlify.app/components/box
I often find myself switching between a PR and its base branch when doing manual testing. It was a bit annoying to constantly have to adjust these links manually so I just automatically include them now in deploys on `mui-org/material` (or local development). material-ui.com deploys should be minimally affected due to dead-code-elimination.
Also includes a permalink which was was not that trivial to get (always scrolled through netlify.com).
=> [docs] Add links for demo in different deploys

docs/src/pages/components/typography/typography.md
Update references from fontsource-roboto to @fontsource/roboto. The author has indicated that fontsource-roboto is now deprecated ( https://www.npmjs.com/package/fontsource-roboto ), and points users to instead use @fontsource/roboto ( https://www.npmjs.com/package/@fontsource/roboto )
=> [docs] Update typography.md to non-deprecated fontsource

docs/src/pages/components/date-picker/LocalizedDatePicker.js, docs/src/pages/components/date-picker/LocalizedDatePicker.tsx, docs/src/pages/components/date-picker/SubComponentsPickers.js, docs/src/pages/components/date-picker/SubComponentsPickers.tsx, docs/src/pages/components/date-range-picker/CustomDateRangeInputs.js, docs/src/pages/components/date-range-picker/CustomDateRangeInputs.tsx, docs/src/pages/components/date-range-picker/CustomDateRangePickerDay.js, docs/src/pages/components/date-range-picker/CustomDateRangePickerDay.tsx, docs/src/pages/components/pickers/MaterialUIPickers.js, docs/src/pages/components/pickers/MaterialUIPickers.tsx, docs/src/pages/components/time-picker/LocalizedTimePicker.js, docs/src/pages/components/time-picker/LocalizedTimePicker.tsx, docs/src/pages/components/time-picker/SubComponentsTimePickers.js, docs/src/pages/components/time-picker/SubComponentsTimePickers.tsx
A detail, apply the same convention as for the other components:
- name of the state = name of the prop
- name of the argument is prefixed with `new`
=> [docs] Normalize name use for state in pickers demo

.eslintrc.js, packages/eslint-plugin-material-ui/src/rules/mui-name-matches-component-name.js, packages/eslint-plugin-material-ui/src/rules/mui-name-matches-component-name.test.js, packages/material-ui-lab/src/DatePicker/DatePicker.tsx, packages/material-ui-lab/src/DatePicker/shared.ts, packages/material-ui-lab/src/DateTimePicker/DateTimePicker.tsx, packages/material-ui-lab/src/DateTimePicker/shared.ts, packages/material-ui-lab/src/DesktopDatePicker/DesktopDatePicker.tsx, packages/material-ui-lab/src/DesktopDateTimePicker/DesktopDateTimePicker.tsx, packages/material-ui-lab/src/DesktopTimePicker/DesktopTimePicker.tsx, packages/material-ui-lab/src/MobileDatePicker/MobileDatePicker.tsx, packages/material-ui-lab/src/MobileDateTimePicker/MobileDateTimePicker.tsx, packages/material-ui-lab/src/MobileTimePicker/MobileTimePicker.tsx, packages/material-ui-lab/src/StaticDatePicker/StaticDatePicker.tsx, packages/material-ui-lab/src/StaticDateTimePicker/StaticDateTimePicker.tsx, packages/material-ui-lab/src/StaticTimePicker/StaticTimePicker.tsx, packages/material-ui-lab/src/TimePicker/TimePicker.tsx, packages/material-ui-lab/src/TimePicker/shared.tsx
Removes the `*config` objects in favor of ES modules.
Will handle lint and other pickers later. Just want to get a look at bundle size. Edit: 
What I expected:
> StaticDatePicker | ▼ -55.7 kB (-25.29% ) | 165 kB | ▼ -16 kB (-22.65% ) | 54.7 kB
>-- | -- | -- | -- | --
>MobileDatePicker | ▼ -26.8 kB (-12.20% ) | 193 kB | ▼ -8.54 kB (-12.08% ) | 62.1 kB
>DesktopDatePicker | ▼ -25.5 kB (-11.62% ) | 194 kB | ▼ -5.9 kB (-8.35% ) | 64.7 kB
>@material-ui/lab | ▼ -210 B (-0.05% ) | 387 kB | ▲ +22 B (+0.02% ) | 116 kB
>DatePicker | ▼ -106 B (-0.05% ) | 220 kB | ▲ +106 B (+0.15% ) | 70.8 kB
=> [internal][pickers] Move useInterceptProps into module

packages/material-ui/src/Dialog/Dialog.js
I have found this opportunity looking into https://github.com/mui-org/material-ui/issues/21745#issuecomment-829518635. The style of the Dialog can be simplified, reducing bundle size, runtime cost maybe also a bit and setting a stone closer to the support of custom breakpoints
Before: https://609021bac16d7a0007430a6b--material-ui.netlify.app/components/dialogs#MaxWidthDialog
After: https://deploy-preview-26092--material-ui.netlify.app/components/dialogs/#optional-sizes
=> [Dialog] Improve support for custom breakpoints

packages/material-ui-lab/src/DatePicker/DatePicker.tsx, packages/material-ui-lab/src/DateTimePicker/DateTimePicker.tsx, packages/material-ui-lab/src/DesktopDatePicker/DesktopDatePicker.tsx, packages/material-ui-lab/src/DesktopDateTimePicker/DesktopDateTimePicker.tsx, packages/material-ui-lab/src/DesktopTimePicker/DesktopTimePicker.tsx, packages/material-ui-lab/src/MobileDatePicker/MobileDatePicker.tsx, packages/material-ui-lab/src/MobileDateTimePicker/MobileDateTimePicker.tsx, packages/material-ui-lab/src/MobileTimePicker/MobileTimePicker.tsx, packages/material-ui-lab/src/StaticDatePicker/StaticDatePicker.tsx, packages/material-ui-lab/src/StaticDateTimePicker/StaticDateTimePicker.tsx, packages/material-ui-lab/src/StaticTimePicker/StaticTimePicker.tsx, packages/material-ui-lab/src/TimePicker/TimePicker.tsx
They were incorrectly typed as `HTMLInputElement` when it was `HTMLDivElement` at runtime. This affects `TimePicker`, `DatePicker`, `DateTimePicker` and their mobile and desktop variants.
The types were incorrectly casted. See `ref: React.Ref<HTMLDivElement>,`
=> [pickers] Fix ref types

packages/material-ui-lab/src/DesktopDatePicker/DesktopDatePicker.tsx, packages/material-ui-lab/src/DesktopDateRangePicker/DesktopDateRangePicker.tsx, packages/material-ui-lab/src/DesktopDateTimePicker/DesktopDateTimePicker.tsx, packages/material-ui-lab/src/DesktopTimePicker/DesktopTimePicker.tsx
Clears up where props goes. 
Minor step with the goal of removing the `ResponsiveWrapper`.
=> [internal][pickers] Pass desktop wrapper props explicitly

test/regressions/fixtures/pickers/UncontrolledDateTimePicker.tsx, test/regressions/index.test.js
Helps with https://github.com/mui-org/material-ui/pull/26123
Right now I'm probably moving forward with https://github.com/mui-org/material-ui/pull/26123 even though it does regress in certain areas. Since the behavior is already fairly inconsistent (notice how the displayed view changes when switching to mobile i.e. it goes from year to calendar view) I feel safer just resetting entirely instead of only persisting some areas (e.g. `open` is persisted but not `view`).
Long term we can probably bring this back by using controlled/uncontrolled patterns. Short term people can restore the previous behavior by controlling `open`:
```tsx
function ResponsiveDateTimePicker() {
const [open, setOpen] = React.useState(false);
return <DateTimePicker open={open} onClose={() => setOpen(false)} …
```
=> [test] Add test for behavior when picker variant changes

docs/src/pages/components/box/box.md, docs/src/pages/customization/how-to-customize/how-to-customize.md, docs/src/pages/system/advanced/advanced.md, docs/src/pages/system/basics/BreakpointsAsObject.js, docs/src/pages/system/basics/BreakpointsAsObject.tsx, docs/src/pages/system/basics/basics.md
1. each sentence on a line 
Helps review
2. Link to what `sx` does whenever it is mentioned
This helps discovery if algolia decides to display a mention of `sx` as the first result
3. Remove some `this` mention (https://developers.google.com/tech-writing/one/words#this_and_that)
`this` can work if the reference is obvious. That's not always obvious though and may even change over time if sentences move farther apart. 
4. Describe in prose what `sx={{ lg: {} }}` matches
breakpoints comparison was mentioned in the paragraph earlier in a code comment so easy to miss if you already know `sx` but not how breakpoints work. 
See my struggle in https://github.com/mui-org/material-ui/pull/26135#discussion_r626396190
=> [docs] More explicit breakpoint documentation in `sx`

docs/babel.config.js, test/e2e/.mocharc.js, test/e2e/index.js, test/e2e/index.test.ts, test/regressions/.mocharc.js, test/regressions/index.js, test/utils/initPlaywrightMatchers.ts, test/utils/setupBabelPlaywright.js
Cherry-picked some enhancements from https://github.com/mui-org/material-ui/pull/26107/files that are useful when testing `react@experimental`.
=> [core] Improve `react@experimental` compat

docs/src/pages/components/tree-view/BarTreeView.js, docs/src/pages/components/tree-view/BarTreeView.tsx, docs/src/pages/components/tree-view/ControlledTreeView.js, docs/src/pages/components/tree-view/ControlledTreeView.tsx, docs/src/pages/components/tree-view/CustomizedTreeView.js, docs/src/pages/components/tree-view/CustomizedTreeView.tsx, docs/src/pages/components/tree-view/DisabledTreeItems.js, docs/src/pages/components/tree-view/DisabledTreeItems.tsx, docs/src/pages/components/tree-view/FileSystemNavigator.js, docs/src/pages/components/tree-view/FileSystemNavigator.tsx, docs/src/pages/components/tree-view/GmailTreeView.js, docs/src/pages/components/tree-view/GmailTreeView.tsx, docs/src/pages/components/tree-view/IconExpansionTreeView.js, docs/src/pages/components/tree-view/IconExpansionTreeView.tsx, docs/src/pages/components/tree-view/MultiSelectTreeView.js, docs/src/pages/components/tree-view/MultiSelectTreeView.tsx, docs/src/pages/components/tree-view/RichObjectTreeView.js, docs/src/pages/components/tree-view/RichObjectTreeView.tsx
Migrates `TreeView` demos to emotion. One of One of https://github.com/mui-org/material-ui/issues/16947
https://deploy-preview-26146--material-ui.netlify.app/components/tree-view/
=> [docs] Migrate TreeView demos

docs/src/pages/styles/advanced/GlobalCss.js, docs/src/pages/styles/advanced/GlobalCss.tsx, docs/src/pages/styles/advanced/HybridGlobalCss.js, docs/src/pages/styles/advanced/HybridGlobalCss.tsx, docs/src/pages/styles/advanced/ThemeNesting.js, docs/src/pages/styles/advanced/ThemeNesting.tsx, docs/src/pages/styles/advanced/Theming.js, docs/src/pages/styles/advanced/Theming.tsx, docs/src/pages/styles/advanced/UseTheme.js, docs/src/pages/styles/advanced/UseTheme.tsx, docs/src/pages/styles/basics/AdaptingHOC.js, docs/src/pages/styles/basics/AdaptingHOC.tsx, docs/src/pages/styles/basics/AdaptingHook.js, docs/src/pages/styles/basics/AdaptingHook.tsx, docs/src/pages/styles/basics/HigherOrderComponent.js, docs/src/pages/styles/basics/HigherOrderComponent.tsx, docs/src/pages/styles/basics/Hook.js, docs/src/pages/styles/basics/Hook.tsx, docs/src/pages/styles/basics/NestedStylesHook.js, docs/src/pages/styles/basics/NestedStylesHook.tsx, docs/src/pages/styles/basics/StressTest.js, docs/src/pages/styles/basics/StressTest.tsx
This PR updates the imports on the docs/styles pages to use only `@material-ui/styles`
=> [docs] Remove `@material-ui/core/styles` from the styles pages

docs/src/pages/components/switches/CustomizedSwitches.js, docs/src/pages/components/switches/CustomizedSwitches.tsx
Added Android 12 switch and custom icon in thumb example to the docs
Issue: #25919
Fix #25985
Preview: https://deploy-preview-26096--material-ui.netlify.app/components/switches/#customized-switches
=> [docs] Add new customized switch examples

packages/material-ui/src/styles/overrides.d.ts, packages/material-ui/src/styles/variants.d.ts
Updates the `theme.components.styleOverrides` and `theme.components.variants` to use the same typigns for the styles as the `experimentalStyled()`.
=> [core] Update typings for theme's components

docs/pages/api-docs/tab-list.json, packages/material-ui-lab/src/TabList/TabList.d.ts, packages/material-ui-lab/src/TabList/TabList.js, packages/material-ui-lab/src/TabList/TabList.test.js
=> [Tabs] Fix support for null children in TabList

docs/src/pages/components/steppers/CustomizedSteppers.js, docs/src/pages/components/steppers/CustomizedSteppers.tsx, docs/src/pages/components/steppers/DotsMobileStepper.js, docs/src/pages/components/steppers/DotsMobileStepper.tsx, docs/src/pages/components/steppers/HorizontalLinearAlternativeLabelStepper.js, docs/src/pages/components/steppers/HorizontalLinearAlternativeLabelStepper.tsx, docs/src/pages/components/steppers/HorizontalLinearStepper.js, docs/src/pages/components/steppers/HorizontalLinearStepper.tsx, docs/src/pages/components/steppers/HorizontalNonLinearStepper.js, docs/src/pages/components/steppers/HorizontalNonLinearStepper.tsx, docs/src/pages/components/steppers/HorizontalStepperWithError.js, docs/src/pages/components/steppers/HorizontalStepperWithError.tsx, docs/src/pages/components/steppers/ProgressMobileStepper.js, docs/src/pages/components/steppers/ProgressMobileStepper.tsx, docs/src/pages/components/steppers/SwipeableTextMobileStepper.js, docs/src/pages/components/steppers/SwipeableTextMobileStepper.tsx, docs/src/pages/components/steppers/TextMobileStepper.js, docs/src/pages/components/steppers/TextMobileStepper.tsx, docs/src/pages/components/steppers/VerticalLinearStepper.js, docs/src/pages/components/steppers/VerticalLinearStepper.tsx, docs/src/pages/components/tooltips/CustomizedTooltips.js, docs/src/pages/components/tooltips/CustomizedTooltips.tsx, docs/src/pages/components/tooltips/PositionedTooltips.js, docs/src/pages/components/tooltips/PositionedTooltips.tsx, docs/src/pages/components/tooltips/VariableWidth.js, docs/src/pages/components/tooltips/VariableWidth.tsx
https://deploy-preview-26165--material-ui.netlify.app/components/tooltips/
=> [docs] Migrate Tooltip, Steppers demos to emotion

docs/src/pages/guides/composition/composition.md, docs/src/pages/guides/routing/ListRouter.js, docs/src/pages/guides/routing/ListRouter.tsx
=> [docs] Fixed React.forwardRef missing display name ESLint error

packages/material-ui/src/TableCell/TableCell.js
HEAD:
https://next.material-ui.com/components/tables/#sticky-header
https://user-images.githubusercontent.com/4471489/117297334-60e61f00-ae76-11eb-8246-ef1e0611a3b2.mov
PR:
https://deploy-preview-26159--material-ui.netlify.app/components/tables/#sticky-header
https://user-images.githubusercontent.com/4471489/117297358-693e5a00-ae76-11eb-93db-9c3ff0305fce.mov
=> [Table] Synchronize horizontal sticky header position with body

docs/src/pages/guides/migration-v4/migration-v4.md, framer/Material-UI.framerfx/code/ThemeProvider.tsx, packages/material-ui/src/styles/index.d.ts, packages/material-ui/src/styles/index.js
- [theme] The `MuiThemeProvider` is no longer exported from `@material-ui/core/styles`. Use `ThemeProvider` instead.
```diff
-import { MuiThemeProvider } from '@material-ui/core/styles';
+import { ThemeProvider } from '@material-ui/core/styles';
```
---
Part of #20012
=> [theme] Remove `MuiThemeProvider` alias

dangerfile.js
The new page caches more aggressively so subsequent visits should be considerably faster (for the same commit obviously). On a cache-miss it's not clear though.
Since this uses caching, vercel and experimental tech (remix.run) it'll just live next to the stable page.
=> [core] Link to experimental size-comparison page

packages/material-ui/src/ButtonBase/ButtonBase.js, packages/material-ui/src/ButtonBase/ButtonBase.test.js
Followed @oliviertassinari instructions on adding a check for the `aria-disabled` attribute.
Fixes: #25531
=> [ButtonBase] Omit aria-disabled if not disabled

docs/src/pages/components/tree-view/ControlledTreeView.js, docs/src/pages/components/tree-view/ControlledTreeView.tsx, docs/src/pages/components/tree-view/CustomizedTreeView.js, docs/src/pages/components/tree-view/CustomizedTreeView.tsx, docs/src/pages/components/tree-view/DisabledTreeItems.js, docs/src/pages/components/tree-view/DisabledTreeItems.tsx, docs/src/pages/components/tree-view/FileSystemNavigator.js, docs/src/pages/components/tree-view/FileSystemNavigator.tsx, docs/src/pages/components/tree-view/GmailTreeView.js, docs/src/pages/components/tree-view/GmailTreeView.tsx, docs/src/pages/components/tree-view/IconExpansionTreeView.js, docs/src/pages/components/tree-view/IconExpansionTreeView.tsx, docs/src/pages/components/tree-view/MultiSelectTreeView.js, docs/src/pages/components/tree-view/MultiSelectTreeView.tsx, docs/src/pages/components/tree-view/RichObjectTreeView.js, docs/src/pages/components/tree-view/RichObjectTreeView.tsx
The [gmail clone treeview](https://6093d26ee081cf00074f9d5d--material-ui.netlify.app/components/tree-view#GmailTreeView) overflows its demo containers
Noticed on the gmail clone which now behaves like actual gmail (adds a scrollbar on overflow). Applied to all the other demos which can have the same issue on larger font sizes.
Before:
-- https://6093d26ee081cf00074f9d5d--material-ui.netlify.app/components/tree-view#GmailTreeView
After:
-- https://deploy-preview-26161--material-ui.netlify.app/components/tree-view/#GmailTreeView
=> [docs] Ensure TreeView demos don't overflow demo container

docs/src/modules/components/AppFrame.js
Noticed that [`Router.onRouteChangeComplete` wasn't documented](https://nextjs.org/docs/api-reference/next/router#routerevents) so I used the opportunity to make the implementation not leak if we navigate to pages without NProgress.
=> [docs] Use public next/router events API

benchmark/browser/scenarios/make-styles/index.js, docs/pages/index.tsx, docs/src/modules/components/MarkdownElement.js, docs/src/pages/components/buttons/ButtonBase.js, docs/src/pages/components/buttons/ButtonBase.tsx, docs/src/pages/components/date-picker/CustomDay.js, docs/src/pages/components/date-picker/CustomDay.tsx, docs/src/pages/components/date-picker/SubComponentsPickers.js, docs/src/pages/components/date-picker/SubComponentsPickers.tsx, docs/src/pages/components/date-range-picker/CustomDateRangePickerDay.js, docs/src/pages/components/date-range-picker/CustomDateRangePickerDay.tsx, docs/src/pages/components/dividers/DividerText.js, docs/src/pages/components/dividers/DividerText.tsx, docs/src/pages/components/dividers/VerticalDividerText.js, docs/src/pages/components/dividers/VerticalDividerText.tsx, docs/src/pages/components/material-icons/SearchIcons.js, docs/src/pages/components/popper/ScrollPlayground.js, docs/src/pages/customization/default-theme/DefaultTheme.js, docs/src/pages/customization/palette/DarkTheme.js, docs/src/pages/guides/right-to-left/RtlOptOut.js, docs/src/pages/guides/right-to-left/RtlOptOut.tsx, docs/src/pages/production-error/ErrorDecoder.js, test/regressions/fixtures/Menu/MenuContentAnchors.js, test/regressions/fixtures/Textarea/Textarea.js
This PR removes last dependencies on `makeStyles` from `@material-ui/core/styles`. Next step would be removing this util from the core.
=> [docs] Remove last dependencies on `makeStyles` from `@material-ui/core/styles`

docs/src/pages/guides/migration-v4/migration-v4.md, packages/material-ui/src/Autocomplete/Autocomplete.js, packages/material-ui/src/Autocomplete/Autocomplete.test.js, packages/material-ui/src/useAutocomplete/useAutocomplete.js
- [Autocomplete] Apply `.Mui-focused` instead of `data-focus` on the focused option. This helps with consistency in the global CSS API. 
```diff
-'.MuiAutocomplete-option[data-focus="true"]': {
+'.MuiAutocomplete-option.Mui-focused': {
```
---
One of #20012 
Closes #19692
=> [Autocomplete] Apply `.Mui-focused` instead of `data-focus` on the focused option

docs/pages/_app.js, docs/src/modules/utils/getDemoConfig.js, docs/src/pages/guides/interoperability/interoperability.md, docs/src/pages/guides/migration-v4/migration-v4.md, examples/create-react-app-with-styled-components-typescript/src/index.tsx, examples/create-react-app-with-styled-components/src/index.js, examples/create-react-app-with-typescript/src/index.tsx, examples/create-react-app/src/index.js, examples/gatsby-theme/src/pages/about.js, examples/gatsby-theme/src/pages/index.js, examples/gatsby/src/pages/about.js, examples/gatsby/src/pages/index.js, examples/preact/src/App.js, packages/material-ui/scripts/rollup.config.js, packages/material-ui/src/StyledEngineProvider/index.d.ts, packages/material-ui/src/StyledEngineProvider/index.js, packages/material-ui/src/index.d.ts, packages/material-ui/src/index.js, packages/material-ui/src/styles/index.d.ts, packages/material-ui/src/styles/index.js, test/e2e/TestViewer.js, test/regressions/TestViewer.js
`StyledEngineProvider` location is changed. The previous location is deprecated, it will be removed in v5.beta.
```diff
-import StyledEngineProvider from '@material-ui/core/StyledEngineProvider ';
+import { StyledEngineProvider } from '@material-ui/core/styles';
```
Closes #23208
One of #20012
=> [core] Move `StyledEngineProvider` to `@material-ui/core/styles`

packages/material-ui-lab/src/internal/pickers/wrappers/StaticWrapper.tsx
=> [pickers] Migrate StaticWrapper to emotion

docs/pages/api-docs/native-select.json, docs/pages/api-docs/select.json, docs/src/pages/guides/migration-v4/migration-v4.md, docs/translations/api-docs/native-select/native-select.json, docs/translations/api-docs/select/select.json, packages/material-ui/src/NativeSelect/NativeSelect.d.ts, packages/material-ui/src/NativeSelect/NativeSelect.js, packages/material-ui/src/NativeSelect/NativeSelect.test.js, packages/material-ui/src/NativeSelect/NativeSelectInput.js, packages/material-ui/src/NativeSelect/nativeSelectClasses.js, packages/material-ui/src/Select/Select.d.ts, packages/material-ui/src/Select/Select.js, packages/material-ui/src/Select/Select.test.js, packages/material-ui/src/Select/SelectInput.js, packages/material-ui/src/Select/selectClasses.js, packages/material-ui/src/TablePagination/TablePagination.js
- [Select] The `selectMenu` slot was merged into `select` because `selectMenu` slot was redundant. The `root` slot is no longer applied to the select, but to the root.
```diff
-<Select classes={{ root: 'class1', select: 'class2', selectMenu: 'class3' }} />
+<Select classes={{ root: 'class1', select: 'class2 class3' }} />
```
- [NativeSelect] The `selectMenu` slot was merged into `select` because `selectMenu` slot was redundant. The `root` slot is no longer applied to the select, but to the root.
```diff
-<NativeSelect classes={{ root: 'class1', select: 'class2', selectMenu: 'class3' }} />
+<NativeSelect classes={{ select: 'class1 class2 class3' }} />
```
- [TablePagination] The `classes.input` key was changed to be applied on another element. Use `classes.select` instead.
```diff …
```
=> [Select][NativeSelect] Polish CSS classes

packages/material-ui/src/OutlinedInput/NotchedOutline.d.ts
If using NotchedOutline as a direct import TypeScript reported compilation error because label was missing from the NotchedOutlineProps types.
=> [core] Fix NotchedOutlineProps type

packages/material-ui/src/FilledInput/FilledInput.js, packages/material-ui/src/FilledInput/FilledInput.test.js, packages/material-ui/src/Input/Input.test.js, packages/material-ui/src/OutlinedInput/OutlinedInput.test.js
=> [TextField] Fix classes forward to InputBase 

test/karma.conf.js
For example, `next:  https://circleci.com/gh/mui-org/material-ui/252223` or `12345: https://circleci.com/gh/mui-org/material-ui/252223`
Prefixing the pr number with `#` does not work: https://github.com/mui-org/material-ui/pull/26322#discussion_r633067960
=> [core] Include human readable target in the browserstack build

packages/material-ui-lab/src/ClockPicker/Clock.tsx
Another internal component.
One of #24405
=> [pickers] Migrate Clock to emotion

docs/pages/api-docs/container.json, packages/material-ui/src/Container/Container.d.ts, packages/material-ui/src/Container/Container.js, packages/material-ui/test/typescript/moduleAugmentation/breakpointsOverrides.spec.tsx, packages/material-ui/test/typescript/moduleAugmentation/breakpointsOverrides.tsconfig.json
With this PR I'm fixing the Container component when you define custom breakpoints.
Used the patch code by @oliviertassinari in this fix #21745
Also, run tests & try it in my own project. Everything working 💯
=> [Container] Fix support for custom breakpoints

docs/src/pages/components/slider/ColorSlider.js, docs/src/pages/components/slider/ColorSlider.tsx, docs/src/pages/components/slider/ContinuousSlider.js, docs/src/pages/components/slider/ContinuousSlider.tsx, docs/src/pages/components/slider/DiscreteSlider.js, docs/src/pages/components/slider/DiscreteSlider.tsx, docs/src/pages/components/slider/DiscreteSliderLabel.js, docs/src/pages/components/slider/DiscreteSliderLabel.tsx, docs/src/pages/components/slider/DiscreteSliderMarks.js, docs/src/pages/components/slider/DiscreteSliderMarks.tsx, docs/src/pages/components/slider/DiscreteSliderSteps.tsx, docs/src/pages/components/slider/DiscreteSliderValues.js, docs/src/pages/components/slider/DiscreteSliderValues.tsx, docs/src/pages/components/slider/MinimumDistanceSlider.js, docs/src/pages/components/slider/MinimumDistanceSlider.tsx, docs/src/pages/components/slider/RangeSlider.js, docs/src/pages/components/slider/RangeSlider.tsx, docs/src/pages/components/slider/UnstyledSlider.js, docs/src/pages/components/slider/UnstyledSlider.tsx, docs/src/pages/components/slider/VerticalAccessibleSlider.js, docs/src/pages/components/slider/VerticalAccessibleSlider.tsx, docs/src/pages/components/slider/VerticalSlider.js, docs/src/pages/components/slider/VerticalSlider.tsx, docs/src/pages/components/slider/slider.md
A follow-up on #26285
- Shorten the demo and remove distractions
- Add color demo
- Update the unstyled demo to match Ant Design / Fluent UI pattern.
Preview https://deploy-preview-26324--material-ui.netlify.app/components/slider/
=> [docs] Simplify demos slider

packages/material-ui-lab/src/DateTimePicker/DateTimePickerTabs.tsx, packages/material-ui-lab/src/DateTimePicker/DateTimePickerToolbar.tsx
This PR include 2 internal components for DateTimePicker
- DateTimePickerTabs
- DateTimePickerToolbar
=> [DateTimePicker] Migrate DateTimePickerTabs and Toolbar to emotion

packages/material-ui-lab/src/CalendarPicker/PickersFadeTransitionGroup.tsx, packages/material-ui-lab/src/CalendarPicker/PickersSlideTransition.tsx
included similar PickersTransition components (both are internal components)
- PickersSlideTransition
- PickersFadeTransitionGroup
=> [pickers] Migrate PickersTransition to emotion

packages/material-ui/src/Tooltip/Tooltip.js
Closes #23363
I gave a second look at the issue. Since my last proposal #23363, I have changed a bit my hypothesis and conclusion. At first, I thought that using the screen width to change the density of the tooltip would make the most sense, but I realized that with responsive font sizes, we do the opposite, we reduce the font size, we don't increase it. Also, these density visual changes seem to contribute to increasing the gap, which uses `styleProps.touch` too.
=> [Tooltip] Improve handling of small vs. touch screens

packages/material-ui-lab/src/internal/pickers/PickersModalDialog.tsx
**Note**
- replace `:first-child` with `:first-of-type` due to emotion error
- remove `withAdditionalAction` and use `styleProps` styling instead
=> [pickers] Migrate PickersModalDialog to emotion

packages/material-ui-lab/src/CalendarPicker/PickersCalendar.tsx, packages/material-ui-lab/src/DateRangePicker/DateRangePicker.tsx, packages/material-ui-lab/src/DateRangePicker/DateRangePickerInput.tsx, packages/material-ui-lab/src/DateRangePicker/DateRangePickerToolbar.tsx, packages/material-ui-lab/src/DateRangePicker/DateRangePickerViewDesktop.tsx, packages/material-ui-lab/src/DesktopDateRangePicker/DesktopDateRangePicker.tsx, packages/material-ui-lab/src/MobileDateRangePicker/MobileDateRangePicker.tsx
These internal components follow the same approach for migration so I think it is easier to bundle them together to review.
- PickersCalendar
- DateRangePickerViewDesktop
- DateRangePickerToolbar
- DateRangePickerInput
=> [DateRangePicker] Migrate internal components to emotion

docs/pages/api-docs/dialog.json, packages/material-ui/src/Dialog/Dialog.d.ts, packages/material-ui/src/Dialog/Dialog.js, packages/material-ui/test/typescript/moduleAugmentation/breakpointsOverrides.spec.tsx
Update Dialog typings to accept custom breakpoints on `maxWidth` by using `Breakpoint` utility.
Tests run with `yarn test` and `yarn proptypes`
Closes #26330
=> [Dialog] Fix support for custom breakpoints

packages/material-ui/src/styles/index.d.ts
Leftover from https://github.com/mui-org/material-ui/pull/26100
=> [core] Remove `@material-ui/styles` dependencies from declaration files too

docs/pages/api-docs/clock-picker.json, docs/pages/api-docs/date-time-picker.json, docs/pages/api-docs/desktop-date-time-picker.json, docs/pages/api-docs/desktop-time-picker.json, docs/pages/api-docs/mobile-date-time-picker.json, docs/pages/api-docs/mobile-time-picker.json, docs/pages/api-docs/static-date-time-picker.json, docs/pages/api-docs/static-time-picker.json, docs/pages/api-docs/time-picker.json, docs/src/pages/components/time-picker/SubComponentsTimePickers.js, docs/src/pages/components/time-picker/SubComponentsTimePickers.tsx, docs/translations/api-docs/clock-picker/clock-picker.json, docs/translations/api-docs/desktop-time-picker/desktop-time-picker.json, docs/translations/api-docs/mobile-time-picker/mobile-time-picker.json, docs/translations/api-docs/static-time-picker/static-time-picker.json, docs/translations/api-docs/time-picker/time-picker.json, packages/material-ui-lab/src/ClockPicker/Clock.tsx, packages/material-ui-lab/src/ClockPicker/ClockNumber.tsx, packages/material-ui-lab/src/ClockPicker/ClockPicker.test.tsx, packages/material-ui-lab/src/ClockPicker/ClockPicker.tsx, packages/material-ui-lab/src/DateTimePicker/DateTimePicker.tsx, packages/material-ui-lab/src/DesktopDateTimePicker/DesktopDateTimePicker.tsx, packages/material-ui-lab/src/DesktopTimePicker/DesktopTimePicker.tsx, packages/material-ui-lab/src/MobileDateTimePicker/MobileDateTimePicker.tsx, packages/material-ui-lab/src/MobileTimePicker/MobileTimePicker.tsx, packages/material-ui-lab/src/StaticDateTimePicker/StaticDateTimePicker.tsx, packages/material-ui-lab/src/StaticTimePicker/StaticTimePicker.tsx, packages/material-ui-lab/src/TimePicker/TimePicker.tsx, packages/material-ui-lab/src/internal/pickers/Picker/Picker.tsx
Removes `allowKeyboardControl` from `ClockPicker` (and `TimePicker` and variants)
Part of https://github.com/mui-org/material-ui/issues/25481
1. removes `allowKeyboardControl` from `ClockPicker` (and `TimePicker` and variants)
1. autofocus clock when the time picker is opened
1. allows keyboard access of clock picker in static mode
1. rework a11y tree
I don't know what the pattern was before i.e. I've never seen menu + a separate aria-live that announces the value before. Now the clock is implemented as a listbox where the hours are options. 
Preview: https://deploy-preview-26400--material-ui.netlify.app/components/time-picker
Follow-up:
=> [ClockPicker] Rework keyboard implementation

packages/material-ui-lab/src/TreeView/TreeView.js, packages/material-ui-lab/src/TreeView/TreeView.test.js
This should fix #26404 using the implementation I suggested in the issue.
=> [TreeView] Correctly select items in deeply nested trees

packages/material-ui-docs/package.json, packages/material-ui-lab/package.json, packages/material-ui-system/package.json
This is a follow-up on the lead given in https://github.com/mui-org/material-ui/issues/20012#issuecomment-844724225. I have created a new project with **yarn v2** and vite, using the date picker. It yields two resolution issues:
I have pushed:
- 5353bd6 to solve the first error. The system doesn't need react-dom, so it won't complain in the lab that depends on it.
- 180ac23 to solve the second error. react-transition-group depends on react-dom, we need to declare it.
- dc28ce4 bonus
=> [core] Fix peer dependencies declaration with yarn v2

docs/src/pages/components/material-icons/SearchIcons.js, docs/src/pages/components/material-icons/synonyms.js
Preview: https://deploy-preview-26336--material-ui.netlify.app/components/material-icons/
The timeout always felt weird since the copied state doesn't actually change after N seconds. I feel like capturing the user intention by clearing when the cursor moves (i.e. the tooltip disappears) is the better UX here.
Included a bunch of refactorings to the page that stood out to me. Only b524eeafd0cc8d3943acdd75d9b8ba31b559885d changes user observable behavior. Review by commit is advised.
=> [docs] Persist copied state indefinitely or until the user moves their cursor

packages/material-ui-lab/src/internal/pickers/test-utils.tsx
Previously `setProps` from `createPickerRender` would set props on the provider. This was suprising to me and probably not what we want generally.
=> [test] setProps from createPickerRender should set props on the rendered element

.circleci/config.yml
Instead of cache+yarn we now persist and attach the whole workspace.
On a normal run this has no effect (persisting 50s + attaching 10s vs cache+yarn 60s). However, failures  due to flakyness are going to be a lot faster since they only have to attach the workspace. So on these "restart from failed" runs we save 50s.
Will try this out starting next week if accepted and see how this affects CI perf.
=> [core] Leverage CircleCI workspaces for jobs after checkout

packages/material-ui/src/InputAdornment/InputAdornment.test.js
Noticed in the CI log of #26428.
The CI doesn't fail for them, for some reason.
=> [test] Fix prop-type warning

.circleci/config.yml, test/utils/userEvent.ts
Otherwise it wouldn't behave the same as using `fireEvent.click`. `react@next` started failing due to not flushing the scheduled effects.
=> [test] Flush scheduled effects before user event returns

docs/src/pages/components/selects/MultipleSelect.js, docs/src/pages/components/selects/MultipleSelect.tsx, docs/src/pages/components/selects/MultipleSelectCheckmarks.js, docs/src/pages/components/selects/MultipleSelectCheckmarks.tsx, docs/src/pages/components/selects/MultipleSelectChip.js, docs/src/pages/components/selects/MultipleSelectChip.tsx
This PR fixed typo in MultipleSelect component docs.
The changes affect these components
- MultipleSelect.js
- MultipleSelect.tsx
- MultipleSelectCheckmarks.js
- MultipleSelectCheckmarks.tsx
- MultipleSelectChip.js
- MultipleSelectChip.tsx
=> [docs] Typo in MultipleSelect

docs/src/pages/components/tabs/TabsWrappedLabel.js, docs/src/pages/components/tabs/TabsWrappedLabel.tsx, docs/src/pages/guides/migration-v4/migration-v4.md, packages/material-ui/src/Tab/Tab.js
closes #15824
The change follow [material design spec](https://material.io/components/tabs#specs)
Preview: https://deploy-preview-26458--material-ui.netlify.app/components/tabs/
=> [Tabs] Update `min` & `max` width and remove `minWidth` media query

.git-blame-ignore-revs
Previously recommended a global config but that crashes git-blame in any repository without such a file.
=> [docs] Add warning about git-blame-ignore-revs

packages/material-ui/src/Autocomplete/Autocomplete.js, packages/material-ui/src/Select/SelectInput.js
Closes #18493
Address point 1. of #18136
=> [Select] Open popup below button

packages/material-ui-lab/src/ClockPicker/Clock.tsx, packages/material-ui-lab/src/ClockPicker/ClockNumbers.tsx, packages/material-ui-utils/src/useId.d.ts, packages/material-ui-utils/src/useId.ts
The typings are currently incorrect (they return a non-nullable string when it is in fact always null on the server). Cherry-pick from https://github.com/mui-org/material-ui/pull/26489
=> [utils] Convert useId to TypeScript

docs/pages/api-docs/dialog-title.json, docs/src/modules/utils/defaultPropsHandler.js, docs/src/pages/components/dialogs/CustomizedDialogs.js, docs/src/pages/components/dialogs/CustomizedDialogs.tsx, docs/src/pages/components/dialogs/SimpleDialog.js, docs/src/pages/components/dialogs/SimpleDialog.tsx, docs/src/pages/guides/migration-v4/migration-v4.md, docs/translations/api-docs/dialog-title/dialog-title.json, packages/material-ui/src/DialogContent/DialogContent.js, packages/material-ui/src/DialogContentText/DialogContentText.js, packages/material-ui/src/DialogTitle/DialogTitle.d.ts, packages/material-ui/src/DialogTitle/DialogTitle.js, packages/material-ui/src/DialogTitle/DialogTitle.test.js
- [Dialog] Flatten DialogTitle DOM structure, remove `disableTypography` prop
```diff
-<DialogTitle disableTypography>
-  <Typography variant="h4" component="h2">
+<DialogTitle>
+  <Typography variant="h4" component="span">
My header
</Typography>
```
---
Quickly testing. The goal of https://github.com/mui-org/material-ui/issues/19696 was to make the impl and behavior simpler. But the discussion in https://github.com/mui-org/material-ui/issues/19696 goes in the opposite direction right now.
https://deploy-preview-26323--material-ui.netlify.app/components/dialogs/
Closes #19696
Solve https://github.com/mui-org/material-ui/issues/26386#issuecomment-846354982
=> [Dialog] Flatten DialogTitle DOM structure, remove `disableTypography`

docs/src/modules/components/MarkdownElement.js, docs/src/pages.js
Once merged this PR, sync with @mui-org/x before doing the push to the docs repo. This is to prevent dead links since existing pages were moved.
---
Related to https://github.com/mui-org/material-ui-x/pull/1529
- 8e42f12 - adds paths for new API pages 
- 642cc69 - adds a class name to be used on optional properties:
Preview https://deploy-preview-1529--material-ui-x.netlify.app/api/data-grid/data-grid/
=> [docs] Prepare for data grid auto-generated docs

docs/pages/api-docs/tooltip.json, docs/translations/api-docs/tooltip/tooltip.json, packages/material-ui/src/Tooltip/Tooltip.js, packages/material-ui/src/Tooltip/tooltipClasses.ts
Previously the Tooltip could re-open during exit transitions. This could create flickering tooltips e.g. https://github.com/mui-org/material-ui/issues/26416. It's probably best to finish exiting before you can open a Tooltip again
Closes https://github.com/mui-org/material-ui/issues/26416
Note that the repro still needs adjustment: 
```diff
)(({ theme }) => ({
[`& .${tooltipClasses.tooltip}`]: {
backgroundColor: "#f5f5f9",
color: "rgba(0, 0, 0, 0.87)",
maxWidth: "none",
padding: `${theme.spacing(1.5)} ${theme.spacing(1.5)}`,
boxShadow: theme.shadows[10],
-    pointerEvents: "auto"
},
[`& .${tooltipClasses.arrow}`]: {
color: "#f5f5f9"
}
}));
```
--- https://codesandbox.io/s/nervous-perlman-k0pq5
=> [Tooltip] Finish exiting once started

packages/material-ui-system/src/createBox.js
FIxing an issue foind while testing out `styled-components` usage with the new `Box` component. 
Before:
https://codesandbox.io/s/wizardly-dew-9m8p8?file=/src/index.js
Now:
https://codesandbox.io/s/condescending-nightingale-mdc80?file=/package.json
=> [Box] Fix runtime error when using styled-components without ThemeProvider

docs/pages/api-docs/app-bar.json, docs/src/modules/components/AppFrame.js, docs/src/pages/components/app-bar/app-bar.md, docs/src/pages/guides/migration-v4/migration-v4.md, docs/translations/api-docs/app-bar/app-bar.json, packages/material-ui/src/AppBar/AppBar.d.ts, packages/material-ui/src/AppBar/AppBar.js
closes #18308
Preview https://deploy-preview-26545--material-ui.netlify.app/components/app-bar/
The case of AppBar is special because the specified color should be enabled only in `light` mode. I propose the fix by adding another flag (naming can be discussed) to neglect the color prop in dark mode. This approach works great because `AppBar` inherit `Paper` which support elevation already. The flag is `true` by default (consider breaking change) due to the [material design spec](https://material.io/design/color/dark-theme.html)
Even bottom appbar also use elevation https://material.io/design/color/dark-theme.html#custom-application
```jsx
<AppBar color="primary" /> // color has no effect in dark mode
```
```jsx
<AppBar color="primary" enableColorOnDark />
```
```js
createTheme({ …
```
=> [AppBar] Fix background color on dark mode

packages/material-ui/src/NativeSelect/NativeSelectInput.js
Modifying the calc in order to center the select arrow vertically when the font size is changed [#26401}
Fixes #26401
=> [Select] Fix custom font size centering arrow

docs/scripts/buildApi.ts, docs/translations/api-docs/rating/rating.json, packages/material-ui/src/Rating/Rating.d.ts, packages/material-ui/src/Rating/Rating.js
- [o] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui-org/material-ui/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).
The previous PR I created somehow got closed immediately after I reverted my previous change.  Please look at this PR instead.
@eps1lon you told me to look at material-ui/packages/material-ui/src/Rating/Rating.d.ts Line 82, but I think you meant I might take a look of a different line of Rating.d.ts.  I couldn't understand when I looked an line 82.
Put in null in onChange in Rating, and also put in handling NullLiteral in auto generation of the descriptions of a function and its parameters.
Closes #26497
=> [docs] `Rating` `value` is nullable in `onChange`

docs/src/pages/guides/migration-v4/migration-v4.md
Developers that still use `makeStyles` and `withStyles`, now need to use the utils exported from `@material-ui/styles`. However, if these are used together with `@material-ui/core`, they no longer have the `DefaultTheme` as the correct one. They need to use module augmentation to achieve this.
=> [docs] Improve migration guide for `@material-ui/styles`

docs/src/pages/components/selects/MultipleSelect.js, docs/src/pages/components/selects/MultipleSelect.tsx, docs/src/pages/components/selects/MultipleSelectCheckmarks.js, docs/src/pages/components/selects/MultipleSelectCheckmarks.tsx, docs/src/pages/components/selects/MultipleSelectChip.js, docs/src/pages/components/selects/MultipleSelectChip.tsx, docs/src/pages/components/selects/MultipleSelectPlaceholder.js, docs/src/pages/components/selects/MultipleSelectPlaceholder.tsx
When selecting different values for multiple select the width of select changed. This PR solves it by setting the width to `300px` for multiple selects in demos. 
Closes: #19245
Preview: https://deploy-preview-26539--material-ui.netlify.app/components/selects/#multiple-select
=> [docs] Multiple select demos moving when selecting values

packages/material-ui/src/Rating/Rating.js
=> [Rating] onChangeActive shouldn't be fired on blur/focus

packages/material-ui/src/Popover/Popover.js, packages/material-ui/src/Popover/Popover.test.js
Fixes #26538
Fixed by making use of `useForkRef` utility as described in the issue comments.
=> [Popover] Fix PaperProps.ref breaking positioning

packages/material-ui/src/Checkbox/Checkbox.js, packages/material-ui/src/Radio/Radio.js
Fix regression from #26460, see the latest commit on HEAD: https://validator.w3.org/nu/?doc=https%3A%2F%2F60bcae09a9d7c90007682486--material-ui.netlify.app%2Fcomponents%2Fcheckboxes%2F to reproduce the error.
This is the error from `Checkbox`. 
@oliviertassinari @mnajdova in case I miss anything else.
=> [Radio][Checkbox] Don't forward `color` to DOM elements

packages/material-ui/src/Popper/Popper.test.js, packages/material-ui/src/TextareaAutosize/TextareaAutosize.test.js, test/utils/createClientRender.tsx, test/utils/mochaHooks.test.js
This allows us to run the test suite with different defauls for StrictMode.
Might be that we have to run some tests without StrictMode for some time until we're compatible with concurrent React.
=> [test] Make tests oblivious to StrictMode

.circleci/config.yml, test/bundling/README.md
`useBuildFromSource` was always overridden by `yarn install`. We need to install first before we portal the build from source.
bundling pipeline should fail without https://github.com/mui-org/material-ui/pull/26656#issuecomment-857082885: https://app.circleci.com/pipelines/github/mui-org/material-ui/43159/workflows/d5eccc95-2c13-4974-b370-ad3bfdfa52b3
Good news: It's only `next`. All other meta frameworks are unaffected.
=> [test] Bundling fixtures should not override source build with published build

.circleci/config.yml, packages/material-ui-unstyled/package.json, packages/material-ui-unstyled/scripts/testModuleAugmentation.js, packages/material-ui-unstyled/src/SliderUnstyled/SliderUnstyled.d.ts, packages/material-ui-unstyled/test/typescript/moduleAugmentation/sliderStyleProps.spec.tsx, packages/material-ui-unstyled/test/typescript/moduleAugmentation/sliderStyleProps.tsconfig.json
After doing some stress test for creating styled slider with TS I faced some issues that are fixes in this PR:
- add overrides point for the `styleProps`
- made `as` prop option on the `componentsProps.root`
=> [SliderUnstyled] Improve TS definition

packages/material-ui/src/index.d.ts, packages/material-ui/src/index.js
close #26660 
Add ListItemButton as export in packages/material-ui/src/index.js and packages/material-ui/src/index.d.ts files
=> [List] Add ListItemButton export to index

packages/material-ui-system/src/createTheme/createTheme.js
Looks like a spread operator is missing.
=> [system] Fix support of custom shape in createTheme

docs/pages/api-docs/button.json, docs/pages/api-docs/loading-button.json, docs/src/pages/guides/migration-v4/migration-v4.md, docs/src/pages/premium-themes/paperbase/Paperbase.js, docs/src/pages/premium-themes/paperbase/Paperbase.tsx, docs/translations/api-docs/button/button.json, docs/translations/api-docs/loading-button/loading-button.json, packages/material-ui-lab/src/LoadingButton/LoadingButton.d.ts, packages/material-ui-lab/src/LoadingButton/LoadingButton.js, packages/material-ui-lab/src/LoadingButton/loadingButtonClasses.ts, packages/material-ui/src/Button/Button.js, packages/material-ui/src/Button/Button.test.js, packages/material-ui/src/Button/buttonClasses.ts
**Preview**
https://deploy-preview-26666--material-ui.netlify.app/components/buttons/#main-content
**Changes Summary**
- remove `label` classes and element from `Button` and `LoadingButton`
- fix `LoadingButton` position: center styling because it rely on label before.
**History**
- ✅ Edge
=> [Button] Remove label span

packages/material-ui/src/useMediaQuery/useMediaQuery.test.js, packages/material-ui/src/useScrollTrigger/useScrollTrigger.test.js, test/utils/components.js
Uses `React.Profiler` instead of `useEffect` to count commits (implementation in https://github.com/eps1lon/material-ui/blob/af74ef1e9fcbbc40d23b0fd6f05fb05fac42689e/test/utils/components.js#L45-L63). `useEffect` will have slightly different semantics in React 18. See https://github.com/reactwg/react-18/discussions/18 for more context.
/cc @oliviertassinari and @dtassone. I think one of you asked me a while back how to test render count.
=> [test] Count profiler renders not passive effects

.circleci/config.yml
Adds `test_e2e` to our `react-next` workflow
=> [test] Run e2e test with React 18 on a schedule

docs/src/pages/premium-themes/onepirate/ForgotPassword.js, docs/src/pages/premium-themes/onepirate/ForgotPassword.tsx, docs/src/pages/premium-themes/onepirate/SignIn.js, docs/src/pages/premium-themes/onepirate/SignIn.tsx, docs/src/pages/premium-themes/onepirate/SignUp.js, docs/src/pages/premium-themes/onepirate/SignUp.tsx, docs/src/pages/premium-themes/onepirate/modules/components/AppBar.js, docs/src/pages/premium-themes/onepirate/modules/components/AppBar.tsx, docs/src/pages/premium-themes/onepirate/modules/components/Button.js, docs/src/pages/premium-themes/onepirate/modules/components/Button.tsx, docs/src/pages/premium-themes/onepirate/modules/form/FormFeedback.js, docs/src/pages/premium-themes/onepirate/modules/form/FormFeedback.tsx, docs/src/pages/premium-themes/onepirate/modules/views/AppFooter.js, docs/src/pages/premium-themes/onepirate/modules/views/AppFooter.tsx, docs/src/pages/premium-themes/onepirate/modules/views/ProductCTA.js, docs/src/pages/premium-themes/onepirate/modules/views/ProductCTA.tsx, docs/src/pages/premium-themes/onepirate/modules/views/ProductHowItWorks.js, docs/src/pages/premium-themes/onepirate/modules/views/ProductHowItWorks.tsx, docs/src/pages/premium-themes/onepirate/modules/views/ProductSmokingHero.js, docs/src/pages/premium-themes/onepirate/modules/views/ProductSmokingHero.tsx, docs/src/pages/premium-themes/onepirate/modules/views/ProductValues.js, docs/src/pages/premium-themes/onepirate/modules/views/ProductValues.tsx
This is a first part of the migration
One of #16947 
https://deploy-preview-26671--material-ui.netlify.app/premium-themes/onepirate/
=> [docs] Migrate onepirate premium template to emotion part1

scripts/sizeSnapshot/webpack.config.js
A follow-up on https://github.com/mui-org/material-ui/pull/26668#issuecomment-858048319, as we plan to add more modules to the system package. It should help monitor the size of its two main modules, simplifying the problem by removing tree-shaking from the equation.
=> [core] Monitore size of key system modules

docs/src/pages/components/text-fields/FullWidthTextField.js, docs/src/pages/components/text-fields/FullWidthTextField.tsx, docs/src/pages/components/text-fields/LayoutTextFields.js, docs/src/pages/components/text-fields/LayoutTextFields.tsx, docs/src/pages/components/text-fields/text-fields.md
Fix #26703
Preview https://deploy-preview-26710--material-ui.netlify.app/components/text-fields/#margin
=> [docs] Fix TextField demo layout

docs/src/pages/components/lists/BasicList.js, docs/src/pages/components/lists/BasicList.tsx, docs/src/pages/components/lists/SimpleList.js, docs/src/pages/components/lists/SimpleList.tsx, docs/src/pages/components/lists/lists.md
small update from https://github.com/mui-org/material-ui/pull/26446#issuecomment-860066988
Preview: https://deploy-preview-26742--material-ui.netlify.app/components/lists/
=> [List] fix demo to have correct semantic

docs/src/pages/customization/palette/Palette.js, docs/src/pages/customization/palette/Palette.tsx, packages/material-ui-lab/src/LoadingButton/LoadingButton.js, packages/material-ui-lab/src/TreeView/TreeView.js, packages/material-ui-system/src/createStyled.js, packages/material-ui-system/src/index.d.ts, packages/material-ui-system/src/index.js, packages/material-ui-system/src/useThemeProps/index.d.ts, packages/material-ui-system/src/useThemeProps/index.js, packages/material-ui-system/src/useThemeProps/useThemeProps.d.ts, packages/material-ui-system/src/useThemeProps/useThemeProps.js, packages/material-ui-system/src/useThemeProps/useThemeProps.spec.ts, packages/material-ui-unstyled/src/SliderUnstyled/SliderUnstyled.js, packages/material-ui/src/Badge/Badge.js, packages/material-ui/src/InputBase/InputBase.js, packages/material-ui/src/Menu/Menu.js, packages/material-ui/src/Slider/Slider.js, packages/material-ui/src/SwipeableDrawer/SwipeableDrawer.js, packages/material-ui/src/TabScrollButton/TabScrollButton.js, packages/material-ui/src/Tooltip/Tooltip.js, packages/material-ui/src/Typography/Typography.js, packages/material-ui/src/styles/useThemeProps.d.ts, packages/material-ui/src/styles/useThemeProps.spec.ts, packages/material-ui/src/useMediaQuery/useMediaQuery.js
The `isRtl` and `theme` props are no longer added by the `useThemeProps` hook. You can use the `useTheme` hook for this.
```diff
-import { unstable_useThemeProps as useThemeProps } from '@material-ui/core/styles';
+import { unstable_useThemeProps as useThemeProps, useTheme } from '@material-ui/core/styles';
const Component = (inProps) => {
-  const { isRtl, theme, ...props } = useThemeProps({ props: inProps, name: 'MuiComponent' });
+  const props = useThemeProps({ props: inProps, name: 'MuiComponent' });
+  const theme = useTheme();
+  const isRtl = theme.direction === 'rtl';
//.. rest of the code
}
```
=> [system] Remove `theme` & `isRtl` from `useThemeProps`

docs/src/pages/components/css-baseline/css-baseline-pt.md
Just a small typo fix here: https://material-ui.com/pt/components/css-baseline/. It says `inciar`, but the correct spelling is `iniciar`. That's all! Great work with Material UI, guys!
=> [docs] Fix small PT typo fix: inciar -> iniciar

docs/src/modules/components/AppFrame.js, docs/src/modules/components/ThemeContext.js
close #22112
I still want to keep `#222` as background because I think this
is better than
So I move the color to frame instead. I don't think this will confuse the people because the body still contain default background color. @oliviertassinari what do you think?
=> [docs] Move custom theme to frame

packages/material-ui-utils/src/useId.ts
We're not sending these IDs over the wire anyway so all the bytes we can safe are the ones used for writing out the multiplier (currently 3 bytes).
We go from 1:25 Million to 1:25 Quintillion. I'm buying all the lottery tickets there are if I hit that chance before `useOpaqueIdentifier` is released. Edit: It's not that unlikely for most cases considering the [birthday problem](https://en.wikipedia.org/wiki/Birthday_problem).
Reduces likelyhood of test failures such as https://app.circleci.com/pipelines/github/mui-org/material-ui/43396/workflows/9085d613-22fa-4e90-b3a6-6e5fcd4eafbe/jobs/260663
=> [useId] Reduce likelyhood of collisions

docs/pages/api-docs/icon-button.json, docs/src/modules/components/AppFrame.js, docs/src/modules/components/DemoToolbar.js, docs/src/modules/components/Notifications.js, docs/src/pages/components/app-bar/BottomAppBar.js, docs/src/pages/components/app-bar/BottomAppBar.tsx, docs/src/pages/components/app-bar/ButtonAppBar.js, docs/src/pages/components/app-bar/ButtonAppBar.tsx, docs/src/pages/components/app-bar/MenuAppBar.js, docs/src/pages/components/app-bar/MenuAppBar.tsx, docs/src/pages/components/app-bar/PrimarySearchAppBar.js, docs/src/pages/components/app-bar/PrimarySearchAppBar.tsx, docs/src/pages/components/app-bar/ProminentAppBar.js, docs/src/pages/components/app-bar/ProminentAppBar.tsx, docs/src/pages/components/app-bar/SearchAppBar.js, docs/src/pages/components/app-bar/SearchAppBar.tsx, docs/src/pages/components/buttons/ButtonSizes.js, docs/src/pages/components/buttons/ButtonSizes.tsx, docs/src/pages/components/buttons/IconButtonSizes.js, docs/src/pages/components/buttons/IconButtonSizes.tsx, docs/src/pages/components/buttons/buttons.md, docs/src/pages/components/lists/CustomizedList.js, docs/src/pages/components/lists/CustomizedList.tsx, docs/src/pages/guides/migration-v4/migration-v4.md, docs/translations/api-docs/icon-button/icon-button.json, packages/material-ui/src/IconButton/IconButton.d.ts, packages/material-ui/src/IconButton/IconButton.js, packages/material-ui/src/IconButton/IconButton.test.js, packages/material-ui/src/IconButton/iconButtonClasses.ts
- The default size's padding is reduced to `8px` which makes the default IconButton size of `40px`. To get the old default size (`48px`), use `size="large"`. The change was done to better match Google's products when Material Design stopped documenting the icon button pattern.
```diff
- <IconButton>
+ <IconButton size="large">
```
---
close #24045
🔗 https://deploy-preview-26748--material-ui.netlify.app/
- add size `large`
- update padding on `small` and `medium` size
- update `ButtonSizes` demo to include `<IconButton size="large">`
- add to `migration-v4.md` about breaking change
One thing I notice, should `label` be removed from `IconButton` same as #26666 
|                       | inherit | small[20px] | medium[24px] (default) | large[35px] | …
=> [IconButton] Add size `large` and update styles

docs/src/modules/components/Notifications.js
Reverting the color of the notification to be red. It has bigger contrast, and it is usually the color used for notifications.
**Previously**
**Now**
=> [docs] Improve notification color

docs/pages/api-docs/icon-button.json, docs/src/pages/guides/migration-v4/migration-v4.md, docs/translations/api-docs/icon-button/icon-button.json, packages/material-ui/src/IconButton/IconButton.js, packages/material-ui/src/IconButton/IconButton.test.js, packages/material-ui/src/IconButton/iconButtonClasses.ts
`span` element that wraps children has been removed. `label` classKey is also removed. More details about [this change](https://github.com/mui-org/material-ui/pull/26666).
```diff
<button class="MuiIconButton-root">
- <span class="MuiIconButton-label">
<svg />
- </span>
</button>
```
---
follow up of #26666
**preview** 👉 https://deploy-preview-26801--material-ui.netlify.app/components/buttons/#icon-button
=> [IconButton] Remove label span

packages/material-ui/src/ButtonBase/Ripple.js
Gets rid of all layout effects in `ButtonBase`. That way passive effects in a parent aren't flushed anymore just because the ButtonBase used a layout effect.
This was the main offender:
```js
// Ripple is used for user feedback (e.g. click or press) so we want to apply styles with the highest priority
useEnhancedEffect(() => {
if (!inProp) setLeaving(true)
}, [inProp]);  
```
Preview: https://deploy-preview-26762--material-ui.netlify.app/components/buttons/
=> [ButtonBase] Derive state on render instead of in layout effects

docs/src/modules/components/ApiPage.js, docs/translations/translations.json
Closes https://github.com/mui-org/material-ui/issues/26752
1. Move spread hint to the top of the table to make it harder to miss
1. Explain it more in terms what the dev wants
They're probably not interested what happens with excess props but rather what props are available.
Preview: https://deploy-preview-26778--material-ui.netlify.app/api/text-field/
=> [docs] Explain "inherited props" better in the props table

framer/package.json
Running `yarn framer:build` under PowerShell 7 on Windows throws an error:
`[error] No files matching the pattern were found: "'./**/*.{js,tsx}'".`
This is caused by apostrophes around the file pattern in `prettier` task.
=> [core] Fix running Framer's prettier under pwsh

babel.config.js, docs/babel.config.js
We've been a bit hesitant to adopt nullish coalescing (`prop ?? defaultValue`) and optional chaining (`Props?.onChange`) due to the [heavy transpilation cost](https://babeljs.io/repl#?browsers=chrome%2040&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=A4Jw9sAED82QJgUwGYEMCuAbALgNVZuogNwBQACuMAM7QB0YAdgMIAWqjA5iUA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.14.6&externalPlugins=%40babel%2Fplugin-transform-react-constant-elements%407.13.10).
However, we can make some assumptions that allow [lighter transpilation](https://babeljs.io/repl#?browsers=chrome%2040&build=&builtIns=false&corejs=3.6&spec=false&loose=true&code_lz=A4 …
=> [core] Assume no document.all at runtime

packages/material-ui/src/Drawer/Drawer.d.ts
Previously `<Drawer onEntered={() => {}} />` passed type-checking even though `onEntered` had no effect on runtime. Only `<Drawer SlideProps={{ onEntered: () => {} }} />` or `<Drawer BackdropProps={{ onEntered: () => {} }} />` has an effect at runtime.
=> [Drawer] Remove incorrect transition handler props

packages/material-ui/src/Rating/Rating.js, packages/material-ui/src/Rating/Rating.test.js, test/regressions/fixtures/Rating/PreciseFocusVisibleRating.js, test/regressions/index.test.js
Incomplete. Please review by commit.
Previous usage of `useId` was incompatible with the upcoming `React.useOpaqueIdentifier`. We can refactor the `item()` factory to a `<Item />` component which allows us to to use `React.useOpaqueIdentifier` for each item.
This may break tests if you relied on stable ids for the individual radio inputs. However, you can use `[value]` attribute selectors instead which also means you no longer have to provide an explicit `name` in your tests:
```diff
-container.querySelector('input[name="rating-test-2"]')
+container.querySelector('input[value="2"]')
```
(This example queries for the input for the rating value "2")
Given that your container only has a single `input` of course. Otherwise you probably should provide an explicit name.
Preview: …
=> [Rating] Make input ids less predictable

packages/material-ui/src/Drawer/Drawer.test.js
=> [test] Convert Drawer tests to testing-library

docs/src/pages/components/buttons/LoadingButtonsTransition.js, docs/src/pages/components/buttons/LoadingButtonsTransition.tsx, docs/src/pages/components/buttons/buttons.md, packages/material-ui-lab/src/LoadingButton/LoadingButton.js
Fix #26833
I have also added a new disable switch to the docs to test it. Should it be removed?
=> [Button] Fix loading text invisible when disabled

docs/src/pages/guides/routing/ButtonDemo.js, docs/src/pages/guides/routing/ButtonDemo.tsx, docs/src/pages/guides/routing/ButtonRouter.js, docs/src/pages/guides/routing/ButtonRouter.tsx, docs/src/pages/guides/routing/LinkDemo.js, docs/src/pages/guides/routing/LinkDemo.tsx, docs/src/pages/guides/routing/ListRouter.js, docs/src/pages/guides/routing/ListRouter.tsx, docs/src/pages/guides/routing/routing.md, packages/material-ui/src/ButtonBase/ButtonBase.js, packages/material-ui/src/ButtonBase/ButtonBase.test.js
`<ButtonBase component={CustomComponent} to="/some/value" />` will no longer pass `role="button"` to `CustomComponent`.
Fixes #26453 by improving the documentation and the component's logic:
- The prop name `to` is frequently used by routing libraries to provide the location to navigate to. Developers find it in react-router and reach-router, by the same authors. We now handle the existent of the prop as a heuristic to remove the role="button" attribute provided on the `component` prop. We assume that the final host will be a `<a>` element. This fixes the first example of this demo: https://next.material-ui.com/guides/routing/#button
- The second example of https://next.material-ui.com/guides/routing/#button requires extra care as the ButtonBase receives no information about the final …
=> [ButtonBase] Consider as a link with a custom component and `to` prop

docs/src/pages/components/date-picker/HelperText.js, docs/src/pages/components/date-picker/HelperText.tsx, docs/src/pages/components/date-picker/date-picker.md, packages/material-ui-lab/src/DesktopDatePicker/DesktopDatePickerKeyboard.test.tsx, packages/material-ui-lab/src/internal/pickers/hooks/useMaskedInput.tsx
I removed the default value to the helperText, and put an example in docs, to show how to use it. 
Closes #23533 
Preview: https://deploy-preview-26866--material-ui.netlify.app/components/date-picker/#helper-text
=> [DatePicker] Remove helper text default value

docs/pages/api-docs/dialog.json, packages/material-ui/src/Dialog/Dialog.js, packages/material-ui/src/Modal/Modal.d.ts, packages/material-ui/src/Modal/Modal.spec.tsx
Previously `ModalProps` pointed to the unstyled modal props. So e.g. `let backdropProps: ModalProps['BackdropProps'] = {  onEntered: () ==> console.log('entered') }` failed type checking even though it was valid when directly passed to `<Modal />`.
=> [Modal] Type BackdropProps according to styled version

docs/src/pages/components/autocomplete/FreeSoloCreateOptionDialog.js, docs/src/pages/components/autocomplete/FreeSoloCreateOptionDialog.tsx, docs/src/pages/components/dialogs/AlertDialogSlide.js, docs/src/pages/components/dialogs/AlertDialogSlide.tsx, docs/src/pages/components/dialogs/ConfirmationDialog.js, docs/src/pages/components/dialogs/ConfirmationDialog.tsx, docs/src/pages/components/dialogs/FormDialog.js, docs/src/pages/components/dialogs/FormDialog.tsx, docs/src/pages/components/dialogs/MaxWidthDialog.js, docs/src/pages/components/dialogs/MaxWidthDialog.tsx, docs/src/pages/components/dialogs/SimpleDialog.js, docs/src/pages/components/dialogs/SimpleDialog.tsx, docs/src/pages/components/material-icons/SearchIcons.js, packages/material-ui/src/Dialog/Dialog.js, packages/material-ui/src/Dialog/DialogContext.ts, packages/material-ui/src/DialogTitle/DialogTitle.js, packages/material-ui/test/integration/DialogIntegration.test.js
Removes the need to manually wire up Dialog and DialogTitle
Instead of 
```js
<Dialog aria-labelledby={id}>
<DialogTitle id={id} />
</Dialog>
```
you can write
```js
<Dialog>
<DialogTitle />
</Dialog>
```
instead which automatically labels the `role="dialog"` with the contents of `DialogTitle`.
=> [Dialog] Automatically label by its DialogTitle

packages/material-ui/src/Dialog/Dialog.d.ts, packages/material-ui/src/Menu/Menu.d.ts, packages/material-ui/src/Popover/Popover.d.ts, packages/material-ui/src/Snackbar/Snackbar.d.ts, packages/material-ui/src/SpeedDial/SpeedDial.d.ts
Applying the same fix as https://github.com/mui-org/material-ui/pull/26835 to all incorrect usages of `TransitionHandlerProps`.
=> [typescript] Disallow spreading TransitionHandlerProps

packages/material-ui/src/Select/Select.test.js, packages/material-ui/src/SpeedDial/SpeedDial.test.js, packages/material-ui/test/integration/Select.test.js
Part of https://github.com/mui-org/material-ui/issues/13394
=> [test] Make remaining testing-library tests StrictMode compatible

packages/material-ui/src/Backdrop/Backdrop.test.js, packages/material-ui/src/Modal/Modal.test.js
=> [test] Convert Modal tests to testing-library

packages/material-ui-codemod/README.md
The fix: some of the codemod paths are wrong, e.g  `button-color-prop` references `box-sx-prop`.
=> [codemod] Correct codemod path

packages/material-ui-lab/package.json
material-ui-lab did not list @material-ui/unstyled as a dependency.
This causes trouble with yarn 2, build fails with:
`material-ui/lab tried to access @material-ui/unstyled, but it isn't declared in its dependencies, this makes the require call ambiguous and unsound`
One example: https://github.com/mui-org/material-ui/blob/dd02ee9ff073afdd31b57d6ea6faca412ac338c3/packages/material-ui-lab/src/CalendarPicker/CalendarPicker.tsx#L5-L9
- [ X] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui-org/material-ui/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).
=> [lab] Fix missing dependency on unstyled

packages/material-ui/src/SwipeableDrawer/SwipeableDrawer.test.js
Part of https://github.com/mui-org/material-ui/issues/13394
=> [test] Convert SwipeableDrawer tests to testing-library

packages/material-ui-lab/src/CalendarPicker/CalendarPicker.test.tsx, packages/material-ui-lab/src/DateRangePickerDay/DateRangePickerDay.test.tsx, packages/material-ui-lab/src/MonthPicker/MonthPicker.test.tsx, packages/material-ui-lab/src/YearPicker/YearPicker.test.tsx
`createPickerMount` is already an abstraction around
```js
const localizedMount = (node: React.ReactNode) => {
return mount(<LocalizationProvider dateAdapter={AdapterDateFns}>{node}</LocalizationProvider>);
};
```
=> [test] Use createPickerMount where appropriate

packages/material-ui-system/src/Box/Box.d.ts, packages/material-ui-system/src/Box/Box.spec.tsx, packages/material-ui-system/src/styleFunctionSx/AliasesCSSProperties.d.ts, packages/material-ui-system/src/styleFunctionSx/styleFunctionSx.d.ts, packages/material-ui/src/Box/Box.d.ts, packages/material-ui/src/Grid/Grid.d.ts, packages/material-ui/src/Stack/Stack.d.ts, packages/material-ui/src/Typography/Typography.d.ts
Fixes TypeScript issue spotted in #25771
=> [Box] Fix TypeScript error on maxWidth prop

packages/material-ui/src/FilledInput/FilledInput.js, packages/material-ui/src/InputBase/InputBase.js
**reproduce** https://codesandbox.io/s/basictextfields-material-demo-forked-hmhf6?file=/demo.tsx
=> [TextField] Prevent `hiddenLabel` from spreading to DOM

docs/pages/api-docs/radio-group.json, packages/material-ui/src/RadioGroup/RadioGroup.d.ts, packages/material-ui/src/RadioGroup/RadioGroup.js
Complementary to #26772, it fixes a simple inconsistency I have noticed looking at #26772. We want to have the same type for RadioGroup.defaultValue, RadioGroup.value, and Radio.value.
=> [Radio] Fix `defaultValue` to match the other value types 

packages/material-ui-codemod/README.md
This is a follow-up on #26932. I had already noticed the issues, but seeing the PR made me trigger a time allocation slot. This is fixing the frustrations I had when trying to leverage the package for [material-ui-store](https://github.com/mui-org/material-ui-store).
The change:
1. The formatting of the page is off
3. The `/lib` folder do no longer exists. https://unpkg.com/browse/@material-ui/codemod@next/
4. Give up on npx. It's both slow, It reinstall each time, adding +8s of run. It's also **not working**: https://github.com/facebook/jscodeshift/issues/441. In my case:
5. Crosslink between codemod and migration guide
6. Better sort asc, group related codemodes
=> [codemod] Improve DX when using the package

docs/src/pages/guides/migration-v4/migration-v4.md
To increase accuracy of docs, this PR removes a link that points to v4 medium post and replaces it with note that there will be an upcoming post on Medium covering the _why_ of upgrading.
=> [docs] Remove link that points to v4 blog post

packages/material-ui/src/Stepper/Stepper.d.ts, packages/material-ui/src/Stepper/Stepper.test.tsx
The purpose of this PR is to allow to set a null stepper connector in TS. It works in JS. Perhaps there's another way to acomplish this, please let me know..
=> [Stepper] Fix support for no connectors

docs/pages/api-docs/bottom-navigation-action.json, docs/src/pages/guides/migration-v4/migration-v4.md, docs/translations/api-docs/bottom-navigation-action/bottom-navigation-action.json, packages/material-ui/src/BottomNavigationAction/BottomNavigationAction.js, packages/material-ui/src/BottomNavigationAction/bottomNavigationActionClasses.ts
- [BottomNavigation] Remove wrapper from BottomNavigationAction (#26923) @siriwatknp 
`span` element that wraps children has been removed. `wrapper` classKey is also removed. More details about [this change](https://github.com/mui-org/material-ui/pull/26666).
```diff
<button class="MuiBottomNavigationAction-root">
- <span class="MuiBottomNavigationAction-wrapper">
{icon}
<span class="MuiBottomNavigationAction-label">
{label}
</span>
- </span>
</button>
```
---
**WHY the wrapper is removed**
- ✅ Edge
---
fix one of …
=> [BottomNavigation] Remove `wrapper` from BottomNavigationAction

docs/pages/api-docs/tab.json, docs/src/pages/guides/migration-v4/migration-v4.md, docs/translations/api-docs/tab/tab.json, packages/material-ui/src/Tab/Tab.js, packages/material-ui/src/Tab/Tab.test.js, packages/material-ui/src/Tab/tabClasses.ts
- [Tabs] Remove unnecessary wrapper from Tab (#26926) @siriwatknp 
`span` element that wraps children has been removed. `wrapper` classKey is also removed. More details about [this change](https://github.com/mui-org/material-ui/pull/26666).
```diff
<button class="MuiTab-root">
- <span class="MuiTab-wrapper">
{icon}
{label}
- </span>
</button>
```
---
**WHY the wrapper is removed**
- ✅ Edge
---
Preview: https://deploy-preview-26926--material-ui.netlify.app/components/tabs/#icon-tabs
=> [Tabs] Remove unnecessary `wrapper` from Tab

packages/material-ui-codemod/src/util/readFile.js, packages/material-ui-codemod/src/v0.15.0/import-path.test.js, packages/material-ui-codemod/src/v1.0.0/color-imports.test.js, packages/material-ui-codemod/src/v1.0.0/import-path.test.js, packages/material-ui-codemod/src/v1.0.0/svg-icon-imports.test.js, packages/material-ui-codemod/src/v4.0.0/optimal-imports.test.js, packages/material-ui-codemod/src/v4.0.0/theme-spacing-api.test.js, packages/material-ui-codemod/src/v4.0.0/top-level-imports.test.js, packages/material-ui-codemod/src/v5.0.0/autocomplete-rename-closeicon.test.js, packages/material-ui-codemod/src/v5.0.0/avatar-circle-circular.test.js, packages/material-ui-codemod/src/v5.0.0/badge-overlap-value.test.js, packages/material-ui-codemod/src/v5.0.0/box-borderradius-values.test.js, packages/material-ui-codemod/src/v5.0.0/box-rename-gap.test.js, packages/material-ui-codemod/src/v5.0.0/box-sx-prop.test.js, packages/material-ui-codemod/src/v5.0.0/button-color-prop.test.js, packages/material-ui-codemod/src/v5.0.0/chip-variant-prop.test.js, packages/material-ui-codemod/src/v5.0.0/circularprogress-variant.test.js, packages/material-ui-codemod/src/v5.0.0/collapse-rename-collapsedheight.test.js, packages/material-ui-codemod/src/v5.0.0/component-rename-prop.test.js, packages/material-ui-codemod/src/v5.0.0/fade-rename-alpha.test.js, packages/material-ui-codemod/src/v5.0.0/grid-justify-justifycontent.test.js, packages/material-ui-codemod/src/v5.0.0/moved-lab-modules.test.js, packages/material-ui-codemod/src/v5.0.0/theme-breakpoints.test.js, packages/material-ui-codemod/src/v5.0.0/theme-spacing.test.js, packages/material-ui-codemod/src/v5.0.0/use-transitionprops.test.js, packages/material-ui-codemod/src/v5.0.0/variant-prop.test.js, packages/material-ui-envinfo/envinfo.test.js, packages/material-ui-icons/builder.js, packages/material-ui-utils/macros/MuiError.macro.js
Running `yarn test` on Windows causes several tests to fail. Mostly these are codemod tests that expect LF but are receiving CRLF when codemods are executed on Windows.
In other case the builder from material-ui-icons passes a path to fast-glob without ensuring it contains forward slashes as separators (fast-glob does not support backslashes).
=> [core] Fix tests on Windows

CONTRIBUTING.md
Another pass over CONTRIBUTING in preparation of https://ghc.anitab.org/programs-and-awards/open-source-day/.
1. explain abbreviations when they're first used (either by not using an abbreviation when first used or linking to a detailed explainer)
1. Make clear that contributions aren't limited to issues we dedicate
1. Notice about CircleCI logs requiring a login
=> [docs] Misc CONTRIBUTING.md changes

docs/next.config.js, docs/packages/markdown/loader.js, docs/packages/markdown/parseMarkdown.js
The import paths are currently more complicated than they need to. Ideally the `{{"demo":"demo/path"}}` syntax would just use import paths that are valid in JS as well. Right now they neither work with regular JS import nor webpack because they all start with `pages/`.
We can fix this another time though.
=> [docs] Fix demo paths in windows

docs/src/pages/components/badges/UnstyledBadge.js, docs/src/pages/components/badges/UnstyledBadge.tsx, docs/src/pages/components/modal/ModalUnstyled.js, docs/src/pages/components/modal/ModalUnstyled.tsx, docs/src/pages/components/slider/UnstyledSlider.js, docs/src/pages/components/slider/UnstyledSlider.tsx
Preview: https://deploy-preview-26869--material-ui.netlify.app/components/slider/#unstyled
=> [docs] Update unstyled demos to not depend on `@material-ui/core`

packages/material-ui-lab/src/CalendarPicker/CalendarPicker.tsx, packages/material-ui-lab/src/CalendarPicker/PickersCalendarHeader.tsx, packages/material-ui-lab/src/ClockPicker/Clock.tsx, packages/material-ui-lab/src/ClockPicker/ClockNumber.tsx, packages/material-ui-lab/src/ClockPicker/ClockPicker.tsx, packages/material-ui-lab/src/DatePicker/DatePickerToolbar.tsx, packages/material-ui-lab/src/MonthPicker/MonthPicker.tsx, packages/material-ui-lab/src/TimePicker/TimePickerToolbar.tsx, packages/material-ui-lab/src/TimelineConnector/TimelineConnector.js, packages/material-ui-lab/src/TimelineSeparator/TimelineSeparator.js, packages/material-ui-lab/src/YearPicker/YearPicker.tsx, packages/material-ui-lab/src/internal/pickers/PickersArrowSwitcher.tsx, packages/material-ui-lab/src/internal/pickers/PickersModalDialog.tsx, packages/material-ui-lab/src/internal/pickers/PickersPopper.tsx, packages/material-ui-lab/src/internal/pickers/PickersToolbar.tsx, packages/material-ui/src/AccordionDetails/AccordionDetails.js, packages/material-ui/src/AlertTitle/AlertTitle.js, packages/material-ui/src/BottomNavigationAction/BottomNavigationAction.js, packages/material-ui/src/CardActionArea/CardActionArea.js, packages/material-ui/src/SnackbarContent/SnackbarContent.js, packages/material-ui/src/SpeedDialIcon/SpeedDialIcon.js, packages/material-ui/src/TablePagination/TablePagination.js
The root issue was fixed by @eps1lon in some PR (I can't remember where I saw the fix). So we can speed up the runtime of these components.
=> [core] Remove unused props clone

packages/material-ui/src/NativeSelect/NativeSelect.d.ts, packages/material-ui/src/NativeSelect/NativeSelectInput.d.ts, packages/material-ui/src/NativeSelect/NativeSelectInput.test.js
Based on https://github.com/mui-org/material-ui/pull/26949 ([diff](https://github.com/eps1lon/material-ui/compare/test/hide-enzyme...eps1lon:test/NativeSelectInput/testing-library))
Last tests where we can switch from enzyme. The remaining test need enzyme. Not converting the JSS tests since I consider them legacy at this point and don't want them to block React 18 efforts in case JSS has  issues with concurrent rendering.
=> [test] Convert NativeSelectInput tests to testing-library

docs/src/pages/components/tables/EnhancedTable.js, docs/src/pages/components/tables/EnhancedTable.tsx
Closes #26993
Add note to `stableSort` function about IE11 compatibility  
Add snippet using `sort()` as suggestion to replace `stableSort` call
=> [docs] Add notes to Table demo about stableSort

packages/material-ui-lab/src/CalendarPicker/CalendarPicker.test.tsx, packages/material-ui-lab/src/ClockPicker/ClockPicker.test.tsx, packages/material-ui-lab/src/DateRangePicker/DateRangePicker.test.tsx, packages/material-ui-lab/src/DateRangePickerDay/DateRangePickerDay.test.tsx, packages/material-ui-lab/src/DesktopDateRangePicker/DesktopDateRangePicker.test.tsx, packages/material-ui-lab/src/DesktopTimePicker/DesktopTimePicker.test.tsx, packages/material-ui-lab/src/MobileDateRangePicker/MobileDateRangePicker.test.tsx, packages/material-ui-lab/src/MobileTimePicker/MobileTimePicker.test.tsx, packages/material-ui-lab/src/MonthPicker/MonthPicker.test.tsx, packages/material-ui-lab/src/PickersDay/PickersDay.test.tsx, packages/material-ui-lab/src/StaticDateRangePicker/StaticDateRangePicker.test.tsx, packages/material-ui-lab/src/StaticTimePicker/StaticTimePicker.test.tsx, packages/material-ui-lab/src/TabList/TabList.test.js, packages/material-ui-lab/src/TabPanel/TabPanel.test.tsx, packages/material-ui-lab/src/TimePicker/TimePicker.test.tsx, packages/material-ui-lab/src/YearPicker/YearPicker.test.tsx, packages/material-ui-lab/src/internal/pickers/test-utils.tsx, packages/material-ui/src/Popover/Popover.test.js, packages/material-ui/src/StepContent/StepContent.test.js, packages/material-ui/src/TableBody/TableBody.test.js, packages/material-ui/src/TableCell/TableCell.test.js, packages/material-ui/src/TableFooter/TableFooter.test.js, packages/material-ui/src/TableHead/TableHead.test.js, packages/material-ui/src/TablePagination/TablePagination.test.js, packages/material-ui/src/TableRow/TableRow.test.js, test/utils/describeConformance.js, test/utils/describeConformanceV5.js
This way we know that if we actually create a mount implementation in a test suite, at least one test is using enzyme.
Follow-up to https://github.com/mui-org/material-ui/pull/26949
=> [test] Only allow wrapping enzyme mount not creating

packages/material-ui-lab/src/CalendarPicker/CalendarPicker.test.tsx, packages/material-ui-lab/src/DesktopDatePicker/DesktopDatePicker.test.tsx, packages/material-ui-lab/src/DesktopDateRangePicker/DesktopDateRangePicker.test.tsx, packages/material-ui-lab/src/MobileDatePicker/MobileDatePicker.test.tsx, packages/material-ui-lab/src/MobileDateTimePicker/MobileDateTimePicker.test.tsx, packages/material-ui-lab/src/StaticDatePicker/StaticDatePicker.test.tsx, packages/material-ui-styles/src/makeStyles/makeStyles.test.js
Part of https://github.com/mui-org/material-ui/issues/13394
Every test not using StrictMode now is annotated with `StrictModeViolation` and the reason.
Follow-up:
=> [test] Update tests with latest state of StrictMode compatibility

packages/material-ui/src/styles/components.d.ts
=> [theme] Add missing MuiRating types to components.d.ts

.eslintrc.js, docs/packages/markdown/index.js, docs/packages/markdown/package.json, docs/pages/index.tsx, docs/src/modules/utils/mapApiPageTranslations.js, docs/src/pages/landing/Sponsors.js
On 3G:
1s faster LCP
.5s faster visually complete
Preview: https://60ded7131d29f000078293ea--material-ui.netlify.app/
webpagetest comparison: https://www.webpagetest.org/video/compare.php?tests=210702_BiDcP4_2cd4ae910ce48056696f0c9380ed0731%2C210702_AiDc1H_9c8e1753971838289020ba4efb8e776d&thumbSize=200&ival=500&end=visual
`yarn docs:build` changes
```diff
Page                                                           Size     First Load JS
-┌ λ /                                                          42.6 kB         328 kB
+┌ λ /                                                          23.9 kB         309 kB
```
=> [docs] Use custom markdown loader for landing page

docs/pages/api-docs/fab.json, docs/src/pages/guides/migration-v4/migration-v4.md, docs/translations/api-docs/fab/fab.json, packages/material-ui/src/Fab/Fab.js, packages/material-ui/src/Fab/Fab.test.js, packages/material-ui/src/Fab/fabClasses.ts
- [Fab] Remove no longer necessary span wrapper
- ✅ Edge
---
=> [Fab] Remove no longer necessary span wrapper

packages/material-ui-lab/src/CalendarPicker/CalendarPicker.test.tsx, packages/material-ui-lab/src/CalendarPicker/PickersCalendar.tsx, packages/material-ui-lab/src/CalendarPicker/PickersFadeTransitionGroup.tsx, packages/material-ui-lab/src/DesktopDatePicker/DesktopDatePicker.test.tsx, packages/material-ui-lab/src/DesktopDateRangePicker/DesktopDateRangePicker.test.tsx, packages/material-ui-lab/src/MobileDatePicker/MobileDatePicker.test.tsx, packages/material-ui-lab/src/MobileDateTimePicker/MobileDateTimePicker.test.tsx, packages/material-ui-lab/src/StaticDatePicker/StaticDatePicker.test.tsx
The visuals might've slightly changed for fading but the implementation is now a lot simpler. Devs expecting that a customization of Fade affects every fade-like transition are no longer surprised.
We can't apply the same pattern to the sliding transition since it has different directions for enter an d exit which our Slide doesn't support as far as I can tell.
=> [CalendarPicker] Use transition components from core instead of a custom implementation

docs/src/pages/premium-themes/.eslintrc.js, docs/src/pages/premium-themes/paperbase/Header.js, docs/src/pages/premium-themes/paperbase/Header.tsx
Use an actual link in the template instead of a dummy. Dummy components are just confusing in demos. We might as well use an image instead. And it's also confusing since one doesn't know what this link is for without a proper `href`.
=> [docs] Use actual link to paperbase

examples/cdn/index.html, examples/create-react-app-with-styled-components-typescript/src/index.tsx, examples/create-react-app-with-styled-components/src/index.js, examples/create-react-app-with-typescript/src/index.tsx, examples/create-react-app/src/index.js, examples/gatsby-theme/src/pages/index.js, examples/gatsby/src/pages/about.js, examples/gatsby/src/pages/index.js, examples/preact/src/App.js
It is safe to remove the `<StyledEngineProvider injectFirst />` from the examples, as all components are migrated to emotion and there is no dependency on `@material-ui/styles`.
=> [examples] Remove `StyledEngineProvider` as JSS is not used

.github/renovate.json
It's a CI check anyway so we might as well run it ourselfs. Safes CI and human resources.
~@oliviertassinari You need to `deduplicate` to `allowedPostUpgradeCommands` which is an admin-only configuration of Renovate (https://docs.renovatebot.com/configuration-options/#postupgradetasks)~
=> [core] Run yarn deduplicate on Renovate updates

docs/pages/api-docs/toggle-button.json, docs/src/pages/guides/migration-v4/migration-v4.md, docs/translations/api-docs/toggle-button/toggle-button.json, packages/material-ui/src/ToggleButton/ToggleButton.d.ts, packages/material-ui/src/ToggleButton/ToggleButton.js, packages/material-ui/src/ToggleButton/ToggleButton.test.js, packages/material-ui/src/ToggleButton/toggleButtonClasses.ts
---
- [ToggleButton] Remove no longer necessary span wrapper
- ✅ Edge
=> [ToggleButton] Remove unnecessary span

scripts/copy-files.js
The path for the `module` in v4.12.0 version was broken, as it was released from Windows. For example - https://unpkg.com/browse/@material-ui/core@4.12.0/Accordion/package.json 
The correct one should look like - https://unpkg.com/browse/@material-ui/core@4.11.4/Accordion/package.json
Fixes https://github.com/mui-org/material-ui/issues/27147
We should do a new release once this is merged.
=> [core] Fix generation of package.json file on Windows

docs/src/modules/components/AppSearch.js, docs/src/pages/customization/default-theme/DefaultTheme.js
Noticed that we're using the `url` polyfill which isn't even a declared dependency. I suspect that the package is responsible for https://github.com/mui-org/material-ui/issues/26943.
Closes https://github.com/mui-org/material-ui/issues/26943
Preview: https://deploy-preview-27151--material-ui.netlify.app/
=> [docs] Remove usage of `url` package

docs/pages/api-docs/autocomplete.json, docs/pages/api-docs/button-group.json, docs/pages/api-docs/fab.json, docs/pages/api-docs/pagination-item.json, docs/pages/api-docs/pagination.json, docs/pages/api-docs/rating.json, docs/pages/api-docs/slider.json, docs/pages/api-docs/table-cell.json, docs/pages/api-docs/toggle-button-group.json, docs/pages/api-docs/toggle-button.json, framer/Material-UI.framerfx/code/Slider.tsx, packages/material-ui/src/Autocomplete/Autocomplete.js, packages/material-ui/src/ButtonGroup/ButtonGroup.js, packages/material-ui/src/Fab/Fab.js, packages/material-ui/src/Pagination/Pagination.js, packages/material-ui/src/PaginationItem/PaginationItem.js, packages/material-ui/src/Rating/Rating.js, packages/material-ui/src/Slider/Slider.js, packages/material-ui/src/TableCell/TableCell.js, packages/material-ui/src/ToggleButton/ToggleButton.js, packages/material-ui/src/ToggleButtonGroup/ToggleButtonGroup.js, scripts/generateProptypes.ts
A quick follow-up on https://github.com/mui-org/material-ui/pull/27164#discussion_r666061712. Not really important
https://deploy-preview-27186--material-ui.netlify.app/api/button/
=> [docs] Sort the size in a more logical order

docs/src/modules/components/Ad.js
Follow-up to https://github.com/mui-org/material-ui/pull/27173 and https://github.com/mui-org/material-ui/pull/27151#pullrequestreview-700403457.
The page shouldn't crash if an Ad crashes. We get no ad impressions either way and a bad user impression when it does crash. 
The only downside would be that we won't get any reports when it does crash. Therefore we send custom google-analytics events on crash. Ultimately a proper error monitoring service would do this (e.g. Sentry).
Preview: https://deploy-preview-27178--material-ui.netlify.app/components/alert/
Report (not sure if "custom reports" are user or org specific): https://analytics.google.com/analytics/web/#/my-reports/tV0Fi0LzQT6Pq3dtgC-dFQ/a106598593w159022482p160376982/
Report template: …
=> [docs] Don't crash page if an Ad crashes

docs/translations/api-docs/button-base/button-base.json, docs/translations/api-docs/button/button.json, docs/translations/api-docs/icon-button/icon-button.json, docs/translations/api-docs/tab/tab.json, docs/translations/api-docs/toggle-button/toggle-button.json, packages/material-ui/src/Button/Button.js, packages/material-ui/src/ButtonBase/ButtonBase.d.ts, packages/material-ui/src/ButtonBase/ButtonBase.js, packages/material-ui/src/IconButton/IconButton.js, packages/material-ui/src/Tab/Tab.js, packages/material-ui/src/ToggleButton/ToggleButton.js
Changes the incorrect `Mui-focusedVisible` to `Mui-focusVisible` class name in ButtonBase's (and descendants) API description.
=> [ButtonBase] Correct `disableRipple` API description

docs/src/modules/components/ComponentLinkHeader.js, docs/src/modules/components/Demo.js, docs/src/modules/components/DemoSandboxed.js, docs/src/modules/components/DemoToolbar.js, docs/src/modules/components/DiamondSponsors.js, docs/src/modules/components/MarkdownElement.js, docs/src/modules/components/Notifications.js, docs/src/pages/components/date-picker/CustomDay.js, docs/src/pages/components/date-picker/CustomDay.tsx, docs/src/pages/components/date-range-picker/CustomDateRangePickerDay.js, docs/src/pages/components/date-range-picker/CustomDateRangePickerDay.tsx, docs/src/pages/components/material-icons/SearchIcons.js, docs/src/pages/components/popper/ScrollPlayground.js, docs/src/pages/customization/palette/Intentions.js, docs/src/pages/production-error/ErrorDecoder.js
This PR migrates the rest of the documentation to emotion. The only code related to emotion left is the one on the landing page. It will anyway go away with the branding so I didn't want to spend time on it.
Preview: https://deploy-preview-27184--material-ui.netlify.app/
---
Looks like in the first iteration I left the most complicated/extensive components 😄
=> [docs] Migrate rest of the docs to emotion

test/karma.conf.js
It seems that we have added more tests, the run is now slower and more often hit the limit:
https://automate.browserstack.com/dashboard/v2/builds/950ced05fbc968c6ce8e068a01034283c3f98714
=> [test] Increase BS timeout to 6min

packages/material-ui-codemod/src/v5.0.0/modal-props.js, packages/material-ui-codemod/src/v5.0.0/theme-palette-mode.js
The latest 5.0 codemods' tests failed on Windows as they did not handle line endings properly. This PR fixes them.
=> [codemod] Fix 5.0 codemods on Windows

docs/src/modules/components/AppFrame.js
Noticed while reviewing https://github.com/mui-org/material-ui-x/pull/2108. In the Material-UI X docs this error is very annoying. 
It's caused because we only consider HTTPS links as external:
https://github.com/mui-org/material-ui/blob/dc5daa7464c5bb35fc879431afd4b9ddd785bbb9/docs/src/modules/components/Link.js#L55
=> [docs] Fix https protocol

docs/src/modules/components/AppLayoutDocs.js
Fix https://github.com/mui-org/material-ui/pull/27138#issuecomment-878951342
---
Next up, we might want to look into https://github.com/mui-org/material-ui/pull/27043#issuecomment-877776720 before the release of v5.0.0-beta.1, it's a regression, and seems to have a large impact (my assumption is that we would quickly get a bug report if we release it). The transition is now technically strict mode compatible 👌  but does no longer serves its original product purpose. I will see what I can do to improve it tomorrow. The simplest might be to remove the transition, it would already be better, but I hope that with more effort we can get the best of the two worlds, a simple, strict mode transition, with a great UX.
=> [docs] Fix layout regression

docs/src/modules/components/AppLayoutDocs.js
Reverts mui-org/material-ui#27266 which was accidentally merged. There was no reproduction provided and we don't merge "fixes" that are unconfirmed.
Broke layout on 
- Chrome Version 91.0.4472.114 (Official Build) (64-bit) Ubuntu 20.04
- Firefox Version 89.0.2 Ubuntu 20.04
- Chrome Version 91.0.4472.114 (Official Build) (64-bit) macOS Catalina
- Safari Version 14.1.1 (Official Build) (64-bit) macOS Catalina
=> Revert "[docs] Fix layout regression"

test/e2e/TestViewer.js, test/regressions/TestViewer.js
=> [test] Remove `StyledEngineProvider` usage from regressions and e2e tests

packages/material-ui-lab/src/CalendarPicker/PickersCalendar.tsx
Regressed in https://github.com/mui-org/material-ui/pull/27043
Preview: https://deploy-preview-27273--material-ui.netlify.app/components/date-picker/#landscape-orientation
Changelog entry can be ignored if we have no release between https://github.com/mui-org/material-ui/pull/27043 and now
=> [CalendarPicker] Fix slide transition regression

docs/src/pages/system/sizing/sizing.md, docs/src/pages/system/the-sx-prop/the-sx-prop.md, packages/material-ui-system/src/sizing.js, packages/material-ui-system/src/styleFunctionSx/styleFunctionSx.test.js
Adds breakpoint value support on Box `maxWidth` prop as suggested in [this comment](https://github.com/mui-org/material-ui/issues/25771#issuecomment-846477908)
Closes #25771 
Preview: https://deploy-preview-26984--material-ui.netlify.app/system/sizing/#max-width
=> [Box] Add breakpoint value support to maxWidth prop

packages/material-ui-lab/src/CalendarPicker/PickersFadeTransitionGroup.tsx
This is a follow-up on https://github.com/mui-org/material-ui/pull/27273#pullrequestreview-706260994. It fixes something that I have noticed during the review. See the behavior when JavaScript is disabled:
v5.0.0-beta.0: https://next.material-ui.com/components/date-picker/#static-mode
HEAD: https://next--material-ui.netlify.app/components/date-picker/#static-mode
The fix is to set http://reactcommunity.org/react-transition-group/transition#Transition-prop-appear. It makes me think of https://github.com/mui-org/material-ui/issues/26108#issue-874822103. We might want to change the default value in v6.
Preview: https://deploy-preview-27283--material-ui.netlify.app/components/date-picker/#static-mode
=> [pickers] Fix Fade animation behavior change

docs/public/static/error-codes.json, packages/material-ui-lab/src/internal/pickers/hooks/useUtils.ts
Also improves the stack trace. Using functions to throw error is generally problematic since the last frame will no longer point to the very lint that caused the error. It's still not ideal since it's nested inside `useUtils` but that's at least right where we try to access the utils.
=> [pickers] Minify error when LocalizationProvider is missing

docs/src/modules/components/TopLayoutBlog.js, docs/src/modules/components/TopLayoutCompany.js, docs/src/pages/components/material-icons/SearchIcons.js
- Preview: https://deploy-preview-27237--material-ui.netlify.app/components/material-icons/#material-icons
- Preview: https://deploy-preview-27237--material-ui.netlify.app/company/careers/
=> [docs] Fix various layout issues with the v5 banner

packages/material-ui/src/Autocomplete/Autocomplete.test.js, packages/material-ui/src/useAutocomplete/useAutocomplete.js
This is a fix for issue #26378
=> [Autocomplete] Popper is not closing when the Autocomplete is disabled

docs/pages/index.js, docs/src/modules/components/AppTableOfContents.js, docs/src/modules/components/MarkdownDocs.js, docs/src/modules/components/TopLayoutBlog.js, docs/src/modules/components/TopLayoutCompany.js, docs/src/modules/constants.js, docs/src/pages/components/material-icons/SearchIcons.js, docs/src/pages/landing/Pro.js
Creating `BANNER_HEIGHT` constant for easier replacing/removing the updates, once the banner is removed.
=> [docs] Add constant for the banner height

docs/pages/api-docs/text-field.md, packages/material-ui/src/TextField/TextField.d.ts, packages/material-ui/src/TextField/TextField.js
Closes https://github.com/mui-org/material-ui/issues/27291: https://codesandbox.io/s/create-react-app-forked-fcujs?file=/src/App.js
Forgot to backport https://github.com/mui-org/material-ui/pull/22831.
=> [TextField] Add support for `minRows`

.gitattributes
I was working on #15984 to monitor our progress on the issue:
When I realize that we broke the language stats. Before
```
89.82%  JavaScript
10.17%  TypeScript
0.01%   HTML
```
After
```
64.52%  JavaScript
35.44%  TypeScript
0.04%   HTML
```
The change is based on https://github.com/github/linguist/issues/5439#issuecomment-873066279.
=> [core] Fix GitHub language detection

docs/pages/api-docs/form-control-label.json, docs/translations/api-docs/form-control-label/form-control-label.json, packages/material-ui/src/FormControlLabel/FormControlLabel.d.ts, packages/material-ui/src/FormControlLabel/FormControlLabel.js, packages/material-ui/src/FormControlLabel/FormControlLabel.test.js
- [TextField] Fix name of componentsProps (#27338) @oliviertassinari
```diff
<FormControlLabel
label="Pizza"
-  componentProps={{
+  componentsProps={{
typography: {
```
---
Something I have noticed in #26810. Confusion between `componentsProps` and `componentProps` coming from #25883.
=> [TextField] Fix name of componentsProps

packages/material-ui/src/Grid/Grid.js, packages/material-ui/src/Grid/Grid.test.js
No need to set `width` for `rowSpacing` as it makes Grid container wider than its parent.
Example: https://codesandbox.io/s/blazing-night-49tx4
Preview: https://deploy-preview-27326--material-ui.netlify.app/components/grid/
=> [Grid] Remove width prop for rowSpacing

packages/material-ui/src/Tabs/Tabs.js
Use `theme.transitions.duration.standard` for scrollable Tabs animation instead of a hardcoded duration. Improves experience for people with motion sickness (prefer-reduced motion) as well as visual regression tests where one usually disables animations.
Fix #27300
=> [Tabs] Use theme transition duration for the Tab animation

docs/next.config.js
Docs currently crash in IE11 because the markdown loader creates arrow functions. The generated JS should be transpiled regardless.
=> [docs] Transpile markdown files

docs/src/pages/guides/migration-v4/migration-v4.md
Related to https://github.com/mui-org/material-ui/pull/27351
- Fix `focused` removal falsely pointing to `Accordion` (instead of `AccordionSummary`)
- Fix some migration notes not having their own heading
=> [docs] Fix ExpansionPanel migration notes

docs/src/pages/guides/migration-v4/migration-v4.md
Got duplicate keys warning which is intended. All items first "Theme" section could be placed in existing headers.
=> [docs] Fix duplicate "Theme" header

docs/src/pages/customization/unstyled-components/StylingCustomCss.js, docs/src/pages/customization/unstyled-components/StylingCustomCss.tsx, docs/src/pages/customization/unstyled-components/StylingHooks.js, docs/src/pages/customization/unstyled-components/StylingHooks.tsx, docs/src/pages/customization/unstyled-components/StylingSlots.js, docs/src/pages/customization/unstyled-components/StylingSlots.tsx, docs/src/pages/customization/unstyled-components/unstyled-components.md
A quick follow-up on #27158. The high-level changes, only details:
- Component name convention -> PascalCase.tsx
- Import convention: one level deep to get tree-shaking in dev mode. Also, mitigate that we don't have one package per component
- One sentence per markdown helps in the review and future updates.
- Remove "just" (I personally don't like this word, to put it nicely), but it was pinned by Grammarly too.
=> [docs] Improve unstyled docs

packages/material-ui-codemod/package.json
Manually released that version from https://github.com/mui-org/material-ui/tree/v5.0.0-beta.1. Version bump was forgotten due to manual edits in https://github.com/mui-org/material-ui/pull/27230.
=> [codemod] Fix published version

packages/material-ui-codemod/codemod.js
On Windows, Lerna does not create symlinks from `node_modules/.bin` but instead creates bash and cmd scripts that execute the target script. Thus `require.resolve('.bin/jscodeshift')` would point to the bash script that can't be executed by node. This PR changes the `jscodeshiftExecutable` finding logic to look in workspace root's node_modules.
Fixes #27320
=> [codemod] Fix running codemod CLI on Windows

docs/pages/api-docs/form-label.json, docs/pages/api-docs/input-label.json, packages/material-ui/src/FormLabel/FormLabel.d.ts, packages/material-ui/src/FormLabel/FormLabel.js, packages/material-ui/src/InputLabel/InputLabel.js
A continuation of: #26697. I have noticed this working on https://github.com/mui-org/material-ui-store/commit/c54f85d582c43326cb5aa45dd6262bc989f6368d#r53613823.
I have also noticed that ToggleButton wasn't handled but I'm not taking care of it.
=> [TextField] Allow custom colors in FormLabel

docs/pages/api-docs/textarea-autosize.md, packages/material-ui/src/TextareaAutosize/TextareaAutosize.d.ts, packages/material-ui/src/TextareaAutosize/TextareaAutosize.js
When using the `rows` prop on a `TextField`, you get a console error about `rows` being deprecated. It suggests using `rowsMin`, which is also deprecated. 
It should instead tell the developer to use `minRows`.
=> [TextareaAutosize] Updated deprecation warning to suggest minRows instead of rowsMin

packages/material-ui-system/src/createStyled.js, packages/material-ui-system/src/createStyled.test.js
Otherwise the created components appear as anonymous in devtools. 
The `Styled` badge should ideally appear as well. Tracking in https://github.com/facebook/react/issues/21939
Before:
After:
=> [system] Compute display name of `styled` component if `name` isn't set

packages/material-ui-utils/src/getDisplayName.test.tsx
Guarding against a potential change of implementation that seems to make things simpler but produces incorrect output.
Debateable whether we need `getDisplayName` for context components but they suffice as a guard for "don't just access `displayName`".
=> [test] Add current behavior for getDisplayName with context components

packages/material-ui-utils/src/createChainedFunction.d.ts, packages/material-ui-utils/src/createChainedFunction.ts
JSDoc types were inaccurate, TypeScript types not accurate enough.
Removed the console error message in the process. It's unhelpful the way we use `createChainedFunction` and for direct consumers we encourage proper type-checking.
=> [utils] Convert createChainedFunction to TypeScript

docs/translations/api-docs/autocomplete/autocomplete.json, packages/material-ui/src/Autocomplete/Autocomplete.d.ts, packages/material-ui/src/Autocomplete/Autocomplete.js
Made more clear how that the `loading` shows `loadingText` only when `options` are empty.
Fixes #27397
=> [Autocomplete] Explain how the loading prop works

.github/renovate.json
> Please check the docs for `rangeStrategy`. The default value is `replace` but it sounds like you're perhaps expecting `update-lockfile`.
-- https://github.com/renovatebot/renovate/discussions/10968#discussioncomment-1051343
Yes we do want `update-lockfile`:
> update-lockfile = Update the lock file when in-range updates are available, otherwise replace for updates out of range. Works for bundler, composer, npm, yarn and poetry so far
-- https://docs.renovatebot.com/configuration-options/#rangestrategy
=> [core] Receive patch and minor dependency updates

packages/material-ui/src/TablePagination/TablePagination.js, packages/material-ui/src/TablePagination/TablePaginationActions.d.ts, packages/material-ui/src/TablePagination/TablePaginationActions.js
Closes https://github.com/mui-org/material-ui/issues/27192
Verified: https://codesandbox.io/s/awesome-frost-5nxj0
=> [TablePagination] Re-introduce deprecated `onChangePage` to `ActionsComponent`

docs/src/pages/guides/migration-v4/migration-v4.md, packages/material-ui-codemod/README.md
It's a follow-up on #27292. 
- Add the missing instructions to use the codemod
- Fix the warning grammar
- Fix the git diff
- Add dots to close the sentences
- Cross-link migration guide and jss codemod
=> [docs] Polish jss-to-styled docs

docs/packages/markdown/parseMarkdown.js, docs/packages/markdown/parseMarkdown.test.js
#22836 introduced a regression on pages that have another `</p>` element in the page. For instance: 
https://github.com/mui-org/material-ui/blob/af26cc697e4342251499bb6fb243d9992789396b/docs/src/pages/components/modal/modal.md#L125
Turns into a very long description: https://next.material-ui.com/components/modal/
Which is flagged as causing SEO issues by our crawlers.
=> [docs] Non greedy description matchers

test/karma.conf.js
I have seen this type of fail come up every now and then https://app.circleci.com/pipelines/github/mui-org/material-ui/49708/workflows/6199969c-e3c9-4825-88ca-7bd23dd719ad/jobs/277789
> Firefox 78.0 (Windows 10) <DesktopDateRangePicker /> scrolls current month to the active selection on focusing appropriate field FAILED
Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
I didn't look into what's going wrong in Firefox, but the tests are x2 slower than in the other environments:
Maybe we should run with a more recent version of Firefox or find  the performance bottleneck 🤷‍♂️
=> [test] Allow tests to run for 6s before timeout

docs/pages/_app.js, docs/pages/_document.js, docs/src/createEmotionCache.ts, docs/src/modules/utils/StyledEngineProvider.js, examples/nextjs-with-styled-components-typescript/pages/_app.tsx, examples/nextjs-with-typescript/pages/_app.tsx, examples/nextjs-with-typescript/pages/_document.tsx, examples/nextjs-with-typescript/src/createEmotionCache.ts, examples/nextjs/pages/_app.js, examples/nextjs/pages/_document.js, examples/nextjs/src/createEmotionCache.js
Fixes #27045 
Fixes #26957
Preview: https://deploy-preview-27331--material-ui.netlify.app/
=> [examples] Improve integration examples with Next.js

packages/material-ui-codemod/src/v5.0.0/jss-to-styled.js
When testing the codemod on the store (https://github.com/mui-org/material-ui-store/pull/55) the PREFIX was wrongly generated on Windows:
```js
const PREFIX = 'D:\\workspace\\material-ui-store\\web\\src\\modules\\components\\FormButton';
```
This PR fixes it to be:
```js
const PREFIX = 'FormButton'
```
=> [codemod] Fix `jss-to-styled` PREFIX generation on Windows

packages/material-ui/src/NativeSelect/NativeSelectInput.js
Closes https://github.com/mui-org/material-ui/issues/27449 
Preview: https://deploy-preview-27511--material-ui.netlify.app/components/selects/#basic-select
Accidentally the styles for the filled variant were copied when the select is opened.
=> [Select] Fix regression for icon not rotating

package.json
The previous include pattern was inconsistent with file extensions. I would've expected e.g. `/unstyled`  to not be monitored (since it's not part of the include pattern) but it was already included in codecov though I don't understand why.
`/codemod` is now monitored. We leverage codemods more and more so we also need to be able to monitor test coverage.
coverage changes: https://codecov.io/gh/mui-org/material-ui/compare/b9a55392af4cd19086898dbfcd9d55a4c9396983...3b71b3045cc15c117f282ec839b4e8506349f26e
=> [test] Update coverage to include all @material-ui packages

docs/src/modules/components/DemoToolbar.js, docs/src/modules/utils/getDemoConfig.js, docs/translations/translations.json
Closes https://github.com/mui-org/material-ui/issues/27255 as per discussion with @oliviertassinari.
Additional notes:
- React+TypeScript support that's mentioned in the original issue has been fixed on the StackBlitz side
- the `"jsx": "preserve"` in the generated `tsconfig.json` for the demos is handled by CodeSandbox but not by StackBlitz, while `"jsx": "react"` is handled by both hence the updated value
Preview: https://deploy-preview-27391--material-ui.netlify.app/components/alert/#basic-alerts
=> [docs] Add StackBlitz edit demo integration

docs/pages/api-docs/collapse.md, docs/pages/api-docs/grid.md, docs/pages/api-docs/image-list-item-bar.md, docs/pages/api-docs/image-list.md, docs/pages/api-docs/textarea-autosize.md, docs/src/modules/utils/generateMarkdown.js
This PR fixes the generation for the deprecated prop types using `deprecatedPropType`. Previosly the generation handled only the primitive proptypes, like PropTypes.number, PropTypes.string etc. When there was `oneOfType`, or `oneOf` usages it broke. 
**Collapse**
https://material-ui.com/api/collapse/#collapse-api
**Grid**
https://material-ui.com/api/grid/
-----
**Collapse**
https://deploy-preview-27576--material-ui.netlify.app/api/collapse/#collapse-api
**Grid**
https://deploy-preview-27576--material-ui.netlify.app/api/grid/
=> [docs] Fix api generation for `deprecatedPropType`

.github/renovate.json
As soon as one renovate PR is merged, all the other ones are rerun. It's not scaling with our CI. Try to force the value.
I'm testing the fix in https://github.com/mui-org/material-ui-x/pull/2271. No, it doesn't work.
=> [core] rebaseWhen=auto does not seem to work

docs/src/pages/guides/migration-v4/migration-v4.md
* destructure `theme` in `styled` when migration `makeStyles`
to emotion
=> [docs] fix syntax error in v5 migration `styled` api example

docs/src/pages/components/badges/badges.md, docs/src/pages/components/breadcrumbs/breadcrumbs.md, docs/src/pages/components/buttons/buttons.md, docs/src/pages/components/checkboxes/checkboxes.md, docs/src/pages/components/dialogs/dialogs.md, docs/src/pages/components/lists/lists.md, docs/src/pages/components/menus/menus.md, docs/src/pages/components/progress/progress.md, docs/src/pages/components/radio-buttons/radio-buttons.md, docs/src/pages/components/rating/rating.md, docs/src/pages/components/selects/selects.md, docs/src/pages/components/slider/slider.md, docs/src/pages/components/snackbars/snackbars.md, docs/src/pages/components/switches/switches.md, docs/src/pages/components/tables/tables.md, docs/src/pages/components/tabs/tabs.md, docs/src/pages/components/text-fields/text-fields.md, docs/src/pages/components/timeline/timeline.md, docs/src/pages/components/toggle-button/toggle-button.md, docs/src/pages/components/tooltips/tooltips.md, docs/src/pages/components/tree-view/tree-view.md
A follow-up on #27411, it seems that we have an opportunity to normalize the header, to make it easier for developers to find this section when they land on the page of a new component.
=> [docs] Use the same h2 for the customization demos

docs/src/pages/customization/unstyled-components/unstyled-components.md
This was reported by our SEO crawlers. It's a follow-up on #27158. The links were not close to correct :). Can be reproduced on https://next.material-ui.com/customization/unstyled-components/#overriding-the-unstyled-components-slots.
=> [docs] Fix 404 links

packages/material-ui-codemod/src/v5.0.0/jss-to-styled.js, packages/material-ui-codemod/src/v5.0.0/jss-to-styled.test.js, packages/material-ui-codemod/src/v5.0.0/jss-to-styled.test/withCreateStyles.actual.tsx, packages/material-ui-codemod/src/v5.0.0/jss-to-styled.test/withCreateStyles.expected.tsx, packages/material-ui-codemod/src/v5.0.0/jss-to-styled.test/withCreateStyles1.actual.tsx, packages/material-ui-codemod/src/v5.0.0/jss-to-styled.test/withCreateStyles1.expected.tsx, packages/material-ui-codemod/src/v5.0.0/jss-to-styled.test/withCreateStyles2.actual.tsx, packages/material-ui-codemod/src/v5.0.0/jss-to-styled.test/withCreateStyles2.expected.tsx, packages/material-ui-codemod/src/v5.0.0/jss-to-styled.test/withCreateStyles3.actual.tsx, packages/material-ui-codemod/src/v5.0.0/jss-to-styled.test/withCreateStyles3.expected.tsx
Closes https://github.com/mui-org/material-ui/issues/27490
Adds support for converting `makeStyles` and `withStyles` usages when `createStyles` is used.
=> [codemod] Add support for `createStyles` usage in `jss-to-styled`

examples/create-react-app-with-styled-components-typescript/README.md, examples/create-react-app-with-styled-components-typescript/config-overrides.js, examples/create-react-app-with-styled-components-typescript/package.json, examples/create-react-app-with-styled-components-typescript/tsconfig.json, examples/create-react-app-with-styled-components/README.md, examples/create-react-app-with-styled-components/config-overrides.js, examples/create-react-app-with-styled-components/package.json
Follow up on https://github.com/mui-org/material-ui/pull/27583
This PR updates the create-react-app examples that use styled-components to use package aliases.
=> [examples] Update create-react-app examples with styled-components to use package aliases

docs/translations/api-docs/select/select.json, packages/material-ui/src/Select/Select.d.ts, packages/material-ui/src/Select/Select.js
Follow-up to https://github.com/mui-org/material-ui/pull/27370. The documented signature wasn't ideal anyway. `doctrine` can't parse more complex types as well. We may want to switch to TSDoc parsers to support more complex types. For example, here I would've wanted to type `event` as `import('@material-ui/core/Select').SelectChangeEvent` so that people know where the type comes from.
Noticed when reviewing snapshot changes: https://github.com/eps1lon/mui-scripts-incubator/pull/2795/files
=> [docs] Bring back Select#onChange signature API

docs/src/pages/customization/color/ColorTool.js
Closes https://github.com/mui-org/material-ui/issues/27413
Preview: https://deploy-preview-27446--material-ui.netlify.app/customization/color/#playground
Seems like `import * as namespace` doesn't have a guaranteed order in production (webpack? spec?). See https://60ef10f597a6c60008ffde24--material-ui-docs.netlify.app/customization/color/#playground where the order is completely different (and `common` is included) than what you see locally (`common` is excluded).
=> [docs] Hardcode listed colors in /customization/color/#playground

packages/material-ui-unstyled/src/ModalUnstyled/ModalManager.test.js, packages/material-ui-unstyled/src/ModalUnstyled/ModalManager.ts
=> [Modal] Restore `overflowX` and `overflowY` styles

docs/src/modules/components/AppLayoutDocs.js
Open https://next.material-ui.com/components/alert/ with SSR disabled
**Actual**
**Expected**
This regression happened because JSS was determining the resolution based on the import order, emotion, on the other hand, provides no guarantees. See actual:
I was annoyed by the layout shift, hates them.
Preview: https://deploy-preview-27619--material-ui.netlify.app/components/alert/
=> [docs] Fix layout shift when opening hash anchor

docs/src/pages/guides/minimizing-bundle-size/minimizing-bundle-size.md
Preview: https://deploy-preview-27335--material-ui.netlify.app/guides/minimizing-bundle-size/
Background:
- At first it was a `babel-plugin-material-ui`: #5625, #5754
- Then it was reimplemented as generic `babel-plugin-direct-import`: #7707
- It was deprecated after `webpack` start to support `sideEffects` flag: https://github.com/umidbekk/babel-plugin-direct-import/issues/13#issuecomment-419017347
- Then it was removed from this section of the docs (can't find the link to PR)
Why returning back?
- `webpack` applies optimizations for `sideEffects` flag only during production, so importing single icon from `@material-ui/icons` drastically slows initial start for CRA server, same goes for NextJS (hopefully wide adaptation of Vite and Snowpack will resolve it's issue in the future)
- At …
=> [docs] Recommend the `direct-import` babel plugin over `transform-import`

docs/src/pages/components/image-list/CustomImageList.js, docs/src/pages/components/image-list/CustomImageList.tsx, docs/src/pages/components/image-list/MasonryImageList.js, docs/src/pages/components/image-list/MasonryImageList.tsx, docs/src/pages/components/image-list/QuiltedImageList.js, docs/src/pages/components/image-list/QuiltedImageList.tsx, docs/src/pages/components/image-list/StandardImageList.js, docs/src/pages/components/image-list/StandardImageList.tsx, docs/src/pages/components/image-list/TitlebarBelowImageList.js, docs/src/pages/components/image-list/TitlebarBelowImageList.tsx, docs/src/pages/components/image-list/TitlebarBelowMasonryImageList.js, docs/src/pages/components/image-list/TitlebarBelowMasonryImageList.tsx, docs/src/pages/components/image-list/TitlebarImageList.js, docs/src/pages/components/image-list/TitlebarImageList.tsx, docs/src/pages/components/image-list/WovenImageList.js, docs/src/pages/components/image-list/WovenImageList.tsx
I have found this by chance on https://github.com/mui-org/material-ui/pull/27439/commits/a25140632299fc917992801d1990dc1a0bf43dd8. See the issue with the page https://validator.w3.org/nu/?doc=https%3A%2F%2Fnext.material-ui.com%2Fcomponents%2Fimage-list%2F
Preview https://deploy-preview-27632--material-ui.netlify.app/components/image-list/
=> [docs] img should have a src attribute

packages/material-ui-lab/src/TreeItem/TreeItem.js
Applied the suggested changes by @eps1lon 
Closes #27372
=> [TreeView] Fix TreeItem label overflow

.github/renovate.json
We were initially using the default value: "replace". It wasn't updating for in-range updates, we weren't not updating enough. So we changed it to "update-lockfile" #27455. This is not working either, per https://github.com/renovatebot/renovate/discussions/11083, it reruns all the PRs's CI each time one of them is merged. I'm trying a new one.
I have merged this change in x, it seems to work https://github.com/mui-org/material-ui-x/pull/2304
=> [core] Change range strategy to bump

docs/src/pages/components/grid/VariableWidthGrid.js, docs/src/pages/components/grid/VariableWidthGrid.tsx, docs/src/pages/components/grid/grid.md, packages/material-ui/src/Grid/Grid.js, packages/material-ui/src/Grid/Grid.test.js
In #11804, support for the `"auto"` value was added to props like `xs`, `sm` et. al.
This prop value causes the MUI grid to work just like [Bootstrap's grid "auto" setting](https://getbootstrap.com/docs/4.0/layout/grid/#variable-width-content) _most_ of the time, with a few exceptions:
1. `flex-shrink` remains set to `1`, which means the item will not always remain sized based on the "natural" width of its contents like users expect. 
* [Reduced test case](https://codesandbox.io/s/variablewidthgrid-material-demo-forked-juoqo)
1. `width: 100%` is still applied when using the `"auto"` setting on a [nested `Grid` container items](https://next.material-ui.com/components/grid/#heading-nested-grid) (`<Grid container item xs="auto" />`), which causes the item to not be sized based on the …
=> [Grid] Fix "auto" behavior to match natural width of its content

packages/material-ui/src/Checkbox/Checkbox.js
It's a follow-up on #27314, we don't need any of the hover styles when disableRipple is true.
=> [core] Reduce use CSS when Checkbox disableRipple is set

docs/src/pages/components/text-fields/InputAdornments.js, docs/src/pages/components/text-fields/InputAdornments.tsx
Preview: https://deploy-preview-27507--material-ui.netlify.app/components/text-fields/#input-adornments
This is just a trivial PR about documentation .
I found the password visibility ("eye") icons in your docs are opposite to common.
In common:
https://www.google.com/search?q=unmask+password+icon&tbm=isch
* eye-open icon on masked password:
* means "will be shown if you click me."
* eye-close icon on unmasked password:
* means "will be hidden if you click me."
[FYI] action-icon vs. state-icon: https://ux.stackexchange.com/questions/54162/icon-for-unmasking-passwords-open-or-closed-to-begin-with
I just felt uncommon. So, if it is not intended, should be fixed.
Thanks.
=> [TextField] password visibility icons ( "visibility" ⇔ "visibility-off" ) should be reversed

packages/material-ui-system/src/Box/Box.d.ts, packages/material-ui-system/src/index.spec.tsx
Closes #27605
This is a simple PR that exposes the `filterProps` string array on the `compose` function from the `@material-ui/system` package.  The changes apply to the TypeScript types for the aforementioned function.
=> [system] Fix missing filterProps in compose type

packages/material-ui-lab/src/PickersDay/PickersDay.test.tsx
I wasn't really aware of the difference between a11y name and visible label in `PickersDay` so let's encode it in tests.
Sparked by https://github.com/mui-org/material-ui/pull/27462
=> [test] Add current behavior for a11y name vs visible name for PickersDay

test/karma.conf.js
See https://github.com/mui-org/material-ui/pull/27389#issuecomment-894820124 for the issue. Judging from https://github.com/karma-runner/karma/issues/2342, there is no real workaround for the logs in th CI.
=> [test] Dodge double logging in dev mode

docs/pages/api-docs/toggle-button-group.json, packages/material-ui/src/ToggleButton/ToggleButton.d.ts, packages/material-ui/src/ToggleButton/ToggleButton.js, packages/material-ui/src/ToggleButtonGroup/ToggleButtonGroup.d.ts, packages/material-ui/src/ToggleButtonGroup/ToggleButtonGroup.js
This PR fixes two independent bugs related to the toggle button.
1. The `color` prop is applied for nothing, leading to https://validator.w3.org/nu/?doc=https%3A%2F%2Fnext.material-ui.com%2Fcomponents%2Ftoggle-button%2F
I have noticed it on https://next--material-ui.netlify.app/branding/home/
2. The `color` migration to custom values with the theme and module augmentation was missed. I'm doing a follow-up on https://github.com/mui-org/material-ui/pull/27337#issuecomment-884365468.
=> [ToggleButton] Fix handling of color prop

docs/pages/api-docs/radio.json, packages/material-ui/src/Checkbox/Checkbox.js, packages/material-ui/src/Radio/Radio.d.ts, packages/material-ui/src/Radio/Radio.js, packages/material-ui/src/Radio/Radio.test.js, test/regressions/fixtures/Radio/RadioIconSizeSmall.js
Changed the way to set the fontSize for Radio and Checkbox components. And added a test case to match the fontSize in the Radio button standard and icon.
With the bug, the Radio was rendered with fontSize of 1.50rem 24x24 and now is render as expected with 1.25rem 20x20.
Closes #27510
=> [Radio] Fix size prop forwarding with custom icons

packages/material-ui-lab/src/PickersDay/PickersDay.tsx
Closes [#27506](https://github.com/mui-org/material-ui/issues/27506)
Improve contrast color of disabled days in calendar
=> [Calendarpicker] Improve contrast between enabled and disabled days

docs/src/pages/components/toggle-button/ToggleButtonNotEmpty.js, docs/src/pages/components/toggle-button/ToggleButtonNotEmpty.tsx, docs/src/pages/components/toggle-button/toggle-button.md
In [this example](https://next.material-ui.com/components/toggle-button/#enforce-value-set) the order of the handle functions is not the same as the order of the rendered components.
Some of my colleagues (myself included) trip over this every now and then, so I decided to change it :smile:
(I've added this example in the first place, so it's my fault it's out of order anyway :grin:)
I've also used the chance to do a bit of cleanup:
- replace the `Grid` wrapper with a `Stack`
- rename "format" to "device", so the demo is simpler to understand
=> [docs] Reorder and rename "enforce value" ToggleButton demo

packages/material-ui/src/ButtonBase/ButtonBase.d.ts, packages/material-ui/src/ButtonBase/ButtonBase.js, packages/material-ui/src/MenuItem/MenuItem.js
Closes #27669
Type now matches that of @types/react.
=> [ButtonBase]: Fix tabIndex type

packages/material-ui/src/Badge/Badge.js, packages/material-ui/src/Badge/Badge.test.js
You either have to fix deprecation warnings for both `classes` and `overlap` or none. But only fixing `classes` while not fixing `overlap` is too complicated to support right now in my opinion.
Closes https://github.com/mui-org/material-ui/issues/27571
=> [Badge] Warn on default `overlap` value as well

docs/src/pages/guides/content-security-policy/content-security-policy.md
Closes https://github.com/mui-org/material-ui/issues/24156
Updates the CSP guide with instructions of how the `nonce` can be set with emotion.
https://deploy-preview-27627--material-ui.netlify.app/guides/content-security-policy/
=> [docs] Update CSP page

docs/src/pages.ts, docs/src/pages/styles/basics/basics.md, docs/translations/translations.json
Act on https://github.com/mui-org/material-ui/issues/13394#issuecomment-885455260. I have also used the opportunity to push the legacy notice further than what we did so far for `@material-ui/styles`.
Preview: https://deploy-preview-27639--material-ui.netlify.app/styles/basics/
=> [docs] Document that @material-ui/styles is not strict mode compatible

docs/src/pages/guides/interoperability/interoperability.md, docs/src/pages/guides/styled-engine/styled-engine.md
Updates the guides for how to configure styled-components as a styled engine.
=> [docs] Update guides for @material-ui/styled-engine-sc installation

docs/src/modules/components/Demo.js
The ref was never read from but the write was not concurrent safe (React 18).
=> [docs] Remove unused code

docs/src/pages/components/lists/lists.md
It's confusing to use the same name for different section. Our implementation for page table of contents also doesn't support it (see duplicate key warnings on affected pages). 
https://deploy-preview-27694--material-ui.netlify.app/components/lists/#customization
=> [docs] Fix duplicate headers in List

CHANGELOG.md
This adds changelog entries that were missing in #27714.
=> [CHANGELOG] Include new changes for v5.0.0-beta.4

docs/src/modules/components/DemoToolbar.js
We default to the previous `codeVariant` anyway if we receive a falsy `codeVariant`. Might as well not dispatch it at all.
=> [docs] Don't dispatch ignored "reset code variant" actions

packages/material-ui-lab/src/themeAugmentation/components.d.ts, packages/material-ui-lab/src/themeAugmentation/overrides.d.ts, packages/material-ui-lab/src/themeAugmentation/props.d.ts
A follow-up on https://github.com/mui-org/material-ui-x/pull/2307#discussion_r684743848. I assume that the author of this PR has copyed our source.
=> [lab] Use the public API for module augmentation

packages/material-ui-unstyled/src/SliderUnstyled/SliderUnstyled.js
Utilize the `CSS.supports` method in `SliderUnstyled` component to check if `touch-action` is supported.
=> [core] Utilize `CSS.supports` in `SliderUnstyled` component

packages/material-ui-icons/README.md, packages/material-ui-lab/README.md, packages/material-ui-styled-engine-sc/README.md, packages/material-ui-styled-engine-sc/package.json, packages/material-ui-styled-engine/README.md, packages/material-ui-styled-engine/package.json, packages/material-ui-system/README.md, packages/material-ui-unstyled/README.md
The mention of webpack in the package README is no longer relevant. I noticed this in #27776
=> [docs] Fix outdated styled-engine docs

docs/src/modules/components/ApiPage.js
This is based on feedback that @mbrookes left on the new docs UI in the Figma file where he was concerned about the usefulness of the button. When clicking on the "Edit this page" link in https://next.material-ui.com/api/alert/.
It seems more relevant to link the TypeScript definitions than the JavaScript file. I'm not 100% sure it's better, but it seems to be a change worth considering.
=> [docs] Prefer linking API source TypeScript

docs/src/pages/guides/composition/composition.md, docs/src/pages/guides/typescript/typescript.md
The high-level change of this PR is about hosting the content here https://next.material-ui.com/guides/composition/#with-typescript instead of linking it.
It's a continuation of https://github.com/mui-org/material-ui/pull/27417#discussion_r686585397. We can keep the TypeScript page for things that have no better places, and keep the TypeScript coverage of specific features at the same place where we talk about the JavaScript behavior. I think that it could help make the docs clearer by providing more context to the developers, and to make the content easier to discover.
Preview https://deploy-preview-27782--material-ui.netlify.app/guides/typescript/#usage-of-component-prop
=> [docs] Move TypeScript docs in context

docs/src/pages/components/transfer-list/transfer-list.md
This is a follow-up on #27579.
=> [docs] Document the transfer-list limitations

docs/src/modules/components/AppNavDrawerItem.js, packages/material-ui-system/src/createStyled.d.ts
- [styled-engine] Drop withComponent support (`#27780`) @oliviertassinari
Use the `as` prop instead. It's not style destructive when using multiple layers of styled() calls.
---
Why?
1. styled-components talks about removing it
https://styled-components.com/docs/api#withcomponent
2. goober doesn't support it
https://goober.js.org/
3. We almost never use it in the codebase, the smaller the API surface, the easier we can make changes.
I have noticed this in #27776.
=> [styled-engine] Drop withComponent support

docs/src/pages/components/steppers/TextMobileStepper.js, docs/src/pages/components/steppers/TextMobileStepper.tsx
I updated the demo of the Mobile Text Stepper, adding variant="text".  The description said that it would show the current step number in text form but it actually showed the current step number with the default dots. 
@siriwatknp also recommended this change
--- a/docs/src/pages/components/steppers/TextMobileStepper.tsx
+++ b/docs/src/pages/components/steppers/TextMobileStepper.tsx
But I couldn't find the place in the file tree where the "a" and "b" versions of the docs are.
Closes https://github.com/mui-org/material-ui/issues/27608
=> [docs] Fix MobileTextStepper example to match description

docs/src/pages/components/about-the-lab/about-the-lab.md, packages/material-ui-lab/src/themeAugmentation/index.js
Runtime and types should have the same shape. The types don't export any runtime so neither should the actual runtime. 
Closes https://github.com/mui-org/material-ui/issues/27704
=> [docs] Zero runtime themeAugmentation documentation

packages/material-ui/src/InputLabel/InputLabel.js, packages/material-ui/src/InputLabel/InputLabel.test.js
Closes #27707
Problem
As it's pointed out in the #27707 , `InputLabel` doesn't forward the `asterisk` class to `FormLabel`'s `AsteriskComponent` despite it's specifically mentioned in the documentation. It causes problems with both tests and styling.
Changes
- Forward the `asterisk` class to `FormLabel`'s `AsteriskComponent` if `InputLabel` has the `required` property
- Add a test to ensure that `AsteriskComponent` receives both (`.MuiFormLabel-asterisk.MuiInputLabel-asterisk`) classes
=> [InputLabel] Apply `asterisk` class when `required`

docs/pages/branding/about.tsx, docs/src/pages/components/autocomplete/CountrySelect.js, docs/src/pages/components/autocomplete/CountrySelect.tsx
Closes #27525
Preview: https://deploy-preview-27723--material-ui.netlify.app/components/autocomplete/#country-select
=> [docs] Use country image instead of emoji

docs/packages/markdown/loader.js
Broke in https://github.com/mui-org/material-ui/pull/27406 and was not caught in review.
Preview: https://deploy-preview-27691--material-ui.netlify.app/components/date-picker/#main-content
Also fixes a crash in development when the TypeScript version of a demo doesn't exist (e.g. `/getting-started/usage/`)
=> [docs] Display TypeScript code of demo if requested

docs/src/pages/components/cards/ActionAreaCard.js, docs/src/pages/components/cards/ActionAreaCard.tsx, docs/src/pages/components/cards/ImgMediaCard.js, docs/src/pages/components/cards/ImgMediaCard.tsx, docs/src/pages/components/cards/MediaCard.js, docs/src/pages/components/cards/MediaCard.tsx, docs/src/pages/components/cards/MediaControlCard.js, docs/src/pages/components/cards/MediaControlCard.tsx, docs/src/pages/components/cards/MultiActionAreaCard.js, docs/src/pages/components/cards/MultiActionAreaCard.tsx, docs/src/pages/components/cards/NotificationCard.js, docs/src/pages/components/cards/NotificationCard.tsx, docs/src/pages/components/cards/PlayerCard.js, docs/src/pages/components/cards/PlayerCard.tsx, docs/src/pages/components/cards/RecipeReviewCard.js, docs/src/pages/components/cards/RecipeReviewCard.tsx, docs/src/pages/components/cards/TaskCard.js, docs/src/pages/components/cards/TaskCard.tsx, docs/src/pages/components/skeleton/Facebook.js, docs/src/pages/components/skeleton/Facebook.tsx, docs/src/pages/getting-started/templates/album/Album.js, docs/src/pages/getting-started/templates/album/Album.tsx, docs/src/pages/getting-started/templates/blog/Blog.js, docs/src/pages/getting-started/templates/blog/Blog.tsx, docs/src/pages/getting-started/templates/blog/FeaturedPost.js, docs/src/pages/getting-started/templates/blog/FeaturedPost.tsx
- Add `alt` to existing images
- Remove `title` in favor of `alt`
- Name `button`
- Expose image semantics of `<CardMedia image />`
- https://www.argos-ci.com/mui-org/material-ui/builds/676 revealed that the PlayerCard album cover shouldn't use an avatar 
Increases a11y lighthouse score from 85 (https://61119ce4bacc510008cb3ee1--material-ui.netlify.app/components/cards/) to 96 (https://deploy-preview-27675--material-ui.netlify.app/components/cards).
The improvement is actually higher since some elements that were clearly images (`<CardMedia image />`) were not exposed as images at all. I'll follow-up with a patch to `CardMedia` that patches this up for older demos.
Visual changes are expected: https://www.argos-ci.com/mui-org/material-ui/builds/681
=> [docs] Improve accessible labels for Card demos

packages/material-ui-lab/src/TimelineDot/TimelineDot.js, packages/material-ui-lab/src/TimelineDot/TimelineDot.test.js
Fixes https://github.com/mui-org/material-ui/issues/27688
Currently when using `color="inherit"` on the `TimelineDot` it crashes. We need to apply the styles for the background/border color on the TimelineDot only if the color is not `inherited`
=> [Timeline] Fix color="inherit" on TimelineDot

packages/material-ui/src/NativeSelect/NativeSelect.test.js, packages/material-ui/src/NativeSelect/NativeSelectInput.js
Closes https://github.com/mui-org/material-ui/issues/27655
=> [Select] Fix NativeSelect propagating classes to the DOM element

docs/next.config.js, docs/src/modules/utils/helpers.ts, packages/material-ui/scripts/rollup.config.js
I have noticed this in #27776. The value of removing the alias is to fail sooner. I have made one commit for each removal to explain why.
=> [styled-engine] Remove unecessary aliases

packages/material-ui/src/Stack/Stack.js
I have first noticed how we were using `Stack` instead of `MuiStack` for the name by chance. Then, I realized we could close #27498 at the same time.
=> [Stack] Match the customization standard

packages/material-ui-lab/src/DateRangePickerDay/DateRangePickerDay.test.tsx, packages/material-ui/src/NativeSelect/NativeSelect.test.js, test/utils/describeConformance.js
The PR updates the way of how we test if the `classes` prop is forwarded to some DOM element. Previously, it was checking for only the first child, but that was not enough, for example for ensuring it works in the `NativeSelect` where the prop was spread to the `select` element. Now we test that there isn't any DOM element with a `classes` attribute. 
~There wasn't any new failing test.~ Not true, here are the logs from the unit tests - https://app.circleci.com/pipelines/github/mui-org/material-ui/50805/workflows/4d4535b3-89fd-4404-989e-8b0cb1197d17/jobs/285659 Going to fix them now
----
Edit: Turns out there was a problem with how the `classes` prop was tested, especially if `wrapMount` was used, that is why the tests were failing. All fixed with …
=> [test] Improve test for checking if classes is forwarded to any DOM element

packages/material-ui-system/src/createStyled.js, packages/material-ui/src/styles/styled.test.js
Closes https://github.com/mui-org/material-ui/issues/27697
The `rootShouldForwardProps` option is added only if the `slot` option is specified explicitly as `Root`. Otherwise the default shouldForwardProps are being propagated.
=> [system] Forward `classes` prop if no slot specified in the options

docs/src/pages/components/autocomplete/CountrySelect.js, docs/src/pages/components/autocomplete/CountrySelect.tsx
A follow-up on https://github.com/mui-org/material-ui/pull/27723, it fixes the layout shift when the image is loading. Before:
https://user-images.githubusercontent.com/3165635/129696620-87a30c9a-a3e3-4f8b-b9c8-c84d1ad55181.mp4
=> [docs] Fix Autocomplete country layout shift

.browserslistrc, docs/src/pages/getting-started/supported-platforms/supported-platforms.md, docs/src/pages/guides/migration-v4/migration-v4.md, test/karma.conf.js, test/karma.conf.profile.js, yarn.lock
---
Update our `.browserslistrc` one final time before stable release following the comments in the file.
=> [core] Update `.browserslistrc` file

docs/src/modules/components/MarkdownElement.js
Removed the CSS property that was hiding overflow.
Fixes #27612 
I have visually confirmed that this fixes the bug in Chrome and Firefox and that other components do not seem to be affected.
Preview: https://deploy-preview-27787--material-ui.netlify.app/api/swipeable-drawer/
=> [docs] Make API documentation tables horizontally scrollable

packages/material-ui/src/ButtonGroup/ButtonGroup.d.ts
Currently, typescript consumers can augment the available values for `ButtonProps.size`. However, they cannot do the same for `ButtonGroupProps.size`.
This can cause consumers to have inconsistent prop API options for button sizes when set on the group versus the individual buttons.
1. Add/export the `ButtonGroupPropsSizeOverrides` interface
1. Use `OverridableStringUnion` to allow the MUI size values, or any values specified by the consumer in the aforementioned interface.
=> [ButtonGroup] Allow `size` customization via module augmentation

packages/material-ui/src/useAutocomplete/useAutocomplete.d.ts
The useAutocomplete hook uses a type called `Value`. It's a very generic name for a type specific to the Autocomplete control. This PR renames it to AutocompleteValue.
* The type 'Value' exported from @material-ui/core is now named 'AutocompleteValue'
=> [Autocomplete] Rename Value type to AutocompleteValue

docs/src/modules/components/AppFrame.js, docs/src/modules/components/AppNavDrawer.js, docs/src/modules/components/AppSearch.js, docs/src/modules/components/AppSettingsDrawer.js, docs/src/modules/components/DemoSandboxed.js, docs/src/modules/components/Notifications.js, docs/src/modules/components/ThemeContext.js
Preview - https://deploy-preview-27789--material-ui.netlify.app/
Changes done in the PR:
- Use the branding theme on all website
- Wrap each demo with `ThemeProvider` with the default theme
- Updated AppBar and SideBar 
- Updated the container background colors to match the new branding colors
Should we fragment the changes and do them step by step? I think these changes are an important foundation to do all other changes. It is important to have the branding theme out here on the docs so that the other changes can use it as well.
----
In a follow up PRs we can do the changes on the:
- Sidebar
- The page legend
- The demos icons
- ....
=> [docs] Apply the new branding theme and do the AppBar redesign

docs/src/modules/components/DemoSandboxed.js
The PR fixes a regression from https://github.com/mui-org/material-ui/pull/27789 The direction was not set initially, it is fixed now by setting the direction from the outer theme.
=> [docs] Fix rtl issue on the demos

packages/material-ui-system/src/createStyled.js, packages/material-ui-system/src/createStyled.test.js
This is a continuation of this issue: https://github.com/mui-org/material-ui/issues/26944
Problem:
You can see that the styles of pseudo classes of variants are not merged correctly here: https://codesandbox.io/s/musing-darkness-2cd8d?file=/src/App.js:119-613
Solution: Following @oliviertassinari 's suggestion (https://github.com/mui-org/material-ui/issues/26944#issuecomment-869223488), using an array to store variant styles rather than an object does the fix.
```diff
@@ -33,7 +33,7 @@ const getVariantStyles = (name, theme) => {
const variantsResolver = (props, styles, theme, name) => {
const { styleProps = {} } = props;
-  let variantsStyles = {};
+  const variantsStyles = [];
const themeVariants = theme?.components?.[name]?.variants;
if (themeVariants) { …
```
=> [theme] Fix pseudo class overridden in variants

docs/src/pages/components/progress/CircularIntegration.js, docs/src/pages/components/progress/CircularIntegration.tsx
Since `sx` `marginTop` and `marginLeft` are coefficients now, the demo is broken:
Note that the right button progress is outside of the demo box.
=> [docs] Fix circular integration demo

docs/src/modules/components/DemoSandboxed.js, packages/material-ui/src/Tooltip/Tooltip.js, test/regressions/fixtures/Tooltip/PositionedTooltipsRtl.js
Fixes https://github.com/mui-org/material-ui/issues/27858 The fix was to prevent some styles from flipping in rtl. As `/* @noflip */` is working only with string templates, I've added the `isRtl` prop and added the appropriate styles based on it.
Codesandbox in RTL on master: 
https://codesandbox.io/s/material-demo-forked-qh2ds?file=/demo.js
Codesandbox in RTL on next:
https://codesandbox.io/s/basictooltip-material-demo-forked-5gc67?file=/demo.js
Codesandbox using the packages in the PR:
https://codesandbox.io/s/basictooltip-material-demo-forked-44bhg?file=/demo.js
-----
Next docs 😢 :
Current PR docs:
=> [Tooltip] Fix broken arrow position in rtl

docs/src/modules/components/DemoToolbar.js
We previously nested the `Menu` inside the `Toolbar`:
```jsx
<Toolbar>
{...controls}
<Menu />
</Toolbar>
```
Now `Toolbar` and `Menu` are siblings
The issue was that we warn on any focus event from inside `Toolbar` since only the `Toolbar` should control focus. 
There's an argument to be made that it shouldn't do that to begin with or at least check if focused element is part of the toolbar (since the Toolbar becomes inaccessible when the Menu is open there's no reason to warn).
However, this is a bit more complicated and the warning is valueable since we need to manually wire up each toolbar control to the toolbar. 
Though definitely something to consider when we want to work on a Toolbar. Ideally it would "just" know what the controls are.
=> [docs] Fix false-positive useToolbar warning when using the demo toolbar menu

docs/src/pages/components/date-picker/ServerRequestDatePicker.js, docs/src/pages/components/date-picker/ServerRequestDatePicker.tsx
Previously we logged "Wow, you are switching months too quickly 🐕" which is not useful. The whole point was to abort gracefully, not log that this abortion is excessive (which it isn't).
It also hid actual fetch errors.
Now we just ignore the abort errors and let the actual fetch error surface.
=> [docs] Don't log if a request was aborted in ServerRequestDatePicker demo

docs/src/modules/components/DemoToolbar.js
When landing on page while hovering over a demo you previously got a "switching from controlled to uncontrolled mode" because we didn't actually update the `key` when the mode changed.
https://user-images.githubusercontent.com/12292047/130036835-73ba1286-4c49-4346-8e36-fdacc4cd143d.mp4
We don't need to remount the Tooltip to begin with and can just use a fully controlled Tooltip.
Also fixes flickering of the tooltip when we move the cursor from icon to demo:
Before:
https://user-images.githubusercontent.com/12292047/130039772-246bd0d4-a983-4ea1-b67c-36121d361802.mp4
After:
https://user-images.githubusercontent.com/12292047/130039785-9e78c5dd-1a78-4603-aba2-c70beb15b3af.mp4
This also allows pushing usage of `useMediaQuery` further down avoiding unnecessary work when the value changes.
=> [docs] Fix Tooltip flicker when hovering between code icon and demo

examples/create-react-app-with-styled-components-typescript/README.md, examples/create-react-app-with-styled-components-typescript/config-overrides.js, examples/create-react-app-with-styled-components-typescript/package.json, examples/create-react-app-with-styled-components-typescript/tsconfig.json, examples/create-react-app-with-styled-components/README.md, examples/create-react-app-with-styled-components/config-overrides.js, examples/create-react-app-with-styled-components/package.json
Reverts mui-org/material-ui#27591
`npm` does not work with the current setup. Closes https://github.com/mui-org/material-ui/issues/27846
Alternativly we can specify in the project's readme that only `yarn` is supported at the moment.
--- 
Also need to revert the changes in the nextjs with styled-components example. (or again specify in the readme that only `yarn` is supported.
For nextjs I would vote for adding in the readme to use `yarn` as those changes also fixed the class name mismatch error.
=> Revert "[examples] Update create-react-app examples with styled-components to use package aliases"

docs/src/pages/components/autocomplete/CustomizedHook.js, docs/src/pages/components/autocomplete/CustomizedHook.tsx, docs/src/pages/components/autocomplete/autocomplete.md
As discussed in https://github.com/mui-org/material-ui/pull/27524/files/d927b0af38eae07b78c1e5ed4899dedd246a2382#r683710492, this PR changes the useAutocomplete import path in one demo, making it consistent with other demos showcasing the unstyled building blocks.
=> [docs] Correct the useAutocomplete import path

examples/nextjs-with-styled-components-typescript/next.config.js, examples/nextjs-with-styled-components-typescript/package.json, examples/nextjs-with-styled-components-typescript/tsconfig.json
Reverts mui-org/material-ui#27583
Follow up on https://github.com/mui-org/material-ui/pull/27917 I've tested installing and starting with `npm` it doesn't work - it requires emotion.
Reopens https://github.com/mui-org/material-ui/issues/27512
=> Revert "[examples] Fix nextjs with styled-components example"

packages/material-ui-system/src/createStyled.js, packages/material-ui-system/src/styled.test.js
I noticed this issue when working on a test case for https://github.com/mui-org/material-ui/pull/27847
Here is a codesandbox that illustrates the issue - https://codesandbox.io/s/ancient-snow-45mhz?file=/src/App.js Note that the styles from the variants are being applied only if the `overridesResolver` is defined. These are not related and this dependency is not expected.
=> [system] Remove dependency on `overridesResolver` for the `variants`

docs/src/modules/components/DemoToolbar.js, docs/src/modules/components/MarkdownElement.js, docs/src/pages/components/tables/ReactVirtualizedTable.js, docs/src/pages/components/tables/ReactVirtualizedTable.tsx, packages/material-ui/src/ButtonBase/TouchRipple.js, packages/material-ui/src/Snackbar/Snackbar.js
I've searched on master and found the following occurrences of `flip: false` (I've ignored the docs documenting this feature):
```
// Fixed with the changes in DemoToolbar.js
docs\src\modules\components\Demo.js:
90            display: 'flex',
91:           flip: false,
92            top: 0,
// Fixed with the changes in MarkdownElement.js
docs\src\modules\components\MarkdownElement.js:
203  });
204: const useStyles = makeStyles(styles, { name: 'MarkdownElement', flip: false });
205  
// Fixed with the changes in ReactVirtualizedTable.js
docs\src\pages\components\tables\ReactVirtualizedTable.js:
18      '& .ReactVirtualized__Table__headerRow': {
19:       flip: false,
20        paddingRight: theme.direction === 'rtl' ? '0 !important' : undefined,
// Fixed with the changes in …
```
=> [core] Fix various flip: false regressions

docs/pages/api-docs/autocomplete.json, packages/material-ui/src/Autocomplete/Autocomplete.js, packages/material-ui/src/Autocomplete/Autocomplete.test.js
=> [Autocomplete] Add verbose warning for defaultValue

packages/material-ui/src/SvgIcon/SvgIcon.js, test/regressions/fixtures/SvgIcon/CustomColorSvgIcon.js
Given
```jsx
export default function SvgIconsColor() {
palette: {
custom: { main: '#ec407a' },
},
});
return (
<ThemeProvider theme={theme}>
<FavoriteRounded fontSize="large" />
<FavoriteRounded fontSize="large" color="secondary" />
<FavoriteRounded fontSize="large" color="custom" />
</ThemeProvider>
);
}
```
Before:
After:
Closes https://github.com/mui-org/material-ui/issues/27831 see https://codesandbox.io/s/material-ui-v5-icons-custom-color-bug-forked-mzyxm
=> [SvgIcon] Apply custom color if defined in the theme

docs/src/modules/components/DemoSandboxed.js
Just flipped the composition order of `Sandbox -> ThemeProvider` to `ThemeProvider -> Sandbox`.
The demo component needs to be a child of `Sandbox` since some implementations rely on `cloneElement` (this is why `cloneElement` is bad). Otherwise the `window` of the current frame would be incorrect (due to lexical scope).
Notice how the "scroll to top" button is always visible regardless of the scrollbar position of the demo. Or simpler: See the prop-types warning in the `BackToTop` demo on 0ab84c3b0246ef123c9abad3d1aee34c823fc159.
Before:
https://6123aa67c1b1b700071a0df2--material-ui.netlify.app/components/app-bar/#BackToTop
After:
https://deploy-preview-27924--material-ui.netlify.app/components/app-bar/#BackToTop
It's the simplest solution I can come up with since we have to consider that …
=> [docs] Pass window of iframe to framed demos

docs/src/components/productDesignKit/DesignKitDemo.tsx, docs/src/components/productDesignKit/DesignKitFAQ.tsx, docs/src/components/productDesignKit/DesignKitHero.tsx, docs/src/components/productTemplate/TemplateHero.tsx, docs/src/modules/components/Link.tsx
The nav items didn't include the common affordances for links (e.g. open new tab, copy link adress etc).
Before: https://6124b8cbdf676e0008cc3e43--material-ui.netlify.app/components/box/
After: https://deploy-preview-27936--material-ui.netlify.app/components/box/
Bisecting lead to 49f21f82bec4a6bb5bec8248c044374bc58f3d5a which makes sense since the child element of `next/link` no longer had the `a` type and therefore needed an explicit `passHref`. 
It's unclear why `passHref` was a supported prop. It wouldn't be useful since the child type is controlled by the implementation not its usage. But we may have destructured it in `NextLinkComposed` because its callsites didn't properly filter `passHref`. This is a responsibility of the callsite of `NextLinkComposed`. Good think is that …
=> [docs] Fix missing `href` for AppDrawerNavItems

docs/src/pages/guides/migration-v4/migration-v4.md
This change is mostly about giving the "Theme structure" a dedicated h3. This aspect of the migration seems important enough to deserve it. While I was at it, I also fixed a few git diff.
=> [docs] Migration, emphasize theme structure change

packages/material-ui/src/Badge/Badge.js
Noticed they were missing. TypeScript told me I could use them, the browser got angry with me for trying to use `undefined` 😄
=> [Badge] Add missing classes to exported class object

docs/pages/api-docs/button-group.json, packages/material-ui/src/ButtonGroup/ButtonGroup.js
This is a follow-up to #27834 that makes `PropTypes` for `ButtonGroup` align with the newly "augmentable" size interface.
@oliviertassinari
=> [ButtonGroup] Update PropTypes to match augmentable interface

docs/src/pages.ts
Same as #27414 but on the next branch
=> [docs] Add GridExportCSVOptions page to documentation pages

.eslintrc.js, docs/src/components/header/HeaderNavBar.tsx, docs/src/components/home/DesignKits.tsx, docs/src/components/home/ElementPointer.tsx, docs/src/components/home/StoreTemplatesBanner.tsx, docs/src/components/showcase/FolderTable.tsx, docs/src/modules/utils/find.js, docs/src/pages/components/tables/EnhancedTable.js, docs/src/pages/components/tables/EnhancedTable.tsx, docs/src/pages/discover-more/showcase/Showcase.js, packages/material-ui-codemod/src/util/memoize.js, packages/material-ui-codemod/src/v4.0.0/optimal-imports.js, packages/material-ui-codemod/src/v4.0.0/top-level-imports.js, packages/material-ui-codemod/src/v5.0.0/optimal-imports.js, packages/material-ui-lab/src/PickersDay/PickersDay.tsx, packages/material-ui-lab/src/TabContext/TabContext.test.js, packages/material-ui-styled-engine-sc/src/GlobalStyles/GlobalStyles.test.js, packages/material-ui-styled-engine/src/GlobalStyles/GlobalStyles.test.js, packages/material-ui-system/src/styleFunctionSx/styleFunctionSx.js, packages/material-ui/src/GlobalStyles/GlobalStyles.test.js, packages/material-ui/src/Grid/Grid.js, packages/material-ui/src/Grid/Grid.test.js, packages/material-ui/src/TablePagination/TablePagination.js, packages/material-ui/src/locale/index.ts, packages/typescript-to-proptypes/src/injector.ts, packages/typescript-to-proptypes/src/loadConfig.ts, packages/typescript-to-proptypes/src/parser.ts
Talked about this informally before. I feel like this improves readability in all instances so we should enforce it (fixable) via lint rule instead of nitpicking in code reviews.
=> [core] Enforce curly braces for block statements

docs/src/pages/components/breadcrumbs/RouterBreadcrumbs.js, docs/src/pages/components/breadcrumbs/RouterBreadcrumbs.tsx
Either we disable the rule or not. But I feel like every nested ternary can be written more readable without a nested ternary. And especially for demos we want to prioritize readability.
And it makes it more obvious that there might be a better composition possible in the feature `ListItemLink` that is "expandable" and one that isn't.
=> [docs] Don't use nested ternary

docs/src/pages/getting-started/templates/sign-up/SignUp.js, docs/src/pages/getting-started/templates/sign-up/SignUp.tsx, docs/src/pages/premium-themes/onepirate/SignUp.js, docs/src/pages/premium-themes/onepirate/SignUp.tsx
Just updating the sign-up template to comply with the HTML form control infrastructure standards. 
You can find [here](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#attr-fe-autocomplete-new-password), that `new-password` is preferred in the `autocomplete` field over `current-password` when creating a new account.
Thank you for this awesome package, keep up the good work :)
=> [docs] Change sign-up template autocomplete to use "new-password"

docs/package.json, docs/src/pages/components/snackbars/IntegrationNotistack.js, docs/src/pages/components/snackbars/IntegrationNotistack.tsx, docs/src/pages/components/snackbars/snackbars.md, yarn.lock
It took a while for notistack to be compatible with v5, but I'm glad that it is compatible now.
=> [docs] Add notistack example compatible with v5.x.x

docs/src/components/home/ElementPointer.tsx
`useCallback(debounce(fn))` is not lintable by `exhaustive-deps` (see https://github.com/facebook/react/issues/20904).
However, we can make it lintable by just using `useMemo`:
```diff
-const handleSomething = useCallback(debounce(() => doSomething(someVariable)), [someVariable])
+const handleSomething = useMemo(() => debounce(() => doSomething(someVariable)), [someVariable])
```
Also: Please use global eslint-disable sparringly. There's rarely ever a reson to. Use `eslint-disable-next-line` instead. And if you do disable a rule, please add a rationale.
=> [core] Use lintable pattern for debounced callbacks

.circleci/config.yml, test/README.md, test/karma.conf.js
1. Limited ressources on BrowserStack lead starvation of the `test_browser` CircleCI job
2. Number of commits in PRs is way bigger than the number of merged commits
3. BrowserStack rarely fails with actual issues
We can save a lot of ressources by only running BS on merged commits. BS now acts as a stop gap for broken releases not broken merges.
Closes https://github.com/mui-org/material-ui/issues/27991
[Documentation of new workflow](https://github.com/eps1lon/material-ui/tree/test/disable-browserstack-pr/test#browserstack)
Usual PR run (now with no BrowserStack): https://app.circleci.com/pipelines/github/mui-org/material-ui/51444/workflows/b40d81d2-6f75-431e-b6b6-3b1f480300a2/jobs/290265
PR with `"parameters": { "browserstack-force": true }` i.e. with BrowserStack: …
=> [test] Disable browserstack for PRs

packages/eslint-plugin-material-ui/src/rules/no-hardcoded-labels.js, packages/eslint-plugin-material-ui/src/rules/no-hardcoded-labels.test.js
The following patterns are now considered valid:
```jsx
<h2>{componentName} API</h2>
// ignore literals that only consist of non-word characters
<span>*</span>
<span>.{className}</span>
```
`API` is tech jargon. I'm not aware of translations of the abbreviation that are used in other languages.
All of these patterns were reported in `docs/src/modules/components/ApiPage.js`
Also updated the error message now that `t` has its own hook and is no longer tied to redux.
=> [eslint-plugin-material-ui] Only require translation of word characters and not API

docs/src/modules/components/DemoToolbar.js
To behave more closely to https://next.material-ui.com/components/menus/#basic-menu
Before 
After
=> [docs] Update toolbar menu to behave closer to default

docs/src/pages/customization/how-to-customize/how-to-customize.md
`GlobalStyles` when rendered with `styled-components` update the `<style>` tag on each render (see https://github.com/mui-org/material-ui/pull/28070 for example). Adding a note on the documentation that will suggest to hoist the `GlobalStyles` to static const whenever possible.
=> [docs] Add a recommendation for hoisting GlobalStyles to static constant

docs/src/modules/utils/getJsxPreview.js, docs/src/modules/utils/getJsxPreview.test.js
Per-commit review advised.
1. Group detection of wrapper elements
Hopefully it's clearer now that `div`, `Box` and `Stack` are all considered the same.
2. Showcase current behavior causing 
3. Fix current behavior
Closes https://github.com/mui-org/material-ui/issues/27958
Closes https://github.com/mui-org/material-ui/pull/27994
Before: https://612f5f75432821000775a0be--material-ui.netlify.app/components/transitions#SlideFromContainer
After: https://deploy-preview-28092--material-ui.netlify.app/components/transitions/#SlideFromContainer
Note that a regular expression will never be 100% accurate. JavaScript uses a context-sensitive grammar and regular expressions are not powerful enough to parse this type of grammar.
If we hit another edge case, we should move this work into a babel plugin …
=> [docs] Fix preview for multiline JSX attributes

docs/src/pages/components/masonry/BasicMasonry.js, docs/src/pages/components/masonry/BasicMasonry.tsx, docs/src/pages/components/masonry/DiffColSizeMasonry.js, docs/src/pages/components/masonry/DiffColSizeMasonry.tsx, docs/src/pages/components/masonry/DiffColSizeMasonryBroken.js, docs/src/pages/components/masonry/DiffColSizeMasonryBroken.tsx, docs/src/pages/components/masonry/FixedColumns.js, docs/src/pages/components/masonry/FixedColumns.tsx, docs/src/pages/components/masonry/FixedSpacing.js, docs/src/pages/components/masonry/FixedSpacing.tsx, docs/src/pages/components/masonry/ResponsiveColumns.js, docs/src/pages/components/masonry/ResponsiveColumns.tsx, docs/src/pages/components/masonry/ResponsiveSpacing.js, docs/src/pages/components/masonry/ResponsiveSpacing.tsx, docs/src/pages/components/masonry/SSRMasonry.js, docs/src/pages/components/masonry/SSRMasonry.tsx
The style of the div items used for demo of `Masonry` can be improved to be consistent with those used for demo of `Grid`, which can be found here: https://next.material-ui.com/components/grid/#main-content
**Before**:
https://deploy-preview-27439--material-ui.netlify.app/components/masonry/
**After**:
https://deploy-preview-27957--material-ui.netlify.app/components/masonry/
=> [Masonry] Improve the styling on the demos

packages/material-ui/scripts/rollup.config.js
Fixes the problem discussed in https://github.com/mui-org/material-ui/pull/28074#issuecomment-909340177 by searching for index.ts in addition to index.js in rollup config.
=> [core] Include TS modules in rollup import resolution

docs/src/modules/components/AppFrame.js, docs/src/modules/components/AppNavDrawer.js
I am proposing we push the Language last, it looked a bit strange to be between the icon buttons and the input, as it doesn't have any borders around.
Previously:
Now:
=> [docs] Reorder app bar actions

docs/src/modules/components/DemoToolbar.js
I think that we should be careful with the `sx` prop. It seems that we can easily overuse it. In #27956 I saw similar patterns where we were using styled(), then overriding the same property in sx.
=> [docs] Remove style duplication

packages/material-ui-system/src/createStyled.js
Testing this idea https://github.com/mui-org/material-ui/pull/27838#issuecomment-902731446 out.
- Before: https://next--material-ui.netlify.app/branding/home/: 15.5 kB - 136 kB
- After: https://deploy-preview-27932--material-ui.netlify.app/branding/home/ 15.2 kB - 125 kB
It doesn't make a major difference but it seems harmless and consistent with how emotion & styled-components handles debuggable class names.
I have tried https://www.webpagetest.org/ but the variance was too high to see a real difference. So I guess, it's more around, do we want the long class names in production at the expense of an inlined CSS a bit larger?
=> [system] Shorten class names in production

packages/material-ui-lab/src/MasonryItem/MasonryItem.js, packages/material-ui/src/Tabs/Tabs.js, packages/material-ui/src/TextareaAutosize/TextareaAutosize.js
A follow-up on #27791 and #27840, it seems that we could simplify the logic, without having to mock.
Preview: https://deploy-preview-28037--material-ui.netlify.app/components/masonry/#server-side-rendering
=> [core] Simplify ResizeObserver logic

packages/material-ui/src/Link/Link.d.ts, packages/material-ui/src/Link/Link.spec.tsx
Closes https://github.com/mui-org/material-ui/pull/28046
Closes https://github.com/mui-org/material-ui/issues/24901
=> [Link] Infer `ref` type from `component`

docs/src/pages/getting-started/templates/album/Album.js, docs/src/pages/getting-started/templates/album/Album.tsx, docs/src/pages/getting-started/templates/blog/Blog.js, docs/src/pages/getting-started/templates/blog/Blog.tsx, docs/src/pages/getting-started/templates/checkout/Checkout.js, docs/src/pages/getting-started/templates/checkout/Checkout.tsx, docs/src/pages/getting-started/templates/dashboard/Dashboard.js, docs/src/pages/getting-started/templates/dashboard/Dashboard.tsx, docs/src/pages/getting-started/templates/sign-in-side/SignInSide.js, docs/src/pages/getting-started/templates/sign-in-side/SignInSide.tsx, docs/src/pages/getting-started/templates/sign-in/SignIn.js, docs/src/pages/getting-started/templates/sign-in/SignIn.tsx, docs/src/pages/getting-started/templates/sign-up/SignUp.js, docs/src/pages/getting-started/templates/sign-up/SignUp.tsx
This PR adds the MD theme on the templates so that the docs theme does not leak its styles on the templates.
=> [docs] Fix branding theme leaking on the templates

docs/src/pages/components/links/links.md
=> [docs] Fix Link outdated default `underline` prop

docs/src/pages/components/snackbars/snackbars.md
Fix #21053
In [this comment](https://github.com/mui-org/material-ui/issues/21053#issuecomment-861394577), Olivier suggested putting the plain example under the ["Change Transition"](https://next.material-ui.com/components/snackbars/#change-transition) heading. However, I placed it under the ["Control Slide direction"](https://next.material-ui.com/components/snackbars/#control-slide-direction) heading because I thought it suited better here. Please confirm.
=> [docs] Demo how to use a specific slide direction for Snackbar

.codesandbox/ci.json, babel.config.js, docs/babel.config.js, docs/next.config.js, docs/src/modules/utils/helpers.ts, packages/mui-material-next/README.md, packages/mui-material-next/package.json, packages/mui-material-next/src/index.test.js, packages/mui-material-next/src/index.ts, packages/mui-material-next/tsconfig.build.json, packages/mui-material-next/tsconfig.json, scripts/generateProptypes.ts, scripts/sizeSnapshot/webpack.config.js, test/karma.tests.js, tsconfig.json, webpackBaseConfig.js
This adds a new empty package - `@mui/material-next`.
I set the version to 6.0.0-alpha.0, as the components here will become @mui/material components in v6 (at least that is the goal for now).
I decided not to make the package private. If anyone would like to try it out, I don't see a reason why they shouldn't.
=> [core] Create @mui/material-next package

packages/mui-system/src/borders.js, packages/mui-system/src/borders.test.js, packages/mui-system/src/breakpoints.js, packages/mui-system/src/grid.js, packages/mui-system/src/grid.test.js, packages/mui-system/src/sizing.js, packages/mui-system/src/sizing.test.js
close #28193
**before**
```js
// or any component
<Alert sx={{ borderRadius: 0 }} />
```
`borderRadius: 0` is never attach as a style to emotion.
=> [system] Fix zero value condition

packages/mui-lab/src/MasonryItem/MasonryItem.js
Bad return values for effects will crash React 18.
I think the constraint was always in place but not actively used. See https://github.com/reactwg/react-18/discussions/95
=> [MasonryItem] Fix crash on unmount when using React 18

docs/src/pages/system/styled/UsingOptions.js, docs/src/pages/system/styled/UsingOptions.tsx, packages/mui-lab/src/PickersDay/PickersDay.tsx, packages/mui-system/src/createStyled.d.ts
Continuation of https://github.com/mui-org/material-ui/pull/27983
It was suggested in this issue (https://github.com/mui-org/material-ui/issues/27234) to add generics to `overridesResolver` for type safety. However, it was decided to not implement this for the reasons mentioned here (https://github.com/mui-org/material-ui/pull/27983#pullrequestreview-746952414).
This simply changes the types of `styles` arg and the return value of `overridesResolver`: from `Record<string, any>` to `Record<string, CSSInterpolation>` and from `Record<string, any>` to `CSSInterpolation` respectively.
=> [system] Change type of `styles` arg and return value of `overridesResolver`

test/regressions/fixtures/pickers/OpenDatePicker.tsx, test/regressions/fixtures/pickers/OpenDateTimePicker.tsx, test/regressions/fixtures/pickers/OpenDateTimePickerClock.tsx, test/regressions/fixtures/pickers/OpenTimePicker.tsx, test/regressions/index.test.js
These are required to catch https://github.com/mui-org/material-ui/issues/25422
Including separately as opposed to inside https://github.com/mui-org/material-ui/pull/27534 so that we see the fix better and keep the tests even if we have to revert https://github.com/mui-org/material-ui/pull/27534
=> [pickers] Add visual regression tests for open views

docs/package.json, docs/pages/blog/2019.md, docs/pages/index.js, docs/src/modules/components/AppSearch.js, docs/src/modules/components/Head.js
The PR prepares the deploy for https://v4.material-ui.com
I followed the last three commits from https://github.com/mui-org/material-ui-docs/commits/v3 
I hope I haven't missed something important.
=> [docs] Prepare for v4.material-ui.com deploy

docs/pages/index.tsx, docs/src/modules/components/AppSearch.js, docs/src/modules/components/Head.js
Based on https://github.com/mui-org/material-ui/pull/28227 and recommended by https://github.com/mui-org/material-ui/pull/28227#issuecomment-915442150 adding `#major-version-switch` comments on the lines that need to change when the major version is released.
=> [core] Mark lines that needs to be changed with a major release

packages/mui-material/src/ButtonBase/ButtonBase.js
Reverts the ButtonBase to the state before #27600 (sans changes related to package renames that happened in the meantime).
=> [ButtonBase] Revert to the pre-unstyled implementation

docs/public/_redirects
https://next.material-ui.com/components/data-grid is pointing to `next`, which is the development branch of the v5 version. I've created the `docs-v5` branch to deploy the v5 docs. This new branch was created based on `master`.
Before: https://next.material-ui.com/api/data-grid/data-grid/#css
After: https://deploy-preview-28263--material-ui.netlify.app/api/data-grid/data-grid/#css
=> [docs] Update redirects to X's docs

docs/pages/api-docs/checkbox.json, packages/mui-material/src/Checkbox/Checkbox.js
There's a typo in the proptypes for `Checkbox` color. It looks like ignore comment is preventing `yarn proptypes` from fixing this. Thanks!
=> [Checkbox] Fix color proptype typo

package.json, test/README.md, test/cli.js
`yarn test:watch` is really not suitable for 99% of the use cases. The one-off tasks can use `yarn test:unit --watch`.
Also removes the `--inspect-brk` flag from the experimental CLI since it's not straight forward to use. If you need it, and know what you're doing, you're better off editing the CLI locally.
=> [test] Recommend yarn t over test:watch

test/e2e/TestViewer.js, test/e2e/index.js, test/regressions/TestViewer.js, test/regressions/index.js
Previously all fixtures were bundled in a single chunk. We can use dynamic `import()` instead to split the the file up into multiple chunks. This has only minor implications during development since the browser no longer has to evaluate 14MB of JavaScript on landing (initial chunk is down to 3MB).
It's mainly done now to enable [`lazyCompilation`](https://webpack.js.org/configuration/experiments/#experimentslazycompilation) once it's stable. Lazily compiling the demos will be the major booster since we could basically have a very fast cold start and then compile the next demos while running the test i.e. compilation and test will be concurrent.
=> [test] Lazily import fixtures

packages/mui-codemod/src/v5.0.0/jss-to-styled.js, packages/mui-codemod/src/v5.0.0/jss-to-styled.test.js, packages/mui-codemod/src/v5.0.0/jss-to-styled.test/exportClass.actual.js, packages/mui-codemod/src/v5.0.0/jss-to-styled.test/exportClass.expected.js, packages/mui-codemod/src/v5.0.0/jss-to-styled.test/exportFunction.actual.js, packages/mui-codemod/src/v5.0.0/jss-to-styled.test/exportFunction.expected.js
=> [codemod] Fix jss-to-styled to support other export class, function etc.

dangerfile.js
The experimental page used remix.run which requires a private license and is currently in beta.
=> [core] Remove experimental bundle size tracking page

docs/src/modules/components/AppTableOfContents.js, docs/src/pages/company/careers/developer-advocate.md, docs/src/pages/company/careers/full-stack-engineer.md, docs/src/pages/company/careers/product-manager.md, docs/src/pages/company/careers/react-engineer.md, docs/src/pages/company/careers/technical-product-manager.md
cd8aeb64a9038ae9cb8ecf1cd7fd8a2bfea2d6b6 was the last commit on `master` before we merged `next` and since we had commits on v4.x that weren't on `master` we can't just `git merge --ff-only master`. So I'm just cherry-picking cd8aeb64a9038ae9cb8ecf1cd7fd8a2bfea2d6b6.
Original commit description:
Too many inbound applications than we can handle.
This reverts commit 120c564109245a3b070b1cbaf2c9f3f8659fd9fa.
=> [docs] Remove job ad on the website

docs/package.json, docs/src/pages/components/breadcrumbs/RouterBreadcrumbs.js, docs/src/pages/components/breadcrumbs/RouterBreadcrumbs.tsx, docs/src/pages/components/pagination/PaginationLink.js, docs/src/pages/components/pagination/PaginationLink.tsx, docs/src/pages/guides/routing/ButtonRouter.js, docs/src/pages/guides/routing/ButtonRouter.tsx, docs/src/pages/guides/routing/LinkRouter.js, docs/src/pages/guides/routing/LinkRouter.tsx, docs/src/pages/guides/routing/LinkRouterWithTheme.js, docs/src/pages/guides/routing/LinkRouterWithTheme.tsx, docs/src/pages/guides/routing/ListRouter.js, docs/src/pages/guides/routing/ListRouter.tsx, packages/mui-material/test/typescript/hoc-interop.spec.tsx, yarn.lock
In an application only a single version of `react-router` can exist (https://github.com/remix-run/react-router/releases/tag/v5.0.0).
Since `react-router-dom` exports everything from `react-router` we can automatically ensure this by not directly importing from `react-router`. Otherwise we get failures such as https://app.netlify.com/sites/material-ui/deploys/613d60a8b0b0ad00075eb389
Closes https://github.com/mui-org/material-ui/pull/28282
=> [docs] No import from `react-router`

docs/src/pages/customization/unstyled-components/unstyled-components.md
Found one stray occurrence of the old `material/unstyled`
=> [docs] Replace remaining unstyled package reference

docs/src/modules/utils/helpers.ts
Empty strings are just fine here. The function is also never used outside the module so let's not export it.
=> [core] Remove unnecessary titleize warning

packages/mui-icons-material/package.json, yarn.lock
Makes building `@mui/icons-material` (and, therefore, running `yarn release:build` in the repository root) succeed on Windows.
=> [core] Support release:build with cmd.exe

docs/next.config.js, docs/src/modules/components/MarkdownLinks.js
Next.js previously fell back to basic URL navigation (opposed to client-side routing) for links to `/api` routes that were rendered via markdown.
Compare clicking on the "InputBase" link in "Props of the InputBase component are also available." on https://613f2e53d5823400073263e4--material-ui.netlify.app/api/outlined-input/ vs https://deploy-preview-28356--material-ui.netlify.app//api/outlined-input/
I previously thought `rewrites` was just not working for client-side navigation (https://github.com/mui-org/material-ui/pull/23586). Turns out it's just bugged when the rewrite doesn't have a trailing slash with `trailingSlash: true` (https://github.com/vercel/next.js/issues/25673, https://github.com/vercel/next.js/issues/25104, https://github.com/vercel/next.js/issues/20984).
We can probably …
=> [docs] Fix failing client-side navigation for /api routes

.github/workflows/ci.yml, packages/mui-lab/package.json, packages/mui-system/package.json, packages/mui-system/tsconfig.build.json
Closes https://github.com/mui-org/material-ui/issues/28359 (though I do not fully understand why. I still suspect https://github.com/mui-org/material-ui/issues/28359 is just a race condition.)
=> [system] Fix missing typings for createSpacing

.gitmodules, netlify.toml
The repositories were deleted and a deploy would therfore fail e.g. https://app.netlify.com/sites/material-ui-docs/deploys/6142e735ac632200074f6e25.
=> [core] Make deployable on netlify

packages/mui-material/src/Tooltip/Tooltip.js, packages/mui-material/src/Tooltip/Tooltip.test.js
Currently if you tap on a button within a tooltip on mobile (safari/chrome) the user select will be set to 'none', the `handleTouchEnd` function will remove the touchtimer from the touch start, so the user select ‘none’ will now be left on for the rest of the session.
Demo of the bug here (bug exists in current mui and 5 rc), https://codesandbox.io/s/usage-forked-vow1z?file=/index.js ... if you go to the resolved window on chrome and use a mobile view to trigger event by "tapping" the button, you will see that you can no longer select the text in the document.
=> [Tooltip] Ensure `user-select` CSS property is reverted after touch end

packages/mui-material/src/Tooltip/Tooltip.test.js
Safari normalizes `revert` to `Revert` but not `text`. So let's just use a value that's invariant across browsers. The test just needs a valid value anyway.
Fixes https://app.circleci.com/pipelines/github/mui-org/material-ui/52440/workflows/66f0e1ec-17e3-4ab1-b0f1-b703d0d6a35a/jobs/297054 which broke in https://github.com/mui-org/material-ui/pull/28372
Browser run: https://app.circleci.com/pipelines/github/mui-org/material-ui/52442/workflows/6a90301d-e8f1-4a1c-b6c5-4a7190382b9d/jobs/297071
=> [test] Assert on user-select that has the same value across browsers

CHANGELOG.md, CODE_OF_CONDUCT.md, docs/pages/about.tsx, docs/pages/blog/2021-q2-update.md, docs/pages/blog/may-2019-update.md, docs/pages/blog/mui-core-v5.md, docs/pages/core.tsx, docs/pages/design-kits.tsx, docs/pages/pricing.tsx, docs/pages/templates.tsx, docs/pages/x.tsx, docs/public/_redirects, docs/public/static/manifest.json, docs/src/layouts/AppFooter.tsx, docs/src/modules/components/AppNavDrawerItem.js, docs/src/pages/components/switches/switches.md, docs/src/pages/discover-more/roadmap/roadmap.md, docs/src/pages/system/the-sx-prop/Example.js, docs/src/pages/system/the-sx-prop/Example.tsx
I have pushed one commit, with a description sometimes to get a more granular level of "why"
=> [core] Batch small fixes

docs/notifications.json, docs/src/modules/components/Notifications.js, docs/src/modules/utils/helpers.ts
The issue: open https://mui.com/components/alert/ without any cookies and notice how the notifications are not displayed. The reason is that `getCookie` returned undefined when there is no match, not an empty string as the notification expects
=> [docs] Fix the notification display logic

docs/src/pages/guides/migration-v4/migration-v4.md
A few corrections of the migration document.
I had to remove the emoji from preset-safe codemod title as it doesn't render on Windows.
=> [docs] Correct the migration doc

docs/src/pages/system/the-sx-prop/the-sx-prop.md
Spelling.
Per the CONTRIBUTING page, I tried to point this @ next, but there were too many changes for that to feel correct.
=> [docs] Fix typo in /system/the-sx-prop

docs/pages/blog/2021-q1-update.md, docs/src/pages/company/careers/developer-advocate.md, docs/src/pages/company/careers/full-stack-engineer.md, docs/src/pages/company/careers/react-engineer.md, docs/src/pages/guides/routing/routing-de.md, docs/src/pages/guides/routing/routing-es.md, docs/src/pages/guides/routing/routing-fr.md, docs/src/pages/guides/routing/routing-ja.md, docs/src/pages/guides/routing/routing-pt.md, docs/src/pages/guides/routing/routing-zh.md
Fixing some dead links reported by moz.com
---
~The ones left are related to the API pages of the DataGrid. Looks like the URLs for the API pages changed. The SideBar references URLs starting with `/api-docs/data-grid/*`, but the valid links are actually starting with `/api/data-grid/*`. We should either change the _redirecs:~
```diff
diff --git a/docs/public/_redirects b/docs/public/_redirects
index 9678655950..65243167a0 100644
--- a/docs/public/_redirects
+++ b/docs/public/_redirects
@@ -184,7 +184,7 @@ https://v4.material-ui.com/* https://v4.mui.com/:splat 301!
-/api/*/ https://docs-v5--material-ui-x.netlify.app/api/:splat/ 200
+/api-docs/*/ https://docs-v5--material-ui-x.netlify.app/api/:splat/ 200
/:lang/api/*/ https://docs-v5--material-ui-x.netlify.app/:lang/api/:splat/ 200 …
```
=> [website] Fix 40x links

docs/translations/api-docs/avatar/avatar.json, docs/translations/api-docs/native-select/native-select.json, packages/mui-material/src/Avatar/Avatar.d.ts, packages/mui-material/src/Avatar/Avatar.js, packages/mui-material/src/NativeSelect/NativeSelect.d.ts, packages/mui-material/src/NativeSelect/NativeSelect.js
I noticed some broken attributes links in the API docs for Avatar and NativeSelect. It also seems like the attributes links were pointing to the completely incorrect page in addition to being broken. Avatar was pointing to Input element attributes on MDN, and NativeSelect was pointing to the same as well. I change them to point to image and select attributes respectively.
This is my first PR here so let me know if I did anything wrong.
=> [docs] Fix broken/incorrect attributes links in Avatar and NativeSelect API pages

docs/next.config.js
Adds stats and page titles for client and server bundle. Previously you'd only get one.
=> [core] Ensure both docs bundles are analyzeable

packages/mui-material/src/useMediaQuery/useMediaQuery.js
By leveraging `getThemeProps`. Also ensures that priority of default values is consistent across hoosk/components to avoid surprise when using hooks and components.
Mainly motivated by https://github.com/mui-org/material-ui/pull/28413 which revealed that the options weren't sound.
=> [useMediaQuery] Reduce bundle size

docs/src/pages/guides/minimizing-bundle-size/minimizing-bundle-size.md
Caret positions were still assuming `@material-ui`
Preview: https://deploy-preview-28426--material-ui.netlify.app/guides/minimizing-bundle-size/#option-1
=> [docs] Update caret position in comments to match npm scope

.github/renovate.json, docs/package.json, package.json, yarn.lock
Drops `raw-loader` and `url-loader` that became obsolete with https://github.com/mui-org/material-ui/pull/28248.
Closes https://github.com/mui-org/material-ui/pull/28442
=> [core] Remove unused dependencies

packages/mui-codemod/src/v5.0.0/theme-spacing.js, packages/mui-codemod/src/v5.0.0/theme-spacing.test/actual.js, packages/mui-codemod/src/v5.0.0/theme-spacing.test/expected.js
This PR should prevent the bug from https://github.com/mui-org/mui-store/commit/9c1da0176ec2de1c24e2047c9e76371da185a374 to support this transformation
```js
`-${theme.spacing(1)}px` => theme.spacing(-1) // 1st case
`${-theme.spacing(1)}px` => theme.spacing(-1) // 2nd case
```
=> [codemod] Cover edge case for theme-spacing

test/karma.conf.js
The tests with Firefox 78 are frequently hitting the timeout. It's much slower than the other browsers. 
~This PR aims to evaluate how much faster the latest version of Firefox is in BrowserStack.~ didn't work
=> [test] Increase BS timeout for Firefox

docs/src/components/productCore/CoreComponents.tsx, docs/src/layouts/AppHeader.tsx, docs/src/modules/components/AppSettingsDrawer.js, docs/src/modules/utils/helpers.ts
Initially, I wanted to fix https://twitter.com/sairaj2119/status/1439453551944552448. Open https://mui.com/core/ and click on "Table", it crashes
but then I also noticed:
- We were using flex gap -> removed it
- We were having a dead prop -> removed it
- getCookie silently returns undefined if read on the server -> throw to force making it the SSR handling safer
Fixes https://github.com/mui-org/material-ui/issues/28487
=> [website] Fix crash

docs/pages/blog/material-ui-is-now-mui.md, docs/pages/blog/mui-core-v5.md, docs/pages/core.tsx, docs/src/components/header/HeaderNavBar.tsx, docs/src/components/header/HeaderNavDropdown.tsx, docs/src/components/home/ProductsSwitcher.tsx
- foverer -> forever
- cashflow -> cash flow
- https://medical-dictionary.thefreedictionary.com/ready-to-use
=> [website] Fix typo

docs/pages/components.tsx, docs/src/modules/brandingTheme.ts
**Preview**: https://deploy-preview-28485--material-ui.netlify.app/components/
This page is essential for setting `page_rank` of all components to appear first in docsearch. According to #28333 
- For the design, I make it similar to Navigation drawer but with our Masonry component! (I think we can go with this simple design at first to unblock the docsearch improvement because it can only be access directly from the url and later improve with fancy design)
- Same pages data as in navigation 
---
=> [website] Add components index page

test/utils/createClientRender.tsx
Adds `screen.queryDescriptionOf`, `screen.getDescriptionof`, and `screen.findDescriptionOf`.
Also re-enable `ByLabelText`. It's widely used in the pickers test. Ideally we'd never use it because it requires deep understanding of its limitations. But it has a perf benefit which is especially notable in pickers test. Just have to bet on developer discipline that it's not abused.
=> [test] Add custom queries to `screen`

docs/pages/careers.tsx, docs/src/modules/components/TopLayoutCompany.js
- Updated the file `TopLayoutCompany` to use the AppHeader and AppFooter used in the marketing pages instead of the documentation ones (footer was already outdated though). 
- Added a link to the role pages linking back to the Open Roles section on the Careers page. 
[Deploy preview →](https://deploy-preview-28498--material-ui.netlify.app/company/product-manager/)
=> [website] Update /company pages to use marketing website Header and Footer

docs/pages/_app.js, docs/src/modules/utils/StyledEngineProvider.js
Switching between right-to-left and left-to-right currently re-mounts the whole tree since we inject an additional CacheProvider for right-to-left. It's unclear why. Instead, we use a single CacheProvider and just pass a different value. 
This also helps identifying where a cache is coming from.
=> [docs] Avoid re-mounting the whole tree when switching theme direction

docs/src/modules/components/MarkdownElement.js, docs/src/pages/guides/migration-v4/migration-v4.md
close #28477
close #28496 
- fix the installation new packages step
- fix CssBaseline suggestion for the font-size change
- add one more troubleshooting from https://github.com/mui-org/material-ui/issues/28496
- add styling for `<summary>` tag
---
=> [docs] Fix migration v5 docs

docs/src/pages/system/the-sx-prop/the-sx-prop.md
- [x ] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui-org/material-ui/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).
=> [docs] Fix wrong name for zIndex's property example in /system/

packages/mui-material/src/internal/SwitchBase.js, packages/mui-material/src/internal/SwitchBase.test.js
Hello,  
Mui checkboxes, when used in a `<form>`, don't submit their values.  
https://user-images.githubusercontent.com/6702424/133891709-41dea162-1130-42f7-91ea-5040ea2c4f16.mov
[Playground link](https://stackblitz.com/edit/tss-react-sedypu?devtoolsheight=33&file=index.tsx)
This is due to the fact that, if we [put a `value` prop to the `<input />`](https://github.com/mui-org/material-ui/blob/aa8ab172aaaf49a142cb062984deec480c49c0d4/packages/mui-material/src/internal/SwitchBase.js#L171), even if it's `undefined`, it ends up as an [html property](https://user-images.githubusercontent.com/6702424/133891848-2d2f5453-c680-430c-9723-b0cfd7426027.png) and at the time of submiting the form will be interpreted as a void string overriding the checked value.  
This PR fixes it but maybe it would …
=> [Checkbox] Fix form submission with empty value

docs/src/modules/components/Link.tsx, examples/nextjs-with-styled-components-typescript/src/Link.tsx, examples/nextjs-with-typescript/src/Link.tsx, examples/nextjs/src/Link.js
- Use #27936 to remove the support for the `passHref` prop, it doesn't make sense in our context.
- Use #28101 to remove the typecasting, TypeScript is also smarter in the latest version.
- Remove `cursor: pointer` as it was previously hiding a root issue, and we never need it.
- Keep all the Next.js's Link instances in sync.
=> [docs] Push the fixes on Next.js's Link to the examples

docs/src/components/pricing/EarlyBird.tsx, docs/src/components/pricing/PricingTable.tsx, docs/src/components/productDesignKit/DesignKitFAQ.tsx, docs/src/modules/brandingTheme.ts, docs/src/modules/components/AppTheme.js, docs/src/modules/components/ad.styles.js, docs/src/pages/components/buttons/buttons.md
This PR batches a few small changes:
- Add the missing pricing cap "Price capped at 10 developers per application"
- Fix anchor naming convention: kebab case, as the other parts of the URL: EarlyBird -> early-bird
- Remove unnecessary div
- Increase the contrast between `palette.text.primary` and `palette.text.secondary`. I'm not so sure about this one. I was personally struggling to see a difference in the text between the two
- Make the Ad "powered by" mention less visible
- Update a few headers to match the convention
- Add a new FAQ for the design kits, related to https://github.com/mui-org/mui-store/pull/70
Preview: https://deploy-preview-28581--material-ui.netlify.app/
=> [docs] Mention Premium pricing cap

docs/src/modules/components/ApiPage.js
https://mui.com/api/alert/
Found that looking into a quick video @zromick did (https://www.youtube.com/watch?v=7RqVQ0Zn6-E)
https://deploy-preview-28634--material-ui.netlify.app/api/alert/
=> [docs] Fix title MUI x2

packages/mui-lab/src/DateTimePicker/DateTimePicker.test.tsx, packages/mui-lab/src/MobileDateTimePicker/MobileDateTimePicker.test.tsx
The tests added in https://github.com/mui-org/material-ui/pull/25095 assumed `DatePicker` would render a `MobileDatePicker`. But that depends on the environment. For us that meant that browser tests were failing while headless tests were passing (because different components were rendered). The actual feature is only supported by the `MobileDatePicker` so let's just test it for that component.
Browser pass: https://app.circleci.com/pipelines/github/mui-org/material-ui/52746/workflows/6ae67665-93b2-404e-a3ab-b01acc38b759/jobs/299238 (failures are unrelated)
=> [test] Make `seconds` `views` test pass in browsers

packages/mui-material/src/internal/SwitchBase.test.js
Just a quick follow-up to https://github.com/mui-org/material-ui/pull/28423 that adds a bit of clarity to why `value` is the way it is.
=> [test] Document where the value for SwitchBase#value comes from

examples/nextjs-with-styled-components-typescript/src/Link.tsx, examples/nextjs-with-typescript/src/Link.tsx, examples/nextjs/src/Link.js
Closes #28588 `passHref` was added to all three of the nextjs examples. 
- /examples/nextjs
- /examples/nextjs-with-styled-components-typescript
- /examples/nextjs-with-typescript
=> [examples] Nextjs Link missing passHref #28588

docs/src/pages/components/toggle-button/ToggleButtonSizes.js, docs/src/pages/components/toggle-button/ToggleButtonSizes.tsx
- Removed the `fontSize="small"` of the icons used in the [Toggle Button size demo](https://mui.com/components/toggle-button/#size). Doing so, Figma and code will match, which closes https://github.com/mui-org/material-ui/issues/28654.
- This accidentally helps with making this component demos be more consistent/simpler since this was the only instance where the icons didn't render at their default size.
=> [docs] Make the Toggle Button size demo use default icon size

docs/src/modules/components/AppNavDrawer.js, docs/src/modules/components/DiamondSponsors.js
https://deploy-preview-28651--material-ui.netlify.app/getting-started/usage/
I've seen some users, after v5 release, struggling to find v4 documentation. Friends even came to me asking for it. This indicates that the version button on the top left near the logo doesn't have enough affordance. If it had, people would be able to go to the _**/versions**_ page where they would find every version documentation.
In order to facilitate accessing v4 documentation and increase discoverability of older versions in general, here's the proposed design prototype where I'm first using the outlined variant plus and arrow icon to clarify it's a button. Then, I'm actually turning it into a menu with only two options (could be more, no strong opinions) being the first the current lib version and the …
=> [docs] Improve old doc versions discoverability

packages/mui-codemod/README.md, packages/mui-codemod/src/v1.0.0/menu-item-primary-text.js, packages/mui-codemod/src/v1.0.0/menu-item-primary-text.test.js, packages/mui-codemod/src/v1.0.0/menu-item-primary-text.test/actual.js, packages/mui-codemod/src/v1.0.0/menu-item-primary-text.test/expected.js
=> [codemod] Add MenuItem v.1.0.0 transform for primaryText property

packages/mui-material/src/Switch/Switch.js, packages/mui-material/src/Switch/Switch.test.js, test/utils/describeConformance.js
Overrides theme styles applied on input.
Fixes style overrides on checkbox input in SwitchBase.
Closes #28555
=> [Switch] Fix style overrides on input

packages/mui-material/src/InputLabel/InputLabel.js
Revert the condition to correctly apply formControl styles when formControl=true
Fixes https://github.com/mui-org/material-ui/issues/28686
=> [InputLabel] Fix condition for applying `formControl` overrides

docs/pages/_app.js, docs/pages/_document.js, docs/src/modules/components/DemoSandboxed.js
We only need JSS for the demos now since the migration to Emotion is complete. So we might as well move it to the demos. This removes JSS from the bundle of the landing page.
Though now we have one JSS instance per demo so I'm not sure if this works. 
Might need to work on conditionally applying JSS to `MarkdownDocs` if at least one of the demos needs it.
```diff
-├ chunks/pages/_app.e18b17.js                116 kB
+├ chunks/pages/_app.cd857f.js                103 kB
```
master deploy logs: https://app.netlify.com/sites/material-ui/deploys/61544df498787c0008a68275
PR deploy logs: https://app.netlify.com/sites/material-ui/deploys/61548b3b26ce69000ab2341d
=> [docs] Only add JSS to demos

CONTRIBUTING.md
- update ID link to docs with proper heading
- Add links to LICENSE file and repo
---
- Is is okay that some of the links to file are to HEAD of the repo?
=> [docs] Fix various links in CONTRIBUTING

docs/pages/api-docs/tooltip.json, docs/translations/api-docs/tooltip/tooltip.json, packages/mui-material/src/Tooltip/Tooltip.d.ts, packages/mui-material/src/Tooltip/Tooltip.js, packages/mui-material/src/Tooltip/Tooltip.test.js, packages/mui-system/src/createStyled.d.ts
First discussed in https://github.com/mui-org/material-ui/issues/28679#issuecomment-930047738
Adds `components` and `componentProps` props to the Tooltip component.
For slots that were customizable before (Transition, Popper), the old props (`TransitionComponent`, `TransitionProps`, `PopperComponent`, `PopperProps`) take precedence over the new ones.
=> [Tooltip] Allow overriding internal components and their props

docs/src/pages/customization/theming/theming.md
Typo has fixed in theme documentation.
"createdTheme" => "createTheme"
=> [docs] Theme documentation, typo fix

docs/src/pages/components/date-picker/date-picker.md
Changed DayJS to Dayjs in documentation, as there is not DayJS folder in node_modules. On importing as DayJS I am getting a error `'index.js' does not match the corresponding name on disk: '.\node_modules\@mui\lab\AdapterDayJS\AdapterDayjs'.` so based on node_modules structure I changed the import file name to Dayjs and it worked.
=> [docs] AdapterDayJS -> AdapterDayjs

docs/src/pages/components/selects/selects.md
Updated the description to match reality after changes introduced in #26200.
=> [docs] Correct Select's menu placement description

packages/mui-material/src/Button/Button.spec.tsx
Revealed by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56026
=> [test] Fix instances where type tests were only passing due to object being part of ReactNode

docs/pages/x.tsx, docs/src/components/productX/XHero.tsx
Adding the "React" word to the /x page hero and SEO description. This is an iteration after one customer bought MUI X Pro thinking it was actually buying the Design Kits. We weren't mentioning that the /x page as about React components as well so maybe this helps to avoid this same confusion happening again.
Preview: https://deploy-preview-28830--material-ui.netlify.app/x/
=> [website] Add "React" to the /x page hero description

docs/src/pages/getting-started/templates/sign-up/SignUp.js, docs/src/pages/getting-started/templates/sign-up/SignUp.tsx, docs/src/pages/premium-themes/onepirate/SignUp.js, docs/src/pages/premium-themes/onepirate/SignUp.tsx
The standard in HTML for autocomplete attributes for first or last names is to use `given-name` or `family-name`, respectively. By having examples which use incorrect standards, many developers will simply use these incorrect attributes. This pull request updates the `SignUp` examples in MUI to use the proper attributes for HTML autocomplete according to the following standards:
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete
> "name"
The field expects the value to be a person's full name. Using "name" rather than breaking the name down into its components is generally preferred because it avoids dealing with the wide diversity of human names and how they are structured; however, you can use the following autocomplete values if you do need to break the name down …
=> [docs] Use HTML standards for autocomplete attributes

packages/mui-codemod/src/v5.0.0/optimal-imports.js
Open as draft to discuss about this change. I can reproduce with `@material-ui/core` latest(4.12.3) that codemod cannot transform `import blueGrey from "@material-ui/core/colors/blueGrey";`
Got the same error as in #28542 
```
ERR /Users/siriwatknp/practice-repos/mui-colors-codemod/src/App.js Transformation error (Cannot find module '@material-ui/core/modern/colors' Require stack: - /Users/siriwatknp/Personal-Repos/material-ui/packages/mui-codemod/src/v5.0.0/optimal-imports.js - /Users/siriwatknp/Personal-Repos/material-ui/packages/mui-codemod/src/v5.0.0/preset-safe.js - /Users/siriwatknp/Personal-Repos/material-ui/node_modules/jscodeshift/src/Worker.js)
Error: Cannot find module '@material-ui/core/modern/colors'
```
but by using `/es/` folder, it works. @mnajdova what is the reason to …
=> [codemod] Fix `optimal-imports` to support v4 and v5-alpha, beta

docs/src/pages/components/dialogs/CustomizedDialogs.js, docs/src/pages/components/dialogs/CustomizedDialogs.tsx
=> [docs] Fix typo in Mui CSS classname

docs/src/components/home/DiamondSponsors.tsx
Since all 3 spots for diamond sponsors are filled, we can disable the "Become a sponsor" box on landing page.
Request: https://github.com/mui-org/material-ui/pull/28737#issuecomment-933188757
=> [website] Hide 'become a diamond sponsor' box on landing page

package.json, scripts/README.md
This will help us not to manually update the version with `^` when doing release. @michaldudak please try it out in this release and see if there is any error with this change.
=> [core] Remove `--exact` from `release:version`

packages/mui-styled-engine-sc/src/styled.test.js
=> [test] Add a test for not allowing styled-components' APIs on mui `styled` function

packages/mui-material/src/Tooltip/Tooltip.d.ts
Addresses point 4 from https://github.com/mui-org/material-ui/pull/29023#issuecomment-948425123
Before: https://codesandbox.io/s/popperprops-issue-o0wkg?file=/src/App.tsx
After: https://codesandbox.io/s/popperprops-issue-sru1s?file=/src/App.tsx
=> [Tooltip] `open` prop in `componentsProps.popper` can be optional

docs/pages/about.tsx
Preview: https://deploy-preview-29314--material-ui.netlify.app/about/
=> [docs] Fix about page flags

docs/src/modules/components/AppLayoutDocs.js, docs/src/modules/components/AppTableOfContents.js
Since #29204, it's no longer possible to reach this highlight state by scrolling;
https://master--material-ui.netlify.app/components/autocomplete/#customized-hook
~This reverts commit 6b12d46a24dad402178f2152708c0c965f5042bb, to fix the regression it introduces. I propose we either ignore the case (we don't use the React streaming feature, and we might never do) or have a deeper look into how to fix the issue.~
=> [docs] Fix TOC highlighting logic

docs/public/_redirects
This is outdated. I believe we should be able to always ask to provide a reproduction using https://mui.com/r/issue-template, without maintainers having to care about what's the underlying codesandbox used. No, it should no point to a codesandbox using next.
=> [core] Fix issue template redirection

docs/pages/_app.js, docs/src/modules/components/AppLayoutDocsFooter.js, docs/src/modules/components/DemoSandboxed.js, docs/src/modules/components/ThemeContext.js, docs/src/modules/components/bootstrap.js, test/utils/setup.js
This is a continuation of #24122. It's the encouraged path in https://github.com/vercel/next.js/pull/7651.
=> [docs] Remove usage of `process.browser`

packages/mui-codemod/package.json, packages/mui-core/package.json, packages/mui-icons-material/package.json, packages/mui-lab/package.json, packages/mui-material-next/package.json, packages/mui-material/package.json, packages/mui-private-theming/package.json, packages/mui-styled-engine-sc/package.json, packages/mui-styled-engine/package.json, packages/mui-styles/package.json, packages/mui-system/package.json, packages/mui-types/package.json, packages/mui-utils/package.json
React and its ecosystem uses "react" a keyboard for its packages, e.g. https://unpkg.com/prop-types@15.7.2/package.json. 
In this PR, I have 1. replaced "material-ui" with "mui", and 2. added "material-ui" where it's relevant as a synonymous of "Material Design".
What's the use case? Here is one https://unpkg.com/browse/@mui/material@5.0.4/package.json, https://xpvrpr7r4o.codesandbox.io/: to make it easier for developers to find packages that are compatible with our ecosystem.
=> [core] Add mui as a npm keyword

docs/src/modules/components/AppContainer.js
Since #24531, we use the ch unit for setting the max-width of the container, but the ch px value depends on the font family used. The font family is not stable. IBM Plex is loaded with `font-display:swap`, which is a very short block period, not long enough:
For instance, when loading https://mui.com/components/alert/, you can observe the following:
It was driving me nuts.
In this PR:
1. I have made the layout stable, by forcing the font family. I believe we still get the main benefit: width changing with the default font size.
2. I have increased the max-width in the default configuration by +30px as @mui-org/x was complaining about not having enough space in the demo. This is still -50px less compared to the docs layout of v4.
Preview: …
=> [docs] Fix layout-shift on id='main-content'

docs/src/modules/components/AppTableOfContents.js
I have first noticed the issue on X: https://deploy-preview-3006--material-ui-x.netlify.app/components/data-grid/editing/#server-side-validation with @m4theushw's PR. But it can also be reproduced on the Core. As you scroll, the font weight of the highlighted item increases, making it sometimes wrap, and shifting the rest of the table of content.
https://mui.com/components/links/#security
Compare with how it feels smoother on https://stripe.com/docs/terminal/overview. I went on reproducing the same behavior: no change of font-weight. I believe there is already enough contrast, more is taking the risk to catch the attention of the user away from what matters: the body of the page.
Preview: https://deploy-preview-29436--material-ui.netlify.app/components/links/
=> [docs] Fix layout shift when scrolling

packages/mui-material/src/Select/Select.test.js, test/utils/createClientRender.tsx
Every usage can be replaced with `screen`. One less API to know about.
=> [test] Remove render#baseElement

docs/src/pages/customization/color/color.md, docs/src/pages/customization/theming/theming.md, docs/src/pages/discover-more/related-projects/related-projects.md
The create-mui-theme project is no longer maintained. The service hasn't been functional since at least May 2020. This PR removes the 3 references in the MUI docs to the project.
=> [docs] Remove create-mui-theme no longer working

packages/mui-material/src/ButtonGroup/ButtonGroup.js
Fixes #29219 
The border-color style is applied in the `Button` component and we don't need to have it in `ButtonGroup`. Since the hovering behaviour is such that it is not on the _complete_ ButtonGroup but instead on individual buttons within button group.
Since in `ButtonGroup` the `border-right-color` and `border-bottom-color` for `horizontal` and `vertical` orientation respectively is `transparent`, while hovering we take the current color value. 
I think this is a regression from `v5.0.0-alpha.25 ` from PR #24775.
In v4, we had border color styles while hovering on both `ButtonGroup` and `Button` but the `Button `ones had high specificity. In v5, with the new styling solution, the `grouped`  selector within `root` (`$ .grouped`) in `ButtonGroup` got the high specificity. But anyway I …
=> [ButtonGroup] Fix variant outlined always has primary color borders on hover

docs/pages/_app.js, docs/pages/_document.js, docs/src/components/header/ThemeModeToggle.tsx, docs/src/layouts/AppHeader.tsx, docs/src/modules/components/AppSettingsDrawer.js, docs/src/modules/components/GoogleAnalytics.js, docs/src/modules/components/ThemeContext.js, docs/src/modules/utils/codeVariant.js, docs/src/pages/customization/typography/typography.md
The main objective of this PR is to add the last two Google Analytics custom dimensions:
[source of the screneshot](https://analytics.google.com/analytics/web/#/a106598593w159022482p160376982/admin/custom-dimensions/m-content-dimensionsContent.rowShow=10&m-content-dimensionsContent.rowStart=0&m-content-dimensionsContent.sortColumnId=index&m-content-dimensionsContent.sortDescending=false&m-content.mode=LIST)
- `colorSchemeOS`: The color scheme used by the OS of the developer. 
- `colorScheme`: The color scheme used on the documentation.
Maintainers will be able to access the data the same way we have an example of [the pixel density](https://www.notion.so/mui-org/Analytics-f2e2576203564e6c8dc3429cf305a36f).
Why work on this? I have seen a growing trend toward dark mode, but I have no idea …
=> [docs] Track usage of dark mode in Google Analytics

packages/mui-material/src/ListItem/ListItem.d.ts, packages/mui-material/src/ListItemButton/ListItemButton.d.ts
This PR exports `ListItemBaseProps` and `ListItemButtonBaseProps` to fix a TS4023 error.
Fixes #29291
=> [ListItem] Add missing exports

packages/mui-material/src/InputBase/InputBase.js
On Safari for iOS 15.1, the appearance of text fields has a background color which is being shown on the search input type. This removes the appearance from the base styles so it no longer attempts to display a background.
Closes #29365
=> [InputBase] Remove WebkitAppearance from search type

.gitignore, docs/pages/playground.example.tsx
This is a continuation of https://github.com/mui-org/material-ui-x/pull/3057. I have been using the following workflow for as long as I can remember since we have the Next.js documentation (for 3 years?):
1. There is a change I want to try
2. Got to `/docs/pages/index.tsx`, copy and paste the component I need to work on
3. Try changes
Since then, I haven't found anything better. For instance, editing demos in the documentation was feeling slower. However, this approach has one important downside, I had to make sure I wasn't committing `/docs/pages/index.tsx`. This was painful.
This PR is about improving this and sharing the pattern with this possible workflow with the rest of the team. Now, we can copy the `/docs/pages/playground.example.tsx` file into `/docs/pages/playground.tsx` and …
=> [core] Add playground

packages/mui-lab/src/Masonry/Masonry.js, packages/mui-lab/src/Masonry/Masonry.test.js, test/regressions/fixtures/Masonry/EmptyMasonry.js
Closes https://github.com/mui-org/material-ui/issues/29362
Closes https://github.com/mui-org/material-ui/issues/29446
Problem:
- `Uncaught TypeError: Cannot read properties of null (reading 'clientWidth') at ResizeObserver.handleResize`
- [code sandbox](https://codesandbox.io/s/basicmasonry-material-demo-forked-dgbyn)
Solution:
- Make the following change at the start of `handleResize()` in order to prevent `Cannot read properties of null` error.
```diff
diff --git a/packages/mui-lab/src/Masonry/Masonry.js b/packages/mui-lab/src/Masonry/Masonry.js
index 73bc1e166d..e127668cd7 100644
--- a/packages/mui-lab/src/Masonry/Masonry.js
+++ b/packages/mui-lab/src/Masonry/Masonry.js
@@ -184,6 +184,9 @@ const Masonry = React.forwardRef(function Masonry(inProps, ref) {
React.useEffect(() => {
const …
```
=> [Masonry] Check if container or child exists to prevent error

packages/mui-lab/src/CalendarPicker/CalendarPicker.test.tsx, packages/mui-lab/src/ClockPicker/ClockPicker.test.tsx, packages/mui-lab/src/DatePicker/DatePicker.test.tsx, packages/mui-lab/src/DateRangePicker/DateRangePicker.test.tsx, packages/mui-lab/src/DateRangePickerDay/DateRangePickerDay.test.tsx, packages/mui-lab/src/DateTimePicker/DateTimePicker.test.tsx, packages/mui-lab/src/DesktopDatePicker/DesktopDatePicker.test.tsx, packages/mui-lab/src/DesktopDatePicker/DesktopDatePickerKeyboard.test.tsx, packages/mui-lab/src/DesktopDatePicker/DesktopDatePickerLocalization.test.tsx, packages/mui-lab/src/DesktopDateRangePicker/DesktopDateRangePicker.test.tsx, packages/mui-lab/src/DesktopDateTimePicker/DesktopDateTimePicker.test.tsx, packages/mui-lab/src/DesktopTimePicker/DesktopTimePicker.test.tsx, packages/mui-lab/src/MobileDatePicker/MobileDatePicker.test.tsx, packages/mui-lab/src/MobileDatePicker/MobileDatePickerLocalization.test.tsx, packages/mui-lab/src/MobileDateRangePicker/MobileDateRangePicker.test.tsx, packages/mui-lab/src/MobileDateTimePicker/MobileDateTimePicker.test.tsx, packages/mui-lab/src/MobileTimePicker/MobileTimePicker.test.tsx, packages/mui-lab/src/MonthPicker/MonthPicker.test.tsx, packages/mui-lab/src/PickersDay/PickersDay.test.tsx, packages/mui-lab/src/StaticDatePicker/StaticDatePicker.test.tsx, packages/mui-lab/src/StaticDatePicker/StaticDatePickerKeyboard.test.tsx, packages/mui-lab/src/StaticDateRangePicker/StaticDateRangePicker.test.tsx, packages/mui-lab/src/StaticDateTimePicker/StaticDateTimePicker.test.tsx, packages/mui-lab/src/YearPicker/YearPicker.test.tsx, packages/mui-lab/src/internal/pickers/test-utils.tsx, test/utils/createRenderer.tsx
Applies the changes of `createClientRender` to `createPickerRender`.
=> [test] createPickerRender -> createPickerRenderer

docs/src/components/header/HeaderNavBar.tsx, docs/src/components/header/HeaderNavDropdown.tsx, docs/src/components/home/ProductsSwitcher.tsx, docs/src/components/productDesignKit/DesignKitHero.tsx, docs/src/layouts/AppFooter.tsx, docs/src/pages/discover-more/roadmap/roadmap.md
This [roadmap](https://github.com/mui-org/mui-design-kits/projects/1) is owned by @adrianmanea.
https://deploy-preview-29433--material-ui.netlify.app/discover-more/roadmap/#quarterly-roadmap
=> [docs] Link to the new public roadmap for the design kits

docs/src/pages/discover-more/related-projects/related-projects.md, docs/src/pages/getting-started/installation/installation.md
I was talking with UXPin, they allow designers to prototype with our React components directly in a design editor. @jackbehar please review the wording if it's OK with you.
@mbrookes I have removed framer as it links to https://www.framer.com/templates/material-ui/ now, which I believe doesn't really make sense. No Material Design is not called Material UI, and no, while we try to match Material Design, there are design inconsistencies, design judgment calls we had to make to resolve them.
Framer seems to be working on https://framer.canny.io/feature-requests/p/use-public-npm-packages while encouraging their own UI components:
https://www.framer.com/components/?packages
Preview: https://deploy-preview-29422--material-ui.netlify.app/discover-more/related-projects/#design-resources
=> [docs] Link UXPin integration

docs/pages/api-docs/select.json, docs/translations/api-docs/select/select.json, packages/mui-material/src/Select/Select.js, packages/mui-material/src/Select/selectClasses.ts
Closes https://github.com/mui-org/material-ui/issues/29342
Closes https://github.com/mui-org/material-ui/pull/29384
`Select` component is implemented as a custom input of `Input` component. However, this is not clear in code and in docs API. 
e.g.,
Due to the lack of clarity, some developers expect such theme to take effect:
```javascript
components: {
MuiSelect: {
styleOverrides: {
root: {
background: "red"
}
}
}
}
});
```
Before:
- [codesandbox](https://codesandbox.io/s/lingering-violet-7rixw)
- if you inspect `Select` component, you will see `MuiSelect-root` in classname.
After:
- [codesandbox](https://codesandbox.io/s/quiet-microservice-td4lx?file=/package.json)
- if you inspect `Select` component, you won't see `MuiSelect-root` in classname.
=> [Select] Make it clear that `Select` is not a root component

.github/workflows/support.yml
Follow up on https://github.com/mui-org/material-ui/pull/29594 (@oliviertassinari it's not one commit after all :\)
When working on the same on the X team I noticed that the new lines are not working. The PR should fix this issue.
Previously:
Now:
=> [core] Improve support request message

azure-pipelines.yml, docs/public/_redirects, scripts/sizeSnapshot/loadComparison.js
s3 bucket was previously owned by me. Created a new bucket under our org. Copied all existing objects via `aws --profile Administrator s3 cp s3://eps1lon-material-ui/ s3://mui-org-material-ui/ --recursive --acl bucket-owner-full-control`
Pushed to upstream so that I get full coverage of the azure pipeline. 
Same as https://github.com/mui-org/material-ui/pull/29608 but from upstream to test behavior on `master`
=> [core] Move s3 bucket ownership to mui-org

docs/src/modules/components/AppFrame.js, docs/src/modules/components/AppSearch.js, docs/src/modules/components/Link.tsx, docs/src/modules/components/MarkdownLinks.js, docs/src/pages/discover-more/languages/Languages.js
Closes https://github.com/mui-org/material-ui/issues/29332
Closes https://github.com/mui-org/material-ui/issues/29461
Problem:
- When user is using a language other than English, links in Algolia search contain the language snippet (zh or pt). This results in repetition of the language snippet in url; e.g., `https://mui.com/zh/zh/components/buttons/#main-content`
- This is because `mui.com` already changes to `mui.com/${language}` if language other than English is set.
- To reproduce, follow these steps:
(1) Go to https://mui.com/getting-started/usage/
(2) Change language setting to Portuguese
(3) Open algolia searchbox and enter "mig"
(4) Click the first link
(4) You will be directed to `https://mui.com/pt/pt/guides/migration-v4/#main-content`
Solution:
- When user is using language …
=> [docs] Do not repeat language snippet in url in Algolia search

packages/mui-material/src/Breadcrumbs/BreadcrumbCollapsed.js, packages/mui-material/src/Divider/Divider.js
Replace decimal values passed to `theme.spacing()` with integers
* use combination of `theme.spacing()` and css `calc()` arithmetic to obtain final value
* components affected: `BreadcrumbCollapsed`, `DividerWrapper` 
* close #29479
=> [Breadcrumbs][Divider] Replace decimal spacing values with integers and css calc

docs/next.config.js, docs/pages/experiments/index.js, docs/pages/playgrounds/index.js
Preview: https://deploy-preview-29582--material-ui.netlify.app/experiments/
The purpose of `experiments/*` pages is for us to share ideas with POCs/demos locally and in PR. These experiments will not be deployed to the production site.
Follow up from:
- https://github.com/mui-org/material-ui/pull/29423#issuecomment-957349252
- https://github.com/oliviertassinari/material-ui/pull/18
=> [core] Add `experiments` index page

docs/src/modules/components/AppLayoutDocsFooter.js, docs/src/modules/components/Link.tsx
Two bugs:
1. Open https://mui.com/api/alert-title/#demos
2. Click on
3. See how the URL is wrong https://mui.com/api-docs/alert/
---
1. Open https://mui.com/zh/components/autocomplete/#api
2. Click on 
3. See how the URL is wrong https://mui.com/getting-started/support/
=> [docs] Fix link locale handling

packages/material-ui/src/locale/index.ts
Reverts mui-org/material-ui#29010
@ spitfire, apologies, I didn't spot that your PR targeted v4. There's a newer PR for v5 here: https://github.com/mui-org/material-ui/pull/29507. Feel free to give feedback before it's merged.
=> Revert "add norwegian locale"

packages/mui-material/src/ImageList/ImageList.test.js
This test's title says it is testing the `quilted` variant of the `ImageList` component, but it actually creates a `woven` variant.
This is my first contribution here, so please let me know if there's anything I missed. I hope to contribute more in the future!
=> [ImageList] Verify a quilted variant is created as test title suggests

docs/src/modules/components/ApiPage.js
Fixes #29559 
Some components do not have CSS classes, so not rendering it in the top-right navbar in the API docs. It was not checking for empty array. 
[Preview](https://deploy-preview-29622--material-ui.netlify.app/api/date-picker/#props)
=> [docs] Do not render CSS section in API docs navbar if there are no CSS classes

packages/mui-material/src/Tooltip/Tooltip.test.js
The `requestAnimationFrame` may have been important in earlier implementations for `@popperjs/core`. But now `@popperjs/core` only relies on microtasks for batching state updates.
So let's just flush the state update (wrapped in act). This significantly simplifies the test since we use less helpers and can re-use the same (fake) clock as the other tests in this suite.
React 17 browser run: https://app.circleci.com/pipelines/github/mui-org/material-ui/56264/workflows/8a04eba7-a91c-4dc3-b477-35df19bfe3f5
React 18 browser run (failures are unrelated): https://app.circleci.com/pipelines/github/mui-org/material-ui/56266/workflows/8e18b4b2-0da2-48da-90f2-45c26c85cc2a
=> [test] Correctly identify what the `raf` helper is for

docs/src/modules/brandingTheme.ts
It appears that the theme of the doc pages and the brand pages are different. That cause the dark mode migration to fail on branding pages
Preview: https://deploy-preview-29611--material-ui.netlify.app/
=> [website] Fix dark mode on brand pages

test/cli.js
Enables running more focused tests e.g. `yarn t Autocomplete/Autocomplete.test`. Previously you only had access to `yarn t Autocomplete` which would also run `useAutocomplete.test`.
This also enables custom VSCode tasks for using the integrated debugger via
`.vscode/launch.json`
```json
{
"version": "0.2.0",
"configurations": [
{
"type": "node",
"request": "launch",
"name": "Test Current File",
"program": "test/cli.js",
"args": ["${relativeFile}"],
"console": "integratedTerminal",
"internalConsoleOptions": "neverOpen",
"disableOptimisticBPs": true,
}
]
}
```
=> [test] Allow experimental CLI to run exact test

packages/mui-material/src/Select/SelectInput.js
Include `aria-selected=false` attribute for not selected options. This makes screen readers announce the change of state when an option is selected.
Fixes #26964.
Preview: http://deploy-preview-29695--material-ui.netlify.app/components/selects/#multiple-select
=> [Select] Include aria-selected=false when option not selected

test/cli.js
A follow-up to #29685.
Allows to provide the test path with forward slashes, e.g. `yarn t Autocomplete/Autocomplete.test`.
This enables integrating with VSCode tasks on Windows
```json
{
"version": "0.2.0",
"configurations": [
{
"type": "node",
"request": "launch",
"name": "Test Current File",
"program": "test/cli.js",
"args": ["${relativeFile}"],
"console": "integratedTerminal",
"internalConsoleOptions": "neverOpen",
"disableOptimisticBPs": true,
}
]
}
```
=> [test] Accept backslashes as path separators in test CLI

docs/pages/api-docs/popper.json, packages/mui-material/src/Popper/Popper.test.js, packages/mui-material/src/Popper/Popper.tsx
Simplifies the Popper's prop types as discussed in https://github.com/mui-org/material-ui/pull/29488#discussion_r748200003
=> [Popper] Simplify prop types

packages/mui-base/src/FormControlUnstyled/FormControlUnstyled.tsx
Fixes https://github.com/mui-org/material-ui/issues/29636 with the solution proposed by @hbjORbj
Source of error:
```javascript
@@ -70,7 +70,7 @@ const FormControlUnstyled = React.forwardRef(function FormControlUnstyled<
componentsProps = {},
disabled = false,
error = false,
focused: visuallyFocused = false, <------------ here
onChange,
required = false,
value: incomingValue,
```
Hence, `focused` is always set to `false` unless explicitly set to true as a prop.
```javascript
const focused = visuallyFocused !== undefined && !disabled ? visuallyFocused : focusedState;
```
Fix:
```diff
diff --git a/packages/mui-base/src/FormControlUnstyled/FormControlUnstyled.tsx b/packages/mui-base/src/FormControlUnstyled/FormControlUnstyled.tsx
index 164161c030..593e18c047 100644
--- …
```
=> [FormControlUnstyled] `focused` is always false unless explicitly set to `true`

docs/src/pages/components/tooltips/tooltips.md
Added note about touch event requiring long-press to tooltip trigger documentation, per issue #29716.
Fixes #29716
=> [docs] Update tooltip doc to better define touch action

packages/mui-material/src/styles/createTheme.spec.ts, packages/mui-material/src/styles/createTheme.test.js, packages/mui-material/src/styles/variants.d.ts
The PR fixes the types for the `variants` by changing the `CSSInterpolation` with `Interpolation` which accepts function callbacks. Added tests for types as well as run time behavior.
=> [material] Fix types for `variants.style` to accept callbacks

.circleci/config.yml
Branch is stale. Failures won't be worked on anyway.
=> [test] Disable nightly integration tests on `next` branch

packages/mui-material/src/styles/styled.spec.tsx, packages/mui-styled-engine/src/index.d.ts
Fixes https://github.com/mui-org/material-ui/issues/28844
Explanation: https://github.com/emotion-js/emotion/pull/1664/files#r353487626
=> [styled-engine] Fix props inference in styled-engine

packages/mui-system/src/cssVars/createCssVarsProvider.js, packages/mui-system/src/cssVars/createCssVarsProvider.test.js, packages/mui-system/src/cssVars/getInitColorSchemeScript.test.js, packages/mui-system/src/cssVars/getInitColorSchemeScript.tsx
This PR fixes several issues regarding CSS variables APIs.
**createCssVarsProvider**
- `vars` should be merged (before was using replace) from all color schemes
- add `colorSchemes` to theme for referencing color values
**getInitColorSchemeScript**
- add single quote and fix misuse variables
- add tests
---
=> [system] Fix minor CssVars issues 

packages/mui-lab/src/themeAugmentation/components.d.ts
The `@mui/lab/themeAugmentation` declarations were missing the `MuiDatePicker` and `MuiDateTimePicker` components. This made it not possible to override the props and styles for those components in a custom theme.
It appears these components were at one point part of the declarations file https://github.com/mui-org/material-ui/pull/24092/files but not sure how it was dropped or lost.
=> [DatePicker][TimePicker] Add missing component declarations

packages/mui-lab/src/index.d.ts, packages/mui-lab/src/index.js
Fixes #29705 with the solution proposed by @siriwatknp
When attempting to use Masonry like so:
`import {Masonry} from '@mui/lab';`
the component cannot be found.
By export Masonry in packages/mui-lab/src/index.(js|d.ts)
=> Masonry export in packages/mui-lab/src/index.(js|d.ts)

packages/mui-lab/package.json, yarn.lock
Closes #29580 
Luxon v2 is supported as of `@date-io/luxon@2.11.1` which is ensured due to our `dependencies`.
=> [pickers] Widen accepted `luxon` version range

package.json, yarn.lock
Required until MUI X uses `/base`
=> [core] Ensure `@mui/core` is an alias for `@mui/base`

test/regressions/TestViewer.js
This caused React devtools to sometimes fail element inspection because the backend runs with the same clock as the React component depending on when its hook is injected.
Since we don't actually need to mock a ticking clock and just the current time for stable screenshots of Date, we can reduce the mocked APIs.
Note that this can potentially be confusing since `new Date()` never changes. But neither broken devtools nor unstable screenshots are an alternative so hopefully this works.
=> [test] Only mock Date in regression tests

packages/mui-material/src/useMediaQuery/useMediaQuery.test.js, packages/mui-material/src/useMediaQuery/useMediaQuery.ts
Fixes https://app.circleci.com/pipelines/github/mui-org/material-ui/56494/workflows/3531a490-8a12-4234-a7e6-f07aad6eb414/jobs/317457
While `addListener`/`removeListener` are deprecate, they're required to use in Safari < 14 and IE 11.
Full browser run: https://app.circleci.com/pipelines/github/mui-org/material-ui/56529/workflows/87e04b92-c6ea-4afd-bd11-197d8024ac6b
=> [useMediaQuery] Fix crash in Safari < 14 and IE 11

packages/mui-material-next/src/Tabs/ScrollbarSize.test.js, packages/mui-material-next/src/Tabs/Tabs.test.js
Follow-up to https://github.com/mui-org/material-ui/pull/29684. Some tests written before the introduction of https://github.com/mui-org/material-ui/pull/29684 were not updated.
=> [test] Use renderer clock instead of custom useFakeTimers call

.codesandbox/ci.json
Closes https://github.com/mui-org/material-ui/issues/29707
Was moved when the template was renamed. Unclear why it as renamed and why the change in URL was not considered.
=> [core] Update latest issue template for codesandbox CI

packages/mui-system/src/breakpoints.js, packages/mui-system/src/breakpoints.test.js, packages/mui-system/src/styleFunctionSx/styleFunctionSx.js, packages/mui-system/src/styleFunctionSx/styleFunctionSx.spec.tsx, packages/mui-system/src/styleFunctionSx/styleFunctionSx.test.js
close #29710
`sx` types allow to do this:
```js
<Text sx={{ m: null, transform: null, typography: undefined }} />;
```
But it throws an error. This PR fixes the behavior by neglecting the null or undefined values.
=> [system] Fix `sx` throw error when value is `null` or `undefined`

packages/mui-material/src/IconButton/IconButton.js, packages/mui-material/src/IconButton/IconButton.test.js
Added a check for the `disableRipple` prop before adding the on-hover background color styling.
Addresses #11108
=> [IconButton] remove on hover effect when disableRipple is set

docs/src/pages/guides/localization/localization.md
Included the recently added am-ET locale in the Localization guide as per https://github.com/mui-org/material-ui/pull/29153#issuecomment-975355708
=> [docs] Update the list of supported locales

docs/src/pages/components/toggle-button/toggle-button.md
Exclusive selection for `ToggleButtonGroup` does not enforce value at the moment. Since the most common use scenario for the exclusive selection is using `ToggleButtonGroup` in a similar manner to `RadioGroup` it would be worth noting that `exclusive` flag does not enforce value in documentation for exclusive selection. 
Closes https://github.com/mui-org/material-ui/issues/29784
=> [docs] Add a note that ToggleButton exclusive does not enforce selection

docs/src/modules/components/AppLayoutDocsFooter.js, docs/src/modules/components/AppNavDrawerItem.js, docs/src/modules/components/AppTableOfContents.js, docs/src/modules/components/Link.tsx, docs/src/pages.ts, examples/nextjs-with-styled-components-typescript/src/Link.tsx, examples/nextjs-with-typescript/src/Link.tsx, examples/nextjs/src/Link.js
I still don't quite understand why this was caused, since the changes have been in master for a few days and I've been able to access the MUI docs in the interim (I think, although can't be fully sure since we haven't migrated from 4 to 5 yet), but I guess it's due to the way that you guys do releases?
I also have a feeling that the typing for the props expected to be passed to the `Link` component in `docs/src/modules/components/Link.tsx` are slightly wrong since we should be `Omit`ing the `linkAs` prop as specified in the typing.
Happy to have more of a look at this in the future, but this at least un-blocks the prod website from being completely broken.
Fixes https://github.com/mui-org/material-ui/issues/29704
Fixes #29708
https://deploy-preview-29711--material-ui.netlify.app/api/form-c …
=> [docs] Fix broken Next and Previous links

.gitignore, .vscode/launch.json, test/README.md, test/cli.js
Couldn't find comprehensive ressources for node debuggers. https://nodejs.org/en/docs/guides/debugging-getting-started/ and https://developer.chrome.com/docs/devtools/javascript/ combined hopefully explain what you can do.
In the context of React and frontend development the debugger starts to shine once you need to track async callstacks.
For example, with just `console.log` it's not trivial to find what scheduled a timeout (since it's not only the setTimeout you need to find but also what scheduled this specific effect (`useEffect`). "missing act" warnings are a breeze to debug with [async stack traces](https://thecodebarbarian.com/async-stack-traces-in-node-js-12).
=> [test] Allow debugging with Chrome and VSCode inspector

docs/pages/about.tsx
A small detail, but that has annoyed me for some time when loading the page:
**Before**
https://user-images.githubusercontent.com/3165635/143063485-d553072c-7a2b-4fb6-9d3d-cf72a51dcc30.mp4
**After**
https://user-images.githubusercontent.com/3165635/143063137-5469f350-1c6e-48c2-9173-dff0bfd66660.mp4
=> [docs] Smoother image loading UX

packages/mui-material/src/Select/Select.test.js, packages/mui-material/src/Select/SelectInput.js
Closes https://github.com/mui-org/material-ui/issues/29832
React Nodes are preserved in an array instead of being converted into string (to avoid printing [object Object] when MenuItem contains React Nodes)
=> [SelectInput] `multiple` does not handle React node properly (instead prints [object Object])

docs/notifications.json
Notify the community about the 2021 developer survey: https://mui-org.typeform.com/2021-dev-survey
See https://github.com/mui-org/material-ui/commit/c776d34ffdf79dc9eadcb3a37c6e630b4d92707f#diff-3622d991f50bb01649e3d614784bdbb7e4954fbdc9bb92c73e7f73920cb1b495 for the prior art in 2020.
=> [docs] MUI's 2021 Developer survey

packages/mui-material/src/Autocomplete/Autocomplete.test.js, packages/mui-material/src/RadioGroup/RadioGroup.test.js, packages/mui-material/src/useMediaQuery/useMediaQuery.test.js, packages/mui-material/src/useMediaQuery/useMediaQuery.ts, packages/mui-utils/src/useId.test.js, packages/mui-utils/src/useId.ts, scripts/use-react-dist-tag.js
Closes https://github.com/mui-org/material-ui/issues/29860
These new APIs aren't required for usage with React 18. The either fix some very rare bugs (tearing in `useMediaQuery`) or improve existing behavior (`useId` on the server).
However, in the meantime they disrupt usage with stable React releases which is not ok. Though until React 18 is stable, we need a workaround for https://github.com/webpack/webpack/issues/14814.
A separate `/compat` entrypoint like `react-redux` will require a lot of work from our and consumer side so I don't think this'll be viable.
Ideally we'd just put this behind a feature flag instead of reverting but we don't have any infra for that.
=> [useMediaQuery][utils] Remove usage of React 18 APIs

packages/mui-system/src/cssVars/createCssVarsProvider.d.ts, packages/mui-system/src/cssVars/createCssVarsProvider.js, packages/mui-system/src/cssVars/createCssVarsProvider.test.js
Part of https://github.com/mui-org/material-ui/issues/27651
- Support for `enableColorScheme` in `createCssVarsProvider` (when true, we indicate to the browser which `color-scheme` to use when rendering built-in UI)
- Set `color-scheme` property to `body` with correct `mode` value (light or dark) inside `createCssVarsProvider`
=> [system] Add support for `enableColorScheme` in `createCssVarsProvider`

packages/mui-system/src/cssVars/createCssVarsProvider.d.ts, packages/mui-system/src/cssVars/createCssVarsProvider.js, packages/mui-system/src/cssVars/createCssVarsProvider.test.js
Part of https://github.com/mui-org/material-ui/issues/27651
- Support for `disableTransitionOnChange` in `createCssVarsProvider` (when true, we disable all css transitions momentarily when switching between modes; this allows the switch to be smooth; ref: https://paco.me/writing/disable-theme-transitions)
=> [system] Add support for `disableTransitionOnChange` in `createCssVarsProvider`

.circleci/config.yml
Another attempt at https://github.com/mui-org/material-ui/pull/29879
I tested both true and false in https://github.com/mui-org/material-ui/pull/29879 but I didn't actually check which branch was hit in the PR run so let's focus now.
- FAIL With 8fbae13cf351ebe899011d1720b015c84c949d83 mui-material.tgz should be uploaded on PRs but not size-snapshot.json: https://app.circleci.com/pipelines/github/mui-org/material-ui/57086/workflows/5c032d03-80ff-4683-9369-27b5b18a63e5/jobs/320317
- PASS: With 55edd01f57053d3558b8a397d114700c5930d72d mui-material.tgz should be uploaded on PRs but not size-snapshot.json: https://app.circleci.com/pipelines/github/mui-org/material-ui/57088/workflows/93f6f261-0706-4cc4-873c-c914c7049139/jobs/320333
=> [core] Fix PR detection pattern in test_bundle_size_monitor

packages/mui-lab/src/Masonry/Masonry.test.js, packages/mui-system/src/sx/sx.test.js, test/utils/initMatchers.ts
Fixes https://app.circleci.com/pipelines/github/mui-org/material-ui/57061/workflows/607c4168-b6ad-4152-9806-5a03a9a6bfb8/jobs/320116
Browser run: https://app.circleci.com/pipelines/github/mui-org/material-ui/57084/workflows/57e049e7-1ecf-46f4-9249-f8f516995609
Since these types of failures are easy to make and frequent, we just reject shorthand properties outright.
Example failure (notice the link to constituent properties making it easier to find what you should write instead):
```bash
Chrome Headless 97.0.4666.0 (Linux x86_64) sx system resolves system when used inside styled() FAILED
Error: Shorthand properties are not supported in computed styles matchers since browser can compute them differently. Use longhand properties instead for the follow shorthand properties:
- …
```
=> [test] Reject shorthand properties in style matchers

docs/src/modules/components/Link.tsx, examples/nextjs-with-styled-components-typescript/src/Link.tsx, examples/nextjs-with-typescript/src/Link.tsx, examples/nextjs/src/Link.js
While I was checking out the examples for setting up MUI in Next.js project I've found that the urls to next/link are outdated (since the version 8 of Next.js I believe)
=> [docs] Fix outdated link to next/link docs

packages/mui-system/src/cssVars/createCssVarsProvider.test.js
Note that [`color-scheme` is not supported](https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme#browser_compatibility) by the Firefox version we currently support. Adjusted tests accordingly.
Browser run:  https://app.circleci.com/pipelines/github/mui-org/material-ui/57190/workflows/75d1d968-a742-451a-a703-90d7ea6bd1f7
=> [test] Fix browser tests

packages/mui-material/src/List/List.d.ts, packages/mui-material/src/MenuList/MenuList.d.ts, packages/mui-material/src/MenuList/MenuList.js, packages/mui-material/src/MenuList/MenuList.spec.tsx
Adding a new prop named `component` for the MenuList component. The underlying component List already accepts this prop.
Closes https://github.com/mui-org/material-ui/issues/29628
Before:
- code sandbox: https://codesandbox.io/s/unruffled-shamir-o6323?file=/src/Demo.tsx
After:
- code sandbox: https://codesandbox.io/s/cocky-cdn-z0b5r?file=/src/Demo.tsx
=> [MenuList] Add component prop

docs/pages/_document.js
I broke this in #29623. It got caught by ahrefs:
`view-source:https://master--material-ui.netlify.app/`
```html
<link rel="canonical" href="https://mui.comundefined"/>
```
I have deployed a hot-fix in production.
=> [website] Fix canonical links

docs/src/modules/components/DemoToolbar.js
In #27184, we have introduced a regression, we started to apply a z-index on the toolbar buttons, instead of the tooltip's popper. To reproduce the issue, you can do one of these three, same root cause:
1. https://mui.com/components/autocomplete/#customized-hook. See the icon above the autocomplete's popup (this is initially what got me to look into what was wrong):
2. https://mui.com/components/autocomplete/#customized-hook. See the tooltip above the header:
3. https://mui.com/components/autocomplete/#customized-hook. See the rogue z-index:
This reminds me a bit of #28679. It could be interesting to move this file to TypeScript in the future, to see if our typings are working.
=> [docs] Apply the z-index on the right DOM element

examples/cdn/README.md, examples/cdn/index.html, examples/create-react-app-with-styled-components-typescript/src/App.tsx, examples/create-react-app-with-styled-components/src/App.js, examples/create-react-app-with-typescript/src/App.tsx, examples/create-react-app/src/App.js, examples/gatsby/src/pages/about.js, examples/gatsby/src/pages/index.js, examples/nextjs-with-styled-components-typescript/pages/about.tsx, examples/nextjs-with-styled-components-typescript/pages/index.tsx, examples/nextjs-with-typescript/pages/about.tsx, examples/nextjs-with-typescript/pages/index.tsx, examples/nextjs/pages/about.js, examples/nextjs/pages/index.js, examples/preact/src/App.js, examples/ssr/App.js, examples/ssr/README.md
I believe that people could read "Create React App v5 example" as CRA is on v5, while we mean MUI. Also, as you can see, we forgot to update one of the examples, it was on "Next.js v5-beta with TypeScript example". So, I propose we remove the mention of the version in the headers, people can check what's installed on the yarn/npm lock or the version https://github.com/mui-org/material-ui/blob/4241561c4b81dfca750ff3fb9c3e74097a8334f9/examples/nextjs/package.json#L3
=> [docs] Fix v5-beta confusing example description

packages/mui-system/src/cssVars/createCssVarsProvider.js, packages/mui-system/src/cssVars/createCssVarsProvider.test.js
Follow-up to https://github.com/mui-org/material-ui/pull/29929#discussion_r758171571
I adjusted the test descriptions since it sounded like the `body` element would be affected. However, [`document.documentElement`](https://developer.mozilla.org/en-US/docs/Web/API/Document/documentElement)  points to `<html>` not `<body>` (that would be [`docoument.body`](https://developer.mozilla.org/en-US/docs/Web/API/Document/body))
Browser run: https://app.circleci.com/pipelines/github/mui-org/material-ui/57238/workflows/f8e8f5bb-04d8-4db2-990e-f7c0d7a2b75a
=> [system] CSSVarsProvider cleans up `html[style]` when unmounting

docs/notifications.json
To be merged around 2021-11-29T21:00Z.
It might be useful to have start and end dates on notifications in the future.
=> [docs] Remove Black Friday sale notification

docs/src/pages/getting-started/support/support.md
This document has a contradictory statement in "StackOverflow is also frequented, from time to time, by the maintainers of MUI."  Something can only be "frequented" if it is visited frequently.  By contrast, "from time to time" implies the visits are only occasional, not frequent, and perhaps closer to seldom.  I'm assuming the intent was to suggest MUI maintainers only occasionally visit, so I propose "visited" in place of "frequented," but if the truth is that MUI maintainers frequently visit, then perhaps just drop the "from time to time" altogether instead.
=> [docs] Improve wording in StackOverflow section of support page

docs/src/pages/system/basics/basics.md
Benchmarks folder initially pointed to a non-existent branch "next" that redirected to "foo". This change now redirects to the master branch.
=> [docs] Fix benchmarks folder link

packages/mui-material/src/styles/cssUtils.d.ts, packages/mui-material/src/styles/index.d.ts
=> [utils] Add typings for `@mui-material/styles/cssUtils`

docs/pages/api-docs/slider-unstyled.json, docs/pages/api-docs/slider.json, docs/pages/api-docs/step-connector.json, docs/pages/api-docs/step-icon.json, docs/pages/api-docs/step-label.json, docs/pages/api-docs/step.json, docs/pages/api-docs/table-sort-label.json, docs/scripts/buildApi.ts, packages/mui-styles/src/createGenerateClassName/createGenerateClassName.js
The API docs generator did not treat `active` and `completed` as global state classes. It resulted in API docs for several components being invalid. This PR adds the missing classes and updates all the affected API pages.
Fixes #29825.
=> [docs] Add missing global state classes to API docs generator

packages/mui-material/src/Accordion/Accordion.test.js
[Accordion.test.js](https://github.com/mui-org/material-ui/blob/master/packages/mui-material/src/Accordion/Accordion.test.js) was missing a test to verify the functionality of the `square` prop
=> [Accordion] Add a test for handling `square` prop

docs/src/pages/components/paper/paper.md
Added a brief explanation about both background-color and background-image being used by Paper in dark mode.
Closes #29134.
=> [docs] Explain how Paper changes shade in dark mode

packages/mui-lab/src/DateRangePickerDay/DateRangePickerDay.tsx, packages/mui-lab/src/themeAugmentation/props.d.ts
Fix for #28373.
Problem:
- npm build with tsc fails with a typescript throw
Solution:
- Follow the existing pattern of other lab components (`MuiDatePicker`, `MuiDateTimePicker`, etc…) of providing `unknown` as a default value for `TDate`.
=> [DateRangePicker] Fix `DateRangePickerDayProps` interface

README.md, docs/pages/about.tsx, docs/src/layouts/AppFooter.tsx, docs/src/pages/getting-started/faq/faq-pt.md, docs/src/pages/getting-started/faq/faq-zh.md, docs/src/pages/getting-started/faq/faq.md, docs/src/pages/getting-started/support/support-pt.md, docs/src/pages/getting-started/support/support-zh.md, docs/src/pages/getting-started/support/support.md
*mui* is managed as a synonym of *material-ui* on StackOverflow: https://stackoverflow.com/tags/material-ui/synonyms. I propose we consolidate everything under mui. In the future, if we need to distinguish between different products then I think we could have sub-labels. For instance, Angular has:
- [angular](https://stackoverflow.com/questions/tagged/angular)
- [angular-material](https://stackoverflow.com/questions/tagged/angular-material)
- [angular-cdk](https://stackoverflow.com/questions/tagged/angular-cdk)
We could have `mui-base`, `mui-joy`, `mui-material`, `mui-studio`, `mui-x` in the future. We had a chat with Ryan about it on https://github.com/mui-org/material-ui-x/pull/2676#discussion_r716739659.
This PR is part of #27825.
=> [core] Transition to a new StackOverflow tag

docs/src/pages/guides/typescript/typescript.md
Fix broken link on https://mui.com/guides/typescript/ from [this](https://github.com/mui-org/material-ui/tree/foo/examples/create-react-app-with-typescript) to [this](https://github.com/mui-org/material-ui/tree/master/examples/create-react-app-with-typescript).
Closes #30019
=>  [docs] Fix link in TypeScript doc page

docs/pages/api-docs/stack.json, docs/scripts/buildApi.ts
This PR add documentation about system props to [Stack API docs](https://mui.com/api/stack/) just like in [Typography API docs](https://mui.com/api/typography/)
> As a CSS utility, the Typography component also supports all system properties. You can use them as props directly on the component.
=> [Stack] Document system props in Stack API

docs/src/pages/guides/migration-v4/migration-v4.md
Closes https://github.com/mui-org/material-ui/issues/29757
Add to migration v4 to v5 README on that users have to bump up css specificity in v5.
=> [docs] Add to migration v4 to v5 docs on CSS specificity

docs/pages/careers.tsx
"Material-UI" -> "MUI" renames went too far.
=> [website] Correct the Careers page description

docs/src/pages.ts, docs/translations/translations.json
We released the 1st feature of this page last week so we have to remove this icon :+1:
=> [docs] Remove the 'WIP' icon from the 'Group & Pivot' page title

packages/mui-material/src/Select/Select.test.js, packages/mui-material/src/Select/SelectInput.js
Fixes #29836
📦  https://codesandbox.io/s/mui-issue-latest-forked-4pg71
For the case that an empty list is passed for multiple, a fallback needs to be passed to the reduce.
Otherwise the first element is selected, which is undefined in this case ( empty list ) and it crashes the code.
[References](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Reduce_of_empty_array_with_no_initial_value)
=> [Select] Should not crash when an empty array is passed with `multiple` enabled

docs/src/pages/customization/breakpoints/breakpoints.md, packages/mui-system/src/createTheme/createBreakpoints.d.ts, packages/mui-system/src/createTheme/createBreakpoints.js, packages/mui-system/src/createTheme/createBreakpoints.test.js
Allow to easily create styles, which are the inverted version of the only operator
Updated the documentation and included tests
This change is related to issue #29228
=> [system] Add `not` operator to `breakpoints`

scripts/sizeSnapshot/webpack.config.js
While working on https://github.com/mui-org/material-ui/pull/30080, I noticed this in the build for `yarn size:snapshot`
```
...
Compiling 210-220: "SwitchUnstyled", "TabPanelUnstyled", "TabUnstyled", "TablePaginationUnstyled", "TabsListUnstyled", "TabsUnstyled", "TextareaAutosize", "Unstable_TrapFocus", "@material-ui/utils", "@material-ui/core.legacy"
Compiling 220-230: "undefined", "undefined", "undefined", "undefined", "undefined", "undefined", "undefined", "undefined", "undefined", "undefined"
Done in 231.85s.
CircleCI received exit code 0
```
=> [fix] size:snapshot for mui-material-next and mui-joy components

docs/src/pages/components/backdrop/backdrop.md
Searched for this import but I could not find it:
```js
import Backdrop from '@mui/base/Backdrop';
```
I found this import though, which seems to be correct:
```js
import BackdropUnstyled from '@mui/base/BackdropUnstyled';
```
=> [docs] Fix import example inside Unstyled Backdrop section

docs/src/pages/getting-started/support/support.md
Tackles the problem reported at https://github.com/mui-org/material-ui/issues/29764.
This tip could be generally helpful, not only when in this StackOverflow use-case, so wondering if we should place it somewhere else. Open to suggestions :)
Deploy preview: https://deploy-preview-30101--material-ui.netlify.app/getting-started/support/#stackoverflow
=> [docs] Add tip to help access the docs of a previous version when finding answers in StackOverflow

.circleci/config.yml, scripts/sizeSnapshot/loadComparison.js
We're closing the account under which the bucket was created and ownership of buckets can't be transferred. So we're recreating it.
On the new bucket I'm also using bucket policies to control object access instead of putting object ACL.
will have to update the dashboard as well: https://github.com/mui-org/mui-contributor-dashboard/blob/9010a86de7aee24aabc2dbb0ef421c8f6a267395/src/pages/SizeComparison.tsx#L150
To Do after merging:
=> [ci] Update CI bucket

.circleci/config.yml, scripts/sizeSnapshot/loadComparison.js
Follow up on https://github.com/mui-org/material-ui/pull/30080
The main credentials are updated on cci, the bucket is copied, we can revert to the previous situation but with new bucket configured
=> [fix] Update snapshots and s3 fallback

packages/mui-material/src/styles/createTheme.d.ts
=> [system] Fix discrepancy between core and system `ThemeOptions`

docs/src/pages/discover-more/related-projects/related-projects.md
- Data Driven Forms now fully support MUI5
```
Data Driven Forms converts JSON form definitions into fully functional React forms.
```
based on React Final Form.
=> [docs] Add Data Driven Forms to related projects

packages/mui-material/src/OutlinedInput/OutlinedInput.js, packages/mui-material/src/OutlinedInput/OutlinedInput.test.js, packages/mui-material/src/TextField/TextField.js
Fixes #29206
**Problem:**
- When the required is being set in the Formcontrol component , the border of input touches the end of the label, and it does not add a non-breaking space between border and asterik. Meanwhile, this non-breaking space is being considered when the input is created by Textfield component.
**Solution:**
- Adding `'\u00a0*'` to the OutlinedInput's label when required is set.
=> [TextField] Fix missing space before asterisk in `OutlinedInput`'s label

docs/src/pages/components/selects/selects.md
Added a note to include the label twice when using an outlined Select.
Closes #27533
=> [docs] Explain the use of Select's label in FormControl

packages/mui-material/src/Badge/Badge.test.js
Add tests to `Badge` to verify correct styles are applied for different values of the `anchorOrigin` prop and their interactions with `overlap`.
=> [Badge] Add tests for `anchorOrigin` prop

.github/workflows/ci.yml
check the step `yarn install` in these pipelines
**without cache**
https://github.com/mui-org/material-ui/actions/runs/1581192533
**with cache**
https://github.com/mui-org/material-ui/actions/runs/1581497967
---
=> [core] cache dependencies in github actions

.circleci/config.yml, dangerfile.js
Make sure to return a non-zero exit code when the danger command errors to avoid failures going unnoticed. Like in workflow: https://app.circleci.com/pipelines/github/mui-org/material-ui/59709/workflows/977019ed-7315-4f51-9da7-f0627e17b23f/jobs/327719
=> [fix] Fail the build when the dangerjs script errors

docs/src/pages/guides/migration-v4/migration-v4.md
Closes https://github.com/mui-org/material-ui/issues/27993
=> [docs] Add to migration doc about ref type specificity

package.json, scripts/sizeSnapshot/create.js, scripts/sizeSnapshot/webpack.config.js, scripts/sizeSnapshot/worker.js, yarn.lock
Noticed that the size snapshot script regularly gets OOM killed by the circle ci docker host (e.g. https://app.circleci.com/pipelines/github/mui-org/material-ui/59188/workflows/3a20643a-72d7-4111-b7ad-265ef5b7bf94/jobs/326618). Been testing locally and it's indeed flirting with the 4GB memory limit set for the cci medium instances. I've been investigating and noticed a memory leak with `webpack-bundle-analyzer`. Memory grows with each batch of compilations and doesn't get reclaimed. Removing `webpack-bundle-analyzer` from the webpack configuration keeps the memory stable.
I propose a different way of parallelizing the size calculations by using node.js worker threads. This makes sure memory gets cleaned up for every webpack run so that the script becomes scalable again.  First …
=> Reduce bundle size comparison memory consumption

docs/src/pages/components/backdrop/backdrop.md, docs/src/pages/components/click-away-listener/click-away-listener.md, docs/src/pages/components/no-ssr/no-ssr.md, docs/src/pages/components/portal/portal.md, docs/src/pages/components/textarea-autosize/textarea-autosize.md, docs/src/pages/components/trap-focus/trap-focus.md, docs/src/pages/customization/unstyled-components/unstyled-components.md, packages/mui-base/README.md
Found few remaining references to 'unstyled' and replaced them with Base.
=> [docs] Rename remaining 'unstyled' references to 'base'

packages/mui-material-next/src/Tabs/Tabs.d.ts, packages/mui-material/src/Tabs/Tabs.d.ts, packages/mui-material/src/Tabs/Tabs.spec.tsx
Since the properties of `React.HTMLAttributes` are all optional, Partial utility type is not needed.
=> [Tabs] Remove `Partial<>` type around TabIndicatorProps type

docs/translations/api-docs/loading-button/loading-button.json, packages/mui-lab/src/LoadingButton/LoadingButton.d.ts, packages/mui-lab/src/LoadingButton/LoadingButton.js, packages/mui-lab/src/LoadingButton/LoadingButton.test.js
Pending screen reader testing based on https://codesandbox.io/s/loadingbuttonstransition-material-demo-forked-rf2hm?file=/demo.js: https://codesandbox.io/s/loadingbuttonstransition-material-demo-forked-49ok6
Preview: https://deploy-preview-30002--material-ui.netlify.app/components/buttons/
NVDA currently doesn't announce indeterminate progress bars. But the spec is there so eventually there will be some implementation. We shouldn't make any claims about the progressbar of LoadingButton. For now fixing issues with automated a11y testing tools is reason enough to merge this.
Note that loading buttons that just read "loading..." are problematic to begin with and won't get better with the proposed implementation. The problem with a generic "loading..." is that it's just redundant. We already …
=> [LoadingButton] Label progressbar by the LoadingButton

examples/remix-with-typescript/README.md
After cloning the example project, the project folder is `remix-with-typescript` but the README was mentioning `cd nextjs` for getting to the working folder.
=> Fix typo in remix-with-typescript example README

docs/src/modules/components/MarkdownElement.js
Make sure to coalesce the colors before feeding them into `alpha` for the dark theme.
Fixes https://github.com/mui-org/material-ui/issues/30304
Preview: https://deploy-preview-30319--material-ui.netlify.app/components/material-icons/
=> [docs] Fix Icon Search UI crash

docs/src/modules/components/AppSearch.js, test/e2e-website/material-docs.spec.ts
This PR cover all scenarios when searching with cmd+K (algolia search):
**Before migration**
The feature toggle is not turned on, so the behavior is still the same.
**Migration phase**
When the contents are duplicated to `docs/pages/material/*` and the feature toggle is turned on, all the search results (related to components, API, etc.) are replaced to point to `/material/*` URL.
**Post migration**
The search config on the doc search is updated and the new `/material/*` have been indexed, the URL will not be replaced because of the regex in the code.
✅ E2E website added.
---
=> [docs] Redirect old urls to `/material/*` when search

packages/mui-base/src/InputUnstyled/InputUnstyled.tsx, packages/mui-material-next/src/Button/Button.js
=> [core] Rename missed `Material-UI` text to `MUI` in warning logs

docs/src/pages/customization/breakpoints/breakpoints.md
The #29311 PR forgot to update the number of breakpoint helpers in the docs. The text says four, but they are now five.
=> [docs] Fix incorrect number of breakpoint helpers

docs/src/pages/components/speed-dial/ControlledOpenSpeedDial.js, docs/src/pages/components/speed-dial/ControlledOpenSpeedDial.tsx
The controlled SpeedDial demo has the aria label "uncontrolled" where it should be "controlled".
=> [docs] Fix incorrect aria label in SpeedDial demo

docs/public/_redirects
Fix #30356. With Jan, we moved the S3 to the root AWS account of MUI, we had to create a new bucket.
=> [docs] Fix link to /size-snapshot

docs/src/pages/guides/localization/localization.md, packages/mui-material/src/locale/index.ts
=> [l10n] Add Norwegian Bokmål (nb-NO) locale

docs/src/modules/components/EditPage.js
I fix a regression that happens, I have no idea when. Before when you would click on the "translate docs button":
https://mui.com/zh/components/alert/
it would filter the tree and only display the page you can translate:
Today, as a developer that want to fix a bug in the translation, you have to find the page yourself, it's painful:
=> [docs] Improve the translation experience

docs/src/modules/components/AppLayoutDocsFooter.js, docs/src/pages/components/accordion/accordion.md, docs/src/pages/components/transitions/transitions.md
I have noticed this having a quick look at #30378. When you open WAVE, on any page, say https://mui.com/components/alert/, it will let you know that
the textbox in the rating popup is missing a text label. But why is this rendered in the DOM in the first place?
So, I'm removing it from the DOM with the prop. It should help with performance, only rendering what's needed.
Second, since this is kind of an obscure trick and I saw people asking about it 1-2 years ago on the issue, and that it's still not in the docs, I added it. https://deploy-preview-30382--material-ui.netlify.app/components/transitions/#performance-amp-seo
=> [docs] Document how to unmount transition child

docs/src/pages/components/menus/AccountMenu.js, docs/src/pages/components/menus/AccountMenu.tsx, docs/src/pages/components/menus/BasicMenu.js, docs/src/pages/components/menus/BasicMenu.tsx, docs/src/pages/components/menus/CustomizedMenus.js, docs/src/pages/components/menus/CustomizedMenus.tsx, docs/src/pages/components/menus/FadeMenu.js, docs/src/pages/components/menus/FadeMenu.tsx, docs/src/pages/components/menus/LongMenu.js, docs/src/pages/components/menus/LongMenu.tsx, docs/src/pages/components/menus/PositionedMenu.js, docs/src/pages/components/menus/PositionedMenu.tsx, packages/mui-base/src/AutocompleteUnstyled/useAutocomplete.js
Closes #30125 
Improves the Lighthouse accessibility score from 84 to 94 of this demo.
https://deploy-preview-30378--material-ui.netlify.app/components/menus/
=> [docs] Fix a11y in Menu demos

packages/mui-material/src/ButtonGroup/ButtonGroupContext.ts
Change `disabledElevation` to `disableElevation`
The ButtonGroup and Button components both use `disableElevation` not `disabledElevation`. This fixes that typo.
=> [ButtonGroup] Fix typo in `ButtonGroupContext`'s interface

docs/src/pages/guides/minimizing-bundle-size/minimizing-bundle-size.md
=> [docs] Fix text from `material-ui` to `@mui` to reflect v5 name changes

docs/src/modules/components/AppSearch.js, docs/src/modules/utils/i18n.js, docs/src/modules/utils/replaceMarkdownLinks.test.js, docs/src/modules/utils/replaceMarkdownLinks.ts, docs/src/modules/utils/replaceUrl.test.js, docs/src/modules/utils/replaceUrl.ts
Fixes #30344
I've followed steps in described in `Review suggestion` #30107 to run `test:e2e-website:dev`, but relevant tests kept failing for some reason (even before my changes).
Let me know if there's something missing in the PR.
=> [docs] Fix crash on Safari because of unsupported lookahead feature

docs/src/modules/components/AppTableOfContents.js, docs/src/modules/components/Link.tsx
The issue is I got unexpected error when copy installation page to `docs/pages/material/getting-started/installation` (it should not throw error).
The error occurs in AppTableOfContent because there is no active page. However, it does not make sense that the AppTableOfContent should know about the active page. Instead, it should just read the browser URL (provided by nextjs) and apply a hash to the URL when clicked. 
I feel that this is simpler and easier to maintain, so open this small PR to check that I don't miss anything important.
---
=> [website] Refactor page context with next router

packages/mui-material/src/Badge/Badge.d.ts, packages/mui-material/src/Badge/Badge.spec.tsx
Fixes #30419 
Missed in #30246 that old classes should be marked optional when moved from `badgeUnstyledClasses` to `Badge.d.ts`.
=> [Badge] Fix `classes` prop TypeScript type

packages/mui-material/src/locale/index.ts
Originally, I was planning to only include one option but upon seeing how the change would look in an actual table I came up with two possible solutions since the Finnish language does not have a similar word as "of" in English:
* First (currently in the PR and more line with rest of the languages' style):
* Second (aesthetically more pleasing since at no other positions of the string are words used):
Any comments and/or discussion regarding the topic is welcome.
=> [l10n] Improve fiFI locale

docs/pages/api-docs/svg-icon.json, docs/src/pages/components/icons/icons.md, docs/translations/api-docs/svg-icon/svg-icon.json, packages/mui-material/src/SvgIcon/SvgIcon.d.ts, packages/mui-material/src/SvgIcon/SvgIcon.js, packages/mui-material/src/SvgIcon/SvgIcon.test.js
Fix #18782
Based on [previous PR](https://github.com/mui-org/material-ui/pull/28231) dedicated to that issue, just fixed last unresolved comments and opened my own PR on it.
=> [SvgIcon] Allow viewBox to inherit from Component through inheritViewBox prop

docs/src/pages/components/use-media-query/use-media-query.md
I tried following the example and the `ssrMatchMedia` was never used. I think the current example is still using v4 implementation. I updated it to the new Theme structure of v5.
https://deploy-preview-30454--material-ui.netlify.app/components/use-media-query/#server-side-rendering
=> [docs] Fix `useMediaQuery` SSR example to v5 theme API

docs/src/pages/components/radio-buttons/radio-buttons.md
we should suggest not a generic 'dropdown menu' to the user but rather a Select component, which is the same thing, but in the MUI world (where the user is and most likely wishes to stay)
=> [docs] Make the reference to the select clearer

examples/remix-with-typescript/app/entry.server.tsx, examples/remix-with-typescript/app/root.tsx, examples/remix-with-typescript/app/src/StylesContext.tsx, examples/remix-with-typescript/remix.config.js
Resolves https://github.com/mui-org/material-ui/pull/29952#discussion_r762576860
The goal is to avoid double rendering on the server. It was solved by injecting the emotion style tag after a specific `meta` tag in the head. It is similar to the new `insertionPoint` option recently added in emotion - https://github.com/emotion-js/emotion/pull/2521
I could use some help testing out, to make sure I didn't miss anything.
=> [example] Avoid double rendering in the Remix example

docs/src/pages/components/icons/icons.md, docs/translations/api-docs/svg-icon/svg-icon.json, packages/mui-material/src/SvgIcon/SvgIcon.d.ts, packages/mui-material/src/SvgIcon/SvgIcon.js, packages/mui-material/src/SvgIcon/SvgIcon.test.js
Fix issues reported in https://github.com/mui-org/material-ui/pull/29954#pullrequestreview-842256913
=> [SvgIcon] Correct API docs and code style

docs/src/pages/system/the-sx-prop/the-sx-prop.md
Corrected `trough` with `through` +
I'm not a native English speaking person, so I am not completely sure about the other 2 suggestions. I'm up for improvements or removing them altogether if they don't make sense.
=> [docs] Fix typo and spelling in the-sx-prop.md

docs/src/modules/utils/replaceUrl.test.js, docs/src/modules/utils/replaceUrl.ts
Found this bug while integrating the migration in https://github.com/mui-org/material-ui-x/pull/3515.
- tests added to cover data-grid url
---
=> [docs] fix replace url on data-grid

docs/src/modules/utils/replaceUrl.test.js, docs/src/modules/utils/replaceUrl.ts
🥲 I missed this case (take a look at the test).
**Note**: This is a bug fix when doing the migration. There is no impact on the current version of the docs.
=> [docs] fix edge case when replacing data-grid url for migration

docs/src/pages/guides/migration-v4/migration-v4.md
Hi,  
I got [an issue](https://github.com/garronej/tss-react/issues/49) tonight from a user that was wondering [how to override the `classes` prop](https://v4.mui.com/styles/advanced/#makestyles).  
I wasn't aware of this feature's existence. I implemented [an equivalent for TSS](https://github.com/garronej/tss-react#usemergedclasses).  
This PR is an update of the codemod for migrating from jss to tss.  
Best regard
=> [docs] Codemod doc for overriding styles using tss

docs/src/modules/components/DemoSandboxed.js, docs/src/modules/components/ThemeContext.js, test/e2e-website/material-color-playground.spec.ts, test/e2e-website/playwright.config.ts
🔗 https://deploy-preview-30563--material-ui.netlify.app/customization/color/#playground
close #30343
=> [docs] Fix the crash when applying custom colors

docs/packages/markdown/parseMarkdown.js, docs/packages/markdown/parseMarkdown.test.js, docs/src/pages/customization/theme-components/theme-components.md
On https://mui.com/customization/theme-components/ the page description element (which is `<p class="description">`) contains backticks which are rendered incorrectly (at least compared to how the backticks work for markdown).
Preview:
Looking into understanding why that happens I found out that the `description` is rendered in the head of the page. Looking more into it I found out that the `title` is rendered the same, but the title already was trimming the backtics. So I added trimming of the backtics for the `description` as well.
While this makes sense to me, obviously I cannot grasp the entire set of implications. Easiest thing to do for now, without introducing this change, would be to remove the backticks from description in the mentioned file.
Deploy preview: …
=> [docs] Update markdown parser to remove backticks from description

docs/src/pages/premium-themes/onepirate/modules/components/TextField.js, docs/translations/api-docs/text-field/text-field.json, packages/mui-material/src/InputLabel/InputLabel.js, packages/mui-material/src/TextField/TextField.d.ts, packages/mui-material/src/TextField/TextField.js
Closes #30488
Issue:
- When using `TextField` and its `InputLabelProps` prop, which is passed to `InputLabel` component, event handlers (e.g., `onClick`, `onFocus`) passed to `InputLabelProps` don't work.
- [Code sandbox](https://codesandbox.io/s/formpropstextfields-material-demo-forked-nfoke)
Soluition:
- This is a regression from #13040 that was created to fix [an old issue](https://github.com/mui-org/material-ui/issues/12997).
- Simply removing `pointer-events: none` will fix the current issue.
- With our current implementation, even with the removal of `pointer-events: none`, [the old issue](https://github.com/mui-org/material-ui/issues/12997) no longer appears. [Proof](https://codesandbox.io/s/formpropstextfields-material-demo-forked-4b9vr?file=/demo.tsx)
- [Code …
=> [TextField][InputLabel] Remove `pointer-events: none` property

docs/src/pages/system/typography/TextTransform.js, docs/src/pages/system/typography/TextTransform.tsx, docs/src/pages/system/typography/TextTransform.tsx.preview, docs/src/pages/system/typography/typography.md, packages/mui-system/src/Box/Box.d.ts, packages/mui-system/src/index.d.ts, packages/mui-system/src/typography.js
Fixes #30435
Issue:
- `Typography`, `Grid` and `Box` mentions on their docs that they support "all system properties" and that developers can "use them as props directly on the component."
- However, using `textTransform` directly as a prop throws a typescript error and doesn't work in effect as well
- [code sandbox](https://codesandbox.io/s/cocky-mayer-intql?file=/src/Demo.tsx:371-372)
After:
- [code sandbox](https://codesandbox.io/s/kind-poincare-8kwj7?file=/src/Demo.tsx)
=> [system][Box, Grid, Typography] `textTransform` prop should work directly on component

packages/mui-codemod/package.json, yarn.lock
Close #30565
TL;DR
jscodeshift had `colors` as dependency which contains an intentional DoS. They have replaced with `chalk` in v0.13.1
https://github.com/facebook/jscodeshift/commit/7cf9969c1fed3dcf535aebbc9986c32be9214ffc
=> [codemod] Bump `jscodeshift` to remove `colors` dependency

packages/mui-lab/src/MobileDatePicker/MobileDatePicker.test.tsx, packages/mui-lab/src/internal/pickers/PureDateInput.tsx
Fixes #29310
**Problem**:
- When the `readOnly` prop is true, clicking on the `MobileDatePicker` component opens the date selector
**Solution**
- adding a condition to check whether the `readOnly` is true before calling onOpen function
[demo](https://codesandbox.io/s/responsivedatepickers-material-demo-forked-uxf4m?file=/demo.js)
=> [MobileDatePicker] Fix calling onOpen when readOnly is true

docs/public/_redirects
I noticed this in https://github.com/mui-org/material-ui-x/pull/3530/files#r777226554 which we link in:
https://github.com/mui-org/material-ui/blob/b9117f2ff7fa99d85dd66b5c240dcb32e833a1c9/.github/ISSUE_TEMPLATE/1.bug.yml#L42
**Before**
**After**
=> [core] Fix outdated TypeScript template

packages/mui-styled-engine-sc/src/index.js, packages/mui-styled-engine-sc/src/styled.test.js, packages/mui-system/src/createStyled.js
Part of https://github.com/mui-org/material-ui/pull/29873
The `babel-plugin-styled-components` expects that this option exists on the `styled()` utility.
=> [styled-engine-sc] Add the withConfig API to enable using the babel plugin

docs/src/pages/guides/localization/Locales.js, docs/src/pages/guides/localization/Locales.tsx, docs/src/pages/guides/localization/localization.md
Fix https://github.com/mui-org/material-ui-x/issues/3514
It is not clear that when using the DataGrid component locales must be imported from the DataGrid package.
Also the codesandbox did not work because the following line is using `outerTheme` to know if the documentation is in light or dark mode.
```js
theme={(outerTheme) => createTheme(outerTheme, locales[locale])}
```
But the codeSandbox, does not declareanother them, so `outerTheme` is not defined, leading to a bug.
I removed the demo toolbar because there is an example on top of the demo
=> [docs] Inform about specific files for DataGrid locales

docs/src/pages/guides/migration-v0x/migration-v0x.md, docs/src/pages/guides/migration-v3/migration-v3.md, docs/src/pages/guides/migration-v4/migration-v4.md
fix: migration anchor tag in migration of v4 to v5 documentation.
https://deploy-preview-30595--material-ui.netlify.app/guides/migration-v4/
=> [docs] Fix anchor tag in table of contents of v4->v5 docs

docs/src/pages/components/masonry/MasonryWithVariableHeightItems.js, docs/src/pages/components/masonry/MasonryWithVariableHeightItems.tsx, docs/src/pages/components/masonry/MasonryWithVariableHeightItems.tsx.preview, docs/src/pages/components/masonry/masonry.md, packages/mui-lab/src/Masonry/Masonry.js, packages/mui-lab/src/Masonry/Masonry.test.js
Closes https://github.com/mui-org/material-ui/issues/29692
Closes https://github.com/mui-org/material-ui/issues/30453
Before:
- `ResizeObserver API` was only observing the masonry container and the first child (which we expected will cause issues in the future). As a result, changes in the dimension of children other than the first do not trigger computation (needed for correct layout of masonry). [Code sandbox](https://codesandbox.io/s/masonry-additional-column-error-hri37?file=/demo.tsx)
- Why does observing the container not detect changes in dimensions of children? Because masonry container is set to a fixed height after every computation. As a result, except the first mounting, when masonry container doesn't have a fixed height yet, changes in dimensions of children do not get …
=> [Masonry] Observe every masonry child to trigger computation when needed

crowdin.yml
The migration will move content from `/docs/src/pages/*` to `/docs/data/$product/*`
=> [core] Add new structure to ignore list crowdin

docs/translations/api-docs/autocomplete/autocomplete.json, packages/mui-base/src/AutocompleteUnstyled/useAutocomplete.d.ts, packages/mui-material/src/Autocomplete/Autocomplete.js
Changed the AutoComplete `clearOnBlur` API documentation from 
> If true, the input's text is cleared on blur if no value is selected.Set to true if you want to help the user enter a new value. Set to false if you want to help the user resume **his** search.
to
> If true, the input's text is cleared on blur if no value is selected.Set to true if you want to help the user enter a new value. Set to false if you want to help the user resume **their** search.
The AutoComplete `clearOnBlur` API documentation fails to recognise that about half the planet/potential users do not identify with he/his pronouns. I figured that this was a small enough change that it would be reasonably simple to fix.
EDIT: I'd like to say thanks for all the work that has gone into the `material-ui` package and …
=> [docs] Make Autocomplete docs gender neutral

docs/src/pages/discover-more/related-projects/related-projects.md, docs/src/pages/getting-started/installation/installation.md
UXPin has released a new landing page, so I have updated the URL links in the related-projects and installation README.
=> [docs] Update UXPin link to new landing page

docs/src/pages/guides/migration-v4/migration-v4.md
Same as other components (`Radio`, `Switch` etc), the default value for the `color` prop has changed, it was "secondary" in [v4](https://github.com/mui-org/material-ui/blob/77a8daeed0e8efa67c6d86f3cc40239dc6eb3d94/packages/material-ui/src/Checkbox/Checkbox.js#L66), when it is now "primary" in [v5](https://github.com/mui-org/material-ui/blob/681632be73fa2d6dc090cf72d01ef59f8b98f822/packages/mui-material/src/Checkbox/Checkbox.js#L77).
Copied the text from `Radio` component description.
https://deploy-preview-30697--material-ui.netlify.app/guides/migration-v4/#checkbox
=> [docs] Add Checkbox color prop change

docs/scripts/buildApiUtils.test.ts
Took Windows-specific path separators into account when performing filename assertions.
=> [test] Fix buildApiUtils tests on Windows

examples/remix-with-typescript/app/entry.client.tsx, examples/remix-with-typescript/app/root.tsx, examples/remix-with-typescript/app/routes/index.tsx, examples/remix-with-typescript/app/src/ClientStyleContext.tsx
Closes https://github.com/mui-org/material-ui/issues/30436
Based on https://github.com/mui-org/material-ui/issues/30436#issuecomment-1003339715 with small adjustments to avoid double rendering.
Credits go to @lvauvillier for the initial implementation.
=> [docs] Update remix example to restore from error pages

docs/data/material/pages.ts, docs/next.config.js, docs/scripts/postMigration.ts, test/e2e-website/material-color-playground.spec.ts, test/e2e-website/material-current.spec.ts, test/e2e-website/material-new.spec.ts, test/e2e-website/material-redirects.spec.ts, test/regressions/index.js
- Fix some e2e mistakes
- add redirects in post-migration script because `nextjs.config` does not work on the production
I deployed the final result of the site to `https://migration.mui.com`
(which includes migration and post-migration steps)
You can use the e2e-website test to run against the migrated content by
- pull this branch
- update `enable_product_scope` & `enable_redirects` in `docs/src/featureToggle.js` to `true`
- run:
```bash
yarn cross-env PLAYWRIGHT_TEST_BASE_URL=https://migration.mui.com playwright test test/e2e-website --config test/e2e-website/playwright.config.ts
```
All the tests should pass.
**Do we need to handle legacy languages redirect to the new location?** @oliviertassinari 
---
=> [docs] Post migration preparation fix

docs/src/modules/utils/replaceUrl.test.js, docs/src/modules/utils/replaceUrl.ts, docs/src/route.ts
will merge and deploy as soon as the CIs are green.
=> [docs] Hotfix the wrong URL in X marketing page

docs/translations/api-docs/button/button.json, docs/translations/api-docs/loading-button/loading-button.json, packages/mui-material/src/Button/buttonClasses.ts
Please let me know if there are any other files that should be changed: I read in the docs that there's no need to update `button-locale.json` files, so I didn't. I did check that the correct text shows up when running the docs site locally 🙂
=> [docs] Fix typo in containedSizeMedium class

docs/src/pages/components/autocomplete/autocomplete.md
Fix an omission ('...can provided...' to '...can be provided...')
=> [Autocomplete] Fix typos in the page

test/utils/createRenderer.test.js, test/utils/createRenderer.tsx
Previously `aria-describedby="r:1 r2"` would crash due to `document.querySelectorAll('#r:2')` not being a valid selector.
It also falsy didn't support multiple describing elements. But [`aria-describedby` does allow ID reference list](https://www.w3.org/TR/wai-aria-1.1/#aria-describedby) not just ID reference.
Required for https://github.com/mui-org/material-ui/pull/30654
=> [test] Support React.useId format in *DescriptionOf

packages/mui-lab/src/DateTimePicker/DateTimePickerTabs.tsx
Simple issue where using the api views prop would result in the user seeing the Month picker but having the Time Tab highlighted instead.
=> [DateTimePicker] Fix month view highlight wrong tab

docs/pages/api-docs/form-control-label.json, docs/pages/api-docs/form-group.json, docs/translations/api-docs/form-control-label/form-control-label.json, docs/translations/api-docs/form-group/form-group.json, packages/mui-material/src/FormControlLabel/FormControlLabel.js, packages/mui-material/src/FormControlLabel/FormControlLabel.test.js, packages/mui-material/src/FormControlLabel/formControlLabelClasses.ts, packages/mui-material/src/FormGroup/FormGroup.js, packages/mui-material/src/FormGroup/FormGroup.test.js, packages/mui-material/src/FormGroup/formGroupClasses.ts
Fixes: #30576
[demo](https://codesandbox.io/s/basictimepicker-material-demo-forked-dyl5g?file=/demo.js)
**Problem:**
- `FormControlLabel` and `FormGroup` components did not inherit the `Mui-error` class
**Solution:**
- Adding Mui-error className option based on the `FormControl` to these two components
=> [FormControlLabel][FormGroup] add Mui-error class

packages/mui-material/src/useMediaQuery/useMediaQuery.test.js, packages/mui-material/src/useMediaQuery/useMediaQuery.ts
Restores https://github.com/mui-org/material-ui/pull/28491 which was reverted in https://github.com/mui-org/material-ui/pull/29870 by using a workaround described in https://github.com/webpack/webpack/issues/14814#issuecomment-1013856049.
Failed checks are from the React 18 run and just `git diff --exit-code` which is expected.
- [React 17 pipeline](https://app.circleci.com/pipelines/github/mui-org/material-ui/62094/workflows/4346c0f9-58e8-4d22-aadc-ce2264f09864)
- [React 18 pipeline](https://app.circleci.com/pipelines/github/mui-org/material-ui/62103/workflows/ae5894d9-0f1e-4021-8f50-fd8079480564)
=> [useMediaQuery] Ensure no tearing in React 18

test/utils/initMatchers.ts
Currently, to be able to create assertions using the custom Chai matchers (e.g. `toErrorDev`) in the tests for the DataGrid in MUI X we need to always [snooze](https://github.com/mui-org/material-ui-x/blob/a7b2ffb7e2f0a41f865ceefc62cd95976f3e6f6a/packages/grid/x-data-grid/src/tests/selection.DataGrid.test.tsx#L462) a TypeScript error, since it can't load the types of these matchers. In https://github.com/mui-org/material-ui-x/pull/3754 I configured the `tsconfig.json` to load the module augmentation provided by `test/utils/initMatchers.ts`. The only problem I faced was that the configuration of `tsconfig.json` is different between MUI Core and MUI X. MUI X sets `noImplicitAny=false` while MUI Core assumes `true` (default if not specified). Because of this difference, `initMatchers.ts` …
=> [test] Add explicit types to support `noImplicitAny=false`

packages/mui-material/src/styles/ThemeProvider.d.ts, packages/mui-system/src/ThemeProvider/ThemeProvider.d.ts
Former link was redirecting to a 404 page. I presume this link is the correct one, cheers!
=> [docs] Change ThemeProvider API links

packages/mui-base/src/AutocompleteUnstyled/useAutocomplete.test.js
Node 16 changed the error message associated with reading a property of a null reference.
This PR adds logic to detect node version and assert on the correct error message.
=> [test] Fix tests on Node 16

packages/mui-material/src/Grid/Grid.js, packages/mui-material/src/Grid/Grid.test.js
Closes https://github.com/mui-org/material-ui/issues/30812
=> [Grid] Fix prop check for applying wrap-reverse

packages/mui-material/src/OutlinedInput/NotchedOutline.js, packages/mui-material/src/OutlinedInput/NotchedOutline.test.js, packages/mui-material/src/OutlinedInput/OutlinedInput.js, packages/mui-material/src/TextField/TextField.js, packages/mui-material/src/TextField/TextField.test.js
Fixes #30230
**Problem:**
- TextField component renders a notch with an empty label
**Solution:**
- check if the label value is not empty, null, or undefined before rendering the label
- Also added some tests to cover edge cases by testing the styles and rendered label value when the label is equal to `0`,`''`, `null`, `undefined`
[demo](https://codesandbox.io/s/formpropstextfields-material-demo-forked-ytmdf?file=/demo.js)
=> [TextField] remove notch when no label is added

packages/mui-material/src/index.d.ts, packages/mui-material/src/index.js
The Base components were exported from @mui/material package and treated as stable even though the @mui/base package is in development. It could create a lot of confusion if developers start using Base components, depend on them, and demand quality found in "proper" Material components. We admit it was a mistake to reexport these components without marking them as unstable.
This PR removes the Base components from @mui/material package. Developers are still encouraged to evaluate the Base components, but they should do so by explicitly installing the @mui/base package.
This is technically a breaking change as it removes a number of components from the @mui/material package. However, we believe that removing the components now and potentially breaking the codebases will do less harm than …
=> [core] Do not reexport Base from Material

docs/notifications.json
=> [docs] Add notifications for the blog posts

docs/pages/experiments/joy/button.tsx, docs/pages/experiments/joy/components.tsx, packages/mui-joy/src/Button/Button.spec.tsx, packages/mui-joy/src/Button/Button.test.js, packages/mui-joy/src/Button/Button.tsx, packages/mui-joy/src/Button/ButtonProps.ts, packages/mui-joy/src/Button/buttonClasses.ts
**Playground**: https://deploy-preview-30803--material-ui.netlify.app/experiments/joy/components/  
**Demo**: https://deploy-preview-30803--material-ui.netlify.app/experiments/joy/button/
- add Button CSS variables (naming can be discussed later). The great benefit about using CSS variables is that we don't need to use pseudo selectors like in `@mui/material/Button`. Also, the customization experience is a lot better because developers only need to change the value without writing the whole stylesheet for every size.
- `--Button-minHeight`: to make the button's height explicit and predictable for different sizes.
- `--Button-gutter`: represents the padding-left & right of the button to be used to calculate icon margin.
- `--Button-iconOffsetStep`: the negative margin of the start/end icon …
=> [Joy] Use icon inside a Button

docs/src/pages/components/autocomplete/GoogleMaps.js, docs/src/pages/components/autocomplete/GoogleMaps.tsx, docs/src/pages/components/autocomplete/autocomplete.md
For autocomplete to work with Google Maps Javascript API, Google's Places API also needs to be enabled.
=> [docs] Update Instructions for Google Maps Autocomplete

docs/pages/api-docs/fab.json, packages/mui-material/src/Fab/Fab.d.ts, packages/mui-material/src/Fab/Fab.js, packages/mui-material/src/Fab/Fab.test.js, packages/mui-material/src/Fab/fabClasses.ts
Fixes: #30665
[CodeSandBox Demo](https://codesandbox.io/s/floatingactionbuttons-material-demo-forked-vsk24?file=/demo.js)
**Problems:**
Fab component only supports primary and secondary values for its color, and it does not support other values such as info, success, etc. It is expected that Fab component accepts them, such as the Button component.
**Solution:**
changing the condition for the color classes and values, and adding them to its valid proptypes.
=> [Fab] supporting other colors

docs/pages/versions.js
Previously: https://mui.com/versions/#released-versions
Now: https://deploy-preview-30863--material-ui.netlify.app/versions/#released-versions
=> [docs] Remove migration from the versions page

docs/pages/blog/2021.md, docs/pages/blog/material-ui-is-now-mui.md, docs/pages/material.tsx
Reflects https://www.notion.so/mui-org/MUI-Material-or-Material-UI-439dbdb694ab4436924679e4de061b1e. I didn't change "Material-UI" to "Material UI". I think that this can be done in a follow-up. https://github.com/mui-org/material-ui/pull/30861#issuecomment-1026876652
=> [docs] Clarify what the name of @mui/material is

docs/pages/api-docs/image-list.json, docs/pages/api-docs/loading-button.json, docs/pages/api-docs/slider.json, framer/Material-UI.framerfx/code/Slider.tsx, framer/scripts/framerConfig.js, packages/mui-joy/src/Button/Button.tsx, packages/mui-joy/src/Switch/Switch.tsx, packages/mui-lab/src/LoadingButton/LoadingButton.js, packages/mui-material/src/ImageList/ImageList.js, packages/mui-material/src/Slider/Slider.js
As [mentioned](https://github.com/mui-org/material-ui/issues/27130#issuecomment-1009778251) by @mnajdova I've created a PR to add missing string annotations for props that use the `OverridableStringUnion`
Fixes https://github.com/mui-org/material-ui/issues/30715
=> [core] Fix propTypes in components where OverridableStringUnion is used

packages/mui-material/src/Autocomplete/Autocomplete.test.js, packages/mui-utils/src/useId.test.js, packages/mui-utils/src/useId.ts
Based on https://github.com/mui-org/material-ui/pull/30657
Restores https://github.com/mui-org/material-ui/pull/26489 which was reverted in https://github.com/mui-org/material-ui/pull/29870 by using a workaround described in https://github.com/webpack/webpack/issues/14814#issuecomment-1013856049.
Failed checks are from the React 18 run and just `git diff --exit-code` which is expected.
- [React 17 pipeline](https://app.circleci.com/pipelines/github/mui-org/material-ui/62934/workflows/8a3a2cc0-d707-41eb-8a93-46372d581c72)
- [React 18 pipeline](https://app.circleci.com/pipelines/github/mui-org/material-ui/62935/workflows/93586a6b-c379-4de3-8df1-f4ef316f4149)
=> [utils] Use built-in hook when available for useId

packages/mui-base/src/MultiSelectUnstyled/MultiSelectUnstyled.test.tsx, packages/mui-base/src/SelectUnstyled/SelectUnstyled.test.tsx
Failing GH status checks are expected due to git-diff in React 18 pipeline.
There's a difference for <kbd>Enter</kbd> and <kbd>Space</kbd> in `keydown` and `keyup` with regards to activation behavior. For <kbd>Enter</kbd> `keydown` will activate the element. For <kbd>Space</kbd> `keyup` will activate the element.
This was not codified in tests and started failing for React 18. It should be codified in tests anyway. Other usages of `userEvent.keypress` should also be investigated. `userEvent` was really just a temporary solution for timing related changes between React 17 and 18. It shouldn't be used freely.
[React 17 pipeline](https://app.circleci.com/pipelines/github/mui-org/material-ui/63135/workflows/845a50b9-bd20-4257-9dce-ef81ff66a56b)
[React 18 …
=> [test] Codify the difference between keyup and keydown in SelectUnstyled

docs/src/pages/getting-started/example-projects/example-projects.md
=> [docs] Fix the link to the Vite.js example project

docs/data/styles/advanced/advanced.md
Steps to reproduce:
- Visit https://mui.com/styles/advanced/#augmenting-your-props-using-withstyles
- Second code sample references previous import location for `WithStyles`
Screenshot:
=> [docs] Fix WithStyles import statement for @mui/styles

docs/data/material/guides/right-to-left/right-to-left.md
i added createtheme method to step 2 in [Right-to-left guide](https://mui.com/guides/right-to-left/) because any new users dont know where is this method
=> [docs] Add missing import to RTL guide

docs/translations/api-docs/modal-unstyled/modal-unstyled.json, docs/translations/api-docs/modal/modal.json, docs/translations/api-docs/unstable-trap-focus/unstable-trap-focus.json, packages/mui-base/src/ModalUnstyled/ModalUnstyled.d.ts, packages/mui-base/src/ModalUnstyled/ModalUnstyled.js, packages/mui-base/src/Unstable_TrapFocus/Unstable_TrapFocus.d.ts, packages/mui-base/src/Unstable_TrapFocus/Unstable_TrapFocus.js, packages/mui-material/src/Modal/Modal.js
This behavior also runs on unmount (it is in the return function of an effect).
=> [docs] Improve description of the `disableRestoreFocus` prop of the `TrapFocus`

packages/mui-base/src/BadgeUnstyled/BadgeUnstyled.js, packages/mui-base/src/BadgeUnstyled/BadgeUnstyledProps.ts, packages/mui-base/src/BadgeUnstyled/useBadge.ts, packages/mui-material/src/Badge/Badge.js, packages/mui-material/src/Badge/Badge.test.js
Closes #30807 [codeSandBox demo](https://codesandbox.io/s/simplebadge-material-demo-forked-n1388?file=/demo.js)
**Problem:**
`Badge` component did not work correctly when the invisible prop was equal to false.
**Solution:**
In the Badge component, instead of checking if the invisible prop is not equal to null or undefined, we can check if it is not true. Then we can change the invisible value to true in certain circumstances, such as when the `badgeContent` is zero and `showZero` is false.
=> [Badge] fix showzero and invisible condition

docs/pages/_document.js
https://deploy-preview-30919--material-ui.netlify.app/getting-started/installation/
In GA, we had the following warning a few days ago:
This is our current quote usage:
We are above the 10M/month limit: https://developers.google.com/analytics/devguides/collection/analyticsjs/limits-quotas.
While Google doesn't seem to penalize us so far, he might in the future. I'm adding a bit of sampling https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference in case.
=> [website] Sample GA to avoid hit limit

docs/data/material/guides/migration-v4/migration-v4.md
I fixed a mistake I found during the migration.
=> [docs] Fix link-underline-hover chapter of migration guides v4

packages/mui-lab/src/ClockPicker/ClockNumber.tsx
Fixes: #30228
**Problem**
- In `ClockNumber` component, `fontFamily` was not assigned to the outer numbers
**Solution**
- adding fontFamily based on the typography's font
=> [ClockNumber] add font for outer numbers

.markdownlint.jsonc, docs/data/material/guides/interoperability/interoperability.md
Good day,  
I think the JSS hook-based API (`makeStyles` ->  `useStyles`) has still a solid fanbase.  
If you think that this is pushing TSS too hard, feel free to close, I won't take offense.  
Best regads,
=> [docs] Include JSS in styling solution interoperability guide

docs/data/material/getting-started/templates/dashboard/Dashboard.js, docs/data/material/getting-started/templates/dashboard/Dashboard.tsx, docs/data/material/getting-started/templates/dashboard/listItems.js, docs/data/material/getting-started/templates/dashboard/listItems.tsx
The existing nav structure was:
```
<ul>
<div>
<div aria-role="button">...</div>
</div>
<hr>
<div>
<div aria-role="button">...</div>
</div>
</ul>
```
This PR replaces with the semantic
```
<nav>
<div aria-role="button">...</div>
<hr>
<div aria-role="button">...</div>
</nav>
```
=> [docs] Remove ul with div children and replace with nav element

benchmark/package.json, yarn.lock
`yarn benchmark:browser` was failing due to a missing dependency. Theme UI requires @mdx-js/react as a peer dependency.
=> [benchmark] Add missing dependency

packages/mui-material/src/index.d.ts, packages/mui-material/src/index.js
Recently #30853 is pushed and applied version 5.4.x.
However, **Portal Component is missing and can't access the component.**
In #30853 PR, 
> Note: utility components, such as ClickAwayListener, NoSsr, Portal, and TextareaAutosize continue to be exported from both @mui/material and @mui/base
This PR is a re-export Portal Component and can access the Component without **'@mui/base'** package.
```diff
// package/mui-material/src/index.js
...
export * from './Popper';
+ export { default as Portal } from './Portal';
+ export * from './Portal';
+
export { default as Radio } from './Radio';
...
```
```diff
// package/mui-material/src/index.d.ts
...
export * from './Popper';
+ export { default as Portal } from './Portal';
+ export * from './Portal';
+
export { default as Radio } from './Radio'; …
```
=> [Portal] Re-export 'Portal' in material

docs/src/modules/components/AppNavDrawer.js
- Rename "Material" to "Material UI" as the official name
- Rename "Material Design" to "Material UI"  as the official name
- Rename "System" to "MUI System" to match the pricing page: The name should be self-sustained, a great test is can you search it on Google?
- ~Rename "Data Grid" to "Advanced components" as it will include the date picker very soon.~ Moved to #30972
=> [docs] Use full product names (Material UI, MUI System)

docs/pages/api-docs/desktop-date-picker.json, docs/pages/api-docs/desktop-date-range-picker.json, docs/pages/api-docs/desktop-date-time-picker.json, docs/pages/api-docs/desktop-time-picker.json, docs/pages/material/api/desktop-date-picker.json, docs/pages/material/api/desktop-date-range-picker.json, docs/pages/material/api/desktop-date-time-picker.json, docs/pages/material/api/desktop-time-picker.json, docs/translations/api-docs/desktop-date-picker/desktop-date-picker.json, docs/translations/api-docs/desktop-date-range-picker/desktop-date-range-picker.json, docs/translations/api-docs/desktop-date-time-picker/desktop-date-time-picker.json, docs/translations/api-docs/desktop-time-picker/desktop-time-picker.json, packages/mui-lab/src/DatePicker/DatePicker.tsx, packages/mui-lab/src/DesktopDatePicker/DesktopDatePicker.test.tsx, packages/mui-lab/src/DesktopDatePicker/DesktopDatePicker.tsx, packages/mui-lab/src/DesktopDateRangePicker/DesktopDateRangePicker.tsx, packages/mui-lab/src/DesktopDateTimePicker/DesktopDateTimePicker.tsx, packages/mui-lab/src/DesktopTimePicker/DesktopTimePicker.tsx, packages/mui-lab/src/internal/pickers/PickersPopper.tsx, packages/mui-lab/src/internal/pickers/wrappers/DesktopWrapper.tsx
Fixes: #30676
[Demo](https://codesandbox.io/s/responsivedatepickers-material-demo-forked-p4z0y?file=/demo.js)
**Problems:**
- clearable prop did not render the clear button in DesktopDatePicker component and it was only passed to the MobileDatePicker component
**Solution:**
- passing clearable and clearText props and rendering clear button on PickersPopper whenever clearable is true
=> [DatePicker] Fix passing clearable prop

packages/mui-material/src/index.test.js
Added a test to make sure @mui/material reexports certain members of @mui/base (to prevent issues like #31003 in the future).
=> [test] Test if certain Base members are exported from Material UI

docs/data/material/components/icons/icons.md
The documentation of the `icons` package mentions that we need to install MUI in order to use it. However, the MUI installation command is missing `@emotion/react` and `@emotion/styled`. Instead of adding them to the command, I replaced the command with the link to the MUI installation guide so that we won't have to keep the two guides in-sync.
=> [docs] Update installation guide of the icons package

docs/public/_headers
It's not really important but it doesn't harm either to **signal** that we care about security. It's already deployed in production and seems to work:
- https://snyk.io/test/website-scanner/?test=220213_AiDcC7_7YF
- https://securityheaders.com/?q=https%3A%2F%2Fmui.com%2F
I have tested the CSP policy using https://sentry.io/organizations/mui-org/issues/?project=6201480 in report-only mode beforehand.
=> [website] Minor security improvements

docs/src/pages/careers/TEMPLATE.md, docs/src/pages/careers/designer.md, docs/src/pages/careers/developer-advocate.md, docs/src/pages/careers/developer-experience-engineer.md, docs/src/pages/careers/people-operation-manager.md, docs/src/pages/careers/product-engineer.md, docs/src/pages/careers/product-manager.md, docs/src/pages/careers/react-engineer.md, docs/src/pages/careers/react-support-engineer.md, docs/src/pages/careers/support-agent.md, docs/src/pages/careers/technical-product-manager.md, docs/src/pages/company/careers/full-stack-engineer.md
Advertising our open roles on the documentation has been a very efficient lever to source candidates but this strategy has limitations:
- Only a small percentage of the audience of MUI are actually people that would be great fits at MUI. For example, when we hear "MUI is awesome, I have been using it executively for all my projects", this is a red flag. The ideal developer candidate is somebody that uses MUI when time is a constraint but rebuilds everything himself when he has the bandwidth.
- There might be better channels to source our ideal candidates. We are exploring new ones:
- https://www.linkedin.com/jobs/view/2916986793/
- https://angel.co/company/mui-org/jobs/1977657-senior-designer
- https://www.behance.net/joblist/182011/Senior-Designer
- Indeed (WIP)
- Glassdoor (WIP)
- …
=> [website] Prefill source in job application links

packages/mui-material/src/locale/index.ts
The translation for `labelDisplayedRows` was missing so when using a component that required it (e.g, the the `DataGrid` component from the `mui-x` library), the default one (english) was used.
=> [l10n] Add it-IT translation for labelDisplayedRows

docs/data/material/guides/migration-v4/migration-v4.md
fix typo
- `<TextareAutosize>` 
- trasnformation
fixed #31115
=> [docs] Fix typo of migration guides v4

docs/translations/api-docs/button-base/button-base.json, packages/mui-material/src/ButtonBase/ButtonBase.d.ts, packages/mui-material/src/ButtonBase/ButtonBase.js
Change `TouchRippple` to `TouchRipple`
=> [Button Base] Fix typo

docs/src/components/pricing/PricingTable.tsx
Add "master detail" and "row grouping" as developed on the pricing page
https://deploy-preview-30913--material-ui.netlify.app/pricing/
It's the same as https://github.com/mui/mui-x/pull/3877 but since we duplicate the content, we have to update both locations.
=> [website] Sync MUI X table feature

docs/pages/experiments/joy/components.tsx, docs/pages/experiments/joy/list.tsx, packages/mui-joy/src/List/List.test.js, packages/mui-joy/src/List/List.tsx, packages/mui-joy/src/List/ListProps.ts, packages/mui-joy/src/List/listClasses.ts, packages/mui-joy/src/ListItem/ListItem.test.js, packages/mui-joy/src/ListItem/ListItem.tsx, packages/mui-joy/src/ListItem/ListItemProps.ts, packages/mui-joy/src/ListItem/listItemClasses.ts, packages/mui-joy/src/ListItemButton/ListItemButton.tsx
2nd iteration for the List component. I am pushing `List` component to be the first complete component that can be compared with Material, so that we can measure how it is different & how much improvements we gain with the new approach.
- support different sizes
- able to provide secondary action on the list item
- sticky subheader
- add `size: 'sm' | 'md' | 'lg'` to `List` component (**take a look at the Preview**)
- add `secondaryAction` (same as Material) to `ListItem` (**take a look at the Preview**)
- add `sticky` prop to `ListItem`. I think this is a lot easier than in Material:
- No need a new component (ListSubheader in Material)
- background is handled automatically (controlled by the List)
**New**
- `--List-item-secondaryActionWidth`: this var is needed to communicate with …
=> [Joy] `List` second iteration

packages/mui-system/src/cssVars/createCssVarsProvider.d.ts, packages/mui-system/src/cssVars/createCssVarsProvider.js, packages/mui-system/src/cssVars/cssVarsParser.test.ts, packages/mui-system/src/cssVars/cssVarsParser.ts, test/regressions/fixtures/CssVarsProvider/CssVarsProviderJoy.js
Based no #31138, there is a problem when `baseTheme` provided to `createCssVarsProvider` contains functions. Those functions are removed because of JSON.stringify to make the object fresh on every render (the logic inside `CssVarsProvider` mutate the object, so we need to make sure that the object is new on every call, otherwise the multiple `CssVarsProvider` on a single page would not work).
There are 2 possible ways to fix this:
1. receive `basedTheme` as a function that returns a new object 
2. fix the logic inside `CssVarsProvider` to not mutate the object
In this PR, I chose the 2nd option because it is safer. It guarantees that the object is new on every renders and developers do not need to be concerned about the theme they are passing.
> Note: the first option seems not a good …
=> [system] Fix `CssVarsProvider` theme mutation

docs/data/material/guides/migration-v4/migration-v4.md
For tss-react migration guide: add missing import CacheProvider and replace unused ThemProvider import
=> [docs] Add missing import into tss-react migration guide

packages/mui-system/src/Box/Box.spec.tsx, packages/mui-system/src/createBox.spec.tsx, packages/mui-system/src/styleFunctionSx/styleFunctionSx.d.ts
I noticed this in https://github.com/mui/material-ui/pull/31138. Basically, if the CSS variables are used together with some nested selectors in the `sx` prop, it breaks the types. I've added tests and update the types, see https://github.com/mui/material-ui/pull/31163#discussion_r811163352.
I had to remove two @ts-expect-errors, not ideal, but I think fixing the problem with the CSS variables used together with the nested selectors is more important.
=> [system] Fix sx prop types when CSS variables are used with nested selectors

docs/src/modules/components/AppFrame.js, docs/src/modules/components/AppNavDrawer.js, docs/src/modules/components/AppSearch.js, docs/src/modules/utils/replaceUrl.ts
Using the new app for only the new URLs will allow us to test the search experience without impacting the existing experience on the old URLs.
I adjust the setting on the new app (in algolia console) to have `queryType: "prefixAll"` which is different from the old app setting.
**current URLs result**
The `queryType` is `prefixLast`. https://deploy-preview-31178--material-ui.netlify.app/getting-started/installation/
**New URLs result**
https://deploy-preview-31178--material-ui.netlify.app/material/getting-started/installation/
This proves that the new algolia app is working on the new URLs.
---
=> [docs] Use new Algolia app for new structure

docs/pages/api-docs/popper-unstyled.json, docs/pages/api-docs/popper.json, docs/pages/base/api/popper-unstyled.json, docs/pages/material/api/popper.json, packages/mui-base/src/PopperUnstyled/PopperUnstyled.js, packages/mui-material/src/Popper/Popper.tsx, packages/typescript-to-proptypes/src/parser.ts, packages/typescript-to-proptypes/test/partial-any-props/input.d.ts, packages/typescript-to-proptypes/test/partial-any-props/output.js
The following change will generate incorrect propTypes:
```diff
diff --git a/packages/mui-material/src/Popper/Popper.tsx b/packages/mui-material/src/Popper/Popper.tsx
index cb0bf4de5d..5bf0957724 100644
--- a/packages/mui-material/src/Popper/Popper.tsx
+++ b/packages/mui-material/src/Popper/Popper.tsx
@@ -19,7 +19,7 @@ export type PopperProps = Omit<PopperUnstyledProps, 'direction'>;
* - [Popper API](https://mui.com/api/popper/)
*/
const Popper = React.forwardRef(function Popper(
-  props: PopperProps,
+  props: PopperProps & Partial<{ fooBar: any }>,
ref: React.ForwardedRef<HTMLDivElement>,
) {
const theme = useTheme<{ direction?: Direction }>();
@@ -65,6 +65,10 @@ Popper.propTypes /* remove-proptypes */ = {
* @default false
*/
disablePortal: PropTypes.bool,
+  /**
+   * @ignore
+   */
+ …
```
=> [core] Fix propTypes generation for optional `any` props

.circleci/config.yml
The error below occurs frequently, and triggering the failed pipeline again seems to work most of the time. I suspect that the error comes from the unfinished build of the dependency types.
It always happens with `base` because `material`, `material-next`, and `joy` rely on it. If the `base` part that Joy needs is not there (unfinished built), then there will be an error. It is likely because of the `--parallel` flag we specify (by default, lerna build based on topological sorting).
https://github.com/lerna/lerna/tree/main/commands/exec#--parallel
=> [core] Remove parallel on `buildTypes`

docs/public/static/error-codes.json, packages/mui-material/src/styles/makeStyles.js, packages/mui-material/src/styles/withStyles.js, packages/mui-material/src/styles/withTheme.js
In the error message, "not longer" is not grammatically correct and should instead be "no longer".
=> [styles] Fix typo in import error

docs/pages/blog/introducing-the-row-grouping-feature.md
This PR suggests various revisions for the row grouping announcement blog post.
- adds value proposition to headline and subheader
- removes unnecessary intro text
- adds more line breaks for readability and skim-ability
- fixes minor grammar and punctuation mistakes throughout
- simplifies and clarifies language and phrasing throughout to better match the norms of US English
- defines "share your feedback" as the primary call to action in the conclusion
@alexfauquette I hope this is helpful! Please let me know if you'd like any more detailed feedback. The main things I would point out would be adding the value proposition in the headline, getting straight to the point in the intro, and defining a clear call to action in the conclusion. These tweaks can make a big difference! 😁 …
=> [website] Revise the row grouping blog post

.github/renovate.json
Fixes issue that came across in https://github.com/mui/material-ui/pull/31056 where the core package was not being updated together with the icons package.
=> [renovate] Add group for the @fortawesome dependencies

packages/mui-material/src/FilledInput/FilledInput.test.js, packages/mui-material/src/FilledInput/filledInputClasses.ts, packages/mui-material/src/Input/Input.test.js, packages/mui-material/src/Input/inputClasses.ts, packages/mui-material/src/OutlinedInput/OutlinedInput.test.js, packages/mui-material/src/OutlinedInput/outlinedInputClasses.ts
Fixes https://github.com/mui/material-ui/issues/31080
The input components (Input, FilledInput, OutlinedInput) were exporting the wrong classes in the respected `inputClasses`, `filledInputClasses` and the `outliendInputClasses`. The classes exported now are the `inputBaseClasses` wih the additional classes added by the specific component.
=> [Input] Export InputBase's classes from the classes const

docs/data/material/guides/migration-v4/migration-v4.md, docs/data/material/guides/routing/routing.md, docs/packages/markdown/parseMarkdown.js, docs/pages/about.tsx
In https://mui.com/zh/guides/migration-v4/#update-mui-core-version, the link to the blog is broken
The error https://app.ahrefs.com/site-audit/2944028/34/data-explorer?columns=pageRating%2Curl%2Ctraffic%2ChttpCode%2Cdepth%2Ccompliant%2CincomingAllLinks%2Corigin&filterCollapsed=true&filterId=ce299062c267aa6829f86c4c4966bd3c&issueId=c64dae3f-d0f4-11e7-8ed1-001e67ed4656&sorting=-pageRating&udUrl=https%3A%2F%2Fmui.com%2Fzh%2Fblog%2Fmaterial-ui-is-now-mui%2F
=> [docs] Fix 404 link to the blog

packages/mui-lab/src/themeAugmentation/components.d.ts, packages/mui-material/src/styles/components.d.ts
Due to the ongoing discussion in https://github.com/mui/material-ui/issues/30412#issuecomment-1018467855 and comment in https://github.com/mui/material-ui/pull/30524#discussion_r789602389.
It is too early to deprecate the variants theming. This PR revert the deprecation warning in the types.
=> [Typescript] Remove variants deprecation

packages/mui-material/src/AvatarGroup/AvatarGroup.js
Closes https://github.com/mui/material-ui/issues/29641
The `marginLeft` style (applied only for custom `spacing`) should be applied on all but the last element of the group, in order to avoid misalignment of the Avatar children. This makes the non-default spacing (such as `spacing="small"` or `spacing={10}`) consistent with the behavior of the default `spacing="medium"` CSS, which leaves the margin-left as-is for the `:last-child`.
(This demo uses default spacing, then `spacing={10}`, then `spacing={-10}`, then `spacing="small"`.)
=> [AvatarGroup] Fix misalignment with non-default spacing

packages/mui-material/src/Select/Select.d.ts, packages/mui-material/src/Select/Select.spec.tsx
Closes https://github.com/mui/material-ui/issues/31208
According to [docs](https://mui.com/api/select/#props) Select should have OutlineInput props available. Functionality works, but typescript coverage was lacking.
=> [Select] Add extending `OutlinedInputProps` by SelectProps

docs/data/material/components/drawers/MiniDrawer.js, docs/data/material/components/drawers/MiniDrawer.tsx
credit: @devzgabriel
original: #30205
**Result**
https://deploy-preview-31267--material-ui.netlify.app/components/drawers/#mini-variant-drawer
=> [Drawer] Adjustments to the mini variant to improve UI/UX

docs/pages/experiments/joy/link.tsx, packages/mui-joy/src/Link/Link.spec.tsx, packages/mui-joy/src/Link/Link.test.js, packages/mui-joy/src/Link/Link.tsx, packages/mui-joy/src/Link/LinkProps.ts, packages/mui-joy/src/Link/index.ts, packages/mui-joy/src/Link/linkClasses.ts, packages/mui-joy/src/index.ts, packages/mui-joy/src/styles/components.d.ts
- `variant`: `'text' | 'outlined' | 'light' | 'contained'` (`undefined` by default)
- `color`: `'danger' | 'info' | 'neutral' | 'primary' | 'success' | 'warning'` (`primary` by default)
- `level`: `'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'body1' | 'body2' | 'body3'` (`body1` by default)
-  `underline`: `'none' | 'hover' | 'always'` (`always` by default)
Preview: https://deploy-preview-31175--material-ui.netlify.app/experiments/joy/link/
=> [Joy] Add `Link` component

docs/src/components/banner/TableOfContentsBanner.tsx, docs/src/featureToggle.js
Let me know any improvement to the writing or anything else.
Preview: https://deploy-preview-31275--material-ui.netlify.app/getting-started/installation/
=> [docs] Add banner in solidarity of Ukraine

packages/mui-material-next/package.json
Without `@mui/material` as a dependency in `@mui/material-next`, this error could happen in any PRs. The fix allows lerna to organize the build order for us.
Source: https://app.circleci.com/pipelines/github/mui/material-ui/65801/workflows/aebea217-a369-486e-83e0-452db3ff7c20/jobs/355054
---
=> [material-next] Mark `@mui/material` as a dependency

test/utils/createRenderer.tsx
The option is no longer used.
We gradually moved from full test -> specific test -> branch assertions over time (e.g. https://github.com/mui-org/material-ui/blob/3bf3e18a95f9aa54a17d44fbb126ca5b88d3fef3/packages/mui-material/src/Autocomplete/Autocomplete.test.js#L2230)
=> [test] Remove legacyRoot option from test renderer

packages/mui-base/src/AutocompleteUnstyled/useAutocomplete.js, packages/mui-base/src/AutocompleteUnstyled/useAutocomplete.test.js, packages/mui-material/src/Autocomplete/Autocomplete.test.js
- [ x ] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui-org/material-ui/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).
Fixes: https://github.com/mui-org/material-ui/issues/30369
Problem:
1. Start your the NVDA or JAWS screen reader
2. Tab to the Autocomplete component and open the dropdown by pressing down arrow
3. The screen reader should announce that the combobox is open ❌ 
4. Close the dropdown by pressing escape
5. The screen reader should announce that the combobox is closed ❌ 
Solution:
- Move `role="combobox"` to input
- Move `aria-expanded` to input
=> [Autocomplete] Have the screen reader announce when autocomplete is open and closed

packages/mui-material/src/Autocomplete/Autocomplete.test.js
Fixed Autocomplete tests that started to fail after changes introduced in #30601 were merged in.
=> [Autocomplete] Fix failing unit tests

docs/pages/experiments/joy/button.tsx, docs/pages/experiments/joy/components.tsx, docs/pages/experiments/joy/input.tsx, docs/pages/experiments/joy/list.tsx, docs/pages/experiments/joy/sheet.tsx, docs/pages/experiments/joy/switch.tsx, docs/pages/experiments/joy/typography.tsx, docs/pages/experiments/joy/variant-overrides.tsx, docs/pages/experiments/joy/variant.tsx, packages/mui-joy/src/Button/Button.tsx, packages/mui-joy/src/IconButton/IconButton.tsx, packages/mui-joy/src/styles/CssVarsProvider.tsx, packages/mui-material/src/SvgIcon/SvgIcon.js
This is an experimental feature called ["Adaptive component"](https://www.notion.so/mui-org/Adaptive-component-4cf81866231b4071ae25cb2eba1c64dd).
It gives the parent component the ability to control the children without hurting customization experience.
In Material UI, it is using CSS selector to control the children which leads to bad customization experience. https://github.com/mui/material-ui/issues/28917
```js
<Button size="small" startIcon={<Icon />}>...</Button>
// some icon looks great by default, but for some icon needs customization
// here is what I expect to do with sx
<Button size="small" startIcon={<Icon sx={{ fontSize: '18px' }} />}>...</Button>
//❗️it does not work, and then I have to open a devtool and found that it is using CSS selector
// Finally, ends up with this …
```
=> [Joy] Make Icon `fontSize` adaptable to its parent

packages/mui-base/src/MultiSelectUnstyled/MultiSelectUnstyled.tsx, packages/mui-base/src/OptionUnstyled/OptionUnstyled.test.tsx, packages/mui-base/src/OptionUnstyled/OptionUnstyled.tsx, packages/mui-base/src/SelectUnstyled/SelectUnstyled.tsx, packages/mui-base/src/SelectUnstyled/SelectUnstyledContext.ts, packages/mui-base/test/integration/SelectUnstyled.test.tsx, test/karma.tests.js
Changes the implementation of scrolling to the highlighted option. Instead of using `scrollIntoView`, the listbox `scrollTop` is calculated and applied if necessary. This ensures only the listbox content is scrolled, not the entire window (or other external scroll container).
Fixes #31010
=> [SelectUnstyled] Prevent window scrolling after opening

docs/src/modules/components/AppNavDrawerItem.js
In February 2022, we have used 5.2 TB of data for https://mui.com/. Netlify doesn't provide much analytics, so we can only guess why. Now, I did notice behavior that looks completely wrong. The Next's Link component prefetches all the pages for the page that are in the viewport https://nextjs.org/docs/api-reference/next/link. So this means, loading many pages (100?) when only consuming on. This only happens in production:
https://user-images.githubusercontent.com/3165635/156935100-b3617f14-e9bf-4761-9199-748f3c909c02.mp4
https://mui.com/components/alert/
I would expect (hope) this fix to reduce the bandwidth usage by a good 3 TB, saving $600/month. https://deploy-preview-31341--material-ui.netlify.app/components/alert/
Why did I work on this? Because Netlify started to bill $1,000/month …
=> [docs] Fix JS files overloading

crowdin.yml
Our career page should be English only, we filter candidates based on this. I'm ignoring these files
https://translate.mui.com/project/material-ui-docs/zh-CN#/material-ui/master/docs
I would propose we start to actively translate the docs once the docs split is pushed enough.
=> [docs] Remove career pages from translation

package.json
Changed `'` to `"` in markdownlint script to allow it to be run on Windows
=> Fix running markdownlint on Windows

packages/mui-base/src/ButtonUnstyled/ButtonUnstyled.types.ts, packages/mui-base/src/MultiSelectUnstyled/MultiSelectUnstyled.types.ts, packages/mui-base/src/SelectUnstyled/SelectUnstyled.types.ts, packages/mui-types/index.d.ts
This changes the display of slot props types from the quite cryptic
```ts
type ButtonUnstyledRootSlotProps = Omit<{}, keyof UseButtonRootSlotOwnProps> & UseButtonRootSlotOwnProps & {
ownerState: ButtonUnstyledOwnerState;
className: string;
children?: React.ReactNode;
}
```
to more readable
```ts
type ButtonUnstyledRootSlotProps = {
'aria-disabled'?: Booleanish | undefined;
disabled?: boolean | undefined;
tabIndex: number;
// ...
}
```
The shape of the types remains unchanged. Just the display in the editor is affected.
The idea was taken from https://effectivetypescript.com/2022/02/25/gentips-4-display/
=> [typescript] Simplify display of slot props types

docs/src/components/banner/TableOfContentsBanner.tsx
The current link in the Ukraine banner returns a 404. The support page appears to have been moved to a new subdomain. I have updated the link, and also removed the word "here" from the call to action so it reads better.
=> [website] Update Ukraine support link

packages/mui-material/src/locale/index.ts
Remove comment and translate language variable for pagination on itIT.
=> [i18n] Update italian language variable

docs/data/material/components/text-fields/text-fields.md, docs/translations/api-docs/filled-input/filled-input.json, docs/translations/api-docs/input-base/input-base.json, docs/translations/api-docs/input/input.json, docs/translations/api-docs/outlined-input/outlined-input.json, packages/mui-material/src/FilledInput/FilledInput.js, packages/mui-material/src/Input/Input.js, packages/mui-material/src/InputBase/InputBase.d.ts, packages/mui-material/src/InputBase/InputBase.js, packages/mui-material/src/OutlinedInput/OutlinedInput.js
The documentation here read to me that if you set `multiline` and use the `rows` prop, you'd get a textarea component that was not a `TextareaAutosize` component. Looking into the code it looks like that used to be the case but was changed in this PR: git@github.com:jontewks/material-ui.git to always be a `TextareaAutosize` no matter what props are passed. Updated the documentation wording here to be more clear that using the `multiline` prop will always result in a `TextareaAutosize` component, and then any additional props just bound how that `TextareaAutosize` adjusts.
=> [docs] Update TextField multiline description

docs/pages/experiments/joy/input.tsx, docs/pages/experiments/joy/link.tsx, docs/pages/experiments/joy/list.tsx, docs/pages/experiments/joy/typography.tsx, packages/mui-joy/src/Button/Button.tsx, packages/mui-joy/src/IconButton/IconButton.tsx, packages/mui-joy/src/Input/Input.tsx, packages/mui-joy/src/Input/InputProps.ts, packages/mui-joy/src/Link/Link.tsx, packages/mui-joy/src/List/List.tsx, packages/mui-joy/src/List/index.ts, packages/mui-joy/src/ListDivider/index.ts, packages/mui-joy/src/ListItem/index.ts, packages/mui-joy/src/ListItemButton/index.ts, packages/mui-joy/src/ListItemContent/index.ts, packages/mui-joy/src/ListItemDecorator/index.ts, packages/mui-joy/src/Typography/Typography.tsx
🖥 **Preview**
- [Link](https://deploy-preview-31360--material-ui.netlify.app/experiments/joy/link/)
- [List](https://deploy-preview-31360--material-ui.netlify.app/experiments/joy/list/)
- [Typography](https://deploy-preview-31360--material-ui.netlify.app/experiments/joy/typograhy/)
- [Input](https://deploy-preview-31360--material-ui.netlify.app/experiments/joy/input/)
A follow-up PR from https://github.com/mui/material-ui/pull/31268 to let other components that usually contain Icon as a child control the icon font-size.
Also, fix some components that do not define variables for each size.
=> [Joy] Add `--Icon-fontSize` to components

packages/mui-material/src/Grid/Grid.js, packages/mui-material/src/Grid/Grid.test.js
Fix #30209.
This fixes the problem of giving a grid item within a nested grid container the wrong `width`. I think the source of the problem is the grid container inherits the `columns` of the root container and this happens only in the case when the prop `columns` value is 12. I tried to use the default `columns` value which’s 12.
=> [Grid] Fix columns of nested container

docs/data/system/styled/styled.md
Fixes https://github.com/mui/material-ui/issues/31252
=> [docs] Fix wrong documentation on the `styled`'s slot option

docs/pages/experiments/joy/switch.tsx, packages/mui-joy/src/Switch/Switch.tsx
No extra elements are needed to achieve the result 👍, just adding more styles to cover edge cases.
```js
// add icon to the thumb
<Switch
componentsProps={{
thumb: {
children: <Moon />,
},
}}
/>
// add label to the track
<Switch
componentsProps={{
track: {
children: (
<React.Fragment>
<Typography component="span" level="inherit" sx={{ ml: '10px' }}>
On
</Typography>
<Typography component="span" level="inherit" sx={{ mr: '8px' }}>
Off
</Typography>
</React.Fragment>
),
},
}}
/>
```
=> [Joy] Add icon & label `Switch` examples
