mui/material-ui

- packages/mui-material/src/locale/index.ts
As in title - added proper polish translation for labelDisplayedRows.
> [l10n] Add pl-PL translation for labelDisplayedRows

- docs/data/material/components/material-icons/synonyms.js
> [icons] Add "circle" icon synonyms

- docs/src/pages/careers/full-stack-engineer.md
Just making sure that "expertise in backend" goes further than "able to build REST APIs".
> Update FS role

- packages/mui-joy/src/Button/ButtonProps.ts
> [Joy] Fix `Button` missing slot type

- docs/data/material/guides/interoperability/interoperability.md
> [docs] Update interoperability.md broken tailwind links

- docs/data/material/components/stack/stack.md
> [docs] Fix typo in Stack documentation

- packages/mui-material/src/OutlinedInput/NotchedOutline.js
> [TextField] Fix horizontal scroll when label is too long

- .circleci/config.yml
> [core] Update playwright docker to match the specified version

- packages/mui-system/src/createStyled.js
It's almost the same as https://github.com/mui/material-ui/pull/29290 , fixing the second scenario like that that got reported here: https://github.com/mui/material-ui/issues/29078#issuecomment-1036208915
> [system] Fix executing server-side Emotion component as function interpolation 2

- examples/nextjs-with-typescript/package.json
Without this, the example currently errors.
> Add @types/node to nextjs typescript starter.

- packages/mui-joy/src/SvgIcon/SvgIcon.test.js
> [Joy] Improve `SvgIcon` tests

- packages/mui-joy/src/Sheet/Sheet.test.js
> [Joy] Improve `Sheet` tests

- docs/data/material/components/tabs/ScrollableTabsButtonAuto.js
- docs/data/material/components/tabs/ScrollableTabsButtonAuto.tsx
- docs/data/material/components/tabs/ScrollableTabsButtonForce.js
- docs/data/material/components/tabs/ScrollableTabsButtonForce.tsx
- docs/data/material/components/tabs/ScrollableTabsButtonPrevent.js
- docs/data/material/components/tabs/ScrollableTabsButtonPrevent.tsx
- docs/data/material/components/tabs/ScrollableTabsButtonVisible.js
- docs/data/material/components/tabs/ScrollableTabsButtonVisible.tsx
Closes https://github.com/mui/material-ui/issues/31272
It was happening too in LTR :)
> [docs] Fix `maxWidth` of scrollable Tabs demos

- package.json
I've noticed it while working on https://github.com/mui/material-ui/pull/29809
> [core] Fix the stylelint script on Windows

- docs/src/modules/components/MarkdownDocs.js
Closes https://github.com/mui/material-ui/issues/31315
> [docs] Fix GitHub source links in the demo toolbar

- docs/src/modules/components/AppSearch.js
A quick fix for https://github.com/mui/material-ui/issues/31384
> Fix Search crash

- docs/data/material/components/stack/BasicStack.js
- docs/data/material/components/stack/BasicStack.tsx
Closes https://github.com/mui/material-ui/issues/31413
Preview: https://deploy-preview-31423--material-ui.netlify.app/components/stack/#main-content
> [docs] Adjust Stack's basic usage demo

- test/e2e-website/material-current.spec.ts
- test/e2e-website/material-new.spec.ts
Follow up from https://github.com/mui/mui-x/pull/4136
> [docs] Remove unnecessary await in e2e-tests

- docs/src/modules/components/GoogleAnalytics.js
Fix #31420
https://deploy-preview-31458--material-ui.netlify.app/
> [docs] Fix docs site crash on iOS Safari 12

- docs/data/base/getting-started/installation/installation.md
- docs/data/material/guides/migration-v3/migration-v3.md
- packages/mui-material/src/Snackbar/Snackbar.js
Spotted in the lastest ahrefs crawl.
> [docs] Fix SEO issues

- docs/data/material/guides/localization/localization.md
- packages/mui-material/src/locale/index.ts
- [ x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/material-ui/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).
Just adding localization for Macedonian language
> [docs] Add Macedonian translation

- docs/data/material/components/checkboxes/checkboxes-zh.md
> [docs] Fix demo filename on zh markdown

- packages/mui-styled-engine-sc/src/GlobalStyles/GlobalStyles.d.ts
- packages/mui-styled-engine-sc/src/GlobalStyles/GlobalStyles.spec.tsx
- packages/mui-styled-engine/src/GlobalStyles/GlobalStyles.d.ts
- packages/mui-styled-engine/src/GlobalStyles/GlobalStyles.spec.tsx
Closes https://github.com/mui/material-ui/issues/30817
> [styled-engine-sc] GlobalStylesProps inconsistent between the different packages

- docs/src/modules/utils/helpers.ts
**Before**
https://mui.com/base/api/menu-unstyled/ 
**After**
https://mui.com/material-ui/api/accordion-actions/
> [docs] Fix side nav capitalization of API

- packages/mui-material/test/typescript/OverridableComponent.spec.tsx
- packages/mui-material/test/typescript/index.spec.tsx
Adds tests for https://github.com/mui/material-ui/issues/31928 https://github.com/mui/material-ui/issues/31932
> [test] Add tests for component using `StandardProps` and polymorphic components

- docs/translations/api-docs/autocomplete/autocomplete.json
- packages/mui-base/src/AutocompleteUnstyled/useAutocomplete.d.ts
- packages/mui-material/src/Autocomplete/Autocomplete.js
Closes https://github.com/mui/material-ui/issues/31202
> [docs] Fix the documention for `filterOptions` in Autocomplete API page

- docs/data/material/components/rating/HoverRating.js
- docs/data/material/components/rating/HoverRating.tsx
- docs/data/material/components/rating/HoverRating.tsx.preview
Fixes https://github.com/mui/material-ui/issues/31364
Deploy preview: https://deploy-preview-31970--material-ui.netlify.app/components/rating/#hover-feedback
> [docs] Improve the a11y on the hover rating demo

- docs/data/material/components/paper/paper.md
- docs/data/material/getting-started/supported-platforms/supported-platforms.md
- docs/src/pages/production-error/ErrorDecoder.js
> [docs] Correct typos

- docs/data/material/components/text-fields/text-fields.md
> [docs] Add react-hook-form-mui to Complementary projects

- packages/material-ui/src/TableHead/TableHead.d.ts
Should've been part of https://github.com/mui/material-ui/pull/32041
> [TableHead] Fix TypeScript 4.7 compat issues

- docs/data/base/components/modal/modal.md
- docs/pages/base/api/form-control-unstyled.json
I think we put the most work into this doc before merging it, so it was already 99% done before this PR.
I've just made a few tiny style edits, and suggested a format for the title that I think we should use across all of these pages: **Unstyled React {{name}} component (and hook)**
> [docs] Base Modal style revisions and final review

- docs/data/base/components/input/input.md
- docs/pages/base/api/form-control-unstyled.json
This page already got lots of love in the first draft so almost nothing has changed here other than a couple tiny style updates for consistency.
> [docs] Base Input style revisions and final review

- docs/data/base/components/select/select.md
- docs/pages/base/api/form-control-unstyled.json
This PR updates the title to match the format proposed in #32093 and clarifies some wording in one sentence. Otherwise I think it's ready to go!
Does it make sense to name the hook in the title as I've done here? Would it make a difference for searching the docs/SEO? Edit: the answer is no! They get too dense when there are multiple hooks to name.
> [docs] Base Select style revisions and final review

- docs/data/base/components/trap-focus/trap-focus-pt.md
- docs/data/base/components/trap-focus/trap-focus-zh.md
- docs/data/material/customization/unstyled-components/unstyled-components-zh.md
- docs/src/modules/components/AppNavDrawer.js
> [docs] Fix 404 from `ahrefs` report

- docs/notifications.json
> [docs] Add notification for the doc restructure and date pickers update

- docs/public/_redirects
> [docs] Fix date-pickers redirects

- docs/pages/blog/lab-date-pickers-to-mui-x.md
Found by [ahrefs](https://app.ahrefs.com/site-audit/2944028/41/data-explorer?columns=pageRating%2Curl%2Ctraffic%2ChttpCode%2CcontentType%2Cdepth%2ClinksInternal4xx%2ClinksInternal5xx%2ClinksCountInternal4xx%2ClinksCountInternal5xx%2ClinksExternal4xx%2ClinksExternal5xx%2ClinksCountExternal4xx%2ClinksCountExternal5xx&filterCollapsed=true&filterId=2ba916be8a15982c0bb9bdae70ab1991&issueId=c64daf06-d0f4-11e7-8ed1-001e67ed4656&udUrl=https%3A%2F%2Fmui.com%2Fblog%2Flab-date-pickers-to-mui-x%2F) audit.
> [docs] Fix wrong url

- packages/mui-base/package.json
- packages/mui-docs/package.json
- packages/mui-icons-material/package.json
- packages/mui-joy/package.json
- packages/mui-lab/package.json
- packages/mui-material-next/package.json
- packages/mui-material/package.json
- packages/mui-private-theming/package.json
- packages/mui-styles/package.json
- packages/mui-system/package.json
Act on https://github.com/mui/material-ui/pull/32063#discussion_r841103006
> [core] Fix misleading types range

- CHANGELOG.old.md
- docs/data/material/discover-more/showcase/appList.js
- docs/pages/blog/2019.md
- docs/pages/blog/2020.md
- docs/pages/blog/docs-restructure-2022.md
- docs/pages/blog/material-ui-v4-is-out.md
- docs/pages/blog/mui-core-v5.md
- docs/pages/blog/september-2019-update.md
- docs/public/_redirects
- packages/mui-base/package.json
- packages/mui-lab/package.json
- packages/mui-material-next/package.json
- packages/mui-material/package.json
- packages/mui-styles/README.md
- packages/mui-styles/package.json
There are more issues like this, I don't have the time to take care of them all.
> [docs] Fix small external links issue

- packages/mui-joy/src/styles/styleFunctionSx.ts
- packages/mui-system/src/index.d.ts
- packages/mui-system/src/style.js
- packages/mui-system/src/style.test.js
The PR updates the `style` function inside the system to pull values automatically from the `vars` if they exist. If we decide to go in this direction, I will simplify the style function for the sx prop in Joy.
> [system] Update style function to use vars automatically if available

- test/utils/setupBabel.js
Corrected the path separators in setupBabel so unit tests can run under Windows.
> [test] Fix running unit tests on Windows

- docs/data/material/guides/right-to-left/right-to-left.md
Updated the RTL guide based on https://github.com/mui/material-ui/pull/32194#issuecomment-1093133181
Closes #32022
Preview: https://deploy-preview-32242--material-ui.netlify.app/guides/right-to-left/#1-html
> [docs] Update RTL guide

- docs/src/components/header/HeaderNavBar.tsx
- docs/src/components/header/HeaderNavDropdown.tsx
closes #32243 
Try clicking "Docs" in the previews:
- https://deploy-preview-32290--material-ui.netlify.app/x/
- https://deploy-preview-32290--material-ui.netlify.app
---
> [docs] Link to advanced components page

- docs/src/modules/components/AppNavDrawer.js
I was looking into fixing an SEO issue and noticed a couple of opportunities to polish this file. I have done one commit per opportunity, so it's easy to review.
https://deploy-preview-32237--material-ui.netlify.app/material-ui/getting-started/installation/
> [core] Remove unecessary div

- docs/data/material/components/lists/GutterlessList.js
- docs/data/material/components/lists/GutterlessList.tsx
- docs/data/material/components/lists/GutterlessList.tsx.preview
> [docs] Add `aria-label` for `IconButton`

- docs/data/base/components/trap-focus/trap-focus.md
This PR reviews the Base `TrapFocus` document.  I did a fair bit of rewriting and reorganizing on this one.
> [docs] Base TrapFocus style revisions and final review

- docs/src/pages/components/typography/typography.md
> [docs] Fix broken fontsource link

- docs/pages/blog/lab-date-pickers-to-mui-x.md
Things that I noticed while working on #32323 and is a follow-up on #31831.
https://deploy-preview-32325--material-ui.netlify.app/blog/lab-date-pickers-to-mui-x/
> [blog] A few improvements on date picker change

- docs/data/material/components/tables/ReactVirtualizedTable.js
- docs/data/material/components/tables/ReactVirtualizedTable.tsx
- docs/src/modules/components/TopLayoutBlog.js
- docs/src/pages/premium-themes/onepirate/modules/components/Markdown.js
- docs/src/pages/premium-themes/onepirate/modules/components/Markdown.tsx
- docs/src/pages/premium-themes/onepirate/modules/components/Snackbar.js
- docs/src/pages/premium-themes/onepirate/modules/components/Snackbar.tsx
- docs/src/pages/premium-themes/onepirate/modules/components/TextField.js
- docs/src/pages/premium-themes/onepirate/modules/components/TextField.tsx
- docs/src/pages/premium-themes/onepirate/modules/components/Typography.js
- docs/src/pages/premium-themes/onepirate/modules/components/Typography.tsx
It's time, let's finish this up. Closes https://github.com/mui/material-ui/issues/16947
> [docs] Cleanup remaining @mui/styles usages

- scripts/releaseChangelog.js
While going through the changelog generation process, I noticed what I believe to be a typo in the warning message.
> [core] Fix changelog script warning message

- docs/pages/careers.tsx
Getting close to filling this role so guess it's time to remove it.
> [website] Remove designer role from Careers page

- docs/data/system/shadows/shadows.md
> [docs] Fix grammar mistake in `shadows.md`

- docs/data/material/components/snackbars/snackbars.md
> [docs] Fix import path in the Snackbar article

- .markdownlint.jsonc
- docs/packages/markdown/parseMarkdown.js
- docs/pages/experiments/docs/callouts.js
- docs/pages/experiments/docs/callouts.md
- docs/src/modules/components/MarkdownElement.js
closes #31815 
**Preview**: https://deploy-preview-32402--material-ui.netlify.app/experiments/docs/callouts/
Use custom markdown syntax (similar to Docusaurus)
```md
:::info
This is an info alert — check it out!
:::
:::warning
This is an warning alert — check it out!
:::
:::success
This is an success alert — check it out!
:::
:::error
This is an error alert — check it out!
:::
```
> [docs] Support callouts

- docs/pages/blog/2021-developer-survey-results.md
- docs/pages/blog/2021.md
- docs/pages/blog/introducing-the-row-grouping-feature.md
- docs/pages/blog/mui-x-v5.md
Follow up to #4441, do not merge / release before X releases its next version
> [docs] Update links to the new Group & Pivot pages

- docs/pages/experiments/material-ui/css-vars-template.tsx
https://github.com/mui/material-ui/issues/32049 Use template to create new pages to prevent code conflict from multiple PRs.
> [experiment] Add template for testing Material UI components with CSS variables

- docs/data/base/components/textarea-autosize/textarea-autosize.md
This PR reviews the Base `TextareaAutosize` document. I revised the description and introduction for clarity.
> [docs] Base TextareaAutosize style revisions and final review

- docs/pages/experiments/material-ui/badge.tsx
- packages/mui-material/src/Badge/Badge.js
Preview: https://deploy-preview-32516--material-ui.netlify.app/experiments/material-ui/badge/
> [Badge] Add support for CSS variables

- docs/pages/experiments/material-ui/avatar-group.tsx
- packages/mui-material/src/AvatarGroup/AvatarGroup.js
Preview: https://deploy-preview-32507--material-ui.netlify.app/experiments/material-ui/avatar-group/
> [AvatarGroup] Add support for CSS variables

- docs/data/material/getting-started/support/support.md
- docs/pages/blog/2021-developer-survey-results.md
- docs/pages/blog/mui-core-v5.md
- docs/public/_redirects
- docs/src/components/pricing/PricingTable.tsx
Goes hand in hand with https://github.com/mui/mui-x/pull/4711
- Fix one regression from https://github.com/mui/material-ui/pull/31878/files#r862370331
> [docs] SEO fixes

- package.json
> v5.6.4 (Fix repo `package.json`)

- packages/mui-material/src/styles/ThemeProvider.d.ts
- packages/mui-system/src/ThemeProvider/ThemeProvider.d.ts
Use full api link for ThemeProvider
> [docs] Use full API link for ThemeProvider

- docs/pages/experiments/material-ui/dialog-content.tsx
- packages/mui-material/src/DialogContent/DialogContent.js
Preview: https://deploy-preview-32555--material-ui.netlify.app/experiments/material-ui/dialog-content/
Within the dialog there is a light/dark switch to better review the implementation. 🤓
> [Dialog] Add support for CSS variables

- docs/pages/experiments/material-ui/rating.tsx
- packages/mui-material/src/Rating/Rating.js
Preview: https://deploy-preview-32556--material-ui.netlify.app/experiments/material-ui/rating/
> [Rating] Add support for CSS variables

- docs/data/material/components/material-icons/SearchIcons.js
- docs/src/modules/components/HighlightedCode.js
close #32559. will merge and deploy the docs after all CIs are green.
> [docs] Hide copy button on search icon dialog

- docs/pages/experiments/material-ui/list-subheader.tsx
- packages/mui-material/src/ListSubheader/ListSubheader.js
One of #32049 
Preview: https://deploy-preview-32584--material-ui.netlify.app/experiments/material-ui/list-subheader/
> [ListSubheader] Add support for CSS variables

- docs/pages/experiments/material-ui/list-item-icon.tsx
- packages/mui-material/src/ListItemIcon/ListItemIcon.js
One of #32049 
Preview: https://deploy-preview-32583--material-ui.netlify.app/experiments/material-ui/list-item-icon/
(I'm not sure if this at reference is working because it doesn't show as a link)
> [ListItemIcon] Add support for CSS variables

- docs/pages/experiments/material-ui/list-item-button.tsx
- packages/mui-material/src/ListItemButton/ListItemButton.js
One of #32049 
(I'm not sure if this at reference is working because it doesn't show as a link)
> [ListItemButton] Add support for CSS variables

- docs/pages/experiments/material-ui/card-action-area.tsx
- packages/mui-material/src/CardActionArea/CardActionArea.js
Preview: https://deploy-preview-32554--material-ui.netlify.app/experiments/material-ui/card-action-area/
> [Card] Add support for CSS variables 

- docs/pages/experiments/material-ui/autocomplete.tsx
- packages/mui-material/src/Autocomplete/Autocomplete.js
One of #32049 
**Preview:** https://deploy-preview-32598--material-ui.netlify.app/experiments/material-ui/autocomplete/
> [Autocomplete] Add support for CSS variables

- docs/pages/experiments/material-ui/menu-item.tsx
- packages/mui-material/src/MenuItem/MenuItem.js
Preview: https://deploy-preview-32561--material-ui.netlify.app/experiments/material-ui/menu-item/
> [MenuItem] Add support for CSS variables

- docs/pages/experiments/material-ui/drawer.tsx
- packages/mui-material/src/Drawer/Drawer.js
Preview: https://deploy-preview-32565--material-ui.netlify.app/experiments/material-ui/drawer/
> [Drawer] Add support for CSS variables

- docs/pages/experiments/material-ui/speed-dial.js
- packages/mui-material/src/SpeedDial/SpeedDial.js
Preview: https://deploy-preview-32613--material-ui.netlify.app/experiments/material-ui/speed-dial/
> [SpeedDial] Add support for CSS variables

- docs/pages/experiments/material-ui/modal.tsx
- packages/mui-material/src/Modal/Modal.js
Add support for CSS variables for `Modal` 
(#32049).
of the contributing guide](https://github.com/mui/material-ui/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).
> [Modal] Add support for CSS variables

- docs/pages/experiments/material-ui/table-pagination.tsx
- packages/mui-material/src/TablePagination/TablePagination.js
Add support for CSS variables for the component `TablePagination` 
component (#32049).
guide](https://github.com/mui/material-ui/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).
> [TablePagination] Add support for CSS vars

- docs/pages/experiments/material-ui/step.tsx
- packages/mui-material/src/StepIcon/StepIcon.js
- packages/mui-material/src/StepLabel/StepLabel.js
Preview: https://deploy-preview-32609--material-ui.netlify.app/experiments/material-ui/step/
> [StepLabel, StepIcon] Add support for CSS variables

- docs/pages/experiments/material-ui/snackbar.tsx
- packages/mui-material/src/Snackbar/Snackbar.js
Preview: https://deploy-preview-32603--material-ui.netlify.app/experiments/material-ui/snackbar/
> [Snackbar] Add support for CSS variables

- docs/src/modules/components/AppNavDrawer.js
We need this for https://github.com/mui/mui-x/pull/4692 started by @samuelsycamore
> [docs] Show product identifier on new X pages

- docs/data/joy/getting-started/principles/principles.md
- docs/data/joy/pages.ts
- docs/pages/joy-ui/getting-started/principles.js
**Preview**: https://deploy-preview-32648--material-ui.netlify.app/joy-ui/getting-started/principles/
It's time to share Joy's principles with the world!
The content is from:
- https://www.notion.so/mui-org/Product-principles-9453ff41162d40c18d946849e6cfb013
- https://www.notion.so/mui-org/Joy-Principles-f6fa5f8f0cf64067a8a0227bec0b7068
---
> [Joy] Add principles page

- packages/mui-base/src/AutocompleteUnstyled/useAutocomplete.js
- packages/mui-base/src/AutocompleteUnstyled/useAutocomplete.test.js
Resolves #32272 
- [✅ ] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/material-ui/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).
> [Autocomplete] Fix clearing single array values

- CHANGELOG.md
Corrected the invalid version of @mui/base in the changelog
> [changelog] Correct @mui/base version

- docs/data/base/components/menu/MenuSimple.js
- docs/data/base/components/menu/MenuSimple.tsx
- docs/data/base/components/menu/UseMenu.js
- docs/data/base/components/menu/UseMenu.tsx
- docs/data/base/components/menu/WrappedMenuItems.js
- docs/data/base/components/menu/WrappedMenuItems.tsx
- docs/pages/base/api/menu-unstyled.json
- docs/translations/api-docs/menu-unstyled/menu-unstyled.json
- packages/mui-base/src/MenuItemUnstyled/MenuItemUnstyled.tsx
- packages/mui-base/src/MenuItemUnstyled/useMenuItem.ts
- packages/mui-base/src/MenuUnstyled/MenuUnstyled.tsx
- packages/mui-base/src/MenuUnstyled/MenuUnstyled.types.ts
Addressed comments from https://github.com/mui/material-ui/pull/32661#issue-1228340370
Also made the menu buttons look less like Select components and more like actual buttons
> [MenuUnstyled] Demos improvements

- docs/notifications.json
- docs/src/modules/components/Notifications.js
Add notification for Premium release blog post. (To merge after new plan's release)
> [docs] Add notification for Premium release blog post

- .github/renovate.json
Enabled automatic lockfile maintenance, as suggested in https://github.com/mui/material-ui/pull/32575#pullrequestreview-960151104
> [core] Enabled Renovate's lockfile maintenance

- packages/mui-material/src/locale/index.ts
I hope you accept this PR. just making the translation more accurate and fix some errors.
> [l10n] Fix typos and translations on arSD and arEG locales

- docs/src/modules/components/MarkdownElement.js
Follow up to https://github.com/mui/material-ui/pull/32567#issuecomment-1121116347!
https://deploy-preview-32709--material-ui.netlify.app/experiments/docs/callouts/
> [docs] Improve callouts design

- README.md
- docs/data/material/discover-more/backers/backers.md
> [docs] Update Crowdin logo

- docs/src/components/productX/XComponents.tsx
- docs/src/components/productX/XDateRangeDemo.tsx
- docs/src/components/productX/XTreeViewDemo.tsx
Closes https://github.com/mui/mui-x/issues/4782
**To-dos:**
What else can we do? Should we add to the Date range picker as well?! Add more text content?
> [website] Improve communication about MUI X components that are still wip

- docs/data/joy/components/badge/AccessibleBadges.js
- docs/data/joy/components/badge/AccessibleBadges.tsx
- docs/data/joy/components/badge/AccessibleBadges.tsx.preview
- docs/data/joy/components/badge/BadgeAlignment.js
- docs/data/joy/components/badge/BadgeAlignment.tsx
- docs/data/joy/components/badge/BadgeInset.js
- docs/data/joy/components/badge/BadgeInset.tsx
- docs/data/joy/components/badge/BadgeInset.tsx.preview
- docs/data/joy/components/badge/BadgeMax.js
- docs/data/joy/components/badge/BadgeMax.tsx
- docs/data/joy/components/badge/BadgeMax.tsx.preview
- docs/data/joy/components/badge/BadgeUsage.js
- docs/data/joy/components/badge/BadgeVisibility.js
- docs/data/joy/components/badge/BadgeVisibility.tsx
- docs/data/joy/components/badge/BadgeVisibility.tsx.preview
- docs/data/joy/components/badge/ContentBadge.js
- docs/data/joy/components/badge/ContentBadge.tsx
- docs/data/joy/components/badge/ContentBadge.tsx.preview
- docs/data/joy/components/badge/NumberBadge.js
- docs/data/joy/components/badge/NumberBadge.tsx
- docs/data/joy/components/badge/SimpleBadge.js
- docs/data/joy/components/badge/SimpleBadge.tsx
- docs/data/joy/components/badge/SimpleBadge.tsx.preview
- docs/data/joy/components/badge/badge.md
- docs/data/joy/pages.ts
- docs/pages/joy-ui/react-badge.js
- docs/src/modules/components/HighlightedCode.js
- docs/types/docs.d.ts
- packages/mui-joy/src/styles/extendTheme.ts
**Preview**: https://deploy-preview-32790--material-ui.netlify.app/joy-ui/react-badge/
> [Joy] Add `Badge` doc

- docs/pages/experiments/material-ui/radio.tsx
- packages/mui-material/src/Radio/Radio.js
- packages/mui-material/src/styles/CssVarsProvider.test.js
- packages/mui-material/src/styles/createPalette.d.ts
- packages/mui-material/src/styles/experimental_extendTheme.js
- packages/mui-material/src/styles/experimental_extendTheme.test.js
Preview: https://deploy-preview-32599--material-ui.netlify.app/experiments/material-ui/radio/
> [Radio] Add support for CSS variables

- packages/mui-material/src/ListItemButton/ListItemButton.js
- packages/mui-material/src/ListItemButton/ListItemButton.test.js
> [ListItemButton] Render as link if href specified

- packages/mui-lab/package.json
Added missing peerDependencies in order to not break projects using yarn pnp. 
Closes #32620
> [lab] Add missing peerDependencies

- docs/data/material/components/icons/icons.md
> [docs] Fixed broken link on the icons page

- docs/data/joy/components/card/BasicCard.js
- docs/data/joy/components/card/CardCovers.js
- docs/data/joy/components/card/CardVariables.js
- docs/data/joy/components/card/ContainerResponsive.js
- docs/data/joy/components/card/DribbbleShot.js
- docs/data/joy/components/card/GradientCover.js
- docs/data/joy/components/card/InstagramPost.js
- docs/data/joy/components/card/InteractiveCard.js
- docs/data/joy/components/card/MediaCover.js
- docs/data/joy/components/card/MultipleInteractionCard.js
- docs/data/joy/components/card/OverflowCard.js
- docs/data/joy/components/card/card.md
- docs/data/joy/pages.ts
- docs/pages/experiments/joy/card.tsx
- docs/pages/joy-ui/react-card.js
- packages/mui-joy/src/AspectRatio/AspectRatio.tsx
- packages/mui-joy/src/Card/Card.tsx
- packages/mui-joy/src/CardCover/CardCover.tsx
- packages/mui-joy/src/CardOverflow/CardOverflow.tsx
- packages/mui-joy/src/Link/Link.tsx
**Preview**: https://deploy-preview-32825--material-ui.netlify.app/joy-ui/react-card/
> [Joy] Add doc for the card components

- docs/src/components/pricing/PricingTable.tsx
Fix tweet https://twitter.com/monirom/status/1527388230353489920
> [docs] Fix urls to columns pages in pricing table

- docs/data/joy/getting-started/tutorial/tutorial.md
- docs/src/route.ts
The URLs were changed in #32883 but the links are not updated. Will merge once the CIs are green.
> [Joy] Fix wrong urls

- docs/data/joy/components/aspect-ratio/BasicRatio.js
- docs/data/joy/components/aspect-ratio/CarouselRatio.js
- docs/data/joy/components/aspect-ratio/CustomRatio.js
- docs/data/joy/components/aspect-ratio/FlexRowRatio.js
- docs/data/joy/components/aspect-ratio/ListStackRatio.js
- docs/data/joy/components/aspect-ratio/MediaRatio.js
- docs/data/joy/components/aspect-ratio/MinMaxRatio.js
- docs/data/joy/components/aspect-ratio/aspect-ratio.md
- docs/data/joy/components/card/ContainerResponsive.js
- docs/data/joy/components/card/InteractiveCard.js
- docs/data/joy/pages.ts
- docs/pages/experiments/joy/card.tsx
- docs/pages/joy-ui/react-aspect-ratio.js
- packages/mui-joy/src/AspectRatio/AspectRatio.tsx
- packages/mui-joy/src/AspectRatio/AspectRatioProps.ts
- packages/mui-joy/src/AspectRatio/aspectRatioClasses.ts
**Preview**: https://deploy-preview-32848--material-ui.netlify.app/joy-ui/react-aspect-ratio/
> [Joy] Add `AspectRatio` demos

- docs/pages/blog.tsx
- docs/src/modules/components/TopLayoutBlog.js
Fix https://github.com/mui/material-ui/pull/32720#issuecomment-1122744019
https://deploy-preview-32890--material-ui.netlify.app/blog/premium-plan-release/
> [blog] Fix avatar image resolution

- docs/src/modules/components/AppSearch.js
A follow-up on #32844.
https://deploy-preview-32940--material-ui.netlify.app/material-ui/react-alert/
> [core] Remove dead logic

- docs/pages/base/api/button-unstyled.json
- packages/mui-base/src/ButtonUnstyled/ButtonUnstyled.test.tsx
- packages/mui-base/src/ButtonUnstyled/ButtonUnstyled.tsx
- packages/mui-base/src/ButtonUnstyled/ButtonUnstyled.types.ts
- test/utils/describeConformanceUnstyled.tsx
Part of #32144.
Additionally, I modified the conformance tests to check if class names from componentsProps are merged correctly.
> [ButtonUnstyled] Accept callbacks in componentsProps

- docs/pages/base/api/switch-unstyled.json
- packages/mui-base/src/SwitchUnstyled/SwitchUnstyled.test.tsx
- packages/mui-base/src/SwitchUnstyled/SwitchUnstyled.tsx
- packages/mui-base/src/SwitchUnstyled/SwitchUnstyled.types.ts
> [SwitchUnstyled] Accept callbacks in componentsProps

- docs/data/base/getting-started/overview/overview.md
- docs/data/base/getting-started/usage/usage.md
- docs/data/joy/getting-started/overview/overview.md
- docs/data/joy/getting-started/usage/usage.md
- docs/data/material/getting-started/overview/overview.md
- docs/src/modules/components/MarkdownElement.js
- docs/src/route.ts
> [docs] Polish overview page to Material UI

- docs/public/_redirects
The objective is to reduce the number of 404 reported by Google
https://search.google.com/search-console/index/drilldown?resource_id=sc-domain%3Amui.com&item_key=CAMYDSAC&hl=en
> [docs] Redirect older URLs

- docs/data/joy/core-features/perfect-dark-mode/perfect-dark-mode.md
- docs/data/joy/guides/apply-dark-mode/ModeToggle.js
- docs/data/joy/guides/apply-dark-mode/apply-dark-mode.md
- docs/data/joy/pages.ts
- docs/pages/joy-ui/core-features/perfect-dark-mode.js
- docs/pages/joy-ui/guides/apply-dark-mode.js
- [core-features/perfect-dark-mode](https://deploy-preview-33002--material-ui.netlify.app/joy-ui/core-features/perfect-dark-mode/)
- [guides/apply-dark-mode](https://deploy-preview-33002--material-ui.netlify.app/joy-ui/guides/apply-dark-mode/)
---
> [Joy] Add docs about dark mode

- packages/mui-codemod/src/v5.0.0/jss-to-tss-react.js
- packages/mui-codemod/src/v5.0.0/jss-to-tss-react.test/actual-todo-comments.js
- packages/mui-codemod/src/v5.0.0/jss-to-tss-react.test/expected-todo-comments.js
This is addressing the issue pointed out by @joshkel in #32988, but the approach I wanted to use to address the bug was different enough that it was simpler to put it in a new pull request.
> [codemod] Fix infinite loop in jss-to-tss-react and add TODO

- packages/mui-codemod/src/v5.0.0/jss-to-tss-react.js
- packages/mui-codemod/src/v5.0.0/jss-to-tss-react.test.js
- packages/mui-codemod/src/v5.0.0/jss-to-tss-react.test/actual-from-mui-styles-makeStyles.js
- packages/mui-codemod/src/v5.0.0/jss-to-tss-react.test/expected-from-mui-styles-makeStyles.js
> [codemod] Add support for `@mui/styles/makeStyles` imports

- CONTRIBUTING.md
Testing and debugging locally was a huge hassle and was very time consuming, especially for a beginner like me who has to console.log everything to understand what's going on. These instructions, will help save a lot of time debugging user changes. 
Furthermore, these changes can later further be incorporated into a script to automate the whole process.
> [Contributing.md] Local install instructions

- docs/data/material/getting-started/overview/overview.md
- docs/src/pages/versions/versions.md
- docs/src/route.ts
- packages/mui-material-next/package.json
- packages/mui-material/package.json
An iteration on #32643.
I was working on https://github.com/docker/extensions-sdk/pull/190 and following some of the links that they have in their documentation. It then became obvious, I feel that we missed the elephant in the room: customizations. It's referred to in:
- https://mui.com/blog/2021-developer-survey-results/#what-are-your-most-important-criteria-for-choosing-a-ui-library
- https://mui.com/blog/2021-developer-survey-results/#what-is-the-main-benefit-you-get-from-using-mui
As a follow-up, I think that one thing that could be awesome is to get upfront with the fears that developers have on this page. We could imagine having:
```
```
https://deploy-preview-33014--material-ui.netlify.app/material-ui/getting-started/overview/
> [docs] Add customization as a value proposition

- packages/mui-base/src/ButtonUnstyled/ButtonUnstyled.tsx
- packages/mui-base/src/ButtonUnstyled/ButtonUnstyled.types.ts
Prepare slots' props with the useSlotProps hook.
> [ButtonUnstyled] Use useSlotProps

- docs/pages/base/api/badge-unstyled.json
- docs/pages/material-ui/api/badge.json
- packages/mui-base/src/BadgeUnstyled/BadgeUnstyled.test.tsx
- packages/mui-base/src/BadgeUnstyled/BadgeUnstyled.tsx
- packages/mui-base/src/BadgeUnstyled/BadgeUnstyled.types.ts
- packages/mui-joy/src/Badge/Badge.tsx
- packages/mui-material/src/Badge/Badge.js
> [BadgeUnstyled] Accept callbacks in componentsProps

- docs/src/pages/careers/react-engineer-core.md
- docs/src/pages/careers/react-engineer-x.md
- docs/src/pages/careers/react-support-engineer.md
These are the 3 jobs that are currently migrated.
> [website] Replace Airtable with Ashby links for applying to a opened position

- docs/data/joy/components/checkbox/BasicCheckbox.js
- docs/data/joy/components/checkbox/CheckboxUsage.js
- docs/data/joy/components/checkbox/ExampleChoiceChipCheckbox.js
- docs/data/joy/components/checkbox/ExampleFilterMemberCheckbox.js
- docs/data/joy/components/checkbox/ExampleFilterStatusCheckbox.js
- docs/data/joy/components/checkbox/FocusCheckbox.js
- docs/data/joy/components/checkbox/GroupCheckboxes.js
- docs/data/joy/components/checkbox/HoverCheckbox.js
- docs/data/joy/components/checkbox/IconlessCheckbox.js
- docs/data/joy/components/checkbox/IconsCheckbox.js
- docs/data/joy/components/checkbox/IndeterminateCheckbox.js
- docs/data/joy/components/checkbox/OverlayCheckbox.js
- docs/data/joy/components/checkbox/checkbox.md
- docs/data/joy/pages.ts
- docs/pages/joy-ui/react-checkbox.js
- docs/src/modules/components/JoyUsageDemo.tsx
- packages/mui-joy/src/Checkbox/CheckboxProps.ts
- packages/mui-joy/src/Checkbox/checkboxClasses.ts
**Preview**: https://deploy-preview-33171--material-ui.netlify.app/joy-ui/react-checkbox/
---
> [Joy] Add Checkbox documentation

- docs/pages/blog/premium-plan-release.md
- Trying to make clear that the disclaimer on pricing does not relate to row grouping.
- Trying to point out that since the beginning row grouping was only temporary on Pro.
preview: https://deploy-preview-33131--material-ui.netlify.app/blog/premium-plan-release/
> [blog] Update Blogpost to clear confusion on "no impact" disclaimer.

- docs/pages/base/api/form-control-unstyled.json
- docs/translations/api-docs/form-control-unstyled/form-control-unstyled.json
- packages/mui-base/src/FormControlUnstyled/FormControlUnstyled.spec.tsx
- packages/mui-base/src/FormControlUnstyled/FormControlUnstyled.test.tsx
- packages/mui-base/src/FormControlUnstyled/FormControlUnstyled.tsx
- packages/mui-base/src/FormControlUnstyled/FormControlUnstyled.types.ts
- packages/mui-base/src/FormControlUnstyled/formControlUnstyledClasses.ts
> [FormControlUnstyled] Accept callbacks in componentsProps

- docs/next.config.js
- docs/packages/markdown/parseMarkdown.js
- docs/pages/_app.js
- docs/src/modules/components/Link.tsx
- docs/src/modules/constants.js
A quick fix for https://twitter.com/stackFlam1ngo/status/1536871044958433280
I have created https://mui-org.notion.site/Localization-Chinese-version-of-the-website-docs-3f370280b58f446fbb5559dfc08fe03e to improve our rigor around the decision of dropping the translations (I suspect that in 2-3 years from now, the topic could come again).
> [blog] Fix infinite redirection

- docs/data/joy/components/list/ExampleIOSList.js
- docs/data/joy/components/switch/ExampleChakraSwitch.js
- docs/data/joy/components/switch/ExampleFluentSwitch.js
- docs/data/joy/components/switch/ExampleIosSwitch.js
- docs/data/joy/components/switch/ExampleMantineSwitch.js
- docs/data/joy/components/switch/ExampleMaterialSwitch.js
- docs/data/joy/components/switch/ExampleStrapiSwitch.js
- docs/data/joy/components/switch/ExampleTailwindSwitch.js
- docs/data/joy/components/switch/ExampleThumbChild.js
- docs/data/joy/components/switch/ExampleTrackChild.js
- docs/data/joy/components/switch/SwitchControlled.js
- docs/data/joy/components/switch/SwitchDecorators.js
- docs/data/joy/components/switch/SwitchLabel.js
- docs/data/joy/components/switch/SwitchUsage.js
- docs/data/joy/components/switch/SwitchVariables.js
- docs/data/joy/components/switch/switch.md
- docs/data/joy/pages.ts
- docs/pages/joy-ui/react-switch.js
- docs/src/modules/components/JoyUsageDemo.tsx
- docs/src/modules/components/JoyVariablesDemo.tsx
- packages/mui-joy/src/Switch/Switch.tsx
> [Joy] Add switch documentation

- docs/data/material/components/slider/MusicPlayerSlider.js
- docs/data/material/components/slider/MusicPlayerSlider.tsx
In the **Slider**  component [example](https://mui.com/material-ui/react-slider/#music-player
), the time display is a bit of a problem.
So the time should be displayed as "0:09"
> [docs] Fix Slider's "player" demo

- docs/pages/base/api/table-pagination-unstyled.json
- docs/translations/api-docs/table-pagination-unstyled/table-pagination-unstyled.json
- packages/mui-base/src/SliderUnstyled/SliderUnstyled.test.js
- packages/mui-base/src/TablePaginationUnstyled/TablePaginationActionsUnstyled.tsx
- packages/mui-base/src/TablePaginationUnstyled/TablePaginationActionsUnstyled.types.ts
- packages/mui-base/src/TablePaginationUnstyled/TablePaginationUnstyled.test.tsx
- packages/mui-base/src/TablePaginationUnstyled/TablePaginationUnstyled.tsx
- packages/mui-base/src/TablePaginationUnstyled/TablePaginationUnstyled.types.ts
- packages/mui-material-next/src/TablePagination/TablePagination.js
> [TablePaginationUnstyled] Accept callbacks in componentsProps

- docs/data/material/guides/server-rendering/server-rendering.md
> Correcting small grammatical error

- docs/pages/base/api/tab-panel-unstyled.json
- docs/pages/base/api/tab-unstyled.json
- docs/pages/base/api/tabs-list-unstyled.json
- docs/pages/base/api/tabs-unstyled.json
- packages/mui-base/src/TabPanelUnstyled/TabPanelUnstyled.test.tsx
- packages/mui-base/src/TabPanelUnstyled/TabPanelUnstyled.tsx
- packages/mui-base/src/TabPanelUnstyled/TabPanelUnstyled.types.ts
- packages/mui-base/src/TabUnstyled/TabUnstyled.test.tsx
- packages/mui-base/src/TabUnstyled/TabUnstyled.tsx
- packages/mui-base/src/TabUnstyled/TabUnstyled.types.ts
- packages/mui-base/src/TabsListUnstyled/TabsListUnstyled.test.tsx
- packages/mui-base/src/TabsListUnstyled/TabsListUnstyled.tsx
- packages/mui-base/src/TabsListUnstyled/TabsListUnstyled.types.ts
- packages/mui-base/src/TabsUnstyled/TabsUnstyled.test.tsx
- packages/mui-base/src/TabsUnstyled/TabsUnstyled.tsx
- packages/mui-base/src/TabsUnstyled/TabsUnstyled.types.ts
Part of #32144
Covers all Tab-related unstyled components
> [TabsUnstyled] Accept callbacks in componentsProps

- docs/src/components/pricing/PricingTable.tsx
preview: https://deploy-preview-32984--material-ui.netlify.app/pricing/
Following iteration on the pricing page.
https://github.com/mui/material-ui/pull/32811#pullrequestreview-990186700
> [website] Shorten the plan descriptions on the pricing page

- docs/data/joy/components/avatar/avatar.md
- docs/data/joy/components/radio/radio.md
- docs/data/joy/customization/theme-tokens/theme-tokens.md
- docs/data/joy/guides/applying-dark-mode/ModeToggle.js
- docs/data/joy/guides/applying-dark-mode/applying-dark-mode.md
- docs/data/joy/pages.ts
- docs/data/material/components/radio-buttons/radio-buttons.md
- docs/pages/blog/first-look-at-joy.md
- docs/public/_redirects
A quick follow-up on https://github.com/mui/material-ui/pull/33158#pullrequestreview-1033680049.
> [docs] Fix dead links

- packages/mui-base/src/ButtonUnstyled/useButton.types.ts
- packages/mui-base/src/InputUnstyled/useInput.types.ts
- packages/mui-base/src/ModalUnstyled/ModalUnstyled.types.ts
- packages/mui-base/src/SliderUnstyled/SliderUnstyled.types.ts
- packages/mui-base/src/SliderUnstyled/useSlider.types.ts
- packages/mui-base/src/TablePaginationUnstyled/TablePaginationActionsUnstyled.types.ts
- packages/mui-base/src/TablePaginationUnstyled/TablePaginationUnstyled.types.ts
- packages/mui-joy/src/Slider/SliderProps.ts
Exports recently introduced types that are parts of exported props' interfaces.
Fixes #33495
Fixes #33509
> [Base] Export types used by components' props

- docs/src/layouts/AppFooter.tsx
Given upcoming educational & marketing pushes, added easy access to MUI's YouTube channel in the footer.
> [website] Add YouTube link to footer

- packages/mui-lab/src/LoadingButton/LoadingButton.js
> [LoadingButton] Refactor duplicate code

- docs/data/material/components/alert/alert.md
Preview: https://deploy-preview-33586--material-ui.netlify.app/material-ui/react-alert/#toast
> [docs] Fix link to Snackbar customization section in Alert docs

- docs/public/_redirects
Merge after https://github.com/mui/mui-toolpad/pull/661 is merged
Fixes mui/mui-toolpad#660
https://deploy-preview-33524--material-ui.netlify.app/toolpad/
https://deploy-preview-33524--material-ui.netlify.app/toolpad/getting-started/setup/
> [docs] Fix Toolpad docs redirection

- docs/data/joy/guides/applying-dark-mode/applying-dark-mode.md
> [docs] Fix typo in Joy UI dark mode page

- docs/data/material/components/dividers/dividers.md
> [Divider] Add accessibility tips

- docs/src/components/footer/EmailSubscribe.tsx
Following up on the discussion happening on https://github.com/mui/material-ui/pull/32107 about styles for the Text Field.
**Deploy preview:** https://deploy-preview-33585--material-ui.netlify.app/
| Before (current)      | After |
| ----------- | ----------- |
| <img width="360" alt="Screen Shot 2022-07-20 at 16 47 48" src="https://user-images.githubusercontent.com/67129314/180068969-c4bbb224-6217-4b38-8ab2-96367f106435.png">  | <img width="360" alt="Screen Shot 2022-07-20 at 16 47 59" src="https://user-images.githubusercontent.com/67129314/180068979-9b346517-2e1c-4d63-9a74-9b2a9b384961.png">  |
> [website] Improve newsletter input design

- docs/pages/material-ui/api/dialog.json
- docs/pages/material-ui/api/modal.json
- packages/mui-material/src/Dialog/Dialog.js
- packages/mui-material/src/Modal/Modal.d.ts
- packages/mui-material/src/Modal/Modal.js
Addresses the comment in https://github.com/mui/material-ui/pull/32901#discussion_r910950208
> [Modal] Explain the meaning of deprecation of the BackdropComponent prop

- packages/mui-joy/README.md
Just copying content from the Overview page so it's consistent and more organized.
> [Joy] Update read.me content

- docs/pages/material-ui/api/input-base.json
- docs/translations/api-docs/input-base/input-base.json
- packages/mui-material/src/InputBase/InputBase.js
- packages/mui-material/src/InputBase/InputBase.test.js
- packages/mui-material/src/InputBase/inputBaseClasses.ts
Added the `readOnly` state class, to match the behavior of the `disabled` prop.
Fixes #33613.
> [Input] Add the readOnly state class

- packages/mui-joy/src/AvatarGroup/AvatarGroup.tsx
- packages/mui-joy/src/Badge/Badge.tsx
- packages/mui-joy/src/Card/Card.tsx
- packages/mui-joy/src/Input/Input.tsx
- packages/mui-joy/src/ListItem/ListItem.tsx
- packages/mui-joy/src/ListItemButton/ListItemButton.tsx
- packages/mui-joy/src/ListItemButton/ListItemButtonProps.ts
- packages/mui-joy/src/Menu/Menu.tsx
- packages/mui-joy/src/Select/Select.tsx
- packages/mui-joy/src/Sheet/Sheet.tsx
- packages/mui-joy/src/styles/types/colorSystem.ts
- packages/mui-system/src/cssVars/createCssVarsProvider.js
- test/regressions/fixtures/CssVarsProvider/ForceColorSchemes.js
> [Joy] Miscellaneous fixes

- docs/src/components/pricing/PricingTable.tsx
Update pricing table to add aggregation and row pinning (to be released in v.5.15.0  - next release)
https://deploy-preview-33659--material-ui.netlify.app/pricing
> [website] Update pricing table to add aggregation and row pinning

- docs/src/components/pricing/WhatToExpect.tsx
Complementary to https://github.com/mui/mui-store/pull/199
https://deploy-preview-33668--material-ui.netlify.app/pricing/
> [website] Clarify when a license in development is required

- docs/pages/blog/premium-plan-release.md
- docs/public/_redirects
- docs/src/components/pricing/FAQ.tsx
- docs/src/components/pricing/WhatToExpect.tsx
- docs/src/route.ts
This PR should be deployed before https://github.com/mui/mui-store/pull/196 can be merged, we would break the store otherwise.
https://deploy-preview-33650--material-ui.netlify.app/store/
https://deploy-preview-33650--material-ui.netlify.app/legal/
> [website] Add new legal pages

- packages/mui-material/src/StepLabel/StepLabel.js
- packages/mui-material/src/StepLabel/StepLabel.test.js
I have tested this fix locally and also tested using a preview package on CodeSandbox.
May close #33410
> [Stepper] Fix classes for icon container

- docs/pages/about.tsx
- docs/pages/blog.tsx
- docs/pages/careers.tsx
- docs/pages/components.tsx
- docs/pages/core.tsx
- docs/pages/design-kits.tsx
- docs/pages/index.tsx
- docs/pages/material-ui.tsx
- docs/pages/pricing.tsx
- docs/pages/templates.tsx
- docs/pages/x.tsx
- docs/src/BrandingProvider.tsx
- docs/src/modules/components/AppContainer.js
- docs/src/modules/components/AppFrame.js
- docs/src/modules/components/AppLayoutDocs.js
- docs/src/modules/components/SkipLink.tsx
- examples/base-cra-typescript/README.md
I have been annoyed by this bug for a long time. I would get distracted by it, randomly, every now and then. This weekend, I got again confused by it while I was working on https://github.com/mui/material-ui/pull/33706. The reproduction:
1. Open https://master--material-ui.netlify.app/blog/aggregation-functions/
2. Click on the main of the page
3. Press the <kbd>Arrow Down</kbd> key
4. 💥
I have used the opportunity to push the handling of the skip nav one step forward, as it's because of it that we had the bug in the first place.
Preview: https://deploy-preview-33707--material-ui.netlify.app/blog/aggregation-functions/
> [blog] Fix blue outline bug

- packages/mui-material/src/useScrollTrigger/useScrollTrigger.js
> [useScrollTrigger] Add passive flag to scroll trigger event listener #32437 

- docs/data/system/components/stack/stack.md
> [core] Avoid duplication of packageName

- packages/mui-joy/src/Card/Card.tsx
- packages/mui-joy/src/Card/CardProps.ts
> [Card][Joy] Fix wrong api description for `size` prop

- docs/data/material/components/steppers/HorizontalNonLinearStepper.js
- docs/data/material/components/steppers/HorizontalNonLinearStepper.tsx
I fixed https://github.com/mui/material-ui/issues/33695
> [docs] Improve the HorizontalNonLinearStepper demo styling

- docs/data/material/components/text-fields/CustomizedInputBase.js
- docs/data/material/components/text-fields/CustomizedInputBase.tsx
Fixes #33851 
Preview of changes - https://deploy-preview-33852--material-ui.netlify.app/material-ui/react-text-field/#customization
> [docs] Avoid refreshing the page when button on demo is clicked

- packages/mui-lab/src/TimelineDot/TimelineDot.js
Part of #33959 
CodeSandbox to test in - https://codesandbox.io/s/create-react-app-with-typescript-forked-247ix3
> [TimelineDot] Add support for CSS variables

- .github/CODEOWNERS
Specified owners of different areas of the code according to https://www.notion.so/mui-org/Product-owners-836c72feffcc4cb2b735b51527e6991a
About code owners: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
> [core] Specify code owners

- .circleci/config.yml
- test/regressions/index.js
Fix https://github.com/mui/material-ui/pull/33027#discussion_r956487227, found this in https://github.com/mui/material-ui/pull/33896#issuecomment-1229014429.
> [core] Fix prop-type warning in regression tests

- docs/data/joy/components/select/select.md
Signed-off-by: VelociRaptor <77036902+HexM7@users.noreply.github.com>
> [docs] Fix typo in `Select` component

- packages/mui-base/src/SelectUnstyled/useSelect.ts
> [Select][base] Fix typo in listbox blur event handler

- packages/mui-joy/src/AspectRatio/AspectRatio.tsx
- packages/mui-joy/src/AspectRatio/AspectRatioProps.ts
- packages/mui-joy/src/Avatar/Avatar.tsx
- packages/mui-joy/src/Avatar/AvatarProps.ts
- packages/mui-joy/src/Badge/Badge.tsx
- packages/mui-joy/src/Badge/BadgeProps.ts
- packages/mui-joy/src/Breadcrumbs/Breadcrumbs.tsx
- packages/mui-joy/src/Breadcrumbs/BreadcrumbsProps.ts
- packages/mui-joy/src/Button/Button.tsx
- packages/mui-joy/src/Button/ButtonProps.ts
- packages/mui-joy/src/Checkbox/Checkbox.tsx
- packages/mui-joy/src/Checkbox/CheckboxProps.ts
- packages/mui-joy/src/Chip/Chip.tsx
- packages/mui-joy/src/Chip/ChipProps.ts
- packages/mui-joy/src/FormLabel/FormLabel.tsx
- packages/mui-joy/src/FormLabel/FormLabelProps.ts
- packages/mui-joy/src/Input/Input.tsx
- packages/mui-joy/src/Input/InputProps.ts
- packages/mui-joy/src/Link/Link.tsx
- packages/mui-joy/src/Link/LinkProps.ts
- packages/mui-joy/src/Radio/Radio.tsx
- packages/mui-joy/src/Radio/RadioProps.ts
- packages/mui-joy/src/Select/Select.tsx
- packages/mui-joy/src/Select/SelectProps.ts
- packages/mui-joy/src/Switch/Switch.tsx
- packages/mui-joy/src/Switch/SwitchProps.ts
- packages/mui-joy/src/Textarea/Textarea.tsx
- packages/mui-joy/src/Textarea/TextareaProps.ts
- packages/mui-joy/src/Typography/Typography.tsx
- packages/mui-joy/src/Typography/TypographyProps.ts
> [Joy] Make the description of `componentsProps` generic

- docs/src/pages/careers/ROLE_TEMPLATE.md
- docs/src/pages/careers/designer.md
- docs/src/pages/careers/developer-advocate.md
- docs/src/pages/careers/developer-experience-engineer.md
- docs/src/pages/careers/engineering-manager.md
- docs/src/pages/careers/full-stack-engineer.md
- docs/src/pages/careers/people-operation-manager.md
- docs/src/pages/careers/product-engineer.md
- docs/src/pages/careers/product-manager.md
- docs/src/pages/careers/react-engineer-core.md
- docs/src/pages/careers/react-engineer-x.md
- docs/src/pages/careers/react-support-engineer.md
- docs/src/pages/careers/support-agent.md
- docs/src/pages/careers/technical-product-manager.md
Based on this discussion https://mui-org.slack.com/archives/C031JQCPSTH/p1661844094091489
I've also updated the descriptions in Ashby.
> [website] Update job descriptions

- README.md
Same as https://github.com/mui/mui-x/pull/6171
> [docs] Link the OpenSSF Best Practices card

- docs/pages/blog/introducing-mui-base.md
> [blog] MUI Base announcement typo fixed

- docs/data/material/customization/breakpoints/breakpoints.md
Signed-off-by: Dustin-Digitar <113573618+Dustin-Digitar@users.noreply.github.com>
> [docs] Capitalize Material Design on the Breakpoints page

- packages/mui-material/src/FormControlLabel/FormControlLabel.d.ts
Signed-off-by: Nathan Hughes <nathanwhughes@gmail.com>
> [TextField] Fix typo in FormControlLabel declaration file

- test/regressions/fixtures/AppBar/AppBarColorTransparent.js
I believe this comment is not useful for developers.
> [core] Remove useless comment in fixtures

- package.json
> [core] Update root package.json version

- packages/mui-system/src/Unstable_Grid/createGrid.tsx
- packages/mui-system/src/Unstable_Grid/gridGenerator.test.js
- packages/mui-system/src/Unstable_Grid/gridGenerator.ts
resolves https://github.com/mui/material-ui/issues/34571
> [Grid v2][system] handle direction object prop for responsive design

- docs/data/base/components/select/UnstyledSelectRichOptions.js
- docs/data/base/components/select/UnstyledSelectRichOptions.tsx
- docs/data/material/components/autocomplete/CountrySelect.js
- docs/data/material/components/autocomplete/CountrySelect.tsx
2005 version https://en.wikipedia.org/w/index.php?title=Taiwan&oldid=12192976, this comment looks legit to fix.
cc @mj12albert is this OK?
> [docs] Fix Taiwan description

- .circleci/config.yml
Based on https://github.com/mui/mui-toolpad/pull/1098.
**Before**
https://app.circleci.com/pipelines/github/mui/material-ui/82139/workflows/19ad4261-2d8b-475d-bf6b-0981c5be0b97/jobs/434594
**After**
https://app.circleci.com/pipelines/github/mui/material-ui/82141/workflows/c900dc71-7e63-4b25-994d-44e75beac5ea/jobs/434605
> [core] Speedup of yarn install in the CI

- docs/data/joy/getting-started/templates/email/components/EmailContent.tsx
- docs/data/joy/getting-started/tutorial/LoginFinal.js
- docs/data/joy/getting-started/tutorial/tutorial.md
- docs/data/material/experimental-api/css-theme-variables/migration.md
- docs/public/_redirects
- docs/src/modules/components/Demo.js
I started to fix https://app.ahrefs.com/site-audit/3524616/33/data-explorer?columns=pageRating%2Curl%2Ctraffic%2ChttpCode%2Cdepth%2Ccompliant%2CincomingAllLinks%2Corigin&filterCollapsed=true&filterId=91013c8aafad4fe1f7a0ad504eccad42&issueId=c64da643-d0f4-11e7-8ed1-001e67ed4656&sorting=-pageRating and made a follow-up on #34569.
> [docs] Improve Joy UI tutorial demo

- docs/data/material/customization/palette/palette.md
Signed-off-by: Kinayat Abay <74435594+AbayKinayat@users.noreply.github.com>
> [docs] Add a missing comma in the customization example

- .github/workflows/codeql.yml
Based on this -> https://github.com/mui/mui-x/pull/6387#issuecomment-1272345031
> [core] Add code scanning via CodeQL

- docs/data/joy/main-features/global-variants/LevelOfImportance.js
- docs/data/joy/main-features/global-variants/global-variants.md
Part of #33998 
This PR revises the Joy UI "Global variants" page. 
I rewrote the intro text to put the most important information at the very top, along with the demo that shows off the variants. I think this will give most readers everything they need as soon as they land on the page. 
I also renamed the final section to try to make it more obvious what you'll learn about if you read that section. And I tweaked the name of the second demo because I've never heard the word "importancy" before. 😁
> [docs] Revise the Joy UI "Global variants" page

- docs/data/joy/main-features/automatic-adjustment/automatic-adjustment.md
Part of #33998
This PR revises the Joy UI "Automatic adjustment" page. Mainly just style and grammar edits throughout. I restructured the headers a bit to underscore the kinds of adjustments that Joy makes and bring consistency to the page structure.
> [docs] Revise the Joy UI "Automatic adjustment" page

- docs/src/components/pricing/PricingTable.tsx
I'm trying to solve one of the root problems in https://mui.zendesk.com/agent/tickets/5157.
> I asked a question about the nested tab. I paid for priority support and was told to post my question on an open forum. What exactly did I pay 400 dollars?
I'm also going one extra step by suggesting that, eventually (long term) we will need to have support on MUI Core in the Premium plan. Why? Because how can you outperform Kendo UI/Syncfusion/DevExpress without? I can revert this part if we have mixed feelings about it (I mean, we can take our time). 
**Before**
https://mui.com/pricing/
**After**
https://deploy-preview-34607--material-ui.netlify.app/pricing/
> [website] Clarify Pro/Premium support

- packages/mui-codemod/src/v5.0.0/modal-props.js
- packages/mui-system/src/cssVars/cssVarsParser.ts
This PR makes some conditionals clearer by removing not used checks.
> [core] Clean conditionals

- docs/src/components/home/AdvancedShowcase.tsx
- docs/src/components/productX/XDataGrid.tsx
- docs/src/components/productX/XGridFullDemo.tsx
- docs/src/components/productX/XHero.tsx
- docs/src/components/productX/XTheming.tsx
- docs/src/components/x-grid/EditProgress.tsx
- docs/src/components/x-grid/EditStatus.tsx
Fixes https://github.com/mui/mui-x/issues/6047
Before: https://mui.com/x/
After: https://deploy-preview-34220--material-ui.netlify.app/x/
> [docs] Use new editing API in homepage demos

- docs/src/components/productX/XRoadmap.tsx
Update landing page to correct items that are work in progress.
https://deploy-preview-34810--material-ui.netlify.app/x/
There's a planned initiative this quarter to fully refactor the landing page. This is just a small update to clear any potential confusion about the availability of features until the new landing page is ready.
> [website] Update future work items on X landing page

- docs/src/route.ts
See https://github.com/mui/material-ui/pull/34749#discussion_r1001567954
> [docs] Fix Toolpad docs 301 route

- docs/notifications.json
Adding a notification for MUI X v6 alpha blog post (a bit late, but it's still relevant to get users to see)
> [docs] Add notification for blogpost MUI X v6 alpha

- docs/pages/_app.js
Removing the JavaScript redirect logic for localization, see https://github.com/mui/material-ui/pull/34820#pullrequestreview-1147494222
> [docs] Remove localization redirects

- docs/data/material/components/bottom-navigation/bottom-navigation.md
Fixed typo
Signed-off-by: Roody <18101218+RoodyCode@users.noreply.github.com>
> [docs] Fix typo in bottom-navigation.md

- packages/mui-material/src/Tooltip/Tooltip.test.js
A continuation of https://github.com/mui/material-ui/pull/34853#issuecomment-1288659049
> [test] Use screen when possible for simplicity

- docs/data/material/getting-started/templates/album/README.md
- docs/data/material/getting-started/templates/blog/README.md
- docs/data/material/getting-started/templates/checkout/README.md
- docs/data/material/getting-started/templates/dashboard/README.md
- docs/data/material/getting-started/templates/pricing/README.md
- docs/data/material/getting-started/templates/sign-in-side/README.md
- docs/data/material/getting-started/templates/sign-in/README.md
- docs/data/material/getting-started/templates/sign-up/README.md
- docs/data/material/getting-started/templates/sticky-footer/README.md
Mention the dependencies required to run the templates in each one's README.
Closes #34703
> [docs] Update templates' readme files to include required dependencies

- packages/mui-joy/src/CircularProgress/CircularProgress.tsx
- packages/mui-joy/src/LinearProgress/LinearProgress.tsx
Follow-up of this disccussion: https://github.com/mui/material-ui/pull/34514#pullrequestreview-1154033581
Preview: https://deploy-preview-34897--material-ui.netlify.app/joy-ui/react-circular-progress/#determinate
> [Joy][CircularProgress] Prevent new styles from being generated when `value` changes

- docs/data/material/components/image-list/image-list.md
> [docs] Fix typo in docs title

- packages/mui-system/src/cssVars/getInitColorSchemeScript.tsx
Fixes #34801 
- [x ] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/material-ui/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).
> Added a missing key attribute in getInitColorScheme to fix key issue

- CHANGELOG.md
Follow up of https://github.com/mui/material-ui/pull/35033
> [core] Improve the changelog for v5.10.13 release

- packages/mui-material/src/styles/CssVarsProvider.test.js
- packages/mui-material/src/styles/experimental_extendTheme.d.ts
- packages/mui-material/src/styles/experimental_extendTheme.js
- packages/mui-material/src/styles/experimental_extendTheme.test.js
- packages/mui-material/src/themeCssVarsAugmentation/index.d.ts
For https://github.com/mui/mui-x/pull/6784#issuecomment-1308449668.
> [Material UI] Add `palette.background.defaultChannel` token

- docs/src/modules/components/AdCarbon.js
- docs/src/modules/components/Demo.js
- docs/src/modules/components/DemoEditor.tsx
- docs/src/modules/components/ad.styles.js
Fix point 3 and 4 in https://github.com/mui/material-ui/pull/34870#issuecomment-1307966805.
> [docs] Fix code editor styles mismatches

- packages/mui-material/src/styles/experimental_extendTheme.d.ts
Should fix TS error in https://github.com/mui/mui-x/pull/6784
> [typescript] Add `background.defaultChannel` to `CssVarsPalette`

- packages/mui-material/src/Fab/Fab.js
closes https://github.com/mui/material-ui/issues/35039
> [Fab] Increase disabled styles precedence

- packages/mui-joy/src/Textarea/textareaClasses.ts
Signed-off-by: VelociRaptor <77036902+zignis@users.noreply.github.com>
> [Joy][Textarea] Expose decorator classes

- docs/src/components/home/MuiStatistics.tsx
> [website] Update MUI stats: GitHub stars, Twitter followers, etc.

- packages/mui-material/src/utils/index.js
I found this by chance looking in the source of https://databar.ai/static/js/4.29980672.chunk.js for https://groups.google.com/a/mui.com/g/core/c/vipNV4kM7k0.
> [core] Fix warning leak in production

- CONTRIBUTING.md
Corrected grammatically incorrect sentences, punctuations and typos for better readability.
Signed-off-by: Pandey-utkarsh <91661580+Pandey-utkarsh@users.noreply.github.com>
> [docs] Correct grammatically incorrect sentences in CONTRIBUTING.md

- docs/src/modules/components/AppLayoutDocsFooter.js
Fix 
> In the Slack message, it could help to have "Google Maps place" as a link. (edited)
> [docs] Format feedback to add a link to the commented section

- docs/data/joy/components/list/ListUsage.js
> [Joy][docs] List component introduction example default code is missing ListItemContent component

- docs/data/system/experimental-api/configure-the-sx-prop/configure-the-sx-prop.md
> [docs] Fix `unstable_sxConfig` typo

- docs/data/material/guides/minimizing-bundle-size/minimizing-bundle-size-pt.md
- docs/data/material/guides/minimizing-bundle-size/minimizing-bundle-size-zh.md
- docs/data/material/guides/minimizing-bundle-size/minimizing-bundle-size.md
- packages/eslint-plugin-material-ui/README.md
- packages/mui-lab/tsconfig.build.json
The modules were removed in #21855.
> [core] Cleanup mention of test-utils

- docs/data/material/components/tables/EnhancedTable.js
- docs/data/material/components/tables/EnhancedTable.tsx
- docs/src/components/showcase/FolderTable.tsx
Created this PR following discussion at https://github.com/mui/material-ui/pull/34189#issuecomment-1356839413.
> [docs] Clarify comment about `sortStability()` use case

- docs/pages/blog.tsx
- docs/src/components/header/HeaderNavBar.tsx
- docs/src/modules/components/DemoEditor.tsx
- packages/mui-joy/src/ModalDialog/ModalDialog.tsx
- packages/mui-joy/src/Select/Select.tsx
> [core] Shorthand notation to remove outline

- packages/mui-system/src/Box/Box.spec.tsx
- packages/mui-system/src/createBox.spec.tsx
- packages/mui-system/src/styleFunctionSx/styleFunctionSx.test.js
See https://github.com/emotion-js/emotion/issues/2270#issuecomment-1368483169 for more details on why it's wrong.
> [test] Always use & for nesting styles

- docs/pages/careers.tsx
- docs/src/pages/careers/lead-designer.md
Act on @gerdadesign review in https://github.com/mui/material-ui/pull/35240#pullrequestreview-1219582722
> [website] Improve Lead Designer role description

- docs/pages/base/api/portal.json
- packages/mui-base/src/Portal/Portal.test.tsx
- packages/mui-base/src/Portal/Portal.tsx
- packages/mui-base/src/Portal/Portal.types.ts
- packages/mui-base/src/Portal/index.js
- packages/mui-base/src/Portal/index.ts
- packages/mui-joy/src/Modal/Modal.tsx
closes: https://github.com/mui/material-ui/issues/34719
> [Portal][base] Convert code to TypeScript

- docs/data/joy/components/aspect-ratio/BasicRatio.js
- docs/data/joy/components/aspect-ratio/BasicRatio.tsx
- docs/data/joy/components/aspect-ratio/BasicRatio.tsx.preview
- docs/data/joy/components/aspect-ratio/CustomRatio.js
- docs/data/joy/components/aspect-ratio/CustomRatio.tsx
- docs/data/joy/components/aspect-ratio/CustomRatio.tsx.preview
- docs/data/joy/components/checkbox/CheckboxUsage.js
- docs/data/joy/components/checkbox/ExampleButtonCheckbox.js
- packages/mui-joy/src/Checkbox/Checkbox.tsx
- packages/mui-joy/src/Link/Link.spec.tsx
- packages/mui-joy/src/Link/LinkProps.ts
- packages/mui-joy/src/Radio/Radio.tsx
- packages/mui-joy/src/Typography/Typography.spec.tsx
- packages/mui-joy/src/Typography/TypographyProps.ts
- packages/mui-joy/src/styles/types/theme.ts
- Add `background.surface` to Radio and Checkbox to conform with Input
- Improve `textColor` types for Link and Typography
- Simplify AspectRatio demos
---
> [Joy] Miscellaneous improvements

- docs/data/material/guides/composition/composition.md
Signed-off-by: Matthew Soyka <msoyka91@gmail.com>
> [docs] Fix typo in the Composition page

- packages/mui-base/src/AutocompleteUnstyled/useAutocomplete.js
- packages/mui-base/src/ClickAwayListener/ClickAwayListener.test.js
- packages/mui-base/src/FocusTrap/FocusTrap.tsx
- packages/mui-base/src/ListboxUnstyled/useControllableReducer.ts
> [base] Fix typos

- docs/data/joy/components/typography/typography.md
Signed-off-by: Alexander Trefonas <72869083+atrefonas@users.noreply.github.com>
> [docs][joy] Fix grammar in `Typography` docs

- docs/data/joy/components/list/list.md
- docs/data/joy/components/tabs/TabsUnderlineExample.js
- docs/data/joy/components/tabs/TabsUnderlineExample.tsx
- docs/data/joy/components/tabs/tabs.md
- packages/mui-joy/src/ListItemButton/ListItemButton.tsx
- packages/mui-joy/src/Tab/Tab.tsx
closes: https://github.com/mui/material-ui/issues/35675
> [Tabs][Joy] Don't apply `:hover, :active` styles when `selected`

- docs/data/material/customization/color/color.md
> [docs] Fix wording in `Color` page

- docs/notifications.json
Add docs notification calling out for the blogpost "Date and Time Pickers revamped"
> [docs] Add docs notification to Date and Time Pickers revamped

- docs/data/joy/components/chip/chip-pt.md
- docs/data/joy/components/chip/chip-zh.md
- docs/data/joy/components/chip/chip.md
> [docs][joy] Removed Badge info from Chip docs

- packages/mui-joy/src/Checkbox/Checkbox.test.js
- packages/mui-joy/src/Checkbox/Checkbox.tsx
closes: https://github.com/mui/material-ui/issues/35867
used logic as per: https://github.com/mui/material-ui/issues/35867#issuecomment-1403161530
> [Joy][Checkbox] Display correct icon in checkbox

- docs/data/joy/guides/using-icon-libraries/using-icon-libraries.md
> [docs][joy] Fixed a typo in `Using icon libraries` page

- packages/mui-joy/src/index.ts
Fixes https://github.com/mui/material-ui/issues/36009
> [Joy] Add missing `Table` export from root

- test/utils/setup.js
- test/utils/setupJSDOM.js
Found this minor typo while looking into https://github.com/mui/material-ui/pull/35980.
> [core] Fix a typo in the comment in setup test files

- docs/data/material/getting-started/overview/overview.md
Alternatively
> "You can count on community support for years to come...
Signed-off-by: Alex Ownejazayeri <alirezaownejazayeri@gmail.com>
> [docs] Update grammar

- docs/data/joy/customization/approaches/approaches-pt.md
- docs/data/joy/customization/approaches/approaches-zh.md
- docs/data/joy/customization/approaches/approaches.md
> [docs] [Joy] Fixed a typo in `customizing theme tokens`

- docs/pages/careers.tsx
- docs/src/pages/careers/ROLE_TEMPLATE.md
- docs/src/pages/careers/accessibility-engineer.md
- docs/src/pages/careers/design-engineer.md
- docs/src/pages/careers/designer.md
- docs/src/pages/careers/developer-advocate.md
- docs/src/pages/careers/developer-experience-engineer.md
- docs/src/pages/careers/engineering-manager.md
- docs/src/pages/careers/full-stack-engineer.md
- docs/src/pages/careers/lead-designer.md
- docs/src/pages/careers/people-operation-manager.md
- docs/src/pages/careers/product-engineer.md
- docs/src/pages/careers/product-manager.md
- docs/src/pages/careers/product-marketing-manager.md
- docs/src/pages/careers/react-engineer-core.md
- docs/src/pages/careers/react-engineer-x-grid.md
- docs/src/pages/careers/react-engineer-x.md
- docs/src/pages/careers/react-support-engineer.md
- docs/src/pages/careers/react-tech-lead-core.md
- docs/src/pages/careers/react-tech-lead-x-grid.md
- docs/src/pages/careers/support-agent.md
- docs/src/pages/careers/technical-product-manager.md
- docs/src/pages/careers/technical-recruiter.md
The main goal is to apply the template role changes of #35912 to all the other roles.
> [website] Revise the Lead Designer role job ad (v1)

- scripts/README.md
Proposing some updates to the instructions after doing this process for the first time ~
> [docs] Update release instructions

- CHANGELOG.md
Just a small typo. I already fixed the corresponding GitHub release.
> [docs] Fix typo in the released version of @mui/styled-engine

- docs/pages/base/api/use-tabs-list.json
- docs/translations/api-docs/use-tabs-list/use-tabs-list.json
- packages/mui-base/src/TabsListUnstyled/useTabsList.ts
- packages/mui-base/src/TabsListUnstyled/useTabsList.types.ts
UseTabsList return value interface
closes useTabsList in https://github.com/mui/material-ui/issues/35933
preview: https://deploy-preview-36048--material-ui.netlify.app/base/api/use-tabs-list/#return-value
> [useTabsList] Add explicit return type

- packages/mui-material/src/AppBar/AppBar.js
Closes #36125.
**After**: https://codesandbox.io/s/romantic-breeze-gv59js?file=/src/App.jsx
> [AppBar] Fix joinVars() not handling undefined

- .markdownlint-cli2.cjs
- SECURITY.md
- docs/data/base/components/form-control/form-control.md
- docs/data/material/discover-more/roadmap/roadmap.md
- docs/data/material/experimental-api/css-theme-variables/overview.md
- docs/data/system/getting-started/usage/usage.md
- docs/pages/blog/2019-developer-survey-results.md
- packages/markdownlint-rule-mui/straight-quotes.js
- packages/markdownlint-rule-mui/table-alignment.js
- packages/typescript-to-proptypes/README.md
- test/e2e/README.md
- test/regressions/README.md
Center alignment never makes sense, as far as I know, but it's the default. https://ux.stackexchange.com/questions/24066/what-is-the-best-practice-for-data-table-cell-content-alignment
Same as https://github.com/mui/mui-x/pull/7898.
> [docs] Fix markdown table alignments

- docs/data/material/components/tree-view/DisabledTreeItems.js
- docs/data/material/components/tree-view/DisabledTreeItems.tsx
> [docs] Fix padding in `Disabled tree items` section in Tree View docs

- packages/mui-joy/src/AutocompleteOption/AutocompleteOption.tsx
- packages/mui-joy/src/Badge/Badge.tsx
- packages/mui-joy/src/Button/Button.tsx
- packages/mui-joy/src/Card/Card.tsx
- packages/mui-joy/src/Checkbox/Checkbox.tsx
- packages/mui-joy/src/Chip/Chip.tsx
- packages/mui-joy/src/CircularProgress/CircularProgress.tsx
- packages/mui-joy/src/IconButton/IconButton.tsx
- packages/mui-joy/src/Input/Input.tsx
- packages/mui-joy/src/LinearProgress/LinearProgress.tsx
- packages/mui-joy/src/ListItemButton/ListItemButton.tsx
- packages/mui-joy/src/Radio/Radio.tsx
- packages/mui-joy/src/Select/Select.tsx
- packages/mui-joy/src/Sheet/Sheet.tsx
- packages/mui-joy/src/Slider/Slider.tsx
- packages/mui-joy/src/SvgIcon/SvgIcon.tsx
- packages/mui-joy/src/Switch/Switch.tsx
- packages/mui-joy/src/Textarea/Textarea.tsx
> [Joy] Remove transition from all components

- docs/data/material/getting-started/example-projects/example-projects-pt.md
> [docs] Update links to pt examples

- packages/mui-material/src/Snackbar/Snackbar.js
> [Snackbar] Replace component logic with `useSnackbar` hook

- docs/data/base/guides/working-with-tailwind-css/working-with-tailwind-css.md
> [docs] Fix code on the Working with Tailwind CSS guide

- packages/mui-material/src/Autocomplete/Autocomplete.d.ts
- packages/mui-material/src/Autocomplete/Autocomplete.spec.tsx
closes : https://github.com/mui/material-ui/issues/36214
before: https://codesandbox.io/s/confident-worker-5ek4x8
after: https://codesandbox.io/s/friendly-montalcini-lt0s57?file=/demo.tsx
> [Autocomplete] Adds `sx` prop to `ListboxProps` type

- docs/data/joy/components/typography/DecoratorExamples.tsx
- docs/data/joy/components/typography/NestedTypography.tsx
- docs/data/joy/components/typography/NestedTypography.tsx.preview
- docs/data/joy/components/typography/TypographyDecorators.tsx
- docs/data/joy/components/typography/TypographyDecorators.tsx.preview
- docs/data/joy/components/typography/TypographyScales.tsx
- docs/data/joy/components/typography/TypographyScales.tsx.preview
Typography Part of [#36367](https://github.com/mui/material-ui/issues/36367)
> [docs][joy] Build TS versions for Typography component demos

- docs/data/joy/components/radio/ControlledRadioButtonsGroup.tsx
- docs/data/joy/components/radio/ControlledRadioButtonsGroup.tsx.preview
- docs/data/joy/components/radio/ExampleAlignmentButtons.tsx
- docs/data/joy/components/radio/ExamplePaymentChannels.tsx
- docs/data/joy/components/radio/ExampleProductAttributes.tsx
- docs/data/joy/components/radio/ExampleSegmentedControls.tsx
- docs/data/joy/components/radio/ExampleTiers.tsx
- docs/data/joy/components/radio/IconlessRadio.tsx
- docs/data/joy/components/radio/IconsRadio.tsx
- docs/data/joy/components/radio/OverlayRadio.tsx
- docs/data/joy/components/radio/RadioButtonControl.tsx
- docs/data/joy/components/radio/RadioButtonControl.tsx.preview
- docs/data/joy/components/radio/RadioButtonLabel.tsx
- docs/data/joy/components/radio/RadioButtonLabel.tsx.preview
- docs/data/joy/components/radio/RadioButtons.tsx
- docs/data/joy/components/radio/RadioButtons.tsx.preview
- docs/data/joy/components/radio/RadioButtonsGroup.tsx
- docs/data/joy/components/radio/RadioButtonsGroup.tsx.preview
- docs/data/joy/components/radio/RadioFocus.tsx
- docs/data/joy/components/radio/RadioFocus.tsx.preview
- docs/data/joy/components/radio/RadioPositionEnd.tsx
part of https://github.com/mui/material-ui/issues/36367
> [docs][joy] Build TS versions for Radio component demos

- docs/notifications.json
Docs notification for https://mui.com/blog/mui-x-v6/
> [docs] Add blog post notification for v6 release

- docs/src/components/home/MuiStatistics.tsx
> [website] Update stats

- docs/data/system/properties/properties.md
> [docs] Fix a grammar error

- docs/pages/joy-ui/getting-started/templates/files.js
- docs/pages/joy-ui/getting-started/templates/order-dashboard.js
- docs/pages/joy-ui/getting-started/templates/sign-in-side.js
> [docs] Fix function name for Joy templates

- docs/pages/careers.tsx
- docs/pages/careers/head-of-operations.js
- docs/src/pages/careers/ROLE_TEMPLATE.md
- docs/src/pages/careers/accessibility-engineer.md
- docs/src/pages/careers/design-engineer.md
- docs/src/pages/careers/designer.md
- docs/src/pages/careers/developer-advocate.md
- docs/src/pages/careers/developer-experience-engineer.md
- docs/src/pages/careers/engineering-manager.md
- docs/src/pages/careers/full-stack-engineer.md
- docs/src/pages/careers/head-of-operations.md
- docs/src/pages/careers/lead-designer.md
- docs/src/pages/careers/people-operation-manager.md
- docs/src/pages/careers/product-engineer.md
- docs/src/pages/careers/product-manager.md
- docs/src/pages/careers/product-marketing-manager.md
- docs/src/pages/careers/react-engineer-core.md
- docs/src/pages/careers/react-engineer-x-grid.md
- docs/src/pages/careers/react-engineer-x.md
- docs/src/pages/careers/react-support-engineer.md
- docs/src/pages/careers/react-tech-lead-core.md
- docs/src/pages/careers/react-tech-lead-x-grid.md
- docs/src/pages/careers/support-agent.md
- docs/src/pages/careers/technical-product-manager.md
- docs/src/pages/careers/technical-recruiter.md
I was about to start working on https://www.notion.so/mui-org/Scale-collaborative-inbox-in-Google-Groups-f6f3d7a8a6bd4c24be1fc8b13a8f33f6 but instead worked on drafting this job description as there is soo much we could do around it.
Preview: https://deploy-preview-36501--material-ui.netlify.app/careers/head-of-operations/.
cc @mikailaread
> [website] Open Head of Operations role

- docs/pages/base/api/use-autocomplete.json
- docs/pages/base/api/use-button.json
- docs/pages/base/api/use-input.json
- docs/pages/base/api/use-menu-item.json
- docs/pages/base/api/use-menu.json
- docs/pages/base/api/use-option.json
- docs/pages/base/api/use-slider.json
- docs/pages/base/api/use-snackbar.json
- docs/pages/base/api/use-switch.json
- docs/pages/base/api/use-tab-panel.json
- docs/pages/base/api/use-tab.json
- docs/pages/base/api/use-tabs-list.json
- docs/pages/base/api/use-tabs.json
- packages/api-docs-builder/ApiBuilders/HookApiBuilder.ts
Noticed a small mistake in sanitization code.
> [docs] Fix typo in API docs

- docs/src/components/banner/AppFrameBanner.tsx
- docs/src/components/banner/TableOfContentsBanner.tsx
- docs/src/components/home/AdvancedShowcase.tsx
- docs/src/components/home/NewsletterToast.tsx
- docs/src/components/home/ShowcaseContainer.tsx
- docs/src/components/productX/XComponents.tsx
- docs/src/components/productX/XDateRangeDemo.tsx
- docs/src/components/productX/XTreeViewDemo.tsx
- docs/src/components/x-grid/EditProgress.tsx
- docs/src/components/x-grid/ProgressBar.tsx
- docs/src/components/x-grid/Status.tsx
- docs/src/modules/components/AppFrame.js
- docs/src/modules/components/AppNavDrawer.js
- docs/src/modules/components/AppNavDrawerItem.js
- docs/src/modules/components/AppSearch.js
- docs/src/modules/components/AppSettingsDrawer.js
- docs/src/modules/components/AppTableOfContents.js
- docs/src/modules/components/BackToTop.tsx
- docs/src/modules/components/Demo.js
- docs/src/modules/components/DemoEditor.tsx
- docs/src/modules/components/DemoSandbox.js
- docs/src/modules/components/DemoToolbar.js
- docs/src/modules/components/DiamondSponsors.js
- docs/src/modules/components/EditPage.js
- docs/src/modules/components/MarkdownElement.js
- docs/src/modules/components/MaterialYouUsageDemo.tsx
- docs/src/modules/components/MuiProductSelector.tsx
- docs/src/modules/components/Notifications.js
- docs/src/modules/components/PropertiesTable.js
> Revert "[docs] Use `theme.applyDarkStyles` for the rest of the docs"

- docs/data/material/guides/interoperability/interoperability.md
> [docs] Fix broken example link

- docs/src/modules/components/ApiPage.js
Follow-up of https://github.com/mui/material-ui/pull/36328#issuecomment-1475449521
**Before**
- https://deploy-preview-36490--material-ui.netlify.app/joy-ui/api/link/#slots
**After**
- https://deploy-preview-36621--material-ui.netlify.app/joy-ui/api/link/#slots
> [docs] Remove duplicated slot descriptions

- docs/data/joy/components/input/input.md
Fix a small typo "Input" instead of "Avatar" (from a copy-paste I guess).
> [docs] Fix small typo

- docs/data/joy/customization/theme-builder/theme-builder.md
Super quick and simple one reported on this page.
@samuelsycamore let me know if you find opportunities to improve the overall thing, though!
> [docs] Fix typo on the Joy UI theme builder

- docs/public/_redirects
Changed in #35554, https://mui.com/joy-ui/customization/theme-tokens/ is a 404
> [docs] Fix Joy UI URL to tokens

- netlify/functions/feedback-management.js
Test done: https://mui-org.slack.com/archives/C041SDSF32L/p1680178710295169
before, after:
Send them to specific slack channels for
- x
- joy
- toolpad
> [docs] Update feedbacks management on slack

- docs/next.config.js
No longer needed can be removed per https://github.com/mui/material-ui/pull/36472#issuecomment-1491698386
> [core] Remove unused token

- docs/src/pages/careers/senior-designer.md
@gerdadesign I've thought about swapping the "day-to-day" section there as it was fairly generic with this "first 3 months" one. These are likely stuff they'll continue doing across their journey but not necessarily everything will pop up in this initial period. Might need to iterate further ⎯ but let me know!
> [website] Tweaks to the Designer position ad

- docs/translations/api-docs-joy/divider/divider.json
- docs/translations/api-docs-joy/slider/slider.json
- packages/mui-joy/src/Divider/Divider.tsx
- packages/mui-joy/src/Divider/DividerProps.ts
- packages/mui-joy/src/Slider/Slider.tsx
- packages/mui-joy/src/Slider/SliderProps.ts
> [docs][Joy] Fix wrong prop descriptions

- docs/data/material/components/backdrop/backdrop.md
Resolves comment https://github.com/mui/material-ui/pull/34244#discussion_r1161743042.
> [docs] Revert CircularProgress component text to be proper noun instead

- docs/src/modules/components/MarkdownDocsV2.js
Resolves https://github.com/mui/material-ui/pull/35938#discussion_r1155105656
> [docs] Improve perf on tab APIs

- docs/data/material/components/selects/SelectSmall.js
- docs/data/material/components/selects/SelectSmall.tsx
closes https://github.com/mui/material-ui/issues/36790
> [docs][Select] Fix duplicate ID in small size Select demo

- docs/data/base/components/popper/SimplePopper.js
- docs/data/base/components/popper/SimplePopper.tsx
Part of #36498
---
This code was written and reviewed by GitStart Community. Growing great engineers, one PR at a time.
> [docs][base] Move styles to the bottom of demos code for `Popper`

- docs/data/base/components/badge/AccessibleBadges.js
- docs/data/base/components/badge/AccessibleBadges.tsx
- docs/data/base/components/badge/BadgeMax.js
- docs/data/base/components/badge/BadgeMax.tsx
- docs/data/base/components/badge/BadgeVisibility.js
- docs/data/base/components/badge/BadgeVisibility.tsx
- docs/data/base/components/badge/ShowZeroBadge.js
- docs/data/base/components/badge/ShowZeroBadge.tsx
- docs/data/base/components/badge/UnstyledBadge.js
- docs/data/base/components/badge/UnstyledBadge.tsx
- docs/data/base/components/badge/UnstyledBadgeIntroduction.js
- docs/data/base/components/badge/UnstyledBadgeIntroduction.tsx
>  [docs][base] Move styles to the bottom of demos code for `BadgeUnstyled`

- docs/data/joy/components/card/card.md
> [docs] Content changed from 'row' to 'orientation=horizontal'

- docs/pages/careers.tsx
Removing it from the open roles list.
> [website] Design role updates

- packages/mui-joy/src/Autocomplete/Autocomplete.test.tsx
- packages/mui-material/src/Autocomplete/Autocomplete.test.js
Fixing CI browser test failure: https://app.circleci.com/pipelines/github/mui/material-ui/96251/workflows/80347730-f2f6-4d67-a9de-d1da14f5ca31/jobs/511855
> [core] Fix CI failure on `master`

- docs/src/modules/components/BackToTop.tsx
> [docs] smooth scrolling added for `back to top`

- docs/data/material/getting-started/templates/blog/Blog.js
- docs/data/material/getting-started/templates/blog/Blog.tsx
> [templates] Image not displayed in blog layout of React template.

- docs/notifications.json
> [docs] Add notification to the release of the new Time Picker UI

- packages/mui-joy/src/AspectRatio/AspectRatio.test.tsx
> [AspectRatio][joy] js test replaced with ts test

- docs/data/material/discover-more/roadmap/roadmap.md
- docs/pages/blog/2020-q3-update.md
- docs/pages/blog/2021-q1-update.md
- docs/pages/blog/2021-q2-update.md
- docs/pages/blog/2021-q3-update.md
- docs/pages/blog/benny-joo-joining.md
- docs/pages/blog/marija-najdova-joining.md
> [docs] Update links to the public roadmap

- packages/mui-joy/src/Alert/Alert.test.tsx
> [Alery][joy] Turn JS test to TS test

- packages/mui-joy/src/AvatarGroup/AvatarGroup.test.tsx
- packages/mui-joy/src/Badge/Badge.test.tsx
> [Badge][AvatarGroup][joy] js test replaced with ts test

- packages/mui-joy/src/Avatar/Avatar.test.js
> [test][Joy] Remove duplicate Avatar test

- README.md
> [docs] Change Base UI `alpha` to `beta` in README

- docs/pages/careers.tsx
- docs/src/pages/careers/design-engineer.md
- docs/src/pages/careers/react-engineer-core.md
- docs/src/pages/careers/react-tech-lead-core.md
TODO:
https://deploy-preview-37224--material-ui.netlify.app/careers/
> [website] Update core open roles

- docs/data/material/migration/migration-v4/migration-v4.md
Fix https://github.com/mui/material-ui/pull/35232#discussion_r1104940056
> [docs] Fix v5 migration npm install instruction

- docs/data/material/components/transitions/transitions.md
> [docs][Transitions] Fix typo in code sample

- docs/data/base/getting-started/quickstart/quickstart.md
- docs/data/joy/getting-started/installation/installation.md
- docs/data/joy/getting-started/overview/overview.md
- docs/data/material/getting-started/installation/installation.md
- packages/mui-joy/README.md
Same as https://github.com/mui/mui-x/pull/9067
> [docs] Clarify the peer dependency with react

- packages/mui-material/src/useMediaQuery/useMediaQuery.test.js
> [test][useMediaQuery] Change SSR test description

- docs/data/material/experimental-api/css-theme-variables/overview.md
- docs/data/material/experimental-api/css-theme-variables/usage.md
- docs/public/_redirects
> [docs] Move contents of css-variables to sibling pages

- docs/src/layouts/AppFooter.tsx
- docs/src/route.ts
- docs/translations/translations-zh.json
As pointed out here: https://github.com/mui/material-ui/pull/37314#issuecomment-1564285478
> [docs] Fix "Language" page removal leftovers

- docs/pages/_app.js
- docs/src/modules/components/AppNavDrawer.js
- docs/src/modules/utils/useRouterExtra.ts
- packages/markdown/parseMarkdown.js
This PR makes it mandatory to provide a context for the current docs displayed. It also makes providing versions mandatory. We saw the opportunity from https://github.com/mui/mui-x/pull/9221.
It's a continuation of #35078.
> [docs-infra] Mandatory versions

- docs/data/material/components/breadcrumbs/breadcrumbs.md
- docs/data/material/components/drawers/drawers.md
- docs/data/material/components/use-media-query/use-media-query.md
- docs/data/material/customization/theme-components/theme-components.md
- docs/data/material/customization/transitions/transitions.md
- docs/data/material/discover-more/roadmap/roadmap.md
- docs/data/material/getting-started/templates/templates.md
- docs/data/material/guides/interoperability/interoperability.md
- docs/data/material/guides/routing/routing.md
- docs/data/material/migration/migration-v4/v5-component-changes-pt.md
- docs/data/material/migration/migration-v4/v5-component-changes-zh.md
- docs/data/material/migration/migration-v4/v5-component-changes.md
- docs/data/material/migration/migration-v4/v5-style-changes-pt.md
- docs/data/material/migration/migration-v4/v5-style-changes-zh.md
- docs/data/material/migration/migration-v4/v5-style-changes.md
- docs/data/system/display/display.md
- docs/data/system/properties/properties.md
- docs/pages/careers.tsx
- docs/src/pages/careers/react-community-engineer.md
- packages/markdown/parseMarkdown.js
- packages/markdown/parseMarkdown.test.js
See https://app.ahrefs.com/site-audit/3524616/68/data-explorer?columns=pageRating%2Curl%2Ctraffic%2ChttpCode%2Cdepth%2CmetaDescription%2CmetaDescriptionLength%2CnrMetaDescription%2Ccompliant&filterId=2864d4a78dbccdda9cf9629aa273bd61&issueId=c64d56c9-d0f4-11e7-8ed1-001e67ed4656
> [docs-infra] Enforce max length on description

- scripts/README.md
Add a couple of instructions that were missing from the release guide.
> [docs] Improve release guide

- docs/data/base/getting-started/quickstart/BaseButtonMuiSystem.js
- docs/data/base/getting-started/quickstart/BaseButtonMuiSystem.tsx
- docs/data/base/getting-started/quickstart/BaseButtonMuiSystem.tsx.preview
- docs/data/base/getting-started/quickstart/quickstart.md
- docs/data/joy/components/tooltip/GitHubTooltip.js
- docs/data/joy/components/tooltip/GitHubTooltip.tsx
- docs/data/joy/components/tooltip/tooltip.md
- scripts/README.md
> [docs] Fix GitHub typo

- docs/data/base/components/autocomplete/autocomplete.md
- docs/public/_redirects
> [docs] Fix small base -> base-ui migration issue

- examples/material-next-app-router-ts/README.md
> [example] Shell command fix in the readme file of material-next-app-router-ts example

- docs/next.config.js
- docs/src/modules/components/EditPage.js
See https://github.com/mui/material-ui/pull/37691#issuecomment-1605759163 for why
Before: https://mui.com/material-ui/getting-started/overview/
Preview: https://deploy-preview-37695--material-ui.netlify.app/material-ui/getting-started/overview/
This is a breaking change for the docs-infra, the config needs to be updated.
> [docs-infra] Improve the edit page experience

- docs/data/base/components/select/select.md
Adds the explanation about portals in Select. 
Hopefully it'll help prevent issues like #37591
> [docs] Explain how to disable Base Select's portal

- docs/src/layouts/AppHeader.tsx
> [docs-infra] Make the GitHub link in the nav bar open in a new tab

- docs/data/base/components/button/UnstyledButtonCustom.js
- docs/data/base/components/button/UnstyledButtonCustom.tsx
- docs/data/base/components/button/UnstyledButtonIntroduction.js
- docs/data/base/components/button/UnstyledButtonIntroduction.tsx
- docs/data/base/components/button/UnstyledButtonsDisabledFocus.js
- docs/data/base/components/button/UnstyledButtonsDisabledFocus.tsx
- docs/data/base/components/button/UnstyledButtonsDisabledFocusCustom.js
- docs/data/base/components/button/UnstyledButtonsDisabledFocusCustom.tsx
- docs/data/base/components/button/UnstyledButtonsSimple/css/index.js
- docs/data/base/components/button/UnstyledButtonsSimple/css/index.tsx
- docs/data/base/components/button/UnstyledButtonsSimple/system/index.js
- docs/data/base/components/button/UnstyledButtonsSimple/system/index.tsx
- docs/data/base/components/button/UnstyledButtonsSimple/tailwind/index.js
- docs/data/base/components/button/UnstyledButtonsSimple/tailwind/index.tsx
- docs/data/base/components/button/UnstyledButtonsSimple/tailwind/index.tsx.preview
- docs/data/base/components/button/UnstyledButtonsSpan.js
- docs/data/base/components/button/UnstyledButtonsSpan.tsx
- docs/data/base/components/button/UseButton.js
- docs/data/base/components/button/UseButton.tsx
This PR basically makes the Base UI button demos a bit denser.
https://deploy-preview-37689--material-ui.netlify.app/base-ui/react-button/#introduction
> [docs][base] Make Base UI button demos denser

- docs/data/base/components/input/InputAdornments.js
- docs/data/base/components/input/InputAdornments.tsx
- docs/data/base/components/input/InputMultiline.js
- docs/data/base/components/input/InputMultiline.tsx
- docs/data/base/components/input/InputMultilineAutosize.js
- docs/data/base/components/input/InputMultilineAutosize.tsx
- docs/data/base/components/input/UnstyledInputBasic/css/index.js
- docs/data/base/components/input/UnstyledInputBasic/css/index.tsx
- docs/data/base/components/input/UnstyledInputBasic/system/index.js
- docs/data/base/components/input/UnstyledInputBasic/system/index.tsx
- docs/data/base/components/input/UnstyledInputBasic/tailwind/index.js
- docs/data/base/components/input/UnstyledInputBasic/tailwind/index.tsx
- docs/data/base/components/input/UnstyledInputBasic/tailwind/index.tsx.preview
- docs/data/base/components/input/UnstyledInputIntroduction.js
- docs/data/base/components/input/UnstyledInputIntroduction.tsx
- docs/data/base/components/input/UseInput.js
- docs/data/base/components/input/UseInput.tsx
This PR basically makes the Input demos a bit denser.
https://deploy-preview-37750--material-ui.netlify.app/base-ui/react-input/
> [docs][base] Make Base UI input demos denser

- packages/mui-base/src/Slider/Slider.test.tsx
- packages/mui-base/src/Slider/Slider.tsx
- packages/mui-base/src/Slider/Slider.types.ts
- packages/mui-base/src/utils/resolveComponentProps.ts
- packages/mui-base/src/utils/types.ts
- packages/mui-base/src/utils/useSlotProps.test.tsx
- packages/mui-base/src/utils/useSlotProps.ts
Resolves https://github.com/mui/material-ui/pull/37736#discussion_r1243580438
> [base][slider] Provide slot state to Slider's thumb slot props callback

- yarn.lock
Updated the lockfile that hasn't been committed with an earlier dependency bump.
> [core] Update yarn lockfile

- docs/data/material/migration/migration-v4/v5-component-changes.md
Fix an old slack feedback
> I think the provided code block is an example of how to mimic old v4 behavior, but that isn't explicitly mentioned. Rather instead, some example code is given and a developer would have to infer its meaning.
> [docs] Small pickers migration improvement

- .markdownlint-cli2.cjs
- packages/markdown/parseMarkdown.js
- packages/markdown/parseMarkdown.test.js
- packages/markdown/prism.js
- packages/markdownlint-rule-mui/terminal-language.js
A quick complement to #37643, to get a clear error:
and
> [docs-infra] Add test case when using sh

- docs/pages/careers.tsx
- docs/src/components/home/MuiStatistics.tsx
- docs/src/pages/careers/accessibility-engineer.md
- docs/src/pages/careers/product-marketing-manager.md
- docs/src/pages/careers/react-community-engineer.md
- docs/src/pages/careers/react-engineer-x.md
- docs/src/pages/careers/technical-recruiter.md
https://deploy-preview-37847--material-ui.netlify.app/careers/
> [website] Sync career page

- package.json
- yarn.lock
This is unlocked by #37173. Same as https://github.com/mui/mui-x/pull/8979
> Bump yarn-deduplicate to ^6.0.2

- docs/data/base/components/slider/LabeledValuesSlider.js
- docs/data/base/components/slider/LabeledValuesSlider.tsx
- docs/src/modules/components/Demo.js
- docs/src/modules/components/DemoToolbar.js
- docs/src/modules/components/DemoToolbarRoot.ts
Fix a regression I introduced in #37762
Open https://mui.com/x/react-data-grid/column-visibility/#disable-action-buttons, it moves, the scrollbar position is wrong.
> [docs-infra] Fix layout shift on xGrid

- docs/data/material/guides/next-js-app-router/next-js-app-router.md
> [docs] Fix typo in next-js-app-router.md

- docs/pages/blog/2023-toolpad-beta-announcement.md
> Blog MUI X pro statement removed 

- docs/src/components/productCore/CoreProducts.tsx
> [website] Link new core page to new Base UI landing page

- docs/src/components/pricing/PricingTable.tsx
The pricing page is confusing, the problem was raised in https://github.com/mui/mui-x/issues/199#issuecomment-1641082611.
> [website] Fix Cell selection feature name

- docs/data/joy/components/link/BasicsLink.js
- docs/data/joy/components/link/BasicsLink.tsx
- docs/data/joy/components/link/BasicsLink.tsx.preview
- docs/data/joy/components/link/LinkColors.js
- docs/data/joy/components/link/LinkColors.tsx
- docs/data/joy/components/link/LinkDisabled.js
- docs/data/joy/components/link/LinkDisabled.tsx
- docs/data/joy/components/link/LinkDisabled.tsx.preview
- docs/data/joy/components/link/LinkLevels.js
- docs/data/joy/components/link/LinkLevels.tsx
- docs/data/joy/components/link/LinkUnderline.js
- docs/data/joy/components/link/LinkUnderline.tsx
- docs/data/joy/components/link/LinkUnderline.tsx.preview
- docs/data/joy/components/link/LinkVariants.js
- docs/data/joy/components/link/LinkVariants.tsx
- docs/data/joy/components/link/LinkVariants.tsx.preview
- docs/data/joy/components/link/link.md
Part of https://github.com/mui/material-ui/issues/33998
This revision comes inspired by https://github.com/mui/material-ui/pull/37817 where I personally realized the different Link behavior when it comes to the variant prop. Made sure to document that and also included other standard sections/demos other components have.
> [docs][joy] Revise the Joy UI Link page

- docs/data/material/customization/palette/ContrastThreshold.js
- docs/data/material/customization/palette/ContrastThreshold.tsx
- docs/data/material/customization/palette/ManuallyProvideCustomColor.js
- docs/data/material/customization/palette/ManuallyProvideCustomColor.tsx
- docs/data/material/customization/palette/ManuallyProvidePaletteColor.js
- docs/data/material/customization/palette/ManuallyProvidePaletteColor.tsx
- docs/data/material/customization/palette/UsingAugmentColor.js
- docs/data/material/customization/palette/UsingAugmentColor.tsx
- docs/data/material/customization/palette/UsingColorObject.js
- docs/data/material/customization/palette/UsingColorObject.tsx
- docs/data/material/customization/palette/UsingStylesUtils.js
- docs/data/material/customization/palette/UsingStylesUtils.tsx
Fix [test_lint](https://app.circleci.com/pipelines/github/mui/material-ui/103061/workflows/bb25933c-73e2-41bd-a505-69a59cb1b300/jobs/550026) on master branch by matching main component demo name to filename. The ESlint rule was intoduced in #37278, and it was missed to merge with the latest master branch in #37743.
> [test] Fix linting error by matching main component demo name to filename

- docs/pages/blog/2023-toolpad-beta-announcement.md
> [blog] Update discord server link

- docs/data/joy/components/menu/MenuToolbarExample.js
> [docs] Fix Joy UI menu example

- docs/src/components/header/HeaderNavDropdown.tsx
> [website] Mobile navigation: Toolpad to Beta 

- docs/pages/blog/2023-toolpad-beta-announcement.md
- docs/public/_redirects
A continuation of #38131
To consider if it's worth getting the the level 3 of boost for https://www.notion.so/mui-org/Thoughts-on-Discord-server-first-draft-5a35bbfbca254ed29245b11808f93cc3?pvs=4#e93d7c2b987c4f33b07210880400200d. Or if this could be simple enough. In any case, if we ever decide to change in the future, a redirection could be great to avoid broken links.
> [docs] Avoid broken link

- docs/data/joy/customization/theme-typography/NewTypographyLevel.tsx
After #38199, #36843 was merged without updating with the latest master branch. We need to match the TS demo with the newly updated JS demo file which has the style changes. This will fix the failing CI.
> [docs][joy] Update the TypeScript file to match the styles in the corresponding JavaScript file for adding more typography levels demo

- docs/pages/_app.js
- docs/src/modules/components/AppSearch.js
A small detail fix
On https://mui.com/core/
it would make more sense to get results from MUI Core, not MUI X.
> [docs-infra] Search with productCategory when product is missing

- docs/pages/base-ui/api/number-input.json
Fix the CI for #36119. Found while working on #38123.
> [docs] Update API docs for Number Input component

- docs/data/joy/customization/theme-typography/CustomTypographyLevel.js
- docs/data/joy/customization/theme-typography/CustomTypographyLevel.tsx
- docs/data/joy/customization/theme-typography/CustomTypographyLevel.tsx.preview
- docs/data/joy/customization/theme-typography/TypographyThemeViewer.js
- docs/data/joy/customization/theme-typography/TypographyThemeViewer.tsx
- docs/data/joy/customization/theme-typography/theme-typography.md
While playing with this PR https://github.com/mui/material-ui/pull/38284 and browsing through the docs-feedback channel, I realized this page could use a revision, considering some stuff became outdated after the default theme polish PR merge!
**https://deploy-preview-38285--material-ui.netlify.app/joy-ui/customization/theme-typography/**
> [docs][joy-ui] Revise the theme typography page

- docs/src/components/productBaseUI/BaseUITestimonial.tsx
A quick frustration I had, my network sometimes struggles
Before
https://github.com/mui/material-ui/assets/3165635/c7881a2a-769d-4e36-9119-3b7330742637
After
https://github.com/mui/material-ui/assets/3165635/0f172550-2457-4039-a62d-10bc8fff70dd
> [website] Fix image layout shift

- docs/pages/joy-ui/api/tab-panel.json
- docs/translations/api-docs-joy/tab-panel/tab-panel.json
- packages/mui-joy/src/TabPanel/TabPanel.tsx
- packages/mui-joy/src/TabPanel/TabPanelProps.ts
> [TabPanel][joy] Add `keepMounted` prop

- docs/src/components/home/StoreTemplatesBanner.tsx
Closes https://github.com/mui/material-ui/issues/38458
> [website] Fix template link on the homepage

- docs/data/material/components/tabs/NavTabs.js
- docs/data/material/components/tabs/NavTabs.tsx
- docs/data/material/components/tabs/tabs.md
- docs/data/material/guides/routing/routing.md
- docs/src/modules/components/AppNavDrawerItem.js
- docs/src/modules/components/AppTableOfContents.js
- docs/src/modules/components/MarkdownLinks.js
Closes: #35388
An alternative to #35597
Preview: https://deploy-preview-38315--material-ui.netlify.app/material-ui/react-tabs/#nav-tabs
> [docs][material-ui] Improve nav link tab example

- CHANGELOG.md
- CHANGELOG.old.md
- README.md
- docs/data/material/discover-more/backers/backers.md
- docs/data/material/getting-started/faq/faq.md
- docs/pages/about.tsx
- docs/pages/blog/material-ui-v1-is-out.md
- docs/src/components/home/DiamondSponsors.tsx
Ensuring it's up to date with the `DiamondSponsors` component!
> [docs] Update the backers page

- packages/mui-material/src/Skeleton/Skeleton.js
Replicate #38384
Preview: https://deploy-preview-38506--material-ui.netlify.app/material-ui/react-skeleton/
> [Skeleton][material-ui] Soften the pulse animation

- docs/data/joy/getting-started/templates/TemplateCollection.js
Data from https://analytics.google.com/analytics/web/#/analysis/p353089763/edit/YnoVycxnS_K4lKrbocE9-A
Preview: https://deploy-preview-38490--material-ui.netlify.app/joy-ui/getting-started/templates/
> [docs][joy-ui] Sort templates by popularity

- docs/src/components/home/MaterialDesignComponents.tsx
- docs/src/components/productMaterial/MaterialComponents.tsx
- docs/src/components/productMaterial/MaterialHero.tsx
- docs/src/components/productMaterial/MaterialStyling.tsx
- docs/src/components/productMaterial/MaterialTheming.tsx
- docs/src/components/showcase/PlayerCard.tsx
- docs/src/components/showcase/RealEstateCard.tsx
Just doing a general fine-tune quality-of-life attention to this page. Some stuff here was already outdated!
**https://deploy-preview-38590--material-ui.netlify.app/material-ui**
> [website] Add stray design improvements to the Material UI page

- docs/src/modules/components/Ad.js
- docs/src/modules/components/AppLayoutDocs.js
This time, share the same variables, I made the mistake the previous time not to do it.
Fix https://github.com/mui/material-ui/pull/38504#issuecomment-1690637684
> [docs-infra] Fix ad layout shift

- docs/pages/blog/mui-x-mid-v6-features.md
- docs/pages/blog/mui-x-v6.md
- docs/pages/experiments/docs/headers.md
- docs/pages/experiments/docs/markdown.md
- packages/markdown/parseMarkdown.js
Raised in https://github.com/mui/mui-x/pull/10026#discussion_r1293184811. This PR adds support for: https://github.com/mui/material-ui/blob/f2fbe4b2ba3a0e996c7119c4d25a42563d1753d0/docs/pages/experiments/docs/markdown.md?plain=1#L36
> [docs-infra] Support link title

- docs/translations/api-docs/loading-button/loading-button.json
- packages/mui-lab/src/LoadingButton/LoadingButton.d.ts
- packages/mui-lab/src/LoadingButton/LoadingButton.js
opened PR based on: https://github.com/mui/material-ui/pull/38156#discussion_r1304061471
preview: https://deploy-preview-38625--material-ui.netlify.app/material-ui/api/loading-button/#LoadingButton-prop-loading
> [docs][lab][LoadingButton] Improve `loading` prop documentation

- docs/src/components/home/DiamondSponsors.tsx
- docs/src/components/home/GoldSponsors.tsx
Just some quality-of-life improvements to make the icon button consistent as well as ensure better contrast with the yellow "Gold" heading! 😬
> [website] Add tiny fixes the homepage Sponsors section

- docs/data/material/guides/server-rendering/server-rendering.md
- docs/data/material/guides/understand-mui-packages/understand-mui-packages.md
Fix:
- https://mui-org.slack.com/archives/C041SDSF32L/p1693035467611079
- https://mui-org.slack.com/archives/C041SDSF32L/p1692963817065519
Preview: https://deploy-preview-38651--material-ui.netlify.app/material-ui/guides/server-rendering/#reference-implementations
> [docs] Improve SSR example reference

- docs/data/joy/components/stack/BasicStack.js
- docs/data/joy/components/stack/BasicStack.tsx
- docs/data/joy/components/stack/DirectionStack.js
- docs/data/joy/components/stack/DirectionStack.tsx
- docs/data/joy/components/stack/DirectionStack.tsx.preview
- docs/data/joy/components/stack/DividerStack.js
- docs/data/joy/components/stack/DividerStack.tsx
- docs/data/joy/components/stack/FlexboxGapStack.js
- docs/data/joy/components/stack/FlexboxGapStack.tsx
- docs/data/joy/components/stack/FlexboxGapStack.tsx.preview
- docs/data/joy/components/stack/InteractiveStack.js
- docs/data/joy/components/stack/InteractiveStack.tsx
- docs/data/joy/components/stack/ResponsiveStack.js
- docs/data/joy/components/stack/ResponsiveStack.tsx
- docs/data/joy/components/stack/ZeroWidthStack.js
- docs/data/joy/components/stack/ZeroWidthStack.tsx
- docs/data/joy/components/stack/stack.md
This PR does some polishing to the Joy UI Stack page, making it adhere to the heading hierarchy we've been using it, as well as very light touches on copywriting and the component demos. 
**https://deploy-preview-38623--material-ui.netlify.app/joy-ui/react-stack/**
> [docs][joy-ui] Polish the Stack page

- docs/src/modules/brandingTheme.ts
Just some additional quality-of-life fine-tuning on the branding theme buttons.
> [website] Fine-tune branding buttons box shadows

- docs/src/components/header/HeaderNavDropdown.tsx
> [website] Fix out-of-date label on Toolpad

- docs/data/joy/components/link/LinkCard.js
- docs/data/joy/components/link/LinkCard.tsx
- docs/data/joy/components/link/LinkCard.tsx.preview
As reported in https://github.com/mui/material-ui/issues/38701. Also took the opportunity to simplify it considerably!
**https://deploy-preview-38702--material-ui.netlify.app/joy-ui/react-link/#overlay-prop**
> [docs][joy-ui] Fix Link's `overlay` prop demo

- CHANGELOG.md
- CHANGELOG.old.md
- docs/data/joy/components/autocomplete/FreeSoloCreateOptionDialog.js
- docs/data/joy/components/autocomplete/FreeSoloCreateOptionDialog.tsx
- docs/data/material/components/autocomplete/FreeSoloCreateOptionDialog.js
- docs/data/material/components/autocomplete/FreeSoloCreateOptionDialog.tsx
- docs/data/material/guides/minimizing-bundle-size/minimizing-bundle-size-pt.md
- docs/data/material/guides/minimizing-bundle-size/minimizing-bundle-size-zh.md
- docs/data/material/guides/minimizing-bundle-size/minimizing-bundle-size.md
- docs/pages/blog/callback-support-in-style-overrides.md
- docs/src/modules/sandbox/Dependencies.ts
- docs/translations/api-docs/circular-progress/circular-progress-pt.json
- docs/translations/api-docs/circular-progress/circular-progress-zh.json
- docs/translations/api-docs/circular-progress/circular-progress.json
- packages/mui-joy/src/Button/Button.tsx
- packages/mui-joy/src/Chip/Chip.tsx
- packages/mui-joy/src/IconButton/IconButton.tsx
- packages/mui-joy/src/ListItem/ListItem.tsx
- packages/mui-joy/src/styles/styleUtils.ts
- packages/mui-material/src/CircularProgress/CircularProgress.d.ts
- packages/mui-material/src/CircularProgress/CircularProgress.js
- packages/typescript-to-proptypes/src/injector.ts
- packages/zero-tag-processor/src/utils/sxObjectExtractor.ts
- scripts/generateProptypes.ts
- test/README.md
- test/utils/initMatchers.ts
Noticed in #38747
https://english.stackexchange.com/questions/241104/is-e-g-or-e-g-correct
> [docs] Fix e.g. typo

- docs/public/_redirects
- docs/src/modules/components/ApiPage.js
- docs/src/modules/components/ComponentsApiContent.js
> [docs] Fix Joy UI docs link regression

- docs/src/modules/components/JoyThemeBuilder.tsx
- As of now if you add a color string in theme and remove it, it breaks the UI
- We can add token with empty names and invalid color
> [joy-ui][theme] Improve theme builder exceptions

- docs/data/joy/components/linear-progress/LinearProgressCountUp.js
- docs/data/joy/components/linear-progress/LinearProgressCountUp.tsx
- docs/data/joy/components/linear-progress/linear-progress.md
- docs/package.json
- packages/mui-joy/src/LinearProgress/LinearProgress.tsx
- yarn.lock
> [docs][joy-ui] Integrate a count-up feature to the Linear Progress

- docs/data/base/getting-started/customization/PrepareForSlot.js
- docs/data/base/getting-started/customization/PrepareForSlot.tsx
- docs/data/base/getting-started/customization/PrepareForSlot.tsx.preview
As discussed in https://github.com/mui/material-ui/pull/38138#discussion_r1299417564
> [docs][base-ui] Add type parameter to the button in prepareForSlot demo

- docs/data/material/components/typography/typography.md
Another one from the series "surfing around looking for improvement opportunities", figured this one would be a quickie. 😬 
**https://deploy-preview-38543--material-ui.netlify.app/material-ui/react-typography/**
> [docs][material-ui] Revise the Typography page

- docs/data/material/components/buttons/InputFileUpload.js
- docs/data/material/components/buttons/InputFileUpload.tsx
- docs/data/material/components/buttons/InputFileUpload.tsx.preview
Following up on comments left at https://github.com/mui/material-ui/pull/38786.
> [material-ui][Button] Update the file upload demo

- docs/data/base/pages.ts
Added the Preview chip to the Popup in the side nav.
> [docs][base-ui] Mark Popup with the Preview tag

- docs/data/joy/main-features/color-inversion/color-inversion.md
I found the grammar fixes while reading this page to implement color inversion for the Joy UI Snackbar component (#38801).
> [docs][joy-ui] Fix grammar and update Usage section in color inversion page

- packages/mui-system/src/cssVars/getInitColorSchemeScript.tsx
This seems dead code.
I noticed this in #38794.
> [system] Remove dead code

- docs/data/joy/getting-started/tutorial/tutorial.md
As reported on the docs-feedback channel!
> [docs][joy-ui] Fix copy on the Tutorial page

- README.md
- packages/mui-base/README.md
- packages/mui-icons-material/README.md
- packages/mui-joy/README.md
- packages/mui-lab/README.md
- packages/mui-material/README.md
- packages/mui-styled-engine-sc/README.md
- packages/mui-styled-engine/README.md
- packages/mui-styles/README.md
- packages/mui-system/README.md
- scripts/copyFiles.mjs
The objective is to create a nice experience like in https://www.npmjs.com/package/next. These two don't feel great:
- https://www.npmjs.com/package/@mui/material
- https://www.npmjs.com/package/@mui/joy
New content:
- https://github.com/oliviertassinari/material-ui/blob/docs-improve-readme/README.md
- https://github.com/oliviertassinari/material-ui/blob/docs-improve-readme/packages/mui-material/README.md
- https://github.com/oliviertassinari/material-ui/blob/docs-improve-readme/packages/mui-joy/README.md
- https://github.com/oliviertassinari/material-ui/blob/docs-improve-readme/packages/mui-base/README.md
> [docs] Improve npm experience

- .circleci/config.yml
Tested with the PR conditional disable and managed to upload to S3 in https://app.circleci.com/pipelines/github/mui/material-ui/108396/workflows/eb202997-db81-409b-81ba-8c6b81160b1f/jobs/580529/parallel-runs/0/steps/0-113 and in https://app.circleci.com/pipelines/github/mui/material-ui/108396/workflows/eb202997-db81-409b-81ba-8c6b81160b1f/jobs/580529/parallel-runs/0/steps/0-120
> [core] Fix bundle size upload to S3 job

- docs/data/material/components/pagination/pagination.md
- docs/pages/material-ui/api/table-pagination.json
- packages/mui-material/src/TablePagination/TablePagination.d.ts
> [docs][material-ui][Pagination] Add `TablePagination` to the API components list

- packages/mui-utils/src/useEnhancedEffect/useEnhancedEffect.ts
See https://github.com/mui/mui-toolpad/pull/2671#discussion_r1328078673
also, consider renaming this hook to something more descriptive. e.g. I've seen other libraries use `useIsomorphicLayoutEffect`.
> [core] Add a comment to explain `useEnhancedEffect`

- docs/src/modules/components/JoyStartingLinksCollection.js
Closes https://github.com/mui/material-ui/issues/39085
> [docs][joy-ui] Fix the Templates link on the Overview page

- packages/mui-material/src/locale/index.ts
> [l10n] labelDisplayedRows is added for trTR localization

- docs/data/joy/components/card/card.md
> [docs][joy-ui] Fix wrong hash on Card's page

- .eslintrc.js
- docs/pages/base-ui.tsx
- docs/pages/joy-ui/getting-started/templates/messages.js
- docs/pages/joy-ui/getting-started/templates/order-dashboard.js
- docs/pages/joy-ui/getting-started/templates/profile-dashboard.js
- docs/pages/joy-ui/getting-started/templates/rental-dashboard.js
- docs/pages/joy-ui/getting-started/templates/sign-in-side.js
- package.json
- yarn.lock
Enables https://nextjs.org/docs/pages/building-your-application/configuring/eslint#eslint-plugin on the docs
A redo of https://github.com/mui/material-ui/pull/32809
> Add next lint config to eslint

- docs/src/components/action/InfoCard.tsx
- docs/src/components/productCore/CoreProducts.tsx
Just cleaning up stuff a bit in the `CoreProducts` file. I had introduced the `InfoCard` component a while back and this one was missing on using it. 😄 
👉  **https://deploy-preview-39194--material-ui.netlify.app/core**
> [website] Simplify the Core products file

- docs/data/joy/components/accordion/accordion.md
Fixed minor typo in accordion.md
- [✓] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/material-ui/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).
> [docs][joy-ui] Fix typo in the Accordion page

- docs/data/joy/components/aspect-ratio/aspect-ratio.md
Removed incomplete sentence in aspect-ratio.md. I didn't finish the sentence because I don't think there is much more to say, but I am open to suggestions.
- [✓] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/material-ui/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).
> [docs][joy-ui] Removed incomplete sentence in the Aspect Ratio page

- docs/pages/careers/react-engineer-x-charts.md
Ashby role has been created so this is the correct link for this position
> [website] Update `React Engineer - xCharts` Ashby link

- .eslintrc.js
- docs/src/modules/components/AppNavDrawer.js
- packages/typescript-to-proptypes/src/getPropTypesFromFile.ts
Follow-up of this shaping document: https://www.notion.so/mui-org/eslint-rules-update-eec627990f2d4a84830e9fd0981e2f6d.
cc @mui/code-infra
> [core] Update eslint rules

- docs/src/components/pricing/PricingTable.tsx
https://github.com/mui/material-ui/pull/38680#pullrequestreview-1641823470 I image it's a leftover.
> [website] Add Heat map in pricing page

- docs/data/base/components/input/InputMultiline.js
- docs/data/base/components/input/InputMultiline.tsx
- docs/data/base/components/input/InputMultilineAutosize.js
- docs/data/base/components/input/InputMultilineAutosize.tsx
Fixed https://github.com/mui/material-ui/issues/39176
https://github.com/mui/material-ui/assets/9917124/c6446b61-1bc8-496f-a5d0-9e92dd8d28b9
> [docs][base-ui] Fix style for root div of multiline input

- docs/data/material/components/chips/chips.md
This PR adds just a tiny design improvement to the playground demo (i.e., adds `bg: playground` to remove the padding) and standardizes the paragraph for the Material You section. 😊
> [docs][material-ui] Adjust the Material You Chip section

- packages/mui-material-next/src/Menu/Menu.d.ts
- packages/mui-material-next/src/Menu/Menu.js
- packages/mui-material-next/src/Menu/Menu.test.js
- packages/mui-material-next/src/Menu/index.d.ts
- packages/mui-material-next/src/Menu/index.js
- packages/mui-material-next/src/Menu/menuClasses.ts
- packages/mui-material-next/src/MenuItem/MenuItem.d.ts
- packages/mui-material-next/src/MenuItem/MenuItem.js
- packages/mui-material-next/src/MenuItem/MenuItem.spec.tsx
- packages/mui-material-next/src/MenuItem/MenuItem.test.js
- packages/mui-material-next/src/MenuItem/index.d.ts
- packages/mui-material-next/src/MenuItem/index.js
- packages/mui-material-next/src/MenuItem/menuItemClasses.ts
> [Menu][material-next] Copy v5 Menu components

- docs/src/components/footer/EmailSubscribe.tsx
- docs/src/layouts/AppFooter.tsx
Closes https://github.com/mui/material-ui/issues/39270
Responsiveness improvements to the website's footer component. The issues were mostly visible below 330px wide.
> [website] Fix footer responsiveness

- packages/mui-joy/src/Textarea/Textarea.tsx
- packages/mui-joy/src/Textarea/TextareaProps.ts
close #39329 
**After**: https://codesandbox.io/s/joy-ui-cra-ts-k6tncs?file=/src/App.tsx
> [joy-ui][Textarea] Fix focus ring for error state

- docs/data/material/components/snackbars/FabIntegrationSnackbar.js
- docs/data/material/components/snackbars/FabIntegrationSnackbar.tsx
The theme type was fixed in #30072, making this TODO irrelevant.
> [docs][material-ui] Remove irrelevant TODO from Snackbar demo

- docs/data/material/getting-started/design-resources/design-resources.md
- docs/pages/material-ui/getting-started/design-resources.js
- docs/src/components/action/InfoCard.tsx
- docs/src/modules/components/JoyStartingLinksCollection.js
- docs/src/modules/components/MaterialUIDesignResources.js
This PR adds the Figma store link to the Joy UI overview page + adds a bit of polish to the Material UI one.
- **https://deploy-preview-39367--material-ui.netlify.app/joy-ui/getting-started/#start-now**
- **https://deploy-preview-39367--material-ui.netlify.app/material-ui/getting-started/design-resources/**
> [docs] Adjust design kits-related content

- docs/data/material/components/table/EnhancedTable.js
- docs/data/material/components/table/EnhancedTable.tsx
Closes #39107 - there is a bug in the "[Sorting & Selecting](https://mui.com/material-ui/react-table/#sorting-amp-selecting)" demo with items with the same name. 
- Added `id` in the createData function and tweaked other functions. 
I would like @samuelsycamore to review this PR.
> [material-ui][Table] Bug in "Sorting & Selecting" demo

- docs/pages/careers/ROLE_TEMPLATE.md
- docs/pages/careers/accessibility-engineer.md
- docs/pages/careers/design-engineer.md
- docs/pages/careers/designer.md
- docs/pages/careers/developer-advocate.md
- docs/pages/careers/developer-experience-engineer.md
- docs/pages/careers/engineering-manager.md
- docs/pages/careers/full-stack-engineer.md
- docs/pages/careers/head-of-operations.md
- docs/pages/careers/people-operation-manager.md
- docs/pages/careers/product-engineer.md
- docs/pages/careers/product-manager.md
- docs/pages/careers/product-marketing-manager.md
- docs/pages/careers/react-community-engineer.md
- docs/pages/careers/react-engineer-core.md
- docs/pages/careers/react-engineer-x-charts.md
- docs/pages/careers/react-engineer-x-grid.md
- docs/pages/careers/react-engineer-x.md
- docs/pages/careers/react-tech-lead-core.md
- docs/pages/careers/react-tech-lead-x-grid.md
- docs/pages/careers/senior-designer.md
- docs/pages/careers/support-agent.md
- docs/pages/careers/technical-product-manager.md
- docs/pages/careers/technical-recruiter.md
Propagate #39210, new template: https://deploy-preview-39386--material-ui.netlify.app/careers/react-engineer-x-charts/
> [website] Update new role template

- packages/mui-material/src/Tabs/Tabs.js
Closes #39394
Before:
https://github.com/mui/material-ui/assets/717550/7bab4814-8dfa-4db7-838e-b7107f0194a8
After:
https://deploy-preview-39415--material-ui.netlify.app/material-ui/react-tabs/#dynamically-added-tabs
> [material][tab] Show/hide scroll buttons for dynamically added children

- packages/mui-styled-engine-sc/package.json
- packages/mui-styled-engine-sc/src/index.d.ts
- packages/mui-styled-engine/src/index.d.ts
- packages/mui-system/src/Container/createContainer.tsx
- yarn.lock
Fixes https://github.com/mui/material-ui/issues/34527
Testing repository: https://github.com/mnajdova/mui-styled-engine-sc-ts-fixes
> [styled-engine-sc] Fix TS issues because of missing types

- docs/pages/blog.tsx
- docs/src/components/action/Item.tsx
- docs/src/components/home/CoreShowcase.tsx
- docs/src/components/home/Hero.tsx
- docs/src/components/home/MaterialDesignComponents.tsx
- docs/src/components/home/MaterialDesignDemo.tsx
- docs/src/components/home/UserFeedbacks.tsx
- docs/src/components/productBaseUI/BaseUIComponents.tsx
- docs/src/components/productBaseUI/BaseUIEnd.tsx
- docs/src/components/productBaseUI/BaseUIHero.tsx
- docs/src/components/productBaseUI/BaseUITestimonial.tsx
- docs/src/components/productDesignKit/DesignKitDemo.tsx
- docs/src/components/productMaterial/MaterialComponents.tsx
- docs/src/components/productMaterial/MaterialDesignKits.tsx
- docs/src/components/productTemplate/TemplateDemo.tsx
- docs/src/components/productX/XComponents.tsx
- docs/src/components/productX/XDataGrid.tsx
- docs/src/components/productX/XTheming.tsx
- docs/src/components/showcase/FolderTable.tsx
- docs/src/components/showcase/NotificationCard.tsx
- docs/src/components/showcase/TaskCard.tsx
- docs/src/components/showcase/ThemeDatePicker.tsx
- docs/src/components/typography/SectionHeadline.tsx
This PR adds a series of small design adjustments as well as some code simplifications here and there. 
Mostly a website housekeeping! 🤙
> [website] Add stray design adjustments

- docs/data/material/guides/localization/localization.md
- packages/mui-material/src/locale/index.ts
> [I10n] Add Norwegian (nynorsk) (nn-NO) locale

- docs/data/joy/components/box/box.md
- docs/data/joy/pages.ts
- docs/data/material/components/box/box.md
- docs/data/system/components/box/BoxBasic.js
- docs/data/system/components/box/BoxBasic.tsx
- docs/data/system/components/box/BoxBasic.tsx.preview
- docs/data/system/components/box/BoxSx.js
- docs/data/system/components/box/BoxSx.tsx
- docs/data/system/components/box/box.md
- docs/pages/joy-ui/react-box.js
- docs/pages/system/api/box.json
- docs/translations/translations.json
- packages/mui-system/src/Box/Box.d.ts
Closes https://github.com/mui/material-ui/issues/35699
This PR revises the Box page on the MUI System docs and adds a Box page to the Joy UI docs, but just to refer back to the original MUI System docs to avoid content duplication and maintenance cost (same with Material UI).
👉 **https://deploy-preview-39159--material-ui.netlify.app/system/react-box/**
👉  **https://deploy-preview-39159--material-ui.netlify.app/joy-ui/react-box/**
> [docs][system] Revise the Box page

- docs/data/base/components/slider/DiscreteSlider.js
- docs/data/base/components/slider/DiscreteSlider.tsx
- docs/data/base/components/slider/DiscreteSliderMarks.js
- docs/data/base/components/slider/DiscreteSliderMarks.tsx
- docs/data/base/components/slider/DiscreteSliderValues.js
- docs/data/base/components/slider/DiscreteSliderValues.tsx
- docs/data/base/components/slider/LabeledValuesSlider.js
- docs/data/base/components/slider/LabeledValuesSlider.tsx
- docs/data/base/components/slider/RangeSlider.js
- docs/data/base/components/slider/RangeSlider.tsx
- docs/data/base/components/slider/UnstyledSlider.js
- docs/data/base/components/slider/UnstyledSlider.tsx
- docs/data/base/components/slider/UnstyledSliderBasic/system/index.js
- docs/data/base/components/slider/UnstyledSliderBasic/system/index.tsx
- docs/data/base/components/slider/UnstyledSliderIntroduction/css/index.js
- docs/data/base/components/slider/UnstyledSliderIntroduction/css/index.tsx
- docs/data/base/components/slider/UnstyledSliderIntroduction/system/index.js
- docs/data/base/components/slider/UnstyledSliderIntroduction/system/index.tsx
- docs/data/base/components/slider/UnstyledSliderIntroduction/tailwind/index.js
- docs/data/base/components/slider/UnstyledSliderIntroduction/tailwind/index.tsx
- docs/data/base/components/slider/VerticalSlider.js
- docs/data/base/components/slider/VerticalSlider.tsx
Follow-up to https://github.com/mui/material-ui/pull/38820
Standardize the `focus-visible` on all Base UI `Slider` demos.
> [base-ui][Slider] Refine demos

- docs/data/material/getting-started/overview/overview.md
> [docs][material-ui] Typo fixes in overview page

- apps/zero-runtime-next-app/next.config.js
- apps/zero-runtime-next-app/src/components/Grid.tsx
- apps/zero-runtime-next-app/src/components/Slider/ZeroSlider.tsx
- apps/zero-runtime-next-app/src/components/SliderWrapper.tsx
- apps/zero-runtime-next-app/src/extend-zero.d.ts
- apps/zero-runtime-vite-app/.eslintrc
- apps/zero-runtime-vite-app/package.json
- apps/zero-runtime-vite-app/src/App.tsx
- apps/zero-runtime-vite-app/src/Slider/ZeroSlider.tsx
- apps/zero-runtime-vite-app/src/extend-zero.d.ts
- apps/zero-runtime-vite-app/src/main.tsx
- apps/zero-runtime-vite-app/tsconfig.json
- apps/zero-runtime-vite-app/vite-env.d.ts
- apps/zero-runtime-vite-app/vite.config.ts
- packages/zero-runtime/package.json
- packages/zero-runtime/src/base.d.ts
- packages/zero-runtime/src/index.ts
- packages/zero-runtime/src/keyframes.d.ts
- packages/zero-runtime/src/styled.d.ts
- packages/zero-runtime/src/styled.spec.tsx
- packages/zero-runtime/src/sx.d.ts
- packages/zero-runtime/src/theme.d.ts
- packages/zero-tag-processor/src/pre-linaria-plugin.ts
- packages/zero-tag-processor/src/sx.ts
> [zero][runtime] Implement typings for public runtime API

- docs/data/joy/components/textarea/TextareaRef.js
- docs/data/joy/components/textarea/TextareaRef.tsx
- docs/data/joy/components/textarea/TextareaRef.tsx.preview
- docs/data/joy/components/textarea/textarea.md
Closes https://github.com/mui/material-ui/issues/39187
This PR adds the same thing as this one https://github.com/mui/material-ui/pull/39277. I'm just recreating it because the tests keep repeatedly failing due to some strange auth problem I couldn't figure out. Credits goes out to @luv2027 for taking the initiative to work on this issue! 🤙
> [joy-ui][Textarea] Add ref usage instructions

- benchmark/browser/index.html
- docs/data/material/guides/server-rendering/server-rendering.md
- docs/src/modules/sandbox/CodeSandbox.test.js
- docs/src/modules/sandbox/CreateReactApp.ts
- docs/src/modules/sandbox/StackBlitz.test.js
- examples/material-ui-express-ssr/server.js
- examples/material-ui-via-cdn/index.html
Noticed this in https://github.com/mui/mui-x/pull/10661#issuecomment-1761511263.
> [docs-infra] Add meta charset in codesandbox examples

- docs/data/joy/customization/themed-components/themed-components.md
Closes #38509
👉 **https://deploy-preview-39597--material-ui.netlify.app/joy-ui/customization/themed-components/**
> [joy-ui][docs] Add docs for changing styles based on states

- docs/data/joy/components/card/NestedCard.js
- docs/data/joy/components/card/NestedCard.tsx
- docs/data/joy/components/card/card.md
- packages/mui-joy/src/CardOverflow/CardOverflow.tsx
closes #39621 
🖥️ **Preview**: https://deploy-preview-39668--material-ui.netlify.app/joy-ui/react-card/#nested-cards
**Before**:
https://codesandbox.io/s/sparkling-surf-r2p3h6?file=/src/Demo.tsx
**After**:
https://codesandbox.io/s/billowing-bush-pgx3ks?file=/src/Demo.tsx
> [Card] Fix CardOverflow in nested cards

- packages/zero-runtime/src/styled.d.ts
- packages/zero-runtime/src/styled.js
- packages/zero-runtime/src/styled.spec.tsx
- packages/zero-runtime/src/styled.test.js
Added a small test and more TS specs
> [zero][system] Support props from "as" component

- README.md
❌ www.mui.com/system/ —> ✅ www.mui.com/system/getting-started/
> [core][docs] Fix broken MUI System link in README.md

- CHANGELOG.md
Corrected the Joy UI package version in the changelog.
Fixes #39784
> [CHANGELOG] Correct the Joy UI version in the changelog

- docs/data/base/components/number-input/NumberInputIntroduction/css/index.js
- docs/data/base/components/number-input/NumberInputIntroduction/css/index.tsx
- docs/data/base/components/number-input/NumberInputIntroduction/tailwind/index.js
- docs/data/base/components/number-input/NumberInputIntroduction/tailwind/index.tsx
> [docs][base-ui][number-input] Fix inconsistent demo component names

- packages/mui-joy/src/Select/Select.test.tsx
- packages/mui-joy/src/Select/Select.tsx
part of : https://github.com/mui/material-ui/issues/39799 (ts bug mentioned in this [comment](https://github.com/mui/material-ui/issues/39799#issuecomment-1801747839) is not fixed in this PR)
missed handling this bug in this PR https://github.com/mui/material-ui/pull/39454
> [Select][joy-ui] Fix displaying placeholder when multiple is true

- docs/data/joy/components/button-group/button-group.md
address: https://mui-org.slack.com/archives/C050VE13HDL/p1699896563736099
preview: https://deploy-preview-39876--material-ui.netlify.app/joy-ui/react-button-group/#vertical-group
> [docs][joy-ui][ButtonGroup] Fix orientation prop description 

- docs/pages/joy-ui/api/box.json
- docs/translations/api-docs-joy/box/box.json
- packages/mui-joy/src/Box/Box.tsx
- packages/mui-joy/src/Box/boxClasses.ts
- packages/mui-joy/src/Box/index.ts
Added boxClasses for Box component in joy-ui [#39889](https://github.com/mui/material-ui/pull/39889)
> [joy-ui][Box] Added boxClasses

- docs/pages/system/api/box.json
- docs/translations/api-docs/box/box.json
- packages/mui-system/src/Box/Box.js
- packages/mui-system/src/Box/Box.test.js
- packages/mui-system/src/Box/boxClasses.ts
- packages/mui-system/src/Box/index.d.ts
- packages/mui-system/src/Box/index.js
Added boxClasses for Box component in system [#39889](https://github.com/mui/material-ui/pull/39889)
> [system][Box] Added boxClasses

- docs/data/joy/integrations/material-ui/material-ui.md
Preview - https://deploy-preview-39899--material-ui.netlify.app/joy-ui/integrations/material-ui/
> [docs][joy-ui] Fixes in theme scoping documentation

- packages/mui-types/index.d.ts
> [types] Add `PartiallyRequired` type to `@mui/types`

- docs/src/components/action/InfoCard.tsx
- docs/src/modules/components/ApiPage/list/ExpendableApiItem.tsx
- docs/src/modules/components/ApiPage/list/PropertiesList.tsx
- docs/src/modules/components/JoyStartingLinksCollection.js
- docs/src/modules/components/MaterialUIDesignResources.js
See https://github.com/mui/material-ui/pull/39367#discussion_r1401288707 for why
Preview: https://deploy-preview-39956--material-ui.netlify.app/material-ui/getting-started/design-resources/
> [docs] Restore Algolia results when searching for "Figma"

- docs/src/modules/components/MaterialUIExampleCollection.js
> [docs] Make integration searchable

- docs/data/material/migration/migration-v4/v5-style-changes.md
address: https://mui-org.slack.com/archives/C041SDSF32L/p1700753367144609
> [docs][material-ui] Fix theme prop in v5 migration guide

- packages/mui-system/src/borders.js
- packages/mui-system/src/borders.test.js
- packages/mui-system/src/styleFunctionSx/defaultSxConfig.js
- packages/mui-system/src/styleFunctionSx/styleFunctionSx.test.js
> [system] Add outlineColor to defaultSxConfig

- docs/src/components/pricing/PricingTable.tsx
Preview: https://deploy-preview-40023--material-ui.netlify.app/pricing/
> [website] Update pricing table

- docs/notifications.json
New notification for https://mui.com/blog/mui-x-end-v6-features/
> [docs] End v6 blogpost notification

- docs/data/material/getting-started/supported-components/supported-components.md
Remove reference to non-existent checkmark.
Preview: https://deploy-preview-40056--material-ui.netlify.app/material-ui/getting-started/supported-components/
> [docs] Fix reference to non-existent checkmark in supported-components.md

- docs/data/joy/components/css-baseline/css-baseline.md
> [joy-ui][docs] Fix typo in the CSS baseline page

- CHANGELOG.md
- docs/data/joy/components/text-field/text-field.md
- docs/data/material/migration/migration-v4/migrating-from-jss.md
- docs/data/material/migration/migration-v4/migration-v4.md
- docs/data/material/migration/migration-v4/troubleshooting.md
- docs/pages/blog/lab-date-pickers-to-mui-x.md
- docs/pages/blog/lab-tree-view-to-mui-x.md
- packages/mui-codemod/README.md
- packages/mui-joy/src/TextField/TextField.tsx
I spotted this problem from https://github.com/mui/mui-x/pull/11521#discussion_r1436637173.
> [docs] Always mention the npm tag with npx

- docs/data/base/getting-started/overview/overview.md
This PR updates the Base UI Overview page, removing the deadline that by Material v6, we'd have components refactored using Base components and hooks. Maybe that's still true, though, as we aim to do iteratively/gradually, but felt like mentioning v6 right away created a bigger expectation.
> [base-ui][docs] Update the overview page

- docs/src/modules/components/DiamondSponsors.js
- docs/src/modules/components/Notifications.js
A continuation of https://github.com/mui/material-ui/pull/39638
> [docs-infra] Remove dead code aria-label sponsors

- packages/mui-lab/package.json
- pnpm-lock.yaml
Addresses https://github.com/mui/material-ui/pull/39679#issuecomment-1862076021.
> [lab] Update `@mui/material` peer dependency version

- docs/data/material/guides/nextjs/nextjs.md
> [docs][material-ui] Fix typo on Next.js integration guide

- docs/data/joy/components/card/RowCard.js
- docs/data/joy/components/card/RowCard.tsx
Fix https://mui-org.slack.com/archives/C050VE13HDL/p1705067288413159. 
Preview: https://deploy-preview-40562--material-ui.netlify.app/joy-ui/react-card/#horizontal-alignment
> [docs][joy-ui][Card] Fix text alignment in horizontal aligned card demo

- docs/data/material/components/buttons/buttons.md
- docs/data/material/components/cards/cards.md
- docs/data/material/components/checkboxes/checkboxes.md
- docs/data/material/components/lists/lists.md
- docs/data/material/components/menus/menus.md
- docs/data/material/components/selects/selects.md
- docs/data/material/components/switches/switches.md
- docs/data/material/components/tabs/tabs.md
- docs/data/material/components/text-fields/text-fields.md
Closes https://github.com/mui/material-ui/issues/40554
> [docs] Fix MUI Treasury links

- docs/data/joy/getting-started/templates/messages/utils.ts
- docs/data/joy/getting-started/templates/order-dashboard/utils.ts
- docs/data/joy/getting-started/templates/profile-dashboard/utils.ts
Saw this in https://github.com/mui/material-ui/pull/40436/files#diff-1a789c7102503b05ee999e6b5919f0bb7ed66eda5ca272d88ee3e40f8288dff2R3. I think it's best to stick to a single API throughout MUI's codebase.
This is a detail though. I don't expect meaningful outcomes from this PR other than making it easier to search in the codebase these instances.
> [core] Simplify server detection

- docs/data/base/components/switch/UnstyledSwitchIntroduction/css/index.js
- docs/data/base/components/switch/UnstyledSwitchIntroduction/css/index.tsx
- docs/data/base/components/switch/UnstyledSwitchIntroduction/system/index.js
- docs/data/base/components/switch/UnstyledSwitchIntroduction/system/index.tsx
- docs/data/base/components/switch/UseSwitchesBasic.js
- docs/data/base/components/switch/UseSwitchesBasic.tsx
Closes #40634
https://deploy-preview-40638--material-ui.netlify.app/base-ui/react-switch/
> [base-ui][switch] Add border-box to demos

- docs/data/material/components/slider/CustomMarks.js
- docs/data/material/components/slider/CustomMarks.tsx
- docs/data/material/components/slider/CustomMarks.tsx.preview
- docs/data/material/components/slider/slider.md
Added example of how to add custom labels to the slider because of this issue
https://github.com/mui/material-ui/issues/40544
> [material-ui][docs][Slider] Added custom mark labels demo

- docs/src/components/productBaseUI/BaseUIThemesDemo.tsx
- docs/src/components/productBaseUI/components/BaseButtonDemo.tsx
- docs/src/components/productBaseUI/components/BaseInputDemo.tsx
- docs/src/components/productBaseUI/components/BaseMenuDemo.tsx
- docs/src/components/productBaseUI/components/BaseSliderDemo.tsx
- docs/src/components/productBaseUI/components/BaseTabsDemo.tsx
- docs/tailwind.config.js
Fixed the /base-ui page that got broken after changing the Base UI class prefix to `base-`
Preview: https://deploy-preview-40683--material-ui.netlify.app/base-ui
> [website] Fix broken styles on Base UI page

- docs/data/joy/getting-started/tutorial/LoginFinal.js
- docs/data/joy/getting-started/tutorial/tutorial.md
- docs/src/modules/components/Demo.js
https://mui.com/joy-ui/getting-started/tutorial/#interactive-demo has a couple of issues that this PR fix.
> [docs][joy-ui] Move tutorial to iframe

- packages/zero-runtime/src/utils/generateCss.ts
- packages/zero-unplugin/src/index.ts
- packages/zero-vite-plugin/src/index.ts
> [zero] Fix theme token import in source file

- docs/public/static/components-gallery/base-theme.css
This PR is just for small tweaks to the plain CSS theme stylesheet, mostly to correct the CSS vars that were using the old names.
> [docs][base-ui] Fix CSS vars from the plain CSS theme stylesheet

- docs/src/components/home/MuiStatistics.tsx
> [website] Update stats on the testimonials section

- docs/pages/careers.tsx
- docs/src/components/about/OurValues.tsx
- docs/src/components/home/StartToday.tsx
- docs/src/components/typography/SectionHeadline.tsx
- docs/src/layouts/Section.tsx
- docs/src/modules/brandingTheme.ts
This PR adds some light refinements to the Careers page, including layout and copywriting tweaks/updates.
https://deploy-preview-40793--material-ui.netlify.app/careers
> [website] Refine the careers page slightly

- docs/pages/material-ui/api/tab-context.json
- packages/mui-lab/src/TabContext/TabContext.d.ts
- packages/mui-lab/src/TabContext/TabContext.js
> [lab][TabContext] Support number type in `value`

- packages/mui-base/src/unstable_useModal/useModal.ts
- packages/mui-material-next/src/Menu/Menu.tsx
- packages/mui-material-next/src/MenuItem/MenuItem.tsx
- packages/mui-material-next/src/Option/Option.tsx
@DiegoAndai @mnajdova as you recently added mutable refs, see #38762.
> [core] Rely on immutable ref when possible

- docs/src/components/action/Highlighter.tsx
- docs/src/components/footer/EmailSubscribe.tsx
Just some stray polishing after #40751.
- Standardize the border-radius of the footer's input
- Softened the Highlighter a bit to be more cohesive with the light theme
👉  https://deploy-preview-40846--material-ui.netlify.app/
> [website] Small polishing after latest changes to the theme

- docs/src/components/action/Item.tsx
- docs/src/components/home/GetStartedButtons.tsx
- docs/src/components/home/ProductSuite.tsx
- docs/src/components/home/StartToday.tsx
- docs/src/components/productBaseUI/BaseUICustomization.tsx
- docs/src/components/productBaseUI/BaseUISummary.tsx
This PR fixes some stray rough edges across a couple of pages — most of these fixes are mobile-focused and some direct consequences of previous PRs of mine 🙈 heh. Aside from that, it's just minor spacing adjustments.
> [website] Fix a couple of rough edges

- CONTRIBUTING.md
> [docs] Fix URL and typo in CONTRIBUTING.md

- docs/pages/careers.tsx
- docs/pages/careers/support-agent.js
- docs/pages/careers/support-agent.md
Preview: https://deploy-preview-40890--material-ui.netlify.app/careers/support-agent/
> [website] Add Customer Support Agent role to careers page

- docs/src/components/action/InfoCard.tsx
- docs/src/components/home/MuiStatistics.tsx
- docs/src/components/home/Testimonials.tsx
- docs/src/components/productCore/CoreProducts.tsx
Why: https://github.com/mui/material-ui/pull/40752#pullrequestreview-1861101191
> [website] Fix heading structure

- docs/data/base/getting-started/usage/usage.md
Updated the stale link to the React documentation and simplified the sentence.
> [base-ui][docs] Update usage.md

- docs/src/components/home/MaterialDesignComponents.tsx
We've been making some stray polishing to the website and the default theme, and I thought it's a good opportunity to give some love to this section and refine it a bit.
Preview: https://deploy-preview-40953--material-ui.netlify.app/
> [website] Refine the custom components demo in the homepage

- packages/mui-material/package.json
> [material] Make zero-runtime optional peer dep

- packages/mui-material/package.json
- pnpm-lock.yaml
> [material]: Remove zero-runtime from peer dep

- packages/api-docs-builder/utils/parseSlotsAndClasses.ts
We want to ignore some internal classes in Data Grid: https://github.com/mui/mui-x/pull/11924#discussion_r1483029117
Adding `@ignore` tag:
```diff
diff --git a/packages/mui-base/src/Badge/badgeClasses.ts b/packages/mui-base/src/Badge/badgeClasses.ts
index 6ed7dfc7e1..788e30067f 100644
--- a/packages/mui-base/src/Badge/badgeClasses.ts
+++ b/packages/mui-base/src/Badge/badgeClasses.ts
@@ -8,7 +8,10 @@ export interface BadgeClasses {
root: string;
/** Class name applied to the badge `span` element. */
badge: string;
-  /** State class applied to the badge `span` element if `invisible={true}`. */
+  /**
+   * @ignore - do not document.
+   * State class applied to the badge `span` element if `invisible={true}`.
+   */
invisible: string;
} 
```
Results in the following diff:
```diff
diff --git …
```
> [docs-infra] Ignore classes tagged with `@ignore`

- docs/data/system/components/stack/stack.md
address: https://mui-org.slack.com/archives/C041SDSF32L/p1707468515801879
preview: https://deploy-preview-41032--material-ui.netlify.app/system/react-stack/#basics
> [system][Stack] Update import statement for Stack component

- docs/src/modules/components/HighlightedCodeWithTabs.tsx
Potentially the smallest PR I've ever opened 😅 Just fixing the class name of the selected tab on code blocks.
A regression from #40205
- Before: https://deploy-preview-41033--material-ui.netlify.app/experiments/docs/codeblock/
- After: https://deploy-preview-41036--material-ui.netlify.app/experiments/docs/codeblock/
> [docs-infra] Fix selected tab on codeblocks

- docs/package.json
> [core] Increase node memory limit on Netlify build

- packages/zero-runtime/package.json
- packages/zero-runtime/src/processors/keyframes.ts
- packages/zero-runtime/tests/fixtures/styled.input.js
- packages/zero-runtime/tests/fixtures/styled.output.css
- packages/zero-runtime/tests/fixtures/styled.output.js
- packages/zero-runtime/tests/zero-runtime.test.js
- packages/zero-unplugin/package.json
- packages/zero-vite-plugin/package.json
- pnpm-lock.yaml
Also added test for "keyframes"
> [zero] Update to latest version of wyw-in-js

- docs/data/base/components/autocomplete/AutocompleteIntroduction/css/index.js
- docs/data/base/components/autocomplete/AutocompleteIntroduction/css/index.tsx
- docs/data/base/components/autocomplete/AutocompleteIntroduction/system/index.js
- docs/data/base/components/autocomplete/AutocompleteIntroduction/system/index.tsx
- docs/data/base/components/autocomplete/ControlledStates.js
- docs/data/base/components/autocomplete/ControlledStates.tsx
- docs/data/base/components/autocomplete/UseAutocomplete.js
- docs/data/base/components/autocomplete/UseAutocomplete.tsx
- docs/data/base/components/autocomplete/UseAutocompletePopper.js
- docs/data/base/components/autocomplete/UseAutocompletePopper.tsx
- packages/mui-base/src/useAutocomplete/useAutocomplete.js
This is a regression from #40205.
I landed here from https://app.ashbyhq.com/jobs/2067f9c0-6f54-4436-8934-94749f22ee23/candidate-pipeline/active/right-side/candidates/7f6462d5-8e94-415a-b707-b362265456fc/applications/4c155253-e3fd-4b58-a5f2-04a839133cf9/feedback, @DaniGuardiola comment.
Before:
After: https://deploy-preview-41104--material-ui.netlify.app/
> [autocomplete][docs] Fix focus state demo in Base UI

- docs/data/material/getting-started/faq/faq.md
It's a tiny nitpick, but I was roaming through docs and found this text duplicated.
> [material-ui][docs] Remove duplicated text at FAQ page

- docs/pages/blog/base-ui-2024-plans.md
- docs/pages/careers.tsx
Also updated the Base UI blog post to still link to the Careers page so it's a bit open-ended. Or should we remove the link entirely?
> [website] Update the Careers page role

- docs/data/joy/main-features/color-inversion/color-inversion.md
Fix broken link.
https://deploy-preview-41407--material-ui.netlify.app/joy-ui/main-features/color-inversion/#benefits
> [joy-ui][docs] Fix broken link on the Color Inversion page

- packages/pigment-react/README.md
Yet another follow-up to https://github.com/mui/material-ui/pull/41409 — hopefully the last one for today :) Forgot this last import there.
> [pigment-css][docs] Fix import on the README

- docs/pages/blog/2023-material-ui-v6-and-beyond.md
- docs/pages/blog/mui-core-v5.md
A follow-up to https://github.com/mui/material-ui/pull/41297. On this one, I'm removing the last links I could find for the classic projects and swapping them out for the newer public projects. This will allow us to archive the classic projects.
> [docs] Update GitHub project links

- scripts/pigmentcss-render-mui-demos.mjs
> [docs-infra] Fix pigment css apps path in the render mui demos script

- .github/workflows/no-response.yml
Addresses https://github.com/mui/material-ui/pull/41553#issuecomment-2006682485
> [core] Add comment explaining the frequency of no-response action runs

- apps/pigment-next-app/src/app/material-ui/react-modal/page.tsx
- apps/pigment-vite-app/src/pages/material-ui/react-modal.tsx
- packages/mui-material/src/Modal/Modal.js
part of https://github.com/mui/material-ui/issues/41273
preview: https://deploy-preview-41483--material-ui.netlify.app/material-ui/react-modal/
> [material-ui][Modal] Support CSS extraction

- docs/notifications.json
Notification for https://github.com/mui/material-ui/pull/41563
> [docs] Add notification for MUI X v7 blog post

- docs/data/material/experimental-api/css-theme-variables/customization.md
> [docs][material-ui] Fix typo in CSS theme variables customization

- docs/pages/blog/mui-x-v7.md
Sync with the callout in https://github.com/mui/material-ui/pull/41641
> [blog] Update the callout

- pnpm-lock.yaml
Revert the pnpm-lock.yml done in https://github.com/mui/material-ui/pull/41636. Check https://github.com/mui/material-ui/pull/41636#issuecomment-2018053961
> [core] Restore the pnpm-lock.yaml

- apps/pigment-css-next-app/src/app/material-ui/react-chip/page.tsx
- apps/pigment-css-vite-app/src/pages/material-ui/react-chip.tsx
- packages/mui-material/src/Chip/Chip.js
Convert Chip component to support CSS extraction.
https://github.com/mui/material-ui/assets/16889233/3c2c15f8-2787-4514-a0a5-1ba66248860c
> [material-ui][Chip] Convert to support CSS extraction

- CHANGELOG.md
- packages/mui-lab/package.json
- packages/mui-material-nextjs/package.json
> [release] v6.0.0-alpha.0 updates on changelog & versions

- packages/pigment-css-react/README.md
> [pigment-css] Update README.md installation to use the next tag

- CONTRIBUTING.md
> [docs] Fix typo in CONTRIBUTING.md

- packages/pigment-css-vite-plugin/src/vite-plugin.ts
and just send the reload event to refresh the contents on client side.
Fixes #41628
> [pigment-css][vite-plugin] Use constant filename for pigment styles

- packages/mui-system/src/colorManipulator.js
Cherry-pick 4be02a5c678e550d2de187ab7cfbcca4de26c7cd. It fixes the issue of Snackbar background color when used with CSS variables.
> [system] Fix typo to avoid infinite recursion in function call.

- docs/data/material/components/accordion/accordion.md
> [material-ui][docs] Fix typo on the Accordion page

- docs/pages/blog/mui-x-v7.md
> [blog] Fix typo in MUI X v7 announcement post

- packages/pigment-css-react/README.md
Simple fix in a README code block.
> [pigment-css][docs] Fix output on dynamic styles example

- docs/data/material/getting-started/overview/overview.md
"Adoption of Material Design 3 is tentatively planned for Material UI ~v6~ **_v7_**"
> [material-ui][docs] Fix Material 3 message typo

- docs/src/modules/components/AppFrame.js
Cherry pick  #41807
This impact our performances scores, so I bring it to the stable website for SEO
> [docs-infra] Fix drawer performances (#41807)

- CHANGELOG.md
- package.json
- packages/mui-core-downloads-tracker/package.json
- packages/mui-docs/package.json
- packages/mui-icons-material/package.json
- packages/mui-joy/package.json
- packages/mui-lab/package.json
- packages/mui-material/package.json
- packages/mui-styles/package.json
- packages/pigment-css-nextjs-plugin/package.json
- packages/pigment-css-react/package.json
- packages/pigment-css-unplugin/package.json
- packages/pigment-css-vite-plugin/package.json
> v6.0.0-alpha.2

- docs/data/material/components/table/table.md
[MUI X v7 is stable](https://github.com/mui/mui-x/releases/tag/v7.0.0)
> [material-ui][docs] Remove Data Grid v7 beta callout

- docs/data/material/migration/migrating-from-deprecated-apis/migrating-from-deprecated-apis.md
> [material-ui] Fix import statement in migration guide 

- apps/pigment-css-next-app/src/app/material-ui/react-pagination/page.tsx
- apps/pigment-css-vite-app/src/pages/material-ui/react-pagination.tsx
- packages/mui-material/src/PaginationItem/PaginationItem.js
Part of https://github.com/mui/material-ui/issues/41273
@siriwatknp
| Light | Dark |
| ![localhost_3000_material-ui_react-pagination (4)](https://github.com/mui/material-ui/assets/7714133/39a78289-719d-4f61-95ba-bcdc021f6583) | ![localhost_3000_material-ui_react-pagination (3)](https://github.com/mui/material-ui/assets/7714133/945c4bc5-327e-4f9b-91db-e4f07cc4d169) |
> [material-ui][PaginationItem] Convert to support CSS extraction

- docs/src/modules/components/HighlightedCodeWithTabs.tsx
Fix https://github.com/mui/material-ui/pull/41223#issuecomment-2058014782
https://deploy-preview-41917--material-ui.netlify.app/material-ui/getting-started/installation/
> [docs-infra] Fix code block layout shift

- docs/data/material/getting-started/templates/checkout/Checkout.js
- docs/data/material/getting-started/templates/checkout/Checkout.tsx
- docs/data/material/getting-started/templates/landing-page/components/AppAppBar.js
- docs/data/material/getting-started/templates/landing-page/components/AppAppBar.tsx
- docs/data/material/getting-started/templates/landing-page/components/Pricing.js
- docs/data/material/getting-started/templates/landing-page/components/Pricing.tsx
Having links and connections could be a bad user experience for users who would like to copy the templates' code. This PR aims to remove links and interdependencies from templates so they can have their own code boilerplate and a better copy/paste experience.
> [material-ui][docs] Remove links and interdependencies from free templates

- CHANGELOG.md
- package.json
- packages/mui-codemod/package.json
- packages/mui-core-downloads-tracker/package.json
- packages/mui-docs/package.json
- packages/mui-icons-material/package.json
- packages/mui-joy/package.json
- packages/mui-lab/package.json
- packages/mui-material/package.json
- packages/mui-styles/package.json
- packages/mui-system/package.json
> [release] v6.0.0-alpha.4

- docs/data/material/components/about-the-lab/about-the-lab.md
> [material-ui][docs] Fix minor spelling error in the "About the lab" page

- docs/data/system/getting-started/the-sx-prop/the-sx-prop.md
> [system][docs] Update typo on the sx prop page

- CHANGELOG.md
- package.json
- packages/mui-base/package.json
- packages/mui-codemod/package.json
- packages/mui-core-downloads-tracker/package.json
- packages/mui-docs/package.json
- packages/mui-icons-material/package.json
- packages/mui-joy/package.json
- packages/mui-lab/package.json
- packages/mui-material/package.json
- packages/mui-private-theming/package.json
- packages/mui-styled-engine-sc/package.json
- packages/mui-styled-engine/package.json
- packages/mui-styles/package.json
- packages/mui-system/package.json
- packages/mui-utils/package.json
> v6.0.0-alpha.5

- docs/src/components/home/ValueProposition.tsx
- docs/src/components/productX/XPlans.tsx
- docs/src/modules/components/MaterialStartingLinksCollection.js
- docs/src/modules/components/MaterialUIComponents/MaterialUtilComponents.js
- docs/src/modules/components/MaterialUIDesignResources.js
- packages/mui-docs/src/InfoCard/InfoCard.tsx
Just a small quality-of-life design refinement to this component — @noraleonte very much inspired by what we were playing with on Figma! Not quite that yet, but going towards a simplification direction 😃 
https://deploy-preview-42116--material-ui.netlify.app/
> [website] Refine the InfoCard design

- CHANGELOG.md
- package.json
- packages/mui-base/package.json
- packages/mui-codemod/package.json
- packages/mui-core-downloads-tracker/package.json
- packages/mui-docs/package.json
- packages/mui-icons-material/package.json
- packages/mui-joy/package.json
- packages/mui-lab/package.json
- packages/mui-material/package.json
- packages/mui-styles/package.json
> v6.0.0-alpha.6

- packages/api-docs-builder/utils/findComponents.ts
> [docs-infra] Make  select components with two capital letters

- CHANGELOG.md
- package.json
- packages-internal/docs-utils/package.json
- packages-internal/scripts/package.json
- packages/markdown/package.json
- packages/mui-babel-macros/package.json
- packages/mui-base/package.json
- packages/mui-codemod/package.json
- packages/mui-core-downloads-tracker/package.json
- packages/mui-docs/package.json
- packages/mui-envinfo/package.json
- packages/mui-icons-material/package.json
- packages/mui-joy/package.json
- packages/mui-lab/package.json
- packages/mui-material-nextjs/package.json
- packages/mui-material/package.json
- packages/mui-private-theming/package.json
- packages/mui-styled-engine-sc/package.json
- packages/mui-styled-engine/package.json
- packages/mui-styles/package.json
- packages/mui-system/package.json
- packages/mui-utils/package.json
> v6.0.0-alpha.7

- package.json
- pnpm-lock.yaml
See https://github.com/mui/mui-x/pull/13160
> [code-infra] Remove raw-loader

- docs/pages/blog/introducing-pigment-css.md
Follow-up to Diego's comment in https://github.com/mui/material-ui/pull/42311#issuecomment-2127867990.
> [blog] Add the "Product" tag to the Pigment CSS post

- scripts/releaseChangelog.mjs
message if the actual author of the commit is `github-actions` bot
<details>
<summary>Before</summary>
_May 29, 2024_
A big thanks to the 4 contributors who made this release possible. Here are some highlights ✨:
TODO INSERT HIGHLIGHTS
- &#8203;[material-ui][AlertTitle] Enable extending Typography props (@lucasgmelo) (#42334) @github-actions[bot]
- &#8203;[blog] Add the "Product" tag to the Pigment CSS post (@danilo-leal) (#42366) @github-actions[bot]
- &#8203;[blog] Update blog post OG image (@danilo-leal) (#42306) @github-actions[bot]
- &#8203;[blog] Update Pigment CSS post (@danilo-leal) (#42267) @github-actions[bot]
- &#8203;[core] Fix React 18.3 warnings about spreading keys in the Material UI `Autocomplete` component (#42099) (#42241) @DiegoAndai
- &#8203;[core] Fix a few more key …
> [docs-infra] Try to parse author login from commit

- CHANGELOG.md
- package.json
- packages/mui-base/package.json
- packages/mui-codemod/package.json
- packages/mui-core-downloads-tracker/package.json
- packages/mui-docs/package.json
- packages/mui-icons-material/package.json
- packages/mui-joy/package.json
- packages/mui-lab/package.json
- packages/mui-material/package.json
- packages/mui-private-theming/package.json
- packages/mui-styled-engine-sc/package.json
- packages/mui-styled-engine/package.json
- packages/mui-styles/package.json
- packages/mui-system/package.json
- packages/mui-utils/package.json
> [release] v6.0.0-alpha.9

- docs/data/material/design-resources/material-ui-for-figma/material-ui-for-figma.md
As the title says — to facilitate access to this information, as per the last Design Kits meeting.
> [material-ui][docs] Add changelog section to the design kits page

- netlify/edge-functions/og-image.tsx
Mostly just tweaking (increasing) the font-size and typography-related properties and updating the logo color.
> [docs-infra] Update the OG card image design

- docs/data/material/customization/theming/theming.md
From slack message.
Not sure which sentence is the one to remove
> [docs] Fix duplicated sentence

- package.json
Fix https://github.com/mui/material-ui/pull/41177#issuecomment-2155982546
> [test] Restore pnpm tc command

- packages-internal/test-utils/src/mochaHooks.test.js
- test/regressions/TestViewer.js
part of https://github.com/mui/material-ui/issues/42564
> [test] Fix issues reported by react-compiler in test packages

- packages/mui-system/src/ThemeProvider/ThemeProvider.test.js
part of https://github.com/mui/material-ui/issues/42564
> [mui-system] Fix issues reported by react compiler in `mui-system` package

- package.json
- packages-internal/test-utils/package.json
- packages/mui-styles/src/withStyles/withStyles.test.js
- pnpm-lock.yaml
The parameters for the test script on CI were specified incorrectly. Because of that, majority of tests were not run.
A regression from https://github.com/mui/material-ui/pull/42519
> [test] Fix tests on CI

- docs/src/components/about/OurValues.tsx
- docs/src/components/careers/PerksBenefits.tsx
- docs/src/components/footer/EmailSubscribe.tsx
- docs/src/components/home/DiamondSponsors.tsx
- docs/src/components/home/GoldSponsors.tsx
- docs/src/components/home/SponsorCard.tsx
- docs/src/modules/components/DiamondSponsors.js
- packages/mui-docs/src/branding/brandingTheme.ts
Just the usual housekeeping stuff. Commits are descriptive of the changes.
The biggest highlight here, design-wise, is the simplification of the sponsor's block on the table of contents.
- https://deploy-preview-42646--material-ui.netlify.app/material-ui/getting-started/
- https://deploy-preview-42646--material-ui.netlify.app/careers/
> [docs-infra] Add stray design polish

- CHANGELOG.md
- packages-internal/scripts/package.json
- packages-internal/test-utils/package.json
- packages/markdown/package.json
- packages/mui-babel-macros/package.json
- packages/mui-base/package.json
- packages/mui-codemod/package.json
- packages/mui-core-downloads-tracker/package.json
- packages/mui-docs/package.json
- packages/mui-icons-material/package.json
- packages/mui-joy/package.json
- packages/mui-lab/package.json
- packages/mui-material/package.json
- packages/mui-private-theming/package.json
- packages/mui-styled-engine-sc/package.json
- packages/mui-styled-engine/package.json
- packages/mui-styles/package.json
- packages/mui-system/package.json
- packages/mui-utils/package.json
> [release] v6.0.0-alpha.12

- package.json
> [core] Update root's package.json

- CONTRIBUTING.md
> [docs] Fix link in CONTRIBUTING.md

- CHANGELOG.md
- package.json
- packages-internal/test-utils/package.json
- packages/mui-base/package.json
- packages/mui-core-downloads-tracker/package.json
- packages/mui-docs/package.json
- packages/mui-icons-material/package.json
- packages/mui-joy/package.json
- packages/mui-lab/package.json
- packages/mui-material-nextjs/package.json
- packages/mui-material/package.json
- packages/mui-private-theming/package.json
- packages/mui-styled-engine-sc/package.json
- packages/mui-styled-engine/package.json
- packages/mui-styles/package.json
- packages/mui-system/package.json
- packages/mui-utils/package.json
> v6.0.0-alpha.13

- docs/src/modules/components/AppLayoutDocsFooter.js
- docs/src/modules/components/ComponentPageTabs.js
- docs/src/modules/components/HighlightedCodeWithTabs.tsx
- packages/mui-docs/src/MarkdownElement/MarkdownElement.tsx
Pretty much what each commit says—they're very descriptive. Tiny stuff!
> [docs-infra] Add batch of design polish

- docs/data/material/components/use-media-query/UseWidth.js
- docs/data/material/components/use-media-query/UseWidth.tsx
part of : https://github.com/mui/material-ui/issues/42564
> [material-ui][docs] Fix issues reported by react-compiler in docs folder

- CHANGELOG.md
- package.json
- packages/mui-base/package.json
- packages/mui-codemod/package.json
- packages/mui-core-downloads-tracker/package.json
- packages/mui-docs/package.json
- packages/mui-icons-material/package.json
- packages/mui-lab/package.json
- packages/mui-material-nextjs/package.json
- packages/mui-material-pigment-css/package.json
- packages/mui-material/package.json
- packages/mui-private-theming/package.json
- packages/mui-styled-engine-sc/package.json
- packages/mui-styled-engine/package.json
- packages/mui-styles/package.json
- packages/mui-system/package.json
- packages/mui-utils/package.json
> v6.0.0-beta.1

- packages/mui-material/package.json
- pnpm-lock.yaml
> [material] Add missing dependency

- CHANGELOG.md
- package.json
- packages/mui-core-downloads-tracker/package.json
- packages/mui-docs/package.json
- packages/mui-icons-material/package.json
- packages/mui-material/package.json
- packages/mui-styles/package.json
> [release] v5.16.3

- docs/data/material/getting-started/templates/blog/MainFeaturedPost.js
- package.json
- pnpm-lock.yaml
Fixes #42955 
👉 https://deploy-preview-42956--material-ui.netlify.app/material-ui/getting-started/templates/blog/
> [material-ui][docs] Fix broken image links in blog template

- packages/mui-material-nextjs/package.json
> [material-ui] Add @emotion/react peer dependency to @mui/material-nextjs

- CHANGELOG.md
- package.json
- packages/mui-core-downloads-tracker/package.json
- packages/mui-docs/package.json
- packages/mui-icons-material/package.json
- packages/mui-material-nextjs/package.json
- packages/mui-material/package.json
- packages/mui-private-theming/package.json
- packages/mui-styled-engine/package.json
- packages/mui-styles/package.json
- packages/mui-system/package.json
- packages/mui-utils/package.json
Release v5.16.4 with patch fix https://github.com/mui/material-ui/pull/42967
> [release] v5.16.4

- docs/data/material/migration/migrating-to-v6/migrating-to-v6.md
- docs/data/system/migration/migrating-to-v6/migrating-to-v6.md
> [docs] Fix migration typo

- packages/mui-utils/package.json
- pnpm-lock.yaml
Fixes https://github.com/mui/material-ui/issues/43020.
> [utils] Add dependency to @mui/types

- CHANGELOG.md
- package.json
- packages-internal/scripts/package.json
- packages-internal/test-utils/package.json
- packages/mui-babel-macros/package.json
- packages/mui-base/package.json
- packages/mui-codemod/package.json
- packages/mui-core-downloads-tracker/package.json
- packages/mui-docs/package.json
- packages/mui-envinfo/package.json
- packages/mui-icons-material/package.json
- packages/mui-lab/package.json
- packages/mui-material-nextjs/package.json
- packages/mui-material-pigment-css/package.json
- packages/mui-material/package.json
- packages/mui-private-theming/package.json
- packages/mui-styled-engine-sc/package.json
- packages/mui-styled-engine/package.json
- packages/mui-styles/package.json
- packages/mui-system/package.json
- packages/mui-utils/package.json
> v6.0.0-beta.3

- packages/mui-utils/src/useControlled/useControlled.js
- packages/mui-utils/src/useForkRef/useForkRef.ts
- packages/mui-utils/src/useId/useId.ts
- packages/mui-utils/src/useOnMount/useOnMount.ts
Part of https://github.com/mui/material-ui/issues/42564
> [utils] Fix issues reported by the React Compiler

- CHANGELOG.md
- package.json
- packages/mui-codemod/package.json
- packages/mui-core-downloads-tracker/package.json
- packages/mui-docs/package.json
- packages/mui-icons-material/package.json
- packages/mui-lab/package.json
- packages/mui-material-nextjs/package.json
- packages/mui-material-pigment-css/package.json
- packages/mui-material/package.json
- packages/mui-private-theming/package.json
- packages/mui-styled-engine-sc/package.json
- packages/mui-styled-engine/package.json
- packages/mui-styles/package.json
- packages/mui-system/package.json
- packages/mui-utils/package.json
> [release] v6.0.0-beta.4

- CHANGELOG.md
- package.json
- packages/mui-core-downloads-tracker/package.json
- packages/mui-docs/package.json
- packages/mui-icons-material/package.json
- packages/mui-material-nextjs/package.json
- packages/mui-material/package.json
- packages/mui-private-theming/package.json
- packages/mui-styled-engine/package.json
- packages/mui-styles/package.json
- packages/mui-system/package.json
- packages/mui-utils/package.json
> [release] v5.16.6

- docs/data/material/components/about-the-lab/about-the-lab.md
- docs/data/material/getting-started/supported-platforms/supported-platforms.md
- docs/data/material/guides/typescript/typescript.md
- docs/data/material/migration/migrating-to-v6/migrating-to-v6.md
Closes: https://github.com/mui/material-ui/issues/40996
> [typescript] Update the minimum supported version

- apps/pigment-css-next-app/package.json
- apps/pigment-css-vite-app/package.json
- package.json
- packages/mui-material-pigment-css/package.json
- pnpm-lock.yaml
> Bump Pigment CSS to 0.0.20

- CHANGELOG.md
- package.json
- packages-internal/docs-utils/package.json
- packages-internal/scripts/package.json
- packages-internal/test-utils/package.json
- packages/markdown/package.json
- packages/mui-babel-macros/package.json
- packages/mui-base/package.json
- packages/mui-codemod/package.json
- packages/mui-core-downloads-tracker/package.json
- packages/mui-docs/package.json
- packages/mui-envinfo/package.json
- packages/mui-icons-material/package.json
- packages/mui-lab/package.json
- packages/mui-material-pigment-css/package.json
- packages/mui-material/package.json
- packages/mui-private-theming/package.json
- packages/mui-styled-engine-sc/package.json
- packages/mui-styled-engine/package.json
- packages/mui-styles/package.json
- packages/mui-system/package.json
- packages/mui-utils/package.json
> [release] v6.0.0-beta.5

- CHANGELOG.md
- package.json
- packages/mui-core-downloads-tracker/package.json
- packages/mui-docs/package.json
- packages/mui-icons-material/package.json
- packages/mui-material/package.json
- packages/mui-styles/package.json
- packages/mui-system/package.json
> [release] v5.16.7

- docs/notifications.json
- docs/pages/blog/mui-x-sep-2024-price-update.js
- docs/pages/blog/mui-x-sep-2024-price-update.md
Cherry-pick of #43061
Preview: https://deploy-preview-43272--material-ui-apps.netlify.app/blog/mui-x-sep-2024-price-update/
> [blog] Announcing pricing changes Sep 2024

- packages/mui-docs/src/CodeCopy/CodeCopy.tsx
See https://github.com/mui/mui-x/pull/14220 for why.
> [docs-infra] Fix copy shortcut

- apps/pigment-css-next-app/package.json
- apps/pigment-css-vite-app/package.json
- package.json
- packages/mui-material-pigment-css/package.json
- pnpm-lock.yaml
> [dependencies] Update Pigment CSS to 0.0.21

- CHANGELOG.md
- package.json
- packages-internal/docs-utils/package.json
- packages-internal/test-utils/package.json
- packages/mui-codemod/package.json
- packages/mui-core-downloads-tracker/package.json
- packages/mui-docs/package.json
- packages/mui-icons-material/package.json
- packages/mui-material-nextjs/package.json
- packages/mui-material-pigment-css/package.json
- packages/mui-material/package.json
- packages/mui-private-theming/package.json
- packages/mui-styled-engine-sc/package.json
- packages/mui-styled-engine/package.json
- packages/mui-styles/package.json
- packages/mui-system/package.json
- packages/mui-utils/package.json
> [release] v6.0.1

- docs/pages/blog/material-ui-v6-is-out.md
> [blog] Fix typo in Material UI v6 blog post

- .github/workflows/closed-issue-message.yml
SRY!!! I did change the filename and forgot to update it here! 🙇🏼
> [infra] Fixed workflow file path

- packages/mui-codemod/src/v5.0.0/joy-text-field-to-input.test/actual.js
- packages/mui-codemod/src/v5.0.0/joy-text-field-to-input.test/expected.js
Try to fix https://github.com/mui/material-ui/security/code-scanning/tools/CodeQL/status/configurations/actions-FZTWS5DIOVRC653POJVWM3DPO5ZS6Y3PMRSXC3BOPFWWY/f5e4442d08b839b91c92cbad466bee9b2e7ba1488b7e53f0b683c47de1824766
> [core] Fix CodeQL scan

- .github/workflows/ci.yml
- .github/workflows/publish-canaries.yml
follow up of #43591
https://github.com/mui/material-ui/pull/43591#issuecomment-2326792094
> [code-infra] Update runners from node 18 to 20 for GHA

- pnpm-lock.yaml
Just to see if it has the same issues as https://github.com/mui/mui-x/pull/11894
It doesn't, but we may as well merge it now
> [code-infra] Recreate lockfile

- .eslintignore
I guess we don't need this anymore.
> [core] Remove /.yarn

- packages-internal/scripts/typescript-to-proptypes/src/getPropTypesFromFile.ts
- pnpm-lock.yaml
Fix proptype generation of https://github.com/mui/toolpad/pull/4114/files#diff-95f01a4319537ed50cb9f5367a0ff569befefd073590a4079bf11ea5e2f7c86fR47-R62
> [code-infra] Add new instanceof proptypes for toolpad

- docs/src/components/pricing/PricingTable.tsx
Reflect https://github.com/mui/mui-x/pull/14124. 
Preview: https://deploy-preview-43831--material-ui.netlify.app/pricing/
> [website] Add 'Row spanning'

- packages/mui-material/src/Button/Button.js
> [Button] Fix regression for color `inherit`

- docs/pages/careers.tsx
- docs/pages/careers/technical-recruiter.js
Based on https://groups.google.com/a/mui.com/g/people/c/0DU4uCzlKuU
> [website] Improve Next roles section

- examples/material-ui-express-ssr/README.md
- examples/material-ui-gatsby/README.md
- examples/material-ui-nextjs-pages-router-ts/README.md
- examples/material-ui-nextjs-pages-router/README.md
- examples/material-ui-nextjs-ts-v4-v5-migration/README.md
- examples/material-ui-nextjs-ts/README.md
- examples/material-ui-nextjs/README.md
- examples/material-ui-preact/README.md
- examples/material-ui-remix-ts/README.md
- examples/material-ui-via-cdn/README.md
I tried to run those commands to test something on a new project but it didn't work.
> [examples] Fix v5 clone example instructions

- docs/data/material/migration/upgrade-to-v6/migrating-to-pigment-css.md
> [docs][material-ui] add theme setting for pigment-css migration

- packages/mui-utils/src/useLocalStorageState/useLocalStorageState.ts
Small typo in useLocalStorageState file
> [core] Fix typo in useLocalStorageState

- docs/pages/careers.tsx
Preview: https://deploy-preview-44032--material-ui.netlify.app/careers/
> [docs] Update docs-infra role

- packages/mui-styled-engine-sc/package.json
- pnpm-lock.yaml
> [core] Remove `@mui/styled-engine-sc` dev dependency from `@mui/styled-engine-sc`

- docs/data/material/components/grid2/grid2.md
Fixes a small typo in the docs
> [docs] Fix small typo on Grid2 page

- pnpm-lock.yaml
See https://github.com/mui/material-ui/security/dependabot/183
> Fix fast-xml-parser vulnerability

- docs/src/components/productX/XGridFullDemo.tsx
> [website] Fix density picker in the X product page

- package.json
- pnpm-lock.yaml
- test/bundling/fixtures/create-react-app/package.json
- test/bundling/fixtures/esbuild/package.json
- test/bundling/fixtures/snowpack/package.json
- test/bundling/fixtures/vite/package.json
Fix another batch of https://github.com/mui/material-ui/security/dependabot
`ip`, `ws`, `path-to-regexp`
> [code-infra] Fix dependabot vulnerabilities

- docs/data/material/components/text-fields/InputAdornments.js
- docs/data/material/components/text-fields/InputAdornments.tsx
Closes #44109 
Demo:
https://github.com/user-attachments/assets/8a6751e0-5f16-4d45-a921-99dd0b36a9a1
Tagging @mnajdova for review
> [docs][TextField] Dynamically modify the eye password button aria-label

- packages/mui-system/src/InitColorSchemeScript/InitColorSchemeScript.test.js
Noticed this in #44139. We try as much as possible to test public APIs, here seems to be an opportunity to do such.
> [test] Distinguish private with public tests API

- packages/mui-material/src/AvatarGroup/AvatarGroup.js
> [AvatarGroup] Fix spacing prop

- scripts/releaseChangelog.mjs
> [infra] Fix @renovate[bot] appearing in changelog

- docs/data/material/getting-started/templates/sign-in-side/SignInCard.js
- docs/data/material/getting-started/templates/sign-in-side/SignInCard.tsx
- docs/data/material/getting-started/templates/sign-in/SignIn.js
- docs/data/material/getting-started/templates/sign-in/SignIn.tsx
I don't know what happened here, but this is dead code.
> [docs][material-ui] Remove noise in template

- docs/src/components/home/MuiStatistics.tsx
Last update was a while ago: #40769.
> [website] Update the stats

- CHANGELOG.md
- package.json
- packages-internal/scripts/package.json
- packages-internal/test-utils/package.json
- packages/markdown/package.json
- packages/mui-codemod/package.json
- packages/mui-core-downloads-tracker/package.json
- packages/mui-docs/package.json
- packages/mui-icons-material/package.json
- packages/mui-lab/package.json
- packages/mui-material-nextjs/package.json
- packages/mui-material-pigment-css/package.json
- packages/mui-material/package.json
- packages/mui-private-theming/package.json
- packages/mui-styled-engine-sc/package.json
- packages/mui-styled-engine/package.json
- packages/mui-styles/package.json
- packages/mui-system/package.json
- packages/mui-utils/package.json
- pnpm-lock.yaml
Release v6.1.7
Fix some minor format errors in CHANGELOG for versions `6.1.5` and `6.1.6`
> [release] v6.1.7

- docs/pages/blog/mui-x-v8-alpha-zero.md
https://github.com/mui/material-ui/pull/44377#discussion_r1842592272
> [blog] Fix reference to subdomain on MUI X v8 alpha zero post

- packages/mui-material/src/useMediaQuery/index.d.ts
From https://github.com/mui/material-ui/pull/44339#issuecomment-2482471874
> [material-ui] Add generic back to `useMediaQuery` to prevent a breaking change

- CHANGELOG.md
> [core] Remove TODO line in the changelog

- package.json
- pnpm-lock.yaml
> [core] Bump pnpm to 9.14.2 in v5.x branch

- packages/mui-docs/package.json
- packages/mui-icons-material/package.json
- packages/mui-lab/package.json
- packages/mui-material-nextjs/package.json
- packages/mui-material/package.json
- packages/mui-private-theming/package.json
- packages/mui-styled-engine/package.json
- packages/mui-styles/package.json
- packages/mui-system/package.json
- packages/mui-types/package.json
- packages/mui-utils/package.json
Cherry-pick https://github.com/mui/material-ui/pull/43216
Part of https://github.com/mui/material-ui/issues/44413
> [core] Cherry pick React 19 added to peer dependencies to v5.x

- packages/mui-material/src/styles/createTheme.test.js
- packages/mui-material/src/styles/createThemeWithVars.js
> [material-ui] Skip `tonalOffset` from setting color channel

- docs/data/material/migration/migrating-from-deprecated-apis/migrating-from-deprecated-apis.md
preview: https://deploy-preview-44638--material-ui.netlify.app/material-ui/migration/migrating-from-deprecated-apis
> [material-ui][ListItem] Add missing diffs in migration guide

- packages/mui-material/src/Box/Box.spec.tsx
Follow up on https://github.com/mui/material-ui/pull/44643#discussion_r1869317844
> [material-ui][Box] Fix `component` prop test

- package.json
- pnpm-lock.yaml
Cherry-pick https://github.com/mui/material-ui/pull/44614
>  Bump pnpm to 9.14.4 in v5

- docs/package.json
Equivalent of https://github.com/mui/mui-x/pull/15959
I haven't observed any issue here but the nextjs feature seems problematic so we might as well remove it before we find an issue.
> [docs-infra] Remove Next.js production profiler

- CHANGELOG.md
- package.json
- packages-internal/babel-plugin-resolve-imports/package.json
- packages-internal/scripts/package.json
- packages-internal/test-utils/package.json
- packages/markdown/package.json
- packages/mui-base/package.json
- packages/mui-codemod/package.json
- packages/mui-core-downloads-tracker/package.json
- packages/mui-docs/package.json
- packages/mui-icons-material/package.json
- packages/mui-lab/package.json
- packages/mui-material-nextjs/package.json
- packages/mui-material-pigment-css/package.json
- packages/mui-material/package.json
- packages/mui-private-theming/package.json
- packages/mui-styled-engine-sc/package.json
- packages/mui-styled-engine/package.json
- packages/mui-styles/package.json
- packages/mui-system/package.json
- packages/mui-utils/package.json
- pnpm-lock.yaml
> [release] v6.3.0

- docs/data/material/components/grid2/InteractiveGrid.js
- docs/data/material/components/grid2/InteractiveGrid.tsx
- docs/data/material/components/grid2/grid2.md
> [docs] Add interactive demo for Grid v2

- CHANGELOG.md
- package.json
- packages/mui-core-downloads-tracker/package.json
- packages/mui-docs/package.json
- packages/mui-icons-material/package.json
- packages/mui-material-nextjs/package.json
- packages/mui-material/package.json
- packages/mui-private-theming/package.json
- packages/mui-styled-engine/package.json
- packages/mui-styles/package.json
- packages/mui-system/package.json
- packages/mui-utils/package.json
> [release] v5.16.13

- package.json
Cherry-pick https://github.com/mui/material-ui/pull/44891
> Bump pnpm to 9.15.2 in v5.x

- CHANGELOG.md
- package.json
- packages/mui-core-downloads-tracker/package.json
- packages/mui-docs/package.json
- packages/mui-icons-material/package.json
- packages/mui-material-nextjs/package.json
- packages/mui-material/package.json
- packages/mui-private-theming/package.json
- packages/mui-styled-engine/package.json
- packages/mui-styles/package.json
- packages/mui-system/package.json
- packages/mui-utils/package.json
> [release] v5.16.14

- packages/mui-material/src/Checkbox/Checkbox.js
- packages/mui-material/src/Dialog/Dialog.js
- packages/mui-material/src/Fab/Fab.js
- packages/mui-material/src/Pagination/Pagination.js
- packages/mui-material/src/PaginationItem/PaginationItem.js
> [material-ui] Remove unnecessary blank lines

- docs/data/about/teamMembers.json
Update the MUI's about page to reflect the latest changes in staffing.
Preview: https://deploy-preview-45025--material-ui.netlify.app/
> [website] Update MUI about page

- CHANGELOG.md
- package.json
- packages/mui-codemod/package.json
- packages/mui-core-downloads-tracker/package.json
- packages/mui-docs/package.json
- packages/mui-icons-material/package.json
- packages/mui-lab/package.json
- packages/mui-material-nextjs/package.json
- packages/mui-material-pigment-css/package.json
- packages/mui-material/package.json
- packages/mui-private-theming/package.json
- packages/mui-styled-engine-sc/package.json
- packages/mui-styled-engine/package.json
- packages/mui-styles/package.json
- packages/mui-system/package.json
- packages/mui-utils/package.json
Update changelog and package versions for v6.4.2 release.
> [release] v6.4.2

- packages/mui-material/src/Radio/Radio.js
This PR removes unnessary empty line, this got missed in https://github.com/mui/material-ui/pull/44980
> [material-ui][Radio] Remove empty line

- docs/src/components/productBaseUI/BaseUIThemesDemo.tsx
- docs/src/components/productBaseUI/MuiBaseDeprecation.tsx
- docs/src/layouts/AppFooter.tsx
- docs/src/route.ts
Address: https://github.com/mui/material-ui/pull/45030#discussion_r1934378596.
And a side fix while I was at it.
> [core] Fix double redirection to Base UI

- .circleci/config.yml
Cherry-pick #45185 to `v6.x` branch
> [core] Fix corepack and pnpm installation in CircleCI (#45185)

- CHANGELOG.md
- package.json
- packages/mui-codemod/package.json
- packages/mui-core-downloads-tracker/package.json
- packages/mui-docs/package.json
- packages/mui-icons-material/package.json
- packages/mui-lab/package.json
- packages/mui-material-nextjs/package.json
- packages/mui-material-pigment-css/package.json
- packages/mui-material/package.json
- packages/mui-private-theming/package.json
- packages/mui-styled-engine-sc/package.json
- packages/mui-styled-engine/package.json
- packages/mui-styles/package.json
- packages/mui-system/package.json
- packages/mui-utils/package.json
Update the Changelog and bump versions for the `v6.4.3` release.
> [release] v6.4.3

- docs/data/material/components/dialogs/FormDialog.js
- docs/data/material/components/dialogs/FormDialog.tsx
- docs/data/material/getting-started/templates/sign-in-side/components/ForgotPassword.js
- docs/data/material/getting-started/templates/sign-in-side/components/ForgotPassword.tsx
- docs/data/material/getting-started/templates/sign-in/components/ForgotPassword.js
- docs/data/material/getting-started/templates/sign-in/components/ForgotPassword.tsx
cherry pick https://github.com/mui/material-ui/pull/45195 to `v6.x` branch
> [docs][Dialog] Removes deprecated PaperProps from docs 

- docs/data/material/components/app-bar/app-bar.md
- docs/data/material/components/breadcrumbs/breadcrumbs.md
- docs/data/material/components/container/container.md
- docs/data/material/components/dialogs/dialogs.md
- docs/data/material/components/drawers/drawers.md
- docs/data/material/getting-started/templates/templates.md
Partial revert of: https://github.com/mui/material-ui/pull/43796
> [docs] Mention Toolpad as experimental

- pnpm-lock.yaml
Addresses https://github.com/mui/material-ui/security/dependabot/215
> [code-infra] Update `elliptic`

- docs/data/material/migration/migrating-from-deprecated-apis/migrating-from-deprecated-apis.md
- docs/pages/material-ui/api/menu.json
- docs/pages/material-ui/api/popover.json
- docs/translations/api-docs/popover/popover.json
- packages/mui-codemod/src/deprecations/all/deprecations-all.js
- packages/mui-codemod/src/deprecations/popover-props/index.js
- packages/mui-codemod/src/deprecations/popover-props/popover-props.js
- packages/mui-codemod/src/deprecations/popover-props/popover-props.test.js
- packages/mui-codemod/src/deprecations/popover-props/test-cases/actual.js
- packages/mui-codemod/src/deprecations/popover-props/test-cases/expected.js
- packages/mui-codemod/src/deprecations/popover-props/test-cases/theme.actual.js
- packages/mui-codemod/src/deprecations/popover-props/test-cases/theme.expected.js
- packages/mui-material/src/Menu/Menu.js
- packages/mui-material/src/Modal/Modal.js
- packages/mui-material/src/Modal/Modal.test.js
- packages/mui-material/src/Popover/Popover.d.ts
- packages/mui-material/src/Popover/Popover.js
- packages/mui-material/src/Popover/Popover.test.js
> [material-ui][Popover] Deprecate *Props and complete `slots`, `slotProps`

- docs/pages/material-ui/api/radio.json
- docs/translations/api-docs/radio/radio.json
- packages/mui-material/src/Radio/Radio.d.ts
- packages/mui-material/src/Radio/Radio.js
- packages/mui-material/src/Radio/Radio.spec.tsx
- packages/mui-material/src/Radio/Radio.test.js
> [material-ui][Radio] Add slots and slotProps

- docs/public/static/error-codes.json
- packages/mui-material/src/styles/createTheme.test.js
- packages/mui-material/src/styles/createThemeNoVars.js
> [material-ui] Allow nested theme creation with `vars`

- docs/data/material/migration/migrating-from-deprecated-apis/migrating-from-deprecated-apis.md
- docs/pages/material-ui/api/input-base.json
- docs/translations/api-docs/input-base/input-base.json
- packages/mui-codemod/README.md
- packages/mui-codemod/src/deprecations/all/deprecations-all.js
- packages/mui-codemod/src/deprecations/all/postcss.config.js
- packages/mui-codemod/src/deprecations/input-base-classes/index.js
- packages/mui-codemod/src/deprecations/input-base-classes/input-base-classes.js
- packages/mui-codemod/src/deprecations/input-base-classes/input-base-classes.test.js
- packages/mui-codemod/src/deprecations/input-base-classes/postcss-plugin.js
- packages/mui-codemod/src/deprecations/input-base-classes/postcss.config.js
- packages/mui-codemod/src/deprecations/input-base-classes/test-cases/actual.css
- packages/mui-codemod/src/deprecations/input-base-classes/test-cases/actual.js
- packages/mui-codemod/src/deprecations/input-base-classes/test-cases/expected.css
- packages/mui-codemod/src/deprecations/input-base-classes/test-cases/expected.js
- packages/mui-material/src/InputBase/inputBaseClasses.ts
> [material-ui][InputBase] Deprecate composed classes

- docs/data/material/migration/migrating-from-deprecated-apis/migrating-from-deprecated-apis.md
- packages/mui-codemod/README.md
address: https://github.com/mui/material-ui/pull/45388#discussion_r1967849425 also fixed few typos in ReadMe.md files
> [material-ui][Slider] Fix css class selector in migration guide

- CHANGELOG.md
- package.json
- packages/mui-codemod/package.json
- packages/mui-core-downloads-tracker/package.json
- packages/mui-docs/package.json
- packages/mui-icons-material/package.json
- packages/mui-lab/package.json
- packages/mui-material-pigment-css/package.json
- packages/mui-material/package.json
- packages/mui-styles/package.json
- packages/mui-system/package.json
> [release] v7.0.0-beta.0

- CHANGELOG.md
- package.json
- packages/mui-codemod/package.json
- packages/mui-core-downloads-tracker/package.json
- packages/mui-docs/package.json
- packages/mui-icons-material/package.json
- packages/mui-lab/package.json
- packages/mui-material-pigment-css/package.json
- packages/mui-material/package.json
- packages/mui-private-theming/package.json
- packages/mui-styled-engine-sc/package.json
- packages/mui-styled-engine/package.json
- packages/mui-styles/package.json
- packages/mui-system/package.json
> [release] v7.0.0 beta.1

- examples/material-ui-cra-styled-components-ts/README.md
- examples/material-ui-cra-styled-components/README.md
- examples/material-ui-cra-tailwind-ts/README.md
- examples/material-ui-cra-ts/README.md
- examples/material-ui-cra/README.md
- examples/material-ui-express-ssr/README.md
- examples/material-ui-gatsby/README.md
- examples/material-ui-nextjs-pages-router-ts/README.md
- examples/material-ui-nextjs-pages-router/README.md
- examples/material-ui-nextjs-ts/README.md
- examples/material-ui-nextjs/README.md
- examples/material-ui-pigment-css-nextjs-ts/README.md
- examples/material-ui-pigment-css-vite-ts/README.md
- examples/material-ui-preact/README.md
- examples/material-ui-remix-ts/README.md
- examples/material-ui-via-cdn/README.md
- examples/material-ui-vite-ts/README.md
- examples/material-ui-vite/README.md
> [examples] Fix the invalid argument to extract examples

- packages/mui-material/src/Autocomplete/Autocomplete.test.js
- packages/mui-material/src/Popover/Popover.test.js
- packages/mui-material/src/Snackbar/Snackbar.js
- packages/mui-material/src/Snackbar/Snackbar.test.js
Cherry-pick #45161
Closes https://github.com/mui/material-ui/issues/45477
> [test] Fix React 18 tests (#45161)

- docs/data/material/migration/migrating-from-deprecated-apis/migrating-from-deprecated-apis.md
> [docs][Backdrop] Fix component name in migration guide

- docs/src/components/pricing/PricingFAQ.tsx
> [website] Update pricing FAQ

- packages/mui-material/src/styles/ThemeProvider.test.tsx
- packages/mui-material/src/styles/ThemeProvider.tsx
Cherry-pick of https://github.com/mui/material-ui/pull/45545
> [system] Prevent nested non-vars theme inheritance (@siriwatknp)

- packages/mui-docs/package.json
- pnpm-lock.yaml
Needed to bring this internal package to X/Toolpad docs
> [code-infra] Update peer dependency of `@mui/utils` in `@mui/docs`

- .github/ISSUE_TEMPLATE/1.bug.yml
https://github.com/mui/material-ui/discussions/45424#discussioncomment-12417820
> Add StackBlitz template to issue template

- docs/public/_redirects
> [core] Improve instructions on changing domain

- packages-internal/scripts/typescript-to-proptypes/src/getPropTypesFromFile.ts
- packages-internal/scripts/typescript-to-proptypes/test/component-type/input.d.ts
- packages-internal/scripts/typescript-to-proptypes/test/component-type/input.js
- packages-internal/scripts/typescript-to-proptypes/test/component-type/output.js
_Fixes https://github.com/mui/toolpad/issues/4790
> [code-infra] Support `React.ComponentType` in proptypes generation

- docs/pages/blog/material-ui-v7-is-here.md
> [blog] Update v7 stable blog date

- docs/data/material/components/material-icons/SearchIcons.js
> [docs] Fix Material Icons page in dark mode

- docs/notifications.json
Add notification for v7 stable release.
> [docs] Add "Material UI v7 is here" to the notifications

- docs/src/modules/components/Demo.js
> [docs] Fix Safari issue in dark mode

- docs/data/material/getting-started/templates/blog/components/Footer.js
- docs/data/material/getting-started/templates/blog/components/Footer.tsx
- docs/data/material/getting-started/templates/marketing-page/components/Footer.js
- docs/data/material/getting-started/templates/marketing-page/components/Footer.tsx
> [docs] Rename GitHub icon import

- docs/data/joy/customization/themed-components/themed-components.md
The link got broken with #45031
> [docs] Fix link to mui-joy/src/styles/components.d.ts

- docs/data/material/migration/upgrade-to-v7/upgrade-to-v7.md
- docs/data/system/migration/migrating-to-v6/migrating-to-v6.md
- docs/data/system/migration/upgrade-to-v7/upgrade-to-v7.md
- docs/data/system/pages.ts
- docs/translations/translations.json
Fix a few things that I noticed while reading the migration guide.
> [docs] Fix migration instructions

- test/regressions/vite.config.mts
Make sure function names are not mangled. Context: https://github.com/mui/material-ui/pull/45747#issuecomment-2765855915
> [code-infra] Stabilize theme viewer screenshot tests

- .eslintrc.js
- examples/material-ui-pigment-css-vite-ts/package.json
- examples/material-ui-pigment-css-vite-ts/src/App.tsx
- examples/material-ui-pigment-css-vite-ts/vite.config.ts
Fixes https://github.com/mui/pigment-css/pull/340
> [examples] Fix Pigment vite integration example

- docs/src/components/banner/AppHeaderBanner.tsx
Add v7 is here banner to v6 docs
> [docs] Add v7 is here banner

- CHANGELOG.md
> Fix v6.4.11 changelog

- package.json
> Fix root package.json version

- packages/mui-material-nextjs/src/v13-appRouter/appRouterV13.tsx
> [material-nextjs] Do not wrap `@layer` order rules in App Router

- docs/src/modules/components/AppLayoutDocsFooter.js
The feedback do not get transmeted to slack anymore.
I suspect #45278 to be the root cause
> [docs-infra] Fix feedback management

- .eslintrc.js
- docs/data/joy/components/snackbar/SnackbarHideDuration.js
- docs/data/joy/components/snackbar/SnackbarHideDuration.tsx
Closes https://github.com/mui/mui-public/issues/195
> [code-infra] Disallow redundant window prefixes for globals

- docs/pages/careers.tsx
- docs/pages/careers/react-engineer-docs-infra.md
> [website] Open docs-infra role

- renovate.json
Make sure to update react and its types in sync
> [code-infra] Expand renovate.json for react types

- docs/pages/blog/mui-x-v8.md
> [blog] Update MUI X v8 blogpost release date

- docs/public/_redirects
Polish on #45674
Why: https://www.conductor.com/academy/redirects/faq/redirect-chains/
> [core] Fix redirection chains

- docs/pages/blog/mui-x-v8.md
https://deploy-preview-45945--material-ui.netlify.app/blog/mui-x-v8/#migration-guide
> [blog] Fix migration link on v8 announcement

- docs/pages/_document.js
- examples/joy-ui-cra-ts/public/index.html
- examples/material-ui-cra-ts/public/index.html
- examples/material-ui-cra/public/index.html
- examples/material-ui-nextjs-pages-router-ts/pages/_document.tsx
- examples/material-ui-nextjs-pages-router/pages/_document.js
- examples/material-ui-nextjs-ts-v4-v5-migration/pages/_document.tsx
See https://mathiasbynens.be/notes/rel-shortcut-icon for why.
Also, how to do favicons in 2025 https://evilmartians.com/chronicles/how-to-favicon-in-2021-six-files-that-fit-most-needs
> [core] Fix outdated <link rel="shortcut icon"

- docs/data/material/migration/migration-v4/v5-component-changes.md
> [docs-v5] Add AccordionSummary to the breaking change migration

- docs/data/material/components/avatars/UploadAvatars.js
- docs/data/material/components/avatars/UploadAvatars.tsx
- docs/data/material/components/avatars/avatars.md
Small pr that adds a demo on how to build avatar upload with MUI
Resolves https://github.com/mui/material-ui/issues/45131
> [docs][Avatar] Add avatar upload demo

- docs/pages/careers.tsx
- docs/pages/careers/code-infra-engineer.md
> [website] Update open roles

- docs/data/material/migration/upgrade-to-v6/migrating-to-pigment-css.md
closes https://github.com/mui/material-ui/issues/45904
> [docs][material-ui] Update CSS variable usage in migration guide for Pigment CSS

- docs/data/material/integrations/tailwindcss/tailwindcss-v4.md
> [docs] Add a guide for extending Material UI classes in Tailwind CSS

- docs/src/modules/components/AppLayoutDocs.d.ts
- docs/src/modules/components/AppSearch.d.ts
- docs/src/modules/components/AppSettingsDrawer.d.ts
`skipLibCheck: true` is hiding these problems.
> [code-infra] Correct some manually curated .d.ts files

- docs/next.config.ts
- packages/mui-material/src/Button/Button.js
Related to #45990
Preview:
- https://deploy-preview-46051--material-ui.netlify.app/x/
- https://deploy-preview-46051--material-ui.netlify.app/material-ui/react-menu/#material-ui-popup-state
> [core] Fix internal version duplication

- docs/src/components/about/OurValues.tsx
Sync with https://www.notion.so/mui-org/Values-behaviors-d3a1e1c60e2a4c0782f770cceada54bd, it's outdated now.
Preview: https://deploy-preview-46061--material-ui.netlify.app/careers/
> [website] Update values

- .circleci/config.yml
Port https://github.com/mui/mui-x/pull/17729
> [code-infra] Remove required checkout workflows in circleci

- .circleci/config.yml
We can just run the dedupe check in test_static. Will remove the required check once merged
> [code-infra] Remove checkout job altogether

- docs/src/components/home/DesignKits.tsx
A follow-up on #44956, it doesn't feel aligned
https://mui.com/design-kits/
Preview https://deploy-preview-46065--material-ui.netlify.app/design-kits/
> [website] Fix CSS alignment

- docs/pages/blog/mui-x-sep-2024-price-update.md
Make it clearer based on the case in https://mui.zendesk.com/agent/tickets/25606.
Preview: https://deploy-preview-45265--material-ui.netlify.app/blog/mui-x-sep-2024-price-update/
> [website] Clarify grandfathering policy

- docs/data/joy/components/modal/FadeModalDialog.js
- docs/data/joy/components/modal/FadeModalDialog.tsx
> [docs] fix fade modal demo

- docs/data/material/migration/migrating-from-deprecated-apis/migrating-from-deprecated-apis.md
Cherry-pick of https://github.com/mui/material-ui/pull/46129
> [docs] Add ListItemButton to make the deprecation clear

- docs/data/material/components/init-color-scheme-script/init-color-scheme-script.md
> [docs] Update InitColorSchemeScript options to match colorSchemeSelector

- docs/src/components/pricing/PricingTable.tsx
Pre-requisite to https://github.com/mui/material-ui/pull/44267/
Changed MUI Base -> Base UI and did some minor UI fixes.
Preview: https://deploy-preview-46231--material-ui.netlify.app/pricing/
> [website] Fix pricing page content

- docs/pages/careers.tsx
- docs/pages/careers/technical-recruiter.js
- docs/pages/careers/technical-recruiter.md
https://deploy-preview-46619--material-ui.netlify.app/careers/technical-recruiter/
> [website] Open the Technical Recruiter role

- docs/src/components/pricing/PricingTable.tsx
Preview: https://deploy-preview-46691--material-ui.netlify.app/pricing/
- Made Treemap Community -> Pro
- Linked Export page and marked it available
- No more layout shift in Charts expansion table (bug fix)
> [charts] Marked Treemap chart as Pro

- packages/mui-codemod/src/util/migrateToVariants.js
- packages/mui-codemod/src/v1.0.0/color-imports.js
- packages/mui-codemod/src/v6.0.0/styled/styled-v6.js
- packages/mui-codemod/src/v6.0.0/theme-v6/theme-v6.js
Fix typos in `codemod` package
> [core] Fix typos in `codemod` package

- packages/markdown/loader.mjs
- packages/mui-system/src/cssContainerQueries/cssContainerQueries.ts
- packages/mui-system/src/cssVars/createCssVarsProvider.js
Fix typos in `markdown` and `system` packages
> [core] Fix typos in `markdown` and `system` packages

- docs/src/modules/components/AppNavDrawerItem.tsx
- docs/src/modules/components/TopLayoutBlog.js
- docs/src/modules/joy/literalToObject.ts
Fix typos in `docs/src/modules` folder
> [internal] Fix typos in code comments

- docs/data/material/pages.ts
- docs/translations/translations.json
closes #46687
**Preview**: https://deploy-preview-46832--material-ui.netlify.app/material-ui/getting-started/
> [docs] Add a link to open `llms.txt`

- docs/pages/careers.tsx
- docs/pages/careers/account-executive.md
Closed the AM role and updated the AE description.
https://deploy-preview-46843--material-ui.netlify.app/careers/
> [website] Update sales roles openings

- CHANGELOG.md
- package.json
- packages-internal/scripts/package.json
- packages-internal/test-utils/package.json
- packages/markdown/package.json
- packages/mui-codemod/package.json
- packages/mui-core-downloads-tracker/package.json
- packages/mui-docs/package.json
- packages/mui-envinfo/package.json
- packages/mui-icons-material/package.json
- packages/mui-lab/package.json
- packages/mui-material-nextjs/package.json
- packages/mui-material-pigment-css/package.json
- packages/mui-material/package.json
- packages/mui-private-theming/package.json
- packages/mui-styled-engine-sc/package.json
- packages/mui-styled-engine/package.json
- packages/mui-stylis-plugin-rtl/package.json
- packages/mui-system/package.json
- packages/mui-types/package.json
- packages/mui-utils/package.json
> [release] v7.3.2

- docs/data/material/getting-started/templates/blog/components/MainContent.js
- docs/data/material/getting-started/templates/blog/components/MainContent.tsx
Maintainers: This should have `label:docs` on it.
> [docs] Fix typo in blog component MainContent

- CHANGELOG.md
- package.json
- packages/mui-core-downloads-tracker/package.json
- packages/mui-docs/package.json
- packages/mui-icons-material/package.json
- packages/mui-material/package.json
- scripts/README.md
Not versioning `@mui/lab` as it was done in https://github.com/mui/material-ui/pull/47012
> Release 7.3.4

- docs/package.json
- scripts/README.md
Noticed that it deployed my local master, which was behind.
> [code-infra] Publish docs from upstream
