mui/material-ui

- docs/src/modules/components/AppTableOfContents.js
This is a follow-up on #18756 from @Janpot. I wanted to test that the bug was indeed fixed in Next.js: https://github.com/vercel/next.js/issues/9678. It's indeed fixed, proof: https://deploy-preview-31419--material-ui.netlify.app/components/alert/#basic-alerts.
In https://mui.com/api/data-grid/grid-row-spacing-params/ you can see how the page is missing the `activePage` which breaks the anchor:
> [core] Simplify anchor link

- docs/data/material/customization/typography/ResponsiveFontSizesChart.js
- update unit from `rem` to `px` in displayed responsive font-sizes chart
**before:**
Values shown in the chart are in `px` same as y-axis scale. But y-axis says `rem` instead of `px`
**after:**
> [docs] Fix y-axis unit used in the responsive font sizes chart

- docs/data/material/getting-started/templates/Templates.js
Closes https://github.com/mui/material-ui/issues/30905
Preview: https://deploy-preview-31425--material-ui.netlify.app/getting-started/templates/
> [docs] Fix source code links on the Templates page

- packages/mui-material/src/OutlinedInput/NotchedOutline.js
Fixes https://github.com/mui/material-ui/issues/31367
Makes span in `NotchedOutline` visible so that border respects it and its' padding in Safari
> [TextField] fix disappearing border in Safari

- docs/src/modules/components/AppNavDrawerItem.js
- docs/src/modules/components/Link.tsx
- examples/nextjs-with-typescript/src/Link.tsx
- examples/nextjs/src/Link.js
#31341 introduces a regression:
This is because of the how `docs/src/modules/components/Link` is implemented. In some cases (external links), we don't land into Next.js's Link component that intercepts the `prefetch` prop.
> [examples] Fix Link leak of Next.js props

- examples/nextjs-with-typescript/.gitignore
Same as https://github.com/mui/mui-x/pull/3068, to match https://github.com/vercel/next.js/blob/5a16b1a26f6c213776deed9ac465e2bc81cdf5f3/packages/create-next-app/templates/typescript/gitignore#L35
> [examples] Ignore tsbuildinfo with Next.js

- .circleci/config.yml
Fixes 
From https://app.circleci.com/pipelines/github/mui/material-ui/66259/workflows/a10e4a36-1fc8-4053-9cbf-405af395a630/jobs/357658
More information: https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034
I did the same for X in https://github.com/mui/mui-x/pull/4143
I changed `node:12` -> `node:12.22` because the `12` tag doesn't exist:
> [test] Upgrade CircleCI convenience image

- docs/src/modules/components/ApiPage.js
Safari 15 shows the API table with weird background. The cause here is the use of `hex` and `rgba` values, color transition between different colors ( "contentColor" vs black ) and maybe missing color stop on the transparent black color.
**before**
**after:**
> [docs] Fix API page table styles in Safari

- docs/pages/experiments/joy/list.tsx
- packages/mui-joy/src/List/List.test.js
- packages/mui-joy/src/List/List.tsx
- packages/mui-joy/src/List/ListProps.ts
- packages/mui-joy/src/List/RowListContext.ts
- packages/mui-joy/src/List/listClasses.ts
- packages/mui-joy/src/ListDivider/ListDivider.test.js
- packages/mui-joy/src/ListDivider/ListDivider.tsx
- packages/mui-joy/src/ListDivider/ListDividerProps.ts
- packages/mui-joy/src/ListItem/ListItem.tsx
- packages/mui-joy/src/ListItemButton/ListItemButton.tsx
Prepare for the menu components (menubar).
- add `row` prop to `List` component which passes to React context.
- `ListItem`, `ListItemButton`, and `ListDivider` listen to the context and adjust the styles according to the direction of the parent list.
Note: the context is not nestable which makes sense because the nested row is not common.
---
> [Joy] Support horizontal `List`

- docs/pages/experiments/joy/avatar.tsx
- packages/mui-joy/src/Avatar/Avatar.tsx
- packages/mui-joy/src/Avatar/AvatarProps.ts
- packages/mui-joy/src/Avatar/avatarClasses.ts
- packages/mui-joy/src/Avatar/index.ts
- packages/mui-joy/src/index.ts
- packages/mui-joy/src/internal/svg-icons/Person.tsx
- packages/mui-joy/src/styles/components.d.ts
- `variant`: `'outlined' | 'light' | 'contained'` (`contained` by default)
- `color`: `'danger' | 'info' | 'neutral' | 'primary' | 'success' | 'warning'` (`neutral` by default)
-  `size`: `'sm' | 'md' | 'lg'` (`md` by default)
Preview: https://deploy-preview-31303--material-ui.netlify.app/experiments/joy/avatar/
> [Joy] Add Avatar component

- docs/public/_headers
The reproduction:
1. open https://mui.com/components/data-grid/export/
2. click on the print button.
It was first raised by @alexfauquette in https://mui-org.slack.com/archives/G011VC970AW/p1646824105396129. I broke it in https://github.com/mui/material-ui/pull/31062.
@DanailH Should we document this limitation? Maybe this is a strong case for having a new intermediary API like AG Grid, one that only puts the grid in a print-ready mode to avoid the iframe.
---
@danilo-leal A side note on the screenshot. Did we recently work on the CSS of the `"bg": "inline"}}` option? It feels a bit broken. On https://mui.com/components/data-grid/export/#disabled-format
**Current**
**Expected?**
> [data-grid] Fix print export feature

- docs/src/pages/versions/versions.md
A quick follow-up on #31029. I believe that LTS is a common term developer might search for, but in the current form, there is no relevant matches:
(found this while I was looking at something unrelated on https://next.vuetifyjs.com/en/getting-started/installation/)
> [docs] Make LTS searchable

- docs/src/modules/utils/codeVariant.js
- docs/src/modules/utils/getDemoConfig.js
- docs/src/modules/utils/helpers.test.js
- docs/src/modules/utils/helpers.ts
Motivation: https://github.com/mui/material-ui/pull/30999#discussion_r815464531 and [the most upvoted issues](https://github.com/mui/material-ui/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)
- 2020: https://mui.com/blog/2020-developer-survey-results/#21-what-type-system-are-you-using, TypeScript: 45%
- 2021: https://mui.com/blog/2021-developer-survey-results/#what-type-system-are-you-using, TypeScript: 63%
https://deploy-preview-31808--material-ui.netlify.app/components/switches/#controlled
> [docs] Use TypeScript demos by default

- docs/pages/_document.js
All of the https://mui.com/material-ui/ pages are indexed on Google, for instance: https://www.google.com/search?q=%22https%3A%2F%2Fmui.com%2Fmaterial-ui%2Freact-alert%2F%22. I could find one path that leads to this outcome
1. https://mui.com/components/menus/#unstyled
2. https://mui.com/base/react-menu/
3. https://mui.com/base/api/menu-unstyled/
4. https://mui.com/material-ui/guides/minimizing-bundle-size/ 
5. https://mui.com/material-ui/react-alert/ 🎰
This leads to duplication of content, which we shouldn't let fly.
I have noticed the problem in https://app.ahrefs.com/site-audit/2944028/37/issues. We reach the limit I set on the number of internal pages (2,000). Usually, we have ~1,352 internal pages that are crawlable.
> [docs] Solve duplication of content

- docs/src/components/pricing/PricingTable.tsx
Since we are moving the date picker in X, it seems to make sense to update the pricing page. I have also used the opportunity to bring clarity on using the full name of the MUI Core products:
https://deploy-preview-31889--material-ui.netlify.app/pricing/
> [website] Date picker is in MUI X

- packages/mui-base/src/SliderUnstyled/SliderUnstyled.test.js
- packages/mui-base/src/SliderUnstyled/useSlider.ts
Fixes https://github.com/mui/material-ui/issues/31851
> [SliderUnstyled] Fix dragging on disabled sliders

- docs/pages/api-docs/popper.json
- docs/pages/material-ui/api/popper.json
- docs/translations/api-docs/popper/popper.json
- packages/mui-material/src/Popper/Popper.tsx
Modified material Popper with default styled-component (so that the consumer can pass sx prop to it).
closes #29604
> [Popper] Expose the `sx` prop

- packages/mui-base/src/SelectUnstyled/useSelect.ts
- packages/mui-joy/src/Link/Link.tsx
- packages/mui-utils/src/useForkRef.ts
Currently instances in [ref callbacks are allowed to be nullable due to our bivariance hack](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/78d7283e392c638452e7c1c29001d6cc57453f40/types/react/index.d.ts#L91). However, during runtime these instances can be null: https://codesandbox.io/s/refs-are-nullable-m44vxx
[We'll likely remove the bivariance hack](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/58936) to catch these issues in the future. In the meantime, existing packages and tests should guard against nullable instances regardless.
The issue was first reported in https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/58464
> [utils] Improve type inference of useForkRef

- docs/src/modules/components/AppTableOfContents.js
On a large screen, if the content is short, the TOC is pushed up behind the header. Fixed by setting the height to be `100vh` and increase the padding-top instead (The old approach also use the height + padding so there should be no regression).
> [docs] Fix TOC layout for large screen

- docs/scripts/postMigration.ts
- docs/src/modules/components/AppFrame.js
- docs/src/modules/components/AppLayoutDocs.js
https://app.ahrefs.com/site-audit/3276941/8/overview
**Note:** All the 404 errors come from mui-x URLs which are out of scope of this PR.
---
- Refine the redirects in post-migration
- Exclude new URLs from the old docsearch so that we don't have this duplicate
---
> [docs] Refine the redirects

- docs/data/material/components/avatars/BackgroundLetterAvatars.js
- docs/data/material/components/avatars/BackgroundLetterAvatars.tsx
- packages/mui-system/src/colorManipulator.js
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.
> [core] Replace deprecated String.prototype.substr()

- packages/mui-base/package.json
Currently, `@mui/types` is set to devDependencies.
If `@mui/base` is used by itself in a typescript project, type resolution will not work.
https://github.com/mui/material-ui/blob/1470c720c615bbb0ba3860c2dacf3d8627e5bfb5/packages/mui-base/src/FormControlUnstyled/FormControlUnstyled.tsx#L4
This PR added `@mui/types` to dependencies like [other packages](https://github.com/mui/material-ui/blob/1470c720c615bbb0ba3860c2dacf3d8627e5bfb5/packages/mui-material/package.json#L66).
> [base] Add `@mui/types` to dependencies

- docs/pages/experiments/joy/components.tsx
- docs/pages/experiments/joy/input.tsx
- packages/mui-joy/src/Avatar/Avatar.test.js
- packages/mui-joy/src/Avatar/Avatar.tsx
- packages/mui-joy/src/Avatar/AvatarProps.ts
- packages/mui-joy/src/Input/Input.tsx
- packages/mui-joy/src/styles/defaultTheme.ts
- Input: use `minHeight` instead of `height` (easier when use with other component, take a look at subscribe input in https://deploy-preview-31971--material-ui.netlify.app/experiments/joy/input/)
- Avatar: add missing `ownerState` to slots
---
> [Joy] Miscellaneous fixes 2

- packages/mui-material/src/ButtonBase/ButtonBase.js
Before: https://codesandbox.io/s/checkboxes-material-demo-forked-xrw1ff?file=/demo.tsx
After: https://codesandbox.io/s/checkboxes-material-demo-forked-vg2d2u?file=/demo.tsx
In React 18, any component derived from `ButtonBase` that receives focus during mount will crash when `rippleRef.current.pulsate()` is called. This happens because the `TouchRipple` is rendered conditionally to save resources on SSR. However, in React 18, the effect that sets the focus runs slightly faster than the effect responsible for updating the state to render the ripple. More information see https://github.com/facebook/react/issues/24102#issuecomment-1075524161
I noticed this bug when testing the compatibility of the DataGrid with React 18. In our case, we use `Checkbox` and when a cell switches from view to …
> [ButtonBase] Start ripple pulsation only after mount

- docs/data/system/styled/styled-pt.md
- docs/data/system/styled/styled-zh.md
- docs/data/system/styled/styled.md
Fixed a small typo by removing an extra curly bracket.
> [docs] Fix small typo in the `styled()` utility page

- docs/data/material/guides/interoperability/interoperability.md
Fix the CSS Modules example on styling deeper elements.
CSS Modules generate a unique ID for each class, and the previous example wasn't working because it didn't take that into account.
**How to test**
1. Go to [this Codesandbox example](https://codesandbox.io/s/css-modules-forked-zc5u0t?file=/src/CssModulesSlider.module.css)
2. Erase the ":global" and sees the CSS loses its effect.
> [docs] Fix the CSS modules example in the Interoperability page

- packages/mui-private-theming/src/defaultTheme/index.d.ts
- section on customizing themes has moved from "https://mui.com/guides/typescript/#customization-of-theme" to "https://mui.com/customization/theming/#custom-variables"
- update href to point to new location
> [docs] Update href for 'TypeScript guide on theme customization' 

- docs/pages/experiments/joy/avatar.tsx
- docs/pages/experiments/joy/components.tsx
- packages/mui-joy/src/Avatar/Avatar.tsx
- packages/mui-joy/src/AvatarGroup/AvatarGroup.test.js
- packages/mui-joy/src/AvatarGroup/AvatarGroup.tsx
- packages/mui-joy/src/AvatarGroup/AvatarGroupProps.ts
- packages/mui-joy/src/AvatarGroup/avatarGroupClasses.ts
- packages/mui-joy/src/AvatarGroup/index.ts
- packages/mui-joy/src/index.ts
- packages/mui-joy/src/styles/components.d.ts
- [Demos](https://deploy-preview-31980--material-ui.netlify.app/experiments/joy/avatar/)
- [Playground](https://deploy-preview-31980--material-ui.netlify.app/experiments/joy/components/?name=AvatarGroup)
---
Inspired by https://github.com/mui/material-ui/issues/31958#issuecomment-1078617987.
Get rid of internal calculation about the number of extra to show which give developers full control of the extra number logic. This approach would reduce a lot of edge cases problem because we don't use `React.cloneElement` anymore, developers can wrap with whatever they want. Thanks to CSS variables, we don't introduce any class selector which makes customization so easy.
```js
// Material
<AvatarGroup max={4}>
{items.map(() => <Avatar />}
</AvatarGroup>
// Joy
<AvatarGroup>
{items.slice(0, …
```
> [Joy] Add `AvatarGroup` component

- docs/data/material/components/button-group/SplitButton.js
- docs/data/material/components/button-group/SplitButton.tsx
Fixes https://github.com/mui/material-ui/issues/31357
Deploy preview: https://deploy-preview-31969--material-ui.netlify.app/components/button-group/#split-button
> [docs] Improve a11y on the split button demo

- packages/mui-codemod/src/v5.0.0/variant-prop.js
- packages/mui-codemod/src/v5.0.0/variant-prop.test/expected.js
A spread of props onto an element could contain a variant. If so, that should win over the variant added by the codemod, so adding the codemod variant to the beginning of the props rather than the end.
> [codemod] Fix variant prop placement

- packages/mui-material/src/Grow/Grow.js
Introducing a temporary workaround for CSS transition regression in Safari 15.4
WebKit tickets:
- https://bugs.webkit.org/show_bug.cgi?id=238067
- https://bugs.webkit.org/show_bug.cgi?id=237972  
Note: this workaround does not address the case of concurrent CSS transitions on independent components (e.g. Speed Dial)
Resolves #31380
Preview: https://deploy-preview-31975--material-ui.netlify.app/components/transitions/#grow
> [Grow] Add a workaround for Safari 15.4 CSS transition bug

- packages/material-ui/src/TableBody/TableBody.d.ts
- packages/material-ui/src/TableContainer/TableContainer.d.ts
- packages/material-ui/src/TableFooter/TableFooter.d.ts
- packages/material-ui/src/TableHead/TableHead.d.ts
Targetting 4.x but similar changes are probably required for current typings as well.
Fixes issues with TypeScript 4.7 canary (https://github.com/microsoft/TypeScript/pull/48366 specifically) that are blocking https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56210
> [core] Fix TS 4.7 compat issues

- docs/data/material/components/selects/SelectSmall.js
- docs/data/material/components/selects/SelectSmall.tsx
- docs/data/material/components/selects/selects.md
Added demo in documentation to showcase demo of a select component with `size='small'` prop.
Preview:
https://deploy-preview-32060--material-ui.netlify.app/components/selects/#small-size
closes #31348
> [docs] Add small size Select demo

- packages/mui-material/src/Link/Link.js
- test/regressions/fixtures/Link/LinkColor.js
close #31857
The `Link` inherit `Typography`. As a result, the styles injection order looks like this (order by the highest to the lowest priority):
Link
- sx
- theme.styleOverrides
- Typography
- sx
- theme.styleOverrides
When `color` prop is passed to `Link`(`<Link color="#ff5252">`), it is sent to the Typography which is then turned to sx at the end. The `sx` of typography could not win the `theme.styleOverrides` of the Link, this is why it causes the issue.
This PR passes color to Link's `sx` directly and add a regression test.
---
> [Link] Fix color transformation

- docs/data/material/components/pickers/lab-date-and-time-pickers.md
- docs/notifications.json
- docs/pages/blog/lab-date-pickers-to-mui-x.js
- docs/pages/blog/lab-date-pickers-to-mui-x.md
- docs/src/modules/components/AppNavDrawer.js
- docs/src/modules/components/AppNavDrawerItem.js
- Add date-pickers product identifier
- Use https://mui.com/components/material-icons/?query=date&selected=DateRange as date-pickers navigation icon
- Rename blog post URL to `/blog/lab-date-pickers-to-mui-x`
- Add notification about the blog post
> [docs] Add date-pickers product identifier

- packages/mui-material/src/locale/index.ts
The labelDisplayedRows was partly untranslated and commented out.
I finished the translation and commented it back in. I am a native
speaker of etEE locale.
> [l10n] Fix etEE locale in the Pagination component

- packages/mui-material/src/ListItemButton/ListItemButton.js
Closes #32082
The styling of the `<ListItemButton>` is quite similar to that of `<ListItem>`, but the width specifier was not present among the style rules for the former.
> [ListItemButton] Specified width so that text would ellide

- docs/data/base/components/form-control/BasicFormControl.js
- docs/data/base/components/form-control/BasicFormControl.tsx
- docs/data/base/components/form-control/BasicFormControl.tsx.preview
- docs/data/base/components/form-control/UseFormControl.js
- docs/data/base/components/form-control/UseFormControl.tsx
- docs/data/base/components/form-control/UseFormControl.tsx.preview
- docs/data/base/components/form-control/form-control.md
- docs/data/base/pages.ts
- docs/data/material/components/text-fields/text-fields.md
- docs/pages/api-docs/form-control-unstyled.json
- docs/pages/base/api/form-control-unstyled.json
- docs/pages/base/react-form-control.js
- packages/mui-base/src/FormControlUnstyled/FormControlUnstyled.tsx
- packages/mui-base/src/FormControlUnstyled/FormControlUnstyledProps.ts
Created new content for the FormControlUnstyled page in Base docs.
Preview - https://deploy-preview-32073--material-ui.netlify.app/base/react-form-control/
> [docs] Create the FormControl page

- packages/mui-base/package.json
- packages/mui-docs/package.json
- packages/mui-icons-material/package.json
- packages/mui-joy/package.json
- packages/mui-lab/package.json
- packages/mui-material-next/package.json
- packages/mui-material/package.json
- packages/mui-private-theming/package.json
- packages/mui-styled-engine/package.json
- packages/mui-styles/package.json
- packages/mui-system/package.json
- packages/mui-utils/package.json
We've been testing with React 18 during its incubation period. Should be safe-ish to use React 18 with Mui (except streaming rendering probably).
> [core] Update peer deps to support React 18

- docs/data/material/components/cards/RecipeReviewCard.js
- docs/data/material/components/cards/RecipeReviewCard.tsx
- docs/pages/about.tsx
- docs/pages/blog/2021-developer-survey-results.md
- docs/pages/careers.tsx
- docs/src/components/home/UserFeedbacks.tsx
- docs/src/components/productCore/CoreHero.tsx
- docs/src/components/productDesignKit/DesignKitFAQ.tsx
- docs/src/pages/careers/designer.md
- docs/src/pages/careers/full-stack-engineer.md
- packages/mui-material/test/typescript/components.spec.tsx
"Studio" was the codename of our low-code initiative. We have finalized the public name https://www.notion.so/mui-org/Name-domain-for-Studio-aec19e9fcb6749e5b34ddcf9857c6386. The main interesting property of this name is that "MUI Toolpad" can be shortened to "Toolpad". Of course, we checked trademarks, SEO ranking difficulty, pronunciation, and other dimensions.
> [website] The studio finally has a name, use it

- packages/material-ui-codemod/package.json
release:publish assumes `/build` which `material-ui-codemod` was lacking.
> [core] Fix 4.x release:publish

- docs/data/base/components/button/UnstyledButtonsSimple.js
- docs/data/base/components/button/UnstyledButtonsSimple.tsx
- docs/data/base/components/button/UnstyledButtonsSpan.js
- docs/data/base/components/button/UnstyledButtonsSpan.tsx
ButtonUnstyled demos show the simpler `styled(ButtonUnstyled)` approach where possible. 
It reduced the number of rendered components and allow additional customization (like rendering an `a` instead of a `button`).
https://deploy-preview-32092--material-ui.netlify.app/base/react-button/
> [docs] Simplify customization examples in ButtonUnstyled demos

- packages/mui-material/src/Link/Link.js
- test/regressions/fixtures/Link/LinkColor.js
The change introduced in https://github.com/mui/material-ui/pull/32045 does not support `sx` as array or callback which causes this bug in the doc. Luckily, it is not released yet 😅
This PR fixes it, however, it is not perfect for the `textDecorationColor`. We should find a better way to get rid of the color manipulation in the future.
> [Link] Fix `sx` color to support callback 

- docs/src/modules/utils/getDemoConfig.js
Preview: https://deploy-preview-32130--material-ui.netlify.app/components/buttons/#basic-button
The demos, when opened in CodeSandbox/StackBlitz, are still using `ReactDOM.render` instead of  `ReactDOM.createRoot`. There's a console message warning about that:
> [docs] Update demo config for React 18

- docs/data/material/guides/migration-v4/migration-v4.md
Hi @mnajdova & @oliviertassinari,  
I think you'll be pleased to know that TSS now has [out of the box support for theme styleOverrides](https://docs.tss-react.dev/mui-theme-styleoverrides).  🥳
It's a big deal for libraries based on MUI like [mui-datatables](https://github.com/gregnb/mui-datatables) that now have an option to update to MUIv5 without undergoing heavy refactoring.  
In this PR I update the migration guide.  
Best regards,
> [docs] Add TSS support for theme style overrides

- docs/data/base/components/slider/slider.md
This one was already mostly done before the final review so this is mostly just for style consistency. 🤝 I also introduced the term "thumb" earlier in the piece, and when placed in context I think it's easier to infer the meaning.
> [docs] Base Slider style revisions and final review

- docs/data/base/components/menu/menu.md
- docs/pages/base/api/form-control-unstyled.json
This PR applies the style guide to the Base Menu document. For this piece, the changes mostly amount to placing `MenuUnstyled` and `MenuItemUnstyled` inside back ticks.
This piece also answered the question I posed in #32095 about naming the hooks in the title—and the answer is no! The title of this one would be way too dense if I named both hooks there. I will update the others I've reviewed so far to reflect this.
Preview - https://deploy-preview-32097--material-ui.netlify.app/base/react-menu/
> [docs] Base Menu style revisions and final review

- docs/data/material/getting-started/learn/learn.md
- docs/src/pages.ts
- docs/translations/translations.json
https://deploy-preview-31989--material-ui.netlify.app/getting-started/learn/
This PR revises the Learn page, primarily to replace outdated third-party resources with newer v5 content that the community has created. 
I also took the liberty of dropping the Usage demo directly into this doc rather than linking to the Quick Start page, to encourage the reader to stay in one place and make it easier for them to play around.
One question: Is it worthwhile to continue to list the outdated paid resources? I added a note to underscore this fact, but I would still hate to set someone up for failure by recommending that they spend money on outdated info.
> [docs] Update Learn page copy and resource list

- docs/data/base/components/badge/badge.md
- docs/pages/base/api/form-control-unstyled.json
This PR applies the style guide to the Base Badge document.
Beyond style changes, I rewrote a couple sections for clarity, and I've also proposed some reorganizing: since some of the props only apply to numerical badges, I created a section to group them together.
> [docs] Base Badge style revisions and final review

- docs/data/material/components/material-icons/SearchIcons.js
**Before**
https://mui.com/material-ui/material-icons/
**After**
https://deploy-preview-32239--material-ui.netlify.app/material-ui/material-icons/
---
Asking the review from Michal per https://www.notion.so/mui-org/b3671ef653dc421ea8ab4b6dcac755d2?v=392be6e77b744138b562c263c7cfafb4&p=2c123f5ccdb84f3b91c583463b620807
> [docs] Format number icons search

- packages/mui-material/src/Link/Link.js
- packages/mui-material/src/Link/Link.test.js
- test/regressions/fixtures/Link/LinkColor.js
Closes #32172
Closes #32183 
**Root cause**
The prop `color` (default as `primary`) is passed to `sx` internally which has higher priority than style overrides. This PR check the instance `color` prop before passing it to `sx`.
```js
<Link>...</Link> // ✅ style overrides (note that by overriding `textDecorationColor`, it removes the color calculation)
<Link color=...>...</Link> // goes to sx
<Link sx={{ color: ... }}> // goes to sx
```
> Argos change is expected.
---
> [Link] Fix style overrides 5.6.0 regression

- packages/mui-material/src/Grow/Grow.js
Resolves #32167
Preview: https://deploy-preview-32202--material-ui.netlify.app/material-ui/react-menu/#main-content
> [Grow] Extend Safari CSS transition bug workaround on WebKit browsers

- package.json
- yarn.lock
Revert eslint-plugin-import version update made in #32229, as it causes `yarn start` to fail. I'll try to get to the root cause of it, but reverting the change will make the master branch healthy again.
Closes #32249
> [core] Revert #32229

- packages/mui-base/package.json
- packages/mui-material-next/package.json
- packages/mui-material/package.json
- packages/mui-private-theming/package.json
- packages/mui-styles/package.json
- packages/typescript-to-proptypes/package.json
This change is related to #32181
it's synching the npm packages description with
> [docs] Sync package description with the docs

- docs/src/components/pricing/PricingTable.tsx
Column spanning was released today in https://github.com/mui/mui-x/releases/tag/v5.9.0
> [website] Mark DataGrid Column spanning done on Pricing page

- packages/mui-material/src/FilledInput/FilledInput.js
- packages/mui-material/src/Input/Input.js
Closes #31766 
Preview: https://deploy-preview-32188--material-ui.netlify.app/components/text-fields/#main-content
> [TextField] Add a workaround for Safari CSS transition scale bug

- docs/data/material/customization/how-to-customize/how-to-customize.md
links at top of the page weren't linked to correct anchors. Fixed and updated the name of #&#x2060;2 from "reusable style overrides" to "reusable component" to match the #&#x2060;2 section header.
> [docs] Update "How to customize" page anchor links

- test/README.md
Hi, I found a problem for which I don't even see the point of opening an issue, because the changes are tiny.
In the instructions for writing tests there is a link (Example) that leads directly to page 404.
I opened this file manually and saw that the url is different from the one specified in the link.
The only difference is in the name of the packages (mui-material vs. material-ui).
Well, I corrected it.
> [docs] Fix broken link in the test contributing guide

- docs/data/material/components/material-icons/material-icons.md
It seems to get changed in #32048, I assume it wasn't intended since off the purpose of the PR. In practice, I think that keeping the side nav label, h1, and title as close as possible would be better:
- side nav === h1 helps to not disorient users once they click on a link. It gives them a confirmation that they are on the right page (when I open a load of tabs, it personally helps me).
- h1 === title helps with SEO that it stays on topic and often both are taken into account for the ranking.
I'm capitalizing the "Icons" exceptionally because it seems to be the convention when searching for "XX icons" on Google.
https://deploy-preview-32235--material-ui.netlify.app/material-ui/material-icons/
> [docs] Sync h1 with side nav label

- packages/mui-lab/src/DateRangePicker/DateRangePicker.ts
- packages/mui-lab/src/DateRangePickerDay/DateRangePickerDay.ts
- packages/mui-lab/src/DesktopDateRangePicker/DesktopDateRangePicker.ts
- packages/mui-lab/src/MobileDateRangePicker/MobileDateRangePicker.ts
- packages/mui-lab/src/StaticDateRangePicker/StaticDateRangePicker.ts
In #32048 we renamed the blog post URL without checking if it was linked hence this bug: https://codesandbox.io/s/basicdaterangepicker-material-demo-forked-sqpul5
I noticed the issue in doing a review on an MUI Store author template submission. Considering it's a blog post, the URL is never supposed to change, so I assume that we don't need to rely on `/r/*`, e.g.
https://github.com/mui/material-ui/blob/09a50b290888a02d9da8461b4b9d940f62879552/docs/public/_redirects#L13
like we do when we link docs from the source.
> [docs] Fix 404 link in the code

- packages/mui-base/src/BadgeUnstyled/BadgeUnstyled.js
- packages/mui-base/src/BadgeUnstyled/badgeUnstyledClasses.ts
- packages/mui-base/src/BadgeUnstyled/index.js
- packages/mui-material/src/Badge/Badge.js
- packages/mui-material/src/Badge/Badge.test.js
Fixed the ability to customize state classes of the Badge.
Closes #32177
> [Badge] Fix customization of classes

- docs/data/base/components/form-control/form-control.md
This PR implements the style guide on the `FormControlUnstyled` doc. This one is pretty straightforward—I don't see any clarifications needed.
https://deploy-preview-32309--material-ui.netlify.app/base/react-form-control/
> [docs] Base Form Control style revisions and final review

- docs/pages/experiments/joy/avatar.tsx
- docs/pages/experiments/joy/chip.tsx
- docs/pages/experiments/joy/components.tsx
- docs/pages/experiments/joy/svg-icon.tsx
- packages/mui-joy/src/Avatar/Avatar.tsx
- packages/mui-joy/src/Avatar/AvatarProps.ts
- packages/mui-joy/src/Avatar/avatarClasses.ts
- packages/mui-joy/src/AvatarGroup/AvatarGroup.tsx
- packages/mui-joy/src/Chip/Chip.spec.tsx
- packages/mui-joy/src/Chip/Chip.test.js
- packages/mui-joy/src/Chip/Chip.tsx
- packages/mui-joy/src/Chip/ChipColorContext.ts
- packages/mui-joy/src/Chip/ChipContext.ts
- packages/mui-joy/src/Chip/ChipProps.ts
- packages/mui-joy/src/Chip/chipClasses.ts
- packages/mui-joy/src/Chip/index.ts
- packages/mui-joy/src/ChipDelete/ChipDelete.test.js
- packages/mui-joy/src/ChipDelete/ChipDelete.tsx
- packages/mui-joy/src/ChipDelete/ChipDeleteProps.ts
- packages/mui-joy/src/ChipDelete/chipDeleteClasses.ts
- packages/mui-joy/src/ChipDelete/index.ts
- packages/mui-joy/src/index.ts
- packages/mui-joy/src/internal/svg-icons/Close.tsx
- packages/mui-joy/src/styles/components.d.ts
- packages/mui-joy/src/styles/defaultTheme.ts
**This PR includes:**
- correcting typos in Joy `SvgIcon` demo / Joy `Avatar` demo / Joy `Avatar` API code
- addition of Joy `Chip` component
- tests for Joy `Chip` component
**Props**: `startDecorator`, `endDecorator`, `color`, `size`, `variant`, `disabled`
**Default values**:
- `color`: `primary`
- `size`: `md`
- `variant`: `contained`
- `disabled`: `false`
I removed `onDelete`, `icon`, `avatar`, `label`, `clickable` and `deleteIcon` props and added `startDecorator` / `endDecorator` following up with this [discussion](https://github.com/mui/material-ui/pull/31873#discussion_r830919915)
Preview: https://deploy-preview-31983--material-ui.netlify.app/experiments/joy/chip/
**Lines of code comparison**
|                          | Material   | Joy        | % change   |
| …
> [Joy] Add `Chip` component

- docs/data/material/components/radio-buttons/FormControlLabelPlacement.js
- docs/data/material/components/radio-buttons/FormControlLabelPlacement.tsx
Edit label typo in code example to mutch markup.
[react-radio-button example](https://mui.com/material-ui/react-radio-button/#label-placement)
✍️ `<FormLabel id="demo-form-control-label-placement">labelPlacement</FormLabel>`
[checkboxes example](https://mui.com/material-ui/react-checkbox/#label-placement)
👍 `<FormLabel component="legend">Label placement</FormLabel>`
> [docs] Change label on `FormControlLabelPlacement`

- packages/mui-material/src/DialogTitle/DialogTitle.d.ts
- packages/mui-material/src/DialogTitle/DialogTitle.spec.tsx
Closes https://github.com/mui/material-ui/issues/32369
Before:
- [Codesandbox](https://codesandbox.io/s/loving-sound-koxqm3)
After:
- [Codesandbox](https://codesandbox.io/s/cold-wave-upqg21)
> [Dialog] The `component` prop is not available in `DialogTitleProps`

- docs/pages/experiments/joy/radio.tsx
- packages/mui-joy/src/Button/Button.tsx
- packages/mui-joy/src/Checkbox/Checkbox.tsx
- packages/mui-joy/src/Chip/Chip.tsx
- packages/mui-joy/src/ChipDelete/ChipDelete.tsx
- packages/mui-joy/src/IconButton/IconButton.tsx
- packages/mui-joy/src/Link/Link.tsx
- packages/mui-joy/src/ListItemButton/ListItemButton.tsx
- packages/mui-joy/src/Radio/Radio.tsx
- packages/mui-joy/src/Sheet/Sheet.tsx
- packages/mui-joy/src/Switch/Switch.tsx
- packages/mui-joy/src/styles/CssVarsProvider.test.tsx
- packages/mui-joy/src/styles/defaultTheme.ts
- packages/mui-joy/src/styles/styled.spec.tsx
`theme.focus` can be used with pseudo-elements as well. This PR adds `theme.focus.selector` and fix all the component focus to be:
```js
{
[theme.focus.selector]: theme.focus.default,
}
// for pseudo element
{
[theme.focus.selector]: {
'&::after': theme.focus.default,
}
}
```
> [Joy] Improve theme focus to be more flexible

- docs/src/layouts/AppFooter.tsx
- docs/src/route.ts
Follow up on the email you sent @oliviertassinari. 
Might as well wait for you to finish there so we can merge this one.
https://deploy-preview-32080--material-ui.netlify.app/
---
Olivier's Edit: needed for https://support.google.com/cloud/answer/9110914
> The Privacy Policy must be visible to users, hosted within the domain of your website, and linked from the OAuth consent screen on the Google API Console.
We need to use Google OAuth for Google Spreadsheet integration with MUI Toolpad.
> [website] Add privacy policy link to website's footer

- docs/src/modules/components/AppNavDrawerItem.js
This PR is easier to review without whitespace: https://github.com/mui/material-ui/pull/32324/files?diff=unified&w=1
---
Add `@media (hover: none)` to fix the style on mobile. See how the nav item keeps the hover style even after I remove the finger. This is wrong, to **always** add `@media (hover: none)`. 
**Before**
https://user-images.githubusercontent.com/3165635/163673288-060e495d-9fd7-4a2c-9371-6f291ca0d915.mp4
**After**
https://deploy-preview-32324--material-ui.netlify.app/material-ui/getting-started/installation/
> [docs] Fix sidenav mobile color

- docs/data/system/the-sx-prop/the-sx-prop.md
- docs/src/components/pricing/FAQ.tsx
- packages/mui-system/src/Box/Box.spec.tsx
- packages/mui-system/src/styleFunctionSx/styleFunctionSx.d.ts
Fix of: [this](https://mui.com/system/the-sx-prop/#fill-callback-gives-theme-type-as-any)
Readonly array does not have properties such as fill, push, etc... So on this way we can safely replace Array with ReadonlyArray and our problem will disappear.
> [system] Fix prop types when the `fill` CSS property is used

- docs/data/system/flexbox/AlignContent.js
- docs/data/system/flexbox/AlignItems.js
- docs/data/system/flexbox/AlignSelf.js
- docs/data/system/flexbox/FlexDirection.js
- docs/data/system/flexbox/FlexGrow.js
- docs/data/system/flexbox/FlexShrink.js
- docs/data/system/flexbox/FlexWrap.js
- docs/data/system/flexbox/JustifyContent.js
- docs/data/system/flexbox/Order.js
- docs/data/system/grid/Gap.js
- docs/data/system/grid/GridAutoColumns.js
- docs/data/system/grid/GridAutoFlow.js
- docs/data/system/grid/GridAutoRows.js
- docs/data/system/grid/GridTemplateColumns.js
- docs/data/system/grid/GridTemplateRows.js
- docs/data/system/grid/RowAndColumnGap.js
- packages/mui-joy/src/Box/Box.tsx
- packages/mui-joy/src/Box/BoxProps.ts
- packages/mui-material/src/Box/Box.d.ts
- packages/mui-material/src/Box/Box.js
- packages/mui-system/src/Box/Box.d.ts
- packages/mui-system/src/Box/Box.js
- packages/typescript-to-proptypes/src/injector.ts
Follow up on https://github.com/mui/material-ui/pull/32295. I've realized after merging that the `typescript-to-proptypes` is an inhouse dependency that we can alter :)
We now have full support for generating prop types out of the `@mui/system` components.
> [core] Update the proptypes scripts to support components in @mui/system

- packages/mui-codemod/src/v5.0.0/theme-spacing.js
- packages/mui-codemod/src/v5.0.0/theme-spacing.test/actual.js
- packages/mui-codemod/src/v5.0.0/theme-spacing.test/expected.js
Scenario can happen (and did occur in my app) with long lines due to `prettier` behavior
> [codemod] Allow for line breaks within theme.spacing parentheses

- docs/next.config.js
- docs/pages/_app.js
Preview with the fix: https://deploy-preview-32399--material-ui.netlify.app/material-ui/getting-started/installation/
Preview to test the bug: https://deploy-preview-32458--material-ui.netlify.app/material-ui/getting-started/installation/
My cellphone is in Portuguese. When I open any deploy preview, it tries to redirect me to the translated page, but only the English language is included in the preview, so I see a 404 page. This PR disables the redirect for previews. To test the fix, you can add the Portuguese language to a browser and open the link above. In this PR it won't redirect, but with any other preview it should display a 404 error. Once approved I'll also fix this in MUI X.
> [docs] Don't redirect on deploy preview

- docs/data/base/components/popper/popper.md
This PR reviews the Base `PopperUnstyled` document. The current version is mostly copypasta from the Material UI doc, so I did a fair bit of rewriting to make it a proper standalone piece. The "Features" section felt more like a list of random details, so I reworked it and dispersed those details throughout the doc.
The earlier version mentions transitions and links to a section that doesn't exist—looks like this was pulled directly from the Material UI doc. So I grabbed the text about transitions from that piece and added it here. I'm thinking we should probably add a Base version of the corresponding demo as well.
> [docs] Base Popper style revisions and final review

- packages/mui-codemod/src/v5.0.0/theme-breakpoints.js
- packages/mui-codemod/src/v5.0.0/theme-breakpoints.test/actual.js
- packages/mui-codemod/src/v5.0.0/theme-breakpoints.test/expected.js
The codemod was previously changing numeric values to `undefined`
> [codemod] Leave numeric arguments to breakpoints functions unchanged

- packages/mui-material/src/FilledInput/FilledInput.js
- packages/mui-material/src/FilledInput/FilledInput.test.js
Closes https://github.com/mui/material-ui/issues/32256
Problem:
- Explicitly setting `color` prop to `undefined` leads to crash in `FilledInput`
```jsx
<FilledInput color={undefined} // Fixed "❌ TypeError: Cannot read properties of undefined (reading 'main')"/>
```
Before:
- [Code sandbox](https://codesandbox.io/s/basictextfields-material-demo-forked-10zp1n?file=/demo.tsx)
After:
- [Code sandbox](https://codesandbox.io/s/basictextfields-material-demo-forked-5iox88?file=/demo.tsx)
> [FilledInput] Fix type error from undefined `color`

- packages/mui-material/src/locale/index.ts
Fixed a typo in the csCZ translation of Pagination component.
> [l10n] Fix typo in csCZ translation of Pagination component

- docs/packages/markdown/parseMarkdown.js
**Before**
**After**
Why: https://backlinko.com/nofollow-link
> [docs] Update the list of external domains

- docs/pages/experiments/material-ui/bottom-navigation.tsx
- packages/mui-material/src/BottomNavigation/BottomNavigation.js
- packages/mui-material/src/BottomNavigationAction/BottomNavigationAction.js
Preview: https://deploy-preview-32517--material-ui.netlify.app/experiments/material-ui/bottom-navigation/
> [BottomNavigation] Add support for CSS variables

- packages/mui-material/src/Tabs/Tabs.d.ts
- packages/mui-material/src/Tabs/Tabs.spec.tsx
closes #32490
Adds `sx` prop to `TabIndicatorProps` type
> [Tabs] Fix `TabIndicatorProps` prop missing `sx` prop

- docs/pages/experiments/material-ui/accordion.tsx
- packages/mui-material/src/Accordion/Accordion.js
- packages/mui-material/src/AccordionSummary/AccordionSummary.js
One of #32049 
**Preview:** https://deploy-preview-32542--material-ui.netlify.app/experiments/material-ui/accordion/
If you inspect the preview docs, the `AccordionSummary` classNames won't change as expected but `Accordion` classNames will change because CSS variables is not yet supported in `Paper` component from which the `Accordion` is built.
> [Accordion] Add support for CSS variables

- yarn.lock
Updated html-tokenizer that depended on vulnerable version of minimist.
It wasn't picked by renovate as it's only a transitive dependency.
> [core] Update minimist to fix security vulnerability

- docs/pages/experiments/material-ui/tabs.tsx
- packages/mui-material/src/Tab/Tab.js
- packages/mui-material/src/Tabs/Tabs.js
One of #32049 
**Preview:** https://deploy-preview-32547--material-ui.netlify.app/experiments/material-ui/tabs/
> [Tabs] Add support for CSS variables

- docs/src/modules/utils/helpers.test.js
- docs/src/modules/utils/helpers.ts
In X repo, we would like to use in demonstrations the following imports to specify to codesanbox that the 'exceljs' library is required for this specific demo
```js
import 'exceljs'
```
Reading `m[2]` throw an error and block codesandbox generation, because the regexp matching returns the following array
```js
import 'exceljs' // => ["import 'exceljs'", 'exceljs', undefined]
import {} from 'exceljs' // => ["import 'exceljs'", undefined, 'exceljs']
```
> [docs] Allows to use `import '<library name>'` in demonstrations

- docs/pages/experiments/material-ui/icon-button.tsx
- packages/mui-material/src/IconButton/IconButton.js
Preview: https://deploy-preview-32590--material-ui.netlify.app/experiments/material-ui/icon-button/
> [IconButton] Add support for CSS variables

- docs/pages/experiments/material-ui/form-control-label.tsx
- packages/mui-material/src/FormControlLabel/FormControlLabel.js
One of #32049 
Preview: https://deploy-preview-32588--material-ui.netlify.app/experiments/material-ui/form-control-label/
@mui/core
> [FormControlLabel] Add support for CSS variables

- docs/pages/experiments/material-ui/list-item.tsx
- packages/mui-material/src/ListItem/ListItem.js
One of #32049
(I'm not sure if this at reference is working because it doesn't show as a link)
> [ListItem] Add support for CSS variables

- docs/pages/experiments/material-ui/image-list-item-bar.tsx
- packages/mui-material/src/ImageListItemBar/ImageListItemBar.js
Preview: https://deploy-preview-32578--material-ui.netlify.app/experiments/material-ui/card-action-area/
> [ImageListItemBar] Add support for CSS variables

- docs/data/base/components/button/UseButton.js
- docs/data/base/components/button/UseButton.tsx
- docs/data/base/components/button/button.md
- docs/data/base/components/menu/UseMenu.js
- docs/data/base/components/menu/UseMenu.tsx
- docs/pages/base/api/button-unstyled.json
- docs/translations/api-docs/button-unstyled/button-unstyled.json
- packages/mui-base/src/ButtonUnstyled/ButtonUnstyled.tsx
- packages/mui-base/src/ButtonUnstyled/useButton.test.tsx
- packages/mui-base/src/ButtonUnstyled/useButton.ts
- packages/mui-base/src/ButtonUnstyled/useButton.types.ts
- packages/mui-base/src/MenuItemUnstyled/MenuItemUnstyled.tsx
- packages/mui-base/src/MenuItemUnstyled/useMenuItem.ts
- packages/mui-base/src/MenuItemUnstyled/useMenuItem.types.ts
- packages/mui-base/src/MultiSelectUnstyled/MultiSelectUnstyled.tsx
- packages/mui-base/src/SelectUnstyled/SelectUnstyled.tsx
- packages/mui-base/src/SelectUnstyled/useSelect.ts
- packages/mui-base/src/SelectUnstyled/useSelect.types.ts
- packages/mui-joy/src/Button/Button.tsx
- packages/mui-joy/src/Chip/Chip.tsx
- packages/mui-joy/src/ChipDelete/ChipDelete.tsx
- packages/mui-joy/src/IconButton/IconButton.tsx
- packages/mui-joy/src/ListItemButton/ListItemButton.tsx
Fixed the detection of native elements in useButton. It should be now possible to trigger click events on ButtonUnstyled, which root is a <button> wrapped in a component.
Unfortunately, this is not unit-testable, as neither JSDOM, nor browsers trigger the click event when <kbd>Enter</kbd> or <kbd>Space</kbd> is pressed on a native button.
Also added a doc section about custom buttons not interacting with forms as their native counterparts.
Fixes #32193
---
The first commit contains the actual fix. The second is a cleanup of no longer needed `component` parameter from `useButton` (this makes it more in-line with other hooks that are not concerned about the `component` or `components`).
> [ButtonUnstyled] Fix keyboard navigation on customized elements

- docs/pages/experiments/material-ui/form-helper-text.tsx
- packages/mui-material/src/FormHelperText/FormHelperText.js
One of #32049 
**Preview:** https://deploy-preview-32596--material-ui.netlify.app/experiments/material-ui/form-helper-text/
> [FormHelperText] Add support for CSS variables

- docs/pages/experiments/material-ui/fab.tsx
- packages/mui-material/src/Fab/Fab.js
Preview: https://deploy-preview-32564--material-ui.netlify.app/experiments/material-ui/fab/
> [Fab] Add support for CSS variables

- docs/pages/experiments/material-ui/form-label.tsx
- packages/mui-material/src/FormLabel/FormLabel.js
One of #32049 
**Preview:** https://deploy-preview-32602--material-ui.netlify.app/experiments/material-ui/form-label/
cc @mui/contributors
> [FormLabel] Add support for CSS variables

- docs/pages/experiments/material-ui/table.tsx
- packages/mui-material/src/Table/Table.js
- packages/mui-material/src/TableRow/TableRow.js
Preview: https://deploy-preview-32614--material-ui.netlify.app/experiments/material-ui/table/
> [Table, TableRow] Add support for CSS variables

- docs/pages/experiments/material-ui/table-sort-label.tsx
- packages/mui-material/src/TableSortLabel/TableSortLabel.js
Add support for CSS variables for the component `TableSortLabel` component 
(#32049).
guide](https://github.com/mui/material-ui/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).
> [TableSortLabel]: Add support for CSS vars

- docs/data/base/pages.ts
- docs/translations/translations.json
This PR is a tiny fix to add a link to the MUI Base `BadgeUnstyled` document in the side nav—it appears to have been overlooked.
> [docs] Adds Badge link to Base doc nav

- docs/pages/experiments/material-ui/css-baseline.tsx
- packages/mui-material/src/CssBaseline/CssBaseline.js
Add support for CSS variables for the component API `CssBaseline` 
(#32049).`
Preview: https://deploy-preview-32618--material-ui.netlify.app/experiments/material-ui/css-baseline/
guide](https://github.com/mui/material-ui/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).
> [CssBaseline] Add support for CSS vars

- docs/pages/experiments/material-ui/toggle-btn-group.tsx
- packages/mui-material/src/ToggleButtonGroup/ToggleButtonGroup.js
Add support for css variables for the component 
`ToggleButtonGroup` (#32049).
section of the contributing guide](https://github.com/mui/material-ui/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).
Preview: https://deploy-preview-32617--material-ui.netlify.app/experiments/material-ui/toggle-btn-group/
> [ToggleButtonGroup] Add support for CSS vars

- docs/pages/experiments/material-ui/mobile-stepper.tsx
- packages/mui-material/src/MobileStepper/MobileStepper.js
Add support for CSS variables for the 
`MobileStepper` component (#32049).
of the contributing guide](https://github.com/mui/material-ui/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).
Preview: https://deploy-preview-32606--material-ui.netlify.app/experiments/material-ui/mobile-stepper/
> [MobileStepper] Add support for CSS vars

- docs/pages/experiments/material-ui/toggle-button.tsx
- packages/mui-material/src/ToggleButton/ToggleButton.js
> [ToggleButton] Add support for CSS variables

- docs/src/components/home/AdvancedShowcase.tsx
- docs/src/components/home/CoreShowcase.tsx
- docs/src/components/productCore/CoreComponents.tsx
- docs/src/components/productCore/CoreStyling.tsx
- docs/src/components/productCore/CoreTheming.tsx
- docs/src/components/productX/XDataGrid.tsx
- docs/types/docs.d.ts
Currently, the code block on marketing pages displays the copy button. We don't need the copy button on these pages. This PR specifies the `copyButtonHidden` prop to all `HighlightedCode` in marketing pages.
> [website] Remove copy button on marketing pages

- docs/src/modules/utils/CodeCopy.tsx
It is breaking the dev environment. I am not sure why this does not happen before at the time I introduced this logic. I'm merging this as soon as the CIs are green to unblock other branches that encounter the error.
> [docs] Fix copy button childNode not found

- docs/data/material/getting-started/templates/templates.md
- docs/data/material/pages.ts
- docs/src/components/home/DesignKits.tsx
- docs/src/components/home/StoreTemplatesBanner.tsx
- docs/src/components/productDesignKit/DesignKitDemo.tsx
- docs/src/components/productDesignKit/DesignKitHero.tsx
- docs/src/components/productTemplate/TemplateDemo.tsx
- docs/src/components/productTemplate/TemplateHero.tsx
- docs/src/route.ts
- docs/translations/translations.json
https://deploy-preview-32646--material-ui.netlify.app/material-ui/getting-started/installation/
Fix drop of -26% of traffic to https://mui.com/store/ by adding the sidenav menu back:
like in older versions of the docs, e.g. https://v5-0-6.mui.com/components/autocomplete/ and like in other products:
- Bootstrap https://getbootstrap.com/
- Chakra https://chakra-ui.com/guides/principles
- Tailwind CSS https://tailwindcss.com/docs/flex-basis
It even makes me wonder if we couldn't give the templates in the store more emphasis.
I have found this regression thanks to the events that we send on clicks. ["sidenav"](https://analytics.google.com/analytics/web/#/report/content-event-events/a106598593w159022482p160376982/_u.date00=20220101&_u.date01=20220131&explorer-segmentExplorer.segmentId=analytics …
> [website] Optimize conversion to store

- packages/mui-material/src/Link/Link.js
- test/regressions/fixtures/Link/LinkColor.js
close #32574
**Before**: https://codesandbox.io/s/infallible-fog-n15fl3?file=/src/Demo.tsx
**After**: https://codesandbox.io/s/confident-sea-1kxjnj?file=/src/Demo.tsx
Changes in this PR:
- `styleOverrides` works for normal color prop (`primary`, `secondary`, ...etc)
- `sx` prop should not change the underline as stated in https://github.com/mui/material-ui/pull/32182/files#r847428212
- add more regression tests
> Argos change is expected.
**Scenarios**
```js
// ✅ v4 behavior, affect text color and underline. styleOverrides still works.
<Link />
<Link color="secondary" /> 
// ✅ v5 shorthand support, affect text color and underline. wins over styleOverrides
<Link color="primary.dark" />
<Link color="#ff5252" />
// ✅ v5 sx, affect only text color.
<Link sx={{ color: 'red' }} />
<Link sx={{ …
```
> [Link] Fix style overrides color prop

- packages/mui-base/src/AutocompleteUnstyled/useAutocomplete.js
- packages/mui-material/src/Autocomplete/Autocomplete.test.js
Fixes: #31083
[Code sandbox demo](https://codesandbox.io/s/tags-material-demo-forked-6msp73?file=/demo.js)
**Problem:**
The list is closed upon clicking the ArrowLeft and ArrowRight key buttons if the user wants to move the cursor on the input value text.
**Solution:**
Adding a condition before closing the listbox, in order to check if the input value is not empty or not.
> [Autocomplete] Fix keep listbox open on left/right keys when inputValue is not empty

- docs/pages/base/api/click-away-listener.json
- packages/mui-base/src/ClickAwayListener/ClickAwayListener.test.js
- packages/mui-base/src/ClickAwayListener/ClickAwayListener.tsx
I encountered this situation today where using the `ClickAwayListener` was not triggering when components are use pointer events instead of click.
Arguably if we follow the philosophy described here https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events we should always think in terms of pointer inputs rather than click inputs since `pointer` includes `click`.
I've enabled the ability to provide the `down` and `up` pointer inputs to enable such situations.
I currently an overcoming this situation in my project by casting `onPointerUp` to `any`🥲
> [ClickAwayListener] Allow pointer up/down events to event handler

- docs/src/layouts/AppFooter.tsx
In light of MUI X's Premium release, I've realized we weren't linking the Store in the footer—so there you go. Additionally, changed the "hiring" chip color to green as red was seeming a bit strange as red is usually attributed to "unavailable/error".
> [website] Add store to the footer and "hiring" chip adjustment

- docs/data/base/components/button/button.md
- docs/data/base/components/trap-focus/trap-focus.md
Added trailing slash to links to prevent redirects.
https://app.ahrefs.com/site-audit/3524616/11/data-explorer?columns=pageRating%2Curl%2Ctraffic%2ChttpCode%2CredirectChainUrls%2CisRedirectLoop%2CincomingAllLinks%2CincomingRedirect%2Corigin&filterCollapsed=true&filterId=808b08e88c934ee19e04fdec4ed87a5a&issueId=c64d12c1-d0f4-11e7-8ed1-001e67ed4656&sorting=-pageRating
> [docs] Correct links to prevent 301 redirects

- docs/src/modules/components/Demo.js
- docs/src/modules/components/MarkdownDocs.js
From #32576, `React.Fragment` only accepts `key` and `children`.
> [docs] Fix warning mode pass to `React.Fragment`

- examples/remix-with-typescript/tsconfig.json
Added required TS config values to the Remix example as it was failing without them (as per https://github.com/mui/material-ui/pull/32506#pullrequestreview-962953949)
> [examples] Update remix example's tsconfig with required values

- docs/translations/api-docs/autocomplete/autocomplete.json
- packages/mui-material/src/Autocomplete/Autocomplete.d.ts
- packages/mui-material/src/Autocomplete/Autocomplete.js
To be able to access e.g. getOptionLabel() inside renderTags()
Fixes #32548
> [Autocomplete] Forward props to renderTags()

- docs/src/modules/components/AppLayoutDocs.js
In MUI X I've noticed that some pages have horizontal scroll on smaller screens, for example:
https://mui.com/x/react-data-grid/state/
https://user-images.githubusercontent.com/13808724/167820544-5cc4250b-5c90-4431-841d-940390956da7.mov
I've tracked this down to this:
https://github.com/mui/material-ui/blob/7028a342fe7ab097d3264cc4d42e028b37b71ced/docs/src/modules/components/AppLayoutDocs.js#L39-L57
Here you can see that `!disableToc` styles are nested inside `!disableAd` styles, so they are not applied unless `disableAd=false`. The page in MUI X I've linked above has `disableAd=true`, and missing TOC-related style cause horizontal scroll.
This seems to be a regression from [`bf225c3` (#27150)](https://github.com/mui/material-ui/pull/27150/commits/bf225c31ccae201676e8cc382a3aa381398301f6#d …
> [docs] Fix TOC-related styles not being applied when disableAd=true

- packages/mui-material/src/styles/createMixins.d.ts
- packages/mui-material/src/styles/createMixins.js
- packages/mui-material/src/styles/createMixins.test.js
- packages/mui-material/src/styles/createTheme.js
The `spacing` parameter is not being used in the method definition. 
I hope this is not a breaking change.
> [core] Remove unnecessary `spacing` parameter from `createMixins` method

- docs/src/MuiPage.ts
- docs/src/pages.ts
In MUI X, we want to use `MuiPage` interface, but since we have `noImplicitAny` enabled, TS compiler throws the following error:
```sh
../node_modules/@mui/monorepo/docs/src/pages.ts(1,22): error TS7016: Could not find a declaration file for module './pagesApi'.
```
To solve this issue, I've extracted interfaces to a separate file, so that we can use them in MUI X without issues.
`pages.ts` still exports those interfaces to avoid changes in other parts of the codebase.
I've also updated `scopePathnames` description to mention that it can use partial pathname (see https://github.com/mui/mui-x/pull/4816)
> [core] Extract `MuiPage` interface to separate file

- packages/mui-material/src/Badge/Badge.d.ts
- packages/mui-material/src/Badge/Badge.spec.tsx
- packages/mui-material/src/Badge/badgeClasses.ts
- packages/mui-material/src/styles/createTheme.spec.ts
Fixes #32699
Regression from #31974
Basically `BadgeClasses` should contain all the CSS classes.
> [Badge] Fix TypeScript error when adding style overrides for Badge

- docs/package.json
Pointed out by @cherniavskii in https://github.com/mui/material-ui/pull/32576#discussion_r870693822
> [docs] Add joy to docs package.json

- packages/mui-base/src/OptionGroupUnstyled/OptionGroupUnstyled.spec.tsx
- packages/mui-base/src/OptionGroupUnstyled/OptionGroupUnstyled.tsx
- packages/mui-base/src/OptionGroupUnstyled/OptionGroupUnstyled.types.ts
- packages/mui-base/src/OptionGroupUnstyled/index.ts
- packages/mui-base/src/OptionUnstyled/OptionUnstyled.spec.tsx
- packages/mui-base/src/OptionUnstyled/OptionUnstyled.test.tsx
- packages/mui-base/src/OptionUnstyled/OptionUnstyled.tsx
- packages/mui-base/src/OptionUnstyled/OptionUnstyled.types.ts
- packages/mui-base/src/OptionUnstyled/index.ts
- packages/mui-base/src/SelectUnstyled/SelectUnstyledContext.ts
Defined types for slots of OptionUnstyled and OptionGroupUnstyled
> [OptionUnstyled] Define ownerState and slot props' types

- docs/data/material/components/menus/ContextMenu.js
- docs/data/material/components/menus/ContextMenu.tsx
Solve one part of https://twitter.com/rsms/status/1522583516265029633 "is the first item perfectly aligned 1px adjacent to the pointer hit pixel?" a point made by rsms. At least, it's how macOS 12, Windows 11, and Figma behave.
https://mui.com/material-ui/react-menu/#context-menu
https://deploy-preview-32661--material-ui.netlify.app/material-ui/react-menu/#context-menu
---
Does click-drag-release work properly? Nop, but it's pretty hard, maybe overkill for us 🙃. I have also seen https://react-spectrum.adobe.com/react-spectrum/Menu.html support this correctly.
--- 
**Off-topic**. @michaldudak in https://mui.com/base/react-menu/#basic-usage, I think that we will want to reconsider the demo, there are regressions from https://mui.com/material-ui/react-menu/ that would likely not fly in …
> [Menu] Fix context menu open position

- packages/mui-icons-material/package.json
- packages/mui-styled-engine-sc/package.json
- packages/mui-styled-engine/package.json
> [docs] Fix link to the material icons

- docs/data/material/customization/theme-components/theme-components.md
Fixes #32760 
Callback as a value is in the CSS class properties not in the styleOverrides key. 
In any case, I think, this particular code snippet with the following description doesn't match:
```
Each component is composed of several different parts.
These parts correspond to classes that are available to the component—see the **CSS** section of the component's API page for a detailed list.
You can use these classes inside the `styleOverrides` key to modify the corresponding parts of the component.
```
Also this sub-section seems redundant with the section below: `Overrides based on props`. 
I would propose to remove this sub-section which was added in #31997. 
Preview: https://deploy-preview-32781--material-ui.netlify.app/material-ui/customization/theme-components/#global-style-override …
> [docs] Fix wrong code snippet for overriding styles in theme with a callback value

- docs/data/material/components/autocomplete/CustomizedHook.js
- docs/data/material/components/autocomplete/CustomizedHook.tsx
- docs/data/material/components/autocomplete/GitHubLabel.js
- docs/data/material/components/autocomplete/GitHubLabel.tsx
- docs/data/material/components/autocomplete/UseAutocomplete.js
- docs/data/material/components/autocomplete/UseAutocomplete.tsx
Fixes #32563 
`data-focus` attribute was removed in #26181. So we can't select with it anymore in CSS.
**Preview:** https://deploy-preview-32757--material-ui.netlify.app/material-ui/react-autocomplete/#useautocomplete
> [docs] Update `useAutocomplete` demos to use `Mui-focused` class

- docs/data/material/guides/interoperability/interoperability.md
Hi,  
There is now [an ESLint plugin](https://docs.tss-react.dev/detecting-unused-classes) for detecting unused classes.  
This PR mentions it.  
Best regards,
> [docs] Mention the ESLint plugin for detecting unused classes

- packages/mui-material/src/ButtonBase/TouchRipple.js
According to the typescript interface of the `TouchRipple` the ref should allows to call start and stop without the `event` argument. 
```tsx
export interface TouchRippleActions {
start: (
event?: React.SyntheticEvent,
options?: StartActionOptions,
callback?: () => void,
) => void;
pulsate: (event?: React.SyntheticEvent) => void;
stop: (event?: React.SyntheticEvent, callback?: () => void) => void;
}
```
But `events` properties such as `event.type` are used in `start` and `stop` methods which makes them return an error. WHen calling `rippleRef.current.stop()`
> [TouchRipple] Allows call imperative methods without event

- packages/mui-codemod/README.md
- [ x ] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/material-ui/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).
> [docs] Fixed wrong command for the `link-underline-hover` codemod

- packages/mui-base/src/SliderUnstyled/useSlider.ts
- packages/mui-material/src/Slider/Slider.test.js
Fixes #32381 
Added `move: true` on getFingerNewValue in handleTouchEnd. Because at the 'touchEnd' the value is moved and we want to get 'previousIndex' for activeIndex. Not the 'closest'. (lines 418-422).
> [SliderUnstyled] Fix `disabledSwap` not being respected in `onChangeCommitted`

- packages/mui-material/src/styles/CssVarsProvider.test.js
- packages/mui-system/src/spacing.js
- packages/mui-system/src/style.js
Fixes https://github.com/mui/material-ui/issues/32804
> [system] Fix `borderRadius` errors when used inside `CssVarsProvider`

- packages/mui-system/src/cssVars/createCssVarsProvider.js
- test/regressions/fixtures/CssVarsProvider/DarkModeSpecificity.js
The attribute specificity generated by `CssVarsProvider` is currently the same:
```css
:root // light mode
[data-mui-color-scheme="dark"] // dark mode
```
This means stylesheet injection order matters. If I customize only the `dark` color scheme like this:
```js
<CssVarsProvider theme={{ colorSchemes: { dark: { ... }}}>
// It turns out that the theme before generated CSS variables can be:
{
colorSchemes: {
dark: {...}, // dark comes before light in the object
light: {...},
}
}
```
It creates these styles in the `head` and since both of them have the same specificity, the `:root` wins and dark mode does not work:
```html
<style>[data-mui-color-scheme="dark"] { ...variables }</style>
<style>:root { ...variables }</style> // this wins in dark mode
```
This PR increases the specificity to the …
> [system] Fix color scheme specificity

- packages/mui-material/src/styles/index.d.ts
- packages/mui-material/test/typescript/moduleAugmentation/createTheme.spec.ts
- packages/mui-material/test/typescript/moduleAugmentation/createTheme.tsconfig.json
I noticed while providing a solution to https://github.com/mui/material-ui/issues/32721 that we do not export the `Mixins` type from `@mui/material/styles`, leading to developers needing to declare module for it from a private path: `@mui/material/styles/createMixins`. 
The goal is to allow the following:
```diff
-declare module "@mui/material/styles/createMixins" {
+declare module "@mui/material/styles" {
interface Mixins {
myCustomGuttersMixin: CSSProperties;
}
}
```
> [typescript] Allow module augmentation for `Mixins`

- packages/mui-system/src/cssVars/createCssVarsProvider.js
Due to #32628, the stylesheet creation is forced to be:
```js
html[data-mui-color-scheme="dark"] { ... }
```
Other elements can't leverage the stylesheet because it is fixed to `html`. I think the better way is to make sure that the default color scheme stylesheet is injected before the rest of the color schemes (which is the change in this PR).
We have a regression test covered, so I will merge once the CIs are green. cc @mnajdova 
---
> [system] Simplify stylesheet injection logic

- docs/next.config.js
- docs/src/featureToggle.js
- docs/src/modules/components/AppNavDrawer.js
@oliviertassinari pointed out that Joy pages should appear on the master branch (https://material-ui.netlify.app/) so that we can check them out (currently, they appear only on the pull requests which is not convenient to look at).
By using the existing `staging` environment variable.
---
> [Joy] Show Joy pages on master

- docs/packages/markdown/parseMarkdown.js
- docs/src/modules/components/ApiPage.js
- docs/src/modules/components/AppLayoutDocs.js
- docs/src/modules/components/AppSearch.js
- docs/src/modules/components/MarkdownElement.js
https://deploy-preview-32844--material-ui.netlify.app/material-ui/react-autocomplete/#grouped
This change goes in the same direction as https://github.com/twbs/bootstrap/pull/30273. It's about removing this DOM node for each header:
From a browser support perspective, the use of `scroll-margin-top` seems all good: https://caniuse.com/mdn-css_properties_scroll-margin-top.
---
**Next**: I think that we should add a default value in the Typography for everybody, see https://github.com/mui/mui-store/pull/149.
For those who don't have access:
> [docs] Simplify header DOM structure

- CHANGELOG.md
- docs/data/base/getting-started/customization/customization.md
- docs/data/base/getting-started/usage/usage.md
- docs/data/material/guides/understand-mui-packages/understand-mui-packages-zh.md
- docs/data/material/guides/understand-mui-packages/understand-mui-packages.md
- docs/pages/about.tsx
- docs/pages/blog/2021.md
- docs/pages/blog/mui-core-v5.md
- docs/public/_redirects
- docs/src/pages/careers/designer.md
- packages/mui-base/README.md
- packages/mui-base/package.json
Fix a couple of recent docs navigation regressions. https://app.ahrefs.com/site-audit/3524616/13/issues
We might want to look into implementing checks in the CI so we can have a faster feedback loop. I feel that I need to make this kind of fixes too frequently.
> [docs] Fix navigation links

- docs/data/material/components/icons/icons.md
- docs/data/material/components/material-icons/material-icons.md
- docs/data/material/getting-started/installation/installation.md
- packages/mui-icons-material/README.md
https://fonts.google.com/icons now shows Material Symbols by default, instead of Material Icons. This PR fixes this regression.
Related to #32846.
https://deploy-preview-32847--material-ui.netlify.app/material-ui/material-icons/
> [docs] Fix wrong link to Material Icons

- docs/src/modules/sandbox/Dependencies.ts
- docs/src/modules/sandbox/StackBlitz.test.js
- docs/src/modules/sandbox/StackBlitz.ts
Test that we don't need this dependency. https://deploy-preview-32874--material-ui.netlify.app/material-ui/react-checkbox/
As a side note, the version of `@babel/runtime` must be compatible with the version of `@babel/plugin-transform-runtime` used. Leaving "latest" might create bugs
This is a quick follow-up on #32726 (happy that we now better support Joy & Base :)
> [core] Avoid leaking @babel/runtime

- docs/pages/careers.tsx
- docs/pages/careers/developer-experience-engineer.js
- docs/pages/careers/engineering-manager.js
- docs/pages/careers/react-engineer-core.js
- docs/pages/careers/react-engineer-x.js
- docs/src/pages/careers/ROLE_TEMPLATE.md
- docs/src/pages/careers/developer-advocate.md
- docs/src/pages/careers/developer-experience-engineer.md
- docs/src/pages/careers/engineering-manager.md
- docs/src/pages/careers/full-stack-engineer.md
- docs/src/pages/careers/people-operation-manager.md
- docs/src/pages/careers/product-engineer.md
- docs/src/pages/careers/product-manager.md
- docs/src/pages/careers/react-engineer-core.md
- docs/src/pages/careers/react-engineer-x.md
- docs/src/pages/careers/react-support-engineer.md
- docs/src/pages/careers/support-agent.md
- docs/src/pages/careers/technical-product-manager.md
https://deploy-preview-32535--material-ui.netlify.app/careers/
We can close the designer and full-stack roles, they have been filled. Now, we can open the next roles. This should be inline with the plan for 2022 https://www.notion.so/mui-org/2022-goals-f5b6e1b14da84a718802fd56a8bdbe20#ae4e882ccc1b4fc2841518c3a688212f and aligned with the hiring priorities: https://www.notion.so/mui-org/Hiring-plan-eae823b3292249829dee677b21a53f0e
- React Support Engineer: A strong engineer that loves interacting with developers, more likely to be for the X team.
- React Engineer X: To help deliver on what we promised
- React Engineer Core: this speaks for itself, the community is asking for me
We are doing something that works, the community wants more. It could also be great to have an emphasis on a11y …
> [website] Update the careers's page with the new roles

- .github/workflows/check-if-pr-has-label.yml
Tested in https://github.com/dimovi91/material-ui/pull/10, but apparently can also be tested on the PR itself :)) 
For the check, I've forked https://github.com/mheap/github-action-required-labels and added option for checking just minimum num of labels without needing to specify list of labels that should be applied.
> [core] Add CI check that the PR has label

- docs/src/modules/utils/generatePropDescription.ts
If a prop receives a function whose return has `undefined`, then `yarn docs:api` crashes with:
> TypeError: resolveType for 'UndefinedLiteral' not implemented
This can be tested applying the diff below:
```diff
diff --git a/packages/mui-material/src/Rating/Rating.d.ts b/packages/mui-material/src/Rating/Rating.d.ts
index 1eb262d4c4..704c4443f9 100644
--- a/packages/mui-material/src/Rating/Rating.d.ts
+++ b/packages/mui-material/src/Rating/Rating.d.ts
@@ -42,12 +42,12 @@ export interface RatingProps
*
* For localization purposes, you can use the provided [translations](/material-ui/guides/localization/).
* @param {number} value The rating label's value to format.
-   * @returns {string}
+   * @returns {string | undefined}
* @default function defaultLabelText(value) {
*   return `${value} …
```
> [docs] Allow function prop to return `undefined`

- packages/mui-base/src/TabUnstyled/TabUnstyled.spec.tsx
- packages/mui-base/src/TabUnstyled/TabUnstyled.tsx
- packages/mui-base/src/TabUnstyled/TabUnstyled.types.ts
- packages/mui-base/src/TabUnstyled/index.ts
- packages/mui-base/src/TabUnstyled/useTab.ts
- packages/mui-base/src/TabUnstyled/useTab.types.ts
* Defined types for TabUnstyled's ownerState, useTab, and its slots.
* Renamed types and files according to #31415
> [TabUnstyled] Define ownerState and slot props' types

- docs/pages/experiments/joy/style-guide.tsx
- packages/mui-joy/src/styles/types/theme.ts
- packages/mui-system/src/cssVars/createCssVarsProvider.js
- packages/mui-system/src/cssVars/createCssVarsProvider.test.js
- test/regressions/fixtures/CssVarsProvider/ColorSchemeSelector.js
From https://github.com/mui/material-ui/pull/32835/files#r877687572, this PR adds a simple util to prevent hard-coded style like this:
```js
styled('div')(({ theme }) => ({
[theme.getColorSchemeSelector('dark')]: {
// becomes '[data-mui-color-scheme="dark"] &'
...styles for dark mode
}
})
```
without this util, the bug appears when developers provide a custom attribute to `CssVarsProvider`:
```js
<CssVarsProvider attribute="data-company-color-scheme">
// HTML
<html data-company-color-scheme="dark">
```
Unit and regression tests are added.
---
> [system] Add `getColorSchemeSelector` util

- packages/mui-base/src/TabsUnstyled/TabsUnstyled.spec.tsx
- packages/mui-base/src/TabsUnstyled/TabsUnstyled.test.tsx
- packages/mui-base/src/TabsUnstyled/TabsUnstyled.tsx
- packages/mui-base/src/TabsUnstyled/TabsUnstyled.types.ts
- packages/mui-base/src/TabsUnstyled/index.ts
- packages/mui-base/src/TabsUnstyled/useTabs.ts
* Defined types for TabUnstyled's ownerState and its slots.
* Renamed types and files according to #31415
* Removed `getRootProps` from the `useTabs` return value as it returned an empty object.
> [TabsUnstyled] Define ownerState and slot props' types

- docs/data/joy/components/badge/NumberBadge.js
- docs/data/joy/components/badge/NumberBadge.tsx
- docs/data/joy/components/card/CardCovers.js
- docs/data/joy/components/card/CardCovers.tsx
- docs/data/joy/components/card/GradientCover.js
- docs/data/joy/components/card/GradientCover.tsx
- docs/data/joy/components/card/MediaCover.js
- docs/data/joy/components/card/MediaCover.tsx
- docs/data/joy/components/card/RowCard.js
- docs/data/joy/components/card/RowCard.tsx
- docs/pages/experiments/joy/checkbox.tsx
- docs/pages/experiments/joy/components.tsx
- docs/pages/experiments/joy/list.tsx
- docs/pages/experiments/joy/radio.tsx
- docs/pages/experiments/joy/switch.tsx
- docs/pages/experiments/joy/typography.tsx
- packages/mui-joy/src/Link/Link.spec.tsx
- packages/mui-joy/src/Link/Link.tsx
- packages/mui-joy/src/Link/LinkProps.ts
- packages/mui-joy/src/Typography/Typography.spec.tsx
- packages/mui-joy/src/Typography/Typography.tsx
- packages/mui-joy/src/Typography/TypographyProps.ts
- packages/mui-joy/src/Typography/typographyClasses.ts
Joy will follow the [approach](https://github.com/mui/material-ui/issues/32141#issuecomment-1105176854). This will give the same experience throughout the components.
**Usage**
```js
<Typography color="primary" variant="soft" /> // the combination of variant and color palette
<Link color="success" variant="soft" /> // the combination of variant and color palette
<Typography textColor="neutral.500" /> // CSS color prop, similar to `sx={{ color: 'neutral.500' }}`
<Link textColor="neutral.500" /> // CSS color prop, similar to `sx={{ color: 'neutral.500' }}`
```
---
> [Joy] use `textColor` prop for Typography and Link

- docs/data/material/components/alert/alert.md
We were implementing the toast component using Snackbar and the outlined Alert variant, but the content was bleeding through (see #32797 ). First we assumed a problem with z-index or a positioning issue but it took us some time to figure out that the outlined variants don't have a background by design.
> [docs] Add note about transparent background on the outlined Alert variant

- docs/pages/material-ui/api/input-label.json
- docs/translations/api-docs/input-label/input-label.json
- packages/mui-material/src/InputLabel/InputLabel.d.ts
- packages/mui-material/src/InputLabel/InputLabel.js
For component [`InputLabel`](https://mui.com/material-ui/api/input-label/), add missing property `size` with values `normal` (by default) and `small` to the propTypes and TypeScript types. The functionality was already implemented.
> [InputLabel] Document the `size` prop

- docs/package.json
- yarn.lock
Removes the apparently unused `address` dependency from the docs (as noted in #32678)
Closes https://github.com/mui/material-ui/pull/32678
> [website] Remove unnecessary `address` dependency

- docs/data/material/components/material-icons/synonyms.js
- docs/scripts/updateIconSynonyms.js
- package.json
- packages/mui-icons-material/scripts/download.js
Initially, I wanted to fix the search results of the query `+`. I couldn't make it happen. Instead, I have run `docs:mdicons:synonyms` but I had to clean up the output. This script is not perfect. 
**Before**
http://0.0.0.0:3000/material-ui/material-icons/
> [core] Improve icon synonyms

- packages/mui-base/test/integration/SelectUnstyled.test.tsx
@mui/system is used in a test, so it should be explicitly mentioned.
> [base] Remove @mui/system in tests

- docs/data/material/getting-started/supported-platforms/supported-platforms.md
- docs/src/pages/versions/versions.md
https://deploy-preview-32850--material-ui.netlify.app/versions/#what-doesnt-count-as-a-breaking-change
This PR does some cleanup on the page and adds a `What doesn't count as a breaking change?` section. I have kept it simple. I didn't add anything new to how we function right now, it's copied from https://reactjs.org/docs/faq-versioning.html.
The work on this PR sparked ⚡️ from https://github.com/mui/mui-store/pull/165#discussion_r874910623. Terminology-wise, I think that we should push forward with this convention: "experimental" for docs and `unstable_` for API. 
As a next step, we can consider adding to the list of what is not warranting a major:
- Types changes
- Test changes because some low-level things changed
> [docs] Add What doesn't count as a breaking change?

- docs/next.config.js
Next.js introduced another runtime when ran with React 18 (https://nextjs.org/docs/advanced-features/react-18/switchable-runtime). Even when the Edge runtime is not enabled, Next executes the config in the context of it, causing problems with our webpack externals check.
This PR adds a guard to run our checks only on Node runtime. It is backwards compatible with React 17.
> [core] Prepare Next config for React 18

- docs/src/modules/components/AppNavDrawer.js
Following up on #32657 — the name of the path has been changed to `/x/introduction/` so this needs to be updated to make the product identifier visible again in https://github.com/mui/mui-x/pull/4692.
I believe we all fully agreed on the new path name for this section, so hopefully we won't have to change it again until the main PR gets merged on the X side. At that point, we can remove the bit marked with `// TODO`, add a redirect, and scrape the Core docs for outdated links in a new PR on this side.
> [docs] Show product identifier on updated MUI X Introduction pages

- docs/data/base/components/badge/AccessibleBadges.js
- docs/data/base/components/badge/AccessibleBadges.tsx
- docs/data/base/components/badge/BadgeMax.js
- docs/data/base/components/badge/BadgeMax.tsx
- docs/data/base/components/badge/BadgeVisibility.js
- docs/data/base/components/badge/BadgeVisibility.tsx
- docs/data/base/components/badge/ShowZeroBadge.js
- docs/data/base/components/badge/ShowZeroBadge.tsx
- docs/data/base/components/badge/UnstyledBadge.js
- docs/data/base/components/badge/UnstyledBadge.tsx
The Mail icon is almost not visible in dark mode in the Base's Badge component docs. 
The `color` style is not needed because of which the SVG picks it up and applies in it's `fill: currentColor` property. 
Check the docs in both the modes:
**Before:** https://mui.com/base/react-badge/
**Now:** https://deploy-preview-32976--material-ui.netlify.app/base/react-badge/
If it looks good, I will approve the argos CI since there is difference in light mode (now it's just a bit darker `rgba(0, 0, 0, 0.7) -> rgb(0, 0, 0)`).
> [docs] Fix icon color in `BadgeUnstyled` docs

- docs/pages/base/api/table-pagination-unstyled.json
- docs/translations/api-docs/table-pagination-unstyled/table-pagination-unstyled.json
- packages/mui-base/src/TablePaginationUnstyled/TablePaginationActionsUnstyled.spec.tsx
- packages/mui-base/src/TablePaginationUnstyled/TablePaginationActionsUnstyled.tsx
- packages/mui-base/src/TablePaginationUnstyled/TablePaginationActionsUnstyled.types.ts
- packages/mui-base/src/TablePaginationUnstyled/TablePaginationUnstyled.spec.tsx
- packages/mui-base/src/TablePaginationUnstyled/TablePaginationUnstyled.tsx
- packages/mui-base/src/TablePaginationUnstyled/TablePaginationUnstyled.types.ts
- packages/mui-base/src/TablePaginationUnstyled/index.ts
Defined types for TablePaginationUnstyledownerState and its slots.
Also renamed types and files according to #31415
> [TablePaginationUnstyled] Define ownerState and slot props' types 

- packages/mui-base/src/TabsListUnstyled/TabsListUnstyled.spec.tsx
- packages/mui-base/src/TabsListUnstyled/TabsListUnstyled.tsx
- packages/mui-base/src/TabsListUnstyled/TabsListUnstyled.types.ts
- packages/mui-base/src/TabsListUnstyled/index.ts
- packages/mui-base/src/TabsListUnstyled/useTabsList.ts
- packages/mui-base/src/TabsListUnstyled/useTabsList.types.ts
* Defined types for TabsListUnstyled's ownerState, its slots, and useTabsList.
* Renamed types and files according to #31415
> [TabsListUnstyled] Define ownerState and slot props' types

- packages/mui-base/src/TabPanelUnstyled/TabPanelUnstyled.spec.tsx
- packages/mui-base/src/TabPanelUnstyled/TabPanelUnstyled.tsx
- packages/mui-base/src/TabPanelUnstyled/TabPanelUnstyled.types.ts
- packages/mui-base/src/TabPanelUnstyled/index.ts
- packages/mui-base/src/TabPanelUnstyled/useTabPanel.ts
- packages/mui-base/src/TabPanelUnstyled/useTabPanel.types.ts
* Defined types for TabPanelUnstyled's ownerState, its slots, and useTabPanel
* Renamed types and files according to #31415
> [TabPanelUnstyled] Define ownerState and slot props' types

- docs/data/material/components/app-bar/BackToTop.js
- docs/data/material/components/app-bar/BackToTop.tsx
- docs/pages/_app.js
- docs/src/modules/components/AppLayoutDocs.js
- docs/src/modules/components/BackToTop.js
- docs/src/modules/components/BackToTop.tsx
This is an attempt to iterate on https://github.com/mui/material-ui/pull/30441#issuecomment-1131540126
To compare the UX:
- https://mui.com/material-ui/getting-started/installation/
- https://deploy-preview-32896--material-ui.netlify.app/material-ui/getting-started/installation/
> [docs] Improve UX with back to top

- docs/pages/experiments/joy/checkbox.tsx
- docs/pages/experiments/joy/list.tsx
- packages/mui-joy/src/styles/CssVarsProvider.tsx
- packages/mui-material/src/styles/CssVarsProvider.js
- packages/mui-system/src/cssVars/createCssVarsProvider.d.ts
- packages/mui-system/src/cssVars/createCssVarsProvider.js
- packages/mui-system/src/cssVars/createCssVarsProvider.test.js
- packages/mui-system/src/cssVars/getInitColorSchemeScript.tsx
**Before**
Both Joy and Material UI has `<html data-mui-color-scheme="dark">` without configurable options.
**After**
Joy and Material UI and use their own prefix as a default values:
```js
// Material UI
<html data-mui-color-scheme="dark">
// Joy
<html data-joy-color-scheme="dark">
```
---
> [system] Configurable attributes for libraries

- docs/src/components/pricing/EarlyBird.tsx
- docs/src/layouts/AppHeader.tsx
- docs/src/modules/components/AppFrame.js
- docs/src/modules/components/AppLayoutDocs.js
I have just realized this as I was sharing a link to https://mui.com/blog/2021-developer-survey-results/#which-of-the-following-best-describes-your-current-job-role, the scroll is broken.
The regression is coming from #32844. `docs/src/modules/components/AppLayoutDocs.js` component adds the CSS variables but it's not used by the blog.
https://deploy-preview-32994--material-ui.netlify.app/material-ui/react-button-group/#button-variants
> [blog] Fix anchor link scroll

- packages/mui-material/src/Popover/Popover.d.ts
- packages/mui-material/src/Popover/index.js
Wondering if there's a reason why `getOffsetTop` and `getOffsetLeft` aren't exported from the index? They're actually exported from the main `Popover.js` file but not from the index or typings. Almost seems like a miss.
We've found use for these when programmatically supplying a position to the Popover component (i.e. `anchorReference: 'anchorPosition'` and `anchorPostion: { top, left }`).
To use them, we have to ts-ignore the line due to the lack of typings and import from the 4th level which is meant to be _private_.
```ts
// @ts-ignore
import { getOffsetLeft, getOffsetTop } from '@mui/material/Popover/Popover';
```
It'd be nice to have them public
```ts
import { getOffsetLeft, getOffsetTop } from '@mui/material/Popover';
```
> [Popover] Export `getOffsetTop` & `getOffsetLeft` from Popover's index and add typings

- docs/src/components/pricing/PricingTable.tsx
See https://groups.google.com/a/mui.com/g/x/c/p7BiZrd8cMU for why. It doesn't solve the root problem, but it makes it a bit clearer. https://github.com/mui/mui-store/issues/181 could help too.
https://deploy-preview-33069--material-ui.netlify.app/pricing/
> [website] Clarify the pricing a bit

- docs/data/joy/components/aspect-ratio/BasicRatio.js
- docs/data/joy/components/aspect-ratio/BasicRatio.tsx
- docs/data/joy/components/aspect-ratio/BasicRatio.tsx.preview
- docs/data/joy/components/aspect-ratio/CarouselRatio.js
- docs/data/joy/components/aspect-ratio/CarouselRatio.tsx
- docs/data/joy/components/aspect-ratio/CustomRatio.js
- docs/data/joy/components/aspect-ratio/CustomRatio.tsx
- docs/data/joy/components/aspect-ratio/CustomRatio.tsx.preview
- docs/data/joy/components/aspect-ratio/FlexRowRatio.js
- docs/data/joy/components/aspect-ratio/FlexRowRatio.tsx
- docs/data/joy/components/aspect-ratio/ListStackRatio.js
- docs/data/joy/components/aspect-ratio/ListStackRatio.tsx
- docs/data/joy/components/aspect-ratio/MediaRatio.tsx
- docs/data/joy/components/aspect-ratio/MediaRatio.tsx.preview
- docs/data/joy/components/aspect-ratio/MinMaxRatio.tsx
- docs/data/joy/components/aspect-ratio/MinMaxRatio.tsx.preview
- docs/data/joy/components/aspect-ratio/PlaceholderAspectRatio.js
- docs/data/joy/components/aspect-ratio/PlaceholderAspectRatio.tsx
- docs/data/joy/components/aspect-ratio/PlaceholderAspectRatio.tsx.preview
- docs/data/joy/components/aspect-ratio/aspect-ratio.md
- packages/mui-joy/src/AspectRatio/AspectRatio.tsx
- New demos
- placeholder
- next.js image integration
- Add typescript demos
---
> [docs] Improve aspect ratio docs and integration

- docs/notifications.json
This PR should be merged after the release of the blog post.
---
> [docs] Add notification for Joy blog post

- docs/data/base/components/input/input.md
Just a small typo I noticed while reading the docs.
**Preview:** https://deploy-preview-33077--material-ui.netlify.app/base/react-input/#multiline
> [docs] Fix a typo in `InputUnstyled` docs

- CHANGELOG.md
- docs/data/joy/customization/approaches/ButtonThemes.js
- docs/scripts/ApiBuilders/ComponentApiBuilder.ts
- docs/src/modules/components/DemoErrorBoundary.js
I have noticed this here: https://twitter.com/iamsamwalsh/status/1534315326900699140
> [docs] Fix GitHub capitalization

- packages/mui-material/src/Grow/Grow.js
Limiting Grow CSS transition bug workaround to Safari 15.4 as per https://github.com/mui/material-ui/issues/31380#issuecomment-1144515973
Preview: https://deploy-preview-32996--material-ui.netlify.app/material-ui/react-menu/#main-content
> [Grow] Limit CSS transition bug workaround to Safari 15.4 only

- packages/mui-material/src/Tabs/Tabs.js
- packages/mui-material/src/Tabs/Tabs.test.js
Currently, you're not able to scroll tabs when the container is narrow enough to have only one tab (partially) visible. This is my proposed solution, which would scroll by the width of the first visible tab in such a case.
Fixes https://github.com/mui/material-ui/issues/32748
> [Tabs] Scroll by width of the first visible tab if only one tab is partially visible

- docs/data/base/components/input/UseInput.js
- docs/data/base/components/input/UseInput.tsx
- docs/data/base/getting-started/usage/usage.md
I am working on `SnackbarUnstyled` component and thus noticed the following while reading the docs:
1. It should be `badge` props slot, not `input` in the usage section.
2. Code comment in `useInput` demo.
> [docs] Miscellaneous fixes in `MUI Base` docs

- CHANGELOG.old.md
- docs/data/base/getting-started/overview/overview.md
- docs/data/material/getting-started/faq/faq.md
- docs/data/material/getting-started/overview/overview.md
- docs/data/material/guides/content-security-policy/content-security-policy.md
- docs/data/material/guides/interoperability/interoperability.md
- docs/data/material/guides/right-to-left/right-to-left.md
- docs/data/material/guides/server-rendering/server-rendering.md
- docs/data/material/guides/understand-mui-packages/understand-mui-packages.md
- docs/data/material/migration/migration-v4/migration-v4-zh.md
- docs/data/material/migration/migration-v4/v5-style-changes.md
- docs/data/styles/advanced/advanced.md
- docs/data/styles/api/api.md
- docs/data/styles/basics/basics.md
- docs/data/system/basics/basics.md
- docs/data/system/styled/styled.md
- docs/pages/blog/2020-q3-update.md
- docs/pages/blog/2020.md
- docs/pages/blog/2021-developer-survey-results.md
- docs/pages/blog/mui-core-v5.md
- examples/nextjs-with-typescript/pages/_document.tsx
- examples/nextjs/pages/_document.js
- examples/remix-with-typescript/app/entry.server.tsx
- packages/mui-codemod/README.md
- packages/mui-lab/README.md
- packages/mui-system/src/createStyled.js
- packages/mui-system/src/styleFunctionSx/styleFunctionSx.js
- packages/mui-utils/src/elementAcceptingRef.ts
I was using https://mui.com/material-ui/getting-started/overview/ to update our G2 product:
And I notice the typo. While I was at it, I also look into batching 😁 https://github.com/emotion-js/emotion/issues/2767
> [docs] Fix typo in Material UI overview page

- docs/data/material/guides/shadow-dom/ShadowDOMDemo.js
- docs/data/material/guides/shadow-dom/ShadowDOMDemo.tsx
- docs/data/material/guides/shadow-dom/ShadowDOMDemo.tsx.preview
- docs/data/material/guides/shadow-dom/shadow-dom.md
- docs/data/material/pages.ts
- docs/pages/material-ui/guides/shadow-dom.js
- docs/translations/translations.json
Closes https://github.com/mui/mui-x/issues/5030
Closes #17473
Closes #31188
Also addresses already closed issues:
- https://github.com/mui/mui-x/issues/3381
- https://github.com/mui/mui-x/issues/3319
- https://github.com/mui/material-ui/issues/30005
Preview: https://deploy-preview-33007--material-ui.netlify.app/material-ui/guides/shadow-dom/
> [docs] Add Shadow DOM guide

- packages/mui-lab/src/CalendarPicker/CalendarPicker.tsx
- packages/mui-lab/src/CalendarPickerSkeleton/CalendarPickerSkeleton.tsx
- packages/mui-lab/src/ClockPicker/ClockPicker.tsx
- packages/mui-lab/src/DateTimePicker/DateTimePicker.tsx
- packages/mui-lab/src/DesktopDatePicker/DesktopDatePicker.tsx
- packages/mui-lab/src/DesktopDateTimePicker/DesktopDateTimePicker.tsx
- packages/mui-lab/src/DesktopTimePicker/DesktopTimePicker.tsx
- packages/mui-lab/src/LocalizationProvider/LocalizationProvider.tsx
- packages/mui-lab/src/MobileDatePicker/MobileDatePicker.tsx
- packages/mui-lab/src/MobileDateTimePicker/MobileDateTimePicker.tsx
- packages/mui-lab/src/MobileTimePicker/MobileTimePicker.tsx
- packages/mui-lab/src/MonthPicker/MonthPicker.tsx
- packages/mui-lab/src/PickersDay/PickersDay.tsx
- packages/mui-lab/src/StaticDatePicker/StaticDatePicker.tsx
- packages/mui-lab/src/StaticDateTimePicker/StaticDateTimePicker.tsx
- packages/mui-lab/src/StaticTimePicker/StaticTimePicker.tsx
- packages/mui-lab/src/TimePicker/TimePicker.tsx
- packages/mui-lab/src/YearPicker/YearPicker.tsx
So developers get less noise, so they can focus on the important messages. We didn't test #32950 in depth.
Sample test:
```jsx
import * as React from 'react';
import TextField from '@mui/material/TextField';
import { AdapterDateFns } from '@mui/x-date-pickers/AdapterDateFns';
import LocalizationProvider from '@mui/lab/LocalizationProvider';
import DatePicker from '@mui/lab/DatePicker';
export default function BasicDatePicker() {
const [value, setValue] = React.useState<Date | null>(null);
return (
<LocalizationProvider dateAdapter={AdapterDateFns}>
<DatePicker
label="Basic example"
value={value}
onChange={(newValue) => {
setValue(newValue);
}}
renderInput={(params) => <TextField {...params} />}
/>
</LocalizationProvider>
);
}
```
**Before**
**After**
> [pickers] Fix broken ref forwarding

- docs/data/joy/components/card/CardCovers.js
- docs/data/joy/components/card/CardCovers.tsx
- docs/data/joy/components/card/DribbbleShot.js
- docs/data/joy/components/card/DribbbleShot.tsx
- docs/data/joy/components/card/InstagramPost.js
- docs/data/joy/components/card/InstagramPost.tsx
- docs/data/joy/components/card/card.md
- packages/mui-joy/src/AspectRatio/AspectRatio.tsx
- packages/mui-joy/src/CardCover/CardCover.tsx
- packages/mui-joy/src/CardOverflow/CardOverflow.tsx
> [Joy] Miscellaneous card fixes 

- yarn.lock
As https://github.com/microsoft/DefinitelyTyped-tools/releases/tag/v0.0.113 (containing https://github.com/microsoft/DefinitelyTyped-tools/pull/446) has been released, we can update the vulnerable version of `tar`, closing a couple of high severity security alerts:
* https://github.com/mui/material-ui/security/dependabot/9
* https://github.com/mui/material-ui/security/dependabot/12
* https://github.com/mui/material-ui/security/dependabot/16
* https://github.com/mui/material-ui/security/dependabot/18
* https://github.com/mui/material-ui/security/dependabot/20
> [core] Update dependencies to fix security vulnerabilities

- packages/mui-lab/src/DatePicker/DatePicker.tsx
Follow up on https://github.com/mui/material-ui/pull/33107
Fixes https://github.com/mui/material-ui/issues/33085
Fixes https://github.com/mui/material-ui/issues/33080
> [lab] Fix React's `forwardRef` warning when importing from the index

- packages/mui-joy/package.json
- packages/mui-material-next/package.json
- packages/mui-material/package.json
- packages/mui-material/src/Hidden/withWidth.js
The API was removed in #26136 but we forgot to remove this dead logic. I found it thanks to https://npm.anvaka.com/#/view/2d/%2540mui%252Fmaterial, one of the few licenses that is not MIT:
> [Hidden] Remove dependency on hoist-non-react-statics

- docs/data/material/components/app-bar/DrawerAppBar.js
- docs/data/material/components/app-bar/DrawerAppBar.tsx
- docs/data/material/components/app-bar/app-bar.md
Similar to https://getbootstrap.com/docs/5.2/components/navbar/
> [docs] Add responsive AppBar with drawer

- docs/packages/markdown/parseMarkdown.js
- docs/src/modules/components/HighlightedCode.js
- docs/src/modules/utils/CodeCopy.tsx
From Matt's comment in:
- https://github.com/mui/material-ui/pull/32649#issuecomment-1120295914
- https://github.com/mui/material-ui/pull/32649#issuecomment-1120311744
**Before**
**After**
---
> [docs] Update code block copy label

- packages/mui-material/src/Tabs/Tabs.js
- packages/mui-material/src/Tabs/Tabs.test.js
In #32778, I would argue that the new logic is both more complex than it needs to be and not true to the initial intent: only scroll by the minimum amount possible so end-users can orient themselves.
cc @frankkluijtmans for review. Does it work?
> [Tabs] Increment scroll of the minimum amount possible

- docs/data/material/guides/shadow-dom/shadow-dom.md
Follow up on #33007
I've noticed that `Dialog` in Shadow DOM looses its styles, so I've updated theme overrides to include `MuiModal` there.
Before: https://codesandbox.io/s/shadow-dom-forked-9dpix9 (open dialog in Shadow DOM first to see the issue)
After: https://codesandbox.io/s/shadow-dom-forked-11gq2b
I've already updated the Codesandbox demo on the doc page: https://mui.com/material-ui/guides/shadow-dom/#demo
> [docs] Update Shadow DOM guide

- docs/data/joy/getting-started/templates/TemplateCollection.js
- docs/next.config.js
- docs/src/modules/utils/extractTemplates.test.js
- docs/src/modules/utils/extractTemplates.ts
- package.json
- yarn.lock
https://deploy-preview-33159--material-ui.netlify.app/joy-ui/getting-started/templates/
From
- https://github.com/mui/material-ui/pull/32791#discussion_r895046865
- https://github.com/mui/material-ui/pull/32791#discussion_r895045638
The raw-loader is replaced by using [asset-modules](https://webpack.js.org/guides/asset-modules/#replacing-inline-loader-syntax)
---
> [docs] Improve Joy template UX

- packages/mui-codemod/src/v5.0.0/jss-to-tss-react.js
- packages/mui-codemod/src/v5.0.0/jss-to-tss-react.test/actual-from-material-ui-core.js
- packages/mui-codemod/src/v5.0.0/jss-to-tss-react.test/actual-mixins-pattern.js
- packages/mui-codemod/src/v5.0.0/jss-to-tss-react.test/actual-todo-comments.js
- packages/mui-codemod/src/v5.0.0/jss-to-tss-react.test/expected-from-material-ui-core.js
- packages/mui-codemod/src/v5.0.0/jss-to-tss-react.test/expected-mixins-pattern.js
- packages/mui-codemod/src/v5.0.0/jss-to-tss-react.test/expected-todo-comments.js
- Preserve comments for imports that get replaced
- Preserve comments for an import that gets removed if it was the first import in the file (otherwise the comment is probably no longer relevant)
- When preserving the initial comment in a file, avoid wiping out comments for the next import in the file
This is a replacement implementation for the issue brought up in #32964.
> [codemod] Preserve comments within jss-to-tss-react

- packages/mui-lab/src/Masonry/Masonry.js
When used in React 18, there is a visible flickering in the Masonry component. See https://github.com/mui/material-ui/issues/32518's reproduction: https://codesandbox.io/s/b83ug2 (try to open/close some of the accordions and notice the flickering).
I could find one relevant issue on React's repo https://github.com/facebook/react/issues/24331 where the suggestion is to batch the states updates in the `ResizeObserver`'s callback together.
Codesandbox using the packages from this PR
- [Masonry with React 18 codesandbox](https://codesandbox.io/s/masonrywithvariableheightitems-material-demo-forked-vx4vmb?file=/demo.tsx)
- [Masonry with React 17 codesandbox](https://codesandbox.io/s/masonrywithvariableheightitems-material-demo-forked-jmjtsz?file=/index.tsx) - no regressions using React 17
Fixes …
> [Masonry] Fix flickering when used with React 18

- docs/pages/base/api/switch-unstyled.json
- docs/translations/api-docs/switch-unstyled/switch-unstyled.json
- packages/mui-base/src/ButtonUnstyled/ButtonUnstyled.tsx
- packages/mui-base/src/MenuItemUnstyled/MenuItemUnstyled.tsx
- packages/mui-base/src/MenuUnstyled/MenuUnstyled.tsx
- packages/mui-base/src/SwitchUnstyled/SwitchUnstyled.tsx
- packages/mui-base/src/utils/mergeSlotProps.ts
Prepare slots' props with the useSlotProps hook.
Also improved the consistency of the codebase by introducing the useUtilityClasses function, as in other components.
> [SwitchUnstyled] Use useSlotProps

- package.json
We're installing the workspace root as a package in MUI X and in Toolpad. Getting too many conflicting dependency issues due to package hoisting and the webpack aliases. Would like to be able to experiment with pnpm as a package manager for Toolpad as that will enable us a non-hoisted setup without sacrificing install size/time. 
pnpm currently errors when trying to install unnamed packages.
> Add name to workspace root package.json

- docs/pages/careers/fullstack-engineer.js
- docs/pages/careers/people-operations-manager.js
- docs/pages/careers/product-engineer.js
- docs/pages/careers/react-engineer-core.js
- docs/pages/careers/react-engineer-x.js
- docs/pages/careers/react-support-engineer.js
- docs/pages/careers/support-agent.js
- docs/pages/company/contact.js
- docs/public/_redirects
- docs/src/modules/components/TopLayoutCareers.js
I'm fixing https://search.google.com/search-console/index?resource_id=sc-domain%3Amui.com. There are currently 3,703 URLs that are linked on external domains, that we used to have pages against, etc. that Google is aware of and tries to index. In reality, the number of real 404 pages we have should be in the order of 300, an order of magnitude less. For example: older open jobs that are now closed.
One example a bug this fix:
- https://mui.com/api/portal/
- https://deploy-preview-33206--material-ui.netlify.app/api/portal/
> [docs] Fix 404 from old URLs we forgot to redirect

- docs/next.config.js
It was added in #30716. Same as https://github.com/mui/mui-x/pull/5282. I have found this doing a quick review on something unrelated.
> [core] Remove dead code

- packages/mui-base/src/ModalUnstyled/ModalManager.test.js
- packages/mui-base/src/ModalUnstyled/ModalManager.ts
- test/utils/createDOM.js
https://github.com/mui/material-ui/issues/17473#issuecomment-1156251054
If you set a modal's container to an element inside a shadow DOM, MUI will try to lock scrolling on the container, rather than document.body.
This locks document.body, only in the case where the modal container's immediate parent is the shadow root. This works for the example in [the guide](https://mui.com/material-ui/guides/shadow-dom/), where the modal container `shadowRootElement` is a child of `shadowContainer`.
> [ModalManager] Lock body scroll when container is inside shadow DOM

- docs/data/material/components/box/box.md
This PR is to fix https://github.com/mui/material-ui/issues/33062 updated the internal link in the Box page
> [docs] Fix internal link in Box page

- packages/mui-system/src/cssVars/createCssVarsProvider.js
- packages/mui-system/src/cssVars/getInitColorSchemeScript.tsx
The `enableColorScheme` option did not pass to `getInitColorSchemeScript`. By adding this option, the script attaches the [color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme) before the application is rendered on the screen.
Next step: I will add a script to minimize via [terser](https://terser.org/docs/cli-usage).
---
> [system] Add enableColorScheme option to getInitColorSchemeScript

- docs/src/components/header/HeaderNavBar.tsx
The problem was first surfaced in https://github.com/mui/material-ui/pull/33125#issuecomment-1154980592:
> I can never go to the MUI Base and MUI System docs, sometimes can't go to the Joy UI docs. See the video for why:
https://user-images.githubusercontent.com/3165635/173550936-4dd83683-982b-48d8-84ae-08542ecf755c.mp4
I have implemented the solution suggested in https://github.com/mui/material-ui/pull/33125#issuecomment-1155178214. I didn't try https://bjk5.com/post/44698559168/breaking-down-amazons-mega-dropdown as it feels overkill.
I can reproduce the same UX problem on https://stripe.com/en-fr and https://www.radix-ui.com/docs/primitives/components/navigation-menu we are a taking a step ahead :).
Preview: https://deploy-preview-33203--material-ui.netlify.app/
> [website] Fix navigation menu close behavior

- packages/mui-base/src/FormControlUnstyled/FormControlUnstyled.spec.tsx
- packages/mui-base/src/InputUnstyled/useInput.ts
- packages/mui-base/src/MenuUnstyled/useMenu.ts
- packages/mui-base/src/MultiSelectUnstyled/MultiSelectUnstyled.types.ts
- packages/mui-base/src/SelectUnstyled/SelectUnstyled.types.ts
- packages/mui-base/src/TabsUnstyled/TabsUnstyled.types.ts
- packages/mui-base/src/TabsUnstyled/useTabs.ts
Extracting the type changes related to base from https://github.com/mui/material-ui/pull/33196 (this will serve as a proof that they work with the older version of TypeScript & React's types)
> [base] Improve some types

- packages/mui-material/src/Tabs/Tabs.js
Fixes https://github.com/mui/material-ui/issues/33276 (the last `ResizeObserver` handler called when Suspense replaces the component with the fallback had null for the refs, so we need to add this check before invoking any code that may access some of the refs).
Similar to https://github.com/mui/material-ui/pull/33238
> [Tabs] Fix crash when used with React 18 & Suspense

- docs/data/material/guides/understand-mui-packages/understand-mui-packages.md
As Material UI does not reexport most of the Base components anymore, the docs need to be updated.
> [docs] Remove a note about Base components being reexported from Material UI

- packages/mui-base/src/FormControlUnstyled/FormControlUnstyled.tsx
- packages/mui-base/src/InputUnstyled/InputUnstyled.types.ts
- packages/mui-base/src/SwitchUnstyled/SwitchUnstyled.types.ts
- packages/mui-base/src/utils/appendOwnerState.spec.tsx
- packages/mui-base/src/utils/appendOwnerState.ts
- packages/mui-base/src/utils/useSlotProps.test.tsx
- packages/mui-base/src/utils/useSlotProps.ts
Make useSlotProps (and the underlying appendOwnerState) aware of the type of element
on which the props should be applied. Based on this, ownerState will either be present
or undefined in the resulting type.
> [Base] Improve the return type of useSlotProps

- docs/src/modules/brandingTheme.ts
- docs/src/modules/components/JoyUsageDemo.tsx
- docs/src/modules/components/MarkdownElement.js
Fix the scroll position in https://mui.com/careers/#open-roles. This fix is moving one step toward making the configuration a global one. Maybe even to consider as part of the default design system in v6.
I found this bug while I was working on adding a link to our job board from https://angel.co/company/mui/jobs.
- https://deploy-preview-33215--material-ui.netlify.app/material-ui/react-radio-button/#color
- https://deploy-preview-33215--material-ui.netlify.app/careers/#open-roles
> [website] Fix the scroll-top for all the website

- packages/mui-base/src/BadgeUnstyled/BadgeUnstyled.types.ts
@michaldudak's #33176 introduced changes that moved some `BadgeUnstyled` props out of the public `BadgeUnstyledTypeMap` interface, and into a new _private_ `BadgeUnstyledOwnProps` interface.
This causes a typescript error for consumers who try to extend from `BadgeProps` or `BadgeUnstyledProps` in a library that has `declaration: true` set in their tsconfig. The error occurs because the typescript compiler is unable to determine the exact shape of the custom interface / type because it does not know the shape of `BadgeUnstyledOwnProps`:
```tsx
import {
Badge,
BadgeProps,
BadgeTypeMap
} from "@mui/material";
export type CustomBadgeProps<
D extends React.ElementType = BadgeTypeMap['defaultComponent'],
P = unknown
> = BadgeProps<D, P> & {
/* some custom props …
```
> [BadgeUnstyled] Export BadgeUnstyledOwnProps interface to fix typescript compiler error

- docs/pages/material-ui/api/autocomplete.json
- packages/mui-material/src/Autocomplete/Autocomplete.d.ts
- packages/mui-material/src/Autocomplete/Autocomplete.js
- packages/mui-material/src/Autocomplete/Autocomplete.spec.tsx
- packages/mui-material/src/Autocomplete/Autocomplete.test.js
> [Autocomplete] Extend `componentsProps` to include `popper` and `popupIndicator` slots

- docs/data/joy/components/checkbox/ExampleFilterMemberCheckbox.js
- docs/data/joy/components/checkbox/ExampleFilterStatusCheckbox.js
- docs/data/joy/components/checkbox/checkbox.md
- docs/data/joy/components/radio/ControlledRadioButtonsGroup.js
- docs/data/joy/components/radio/ExamplePaymentChannels.js
- docs/data/joy/components/radio/ExampleProductAttributes.js
- docs/data/joy/components/radio/ExampleRadioPosition.js
- docs/data/joy/components/radio/IconlessRadio.js
- docs/data/joy/components/radio/IconsRadio.js
- docs/data/joy/components/radio/OverlayRadio.js
- docs/data/joy/components/radio/RadioButtons.js
- docs/data/joy/components/radio/RadioButtonsGroup.js
- docs/data/joy/components/radio/RadioFocus.js
- docs/data/joy/components/radio/RadioPositionEnd.js
- docs/data/joy/components/radio/RadioUsage.js
- docs/data/joy/components/radio/radio.md
- docs/data/joy/pages.ts
- docs/pages/joy-ui/react-radio-button.js
- packages/mui-joy/src/ListItem/ListItem.tsx
- packages/mui-joy/src/Radio/Radio.tsx
- packages/mui-joy/src/RadioGroup/RadioGroup.tsx
- packages/mui-joy/src/RadioGroup/RadioGroupContext.ts
- packages/mui-joy/src/RadioGroup/RadioGroupProps.ts
- packages/mui-joy/src/Sheet/Sheet.tsx
**Preview**: https://deploy-preview-33254--material-ui.netlify.app/joy-ui/react-radio-button/
---
> [Joy] Add radio button documentation

- packages/mui-styled-engine/package.json
The TypeScript declaration files for `@mui/styled-engine` import from `csstype`, so `csstype` should be added as a dependency of `@mui/styled-engine`.
```
TS2307: Cannot find module 'csstype' or its corresponding type declarations.
> 1 | import * as CSS from 'csstype';
|                      ^^^^^^^^^
2 | import { StyledComponent, StyledOptions } from '@emotion/styled';
3 | import { PropsOf } from '@emotion/react';
4 |
```
> [styled-engine] Add missing type dependency on csstype

- docs/pages/material-ui/api/select.json
- packages/mui-material/src/Select/Select.d.ts
- packages/mui-material/src/Select/Select.js
Include the empty string `''` as a valid value for the `value` prop of the `Select` component, including when the component's inferred parametric type does not overlap with `string`.
This is necessary because the docs state that `''` is a symbol for "no selection". `undefined` is *not* a valid substitute because this is a symbol for "uncontrolled component" and using it in this way will trigger a warning. Therefore `''` must always be a valid option no matter the type of the available selections.
> [Select] Annotate empty string as valid value prop

- .github/workflows/ci.yml
- package.json
- packages/mui-material/src/styles/CssVarsProvider.tsx
- packages/mui-system/src/cssVars/index.ts
- scripts/validateTypescriptDeclarations.ts
Exports system types used in Material UI. Without these, the Typescript compiler throws errors in built .d.ts files.
Fixes #33321
> [system] Export required types

- docs/public/_redirects
Related to https://github.com/mui/mui-toolpad/pull/542, the goal is to get us one step closer to displaying https://deploy-preview-542--mui-toolpad-docs.netlify.app/toolpad/getting-started/ in https://mui.com/toolpad/getting-started/.
Preview: https://deploy-preview-33287--material-ui.netlify.app/toolpad/
> [website] Link MUI Toolpad in mui.com

- docs/data/joy/customization/approaches/ButtonThemes.js
- docs/data/joy/customization/theme-tokens/BootstrapVariantTokens.js
- docs/data/joy/customization/theme-tokens/theme-tokens.md
- docs/data/joy/customization/using-css-variables/using-css-variables.md
- docs/pages/experiments/joy/variant.tsx
- packages/mui-joy/src/styles/CssVarsProvider.test.tsx
- packages/mui-joy/src/styles/CssVarsProvider.tsx
- packages/mui-joy/src/styles/defaultTheme.test.js
- packages/mui-joy/src/styles/defaultTheme.ts
- packages/mui-joy/src/styles/extendTheme.test.js
- packages/mui-joy/src/styles/extendTheme.ts
- packages/mui-joy/src/styles/index.ts
- packages/mui-joy/src/styles/types/theme.ts
- packages/mui-joy/src/styles/variantUtils.test.js
- packages/mui-joy/src/styles/variantUtils.ts
- packages/mui-material/src/styles/CssVarsProvider.tsx
- packages/mui-material/src/styles/experimental_extendTheme.d.ts
- packages/mui-material/src/styles/experimental_extendTheme.js
- packages/mui-material/src/styles/experimental_extendTheme.test.js
- packages/mui-system/src/cssVars/createCssVarsProvider.d.ts
- packages/mui-system/src/cssVars/createCssVarsProvider.js
- packages/mui-system/src/cssVars/createCssVarsProvider.test.js
- packages/mui-system/src/cssVars/createGetCssVar.ts
- packages/mui-system/src/cssVars/cssVarsParser.test.ts
- packages/mui-system/src/cssVars/cssVarsParser.ts
- test/regressions/fixtures/CssVarsProvider/CssVarsProviderJoy.js
**Sandbox**: https://codesandbox.io/s/joy-cra-typescript-forked-c9csds?file=/src/App.tsx
From #33275, the community is interested in trying Joy but given the small number of components, Material UI is a backup. This PR simplifies the theme for Joy so that it can be used with Material UI (only for the short term).
- **Joy**: Move variants generation to `extendTheme` so that the theme can be combined with Material UI.
- **Joy, Material UI**: Move CSS var prefix to `extendTheme`. This reduces complexity in `CssVarsProvider` and allows theme to be combined.
- **System**: remove `prefix` prop at `CssVarsProvider` given the prefix is handled by `extendTheme`.
---
> Enable Joy and Material UI compatibility

- packages/mui-material/src/SnackbarContent/SnackbarContent.js
- packages/mui-material/src/styles/experimental_extendTheme.js
https://github.com/mui/material-ui/issues/32049#issuecomment-1165572329
This PR fixes the SnackbarContent message text color to use the contrast text color instead of the primary text color.
> [SnackbarContent] fix message text color with css var provider

- docs/data/material/components/tooltips/tooltips.md
Fixes #33152. If any of this doesn't meet MUI's preferred documentation style, edits/corrections/requests for change are welcome.
I wondered if https://mui.com/material-ui/guides/composition/#caveat-with-refs should also reference this (or if this added section should instead be added to https://mui.com/material-ui/guides/composition/#caveat-with-refs, and the Tooltip docs link there).
> [docs] Add caveat about class components with Tooltip

- packages/mui-lab/src/Masonry/Masonry.js
- packages/mui-lab/src/Masonry/Masonry.test.js
- test/regressions/fixtures/Masonry/EmSpacingValue.js
- test/regressions/fixtures/Masonry/RemSpacingValue.js
Closes https://github.com/mui/material-ui/issues/33141
Code sandboxes:
- [Before](https://codesandbox.io/s/basicmasonry-demo-material-ui-forked-4n3912?file=/demo.tsx)
- [After](https://codesandbox.io/s/basicmasonry-demo-material-ui-forked-ez4e01?file=/demo.tsx)
> [Masonry] Support `rem`/`em` values for `spacing` prop

- docs/data/joy/components/radio/ExampleProductAttributes.js
- packages/mui-joy/src/styles/extendTheme.ts
My previous PR (https://github.com/mui/material-ui/pull/33158) might've introduced a couple of color regressions, somehow.
This now fixes those－mostly regarding the soft variant with the warning palette at light mode and all the dark mode disabled solid variant colors.
> [Joy] Fix variants color palette regressions

- docs/data/material/components/buttons/UploadButtons.js
- docs/data/material/components/buttons/UploadButtons.tsx
- docs/data/material/components/buttons/UploadButtons.tsx.preview
- Use MUI Component Composition API to get rid of HTML `label` element.
- Use `hidden` attribute on the HTML `input` to further simplify the code.
We can add the following `onChange` code block for a more declarative example:
```tsx
onChange={(e: React.ChangeEvent<HTMLInputElement>) => {
console.log(e.currentTarget.files);  //Access file(s) selected for upload
}}
```
Here's a live [CodeSandbox](https://codesandbox.io/s/uploadbuttons-demo-material-ui-forked-r3o14c?file=/demo.tsx) of the new changes.
> [docs] Simplify "Upload button" demo

- docs/babel.config.js
The logic was added in #13066. We now fix the same problem with a webpack plugin, we don't need this logic.
This was found working on https://github.com/mui/mui-toolpad/pull/542.
> [core] Remove old babel resolve rule

- docs/src/components/pricing/FAQ.tsx
- docs/src/components/pricing/WhatToExpect.tsx
Nothing major, I have tried to:
- Link more
- Group the related FAQ questions together.
https://deploy-preview-33292--material-ui.netlify.app/pricing/
> [website] Link EULA in the license quantity section

- docs/data/material/guides/understand-mui-packages/understand-mui-packages.md
- docs/src/components/pricing/FAQ.tsx
- docs/src/components/pricing/WhatToExpect.tsx
- docs/src/modules/components/AppNavDrawer.js
- docs/src/route.ts
- test/e2e-website/products-drawer.spec.ts
This PR is connected to https://github.com/mui/mui-x/pull/4692. It updates links pointing to the X Overview page to match the new structure of that PR.
This should only be merged after its sister on the X side is **released** in production 👯‍♀️
> [docs] Update links to MUI X Overview and Introduction pages

- packages/mui-material/src/styles/createTheme.d.ts
- packages/mui-material/test/typescript/moduleAugmentation/themeCustomNode.spec.tsx
- packages/mui-material/test/typescript/moduleAugmentation/themeCustomNode.tsconfig.json
Currently, you can't use the custom node that augment from the theme in `components` style overrides:
```ts
import * as React from 'react';
import { createTheme, styled } from '@mui/material/styles';
import Box from '@mui/material/Box';
interface CustomNode {
background: string;
color: string;
}
declare module '@mui/material/styles' {
interface ThemeOptions {
customNode: CustomNode;
}
interface Theme {
customNode: CustomNode;
}
}
const customTheme = createTheme({
customNode: {
background: '#000',
color: '#fff',
},
components: {
MuiAppBar: {
stylesOverrides: {
root: ({ theme }) => ({
// @ts-expect-error: this should work!
backgroundColor: theme.customNode.background,
})
}
}
}
});
```
> [TypeScript] Fix theme options components types to use `Theme`

- packages/mui-material/src/Tooltip/Tooltip.js
- packages/mui-material/src/Tooltip/Tooltip.test.js
I believe this bug is also caused by https://github.com/facebook/react/issues/7769, where `Ref` effects are called after `Update`, therefore `childNode` (set by ref passed to child) is undefined. The issue is fixed for `onFocus` events in #14496, this PR applies the same fix for `onMouseOver` events. 
fixes #31198
> [Tooltip] Fix children mouse over detection

- docs/pages/material-ui/api/scoped-css-baseline.json
- docs/translations/api-docs/scoped-css-baseline/scoped-css-baseline.json
- packages/mui-material/src/ScopedCssBaseline/ScopedCssBaseline.d.ts
- packages/mui-material/src/ScopedCssBaseline/ScopedCssBaseline.js
- packages/mui-material/src/ScopedCssBaseline/ScopedCssBaseline.spec.tsx
Small follow up PR to https://github.com/mui/material-ui/issues/33402. Just adds `sx` to the typings for `ScopedCssBaseline`'s props so that the TS analyzer doesn't flag it as invalid.
> [ScopedCssBaseline] Add `sx` typings

- docs/data/joy/components/avatar/avatar.md
- docs/data/joy/components/badge/badge.md
- docs/data/joy/components/button/button.md
- docs/data/joy/components/checkbox/checkbox.md
- docs/data/joy/components/chip/chip.md
- docs/data/joy/components/link/link.md
- docs/data/joy/components/radio/radio.md
- docs/data/joy/components/sheet/sheet.md
- docs/data/joy/components/slider/slider.md
- docs/data/joy/components/switch/switch.md
- docs/data/material/components/tree-view/tree-view-pt.md
- docs/src/modules/components/ComponentLinkHeader.js
Hey,
I've noticed that "Bundle size" button links to the `@mui/material` package, so I've updated it to link to `@mui/joy`.
I've also disabled links to design kits, since there's no Joy design kit yet.
Great work on components docs! 🎉
> [docs] Link to the correct package on Joy component pages

- docs/data/material/components/typography/typography.md
A Yarn command for installing the Roboto font has been added for convenience and consistency across the docs.
> [docs] Add yarn command for Roboto font in Material UI's typography.md

- docs/pages/material-ui/api/timeline-dot.json
- packages/mui-lab/src/TimelineDot/TimelineDot.d.ts
- packages/mui-lab/src/TimelineDot/TimelineDot.js
Hi there!
**Current behaviour:**
Extension of color property in TimelineDot interface is not available with module augmentation. 
**Expected behaviour:**
Color property can accept custom color palette properties
Fixes #33492
> [TimelineDot] Add TimelineDotPropsColorOverrides interface to extend color options

- packages/mui-base/src/ListboxUnstyled/defaultListboxReducer.ts
- packages/mui-base/src/ListboxUnstyled/useControllableReducer.ts
- packages/mui-base/src/ListboxUnstyled/useListbox.ts
- packages/mui-base/src/ListboxUnstyled/useListbox.types.ts
- packages/mui-base/src/MultiSelectUnstyled/MultiSelectUnstyled.test.tsx
- packages/mui-base/src/SelectUnstyled/useSelect.ts
Revised the logic of the controllable reducer that powers the useSelect hook. The `onChange` callback was incorrectly called when a controlled value was modified externally.
I was able to simplify the useControlledReducer by the way.
Fixes #33286
> [SelectUnstyled] Do not call onChange unnecessarily

- packages/mui-base/src/ListboxUnstyled/useControllableReducer.ts
After merging #33408 the build on master started failing because of untyped parameters of useCallback. This PR fixes the problem.
> [Base] Add missing type definitions in useControllableReducer

- packages/mui-system/src/breakpoints.js
A small improvement that optional chaining operator is not needed if a default parameter is present. This method is used within `sx`.
> [system] Remove needless optional chaining check in `createEmptyBreakpointObject` method

- examples/nextjs-with-typescript-v4-migration/package.json
When I tried to deploy this to production I got the following errors.
**Root cause:** https://github.com/mui/material-ui/blob/9c7cce753f2313452c0fb268d47364b1121a6253/examples/nextjs-with-typescript-v4-migration/pages/_document.tsx#L43-L45
**Solution:** We need to add these packages in package.json
> [examples] Fix error in Next.js example with @mui/styles

- CHANGELOG.md
> [core] Update CHANGELOG to include pickers breaking change

- docs/src/modules/components/MarkdownElement.js
I'm using display: none to remove the content from the content tree. I don't think that we should use opacity for this use case. For context, I was searching for the "copy" feature in https://mui.com/x/react-data-grid/export/#clipboard. It was super confusing.
**Before**
https://mui.com/material-ui/react-alert/
**After**
https://deploy-preview-33438--material-ui.netlify.app/material-ui/react-alert/
If the plan was to add a transition effect on the opacity, I guess we would need to use a pseudo-element with the CSS content property https://stackoverflow.com/questions/13296789/is-it-possible-to-make-css-generated-content-searchable-by-a-browser.
> [docs] Fix copy search false positives

- docs/data/material/customization/theming/theming.md
This PR moves the useTheme documentation from the advanced(legacy)section to the theming section. This was done to prevent confusion about deprecating the `useTheme` hook (see #32173).
> [docs] Improve the `useTheme` documentation

- docs/data/system/components/grid/grid.md
A small polish. Avoid the need to scroll, and make it less overwhelming to understand what's going on. It took me some time to understand the message we were trying to communicate.
https://mui.com/system/react-grid/#custom-breakpoints
https://deploy-preview-33527--material-ui.netlify.app/system/react-grid/#custom-breakpoints
> [Grid] Avoid scrollbar in demo

- docs/pages/material-ui/api/tabs.json
- packages/mui-material/src/Tabs/Tabs.js
After #33333, I realized it should support `string` proptype as well as in `indicatorColor` else it will throw a warning for custom values. 
However, this should be automatically generated if the types are updated as it can be easily missed.
> [Tabs] Fix `indicatorColor` prop type

- docs/data/material/components/tooltips/tooltips.md
Preview: https://deploy-preview-33571--material-ui.netlify.app/material-ui/react-tooltip/#positioned-tooltips
> [docs] Fix `placement choices` typo in Tooltip docs

- packages/mui-material/src/Stack/Stack.js
- packages/mui-material/src/Stack/Stack.test.js
Closes https://github.com/mui/material-ui/issues/32196
**Problem**:
- If `direction` prop receives a responsive value such that it doesn't start with the smallest breakpoint, such as `direction={{ lg: 'row' }}`, for the breakpoints below `lg`, `"marginundefined": "0px"`is being used in styling instead of `"marginLeft": "0px"` (for `row` direction) or `"marginTop": "0px"` (for `column` direction).
- [This function in line 86](https://github.com/mui/material-ui/blob/master/packages/mui-material/src/Stack/Stack.js#L86) results in `undefined` because `directionValues[breakpoint]` in the next line, [line 87](https://github.com/mui/material-ui/blob/master/packages/mui-material/src/Stack/Stack.js#L87),  is `undefined`.
**Solution**:
- Ensure that [this function in line …
> [Stack] Ensure that `marginundefined` doesn't occur in styling 

- packages/mui-material/src/Stack/Stack.js
- packages/mui-material/src/Stack/Stack.test.js
**Problem**:
-  If `direction` prop receives a responsive value such that it doesn't start with the smallest breakpoint, such as `direction={{ lg: 'row' }}`, `flexDirection` isn't specified for breakpoints below `lg` and hence it is set to the default value of flexbox, which is `row`.
**Solution**:
- Set the `StackRoot`'s `flexDirection` property to `ownerState.direction` if it is a string, or simply to `column`.
- If responsive `direction` values are provided, this `flexDirection` property will be overridden.
**Codesandboxes**:
- [Before](https://codesandbox.io/s/loving-cdn-c99hyj)
- [After](https://codesandbox.io/s/nice-butterfly-fgf6xh)
> [Stack] Fix default `flexDirection` value with responsive prop

- packages/mui-material/src/Stack/Stack.test.js
#33549 was merged into `master` right after #33548 without rebasing and as a result, 2 unit tests of Stack are failing.
> [Stack] Fix unit test failure

- docs/data/material/customization/dark-mode/dark-mode.md
First code example on page uses
`import { ThemeProvider, createTheme, CssBaseline } from '@mui/material/styles';`
which fails with
`export 'CssBaseline' (imported as 'CssBaseline') was not found in '@mui/material/styles' ... `.
Presumably, `CssBaseline` was moved recently and the first code example was not updated correspondingly; last code example on page is fine.
Preview: https://deploy-preview-33614--material-ui.netlify.app/material-ui/customization/dark-mode/#dark-mode-by-default
> [docs] Fix `CssBaseline` import in example code

- package.json
- yarn.lock
Fix https://github.com/mui/material-ui/security/dependabot/78
`thenify` is a deep deps of `argos-cli`, the fastest way to fix this is to use resolutions (from 3.3.0 to 3.3.1).
---
> [core] Fix dep security by resolving `thenify` to latest

- docs/src/modules/components/AdCarbon.js
I'm using uBlock Origin, which blocks this request. I suspect it's the case for more of our contributors:
**Before**
https://user-images.githubusercontent.com/3165635/180577135-d11172f7-0201-4edc-b001-60c99f952a5c.mov
**After**
No error popup that interrupts the contribution workflow unnecessarily in development mode.
> [core] Swallow ad blocker fetch fail

- docs/src/modules/sandbox/CodeSandbox.test.js
- docs/src/modules/sandbox/CodeSandbox.ts
The `name` is usally something like "ContinuousSlider demo — Material UI" which is not allowed:
> The "name" field contains your package's name, and must be lowercase and one word, and may contain hyphens and underscores.
https://docs.npmjs.com/creating-a-package-json-file. In practice, it breaks the deployment of codesandboxes to production with yarn:
https://codesandbox.io/s/continuousslider-demo-material-ui-forked-69rumd?file=/package.json:518-553
It used to work before the last factorization of the explore to codesandbox/stackblitz. What's the value? Sometimes a change in a PR only impacts the behavior in production. I needed this for https://github.com/mui/mui-x/issues/5557#issuecomment-1191764448.
> [docs] Fix production deploy of codesandboxes

- packages/mui-material/src/ImageListItem/ImageListItem.js
Removes the extra vertical whitespace from between images when the ImageList is in masonry mode.
Fixes #33328
> [ImageList] Remove vertical spacing between items in masonry layout

- .circleci/config.yml
- .codesandbox/ci.json
- netlify.toml
Updated the Node.js version used by our CI tools to unblock many dependencies that require version >=14. 
Related to #32546
> [core] Update Node.js version to 14 on CircleCI, CodeSandbox, and Netlify

- package.json
- yarn.lock
A follow-up to #33612
There's no need to have version override in package.json dependencies. yarn.lock is enough for this case.
> [core] Remove thenify version override from package.json resolutions

- docs/pages/blog/mui-x-v5.md
- docs/src/modules/components/MarkdownElement.js
- prettier.config.js
The print container width on blog pages needs to be smaller to avoid horizontal scrolling.
This PR adds a new rule to address this issue and prettify blog pages.
more context: https://github.com/mui/material-ui/pull/33595/files#r929087645
Before: https://mui.com/blog/mui-x-v5/#simplified-style-customization
After: https://deploy-preview-33648--material-ui.netlify.app/blog/mui-x-v5/#simplified-style-customization
> [blog] Fix horizontal scrollbar with code snippets

- docs/data/material/components/pagination/pagination.md
While migrating to Material UI v5, we found the reference to [the docs here](https://mui.com/material-ui/react-pagination/#usepagination) were incorrectly referring to `Pagination`, but it should actually be `usePagination`, and `usePagination` should be a default import
Preview: https://deploy-preview-33675--material-ui.netlify.app/material-ui/react-pagination/#usepagination
> [docs] Update module reference for `usePagination`

- package.json
- test/karma.conf.js
- yarn.lock
Removed [istanbul-instrumenter-loader](https://github.com/webpack-contrib/istanbul-instrumenter-loader) from our dependencies and used Babel with [babel-plugin-istanbul](https://github.com/istanbuljs/babel-plugin-istanbul) to measure coverage of our karma tests.
`istanbul-instrumenter-loader` is no longer maintained and has a transitive dependency on an old version of `ajv`, which has a security vulnerability.
The codecov/project check is failing because of how the coverage is measured. Previously, both production and test files were taken into consideration. After this change, only source files are instrumented. This makes more sense, as tests have 100% function coverage by definition, so by measuring coverage of the source files only, we get a better picture of what the actual condition …
> [test] Replace istanbul-instrumenter-loader with babel-plugin-istanbul

- docs/data/material/components/tables/EnhancedTable.js
- docs/data/material/components/tables/EnhancedTable.tsx
I noticed 2 issues with the current version of the `EnhancedTable` example ([link](https://mui.com/material-ui/react-table/#sorting-amp-selecting))
- There seems to be a typo: `newSelecteds` -> `newSelected` ?
- Clicking the select all checkbox when it has an `indeterminate` state should _deselect_ all rows, like in the [data table example](https://mui.com/material-ui/react-table/#data-table). Currently, it _selects_ all rows.
Both of these issues are addressed here. I think the changes are self explanatory but I am happy to answer any questions. Thanks for taking a look.
> [docs] Fix a typo in the code in `Sorting & selecting` Table demo

- packages/mui-material/src/Stack/Stack.js
- packages/mui-material/src/Stack/Stack.test.js
Closes https://github.com/mui/material-ui/issues/32999
**Problem**:
- When providing responsive values to both `direction` and `spacing`, the CSS styling could result in such that responsive styles are listed in incorrect order (e.g., lower resolution overwriting the higher one, while the correct behaviour is the opposite).
- Example where `900px` resolution's style is overwriting the style of `1200px`.
**Solution**:
- Use the utility function [mergeBreakpointsInOrder](https://github.com/mui/material-ui/blob/master/packages/mui-system/src/breakpoints.js#L107) from `@mui/system`.
- Same example used above:
**Codesandboxes**:
- [Before](https://codesandbox.io/s/friendly-haze-m7s2mn)
- [After](https://codesandbox.io/s/objective-keldysh-b7ktn6)
> [Stack] Responsive styles based on breakpoints should be in the correct order

- yarn.lock
Updated `cheerio` (from 1.0.0-rc.3 to 1.0.0-rc.12) with its dependencies to remove the version of `nth-check` with a security vulnerability (https://github.com/mui/material-ui/security/dependabot/22).
> [core] Update packages with security issues

- docs/data/material/customization/theming/theming.md
- docs/public/static/error-codes.json
- packages/mui-material/src/styles/createTheme.js
- packages/mui-material/src/styles/createTheme.test.js
Closes https://github.com/mui/material-ui/issues/33544
**Problem**:
- Passing `vars` property to `createTheme` results in error, because `theme.vars` is a private field used for CSS variables support.
**Preview**: https://deploy-preview-33619--material-ui.netlify.app/material-ui/customization/theming/#createtheme-options-args-theme
**Codesandboxes**:
- [Before](https://codesandbox.io/s/styled-components-forked-theme-provider-broken-o8jff6)
- [After](https://codesandbox.io/s/styled-components-forked-theme-provider-broken-8ong34)
> [docs][system] Throw an informative error when `theme.vars` is used in `createTheme` and mention this in the theming docs

- packages/mui-styled-engine-sc/package.json
Fixes #33690 
Signed-off-by: Arseny Garelyshev <monstrag@gmail.com>
I tried to find anything in CONTRIBUTING in relation to running `yarn build` or dedupe or whatever to update lockfiles but did not find anything.
Running yarn build anyway did not produce any changes.
> [styled-engine-sc] Add missing @babel/runtime dependency

- docs/pages/blog/2021-q1-update.md
- docs/pages/blog/aggregation-functions.md
- docs/src/components/pricing/PricingTable.tsx
We have split `/rows/` page recently in https://github.com/mui/mui-x/pull/5195, so some URLs have changed.
cc @joserodolfofreitas - would be great to have this merged before releasing the aggregation blog post
> [website] Update links to rows pages

- docs/data/material/components/skeleton/Variants.js
- docs/data/material/components/skeleton/Variants.tsx
- docs/data/material/components/skeleton/Variants.tsx.preview
- docs/data/material/components/skeleton/skeleton.md
- docs/pages/material-ui/api/skeleton.json
- docs/translations/api-docs/skeleton/skeleton.json
- packages/mui-material/src/Skeleton/Skeleton.d.ts
- packages/mui-material/src/Skeleton/Skeleton.js
- packages/mui-material/src/Skeleton/skeletonClasses.ts
closes https://github.com/mui/material-ui/issues/33043, from #33044
> [Skeleton] Add `rounded` variant

- .github/renovate.json
The `playwright` package should have the same version as `@playwright/test`. Ensuring that they are updated together. Also made sure that the `mcr.microsoft.com/playwright` docker image used to run tests on CircleCI is updated alongside.
> [core] Update Playwright packages together

- docs/notifications.json
Add notification linking to blogpost: https://master--material-ui.netlify.app/blog/aggregation-functions/
**Important:** To merge after [this week's release](https://github.com/mui/material-ui/pull/33740).
> [docs] Add notification to aggregation blogpost

- packages/mui-material/src/Grid/Grid.d.ts
Fixes #33165 
This issue occurs only for library apps where it is needed to generate declaration files (`.d.ts`) with `declaration: true` set in it's tsconfig.
Explained well in https://github.com/mui/material-ui/issues/33165#issuecomment-1161445846
Discussion about this in TypeScript repo: https://github.com/Microsoft/TypeScript/issues/5711
----
Before: https://codesandbox.io/s/trusting-water-wxupl4?file=/src/App.tsx
After: https://codesandbox.io/s/create-react-app-with-typescript-forked-iupbvd?file=/src/App.tsx
> [Grid] Export interface `RegularBreakpoints` to fix type error

- packages/mui-material/src/Tooltip/Tooltip.js
This PR fixes the Tooltip arrow background color, to use the same color as the tooltip if CSS variables are used.
> [Tooltip] Fix tooltip arrow css var background

- docs/src/modules/components/AppFrame.js
- docs/src/modules/components/AppNavDrawer.js
Related to https://github.com/mui/material-ui/pull/33196#discussion_r922541351
Fixes the following warning:
No need to update the examples, as the correct propagating of props is used there. This was occurrence of direct usage of Next's Link in the docs.
> [docs] Fix warnings related to Next.js' links

- docs/data/material/components/button-group/SplitButton.js
- docs/data/material/components/button-group/SplitButton.tsx
> [docs] z-index added in popper when used by split button

- docs/src/modules/components/Notifications.js
I've noticed that on mui.com notifications badge doesn't disappear after opening notifications popup:
https://user-images.githubusercontent.com/13808724/182340755-352dec3a-0a6d-47ce-ac8e-ae519689ddbb.mov
This PR fixes this regression from https://github.com/mui/material-ui/pull/32728/files#diff-0c46f5931a115b3f0c7fe7cbecebb058b5acf6b36f0bf82f57a1ef999c9f412aR82
> [website] Fix notifications not being marked as read in production

- packages/mui-joy/src/Stack/Stack.test.js
- packages/mui-joy/src/Stack/Stack.tsx
- packages/mui-joy/src/Stack/StackProps.ts
- packages/mui-joy/src/Stack/index.ts
- packages/mui-joy/src/Stack/stackClasses.ts
- packages/mui-joy/src/index.ts
Demo: https://codesandbox.io/s/currying-hooks-2f8di1?file=/demo.tsx
I haven't seen any doc for the system components, so I didn't add one for the Stack too. I guess they will be coming afterwards.
> [Stack][joy] Add new component

- docs/data/material/components/click-away-listener/click-away-listener.md
> [docs] Fix typo in the ClickAwayListerner name

- docs/src/modules/brandingTheme.ts
- docs/src/modules/components/AppContainer.js
- docs/src/modules/components/TopLayoutBlog.js
- prettier.config.js
Implement https://github.com/mui/material-ui/pull/33670#discussion_r933074451. I have also updated https://www.notion.so/mui-org/Blog-247ec2bff5fa46e799ef06a693c94917#b51c4255803840479e39cf2861af7ed8.
Preview: https://deploy-preview-33706--material-ui.netlify.app/blog/aggregation-functions/
> [blog] Improve the width of the layout

- packages/mui-system/src/createBox.js
- packages/mui-system/src/createBox.test.js
fixes #33443 
The `Box` should not forward the `sx` prop to the override component. We can overwrite the `shouldForwardProp`  function of the `@mui/styled-engine` to solve the problem.
> [system] Fix duplicated styles in Box

- docs/pages/material-ui/api/table-cell.json
- packages/mui-material/src/TableCell/TableCell.d.ts
- packages/mui-material/src/TableCell/TableCell.js
- packages/mui-material/test/typescript/moduleAugmentation/tableCellCustomProps.spec.tsx
- packages/mui-material/test/typescript/moduleAugmentation/tableCellCustomProps.tsconfig.json
Enable TableCell size prop overrides via module augmentation using pattern recommend in https://github.com/mui/material-ui/issues/33802#issuecomment-1206223476.
Fixes #33802
> [TableCell] Enable size prop overrides via module augmentation

- examples/nextjs-with-typescript/src/Link.tsx
Signed-off-by: Adham Tarek <adhamtarek291@gmail.com>
> [examples] Fix `NextLinkComposedProps` type error

- packages/mui-base/src/index.d.ts
- packages/mui-base/src/index.js
Fixes #33694
I added the export statement snippets for TablePaginationUnstyled, in the base/index.js and base/index.d.ts. 
I followed the name ordering (see image below )you get when you default import MUI using NPM on Mac
Ran this locally and it seems to fix it up :). I also checked if any other exports were missing but this seemed to be the only one.
> [base] Add missing `TablePaginationUnstyled` export from root

- docs/next.config.js
I wanted to check the logs server side, and here is what I got, too much noise for my taste 😁:
It comes from https://github.com/mui/material-ui/pull/33626
> [core] Remove outdated Next.js options

- docs/data/system/getting-started/overview/overview.md
Literally https://github.com/mui/material-ui/issues/33865#issuecomment-1208966004
Fixes #33865 
Preview: https://deploy-preview-33867--material-ui.netlify.app/system/getting-started/overview/#mui-system-vs-mui-base
> [docs] Fix `/system/getting-started/advanced/` does not exist

- packages/mui-base/src/InputUnstyled/InputUnstyled.test.tsx
- packages/mui-base/src/InputUnstyled/InputUnstyled.tsx
- packages/mui-base/src/InputUnstyled/InputUnstyled.types.ts
Made sure props related to multiline input (rows, minRows, maxRows) are correctly passed in to the underlying Textarea lot.
Fixes #33060
> [Input][base] Pass the rows prop to the underlying textarea

- package.json
- yarn.lock
Fixes the following warning appearing in the terminal when installing yarn packages:
> warning Pattern ["@definitelytyped/typescript-versions@latest"] is trying to unpack in the same destination "/Users/michal/Library/Caches/Yarn/v6/npm-@definitelytyped-typescript-versions-0.0.115-e446a350438e6c83df0c2e72004ba586f052f782-integrity/node_modules/@definitelytyped/typescript-versions" as pattern ["@definitelytyped/typescript-versions@^0.0.115","@definitelytyped/typescript-versions@^0.0.115","@definitelytyped/typescript-versions@^0.0.115"]. This could result in non-deterministic behavior, skipping.
> [core] Clear yarn installation warning

- docs/packages/markdown/parseMarkdown.js
- docs/packages/markdown/parseMarkdown.test.js
https://mui.com/x/api/data-grid/grid-export-state-params/ is the only page of on mui.com that doesn't have a description. See [ahrefs explanation](https://help.ahrefs.com/en/articles/2630975-meta-description-tag-missing-or-empty-error-in-site-audit) for why we probably want to have one on all the pages. I'm fixing the problem on the surface with: https://github.com/mui/mui-x/pull/5654. It surfaced in [an SEO crawl](https://app.ahrefs.com/site-audit/3523498/21/data-explorer?columns=pageRating%2Curl%2Ctraffic%2ChttpCode%2Cdepth%2CmetaDescription%2CmetaDescriptionLength%2CnrMetaDescription%2Ccompliant&filterCollapsed=true&filterId=c2374462d9d0ef63ad879d0f2dd819fc&issueId=c64d31f0-d0f4-11e7-8ed1-001e67ed4656).
But the main reason why I worked on this is that it seems to be a quick-win …
> [docs] Enforce description for all pages

- docs/notifications.json
- docs/src/modules/components/Notifications.js
A continuation of #33745
- Remove company category blog posts. I feel that it's off-topic for the docs. AFAIK the purpose of this blog is for curious candidates that browse https://mui.com/blog/?tags=Company.
- Add the notification about how to get notifications back. I have also mentioned the blog.
- Welcome Chinese with notification only for them to signal that we want to translate.
> [docs] Add permanent notifications back

- docs/pages/blog/premium-plan-release.md
- docs/src/components/pricing/FAQ.tsx
- docs/src/components/pricing/WhatToExpect.tsx
Per https://www.notion.so/mui-org/MUI-X-Pricing-changes-2022-f17df701bf10406884a3204dcb8a3a3f#f50eb9adbc33495b8876d69cc69350d1 and per @joserodolfofreitas's point on how this point is confusing based on the sales analytics on the number of licenses sold. This effort is part of https://github.com/mui/mui-store/issues/136.
Preview: https://deploy-preview-33553--material-ui.netlify.app/pricing/
- https://mui.zendesk.com/agent/tickets/4208
> [website] Add new FAQ to pricing page

- docs/data/base/components/menu/MenuSimple.js
- docs/data/base/components/menu/MenuSimple.tsx
- docs/data/base/components/menu/WrappedMenuItems.js
- docs/data/base/components/menu/WrappedMenuItems.tsx
Added code to prevent reopening a menu after a trigger button is pressed when the menu is already open.
This was caused by the menu closing due to losing focus, then immediately showing up again when the button's onClick handler was fired.
In the future, when we have the MenuButton component, this will be handled internally by the component. For now, such a workaround in user code is needed.
Fixes #33498
> [docs] Fix the reopening menu problem in MenuUnstyled demo

- examples/nextjs-with-typescript-v4-migration/pages/_document.tsx
- examples/nextjs-with-typescript/pages/_document.tsx
- examples/nextjs/pages/_document.js
Update _document.tsx: Fix broken path to favicon.ico
- Next is not serving static files from "/static" folder anymore. Instead all files inside public
are accessible in pages.
- Replace path "/static/favicon.ico" with "favicon.ico"
Signed-off-by: Vegan Cat
> [examples] Fix broken path to favicon.ico

- packages/mui-joy/src/IconButton/IconButton.tsx
This was probably a typo in https://github.com/mui/material-ui/pull/33750
> [IconButton][Joy] Fix large IconButton scaling

- docs/data/material/customization/transitions/TransitionHover.js
- docs/data/material/customization/transitions/TransitionHover.tsx
- docs/data/material/customization/transitions/TransitionHover.tsx.preview
- docs/data/system/getting-started/custom-components/CombiningStyleFunctionsDemo.js
- docs/data/system/getting-started/custom-components/CombiningStyleFunctionsDemo.tsx
- docs/data/system/getting-started/custom-components/CombiningStyleFunctionsDemo.tsx.preview
- docs/data/system/getting-started/custom-components/StyleFunctionSxDemo.js
- docs/data/system/getting-started/custom-components/StyleFunctionSxDemo.tsx
- docs/data/system/getting-started/custom-components/StyleFunctionSxDemo.tsx.preview
I have noticed this in #33503. The NoSsr was in #23596 at a point where we didn't finalize the SSR implementation of the styled engine yet.
> [docs] Remove dead NoSsr in the demos

- packages/mui-system/src/Container/index.d.ts
Container.ts only exports a default component.  ContainerProps contains definitions for Container Props and it should be exported.
Signed-off-by: Jack Zhao <bugzpodder@hotmail.com>
> [system] Fix ContainerProps export

- docs/data/joy/components/aspect-ratio/aspect-ratio.md
Signed-off-by: IsaacInsoll <30609296+IsaacInsoll@users.noreply.github.com>
Preview: https://deploy-preview-33895--material-ui.netlify.app/joy-ui/react-aspect-ratio/
> [docs] Fix typo in Joy UI's `AspectRatio` docs

- scripts/pushArgos.js
In MUI X sometimes we have false negative regressions like https://app.argos-ci.com/mui/mui-x/builds/3071
Currently, we have to push new commit (or rebase) to trigger whole CI pipeline and upload new screenshot to Argos.
But ideally we would like to restart a single step in the pipeline.
Turned out, we used wrong external build id as pointed out in https://github.com/argos-ci/argos/issues/457#issuecomment-1213308341
> [core] Use proper external build id for Argos uploads

- packages/mui-core-internal-download-tracker/package.json
Add a script to copy the source into the build folder (as required by convention).
Adapted from the mui-types package.
> [core] Add the download tracker build script

- package.json
- packages/mui-core-downloads-tracker/README.md
- packages/mui-core-downloads-tracker/package.json
- packages/mui-core-internal-download-tracker/index.js
- packages/mui-core-internal-download-tracker/package.json
- packages/mui-joy/package.json
- packages/mui-material/package.json
Renamed the downloads tracker to remove the `internal` from its name as it apparently prevents the package from being published.
Also removed the unnecessary index.js file.
> [core] Download tracker rename

- docs/data/joy/components/aspect-ratio/aspect-ratio-pt.md
There was a typo in the Joy UI aspect ratio which has been fixed now!
> [docs] Fix typo in Joy UI's docs

- docs/data/joy/components/list/list.md
Fixed typo in Joy UI's List Component docs
I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/material-ui/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).
> [docs] Fix typo in Joy UI's List Component docs

- docs/data/base/components/badge/badge.md
- docs/data/base/components/button/button.md
- docs/data/base/components/form-control/form-control.md
- docs/data/base/components/input/input.md
- docs/data/base/components/menu/menu.md
- docs/data/base/components/select/select.md
- docs/data/base/components/slider/slider.md
The name of this section header changed at some point in the editing process (#33156) but this interior link slipped through the cracks.
> [docs] Fix interior section links in Base docs that feature hooks

- test/README.md
> [docs] Fix typos in `test` folder's README

- packages/mui-lab/src/TreeItem/TreeItem.js
Part of #33959 
CodeSandbox to test in - https://codesandbox.io/s/create-react-app-with-typescript-forked-1l419x
> [TreeItem] Add support for CSS variables

- packages/mui-lab/src/TimelineConnector/TimelineConnector.js
Part of #33959 
CodeSandbox to test in - https://codesandbox.io/s/create-react-app-with-typescript-forked-1ixyq3
If I inspect the classNames on this component with or without CSS vars I don't see any difference, the classNames are not changed without CSS vars. But I guess, there is something of benefit after we added this support. Perhaps a good DX about knowing the design tokens being used instead of hex values?
> [TimelineConnector] Add support for CSS variables

- packages/mui-system/src/cssVars/useCurrentColorScheme.ts
I was trying to use Joy UI to build a Figma plugin, but localStorage is not available in this environment and so the library could not be used. This would also be the case for private mode as mentioned in https://github.com/mui/material-ui/issues/33853
This PR just wraps all of the calls in a try / catch, which was how one call was already handled. 
Another solution might be to create our own class, similar to a polyfill, that wraps localStorage and proxies commands with a try catch, so the code calling localStorage becomes smaller and potentially more readable.
I didn't not want to make too many assumptions about how MUI team wants to resolve the bug so let me know what you think and I will update if needed.
closes https://github.com/mui/material-ui/issues/33853
> [system] catch localStorage errors

- docs/pages/careers.tsx
> [website] Move the React Engineer - X to next roles

- packages/mui-joy/src/index.ts
I noticed that some of the Components are not re-exported from `@mui/joy`.
> [Joy] Add missing global exports

- packages/mui-material/src/IconButton/IconButton.js
A typo in the `IconButton` styling was preventing the hover effect from appearing when using `CssVarsProvider`. This fixes it.
> [IconButton] Fix hover effect when CSS Variables are enabled

- docs/pages/about.tsx
- docs/pages/blog/material-ui-v1-is-out.md
- docs/pages/blog/material-ui-v4-is-out.md
- docs/pages/careers.tsx
- docs/pages/core.tsx
- docs/pages/material-ui.tsx
Meta descriptions are recommended to be between 110 and 160 characters. I have used the opportunity to update the about us description to exactly match the mission statement: https://www.notion.so/mui-org/Direction-d8b8c142a6a44e3aa963f26edf4e03db#c3479698694645ff906efae69d442be2.
> [website] Optimize meta description length

- docs/data/material/components/transitions/transitions.md
corrected a simple grammar problem at line  88
-- {/* MyComponent must the only child */}
++{/* MyComponent must be the only child */}
Signed-off-by: alireza <94165013+alirezahekmati@users.noreply.github.com>
> [docs] Fix typo in the Transition docs

- CHANGELOG.old.md
- docs/next.config.js
- docs/pages/blog/2019-developer-survey-results.md
- docs/src/components/showcase/ThemeChip.tsx
- docs/src/modules/components/ThemeContext.js
Fix https://github.com/mui/material-ui/pull/33196#discussion_r928753221 using https://github.com/vercel/next.js/issues/37893#issuecomment-1221335543
Before: http://mui.com/
After: https://deploy-preview-34037--material-ui.netlify.app/
---
I have also made a change so that MUI X and MUI Toolpad can do:
```diff
diff --git a/docs/next.config.js b/docs/next.config.js
index 3467a20a..e99f6bb1 100644
--- a/docs/next.config.js
+++ b/docs/next.config.js
@@ -1,4 +1,5 @@
const path = require('path');
+const nextConfig = require('@mui/monorepo/docs/next.config');
const { BundleAnalyzerPlugin } = require('webpack-bundle-analyzer');
// const withTM = require('next-transpile-modules')(['@mui/monorepo']);
const pkg = require('../package.json');
@@ -27,15 +28,9 @@ if (reactStrictMode) {
const …
```
> [core] Fix scroll restoration

- docs/data/base/components/trap-focus/BasicTrapFocus.js
- docs/data/base/components/trap-focus/BasicTrapFocus.tsx
- docs/data/base/components/trap-focus/ContainedToggleTrappedFocus.js
- docs/data/base/components/trap-focus/ContainedToggleTrappedFocus.tsx
- docs/data/base/components/trap-focus/ContainedToggleTrappedFocus.tsx.preview
- docs/data/base/components/trap-focus/DisableEnforceFocus.js
- docs/data/base/components/trap-focus/DisableEnforceFocus.tsx
- docs/data/base/components/trap-focus/LazyTrapFocus.js
- docs/data/base/components/trap-focus/LazyTrapFocus.tsx
- docs/data/base/components/trap-focus/PortalTrapFocus.js
- docs/data/base/components/trap-focus/PortalTrapFocus.tsx
- package.json
- packages/mui-base/src/TrapFocus/TrapFocus.test.js
- test/e2e/fixtures/TrapFocus/ClosedTrapFocus.tsx
- test/e2e/index.test.ts
- yarn.lock
This PR resolves asks from after this PR: https://github.com/mui/material-ui/pull/33543#pullrequestreview-1076496406 merged. The associated issue can be seen here: https://github.com/mui/material-ui/issues/33380.
Preview: https://deploy-preview-34008--material-ui.netlify.app/base/react-trap-focus/
> [TrapFocus] Improve tab test and simplify demo

- docs/pages/experiments/docs/callouts.js
- docs/src/modules/components/Head.tsx
- docs/src/modules/components/TopLayoutBlog.js
I was trying to understand why this bug:
https://www.linkedin.com/feed/update/urn:li:activity:6965034348081209344 
Which I failed at. It looks like an issue on LinkedIn's side. I have created a support request for FeedHive in case.
While I was looking at this, I found a quick win opportunity: https://developers.google.com/search/docs/advanced/structured-data/article#structured-data-type-definitions. You will find it on most of the blogs that compete for SEO keywords.
To test that the structure is correct: https://validator.schema.org/#url=https%3A%2F%2Fdeploy-preview-33954--material-ui.netlify.app%2Fblog%2Faggregation-functions%2F. The value is that it makes it easier for Google to index our content, and to show it on other channels, like the "News" one.
> [blog] Improve SEO metadata

- docs/data/joy/components/radio/ExampleAlignmentButtons.js
- docs/data/joy/components/radio/ExampleProductAttributes.js
- docs/data/joy/components/radio/ExampleSegmentedControls.js
- docs/data/joy/components/radio/IconlessRadio.js
- docs/data/joy/components/radio/RadioPositionEnd.js
- docs/data/joy/components/radio/radio.md
- packages/mui-joy/src/Radio/Radio.tsx
- packages/mui-joy/src/Radio/RadioProps.ts
- packages/mui-joy/src/Radio/radioClasses.ts
- follows the MUI Base `componentsProps` pattern (support callback) which remove the need for `classes` to style between states.
- update typings
- update demos to use the callback
**Before**:
```js
<Radio sx={theme => ({
[`&.${radioClasses.checked}`]: {
[`& .${radioClasses.action}]: { ... }
}
}) />
```
**After**:
```js
<Radio componentsProps={{
action: ({ checked }) => ({
sx: theme => ({
...checked && { ... }
})
})
}} />
```
---
> [Radio][Joy] support `componentsProps` as a function

- docs/data/material/components/tooltips/tooltips.md
Signed-off-by: Snêu <39024711+hoangph271@users.noreply.github.com>
Preview: https://deploy-preview-34064--material-ui.netlify.app/material-ui/react-tooltip/#custom-child-element
> [docs] Fix missing JSX closing tag in Tooltip docs

- docs/src/components/action/Frame.tsx
- docs/src/components/productCore/CoreStyling.tsx
- docs/src/components/productCore/CoreTheming.tsx
A quick opportunity I saw while I updated the link on https://github.com/mui/material-ui from http://mui.com/ to http://mui.com/core/
**Before**
https://mui.com/core/
**After**
https://deploy-preview-34070--material-ui.netlify.app/core/
> [website] Improve visual look of code demos

- docs/data/joy/components/link/link.md
- docs/data/material/guides/routing/routing.md
- examples/nextjs-with-typescript/README.md
- examples/nextjs/README.md
The link in the docs of Joy UI (https://reactrouter.com/docs/en/v6/components/link) leads to a 404.
> [docs] Fix 404 link from Joy to React Router

- docs/data/joy/components/select/SelectFieldDemo.js
I noticed this while trying to create a form with Joy. When using a label we should use the `htmlFor` associated with the select's id. I would probably even drop the `aria-label` in this demo, but I was not sure about that change. Notice now how clicking on the label focuses and opens the select.
Also, I am not sure about the `mt: 0.25`, as it looks a bit off compared to the textfield.
> [Select][joy] Improve the a11y on the select field demo

- docs/data/material/experimental-api/css-variables/css-variables.md
---
- [CSS variables - Server-side rendering](https://mui.com/material-ui/experimental-api/css-variables/#server-side-rendering)
- The array key is not set and react will cause a warning.
- `<Fragment>` add to the Gatsby config sample.
```txt
Warning: Each child in a list should have a unique "key" prop.
Check the top-level render call using <body>. See https://reactjs.org/link/warning-keys for more information.
```
> [docs] Fix Gatsby sample config in CSS variables

- docs/data/base/components/select/UnstyledSelectSimple.tsx
- packages/mui-base/src/MultiSelectUnstyled/MultiSelectUnstyled.spec.tsx
- packages/mui-base/src/MultiSelectUnstyled/MultiSelectUnstyled.tsx
- packages/mui-base/src/MultiSelectUnstyled/MultiSelectUnstyled.types.ts
- packages/mui-base/src/SelectUnstyled/SelectUnstyled.spec.tsx
- packages/mui-base/src/SelectUnstyled/SelectUnstyled.tsx
- packages/mui-base/src/SelectUnstyled/SelectUnstyled.types.ts
- packages/mui-base/src/utils/useSlotProps.test.tsx
TypeScript 4.8 introduced stricter type checks for generics (https://devblogs.microsoft.com/typescript/announcing-typescript-4-8/#unconstrained-generics-no-longer-assignable-to). This causes issues in our codebase.
This PR addresses a part of the problem that affects MUI Base. There are a few issues in other packages that prevent us from updating the TS version globally. They will be fixed in a separate PR.
Fixes #34126
> [Select][base] Fix type issues that appeared with TS 4.8

- docs/scripts/updateIconSynonyms.js
- package.json
The icon metadata from https://fonts.google.com/metadata/icons contain tags that cause our script to produce invalid JS. Specifically, a few tags are surrounded by apostrophes. This fix removes any apostrophes found in the tags.
Additionally, it skips tags that are clearly invalid - ones that contain "Remove", "Duplicate", "Same as", "remove others", so these strings don't appear as synonyms.
> [core] Sanitize input in icon synonyms update script

- scripts/copy-files.js
The copy-files script adds `types: "./index.d.ts" to the built package.json, regardless of the existence of the type definition file. This PR changes the script to check if the d.ts file exists before adding the field.
> [core] Do not append `types` field to packages without index.d.ts

- docs/pages/material-ui/api/avatar-group.json
- docs/translations/api-docs/avatar-group/avatar-group.json
- packages/mui-material/src/Avatar/Avatar.js
- packages/mui-material/src/AvatarGroup/AvatarGroup.d.ts
- packages/mui-material/src/AvatarGroup/AvatarGroup.js
- packages/mui-material/src/AvatarGroup/AvatarGroup.spec.tsx
- packages/mui-material/src/AvatarGroup/AvatarGroup.test.js
Use structured / semantic markup for avatars and avatar groups. Improves experience for screen reader users.
* Add `component` overriding to the `AvatarGroup` component.
* ~Have `AvatarGroup` use `ul` by default.~ (consider in v6)
* ~Have `Avatar` use `li` by default.~ (consider in v6)
Fixes #33993.
> [Avatar] Use structured / semantic markup for avatars and avatar groups

- docs/data/joy/getting-started/overview/overview.md
- docs/src/modules/components/AppLayoutDocs.js
- docs/src/modules/components/AppNavDrawer.js
https://deploy-preview-34087--material-ui.netlify.app/joy-ui/getting-started/overview/
Part of #33998.
This PR revises the copy on the Joy UI Overview page. It was already in good shape to begin with, but I saw some opportunities to sharpen it further so I couldn't help myself. 😅 I tried to do some reshaping to bring the voice and formatting closer to what we've got for Material UI and Base.
We're still in the early stages of figuring out the "elevator pitch" for Joy UI, so I've tried introducing some unique angles to help differentiate it from Material UI et al. and start to pin down the language we want to use to describe it going forward.
One thing I noticed is that the page titles in the Joy UI docs just say "MUI" where other products actually state their name:
I'm not sure where …
> [docs] Revise Joy UI "Overview" page copy

- docs/data/base/components/button/button.md
- docs/data/base/components/form-control/form-control.md
- docs/data/base/components/slider/slider.md
> [docs] Fix a few Base typos

- docs/src/modules/components/AppNavDrawer.js
#33937 and #34087 did not sync.
The variable (`asPathWithoutLang`) in #33937 did not update in #34087, so the docs crashes.
> [docs] Fix crash due to using wrong variable

- docs/data/material/migration/migration-v4/v5-style-changes-zh.md
- docs/data/material/migration/migration-v4/v5-style-changes.md
- docs/src/modules/components/MarkdownElement.js
- packages/mui-codemod/README.md
A quick win. I have noticed the issue here, the text is unreadable:
https://mui.com/x/api/data-grid/grid-col-def/.
It fails the contrast ratio thresholds:
https://webaim.org/resources/contrastchecker/?fcolor=A5B3FF&bcolor=FFFFFF
> [docs] Fix the color contrast on optional API methods

- docs/data/joy/components/select/SelectGroupedOptions.js
- docs/data/joy/components/select/select.md
- docs/src/modules/components/AppNavDrawer.js
- packages/mui-joy/src/List/List.tsx
- packages/mui-joy/src/ListDivider/ListDivider.tsx
- packages/mui-joy/src/Select/Select.tsx
- packages/mui-joy/src/Select/SelectProps.ts
- test/regressions/fixtures/SelectJoy/GroupedOptionSelect.js
closes #34164 
**Preview**: https://deploy-preview-34172--material-ui.netlify.app/joy-ui/react-select/#grouped-options
```js
<Select componentsProps={{
listbox: {
component: 'div',
},
}}>
```
By provided `component: 'div'` to the listbox slot, the div replace the `SelectListbox` slot instead of passing as `as` prop. That's why the styles are gone.
To fix this problem, the component must be specified at the end to `PopperUnstyled` and grab the final `component` from listbox slot props (because it could be a callback) to pass it as `as` prop. 
A visual regression test is added https://app.argos-ci.com/mui/material-ui/builds/4844
---
> [Select][Joy] Fix forwarding listbox `component` prop

- docs/pages/material-ui/api/step.json
- docs/pages/material-ui/api/stepper.json
- docs/translations/api-docs/step/step.json
- docs/translations/api-docs/stepper/stepper.json
- packages/mui-material/src/Step/Step.d.ts
- packages/mui-material/src/Step/Step.js
- packages/mui-material/src/Step/Step.spec.tsx
- packages/mui-material/src/Step/Step.test.js
- packages/mui-material/src/Stepper/Stepper.d.ts
- packages/mui-material/src/Stepper/Stepper.js
- packages/mui-material/src/Stepper/Stepper.spec.tsx
- packages/mui-material/src/Stepper/Stepper.test.tsx
Use structured / semantic markup for steppers and steps. Improves experience for screen reader users.
* Add `component` overriding to the `Stepper` component.
* Add `component` overriding to the `Step` component.
* ~Have `Stepper` use `ol` by default.~ (consider in v6)
* ~Have `Step` use `li` by default.~ (consider in v6)
Fixes #34137.
> Use structured / semantic markup for steps and steppers

- docs/data/material/discover-more/related-projects/related-projects-pt.md
- docs/data/material/discover-more/related-projects/related-projects.md
Here ! I'm happy to propose 2 useful packages for forms ! One for [phone numbers](https://viclafouch.github.io/mui-tel-input/) and one for [colors](https://viclafouch.github.io/mui-color-input/) 😊
> [docs] Add `mui-color-input`, `mui-chips-input`  and `mui-tel-input` into the related projects page

- docs/data/joy/components/list/ExampleCollapsibleList.js
- docs/data/joy/components/list/ListUsage.js
- docs/data/joy/components/list/list.md
- docs/data/joy/components/menu/MenuListGroup.js
- docs/data/joy/components/tabs/TabsPageExample.js
- docs/data/joy/components/tabs/TabsPageExample.tsx
- packages/mui-joy/src/Checkbox/Checkbox.tsx
- packages/mui-joy/src/Input/Input.tsx
- packages/mui-joy/src/List/List.test.js
- packages/mui-joy/src/List/List.tsx
- packages/mui-joy/src/List/ListProps.ts
- packages/mui-joy/src/ListItem/ListItem.test.js
- packages/mui-joy/src/ListItem/ListItem.tsx
- packages/mui-joy/src/ListItem/ListItemProps.ts
- packages/mui-joy/src/ListItem/listItemClasses.ts
- packages/mui-joy/src/ListItemButton/ListItemButton.tsx
- packages/mui-joy/src/MenuList/MenuList.tsx
- packages/mui-joy/src/Radio/Radio.tsx
- test/regressions/fixtures/ListJoy/Flexibility.js
Each commit describes the fixes with appropriate tests (unit and visual regression).
---
> [Joy] Miscellaneous fixes

- package.json
- scripts/pushArgos.js
- yarn.lock
Replaced the unsupported argos-cli with the new @argos-ci/cli package, as per https://github.com/argos-ci/argos/issues/483#issuecomment-1235272656.
> [test] Replace argos-cli with @argos-ci/cli

- packages/mui-joy/src/Textarea/Textarea.test.tsx
- packages/mui-joy/src/Textarea/Textarea.tsx
Signed-off-by: VelociRaptor <77036902+HexM7@users.noreply.github.com>
Fixes textarea props (minLength, maxLength, etc) not being passed to the native element.
> [Joy][Textarea] Pass `textarea` props from `componentsProps`

- .github/ISSUE_TEMPLATE/3.rfc.yml
Added an RFC template to GH issues
This is how it looks like: https://github.com/mui/mui-toolpad/issues/new?assignees=&labels=RFC&template=3.rfc.yml&title=%5BRFC%5D+
Same as https://github.com/mui/mui-x/pull/5739 and https://github.com/mui/mui-toolpad/pull/729
> [core] Add RFC GH issue template

- docs/data/joy/components/radio/ExampleAlignmentButtons.js
- docs/data/joy/components/radio/ExampleSegmentedControls.js
- docs/data/joy/components/radio/ExampleTiers.js
- docs/data/joy/components/radio/RadioButtonControl.js
- docs/data/joy/components/radio/RadioButtonLabel.js
- docs/data/joy/components/radio/radio.md
- docs/src/modules/components/JoyUsageDemo.tsx
- packages/mui-joy/src/Checkbox/Checkbox.tsx
- packages/mui-joy/src/FormControl/FormControl.test.tsx
- packages/mui-joy/src/FormControl/FormControl.tsx
- packages/mui-joy/src/FormHelperText/FormHelperText.tsx
- packages/mui-joy/src/Radio/Radio.tsx
- packages/mui-joy/src/RadioGroup/RadioGroup.tsx
**Basic label**: https://deploy-preview-34277--material-ui.netlify.app/joy-ui/react-radio-button/#label
**Complex example**: https://deploy-preview-34277--material-ui.netlify.app/joy-ui/react-radio-button/#tiers
I missed the Radio in the previous PR. The implementation is the same as other form controls.
Here is what the composition looks like:
```js
<FormControl>
<Radio />
<div>
<FormLabel>Label</FormLabel>
<FormHelperText>Description</FormHelperText>
</div>
</FormControl>
```
The composition is very useful for building a complex layout with form controls.
---
> [Radio][Joy] Integrate with form control

- packages/mui-joy/src/Select/Select.tsx
Fixes https://github.com/mui/material-ui/issues/34210
After fix: https://codesandbox.io/s/joy-issue-34210-select-component-qdwi3h?file=/demo.js
> [Joy] Fix list value of false or 0 (zero) text is incorrectly grey

- .github/ISSUE_TEMPLATE/1.bug.yml
Following up on https://github.com/mui/mui-toolpad/pull/908 which proposes to experiment with this in the core repo first.
When creating issues an issue I tend to
1. describe the steps that lead me to the situation
2. explain what's buggy about it
3. explain what the correct behavior may be
in that order. However, the issue template puts 1. after 3. Whenever I file a core bug report, it feels like the issue template works against me.
> Issue template: move reproduction steps to the top

- docs/pages/blog/2021-developer-survey-results.md
This PR addresses some user feedback regarding the [2021 developer survey results post](https://mui.com/blog/2021-developer-survey-results/).
The original draft misinterpreted the data from the question "How many web applications did you or your team deliver using MUI this year?" by mixing up the x and y axes. I've rewritten the text there to correct this.
https://deploy-preview-34291--material-ui.netlify.app/blog/2021-developer-survey-results/
> [blog] Correct 2021 survey data interpretation

- docs/data/joy/components/text-field/TextFieldUsage.js
- docs/data/joy/components/textarea/TextareaUsage.js
- packages/mui-joy/src/Input/Input.tsx
- packages/mui-joy/src/Textarea/Textarea.tsx
This PR preserves the same background when hovering on the `Input` or `Textarea`.
From the benchmarks, all the popular libraries don't have hovered background:
- https://developer.microsoft.com/en-us/fluentui#/controls/web/textfield
- https://mantine.dev/core/input/
- https://design-system-git-main-strapijs.vercel.app/?path=/story/design-system-components-field--base
- https://getbootstrap.com/docs/5.0/forms/form-control/
- https://chakra-ui.com/docs/components/input/usage
- https://react-spectrum.adobe.com/react-spectrum/TextField.html
- https://ant.design/components/input/#header
[**Before**](https://mui.com/joy-ui/react-textarea/):
https://user-images.githubusercontent.com/18292247/189567090-1932d084-021d-446c-9270-b58251fbcaf8.mov
When the decorators are actionable, the hovered …
> [Joy] Adjust the `Input` and `Textarea` styles

- docs/data/base/components/select/UnstyledSelectIntroduction.js
- packages/mui-base/src/SelectUnstyled/SelectUnstyled.tsx
- packages/mui-joy/src/Select/Select.tsx
- packages/mui-material/src/CardHeader/CardHeader.js
- packages/typescript-to-proptypes/src/parser.ts
- packages/typescript-to-proptypes/test/generic/input.d.ts
- packages/typescript-to-proptypes/test/generic/output.js
While working on X, I noticed that the generation of the proptypes does not work well in the following scenario:
```tsx
type Type = 'one' | 'two' | 'three'
interface ParentProps<T extends Type> {
A: T;
}
interface ChildProps extends ParentProps<'one' | 'two'> {}
export function Foo(props: ChildProps): JSX.Element;
// Should output:
Foo.propTypes = {
A: PropTypes.oneOf(['one', 'two']).isRequired,
};
// But outputs:
Foo.propTypes = {
A: PropTypes.oneOf(['one', 'two', 'three']).isRequired,
};
```
We even looses the optional in the following scenario:
```tsx
type Type = 'one' | 'two' | 'three'
interface ParentProps<T extends Type> {
A: T;
}
interface ChildProps extends Partial<ParentProps<'one' | 'two'>> {}
export function Foo(props: ChildProps): JSX.Element;
// Should output:
Foo.propTypes = …
```
> [core] In `typescript-to-proptypes`, respect the value pass to the generic

- docs/src/components/productX/XComponents.tsx
- docs/src/components/productX/XDateRangeDemo.tsx
- docs/src/components/productX/XTreeViewDemo.tsx
We used to see this:
https://62d59767934a0000083cd4e9--material-ui-docs.netlify.app/x/ (v5.9.1)
After #33585, we now have:
https://62deb307440fcb0008f9665d--material-ui-docs.netlify.app/x/ (v5.9.2)
This PR removes the custom style, to have the same section look like this: 
https://deploy-preview-34330--material-ui.netlify.app/x/
I found this by chance while we were talking with MUI X about the need to refresh this marketing page. The page was created a year ago, things are evolving on MUI X.
> [website] Fix MUI X subscribe email border style

- docs/pages/blog/2022-tenerife-retreat.md
- docs/pages/blog/first-look-at-joy.md
- docs/pages/blog/introducing-mui-base.md
- docs/pages/blog/making-customizable-components.md
- docs/pages/blog/mui-core-v5-migration-update.md
The PR started with https://github.com/mui/material-ui/pull/33778#discussion_r962994679, and then I moved to better handle some of https://www.notion.so/mui-org/Images-solution-30e78dbf24744ed5b570027656139092 for all the blog posts of the first page https://mui.com/blog/ with the hope it will server as an example for the future blog posts.
1. `![]()` has no use valid case.
2. images outside of the viewport should have `loading="lazy"`.
3. images should have `aspect-ratio` to avoid layout shift when loading.
> [blog] Improve image handling

- docs/data/material/getting-started/usage/usage.md
I wanted to link https://mui.com/material-ui/getting-started/usage/ to answer https://twitter.com/SergeyMoiseev/status/1571090668730347521 but couldn't because the use of MUI was confusing.
> [docs] Refine the use of MUI vs. Material UI

- docs/src/modules/components/AppLayoutDocs.js
- docs/src/modules/components/MarkdownDocs.js
- docs/src/modules/components/TopLayoutBlog.js
Same rationale as #32536. When sharing a page to a specific docs page, the social image creates confusion https://twitter.com/olivtassinari/status/1571093885644046339.
Going forward, I think that we have two opportunities to improve, by increasing effort & outcome:
1. Something like https://github.com/mui/material-ui/pull/32536#issuecomment-1120263622, one very low distraction illustration, like "Material UI", one per product
2. Something custom for each page https://www.notion.so/mui-org/Page-image-generator-75bc177fefe64c0b899a42a6f919a907
A bit related to #32181
> [docs] Improve social sharing of docs pages

- docs/data/material/experimental-api/css-variables/css-variables.md
- packages/mui-system/src/cssVars/getInitColorSchemeScript.test.js
- packages/mui-system/src/cssVars/getInitColorSchemeScript.tsx
~`enableSystem`~ has been replaced with `defaultMode` to make it possible to force the `dark` mode initially.
```diff
getInitColorSchemeScript({
-  enableSystem: true,
+  defaultMode: 'system',
})
```
---
Found the issue while writing the doc in #33958.
Currently, it is not possible to initially force `dark` mode. The fix is to follow the props in `CssVarsProvider` by replacing `enableSystem` with `defaultMode`.
```js
// developer can pick the default mode that they want
// This means the initial color scheme will be the same as user's system preference
getInitColorSchemeScript({ defaultMode: 'system' })
// This means the initial color scheme will be the dark color scheme
getInitColorSchemeScript({ defaultMode: 'dark' })
```
---
> [system] Replace `enableSystem` with `defaultMode`

- docs/pages/blog/date-pickers-stable-v5.md
I realized when adding the notification to the blog post, that it was shipped with an old date (Sep 5th).
The PR updates with the correct date of blog post release
> [blog] Update date on date pickers v5 release blog post

- docs/data/material/guides/styled-engine/styled-engine.md
In the Styled Engine Guide, there is an example of configuring an alias in webpack. The file shown is labeled `webpack.alias.js`; this PR updates it to `webpack.config.js`. [Preview link](https://deploy-preview-34446--material-ui.netlify.app/material-ui/guides/styled-engine/#npm)
I think the intent here is just to indicate "put this in your webpack config," and [`webpack.config.js` is the default webpack config file name](https://webpack.js.org/configuration). Additionally, the [webpack docs for resolve.alias](https://webpack.js.org/configuration/resolve/#resolvealias) show the configuration in `webpack.config.js`. Also, in trying out this config option I added it to my `webpack.config.js` and it succeeded.
There are a few references around the web to `webpack.alias.js`, but none in the …
> [docs] Fix webpack file name to the standard: `webpack.config.js`

- packages/mui-joy/src/Chip/Chip.test.js
- packages/mui-joy/src/Chip/Chip.tsx
- packages/mui-joy/src/Chip/ChipProps.ts
> [Joy][Chip] Fix unbinded `onClick` prop

- packages/mui-system/src/colorManipulator.js
- packages/mui-system/src/colorManipulator.test.js
> [system] Fix parsing of hsla colors in getLuminance

- docs/pages/material-ui/api/svg-icon.json
- docs/translations/api-docs/svg-icon/svg-icon.json
- packages/mui-joy/src/SvgIcon/SvgIcon.test.js
- packages/mui-joy/src/SvgIcon/SvgIcon.tsx
- packages/mui-material/src/SvgIcon/SvgIcon.js
- packages/mui-material/src/SvgIcon/SvgIcon.test.js
- packages/mui-material/src/SvgIcon/svgIconClasses.ts
Fixes #34056 
When a custom SVG icon is provided in components slot and the slot's `componentsProps` is defined with the `useSlotProps` hook, it should not override the `ownerState` of the internal SvgIcon.
The `styled` API does prevent forwarding `ownerState` of the hook, but if customizing components by other methods, the ownerState passed to the hook overrides the internal one of the SVG Icon.
Even if custom icon component is not provided, the `ownerState` passed to the hook is causing changes in the svgicon default styling.
---
Before: https://codesandbox.io/s/data-grid-community-forked-5hnr7p?file=/src/App.tsx
After: https://codesandbox.io/s/data-grid-community-forked-p1d7rr
> [SvgIcon] Fix passing an ownerState to SvgIcon changes the font size 

- packages/mui-material/src/styles/styled.spec.tsx
- packages/mui-styled-engine/src/index.d.ts
Related to https://github.com/mui/material-ui/issues/34387 I had to search second time on why the uknown was added, it will help us when preparing v6.
> [core] Document some types in @mui/styled-engine-sc

- docs/data/material/components/app-bar/app-bar.md
Signed-off-by: Dustin-Digitar <113573618+Dustin-Digitar@users.noreply.github.com>
Preview: https://deploy-preview-34479--material-ui.netlify.app/material-ui/react-app-bar/#back-to-top
> [docs] Fix typo in `Back to top` section in AppBar docs

- packages/mui-joy/src/Radio/Radio.test.js
- packages/mui-joy/src/Radio/Radio.tsx
> [Radio][Joy UI] spread `readOnly` and `required` to input

- packages/mui-joy/src/Checkbox/Checkbox.test.js
- packages/mui-joy/src/Checkbox/Checkbox.tsx
- packages/mui-joy/src/Checkbox/CheckboxProps.ts
> [Checkbox][Joy UI] spread `value`, `required`, and `readOnly` to input

- packages/mui-base/src/ListboxUnstyled/useListbox.ts
- packages/mui-base/src/ListboxUnstyled/useListbox.types.ts
- packages/mui-base/src/OptionUnstyled/OptionUnstyled.test.tsx
Mobile Chrome emulates onMouseOver when an option is tapped. This causes both mouseover and click actions to be dispatched next to each other. The MultiSelect behavior is broken in such case. This PR changes the mouseover to pointerover (which is not emulated when tapping on an element), preventing the problem.
Fixes #34151
> [MultiSelect][base] Require a single tap to select an item on mobile Chrome

- test/utils/createDOM.js
This logic was added in #31273. I'm testing that we no longer need it. I suspect that it was added to solve #33853. Removing it makes the test environment better capture the complexity of the production environments, it can also be seen as a test for #34027.
> [test] Set the URL to better match real environments

- packages/mui-lab/package.json
The `@mui/lab` package imports `@mui/types` package in its declaration files, so `@mui/types` should be a regular dependency instead of a devDependency.
```
ERROR in ../../.yarn/__virtual__/@mui-lab-virtual-b4b85e650c/0/cache/@mui-lab-npm-5.0.0-alpha.99-abf77ae8d8-db54edffbd.zip/node_modules/@mui/lab/TabList/TabList.d.ts:3:34
TS2307: Cannot find module '@mui/types' or its corresponding type declarations.
1 | import * as React from 'react';
2 | import { TabsTypeMap } from '@mui/material/Tabs';
> 3 | import { DistributiveOmit } from '@mui/types';
|                                  ^^^^^^^^^^^^
4 | import { OverridableComponent, OverrideProps } from '@mui/material/OverridableComponent';
5 |
6 | export interface TabListTypeMap<
ERROR in …
```
> [lab][deps] Move @mui/types to dependencies

- docs/data/material/migration/migration-v4/migrating-from-jss-pt.md
- docs/data/material/migration/migration-v4/migrating-from-jss-zh.md
- docs/data/material/migration/migration-v4/migrating-from-jss.md
Hello,  
I forget to remove instructions that are no longer required in MUI v4.  
It works as well if when you explicitely provide a cache but you don't need to. 
Best regards,
> [docs] Update the guide for migrating to TSS

- packages/mui-base/src/TextareaAutosize/TextareaAutosize.js
- test/e2e/fixtures/TextareaAutosize/TextareaAutosizeSuspense.tsx
- test/e2e/index.js
- test/e2e/index.test.ts
> [TextareaAutosize] Test for error when used with React 18 & Suspense

- packages/mui-material/src/Button/Button.js
- packages/mui-material/src/Checkbox/Checkbox.js
- packages/mui-material/src/DialogContentText/DialogContentText.js
- packages/mui-material/src/InputLabel/InputLabel.js
- packages/mui-material/src/InputLabel/InputLabel.test.js
- packages/mui-material/src/ListItemButton/ListItemButton.js
- packages/mui-material/src/MenuItem/MenuItem.js
- packages/mui-material/src/Radio/Radio.js
Hi @mnajdova,  
I'm sorry I didn't complete the job in [#33205](https://github.com/mui/material-ui/pull/33205), I did in this PR.  
Thanks a lot for reviewing,  
Best regards,
> [material] Make @emotion/* fully supported in all Material UI components

- docs/pages/careers.tsx
- docs/src/pages/careers/react-engineer-core.md
https://deploy-preview-34494--material-ui.netlify.app/careers/
> [website] Move the React Engineer role from open to next

- packages/mui-base/src/AutocompleteUnstyled/useAutocomplete.js
- packages/mui-base/src/AutocompleteUnstyled/useAutocomplete.test.js
> [Autocomplete] Skip filtering when list of options is loading

- docs/package.json
- yarn.lock
We moved from the v2 (`docsearch.js`) to the v3 (`@docsearch/react`). https://docsearch.algolia.com/docs/DocSearch-v3.
> [core] Remove outdated docsearch.js dependency

- CONTRIBUTING.md
Link in CONTRIBUTING.md was pointing to an old removed repository specific CODE_OF_CONDUCT.md file (#33702), changed the link to the global version
> [core] Fix link to CODE_OF_CONDUCT.md

- packages/mui-joy/src/Alert/alertClasses.ts
- packages/mui-joy/src/Badge/badgeClasses.ts
- packages/mui-joy/src/Chip/chipClasses.ts
**Problem**:
-> For Alert, Badge and Chip components, `variantPlain` classname is missing.
> [Joy] Fix `variantPlain` classname missing in few components

- docs/data/joy/getting-started/tutorial/LoginFinal.js
- docs/data/joy/getting-started/tutorial/tutorial.md
Part of #33998 
This PR revises and expands the Joy UI "Tutorial" page. The biggest changes include:
- expanded introduction
- embedded demo of the final product
- revised headers
- "Summary" and "Next steps" sections
- overhauled code snippets
- the way they were originally written, you couldn't use the **Copy** button efficiently. I edited them to optimize for this.
https://deploy-preview-34569--material-ui.netlify.app/joy-ui/getting-started/tutorial/
> [docs] Revise and expand Joy UI "Tutorial" doc

- docs/src/components/home/Hero.tsx
The date picker auto-focus causes the home page layout to shift.
https://user-images.githubusercontent.com/18292247/193400051-22fb3c26-a007-4853-9783-c1544350e0e8.mov
This is a temporary fix until we have a proper solution. We need to investigate further with the X team.
> [docs] Temporary remove date picker from home page

- packages/mui-material/src/Unstable_TrapFocus/index.d.ts
#34216 inadvertently introduced a breaking change by renaming a type re-exported from @mui/material.
This caused an issue in MUI X (https://github.com/mui/mui-x/issues/6308), as reported in https://github.com/mui/material-ui/issues/33966#issuecomment-1263210842.
This PR restores the previously exported `TrapFocusProps` type in @mui/material. @mui/base continues to export the renamed `FocusTrapProps`, as intended.
Technically, this is a breaking change in relation to @mui/material 5.10.7 and 5.10.8, but not a breaking change in relation to earlier versions.
cc @flaviendelangle
> [TrapFocus] Restore the previously exported type from @mui/material

- docs/src/modules/sandbox/Dependencies.ts
Since https://github.com/mui/mui-x/pull/5481 the bug is a lot more visible. When you export a codesandbox from https://mui.com/x/react-date-pickers/date-picker/#basic-usage
you will get https://codesandbox.io/s/3sem4m?file=/package.json:161-172
but this package doesn't exist. Dayjs already includes the types, proof: https://unpkg.com/browse/dayjs@1.11.5/index.d.ts.
--- 
I found this while I was doing a bit of support in https://groups.google.com/a/mui.com/g/x/c/xHe-_HUVhjc.
> [docs] Fix codesandbox export with dayjs

- docs/packages/markdown/loader.js
Changes introduced in #34243 made it impossible to run components docs locally on Windows due to differences in path delimiters.
This PR fixes the problem by replacing backslashes with slashes and recognizing the `:` character after a drive letter.
> [core] Fix markdown loader on Windows

- docs/data/joy/components/button/ButtonLoading.js
- docs/data/joy/components/button/ButtonLoading.tsx
- docs/data/joy/components/button/ButtonLoading.tsx.preview
- docs/data/joy/components/button/ButtonLoadingPosition.js
- docs/data/joy/components/button/ButtonLoadingPosition.tsx
- docs/data/joy/components/button/ButtonLoadingPosition.tsx.preview
- docs/data/joy/components/button/button.md
- packages/mui-joy/src/Button/Button.spec.tsx
- packages/mui-joy/src/Button/Button.test.js
- packages/mui-joy/src/Button/Button.tsx
- packages/mui-joy/src/Button/ButtonProps.ts
- packages/mui-joy/src/Button/buttonClasses.ts
Fixes: https://github.com/mui/material-ui/issues/33999
**Preview**: https://deploy-preview-34658--material-ui.netlify.app/joy-ui/react-button/#loading
> [Joy] Add button loading functionality

- docs/data/material/getting-started/templates/checkout/Checkout.js
- docs/data/material/getting-started/templates/checkout/Checkout.tsx
- docs/scripts/helpers.js
- docs/src/modules/components/AppNavDrawer.js
- docs/src/modules/utils/i18n.js
- docs/src/modules/utils/replaceUrl.ts
- examples/nextjs-with-typescript-v4-migration/pages/about.tsx
- examples/nextjs-with-typescript-v4-migration/pages/index.tsx
- examples/nextjs-with-typescript/pages/about.tsx
- examples/nextjs-with-typescript/pages/index.tsx
- packages/mui-base/src/utils/appendOwnerState.ts
> [core] Fix some upcoming eslint issues

- packages/mui-material/src/Popover/Popover.js
* #33308
* #33743 (probably)
Previously popovers could have been rendered before they were positioned, resulting in them briefly appearing in the top-left corner particularly on slower devices and with low `transitionDuration`. This PR hides the popover paper until positioning is complete.
On slower devices, the opening animation may be completely skipped since the animation would complete before positioning would finish. This can be demonstrated with the Chrome dev tools' CPU throttling feature. Due to the current way that popover is designed, there is a sort of catch-22 in which the the paper only mounts once the transition begins, but positioning can only occur after the paper mounts. Changing other parts of the code to get around that issue is certainly possible, but I have not …
> [Popover] Fix paper position flash on open

- packages/mui-system/src/palette.js
- packages/mui-system/src/palette.test.js
- packages/mui-system/src/style.d.ts
- packages/mui-system/src/style.js
- #31203
When `"grey"` is used as the value for a color prop in `sx`, a warning will now be printed to the console explaining the issue and a number of potential remedies.
Resolves #31203
> [system] Support CSS `grey` color in `sx`

- packages/mui-base/src/MultiSelectUnstyled/MultiSelectUnstyled.test.tsx
- packages/mui-base/src/MultiSelectUnstyled/MultiSelectUnstyled.tsx
- packages/mui-base/src/SelectUnstyled/SelectUnstyled.test.tsx
When a `renderValue` prop is used on a MultiSelectUnstyled, it gets propagated to the DOM causing console warnings. This PR fixes this problem.
> [MultiSelect][base] Prevent the renderValue prop from being propagated to the DOM

- docs/src/components/productX/XComponents.tsx
- docs/src/components/productX/XDateRangeDemo.tsx
Update landing page to display with date pickers availability.
https://deploy-preview-34750--material-ui.netlify.app/x/
There's a planned initiative this quarter to fully refactor the landing page. This is just a small update to clear any potential confusion about the availability of the date pickers.
> [website] Update the state of the date pickers on the landing page

- packages/mui-material/src/SwipeableDrawer/SwipeableDrawer.spec.ts
- packages/mui-material/src/styles/components.d.ts
Closes https://github.com/mui/material-ui/issues/34500
**This PR includes:**
- Make the component defaultProps overridable
**Codesandbox Before**:
- https://codesandbox.io/s/silent-flower-ysdx81
**Codesandbox After**:
- https://codesandbox.io/s/quizzical-lamarr-me5rcf
> [SwipeableDrawer] Make component `defaultProps` overridable

- dangerfile.js
It might be simpler than having to click on the Netlify status to find the preview URL. For the community, it might even make the difference between trying the preview out and not knowing it exists.
An alternative would be to enable this comment back (easy):
https://github.com/netlify/open-api/pull/394#issuecomment-1233209606. However, for maintainers that aren't using emails to manage their GitHub notifications, this would create even more noise than `mui-bot` already creates (with the email you can create a filter to delete the mui-bot & Netlify comment notification). Netlify's native comment also uses more vertical space.
> [core] Link Netlify in the danger comment

- docs/data/material/customization/how-to-customize/how-to-customize.md
- docs/data/material/experimental-api/css-theme-variables/migration.md
- docs/data/material/experimental-api/css-theme-variables/overview.md
- docs/data/system/getting-started/the-sx-prop/the-sx-prop.md
- docs/data/system/spacing/spacing.md
A small detail I saw while reading https://twitter.com/siriwatknp/status/1579729991642009600. This scrollbar is now gone. I have fixed a few out of sync with the standard syntax that I could notice along the way, quick wins.
> [docs] Avoid scrollbar in the code demos

- docs/pages/versions.js
The `/versions` error "API exceeds limit" is blocking a lot of PRs recently. I think we can remove the authorization for now and I will open another PR to have an appropriate solution.
The interesting part is that even though the authorization is removed, the API call still works 🤷
---
> [core] Temporary remove the authorization

- docs/data/joy/components/switch/switch.md
This fixes a few typos within and around some of the code examples in the Joy UI Switch docs.
> [docs] Fix typos in Joy UI Switch

- .eslintrc.js
- docs/data/material/guides/routing/ListRouter.js
- docs/data/material/guides/routing/ListRouter.tsx
- packages/mui-base/src/BadgeUnstyled/BadgeUnstyled.spec.tsx
- packages/mui-base/src/ButtonUnstyled/ButtonUnstyled.spec.tsx
- packages/mui-base/src/InputUnstyled/InputUnstyled.spec.tsx
- packages/mui-base/src/MenuItemUnstyled/MenuItemUnstyled.spec.tsx
- packages/mui-base/src/MenuUnstyled/MenuUnstyled.spec.tsx
- packages/mui-base/src/ModalUnstyled/ModalUnstyled.spec.tsx
- packages/mui-base/src/MultiSelectUnstyled/MultiSelectUnstyled.spec.tsx
- packages/mui-base/src/OptionGroupUnstyled/OptionGroupUnstyled.spec.tsx
- packages/mui-base/src/OptionUnstyled/OptionUnstyled.spec.tsx
- packages/mui-base/src/PopperUnstyled/PopperUnstyled.spec.tsx
- packages/mui-base/src/SelectUnstyled/SelectUnstyled.spec.tsx
- packages/mui-base/src/SliderUnstyled/SliderUnstyled.spec.tsx
- packages/mui-base/src/SwitchUnstyled/SwitchUnstyled.spec.tsx
- packages/mui-base/src/TabPanelUnstyled/TabPanelUnstyled.spec.tsx
- packages/mui-base/src/TabUnstyled/TabUnstyled.spec.tsx
- packages/mui-base/src/TablePaginationUnstyled/TablePaginationActionsUnstyled.spec.tsx
- packages/mui-base/src/TabsListUnstyled/TabsListUnstyled.spec.tsx
- packages/mui-base/src/TabsUnstyled/TabsUnstyled.spec.tsx
- packages/mui-material-next/src/Button/Button.spec.tsx
- packages/mui-material/src/Button/Button.spec.tsx
- packages/mui-material/src/DialogContentText/DialogContentText.spec.tsx
- packages/mui-material/src/Typography/typography.spec.tsx
- packages/mui-material/test/typescript/components.spec.tsx
Enables [`react/no-unstable-nested-components`](https://github.com/jsx-eslint/eslint-plugin-react/blob/b52e0caf98cff122da9e3a92dacac355d3fe2e48/docs/rules/no-unstable-nested-components.md)
This rule is likely either [going to be in the recommended preset or move to rules-of-hooks](https://github.com/jsx-eslint/eslint-plugin-react/pull/3444). Wanted to see how this rule performs on a medium size repo and the errors all look legitimate to me (although it's all just test-code).
> test: Enable `react/no-unstable-nested-components`

- docs/data/base/components/menu/menu-pt.md
- docs/data/base/components/menu/menu-zh.md
- docs/data/base/components/menu/menu.md
- docs/data/base/components/tabs/tabs.md
- docs/data/joy/components/chip/chip-zh.md
- docs/data/joy/components/chip/chip.md
This PR fixes a handful of typos in the following docs:
- Base
- Menu (95e97e2b49b3ed5177c54a647689d3b0e4ebf113)
- Tabs (c63624439032502308dbde16756ef97dd1563cbc)
- Joy UI
-  Chip (02759de9bfec5cde842a86b7da3e9642684986cc)
> [docs] Fix typos in Base (Menu, Tabs) and Joy UI (Chip)

- docs/src/BrandingCssVarsProvider.tsx
From https://github.com/mui/material-ui/pull/33545#issuecomment-1282948812.
I guess this is a bug on Safari and Firefox because the `color: initial` should use the system [`CanvasText` ](https://www.w3.org/TR/css-color-4/#valdef-system-color-canvastext) color but somehow it returns black (even though the `color-scheme: dark`).
Reference: https://www.w3.org/TR/css-color-4/#changes-from-20191105
Force color to `theme.common.white` to make the color consistent across browsers.
---
I will merge the PR once the CIs are green and make a hotfix deployment.
> [docs] Replace initial value with theme white

- .github/workflows/check-if-pr-has-label.yml
- .github/workflows/maintenance.yml
- .github/workflows/mark-duplicate.yml
- .github/workflows/no-response.yml
- .github/workflows/support-stackoverflow.yml
See https://github.com/mui/mui-x/pull/6396 for the problem it solves. It's part of https://securityscorecards.dev/ and our effort to sell to larger companies.
> [core] Harden GitHub Actions permissions

- packages/mui-codemod/src/v1.0.0/color-imports.js
- packages/mui-codemod/src/v5.0.0/jss-to-styled.test/seventh.actual.js
- packages/mui-codemod/src/v5.0.0/jss-to-styled.test/seventh.expected.js
This is a quick follow-up on #34707. It should close these errors: https://github.com/mui/material-ui/security/code-scanning.
> [core] Fix a few CodeQL errors

- packages/mui-joy/src/CircularProgress/CircularProgress.test.tsx
- packages/mui-joy/src/CircularProgress/CircularProgress.tsx
- packages/mui-joy/src/CircularProgress/circularProgressClasses.ts
**Problem**:
- classname "indeterminate" was being applied when `determinate` is `true`
**Solution**:
- Apply `determinate` classname when `determinate` is `true`
- Add test to prevent the same bug
> [CircularProgress][joy] Fix classnames and add test

- packages/mui-joy/src/Alert/Alert.tsx
- packages/mui-joy/src/Badge/Badge.tsx
- packages/mui-joy/src/Breadcrumbs/Breadcrumbs.tsx
- packages/mui-joy/src/FormControl/FormControl.tsx
- packages/mui-joy/src/ModalClose/ModalClose.tsx
- packages/mui-joy/src/TabPanel/TabPanel.tsx
- Allow `PropTypes.string` in Joy `Alert`, `Badge`, `Breadcrumbs`, `TabPanel`, `ModalClose`, `FormControl` components
> [Joy] Allow string type for `size` prop in components

- docs/pages/base/api/modal-unstyled.json
- docs/pages/base/api/popper-unstyled.json
- docs/pages/base/api/textarea-autosize.json
- packages/mui-base/src/ModalUnstyled/ModalUnstyled.js
- packages/mui-base/src/ModalUnstyled/ModalUnstyled.test.js
- packages/mui-base/src/PopperUnstyled/PopperUnstyled.test.js
- packages/mui-base/src/TabPanelUnstyled/TabPanelUnstyled.test.tsx
- packages/mui-base/src/TabUnstyled/TabUnstyled.test.tsx
- packages/mui-base/src/TabsListUnstyled/TabsListUnstyled.test.tsx
- packages/mui-base/src/TextareaAutosize/TextareaAutosize.test.js
- test/utils/describeConformanceUnstyled.tsx
Unstyled Modal and Popper weren't using all relevant `describeConformanceUnstyled`'s tests and TextareaAutosize was still using Material UI's `describeConformance` to test basic behavior. This PR fixes these issues.
An issue with the Unstyled Modal was found along the way. It incorrectly prioritized `slots.root` over `component`. Fixing this is a breaking change in Base, however, it should not affect most developers, as setting both `component` and `slots.root` makes no sense.
This change doesn't affect the Material UI's Modal as it has its own logic for choosing between `slots.root` and `component`.
This PR also improves how `describeConformanceUnstyled` works with portaled components and improves error display in the ownerStatePropagation test.
**Breaking change**
Prior to this change, …
> [test] Test all Base components with describeConformanceUnstyled

- .markdownlint-cli2.cjs
- CHANGELOG.md
- docs/data/joy/getting-started/usage/usage.md
- docs/data/material/experimental-api/css-variables/css-variables.md
- docs/data/material/getting-started/faq/faq.md
- docs/data/material/guides/minimizing-bundle-size/minimizing-bundle-size.md
- docs/data/material/migration/migration-v0x/migration-v0x.md
- docs/data/material/migration/migration-v3/migration-v3.md
- docs/data/material/migration/migration-v4/migrating-from-jss.md
- docs/data/material/migration/migration-v4/v5-component-changes.md
- docs/data/material/migration/migration-v4/v5-style-changes.md
- packages/markdownlint-rule-mui/git-diff.js
- packages/mui-codemod/README.md
Enforce the git diff format with a custom rule for https://github.com/DavidAnson/markdownlint. It's simply about respecting `git show` output. The new rule is in `packages/markdownlint-rule-mui/git-diff.js`. I felt that I was frequently leaving comments about this aspect, this will save me time 😁.
The discussion in https://github.com/mui/mui-x/pull/6523#discussion_r996671316 covers a bit more the value of it.
> [docs] Enforce correct git diff format

- .markdownlint-cli2.cjs
- CHANGELOG.md
- docs/data/material/components/material-icons/material-icons.md
- docs/data/material/guides/interoperability/interoperability.md
- docs/pages/blog/mui-x-v6-alpha-zero.md
- packages/markdownlint-rule-mui/straight-quotes.js
It's a continuation of this discussion https://github.com/mui/material-ui/pull/34686. The value is about being able to more accurately understand how the markdown will render. A double space for adding a line break is almost invisible during the PR reviews but `\` is visible.
> [docs] Enforce no trailing spaces

- crowdin.yml
If we ever resume work with Crowdin, this change should save us the need to do:
#34851
The docs: https://developer.crowdin.com/configuration-file/.
> [docs] Polish Crowdin config

- docs/pages/material-ui/api/input-base.json
- docs/translations/api-docs/input-base/input-base.json
- packages/mui-material/src/InputBase/InputBase.d.ts
- packages/mui-material/src/InputBase/InputBase.js
- packages/mui-material/src/InputBase/InputBase.spec.tsx
Hi, I was forced to cast `onInvalid` handler to `React.FormEventHandler<HTMLDivElement>` to please tsc.
This shouldn't be the case as it is applied to the inner `InputComponent`
regards,
Nicolas Le Cam
> InputBase: change onInvalid handler to use HTMLInputElement | HTMLTextAreaElement Element type

- docs/data/joy/guides/applying-dark-mode/applying-dark-mode.md
The description for Gatsby  mentions Next.js instead of Gatsby
> [docs] Gatsby Description in Joy dark-mode

- docs/data/material/customization/color/ColorTool.js
Fixes https://github.com/mui/material-ui/issues/34865
Preview: https://deploy-preview-34866--material-ui.netlify.app/material-ui/customization/color/#playground
Before:
After:
> [docs] Fix inconsistent theme colors when applying custom colors in playground

- packages/mui-material/src/SwipeableDrawer/SwipeableDrawer.js
- packages/mui-material/src/SwipeableDrawer/SwipeableDrawer.test.js
Fixes https://github.com/mui/material-ui/issues/30414
Steps to reproduce:
1. Open the sandbox
2. Open the rendered demo in new tab, inspect element and change the device to mobile
3. Try swapping the drawer and you will notice the two problems mentioned in the issue:
- Discovery opens drawer completely
- Partially opened drawer (> hysteresis) is not opened completely (it gets stuck at the position it was when the touch move ended)
❌ Current master [Sandbox](https://codesandbox.io/s/kd0jb8?file=/demo.tsx)  
✅ This PR [Sandbox](https://codesandbox.io/s/7qkr9k?file=/demo.tsx)
Not happy about the `keepMounted`, but if that is not set, the `paperRef.current` is `undefined` when the touch start event on the body is invoked. At first I thought using `flushAsync` on the set state before the check …
> [SwipeableDrawer] Fix React 18 issues

- docs/src/components/footer/EmailSubscribe.tsx
The issue can be seen at the bottom of any blog post, e.g. https://mui.com/blog/mui-x-v6-alpha-zero/
I have used the opportunity to fix the autofill style on Chrome:
> [website] Fix subscribe input with Safari

- docs/src/modules/components/DiamondSponsors.js
We might as well not set the width:
https://validator.w3.org/nu/?doc=https%3A%2F%2Fmui.com%2Fmaterial-ui%2Freact-skeleton%2F
Preview: https://deploy-preview-34860--material-ui.netlify.app/material-ui/getting-started/overview/
> [core] Fix HTML validation error

- docs/src/components/icon/IconImage.tsx
Found this issue while [migrating pages to CSS theme variables](https://github.com/mui/material-ui/issues/34880). The `Box` defaults to div which can not be used inside a Typography.
> [website] Use `span` for icon image

- packages/mui-base/src/ModalUnstyled/ModalManager.ts
- packages/mui-base/src/utils/appendOwnerState.ts
- packages/mui-codemod/src/v5.0.0/jss-to-styled.js
- packages/mui-material-next/src/Button/TouchRipple.js
- packages/mui-material/src/ButtonBase/TouchRipple.js
- packages/typescript-to-proptypes/src/injector.ts
Fix `@typescript-eslint/default-param-last` issues from https://github.com/mui/material-ui/pull/34642/
> [core] Fix @typescript-eslint/default-param-last issues

- docs/next.config.js
- docs/pages/versions.js
A continuation of https://github.com/mui/material-ui/pull/34796#issuecomment-1287480913, it broke the deployment of a hotfix. 
To fix this, I have followed: https://docs.github.com/en/rest/overview/other-authentication-methods#via-personal-access-tokens.
> [core] Fix docs GitHub API rate limit

- .github/ISSUE_TEMPLATE/1.bug.yml
An attempt at https://www.notion.so/mui-org/Weekly-meeting-2022-10-18-0566064ded784ef786b163b1c8dff280#3ff2cf52fdbf4bdf86c00e287e74b122.
**Before**
**After**
> [core] Make the reproduction more important in the bug template

- docs/src/modules/components/AppSearch.js
Safari adds 2px of margin on the `<button>` by default, which leads to the following:
Eww, it feels off, it also leads to a layout shift when loading.
We need to reset the margin. We might want to revamp how we handle the CssBaseline to take care of this. I shouldn't have to do this change. For example, normalize.css takes care of it: https://github.com/necolas/normalize.css/blob/fc091cce1534909334c1911709a39c22d406977b/normalize.css#L157. I have added the idea to #30660 for v6.
> [docs] Fix Safari button misalignment

- docs/pages/_document.js
- docs/src/modules/components/GoogleAnalytics.js
- docs/src/modules/components/TopLayoutBlog.js
- docs/src/modules/utils/helpers.ts
I saw this during the review of #34325. Open http://0.0.0.0:3000/blog/mui-x-v6-alpha-zero/#whats-the-plan-to-get-to-a-stable-release and you will get and hydration mismatch error:
A git diff of the server output with the client output returns:
https://github.com/vercel/next.js/issues/25202 explains what's going on.
> [blog] Fix hydration mistmatch

- .circleci/config.yml
- package.json
- packages/mui-material/src/IconButton/IconButton.test.js
- test/karma.conf.js
- yarn.lock
Firefox seems to disconnect quite often looking at the CI runs in https://github.com/mui/material-ui/commits/master, e.g. https://app.circleci.com/pipelines/github/mui/material-ui/82679/workflows/2da72430-6074-47cb-8bbe-e959f815d794/jobs/437658 so why not run Firefox in CircleCI. The one limitation is that we run the latest version but 🤷‍♂️
Firefox is also slow on BrowserStack relative to the others, maybe why it's unstable:
https://automate.browserstack.com/dashboard/v2/builds/db108dc8dfacc0894749d3eac1271e4d8da8ac4c
> [test] Move Firefox tests to CircleCI

- docs/packages/markdown/loader.js
- docs/scripts/reportBrokenLinks.js
- docs/src/modules/components/Demo.js
- docs/src/modules/components/DemoSandboxed.js
- docs/src/modules/components/DemoToolbar.js
- docs/src/modules/components/MarkdownDocs.js
- docs/src/modules/utils/CodeCopy.tsx
- packages/mui-envinfo/envinfo.test.js
- packages/mui-material/scripts/rollup.config.js
- test/cli.js
Extracted from #34870 as they are improvements on their own.
> [core] A couple of simply fixes from #34870

- docs/data/material/pages.ts
- docs/translations/translations.json
Changed the spelling on the documentation site. The URL with [https://mui.com/material-ui/react-bottom-navigation/](https://mui.com/material-ui/react-bottom-navigation/)
had button navigation as a sub-heading.
originally it should be the bottom navigation subheading..
> [docs] Fix spelling mistake

- docs/src/components/home/GetStartedButtons.tsx
To reproduce the issue: https://validator.w3.org/nu/?doc=https%3A%2F%2Fmui.com%2F
We mixed `display: none` with `visibility: hidden`, the CSS is wrong. As it turns out, we don't need to create a Box, the performance should be better without it.
> [website] Remove one DOM node

- docs/data/material/components/radio-buttons/CustomizedRadios.js
- docs/data/material/components/radio-buttons/CustomizedRadios.tsx
- packages/mui-material/src/Radio/Radio.js
This is follow-up of #16866. As per this [comment](https://github.com/mui/material-ui/issues/16866#issuecomment-888439054), checkbox has been done, and I have checked that IconButton is also done [here](https://github.com/mui/material-ui/pull/29298). Only the Radio component left to be handled.
> [Radio] Skip default hover style when disableRipple is set

- docs/public/static/styles/prism-okaidia.css
- docs/src/components/home/AdvancedShowcase.tsx
- docs/src/components/home/CoreShowcase.tsx
- docs/src/components/markdown/MarkdownElement.tsx
- docs/src/modules/components/MarkdownElement.js
- docs/src/modules/components/TopLayoutBlog.js
The fix relies on https://github.com/necolas/normalize.css/blob/master/normalize.css#L102
**Before**
https://6357aef90039260008eccf21--material-ui-docs.netlify.app/material-ui/react-skeleton/#usage
**After**
https://deploy-preview-34859--material-ui.netlify.app/material-ui/react-skeleton/#usage
Because iOS & blog posts 🙈:
> [docs] Fix Safari code font size

- docs/src/createEmotionCache.ts
This fixes a regression introduced in #33545. I have notice it when I was looking at the screenshot of #34859, it looked wrong, the header background is meant to be blurred:
Why does this happen? Because of https://github.com/emotion-js/emotion/blob/d8a13bcae81812d3dff643bcf446709f965f0909/packages/cache/src/index.js#L84. My end goal is to get a nice reading experience for the blog on iOS.
> [docs] Fix missing emotion prefixes

- docs/packages/markdown/parseMarkdown.js
- docs/src/modules/components/HighlightedCode.js
I suspect that it yields a better experience in lowercase:
**Before**
https://6357aef90039260008eccf21--material-ui-docs.netlify.app/material-ui/react-avatar/#image-avatars
**After**
https://deploy-preview-34950--material-ui.netlify.app/material-ui/react-avatar/#image-avatars
> [docs] Improve UI display for copy code

- docs/pages/pricing.tsx
- docs/src/components/home/Testimonials.tsx
- docs/src/components/pricing/EarlyBird.tsx
- docs/src/components/pricing/FAQ.tsx
- docs/src/components/pricing/HeroPricing.tsx
- docs/src/components/pricing/PricingList.tsx
- docs/src/components/pricing/PricingTable.tsx
> [website] Migrate Pricing page to use CSS theme variables

- packages/mui-base/src/FormControlUnstyled/FormControlUnstyled.tsx
Extracting from https://github.com/mui/material-ui/pull/34849#discussion_r1007890250 just in case. I altered the suggestion to have the effect run less frequently, and to have the focus state update in the same render as the disabled state
> [base] Avoid calling setstate during renders

- docs/src/BrandingProvider.tsx
- docs/src/modules/brandingTheme.ts
No need to create the same theme over and over again between each `BrandingProvider` instance. In the Joy UI pages, we mount this component a lot of times which can lead to a lot of console.log when you try to debug it.
---
**Off-topic** it seems that there are way too many ThemeProvider used in the pages, but it's a different problem, so I'm not looking into it. I think that what we need is:
1. One Material UI customized branding theme provider at the root of the page (not inside `_app`)
2. One raw Material UI theme provider for each Material UI demos, one raw Joy UI theme provider for each Joy UI demo, etc.
> [core] Create the docs theme once

- examples/nextjs-with-typescript/package.json
- examples/nextjs-with-typescript/pages/_document.tsx
- examples/nextjs-with-typescript/src/theme.ts
- examples/nextjs/package.json
- examples/nextjs/pages/_document.js
- examples/nextjs/src/theme.js
Relates to #34898
Next.js v13 introduces a brand new font system which automatically optimizes your fonts and makes using Google fonts super convinient. This feature is currently in beta
[Next.js v13 release blog post](https://nextjs.org/blog/next-13#breaking-changes)
[Next.js font optimization docs](https://beta.nextjs.org/docs/optimizing/fonts)
[@next/font API reference](https://beta.nextjs.org/docs/api-reference/components/font)
This feature is currently in beta but could improve the font loading experience already today. Multiple fontWeigths aren't yet supported without multiple individual font variables, https://github.com/vercel/next.js/issues/41969
If we feel like the pull request is too early and should wait for a stable `@next/font` release then this could be turned into a draft …
> [examples] Next.js examples v13 - fonts

- docs/data/material/guides/api/api.md
Close #34895. It's a quick iteration. From the outcome of the meeting, it seemed that the conclusion was: pick what's most consistent with the rest of the codebase. This definitely feels like what the rest of the codebase is doing.
Preview: https://deploy-preview-34972--material-ui.netlify.app/material-ui/guides/api/#prop-naming
---
Regarding https://github.com/mui/material-ui/issues/34895#issuecomment-1295913044, I increasingly feel that A > B.
> [docs] New API design rule disabled > disable

- docs/src/components/markdown/MarkdownElement.tsx
- docs/src/modules/components/AppTableOfContents.js
- docs/src/modules/components/MarkdownElement.js
We had a regression in the RTL handling of the code blocks from #15996 with the migration from JSS to emotion. 
Emotion swaps the direction in RTL, so we disable it to fix. The main value isn't to fix the RTL but to test that it can be fixed. I had to use https://github.com/styled-components/stylis-plugin-rtl/issues/24#issuecomment-1126894682 to make it work.
**Before**
https://6357aef90039260008eccf21--material-ui-docs.netlify.app/material-ui/react-avatar/#image-avatars
**After**
https://deploy-preview-34951--material-ui.netlify.app/material-ui/react-avatar/#image-avatars
> [docs] Fix code display in RTL

- docs/src/modules/brandingTheme.ts
The regression was introduced in https://github.com/mui/material-ui/pull/34954/files#r1008895718. It wasn't such a good idea.
Instead, we can use https://reactjs.org/docs/higher-order-components.html, https://beta.nextjs.org/docs/optimizing/images, https://beta.reactjs.org/learn/state-as-a-snapshot, https://tailwindcss.com/docs/installation, VS Code font families as benchmarks for what might look best
Before: https://master--material-ui.netlify.app/material-ui/react-button/#basic-button
After: https://deploy-preview-35027--material-ui.netlify.app/material-ui/react-button/#basic-button
> [docs] Improve code font family

- docs/src/modules/brandingTheme.ts
Act on https://github.com/mui/material-ui/pull/35027#issuecomment-1307291985. I think that we have it right this time on macOS and Windows. We match the default font on VS Code.
Regarding Linux, I'm not sure. @flaviendelangle As you are on Linux, do you see changes between 
Before: https://631f4503cb19a90009794dfc--material-ui-docs.netlify.app/material-ui/react-alert/#basic-alerts
After: https://deploy-preview-35053--material-ui.netlify.app/material-ui/react-alert/#basic-alerts?
I'm adding 3 reviewers, each on a different platform.
---
Off-topic, I saw a few interesting custom fonts used during my benchmark:
- Replit: `ReplitHack`
- Codesandbox: https://www.monolisa.dev/
- Tailwind CSS: https://github.com/tonsky/FiraCode
> [docs] Improve code font family v2

- .github/workflows/ci-check.yml
From the [docs](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks), "Make sure that the name key and required job name in both the workflow files are the same".
I hope I got it right this time to match the [main CI](https://github.com/siriwatknp/material-ui/blob/5ce57e9b874447f942a2ef48d1d557fab383f3f9/.github/workflows/ci.yml).
> [core] Fix job name to match the CI

- docs/src/modules/components/DemoEditor.tsx
close #35095
This is a follow-up on #34870, fixing this bug:
1. Open https://mui.com/material-ui/react-tabs/#basic-tabs, e.g. Chrome (I'm using Brave)
2. Turn the dark mode on
3.
https://user-images.githubusercontent.com/19550456/200823731-69ffddf1-6054-4c9c-82c1-2c015590c448.mov
The solution is to move the style override to the same `styled()` element so that emotion can inject the styles in the right order in the DOM.
https://deploy-preview-35064--material-ui.netlify.app/material-ui/react-tabs/#basic-tabs
> [docs] Fix scroll issue on expanded live demos

- docs/pages/core.tsx
- docs/pages/design-kits.tsx
- docs/pages/x.tsx
- docs/src/layouts/AppHeader.tsx
- Modified AppHeader.tsx to detect the current product and link the github icon to the appropriate repository.
Fixes #34336 
A continuation of #34889
> [website] Link respective repositories in product pages

- docs/src/modules/components/Demo.js
Fix issue 2 reported in https://github.com/mui/material-ui/pull/34870#issuecomment-1307966805. To reproduce:
1. Open https://mui.com/material-ui/react-switch/#basic-switches
2. Enjoy, the switch shouldn't change its state
This is particularly a bad UX on the data grid demos, where you most often need to open the demos, and where you lose the state of what you were looking at on the grid. 
https://deploy-preview-35106--material-ui.netlify.app/material-ui/react-switch/#basic-switches
> [docs] Fix bugs with live edit demos

- packages/mui-joy/src/index.ts
This pull request adds `FormControl`, `LinearProgress` and `ListSubheader` to the `@mui/joy` index so they can be exported from it.
```diff
- export FormControl from '@mui/joy/FormControl';
- export LinearProgress from '@mui/joy/LinearProgress';
- export ListSubheader from '@mui/joy/ListSubheader';
+ export { FormControl, LinearProgress, ListSubheader } from '@mui/joy';
```
It also moves some of the exports to be in alphabetical order like all others.
I couldn't find any discussion or reasoning on why these components weren't being exported from here, so my appologies if it has a reason.
> [Joy] Export `FormControl`, `LinearProgress` and `ListSubheader` components from `@mui/joy`

- docs/src/layouts/AppHeader.tsx
- docs/src/modules/components/AppFrame.js
A visual bug that I saw on https://mui.com/blog/date-pickers-stable-v5/
**Before**
**After**
The dark background color leaks too much into the app bar, reducing the opacity helps, I'm not sure that I went far enough, but at least, this feels already a step forward.
> [website] Improve visual design app bar

- packages/mui-joy/src/Autocomplete/Autocomplete.spec.tsx
- packages/mui-joy/src/Autocomplete/Autocomplete.tsx
- packages/mui-joy/src/Autocomplete/AutocompleteProps.ts
Remove outdated `AutocompleteRenderInputParams` and get rid of typecasting.
> [Autocomplete][Joy] Fix types

- docs/src/modules/components/AppFrame.js
This PR is just a follow-up to [this one](https://github.com/mui/material-ui/pull/35111#issuecomment-1315251821) where we adjust the website _and_ documentation backdrop filter to alleviate contrast a bit.
> [docs] Make navbar backdrop filter consistent with website

- docs/data/joy/components/avatar/FallbackAvatars.js
- docs/data/joy/components/avatar/FallbackAvatars.tsx
- docs/data/joy/components/avatar/FallbackAvatars.tsx.preview
- docs/data/joy/components/avatar/avatar.md
Part of #33998
This PR revises the Joy UI "Avatar" component page.
- style and grammar changes throughout
- added info on basic/default usage and component Anatomy
- rearranged a few sections
I also added a new kind of `h2` to this page, which I haven't tried elsewhere: **Usage with [some other component]**. I think this helps to differentiate the content from what would otherwise fall under **Customization**, and hopefully makes it easier for users to find. cc @oliviertassinari do you think this pattern would work in the Material UI docs as well?
> [docs] Revise the Joy UI "Avatar" component page

- docs/src/modules/components/Demo.js
A continuation on #34870.
While I using the live environment (for a real use case), I realize that the UX wasn't great. See this reproduction:
1. Open https://mui.com/material-ui/react-avatar/#letter-avatars
2. Click on "Show the full source" button
3. Make a change
4. Press <kbd>Cmd</kbd>+<kbd>Z</kbd> (undo)
5. 💥
I went with the YOLO solution. The clean solution would have been to store the [`session`](https://github.com/react-simple-code-editor/react-simple-code-editor/blob/4065fa6da6b7ca5eefc660b151fe5ab8b1a740cf/src/index.tsx#L497) between each mode and to restore it, but this feels overkill.
**Before**
https://user-images.githubusercontent.com/3165635/202039207-8a2ccbb1-deb0-40c8-9db2-9f98a5e337c5.mov
**After**
https://user-images.githubusercontent.com/3165635/202039306-d7c67fb2-4dcc- …
> [docs] Fix undo/redo in live editor

- docs/src/modules/components/MarkdownElement.js
**Preview**: https://deploy-preview-35179--material-ui.netlify.app/material-ui/api/alert/
Reported in https://github.com/mui/material-ui/pull/34976#issuecomment-1317785335.
> @siriwatknp I have found a regression from this PR (looking a bit at https://mui-org.slack.com/archives/C042VP80PT5/p1667372692296329):
> 
> The commit on master just before this PR: https://636d3dbaea7a9900083c33e1--material-ui.netlify.app/material-ui/api/alert/
> 
> <img alt="Screenshot 2022-11-16 at 23 33 37" width="774" src="https://user-images.githubusercontent.com/3165635/202309100-224a5a3e-d967-436e-a9ba-2147b4554266.png">
> 
> This PR: https://deploy-preview-34976--material-ui.netlify.app/material-ui/api/alert/
> 
> <img alt="Screenshot 2022-11-16 at 23 33 43" width="771" …
> [docs] Hotfix missing styles in dark mode

- docs/translations/api-docs/input-unstyled/input-unstyled.json
- packages/mui-base/src/InputUnstyled/InputUnstyled.tsx
- packages/mui-base/src/InputUnstyled/InputUnstyled.types.ts
- packages/mui-base/src/InputUnstyled/useInput.types.ts
It wasn't clear from the docs how the `error` prop affects the rendering of the Unstyled Input.
We've had a piece of feedback on our docs proving that this could be a problem for our users. This PR explains what is the effect of using this prop.
> [docs] Explain how the `error` prop works in the Unstyled Input

- .circleci/config.yml
Due to the recent changes in how Prettier is executed (#34062), the CI step does not fail if badly formatted code is present. This PR restores the previous behavior.
> [core] Ensure that prettier CI step fails when code is badly formatted

- docs/data/material/guides/pickers-migration/pickers-migration.md
Fix https://twitter.com/abcdee_p/status/1593182114257592321
preview: https://deploy-preview-35189--material-ui.netlify.app/material-ui/guides/pickers-migration/
> [docs] Inform that pickers are in X repository

- packages/mui-base/src/MultiSelectUnstyled/MultiSelectUnstyled.test.tsx
- packages/mui-base/src/SelectUnstyled/SelectUnstyled.test.tsx
- packages/mui-base/src/SelectUnstyled/useSelect.ts
- packages/mui-base/test/integration/SelectUnstyled.test.tsx
- packages/mui-joy/src/FormControl/FormControl.test.tsx
- packages/mui-joy/src/Select/Select.test.tsx
Adds the role=combobox and aria-controls attributes to the unstyled select and multi-select (implemented in the useSelect hook), as required in WAI-ARIA 1.2 (https://www.w3.org/TR/wai-aria-1.2/#combobox).
@siriwatknp This change affected the Joy's Select tests, as the component has a different role now (`combobox` instead of `button`).
Side note:
I'm amazed by how good the GitHub copilot is. All the tests in SelectUnstyled.test.tsx were generated by it and required only minor changes.
> [Select][base] Add attributes to conform with ARIA 1.2 

- docs/pages/experiments/index.js
- docs/public/_headers
We don't need these pages, e.g. https://deploy-preview-35173--material-ui.netlify.app/performance/table-raw/ in the index or Google to spend our crawling budget on them. The goal is to be able to add them and not have to care in any way that these pages exist.
Why work on this? I saw https://search.google.com/search-console/index/drilldown?resource_id=sc-domain:mui.com&item_key=CAMYEyAC, it seems to be something that can be a quick win.
> [website] Disable SEO for performance pages

- docs/next.config.js
- docs/nextConfigDocsInfra.js
- docs/pages/experiments/index.js
- docs/public/_headers
> [website] Exclude experiment pages in production

- docs/pages/_document.js
- docs/src/BrandingCssVarsProvider.tsx
- docs/src/components/header/ThemeModeToggle.tsx
On https://mui.com/material-ui/getting-started/overview/, when setting mode as `system` (user's preference is "dark") and goto the homepage the mode toggle appearance is incorrect.
https://user-images.githubusercontent.com/18292247/202992090-5a58e859-afb2-4939-b56b-54ebd3e531c3.mov
Use the `systemMode` to determine if the actual mode is `light` or `dark`.
https://user-images.githubusercontent.com/18292247/202995814-df6937e0-a535-4990-bc27-4ce41ab5afcc.mov
> [website] Fix theme mode toggle state

- docs/src/modules/components/AppTableOfContents.js
In https://mui.com/x/introduction/licensing/#validation-failures, I'm always a bit confused about whether I'm at the bottom of the TOCs or not. I think that it's because I can't clearly see that there aren't any more items on the list.
**Before**
**After**
> [docs] Fix confusion in TOCs when reaching scroll bottom

- packages/mui-material/src/Autocomplete/Autocomplete.js
- packages/mui-material/src/Autocomplete/Autocomplete.test.js
fixes: https://github.com/mui/material-ui/issues/34998
working proof: https://www.loom.com/share/8641a1e8a33844b0a48bff6e0d392289
Issue: element.offsetTop from below code returns incorrect value if parent element doesn't have relative position . attached some references below on this
https://github.com/mui/material-ui/blob/c789ca6d448f6032086c2268140c1d6c32bd1f0d/packages/mui-base/src/AutocompleteUnstyled/useAutocomplete.js#L376-L389
https://stackoverflow.com/questions/29277608/jquery-offset-top-returns-wrong-value-error-with-margin#:~:text=if%20you%20try%20to%20get,will%20get%20a%20wrong%20value.&text=Try%20removing%20the%20margin%2Dtop,will%20see%20it%20will%20work.
https://medium.com/@alexcambose/js-offsettop-property-is-not-great-and-here-is-why-b79842ef7582.
So i've added position …
> [Autocomplete] Fix keyboard navigation when using custom popover

- docs/data/joy/components/autocomplete/Playground.js
- docs/data/joy/components/divider/divider.md
Mostly a follow-up to a recently merged PR (https://github.com/mui/material-ui/pull/34316) in which I just realized a couple of things were still broken. @siriwatknp let me know about a better way to do the Autocomplete's playground demo work on dark & light mode, as it's using ternary _and_ hard-coded RGBa values (as they're from the branding theme).
> [Joy] Fix a couple documentation errors

- package.json
- test/utils/describeConformance.tsx
- test/utils/describeConformanceUnstyled.tsx
- yarn.lock
Not much to say here, I just migrated this file to TypeScript, right now using JS utils on the X repo is painful.
There should be no behavior change
> [core] Migrate `describeConformance` to TypeScript

- docs/data/material/migration/migration-v4/migration-v4.md
Fix doc feedback about https://mui.com/material-ui/migration/migration-v4/
> It says to update React to latest version and then make sure the app runs. It does not run with old material UI 4, so the step of updating to MUI 5 should be first.
From @oliviertassinari 
> Agree, it should be first Material UI to at least ^4.11.2, then React 17.
https://deploy-preview-35232--material-ui.netlify.app/material-ui/migration/migration-v4/#update-react-amp-typescript-version
> [docs] Fix migration feedback

- examples/remix-with-typescript/app/entry.client.tsx
- examples/remix-with-typescript/package.json
From https://github.com/mui/material-ui/issues/34991 
This should 'just work' with the updated `entry.client.tsx` for Remix latest and React 18
Note that the latest `entry.server.tsx` in the Remix blog tutorial uses `renderToPipeableStream`, although based on https://github.com/emotion-js/emotion/issues/2800 - I'm not sure this is possible yet.
For interest only, below is what the `renderToPipeableStream` would look like in `entry.server.tsx` if it were supported.
Hope this helps.
```js
import { PassThrough } from "stream";
import type { EntryContext } from "@remix-run/node";
import { Response } from "@remix-run/node";
import { RemixServer } from "@remix-run/react";
import isbot from "isbot";
import { renderToPipeableStream } from "react-dom/server";
const ABORT_DELAY = 5000;
export …
```
> [examples] Updated Remix examples with the lates changes using React 18

- examples/nextjs-with-typescript-v4-migration/package.json
- examples/nextjs-with-typescript-v4-migration/src/Link.tsx
- examples/nextjs-with-typescript/src/Link.tsx
1. `examples/nextjs-with-typescript-v4-migration` is meant to show how to use @mui/styles, so React 17 only, which doesn't work with Next 13 (React 18). It currently crashes when you follow https://github.com/mui/material-ui/tree/master/examples/nextjs-with-typescript-v4-migration.
2. I forgot to remove `passHref` in #28178
3. We did a fix in #33842 but forgot about the other examples
> [examples] Fix Next.js errors

- packages/mui-base/src/AutocompleteUnstyled/useAutocomplete.d.ts
- packages/mui-material/src/Autocomplete/Autocomplete.spec.tsx
> [Autocomplete] Fix inferred value type when `multiple` prop is `true`

- docs/src/modules/components/Ad.js
- docs/src/modules/components/ApiPage.js
- docs/src/modules/components/AppLayoutDocs.js
- docs/src/modules/components/MarkdownDocs.js
The bug: 
https://mui.com/material-ui/api/dialog/
The root of the problem is that `AdGuest` use the DOM API to add the `ad` class name once the Ad component is portaled but on this page, we don't use `dangerouslySetInnerHTML` to render the markdown, we use the React API directly.
I could pinpoint the origin of the change of behavior to the v5.9.0 release. This release includes #33196, so very likely the origin.
https://github.com/mui/mui-x/blob/c8f112caed7bd50fb1ba723f7db47590d08d926b/docs/src/modules/components/ApiDocs.js duplicate this file, so I will need to apply the same fix there too, not ideal but no other choices.
Preview: https://deploy-preview-35201--material-ui.netlify.app/material-ui/api/dialog/
> [docs] Fix ad margin on API pages

- docs/packages/markdown/parseMarkdown.js
This PR updates the copy for the "Unstyled" and "API" sections of the docs pages. I always felt that the earlier version of the "Unstyled" text lacked clarity and context, and that the "API" section could use a description to explain what's on the other side of the links.
**Before:**
**After:**
> [docs] Improve the autogenerated "Unstyled" and "API" text

- docs/data/material/guides/minimizing-bundle-size/minimizing-bundle-size.md
Currently the "Head to **Option 2**" is pointing to the wrong ID
The correct ID should be `option-two-use-a-babel-plugin`
> [docs] Fix incorrect link in minimizing-bundle-size

- packages/mui-material/src/locale/index.ts
- Translate "rows per page" as "每頁數量" to avoid the indefinite translation that could be "列/行" or "行/列" in a different context [1][2].
- Remove "條" because we useually use "列/行" in Taiwan and translate with "~" and "/".
- Fix "標籤" and "沒".
> [1] [Translations in Localized Microsoft Products](https://www.microsoft.com/en-us/language/Search?&searchTerm=columns&langID=129&Source=true&productid=0)
> [2] [The determinant in linear algebra](https://ccjou.wordpress.com/2012/04/17/)
> [l10n] Improve Chinese (Taiwan) zh-TW locale

- docs/src/modules/components/ApiPage.js
A continuation of https://github.com/mui/mui-x/pull/7051, one step closer to sharing the same `ApiPage` component with MUI X. The difference is that in MUI X, there are components that have different names than there style sheet. This happens because of the Pro and Premium components. It's stays the same:
Before: https://mui.com/material-ui/api/alert/
After: https://deploy-preview-35303--material-ui.netlify.app/material-ui/api/alert/
> [core] Use componentStyles.name over componentName

- docs/src/modules/components/ApiPage.js
- docs/translations/translations.json
It might solve these feedback:
https://mui-org.slack.com/archives/C041SDSF32L/p1668804057511509
When I'm landing on the API page, I usually have to scroll to the bottom of the page to then go to the demo (it happens to me quite often). Maybe this is a better UX https://deploy-preview-35202--material-ui.netlify.app/material-ui/api/alert/. I have made sure that searching for "example" yield a result too on the page.
Close #35004
> [docs] Move the demo higher in the API TOC

- docs/src/modules/components/MarkdownElement.js
1. Add a bit more spacing between list items, [Bootstrap uses 4px](https://getbootstrap.com/docs/5.2/getting-started/javascript/#usage-with-javascript-frameworks), [Tailwind CSS uses 8px](https://tailwindcss.com/docs/reusing-styles#avoiding-premature-abstraction). I saw the problem in https://github.com/mui/mui-x/pull/6567#discussion_r1018500264.
Before: https://mui.com/material-ui/getting-started/overview/#advantages-of-material-ui
After: https://deploy-preview-35302--material-ui.netlify.app/material-ui/getting-started/overview/#advantages-of-material-ui
2. Remove the leading margin for the list item. I saw the problem in https://github.com/mui/material-ui/pull/35202.
Before: https://mui.com/joy-ui/customization/using-css-variables/#raw-value
After …
> [docs] Improve spacing with ul

- test/utils/createDescribe.ts
- test/utils/describeConformance.tsx
- test/utils/describeConformanceUnstyled.tsx
- test/utils/index.js
The following now works
```tsx
describeConformance.only(<Alert onClose={() => {}} />, () => ({ ... }));
```
I was missing it when developing the new pickers test suites.
> [core] Support `only` and `skip` on `describeConformance` (and other MUI describes)

- packages/mui-material/src/Menu/Menu.js
- packages/mui-material/src/Menu/Menu.test.js
----
Fixes [#35376](https://github.com/mui/material-ui/issues/35376)
> [Select] Fix `MenuProps.PopoverClasses` being overriden

- docs/package.json
- yarn.lock
This is the same as #35118. For some reason, the original fails to trigger a build on Codesandbox CI.
> [dependencies] Bump next to 13.0.6

- docs/data/material/guides/composition/composition.md
Fix https://mui-org.slack.com/archives/C041SDSF32L/p1670014309285569
> The ThirdPartyComponent example doesn't make any sense to me. It doesn't even use GenericCustomComponent.
https://mui.com/material-ui/guides/composition/#with-typescript
> [docs] Improve a bit the Composition docs

- docs/public/static/styles/prism-okaidia.css
- docs/src/modules/components/MarkdownElement.js
- docs/src/modules/components/TopLayoutBlog.js
A nitpick, a quick follow-up on https://groups.google.com/a/mui.com/g/design/c/S5t9m6klH7o.
The idea of this change is to bring a bit more space between each line of the docs. Right now, if you compare our line height of Tailwind CSS, https://mintlify.com/docs/quickstart or https://stripe.com/docs/billing/subscriptions/overview it seems that the new value match closer, and might be more enjoyable to read.
For the blog, maybe it makes sense to have a bit more line height?
> [docs] Improve line-height readability

- docs/data/material/components/app-bar/DrawerAppBar.js
- docs/data/material/components/app-bar/DrawerAppBar.tsx
Fixes #35351 
Also updated the text color in dark mode in [Responsive App bar with Drawer demo](https://mui.com/material-ui/react-app-bar/#responsive-app-bar-with-drawer) demo. It was not visible.
Check the demo in dark mode - 
Before: https://mui.com/material-ui/react-app-bar/#responsive-app-bar-with-drawer
After: https://deploy-preview-35418--material-ui.netlify.app/material-ui/react-app-bar/#responsive-app-bar-with-drawer
I also approved the Argos build: https://app.argos-ci.com/mui/material-ui/builds/8116/31127253 (I think the font changed which is fine).
> [docs] Improve `Responsive App bar with Drawer` demo

- packages/mui-base/src/PopperUnstyled/PopperUnstyled.js
> [PopperUnstyled] Update PopperTooltip to have correct width when closing with transition

- packages/mui-material/src/OverridableComponent.d.ts
- packages/mui-types/index.d.ts
> [typescript] Add null to return type of OverridableComponent

- packages/mui-base/src/ButtonUnstyled/useButton.test.tsx
- packages/mui-base/src/ButtonUnstyled/useButton.ts
- packages/mui-base/src/ButtonUnstyled/useButton.types.ts
Sets the active state whenever a button's children have been clicked (in addition to previously supported button itself).
Also improved the logic of removing the active state - it's no longer necessary to release the mouse button while still hovering over the button.
Fixes #35164
> [Button][base] Set active class when a subcomponent is clicked

- packages/mui-joy/src/Box/Box.test.js
- packages/mui-joy/src/styles/extendTheme.test.js
Something I noticed while I was working on the KPI page. master is broken:
https://www.notion.so/mui-org/KPIs-1ce9658b85ce4628a2a2ed2ae74ff69c#59bb101e5eab4375a6018d6694d036a7
The issue is that since #35150, this test never pass:
https://app.circleci.com/pipelines/github/mui/material-ui/87228/workflows/4504c13e-6d89-49fe-9589-60586b34e23a/jobs/461431
My proposed solution is to remove it.
---
I was also curious, I saw we had no tests for `theme.unstable_sx` so I added one. On my end, it doesn't behave exactly like I was exepecting:
1. Colors aren't supported.
1. When using `createTheme()` I would expect it returns the raw value.
1. When using `extendTheme()` I would expect it returns the CSS variable.
I even wonder if we shouldn't rename these helpers for clarity:
- `createTheme` -> …
> [test] Fix broken master branch

- docs/data/material/components/cards/MediaCard.js
- docs/data/material/components/cards/MediaCard.tsx
Fixes https://github.com/mui/material-ui/issues/35468
> [docs] Add `CardMedia` example without `component="img"` prop

- docs/data/material/customization/palette/palette.md
This is very minor, but I was pasting this section into an example and noticed the missing comma!
Signed-off-by: Cassidy Williams <1454517+cassidoo@users.noreply.github.com>
> [docs] Add missing comma to `Providing the colors directly` section

- packages/mui-joy/src/Input/Input.tsx
Close #34071
**After:**
https://deploy-preview-35056--material-ui.netlify.app/joy-ui/react-text-field/
> [Input][Joy] Fix autofill styles

- test/karma.conf.js
Since #34764, the tests in BrowserStack are faster (Firefox could be quite slow).
https://automate.browserstack.com/dashboard/v2/builds/a388cf32b522d21452ff09cc50ef498ef4c20d33
So when something is going wrong:
https://automate.browserstack.com/dashboard/v2/builds/444a887beff83e259a560b75df57988643f4eb0b
I think that we could reduce how much it starves the CI.
> [test] Terminate BrowserStack after 5 minutes

- packages/mui-material/src/FilledInput/FilledInput.js
- packages/mui-material/src/Input/Input.js
Fixes Input & FilledInput error focus state style. Fixes #35353 
According to [Material](https://m2.material.io/components/text-fields) these should be 1px default & 2px on focus. Thus having a visible focus state. 
In [MUI](https://mui.com/material-ui/react-text-field/#validation) these are currently 2px default & without any focus state.
Focus visible is an accessibility requirement by [WCAG 2.4.7](https://www.w3.org/WAI/WCAG21/Understanding/focus-visible.html)
> [TextField] Fix error focus style

- packages/mui-base/src/PopperUnstyled/PopperUnstyled.js
When `props.anchorEl` is a function, it sometimes gets called with one argument when it expects no arguments (see [codesandbox example](https://codesandbox.io/s/anchorel-called-with-arg-r5qbgm?file=/demo.tsx)).
This is happening because the state setter `setTooltipAnchorEl(anchorEl)` (recently added in #34714) calls a function `anchorEl` as if it were in the form of `setTooltipAnchorEl((prev) => next)`.
We should call `resolveAnchorEl` on `anchorEl` before setting `tooltipAnchorEl`.
> [Popper][Base] Fix Tooltip Anchor Element Setter

- packages/mui-utils/src/deepmerge.test.ts
- packages/mui-utils/src/deepmerge.ts
I'm not sure about `lodash` but we definetly have to use deep copy for objects otherwise value assign by reference.
Test case has been added.
Fix #35363
> [Utils] mergedeep deeply clones source key if it's an object

- docs/data/material/components/progress/progress.md
Errata: `Maximium` => `Maximum`
Signed-off-by: Jason Sturges <jason@jasonsturges.com>
> [docs] Fix typo in `Progress` docs

- docs/pages/material-ui/api/popper.json
- packages/api-docs-builder/ApiBuilders/ComponentApiBuilder.ts
- packages/mui-material/src/Popper/Popper.tsx
The Popper component has a `direction` prop documented, even though this prop exists only in the PopperUnstyled props. This PR makes sure that omitted props are not taken into consideration when building the API docs.
> [core] Exclude documentation of Base props not used in styled libraries

- docs/src/modules/components/ApiPage.js
Before https://mui.com/material-ui/api/alert/#demos
After https://deploy-preview-35579--material-ui.netlify.app/material-ui/api/alert/#demos
It's about matching the same output of the markdown to HTML logic in this React component.
> [core] Fix API demos callout spacing

- docs/data/material/components/autocomplete/GoogleMaps.js
- docs/data/material/components/autocomplete/GoogleMaps.tsx
- docs/data/material/components/autocomplete/autocomplete-pt.md
- docs/data/material/components/autocomplete/autocomplete-zh.md
- docs/data/material/components/autocomplete/autocomplete.md
Closes https://github.com/mui/material-ui/issues/35391
**Problem**:
- For some queries, the [Google Maps Autocomplete demo](https://mui.com/material-ui/react-autocomplete/#GoogleMaps.js) crashes
**Before**:
(1) Go to https://mui.com/material-ui/react-autocomplete/#google-maps-place
(2) Enter "Darse de Baudour"
(3) Demo crashes
**After**: 
(1) Go to https://deploy-preview-35545--material-ui.netlify.app/material-ui/react-autocomplete/#google-maps-place
(2) Enter "Darse de Baudour"
(3) Demo doesn't crash
> [docs][Autocomplete] Fix GoogleMaps demo

- docs/src/modules/components/ThemeContext.js
Fixes the need to use `light` computer mode or creating a wrapping theme in playground pages to avoid the following case:
**Before:**
**After:**
`activePage` does not exist for playground pages
> [docs] Force `light` theme mode when `activePage` is null

- docs/data/material/components/buttons/buttons.md
We've received some docs feedback that it was not obvious that these demos show experimental APIs usage.
> [docs] Improve the experimental API demos on the button page

- packages/mui-material-next/src/Button/Button.test.js
- packages/mui-material-next/src/Button/Button.tsx
- packages/mui-material-next/src/Button/Button.types.ts
- packages/mui-material-next/src/Button/buttonClasses.ts
- test/utils/describeConformance.tsx
I started the PR with the need to fix the `active` state for the Button, and then realized that in the test we were testing the `@mui/material/Button`, instead of `@mui/material-next/Button`, so I re-write the test and added some necessary features to the `describeConformance` test suit, mainly around supporting different `createTheme` feature.
> [Material You] Update Button test & add active class name

- packages/mui-material/src/TableCell/TableCell.js
- packages/mui-material/src/TableCell/TableCell.test.js
- packages/mui-material/test/integration/TableCell.test.js
fixes: https://github.com/mui/material-ui/issues/35031
> [TableCell]  Fix `scope` prop to be not set when a data cell is rendered within a table head

- packages/mui-joy/src/Radio/Radio.tsx
Closes https://github.com/mui/material-ui/issues/35531
Closes https://github.com/mui/material-ui/issues/34167
**Problem**:
- For `variant="outlined"`, radio icon isn't precisely centered due to the border of radio element.
**Solution**:
```diff --git a/packages/mui-joy/src/Radio/Radio.tsx b/packages/mui-joy/src/Radio/Radio.tsx
--- a/packages/mui-joy/src/Radio/Radio.tsx
+++ b/packages/mui-joy/src/Radio/Radio.tsx
@@ -204,8 +204,8 @@ const RadioIcon = styled('span', {
slot: 'Icon',
overridesResolver: (props, styles) => styles.icon,
})<{ ownerState: RadioOwnerState }>(({ ownerState }) => ({
-  width: '50%',
-  height: '50%',
+  width: 'calc((var(--Radio-size) - var(--variant-borderWidth)) / 2)',
+  height: 'calc((var(--Radio-size) - var(--variant-borderWidth)) / 2)',
```
**Preview**: …
> [Radio][Joy] Use precise dimensions for radio icon

- packages/mui-joy/src/Alert/Alert.tsx
- packages/mui-joy/src/Chip/Chip.tsx
- packages/mui-joy/src/Input/Input.tsx
- packages/mui-joy/src/Select/Select.tsx
- packages/mui-joy/src/Textarea/Textarea.tsx
Make the radius adjustment perfect.
**Before**:
There is a 1px void at the edge of the button.
**After**:
> [Joy] Fix radius adjustment

- docs/src/modules/components/MarkdownElement.js
Something that annoyed me while I used the demo "Copy" button on my phone. I have no keyboard so I can't use the shortcut.
The solution relies on https://developer.mozilla.org/en-US/docs/Web/CSS/@media/any-hover. in the future, we might be able to use: https://github.com/w3c/csswg-drafts/issues/3871.
> [core] Hide keyboard shortcut if no hover feature

- docs/src/modules/components/ApiPage.js
- docs/src/modules/components/AppLayoutDocs.js
- docs/src/modules/components/MarkdownElement.js
- packages/markdown/parseMarkdown.js
The bugs can be seen here: https://mui.com/material-ui/getting-started/faq/#why-are-the-colors-i-am-seeing-different-from-what-i-see-here
1. Wrong vertical alignment between the two links
2. Overlap possible between the two links
3. No reserved space for the links
4. Layout shift on hover
https://user-images.githubusercontent.com/3165635/209474478-2b38492f-4525-4c51-b76a-8c36789cee76.mov
It's all solved: https://deploy-preview-35626--material-ui.netlify.app/material-ui/getting-started/faq/#why-does-component-x-require-a-dom-node-in-a-prop-instead-of-a-ref-object.
> [core] Fix header link layout shift and clash

- docs/data/material/guides/flow/flow-pt.md
- docs/data/material/guides/flow/flow-zh.md
- docs/data/material/guides/flow/flow.md
- docs/data/material/pages.ts
- docs/pages/material-ui/guides/flow.js
- docs/public/_redirects
- docs/src/pages.ts
- docs/translations/translations-pt.json
- docs/translations/translations-zh.json
- docs/translations/translations.json
At this point, few outsides of Meta care about flow. I think that it's better to push people to use TypeScript. We can remove https://mui.com/material-ui/guides/flow/. Related to https://github.com/flow-typed/flow-typed/issues/4051.
> [docs] Remove flow, its legacy

- docs/data/joy/components/stack/BasicStack.js
- docs/data/joy/components/stack/BasicStack.tsx
- docs/data/joy/components/stack/BasicStack.tsx.preview
- docs/data/joy/components/stack/DirectionStack.js
- docs/data/joy/components/stack/DirectionStack.tsx
- docs/data/joy/components/stack/DirectionStack.tsx.preview
- docs/data/joy/components/stack/DividerStack.js
- docs/data/joy/components/stack/DividerStack.tsx
- docs/data/joy/components/stack/DividerStack.tsx.preview
- docs/data/joy/components/stack/InteractiveStack.js
- docs/data/joy/components/stack/InteractiveStack.tsx
- docs/data/joy/components/stack/ResponsiveStack.js
- docs/data/joy/components/stack/ResponsiveStack.tsx
- docs/data/joy/components/stack/ResponsiveStack.tsx.preview
- docs/data/joy/components/stack/ZeroWidthStack.js
- docs/data/joy/components/stack/ZeroWidthStack.tsx
- docs/data/joy/components/stack/stack.md
- docs/data/joy/pages.ts
- docs/pages/joy-ui/react-stack.js
Closes https://github.com/mui/material-ui/issues/35471
**Preview**: https://deploy-preview-35373--material-ui.netlify.app/joy-ui/react-stack
> [docs][Joy] Add documentation for Joy `Stack` component

- docs/data/base/components/modal/modal.md
- docs/src/modules/components/BackToTop.tsx
Fix https://mui-org.slack.com/archives/C041SDSF32L/p1671799892568439.
> When you click on the menu, you'll notice the FAB at your right hand side of the right drawer shifts position. And the scroll bar on the right hand side appears and disappears. I'm also having this same issue in an app I'm building for a client, and the client is not happy about it. Menus and right hand drawers do not like each other
It's simpler to review the change without whitespace: https://github.com/mui/material-ui/pull/35591/files?diff=unified&w=1.
Before: https://mui.com/material-ui/react-select/#basic-select
https://user-images.githubusercontent.com/3165635/209343563-c43bacaa-33db-4fe2-865c-415b893234cd.mov
After: https://deploy-preview-35591--material-ui.netlify.app/material-ui/react-select/#basic-select
The …
> [docs] Fix layout shift with modal

- docs/data/joy/components/card/card.md
Found them while looking at issue #35588.
> [docs] Fix anchor link in the card's docs and fix a typo

- docs/data/joy/customization/theme-tokens/theme-tokens.md
While reading, wanted to navigate quickly b/w these two sections and couldn't do that. 
So added that with this PR.
> [docs][joy] Improved readability on theme tokens page

- docs/data/joy/pages.ts
- docs/data/material/pages.ts
- docs/data/system/pages.ts
- docs/pages/_app.js
- docs/src/MuiPage.ts
- docs/src/modules/components/AppNavDrawer.js
- docs/src/modules/utils/findActivePage.test.js
- docs/src/modules/utils/findActivePage.ts
- docs/src/pages.ts
The notion of `scopePathnames` is painful, e.g. in https://github.com/mui/mui-x/pull/7213/files#diff-ee90840a476635e5e663e42e8bec44d8f102d933541525413da71ef646f60f19R59. "Rows" expand when "Row selection" is selected:
https://deploy-preview-7213--material-ui-x.netlify.app/x/react-data-grid/row-selection/ 
The solution is to traverse the pages to find all the nodes that need to be expanded to have the active page visible.
ℹ️ This is a breaking change for MUI X and MUI Toolpad docs because of all the 🙈 code duplication in _app.js.
> [core] Remove need for scopePathnames

- docs/src/modules/components/AppLayoutDocs.js
- docs/src/modules/components/AppTableOfContents.js
The problem can be seen in:
https://user-images.githubusercontent.com/3165635/209475086-f0f183a0-1214-481d-b4bf-35a2033ad21d.mov
There is this intermediary layout shift:
It's detailed in depth in this blog post: https://twitter.com/jaffathecake/status/1149637428388360197 (from 8 years ago, but still true, and might be true forever).
> Browsers can progressively render content as it's streamed from the server, this is great because it means users can start consuming content before it's all arrived. However, when combined with flexbox it causes misalignment and horizontal shifting.
I believe we are allowed to use CSS Grid https://caniuse.com/css-grid as it's compatible with our browser support.
Preview: https://deploy-preview-35627--material-ui.netlify.app/material-ui/react-autocomplete/
> [docs] Fix layout shift when streaming the page

- docs/src/BrandingCssVarsProvider.tsx
- docs/src/BrandingProvider.tsx
- docs/src/modules/components/AppFrame.js
- docs/src/modules/components/AppNavDrawerItem.js
- docs/src/modules/components/AppTableOfContents.js
- docs/src/modules/components/MarkdownLinks.js
To reproduce the issue: 
1. Open https://mui.com/blog/first-look-at-joy/#global-variants
2. Have the dark mode in
3. Click on the "Global variants" link. 
4. See the flash, it's a server-side page reload, not a client side one.
https://deploy-preview-35628--material-ui.netlify.app/blog/first-look-at-joy/#global-variants
> [blog] Fix handling of markdown links

- test/e2e-website/material-docs.spec.ts
See https://github.com/algolia/docsearch/issues/1745 for context
> [test] Fix Algolia noisy lvl1 anchor

- docs/src/modules/utils/CodeCopy.tsx
Fixes #35645 
The `window.getSelection()` returns an empty string on Firefox browser for a text inside a form field i.e textarea due to which the check fails and copies the whole code text. 
See bug opened 22 years ago which isn't yet fixed: https://bugzilla.mozilla.org/show_bug.cgi?id=85686.
I copied the same logic as in https://github.com/mui/mui-x/pull/6593 which works well.
Link to test after fix: https://deploy-preview-35670--material-ui.netlify.app/material-ui/react-menu/#main-content
> [docs] Fix demo code selection through copy shortcut key on Firefox browser

- docs/src/BrandingCssVarsProvider.tsx
- docs/src/modules/components/DemoSandbox.js
- docs/src/modules/components/MarkdownDocs.js
- docs/src/modules/components/ThemeContext.js
- docs/src/modules/components/TopLayoutCareers.js
Apply https://github.com/mui/material-ui/pull/35330#issuecomment-1363632845 to fix a regression introduced in #35201.
> [docs] Fix ad exception in Joy UI

- packages/mui-material/src/FilledInput/FilledInput.js
- packages/mui-material/src/Input/Input.js
This fixes a regression at the same time, on hover:
**Expected**
https://v1.mui.com/demos/text-fields/#textfield
**Actual**
https://mui.com/material-ui/react-text-field/#basic-textfield
It seems that we can simplify the logic in #35167. The first commit is a revert. The second is the fix. I got pulled into this by "Need final review from @oliviertassinari" and then when I had a quick look, the use of `:focus-within` which I couldn't wrap my head around: why it would be needed in the first place.
> [TextField] Improve WCAG 2.4.7 with error={true}

- docs/pages/material-ui/api/menu-item.json
- docs/translations/api-docs/menu-item/menu-item.json
- packages/mui-joy/src/ListItemButton/ListItemButton.tsx
- packages/mui-joy/src/ListItemButton/ListItemButtonProps.ts
- packages/mui-joy/src/MenuItem/MenuItem.tsx
- packages/mui-material/src/MenuItem/MenuItem.d.ts
- packages/mui-material/src/MenuItem/MenuItem.js
- scripts/generateProptypes.ts
Fixes https://github.com/mui/material-ui/issues/35556. It was a regression from https://github.com/mui/material-ui/pull/26591
> [docs] Fix API page for `MenuItem` to list all valid props

- docs/src/modules/components/JoyVariablesDemo.tsx
Follow-up on https://github.com/mui/mui-toolpad/pull/1274#discussion_r1017032943
- Using `event.code` works only for QWERTY keyboards
> [Joy] Improve `onKeyDown` event handler for demo

- docs/data/material/components/buttons/LoadingButtonsTransition.js
- docs/data/material/components/buttons/LoadingButtonsTransition.tsx
- docs/data/material/components/buttons/buttons.md
This explains the workaround for #27853, as discussed in the issue.
> [docs] Document the workaround for crashing a translated page

- packages/mui-material/src/Tooltip/Tooltip.js
`data-foo="bar"` was unnecessarily added to the `TransitionComponent` in [#34873](https://github.com/mui/material-ui/pull/34873/files#diff-9e609b09872335393b32162304d39d96eb2cfda2822cc913a1af9ce17942ff12R706)
> [Tooltip] Remove `data-foo` attribute

- docs/data/base/components/button/button.md
- docs/data/joy/components/button/BasicButtons.js
- docs/data/joy/components/button/BasicButtons.tsx
- docs/data/joy/components/button/BasicButtons.tsx.preview
- docs/data/joy/components/button/ButtonDisabled.js
- docs/data/joy/components/button/ButtonDisabled.tsx
- docs/data/joy/components/button/ButtonLoading.js
- docs/data/joy/components/button/ButtonLoading.tsx
- docs/data/joy/components/button/ButtonLoading.tsx.preview
- docs/data/joy/components/button/ButtonLoadingIndicator.js
- docs/data/joy/components/button/ButtonLoadingIndicator.tsx
- docs/data/joy/components/button/ButtonLoadingIndicator.tsx.preview
- docs/data/joy/components/button/ButtonsSimple.js
- docs/data/joy/components/button/ButtonsSimple.tsx.preview
- docs/data/joy/components/button/button.md
Part of #33998
This PR revises and expands the Joy UI Button doc. Notable changes include:
- rearranging and reformatting to match the latest style
- adding a couple basic demos
- accessibility and anatomy
While I was comparing this doc with its sister in the Base docs, I noticed that the Base page had a tiny inconsistency in how it's organized, so I went ahead and changed that here because it's not worth creating a PR for on its own.
> [docs] Revise and expand Joy UI Button doc

- docs/data/material/components/autocomplete/Virtualize.js
- docs/data/material/components/autocomplete/Virtualize.tsx
- docs/data/material/components/autocomplete/Virtualize.tsx.preview
- packages/mui-material/src/Autocomplete/Autocomplete.d.ts
- packages/mui-material/src/Autocomplete/Autocomplete.js
The purpose of this PR is to simply expose the index that `renderListOption` intakes, coming from the `AutcompleteListbox` `groupedOptions.map` rendering. This allows a developer to have an easy, and more performant, way to reference the current option's index inside the `renderOption` callback method.
The use-case that brought up this issue was during my attempts at adding virtualization to our Autocomplete components. Our autocompletes that need virtualization may already be using `renderOptions`, or they may simply be using `getOptionLabel`. Either way, in order to create a single "VirtualizedAutocomplete" wrapper that can accept varying render sources as well as support lists where the rendered options have varying heights we need to be able to reference the index of the option being …
> [Autocomplete] Add index to renderOption's AutocompleteRenderOptionState

- scripts/copyFiles.mjs
To change https://unpkg.com/@mui/base@5.0.0-alpha.112/node/index.js. It matches with https://unpkg.com/browse/react-dom@18.2.0/cjs/react-dom-server.node.production.min.js.
Related to https://github.com/mui/mui-x/pull/7367
> [core] Fix the product license reference name

- docs/src/pages/careers/accessibility-engineer.md
So we can move from reports like this https://www.notion.so/mui-org/Accessibility-Engineer-5fd51889c22c41ec80bacaeebe1c2bd7#a8d5508fa70c42eb9537cfe602a73187 to having them **cleanly** solved (and not half backed solution that degrades the product, overall)
I worked on this based on the applications that we receive https://app.ashbyhq.com/jobs/6df7339b-5cee-4d7d-ad69-701b39eb194b/candidate-pipeline/application-review, the applications are too biased toward candidates that have Accessibility testing experience. I think that it would work x10 better to have a Software Engineer that cares about Accessibility but never did the job than an Accessibility tester that never wrote code. In the former case, the person will grow with the feedback of the community, in the latter case, the person will …
> [website] Update the Accessibility Engineer role

- docs/src/modules/components/AppNavDrawer.js
- docs/src/modules/components/DiamondSponsors.js
The scroll position moves by 6 pixels each time you change page:
https://user-images.githubusercontent.com/3165635/210135763-d099ae62-d191-4229-880c-abed56052d94.mov
This regression was introduced between v4.12.4 and v5.0.0, e.g. https://v5-0-6.mui.com/components/typography/ KO, v4.12.4: OK https://v4.mui.com/components/radio-buttons/. It has been driving me crazy for over a year, it won't make it to 2023 (end of 2021: https://github.com/mui/material-ui/pull/29994#issuecomment-983816368).
Why does this happen? Because Next.js REMOUNTs each page. This means that the CssBaseline that is inside the page gets unmounted, removes the `boxSizing: 'border-box',` style, which then means that the 3 diamond sponsors' 1px border is no longer taken into account in the height set, which means +6 pixels …
> [docs] Fix navigation layout shift

- packages/mui-material/src/styles/experimental_extendTheme.js
- packages/mui-material/src/styles/experimental_extendTheme.test.js
close #35768 
**Before**: https://codesandbox.io/s/stoic-wiles-mnmv5i?file=/demo.tsx
**After**: https://codesandbox.io/s/angry-yalow-uozvrr?file=/demo.tsx
Currently, there is no way to suppress the warning even custom token is provided:
```js
extendTheme({
light: {
palette: {
background: {
divider: 'var(--external-divider)', // Material UI can't generate channel token from CSS variable, so a warning appears.
dividerChannel: 'var(--external-dividerChannel)', // this should suppress the warning but it does not.
}
}
}
})
```
Only generate the channel tokens and show a warning if it is not provided.
---
> [Material UI] Custom channel token should suppress the warning

- docs/data/material/components/click-away-listener/click-away-listener.md
- docs/data/material/components/no-ssr/no-ssr.md
- docs/data/material/components/portal/portal.md
- docs/data/material/components/textarea-autosize/textarea-autosize.md
https://deploy-preview-35799--material-ui.netlify.app/material-ui/react-portal/
Iterating on doc feedback following #35293, part of #35077.
We received feedback from a user that suggested that they did not understand where to find demos for the MUI Base components that are re-exported in Material UI. 
This PR attempts to make things more clear and obvious by:
- changing the headline on these pages from **MUI Base** to **This document has moved**
- bumping up the callout severity from `info` to `warning` so it's more eye-catching
- moving the most important link—the corresponding MUI Base doc—to the top of the callout
Before:
After:
> [docs] Clarify where to find docs for MUI Base components in Material UI

- examples/nextjs-with-typescript-v4-migration/.gitignore
- examples/nextjs-with-typescript-v4-migration/next-env.d.ts
- examples/nextjs-with-typescript/.gitignore
- examples/nextjs-with-typescript/next-env.d.ts
`next-env.d.ts` should not be committed and should be ignored by version control.
Source: https://nextjs.org/docs/basic-features/typescript#existing-projects
---
The default `.gitignore` template for `create-next-app` has also been updated to ignore `next-env.d.ts` in this PR: https://github.com/vercel/next.js/pull/39051
> [examples] Remove `next-env.d.ts` from Next.js examples

- docs/data/joy/customization/approaches/approaches.md
Existing code example is invalid. Added a `root` block inside the styleOverrides to fix it
Signed-off-by: Pubudu Dodangoda <pubudu.dodan@gmail.com>
> [docs][joy] Update Customization section code example to use the correct API

- docs/data/material/components/tables/AccessibleTable.js
- docs/data/material/components/tables/AccessibleTable.tsx
- docs/data/material/components/tables/tables-pt.md
- docs/data/material/components/tables/tables-zh.md
- docs/data/material/components/tables/tables.md
Noticed there was a misspelling for `AccessibleTable` so wanted to put a fix in
> [docs] Fix incorrectly named AccessibleTable demo component

- packages/mui-joy/src/TextField/TextField.tsx
- packages/mui-joy/src/TextField/index.ts
- packages/mui-joy/src/index.ts
#35462 removes `TextField` from Joy UI. This PR brings back TextField with error messages so that the developers know how to migrate and why it is removed.
https://codesandbox.io/s/joy-cra-typescript-forked-iu2l1k?file=/src/App.tsx
> [Joy][TextField] Throw error with migration message

- packages/docs-utilities/index.d.ts
- packages/docs-utilities/index.ts
- packages/docs-utilities/package.json
It was throwing the following error:
> A parameter initializer is only allowed in a function or constructor implementation.
_Edit:_ I migrated the `docs-utilities` to TypeScript instead.
> [core]  Migrate internal `docs-utilities` package to TypeScript

- packages/docs-utilities/index.d.ts
- packages/docs-utilities/index.js
- packages/docs-utilities/package.json
Reverting the migration to TypeScript and only keeping the fix of the `getUnstyledFilename` method type (https://github.com/mui/material-ui/commit/6235c1dae7de454708bfbd70f396307fead3f927) as discussed in #35846.
> [core] Revert `docs-utilities` migration to TypeScript and fix type

- packages/mui-material/src/Box/Box.d.ts
Fixes https://github.com/mui/material-ui/issues/35860. This is a regression from https://github.com/mui/material-ui/pull/35532, as `ReturnType` is not supported in TypeScript 3.5
> [Box] Fix usage of not supported features in TypeScript 3.5

- packages/mui-material/src/Button/Button.js
Fixes: #35851 
Standardize the border color for secondary button when it is disabled.
> [Button] Fix border color for secondary disabled button

- docs/data/material/components/menus/AccountMenu.js
- docs/data/material/components/menus/AccountMenu.tsx
Fixes #35844 – the [material-ui Account Menu demo](https://mui.com/material-ui/react-menu/#account-menu) can be opened but not closed using the keyboard.
Preview link with the fix: https://deploy-preview-35870--material-ui.netlify.app/material-ui/react-menu/#account-menu
> [docs] Fix account menu demo not closing with keyboard.

- scripts/releaseChangelog.mjs
After https://github.com/mui/material-ui/pull/35876 was merged the `releaseChangelog` script was failing because the `author` field was empty. I am not sure how the pull request was created.
> [core] Fix release changelog to handle commits with empty author field

- docs/data/material/customization/color/color.md
- docs/data/material/customization/theming/theming.md
This PR simply just changes a suggested community theme builder in the docs from the current to a forked and more up to date one:
- The current: [https://bareynol.github.io/mui-theme-creator/](https://bareynol.github.io/mui-theme-creator/)
- Forked and more up to date one: [https://zenoo.github.io/mui-theme-creator/](https://zenoo.github.io/mui-theme-creator/)
> [docs] Update community theme builder to forked updated one

- docs/.link-check-errors.txt
- docs/data/joy/components/checkbox/CheckboxColors.js
- docs/data/joy/components/checkbox/CheckboxSizes.js
- docs/data/joy/components/checkbox/CheckboxVariants.js
- docs/data/joy/components/checkbox/FocusCheckbox.js
- docs/data/joy/components/checkbox/GroupCheckboxes.js
- docs/data/joy/components/checkbox/HelperTextCheckbox.js
- docs/data/joy/components/checkbox/HoverCheckbox.js
- docs/data/joy/components/checkbox/IconlessCheckbox.js
- docs/data/joy/components/checkbox/IconsCheckbox.js
- docs/data/joy/components/checkbox/OverlayCheckbox.js
- docs/data/joy/components/checkbox/checkbox.md
Part of #33998 
This PR revises and expands the Joy UI Checkbox component doc.
Notable changes include:
- expanded Introduction with guidance on usage vs Switches and Radio Buttons
- details on Variants, Sizes, and Colors, along with demos showing off all options
- more descriptive Label text for demos
- clarifying the "indeterminate" state
- additional details throughout all sections
- anatomy
https://deploy-preview-35817--material-ui.netlify.app/joy-ui/react-checkbox/
> [docs] Revise and expand Joy UI Checkbox doc

- packages/mui-joy/src/styles/CssVarsProvider.tsx
- packages/mui-material/src/styles/CssVarsProvider.tsx
`unstable_sxConfig` should not be generated.
> [CssVarsProvider] Skip `unstable_sxConfig` variables

- docs/data/material/components/accordion/accordion.md
- docs/data/material/components/alert/alert.md
- docs/data/material/components/steppers/steppers.md
- docs/data/material/components/text-fields/text-fields.md
- docs/data/material/components/timeline/timeline.md
Closes #35385
This PR standardizes the callouts on the following pages:
Components no longer documented by Material Design:
- Accordion
- Stepper
- standard variant of Text Field
Components not documented by Material Design:
- Alert
- Timeline
I've also changed the MD link from m2.material.io to simply material.io, so (ideally) we won't have to worry about updating them in the future when we eventually support MD3.
> [docs] Standardize "no longer" / "not documented" callouts in Material UI docs

- docs/src/modules/components/AppLayoutDocs.js
- docs/src/modules/components/Demo.js
- docs/src/modules/components/DemoToolbar.js
- docs/src/modules/components/EditPage.js
- docs/src/modules/components/MarkdownDocs.js
Solve frustration in https://github.com/mui/material-ui/pull/35872#pullrequestreview-1266540707. It's hard to filter the events for a given page.
https://analytics.google.com/analytics/web/#/report/content-event-events/a106598593w159022482p160376982/explorer-segmentExplorer.segmentId=analytics.eventLabel&_r.drilldown=analytics.eventAction:expand&explorer-table.plotKeys=%5B%5D&explorer-table.rowStart=0&explorer-table.rowCount=50
The fix is to expand the path:
```diff
<button
-  data-ga-event-label="BasicAlerts.js"
+  data-ga-event-label="material/components/alert/BasicAlerts.js"
```
This is a regression from #30757.
> [docs] Fix event's label reported to GA

- docs/pages/blog/making-customizable-components.md
- docs/pages/blog/v6-beta-pickers.md
- docs/src/modules/components/MarkdownElement.js
1. Pick your iPhone
2. Open https://mui.com/blog/v6-beta-pickers/ (from #35486)
3. Enjoy
I found this at an Apple store today, I don't have an iPhone, so I wanted to experience MUI like 52% of the people in the US do https://www.statista.com/statistics/266572/market-share-held-by-smartphone-platforms-in-the-united-states/. If this charts keep rising, I will need to ditch my Android phone 🙃
> [blog] Prevent horizontal scroll on blog posts

- docs/data/base/components/button/button.md
- docs/data/base/components/form-control/form-control-pt.md
- docs/data/base/components/form-control/form-control-zh.md
- docs/data/base/components/modal/modal-pt.md
- docs/data/base/components/modal/modal-zh.md
- docs/data/base/components/modal/modal.md
- docs/data/base/components/popper/popper-pt.md
- docs/data/base/components/popper/popper-zh.md
- docs/data/base/components/popper/popper.md
- docs/data/base/components/snackbar/snackbar-pt.md
- docs/data/base/components/snackbar/snackbar-zh.md
- docs/data/base/components/snackbar/snackbar.md
- docs/data/base/components/tabs/tabs-pt.md
- docs/data/base/components/tabs/tabs-zh.md
Fixing some typos in the base component docs
> [docs] Fix typos in base components docs

- docs/src/modules/components/JoyVariablesDemo.tsx
**Before**
The field without a default value always returns a number when edited.
https://user-images.githubusercontent.com/18292247/214749444-bb0a951f-ae7a-4674-af99-f9e105f6035b.mov
**After**
https://user-images.githubusercontent.com/18292247/214749559-1c794d0a-e79b-4839-8b54-9ab06d779720.mov
> [docs] Fix Joy UI variables playground

- docs/data/joy/customization/dark-mode/dark-mode.md
Signed-off-by: Arthur Pedroti <arthurpedroti@gmail.com>
Context and closes: #35888
Add a warning to clear the local storage when change the defaultMode to another value.
> [docs] Add a warning about to clear the local storage when `defaultMode` changes

- package.json
- yarn.lock
Adds caching to `getComputedStyles` for perf. Want to check if this didn't break anything
If I remember correctly `test_unit` had quite the range but [336.15s (branch)](https://app.circleci.com/pipelines/github/mui/material-ui/90080/workflows/20c89d60-e939-4afa-a267-5e7b56b35a0a/jobs/477404) vs [538.74s (master)](https://app.circleci.com/pipelines/github/mui/material-ui/90037/workflows/85c4282d-660f-44db-a1d3-0e23357cb3bb/jobs/477172) looks promising.
jsdom changelog: https://github.com/jsdom/jsdom/blob/master/Changelog.md#2110.
> Bump JSDOM to 21.x

- packages/mui-base/src/BadgeUnstyled/useBadge.ts
- packages/mui-joy/src/Badge/Badge.tsx
- packages/mui-utils/src/usePreviousProps.ts
Also removed unnessary casting 
https://github.com/mui/material-ui/pull/35833/files#diff-725c98d6ab0aa97869894d8da37e4e2c0e9c01bc80c1d0068632eabeacf8367fL166
**_Ignore unnessary suggestions in before picture, those are generated by vscode_**
Before: 
After:
> [usePreviousProps] Improve types for usePreviousProps

- packages/mui-base/src/ListboxUnstyled/useListbox.ts
- packages/mui-base/src/MenuUnstyled/MenuUnstyled.test.tsx
close #35780
This fix the bad focus on options when the list is initialized, In this case the findIndex will always return -1 for the index of the option because the array options is not filled yet.
**before:** https://codesandbox.io/s/k0zipv?file=/demo.js:0-1083
**after:** https://codesandbox.io/s/fix-listbox-uvx06z?file=/demo.js
`highlighted: highlightedIndex === index, // this will be always true as long as the options array is empty`
Force condition by checking index is not equal to -1 when the options is empty
> [ListboxUnstyled] Fix option state highlighted to prevent unnecessary focus

- CHANGELOG.md
- docs/data/material/migration/migration-v4/v5-component-changes-pt.md
- docs/data/material/migration/migration-v4/v5-component-changes-zh.md
- docs/data/material/migration/migration-v4/v5-component-changes.md
I had it wrong in #25063.
Context: https://mui-org.slack.com/archives/C041SDSF32L/p1675141428308229
> It should be indicatorColor="secondary" textColor="inherit"
> [docs] Fix wrong v5 migration instructions

- packages/mui-base/src/FocusTrap/FocusTrap.tsx
- packages/mui-base/src/NoSsr/NoSsr.tsx
- packages/mui-base/src/Portal/Portal.tsx
- packages/mui-base/src/Portal/Portal.types.ts
- packages/mui-lab/src/Timeline/Timeline.tsx
- packages/mui-material/src/Popper/Popper.tsx
Add return type annotations so that Typescript doesn't have to infer it, as suggested in https://github.com/mui/material-ui/issues/35287#issuecomment-1408870399
Before: https://codesandbox.io/s/popper-missing-props-3l97zo?file=/src/App.tsx
After: https://codesandbox.io/s/popper-missing-props-fixed-b0rj7h?file=/src/App.tsx
Fixes #35287
> [typescript] Explicitly define the component return types

- docs/data/material/components/text-fields/StateTextFields.js
- docs/data/material/components/text-fields/StateTextFields.tsx
- docs/data/material/components/text-fields/StateTextFields.tsx.preview
See the change in the `tsx.preview`, you do no longer need to expand the demo to understand how to get the value in the change handler.
https://mui.com/material-ui/react-text-field/#uncontrolled-vs-controlled
https://deploy-preview-35974--material-ui.netlify.app/material-ui/react-text-field/#uncontrolled-vs-controlled
> [docs] Improve inline preview's information

- docs/data/base/pages.ts
- docs/data/material/pages.ts
- docs/data/system/pages.ts
- docs/src/pages.ts
I was trying to understand who uses https://github.com/mui/material-ui/blob/master/docs/data/base/pagesApi.js in the review of #35828. but I got no match for searching the import of `base/pagesApi` and many matches for `/pagesApi`. With this change, I can have a direct search hit.
@Janpot "Find all references" in VS Code doesn't work in this case. It seems that it only works with ESM.
Beyond it, 2. to make "Find all references" work, we first have to find where it's defined. The user flow: see it on GitHub and direct search doesn't work. 3. when we copy & paste files around, the import path break.
So overall, I think that we should use absolute imports as much as possible. However, with packages we publish on npm, the imports must be relative in the final pkg, having the imports relative …
> [core] Make it easier to find who is importing specific files

- docs/src/modules/components/SkipLink.tsx
- docs/src/modules/components/ThemeContext.js
- packages/mui-material/src/useMediaQuery/useMediaQuery.ts
- packages/mui-system/src/cssVars/createCssVarsProvider.js
Fix https://github.com/mui/material-ui/pull/35948#issuecomment-1404618509
> [blog] Fix dark mode support

- packages/mui-material/src/FormLabel/FormLabel.d.ts
This PR fixes https://github.com/mui/material-ui/issues/36035
This issue occurs on the same situation as https://github.com/mui/material-ui/issues/33165.
Explained on https://github.com/mui/material-ui/issues/36035#issuecomment-1415895742.
Before: https://codesandbox.io/s/sad-merkle-3swvv2?file=/src/Demo.tsx
After: https://codesandbox.io/s/nervous-morning-d5onc3?file=/src/Demo.tsx
> [FormLabel] Export `FormLabelOwnProps` from `FormLabel` to fix type error

- docs/src/components/icon/IconImage.tsx
- docs/src/components/pricing/PricingTable.tsx
- docs/src/components/productCore/CoreHero.tsx
- docs/src/components/productDesignKit/DesignKitHero.tsx
- docs/src/components/productTemplate/TemplateHero.tsx
- docs/src/components/productX/XHero.tsx
This layout shift was driving me crazy:
https://user-images.githubusercontent.com/3165635/216846962-d4302a3c-c530-4b2c-9184-f61978718ed9.mov
The issue was that `'& > *': { width: 28, height: 28 },` has no guarantees to win over the style rendered by its children with emotion (it used to be OK with JSS).
---
If you want help seeing it:
https://user-images.githubusercontent.com/3165635/216846956-e55772ef-180c-4f27-bbeb-63a0824549c0.mov
There is also one in the app bar that is annoying but it's outside of my scope.
> [website] Fix layout shift

- docs/src/components/banner/AppFrameBanner.tsx
- docs/src/featureToggle.js
- docs/src/route.ts
Add a banner to the main navigation bar on our docs linking to MUI X v6.
https://deploy-preview-36074--material-ui.netlify.app/material-ui/getting-started/overview/
> [docs] Add banner pointing to "Whats new" in MUI X page

- docs/pages/base/api/use-input.json
- docs/translations/api-docs/use-input/use-input.json
- packages/mui-base/src/InputUnstyled/useInput.ts
- packages/mui-base/src/InputUnstyled/useInput.types.ts
I tried to add a return interface to  UseInput MUI Base Hooks (Those hooks are defined in this issue https://github.com/mui/material-ui/issues/35933).
- added return value type
> [useInput] Add return value interface

- docs/src/modules/components/AppNavDrawer.js
We are already on `beta`, having `v6-alpha` on navigation no longer makes sense.
> [docs] Rename `v6-alpha` to `v6-next` in navigation

- docs/data/base/components/badge/badge.md
- docs/data/base/components/button/button.md
- docs/data/base/components/input/input.md
- docs/data/base/components/menu/menu.md
- docs/data/base/components/select/select.md
- docs/data/base/components/slider/slider.md
- docs/data/base/components/switch/switch.md
- docs/data/base/components/table-pagination/table-pagination.md
- docs/data/base/components/tabs/tabs.md
- docs/src/modules/components/Demo.js
Originally raised in https://github.com/mui/material-ui/pull/35741#issuecomment-1377939041, the bug: https://mui.com/base/react-input/#introduction shows TypeScript while the developer is asking for JavaScript:
This PR fixes these bugs and throws an error if a TS demo is used directly instead of plain JS. It also fixes the export to CodeSandbox.
> [docs] Fix demos showing TypeScript instead of JavaScript

- CHANGELOG.old.md
- CONTRIBUTING.md
- docs/data/material/getting-started/learn/learn.md
- docs/data/material/guides/routing/routing-zh.md
- docs/data/material/guides/routing/routing.md
- docs/pages/blog/2020.md
- docs/pages/blog/2021.md
- docs/pages/blog/build-layouts-faster-with-grid-v2.md
- docs/pages/blog/date-pickers-stable-v5.md
- docs/pages/blog/december-2019-update.md
- docs/pages/blog/first-look-at-joy.md
- docs/pages/blog/lab-date-pickers-to-mui-x.md
- docs/pages/blog/material-ui-is-now-mui.md
- docs/pages/blog/material-ui-v1-is-out.md
- docs/pages/blog/mui-core-v5.md
- docs/pages/blog/premium-plan-release.md
- docs/pages/experiments/docs/blog.js
- docs/pages/experiments/docs/blog.md
- docs/src/modules/components/TopLayoutBlog.js
Fix the handling of the media caption in the blog posts:
```html
<p class="blog-description">The feature in action, from the docs page.</p>
```
**Before**: https://mui.com/blog/2022-tenerife-retreat/#destination
**After**: https://deploy-preview-36069--material-ui.netlify.app/blog/2022-tenerife-retreat/#destination
I noticed this working on https://github.com/mui/material-ui/pull/35839.
> [blog] Fix the look and feel of the media description

- docs/src/components/home/MaterialDesignComponents.tsx
I could pinpoint the origin of this migration to v5.11.0 See https://6398768e1aba5f000883fb24--material-ui-docs.netlify.app/, and more specifically, it was broken in: #35366. This is not MD:
https://mui.com/
---
With this fix:
> [website] Fix homepage MD theme demo

- docs/pages/base/api/use-tab.json
- docs/translations/api-docs/use-tab/use-tab.json
- packages/mui-base/src/TabUnstyled/useTab.ts
- packages/mui-base/src/TabUnstyled/useTab.types.ts
UseTab return value interface
closes: useTab in https://github.com/mui/material-ui/issues/35933
preview: https://deploy-preview-36046--material-ui.netlify.app/base/api/use-tab/#return-value
> [Tab] Add explicit return type to useTab

- packages/mui-base/src/AutocompleteUnstyled/useAutocomplete.js
- packages/mui-base/src/AutocompleteUnstyled/useAutocomplete.test.js
closes: https://github.com/mui/material-ui/issues/36055
Before: https://codesandbox.io/s/suspicious-dust-yxwwst?file=/src/App.tsx
After: https://codesandbox.io/s/wizardly-hugle-rsin57
> [useAutocomplete] Fix `useAutocomplete` disabled prop not disabling the input

- dangerfile.ts
- docs/pages/_app.js
- docs/src/modules/utils/useRouterExtra.ts
**Before**:
Even if there is no docs change, the preview URL should show.
**After**:
---
> [core] Add default preview url

- examples/vitejs/index.html
The [documentation](https://mui.com/material-ui/react-typography/#general) says Roboto font is not automatically loaded by MUI. The user should explicitly load this font in the vitejs example project.
> [examples][vitejs] Load Roboto font

- packages/mui-base/src/BadgeUnstyled/BadgeUnstyled.types.ts
- packages/mui-base/src/ButtonUnstyled/ButtonUnstyled.types.ts
- packages/mui-base/src/FormControlUnstyled/FormControlUnstyled.types.ts
- packages/mui-base/src/FormControlUnstyled/index.ts
- packages/mui-base/src/InputUnstyled/InputUnstyled.types.ts
- packages/mui-base/src/MenuItemUnstyled/MenuItemUnstyled.types.ts
- packages/mui-base/src/MenuUnstyled/MenuUnstyled.types.ts
- packages/mui-base/src/ModalUnstyled/ModalUnstyled.types.ts
- packages/mui-base/src/MultiSelectUnstyled/MultiSelectUnstyled.spec.tsx
- packages/mui-base/src/MultiSelectUnstyled/MultiSelectUnstyled.types.ts
- packages/mui-base/src/OptionGroupUnstyled/OptionGroupUnstyled.types.ts
- packages/mui-base/src/OptionUnstyled/OptionUnstyled.types.ts
- packages/mui-base/src/PopperUnstyled/PopperUnstyled.types.ts
- packages/mui-base/src/SelectUnstyled/SelectUnstyled.spec.tsx
- packages/mui-base/src/SelectUnstyled/SelectUnstyled.types.ts
- packages/mui-base/src/SliderUnstyled/SliderUnstyled.types.ts
- packages/mui-base/src/SnackbarUnstyled/SnackbarUnstyled.types.ts
- packages/mui-base/src/SwitchUnstyled/SwitchUnstyled.types.ts
- packages/mui-base/src/TabPanelUnstyled/TabPanelUnstyled.types.ts
- packages/mui-base/src/TabUnstyled/TabUnstyled.types.ts
- packages/mui-base/src/TablePaginationUnstyled/TablePaginationActionsUnstyled.types.ts
- packages/mui-base/src/TablePaginationUnstyled/TablePaginationUnstyled.types.ts
- packages/mui-base/src/TabsListUnstyled/TabsListUnstyled.types.ts
- packages/mui-base/src/TabsUnstyled/TabsUnstyled.types.ts
- packages/mui-base/test/typescript/moduleAugmentation/selectUnstyledComponentsProps.spec.tsx
- packages/mui-base/test/typescript/moduleAugmentation/sliderComponentsProps.spec.tsx
Closes https://github.com/mui/material-ui/issues/34906
This PR goes with option 1 described in the issue above
> 1. Have a separate type for each slot override (see #35662)
```ts
export interface BadgeUnstyledRootSlotPropsOverrides {}
export interface BadgeUnstyledBadgeSlotPropsOverrides {}
export interface BadgeUnstyledOwnProps {
// ...
slotProps?: {
root?: SlotComponentProps<
'span',
BadgeUnstyledRootSlotPropsOverrides,
BadgeUnstyledOwnerState
>;
badge?: SlotComponentProps<
'span',
BadgeUnstyledBadgeSlotPropsOverrides,
BadgeUnstyledOwnerState
>;
};
}
```
>  This could be slightly easier to use for developers. They would augment the required interface and the changes will apply only to one slot.
It would be slightly more cumbersome to implement, though, and would create many new types …
> [base] Override the types of `slotProps` per slot

- packages/mui-joy/src/Divider/Divider.tsx
- packages/mui-joy/src/Divider/DividerProps.ts
- packages/mui-joy/src/FormHelperText/FormHelperText.tsx
- packages/mui-joy/src/FormHelperText/FormHelperTextProps.ts
- packages/mui-joy/src/ListDivider/ListDivider.tsx
- packages/mui-joy/src/ListDivider/ListDividerProps.ts
- packages/mui-joy/src/ListItemButton/ListItemButton.tsx
- packages/mui-joy/src/ListItemButton/ListItemButtonProps.ts
- packages/mui-joy/src/ListItemContent/ListItemContent.tsx
- packages/mui-joy/src/ListItemContent/ListItemContentProps.ts
- packages/mui-joy/src/ListItemDecorator/ListItemDecorator.tsx
- packages/mui-joy/src/ListItemDecorator/ListItemDecoratorProps.ts
- Many Joy components still support `classes` prop. This PR drops the prop from these components.
It would be easier to merge this only after we merge https://github.com/mui/material-ui/pull/36008 to have less conflict
> [Joy] Remove classes prop from the components that have it

- packages/mui-base/src/AutocompleteUnstyled/useAutocomplete.js
- packages/mui-joy/src/Autocomplete/Autocomplete.test.tsx
- packages/mui-material/src/Autocomplete/Autocomplete.test.js
This PR fixes the regression introduced in #35735 and described in #36114.
It makes sure the options that are compared exist.
Before: https://codesandbox.io/s/recursing-snyder-ybg6m5?file=/demo.tsx
After: https://codesandbox.io/s/hardcore-einstein-yx1xwr?file=/demo.tsx
(see the linked issue for repro steps)
Fixes #36114.
> [Autocomplete] Fix tag removal regression

- docs/src/modules/components/MaterialYouUsageDemo.tsx
- packages/mui-material-next/src/styles/extendTheme.test.ts
- packages/mui-material-next/src/styles/extendTheme.ts
**Preview**: https://deploy-preview-36177--material-ui.netlify.app/material-ui/react-button/#material-you-version
- To follow the [spec](https://m3.material.io/styles/color/the-color-system/tokens) and leverage the official Figma tool for exporting the theme.
Below is what I get from the [Material Theme Builder](https://www.figma.com/community/plugin/1034969338659738588/Material-Theme-Builder).
- This will also ensure that Material UI and Material You can coexist on the same page without clashing due to different prefixes.
---
> [Material You] Use `md` as a CSS var prefix

- docs/pages/base/api/use-autocomplete.json
- docs/pages/base/api/use-badge.json
- docs/pages/base/api/use-button.json
- docs/pages/base/api/use-input.json
- docs/pages/base/api/use-menu-item.json
- docs/pages/base/api/use-menu.json
- docs/pages/base/api/use-slider.json
- docs/pages/base/api/use-snackbar.json
- docs/pages/base/api/use-switch.json
- docs/pages/base/api/use-tab-panel.json
- docs/pages/base/api/use-tab.json
- docs/pages/base/api/use-tabs-list.json
- docs/pages/base/api/use-tabs.json
- docs/src/modules/components/PropertiesTable.js
- packages/api-docs-builder/ApiBuilders/HookApiBuilder.ts
Fixes regression from https://github.com/mui/material-ui/pull/35828 on the component's API prop types.
Before: https://mui.com/base/api/tab-unstyled/
After: https://deploy-preview-36168--material-ui.netlify.app/base/api/tab-unstyled/
Hooks pages are not affected by the change:
Before: https://master--material-ui.netlify.app/base/api/use-tab/
After: https://deploy-preview-36168--material-ui.netlify.app/base/api/use-tab/
> [docs] Fix the prop type regression on the API pages

- packages/mui-joy/src/Box/Box.test.js
- packages/mui-joy/src/Box/Box.tsx
- packages/mui-joy/src/Grid/Grid.test.js
- packages/mui-joy/src/Grid/Grid.tsx
- packages/mui-joy/src/Stack/Stack.test.js
- packages/mui-joy/src/Stack/Stack.tsx
closes part of : https://github.com/mui/material-ui/issues/36082
tried changing classnames of Box from JoyBox-root to MuiBox-root but some existing tests were failing and i was bit spectical on changes introduced
> [Grid][Stack] classNames prefixed with Mui

- packages/mui-base/src/AutocompleteUnstyled/useAutocomplete.js
- packages/mui-base/src/AutocompleteUnstyled/useAutocomplete.test.js
- packages/mui-joy/src/Autocomplete/Autocomplete.test.tsx
- packages/mui-material/src/Autocomplete/Autocomplete.test.js
The `getOptionLabel` prop shouldn't be called with fallback values, as it will not match the TypeScript's contract for generic `getOptionLabel` value.
Fixes #36045
Before: https://codesandbox.io/s/angry-tree-2jcp3o?file=/src/App.tsx
After: https://codesandbox.io/s/frosty-tdd-euyttl?file=/src/App.tsx
> [useAutocomplete] Pass only valid values for the getOptionLabel prop

- packages/mui-styled-engine/src/StyledEngineProvider/StyledEngineProvider.js
Fixes https://github.com/mui/material-ui/issues/36096, a regression from https://github.com/mui/material-ui/pull/36001. The emotion cache provided previously could have been undefined, which was throwing an error. The changes were tested locally, the codesandboxes takes ages to load for me 😕 
Before: https://codesandbox.io/s/lucid-dan-n6hu29?file=/package.json
After: https://codesandbox.io/s/pensive-violet-on5wym?file=/package.json
> [StyledEngineProvider] Fix issue with cache not being defined

- docs/pages/base/api/use-option.json
Ran `yarn docs:api` to regenerate the docs. This was necessary after #36168 was merged without considering the changes from #35946
> [Select][base] Update the generated docs

- docs/src/modules/components/AppSearch.js
That's basically it! Some small tweaks in colors for that component, just to fine-tune a bit more. Also reduced slightly the `minWidth` so we gain a bit more space, especially when there are banners on the side of it.
> [docs] Small color tweaks to the docs search bar

- docs/data/joy/components/alert/alert.md
- docs/data/joy/components/aspect-ratio/aspect-ratio.md
- docs/data/joy/components/avatar/avatar.md
- docs/data/joy/components/badge/badge.md
- docs/data/joy/components/breadcrumbs/breadcrumbs.md
- docs/data/joy/components/button/button.md
- docs/data/joy/components/card/card.md
- docs/data/joy/components/checkbox/checkbox.md
- docs/data/joy/components/grid/grid.md
- docs/data/joy/components/input/input.md
- docs/data/joy/components/stack/stack.md
- docs/data/joy/components/typography/typography.md
Found this while looking into #36082.
> [docs][joy] Update class name prefixes in the `Anatomy` section

- scripts/README.md
Small follow up to: https://github.com/mui/material-ui/pull/36113 – changed the list numbering syntax so it's more readable as plain text
> [docs] Change markdown numbering syntax

- docs/pages/material-ui/api/badge.json
- packages/mui-material/src/Badge/Badge.d.ts
- packages/mui-material/src/Badge/Badge.js
- packages/mui-material/src/Badge/Badge.test.js
Closes https://github.com/mui/material-ui/issues/36130
Solves part of https://github.com/mui/material-ui/issues/34502
- Material `Badge` is implemented using `BadgeUnstyled` at the moment. It is replaced with `useBadge` hook in this PR since we want to implement design system components with hooks.
> [Badge][material] Replace `BadgeUnstyled` with `useBadge` hook

- docs/data/material/components/typography/typography.md
- docs/data/material/customization/typography/TypographyCustomVariant.js
- docs/data/material/customization/typography/TypographyCustomVariant.tsx
- docs/data/material/customization/typography/typography.md
Follow up to: https://github.com/mui/material-ui/issues/36005#issuecomment-1418452661
Preview: https://deploy-preview-36185--material-ui.netlify.app/material-ui/customization/typography/#adding-amp-disabling-variants
This PR expands a little more on how to add custom Typography variants to material-ui.
I am assuming that its very likely a user would want to (or want to know how to) specify the default HTML element for custom Typography variants if they are on this part of the docs, and it's not obvious (at least I completely missed it 🤦 ) that this is the way to do it until Jun pointed it out.
The most related existing doc about this is [here](https://mui.com/material-ui/react-typography/#changing-the-semantic-element) but it's not linked to from that page, and doesn't directly address …
> [docs] Update custom Typography variants example

- docs/data/base/components/input/InputAdornments.js
- docs/data/base/components/input/InputAdornments.tsx
- docs/data/base/components/input/InputMultiline.js
- docs/data/base/components/input/InputMultiline.tsx
- docs/data/base/components/input/InputMultilineAutosize.js
- docs/data/base/components/input/InputMultilineAutosize.tsx
- docs/data/base/components/input/UnstyledInputBasic.js
- docs/data/base/components/input/UnstyledInputBasic.tsx
- docs/data/base/components/input/UnstyledInputIntroduction.js
- docs/data/base/components/input/UnstyledInputIntroduction.tsx
- docs/data/base/components/input/UseInput.js
- docs/data/base/components/input/UseInput.tsx
Closes https://github.com/mui/material-ui/issues/36200
Preview link: https://deploy-preview-36213--material-ui.netlify.app/base/react-input/
Workaround for a Safari [bug](https://bugs.webkit.org/show_bug.cgi?id=20807) where `outline` doesn't respect `border-radius`
> [docs][base] Fix base Input demos for Safari

- packages/mui-material/src/Avatar/Avatar.js
- packages/mui-material/src/Avatar/Avatar.test.js
closes https://github.com/mui/material-ui/issues/36223
> [Avatar] Fix ownerState usage with styleOverrides when fallback is used

- docs/data/material/components/use-media-query/use-media-query.md
- packages/mui-material/src/styles/props.d.ts
- packages/mui-material/src/useMediaQuery/useMediaQuery.test.js
- packages/mui-material/src/useMediaQuery/useMediaQuery.ts
Closes #36054. The solution is to run `matchMedia` on the client side side when React calls `getServerSnapshot`. The docs says:
> **optional getServerSnapshot**: A function that returns the initial snapshot of the data in the store. It will be used only during server rendering and during hydration of server-rendered content on the client. The server snapshot must be the same between the client and the server, and is usually serialized and passed from the server to the client. If this function is not provided, rendering the component on the server will throw an error.
https://beta.reactjs.org/reference/react/useSyncExternalStore
In our case, when a developer set `noSsr: true` he explicitly opt-out from trying to hydrate with the first server-side render, while he also server-side render. …
> [useMediaQuery] Fix behavior of noSsr with React 18

- docs/data/base/components/modal/NestedModal.js
- docs/data/base/components/modal/NestedModal.tsx
- docs/data/base/components/modal/SpringModal.js
- docs/data/base/components/modal/SpringModal.tsx
- docs/data/base/components/modal/TransitionsModal.js
- docs/data/base/components/modal/TransitionsModal.tsx
- docs/data/material/components/modal/NestedModal.js
- docs/data/material/components/modal/NestedModal.tsx
- docs/data/material/components/modal/SpringModal.js
- docs/data/material/components/modal/SpringModal.tsx
- docs/data/material/components/modal/TransitionsModal.js
- docs/data/material/components/modal/TransitionsModal.tsx
- docs/pages/material-ui/api/backdrop.json
- docs/translations/api-docs/backdrop/backdrop.json
- packages/mui-base/src/utils/isHostComponent.ts
- packages/mui-base/src/utils/mergeSlotProps.ts
- packages/mui-base/src/utils/types.ts
- packages/mui-material/src/Backdrop/Backdrop.d.ts
- packages/mui-material/src/Backdrop/Backdrop.js
The two demos in https://mui.com/base/react-modal/#transitions have broken animations. It feels all off.
I noticed this in #36023.
https://deploy-preview-36137--material-ui.netlify.app/base/react-modal/#transitions
> [docs] Fix modal transition demos

- packages/mui-joy/src/AutocompleteListbox/AutocompleteListbox.tsx
- packages/mui-joy/src/Badge/Badge.tsx
- packages/mui-joy/src/Menu/Menu.tsx
- packages/mui-joy/src/Modal/Modal.tsx
- packages/mui-joy/src/Select/Select.tsx
- packages/mui-joy/src/Table/Table.tsx
- packages/mui-joy/src/Tooltip/Tooltip.tsx
- packages/mui-joy/src/styles/CssVarsProvider.test.tsx
- packages/mui-joy/src/styles/defaultTheme.test.js
- packages/mui-joy/src/styles/defaultTheme.ts
- packages/mui-joy/src/styles/extendTheme.test.js
- packages/mui-joy/src/styles/extendTheme.ts
- packages/mui-joy/src/styles/types/theme.ts
- packages/mui-joy/src/styles/types/zIndex.ts
- test/e2e-website/joy-docs.spec.ts
fix https://github.com/mui/material-ui/pull/36181#discussion_r1109785758
> [Joy] Add `zIndex` to theme

- packages/mui-joy/src/Divider/Divider.tsx
- packages/mui-joy/src/ListDivider/ListDivider.test.js
- packages/mui-joy/src/ListDivider/ListDivider.tsx
- packages/mui-joy/src/ListDivider/ListDividerProps.ts
From https://codesandbox.io/s/joy-ui-feat-radix-accordion-4n2p04?file=/demo.tsx, the `ListDivider` does not change from `li` to `div` when List has a custom component.
```js
<List component="div">
<ListDivider /> // => should be `div` without `role`.
```
> [Joy] Fix `ListDivider` to change semantic based on `List`

- docs/pages/base/api/modal-unstyled.json
- docs/pages/base/api/slider-unstyled.json
- docs/pages/base/api/table-pagination-unstyled.json
- docs/pages/material-ui/api/modal.json
- docs/translations/api-docs/modal-unstyled/modal-unstyled.json
- docs/translations/api-docs/modal/modal-zh.json
- docs/translations/api-docs/modal/modal.json
- docs/translations/api-docs/slider-unstyled/slider-unstyled.json
- docs/translations/api-docs/table-pagination-unstyled/table-pagination-unstyled.json
- packages/mui-base/src/InputUnstyled/inputUnstyledClasses.ts
- packages/mui-base/src/ModalUnstyled/ModalUnstyled.tsx
- packages/mui-base/src/ModalUnstyled/ModalUnstyled.types.ts
- packages/mui-base/src/ModalUnstyled/index.ts
- packages/mui-base/src/ModalUnstyled/modalUnstyledClasses.ts
- packages/mui-base/src/SliderUnstyled/SliderUnstyled.tsx
- packages/mui-base/src/SliderUnstyled/SliderUnstyled.types.ts
- packages/mui-base/src/TablePaginationUnstyled/TablePaginationActionsUnstyled.types.ts
- packages/mui-base/src/TablePaginationUnstyled/TablePaginationUnstyled.types.ts
- packages/mui-base/src/TablePaginationUnstyled/tablePaginationUnstyledClasses.ts
- packages/mui-joy/src/Slider/SliderProps.ts
- packages/mui-material/src/Modal/Modal.d.ts
- packages/mui-material/src/Modal/Modal.js
- packages/mui-material/src/Modal/Modal.test.js
- packages/mui-material/src/Slider/Slider.d.ts
- packages/mui-material/src/Slider/Slider.js
- packages/mui-material/src/Slider/Slider.test.js
Closes https://github.com/mui/material-ui/issues/36129
`ModalUnstyled`, `SliderUnstyled`, `TablePaginationUnstyled` and `TablePaginationActionsUnstyled` still support `classes` prop. This PR drops the prop from these components.
> [base] Remove `classes` prop from the Base components that have it

- docs/translations/api-docs/alert/alert.json
- docs/translations/api-docs/backdrop/backdrop.json
- docs/translations/api-docs/badge/badge.json
- docs/translations/api-docs/filled-input/filled-input.json
- docs/translations/api-docs/input-base/input-base.json
- docs/translations/api-docs/input/input.json
- docs/translations/api-docs/list-item/list-item.json
- docs/translations/api-docs/modal/modal.json
- docs/translations/api-docs/outlined-input/outlined-input.json
- docs/translations/api-docs/pagination-item/pagination-item.json
- docs/translations/api-docs/popper/popper.json
- docs/translations/api-docs/slider/slider.json
- docs/translations/api-docs/tooltip/tooltip.json
- packages/api-docs-builder/ApiBuilders/ComponentApiBuilder.ts
Some Material UI Components have this text in the description of `slots` prop when it shouldn't.
**Before**: https://deploy-preview-36104--material-ui.netlify.app/material-ui/api/alert/#slots
**After**: https://deploy-preview-36284--material-ui.netlify.app/material-ui/api/alert/#slots
> [docs] Remove See Slots Section text from Material UI slots description

- docs/src/modules/components/AppFrame.js
- docs/src/modules/components/AppLayoutDocs.js
After a stable MUI X release, in MUI X v5 docs, a notification for v6 is needed to be shown similar to the one [here](https://v4.mui.com/) for v5.
Exposing a prop from `AppLayoutDocs` which receives `Banner` component will allow to:
- Control banner visibility directly from MUI X docs
- Show banner only on MUI X docs (as needed for v5 because both `v5.mui.com` and `mui.com` will point to the same version of MUI Core but different of MUI X, so adding a banner like today won't do the need full.)
- Not have to bump monorepo everytime a new banner is needed in X
This PR will be accompanied by update in docs-v5 adding banner on MUI-X stable release.
> [docs] Allow to pass navigation bar banner from outside

- examples/material-next-ts-v4-v5-migration/README.md
This path was not updated in README. I noticed this while reviewing PR #36109.
> [examples] Update curl link in `material-next-ts-v4-v5-migration` example README

- docs/src/pages/careers/ROLE_TEMPLATE.md
- docs/src/pages/careers/accessibility-engineer.md
- docs/src/pages/careers/design-engineer.md
- docs/src/pages/careers/designer.md
- docs/src/pages/careers/developer-experience-engineer.md
- docs/src/pages/careers/engineering-manager.md
- docs/src/pages/careers/full-stack-engineer.md
- docs/src/pages/careers/lead-designer.md
- docs/src/pages/careers/product-engineer.md
- docs/src/pages/careers/react-engineer-core.md
- docs/src/pages/careers/react-engineer-x-grid.md
- docs/src/pages/careers/react-engineer-x.md
- docs/src/pages/careers/react-support-engineer.md
- docs/src/pages/careers/react-tech-lead-core.md
- docs/src/pages/careers/react-tech-lead-x-grid.md
Fix https://groups.google.com/a/mui.com/g/job/c/dPr5Q8bdkII. I broke these links when I transfered the ownership of the Google Sheet from my personal Google account to MUI's workspace. I think that it's a good opportunity to link the Notion page instead.
> [website] Fix broken links to role levels

- docs/data/joy/components/divider/divider.md
- docs/data/joy/components/modal/DialogVerticalScroll.js
- docs/data/joy/components/modal/modal.md
- packages/mui-joy/src/ModalDialog/ModalDialog.tsx
close #36094
Fixed by setting `maxHeight` and making the ModalDialog a flex column by default, so that the children with long content can be full height overflow
---
> [Joy] Fix modal dialog overflow viewport

- examples/material-next-ts/package.json
- examples/material-next-ts/src/theme.ts
- examples/material-next/package.json
- examples/material-next/src/theme.js
Starting with Next.js 13.2, `@next/font` is now built-in to Next.js as `next/font`. We no longer need to install `@next/font` separately.
Reference: https://nextjs.org/blog/next-13-2#other-improvements
Reference: https://nextjs.org/docs/messages/built-in-next-font
> [examples] Update Next.js examples to use built-in font

- packages/mui-material/src/InputLabel/InputLabel.js
I never thought that there would still be bugs opportunities in this outline input 😁. You can reproduce this on https://codesandbox.io/s/muddy-leaf-t4y7z5?file=/package.json
```jsx
import Box from "@mui/material/Box";
import TextField from "@mui/material/TextField";
export default function BasicTextFields() {
return (
<Box sx={{ m: 2 }}>
<TextField
id="outlined-basic"
InputLabelProps={{ shrink: true }}
label="Foo Foo Foo Foo Foo Foo Foo F"
variant="outlined"
/>
</Box>
);
}
```
Before:
After:
---
I have noticed this on https://next.mui.com/x/react-date-pickers/getting-started/#installation, it's broken:
> [TextField] Fix floating label position

- packages/mui-base/src/PopperUnstyled/PopperUnstyled.types.ts
- packages/mui-base/src/PopperUnstyled/index.ts
- packages/mui-base/src/TabPanelUnstyled/TabPanelUnstyled.types.ts
- packages/mui-base/src/TabUnstyled/TabUnstyled.types.ts
- packages/mui-base/src/TabsListUnstyled/TabsListUnstyled.types.ts
- packages/mui-base/src/TabsUnstyled/TabsUnstyled.types.ts
As noted in https://github.com/mui/material-ui/pull/35964#discussion_r1117542959, some of the slot prop override interfaces were not exported. This PR exports all of them.
> [base] Export all slot prop overrides interfaces

- docs/data/joy/components/divider/DividerChildPosition.tsx
- docs/data/joy/components/divider/DividerChildPosition.tsx.preview
- docs/data/joy/components/divider/DividerInCard.tsx
- docs/data/joy/components/divider/DividerInModalDialog.tsx
- docs/data/joy/components/divider/DividerText.tsx
- docs/data/joy/components/divider/DividerText.tsx.preview
- docs/data/joy/components/divider/DividerUsage.tsx
- docs/data/joy/components/divider/FullscreenOverflowDivider.tsx
- docs/data/joy/components/divider/VerticalDividerText.tsx
- docs/data/joy/components/divider/VerticalDividerText.tsx.preview
- docs/data/joy/components/divider/VerticalDividers.tsx
part of https://github.com/mui/material-ui/issues/36367
> [docs][joy] Add typescript demos for `Divider`

- docs/data/styles/advanced/advanced.md
Fix a regression introduced in #36112 reported by the SEO crawl of ahrefs
- https://github.com/mui/material-ui/blob/814fb60bbd8e500517b2307b6a297a638838ca89/examples/material-next/pages/_document.js#L52-L59 is a 404.
- The other links are out of sync with the docs. Instead of showing how to use `@mui/system` with Material UI v5, I have updated the links to show how to use `@material-ui/styles` with Material UI v4. v5 is closer to v4 than `@mui/system` to `@mui/styles`.
Ideally, we would create new examples for `@mui/styles` but it's unlikely to be ever important enough to be on the priority list.
Preview: https://deploy-preview-36331--material-ui.netlify.app/system/styles/advanced/#server-side-rendering
> [docs] Fix @mui/styles example links

- docs/data/material/components/radio-buttons/radio-buttons.md
- docs/src/modules/components/MarkdownElement.js
This is a continuation of https://github.com/mui/mui-x/pull/7899 to solve the problem differently. Instead of removing the use of loose lists for only tight lists, we can improve how loose lists are displayed to not feel broken. Each would have its own use cases:
a tight list for: bullet points
a loose list for: list paragraphs
The style of the docs currently didn't take into account that [looses](https://spec.commonmark.org/0.30/#loose) lists could exist. The UX (visual design aspect of it) feels broken on https://next.mui.com/x/react-date-pickers/base-concepts/#responsiveness
---
I'm also using a loose list in https://deploy-preview-36190--material-ui.netlify.app/material-ui/react-radio-button/#accessibility now, as it seems to make sense in this context.
> [docs] Improve visual look of loose lists

- docs/src/components/banner/AppFrameBanner.tsx
Context: See https://github.com/mui/material-ui/pull/36299#discussion_r1115212728
Should be merged after MUI X stable release, followed by docs redeploy as mentioned in #36301
> [docs] Update MUI X banner to reflect stable release

- packages/mui-joy/src/Autocomplete/Autocomplete.tsx
Closes #36395
**Preview**: https://deploy-preview-36397--material-ui.netlify.app/joy-ui/react-autocomplete
> [Autocomplete][joy] Add disabled class to the popup indicator

- packages/mui-base/src/useMenu/useMenu.ts
Resolves comment https://github.com/mui/material-ui/pull/36265#discussion_r1123660124
> [useMenu] Fix `import type` syntax

- docs/package.json
- package.json
- packages/typescript-to-proptypes/package.json
- yarn.lock
Reverts mui/material-ui#36350 It breaks the `yarn docs:api` on Windows.
> Revert "Bump rimraf to ^4.1.3"

- scripts/README.md
> [docs] Add instructions for deploying docs without a release

- packages/mui-lab/src/TreeItem/TreeItem.js
Checks if the Node.getRootNode() function is available and use it in handleFocus to prevent a crash when running inside a shadow root.
Fixes #36224
> [TreeView] Fix Tree View inside shadow root crashes

- docs/data/joy/getting-started/tutorial/tutorial.md
- docs/data/joy/getting-started/usage/usage.md
- docs/data/joy/guides/using-icon-libraries/using-icon-libraries.md
After https://github.com/mui/material-ui/pull/35739, the using of CssVarsProvider in Joy UI apps is not required, unless it is used together with the Material UI icons - this is when we need to provide context theme change for the icon components. We may be able to solve this in the future, by updating the icon's styles in Material UI.
> [docs][joy] Clarify when `CssVarsProvider` is required

- examples/material-next-ts-v4-v5-migration/pages/_app.tsx
- examples/material-next-ts-v4-v5-migration/pages/_document.tsx
- examples/material-next-ts/pages/_app.tsx
- examples/material-next-ts/pages/_document.tsx
Two minor typing changes in this example:
- instead of using `any` as the type for the `App` component just so we don't get an error when using the `emotionCache` prop, we define a new component with the right props (the props from Next.js' `AppType` component, plus our `MyAppProps` defined in the `_app.tsx` file)
- the `EmotionJSX.Element` type is just an alias for `JSX.Element`, so I think we can avoid this import here
> [examples] Refactor to have better types in the Next.js + TypeScript examples

- CONTRIBUTING.md
Closes #36435
**Before**
- [Link](https://github.com/mui/material-ui/blob/master/CONTRIBUTING.md#how-can-i-use-a-change-that-wasnt-released-yet)
**After**
- [Link](https://github.com/hbjORbj/material-ui/blob/docs/contributing-readme/CONTRIBUTING.md#how-can-i-use-a-change-that-wasnt-released-yet)
> [docs] Info markdown not rendering in Contributing Guide README

- packages/mui-joy/src/styles/types/theme.ts
- packages/mui-material-next/src/styles/Theme.types.ts
- packages/mui-material-next/src/styles/extendTheme.ts
- packages/mui-material-next/src/styles/index.ts
- packages/mui-material-next/src/styles/shouldSkipGeneratingVar.ts
- packages/mui-material/src/styles/experimental_extendTheme.d.ts
- packages/mui-material/src/styles/experimental_extendTheme.js
- packages/mui-material/src/styles/index.d.ts
- packages/mui-material/src/styles/index.js
- packages/mui-material/src/styles/shouldSkipGeneratingVar.ts
- packages/mui-system/src/cssVars/createCssVarsProvider.d.ts
- packages/mui-system/src/cssVars/createCssVarsTheme.ts
- packages/mui-system/src/cssVars/cssVarsParser.ts
- packages/mui-system/src/cssVars/prepareCssVars.ts
Regression from #35739, `shouldSkipGeneratingVar` is not exported from `@mui/material/styles`.
**Before**: https://codesandbox.io/s/material-ui-feat-joy-ui-vvvv59?file=/demo.tsx
**After**: https://codesandbox.io/s/material-cra-ts-forked-xkczu2?file=/src/App.tsx
There are other minor fixes that I think can be batched with this fix.
- Extract `shouldSkipGeneratingVar` into a separate file for consistency between Material UI and Joy UI
- `generateCssVars` type is missing
- Some types in material-ui-next are redundant
---
> Export `shouldSkipGeneratingVar` from Material UI

- packages/mui-material/package.json
- yarn.lock
In the latest release (v5.11.12) (#36443), I made a mistake of adding a code snippet to `yarn.lock` to pass a CI test failure. This occurred because I didn't bump the version of `@mui/base` from alpha 119 to alpha 120 in the `package.json` of `@mui/material`. (The version of MUI Base itself was bumped and in other packages as well except for the `@mui/material`).
> **Note**
> 
> This PR doesn't need to be merged as this can be resolved as part of the v5.11.13 release on upcoming Monday. Opened this PR as a reference point just in case.
> [core] Remove wrong code from yarn.lock

- docs/data/joy/guides/using-joy-ui-and-material-ui/using-joy-ui-and-material-ui.md
Closes #36451
- The Codesandboxes in https://mui.com/joy-ui/guides/using-joy-ui-and-material-ui-together/ broke after we released the changes introduced in #35739 
- Before: (1) https://codesandbox.io/s/material-ui-feat-joy-ui-vvvv59?file=/demo.tsx and (2) https://codesandbox.io/s/joy-ui-feat-material-ui-k86j2j?file=/demo.tsx
- After: (1) https://codesandbox.io/s/material-ui-feat-joy-ui-1jkvm9?file=/demo.tsx and (2) https://codesandbox.io/s/joy-ui-feat-material-ui-zhcprk?file=/demo.tsx
- https://deploy-preview-36462--material-ui.netlify.app/joy-ui/guides/using-joy-ui-and-material-ui-together/
> [docs][joy] Error in the exemplary Codesandbox of using Material UI and Joy UI together

- docs/data/joy/components/list/list.md
- docs/data/joy/components/radio/radio.md
- packages/mui-codemod/src/v5.0.0/rename-css-variables.js
- packages/mui-codemod/src/v5.0.0/rename-css-variables.test/actual.js
- packages/mui-codemod/src/v5.0.0/rename-css-variables.test/expected.js
- packages/mui-joy/src/List/List.tsx
- packages/mui-joy/src/List/ListProvider.tsx
- packages/mui-joy/src/ListItem/ListItem.tsx
- packages/mui-joy/src/ListItemButton/ListItemButton.tsx
- packages/mui-joy/src/ModalDialog/ModalDialog.tsx
- packages/mui-joy/src/Slider/Slider.spec.tsx
- packages/mui-joy/src/Switch/Switch.spec.tsx
- packages/mui-joy/src/Table/Table.tsx
- packages/mui-joy/src/Tooltip/Tooltip.tsx
Follow-up on #36282 
**This PR fixes**
- Replace `--private_...` with `--unstable_...`
- `--List-itemButtonMargin...` to `--ListItemButton-margin....`
- `--TooltipArrow-...` to `--Tooltip-arrow...`
**This PR adds**
- improvements to `rename-css-variables` Codemod script and its tests
> [Joy] Ensure new CSS variable naming is everywhere

- docs/data/material/components/chips/MultilineChips.js
- docs/data/material/components/chips/MultilineChips.tsx
- docs/data/material/components/chips/MultilineChips.tsx.preview
- docs/data/material/components/chips/chips.md
This adds a basic example on the docs regarding multilined chips. 
It's a known issue regarding `Autocomplete`  (#15185) and generic `Chip` (#14864). 
https://stackoverflow.com/questions/61385380/material-ui-autocomplete-chip-multiline.
Alternative solutions are:
- `Chip` component should export `labelProps`, like `labelProps`.
- Multiline chips should be the default behaviour.
> [docs] Add multiline Chip example

- packages/mui-material/src/StepButton/StepButton.js
- packages/mui-material/src/StepButton/StepButton.test.js
closes https://github.com/mui/material-ui/issues/36475
> [Stepper] Add `aria-current` to the active StepButton

- packages/mui-joy/src/Menu/Menu.tsx
- packages/mui-joy/src/Menu/menuClasses.ts
`menuClasses` exported from Joy `Menu` doesn't include `listbox`.
https://github.com/mui/material-ui/blob/d1662e4d83ed525af30c42a568dc05ac06968488/docs/data/joy/components/menu/MenuIconSideNavExample.js#L101
> [Menu][joy] Classname listbox is missing

- docs/data/joy/components/menu/BasicMenu.tsx
- docs/data/joy/components/menu/GroupMenu.js
- docs/data/joy/components/menu/GroupMenu.tsx
- docs/data/joy/components/menu/MenuIconSideNavExample.js
- docs/data/joy/components/menu/MenuIconSideNavExample.tsx
- docs/data/joy/components/menu/MenuListComposition.tsx
- docs/data/joy/components/menu/MenuListGroup.tsx
- docs/data/joy/components/menu/PositionedMenu.tsx
- docs/data/joy/components/menu/SelectedMenu.tsx
- docs/data/joy/components/menu/SizeMenu.tsx
Menu Part of [#36367](https://github.com/mui/material-ui/issues/36367)
> [docs][joy] Build TS versions for Menu component demos

- packages/mui-lab/src/themeAugmentation/components.d.ts
- packages/mui-lab/src/themeAugmentation/overrides.d.ts
- packages/mui-lab/src/themeAugmentation/props.d.ts
Closes #36240
**Before**: https://codesandbox.io/s/brave-mountain-pdxq44?file=/src/App.tsx
**After**: https://codesandbox.io/s/vigorous-orla-z6ug44?file=/src/App.tsx
> [Masonry] Include Masonry in theme augmentation interface

- packages/mui-system/src/styleFunctionSx/defaultSxConfig.js
- packages/mui-system/src/styleFunctionSx/styleFunctionSx.test.js
Fixes https://github.com/mui/material-ui/issues/36542, it was a regression from https://github.com/mui/material-ui/pull/33621. Test added to cover this functionality.
> [system] Fix sx prop regression for fontWeight values

- docs/pages/base/api/input-unstyled.json
- docs/pages/base/api/slider-unstyled.json
- docs/pages/joy-ui/api/chip.json
- docs/pages/joy-ui/api/slider.json
- packages/api-docs-builder/utils/parseSlots.ts
- packages/mui-base/src/ButtonUnstyled/buttonUnstyledClasses.ts
- packages/mui-base/src/ButtonUnstyled/index.ts
**Follow-up** on (5) of https://github.com/mui/material-ui/pull/36490#issuecomment-1465308374
- Classnames displayed in "Slots" section in API docs are wrong for some components' docs. For example, the className for the input slot and the valueLabel slot are wrong in https://deploy-preview-36499--material-ui.netlify.app/base/api/slider-unstyled/#slots. These classnames don't exist for `SliderUnstyled`.
- I improved `parseSlots` function so that only existing classnames are displayed.
**Before**
https://master--material-ui.netlify.app/base/api/slider-unstyled/#slots
**After**
https://deploy-preview-36539--material-ui.netlify.app/base/api/slider-unstyled/#slots
> [docs] Ensure classname displayed under Slots section in API docs exists

- docs/data/joy/guides/using-joy-ui-and-material-ui/using-joy-ui-and-material-ui.md
Since https://github.com/mui/material-ui/pull/35739, `shouldSkipGeneratingVar` has been moved to `extendTheme`. For using Joy and Material UI, there is no need to merge those functions. 
Remove them in the guide to make it a bit simpler.
> [docs] Remove `shouldSkipGeneratingVar` usage

- docs/data/material/guides/localization/localization.md
- packages/mui-material/src/locale/index.ts
> [l10n] Add Central Kurdish (ku-CKB) locale

- docs/data/material/components/grid2/NestedGridColumns.js
- docs/data/material/components/grid2/NestedGridColumns.tsx
- docs/data/material/components/grid2/grid2.md
- packages/mui-system/src/Unstable_Grid/gridGenerator.test.js
- packages/mui-system/src/Unstable_Grid/gridGenerator.ts
closes #36335
**Before**:
The nested grid container does not get the `--Grid-columns` value from its parent because it is overridden by its own variable. The fix is similar to how nested spacing works.
https://stackblitz.com/edit/react-6xxqec?file=demo.tsx
**After**
https://codesandbox.io/s/material-cra-ts-forked-55ep57?file=/src/App.tsx
---
> [Grid2] Support dynamic nested columns

- packages/mui-base/src/FormControlUnstyled/formControlUnstyledClasses.ts
- packages/mui-base/src/InputUnstyled/inputUnstyledClasses.ts
- packages/mui-base/src/MenuItemUnstyled/menuItemUnstyledClasses.ts
- packages/mui-base/src/MenuUnstyled/menuUnstyledClasses.ts
- packages/mui-base/src/OptionGroupUnstyled/optionGroupUnstyledClasses.ts
- packages/mui-base/src/OptionUnstyled/optionUnstyledClasses.tsx
- packages/mui-base/src/PopperUnstyled/popperUnstyledClasses.ts
- packages/mui-base/src/SelectUnstyled/selectUnstyledClasses.ts
- packages/mui-base/src/SwitchUnstyled/switchUnstyledClasses.ts
- packages/mui-base/src/TabPanelUnstyled/tabPanelUnstyledClasses.ts
- packages/mui-base/src/TabUnstyled/tabUnstyledClasses.ts
- packages/mui-base/src/TabsListUnstyled/tabsListUnstyledClasses.ts
- packages/mui-base/src/TabsUnstyled/tabsUnstyledClasses.ts
In #36539, I added JSDoc comments for classes of `ButtonUnstyled`. This PR is to do the same for those of other Base components to maintain consistency throughout the codebase.
> [Base] Add JSDoc comments for classes of Base components

- docs/data/joy/components/circular-progress/circular-progress.md
Hey @samuelsycamore!
Thought I'd try my hand at another. 
When I was doing this one, it didn't have an accessibility component, so I added the color ratio part. I noticed built into the component, there's ARIA labels already. I was contemplating adding them to the accessibility part but I'm not sure whether you're adding how to make components accessible in this, or explaining some of the out-of-the-box things.
The anatomy section also threw me off a bit. I know that adding the classes is important but I wasn't able to find any examples that had something similar to this one, where SVG tags and a circle tag was involved (really didn't even know this was an HTML tag lol). 
Let me know what you think and if there's anything else I need to revise!
Hope you're having a great day,
> [docs] Revise Joy UI "Circular Progress" page

- docs/src/modules/components/PropertiesTable.js
Resolves https://github.com/mui/material-ui/pull/35938#issuecomment-1486563297, it hides the default column in the API properties table if none of the properties have default value.
Previously:
Now:
> [docs] Hide the default API column if it's empty

- docs/translations/api-docs/badge/badge.json
- docs/translations/api-docs/slider/slider.json
- packages/mui-material/src/Badge/badgeClasses.ts
- packages/mui-material/src/Slider/sliderClasses.ts
**Changes**:
- `"Class name applied to..."` -> `"Styles applied to ..."` in Material `Badge` and `Slider` to keep consistency with the class descriptions of other Material components
> [docs][material] Keep consistency in description of classes

- packages/mui-joy/src/Grid/Grid.tsx
- packages/mui-material/src/Unstable_Grid2/Grid2.tsx
closes #36651
This bug is hidden because styled-component v5 uses `isPropValid` (same as emotion) so `sx` and `ownerState` never leak to DOM.
However, styled-component [v6 removes this automatic props filtering](https://github.com/styled-components/styled-components/releases/tag/v6.0.0-beta.14) so the `slot` is required to explicitly pass the `shouldForwardProp` to styled-component.
> [Grid] Missing slot

- docs/src/modules/components/ApiPage.js
- docs/src/modules/components/ComponentsApiContent.js
- docs/src/modules/components/MarkdownDocsV2.js
Backports changes from https://github.com/mui/material-ui/pull/36104 (and the follow-up improvements on it).
The slots information was missing in the new components API pages in Base UI:
- previously: https://master--material-ui.netlify.app/base/react-button/components-api/
- now: https://deploy-preview-36769--material-ui.netlify.app/base/react-button/components-api/
> [docs] Tabs API add slots section

- CHANGELOG.md
- CHANGELOG.old.md
- docs/data/joy/customization/themed-components/themed-components.md
- docs/data/material/customization/default-theme/default-theme.md
- docs/data/material/getting-started/supported-platforms/supported-platforms.md
- docs/data/material/guides/interoperability/interoperability.md
- docs/data/material/guides/routing/routing.md
- docs/data/material/migration/migration-v3/migration-v3.md
- docs/data/material/migration/migration-v4/migration-v4.md
- docs/data/material/migration/migration-v4/v5-style-changes.md
- docs/next.config.js
- docs/pages/blog/material-ui-v4-is-out.md
- docs/scripts/reportBrokenLinks.js
- docs/src/modules/utils/mapApiPageTranslations.js
- packages/markdown/loader.js
- packages/markdown/parseMarkdown.js
- packages/markdown/parseMarkdown.test.js
- packages/mui-joy/src/TextField/TextField.tsx
The objective is so that the links in the docs continue to work after the code on GitHub is changed. The developers will continue to browse the docs of older versions for a long time. We found the opportunity in https://github.com/mui/mui-x/pull/8383#issuecomment-1485983855.
Before: https://mui.com/joy-ui/customization/themed-components/ links to
`https://github.com/mui/material-ui/blob/master/packages/mui-joy/src/styles/components.d.ts`
After: https://deploy-preview-36729--material-ui.netlify.app/joy-ui/customization/themed-components/ links to
`https://github.com/mui/material-ui/blob/v5.11.15/packages/mui-joy/src/styles/components.d.ts`
> [docs] Introduce markdown permalink to source

- packages/mui-material/src/CardActionArea/CardActionArea.js
Closes https://github.com/mui/material-ui/issues/36285
Fixes this in Safari:
Demo: mouseover the card here - https://deploy-preview-36329--material-ui.netlify.app/material-ui/react-card/#primary-action
> [Card] Fix Card focus effect overflowing parent card

- packages/mui-base/src/useAutocomplete/useAutocomplete.js
- packages/mui-joy/src/Autocomplete/Autocomplete.test.tsx
- packages/mui-joy/src/Autocomplete/Autocomplete.tsx
- packages/mui-material/src/Autocomplete/Autocomplete.js
- packages/mui-material/src/Autocomplete/Autocomplete.test.js
closes https://github.com/mui/material-ui/issues/36364
preview: https://deploy-preview-36369--material-ui.netlify.app/joy-ui/react-autocomplete/
joy UI working video 
https://user-images.githubusercontent.com/60743144/222896115-46fe1248-2a38-46fe-9e29-e6cd91bd9ce5.mov
**material ui Working video**
https://www.loom.com/share/5386e85fa34049b2b481e44abfdade42
> [Autocomplete] Listen for click on the root element

- docs/pages/base/api/use-tab.json
- docs/translations/api-docs-joy/tab/tab.json
- docs/translations/api-docs/tab-unstyled/tab-unstyled.json
- docs/translations/api-docs/use-tab/use-tab.json
- packages/mui-base/src/TabUnstyled/TabUnstyled.tsx
- packages/mui-base/src/TabUnstyled/TabUnstyled.types.ts
- packages/mui-base/src/useTab/useTab.types.ts
- packages/mui-joy/src/Tab/Tab.tsx
- packages/mui-joy/src/Tab/TabProps.ts
> [Tabs] Improve useTab() API page

- docs/src/modules/components/ApiPage.js
- docs/src/modules/components/AppNavDrawerItem.js
- docs/translations/translations.json
- This is a follow-up of the suggestion I made during a discussion in a separate PR: https://github.com/mui/material-ui/pull/36586#discussion_r1145121013
- This PR is to make it clearer to developers the distinction between global state classes and component-level state classes
- **:warning:** If this PR is approved and merged, the same needs to be done for "Classes" table which is in Joy/Base API docs introduced in https://github.com/mui/material-ui/pull/36589
- Make global state classes in CSS table in API docs **bold**
- Add a heading below the section name "CSS": `"The following class names are useful for styling with CSS. The global state classes are in **bold**. To learn more about state classes, check out the [State classes](https://mui.com/material-ui/customization/how-to-customize …
> [docs][material] Highlight global state classes in CSS table in API docs

- docs/src/modules/components/AppNavDrawerItem.js
Following @oliviertassinari's suggestion on https://github.com/mui/material-ui/pull/36279?notification_referrer_id=NT_kwDOBABP4rM1NjU4NjExNzIyOjY3MTI5MzE0#issuecomment-1498315520: this PR changes the "coming soon" chip color from blue to gray, so it grabs less attention from the reader.
| <img width="200" alt="Screen Shot 2023-04-05 at 21 16 47" src="https://user-images.githubusercontent.com/67129314/230241653-b14379c3-af50-4d96-a987-e36abf14c86c.png"> | <img width="200" alt="Screen Shot 2023-04-05 at 21 16 38" src="https://user-images.githubusercontent.com/67129314/230241650-3d0e46ec-6dd4-4ad9-9063-2e2f08e1699d.png"> |
> [docs] Change "coming soon" chip color

- docs/data/material/discover-more/related-projects/related-projects.md
- docs/public/_redirects
A continuation of #34820. Ahrefs has a nice feature that allows seeing backlinks to mui.com that are now 404: https://app.ahrefs.com/v2-site-explorer/broken-backlinks?anchorRules=&domainNameRules=&followType=all&grouping=one-per-domain&limit=50&mode=prefix&offset=0&refPageTitleRules=&refPageUrlRules=&sort=traffic&sortDirection=desc&surroundingRules=&target=https%3A%2F%2Fmui.com%2F&targetUrlRules=. I couldn't find any other broken links that are really worth fixing, otherther than maybe pt and zh links, e.g. https://reactjsexample.com/pokedex-pokemon-api-with-reactjs/
> [website] Fix backlinks to homepage

- docs/src/modules/components/AppNavDrawer.js
- docs/src/modules/components/AppNavDrawerItem.js
I noticed this during the review of #35938. We need to reset the scroll sooner than what we anticipate for:
KO: open https://mui.com/material-ui/react-checkbox/ with a browser width small enough, see how the active link is cut, it's disorienting.
What we want, is to have the active link always in the viewport, and to also account for the URL overlay:
Preview: https://deploy-preview-36732--material-ui.netlify.app/material-ui/react-checkbox/. It's a new iteration on the logic, something we had many iterations on already, e.g. the last one #25619.
There is still one thing that I HATE about the current page navigation experience is that the whole side nav rerenders on each page change, we lose all the DOM state, which means:
- Strange hover behavior, there shouldn't be a flash of the active …
> [docs] Improve side nav scroll into view

- docs/data/material/customization/how-to-customize/how-to-customize.md
Add the missing `readOnly` global state class in the doc, which was added in #32822. I noticed this while I was reading the doc for an issue.
Preview: https://deploy-preview-36788--material-ui.netlify.app/material-ui/customization/how-to-customize/#state-classes
> [docs] Add missing `readOnly` state class in the list

- packages/mui-material/src/Tabs/ScrollbarSize.js
- [v] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/material-ui/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).
Closes #26587
As per https://reactjs.org/blog/2020/08/10/react-v17-rc.html#effect-cleanup-timing, timeout callback set by `debounce` can be called before effect cleanup, which can leads to calling `setMeasurements` with `nodeRef.current` unset.
> [Tabs] Fix null reference in ScrollbarSize after unmounting

- docs/src/components/header/HeaderNavBar.tsx
Bug reported in https://docs.google.com/document/d/1tMPDeUiLeb_3VGaosLSpbyiS3uLTRWXr23P3mvtRQy4/edit#.
**Before**: https://mui.com/
https://user-images.githubusercontent.com/3165635/231864864-0a74fea4-7551-4fe8-a8e6-a17ef7023ddf.mov
---
**After**: https://deploy-preview-36875--material-ui.netlify.app/
https://user-images.githubusercontent.com/3165635/231865088-6ab3ffe6-7921-4b0b-bda1-855e75ce42f5.mov
---
I used the opportunity to fix two things:
- make the focus style bolder than the hover style, see: https://m3.material.io/foundations/interaction/states/state-layers
- change the background area, it feels too tall.
> [website] Fix visual bug appbar

- packages/mui-material/src/Autocomplete/Autocomplete.js
Fixes https://github.com/mui/material-ui/issues/36630
I adjusted the padding between the root element of `Autocomplete` and the `<input>` itself so it aligns with similar components
Sandbox preview: https://codesandbox.io/s/https-github-com-mui-material-ui-pull-36649-cuhcqo?file=/src/App.tsx
> [Autocomplete] Fix autocomplete left padding

- packages/mui-material/src/styles/ThemeProvider.js
- packages/mui-material/src/styles/ThemeProvider.test.tsx
regression from #36664
The `theme` prop can be a function but it is not listed in the prop-types, so there is a warning in the docs.
---
> [ThemeProvider] Fix theme proptypes

- docs/data/base/components/button/button.md
The docs incorrectly state that the `ref` parameter is required in `useButton`. This PR fixes it and explains when to use the parameter.
Closes #36880
> [docs] Remove the incorrect info about useButton's ref parameter

- packages/mui-material/src/FormControl/FormControl.js
- packages/mui-material/src/FormControl/FormControl.test.js
closes https://github.com/mui/material-ui/issues/36744
before: https://www.loom.com/share/dd51510906a945849760449e4f6a0ba7
after: https://www.loom.com/share/441a51c2c10c4a60bcfe9315a99b2829
> [FormControl] Fix `filled` when value is set through `inputProps`

- docs/data/joy/components/input/input.md
Just a small change so you can now Ctrl+F to find how to pass `ref` to `<input/>` element. I think this is enough, but maybe it would be better if it would be it's own paragraph. Something like
> To get the `ref` of the `<input/>` element, you can use the `slotProps` prop
and a code example
> [docs] Add info about passing ref to input element

- packages/mui-base/src/TextareaAutosize/TextareaAutosize.tsx
- packages/mui-material-next/src/Button/TouchRipple.tsx
Adds the explicit return type for TextareaAutosize and material-next's TouchRipple, similarly to #36013. These two were inadvertently omitted from the mentioned PR.
Fixes #36571.
> [typescript] Add the missing explicit component return types

- docs/data/material/components/tabs/tabs.md
- test/e2e-website/material-docs.spec.ts
The tabs API already has an Unstyled section in the docs - https://mui.com/material-ui/react-tabs/#unstyled, no need to specify API for all Mateiral UI and Base UI APIs. There will be even more confusion once the name of the components are the same. This is left over from the time when we were documenting the Base UI's demos on the Material UI page. This is currently blocker for https://github.com/mui/material-ui/pull/36873.
I tried to see what it would take in order for the infra to support this one-off in https://github.com/mui/material-ui/pull/36936, but I don't think it's worth it.
> [docs][material] Tabs API section cleanup

- docs/data/material/components/material-icons/SearchIcons.js
- docs/data/material/components/material-icons/material-icons.md
- docs/src/modules/components/MarkdownElement.js
This PR does some copy/design/formatting adjustments to the Material Icons documentation page. I thought that the content on the current version was too tight, and the callout could be removed for less visual noise. Took advantage of the opportunity to do some light design tweaking as well ⎯ nothing big.
**👉 https://deploy-preview-36937--material-ui.netlify.app/material-ui/material-icons/**
| <img width="1658" alt="Screen Shot 2023-04-19 at 10 24 22" src="https://user-images.githubusercontent.com/67129314/233089454-fc852f02-9bbd-4868-9ac0-e60bfd182c5f.png"> | <img width="1658" alt="Screen Shot 2023-04-19 at 10 24 19" src="https://user-images.githubusercontent.com/67129314/233089438-84b0fc6d-5d6d-4175-978f-0f413d41ec78.png"> |
> [docs] Adjust the Material Icons page design and formatting

- docs/data/material/components/table/EnhancedTable.js
- docs/data/material/components/table/EnhancedTable.tsx
Revert #33236, the logic is 1. buggy, 2. duplicate the filtering logic, and 3. do the opposite of what's recommended: 
1. By "buggy", I mean, open https://mui.com/material-ui/react-table/#customization and see how the scroll position is wrong.
2. By "duplicated", see the number of times `stableSort()` is written.
3. By "opposite", see https://react.dev/learn/you-might-not-need-an-effect#caching-expensive-calculations.
To make the review of the changes easier, I have done two commits 1. revert 2. a fix for the original issue. But in practice, I doubt that this has any kind of impact on the operation. The memo is fast, even with 10,000 records (but how do you fetch 10,000 records client-side?). I was close to simply proposing a revert.
> [Table] Fix `Sorting & Selecting` tables

- docs/data/material/guides/styled-engine/styled-engine.md
Just fixing a small typo discovered when trying to repro https://github.com/mui/material-ui/issues/36910
Proof that it works: https://codesandbox.io/s/chakra-material-forked-qsbpog?file=/src/App.tsx
Closes #36910
> [docs] Fix Chakra UI theme scoping typo
