docs/.link-check-errors.txt, docs/data/material/guides/minimizing-bundle-size/minimizing-bundle-size.md
Clarify this confusion https://mui-org.slack.com/archives/C041SDSF32L/p1680655322928259
=> [docs] Clarify when bundle size optimization is needed

docs/data/joy/components/alert/AlertInvertedColors.js, docs/data/joy/components/alert/AlertInvertedColors.tsx, docs/data/joy/components/alert/alert.md, docs/data/joy/components/menu/AppsMenu.js, docs/data/joy/components/menu/AppsMenu.tsx, docs/data/joy/components/menu/MenuUsage.js, docs/data/joy/components/menu/menu.md, docs/pages/joy-ui/api/alert.json, docs/pages/joy-ui/api/menu-item.json, docs/pages/joy-ui/api/menu.json, docs/src/modules/components/JoyUsageDemo.tsx, docs/translations/api-docs-joy/alert/alert.json, docs/translations/api-docs-joy/menu-item/menu-item.json, docs/translations/api-docs-joy/menu/menu.json, packages/mui-joy/src/Alert/Alert.tsx, packages/mui-joy/src/Alert/AlertProps.ts, packages/mui-joy/src/ListItemButton/ListItemButton.tsx, packages/mui-joy/src/ListItemDecorator/ListItemDecorator.tsx, packages/mui-joy/src/Menu/Menu.tsx, packages/mui-joy/src/Menu/MenuProps.ts, packages/mui-joy/src/MenuItem/MenuItem.tsx, packages/mui-joy/src/styles/ColorInversion.tsx, packages/mui-joy/src/styles/variantUtils.ts
There are real-world examples of the Menu and Alert that use color inversion.
closes #36876
---
=> [Joy] Add `invertedColors` to Menu and Alert

docs/src/modules/components/AppNavDrawerItem.js
From https://github.com/mui/material-ui/pull/36408#issuecomment-1519063829
I moved to the solution discouraging the use of the string API since it's not used anymore, and could be removed when other MUI projects stop using it
=> [docs] Fix console error introduced by #36408

packages/mui-joy/src/Chip/Chip.tsx
Fixes a bug where the button width style is set to 0 when using the Chip onClick prop in the Firefox browser.
Add a width 100% style to the button to fix the issue.
Fixes https://github.com/mui/material-ui/issues/36877
=> [Joy][Chip] Chip button not showing up in Firefox browser

docs/src/components/productX/XHero.tsx
Preview: https://deploy-preview-37001--material-ui.netlify.app/x/
=> [website] Update main data grid demo on X landing page

packages/mui-material/src/InputBase/InputBase.js, packages/mui-material/src/TextField/TextField.d.ts, packages/mui-material/src/TextField/TextField.js, packages/mui-material/src/TextField/TextField.test.js
closes https://github.com/mui/material-ui/issues/36867
before : https://codesandbox.io/s/zen-meadow-lr2flp?file=/demo.tsx
after : https://codesandbox.io/s/beautiful-panka-24o4h2?file=/demo.tsx
Actual issue lies in `TextField` component not in `Autocomplete`. Right now `onClick` event of `TextField` runs even if `TextField` is disabled. This PR fixes it.
=> [TextField] fix running click event on disabled

docs/pages/base/api/use-form-control-context.json, packages/mui-base/src/FormControl/FormControl.types.ts
The docs of the useFormControlContext's return value stated that some fields are optional:
This (nor default values) doesn't make much sense in a return value, so I made all the values present.
=> [FormControl][base] Do not use optional fields in useFormControlContext's return value

docs/data/material/customization/how-to-customize/how-to-customize.md
This header was changed in #31997, but it doesn't seem to need to be a h3. h2 seems enough and retains the anchor link.
e.g. of a broken anchor link: https://marmelab.com/react-admin/BooleanField.html#sx-css-api 
Noticed in https://github.com/marmelab/react-admin/pull/8857
=> [docs] Fix anchor link in customization

docs/data/joy/pages.ts, docs/data/system/pages.ts, docs/src/modules/brandingTheme.ts, docs/src/modules/components/AppContainer.js, docs/src/modules/components/AppFrame.js, docs/src/modules/components/AppLayoutDocs.js, docs/src/modules/components/AppLayoutDocsWithoutAppFrame.js, docs/src/modules/components/AppTableOfContents.js, docs/src/modules/components/ComponentPageTabs.js, docs/src/modules/components/MarkdownDocsV2.js, docs/src/modules/components/MarkdownElement.js, docs/src/pages.ts
A few low-hanging fruits from the items left in #35938.
=> [docs] Fix small regressions API pages

docs/pages/base/api/tab-panel.json, docs/translations/api-docs-base/tab-panel/tab-panel.json, packages/mui-base/src/TabPanel/TabPanel.spec.tsx, packages/mui-base/src/TabPanel/TabPanel.test.tsx, packages/mui-base/src/TabPanel/TabPanel.tsx, packages/mui-base/src/TabPanel/TabPanel.types.ts
`TabPanel` didn't have dedicated documentation page, so i couldn't update docs like i did here (https://deploy-preview-36770--material-ui.netlify.app/base/react-tabs/#usage-with-typescript)
For Base UI components,  the `component` prop value should be moved to `slots.root`: 
```diff
<TabPanel
/>
```
If using TypeScript, you should add the custom component type as a generic on the `TabPanel` component.
```diff
-<TabPanel
+<TabPanel<typeof CustomComponent>
/>
```
=> [TabPanel] drop component prop

docs/pages/base/api/tabs-list.json, docs/translations/api-docs-base/tabs-list/tabs-list.json, packages/mui-base/src/TabsList/TabsList.spec.tsx, packages/mui-base/src/TabsList/TabsList.test.tsx, packages/mui-base/src/TabsList/TabsList.tsx, packages/mui-base/src/TabsList/TabsList.types.ts
`TabsList` didn't have dedicated documentation page, so i couldn't update docs like i did here (https://deploy-preview-36770--material-ui.netlify.app/base/react-tabs/#usage-with-typescript)
For Base UI components,  the `component` prop value should be moved to `slots.root`: 
```diff
<TabsList
/>
```
If using TypeScript, you should add the custom component type as a generic on the `TabsList` component.
```diff
-<TabsList
+<TabsList<typeof CustomComponent>
/>
```
=> [TabsList] Drop component prop

docs/data/base/components/table-pagination/table-pagination.md, docs/pages/base/api/table-pagination.json, docs/translations/api-docs-base/table-pagination/table-pagination.json, packages/mui-base/src/TablePagination/TablePagination.spec.tsx, packages/mui-base/src/TablePagination/TablePagination.test.tsx, packages/mui-base/src/TablePagination/TablePagination.tsx, packages/mui-base/src/TablePagination/TablePagination.types.ts, packages/mui-base/src/TablePagination/TablePaginationActions.spec.tsx, packages/mui-base/src/TablePagination/TablePaginationActions.tsx, packages/mui-base/src/TablePagination/TablePaginationActions.types.ts
For Base UI components,  the `component` prop value should be moved to `slots.root`: 
```diff
<TablePagination
/>
```
If using TypeScript, you should add the custom component type as a generic on the `TablePagination` component.
```diff
-<TablePagination
+<TablePagination<typeof CustomComponent>
/>
```
=> [TablePagination] Drop component prop

docs/pages/base/api/tab.json, docs/translations/api-docs-base/tab/tab.json, packages/mui-base/src/Tab/Tab.spec.tsx, packages/mui-base/src/Tab/Tab.test.tsx, packages/mui-base/src/Tab/Tab.tsx, packages/mui-base/src/Tab/Tab.types.ts
For Base UI components,  the `component` prop value should be moved to `slots.root`: 
```diff
<Tab
/>
```
If using TypeScript, you should add the custom component type as a generic on the `Tab` component.
```diff
-<Tab
+<Tab<typeof CustomComponent>
/>
```
=> [Tab][base] Drop component prop

docs/data/base/components/badge/badge.md, docs/data/base/components/button/button.md, docs/pages/base/api/badge.json, docs/translations/api-docs-base/badge/badge.json, packages/mui-base/src/Badge/Badge.spec.tsx, packages/mui-base/src/Badge/Badge.test.tsx, packages/mui-base/src/Badge/Badge.tsx
For Base UI components, the `component` prop value should be moved to `slots.root`: 
```diff
<Badge
/>
```
If using TypeScript, you should add the custom component type as a generic on the `Badge` component.
```diff
-<Badge
+<Badge<typeof CustomComponent>
/>
```
=> [Badge][base] Drop `component` prop

docs/data/base/components/snackbar/snackbar.md, docs/pages/base/api/snackbar.json, docs/translations/api-docs-base/snackbar/snackbar.json, packages/mui-base/src/Snackbar/Snackbar.test.tsx, packages/mui-base/src/Snackbar/Snackbar.tsx, packages/mui-base/src/Snackbar/Snackbar.types.ts
For Base UI components, the `component` prop value should be moved to `slots.root`:
```diff
<Snackbar
/>
```
If using TypeScript, you should add the custom component type as a generic on the TabsList component.
```diff
-<Snackbar
+<Snackbar<typeof CustomComponent>
customProp
/>
```
=> [Snackbar][base] Drop component prop

docs/pages/base/api/modal.json, docs/translations/api-docs-base/modal/modal.json, packages/mui-base/src/Modal/Modal.spec.tsx, packages/mui-base/src/Modal/Modal.test.tsx, packages/mui-base/src/Modal/Modal.tsx, packages/mui-base/src/Modal/Modal.types.ts
Part of https://github.com/mui/material-ui/issues/36679
=> [Modal][base] Drop component prop

packages/markdown/loader.js, packages/markdown/parseMarkdown.js, test/e2e-website/material-docs.spec.ts
The API links on the Material UI's documentation that conflicts with Base UI's components name, have the wrong links, for e.g.: https://mui.com/material-ui/react-button/#api (the Button link is pointing to the wrong API).
The problem comes from the fact that initially we were planning to use the Base UI's components inside Material UI, so we thought that we would like to document the Base UI components on the Material UI's pages. However, this is no longer the case, as we decided to use the headless hooks. We can basically drop this assumption now.
The problem arise after removing the `unstyled` suffix from the Base UI's components, so the names of the components conflicted.
Here is a link for verifying the fix: https://deploy-preview-37121--material-ui.netlify.app/material-ui/react-button …
=> [docs] Fix Material UI's API linking to Base UI

packages/mui-material/src/Accordion/Accordion.d.ts, packages/mui-material/src/Accordion/Accordion.spec.tsx, packages/mui-material/src/Paper/Paper.d.ts
closes: https://github.com/mui/material-ui/issues/36940
before: https://codesandbox.io/s/priceless-mclaren-e8mq3s
after: https://codesandbox.io/s/infallible-colden-90x7jx?file=/demo.tsx
=> [Accordion] Add missing `component` type

docs/src/featureToggle.js, docs/src/modules/components/AppTableOfContents.js
- Add a toggle variable to turn off/on the Job ad.
- Set the toggle to "off"
Follow up on https://github.com/mui/material-ui/pull/36074#discussion_r1097632956
https://deploy-preview-36080--material-ui.netlify.app/material-ui/getting-started/overview/
=> [docs] Turn off job banner on docs

docs/data/base/components/select/UnstyledSelectMultiple.js, docs/data/base/components/select/UnstyledSelectMultiple.tsx, docs/src/createEmotionCache.ts
Improved the look of multiple selected options in Base UI's Select demos.
Before: 
After:
This relies on the `:has` CSS selector and won't currently work on Firefox (it'll look like before).
~~Interestingly, I couldn't make it work by writing `&.${optionClasses.selected}:has(+ .${optionClasses.selected})`, as for some reason, Emotion was transforming this into `&:has(+ .MuiSelected)`. I wasn't able to isolate this issue, though.~~
I discussed the issue with @siriwatknp, who proposed a fix in createEmotionCache that I included in the PR.
=> [docs] Improve Multiselect demo styling

docs/src/components/header/HeaderNavBar.tsx, docs/src/components/header/HeaderNavDropdown.tsx, docs/src/modules/components/MuiProductSelector.tsx
Updating the Toolpad alpha labels in the submenus to be consistent with the [new Toolpad landing page stylistic changes](https://github.com/mui/mui-toolpad/pull/1786#pullrequestreview-1402061970).
=> [website] make Toolpad alpha labels consistent

packages/mui-base/src/Button/Button.spec.tsx, packages/mui-base/src/utils/PolymorphicComponent.ts
Fixes the regression introduced in #36677 and restores proper types of callbacks and ref parameters.
Closes #37157
=> [typescript][base] Fix types of components callbacks parameters

test/e2e-website/README.md, test/e2e-website/material-docs.spec.ts
- Remove the unnecessary import `FEATURE_TOGGLE`
- Fix e2e-website README. It should be `test:e2e-website:dev`
Noticed while adding tests in #37175.
=> [test] `e2e-website` related minor fixes

packages/markdown/parseMarkdown.js, test/e2e-website/material-docs.spec.ts
Fixes issue mentioned in comment https://github.com/mui/material-ui/pull/37121#issuecomment-1536173049
=> [docs] Redirect NoSsr, Portal and TextareaAutosize to Base UI API page

.gitignore, .vscode/extensions.json
Added the VSCode [recommended workspace extensions](https://code.visualstudio.com/docs/editor/extension-marketplace#_recommended-extensions). 
The following are included:
- Editorconfig
- ESLint
- Markdownlint
- Prettier
- Pretty TypeScript Errors
=> [core] Add VSCode extensions recommendations

packages/mui-material/src/AppBar/AppBar.d.ts, packages/mui-material/src/AppBar/AppBar.spec.tsx
before: https://codesandbox.io/s/gifted-bash-gsto2d?file=/demo.tsx:0-226
after: https://codesandbox.io/s/amazing-cori-xt0uds
1. go to before sandbox
2. hover on the `event` argument on `onClick` function.
3. notice the type of event is set to `React.MouseEvent<HTMLDivElement, MouseEvent>` where type of `event` should be `React.MouseEvent<HTMLAnchorElement, MouseEvent>` as `component='a'` is set to `AppBar`
=> [AppBar] Fix component type

packages/mui-base/src/Select/Select.test.tsx, packages/mui-base/src/useSelect/useSelect.ts
When the Select's value (controlled or uncontrolled) was set to `null`, the `onChange` event handler was called right after the initial render. This PR fixes this behavior and adds tests for various related cases.
Fixes #36783
=> [Select][base] Do not call onChange after initial render

.eslintrc.js
Improve linting time by checking for cyclic dependencies in production code only.
Results from my local machine:
Before:
```
Rule                                 |  Time (ms) | Relative
:------------------------------------|-----------:|--------:
import/no-cycle                      | 227269.294 |    81.7%
import/extensions                    |  10279.738 |     3.7%
import/no-unresolved                 |   4367.926 |     1.6%
@typescript-eslint/naming-convention |   3440.758 |     1.2%
import/order                         |   2216.073 |     0.8%
import/no-duplicates                 |   1916.750 |     0.7%
import/no-named-as-default           |   1767.365 |     0.6%
import/no-import-module-exports      |   1427.037 |     0.5%
@typescript-eslint/no-redeclare      |   1282.992 |     0.5% …
```
=> [core] Check dependency cycles inside packages directory only

docs/data/material/customization/palette/palette.md, docs/data/material/customization/theming/theming.md
=> [docs] Update theme customization typescript

test/utils/initMatchers.ts
The core repo does not use it, and on X we are using our custom version for some time.
The issue is that the typing of the two is diverging and it causes issues.
I can align the typing and the behavior but I think it's simpler to just drop it from your repo.
=> [core] Remove `toEqualDateTime` chai matcher

docs/pages/base/api/use-autocomplete.json, docs/pages/joy-ui/api/autocomplete.json, docs/pages/material-ui/api/autocomplete.json, packages/mui-base/src/useAutocomplete/useAutocomplete.d.ts, packages/mui-joy/src/Autocomplete/Autocomplete.tsx, packages/mui-material/src/Autocomplete/Autocomplete.js
Closes #36780
Material UI - https://deploy-preview-37230--material-ui.netlify.app/material-ui/api/autocomplete/
Joy UI - https://deploy-preview-37230--material-ui.netlify.app/joy-ui/api/autocomplete/
=> [docs] Show default value for `filterOptions` prop in Autocomplete's API docs

packages/mui-joy/src/Tooltip/Tooltip.test.tsx
part of https://github.com/mui/material-ui/issues/37078
=> [Tooltip][Joy] Turn JS test to TS test 

packages/mui-joy/src/RadioGroup/RadioGroup.test.tsx
=> [RadioGroup][joy] Turn JS test to TS test

packages/mui-material/src/Dialog/Dialog.js
Resolves https://github.com/mui/material-ui/issues/37241
Here's a demo of the fix: https://codesandbox.io/s/https-github-com-mui-material-ui-issues-37241-r5334g
=> [Dialog] fixed broken dialog when using maxWidth="xs" and custom breakpoint unit

packages/mui-base/src/useAutocomplete/useAutocomplete.js, packages/mui-material/src/Autocomplete/Autocomplete.test.js
Fix https://github.com/mui/material-ui/issues/33195
Codesandbox: https://codesandbox.io/s/inputadornments-demo-material-ui-forked-j0gvpo?file=/demo.tsx
=> [autocomplete] Allow tooltip text selection

docs/data/material/getting-started/templates/album/Album.js, docs/data/material/getting-started/templates/album/Album.tsx, docs/data/material/getting-started/templates/blog/Blog.js, docs/data/material/getting-started/templates/blog/Blog.tsx, docs/data/material/getting-started/templates/blog/MainFeaturedPost.js, docs/data/material/getting-started/templates/blog/MainFeaturedPost.tsx, docs/data/material/getting-started/templates/checkout/Checkout.js, docs/data/material/getting-started/templates/checkout/Checkout.tsx, docs/data/material/getting-started/templates/dashboard/Dashboard.js, docs/data/material/getting-started/templates/dashboard/Dashboard.tsx, docs/data/material/getting-started/templates/dashboard/Dashboard.tsx.preview, docs/data/material/getting-started/templates/pricing/Pricing.js, docs/data/material/getting-started/templates/pricing/Pricing.tsx, docs/data/material/getting-started/templates/pricing/Pricing.tsx.preview, docs/data/material/getting-started/templates/sign-in-side/SignInSide.js, docs/data/material/getting-started/templates/sign-in-side/SignInSide.tsx, docs/data/material/getting-started/templates/sign-in/SignIn.js, docs/data/material/getting-started/templates/sign-in/SignIn.tsx, docs/data/material/getting-started/templates/sign-up/SignUp.js, docs/data/material/getting-started/templates/sign-up/SignUp.tsx, docs/data/material/getting-started/templates/sticky-footer/StickyFooter.js, docs/data/material/getting-started/templates/sticky-footer/StickyFooter.tsx
🙈 
1. Open https://mui.com/material-ui/getting-started/templates/sign-in-side/ broken image like in #36991.
2. Open https://mui.com/material-ui/getting-started/templates/album/ broken cards
3. Open https://mui.com/material-ui/getting-started/templates/pricing/ wrong theme
But these templates still have room to receive a lot more love.
=> [docs] Fix Material Design templates

packages/mui-base/src/useAutocomplete/useAutocomplete.js, packages/mui-joy/src/Autocomplete/Autocomplete.test.tsx
closes : https://github.com/mui/material-ui/issues/37127
working video: 
https://github.com/mui/material-ui/assets/60743144/6bb2cdfb-dd62-4341-9fc2-2f0f2e3149be
preview: https://deploy-preview-37217--material-ui.netlify.app/joy-ui/getting-started/templates/profile-dashboard/
=> [Joy] Autocomplete scroll

packages/mui-utils/src/useId.ts
Fixes #37182. Based on [this commit from floating-ui](https://github.com/hawkstein/floating-ui/commit/961ec59dc03af9ffc2ea14b9f8b0108d3db609f1). I've confirmed that this will resolve the issue by manually tweaking the `useId` code in a local install of `@mui/utils` and running it through the same bundle process that's stripping the string concatenation.
Note that `+""` has been stripped from `React3["useId"+""]` on line 15. This is what's causing the downstream build issue.
```javascript
// ../../common/temp/node_modules/.pnpm/@mui+utils@5.11.13_react@17.0.2/node_modules/@mui/utils/esm/useId.js
import * as React3 from "react";
var globalId = 0;
function useGlobalId(idOverride) {
const [defaultId, setDefaultId] = React3.useState(idOverride);
const id = idOverride || defaultId; …
```
=> [Utils] fix downstream bundlers remove React 17 useId compatibility

docs/data/material/guides/localization/localization.md, packages/mui-material/src/locale/index.ts
=> [l10n] Add Central Myanmar (my-MY), Malay (ms-MS), Nepali (ne-NP), Tagalog (tl-TL) locales

docs/data/joy/guides/using-joy-ui-and-material-ui/using-joy-ui-and-material-ui.md
`MATERIAL_THEME_ID` is missing here, and `colors` is not used.
=> [docs][joy] Update Joy + Material guide

docs/src/modules/components/ApiPage.js, docs/src/modules/components/ComponentsApiContent.js
Follow-up of https://github.com/mui/material-ui/pull/34990
- [joy](https://deploy-preview-36870--material-ui.netlify.app/joy-ui/api/alert/#slots)
- [base](https://deploy-preview-36870--material-ui.netlify.app/base/react-badge/components-api/#badge-unstyled-slots)
=> [docs] Update link to overriding component structure guide

package.json, packages/mui-material/package.json, packages/mui-material/scripts/rollup.config.js, yarn.lock
This reverts commit ea7201aa8f2cc6295d9c51b866b595757ad992c4.
It causes an error when running `yarn release:build` (Error: EPIPE).
=> Revert "Bump rollup to ^3.21.8 (#35619)"

examples/material-express-ssr/.babelrc, examples/material-express-ssr/package.json
Similar to #36795. It is included by default in `@bable/preset-env`.
=> [examples] Remove `@babel/plugin-proposal-class-properties` from Material-Express-SSR example

docs/next.config.js, docs/nextConfigDocsInfra.js
Moved the `esmExternals` config key to the shared Next.js config, so other applications can use it.
The original reason behind adding the key is #37264
=> [core] Move esmExternals to the shared next config

packages/mui-base/src/useList/useListItem.ts
fixes: https://github.com/mui/material-ui/issues/36979
This PR adds additional check inside callback fn for a root element of a list item. It check if `event.target` is instance of `HTMLAnchorElement`. If it is from an `a` tag, then the default event shouldn't be prevented.
codesandboxes:
- [old](https://codesandbox.io/s/still-platform-rh966j?file=/demo.tsx)
- [new](https://codesandbox.io/s/affectionate-nightingale-ui752q?file=/demo.tsx)
=> [Menu][base] MenuItem as a link does not work 

docs/data/joy/guides/using-icon-libraries/using-icon-libraries.md, docs/data/material/customization/theming/theming.md, docs/src/modules/components/ApiPage.js, docs/src/modules/components/ComponentsApiContent.js, packages/markdown/parseMarkdown.js, packages/markdown/parseMarkdown.test.js
Quick fixes. I have found them looking with Jan into how we can improve Algolia's experience on the docs, especially around the no search results. Its crawler reports issues (301, 404, etc.)
https://crawler.algolia.com/admin/crawlers/739c29c8-99ea-4945-bd27-17a1df391902/monitoring/summary
---
Docs-infra change: I have added a new logic to break the CI if the link is wrong, this shouldn't go to production.
=> [docs-infra] Throw on incorrect internal links

docs/data/material/migration/migration-v4/v5-component-changes.md
- Added a description on Divider migration documentation of the change in margin of the `variant` "middle" in the "vertical" `orientation` of this  #component;
- Added an example of how to override the change to avoid issues;
=> [docs] Divider middle prop migration

packages/api-docs-builder/utils/getPropsFromComponentSymbol.ts
Related to https://github.com/mui/material-ui/pull/37190
Updating the condition was forgotten when generating API docs on MUI-X.
Blocks https://github.com/mui/mui-x/pull/8900
=> [core] Include scoped JSX namespace when resolving props

packages/mui-joy/src/Button/Button.tsx, packages/mui-joy/src/IconButton/IconButton.tsx
Fixes button retaining hover effect on mobile devices.
closes https://github.com/mui/material-ui/issues/36583
---
This code was written and reviewed by GitStart Community. Growing great engineers, one PR at a time.
=> [base][joy] prevent persisting hover state styles onclick on mobile

packages/mui-joy/src/Tooltip/Tooltip.tsx
fixes: https://github.com/mui/material-ui/issues/37132
Took me way too long, hopefully this is it.
The culprit is `pointer-events: none;`, so I delete the 2 locations where this is set. In Material UI's implementation, the tooltip is 2 layers of `div`, so adding `pointer-events: none;` to the child `div` is okay. `mouseenter` event will still be called by the parent `div` when mouse comes to the tooltip. In Joy UI, however, the tooltip is only a div. Adding `pointer-events: none;` here causes `mouseenter` event to not be called when the mouse enter the tooltip.
Example:
- [old](https://mui.com/joy-ui/react-tooltip/#variants:~:text=/%3E%3B%0A%7D-,Variants,-The%20tooltip%20component)
- [new](https://codesandbox.io/s/mui-material-ui-forked-zmmgvb)
=> [Tooltip][Joy] Interactive doesn't work

packages/mui-joy/src/Select/Select.tsx
Fixes #37277
Please advise if this is a good way to deal with this issue.
I can hide the scrollbars by just putting `overflow: "hidden"` but in order to show the ellipsis I had to first put the content inside a span tag and add `width: 0` to it.
This is needed as the button is a flex container due to which I can't directly add `text-overflow: "ellipsis"` to it.
[https://css-tricks.com/flexbox-truncated-text/](https://css-tricks.com/flexbox-truncated-text/)
Visually everything seems to be working fine.
=> [Select] [joy] handle long text content

renovate.json
I noticed renovate opening dependency updates PR for the `examples` packages to a major version. We eventually close them because we don't want the legacy example `material-next-ts-v4-v5-migration`, which uses `@mui/styles` for styling to use the latest versions of Next.js and React (See [multiple closed PRs for examples (major)](https://github.com/mui/material-ui/pulls?page=1&q=is%3Apr+Bump+examples+%28major%29+is%3Aclosed)). All examples packages are pinned to the `latest` versions except `material-next-ts-v4-v5-migration`.
I propose to altogether remove the config from renovate. Those who are not aware of it could unknowingly merge them.
=> [core] Do not let Renovate handle `examples` packages updates

docs/src/modules/components/AppFrame.js, docs/src/modules/components/AppSearch.js
A regression from #36160. It's a firework when the page is loading, this change gets us a bit closer to solving it.
https://github.com/mui/material-ui/assets/3165635/8bfa2878-8edb-4c39-aa1b-48bfd14ce2c5
=> [docs] Fix search bar layout shift

docs/data/base/components/tabs/tabs.md, docs/data/base/getting-started/usage/usage.md
preview: 
- https://deploy-preview-37462--material-ui.netlify.app/base/react-tabs/#third-party-routing-library
- https://deploy-preview-37462--material-ui.netlify.app/base/getting-started/usage/
=> [docs][Base] Remove usage of `component` prop in docs

packages/mui-base/src/Input/Input.test.tsx, packages/mui-base/src/Input/Input.tsx
closes: https://github.com/mui/material-ui/issues/37134
before: https://codesandbox.io/s/broken-cookies-k6px3x?file=/demo.tsx:1459-1539
after: https://codesandbox.io/s/elated-bessie-7k0dkm
=> [Input][base] Fix calling slotProps event handlers

docs/pages/material-ui/api/autocomplete.json, docs/translations/api-docs/autocomplete/autocomplete.json, packages/mui-material/src/Autocomplete/Autocomplete.spec.tsx, packages/mui-material/src/Autocomplete/autocompleteClasses.ts
closes:  https://github.com/mui/material-ui/issues/37410
=> [Autocomplete][Material] Add missing `focusVisible` class in AutocompleteClasses

docs/data/material/components/popover/VirtualElementPopover.js, docs/data/material/components/popover/VirtualElementPopover.tsx, docs/data/material/components/popover/popover.md, docs/translations/api-docs/popover/popover.json, packages/mui-material/src/Popover/Popover.d.ts, packages/mui-material/src/Popover/Popover.js, packages/mui-material/src/Popover/Popover.test.js
Add documentation, demo, and tests for using a virtual element (VE) as an anchor element for the `Popover` component.
- This doesn't require changes in the component, only to update the type and proptype for the `anchorEl` prop. Fixed previous definition: when providing a function for the anchor, the [function doesn't receive any arguments](https://github.com/mui/material-ui/blob/master/packages/mui-material/src/Popover/Popover.js#L62).
- The virtual element is different from the one used for [`Popper`](https://mui.com/material-ui/react-popper/#virtual-element) and [`Tooltip`](https://mui.com/material-ui/react-tooltip/#virtual-element), as the `Popover` [expects the VE's `nodeType` property to be `1`](https://github.com/mui/material-ui/blob/master/packages/mui-material/src/Popover/Popover. …
=> [Material][Popover] Add support for virtual element as anchorEl

docs/src/layouts/AppHeader.tsx, docs/src/modules/components/AppSettingsDrawer.js, docs/src/modules/components/ThemeContext.js
This avoids the page crashing when accessed in Firefox with cookies disabled
Fixes #37514
=> [docs] Fix crash access to localStorage in Firefox 

docs/data/joy/components/typography/TypographyUsage.js, docs/data/joy/components/typography/typography.md
As I was building a few templates, I was watching out for things that could improve DX. Typography is missing a playground (usage component), so I built one out.
=> [docs][joy] Add typography introduction demo component

docs/data/joy/components/text-field/text-field.md
Replaced JoyInput with Input in the documentation file. The previous [documentation](https://mui.com/joy-ui/react-text-field/#manual) referenced JoyInput instead of Input as the component to use. This led to confusion when trying to implement the example in the projects.
=> [docs][Joy] Replace JoyInput with Input component in JoyUI Text Field documentation

docs/src/modules/components/ComponentPageTabs.js
Go to one of the [Base UI component](https://mui.com/base/react-slider) and then search for `Slider`:
The result has 3 links:
1. link to hook-api
2. link to component-api
3. link to demo
I think the last one is enough. It looks better because it groups the component API and hook API altogether.
According to our [crawler](https://crawler.algolia.com/admin/crawlers/739c29c8-99ea-4945-bd27-17a1df391902/configuration/edit), we can skip the DOM from being indexed by adding a className `skip-algolia-crawler`.
---
=> [docs] Skip components and hooks due to duplicate index

docs/data/system/experimental-api/css-theme-variables/CreateCssVarsProvider.js, docs/data/system/experimental-api/css-theme-variables/CreateCssVarsProvider.tsx, docs/data/system/experimental-api/css-theme-variables/CreateCssVarsProvider.tsx.preview, docs/data/system/experimental-api/css-theme-variables/css-theme-variables.md, docs/data/system/pages.ts, docs/pages/system/experimental-api/css-theme-variables.js, docs/translations/translations.json, packages/mui-joy/src/styles/extendTheme.ts, packages/mui-system/src/cssVars/createCssVarsProvider.js
Added a minimal code example to showcase how `createCssVarsProvider` is used.
=> [docs] Add usage of createCssVarsProvider

docs/src/modules/components/ExampleCollection.js
Following up on @oliviertassinari's comments at https://github.com/mui/material-ui/pull/37007.
=> [docs] Review fixes to the Material UI's "Example projects" page

docs/src/modules/components/Demo.js, docs/src/modules/components/JoyUsageDemo.tsx
Just fine-tuning the design and making it a bit more consistent. I removed the unnecessary "False/True" label from the switch (I guess the component conveys this idea clearly already) and also refined the colors from the Playground panel and the container's border. The more true black-tinted dark mode from Joy still doesn't riff perfectly with the docs blue-tinted dark mode but that will soon change and make this component better (🙌)(the Selects, Inputs, & Chips are clashing a bit).  
| <img width="837" alt="Screen Shot 2023-06-13 at 16 29 56" src="https://github.com/mui/material-ui/assets/67129314/e4c72854-7350-4be1-ba08-441f9d284b0e"> | <img width="837" alt="Screen Shot 2023-06-13 at 16 29 52" …
=> [docs][joy] Add design and consistency tweaks to the Playground

docs/data/system/styled/styled.md
Related issues:
- https://github.com/mui/material-ui/issues/37397
- https://github.com/mui/material-ui/issues/33412
The `styles` argument is not listed in the `styled` function arguments list. Adding it will help with its usage.
**A few questions**
- styled` can receive multiple arguments, all with the same type, should we document it? I think it would create more confusion, so my answer is no, but if you disagree please let me know
- I used `({ ...props, theme }) => object` as the function signature because that's the most concise way I could come up with to explain it, but I would appreciate alternatives if you think of some
- Is there anything else that we should add to the explanation?
=> [docs] Add styles to styled argument list

docs/data/joy/components/button-group/GroupOrientation.js, docs/data/joy/components/button-group/GroupOrientation.tsx, docs/data/joy/components/button-group/SpacingButtonGroup.js, docs/data/joy/components/button-group/SpacingButtonGroup.tsx, docs/data/joy/components/button-group/SpacingButtonGroup.tsx.preview, docs/pages/joy-ui/api/button-group.json, docs/translations/api-docs-joy/button-group/button-group.json, packages/mui-joy/src/ButtonGroup/ButtonGroup.tsx, packages/mui-joy/src/ButtonGroup/buttonGroupClasses.ts
closes #37574
**Before**: https://mui.com/joy-ui/react-button-group/#spacing
**After**: https://deploy-preview-37577--material-ui.netlify.app/joy-ui/react-button-group/#spacing
=> [ButtonGroup][joy] Missing border when spacing is more than zero

packages/mui-material/src/Tooltip/Tooltip.js, packages/mui-material/src/Tooltip/Tooltip.test.js
Closes #18119
When Tooltip receives a string as a child, wrap it in a `span` element to avoid a server error. The element will render and a warning will be thrown so the developer knows what to do.
=> [Tooltip][material] Improve warning when Tooltip receives string child

.github/workflows/ci.yml
The developer scripts currently use Node v14 on the test-dev CI. However, now that the pull request https://github.com/mui/material-ui/pull/37173 is completed, we should switch to using Node v18 for consistency. It runs the `yarn install` step.
This should unblock dependencies updates such as https://github.com/mui/material-ui/pull/37349 and others as they require Node `>=16`.
=> [core] Update to Node.js v18 for `test-dev` CI

docs/data/base/components/snackbar/TransitionComponentSnackbar.js, docs/data/base/components/snackbar/TransitionComponentSnackbar.tsx, docs/data/base/components/snackbar/UnstyledSnackbarIntroduction.js, docs/data/base/components/snackbar/UnstyledSnackbarIntroduction.tsx, docs/data/base/components/snackbar/snackbar.md
While browsing through the documentation yesterday, I realized we were lacking an intro demo for the Snackbar, which feels a bit inconsistent with all the other components. Usually, for these intro demos, it's nice to have a more fleshed-out example rather than a simpler one, to which point I again realized that the "Transitions" demo was really polished.
So, what I did was add an intro demo with the example that was being used in the Transitions section and then I simplified that to use the format all other demos were using just so we don't have two repeating polished examples.
Also took the opportunity to refine a bit the trigger button here and will eventually, in another PR, make sure all components that rely on a trigger button to be shown (menu, popper, modal, etc.) have consistent …
=> [docs][base] Add a Snackbar introduction demo

docs/data/base/getting-started/quickstart/quickstart.md, docs/data/joy/guides/using-icon-libraries/using-icon-libraries.md, docs/data/material/components/popover/popover.md, docs/data/material/getting-started/faq/faq.md, docs/data/material/guides/routing/routing.md
https://mui.com/base-ui/getting-started/quickstart/#styling-with-tailwind-css
=> [docs] Inline the Base UI demo

docs/pages/base-ui/api/select.json, docs/pages/base-ui/api/use-select.json, docs/translations/api-docs-base/select/select.json, docs/translations/api-docs/use-select/use-select.json, packages/mui-base/src/Select/Select.test.tsx, packages/mui-base/src/Select/Select.tsx, packages/mui-base/src/Select/Select.types.ts, packages/mui-base/src/useSelect/useSelect.ts, packages/mui-base/src/useSelect/useSelect.types.ts, packages/mui-base/src/utils/useControllableReducer.ts
Enables Select's Options to use values that are not referentially equal with the Select's `value` or `defaultValue`.
Developers can provide the `areOptionsEqual` prop, where they specify which options should be considered the same. This has some performance implications, so additional logic is added to use the old faster method when the default reference equality is used.
Preview: https://codesandbox.io/s/optimistic-roman-q2zwgn?file=/demo.tsx
Closes #37597
=> [Select][base] Expose the `areOptionsEqual` prop

docs/src/modules/components/AppSearch.js
Add `analyticsTags` to enable filtering Algolia analytics by product. One of #16502.
=> [docs-infra] Add analyticsTags to Algolia

docs/src/modules/components/Demo.js
Fix visual bug from #37319, it's most noticeable when using `"bg": true`
https://deploy-preview-37319--material-ui.netlify.app/material-ui/react-grid/
After 
https://deploy-preview-37658--material-ui.netlify.app/material-ui/react-grid/
It's hard to really appreciate the difference from the above screenshots seen on a desktop. It's more noticeable opening the after/before links on a mobile phone.
=> [docs-infra] Fix demos border radius

docs/data/material/components/snackbars/DirectionSnackbar.js, docs/data/material/components/snackbars/DirectionSnackbar.tsx, docs/data/material/components/snackbars/PositionedSnackbar.js, docs/data/material/components/snackbars/PositionedSnackbar.tsx, docs/data/material/components/snackbars/PositionedSnackbar.tsx.preview
Fix #37389, I also worked one removing components in the demo to make it easier to process.
https://deploy-preview-37657--material-ui.netlify.app/material-ui/react-snackbar/#positioned-snackbars
https://deploy-preview-37657--material-ui.netlify.app/material-ui/react-snackbar/#control-slide-direction
=> [docs] Fix scrollbar on snackbar page

.github/ISSUE_TEMPLATE/5.priority-support.yml, .github/workflows/priority-support-validation-prompt.yml
For context -> https://github.com/mui/mui-x/pull/8928
Part of https://www.notion.so/mui-org/X-General-meeting-2023-04-21-6728feb266d64b0f83e608767c05c8e2
I've already created the missing labels: `support: unknown` and `support: priority`
=> [core] Add priority support issue template

docs/data/base/components/input/InputAdornments.js, docs/data/base/components/input/InputAdornments.tsx
The Customization/Adornments demo is causing horizontal scrolling on mobile devices due to its width.
| ![Current](https://github.com/mui/material-ui/assets/37222944/5ce4ce11-15d4-4542-812f-5202c40fede6) | ![new](https://github.com/mui/material-ui/assets/37222944/62bbece4-b584-4fb2-b99f-7819c579fd4b) |
=> [docs][base] Fix horizontal scrolling on the mobile input page

docs/src/modules/components/DemoToolbar.js
Tiny little polish on the toggle buttons' font size + spacing (centering the text within the chip) and the icon buttons' border-radius (we're currently not using a fully rounded hover state in many places within the branding theme, so just to maintain consistency here). Here's the final product:
=> [docs-infra] Polish demo toolbar button designs

docs/src/modules/components/AppLayoutDocs.js, docs/src/modules/components/AppLayoutDocsWithoutAppFrame.js, docs/src/modules/components/EditPage.js, docs/src/modules/components/MarkdownDocsV2.js, packages/markdown/loader.js, packages/markdown/parseMarkdown.js, packages/markdown/parseMarkdown.test.js
Fix the edit page button in https://mui.com/toolpad/examples/qr-generator/, reported in https://app.ahrefs.com/site-audit/3833384/52/data-explorer?columns=pageRating%2Curl%2Ctraffic%2ChttpCode%2CcontentType%2Cdepth%2CincomingAllLinks&filterId=9b88587038fc9bb2e08e0ff143d5f328&issueId=c64d89a6-d0f4-11e7-8ed1-001e67ed4656&sorting=-pageRating
The issue is that the markdown page wasn't inside the /docs folder: https://github.com/mui/mui-toolpad/blob/6937af716d3caa7dfbfa5b1eb737bea67d1ffcf4/docs/pages/toolpad/examples/qr-generator.js#L7.
=> [docs-infra] Support rendering markdown outside of docs

docs/src/modules/components/AdCarbon.js
Fix https://www.notion.so/mui-org/Trip-report-React-Summit-2023-18a3abdb83af4284b2d12f4deed18787?pvs=4#4554193ff13e46878e7f8b3e55db5d12, it was reported by a developer at React Summit, and something I experience every now and then too. Typically, it would look like this:
You can be reproduced easily by opening https://mui.com/material-ui/getting-started/overview/ and running `window._carbonads.init()`. In real life, this happens because the script runs asynchronously, so if you have a slow connection, and quickly switch to a different page, you will see it.
=> [docs–infra] Prevent displaying multiple ads

docs/src/modules/components/DemoEditor.tsx
Through browsing the documentation, found this little opportunity for refinement on the "Press <kbd>Enter</kbd> to start editing" callout. Small padding & color adjustments there.
| <img width="754" alt="Screen Shot 2023-06-22 at 18 49 45" src="https://github.com/mui/material-ui/assets/67129314/108b1c2e-1d05-491b-b05a-797c6a29720c"> | <img width="754" alt="Screen Shot 2023-06-22 at 18 50 20" src="https://github.com/mui/material-ui/assets/67129314/0da68a48-9297-4cef-9f31-5a3e84bf0cba"> |
=> [docs-infra] Tweak editable code blocks callout design

docs/src/modules/components/MarkdownElement.js
Just a tiny quality-of-life improvement to these buttons from a design standpoint. Mostly in dark mode, really. Made the comment icon visually centered, which was driving me a bit nuts 😅 
| <img width="754" alt="Screen Shot 2023-06-27 at 01 44 20" src="https://github.com/mui/material-ui/assets/67129314/28b9a775-c992-4bce-922d-3b9123b9f88e"> | <img width="754" alt="Screen Shot 2023-06-27 at 01 44 29" src="https://github.com/mui/material-ui/assets/67129314/0876f6e3-c0b9-4ff6-838c-83f99c81aef6"> |
| <img width="754" alt="Screen Shot 2023-06-27 at 01 44 06" src="https://github.com/mui/material-ui/assets/67129314/450f672b-9ce1-46e8-8c0f-fb6b660ed3f4"> | <img width="754" alt="Screen Shot 2023-06-27 at 01 44 35" …
=> [docs-infra] Add design polish to the comment and anchor buttons

packages/mui-base/src/TextareaAutosize/TextareaAutosize.test.tsx, packages/mui-base/src/TextareaAutosize/TextareaAutosize.tsx
if the textarea style contain paddingRight and value has multi line, the shadow textarea can't follow the textarea corrently. so we can't overwrite the paddingLeft and paddingRight
=> [TextareaAutosize] Fix wrong height measurement

examples/material-vite/README.md
When I downloaded by example, I got an error and I found out that the wrong address was used.
=> [docs] Fix incorrect package URL in README of example material-vite

docs/pages/experiments/docs/DemoInDocs.js, docs/pages/experiments/docs/DemoInDocs.tsx.preview, docs/pages/experiments/docs/demos.js, docs/pages/experiments/docs/demos.md, docs/src/modules/components/Demo.js, docs/src/modules/components/DemoToolbar.js
I noticed small bugs with the demo, so I created a playground to debug and fixed a few instances.
Preview: https://deploy-preview-37762--material-ui.netlify.app/experiments/docs/demos/
=> [docs-infra] Improve demos toolbar

docs/data/material/components/dividers/DividerText.js, docs/data/material/components/dividers/DividerText.tsx, docs/data/material/components/links/Links.js, docs/data/material/components/links/Links.tsx, docs/data/material/components/links/UnderlineLink.js, docs/data/material/components/links/UnderlineLink.tsx, packages/mui-system/src/Stack/Stack.test.js, packages/mui-system/src/Stack/createStack.tsx
Fix #34965.
And looking at the CSS used by the `<Stack>` component, it looks like the issue is the way the children that the margin is applied to are selected: `& > :not(style) + :not(style)`. This excludes any children that have a `<style>` element in front of them.
By swapping the `+`  (adjacent sibling) combinator for the `~` (general sibling) combinator, this issue should be fixed without affecting anything else.
=> [Stack] Fix spacing when there are <style> children

docs/data/base/components/tabs/UnstyledTabsRouting.js, docs/data/base/components/tabs/UnstyledTabsRouting.tsx, docs/data/base/components/tabs/UnstyledTabsRouting.tsx.preview, docs/data/base/components/tabs/tabs.md, packages/mui-base/src/Button/Button.types.ts
The Routing section in the Base UI Tabs docs pointed to Material UI's docs. The pattern of integrating a router with Tabs is slightly different in Base UI, though (`component` is replaced with `slots.root`). This PR updates the docs in this area.
=> [docs][tabs] Document how to use routing with Tabs in Base UI

packages/mui-material/src/OutlinedInput/OutlinedInput.js
Relevant lines in `ownerState`:
```ts
color: fcs.color || 'primary',
disabled: fcs.disabled,
error: fcs.error,
focused: fcs.focused,
hiddenLabel: fcs.hiddenLabel,
size: fcs.size,
```
Those properties will always be undefined on `fcs` unless they are listed in `states`.
=> [OutlinedInput] Fix form control properties in `ownerState`

docs/pages/experiments/docs/blog.md, docs/src/modules/components/AppTableOfContents.js
This is mostly noticeable on Windows, the truncated scrollbar feels confusing.
It feels like the scroll isn't at the top, so there is more things to scroll up to that his hidden, but once you try to scroll up, you realize that no, you are already at the top 🙈
**Before**:
https://mui.com/joy-ui/react-checkbox/
**After**:
https://deploy-preview-37770--material-ui.netlify.app/joy-ui/react-checkbox/
=> [docs-infra] Fix truncated TOCs scrollbar

docs/data/joy/components/menu/MenuUsage.js
Right now whenever user wants to test different variants of props for `Menu` they have open menu everytime and remember old version and current version to compare. I belive this process has lot of friction, so i kept `Menu` open all the time, so that user need not to open `Menu` everytime they want to try different variants of props.
before: 
https://github.com/mui/material-ui/assets/60743144/621744b0-9996-4073-aac1-02ffc6452958
after:
https://github.com/mui/material-ui/assets/60743144/6df02666-d666-428e-be85-683fd07f236c
=> [Menu][Joy] Improve UX of `Menu` usage demo

docs/src/modules/sandbox/CodeSandbox.ts, docs/src/modules/sandbox/CreateReactApp.ts, docs/src/modules/sandbox/StackBlitz.ts
Regression from #37729
When open a CodeSandbox from any Joy UI component, the `index.tsx` uses `@mui/material`. Turns out it could not pick up the correct product identifier because the name of the variable changed in #37729.
**Before**: open the code sandbox from https://deploy-preview-37729--material-ui.netlify.app/joy-ui/react-button/
https://github.com/mui/material-ui/assets/18292247/e26c3c3a-6014-4b00-98bb-9d350dea2292
**After**: try the deploy preview in this PR
=> [docs] rename product to productId

docs/data/joy/components/table/TableUsage.js
This adds `undefined` as an option for the `stripe` property so that it can be disabled without resetting all customizations.
=> [Docs][Joy][Table] Add `undefined` as an option to `stripe`

packages/markdown/parseMarkdown.js
The `productId` for pickers is used as `x-date-pickers` everywhere else.
It makes sense to align it here as well in order to avoid having discrepancy, between, which `productId` to add to the `md` file when. 🤷
=> [docs] Fix pickers product name

packages/markdown/package.json, packages/markdown/parseMarkdown.js, packages/markdown/parseMarkdown.test.js, packages/markdown/textToHash.test.js, yarn.lock
For a reason I ignore, it was parsing the code already parsed 🫠
Just updated `marked` to v5
=> [docs-infra] Fix code parser

docs/data/joy/components/alert/AlertUsage.js, docs/data/joy/components/avatar/AvatarUsage.js, docs/data/joy/components/badge/BadgeUsage.js, docs/data/joy/components/button-group/ButtonGroupUsage.js, docs/data/joy/components/button/ButtonUsage.js, docs/data/joy/components/checkbox/CheckboxUsage.js, docs/data/joy/components/chip/ChipUsage.js, docs/data/joy/components/circular-progress/CircularProgressUsage.js, docs/data/joy/components/input/InputUsage.js, docs/data/joy/components/linear-progress/LinearProgressUsage.js, docs/data/joy/components/link/LinkUsage.js, docs/data/joy/components/list/ListUsage.js, docs/data/joy/components/menu/MenuUsage.js, docs/data/joy/components/modal/ModalUsage.js, docs/data/joy/components/radio-button/RadioUsage.js, docs/data/joy/components/select/SelectUsage.js, docs/data/joy/components/sheet/SheetUsage.js, docs/data/joy/components/slider/SliderUsage.js, docs/data/joy/components/switch/SwitchUsage.js, docs/data/joy/components/table/TableUsage.js, docs/data/joy/components/tabs/TabsUsage.js, docs/data/joy/components/textarea/TextareaUsage.js, docs/data/joy/components/tooltip/TooltipUsage.js, docs/data/joy/components/typography/TypographyUsage.js
Following recent contributor feedback, I'm changing the variant selector on Joy UI's playground from a Select component to a Chip (radio button under the hood). If you're interacting with it a lot, it's one less click and a bit more convenient experience! 😊
=> [docs-infra][joy] Change Joy UI's playground variant selector 

docs/data/material/guides/interoperability/interoperability.md
Closes https://github.com/mui/material-ui/issues/36390
While implementing interoperability with Tailwind I was having issues with components inside my Dialog component. Turns out the guide is missing some Portal elements according to [this comment](https://github.com/mui/material-ui/issues/36390#issuecomment-1461312169). This PR adds the missing elements to the documentation so others don't waste time looking at this issue and wondering why it's not working.
=> [docs] Add missing Portal elements to Tailwind CSS interoperability guide

docs/data/joy/components/link/LinkUsage.js
This sets the default variant in the `Link` playground to `plain` and the default color to `primary` to keep `variant="null"` from showing and to make sure the current style is properly reflected in the playground options.
| ------ | ----- |
| <img width="624" alt="image" src="https://github.com/mui/material-ui/assets/1693592/710e7390-b2c2-4e6c-a460-1e3ff44c1152"> | <img width="619" alt="image" src="https://github.com/mui/material-ui/assets/1693592/5e989784-ffe9-41d6-ba9b-606bdb9d65dc"> |
=> [Docs][Joy][Link] Set `variant` and `color` defaults for the playground

docs/data/base/components/autocomplete/autocomplete.md, docs/data/base/components/form-control/form-control.md, docs/data/base/components/select/select.md, docs/data/joy/components/autocomplete/autocomplete.md, docs/data/joy/components/switch/switch.md, docs/data/material/components/accordion/accordion.md, docs/data/material/components/autocomplete/autocomplete.md, docs/data/material/components/selects/selects.md, docs/data/material/components/text-fields/text-fields.md, docs/data/material/components/tree-view/tree-view.md, docs/data/material/guides/api/api.md
Users consistently express confusion about our usage of the terms "controlled" vs "uncontrolled"—many developers seem to be unaware of this React concept.
This has been resolved in the X docs by adding a callout everywhere it comes up to direct readers to the official React documentation on the topic. This PR does the same for the Core docs.
I think I caught all instances where the concept is mentioned. (I imagine the community will tell us soon enough if I missed any!)
=> [docs] Add callouts about controlled vs uncontrolled components in Core docs

packages/markdown/parseMarkdown.js, packages/markdown/parseMarkdown.test.js
Removes `<code>` tags in ToC that were introduced in https://github.com/mui/material-ui/pull/37731#discussion_r1247609607
Preview: https://deploy-preview-37834--material-ui.netlify.app/material-ui/experimental-api/css-theme-variables/usage/
This was raised in https://mui-org.slack.com/archives/C042VP80PT5/p1688497370976729 by @samuelsycamore
=> [docs-infra] Remove code tags in ToC

docs/src/components/banner/TableOfContentsBanner.tsx, docs/src/modules/components/AppTableOfContents.js
Final polish on #34795
Before:
1. line wrap when loading and depending on the page
https://github.com/mui/material-ui/assets/3165635/96d39e10-b313-471e-8c4a-608539440235
2. Cut layout on mobile
=> [docs] Polish ukraine banner

packages/mui-utils/src/useEventCallback/useEventCallback.spec.ts, packages/mui-utils/src/useEventCallback/useEventCallback.ts
In MUI X, we often type `React.useCallback` like this:
```tsx
const callback = React.useCallback<(param1: number) => number>((param1) => param, []);
// Example: https://github.com/mui/mui-x/blob/b3939c9f83296e2958daf091f4788524616775c1/packages/grid/x-data-grid-pro/src/hooks/features/columnReorder/useGridColumnReorder.tsx#L86
```
`useEventCallback` doesn't support the same signature, so when we replace `React.useCallback` with `useEventCallback` we need to change the typing - here is an example: https://github.com/mui/mui-x/pull/9394#discussion_r1252296866
This PR adds a function overload to `useEventCallback` that is compatible with `React.useCallback`, so that it's easier to switch between `React.useCallback` and `useEventCallback`:
```diff
-const handleDragEnter = React.useCallback< …
```
=> [utils] Add function overload for `useEventCallback`

docs/src/modules/components/DemoToolbar.js, docs/src/modules/sandbox/CodeSandbox.test.js, docs/src/modules/sandbox/CodeSandbox.ts, docs/src/modules/sandbox/CreateReactApp.ts, docs/src/modules/sandbox/Dependencies.ts, docs/src/modules/sandbox/StackBlitz.test.js, docs/src/modules/sandbox/StackBlitz.ts, docs/src/modules/sandbox/types.ts, packages/markdown/parseMarkdown.js
When you export any of the demos with TypeScript to CodeSandbox, StackBlitz, you will get:
which breaks `yarn build`.
I have found thing working on https://www.notion.so/mui-org/Monthly-meeting-2023-07-04-de26e366aa4148c6ae9cb7bdd55165c0?pvs=4#f4df5a41fc35401d9eb049710c872ea6.
Preview: https://deploy-preview-37830--material-ui.netlify.app/material-ui/react-alert/#basic-alerts
=> [docs-infra] Fix TypeScrit error in demo export

docs/src/modules/components/AppNavDrawerItem.js
After a few days of sleeping on this, I'm enjoying this design. It removes some of the visual weight of the whole docs, simplifies things, and makes it easier to identify subheaders in the side nav. Here's how it looks:
**https://deploy-preview-37860--material-ui.netlify.app/base-ui/getting-started/**
=> [docs-infra] Remove icons and tweak the design of the side nav

docs/pages/base-ui/all-components/index.js, docs/src/modules/components/AppLayoutDocs.js
Something I noticed from https://twitter.com/MUI_hq/status/1678486986137432074
1. Enable disableToc={true} on https://mui.com/base-ui/all-components/ to give it more space (half of the tocs width), same effect on the others page that uses it, like the Material Icon search page, or the template pages.
2. Fix the layout so it's stable when moving from a page that has `disableToc` to a page that doesn't.
https://deploy-preview-37931--material-ui.netlify.app/base-ui/all-components/
=> [docs-infra] Improve disableToc={true} support

docs/package.json, package.json, packages/mui-icons-material/builder.mjs
As noted in https://github.com/mui/material-ui/pull/37889#issuecomment-1630940642, updating rimraf to the latest version caused some problems as globs are not recognized now. This PR updates the call sites to fix this.
=> [core] Make rimraf work after a major update

docs/scripts/reportBrokenLinks.js, packages/markdown/parseMarkdown.js
Fix https://github.com/mui/material-ui/pull/37828#issuecomment-1625106485
The result of `docs:api` can be seen here:
https://app.circleci.com/pipelines/github/mui/material-ui/101747/workflows/4598f1ff-0e6d-455a-9eeb-4281d2b1dc51/jobs/542396?invite=true#step-111-3
=> [code-infra] Remove warnings in docs:api

docs/data/base/getting-started/quickstart/quickstart.md, docs/data/material/discover-more/roadmap/roadmap.md, docs/data/material/getting-started/installation/installation.md, docs/pages/about.tsx, docs/pages/material-ui.tsx
To update https://mui.com/material-ui/discover-more/roadmap/#new-components, the rest is side small fixes (e.g. title too long).
Preview: https://deploy-preview-37944--material-ui.netlify.app/material-ui/discover-more/roadmap/#new-components
I found this by searching for "charts" in Algolia. @alexfauquette shouldn't we instruct Algolia to index the charts pages? I think that you can go ahead and update the config.
=> [docs] Link charts in the roadmap

docs/data/base/getting-started/quickstart/quickstart.md, docs/data/joy/getting-started/installation/installation.md, docs/data/material/components/about-the-lab/about-the-lab.md, docs/data/material/components/material-icons/material-icons.md, docs/data/material/getting-started/installation/installation.md, docs/data/system/getting-started/installation/installation.md, docs/src/modules/components/ExampleCollection.js, docs/src/modules/components/HighlightedCodeWithTabs.tsx
This PR updates installation commands with the new `HighlightedCodeWithTabs` component, adding tabs to the code blocks. Picking up from a fantastic work by @alexfauquette on the component; here, I've refined the styles & updated the Core libraries docs.
**https://deploy-preview-37927--material-ui.netlify.app/material-ui/getting-started/installation/**
| <img width="839" alt="Screen Shot 2023-07-11 at 15 11 52" src="https://github.com/mui/material-ui/assets/67129314/7e67762b-3290-4c03-84eb-9cb891fe820b"> | <img width="839" alt="Screen Shot 2023-07-11 at 15 12 04" src="https://github.com/mui/material-ui/assets/67129314/c6416b18-fd59-4d32-9495-2912717a0a44"> |
=> [docs-infra] Update installation commands to use the new tabs code component

docs/notifications.json, docs/src/featureToggle.js, docs/src/modules/components/Notifications.js
Notification inviting users to check out charts
=> [notifications] Add notification for first Charts release

package.json, renovate.json, yarn.lock
Similar to https://github.com/mui/mui-x/pull/9107. 
Closes #37880.
Despite the statement in https://github.com/mui/material-ui/pull/37793#issuecomment-1617635461, Renovate still opened a pull request (#37880) for the update. See the discussion in #37793.
=> [core] Lock `@types/node` to v18

docs/data/base/components/autocomplete/autocomplete.md, docs/data/base/guides/next-js-app-router/next-js-app-router.md, docs/data/base/pages.ts, docs/data/joy/guides/next-js-app-router/next-js-app-router.md, docs/data/joy/pages.ts, docs/data/material/guides/next-js-app-router/next-js-app-router.md, docs/data/material/pages.ts, docs/pages/experiments/docs/callouts.md, docs/translations/translations.json
The bug was spotted by https://app.ahrefs.com/site-audit/3524616/73/data-explorer?columns=pageRating%2Curl%2Ctraffic%2ChttpCode%2CcontentType%2Cdepth%2CincomingAllLinks&filterId=9b88587038fc9bb2e08e0ff143d5f328&issueId=c64d89a6-d0f4-11e7-8ed1-001e67ed4656&sorting=-pageRatingis
Open https://mui.com/base-ui/guides/next-js-app-router/ and click on the link:
The actual fix is one of the last commits (https://github.com/mui/material-ui/commit/89a088b47f83eff08c13edd4871b1330304e5965), the rest is clean up to match repository conventions or fix small bugs.
=> [docs] Fix broken link to Base UI Next.js App Router 

docs/src/modules/components/HighlightedCodeWithTabs.tsx
Open https://master--material-ui.netlify.app/material-ui/getting-started/installation/#default-installation and struggle to read each tab, it also feels a bit like they were disabled tabs:
Open PR https://deploy-preview-38000--material-ui.netlify.app/material-ui/getting-started/installation/#default-installation and enjoy:
=> [docs-infra] Improve tab contrast in codeblock

packages/mui-material-next/src/Slider/useSliderElementsOverlap.ts
Missed this one in https://github.com/mui/material-ui/pull/37656
=> Add use client directive to useSliderElementsOverlap

packages/mui-material/src/styles/components.d.ts, packages/mui-material/src/styles/overrides.d.ts
Fixes https://github.com/mui/material-ui/issues/37949
The fix allows this to work without a TS error:
```js
components: {
MuiMenuList: {
defaultProps: {
dense: true,
},
},
},
});
```
Sandbox: https://codesandbox.io/s/https-github-com-mui-material-ui-pull-37956-st5yhg?file=/src/index.tsx:221-351
=> [Menu] Add MuiMenuList to createTheme components key

packages/mui-joy/src/Select/Select.tsx
Fixes https://github.com/mui/material-ui/issues/37968
=> [Joy][Select] Fix type error caused by custom variant

docs/data/material/getting-started/templates/checkout/Checkout.js, docs/data/material/getting-started/templates/checkout/Checkout.tsx
The checkout template theme was set to default light. Now it is corresponding to user preference.
=> [docs] checkout template follows user's color scheme preference

packages/mui-base/src/useAutocomplete/useAutocomplete.js
fixes https://github.com/mui/material-ui/issues/37848
Here the bug on mobile devices was due to the fact that we were calculating and scrolling the element / option into the view before selecting it, which selected an incorrect element.
I have made the functionality consistent with what is present in mobile devices.
Demo: https://codesandbox.io/s/nice-bush-mqzcpf?file=/demo.tsx
=> [Autocomplete] Make touch and click behavior on an option consistent

docs/pages/components.tsx
Fixes #38008
Since top level `/components/` doesn't have any `productId`, I am using `material-ui`'s pages to list all the components. Maybe we can provide a `Select` component to change the listing and also add the `productId` to the url param.
=> [docs]: Fix the empty /components page

docs/src/components/header/HeaderNavBar.tsx, docs/src/components/home/Hero.tsx, docs/src/layouts/HeroContainer.tsx, docs/src/modules/components/AppNavDrawer.js
Similar to https://github.com/mui/material-ui/pull/37997
=> [website] Fix a11y issues

docs/src/modules/components/Demo.js, docs/src/modules/components/DemoSandbox.js
A quick clean-up on the logic.
This effort is connected to the need to improve the performance of the docs pages. They should render much faster. We are reinforcing the idea that CSS-in-JS or event our components are slow.
=> [docs-infra] Improve performance hideToolbar: true

docs/pages/experiments/docs/installation.md, packages/markdown/parseMarkdown.js, packages/markdown/parseMarkdown.test.js
I have noticed that codeblocks do not work if the block contains backticks
Preview: https://deploy-preview-37950--material-ui.netlify.app/experiments/docs/installation/
=> [docs-infra] Support backticks in the codeblocks

docs/src/components/home/GetStartedButtons.tsx, docs/src/components/home/Hero.tsx, docs/src/components/home/StartToday.tsx, docs/src/components/productMaterial/MaterialHero.tsx
Take https://search.google.com/search-console/performance/search-analytics, developers were quick to jump into the opportunity to replace their search for "material ui" to "mui", I imagine because it's faster to type:
Noooo
1. Make landing on https://mui.com/material-ui/ from Google a faster way to reach Material UI docs than landing on https://mui.com/. So reduce the advantage of the shorter "mui" search query over typing "material ui".
2. Break the narrative of MUI homepage hosting the installation instructions of Material UI
Preview: https://deploy-preview-37971--material-ui.netlify.app/
It will be even better with #37608
=> [docs] Link Material UI from the landing page

.circleci/config.yml, packages/mui-joy/src/Skeleton/Skeleton.tsx, packages/mui-joy/src/Skeleton/index.ts, packages/mui-joy/src/ToggleButtonGroup/ToggleButtonGroup.tsx, packages/mui-joy/src/ToggleButtonGroup/index.ts
This is the root cause for https://github.com/mui/material-ui/pull/37955, originally I thought it was just a merge conflict
Discovered while testing `rsc:build` locally on the release branch
=> [core] Fix rsc build step in CI

packages/mui-material/src/Modal/Modal.test.js, packages/mui-material/src/Popover/Popover.test.js
`BackdropComponent` and `BackdropProps ` are `deprecated` but those are still used in few tests, This PR removes those instances.
current documentation for these props : https://mui.com/material-ui/api/modal/#props
=> [Modal] Remove deprecated `BackdropComponent` and `BackdropProps ` from tests

docs/src/modules/brandingTheme.ts
Before
https://master--material-ui.netlify.app/base-ui/
After
https://deploy-preview-38052--material-ui.netlify.app/base-ui/
It feels like there should be more y padding on the button, to have it "balanced".
=> [website] Improve button look

examples/material-next-app-router-ts/src/app/layout.tsx, examples/material-next-app-router-ts/src/components/ThemeRegistry/theme.ts
This PR aims to align all the used `font-family` styles of MUI components when `next/font` is used.
With the current approach, `className` which contains `font-family` from `next/font` is added to `body` and the `font-family` from `next/font` is applied to generic HTML elements.
But MUI components still use the default `font-family` from `theme` and since we don't install Roboto font with CDN etc., they don't use this font and they fall back to next fonts like `Helvetica`.
For example, we can check the "On This Page" text. It is a `Typography` component and it uses the default `"Roboto", "Helvetiva", "Arial", sans-serif` `font-family` even if we set the `className` of `body`.
But after this change, it will start using `--font-roboto` CSS variable, which we got from `next/font` and set on …
=> [examples] Fix material-next-app-router Font Usage with next/font

packages/mui-joy/src/Skeleton/Skeleton.tsx
Fixes the error displayed in the console reported in #38051
> Using kebab-case for css properties in objects is not supported. Did you mean WebkitMaskImage?
> in JoySkeletonRoot (created by Skeleton)
> in Skeleton (created by InlineSkeleton)
> in InlineSkeleton
=> [Skeleton][joy] Fix WebkitMaskImage CSS property

docs/data/joy/components/card/CardUsage.js, docs/data/joy/components/card/card.md
This adds a playground to the introduction section of the `Card` component to demo its variants, colors, size, orientation and inverted colors.
My apologies if this was omitted for a reason. Should there be documentation about the variants and colors? Most components have demos for variants and colors, this is also absent from the Card documentation.
=> [docs][joy] Add playground for Card component

docs/data/base/components/textarea-autosize/UnstyledTextarea/css/index.js, docs/data/base/components/textarea-autosize/UnstyledTextarea/css/index.tsx, docs/data/base/components/textarea-autosize/UnstyledTextarea/css/index.tsx.preview, docs/data/base/components/textarea-autosize/UnstyledTextarea/system/index.js, docs/data/base/components/textarea-autosize/UnstyledTextarea/system/index.tsx, docs/data/base/components/textarea-autosize/UnstyledTextarea/system/index.tsx.preview, docs/data/base/components/textarea-autosize/UnstyledTextarea/tailwind/index.js, docs/data/base/components/textarea-autosize/UnstyledTextarea/tailwind/index.tsx, docs/data/base/components/textarea-autosize/UnstyledTextarea/tailwind/index.tsx.preview, docs/data/base/components/textarea-autosize/textarea-autosize.md
Part of https://github.com/mui/material-ui/issues/37222
=> [docs][base] Add Tailwind CSS & plain CSS demos on the Textarea page

tslint.json
The TSLint's `deprecation` rule is broken, spamming the console with errors like `message.trim() is not a function`. Indeed the rule's code makes wrong assumptions about what gets returned from the parser.
The fix is theoretically very simple, but since TSLint is no longer maintained, it is not an option.
I tried to replace it with https://github.com/gund/eslint-plugin-deprecation, but it's insanely slow, so it's a no-go.
=> [core] Remove the deprecation rule in tslint

docs/src/modules/brandingTheme.ts, examples/base-next-app-router-tailwind-ts/src/app/page.tsx, examples/joy-next-app-router-ts/src/app/layout.tsx, examples/joy-next-app-router-ts/src/app/page.tsx, examples/joy-next-app-router-ts/src/components/ThemeRegistry/theme.js, examples/material-next-app-router-ts/src/app/layout.tsx, examples/material-next-app-router-ts/src/components/ThemeRegistry/theme.ts, examples/material-next-ts-v4-v5-migration/pages/_document.tsx, examples/material-next-ts-v4-v5-migration/src/theme.ts, examples/material-next-ts/src/theme.ts, examples/material-next/pages/_document.js, examples/material-next/src/theme.js
This PR aims to align all the used font-family styles of MUI components when next/font is used.
Similar to this PR: https://github.com/mui/material-ui/pull/38026
Close #38083
=> [examples] Fix Joy UI Next.js App Router font loading

docs/data/joy/components/menu/MenuIconSideNavExample.js, docs/data/joy/components/menu/MenuIconSideNavExample.tsx, docs/data/joy/components/radio-button/radio-button.md, docs/data/joy/getting-started/templates/framesx-web-blocks/theme.tsx, packages/mui-joy/src/Autocomplete/Autocomplete.tsx, packages/mui-joy/src/Container/Container.tsx, packages/mui-joy/src/className/index.ts, test/e2e/index.test.ts
closes #38067
This will break the application that is using hardcoded `Joy-` className.
To migrate, replace `Joy-` with `Mui-`:
```diff
- Joy-
+ Mui-
```
Those who are importing classes from components are safe from this breaking change.
---
=> [Joy] Replace leftover `Joy-` prefix with `Mui-`

packages/mui-joy/src/Link/Link.tsx
The reproduction https://codesandbox.io/s/nostalgic-solomon-dmwxr3?file=/Demo.tsx
```jsx
import Box from "@mui/joy/Box";
import Link from "@mui/joy/Link";
export default function LinkLevels() {
return (
<Box sx={{ fontWeight: 800 }}>
<Link level="inherit" component="button">
Link
</Link>
</Box>
);
}
```
Actual
Expected
Same fix as https://github.com/mui/material-ui/pull/38123
=> [Link][Joy UI] Fix font inherit

docs/pages/blog/2023-toolpad-beta-announcement.md
We moved the MUI Discord to a new location since this blog post got merged. Updated to https://discord.gg/tewQuNeUyS
=> [blog] Update Discord invite link in Toolpad beta announcement

.circleci/config.yml, packages/api-docs-builder/buildApiUtils.ts
This is a follow-up on https://github.com/mui/material-ui/pull/37813#discussion_r1260995356.
1. First the most important: I could break `yarn docs:api` without knowing it. The CI should now fail, see the first commit. I have copied `git add -A && git diff --exit-code --staged` from an existing test we have.
2. Second, the fix of `yarn docs:api`, see the second commit.
=> [test] Fail the CI when new unexpected files are created

docs/data/joy/components/select/SelectPosition.js, docs/data/joy/components/select/SelectPosition.tsx, docs/data/joy/components/select/select.md
closes: https://github.com/mui/material-ui/issues/38064
preview: https://deploy-preview-38130--material-ui.netlify.app/joy-ui/react-select/#listbox
=> Add listbox placement demo for Select

packages/mui-material/src/Tabs/Tabs.js
=> [Tabs] Refactor IntersectionObserver logic

docs/data/base/getting-started/quickstart/quickstart.md, docs/data/joy/getting-started/installation/installation.md, docs/data/material/components/about-the-lab/about-the-lab.md, docs/data/material/components/material-icons/material-icons.md, docs/data/material/getting-started/installation/installation.md, docs/data/material/migration/migration-v4/migration-v4.md, docs/data/system/getting-started/installation/installation.md, docs/pages/experiments/docs/codeblock.md
#36650 but for the whole docs. I noticed this here https://mui.com/material-ui/material-icons/. We should have updated everything.
Preview: https://deploy-preview-38161--material-ui.netlify.app/material-ui/material-icons/?query=a
=> [docs] Cover pnpm in more places

docs/src/modules/components/AppSearch.js
I broke this when I refactored the productId logic. The problem is that we were setting `productId:null` as an optional filter in the homepage. Now, Algolia is configured with
```js
ranking: [
"words",
"filters",
"typo",
"attribute",
"proximity",
"exact",
"custom",
],
```
https://www.algolia.com/doc/guides/managing-results/relevance-overview/in-depth/ranking-criteria/#filters
so it would rank first all the pages without a productId, which is right now the MUI X migration page as we have to refactor a bit these pages to get the productId from the markdown.
=> [docs-infra] Fix search ranking when no productId

docs/pages/base-ui/api/use-autocomplete.json, docs/pages/joy-ui/api/autocomplete.json, docs/pages/material-ui/api/autocomplete.json, docs/translations/api-docs/use-autocomplete/use-autocomplete.json, packages/mui-base/src/Badge/Badge.types.ts, packages/mui-base/src/Modal/Modal.types.ts, packages/mui-base/src/Slider/Slider.types.ts, packages/mui-base/src/useAutocomplete/useAutocomplete.d.ts, packages/mui-base/src/utils/areArraysEqual.ts, packages/mui-base/src/utils/mergeSlotProps.ts, packages/mui-base/src/utils/omitEventHandlers.ts, packages/mui-base/src/utils/types.ts, packages/mui-base/src/utils/useLatest.ts, packages/mui-joy/src/Autocomplete/Autocomplete.tsx, packages/mui-material/src/Autocomplete/Autocomplete.js
Similarly to #38155, in this PR I renamed one-letter type parameters in Base's type maps and props to something more meaningful.
=> [typescript][base] Rename one letter type parameters

packages/mui-material-next/src/Button/Button.types.ts, packages/mui-material-next/src/Input/Input.d.ts, packages/mui-material-next/src/Slider/Slider.types.ts, packages/mui-material-next/src/Tab/Tab.d.ts, packages/mui-material-next/src/TablePagination/TablePagination.d.ts, packages/mui-material-next/src/Tabs/Tabs.d.ts, packages/mui-material-next/src/styles/useThemeProps.ts
Similarly to #38155, in this PR I renamed one-letter type parameters in Material-next's type maps and props to something more meaningful.
=> [typescript][material-next] Rename one letter type parameters

packages/mui-material/src/styles/components.d.ts, packages/mui-material/src/styles/overrides.d.ts
Closes: #38151
The `styleOverrides` `MuiStack` key type was missing from the overrides `Components` type: https://github.com/mui/material-ui/pull/28843#issuecomment-939481966
=> [Theme][material] Add missing styleOverrides type for theme MuiStack

docs/src/modules/components/DemoToolbar.js, docs/src/modules/components/GoogleAnalytics.js, docs/src/modules/components/RichMarkdownElement.js
Adding Google event action for the styling menu options.
https://deploy-preview-38085--material-ui.netlify.app/base-ui/react-button/#basics
=> [docs] Add Google Analytics action for the styling menu

docs/translations/api-docs-joy/button/button.json, packages/mui-joy/src/Button/Button.tsx, packages/mui-joy/src/Button/ButtonProps.ts
Opened PR based on https://github.com/mui/material-ui/issues/38101#issuecomment-1650042136
preview: https://deploy-preview-38156--material-ui.netlify.app/joy-ui/api/button/#prop-loading
=> [docs][Button][joy] Improve `loading` prop documentation

packages/mui-system/src/Unstable_Grid/Grid.tsx, scripts/generateProptypes.ts
There is some logic that filter out files where the directory name and filename doesn't match, e.g. `Modal/ModalManager.d.ts`
But we need to make an exception for `Unstable_`/`unstable_`, as we do want Proptypes generated for e.g. `Unstable_Grid/Grid.tsx`
=> [core] Fix generate Proptypes script skipping unstable items

packages/mui-material/src/styles/createTypography.d.ts
All of the `FontStyle` type's properties are already required, so using the `Required` utility type is unnecessary. This was noticed while working on https://github.com/mui/material-ui/pull/38123.
=> [core] Remove unnecessary `Required` utility type from Typography font style type

packages/mui-system/src/Stack/Stack.test.js, packages/mui-system/src/Stack/createStack.tsx
closes: https://github.com/mui/material-ui/issues/37381 by forcing the `margin: 0` reset on all the children of the Stack component. Before this change, the reset is done on almost all the children but not the first child.
https://deploy-preview-37525--material-ui.netlify.app/system/react-stack/
before: https://codesandbox.io/s/sad-aj-45wiii?file=/src/App.js
after: https://codesandbox.io/s/sharp-sun-7pgg8k?file=/package.json
=> [Stack] Fix CSS selector

docs/data/joy/pages.ts
Following up on: https://github.com/mui/material-ui/pull/38174, there is one leftover nav icon that is making the CI fail (`ReferenceError: standardNavIcons is not defined`)
=> [docs-infra] Remove leftover standardNavIcon

docs/data/base/guides/working-with-tailwind-css/PlayerFinal.js, docs/data/base/guides/working-with-tailwind-css/working-with-tailwind-css-pt.md, docs/data/base/guides/working-with-tailwind-css/working-with-tailwind-css-zh.md, docs/data/base/guides/working-with-tailwind-css/working-with-tailwind-css.md, docs/data/material/getting-started/example-projects/example-projects-zh.md, docs/data/material/getting-started/installation/installation-pt.md, docs/data/material/getting-started/installation/installation-zh.md, docs/data/material/guides/interoperability/interoperability-pt.md, docs/data/material/guides/interoperability/interoperability-zh.md, docs/data/material/guides/routing/routing-pt.md, docs/data/material/guides/routing/routing-zh.md, docs/data/material/guides/server-rendering/server-rendering-pt.md, docs/data/material/guides/server-rendering/server-rendering-zh.md, docs/data/material/guides/styled-engine/styled-engine-pt.md, docs/data/material/guides/styled-engine/styled-engine-zh.md, docs/data/material/guides/typescript/typescript-pt.md, docs/data/material/guides/typescript/typescript-zh.md, docs/data/material/migration/migration-v4/migrating-from-jss-pt.md, docs/data/material/migration/migration-v4/migrating-from-jss-zh.md, docs/data/material/migration/migration-v4/migration-v4-pt.md, docs/data/material/migration/migration-v4/migration-v4-zh.md, docs/data/styles/advanced/advanced-pt.md, docs/data/styles/advanced/advanced-zh.md, docs/data/styles/advanced/advanced.md, examples/material-next-ts-v4-v5-migration/README.md
The PR fixes broken links to examples caused by PR #36112 and #36825, which renamed the `examples` directories for standardization. The proposed changes in the current PR resolve these broken links.
=> [docs] fix links to standardized examples

docs/src/modules/components/DiamondSponsors.js
This PR adds a super small spacing tweak to the Diamond Sponsor container and border radius to the link item to make it consistent with all other buttons throughout the documentation.
**https://deploy-preview-38257--material-ui.netlify.app/joy-ui/getting-started/**
=> [docs-infra] Small design polish to the Diamond Sponsor container

docs/pages/material-ui/api/checkbox.json, docs/translations/api-docs/checkbox/checkbox.json, packages/mui-material/src/Checkbox/Checkbox.js, packages/mui-material/src/Checkbox/Checkbox.test.js, packages/mui-material/src/Checkbox/checkboxClasses.ts
Places the `.MuiCheckbox-sizeSmall` and `.MuiCheckbox-sizeMedium` class on checkboxes where `size="small"` and `size="medium"`, respectively, similarly to how Button behaves.
Closes #38176.
=> [Checkbox][material] Add size classes

docs/scripts/reportBrokenLinks.js
The link-check script was crashing on Windows as it wasn't expecting forward slashes as path separators.
=> [core] Fix the link-check script on Windows

docs/src/modules/components/AppNavDrawerItem.js
Was browsing [the Obsidian documentation](https://help.obsidian.md/Home) for inspiration and felt like their side nav is super snappy. Made me realize how I always sort of felt ours was a bit too slow. So, this PR makes it a bit snappier/faster!
**https://deploy-preview-38259--material-ui.netlify.app/material-ui/getting-started/**
=> [docs-infra] Make the side nav collapse animation snappier

docs/src/modules/components/ApiPage.js, docs/src/modules/components/ApiPage/ApiItem.tsx, docs/src/modules/components/ApiPage/SlotsList.tsx, docs/src/modules/components/PropertiesTable.js
This PR adds some small changes to further polish the API content display:
- Delegate spacing to the Divider by removing the unnecessary `marginBottom: 36` and therefore balancing it out more.
- Alignment tweaks on the item note (i.e. "Required", "State").
- Remove the "Description" heading from Slot descriptions to make it consistent with prop descriptions.
- Remove the duplicate divider on the Slots section.
**https://deploy-preview-38282--material-ui.netlify.app/joy-ui/api/aspect-ratio/**
| <img width="851" alt="Screen Shot 2023-08-02 at 09 40 37" src="https://github.com/mui/material-ui/assets/67129314/0873e417-2efc-4a38-a360-16dd07b2f697"> | <img width="851" alt="Screen Shot 2023-08-02 at 09 40 57" …
=> [docs-infra] Add a general round of polish to the API content display

docs/data/material/components/autocomplete/autocomplete.md
The branch from #36483 was (likely) deleted by the author so I'm unable to complete it. This PR adds their warning callout to the Autocomplete doc.
=> [docs][material] Add note to Autocomplete about ref forwarding

docs/src/modules/components/SkipLink.tsx
Something that I noticed running the [Wave Evaluation Tool](https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh). Go to the https://mui.com/ site and press <kbd>Tab</kbd>, you will see it. 🙃
It got broken in #36622, with the change of the secondary color in `docs/src/modules/brandingTheme.ts`. This feature is explained at https://webaim.org/techniques/skipnav/.
I also used the opportunity to support motion reduction `@media (prefers-reduced-motion: reduce)`.
=> [docs-infra] Fix skip to content design

docs/src/modules/components/Demo.js, docs/src/modules/components/DemoSandbox.js
This greyed-ish background shifts the color contrast, it makes a bit more challenge to experience the components in real life.
Before
https://64cc13af167c35000826fb16--material-ui.netlify.app/joy-ui/react-button/#basics
After
https://deploy-preview-38307--material-ui.netlify.app/joy-ui/react-button/#basics
(*For those that the color difference is not visible on their screen, I think we need to find them a new screen, for me it's close to the limit of what I can perceive as a color difference, but it's noticeable, so I think for exigent users, it matters*)
=> [docs] Fix Joy UI demo background color

.eslintrc.js, docs/data/base/components/textarea-autosize/UnstyledTextareaIntroduction.js, docs/data/joy/components/autocomplete/AutocompleteVariables.js, docs/data/joy/components/button-group/ButtonGroupUsage.js, docs/data/joy/components/button/ButtonsSimple.js, docs/data/joy/components/chip/ChipUsage.js, docs/data/joy/components/table/TableUsage.js, docs/data/joy/components/tabs/TabsVariables.js, docs/data/joy/components/typography/TypographyUsage.js, docs/data/joy/customization/theme-colors/RemoveActiveTokens.js, docs/data/joy/getting-started/tutorial/LoginFinal.js, docs/data/joy/main-features/automatic-adjustment/InputVariables.js, docs/data/joy/main-features/automatic-adjustment/ListThemes.js, docs/data/material/components/buttons/ButtonMaterialYouPlayground.js, docs/data/material/components/slider/SliderMaterialYouPlayground.js, docs/data/material/customization/typography/ResponsiveFontSizesChart.js, docs/data/material/experimental-api/css-variables/CssVariablesCustomization.js, docs/data/material/migration/migration-grid-v2/GridDisableEqualOverflow.js
Same as #37278 but also for JavaScript demos. We still have demos that are JS only (e.g. in Joy UI so we can focus on more important topics). I noticed this having a look at a PR on Joy UI.
=> [core] Fix docs demo export function consistency

docs/data/material/components/app-bar/ResponsiveAppBar.js, docs/data/material/components/app-bar/ResponsiveAppBar.tsx
user is not able to navigate to the root page when clicking on the logo in small screen view 
while it works in big screen view
=> [docs][AppBar] Fix `ResponsiveAppBar` demo logo href

packages/mui-joy/src/MenuButton/MenuButton.test.tsx, packages/mui-joy/src/MenuButton/MenuButton.tsx
This PR makes sure `MenuButton` is disabled when `disabled` prop is set to true
before: https://codesandbox.io/s/loving-leftpad-nrxpvc?file=/Demo.js
after: https://codesandbox.io/s/nostalgic-pond-whrs7p
=> [joy-ui][MenuButton] Fix disable of `MenuButton`

docs/data/base/components/button/UnstyledButtonIntroduction/css/index.js, docs/data/base/components/button/UnstyledButtonIntroduction/css/index.tsx, docs/data/base/components/button/UnstyledButtonIntroduction/css/index.tsx.preview, docs/data/base/components/button/UnstyledButtonIntroduction/system/index.js, docs/data/base/components/button/UnstyledButtonIntroduction/system/index.tsx, docs/data/base/components/button/UnstyledButtonIntroduction/system/index.tsx.preview, docs/data/base/components/button/UnstyledButtonIntroduction/tailwind/index.js, docs/data/base/components/button/UnstyledButtonIntroduction/tailwind/index.tsx, docs/data/base/components/button/UnstyledButtonIntroduction/tailwind/index.tsx.preview, docs/data/base/components/button/UnstyledButtonsSimple/tailwind/index.js, docs/data/base/components/button/UnstyledButtonsSimple/tailwind/index.tsx, docs/data/base/components/button/UnstyledButtonsSimple/tailwind/index.tsx.preview, docs/data/base/components/button/UnstyledButtonsSpan/css/index.js, docs/data/base/components/button/UnstyledButtonsSpan/css/index.tsx, docs/data/base/components/button/UnstyledButtonsSpan/css/index.tsx.preview, docs/data/base/components/button/UnstyledButtonsSpan/system/index.js, docs/data/base/components/button/UnstyledButtonsSpan/system/index.tsx, docs/data/base/components/button/UnstyledButtonsSpan/system/index.tsx.preview, docs/data/base/components/button/UnstyledButtonsSpan/tailwind/index.js, docs/data/base/components/button/UnstyledButtonsSpan/tailwind/index.tsx, docs/data/base/components/button/UnstyledButtonsSpan/tailwind/index.tsx.preview, docs/data/base/components/button/button.md
Part of https://github.com/mui/material-ui/issues/37222
=> [docs][base] Add Tailwind CSS + plain CSS demo on the Button page

.github/workflows/ensure-triage-label.yml
For context: https://www.notion.so/mui-org/GitHub-Action-to-add-need-triage-label-if-none-is-present-e6357dacba7947a1879d684c7bb63939?d=4912f8bad6af466783a3ef21ac71bad2
=> [core] Port GitHub workflow for ensuring triage label is present

packages/mui-base/src/Unstable_NumberInput/NumberInput.test.tsx
=> [test] Remove unnecessary `async` keyword from test

docs/src/modules/components/MarkdownElement.js
This PR fixes the info callout border color that had as a variable the `primary` palette but is using the `grey` one instead, which is the correct option.
| <img width="712" alt="Screen Shot 2023-08-07 at 20 58 54" src="https://github.com/mui/material-ui/assets/67129314/8a00984d-9c5e-4362-82a3-327495c638d2"> | <img width="712" alt="Screen Shot 2023-08-07 at 20 58 39" src="https://github.com/mui/material-ui/assets/67129314/1e0d379b-5859-466f-b473-43518e6a1e9f"> |
=> [docs-infra] Fix info callout border color

docs/data/docs-infra/pages.ts, docs/pages/experiments/docs/headers.md, docs/src/modules/components/MarkdownElement.js
Experimenting with tweaking font size and spacing on the docs' headings to separate them visually a bit more.
- https://deploy-preview-38365--material-ui.netlify.app/experiments/docs/headers/
- https://deploy-preview-38365--material-ui.netlify.app/blog/mui-x-v6/ (this one has a lot of headings that are useful to see how it feels like!).
=> [docs-infra] Adjust heading styles

docs/pages/base-ui/api/number-input.json, docs/translations/api-docs-base/number-input/number-input.json, packages/mui-base/src/Unstable_NumberInput/NumberInput.types.ts
Follow up to https://github.com/mui/material-ui/pull/36119#pullrequestreview-1558656545
Add slots and classes in the API page: [preview](https://deploy-preview-38363--material-ui.netlify.app/base-ui/react-number-input/components-api/#number-input-slots)
=> [docs][base-ui] Update number input API docs

docs/data/joy/components/input/InputFormProps.js, docs/data/joy/components/input/InputFormProps.tsx, docs/data/joy/components/input/InputFormProps.tsx.preview, docs/data/joy/components/input/InputValidation.js, docs/data/joy/components/input/InputValidation.tsx, docs/data/joy/components/input/InputValidation.tsx.preview, docs/data/joy/components/input/input.md, packages/mui-joy/src/FormHelperText/FormHelperText.tsx, packages/mui-joy/src/FormLabel/FormLabel.tsx
Fixed issue: #38353
just fixed icons inside the FormHelperText now these icons would inherit the danger color [Issue](https://github.com/mui/material-ui/issues/38353#issuecomment-1668920751).
=> [Input][joy-ui] Fix the `FormHelperText` icon color

packages/mui-joy/src/Skeleton/Skeleton.tsx
Increased the pulse animation time from 1.5s to 2.0s to make it softer and more pleasant when used in many places at the same time.
https://deploy-preview-38384--material-ui.netlify.app/joy-ui/react-skeleton/
https://mui.com/joy-ui/react-skeleton/
=> [Skeleton][joy-ui] Soften the pulse animation

docs/data/joy/getting-started/usage/ButtonUsage.js, docs/data/joy/getting-started/usage/ButtonUsage.tsx, docs/data/joy/getting-started/usage/ButtonUsage.tsx.preview, docs/data/joy/getting-started/usage/usage.md, docs/data/material/getting-started/usage/ButtonUsage.js, docs/data/material/getting-started/usage/ButtonUsage.tsx, docs/data/material/getting-started/usage/ButtonUsage.tsx.preview, docs/data/material/getting-started/usage/usage.md
From the series of "just browsing around looking for improvement opportunities", I realized we could be simpler and more polished on the Quickstart section of the Usage page now that the documentation code snippets are editable. Given that wasn't the case previously, we have a Code Sandbox iframe which always looks a bit clunky with their UI. Figured it'd be much cleaner with a built-in demo. Also, took the liberty to simplify the copy a lot, too!
- **https://deploy-preview-38385--material-ui.netlify.app/material-ui/getting-started/usage/**
- **https://deploy-preview-38385--material-ui.netlify.app/joy-ui/getting-started/usage/**
=> [docs][material-ui][joy-ui] Simplify the Quickstart section on the Usage page

packages/mui-base/src/useButton/useButton.test.tsx, packages/mui-base/src/useButton/useButton.ts
The `onFocusVisible` handler was being removed preemptively, causing it to always be undefined on the focus handler, so a provided handler would never be called: https://codesandbox.io/s/focus-visible-deleted-preemptively-h456fp?file=/Demo.tsx
The fix is to remove `onFocusVisible` after it has been passed to the focus handler, not before.
=> [useButton][base] Fix onFocusVisible not being handled

docs/pages/base-ui/api/switch.json, docs/pages/joy-ui/api/switch.json, packages/api-docs-builder/utils/parseSlotsAndClasses.ts, packages/mui-utils/src/generateUtilityClass/generateUtilityClass.ts
The docs stated that Base's and Joy's Switch has the `.MuiSwitch-readOnly` class, but the components used the `.Mui-readOnly`.
It was caused by a discrepancy between what API builder considered a global state class and what was generated as a state class.
The API docs generation script logic was updated.
Before: https://mui.com/base-ui/react-switch/components-api/#switch-classes
After: https://deploy-preview-38277--material-ui.netlify.app/base-ui/react-switch/components-api/#switch-classes
=> [Switch][docs] Fix the readOnly class name in docs

packages/mui-base/src/Badge/Badge.types.ts, packages/mui-base/src/Modal/Modal.types.ts, packages/mui-base/src/Slider/Slider.types.ts, packages/mui-material/src/Badge/Badge.d.ts
Removed the old `Extend*` types from Badge, Modal, and Slider.
Also changed the Material UI Badge that was incorrectly using the `ExtendBadgeTypeMap` (its implementation isn't tied or related to Base UI's Badge, so it shouldn't reuse its types).
Base UI components' props can be extended using the `*OwnProps` interface:
```ts
import { BadgeOwnProps } from '@mui/base/Badge';
interface MyExtendedBadgeTypeMap<AdditionalProps = {}, DefaultComponent = 'span'> {
props: AdditionalProps & BadgeOwnProps & {
// ... your props here
},
defaultComponent: DefaultComponent
}
```
=> [base] Remove the legacy Extend* types

docs/data/joy/components/menu/ControlledDropdown.js, docs/data/joy/components/menu/ControlledDropdown.tsx, docs/data/joy/components/menu/ControlledDropdown.tsx.preview, docs/data/joy/components/menu/menu.md
Added a section to the Menu docs explaining how to use a controlled Dropdown.
This is a part of the attempt to solve a problem described in #38324.
=> [docs][Menu][joy] Explain how to control the open state

docs/data/joy/components/button/InputFileUpload.js, docs/data/joy/components/button/InputFileUpload.tsx, docs/data/joy/components/button/button.md
This PR adds a new demo which showcases how to turn `Button` component to `input` component with type as `file`.
preview: https://deploy-preview-38420--material-ui.netlify.app/joy-ui/react-button/#file-upload
=> [joy-ui][docs] Add `FileUpload` demo

packages/mui-base/src/useButton/useButton.test.tsx, packages/mui-base/src/useButton/useButton.ts
Closes #38368
The `tabIndex` value was only taken into consideration for certain cases, so its value would be lost when not taken into consideration: https://codesandbox.io/s/usebutton-tabindex-lost-sd37h8?file=/Demo.tsx
This fix adds the `tabIndex` value to the `getRootProps` return value initialization. This way, if explicitly provided, then it will be included in `getRootProps` return value. The previous behavior is maintained as the `tabIndex` is only added as a starting point.
=> [useButton][base] Fix tabIndex not being forwarded

docs/pages/joy-ui/react-button-group.js, docs/pages/joy-ui/react-button.js
Open https://mui.com/joy-ui/react-button/ and try to navigate to the Button Group page
560ms. Note that the Material UI Button -> ButtonGroup page transition also feels really bad, it's only 100-150ms faster: 430ms. According to https://web.dev/vitals/ great is at <100ms. I think where it's killing us comes next.
1. Google Search will use a new performance ranking metric, we don't do well: 
https://search.google.com/search-console/core-web-vitals/summary?resource_id=sc-domain%3Amui.com&device=2#inp-table
2. Second, compare the experience to https://www.radix-ui.com/themes/docs/components/button to move to the Checkbox page:
It's x4 better. Same on https://ui.shadcn.com/docs/components/button, it's at about 130ms. So as a developer, my first impression is: **"No, I'm not using Material UI, …
=> [docs] Improve page transition speed

CHANGELOG.md, docs/src/components/footer/EmailSubscribe.tsx
A quick fix, while I was looking at something else.
Before 
After
=> [website] Fix EmailSubscribe look

packages/mui-material/src/InputBase/InputBase.js, packages/mui-material/src/TextField/TextField.js, packages/mui-material/src/TextField/TextField.test.js, test/e2e/fixtures/TextField/TextFieldWithOnClick.tsx, test/e2e/index.test.ts
https://github.com/mui/material-ui/pull/36892 changed the `onClick` handling behavior on the `TextField` component.
Previously the callback used to be registered on the root element and pickers relied on it (https://github.com/mui/mui-x/pull/6074) to correctly handle click -> open behavior regardless of where the click has been done.
Now we have a regression https://github.com/mui/mui-x/issues/9386 on the mentioned behavior because the fix has basically been negated.
Closes https://github.com/mui/mui-x/issues/9386
If you have any better suggestions on how to solve this conundrum—I'm open to suggestions.
We have considered and tried using `onMouseDown`, but it has its drawbacks and interferes with other component behavior.
One other easy fix would be to remove the `z-index: 1` on the label …
=> [TextField] Fix to handle `onClick` on root element

docs/src/modules/components/AppNavDrawer.js, docs/src/modules/components/AppNavDrawerItem.js
It's a continuation of #38259 retaining the general design direction of it, while also making it feel consistent between different side nav that have **different heights**. What do you think, better or worse?
Before 38259: https://64c9260dfe62470008859eb0--material-ui-docs.netlify.app/material-ui/getting-started/
38259: https://deploy-preview-38259--material-ui.netlify.app/material-ui/getting-started/
This PR: https://deploy-preview-38393--material-ui.netlify.app/material-ui/getting-started/
---
As a related topic, I think it connects back to point 1 in https://github.com/mui/material-ui/pull/38164#pullrequestreview-1549831929.
=> [docs-infra] Retain side nav animation speed

docs/data/docs-infra/pages.ts, docs/pages/experiments/docs/headers.md, docs/pages/experiments/docs/markdown.js, docs/pages/experiments/docs/markdown.md, docs/src/modules/components/MarkdownElement.js
I saw this problem while I was leaving feedback for #38241.
Before https://mui.com/blog/mui-x-v5/
After https://deploy-preview-38456--material-ui.netlify.app/blog/mui-x-v5/
---
I'm more or less copying https://mintlify.com/docs/content/list-table for the docs-infra docs.
=> [docs-infra] Fix nested list margin

docs/data/joy/components/snackbar/snackbar.md, docs/data/material/getting-started/support/support.md, docs/data/material/guides/routing/routing.md, docs/src/modules/components/Link.tsx, packages/markdown/parseMarkdown.js
https://app.ahrefs.com/site-audit/3524616/77/data-explorer?columns=pageRating%2Curl%2Ctraffic%2ChttpCode%2CcontentType%2Cdepth%2Credirect%2CincomingAllLinks&filterId=b3b75b6257a370fcf9f1f73befb5deb5&issueId=c64d8847-d0f4-11e7-8ed1-001e67ed4656&sorting=-pageRating
=> [docs] Fix SEO issues reported by ahrefs

docs/src/modules/components/CodeCopyButton.tsx
=> [docs-infra] Fix GoogleAnalytics missing event for code copy

docs/pages/pricing.tsx, docs/src/components/footer/EmailSubscribe.tsx, docs/src/components/pricing/HeroPricing.tsx, docs/src/modules/brandingTheme.ts, docs/src/modules/components/AppSearch.js, docs/src/modules/components/ComponentPageTabs.js, docs/src/modules/components/DiamondSponsors.js, docs/src/modules/components/MaterialFreeTemplatesCollection.js, docs/translations/translations.json
Just some quality-of-life improvements here ⎯ doing a general polish on spacing and, most notably, adding a subtle box shadow to clickable buttons and links to give that elevated look we've been using now in some demos as well as the new website/docs button styles.
**https://deploy-preview-38501--material-ui.netlify.app/**
=> [docs] Add stray design adjustments to the docs

docs/pages/base-ui/api/number-input.json, docs/pages/base-ui/api/use-modal.json, docs/src/modules/components/JoyUsageDemo.tsx
The Playground bgColor was [getting in the way of some Joy UI demos](https://www.notion.so/mui-org/Olivier-design-review-on-Joy-Design-3ada9a7bcfa44b9fab1fe5032dfb33bb?pvs=4#0b37e7c1e6964af2a53886d67638bbfa), due to the gradient and the blue tone:
So I added the `bgcolor: 'var(--joy-palette-background-surface)'`, making it closer to the context where it'll be applied by the users.
=> [joy-ui][docs] Changed bgcolor of the Playground demo

docs/data/material/guides/api/api.md, docs/src/modules/components/MarkdownElement.js
Just a little quality-of-life thing. Before we had callouts, we used to use the `blockquote` element for that, and the styles were there sitting outdated. Thought we could have something slightly fancier! 😊
**https://deploy-preview-38503--material-ui.netlify.app/material-ui/guides/api/**
=> [docs-infra] Customize the blockquote design

docs/src/modules/components/MarkdownElement.js
Was again just browsing the docs looking for improvement opportunities and realized that the anchor button for the heading was again misaligned (this seems to happen whenever changes happen to the heading styles). 😭 Figured that using an `inline-flex` for the button itself and other flex-related properties would ensure the alignment instead of an arbitrary line height ⎯ similarly with the heading itself instead of absolute positioning the two. 
Not _fully_ aware of whether these changes have unintended consequences, so... let me know if this works out!
**https://deploy-preview-38428--material-ui.netlify.app/experiments/docs/headers/**
=> [docs-infra] Improve the heading buttons positioning

docs/data/base/components/menu/UseMenu.js, docs/data/base/components/menu/UseMenu.tsx, docs/data/base/components/menu/UseMenu.tsx.preview
=> [docs][base-ui] Fix Menu Hooks demo

docs/src/modules/components/Demo.js, docs/src/modules/components/DemoToolbar.js
A warning is being thrown in docs while running it locally regarding `showSourceHint` prop not being recognized by React on a DOM element. This might be due to the replacement of the `ToggleCodeTooltip` component with Material UI's `Button` component in pull request #38421, which is now forwarding the prop.
Noticed while running the docs locally.
=> [docs-infra] Cleanup code on demo code block expansion

docs/data/joy/components/list/ListUsage.js
Added one more item to the `List` playground demo
https://deploy-preview-38499--material-ui.netlify.app/joy-ui/react-list/
=> [joy-ui][docs] Updated the List playground demo

docs/translations/api-docs-joy/autocomplete-listbox/autocomplete-listbox.json, docs/translations/api-docs-joy/list/list.json, docs/translations/api-docs-joy/menu-list/menu-list.json, docs/translations/api-docs-joy/menu/menu.json, docs/translations/api-docs-joy/tab-list/tab-list.json, docs/translations/api-docs-joy/tab-panel/tab-panel.json, docs/translations/api-docs-joy/tab/tab.json, docs/translations/api-docs-joy/tabs/tabs.json, packages/mui-joy/src/AutocompleteListbox/autocompleteListboxClasses.ts, packages/mui-joy/src/List/listClasses.ts, packages/mui-joy/src/Menu/menuClasses.ts, packages/mui-joy/src/MenuList/menuListClasses.ts, packages/mui-joy/src/Tab/tabClasses.ts, packages/mui-joy/src/TabList/tabListClasses.ts, packages/mui-joy/src/TabPanel/tabPanelClasses.ts, packages/mui-joy/src/Tabs/tabsClasses.ts
Classes description was using `Classname` without space. I'm adding the space for consistency wit the rest of the docs
=> [joy-ui] Fix typo: Classname -> Class name for consistency

docs/src/modules/components/MarkdownElement.js
This PR fixes an unintended leftover of the previous PR about the same components (https://github.com/mui/material-ui/pull/38428) that was causing a layout shift on the headings by particularly implementing the suggestion @alexfauquette dropped here: https://github.com/mui/material-ui/pull/38428#issuecomment-1682307116
| <img width="500" alt="Screen Shot 2023-08-16 at 14 01 13" src="https://github.com/mui/material-ui/assets/67129314/30c3f7b3-63d6-49ed-81d1-8aea1d68d116"> | <img width="500" alt="Screen Shot 2023-08-16 at 14 01 13" src="https://github.com/mui/material-ui/assets/67129314/cc921481-5ba2-4e1f-b8f8-2680ef0e90e7"> | 
**https://deploy-preview-38528--material-ui.netlify.app/material-ui/getting-started/faq/#why-are-the-colors-i-am-seeing-differe …
=> [docs-infra] Fix the anchor link on headings

docs/translations/api-docs-joy/input/input.json, packages/mui-joy/src/Input/Input.tsx, packages/mui-joy/src/Input/InputProps.ts
The documentation and prop type definition for the `fullWidth` prop of the Joy-UI `Input` references a button. I think this was likely a copy paste error, and should instead say input.
Preview - https://deploy-preview-38545--material-ui.netlify.app/joy-ui/api/input/#Input-prop-fullWidth
=> [docs][joy-ui] Fix the `fullWidth` prop description for the Input

docs/data/base/all-components/all-components.md, docs/data/material/discover-more/showcase/showcase.md, docs/data/material/getting-started/example-projects/example-projects.md, docs/data/material/getting-started/templates/templates.md, docs/src/modules/components/ExampleCollection.js, packages/markdown/loader.js
A quick follow-up on https://github.com/mui/material-ui/pull/37007#discussion_r1205426539 and https://github.com/mui/material-ui/pull/37444#discussion_r1296538292, to follow the standards, it should be simpler.
=> [docs-infra] Follow import and CSS token standard

docs/pages/joy-ui/customization/theme-builder.js
Give more space for https://mui.com/joy-ui/customization/theme-builder/.
Preview https://deploy-preview-38532--material-ui.netlify.app/joy-ui/customization/theme-builder/ 
---
In hindsight, compared to https://www.radix-ui.com/themes/playground and https://ui.shadcn.com/themes, it feels like we missed the product priority. This demo feels too advanced, not too far from the point where the persona it targets would prefer to do this in code or in Figma. I think the more important use case is quick high-level customization. And the most important: how do you even know if these values make sense? I think Developers should be able to better previous how values impact the look of the components.
So, I would be in favor of:
- create a https://www.radix-ui.com/themes/playground for Material UI …
=> [docs] More space for theme builder

test/regressions/webpack.config.js
=> [core] Remove redundant `@material-ui/` aliases from regression test webpack config

docs/src/components/action/NpmCopyButton.tsx
A quick bug fix, I noticed on my phone checking a SEO report
Before https://mui.com/material-ui/
After https://deploy-preview-38568--material-ui.netlify.app/material-ui/
=> [website] Fix mobile view Material UI page

docs/src/modules/components/AppNavDrawer.js, docs/src/modules/components/AppNavDrawerItem.js
Reopen #38393, resuming the exploration from https://github.com/mui/material-ui/pull/38393#discussion_r1292827227. It was merged while the PR was pending for feedback.
Also related to #38164
=> [docs-infra] Retain velocity animation speed

docs/src/modules/components/MarkdownDocsV2.js
I noticed this bug: Open https://mui.com/material-ui/react-button/#basic-button the anchor offset is wrong. It got annoyed, a trivial fix, so why not? This regression originates from moving from `MarkdownDocs` to `MarkdownDocsV2`.
Preview: https://deploy-preview-38586--material-ui.netlify.app/material-ui/react-button/#basic-button
=> [docs-infra] Fix anchor scroll without tabs

docs/data/base/components/autocomplete/autocomplete.md, docs/data/base/components/slider/slider.md, docs/data/base/components/switch/switch.md, docs/data/base/components/tabs/tabs.md
In the current version of the Base UI docs, the headers are structured like this:
```
```
In practice, there's a lot of overlap between the `Introduction`, `Usage`, and `Basics` sections, and some of the docs have redundant content repeated in each—particularly since we added the Intro playgrounds.
This PR:
- condenses `Usage` and `Basics` in to one section called `Usage`
- removes most of the boilerplate Basics code (leaving only the import, as we've done in the Joy UI docs)
- removes Usage/Basics content where it's just repeating the Introduction
I also couldn't resist doing some copyediting, mostly to the Autocomplete page.
Before: 
After:
Right now this PR only involves a few of the pages, because I want to make sure we agree on the updated format before applying it to all others. I …
=> [docs][base-ui] Revise the structure of the Component docs

docs/data/material/components/dialogs/CustomizedDialogs.js, docs/data/material/components/dialogs/CustomizedDialogs.tsx
Closes #37670.
When the `<button>` is placed outside the dialog title (h2), it announces correctly. While it's not flawless, it avoids saying "Modal title _close dialog_" and "close button _heading level 2_" Instead, it now says "Modal title Dialog," and when tabbed to the close button, it announces "Close button" (Confirmed on NVDA version 2023.1).
I also removed an unnecessary conditional operator regarding the `onClose` handler to show the close icon button.
Before: https://mui.com/material-ui/react-dialog/#customization
After: https://deploy-preview-38592--material-ui.netlify.app/material-ui/react-dialog/#customization
=> [docs][material-ui][Dialog] Improve screen reader announcement of Customized Dialog

docs/src/modules/components/Ad.js, docs/src/modules/components/ad.styles.js
Just a small spacing, fine-tuning, and border styles tweak. Given that the docs have many lines/dividers going on, the more subtle dashed border seems to fit well here, considering the ads already stand out due to their imagery.
**https://deploy-preview-38504--material-ui.netlify.app/material-ui/guides/themeable-component/**
=> [docs-infra] Add light tweaks to the ad container

docs/src/components/action/NpmCopyButton.tsx, docs/src/components/home/GetStartedButtons.tsx, docs/src/modules/brandingTheme.ts
This PR fixes the previously broken without-transition hover styles on the primary button and adds a slight transition to the end icon when hovering over the button. A bonus transition to the paper component was also added (but ommitted from the title for brevity).
**https://deploy-preview-38588--material-ui.netlify.app/base-ui/**
=> [website] Fine-tune the branding theme buttons

docs/pages/base-ui/api/use-button.json, packages/mui-base/src/useButton/useButton.test.tsx, packages/mui-base/src/useButton/useButton.ts, packages/mui-base/src/useButton/useButton.types.ts
Applies changes proposed in https://github.com/mui/material-ui/issues/38186 for the `useButton` hook. This was also raised in https://github.com/mui/material-ui/pull/38392#discussion_r1291787457 to keep a consistent API regarding the `useInput` hook.
=> [useButton][base-ui] Accept arbitrary props in getRootProps and forward them

docs/src/modules/components/SkipLink.tsx
This PR will fix the unwanted behavior of the `SkipLink` button if the user has enabled `prefers-reduced-motion` which made it impossible to click the dropdown on the top left of the docs page. 
closes #38546
=> [docs-infra] Hide the SkipLink button if user prefers reduced motion

docs/data/material/components/badges/badges.md, docs/data/material/components/buttons/buttons.md, docs/data/material/components/slider/slider.md, docs/src/modules/components/Demo.js, docs/src/modules/components/MaterialYouUsageDemo.tsx
As I was recently tweaking the Joy UI version of the Playground demos, I bumped into the Material You one and figured it had a lot that could be polished up. Additionally, created a new variant of the `Demo` component to account for exactly the Playground demos.
- **https://deploy-preview-38636--material-ui.netlify.app/material-ui/react-button/#material-you-version**
- **https://deploy-preview-38636--material-ui.netlify.app/material-ui/react-slider/#material-you-version**
- **https://deploy-preview-38636--material-ui.netlify.app/material-ui/react-badge/#material-you-version**
| <img width="841" alt="Screen Shot 2023-08-24 at 20 04 49" src="https://github.com/mui/material-ui/assets/67129314/9d8f93b3-523d-4c0f-9592-500e5c1fad22"> | <img width="841" …
=> [docs-infra] Adjust the Material You playground demo design

packages/mui-material/test/umd/run.js
Seeing a bunch of [crashes](https://app.circleci.com/pipelines/github/mui/material-ui/106207/workflows/e4975e46-68a7-4d17-a0dd-4237a002c8f1/jobs/568252) lately. Modern headless Chrome should be stable enough to work without this flag.
https://bugs.chromium.org/p/chromium/issues/detail?id=1162815#c5
> --single-process was mostly used for debugbing purpose and is not a mode we really supports.
https://web.archive.org/web/20220125002107/https://www.chromium.org/developers/design-documents/process-models/#TOC-Single-process
> The single process model provides a baseline for measuring any overhead that the multi-process architectures impose. It is not a safe or robust architecture, as any renderer crash will cause the loss of the entire browser process. It is designed for testing and …
=> [core] Potential fix for intermittent ci crashes in e2e test

apps/zero-runtime-vite-app/package.json, apps/zero-runtime-vite-app/src/App.tsx, apps/zero-runtime-vite-app/vite.config.ts, apps/zero-runtime-vite-app/yarn.lock, packages/zero-runtime/package.json, packages/zero-runtime/src/index.ts, packages/zero-runtime/src/styled.js, packages/zero-runtime/src/sx.d.ts, packages/zero-runtime/src/sx.js, packages/zero-tag-processor/package.json, packages/zero-tag-processor/src/pre-linaria-plugin.ts, packages/zero-tag-processor/src/styled.ts, packages/zero-tag-processor/src/sx.ts, packages/zero-tag-processor/src/utils/checkStaticObjectOrArray.ts, packages/zero-tag-processor/src/utils/sxObjectExtractor.ts, yarn.lock
User can pass object or a callback that returns an object.
=> [system][zero][tag] Add support for sx prop

docs/data/joy/getting-started/usage/usage.md, docs/data/material/getting-started/usage/usage.md
Fix https://mui-org.slack.com/archives/C041SDSF32L/p1693255905957869
=> [docs] Show all the code in the usage section

packages/mui-base/src/useAutocomplete/useAutocomplete.js, packages/mui-material/src/Autocomplete/Autocomplete.test.js
Fixes https://github.com/mui/material-ui/issues/36867
Here is a sandbox with the original repro and a simplified one that shows the fix: https://codesandbox.io/s/https-github-com-mui-material-ui-pull-38611-3hygqs?file=/demo.tsx
I can hardly believe how simple this fix could be, but it make sense to block the popup from opening if the component is `disabled`:
```diff
const handleInputMouseDown = (event) => {
-    if (inputValue === '' || !open) {
+    if (!disabledProp && (inputValue === '' || !open)) {
handlePopupIndicator(event);
}
};
```
Here is the simplified repro (I colored different parts of it) showing the bug: https://codesandbox.io/s/https-github-com-mui-material-ui-issues-36867-m25xds?file=/demo.tsx
Both cases are reproducible:
1. Click on any part of the component that doesn't …
=> [Autocomplete] Fix listbox opened unexpectedly when component is `disabled`

docs/data/base/components/number-input/NumberInputIntroduction.js, docs/data/base/components/number-input/NumberInputIntroduction.tsx, docs/data/base/components/number-input/number-input.md, docs/data/base/pages.ts
Fixes several issues raised in https://github.com/mui/material-ui/pull/36119#issuecomment-1678269343
1. Arrow aligment in the intro & basic demos:
2. Fixed indentation in a snippet in the [Basics section](https://deploy-preview-38521--material-ui.netlify.app/base-ui/react-number-input/#basics)
3. Step rounding - I've added a callout about decimals not being supported yet and linking to an issue to upvote
Preview https://deploy-preview-38521--material-ui.netlify.app/base-ui/react-number-input/
=> [docs] Number Input docs fixes

docs/data/base/pages.ts, docs/src/MuiPage.ts, docs/src/modules/components/AppNavDrawer.js, docs/src/modules/components/AppNavDrawerItem.js
Realizing we don't have any way of showing unstable components, I added a chip (similarly to "planned") to the app nav drawer entries.
I marked Base UI's Number Input as such:
=> [docs-infra] Mark unstable components with a chip in the nav drawer

packages/mui-material/src/Select/Select.test.js, packages/mui-material/src/Select/SelectInput.js
When `MenuProps.slotProps.paper` was provided to the Select, it replaced the internal props instead of merging them. This PR solves this.
Fixes #38700.
=> [Select][material-ui] Merge slotProps.paper with internal Paper props

docs/src/modules/components/MarkdownElement.js
This PR fixes a bug happening when there's a code block inside a callout. It was not happening to a bunch of instances, at least as far as I could find, but I recently noticed it on the Joy UI List page. Not sure if this is the ideal fix but it solves the problem for now.
| <img width="731" alt="Screen Shot 2023-08-29 at 11 46 25" src="https://github.com/mui/material-ui/assets/67129314/00179a92-e53b-4094-8e73-73904785c5fe"> | <img width="731" alt="Screen Shot 2023-08-29 at 13 54 09" src="https://github.com/mui/material-ui/assets/67129314/7db18da3-dedc-4378-8ab1-61422479d443"> |
=> [docs-infra] Fix leaking callout content

docs/src/modules/components/HighlightedCodeWithTabs.tsx
I wanted to try something on a demo in the docs, turns out I was not using the right prop based on a console log.
However, there is crap in the console I had to scroll paste:
Introduced in #37643.
=> [docs-infra] Fix emotion :first-child console log

package.json, yarn.lock
Closes #38660
Looks like the webpack types are not used anywhere. It was initially added in #22720.
=> [core] Remove unnecessary `@types/webpack` package

packages/mui-lab/src/LoadingButton/LoadingButton.js
The issue can be seen on https://validator.w3.org/nu/?doc=https%3A%2F%2Fmui.com%2Fmaterial-ui%2Freact-button%2F
While I don't know how useful validator.w3 is, I don't think Material UI component should create noise for developers.
Preview: https://deploy-preview-38584--material-ui.netlify.app/material-ui/react-button/.
I have checked if the bug could be reproduced on Joy UI at the same time, it can't, we use span correctly there.
---
*This has been on [my backlog](https://www.notion.so/mui-org/Win-Product-opportunities-408a9771556a4715830d18f3749af753) for almost 2 years. I moved most of the items to Notion tasks, but this one seems so simple to fix that I'm going for it.*
I saw two CSS bugs on this page with Material UI v6 https://mui.com/material-ui/react-button/#material-you-version: …
=> [LoadingButton] Fix HTML rule button > div forbidden nesting

docs/data/material/components/autocomplete/autocomplete.md
Explained that the Autocomplete's `value` should be referentially stable between renders.
Closes #35533
=> [docs][Autocomplete] Require referentially stable value

packages/mui-system/src/Box/Box.test.js, packages/mui-system/src/sizing.js, packages/mui-system/src/sizing.test.js, packages/mui-system/src/styleFunctionSx/styleFunctionSx.test.js
Fixes https://github.com/mui/material-ui/issues/38594
Here's a sandbox showing the fix: https://codesandbox.io/s/https-github-com-mui-material-ui-pull-38633-6ry8rx?file=/src/App.tsx
=> [system] Fix maxWidth incorrectly resolving breakpoints with non-pixel units

docs/data/material/guides/routing/routing.md
Previously Pages router section was redirecting to `app-router` example, this PR fixes it
preview: https://deploy-preview-38750--material-ui.netlify.app/material-ui/guides/routing/#next-js-pages-router
=> [docs] Fix Next.js pages router example redirect link

docs/data/material/components/material-icons/SearchIcons.js, docs/pages/_app.js, docs/pages/_document.js, docs/src/modules/components/Ad.js, docs/src/modules/components/GoogleAnalytics.js
To merge only after July 1, 2023.
Remove the call to UA when Google will drop its support: https://support.google.com/analytics/answer/9964640.
See https://www.notion.so/Migrate-to-Google-Analytics-v4-8a38a284e9d04507a5d6f108dc72829c for more details.
Preview: https://deploy-preview-37579--material-ui.netlify.app/material-ui/react-alert/
=> [docs-infra] Remove legacy GA

docs/scripts/pages/playground/index.tsx, packages/mui-material/src/ImageListItem/ImageListItem.js
Closes: https://github.com/mui/material-ui/issues/38341#issuecomment-1688064003
=> ImageItemList fix incorrect (below) rendering

docs/data/material/components/transitions/SimpleCollapse.js, docs/data/material/components/transitions/SimpleCollapse.tsx, docs/data/material/components/transitions/SimpleFade.js, docs/data/material/components/transitions/SimpleFade.tsx, docs/data/material/components/transitions/SimpleGrow.js, docs/data/material/components/transitions/SimpleGrow.tsx, docs/data/material/components/transitions/SimpleSlide.js, docs/data/material/components/transitions/SimpleSlide.tsx, docs/data/material/components/transitions/SimpleSlide.tsx.preview, docs/data/material/components/transitions/SimpleZoom.js, docs/data/material/components/transitions/SimpleZoom.tsx, docs/data/material/components/transitions/SlideFromContainer.js, docs/data/material/components/transitions/SlideFromContainer.tsx, docs/data/material/components/transitions/SlideFromContainer.tsx.preview, docs/data/material/components/transitions/TransitionGroupExample.js, docs/data/material/components/transitions/TransitionGroupExample.tsx, docs/data/material/components/transitions/TransitionGroupExample.tsx.preview, docs/data/material/components/transitions/transitions.md
Seeing the change to the online preview in #38646: https://github.com/mui/material-ui/pull/38646/files#diff-abc20b07c6893afa34e4fc5d939e3ab2cae95855b4585748bee4bf3822e0cd6b 
triggered me to have a quick look at improving the demos in the page.
---
Preview: https://deploy-preview-38759--material-ui.netlify.app/material-ui/transitions/#slide
=> [docs] Polish Slider demos

docs/src/modules/sandbox/CodeSandbox.test.js, docs/src/modules/sandbox/CreateReactApp.ts, docs/src/modules/sandbox/StackBlitz.test.js
I noticed in #38684. It's annoying for the codesandbox demo created to be broken on mobile.
Reproduction https://mui.com/material-ui/react-alert/#basic-alerts
https://github.com/mui/material-ui/assets/3165635/b074906a-fc83-42ce-a5f4-ee51d0cf94b3
=> [docs-infra] Fix mobile display in CodeSandbox

docs/data/joy/components/autocomplete/GitHubLabel.tsx, docs/data/material/components/autocomplete/GitHubLabel.tsx, packages/mui-base/src/useAutocomplete/useAutocomplete.d.ts, packages/mui-base/src/useAutocomplete/useAutocomplete.spec.ts, packages/mui-material/src/Autocomplete/Autocomplete.spec.tsx
There is no reason to mutate the array once passed as a prop or when sending it to onChange.
=> [Autocomplete] Type multiple values with readonly arrays.

docs/data/base/components/menu/MenuIntroduction/css/index.js, docs/data/base/components/menu/MenuIntroduction/css/index.tsx, docs/data/base/components/menu/MenuIntroduction/system/index.js, docs/data/base/components/menu/MenuIntroduction/system/index.tsx, docs/data/base/components/menu/MenuIntroduction/system/index.tsx.preview, docs/data/base/components/menu/MenuIntroduction/tailwind/index.js, docs/data/base/components/menu/MenuIntroduction/tailwind/index.tsx, docs/data/base/components/menu/MenuIntroduction/tailwind/index.tsx.preview, docs/data/base/components/menu/MenuSimple/tailwind/index.js, docs/data/base/components/menu/MenuSimple/tailwind/index.tsx, docs/data/base/components/menu/MenuSimple/tailwind/index.tsx.preview, docs/data/base/components/menu/menu.md
Part of https://github.com/mui/material-ui/issues/37222
=> [docs][base] Add Tailwind CSS + plain CSS demo on the Menu page

docs/src/modules/components/DemoEditor.tsx, packages/mui-base/src/Popper/Popper.tsx, packages/mui-base/src/Select/Select.tsx, packages/mui-base/src/useMenu/useMenu.ts, packages/mui-base/src/useSelect/useSelect.ts, packages/mui-joy/src/Button/Button.tsx, packages/mui-joy/src/Chip/Chip.tsx, packages/mui-joy/src/ChipDelete/ChipDelete.tsx, packages/mui-joy/src/FormHelperText/FormHelperText.tsx, packages/mui-joy/src/IconButton/IconButton.tsx, packages/mui-joy/src/ListItemButton/ListItemButton.tsx, packages/mui-joy/src/Select/Select.tsx
Before
After
See for why https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/v17/index.d.ts#L1040
The difference is that:
```tsx
interface RefObject<T> {
readonly current: T | null;
}
interface MutableRefObject<T> {
current: T;
}
```
Does it matter? Probably not, but it seems to be closer to how the API is supposed to be used.
=> [core] Use immutable refs

docs/data/base/guides/next-js-app-router/next-js-app-router.md, docs/data/joy/integrations/next-js-app-router/next-js-app-router.md, docs/data/material/guides/next-js-app-router/next-js-app-router.md, examples/base-ui-nextjs-tailwind-ts/src/app/components.tsx
=> [docs] Fix broken links to Next.js docs

packages/mui-joy/src/Typography/Typography.tsx, packages/mui-joy/src/Typography/TypographyProps.ts, test/regressions/fixtures/LinkJoy/LinkCard.js
close #38701, added [regression test](https://app.argos-ci.com/mui/material-ui/builds/17807/57122991) to prevent the bug in the future.
=> [Typography] Added position only when Skeleton is a direct child

packages/mui-lab/package.json, packages/mui-lab/src/themeAugmentation/index.d.ts, yarn.lock
=> [lab] Fix `@mui/x-tree-view` dependency

docs/data/base/components/table-pagination/TableCustomized/css/index.js, docs/data/base/components/table-pagination/TableCustomized/css/index.tsx, docs/data/base/components/table-pagination/TableCustomized/system/index.js, docs/data/base/components/table-pagination/TableCustomized/system/index.tsx, docs/data/base/components/table-pagination/TableCustomized/tailwind/index.js, docs/data/base/components/table-pagination/TableCustomized/tailwind/index.tsx, docs/data/base/components/table-pagination/TableUnstyled.js, docs/data/base/components/table-pagination/TableUnstyled.tsx, docs/data/joy/components/table/TableSortAndSelection.js, docs/data/joy/components/table/TableSortAndSelection.tsx
During work on #36287, the dependencies got updated, and ESLint started showing errors in some of the table demos. I couldn't pinpoint which dependency was responsible for this, but it's not super important. The issue was that some of the table cells (used to fill empty space) did not have an accessible label. I fixed it by making them invisible to assistive technologies (as they are just for presentation).
=> [docs] Fix a11y issues in tables demos

docs/data/material/experimental-api/css-theme-variables/usage.md, docs/data/system/experimental-api/css-theme-variables/css-theme-variables.md
This was removed in #34639 but we didn't update the docs.
=> [docs] enableColorScheme prop was removed

docs/pages/blog/lab-tree-view-to-mui-x.md, packages/mui-lab/src/AdapterDateFns/AdapterDateFns.ts, packages/mui-lab/src/AdapterDayjs/AdapterDayjs.ts, packages/mui-lab/src/AdapterLuxon/AdapterLuxon.ts, packages/mui-lab/src/AdapterMoment/AdapterMoment.ts, packages/mui-lab/src/CalendarPicker/CalendarPicker.tsx, packages/mui-lab/src/CalendarPickerSkeleton/CalendarPickerSkeleton.tsx, packages/mui-lab/src/ClockPicker/ClockPicker.tsx, packages/mui-lab/src/DateRangePicker/DateRangePicker.ts, packages/mui-lab/src/DateRangePickerDay/DateRangePickerDay.ts, packages/mui-lab/src/DateTimePicker/DateTimePicker.tsx, packages/mui-lab/src/DesktopDatePicker/DesktopDatePicker.tsx, packages/mui-lab/src/DesktopDateRangePicker/DesktopDateRangePicker.ts, packages/mui-lab/src/DesktopDateTimePicker/DesktopDateTimePicker.tsx, packages/mui-lab/src/DesktopTimePicker/DesktopTimePicker.tsx, packages/mui-lab/src/LocalizationProvider/LocalizationProvider.tsx, packages/mui-lab/src/MobileDatePicker/MobileDatePicker.tsx, packages/mui-lab/src/MobileDateRangePicker/MobileDateRangePicker.ts, packages/mui-lab/src/MobileDateTimePicker/MobileDateTimePicker.tsx, packages/mui-lab/src/MobileTimePicker/MobileTimePicker.tsx, packages/mui-lab/src/MonthPicker/MonthPicker.tsx, packages/mui-lab/src/PickersDay/PickersDay.tsx, packages/mui-lab/src/StaticDatePicker/StaticDatePicker.tsx, packages/mui-lab/src/StaticDateRangePicker/StaticDateRangePicker.ts, packages/mui-lab/src/StaticDateTimePicker/StaticDateTimePicker.tsx, packages/mui-lab/src/StaticTimePicker/StaticTimePicker.tsx, packages/mui-lab/src/TimePicker/TimePicker.tsx, packages/mui-lab/src/TreeItem/TreeItem.tsx, packages/mui-lab/src/TreeView/TreeView.tsx, packages/mui-lab/src/YearPicker/YearPicker.tsx
A quick iteration on https://twitter.com/olivtassinari/status/1699416950680481934, to get this DX:
=> [lab] Add TypeScript deprecations

packages/mui-base/CONTRIBUTING.md, packages/mui-base/README.md
Technical documentation for authoring Base UI hooks.
=> [base-ui] Create hooks contribution guide

packages/mui-base/src/FocusTrap/FocusTrap.tsx, test/e2e/fixtures/FocusTrap/DisableEnforceFocusFocusTrap.tsx, test/e2e/index.test.ts
Codesandbox with the broken demo from https://github.com/mui/material-ui/pull/38684: https://codesandbox.io/s/condescending-dan-xmxsxw?file=/Demo.tsx
Fixes https://github.com/mui/material-ui/issues/21569
Before: https://mui.com/base-ui/react-focus-trap/#disable-enforced-focus
After: https://deploy-preview-38816--material-ui.netlify.app/base-ui/react-focus-trap/#disable-enforced-focus
=> [FocusTrap] Fix `disableEnforceFocus` behavior

.circleci/config.yml
Closes https://github.com/mui/material-ui/pull/38776
Deals with the [breaking change](https://github.com/CircleCI-Public/aws-cli-orb/issues/156) in https://github.com/CircleCI-Public/aws-cli-orb/pull/142 (@DiegoAndai Thank you for finding this!)
The parameters have changed from being [`env_var_name`](https://github.com/CircleCI-Public/aws-cli-orb/pull/142/files#diff-ef7a96e661fedfb5b86d2744c2de99e78c53bab5a21687af2bff94b048abe171L54) to `string`. `region` apparently already was a string, but quietly accepted the var name even though as a region it's invalid. changing them to `$VAR_NAME` or `${VAR_NAME}` correctly interpolates them again.
=> [core] Bump aws-cli orb to 4.1

packages/mui-material/src/Modal/Modal.js, packages/mui-material/src/Modal/Modal.test.js
closes: https://github.com/mui/material-ui/issues/38843
before: https://codesandbox.io/s/mui-swipabledrawer-example-new-7pnch2
after: https://codesandbox.io/s/affectionate-hooks-vwlqrk
`Base` `Modal`  extracted `onTransitionEntered`, `onTransitionExited` [here](https://github.com/mui/material-ui/blob/master/packages/mui-base/src/Modal/Modal.tsx#L67)  from `props` before passing to useSlotProps [here](https://github.com/mui/material-ui/blob/master/packages/mui-base/src/Modal/Modal.tsx#L128). That's why same error didn't occured in `BaseUI` `Modal`. This PR follows same implemetation as `BaseUI`  `Modal` to fix the warning
=> [Modal][material] Fix console warning when onTransitionEnter , onTransitionExit provided

packages/mui-base/package.json, packages/mui-joy/package.json, packages/mui-material-next/package.json, packages/mui-material/package.json, packages/mui-private-theming/package.json, packages/mui-styled-engine/package.json, packages/mui-utils/package.json
When looking at https://www.npmjs.com/package/next, https://www.npmjs.com/package/react, the homepage points you to the homepage of each project so I think we could do the same.
e.g. https://www.npmjs.com/package/@mui/joy, so strange:
I noticed this from https://github.com/ericdiviney/react-handbook/pull/89.
=> [docs] Clearer npm package homepages

docs/data/joy/components/autocomplete/GitHubLabel.tsx, docs/data/material/components/autocomplete/GitHubLabel.tsx, packages/mui-base/src/useAutocomplete/useAutocomplete.d.ts, packages/mui-base/src/useAutocomplete/useAutocomplete.spec.ts, packages/mui-material/src/Autocomplete/Autocomplete.spec.tsx
Reverts mui/material-ui#38253, see https://github.com/mui/material-ui/issues/38817.
Next actions should be:
- move the current `useAutocomplete` in Material UI
- iterate on the `useAutocomplete` in Base UI - test the changes in Joy UI
- in v6, migrate Material UI's `Autocomplete` to use the Base UI's `useAutocomplete`
=> Revert "[Autocomplete] Type multiple values with readonly arrays."

packages/mui-system/src/cssVars/getInitColorSchemeScript.tsx
When you look at the source of the page:
Before: view-source:https://mui.com/
After: view-source:https://deploy-preview-38794--material-ui.netlify.app/
it's easier to understand.
=> [system] Remove getInitColorSchemeScript leading spaces

docs/data/material/guides/minimizing-bundle-size/minimizing-bundle-size.md
Noticed in https://github.com/mui/material-ui/pull/38742#issuecomment-1701792594.
Before: https://mui.com/material-ui/guides/minimizing-bundle-size/#available-bundles
After: https://deploy-preview-38747--material-ui.netlify.app/material-ui/guides/minimizing-bundle-size/#available-bundles
=> [docs] Fix use of callouts

docs/.link-check-errors.txt, docs/pages/blog/first-look-at-joy.md, docs/scripts/reportBrokenLinks.js, packages/markdown/parseMarkdown.js, packages/markdown/prepareMarkdown.test.js
A succession of problems led to me breaking master (a71e6a07b80a230c302e687f6034b29eac3347f0 broke the CI on master). 
1. `yarn docs:link-check` outputted `/joy-ui/integrations/material-ui/` in material-ui/docs/.link-check-errors.txt, it should have been `/joy-ui/integrations/material-ui//`. In #38396 it would have made it clearer that we were introducing double trailing slashes. The root problem IMHO is that when we compare URLs we should compare their final version. So in this PR, I make sure we compare the URL with trailing slashes.
2. In #38396 we shouldn't have been able to get the CI pass with https://github.com/mui/material-ui/pull/38396#discussion_r1312360728. I'm introducing a new error. https://help.ahrefs.com/en/articles/2596665-double-slash-in-url-error-in-site-audit
~A side …
=> [docs-infra] Catch duplicated trailing splashes in links

packages/mui-base/src/FocusTrap/FocusTrap.tsx
Things done in the PR:
- moved the `contain` function back in the `useEffect`
- remove the usage of the `nativeEvent` - the reason for adding this event handler was to check if the focus was invoked with different target based on https://github.com/mui/material-ui/pull/21610#discussion_r448234190, but there can never be a difference between the `focusin`'s `event.target` element and the `document.activeElement` - and this check is already captured in the second part of the condition (I was testing the scenario that was shared in that reproduction and it still works as expected, and all tests pass too), so everything should be fine.
=> [FocusTrap] Refactor & cleanup

docs/pages/base-ui/api/use-input.json, packages/mui-base/src/useInput/useInput.test.tsx, packages/mui-base/src/useInput/useInput.ts, packages/mui-base/src/useInput/useInput.types.ts
`getRootProps` and `getInputProps` are already forwarding external props, this PR just aligns the naming
=> [base-ui][useInput] Align ExternalProps naming

docs/data/joy/integrations/next-js-app-router/next-js-app-router.md, docs/data/material/guides/next-js-app-router/next-js-app-router.md, docs/pages/experiments/docs/callouts.md, docs/src/modules/components/MarkdownElement.js
https://master--material-ui.netlify.app/material-ui/guides/next-js-app-router/#props-serialization
https://deploy-preview-38880--material-ui.netlify.app/material-ui/guides/next-js-app-router/#props-serialization
=> [docs–infra] Fix callout container width

docs/src/modules/components/DemoToolbar.js
Closes https://github.com/mui/material-ui/issues/38722
This PR is another iteration of improving the affordance of the "Show code" buttons on the demo's toolbar. The above-linked issue came from a community contributor saying how the recent change from the `<>` icon button to the gray labeled button made it confusing to understand that it was clickable. Here, we're adding a slight border and also turning the label blue to really indicate that's an action visitors can take. Hopefully, this will kick the amount of events this action was triggering back up and improve the UX.
Examples below:
- **https://deploy-preview-38824--material-ui.netlify.app/base-ui/react-button/#introduction**
- **https://deploy-preview-38824--material-ui.netlify.app/joy-ui/getting-started/tutorial/#interactive-demo** …
=> [docs-infra] Improve show code button affordance

docs/pages/base-ui/api/use-snackbar.json, packages/mui-base/src/useSnackbar/useSnackbar.test.tsx, packages/mui-base/src/useSnackbar/useSnackbar.ts, packages/mui-base/src/useSnackbar/useSnackbar.types.ts
This PR aligns the typing and handling of external props and event handlers
=> [base-ui][useSnackbar] Align externalProps handling

packages/mui-base/package.json, packages/mui-styled-engine-sc/package.json, packages/mui-styled-engine/package.json, packages/mui-styles/package.json, packages/mui-system/package.json, packages/mui-types/package.json
In https://github.com/mui/material-ui/pull/38859, dependencies were explicitly added to packages. Some declared themselves as a dependency. `lerna` does not update these versions, causing mismatches. For example from the [v5.14.9 release PR](https://github.com/mui/material-ui/pull/38920), after update `@mui/base` ended up with ["version": "5.0.0-beta.15"](https://github.com/mui/material-ui/blob/7d4e5e7ee71e20b1fddad78e6a77406855ea5b7b/packages/mui-base/package.json#L3) and ["@mui/base": "5.0.0-beta.14"](https://github.com/mui/material-ui/blob/7d4e5e7ee71e20b1fddad78e6a77406855ea5b7b/packages/mui-base/package.json#L53) as a dependency.
=> [core] Remove package declaration from same package dependencies

docs/data/base/components/autocomplete/AutocompleteIntroduction/system/index.js, docs/data/base/components/autocomplete/AutocompleteIntroduction/system/index.tsx, docs/data/base/components/autocomplete/AutocompleteIntroduction/tailwind/index.js, docs/data/base/components/autocomplete/AutocompleteIntroduction/tailwind/index.tsx, docs/pages/base-ui/api/use-autocomplete.json, packages/mui-base/src/useAutocomplete/useAutocomplete.d.ts
The type of the UseAutocompleteReturnValue.getInputProps (in packages\mui-base\src\useAutocomplete\useAutocomplete.d.ts) needed to be extended and include the ref: React.Ref<HTMLInputElement> field.
Closes #36552
=> [Autocomplete][base-ui] Added ref to getInputProps return value

packages/mui-styled-engine-sc/package.json, packages/mui-styled-engine/package.json
React has been added to @mui/styled-engine and @mui/styled-engine-sc dependencies by mistake. It should be a devDependency.
=> [core] Remove react from styled-engine dependencies

packages/mui-utils/package.json
react-dom has been mistakenly added to @mui/utils' peerDependencies, even though it's used only in test and should remain in devDependencies only.
Fixes #38961
=> [core] Remove react-dom from @mui/utils peerDependencies

packages/mui-base/src/unstable_useNumberInput/useNumberInput.test.tsx, packages/mui-base/src/unstable_useNumberInput/useNumberInput.ts
closes: https://github.com/mui/material-ui/issues/38513
=> [NumberInput][base-ui] Warn when changing control mode with `useControlled` 

docs/src/modules/components/PropertiesTable.js, docs/src/pages/production-error/ErrorDecoder.js, docs/translations/api-docs-base/slider/slider.json, docs/translations/api-docs-joy/chip-delete/chip-delete.json, docs/translations/api-docs-joy/slider/slider.json, docs/translations/api-docs/autocomplete/autocomplete.json, docs/translations/api-docs/slider/slider.json, docs/translations/api-docs/tabs/tabs.json, docs/translations/api-docs/use-autocomplete/use-autocomplete.json, docs/translations/api-docs/use-dropdown/use-dropdown.json, docs/translations/api-docs/use-input/use-input.json, docs/translations/api-docs/use-menu/use-menu.json, docs/translations/api-docs/use-modal/use-modal.json, docs/translations/api-docs/use-number-input/use-number-input.json, docs/translations/api-docs/use-select/use-select.json, docs/translations/api-docs/use-slider/use-slider.json, docs/translations/api-docs/use-snackbar/use-snackbar.json, docs/translations/api-docs/use-tab/use-tab.json, docs/translations/api-docs/use-tabs-list/use-tabs-list.json, docs/translations/api-docs/use-tabs/use-tabs.json, packages/api-docs-builder/ApiBuilders/ComponentApiBuilder.ts, packages/api-docs-builder/ApiBuilders/HookApiBuilder.ts, packages/api-docs-builder/utils/generatePropDescription.ts, packages/markdown/index.d.ts, packages/markdown/index.js, packages/markdown/parseMarkdown.js, packages/markdown/parseMarkdown.test.js, packages/mui-material/src/Tabs/Tabs.d.ts, packages/mui-material/src/Tabs/Tabs.js
**Previews:**
Before: https://mui.com/base-ui/react-slider/components-api/#Slider-prop-track
After: https://deploy-preview-38973--material-ui.netlify.app/base-ui/react-slider/components-api/#Slider-prop-track
Before: https://mui.com/joy-ui/api/chip-delete/#ChipDelete-prop-onDelete
After: https://deploy-preview-38973--material-ui.netlify.app/joy-ui/api/chip-delete/#ChipDelete-prop-onDelete
Before: https://mui.com/joy-ui/api/slider/#Slider-prop-track
After: https://deploy-preview-38973--material-ui.netlify.app/joy-ui/api/slider/#Slider-prop-track
Before: https://mui.com/joy-ui/api/slider/#Slider-prop-valueLabelDisplay
After: https://deploy-preview-38973--material-ui.netlify.app/joy-ui/api/slider/#Slider-prop-valueLabelDisplay
Before: …
=> [docs-infra] Display markdown lists correctly in docs for props description

packages/mui-base/src/useList/useList.test.tsx, packages/mui-base/src/useList/useList.ts, packages/mui-base/src/useList/useList.types.ts, packages/mui-base/src/useList/useListItem.ts, packages/mui-base/src/useList/useListItem.types.ts
`getRootProps` of `useList` and `useListItem` already forwards external props, this PR just aligns the naming
=> [base-ui][useList] Accept arbitrary external props and forward to root

test/regressions/index.js
=> [docs] Exclude joy-ui LinearProgressCountup from visual regression

packages/api-docs-builder/buildApi.ts, packages/mui-joy/src/GlobalStyles/GlobalStyles.tsx, packages/mui-joy/src/GlobalStyles/index.tsx
Closes #38494 
In this pull request, I made the following changes:
1. Created a new file, `GlobalStyles.tsx`, in the `packages/mui-joy/src/GlobalStyles` folder.
2. Modified the `packages/mui-joy/src/GlobalStyles/index.tsx` file to export the `GlobalStyles`.
3. Ran the script `yarn rsc:build` to insert the `use client` directive into the `GlobalStyles.tsx` file.
I followed the guidance provided by @siriwatknp in the following comment: https://github.com/mui/material-ui/issues/38494#issuecomment-1714903097.
---
=> [joy-ui][GlobalStyles] Ensure compatibility with RSC

docs/src/components/action/InfoCard.tsx, docs/src/components/home/ValueProposition.tsx, docs/src/components/productBaseUI/BaseUISummary.tsx, docs/src/components/productDesignKit/DesignKitValues.tsx, docs/src/modules/brandingTheme.ts
This PR adds a new component to the website's (i.e., marketing pages) set of action components: the `InfoCard`. It's been a while that I'm feeling like there were just too many repeating instances of these same styles... and given I have some upcoming usages of it already lined up in other PRs, it seemed like a good call to finally do this! 😬 
These are the `InfoCard`s: 
So far available on: 
- **https://deploy-preview-38987--material-ui.netlify.app/**
- **https://deploy-preview-38987--material-ui.netlify.app/base-ui**
- **https://deploy-preview-38987--material-ui.netlify.app/design-kits**
=> [website] Create the `InfoCard` component

docs/pages/joy-ui/api/accordion-group.json, packages/mui-joy/src/AccordionGroup/AccordionGroup.test.tsx, packages/mui-joy/src/AccordionGroup/AccordionGroup.tsx
closes: https://github.com/mui/material-ui/issues/38688
resolves: https://github.com/mui/material-ui/issues/38688#issuecomment-1714884725 comment
=> [joy-ui][AccordionGroup] Fix console warning when using custom color

packages/mui-utils/package.json
=> [utils] Move @types/prop-types back to dependencies

packages/eslint-plugin-material-ui/package.json
eslint-plugin-material-ui should use the existing eslint, not bundle it on its own (as noted in https://github.com/mui/material-ui/pull/38859#discussion_r1325512165).
=> [core] Move eslint to peer dependencies of eslint-plugin-material-ui

docs/src/modules/components/DemoErrorBoundary.js
I have seen enough of it https://github.com/mui/mui-x/issues?q=is%3Aissue+demo+crashes+is%3Aclosed+
I'm stepping in 😁, transferring issues takes time, so let's have developers open the issue in the right repository instead.
I changed a bit the UI as well, it looks like this:
=> [docs-infra] Open demo crash in the right repository

docs/data/joy/components/autocomplete/Asynchronous.js, docs/data/joy/components/autocomplete/Asynchronous.tsx, docs/data/material/components/autocomplete/Asynchronous.js, docs/data/material/components/autocomplete/Asynchronous.tsx, packages/mui-base/src/TextareaAutosize/TextareaAutosize.test.tsx, packages/mui-base/src/TextareaAutosize/TextareaAutosize.tsx, packages/mui-lab/src/Masonry/Masonry.js, packages/waterfall/sleep.mjs, test/bundling/fixtures/create-react-app/testCreateReactAppIntegration.js, test/bundling/fixtures/esbuild/testEsbuildIntegration.js, test/bundling/fixtures/gatsby/testGatsbyIntegration.js, test/bundling/fixtures/next-webpack4/testNextWebpack4Integration.js, test/bundling/fixtures/next-webpack5/testNextWebpack5Integration.js, test/bundling/fixtures/snowpack/testSnowpackIntegration.js, test/bundling/fixtures/vite/testViteIntegration.js, test/e2e/index.test.ts
A quick continuation of #37135. I was triggered because I saw 3 PRs that fix bugs without tests on the same component:
1. https://github.com/mui/material-ui/pull/33238.
2. https://github.com/mui/material-ui/pull/33253
3. https://github.com/mui/material-ui/pull/37135. I have tried to add tests on this one, but the problem is that in Karma, the browser gets confused, It triggers `ResizeObserver loop completed with undelivered notifications` but it's an hallucination https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver#observation_errors. More details in https://github.com/WICG/resize-observer/issues/38, also faced in https://github.com/mui/mui-x/issues/8733.
I'm also removing these `if (inputRef.current) {` defensive checks. Sebastian was asking the right question in …
=> [TextareaAutosize] Simplify logic and add test

docs/data/material/experimental-api/css-theme-variables/overview.md, docs/data/material/experimental-api/css-theme-variables/usage/CssVarsBasic.js, docs/data/material/experimental-api/css-theme-variables/usage/CssVarsBasic.tsx, docs/data/material/experimental-api/css-theme-variables/usage/CssVarsBasic.tsx.preview, docs/data/material/experimental-api/css-theme-variables/usage/usage.md, docs/data/system/experimental-api/css-theme-variables/css-theme-variables.md, docs/pages/material-ui/experimental-api/css-theme-variables/usage.js, packages/mui-system/src/cssVars/createCssVarsProvider.js
I never understood why we didn't have a live demo with CssVarsProvider for Material UI. I have struggled to make this one, I struggled on a couple of points (e.g. tried to use createTheme, tried to use `prefix`, I didn't know where to import extendTheme from).
Use case: https://github.com/mui/mui-x/pull/10214
Preview: https://deploy-preview-38792--material-ui.netlify.app/material-ui/experimental-api/css-theme-variables/usage/#getting-started
Regarding the CSS size, the CSS variables added to the HTML docs adds 4 kB gzipped. It doesn't seem to really impact performance: https://www.webpagetest.org/video/compare.php?tests=230903_BiDcR6_A0Z,230903_AiDcV1_A8W.
---
The dark/light mode switch is broken, but it's beyond this PR. We need to fix this as well to fully migrate our docs to use CSS …
=> [docs] Add live demo with CssVarsProvider

docs/pages/base-ui/api/use-option.json, docs/pages/base-ui/api/use-select.json, docs/translations/api-docs/use-option/use-option.json, packages/mui-base/src/useOption/useOption.ts, packages/mui-base/src/useOption/useOption.types.ts, packages/mui-base/src/useSelect/useSelect.ts, packages/mui-base/src/useSelect/useSelect.types.ts
This PR aligns the typing/handling of external props for `useSelect` and `useOption` and adds some simple tests
=> [base-ui][useSelect][useOption] Align external props handling

docs/pages/base-ui/api/use-menu-button.json, docs/pages/base-ui/api/use-menu-item.json, docs/pages/base-ui/api/use-menu.json, packages/mui-base/src/useMenu/useMenu.test.js, packages/mui-base/src/useMenu/useMenu.ts, packages/mui-base/src/useMenu/useMenu.types.ts, packages/mui-base/src/useMenuButton/useMenuButton.test.tsx, packages/mui-base/src/useMenuButton/useMenuButton.ts, packages/mui-base/src/useMenuButton/useMenuButton.types.ts, packages/mui-base/src/useMenuItem/useMenuItem.test.tsx, packages/mui-base/src/useMenuItem/useMenuItem.ts, packages/mui-base/src/useMenuItem/useMenuItem.types.ts
This PR aligns the typing/handling of external props for `useMenu`, `useMenuButton` and `useMenuItem`, and adds some simple tests
=> [base-ui][useMenu] Align external props handling for useMenu/MenuButton/MenuItem

renovate.json
Include `@types/babel*` packages in the Renovate's Babel group to limit the number of dependency PRs.
=> [core] Update Babel types along with source packages

packages/mui-material-next/src/FormControl/FormControl.d.ts, packages/mui-material-next/src/FormControl/FormControl.js, packages/mui-material-next/src/FormControl/FormControl.test.js, packages/mui-material-next/src/FormControl/FormControlContext.ts, packages/mui-material-next/src/FormControl/formControlClasses.ts, packages/mui-material-next/src/FormControl/formControlState.js, packages/mui-material-next/src/FormControl/index.d.ts, packages/mui-material-next/src/FormControl/index.js, packages/mui-material-next/src/FormControl/useFormControl.ts, packages/mui-material-next/src/index.ts
Part of https://github.com/mui/material-ui/issues/38411, https://github.com/mui/material-ui/issues/29345
This PR copies `FormControl` from `mui-material` to `mui-material-next` with minimal modification (e.g. import paths, just enough to pass CI) so it's easier to see the diffs in [the PR](https://github.com/mui/material-ui/pull/39032) containing the actual code changes
=> [FormControl][material-next] Copy v5 FormControl

docs/data/joy/components/button/ButtonIcons.js, docs/data/joy/components/button/ButtonIcons.tsx, docs/data/joy/components/button/ButtonIcons.tsx.preview, docs/data/joy/components/button/ButtonLoadingIndicator.js, docs/data/joy/components/button/ButtonLoadingIndicator.tsx, docs/data/joy/components/button/ButtonLoadingIndicator.tsx.preview, docs/data/joy/components/button/ButtonLoadingPosition.js, docs/data/joy/components/button/ButtonLoadingPosition.tsx, docs/data/joy/components/button/ButtonLoadingPosition.tsx.preview
Following a recent docs-feedback entry, this PR removes an unnecessary icon import from the Joy UI Button loading indicator demo.
**https://deploy-preview-39082--material-ui.netlify.app/joy-ui/react-button/#loading-indicator**
=> [docs][joy-ui] Simplify the button's loading indicator demo

docs/data/joy/customization/default-theme-viewer/default-theme-viewer.md, docs/data/material/customization/default-theme/DefaultTheme.js, docs/data/material/customization/default-theme/default-theme.md, docs/pages/joy-ui/customization/default-theme-viewer.js, docs/pages/material-ui/customization/default-theme.js, docs/src/modules/components/ThemeViewer.tsx
This PR adds a small uplift on the default viewer page design: tweaked the Tree View a bit and the page formatting (e.g., removing the table of contents)(both the Material UI & Joy Ui pages). It's been bothering me for a while that this very useful resource wasn't fitting in well with the docs current visuals... so, finally put in some time to polish it up a bit.
- **https://deploy-preview-39049--material-ui.netlify.app/material-ui/customization/default-theme/**
- **https://deploy-preview-39049--material-ui.netlify.app/joy-ui/customization/default-theme-viewer/**
| <img width="883" alt="Screen Shot 2023-09-18 at 21 17 24" src="https://github.com/mui/material-ui/assets/67129314/85de7fa7-74a3-4a5a-845d-e2c1ac2dd134"> | <img width="1013" alt="Screen …
=> [docs] Improve the default theme viewer design

docs/data/joy/components/menu/MenuListComposition.js, docs/data/joy/components/menu/MenuListComposition.tsx, docs/src/components/action/Highlighter.tsx, docs/src/components/action/More.tsx, docs/src/components/header/HeaderNavBar.tsx, docs/src/components/header/HeaderNavDropdown.tsx, docs/src/components/home/ElementPointer.tsx, docs/src/layouts/HeroContainer.tsx, examples/joy-ui-vite-ts/src/main.tsx, examples/material-ui-vite-ts/src/main.tsx, packages/mui-base/src/FocusTrap/FocusTrap.tsx, packages/mui-base/src/unstable_useModal/useModal.ts, packages/mui-base/src/useSelect/useSelect.ts, packages/mui-joy/src/Modal/Modal.test.tsx
A continuation of #38762.
Also, better to use https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#non-null-assertion-operator-postfix- to remove null from the type than to reassign the whole type.
=> [core] Improve ref type definition

docs/data/base/components/focus-trap/BasicFocusTrap.js, docs/data/base/components/focus-trap/BasicFocusTrap.tsx, docs/data/base/components/focus-trap/DisableEnforceFocus.js, docs/data/base/components/focus-trap/DisableEnforceFocus.tsx, docs/data/base/components/focus-trap/LazyFocusTrap.js, docs/data/base/components/focus-trap/LazyFocusTrap.tsx, docs/data/base/components/focus-trap/PortalFocusTrap.js, docs/data/base/components/focus-trap/PortalFocusTrap.tsx
Something that I noticed during the review of #38878. It was hard to spot that the focus moved to the container.
https://github.com/mui/material-ui/assets/3165635/c3061ef0-e64f-4460-ae7f-96ed58c710d6
https://deploy-preview-38985--material-ui.netlify.app/base-ui/react-focus-trap/
=> [docs][base-ui] Improve focus trap demo

.gitignore, docs/src/modules/components/AppLayoutDocsFooter.js, netlify/functions/feedback-management.js
The goal is to add actions directly into messages, such that with a single click, you can:
- delete useless messages -> will be saved to see later if there is some pattern
- open an issue
- save it in a sheet (if the message is insightful but is not something to fix)
=> [core] Simplify docs feedback interaction

docs/src/components/pricing/PricingTable.tsx
This PR fixes the row hover on dark mode, which was displaying a much lighter color than it should!
**https://deploy-preview-39097--material-ui.netlify.app/pricing/**
=> [website] Fix Pricing page row hover

package.json, yarn.lock
Lerna 7.3.0 throws an error when running `yarn release:version`. It's not very helpful:
```
lerna ERR! ERROR Not all tasks were run. This is likely a bug in Lerna.
```
In 7.2.0 everything works as expected.
=> [core] Downgrade lerna to 7.2.0

docs/src/components/action/Highlighter.tsx, docs/src/components/action/More.tsx
This PR adds some slight color tweaks to the Highlighter website component, aiming to improve it, especially in dark mode.
**https://deploy-preview-39087--material-ui.netlify.app/material-ui/**
=> [website] Improve the highlighter component colors

docs/pages/experiments/docs/callouts.md, docs/src/modules/components/ApiPage.js, docs/src/modules/components/ApiPage/ApiItem.tsx, docs/src/modules/components/MarkdownElement.js
Closes https://github.com/mui/material-ui/issues/39066
This PR tackles the issue above and adds other stray color/element fixes mostly within the callout scope.
**https://deploy-preview-39084--material-ui.netlify.app/material-ui/api/button-base/#ButtonBase-prop-component**
| <img width="662" alt="Screen Shot 2023-09-20 at 21 53 09" src="https://github.com/mui/material-ui/assets/67129314/2bcfa72f-c90a-49f3-b606-e9a4a6779a99"> | <img width="665" alt="Screen Shot 2023-09-20 at 21 52 48" src="https://github.com/mui/material-ui/assets/67129314/045aa207-517a-43fe-bce0-9ad5ccd60512"> |
=> [docs-infra] Improve callouts design

packages/mui-joy/src/Drawer/DrawerProps.ts, packages/mui-joy/src/styles/components.d.ts, packages/mui-joy/src/styles/extendTheme.spec.ts
=> [Drawer] Add missing `JoyDrawer` in theme components

packages/markdown/parseMarkdown.js, packages/markdown/parseMarkdown.test.js
About: https://github.com/mui/mui-x/pull/10421#discussion_r1333141559
The toc used `replace` with a regexp to remove links and code, but they did not had the `global` parameter
=> [docs-infra] Fix code removal in table of content

docs/data/material/components/autocomplete/Virtualize.js, docs/data/material/components/autocomplete/Virtualize.tsx, docs/data/material/components/autocomplete/Virtualize.tsx.preview
ReactChild is deprecated since https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59879
Solve some of https://mui-org.slack.com/archives/C041SDSF32L/p1695112647646069
Preview: https://deploy-preview-39162--material-ui.netlify.app/material-ui/react-autocomplete/#virtualization
=> [docs] Update Autocomplete demo for React 18

docs/data/material/components/text-fields/FormattedInputs.tsx
Fixes: https://mui-org.slack.com/archives/C041SDSF32L/p1695568788634319
Preview: https://deploy-preview-39140--material-ui.netlify.app/material-ui/react-text-field/#integration-with-3rd-party-input-libraries
=> [TextField][material-ui] Polish types in Textfield demo

docs/pages/base-ui/api/use-slider.json, packages/mui-base/src/useSlider/useSlider.test.js, packages/mui-base/src/useSlider/useSlider.ts, packages/mui-base/src/useSlider/useSlider.types.ts
Aligns the naming of `externalProps: ExternalProps`, and updates the order of some returned props based on https://github.com/mui/material-ui/pull/38679
=> [base-ui][useSlider] Align externalProps handling

packages/mui-material/src/Menu/Menu.d.ts, packages/mui-material/src/Select/Select.spec.tsx, packages/mui-material/src/Select/Select.test.js, packages/mui-material/src/Select/SelectInput.js
Fixes: https://github.com/mui/material-ui/issues/38949
Required changes to fix the issue:
- Forward missing slotProps keys from Select's MenuProps to Menu. Only the paper key was passed to the Menu so the root one was missing.
- The Menu's slots and slotProps type should be the same as the Popover, as they're forwarded.
=> [material-ui][Select] Fix MenuProps slotProps forwarding

docs/data/material/components/icons/CreateSvgIcon.js, docs/data/material/components/icons/CreateSvgIcon.tsx, docs/data/material/components/icons/FontAwesomeIcon.js, docs/data/material/components/icons/FontAwesomeIcon.tsx, docs/data/material/components/icons/FontAwesomeIconSize.js, docs/data/material/components/icons/FontAwesomeIconSize.tsx, docs/data/material/components/icons/FontAwesomeSvgIconDemo.js, docs/data/material/components/icons/FontAwesomeSvgIconDemo.tsx, docs/data/material/components/icons/Icons.js, docs/data/material/components/icons/Icons.tsx, docs/data/material/components/icons/SvgIconsColor.js, docs/data/material/components/icons/SvgIconsColor.tsx, docs/data/material/components/icons/SvgIconsSize.js, docs/data/material/components/icons/SvgIconsSize.tsx, docs/data/material/components/text-fields/FormattedInputs.js, docs/data/material/components/text-fields/FormattedInputs.tsx
addresses  https://github.com/mui/material-ui/pull/39140#issuecomment-1732623667
https://deploy-preview-39174--material-ui.netlify.app/material-ui/react-text-field/#integration-with-3rd-party-input-libraries
all demos in https://deploy-preview-39174--material-ui.netlify.app/material-ui/icons/
=> [docs][material] Replace `Box` with `Stack` in applicable demos

docs/data/material/components/icons/icons.md
This PR was mostly for adding the new `codeblock` component for installation commands, but I couldn't resist some low-hanging stuff that I ended up tackling. There are many more writing opportunities here that we can improve in the future, though!
**https://deploy-preview-38840--material-ui.netlify.app/material-ui/icons/**
=> [docs][material-ui] Small revision to the Icons page

packages/mui-material-next/src/Divider/Divider.d.ts, packages/mui-material-next/src/Divider/Divider.js, packages/mui-material-next/src/Divider/Divider.test.js, packages/mui-material-next/src/Divider/dividerClasses.ts, packages/mui-material-next/src/Divider/index.d.ts, packages/mui-material-next/src/Divider/index.js
This PR copies the Divider from `material` to `material-next` with minimal changes, so later diffs are easier to review
=> [Divider][material-next] Copy v5 Divider

packages/mui-material-next/src/Select/Select.d.ts, packages/mui-material-next/src/Select/Select.js, packages/mui-material-next/src/Select/Select.spec.tsx, packages/mui-material-next/src/Select/Select.test.js, packages/mui-material-next/src/Select/SelectInput.d.ts, packages/mui-material-next/src/Select/SelectInput.js, packages/mui-material-next/src/Select/index.d.ts, packages/mui-material-next/src/Select/index.js, packages/mui-material-next/src/Select/selectClasses.ts, packages/mui-material-next/src/index.ts, packages/mui-material-next/src/internal/svg-icons/ArrowDropDown.tsx
Part of https://github.com/mui/material-ui/issues/38972, https://github.com/mui/material-ui/issues/29345
This PR copies the files related to the Select component from the `material` package to the `material-next` package with minimal modification (e.g. import paths, just enough to pass CI) so it's easier to see the diffs of the following-up  https://github.com/mui/material-ui/issues/38972 PRs.
There are some imports left from the `material` package that will be updated later:
- Input-related components being worked on https://github.com/mui/material-ui/issues/38374
- Menu-related components being worked on https://github.com/mui/material-ui/pull/38934
- Native Select component, no need to move this one yet
=> [material-next][Select] Copy Select files from v5

apps/zero-runtime-next-app/next.config.js, apps/zero-runtime-vite-app/src/App.tsx, apps/zero-runtime-vite-app/vite.config.ts, packages/zero-next-plugin/src/loaders/transformLoader.ts, packages/zero-runtime/package.json, packages/zero-runtime/src/index.ts, packages/zero-runtime/src/keyframes.d.ts, packages/zero-runtime/src/keyframes.js, packages/zero-tag-processor/package.json, packages/zero-tag-processor/src/base-processor.ts, packages/zero-tag-processor/src/keyframes.ts, packages/zero-tag-processor/src/preprocessor.ts, packages/zero-tag-processor/src/styled.ts, packages/zero-tag-processor/src/utils/emotion.ts, packages/zero-tag-processor/src/utils/processCssObject.ts, packages/zero-vite-plugin/src/index.ts, yarn.lock
* The functionality is same as in [Emotion](https://emotion.sh/docs/@emotion/css#animation-keyframes).
* This PR also adds custom preprocessor as the default one had issues when using an animation name in the CSS.
* Added custom stylis plugin support as well. This will let us apply dark theme styles without hacky CSS.
=> [zero][system] Add support for keyframes

docs/pages/base-ui/api/use-tab-panel.json, docs/pages/base-ui/api/use-tab.json, docs/pages/base-ui/api/use-tabs-list.json, packages/mui-base/src/useTab/useTab.test.tsx, packages/mui-base/src/useTab/useTab.ts, packages/mui-base/src/useTab/useTab.types.ts, packages/mui-base/src/useTabPanel/useTabPanel.test.js, packages/mui-base/src/useTabPanel/useTabPanel.ts, packages/mui-base/src/useTabPanel/useTabPanel.types.ts, packages/mui-base/src/useTabsList/useTabsList.test.tsx, packages/mui-base/src/useTabsList/useTabsList.ts, packages/mui-base/src/useTabsList/useTabsList.types.ts
This PR aligns the typing/handling of external props for `useTab`, `useTabsList` and `useTabPanel` and adds some simple tests
=> [base-ui][useTabs] Align external props handling for useTab/useTabPanel/useTabsList

packages/mui-base/src/useTab/useTab.test.tsx, packages/mui-base/src/useTabPanel/useTabPanel.test.js, packages/mui-base/src/useTabsList/useTabsList.test.tsx
I forgot to update to `'@mui-internal/test-utils'` in https://github.com/mui/material-ui/pull/39037 😓 
Fixes CI currently failing on master: https://app.circleci.com/pipelines/github/mui/material-ui/110305/workflows/1def82a9-c4b9-4ac0-aac3-f179632f70ae/jobs/591293
=> [test][base-ui] Fix import paths in useTab tests

packages/mui-joy/src/CssBaseline/CssBaseline.tsx
From https://github.com/mui/material-ui/pull/36829/files/af3d831e7130d34b5ab81b4b2821a387067c87a3#r1343238470.
This fix will make theme scoping work with CssBaseline.
=> [CssBaseline] use Joy `GlobalStyles`

docs/data/joy/components/tabs/TabsBottomNavExample.js, docs/data/joy/components/tabs/TabsBottomNavExample.tsx, docs/data/joy/components/tabs/TabsPageExample.js, docs/data/joy/components/tabs/TabsPageExample.tsx, docs/data/joy/components/tabs/TabsScrollable.js, docs/data/joy/components/tabs/TabsScrollable.tsx, docs/data/joy/components/tabs/TabsScrollable.tsx.preview, docs/data/joy/components/tabs/tabs.md
Part of #34974
A CSS-only approach until we have the JS version from Base UI.
👉  **https://deploy-preview-39260--material-ui.netlify.app/joy-ui/react-tabs/#scrollable-tabs**
=> [docs][joy-ui] Add scrollable tabs example

packages/mui-material-next/src/FormHelperText/FormHelperText.d.ts, packages/mui-material-next/src/FormHelperText/FormHelperText.js, packages/mui-material-next/src/FormHelperText/FormHelperText.spec.tsx, packages/mui-material-next/src/FormHelperText/FormHelperText.test.js, packages/mui-material-next/src/FormHelperText/formHelperTextClasses.ts, packages/mui-material-next/src/FormHelperText/index.d.ts, packages/mui-material-next/src/FormHelperText/index.js, packages/mui-material-next/src/FormLabel/FormLabel.d.ts, packages/mui-material-next/src/FormLabel/FormLabel.js, packages/mui-material-next/src/FormLabel/FormLabel.test.js, packages/mui-material-next/src/FormLabel/formLabelClasses.ts, packages/mui-material-next/src/FormLabel/index.d.ts, packages/mui-material-next/src/FormLabel/index.js, packages/mui-material-next/src/InputAdornment/InputAdornment.d.ts, packages/mui-material-next/src/InputAdornment/InputAdornment.js, packages/mui-material-next/src/InputAdornment/InputAdornment.test.js, packages/mui-material-next/src/InputAdornment/index.d.ts, packages/mui-material-next/src/InputAdornment/index.js, packages/mui-material-next/src/InputAdornment/inputAdornmentClasses.ts, packages/mui-material-next/src/InputLabel/InputLabel.d.ts, packages/mui-material-next/src/InputLabel/InputLabel.js, packages/mui-material-next/src/InputLabel/InputLabel.spec.tsx, packages/mui-material-next/src/InputLabel/InputLabel.test.js, packages/mui-material-next/src/InputLabel/index.d.ts, packages/mui-material-next/src/InputLabel/index.js, packages/mui-material-next/src/InputLabel/inputLabelClasses.ts, packages/mui-material-next/src/index.ts
Part of https://github.com/mui/material-ui/issues/38374
This PR copies (with minimal changes) the remaining components that are required to compose the `filled` variant of `TextField` and `Select`:
- `FormLabel`
- `InputLabel`
- `InputAdornment`
- `FormHelperText`
=> [material-next][TextField] Copy v5 TextField's inner components

docs/data/base/components/select/UnstyledSelectCustomRenderValue.js, docs/data/base/components/select/UnstyledSelectCustomRenderValue.tsx, docs/data/base/components/select/UnstyledSelectCustomRenderValue.tsx.preview, docs/data/base/components/select/UnstyledSelectRichOptions.js, docs/data/base/components/select/UnstyledSelectRichOptions.tsx, docs/data/base/components/select/UnstyledSelectRichOptions.tsx.preview, docs/data/base/components/select/select.md
A quick iteration on #38796 to polish the demo. This feels much clearer for me when reading.
Before: https://master--material-ui.netlify.app/base-ui/react-select/#selected-value-appearance
Preview: https://deploy-preview-38983--material-ui.netlify.app/base-ui/react-select/#selected-value-appearance
---
A side note, I have tried to make this
```diff
diff --git a/docs/data/base/components/select/UnstyledSelectRichOptions.tsx b/docs/data/base/components/select/UnstyledSelectRichOptions.tsx
index 1144795569..b5d901cbc0 100644
--- a/docs/data/base/components/select/UnstyledSelectRichOptions.tsx
+++ b/docs/data/base/components/select/UnstyledSelectRichOptions.tsx
@@ -7,6 +7,7 @@ import { Popper } from '@mui/base/Popper';
export default function UnstyledSelectRichOptions() {
return ( …
```
=> [docs][base-ui] Improve Select's country select demo

CHANGELOG.md
See https://github.com/mui/material-ui/issues/35586
Add missing notice about Select's a11y improvements which involve a role change.
=> [material-ui][Select] Add notice about select's a11y improvement on v5.14.12 changelog

docs/pages/base-ui/api/menu.json, docs/translations/api-docs-base/menu/menu.json, packages/mui-base/src/Menu/Menu.test.tsx, packages/mui-base/src/Menu/Menu.tsx, packages/mui-base/src/Menu/Menu.types.ts
Added the `anchor` prop to the Base UI's Menu to allow more freedom in placing it.
Closes #39284
=> [Menu][base-ui] Add the anchor prop

docs/data/joy/components/input/InputValidation.js, docs/data/joy/components/input/InputValidation.tsx, docs/data/joy/components/input/InputValidation.tsx.preview
preview: https://deploy-preview-39280--material-ui.netlify.app/joy-ui/react-input/#validation
=> [docs][joy-ui] Remove redundant `error` prop from input validation demo

packages/mui-material/src/Checkbox/Checkbox.js
Fixes #39230
Before - https://codesandbox.io/s/unruffled-robinson-llzdmd?file=/src/App.tsx
After - https://codesandbox.io/s/nostalgic-cherry-7nddw5
=> [material-ui][Checkbox] Fix checkbox hover bg with extendTheme

packages/mui-base/src/useAutocomplete/useAutocomplete.js
=> [joy-ui][Autocomplete] Add `type=button` to clear button

docs/pages/experiments/index.js, docs/pages/experiments/md3/buttons.tsx, docs/pages/experiments/md3/index.tsx, docs/pages/experiments/md3/inputs.tsx
Some tweaks to the experiments index page:
- Display the MD3 sections/pages properly, we'll be using this more very soon
- Tweaked the background color, it annoyed me a bit 🙈
=> [docs] Set up MD3 experiments pages

docs/data/material/components/drawers/PersistentDrawerRight.js, docs/data/material/components/drawers/PersistentDrawerRight.tsx
Fixes #29997 
Closes #38760 (PR)
I couldn't push on PR #38760, so I created this one because the author of #38760 has been inactive for a week.
Before: https://mui.com/material-ui/react-drawer/#persistent-drawer
After: https://deploy-preview-39318--material-ui.netlify.app/material-ui/react-drawer/#persistent-drawer
=> [docs][Drawer] Fix right anchored persistent drawer intercepts click when it is closed

docs/src/modules/components/Demo.js
I noticed this from https://github.com/mui/material-ui/issues/39176. Open https://mui.com/base-ui/react-tabs/#introduction, no scrollbar:
IMHO, we should almost never use `overflow: hidden` but there are rare valid ones e.g. skeleton animation background. 
Now, in my example, we should also likely fix the demo itself, but here, my goal is to have better behavior when it goes wrong, and make it feel less broken.
Preview: https://deploy-preview-39225--material-ui.netlify.app/base-ui/react-tabs/#introduction
---
Actually, I think that we can broaden the topic on do we even want a `overflow` style? Why is it different based on the demo type?
It's relatively frequent for a demo to break the mobile layout, e.g. https://github.com/mui/mui-x/pull/10455 recently. Today, when this happens, it's …
=> [docs-infra] Remove overflow: hidden for demo gradient bg

packages/mui-joy/src/Switch/Switch.tsx
=> [joy-ui][Switch] Fix missing class name

docs/data/joy/components/input/DebouncedInput.js, docs/data/joy/components/input/DebouncedInput.tsx, docs/data/joy/components/input/DebouncedInput.tsx.preview, docs/data/joy/components/input/input.md
preview: https://deploy-preview-39300--material-ui.netlify.app/joy-ui/react-input/#debounced-input
https://www.npmjs.com/package/react-debounce-input has 224k weekly downloads, so i think debounce is pouplar enough use-case that can go be a demo.
=> [joy-ui][Input] Add debounce input demo

docs/src/modules/sandbox/CodeSandbox.test.js, docs/src/modules/sandbox/CodeSandbox.ts
Preview: https://deploy-preview-39317--material-ui.netlify.app/material-ui/react-alert/#basic-alerts
Closes https://github.com/mui/material-ui/issues/38860
| ![image](https://github.com/mui/material-ui/assets/67954450/602cb309-96b4-40ba-b567-9cebe0eb375a) | ![image](https://github.com/mui/material-ui/assets/67954450/46b69132-beb4-4b7b-91a5-3f003dfe86b6) | 
Also, I think the issue has also fixed the problem where you navigate to the docker tab and convert to a cloud sandbox.
Thank you so much @Janpot, your suggestion was very helpful and was enough to solve the problem
=> [docs-infra] Fix Code Sandbox download issue

packages/zero-tag-processor/src/generateCss.ts, packages/zero-tag-processor/src/styled.ts, packages/zero-tag-processor/src/sx.ts, packages/zero-tag-processor/src/utils/cssFunctionTransformerPlugin.ts, packages/zero-tag-processor/src/utils/processCssObject.ts
Now, it'll only transform styles in sx prop. Styled css will be converted directly without any transformation (like `pt` to `paddingTop`).
Also fixes the variable replacement for css property runtime functions
=> [zero][tag] Fix styled transformation

docs/data/joy/getting-started/templates/TemplateCollection.js, docs/data/joy/getting-started/templates/index.md
This PR adds some layer of polish to the Templates card design, primarily focusing on adding labels to the buttons to clarify what both of them — the live preview & CodeSanbox — mean, following recent docs-feedback. Additionally, also changed the "open a pull request" link direction to the Contributing guide, as that seems more fitting for folks looking to open one up.
👉 **https://deploy-preview-39369--material-ui.netlify.app/joy-ui/getting-started/templates/**
=> [docs][joy-ui] Adjust the templates page card design

docs/data/joy/components/snackbar/snackbar.md, docs/data/joy/getting-started/roadmap/roadmap.md, docs/src/modules/components/MarkdownElement.js
Fix https://github.com/mui/material-ui/pull/39163#discussion_r1353556265 for context. We could fix the CSS but I figured enforcing a single way to do bold links is a good outcome too.
=> [docs-infra] Fix strong style regression

docs/pages/material-ui/api/app-bar.json, docs/translations/api-docs/app-bar/app-bar.json, packages/mui-material/src/AppBar/AppBar.d.ts, packages/mui-material/src/AppBar/AppBar.js, packages/mui-material/src/AppBar/AppBar.spec.tsx, packages/mui-material/src/AppBar/appBarClasses.ts
Fixes #39053
Before: https://codesandbox.io/s/inspiring-edison-3ffqdm?file=/src/App.tsx
After: https://codesandbox.io/s/mutable-smoke-5sx9sz
=> [material-ui][AppBar] Support all default palette colors in TypeScript

docs/data/material/components/avatars/CustomSurplusAvatars.js, docs/data/material/components/avatars/CustomSurplusAvatars.tsx, docs/data/material/components/avatars/CustomSurplusAvatars.tsx.preview, docs/data/material/components/avatars/avatars.md, docs/pages/material-ui/api/avatar-group.json, docs/translations/api-docs/avatar-group/avatar-group.json, packages/mui-material/src/AvatarGroup/AvatarGroup.d.ts, packages/mui-material/src/AvatarGroup/AvatarGroup.js, packages/mui-material/src/AvatarGroup/AvatarGroup.spec.tsx, packages/mui-material/src/AvatarGroup/AvatarGroup.test.js
…Avatar element
According to @siriwatknp comment, add renderSurplus prop. 
possible solution to #39204
=> [material-ui][AvatarGroup] Add `renderSurplus` prop

packages/mui-joy/src/Skeleton/Skeleton.tsx
Closes #39348 
| ![image](https://github.com/mui/material-ui/assets/104088023/f3c85174-dc24-4030-bf82-0b20963c179b) The Skeleton appears slightly transparent, revealing the text underneath. | ![image](https://github.com/mui/material-ui/assets/104088023/9ca57c30-af5f-4920-8d36-ced013826bdd) Now, the Skeleton is opaque and hides the text underneath. |
=> [joy-ui][Skeleton] Fix semi-transparent scenario when with surface components and color inversion

docs/data/base/components/number-input/number-input.md, docs/data/joy/components/drawer/drawer.md, docs/pages/blog/v6-beta-pickers.md, docs/pages/experiments/docs/markdown.md, docs/src/modules/components/MarkdownElement.js
This PR adds some styling tweaks to the `<kbd>` tag and adds instructions about using the specific `key` class for them. Initially, this PR changed the Markdown Element file targeting to get the whole tag, but I learned through Alex (down below) that the class existed for when we want to wrap individual tags with a parent `kbd` to indicate that they should be pressed together. 
👉 **https://deploy-preview-39397--material-ui.netlify.app/experiments/docs/markdown/#kbd-tag**
=> [docs-infra] Adjust the `kbd` tag styles

packages/mui-material/src/Box/Box.spec.tsx, packages/mui-system/src/Box/Box.d.ts
Fixes https://github.com/mui/material-ui/issues/39402
=> [material-ui][Box] Fix system properties has incorrect `Theme` interface when applied directly

docs/data/joy/components/typography/TypographyTitleBody.js, docs/data/joy/components/typography/TypographyTitleBody.tsx, docs/data/joy/components/typography/typography.md
Updated the 'Title and body' demo on the Typography docs page. After changes made on #38462, the lineHeight from Typography no longer fits with SVG icons, so I tweaked the demo to make sense with the current version.
👉 **https://deploy-preview-39366--material-ui.netlify.app/joy-ui/react-typography/#title-and-body**
| <img width="400" alt="Screenshot 2023-10-09 at 16 27 56" src="https://github.com/mui/material-ui/assets/37222944/6827fd46-3b5a-488c-ad58-0238b6e8eea2"> | <img width="400" alt="Screenshot 2023-10-12 at 09 09 19" src="https://github.com/mui/material-ui/assets/37222944/fe739d1e-65cd-4398-b91f-1cba63c31c72"> |
=> [joy-ui][typography] Update docs after lineHeight changes

docs/data/joy/main-features/color-inversion/ColorInversionAnyParentStyled.js, docs/data/joy/main-features/color-inversion/ColorInversionAnyParentStyled.tsx, docs/data/joy/main-features/color-inversion/ColorInversionHeader.js, docs/data/joy/main-features/color-inversion/ColorInversionHeader.tsx, docs/data/joy/main-features/color-inversion/color-inversion.md, packages/mui-joy/src/colorInversion/colorInversionUtils.spec.tsx, packages/mui-joy/src/colorInversion/colorInversionUtils.ts
This PR fixes some regressions caused by my previous PR on the same page/demos — https://github.com/mui/material-ui/pull/39306 🫠
| <img width="848" alt="Screen Shot 2023-10-11 at 17 00 41" src="https://github.com/mui/material-ui/assets/67129314/43f9ac07-cf66-4ac5-95e7-6519da948e33"> | <img width="848" alt="Screen Shot 2023-10-11 at 17 00 50" src="https://github.com/mui/material-ui/assets/67129314/7b474c22-f97c-4f64-b40e-7b4feff05045"> | 
👉 **https://deploy-preview-39403--material-ui.netlify.app/joy-ui/main-features/color-inversion/**
=> [docs][joy-ui] Fix color inversion demos

docs/pages/experiments/docs/markdown.md, docs/src/modules/components/AppTableOfContents.js
This PR is primarily for adding `textOverflow: 'ellipsis'` to the table of content items, preventing them from overflowing in case there's a big label without spaces. It's been recently surfaced by a non-related PR (https://github.com/mui/material-ui/pull/39412). Also took advantage of the opportunity for some stylistic polish! 😊 
👉 **https://deploy-preview-39417--material-ui.netlify.app/experiments/docs/data-grid-premium/#css**
👉 **https://deploy-preview-39417--material-ui.netlify.app/experiments/docs/markdown/#wordwithoutspaceasitwouldhappenwithapropdeclaration**
=> [docs-infra] Prevent horizontal scroll in the TOC

docs/data/base/components/number-input/number-input.md, docs/data/base/getting-started/quickstart/quickstart.md, docs/data/joy/components/skeleton/skeleton.md, docs/data/system/experimental-api/css-theme-variables/css-theme-variables.md, docs/pages/blog/2021-developer-survey-results.md, docs/pages/blog/2023-mui-values.md, docs/pages/blog/first-look-at-joy.md, docs/pages/blog/mui-core-v5-migration-update.md, docs/pages/careers/senior-designer.md
Multiple typos on multiple files located inside /docs directory has been fixed.
=> [core] Fix multiple typos across the repo

docs/data/joy/components/table/table.md
https://github.com/mui/material-ui-docs/pull/107
=> [docs][joy-ui] Fix row hover prop name in the Table page

docs/src/modules/components/ApiPage/list/ExpendableApiItem.tsx, docs/src/modules/components/ApiPage/sections/ClassesSection.tsx, docs/src/modules/components/ApiPage/sections/CssSection.tsx, docs/src/modules/components/ApiPage/sections/PropertiesSection.js, docs/src/modules/components/ApiPage/sections/SlotsSection.tsx, docs/src/modules/components/ApiPage/table/CSSTable.tsx, docs/src/modules/components/ApiPage/table/ClassesTable.tsx, docs/src/modules/components/ApiPage/table/PropertiesTable.tsx, docs/src/modules/components/ApiPage/table/SlotsTable.tsx
This PR is a follow-up to the recently merged newer API content design iteration — https://github.com/mui/material-ui/pull/38265. Notable changes are:
- Add a scroll margin-top so clicking on the prop anchors work fine
- Fix icon orientation on the list accordion
- Stray stylistic changes
👉 **https://deploy-preview-39425--material-ui.netlify.app/material-ui/api/button/#Button-prop-classes**
=> [docs-infra] Add refinements to the API content design

docs/src/components/pricing/HeroPricing.tsx, docs/src/components/pricing/LicensingModelSwitch.tsx, docs/src/components/pricing/PricingTable.tsx, docs/src/components/pricing/PricingWhatToExpect.tsx
This PR adds a few design adjustments here and there throughout the Pricing page, most notably:
- Annual vs. Perpetual tab tweaks
- Spacing adjustments between all the sections
- Component usage consistency (use what we're using in other pages)
👉 **https://deploy-preview-39472--material-ui.netlify.app/pricing**
=> [website] Add stray design fine-tunning to the Pricing page

docs/data/about/teamMembers.json, docs/src/components/about/Team.tsx
this PR adds a linkedin profile button to contributers cards
linkedin button added as shown in below image
fixes #39453
=> [website] Add the LinkedIn profile to the contributors section on the About page

packages/mui-material/src/InputLabel/InputLabel.js, packages/mui-material/src/InputLabel/InputLabel.test.js
Resolves https://github.com/mui/material-ui/issues/37069, Resolves https://github.com/mui/material-ui/issues/36550, Resolves https://github.com/mui/material-ui/issues/39427
This PR enables users to more easily customize the `maxWidth` of a `TextField`'s label based on it's focused state to control truncation of the label
The before/after end result look same, but after this fix you are no longer required to manually add a focused state to achieve the customization, and it can be done in the theme
Before: https://codesandbox.io/s/https-github-com-mui-material-ui-issues-39427-vx2gvd?file=/demo.tsx
After: https://codesandbox.io/s/https-github-com-mui-material-ui-pull-39470-y7gr8x
=> [InputLabel][material-ui] InputLabel supports ownerState.focused for styleOverrides

packages/mui-joy/src/Link/Link.tsx
=> [joy-ui][Link] Apply `userSelect: none` only when it's a button

packages/mui-material-next/src/Snackbar/Snackbar.d.ts, packages/mui-material-next/src/Snackbar/Snackbar.js, packages/mui-material-next/src/Snackbar/Snackbar.test.js, packages/mui-material-next/src/Snackbar/index.d.ts, packages/mui-material-next/src/Snackbar/index.js, packages/mui-material-next/src/Snackbar/snackbarClasses.ts
related to: #39207
In this change, only the Snackbar files were moved to mui-material-next and their imports were adjusted.
=> [material-next][Snackbar] copy files to mui-material-next

packages/mui-material-next/src/InputAdornment/InputAdornment.js
Fixes https://github.com/mui/material-ui/issues/39507
Import `unstable_capitalize` from `@mui/utils` and not `@mui/base/composeClasses`
=> [material-next][InputAdornment] Fix unstable_capitalize import

packages/mui-lab/package.json
Fixes #39379
lab now uses `@mui/material/generateUtilityClass` which is only available in material after `5.10.10`
=> [lab] Update peer dep of @mui/material

packages/mui-material/src/locale/index.ts
=> [I10n] Additions to Icelandic (is-IS) locale

docs/postcss.config.js
Fix https://github.com/mui/material-ui/pull/37319#issuecomment-1599633128
See the code for why it triggers https://github.com/postcss/autoprefixer/blob/026083ccde85fd16607d1056d3fa058480004184/lib/autoprefixer.js#L33
I'm surprised nobody fixed it already, it would have driven me insane to work with this for 3 months 😁
=> [docs-infra] Fix no-op autoprefixer warning

docs/src/modules/components/AppFrame.js, docs/translations/translations.json
I have just noticed how broken the migration experience from v4 is.
Open https://v4.mui.com/components/container/ 🙈.
- We say "migrate to v5, go to mui.com". meaning v5 is called MUI.
- We don't say anything on how to migrate", good luck
=> [docs] Improve upgrade experience from Material UI v4

apps/local-library/index.d.ts, apps/local-library/index.js, apps/local-library/package.json, apps/zero-runtime-vite-app/package.json, apps/zero-runtime-vite-app/src/App.tsx, apps/zero-runtime-vite-app/vite.config.ts, packages/zero-runtime/package.json, packages/zero-runtime/src/styled.js, packages/zero-tag-processor/src/utils/cssFnValueToVariable.ts, packages/zero-tag-processor/src/utils/cssFunctionTransformerPlugin.ts, packages/zero-tag-processor/src/utils/index.ts, packages/zero-vite-plugin/package.json, packages/zero-vite-plugin/src/index.ts, packages/zero-vite-plugin/src/zero-vite-plugin.ts, yarn.lock
This feature allows users to specify a list of packages
that also uses zero runtime and transform the files at
build time. Default behavior is not transform any files
from node_modules.
Also, fix a bug where the transformation did not allow you to write callback functions for css variables.
=> [zero][vite] Modify plugin to transform node_modules 

docs/data/joy/getting-started/templates/TemplateCollection.js
This PR adds some tiny tweaks to the Joy UI template card, ensuring it scales well in smaller viewports. Also fixed the aria-label for the Source code button, which was with the old one still!
| Current | New |
| <img width="400" alt="Screenshot 2023-10-20 at 13 20 56" src="https://github.com/mui/material-ui/assets/37222944/96eec815-0706-4a1f-855b-ab5a809351f7"> | <img width="350" alt="Screenshot 2023-10-20 at 13 21 16" src="https://github.com/mui/material-ui/assets/37222944/2ee1b274-6765-4d0d-986e-2219ffc34d4d"> | 
👉  https://deploy-preview-39534--material-ui.netlify.app/joy-ui/getting-started/templates/
=> [joy-ui][docs] Adjust the responsiveness of the template card

packages/mui-utils/src/useEventCallback/useEventCallback.ts
Minor touchup, `useRef` is leaner than `useCallback`.
=> [core] Replace a `useCallback` by `useRef` in useEventCallback

docs/data/joy/components/input/InputDecorators.js, docs/data/joy/components/input/InputDecorators.tsx, docs/data/joy/components/textarea/TextareaDecorators.js, docs/data/joy/components/textarea/TextareaDecorators.tsx, packages/mui-joy/src/Button/Button.tsx, packages/mui-joy/src/Input/Input.tsx, packages/mui-joy/src/Select/Select.tsx, packages/mui-joy/src/Textarea/Textarea.tsx
closes #39515 
This is a regression from https://github.com/mui/material-ui/pull/38696 because of the increasing of padding-block. I'm fixing it by introducing an internal CSS variable to the button so that the Input can control it.
**Before**
**After**
https://codesandbox.io/s/jolly-pine-qf29yc
I use this opportunity to do the same with Select and Textarea.
https://app.argos-ci.com/mui/material-ui/builds/19946/62078137
---
=> [joy-ui][Button] Fix button size being a decorator

docs/src/modules/components/AppLayoutDocsFooter.js
I just got the docs crashing. After some navigation in the source code of the page, it appears it's the `feedback` cookies that have incorrect JSON format.
This token is used to save user feedback on pages. Since it's not super important, I just added a try/catch.
=> [docs-infra] Prevent docs crash

docs/src/modules/components/ApiPage/list/PropertiesList.tsx, docs/src/modules/components/ApiPage/sections/PropertiesSection.js, docs/src/modules/components/ApiPage/table/PropertiesTable.tsx
Some fixes are from lukas feedback that color were wrong on table layout, and that we supressed the `<code>` in warnings
Some are just classes renaming
Another one is from [slack message](https://mui-org.slack.com/archives/C05HHSFH2QJ/p1697561118893289)
> Oh yeah, this is way better.
>
> One thing I did notice is that long types are all on one line, which make them hard to read. Example here on api/popper is the modifiers prop:
>
> Type:Array<{ data?: object, effect?: func, enabled?: bool, fn?: func, name?: any, options?: object, phase?: 'afterMain' | 'afterRead' | 'afterWrite' | 'beforeMain' | 'beforeRead' | 'beforeWrite' | 'main' | 'read' | 'write', requires?: Array<string>, requiresIfExists?: Array<string> }>
sent from https://mui.com/material-ui/api/popper/ (from section <|New API …
=> [docs-infra] Refine the API page design

packages/mui-base/src/Input/Input.test.tsx, packages/mui-base/src/useInput/useInput.test.tsx, packages/mui-material-next/src/InputBase/InputBase.test.tsx
Part of: https://github.com/mui/material-ui/pull/38392
Follow up to: https://github.com/mui/material-ui/pull/38392#discussion_r1291341517
This PR ports relevant tests from `material-next/InputBase` to Base's `Input.test`/`useInput.test`, as lot of functionality that was in the v5 InputBase has been migrated to Base UI.
=> [Input][base-ui] Update and port additional tests from material-ui

docs/src/modules/components/AppTableOfContents.js, docs/src/modules/components/DiamondSponsors.js
In the current configuration, it feels like the go-to-top floating button will prevent the audience from comfortably clicking on the 3rd diamond sponsor without clicking on he go-to-top and the other way around. I think this PR goes in the right direction, I made only a small change, maybe it should be bolder.
Before https://master--material-ui.netlify.app/material-ui/react-button/#unstyled
After https://deploy-preview-39572--material-ui.netlify.app/material-ui/react-button/#unstyled
A bit related to #39332.
=> [docs-infra] Fix cut-off sponsors

docs/data/material/getting-started/example-projects/example-projects.md, docs/src/modules/components/MaterialUIExampleCollection.js
As the title says, in this PR, I'm just doing some small fine-tuning on the example collection cards design. Stuff like the example title being rendered with the Arial typeface for some reason (maybe because the variant was set to `body`?). Also changed the file name for "MaterialUIExampleCollection", which although lengthier, I think it's clearer.
👉 **https://deploy-preview-39581--material-ui.netlify.app/material-ui/getting-started/example-projects/**
=> [docs][material-ui] Add stray design fine-tuning to the example collection

docs/src/modules/components/AppSettingsDrawer.js
=> [docs-infra] Fix settings drawer accessibility issues

packages/zero-next-plugin/package.json, yarn.lock
I found [this PR](https://github.com/mui/material-ui/pull/39559) where Renovate is updating the package, but I couldn't find its usage, so I'm removing it. Closes #39559.
Also saw `@types/babel__core` package, which is not used anywhere, so I'm removing it too.
=> [core] Remove not used `@types/loader-utils` package from `zero-next-plugin`

examples/material-ui-nextjs-ts/src/app/layout.tsx
Closes #39473 by removing `color="black"` from the Typography component at the top of `layout.tsx` so the colors will render correctly in light and dark modes.
=> [examples][material-ui] Remove hardcoded `color="black"` from Next.js App Router layout

docs/data/base/components/autocomplete/AutocompleteIntroduction/css/index.js, docs/data/base/components/autocomplete/AutocompleteIntroduction/css/index.tsx, docs/data/base/components/autocomplete/AutocompleteIntroduction/tailwind/index.js, docs/data/base/components/autocomplete/AutocompleteIntroduction/tailwind/index.tsx
Follow-up to https://github.com/mui/material-ui/pull/38820
Standardize the box-shadow on all Base UI `Autocomplete` demos.
👉  https://deploy-preview-39519--material-ui.netlify.app/base-ui/react-autocomplete/
=> [base-ui][Autocomplete] Standardize box shadow on demos

docs/pages/base-ui/api/select.json, docs/pages/base-ui/api/use-select.json, docs/translations/api-docs-base/select/select.json, packages/mui-base/src/Select/Select.test.tsx, packages/mui-base/src/Select/Select.tsx, packages/mui-base/src/Select/Select.types.ts, packages/mui-base/src/useList/listActions.types.ts, packages/mui-base/src/useList/listReducer.test.ts, packages/mui-base/src/useList/listReducer.ts, packages/mui-base/src/useSelect/selectReducer.test.ts, packages/mui-base/src/useSelect/selectReducer.ts, packages/mui-base/src/useSelect/useSelect.test.tsx, packages/mui-base/src/useSelect/useSelect.ts, packages/mui-base/src/useSelect/useSelect.types.ts
Closes https://github.com/mui/material-ui/issues/37646
Support browser autofill in the useSelect hook and Select component.
- Add `onChange` handler to `getHiddenInputProps` which
- dispatches a (new) browser autofill action if the value is found in the options
- dispatches a (new) clear selection action if the value is an empty string
- Add `autoComplete` prop to Select component and forward to the hidden input
- Added tests for all the changes. 
I tested with
- 1Password on Chrome
- Chrome native autofill (including clear autofill, avoiding [#31426](https://github.com/mui/material-ui/issues/31426) by clearing when the onChange handler is called with an empty string as value)
- Safari native autofill
I couldn't get Firefox autofill to work on my computer, so I didn't test with that one. …
=> [base-ui][useSelect] Support browser autofill

docs/data/joy/components/alert/AlertInvertedColors.js, docs/data/joy/components/alert/AlertInvertedColors.tsx, packages/mui-joy/src/CircularProgress/CircularProgress.tsx, packages/mui-joy/src/LinearProgress/LinearProgress.tsx
Part of #39363 
| Current | New |
| <img width="820" alt="Screenshot 2023-10-17 at 15 33 02" src="https://github.com/mui/material-ui/assets/37222944/193e908c-b31a-4e93-9eda-392b1edc84e1"> | <img width="835" alt="Screenshot 2023-10-17 at 15 32 41" src="https://github.com/mui/material-ui/assets/37222944/9110f319-ec11-4195-a82b-1a9184055e2b"> | 
👉  https://deploy-preview-39492--material-ui.netlify.app/joy-ui/react-linear-progress/
| Current | New |
| <img width="829" alt="Screenshot 2023-10-17 at 15 34 35" src="https://github.com/mui/material-ui/assets/37222944/74cf2d5d-2716-4dc7-b3d4-3efbde6eabd5"> | <img width="823" alt="Screenshot 2023-10-17 at 15 34 22" src="https://github.com/mui/material-ui/assets/37222944/e789f91b-fdca-49f9-b59a-3f170151d5a1"> | …
=> [joy-ui][Progress] Revamp Linear and Circular progress variants

packages/mui-material/src/OutlinedInput/NotchedOutline.js, packages/mui-material/src/Radio/RadioButtonIcon.js, packages/mui-material/src/SwipeableDrawer/SwipeArea.js, packages/mui-material/src/internal/SwitchBase.js
This PR fixes https://github.com/mui/material-ui/issues/38431#issuecomment-1766076798. Starting from v6 styled-components no longer blocks the invalid props used on components created with the styled() util. In 4 of the Material UI components we are using a tag without specifying a slot name for it primitive tag without specifying slot name for it. For all of these components, all props propagated are ending up on the DOM element. This PR adds explicitly a `shouldForwardProp` on these places. @siriwatknp we will need to apply the same on Joy UI in cases where we don't have specified slot on the styled component. 
Previous (search for ownerstate in the DOM inspector): https://codesandbox.io/s/styled-components-forked-pxgs8h?file=/src/demo.js
Now (if it wants to load): …
=> [material][styled-engine-sc] Fix ownerstate being propagated to DOM node

docs/data/material/components/dialogs/AlertDialog.js, docs/data/material/components/dialogs/AlertDialog.tsx, docs/data/material/components/dialogs/AlertDialogSlide.js, docs/data/material/components/dialogs/AlertDialogSlide.tsx, docs/data/material/components/dialogs/ConfirmationDialog.js, docs/data/material/components/dialogs/ConfirmationDialog.tsx, docs/data/material/components/dialogs/CustomizedDialogs.js, docs/data/material/components/dialogs/CustomizedDialogs.tsx, docs/data/material/components/dialogs/DraggableDialog.js, docs/data/material/components/dialogs/DraggableDialog.tsx, docs/data/material/components/dialogs/FormDialog.js, docs/data/material/components/dialogs/FormDialog.tsx, docs/data/material/components/dialogs/FullScreenDialog.js, docs/data/material/components/dialogs/FullScreenDialog.tsx, docs/data/material/components/dialogs/ResponsiveDialog.js, docs/data/material/components/dialogs/ResponsiveDialog.tsx, docs/data/material/components/dialogs/ScrollDialog.js, docs/data/material/components/dialogs/ScrollDialog.tsx
- Replace unnecessary divs with `React.Fragment`
- Replace deprecated ListItem `button` with `ListItemButton` component in [Confirmation Dialogs](https://mui.com/material-ui/react-dialog/#confirmation-dialogs) demo.
Preview - https://deploy-preview-39642--material-ui.netlify.app/material-ui/react-dialog/
=> [docs][material-ui] Improve Dialog demos

docs/data/material/getting-started/installation/installation.md
I was unable to compile until I followed this article's recommendations, but as far as I can see, it's only linked to in the description at https://www.npmjs.com/package/@mui/styled-engine-sc
👉 **https://deploy-preview-39620--material-ui.netlify.app/material-ui/getting-started/installation/**
=> [docs][material-ui] Include link to bundler how-to for Styled Components users

docs/data/joy/components/menu/MenuListComposition.js, docs/data/joy/components/menu/MenuListComposition.tsx
fixes: https://mui-org.slack.com/archives/C050VE13HDL/p1696950007321329 Btw issue described in slack only happens on mobile screens.
Before: https://mui.com/joy-ui/react-menu/#menulist-composition
After preview: https://deploy-preview-39459--material-ui.netlify.app/joy-ui/react-menu/#menulist-composition
https://github.com/mui/material-ui/assets/60743144/e505b5b9-d5d6-4f19-9222-c715b416b919
https://github.com/mui/material-ui/assets/60743144/75a79731-da26-47a2-9952-fa0c896776d3
=> [Menu][joy-ui] Fix closing of listbox in `MenuList` demo

packages/mui-material/src/index.js
I noticed this in https://github.com/vercel/next.js/issues/55663#issuecomment-1740148971. We already export `export * from './styles';`.
=> [core] Remove duplicate export

docs/data/styles/advanced/advanced.md, docs/data/styles/api/api.md, docs/data/styles/basics/basics.md
Related to #39643 
We don't maintain `@mui/styles` anymore so we shouldn't invest much effort into these legacy docs, but I noticed some weird styles being applied to the blockquotes on these pages and figured they should be replaced with a much scarier `:::error` callout to discourage users from installing it. I routinely see newer developers on Stack Overflow getting stuck when trying to use `@mui/styles` with the latest version of Material UI—presumably because they're following some outdated third-party content—so maybe this will help minimize those issues.
I also cut all the intro text in the "Basics" page that referred to it as "Material UI's styling solution" and listed all of the reasons why it's such a great choice. 😅
Before:
After:
=> [docs][system] Clean up `@mui/styles` docs and discourage users from installing it

.github/styles/Blog/ComposedWords.yml, .github/styles/Blog/NamingConventions.yml, .github/styles/Blog/Typos.yml, .github/workflows/vale-action.yml, .gitignore, .vale.ini, docs/data/base/components/focus-trap/focus-trap.md, docs/data/base/guides/working-with-tailwind-css/working-with-tailwind-css.md, docs/data/material/components/selects/selects.md, docs/data/material/guides/api/api.md, docs/data/material/guides/interoperability/interoperability.md, docs/data/system/experimental-api/css-theme-variables/css-theme-variables.md
Fix #32486
@samuelsycamore That's a copy past from X (I only removed files about date pickers and data grid)
=> [core] Setup vale for enforcing style guides

packages/mui-material-next/src/SnackbarContent/SnackbarContent.d.ts, packages/mui-material-next/src/SnackbarContent/SnackbarContent.js, packages/mui-material-next/src/SnackbarContent/SnackbarContent.test.js, packages/mui-material-next/src/SnackbarContent/index.d.ts, packages/mui-material-next/src/SnackbarContent/index.js, packages/mui-material-next/src/SnackbarContent/snackbarContentClasses.ts, packages/mui-material-next/src/index.ts
…erial-next
related to: https://github.com/mui/material-ui/issues/39207
In this change, only the Snackbar files were moved to mui-material-next and their imports were adjusted.
I need these changes to be completed in order to proceed with the Snackbar implementation.
=> [material-next][Snackbar] copy Snackbar Content files to material-next package

packages/mui-base/src/utils/mergeSlotProps.test.ts, packages/mui-base/src/utils/mergeSlotProps.ts, packages/mui-material-next/src/FilledInput/FilledInput.test.tsx, packages/mui-material-next/src/FormControl/FormControl.test.tsx
Fixes https://github.com/mui/material-ui/issues/39601
Before: https://codesandbox.io/s/merge-slot-props-classes-order-w9tkzp?file=/src/App.tsx
After: https://codesandbox.io/s/https-github-com-mui-material-ui-pull-39616-syxp9x?file=/src/App.tsx
=> [base-ui] Fix mergeSlotProps className join order

docs/src/modules/components/ApiPage/sections/ToggleDisplayOption.tsx
Due to the new API page #38265, the API layout is randomly chosen the first time a user connects. This choice is saved in the localStorage. But crawlers like Algolia don't keep that information, so at each crawl, they could face either the table, collapse, or expanded layout.
To write a craw for only one layout, we need to enforce this layout when Algolia is visiting. This modification enforces the expanded layout for Algolia and Google bots
Fix https://groups.google.com/a/mui.com/g/docs-infra/c/cr9i8LDORjE
Preview https://deploy-preview-39490--material-ui.netlify.app/material-ui/api/autocomplete/#Autocomplete-prop-autoHighlight
=> [docs-infra] Fix crawler on API pages

docs/data/material/components/drawers/ResponsiveDrawer.js, docs/data/material/components/drawers/ResponsiveDrawer.tsx
Closes #39667 by adding a comment next to the line that should be removed when copying and pasting the "Responsive Drawer" demo into an app. I also changed the "you won't need" comment to be more explicit that it should be removed.
=> [docs][material-ui] Add comment about code to be removed from Drawer demo

.github/workflows/ci.yml
Removed the second build of all the libraries as it's time-consuming (over 6 minutes). While testing if the build is idempotent is valuable, it feels that removing it could be a compromise between completeness and speed. It's not an area that often changes.
=> [core] Speed up the CI by removing the second build

docs/src/modules/components/ApiPage.js, docs/translations/translations.json
There has been more than one docs-feedback entry ([here's an example of a recent one](https://mui-org.slack.com/archives/C041SDSF32L/p1698409526657079)) in varying component API pages, requesting something like "I want to see demos, not just a list of props" as if we didn't provide the usual demo pages. So, this points out how we can call more attention to the "Demos" heading on the top of the API page to, hopefully, improve access to them.
To do that, on this PR, I'm wrapping in a success alert the content that was sitting under the "Demos" heading, as well as changing its title to be even more apparent (and slightly redundant, possibly).
👉 https://deploy-preview-39690--material-ui.netlify.app/joy-ui/api/accordion-summary/#demos
=> [docs-infra] Improve access to the component demos via the API page

docs/src/modules/components/Ad.js, docs/src/modules/components/ApiPage/sections/ClassesSection.tsx, docs/src/modules/components/ApiPage/sections/CssSection.tsx, docs/src/modules/components/ApiPage/sections/SlotsSection.tsx, docs/src/modules/components/ApiPage/sections/ToggleDisplayOption.tsx
A quick follow-up on #39490.
My main concern was about the double render, I didn't benchmark it, but I would expect it not to help with the performance of the page.
Preview: https://deploy-preview-39704--material-ui.netlify.app/material-ui/api/autocomplete/#Autocomplete-prop-renderInput
=> [docs–infra] Small polish on API toggle

docs/src/modules/components/ApiPage/list/ExpendableApiItem.tsx
Befor/After
Also noticed that the default column has some empty ticks that are just due to the content being undefined. It's not the expected behavior, but it looks good :+1:
=> [docs-infra] Fix dark theme color

packages/mui-material-next/src/InputBase/InputBase.spec.tsx, packages/mui-material-next/src/InputBase/InputBase.types.ts
Part of https://github.com/mui/material-ui/issues/38372
This PR ports the fix in https://github.com/mui/material-ui/pull/39569 to `material-next`
=> [InputBase][material-next] InputBase slotProps accepts sx type

docs/src/modules/components/AppLayoutDocsFooter.js
A follow-up on #36556. I have two problems with the current footer:
https://mui.com/material-ui/getting-started/design-resources/
1. We don't want candidates who browse the docs to land on the career page so easily. The last time we tried to encourage people who browse the docs to apply to roles, this was the channel with the worst conversion rate. I think it's better for people to actively search the page.
2. I have removed links that are clearly corporate. I think that we should keep the open-source docs focused on its community.
3. We used the icon that signals `target="_blank"` but we didn't add them, fixed. <img width="16" alt="Screenshot 2023-11-02 at 02 05 15" src="https://github.com/mui/material-ui/assets/3165635/3a7b3613-4cd0-4eb0-9aca-5dacb9bd59f0">
Edit: Ah, I forgot I opened …
=> [docs-infra] Simplify footer

docs/src/modules/components/AppLayoutDocs.js, docs/src/modules/components/AppLayoutDocsFooter.js
I have noticed this while I was looking at https://github.com/mui/material-ui/pull/39704.
- Fix layout shift in https://mui.com/material-ui/getting-started/design-resources/ when loading the page. Overall, it feels like it makes more sense to SSR the footer. In the future, we might be able to make it a Server component. The alternative fix would be to simply force the scrollbar to reserve space.
- Fix the animation by adding a `<div>`. Before
https://github.com/mui/material-ui/assets/3165635/812f8b8e-4f7f-4126-bd10-edf203971d6a
Preview: https://deploy-preview-39710--material-ui.netlify.app/material-ui/getting-started/design-resources/
=> [docs-infra] Render footer in SSR

docs/src/modules/components/RichMarkdownElement.js
I have noticed this while I was looking at #39704.
Before
After
From the network tab, we go from 13.1 to 13.0 MB, so saving ~100KB of JavaScript unzipped on almost all the pages of the docs.
=> [docs-infra] Fix path bloat client-side

packages/mui-joy/src/CardOverflow/CardOverflow.tsx, packages/mui-joy/src/ModalDialog/ModalDialog.tsx
Adding `data-*` props to `CardOverFlow` is removed in this PR as styling is handled by `css` (https://github.com/mui/material-ui/pull/39101/files#diff-ba48a66cb44c70614c0374277ba1300dd6bdccb7d4a87ccad4e7f92d9930dce8) but removing in `ModalDialog` component is missed
=> [joy-ui][ModalDialog] Remove redundant code

packages/mui-base/src/unstable_useModal/useModal.ts, packages/mui-material/src/Dialog/Dialog.test.js
We use the escape key to cancel IME input.
This PR changed a dialog that keeps open when you cancel IME input in a dialog with the escape key.
This is similar to #19435
=> [material-ui][Dialog] Should not close until the IME is cancelled

test/regressions/index.js
I have noticed this while I was looking at https://github.com/mui/material-ui/pull/39704.
See https://app.argos-ci.com/mui/material-ui/builds/20423/63355721 as an example.
---
I think that we should implement the `NoSnap` suffix demo convention here as MUI X does: https://github.com/mui/mui-x/blob/612fb24d6686565dd1adac613c2d42aadf3047d6/test/regressions/index.js#L19
=> [test] Fix flaky screenshot

docs/src/modules/components/ApiPage/list/ExpendableApiItem.tsx
I have noticed this while I was looking at #39704:
1. When I click on prop links in dev mode http://0.0.0.0:3000/material-ui/api/dialog/#Dialog-prop-classes
⬇️
2. When I click on prop links in production is replaces my clipboard, I didn't ask him to.
The simplest solution seems to remove this behavior. If we really want to keep it, we would need to use `clipboard-copy` instead.
=> [docs-infra] Fix bug on API prop copy experience

packages/mui-material/src/FilledInput/FilledInput.js, test/regressions/fixtures/TextField/FilledMultilineHiddenLabelTextField.js
Fixes https://github.com/mui/material-ui/issues/39610
I've adjusted the padding so that the `small` filled multiline hiddenInput TextField has the same `40px` height and updated a regression test
Before: https://codesandbox.io/s/https-github-com-mui-material-ui-issues-39610-66xjhp?file=/src/App.tsx
The `small` one has larger padding than the `medium` one
After: https://codesandbox.io/s/https-github-com-mui-material-ui-pull-39769-5xpmzh?file=/src/App.tsx
=> [TextField][material-ui] Fix padding on small filled multiline TextField

packages/mui-material-next/src/CircularProgress/CircularProgress.d.ts, packages/mui-material-next/src/CircularProgress/CircularProgress.js, packages/mui-material-next/src/CircularProgress/CircularProgress.test.js, packages/mui-material-next/src/CircularProgress/circularProgressClasses.ts, packages/mui-material-next/src/CircularProgress/index.d.ts, packages/mui-material-next/src/CircularProgress/index.js
**CircularProgress issue:** https://github.com/mui/material-ui/issues/39770
**Material You umbrella issue:** https://github.com/mui/material-ui/issues/29345
- Copy `CircularProgress` from `material` v5
- Fix imports
- fix props in d.ts files
=> [material-next][ProgressIndicator] Copy `CircularProgress` to material next

packages/mui-material-next/src/LinearProgress/LinearProgress.d.ts, packages/mui-material-next/src/LinearProgress/LinearProgress.js, packages/mui-material-next/src/LinearProgress/LinearProgress.test.js, packages/mui-material-next/src/LinearProgress/index.d.ts, packages/mui-material-next/src/LinearProgress/index.js, packages/mui-material-next/src/LinearProgress/linearProgressClasses.ts
**LinearProgress issue:** https://github.com/mui/material-ui/issues/39778
**Material You umbrella issue:** https://github.com/mui/material-ui/issues/29345
- Copy `LinearProgress` from `material` v5
- Fix imports
- fix props in d.ts files
=> [material-next][ProgressIndicator] Copy `LinearProgress` to material next

docs/src/modules/components/ThemeViewer.tsx
This PR closes https://github.com/mui/material-ui/issues/39768. Weirdly, though, we have a token on the branding theme (`typography.fontFamilyCode`) that I wanted to use which would already pass what I inserted here but, for some reason, even with passing the theme and pulling the styled function from `/material/styles` rather than the `/system`, it wasn't picked up. 😕
=> [docs] Fix the default theme viewer font family

packages/mui-material/src/FormControlLabel/FormControlLabel.js
Closes https://github.com/mui/material-ui/issues/39626
Demo: https://codesandbox.io/s/https-github-com-mui-material-ui-pull-39721-rdd4kc?file=/src/App.tsx
=> [material-ui][Checkbox] Asterisk placement aligned correctly

packages/mui-material/src/Autocomplete/Autocomplete.js
Closes https://github.com/mui/material-ui/issues/39474
Demo: https://codesandbox.io/p/sandbox/https-github-com-mui-material-ui-pull-39795-fwdm7f?file=%2Fsrc%2Fapp%2Fpage.tsx%3A1%2C1
There should no console errors when opening the listbox with grouped options
Next.js doesn't like it when a `key` prop is part of an object being spread, here's the related issue in their repo: https://github.com/vercel/next.js/issues/55642
BTW I'm not sure why this doesn't repro when the options are ungrouped, as in both cases they both use `defaultRenderOption`
=> [Autocomplete][material-ui] Fix React key warning in Next.js

docs/data/joy/integrations/material-ui/material-ui.md
Added necessary component that exist on the codesandbox example but not in the docs example.
Without the CssBaseline, colors will not work as expected.
=> [joy-ui][docs] Add `CssBaseline` to integration with Material UI page

packages/mui-material/src/Rating/Rating.js, packages/mui-material/src/Rating/Rating.test.js
Fixes #26380
The hover calculation in the mousemove event only considered the icon width, leading to incorrect hover highlighting when there is spacing between icons. Proper hover calculation is achieved when we consider the container's width regardless of spacing or no spacing.
Before: https://codesandbox.io/s/clever-keldysh-k4wshp?file=/src/App.tsx
After: https://codesandbox.io/s/material-ui-cra-ts-forked-2qjdhh
=> [material-ui][Rating] Fix the hover highlighting for spaced icons

docs/src/layouts/AppFooter.tsx, docs/src/route.ts
Until we have a general place to document company-wide initiatives across all teams & products, linking to the MUI Core roadmap on the website's footer seems a bit more appropriate. I wonder if this page makes more sense than the GitHub project, though... curious to hear from others.
=> [website] Change roadmap link destination

docs/src/components/footer/EmailSubscribe.tsx, docs/src/icons/SvgMuiLogotype.tsx, docs/src/layouts/AppFooter.tsx, docs/src/modules/components/AppLayoutDocsFooter.js
Closes https://github.com/mui/material-ui/issues/39789
This PR repositions the company's logo on the website footer and includes it on the documentation footer.
- Website: https://deploy-preview-39810--material-ui.netlify.app/
- Docs: https://deploy-preview-39810--material-ui.netlify.app/joy-ui/getting-started/
=> [docs-infra] Adjust the website & docs footer

docs/src/modules/components/JoyStartingLinksCollection.js
Linking to the Store "MUI for Figma" design kit listing isn't a good landing place for the Joy UI Figma file link on the Overview page. It's not immediately clear how to actually access the Figma file; visitors would need to scroll down until they see — the fairly hidden — Community file link... which is where I think we can link directly. 
👉 **https://deploy-preview-39725--material-ui.netlify.app/joy-ui/getting-started/#start-now**
=> [joy-ui][docs] Change the design kit link on the Overview page

docs/data/joy/main-features/color-inversion/ColorInversionHeader.js, docs/data/joy/main-features/color-inversion/ColorInversionHeader.tsx
- open https://mui.com/joy-ui/main-features/color-inversion/#header
- click on `Main` button
- Again click on `Main`, menu is still open here. It should be closed, This PR fixes that
Preview https://deploy-preview-39785--material-ui.netlify.app/joy-ui/main-features/color-inversion/#header
=> [joy-ui][docs] Fix menu in color inversion header demo

packages/mui-material/src/Autocomplete/Autocomplete.d.ts, packages/mui-material/src/Autocomplete/Autocomplete.js, packages/mui-material/src/Autocomplete/Autocomplete.spec.tsx
addresses: https://mui-org.slack.com/archives/C041SDSF32L/p1699372422138089
joy added `defaultMuiPrevented` type to `Autocomplete` `onKeyDown`, but it got missed in `material ui` `Autocomplete`.
https://github.com/mui/material-ui/blob/05652f68c7e9273923b341796ac7605864903f77/packages/mui-joy/src/Autocomplete/AutocompleteProps.ts#L370-L375
=> [material-ui][Autocomplete] Add `defaultMuiPrevented` to onKeyDown type

docs/data/base/components/menu/MenuSimple/tailwind/index.js, docs/data/base/components/menu/MenuSimple/tailwind/index.tsx, docs/data/base/components/menu/UseMenu.js, docs/data/base/components/menu/UseMenu.tsx, docs/data/base/components/menu/WrappedMenuItems.js, docs/data/base/components/menu/WrappedMenuItems.tsx
Follow-up to https://github.com/mui/material-ui/pull/38820
This PR fixes the active state from Tailwind demo and the box-shadow from the System demos
👉   https://deploy-preview-39823--material-ui.netlify.app/base-ui/react-menu/
=> [base-ui][Menu] Refine demos

docs/data/base/components/switch/UnstyledSwitchIntroduction/css/index.js, docs/data/base/components/switch/UnstyledSwitchIntroduction/css/index.tsx, docs/data/base/components/switch/UnstyledSwitchIntroduction/system/index.js, docs/data/base/components/switch/UnstyledSwitchIntroduction/system/index.tsx, docs/data/base/components/switch/UnstyledSwitchIntroduction/tailwind/index.js, docs/data/base/components/switch/UnstyledSwitchIntroduction/tailwind/index.tsx, docs/data/base/components/switch/UseSwitchesBasic.js, docs/data/base/components/switch/UseSwitchesBasic.tsx, docs/src/modules/sandbox/CreateReactApp.ts, docs/tailwind.config.js
Follow-up to https://github.com/mui/material-ui/pull/38820
Standardize the border and focus style on Base UI `Switch` demos
👉   https://deploy-preview-39822--material-ui.netlify.app/base-ui/react-switch/
=> [base-ui][Switch] Refine demos

docs/src/modules/components/ApiPage.js
I have noticed this while I was looking at #39704.
Before http://0.0.0.0:3000/material-ui/api/dialog/
After: no more hydration warning. https://deploy-preview-39706--material-ui.netlify.app/material-ui/api/dialog/
A continuation of #35201.
=> [docs-infra] Fix hydration api

packages/mui-material-next/src/Select/Select.d.ts, packages/mui-material/src/Select/Select.d.ts
The `onChange` type is being picked unnecessarily when there is a direct definition of the `onChange` type in `SelectProps`, which already utilizes the `SelectInputProps` type.
It was added in #11041 but was missed to remove it in #20298.
=> [material-ui][Select] Remove unnecessary picking of `onChange` type from SelectInputProps

packages/mui-material-next/src/Switch/Switch.d.ts, packages/mui-material-next/src/Switch/Switch.js, packages/mui-material-next/src/Switch/Switch.test.js, packages/mui-material-next/src/Switch/index.d.ts, packages/mui-material-next/src/Switch/index.js, packages/mui-material-next/src/Switch/switchClasses.ts
**Switch issue:** #39886
**Material You umbrella issue:** #29345
- Copy Switch from `material` v5
- Fix imports
The `Switch` component currently still uses the base component from material-ui. In the next PR, this will be replaced by the `useSwitch` hook.
=> [material-next][Switch] Copy `Switch` to material next

docs/src/components/productBaseUI/BaseUIThemesDemo.tsx
Fixes #38468
I'm uncertain why the transition property `all` had an impact on this.
When using `transition: all`, the document's activeElement is the "View Modal" button when opened. However, with specific transition properties applied, as in this PR, the document's activeElement becomes the Modal when opened allowing the Escape key to close the modal.
While I'm unsure about the reason, it seems to work. I would like to understand why using `transition: all` didn't maintain focus on the modal for allowing closure with the Escape key, or if there's another reason behind it.
Before: https://mui.com/base-ui/
After: https://deploy-preview-39880--material-ui.netlify.app/base-ui/
----
Edit: Also see https://github.com/mui/material-ui/pull/38255#issuecomment-1662945897.
=> [website] Fix modal not being closed with the escape key on the Base UI page

docs/data/joy/components/alert/alert.md, docs/data/joy/components/autocomplete/autocomplete.md, docs/data/joy/components/avatar/avatar.md, docs/data/joy/components/badge/badge.md, docs/data/joy/components/breadcrumbs/breadcrumbs.md, docs/data/joy/components/button/button.md, docs/data/joy/components/checkbox/checkbox.md, docs/data/joy/components/chip/chip.md, docs/data/joy/components/circular-progress/circular-progress.md, docs/data/joy/components/divider/divider.md, docs/data/joy/components/input/input.md, docs/data/joy/components/linear-progress/linear-progress.md, docs/data/joy/components/link/link.md, docs/data/joy/components/modal/modal.md, docs/data/joy/components/radio-button/radio-button.md, docs/data/joy/components/select/select.md, docs/data/joy/components/sheet/sheet.md, docs/data/joy/components/slider/slider.md, docs/data/joy/components/snackbar/snackbar.md, docs/data/joy/components/stack/stack.md, docs/data/joy/components/switch/switch.md, docs/data/joy/components/table/table.md, docs/data/joy/components/tabs/tabs.md, docs/data/joy/components/tooltip/tooltip.md, docs/data/material/components/stack/stack.md, docs/data/material/components/transfer-list/transfer-list.md, docs/src/modules/components/ComponentLinkHeader.js
We have these components covered in Joy UI now: https://www.figma.com/community/file/1293288155415213351
Preview: https://deploy-preview-39955--material-ui.netlify.app/joy-ui/react-alert/.
---
I have worked a bit on this because Joy UI Figma file downloads are so low, no designers/developers seem to care
https://docs.google.com/spreadsheets/d/1BXZQmzVCzSkzyOedSnRtG_1gInU-_--Z-jSZNYjAE2k/edit#gid=0
=> [docs] Show design links on Joy UI

docs/src/pages/versions/versions.md
Before https://mui.com/versions/#release-schedule
After https://deploy-preview-39953--material-ui.netlify.app/versions/#release-schedule
=> [docs] Fix use of quote in markdown

packages/mui-material-next/src/IconButton/IconButton.d.ts, packages/mui-material-next/src/IconButton/IconButton.js, packages/mui-material-next/src/IconButton/IconButton.test.js, packages/mui-material-next/src/IconButton/iconButtonClasses.ts, packages/mui-material-next/src/IconButton/index.d.ts, packages/mui-material-next/src/IconButton/index.js
Part of https://github.com/mui/material-ui/issues/39943
This PR copies `IconButton` to `material-next` with minimal changes
=> [IconButton][material-next] Copy IconButton to material-next

docs/package.json, docs/postcss.config.js, package.json
Fixes the warning
Fix regression introduced in #39694
=> [docs] Fix nested CSS warning

docs/data/joy/getting-started/templates/profile-dashboard/components/MyProfile.tsx
Removed `fontWeight: '600'` from the tabs to prevent the layout shift based on [this comment
](https://github.com/mui/material-ui/pull/40017#issuecomment-1826844322)
👉 https://deploy-preview-40022--material-ui.netlify.app/joy-ui/getting-started/templates/profile-dashboard/
=> [joy-ui][templates] Fix layout shift on Profile template

renovate.json
Improve lerna's renovate package rules by adding a description and a maximum allowed version rather than disabling it altogether.
=> [core] Improve lerna's renovate package rules

packages/mui-base/src/Dropdown/Dropdown.test.tsx, packages/mui-base/src/useMenu/useMenu.ts
closes: #39941
https://codesandbox.io/s/recursing-meadow-mqdl28?file=/src/Demo.tsx
https://codesandbox.io/s/flamboyant-microservice-htz9v4
=> [base-ui][Menu] Fix navigation of items when 1st item is disabled

docs/next.config.js, docs/nextConfigDocsInfra.js
I saw this in MUI X.
https://webpack.js.org/plugins/environment-plugin/#usage-with-default-values
First seen in:
Related to https://github.com/mui/material-ui/pull/39608#issuecomment-1785232786
=> [docs-infra] Env variables should be string

docs/data/system/experimental-api/css-theme-variables/css-theme-variables.md
=> [system][docs] Fix typo on the CSS theme variables page

docs/data/material/components/tabs/tabs.md
Just a few text adjustments to make the text description more concise. 
Previously, it was possible to understand that scrolling would be automatic on the desktop, and the properties would only be necessary on mobile. However, what the text actually means is that the props, when applied, will only display the *buttons* on the desktop version.
| Current | New |
| <img width="400" alt="Screenshot 2023-11-29 at 09 50 31" src="https://github.com/mui/material-ui/assets/37222944/56a45e7f-b3ff-44e9-a080-f396ae66a768"> | <img width="400" alt="Screenshot 2023-11-29 at 09 50 01" src="https://github.com/mui/material-ui/assets/37222944/c5ee3f92-af75-4645-8c1b-89c5ceb08882"> |
=> [material-ui][tabs] Refine scrollable tabs description

docs/pages/careers/ROLE_TEMPLATE.md, docs/pages/careers/accessibility-engineer.md, docs/pages/careers/design-engineer-x-grid.md, docs/pages/careers/design-engineer.md, docs/pages/careers/designer.md, docs/pages/careers/developer-experience-engineer.md, docs/pages/careers/engineering-manager.md, docs/pages/careers/full-stack-engineer.md, docs/pages/careers/head-of-operations.md, docs/pages/careers/people-operation-manager.md, docs/pages/careers/product-engineer.md, docs/pages/careers/product-manager.md, docs/pages/careers/product-marketing-manager.md, docs/pages/careers/react-community-engineer.md, docs/pages/careers/react-engineer-core.md, docs/pages/careers/react-engineer-x-charts.md, docs/pages/careers/react-engineer-x-grid.md, docs/pages/careers/react-engineer-x.md, docs/pages/careers/react-tech-lead-core.md, docs/pages/careers/react-tech-lead-x-grid.md, docs/pages/careers/senior-designer.md, docs/pages/careers/support-agent.md, docs/pages/careers/technical-product-manager.md, docs/pages/careers/technical-recruiter.md
I wasn't sold on why we needed this Design Engineer role for the Data Grid (more than others). But since the presentation of the goal for 2024, it now makes a lot more sense to me. I have updated https://www.notion.so/mui-org/Design-Engineer-xGrid-3b9a645faa434fe18fa8ebd5ed2fc086 accordingly.
Preview: https://deploy-preview-40016--material-ui.netlify.app/careers/design-engineer-x-grid/#why-were-hiring
=> [website] Add why Design Engineer for data grid

packages/mui-material/src/InputLabel/InputLabel.js, packages/mui-material/src/Select/SelectInput.js
Reverts mui/material-ui#39414
The change affected native form submission behavior which was reported in https://github.com/mui/material-ui/issues/40128
I've also added a regression test in https://github.com/mui/material-ui/pull/40176
=> Revert "[Select][material-ui] Add name to hidden input element"

packages/mui-joy/src/Input/Input.test.tsx, packages/mui-joy/src/Input/Input.tsx, packages/mui-joy/src/Input/useForwardedInput.ts, packages/mui-joy/src/Radio/Radio.test.tsx, packages/mui-joy/src/Radio/Radio.tsx
https://codesandbox.io/s/vigorous-leaf-l4ynj3?file=/src/index.tsx
https://codesandbox.io/s/elastic-sunset-7fykcs?file=/src/Demo.tsx
In both `Input` and `Radio` `disabled` prop from theme were taking precedence over `disabled` prop from `FormControl`. This PR fixes the issue.
=> [joy-ui][Radio][Input] Fix inheritance of disabled prop

packages/mui-material/src/styles/components.d.ts, packages/mui-material/src/styles/variants.d.ts
Refactored `ComponentsVariants` type to accept a `Theme` parameter. Doing so makes the `ComponentsVariants` type share the same signature as the generic `ComponentsOverrides` type. Since both types are used when overriding a component's style, the callback functions should be identical.
The primary use case is for consumers, like myself, who use a custom Theme interface. We do this through augmenting the `createTheme` module, which works fine, except for this one instance. The current implementation type-checks the `theme` parameter correctly in the `styleOverrides` property, but not in the `variants` property. Here is an example that might better explain this:
```ts
styleOverrides: {
// Here `theme` is typecasted by the argument passed to the Components interface  
root: ({ theme }) => { …
```
=> [material-ui] Refactor ComponentsVariants type into a generic

docs/data/material/components/popper/PositionedPopper.js, docs/data/material/components/popper/PositionedPopper.tsx
This PR places content of Popper above drawer so that text inside popper is clearly visible
preview: https://deploy-preview-40170--material-ui.netlify.app/material-ui/react-popper/#positioned-popper
=> [material-ui][docs][Popper] Update Positioned Popper demo styles

.github/ISSUE_TEMPLATE/1.bug.yml, .github/ISSUE_TEMPLATE/2.feature.yml, .github/ISSUE_TEMPLATE/3.rfc.yml, .github/ISSUE_TEMPLATE/4.docs-feedback.yml, .github/ISSUE_TEMPLATE/5.priority-support.yml, .github/workflows/ensure-triage-label.yml, .github/workflows/mark-duplicate.yml
Follow-up to https://github.com/mui/material-ui/pull/40181
=> [core] Update workflows and issue templates to reflect the updated label

docs/data/material/guides/nextjs/nextjs.md
change intalling to installing
=> [material-ui][docs] Fix typo in the Next.js integration page

packages/mui-styled-engine-sc/src/index.d.ts, packages/mui-styled-engine/src/index.d.ts
Repository for testing the changes: https://github.com/mnajdova/mui-styled-engine-sc-theme-type
Check the theme type in the three use-cases in App.tsx.
Fixes https://github.com/mui/material-ui/issues/39783. The types were taken and adopted from @mui/styled-engine.
=> [styled-engine-sc] Fix `theme` being of type any

docs/data/material/discover-more/related-projects/related-projects.md
As suggested by @oliviertassinari in https://github.com/sjdemartini/mui-tiptap/pull/81#issue-1781366193, this proposes adding a link to [mui-tiptap](https://github.com/sjdemartini/mui-tiptap) as a rich text option in the Material UI docs on related project components. (I noticed we recently crossed 100 stars :D )
Thanks in advance for considering, and for the work you all do maintaining such a valuable component library!
=> [material-ui][docs] Update the related projects page to list `mui-tiptap` for rich text

docs/src/modules/components/AppSearch.js, docs/translations/translations.json
This PR adds several design adjustments to the Algolia search modal. Felt like it needed a little bit of a revision there, mainly as it was sort of broken in dark mode with the low background opacity. Ended up also taking advantage of the opportunity to refresh the default content list, displaying stuff about every MUI product as opposed to just Material UI-focused ones.
https://deploy-preview-40186--material-ui.netlify.app/ — And, here are visual diffs for an easier grasp of the changes:
| <img width="901" alt="Screen Shot 2023-12-12 at 10 24 40" src="https://github.com/mui/material-ui/assets/67129314/d5f17b2d-cd7d-4a2b-bbbe-1603387473ec"> | <img width="901" alt="Screen Shot 2023-12-12 at 10 24 43" …
=> [docs-infra] Uplift the Algolia search modal design

docs/data/material/customization/theme-components/theme-components.md, packages/mui-styled-engine-sc/src/index.d.ts, packages/mui-styled-engine/src/index.d.ts, packages/mui-system/src/createStyled.js, packages/mui-system/src/createStyled.test.js, packages/mui-system/src/styled.test.js
This PR adds a new feature in the variant's API - the props callback. The API looks like this:
```jsx
components: {
MuiTest: {
variants: [
{
props: ({ size }) => size === 'large',
style: {
width: '400px',
height: '400px',
},
},
{
props: ({ size }) => size === 'small',
style: {
width: '200px',
height: '200px',
},
},
],
},
},
});
```
=> [system] Support props callback in the variant's definition

docs/pages/experiments/docs/markdown.md, docs/src/modules/components/MarkdownElement.js
I have just recently learned about this neat CSS property called [`box-decoration-break: clone`](https://developer.mozilla.org/en-US/docs/Web/CSS/box-decoration-break) and thought of using it for our inline code block. 😌 Instead of just being a solid block, it can now break into multiple lines while preserving the overall box look.
| <img width="831" alt="Screenshot 2023-12-20 at 16 09 00" src="https://github.com/mui/material-ui/assets/67129314/d1ee77e8-cc36-450e-a3c7-ad072888eb27"> | <img width="831" alt="Screenshot 2023-12-20 at 16 09 16" src="https://github.com/mui/material-ui/assets/67129314/027b442e-93e4-4198-b9be-0c94f7b2f0ac"> |
=> [docs-infra] Add polish to the inline code block

docs/data/base/getting-started/overview/overview.md, docs/data/joy/getting-started/overview/overview.md, docs/data/material/getting-started/overview/overview.md, docs/data/system/getting-started/overview/overview.md, docs/pages/base-ui.tsx, docs/pages/core.tsx, docs/pages/index.tsx, docs/pages/material-ui.tsx, docs/pages/x.tsx, docs/src/components/header/HeaderNavDropdown.tsx, docs/src/components/productCore/CoreProducts.tsx, packages/mui-base/README.md, packages/mui-base/package.json, packages/mui-joy/README.md, packages/mui-joy/package.json, packages/mui-material/README.md, packages/mui-material/package.json, packages/mui-system/README.md, packages/mui-system/package.json
Act on https://groups.google.com/a/mui.com/g/devex/c/Y-p_Qv2sDlA. The idea is to have a single long format, with concatenation based on the context (e.g. for SEO, we need to mention React, in the docs, we don't), but with the same content in as many places as possible (GitHub repository description, npm description, social cards, Twitter account description, etc.).
SEO title: between 50 and 60 characters
SEO description: between 120 and 158 characters
One-line mobile view: ~60 characters
Two lines: between 120 and 158 characters
- SEO description: Material UI is an open-source React component library that implements Google's Material Design. It's comprehensive and can be used in production out of the box.
- Two lines: An open-source React component library that implements Google's …
=> [docs] Fix SEO regression

docs/data/material/components/tooltips/tooltips.md
https://deploy-preview-40283--material-ui.netlify.app/material-ui/react-tooltip/#showing-and-hiding
Closes #40247 by removing the outdated "as shown in the Controlled Tooltips demo above" from doc.
=> [material-ui][docs] Update the "showing and hiding" section on the Tooltip page

docs/data/joy/getting-started/templates/files/App.tsx
This got flagged in https://app.ahrefs.com/site-audit/3524616/98/data-explorer?columns=pageRating%2Curl%2ChttpCode%2CcontentType%2Csize%2CloadingTime%2CincomingImage&filterId=ad5863095a819f761d42b32931a29649&issueId=c64d8113-d0f4-11e7-8ed1-001e67ed4656&sorting=-size
https://mui.com/joy-ui/getting-started/templates/files/
=> [docs][joy-ui] Fix image size on the Files template

docs/src/components/action/ComponentShowcaseCard.tsx, docs/src/components/action/InfoCard.tsx, docs/src/components/home/MaterialDesignDemo.tsx, docs/src/components/home/Testimonials.tsx, docs/src/components/home/ValueProposition.tsx, docs/src/modules/components/BaseUIComponents.js, docs/src/modules/components/MaterialUIComponents/MaterialInputComponents.js, docs/src/modules/components/MaterialUIComponents/MaterialUtilComponents.js
Act on https://github.com/mui/material-ui/pull/40256#discussion_r1435873800
Before
https://deploy-preview-40311--material-ui.netlify.app/material-ui/all-components/
After
https://deploy-preview-40313--material-ui.netlify.app/material-ui/all-components/
We reduce by half the use of the network.
---
I'm also working a bit on the images, we only want loading="lazy" for images below the fold, as otherwise, it means that the browser can't start loading images until it knows their position. We already know that the first images will be visible, so we can use loading="eager" for them.
=> [docs] Reduce network use on the All Components pages

packages/mui-material-next/src/Slider/useSliderElementsOverlap.ts
Replace `lodash`'s `debounce` and `isEqual` with internal utils in `useSliderElementsOverlap`. With this we avoid adding `lodash` as a dependency.
=> [material-next][Slider] Replace lodash with internal utils

packages/mui-base/src/useSlider/useSlider.ts
As suggested by @pixelass in [issue 39365](https://github.com/mui/material-ui/issues/39365), I removed unnecessary eventListener passive options and added them where needed
=> [base-ui][useSlider] rearrange passive option in eventlisteners

packages/mui-material-next/src/MenuItem/MenuItem.spec.tsx
Import `MenuItem` from `material-next` in spec, not `material`.
=> [material-next][MenuItem] Fix spec import

docs/data/material/components/popover/VirtualElementPopover.js, docs/data/material/components/popover/VirtualElementPopover.tsx
Preview: https://deploy-preview-40239--material-ui.netlify.app/material-ui/react-popover/#virtual-element
Closes #40137
The issue was that with the Popover opening, the selection lost focus on Safari, disabling the autoFocus fixes this issue.
=> [material-ui][docs] Adding autoFocus on Virtual Popover

docs/data/joy/getting-started/templates/order-dashboard/components/OrderTable.tsx
This template wasn't usable IMHO, I'm a new user, overwhelmed, short in time: I see this, I close my tab 😄
https://github.com/mui/material-ui/assets/3165635/734d9a14-b4ed-4815-a8ae-878592e26100
http://0.0.0.0:3000/joy-ui/getting-started/templates/order-dashboard/
The error is gone. There are still others in the Joy UI templates, but at least this massive spam is gone.
---
Noticed by chance while I was fixing #40315. Now, to be fair, I still don't think that this template is fully usable in production for a developer if you compare the report of:
- https://pagespeed.web.dev/
- https://validator.w3.org/
- https://chromewebstore.google.com/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh
- console warnings
between https://ui.shadcn.com/examples/dashboard and …
=> [docs][joy-ui] Fix dashboard template console errors

docs/data/material/guides/nextjs/nextjs.md, docs/data/material/pages.ts, docs/translations/translations.json, packages/mui-material-nextjs/README.md, packages/mui-material-nextjs/package.json
A quick polish on the docs of #39947.
https://deploy-preview-40317--material-ui.netlify.app/material-ui/guides/nextjs/
- Fix broken link
- Fix the wrong git diff format
- Fix horizontal format
- Clarify how to extend `getInitialProps`
=> [material-ui][docs] Polish the Next.js integration page

docs/pages/experiments/md3/buttons.tsx, packages/mui-material-next/src/styles/Theme.types.ts, packages/mui-material-next/src/styles/extendTheme.ts
Move the `ref.palette` out of `colorSchemes` as it doesn't depend on the color mode (`light | dark`). Having it inside the `colorSchemes.light` might confuse users. The change in usage is the following:
```diff
const customTheme = extendTheme({
-  colorSchemes: {
-   light: {
ref: {
palette: {
// ...
},
},
-     },
-  },
});
```
=> [material-next][theme] Move ref palette out of color schemes

packages/mui-material-next/CONTRIBUTING.md
I just updated some version references and outdated links.
=> [material-next] Update CONTRIBUTING guide given v6/v7 rescheduling

docs/src/modules/components/AppLayoutDocsFooter.js
We can't have the links be a relative URL `/blog/` they need to be an absolute URL `https://mui.com/blog/`. This is because once the current version of the docs is archived, e.g. to a subdomain: https://v4.mui.com/, we don't want the links to the blog to point to https://v4.mui.com/blog/
---
Future. Some docs like Hashicorp store their docs as subfolders https://developer.hashicorp.com/terraform/language/v1.7.x, we could do this, it's not hard, allowing to revert this PR, but we don't do it currently. I have no idea if a subfolder is better than a subdomain for historized docs, we never really poured much thought into it.
=> [docs-infra] Fix footer links to link to the main domain

packages/mui-material/package.json, packages/mui-material/src/TabScrollButton/TabScrollButton.test.js, packages/mui-material/src/TablePagination/TablePagination.test.js, packages/mui-material/src/TableSortLabel/TableSortLabel.test.js, packages/mui-material/src/Tabs/Tabs.test.js
A follow-up to #40398. I missed a cycle between @mui/material and @mui/icons-material.
=> [code-infra] Break package dependency cycle between @mui/material and @mui/icons-material

docs/src/modules/components/MarkdownLinks.js
Inspired by #40313. The idea is to reproduce what we do for the side nav but for all the markdown links.
Before: https://deploy-preview-40310--material-ui.netlify.app/material-ui/getting-started/usage/
https://github.com/mui/material-ui/assets/3165635/548ca3ed-6191-4d37-8d11-3b353c063f25
After: https://deploy-preview-40314--material-ui.netlify.app/material-ui/getting-started/usage/
https://github.com/mui/material-ui/assets/3165635/6cd53646-11f3-4cd3-9f58-dba623dea713
We save about 100-200ms in the page transition, that time here:
This is a significant UX improvement on my end, but there is still a lot we could do to make the docs feel super responsive. It doesn't feel great yet.
---
In the future, we should be able to make the whole markdown a server-side component with Next.js link as …
=> [docs-infra] Prefetch pages on hover

docs/src/modules/components/ComponentLinkHeader.js
Fix one of the reports from https://pagespeed.web.dev/analysis/https-mui-com-material-ui-react-button/zomrvia5y0?form_factor=desktop
We were not respecting this rule https://dequeuniversity.com/rules/axe/4.7/label-content-name-mismatch.
Part of the value of this fix is to remove the noise from the docs-infra so we can more easily spot the issues on our components.
=> [docs-infra] Fix a11y violation rule

docs/src/modules/components/ApiPage.js, docs/src/modules/components/ApiPage/list/ClassesList.tsx, docs/src/modules/components/ApiPage/list/ExpandableApiItem.tsx, docs/src/modules/components/ApiPage/list/PropertiesList.tsx, docs/src/modules/components/ApiPage/list/SlotsList.tsx, docs/src/modules/components/ApiPage/sections/PropertiesSection.js, docs/src/modules/components/ApiPage/sections/ToggleDisplayOption.tsx, docs/src/modules/components/ApiPage/table/PropertiesTable.tsx, docs/src/modules/components/ComponentsApiContent.js
Fix a small issue reported in https://pagespeed.web.dev/analysis/https-mui-com-base-ui-react-popper-components-api/enf7e9ejj5?form_factor=desktop
=> [docs-infra] Fix missing button aria-label

docs/pages/joy-ui/api/menu.json, packages/api-docs-builder-core/baseUi/generateApiLinks.ts, packages/api-docs-builder-core/baseUi/getBaseUiComponentInfo.test.ts, packages/api-docs-builder-core/baseUi/getBaseUiComponentInfo.ts, packages/api-docs-builder-core/baseUi/getBaseUiHookInfo.ts, packages/api-docs-builder-core/joyUi/getJoyUiComponentInfo.ts, packages/api-docs-builder-core/materialUi/getMaterialUiComponentInfo.test.ts, packages/api-docs-builder/ApiBuilders/ComponentApiBuilder.ts, packages/api-docs-builder/buildApiUtils.ts, packages/mui-joy/src/Menu/Menu.tsx
Not the cleanest solution but it works to solve 
https://app.ahrefs.com/site-audit/3524616/99/data-explorer?columns=pageRating%2Curl%2Ctraffic%2ChttpCode%2CredirectChainUrls%2CisRedirectLoop%2CincomingAllLinks%2CincomingRedirect%2Corigin&filterId=808b08e88c934ee19e04fdec4ed87a5a&issueId=c64d12c1-d0f4-11e7-8ed1-001e67ed4656&sorting=-pageRating
---
**Off-topic.** When it comes to my own use of the components, the UX before #35938 likely work better with my workflows. Now, some would clearly prefer the new UX. Still, I think that it means that for the new approach to have a higher chance of winning, we have to fill the gaps with the older one:
1. The title of the different pages are the same. https://mui.com/base-ui/react-input/ vs. https://mui.com/base-ui/react-input/components-api/ vs. …
=> [docs] Fix 301 link to Base UI

docs/src/components/productBaseUI/components/BaseInputDemo.tsx, docs/src/components/productBaseUI/components/BaseMenuDemo.tsx, docs/src/components/productBaseUI/components/BaseTabsDemo.tsx, docs/tailwind.config.js
Closes https://github.com/mui/material-ui/issues/40223
https://deploy-preview-40231--material-ui.netlify.app/base-ui
This PR removed the "Unstyled" suffix from the Base UI component imports on the page's component section. 
Also took advantage of the opportunity to fix some stray styles.
=> [website] Fix Base UI page's component section imports & styles

packages/mui-material-nextjs/src/v13-pagesRouter/pagesRouterV13.tsx
The `createEmotionServer` has to be called directly after cache creation due to the side effect of [`cache.compat = true`](https://github.com/emotion-js/emotion/blob/b0014b4edc6be047e0a94d8c627d4e52ecccd371/packages/server/src/create-instance/index.js#L12), otherwise the `<style>` tag will not come with the HTML string from the server.
=> [material-nextjs] Fix order of emotion server

docs/data/material/components/accordion/AccordionExpandDefault.js, docs/data/material/components/accordion/AccordionExpandDefault.tsx, docs/data/material/components/accordion/AccordionExpandIcon.js, docs/data/material/components/accordion/AccordionExpandIcon.tsx, docs/data/material/components/accordion/AccordionTransition.js, docs/data/material/components/accordion/AccordionTransition.tsx, docs/data/material/components/accordion/AccordionUsage.js, docs/data/material/components/accordion/AccordionUsage.tsx, docs/data/material/components/accordion/DisabledAccordion.js, docs/data/material/components/accordion/DisabledAccordion.tsx, docs/data/material/components/accordion/accordion.md
Part of #39952. Adds documentation for accordion's complementary components.
https://deploy-preview-40284--material-ui.netlify.app/material-ui/react-accordion/#introduction
=> [material-ui][docs] Revise the Accordion page

docs/pages/careers.tsx, docs/pages/careers/developer-advocate.md
I don't think it would work to have a person with no product design sensibility in this new role we open. The most successful content creators I see in this space match this criterion: https://www.notion.so/mui-org/Developer-Advocate-DevEx-Engineer-634b2a699266480abf8663c045768902?pvs=4#a6fc0d1aec064fddb2f167e5e7b194aa.
Based on the discussion in https://groups.google.com/a/mui.com/g/devex/c/FOyh_tMixgQ, being clearer about it would help. I structured it so that there is a clear graduation between "required" and "nice to have". The bar is set lower than for our "Designer Engineer" roles (because otherwise we will search a unicorn forever).
=> [website] Evolve the Developer Advocate role

docs/next.config.js, docs/nextConfigDocsInfra.js, docs/tsconfig.json
This catches issues like in https://github.com/mui/mui-toolpad/pull/3026, proof:
It seems that we won't see a next.config.ts support anytime soon: https://github.com/vercel/next.js/issues/5318. But why not lint the file anyway. The alternative would be to have a runtime check of the params like done by Next.js in https://github.com/vercel/next.js/pull/58247 but I don't know, TypeScript feels meant for this purpose.
Assuming that all current & future projects that use docs-infra have to link the config file, it should be OK. We are not playing this card https://github.com/facebook/docusaurus yet.
Now, to be fair, I like how zod also allows us to flag outdated params, ones that do nothing https://github.com/vercel/next.js/blob/0fc1d9e982c9fe2a8da23d95943cd161de4c3178/packages/next/src/server …
=> [docs-infra] Add types for withDocsInfra

nx.json
Configure Lerna to look for project dependencies when running the `build` command.
This should solve the issue described in https://github.com/mui/material-ui/pull/40426#discussion_r1442768438
=> [code-infra] Configure build dependencies in nx

docs/src/modules/components/ApiPage/table/ClassesTable.tsx, docs/src/modules/components/ApiPage/table/PropertiesTable.tsx, docs/src/modules/components/ApiPage/table/SlotsTable.tsx, docs/src/modules/components/ApiPage/table/StyledTableContainer.tsx
I was triggered by `overflow: hidden`, this is 99% of the time a red flag. Turns out, we can improve the table view. The solution reproduces the stable used by the Material UI Table (same as Bootstrap).
Before https://mui.com/base-ui/react-menu/components-api/#menu-item-slots
After https://deploy-preview-40476--material-ui.netlify.app/base-ui/react-menu/components-api/#menu-item-slots
=> [docs-infra] Fix API table full-width

docs/src/modules/components/ApiPage.js, docs/src/modules/components/ApiPage/list/ClassesList.tsx, docs/src/modules/components/ApiPage/list/PropertiesList.tsx, docs/src/modules/components/ApiPage/list/SlotsList.tsx, docs/src/modules/components/ApiPage/sections/PropertiesSection.js, docs/src/modules/components/ApiPage/sections/SlotsSection.tsx, docs/src/modules/components/ApiPage/table/ClassesTable.tsx, docs/src/modules/components/ApiPage/table/PropertiesTable.tsx, docs/src/modules/components/ComponentsApiContent.js
Fix https://github.com/mui/material-ui/pull/40395#issuecomment-1874534065
Before: https://deploy-preview-40395--material-ui.netlify.app/base-ui/react-menu/components-api/#menu-item-classes-focusVisible
After: https://deploy-preview-40450--material-ui.netlify.app/base-ui/react-menu/components-api/#menu-item-classes-focusVisible
=> [docs-infra] Fix anchor links in API pages

package.json, pnpm-lock.yaml
Removed packages duplicated between dependencies and devDependencies. They are used by the Netlify function, so they should live in dependencies.
Also log warnings:
=> [core] Remove duplicate devDependencies

.eslintrc.js, docs/data/joy/main-features/color-inversion/ColorInversionAnyParentStyled.js, docs/data/joy/main-features/color-inversion/ColorInversionAnyParentStyled.tsx, docs/data/material/components/drawers/SwipeableEdgeDrawer.js, docs/data/material/components/drawers/SwipeableEdgeDrawer.tsx, docs/data/material/components/material-icons/SearchIcons.js, docs/src/pages/premium-themes/onepirate/modules/form/FormFeedback.js, docs/src/pages/premium-themes/onepirate/modules/form/FormFeedback.tsx, docs/src/pages/premium-themes/onepirate/modules/views/ProductHeroLayout.js, docs/src/pages/premium-themes/onepirate/modules/views/ProductHeroLayout.tsx, packages/eslint-plugin-material-ui/src/index.js, packages/eslint-plugin-material-ui/src/rules/no-styled-box.js, packages/eslint-plugin-material-ui/src/rules/no-styled-box.test.js, packages/mui-joy/src/colorInversion/colorInversionUtils.spec.tsx, packages/mui-joy/src/colorInversion/colorInversionUtils.test.tsx, packages/mui-system/src/Box/Box.spec.tsx
Something I saw while reviewing https://app.ashbyhq.com/jobs/ee40c71f-2807-4235-a73f-76a397a1e661/candidate-pipeline/active/right-side/candidates/76bcaaf9-3644-497a-b93c-3230b5119b26/applications/331a983d-10a0-4459-b417-ea76bb29aa96/feed. 
We exclusively use the `sx` prop to style with Box, we don't use the flattened prop https://mui.com/system/react-box/#system-props in our codebase (I would be more than happy to deprecate this). So it doesn't make much sense to me to have styled(Box). It's not good for performance.
=> [system] Fix all use of styled(Box)

docs/public/static/components-gallery/base-theme.css
This is a follow-up PR to #40113, where I added some tiny visual tweaks to button box shadows and border-radius.
https://deploy-preview-40487--material-ui.netlify.app/experiments/base/components-gallery/
=> [docs][base-ui] Visual tweaks to the plain CSS theme stylesheet

packages/mui-material/src/Select/Select.test.js
Related to https://github.com/mui/material-ui/issues/40128
This PR adds a test to ensure that the Select's value is not included in the `FormData` of a form if the `name` prop/attribute is not explicitly provided
=> [Select][material-ui] Add form submission regression test

packages/mui-material/src/ClickAwayListener/index.ts
Removes a tailing comma so it is compatible with older supported TypeScript versions.
Fixes #38837 
The benefit is mui v5 works with older supported TypeScript versions. Important when upgrading older projects from material-ui v4.
```ts
node_modules/@mui/material/ClickAwayListener/index.d.ts:1:45 - error TS1005: ',' expected.
1 export { ClickAwayListener as default, type ClickAwayListenerProps, } from '@mui/base/ClickAwayListener';
~~~~~~~~~~~~~~~~~~~~~~
Found 1 error.
```
You can reproduce the error using TypeScript 4.4.3.
```
cd examples/material-ui-cra-ts
npm install
./node_modules/.bin/tsc --version
Version 4.4.3
./node_modules/.bin/tsc
node_modules/@mui/material/ClickAwayListener/index.d.ts:1:45 - error TS1005: ',' expected.
1 export { ClickAwayListener as default, type …
```
=> [material-ui][ClickAwayListener] Fix export of types

packages/mui-material/src/Dialog/Dialog.test.js
=> [material-ui][Dialog] Remove deprecated onBackdropClick from Dialog tests

.circleci/config.yml
The problem was solved differently between:
- https://github.com/mui/material-ui/pull/39131/files
- https://github.com/mui/mui-x/pull/9413/files
This PR matches the solution. It looks like Lukas was right, this env variable is already defined earlier.
Same as https://github.com/mui/mui-x/pull/11607
=> [core] Sync playwright cache between MUI X and Material UI

package.json
I guess "deploy" points to `pnpm deploy` command before looking at `docs deploy` so I switch to `run deploy` instead.
**Before**:
**After**:
=> [code-infra] Add `run` command to deploy docs

packages/mui-joy/src/ModalDialog/ModalDialogProps.ts
This update fixes a type error in ModalDialog layout props that cannot be overridden with ModalDialogPropsLayoutOverrides.
closes #40331
=> [joy-ui][ModalDialog] Fix ModalDialog layout prop override

docs/src/modules/components/AppTableOfContents.js
This is dead code, as far as I know, we won't use this again.
We already have an app banner notification for this, this is legacy:
---
Edit, I reverted this in the end, it's not that a bad idea after all, Base UI users sounds like good matches.
~I think we learned that people who use Material UI are not the people we should hire to work on it. It much better to hire the people who think Material UI is crap and who had to rebuild it themselves because of it (e.g. my own story, and what we are doing again today, Material UI is stuck 1,2 years in the past).~
~For Base UI and MUI System, maybe the rationale would be different. People who use Base UI could be a great fit for Material UI. So why not keep this, but then the design is outdated, so we would need to redo it anyway, and better …
=> [docs-infra] Remove old tocs banners

docs/src/modules/components/ApiPage/ApiAlert.tsx, docs/src/modules/components/ApiPage/ApiWarning.tsx, docs/src/modules/components/ApiPage/list/ClassesList.tsx, docs/src/modules/components/ApiPage/list/ExpandableApiItem.tsx, docs/src/modules/components/ApiPage/list/PropertiesList.tsx, docs/src/modules/components/ApiPage/sections/ClassesSection.tsx, docs/src/modules/components/ApiPage/table/ClassesTable.tsx, docs/src/modules/components/ApiPage/table/PropertiesTable.tsx, docs/translations/translations.json, packages/api-docs-builder/ApiBuilders/ComponentApiBuilder.ts, packages/api-docs-builder/utils/parseSlotsAndClasses.ts, packages/docs-utilities/ComponentClassDefinition.ts
- Standardize API page warnings
- Add "DEPRECATED" label to props and class lists
- Add support for class deprecation
Details of each are below
Introduce the `ApiWarning` component to standardize all API page warning alerts: deprecations and "needs to be able to hold a ref" alerts on both table and list views.
**This doesn't include other warnings throughout the docs**, which might be something we should look into but goes beyond the scope of this PR.
This indicates deprecations when lists are collapsed. Without this change, deprecations cannot be seen until the prop is expanded.
This is required, for example, for https://github.com/mui/material-ui/pull/40418. Here's [an example of how it would look like](https://deploy-preview-40418--material-ui.netlify.app/material-ui/api/accordion-summa …
=> [docs-infra] Improve API page deprecation info

packages/mui-material-nextjs/package.json, pnpm-lock.yaml
closes #40522 
This PR fixes the NextJS integration package release script. After migrating from yarn to pnpm, the entire "mui-material-nextjs" folder is being published, which breaks imports of package components.
=> [material-nextjs] Fix release script

docs/src/modules/components/Ad.js, docs/src/modules/components/AdCarbon.js, docs/src/modules/components/AppLayoutDocs.js, docs/src/modules/components/ad.styles.js, docs/translations/translations.json
I was annoyed by this today while browsing the docs on my phone. This layout shift is not fun:
https://github.com/mui/material-ui/assets/3165635/ad6ecf53-6fec-4041-8f04-2844f6e35d2c
After, the layout shift can still happen (for the longest possible ad descriptions), but it's a lot less likely:
https://github.com/mui/material-ui/assets/3165635/7b8ad38f-426b-45f6-8b48-bd3725b20ef3
https://deploy-preview-40582--material-ui.netlify.app/material-ui/react-checkbox/
=> [docs-infra] Minimize ad layout shift on mobile

packages/mui-codemod/codemod.js
Fixes #40362
----
As the codemod.js script lacks tests, I performed local testing with the following steps:
1. Navigate to the `packages/mui-codemod` directory (`cd packages/mui-codemod`).
2. Create a new json file for testing by adding a `package.json` file under the `src/v5.0.0/mui-replace.test` folder and adding the following code:
```json
{
"name": "mui-codemods",
"version": "1.0.0",
"description": "",
"scripts": {
"test": "echo \"Error: no test specified\" && exit 1"
},
"author": "",
"license": "MIT",
"dependencies": {
"@material-ui/core": "^4.11.0",
"@material-ui/icons": "^4.9.1",
"@material-ui/lab": "4.0.0-alpha.57"
}
}
```
3. Execute `node codemod.js v5.0.0/mui-replace ./src/v5.0.0/mui-replace.test`. This command replaces the occurrences of `@material-ui/*` with `@mui/*`. If the …
=> [codemod] Allow `json` files to be transformed

packages/mui-material/src/Badge/Badge.js, packages/mui-material/src/zero-styled/index.d.ts, packages/mui-material/src/zero-styled/index.js, packages/zero-runtime/package.json, packages/zero-runtime/src/processors/styled.ts, packages/zero-unplugin/src/index.ts, packages/zero-vite-plugin/src/zero-vite-plugin.ts, packages/zero-vite-plugin/tsup.config.ts
and replace emotion/system with zero runtime at build time.
To test locally, see the README of this [repo](https://github.com/brijeshb42/next-js-zero-runtime-intermediate-pkg).
=> [zero] Identify zero runtime styled path

packages/mui-material-nextjs/src/v13-appRouter/appRouterV13.tsx
Add CSP support by passing the `nonce` createCache option down into the `useServerInsertedHTML` script tags.
With this change, you can now follow the [NextJS guide](https://nextjs.org/docs/app/building-your-application/configuring/content-security-policy) on CSP, and in `layout.tsx` pass the `nonce` from headers down into the `AppRouterCacheProvider` to prevent `inline style` `style-src` CSP errors.
✅ Tested the code with mui docs and local project with code sandbox build
=> [material-ui-nextjs] Support Nonces in the App Router Provider

.github/styles/Blog/BrandName.yml, .github/styles/Blog/ComposedWords.yml, .github/styles/Blog/NamingConventions.yml, .github/styles/Blog/NoCompanyName.yml, .vale.ini, docs/pages/blog/mui-x-v6.md
This is a continuation of https://github.com/mui/mui-x/pull/11645#issuecomment-1885369455. See how annoying it is when a non-breaking space is missed with MUI X. That line breaks in the middle 🙈. The other objective is to flag all the cases where we use MUI. In 80% of the time, this shouldn't happen in the first place.
This seems to work:
https://github.com/mui/material-ui/assets/3165635/c4466145-12c9-4913-ae72-60bbbbbc92a2
=> [docs-infra] Enforce brand name rules

packages/mui-base/src/useSelect/useSelect.test.tsx, packages/mui-base/src/useSelect/useSelect.ts
Fix #40565
Preview: https://deploy-preview-40599--material-ui.netlify.app/base-ui/react-select/#introduction
=> [base-ui][select] Fix screen-reader CSS to avoid body scrollbar

docs/data/base/getting-started/quickstart/quickstart.md, docs/data/joy/getting-started/installation/installation.md, docs/data/material/getting-started/installation/installation.md, docs/data/system/getting-started/installation/installation.md
This PR, inspired by [a recent docs-feedback entry](https://mui-org.slack.com/archives/C041SDSF32L/p1705341275066149), adds instructions about what to do regarding the peer dependencies we call out in the Installation pages. I also took advantage of the opportunity to standardize the formatting so that the "Peer dependency" title is an H3.
- https://deploy-preview-40621--material-ui.netlify.app/material-ui/getting-started/installation/#peer-dependencies
- https://deploy-preview-40621--material-ui.netlify.app/joy-ui/getting-started/installation/#peer-dependencies
- https://deploy-preview-40621--material-ui.netlify.app/base-ui/getting-started/quickstart/#peer-dependencies
- https://deploy-preview-40621--material-ui.netlify.app/system/getting-started/installation/#peer-dependencies
=> [docs] Improve instructions about peer dependencies

docs/data/material/components/app-bar/BottomAppBar.js, docs/data/material/components/app-bar/BottomAppBar.tsx, docs/data/material/components/bottom-navigation/FixedBottomNavigation.js, docs/data/material/components/bottom-navigation/FixedBottomNavigation.tsx, docs/data/material/components/breadcrumbs/RouterBreadcrumbs.js, docs/data/material/components/breadcrumbs/RouterBreadcrumbs.tsx, docs/data/material/components/dialogs/FullScreenDialog.js, docs/data/material/components/dialogs/FullScreenDialog.tsx, docs/data/material/components/menus/SimpleListMenu.js, docs/data/material/components/menus/SimpleListMenu.tsx, docs/data/material/components/transfer-list/SelectAllTransferList.js, docs/data/material/components/transfer-list/SelectAllTransferList.tsx, docs/data/material/components/transfer-list/TransferList.js, docs/data/material/components/transfer-list/TransferList.tsx
Since `button` prop is deprecated, replaced all instances of `<ListItem button/>` to `<ListItemButton />` in demos
There are few other ListItem props that are deprected but none of them are used in demos
=> [material-ui][docs] Update <ListItem button/> to ListItemButton in demos

docs/pages/material-ui/api/divider.json, docs/translations/api-docs/divider/divider.json, packages/mui-material/src/Divider/Divider.d.ts, packages/mui-material/src/Divider/Divider.js, packages/mui-material/src/Divider/dividerClasses.ts
part of: https://github.com/mui/material-ui/issues/40417
preview: https://deploy-preview-40563--material-ui.netlify.app/material-ui/api/divider/
=> [material-ui][Divider] Deprecate props and classes for v6

docs/data/material/components/accordion/AccordionTransition.js, docs/data/material/components/accordion/AccordionTransition.tsx, docs/data/material/components/accordion/accordion.md, docs/pages/material-ui/api/accordion-summary.json, docs/pages/material-ui/api/accordion.json, docs/translations/api-docs/accordion-summary/accordion-summary.json, docs/translations/api-docs/accordion/accordion.json, packages/mui-material/src/Accordion/Accordion.d.ts, packages/mui-material/src/Accordion/Accordion.js, packages/mui-material/src/Accordion/Accordion.test.js, packages/mui-material/src/AccordionSummary/accordionSummaryClasses.ts, packages/mui-material/src/utils/slotsTypes.ts, packages/mui-material/src/utils/types.ts, packages/mui-material/src/utils/useSlot.test.tsx, packages/mui-material/src/utils/useSlot.ts
Part of: https://github.com/mui/material-ui/issues/40417
Review accordion-related components:
- **Accordion**: Add deprecations for transition props and the slots API that should replace it.
- **AccordionActions**: No changes
- **AccordionDetails**: No changes
- **AccordionSummary**: Deprecate contentGutters class
Because this is the first deprecations PR, it also adds slot pattern utils developed for Joy UI. This is done as the slots pattern will replace the *Props and *Component type props.
- I took the slot utils from Joy with minor modifications. Something I'm unsure about is the following: Joy's useSlot adds common slot props `component` and `sx`. I kept this as it applies to Material UI, but I was unsure whether to do it.
- I left more questions in the code.
- Are there any other …
=> [material-ui][Accordion] Deprecate *Props props and classes for v6

packages/api-docs-builder/package.json, pnpm-lock.yaml
The @mui-internal/api-docs-builder had a leftover @mui/utils dependency declared in its package.json. Since it isn't used, it's safe to remove it.
=> [code-infra] Remove unnecessary @mui/utils dependency from api-docs-builder

docs/data/material/components/tabs/tabs.md
Part of #39952. Closes #40558. 
https://deploy-preview-40587--material-ui.netlify.app/material-ui/react-tabs/#introduction
=> [material-ui][docs] Improve TabContext, TabList, and TabPanel documentation

packages/mui-icons-material/package.json
Fixes https://github.com/mui/material-ui/issues/40654
Once this PR is merged, `@mui/icons-material` can be republished by itself: https://github.com/mui/material-ui/blob/master/packages/mui-icons-material/package.json#L41
=> [icons-material] Fix icons package.json version

.circleci/config.yml
Investigating what effect disabling package cache has on build times.
It seems that in cases where cache would be hit, the restore + install step takes roughly the same time as installing fresh packages from the registry.
In the cache miss scenario, however, saving the downloaded packages to the cache store take a lot of time (over a minute), so we can optimize this scenario.
[Cache hit](https://app.circleci.com/pipelines/github/mui/material-ui/118730/workflows/0d119699-ff79-42e1-a524-a7737ce25829/jobs/638242): restore + install: 27s + 2s = **29s**
[Cache miss](https://app.circleci.com/pipelines/github/mui/material-ui/118720/workflows/47a15199-8c3e-4a90-9b76-7a2757988ca9/jobs/638192): install + store = 34s + 68s = **102s**
[Fresh …
=> [code-infra] Disable pnpm package cache on CircleCI

docs/pages/material-ui/api/pagination-item.json, docs/translations/api-docs/pagination-item/pagination-item.json, packages/mui-material/src/PaginationItem/PaginationItem.js, packages/mui-material/src/PaginationItem/PaginationItem.test.js, packages/mui-material/src/PaginationItem/paginationItemClasses.ts
part of https://github.com/mui/material-ui/issues/40417
new classes: [primary](https://deploy-preview-40673--material-ui.netlify.app/material-ui/api/pagination-item/#pagination-item-classes-colorPrimary) , [secondary](https://deploy-preview-40673--material-ui.netlify.app/material-ui/api/pagination-item/#pagination-item-classes-colorSecondary)
preview: https://deploy-preview-40673--material-ui.netlify.app/material-ui/api/pagination-item/#classes
=> [material-ui][PaginationItem] Deprecate classes for v6

docs/notifications.json
A continuation of #40553.
_**Caption: Notifications container with the new notification highlighted with a red rectangle**_
=> [docs] Add notification to publish the survey

docs/translations/api-docs/accordion/accordion.json, packages/api-docs-builder/ApiBuilders/ComponentApiBuilder.ts
Fix the following issue on X. Seems it also occures in core
=> [docs-infra] Support markdown link in slots descriptions

docs/data/base/components/textarea-autosize/EmptyTextarea.js, docs/data/base/components/textarea-autosize/EmptyTextarea.tsx, docs/data/base/components/textarea-autosize/MaxHeightTextarea.js, docs/data/base/components/textarea-autosize/MaxHeightTextarea.tsx, docs/data/base/components/textarea-autosize/MinHeightTextarea.js, docs/data/base/components/textarea-autosize/MinHeightTextarea.tsx, docs/data/base/components/textarea-autosize/UnstyledTextarea/css/index.js, docs/data/base/components/textarea-autosize/UnstyledTextarea/css/index.tsx, docs/data/base/components/textarea-autosize/UnstyledTextarea/system/index.js, docs/data/base/components/textarea-autosize/UnstyledTextarea/system/index.tsx, docs/data/base/components/textarea-autosize/UnstyledTextarea/tailwind/index.js, docs/data/base/components/textarea-autosize/UnstyledTextarea/tailwind/index.tsx, docs/data/base/components/textarea-autosize/UnstyledTextarea/tailwind/index.tsx.preview, docs/data/base/components/textarea-autosize/UnstyledTextareaIntroduction/css/index.js, docs/data/base/components/textarea-autosize/UnstyledTextareaIntroduction/css/index.tsx, docs/data/base/components/textarea-autosize/UnstyledTextareaIntroduction/system/index.js, docs/data/base/components/textarea-autosize/UnstyledTextareaIntroduction/system/index.tsx, docs/data/base/components/textarea-autosize/UnstyledTextareaIntroduction/tailwind/index.js, docs/data/base/components/textarea-autosize/UnstyledTextareaIntroduction/tailwind/index.tsx, docs/data/base/components/textarea-autosize/UnstyledTextareaIntroduction/tailwind/index.tsx.preview
The bug https://github.com/mui/material-ui/issues/40605 seems to have relationship with https://github.com/mui/material-ui/issues/40634 due to customer root has no `border-box` attribute.
=> [base-ui][TextareaAutosize] Add border-box to demo

packages/mui-base/src/Option/Option.tsx, packages/mui-base/src/Select/Select.test.tsx
When Select's Options had rich content (= more than a plain string), such as an icon or an image, selecting such an option did not display properly. The effect was as if nothing was selected.
See the "Select a component" Select:
before: https://deploy-preview-40683--material-ui.netlify.app/base-ui/
after: https://deploy-preview-40689--material-ui.netlify.app/base-ui/
=> [base-ui][Select] Fix display of selected Options with rich content

examples/joy-ui-nextjs-ts/src/components/ThemeRegistry/EmotionCache.tsx, examples/material-ui-nextjs-pages-router-ts/pages/_document.tsx, examples/material-ui-nextjs-ts-v4-v5-migration/pages/_document.tsx, packages/mui-material-nextjs/src/v13-appRouter/appRouterV13.tsx, packages/mui-material-nextjs/src/v13-pagesRouter/pagesRouterV13Document.tsx
I noticed that the reproduction of #37500 still leads to an error (but a different kind):
This is a regression from #40199. It's a quick fix, so I thought I might as well go for it.
=> [examples] Fix build on Next.js Pages Router examples

test/README.md
It wasn't so obvious to me how to debug:
Applies to MUI X, Material UI, etc.
This is required now because of the change made in https://github.com/microsoft/playwright/releases/tag/v1.38.0. A much better solution would be to catch the error and log the right error message but I didn't have the time to look into this.
=> [code-infra] Explain how to install the browsers

packages/mui-base/src/index.js, packages/mui-base/src/useAutocomplete/index.js, packages/mui-material/src/Accordion/index.js, packages/mui-material/src/AccordionActions/index.js, packages/mui-material/src/AccordionDetails/index.js, packages/mui-material/src/AccordionSummary/index.js, packages/mui-material/src/Rating/index.js, packages/mui-material/src/Toolbar/index.js, packages/mui-material/src/index.js, packages/mui-system/src/index.js, packages/mui-utils/src/index.ts
I'm randomly removing a few of what I believe are harmful "use client" from our bundle to prove my point in https://github.com/mui/material-ui/issues/39010#issuecomment-1732602132. My idea is that if this goes smoothly in production after a couple of weeks, we can go all-in.
=> [core] Remove unneeded use-clients

packages/mui-material/src/Alert/Alert.test.js
While working on https://github.com/mui/material-ui/pull/40681 I noticed we were missing tests for the `action`, `icon`, and `iconMapping` props.
=> [material-ui][Alert] Add action, icon, and iconMapping tests

docs/data/base/components/menu/UseMenu.js, docs/data/base/components/menu/UseMenu.tsx
Entering the Base UI's Menu docs in dev mode triggered a warning saying there's a hydration mismatch. React HTML-encoded the style tag contents on the server, but didn't do it on the client.
With `dangerouslySetInnerHTML` the problem is gone.
=> [Menu][docs] Fix hydration mismatch error on Base UI's Menu docs

docs/src/components/showcase/ThemeToggleButton.tsx, docs/src/modules/brandingTheme.ts
This PR fixes the MuiToggleButton for selected button right border overlap issue by adding z-index property as higher layer for "Mui-selected" class and "MuiToggleButton" class lower z-index. 
Closes https://github.com/mui/material-ui/issues/40727
| ![Screenshot from 2024-01-23 03-27-36](https://github.com/mui/material-ui/assets/27009987/bc4a12e8-4312-45b9-979a-6df0652156aa) | ![Screenshot from 2024-01-23 03-28-11](https://github.com/mui/material-ui/assets/27009987/4f4fab56-9231-4dc7-9456-e1e82557d95b) |
=> [website] Fix Toggle Button styles in the homepage demos

docs/src/components/home/GetStartedButtons.tsx, docs/src/components/productDesignKit/DesignKitHero.tsx, docs/src/components/productTemplate/TemplateHero.tsx, docs/src/components/productX/XRoadmap.tsx, docs/src/modules/brandingTheme.ts
Changes include:
- Fine-tune the primary blue color scale a bit (mostly light values)
- Further tweak the primary button styles (simplifying it)
- Remove `transform: scale` from both the Button and Button Base to avoid any text rasterizing upon scaling
https://deploy-preview-40751--material-ui.netlify.app/
=> [website] Fine-tune colors and styles on the branding theme

docs/src/components/pricing/LicensingModelSwitch.tsx
Fix a quick regression, from #40623 (I noticed this by chance)
Before
https://github.com/mui/material-ui/assets/3165635/a1044845-4354-4f40-9d03-8079659d696f
After
https://github.com/mui/material-ui/assets/3165635/bf91b239-3830-43ab-885b-0ce60de3761a
=> [website] Fix pricing license model toggle style

CHANGELOG.md, CHANGELOG.old.md, docs/data/joy/getting-started/roadmap/roadmap.md, docs/data/material/discover-more/roadmap/roadmap.md, docs/lib/sourcing.ts, docs/pages/blog/2019-developer-survey-results.md, docs/pages/blog/2019.md, docs/pages/blog/2020-developer-survey-results.md, docs/pages/blog/2021-developer-survey-results.md, docs/pages/blog/first-look-at-joy.md, docs/pages/blog/making-customizable-components.md, docs/pages/blog/march-2019-update.md, docs/pages/blog/material-ui-v4-is-out.md, docs/pages/blog/september-2019-update.md, docs/pages/careers/designer.md, docs/pages/careers/product-manager.md, docs/src/components/banner/AppFrameBanner.tsx, docs/src/components/banner/AppHeaderBanner.tsx, docs/src/featureToggle.js, docs/src/modules/components/AppSearch.js
https://deploy-preview-40553--material-ui.netlify.app/
https://deploy-preview-40553--material-ui.netlify.app/material-ui/getting-started/
=> [docs] Add survey banner to docs and website

docs/src/modules/brandingTheme.ts
Before, layout shift on page transiton
https://github.com/mui/material-ui/assets/3165635/3d78788d-c0ea-426f-8909-7ec49f247e09
After, stable layout
https://github.com/mui/material-ui/assets/3165635/bb5cb412-d95a-4972-a0dc-1b58dcb06633
I opened https://github.com/mui/material-ui/issues/40748 for what a better solution for this would be (it's annoying to see  the scrollbar). This PR relies on a fix I introduced while back to support https://github.com/mui/material-ui/issues/17812#issuecomment-540164415
=> [docs-infra] Avoid layout shift on docs-pages

packages/api-docs-builder-core/package.json, packages/api-docs-builder/package.json, pnpm-lock.yaml
Internal dependencies of API docs builder's Core config were incorrectly not specified using the workspace protocol.
Also, `typescript` was incorrectly defined as a devDependency of @mui-internal/api-docs-builder but it's used at runtime.
This PR fixes both of these issues.
=> [code-infra] Correct API Docs Builder dependencies

docs/src/modules/brandingTheme.ts, packages/mui-joy/src/styles/defaultTheme.test.js, packages/mui-joy/src/styles/extendTheme.test.js, packages/mui-joy/src/styles/extendTheme.ts, packages/mui-joy/src/styles/types/theme.ts, packages/mui-material/src/Avatar/Avatar.js, packages/mui-material/src/styles/createTheme.d.ts, packages/mui-material/src/styles/createTheme.js, packages/mui-material/src/styles/createTheme.test.js, packages/mui-material/src/styles/experimental_extendTheme.d.ts, packages/mui-material/src/styles/experimental_extendTheme.test.js, packages/mui-system/src/createTheme/applyStyles.ts, packages/mui-system/src/createTheme/createTheme.d.ts, packages/mui-system/src/createTheme/createTheme.js, packages/mui-system/src/createTheme/createTheme.test.js, packages/mui-system/src/createTheme/index.d.ts, packages/mui-system/src/createTheme/index.js
- This is a new utility to create styles for a color mode that will smooth the transition from Material UI v5 -> v6.
- Improve the DX for customization. Currently, customization is different between basic theme and CSS theme variables. This utility abstracts the implementation so developers don't need to think about it.
Note: it replaces the existing `theme.applyDarkStyles` from #40324 
```diff
- styled('div')(({ theme }) => ({
-   background: theme.palette.mode === 'light' ? theme.palette.grey[700] : theme.palette.grey[300],
- }))
+ styled('div')(({ theme }) => [
+   { background: theme.palette.grey[700] },
+   theme.applyStyles('dark', {
+      background: theme.palette.grey[300],
+   })
+ ])
```
```diff
- styled('div')(({ theme }) => ({
-   background: theme.vars.palette.grey[700],
- …
```
=> [system] Add `applyStyles()` to theme

docs/data/material/components/dividers/IntroDivider.js, docs/data/material/components/dividers/IntroDivider.tsx, docs/data/material/components/dividers/ListDividers.js, docs/data/material/components/dividers/ListDividers.tsx, docs/data/material/components/dividers/dividers.md
part of https://github.com/mui/material-ui/issues/40417 (Missed this handling in https://github.com/mui/material-ui/pull/40563)
address: https://mui-org.slack.com/archives/C041SDSF32L/p1706187993110469 (Also good to know people are noticing deprecations)
**i guess argos failing is expected since <Divider light/ is exactly not equivalent to <Divider sx={{bgcolor: grey[50]}}**
=> [material-ui][Divider] Remove light prop references from docs

docs/src/components/home/DesignSystemComponents.tsx, docs/src/components/home/HeroEnd.tsx, docs/src/components/home/ProductSuite.tsx, docs/src/components/home/StartToday.tsx
I was annoyed by this trying to enjoy #40784.
The bug:
https://github.com/mui/material-ui/assets/3165635/cee0b69b-ae92-488c-9544-f615017286a8
Preview: https://deploy-preview-40786--material-ui.netlify.app/
=> [website] Fix Footer layout shift

docs/data/material/guides/nextjs/nextjs.md
Closes #40238
https://deploy-preview-40626--material-ui.netlify.app/material-ui/guides/nextjs/#configuration-2
=> [docs][material-nextjs] Add theming and configuration content to the page

packages/mui-joy/src/styles/CssVarsProvider.tsx
=> [joy-ui] Change the color scheme type to `SupportedColorScheme`

packages/typescript-to-proptypes/src/getPropTypesFromFile.ts
Needed for https://github.com/mui/mui-x/pull/11791
To give some context, on the pickers we are supporting several date libraries (dayjs, moment, date-fns and Luxon)
Date-fns is using JavaScript dates for its values and the other are using custom objects
In https://github.com/mui/mui-x/pull/11791, I'm improving the typing so that when you import an adapter (the utility that unifies all the date library APIs), you also say to the components that the props can receive a value in the date format of your date libraries.
But we have one issue, the proptypes generated are not `PropTypes.oneOfType([PropTypes.object, PropTypes.instanceOf(Date)])` due to date-fns. And this is super misleading for people using another date library.
To solve this, I added a new option to the prop-types generation to …
=> [typescript-to-proptypes] Allow to represent dates as `PropTypes.object`

apps/zero-runtime-next-app/src/augment.d.ts, apps/zero-runtime-next-app/src/components/Slider/ZeroSlider.tsx
=> [zero] Use `theme.applyStyles` in the demo app

docs/src/components/home/UserFeedbacks.tsx
Fixing
```
Warning: Each child in a list should have a unique "key" prop. See https://reactjs.org/link/warning-keys for more information.
at renderElement (/Users/janpotoms/Projects/material-ui/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5952:5)
at UserFeedbacks
at LoadableComponent (/Users/janpotoms/Projects/material-ui/node_modules/.pnpm/next@13.4.19_@babel+core@7.23.7_babel-plugin-macros@3.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/shared/lib/loadable.js:111:9)
at div
at /Users/janpotoms/Projects/material-ui/node_modules/.pnpm/@emotion+react@11.11.3_@types+react@18.2.48_react@18.2.0/node_modules/@emotion/react/dist/emotion-element-48d2c2e4.cjs.dev.js:70:25
at Container …
```
=> [website] Fix missing key on the Testimonials section

packages/mui-utils/src/scrollLeft/index.ts
Got this warning when building zero demo next-app
```
../../packages/mui-utils/build/esm/scrollLeft/index.js
export 'default' (reexported as 'default') was not found in './scrollLeft' (possible exports: detectScrollType, getNormalizedScrollLeft)
```
It turns out that the `scrollLeft.ts` does not have default export but the index file try to do it.
=> [utils] Remove unnecessary default export

package.json, pnpm-lock.yaml
I don't see this package being used anywhere. Not sure why it was added in #38859.
Closes #40818
=> [core] Remove unneeded `@slack/web-api` package

docs/package.json, pnpm-lock.yaml
`@types/markdown-to-jsx` is [deprecated](https://www.npmjs.com/package/@types/markdown-to-jsx).
=> [core] Remove deprecated `@types/markdown-to-jsx` package from docs

docs/data/base/components/input/OTPInput.js, docs/data/base/components/input/OTPInput.tsx, docs/data/base/components/input/OTPInput.tsx.preview, docs/data/base/components/input/input.md
Demo: https://deploy-preview-40539--material-ui.netlify.app/base-ui/react-input/#otp-input
looking at downloads of https://www.npmjs.com/package/react-otp-input and considering its applicability in various everyday scenarios, I believe this component warrants inclusion as the demo.
few Inspiration/ benchmarks:
- https://github.com/devfolioco/react-otp-input
- https://github.com/shubhanus/otp-input-react
=> [base-ui][Input] Add OTP input demo

docs/src/modules/components/ApiPage/list/PropertiesList.tsx, docs/src/modules/components/ApiPage/table/PropertiesTable.tsx, docs/src/modules/components/HooksApiContent.js
I broke this in #40450
Before: https://mui.com/base-ui/react-tabs/hooks-api/#use-tab-parameters-value doesn't work
After: https://deploy-preview-40836--material-ui.netlify.app/base-ui/react-tabs/hooks-api/#use-tab-parameters-value
=> [docs-infra] Fix anchor link hook

.markdownlint-cli2.cjs, packages/markdownlint-rule-mui/duplicate-h1.js
This new lint fails the ci when it sees a h1 or duplicated h1 in a page where h1 isn't the first element https://github.com/mui/material-ui/pull/40784#discussion_r1466976674.
For example:
```diff
diff --git a/docs/data/material/components/alert/alert.md b/docs/data/material/components/alert/alert.md
index 1f1a903f2c..bcde949fe0 100644
--- a/docs/data/material/components/alert/alert.md
+++ b/docs/data/material/components/alert/alert.md
@@ -6,13 +6,15 @@ githubLabel: 'component: alert'
waiAria: https://www.w3.org/WAI/ARIA/apg/patterns/alert/
---
+a
+
<p class="description">Alerts display brief messages for the user without interrupting their use of the app.</p>
{{"component": "modules/components/ComponentLinkHeader.js"}}
-## Introduction
+# Introduction
Alerts give users brief and …
```
=> [blog] Lint duplicate h1 on the page

packages/mui-envinfo/envinfo.test.js, packages/mui-envinfo/test/package.json, pnpm-lock.yaml, pnpm-workspace.yaml
Speeds up the envinfo package test that often times out:
- instead of installing packages during the test, we rely on the packages being installed for the whole workspace
- instead of building the envinfo package and calling `npx`, the script is tested by executing it directly with `node`. This slightly increases the potential for errors, but given that the package is hardly ever updated, it's a risk we can accept.
=> [test] Speed up the envinfo test

docs/pages/careers.tsx, docs/pages/careers/staff-ui-engineer-base-ui.js, docs/pages/careers/staff-ui-engineer-base-ui.md
Adds a new open role for a Staff UI Engineer on Base UI.
Preview: https://deploy-preview-40773--material-ui.netlify.app/careers/staff-ui-engineer-base-ui/
=> [website] Add new Base UI role

docs/data/material/guides/styled-components/styled-components.md
Updated the text 'We provides ...' to 'We provide...'
=> [material-ui][docs] Fix typo on styled-components guide

docs/pages/careers.tsx
=> [website] Move `React Engineer - X` into the future roles section

packages/zero-runtime/package.json, packages/zero-runtime/src/processors/css.ts, packages/zero-runtime/src/utils/cssFunctionTransformerPlugin.ts, pnpm-lock.yaml
The individually packaged lodash functions do not receive updates. I changed them to the main lodash package to resolve https://github.com/mui/material-ui/security/dependabot/152
=> [zero-runtime] Use lodash instead of its subpackages

docs/data/material/components/material-icons/SearchIcons.js
Fix https://github.com/mui/material-ui/issues/40847
@oliviertassinari, it seems that your change in https://github.com/mui/material-ui/pull/40449, removing the Box in favor of a plain `<div>`, broke the icon display in the preview dialog. Ended up just putting that back here, as well as adding some tiny design tweaks. 
- Before: https://mui.com/material-ui/material-icons/?query=ab&selected=Abc
- After: https://deploy-preview-40863--material-ui.netlify.app/material-ui/material-icons/?query=ab&selected=Abc
=> [material-ui][docs] Fix the icon preview dialog

docs/src/modules/components/DemoToolbar.js, docs/src/modules/sandbox/CodeSandbox.ts, docs/src/modules/sandbox/Dependencies.ts, docs/src/modules/sandbox/StackBlitz.ts
CodeSandbox is changing its pricing, see https://www.codesandbox.community/c/api-billing-updates/upcoming-pricing-billing-changes. Developers who want to report a bug or edit demos might hit a paywall. Sandboxes are paid after 20. This limit at 20 could be annoying for some of the developers browsing the docs. This can also be a problem for bug reproduction on GitHub. Community members might not be able to easily them if its on CodeSandbox, so increasing the odd for reproduction to be on StackBlitz is likely a win.
Today, CodeSandbox is 70% of the use while StackBlitz is 30%:
https://analytics.google.com/analytics/web/#/analysis/p353089763/edit/KctZ977QSou7VoMyBQMaqw
StackBlitz is up 76% from 6 months ago 83% / 17%. It's not StackBlitz that is used more but rather it seems to be that …
=> [docs-infra] Improve StackBlitz support

packages/zero-runtime/README.md
=> [zero] Add README with installation and basic usage

packages/zero-runtime/src/processors/createUseThemeProps.ts
If there are no default props provided, the Badge still uses `useThemeProps` from the system.
The build result:
```js
import { createUseThemeProps } from "../zero-styled";
…
const useThemeProps = createUseThemeProps("MuiBadge");
```
Always replace the call with zero-runtime tag if the import is used.
The build result:
```js
import { createUseThemeProps as _createUseThemeProps } from "@mui/zero-runtime";
…
const useThemeProps = /*#__PURE__*/_createUseThemeProps("MuiBadge");
```
---
=> [zero] Always replace the `createUseThemeProps` call

docs/src/modules/sandbox/CodeSandbox.test.js, docs/src/modules/sandbox/CodeSandbox.ts
This is a continuation of #32726. To make #40833 for an optimal bug reproduction experience, developers should be able to build their reproduction when they fork demos from the docs.
The current issue https://codesandbox.io/p/sandbox/intelligent-pond-fjkdsd?file=%2Fpackage.json%3A13%2C4
Which is different from standard CRA projects, e.g. 
https://github.com/mui/material-ui/blob/19ff6ada02dafa827531653801a3b657d58047ba/examples/base-ui-cra-ts/package.json#L14-L18
I saw that while I was checking something else on MUI X. Thought it was a quick win.
=> [docs-infra] Allow developers to build their CodeSandbox export

packages/mui-codemod/src/deprecations/accordion-props/test-cases/actual.js
`actual.js` was the same as `expected.js`
=> [codemod][Accordion] Update props actual.js test case

docs/src/components/action/Highlighter.tsx, docs/src/components/action/StylingInfo.tsx, docs/src/components/home/CoreShowcase.tsx, docs/src/components/home/Hero.tsx, docs/src/components/home/MaterialDesignDemo.tsx, docs/src/components/home/ProductSuite.tsx, docs/src/components/home/ShowcaseContainer.tsx, docs/src/components/productMaterial/MaterialStyling.tsx, docs/src/components/productMaterial/MaterialTheming.tsx
This PR is mostly just a fine-tuning of the Material UI homepage demo. On browsing the website on my phone, I noticed this particular demo could be polished a bit. Also, in bento grids' day and age, visitors will hover/try to interact with the demo naturally. Therefore, the "hover over" supporting text stopped feeling that necessary (plus, we were displaying it on mobile, which doesn't really make sense). I also took the opportunity to add random clean-ups in a few components.
Preview: https://deploy-preview-40881--material-ui.netlify.app/
=> [website] Refine the Material UI homepage demo

docs/data/base/components/menu/MenuIntroduction/css/index.js, docs/data/base/components/menu/MenuIntroduction/css/index.tsx, docs/data/base/components/menu/MenuIntroduction/system/index.js, docs/data/base/components/menu/MenuIntroduction/system/index.tsx, docs/data/base/components/menu/MenuIntroduction/system/index.tsx.preview, docs/data/base/components/menu/MenuIntroduction/tailwind/index.js, docs/data/base/components/menu/MenuIntroduction/tailwind/index.tsx, docs/data/base/components/menu/MenuTransitions.js, docs/data/base/components/menu/MenuTransitions.tsx, docs/data/base/components/menu/MenuTransitions.tsx.preview, docs/data/base/components/menu/menu.md, docs/pages/base-ui/api/popup.json, docs/translations/api-docs-base/popup/popup.json, packages/mui-base/src/Dropdown/Dropdown.test.tsx, packages/mui-base/src/Menu/Menu.test.tsx, packages/mui-base/src/Menu/Menu.tsx, packages/mui-base/src/Menu/Menu.types.ts, packages/mui-base/src/Select/Select.test.tsx, packages/mui-base/src/Unstable_Popup/Popup.test.tsx, packages/mui-base/src/Unstable_Popup/Popup.tsx, packages/mui-base/src/Unstable_Popup/Popup.types.ts, packages/mui-base/src/useTransition/useTransitionTrigger.ts, packages/test-utils/src/flushMicrotasks.ts, packages/test-utils/src/index.ts
Replaced the Popper with Popup in the Menu implementation.
Similar to #40524, but with Menu.
- The `slotProps.root` now accepts the `PopupProps` instead of the `PopperProps`
Preview: https://deploy-preview-40731--material-ui.netlify.app/base-ui/react-menu/
=> [base-ui][Menu] Use Popup instead of Popper

packages/mui-base/src/Menu/Menu.test.tsx
After merging #40731, Base UI tests became broken, as another PR that changed them landed in master first. This fixes the usage of the `render` function, making the CI green again.
=> [Menu][base-ui] Fix improperly merged tests

packages/markdown/prepareMarkdown.js
See https://github.com/mui/material-ui/pull/40446#discussion_r1471646636 for why
Before https://deploy-preview-40446--material-ui.netlify.app/material-ui/react-button/#unstyled
After https://deploy-preview-40875--material-ui.netlify.app/material-ui/react-button/#unstyled
=> [base-ui][docs] Improve Base UI traffic from Material UI

docs/data/material/components/typography/typography.md, docs/data/material/getting-started/installation/installation.md, docs/data/material/guides/material-3-components/material-3-components.md, docs/data/material/guides/server-rendering/server-rendering.md, docs/src/modules/sandbox/CodeSandbox.test.js, docs/src/modules/sandbox/CreateReactApp.ts, docs/src/modules/sandbox/StackBlitz.test.js, examples/joy-ui-cra-ts/public/index.html, examples/material-ui-cra-styled-components-ts/public/index.html, examples/material-ui-cra-styled-components/public/index.html, examples/material-ui-cra-tailwind-ts/public/index.html, examples/material-ui-cra-ts/public/index.html, examples/material-ui-cra/public/index.html, examples/material-ui-express-ssr/server.js, examples/material-ui-preact/public/index.html, examples/material-ui-remix-ts/app/root.tsx, examples/material-ui-via-cdn/index.html, examples/material-ui-vite-ts/index.html, examples/material-ui-vite/index.html
The 600 in the URL doesn't seem to do anything and material UI does not use 600 any way. Remove it from the recommended CDN URL.
https://github.com/mui/material-ui/blob/fb2cb7fdfc5a56a612b87d90f523ed211ab3d4b6/packages/mui-material/src/styles/createTypography.js#L21
=> [material-ui][docs] Correct Google font CDN URL as Roboto 600 weight is not used 

packages/mui-material/src/Avatar/Avatar.js, packages/mui-material/src/Tooltip/Tooltip.js
A simplification on #40766 to save bundle size.
https://mui-dashboard.netlify.app/size-comparison?circleCIBuildNumber=643588&baseRef=master&baseCommit=4f793a13d5105373a3eb3765a60bfd17d1d8960c&prNumber=40834
=> [material-ui][Avatar] Simplify valid children assertion

packages/mui-system/src/colorManipulator.d.ts, packages/mui-system/src/colorManipulator.js, packages/mui-system/src/colorManipulator.test.js
Add a blend function to `colorManipulator.js`, which is used in https://github.com/mui/mui-x/pull/10059.
=> [core] add colorManipulator.blend

renovate.json
The @mui packages in envinfo tests are not meant to be up to date. It's important that they reference an older version so they are downloaded from the registry instead of being linked to the workspace package.
The tests require them to be present and do not rely on any exported API, so the exact version does not matter.
=> [dependencies] Do not update envinfo test dependencies

docs/pages/blog.tsx, docs/src/modules/components/AppNavDrawerItem.js, docs/src/modules/components/AppTableOfContents.js, docs/src/modules/components/Link.tsx, docs/src/modules/components/MarkdownLinks.js, examples/material-ui-nextjs-pages-router-ts/src/Link.tsx, examples/material-ui-nextjs-pages-router/src/Link.js
I'm reverting a change we did in #18441 to support Next.js v9. The underlying issue has since been solved in https://github.com/vercel/next.js/pull/15792/files#diff-29e1b9bc8e17f47fa46cad2f0e0e54d5bbb268adee26051c21d929902a2a5c8cR69 by @Janpot
To get the value of this change see https://mui.com/careers/react-engineer-x-charts/#benefits-and-compensation how the `https://mui.com/careers/#perks-and-benefits` link triggers a full page navigation:
https://github.com/mui/material-ui/assets/3165635/54f66500-81da-4ff9-ac6a-b9908aea9c0d
I noticed this from https://github.com/mui/material-ui/pull/40890#discussion_r1477424397.
=> [docs-infra] Improve support for absolute locale URL

docs/data/base/components/autocomplete/ControlledStates.js, docs/data/base/components/autocomplete/ControlledStates.tsx, docs/data/base/components/autocomplete/UseAutocomplete.js, docs/data/base/components/autocomplete/UseAutocomplete.tsx, docs/data/base/components/autocomplete/UseAutocomplete.tsx.preview, docs/data/base/components/autocomplete/UseAutocompletePopper.js, docs/data/base/components/autocomplete/UseAutocompletePopper.tsx, docs/data/base/components/autocomplete/autocomplete.md
A continuation of #37029. This feels much better. Open https://mui.com/base-ui/react-autocomplete/#hook, I can't imagine developers would want to use "Styled" in their actual implementation.
- If developers use the hooks, by default, every component present in the file is styled, so "styled" is noise.
- If they use the unstyled component, I think they should rename them all to be suffixed with `Base`.
`const Button = styled(ButtonBase)({})` makes a lot more sense to me than the opposite. The button comes first, then it's nature. I think it's easier to read when the component is first.
So in https://mui.com/base-ui/react-button/#component, I think that we should rename the alias as well, the same way Radix suffix them with `Primitive` …
=> [base-ui][docs] Remove redundant "Styled" prefix

packages/mui-material/package.json, packages/zero-unplugin/src/index.ts, pnpm-lock.yaml
This requires adding zero runtime as a peer dep of material (at least when using pnpm). Otherwise getting this error -
=> [zero] Fix build for demo next.js app

docs/data/material/components/button-group/BasicButtonGroup.js, docs/data/material/components/button-group/BasicButtonGroup.tsx, docs/data/material/components/button-group/BasicButtonGroup.tsx.preview, docs/data/material/components/button-group/ButtonGroupMaterialYouPlayground.js, docs/data/material/components/button-group/DisableElevation.js, docs/data/material/components/button-group/DisableElevation.tsx, docs/data/material/components/button-group/DisableElevation.tsx.preview, docs/data/material/components/button-group/GroupOrientation.js, docs/data/material/components/button-group/GroupOrientation.tsx, docs/data/material/components/button-group/GroupOrientation.tsx.preview, docs/data/material/components/button-group/GroupSizesColors.js, docs/data/material/components/button-group/GroupSizesColors.tsx, docs/data/material/components/button-group/GroupSizesColors.tsx.preview, docs/data/material/components/button-group/LoadingButtonGroup.js, docs/data/material/components/button-group/LoadingButtonGroup.tsx, docs/data/material/components/button-group/LoadingButtonGroup.tsx.preview, docs/data/material/components/button-group/SplitButton.js, docs/data/material/components/button-group/SplitButton.tsx, docs/data/material/components/button-group/VariantButtonGroup.js, docs/data/material/components/button-group/VariantButtonGroup.tsx, docs/data/material/components/button-group/VariantButtonGroup.tsx.preview
Following recent docs-feedback — some aria labels were really not great and could use some basic polish. Also, we should probably confirm whether it's necessary to add `role=group"` to these containers; it makes sense to me, and it's what [Bootstrap also recommends](https://getbootstrap.com/docs/4.0/components/button-group/#basic-example) folks doing. Unlike aria-labels, though, that role attribute feels like something that should come out of the box, as it will always be needed in this Button Group context.
https://deploy-preview-40892--material-ui.netlify.app/material-ui/react-button-group/
=> [material-ui][docs] Improve aria-label throughout the Button Group demos

docs/babel.config.js, docs/next.config.js, tsconfig.json
These should be resolved by next.js through tsconfig paths
For 3rd party packages, using webpack aliases instead. This avoids having to run these packages through babel
=> [code-infra] Remove babel alias from the docs

packages/mui-styled-engine/src/index.d.ts, packages/mui-system/src/styleFunctionSx/styleFunctionSx.d.ts
The sx prop uses `csstype` which has `ReadonlyArray` changes in `3.1.3` whereas `CSSObject` comes from emotion
- Use `ReadonlyArray` for the `ResponsiveStyleValue` to work with `CSSObject`
- Follow emotion's change in https://github.com/emotion-js/emotion/pull/3141/
---
=> [system] use `ReadonlyArray` for CSS related types

packages/mui-material/src/Autocomplete/Autocomplete.js
A quick follow-up on https://github.com/mui/material-ui/pull/39795#discussion_r1390206320. Adding comments to people in the future can figure out if this logic is still needed. And tried to speed up a bit the rendering.
To be noted that the problem isn't completely solved, the demos we have in the docs are 🙃
=> [autocomplete] Avoid spread operator

apps/zero-runtime-next-app/README.md, apps/zero-runtime-vite-app/README.md, packages/mui-material/package.json
It was added to facilitate testing locally via pnpm but it has created more issues. So removing it. We can test locally by temporarily adding it back but not committing it.
=> [material] Fix: remove zero-runtime peer dep

docs/pages/404.tsx, docs/pages/base-ui.tsx, docs/pages/material-ui.tsx, docs/src/components/NotFoundHero.tsx, docs/src/modules/components/AppFrame.js, docs/src/modules/components/AppSearch.js
Closes https://github.com/mui/material-ui/issues/31349
Okay, this is a longstanding and quite simple PR. It adds a slightly better-designed 404 page than our standard one. Having something a little bit thoughtful for this scenario adds a lot to communicating our care for attention to detail and polish!
From what I could test, based on [the Next.js docs](https://nextjs.org/docs/pages/building-your-application/routing/custom-error), simply creating a `404.tsx` page is enough to route all of the 404 requests to it. It seems to be working well?! I'd appreciate any insights here if there's more wiring I need to do.
Preview: https://deploy-preview-40884--material-ui.netlify.app/material-ui/api/accordion-detailss/
=> [docs] Add a 404 page

docs/notifications.json
Add notification to promote the announcement of [MUI X v7 Beta](https://mui.com/blog/mui-x-v7-beta/).
=> [docs] Add notification for mui x v7 beta

docs/src/modules/components/AppFrame.js, docs/src/modules/components/AppSearch.js
Fix #33731
The problem is that https://docsearch.algolia.com/docs/api/ doesn't allow us to customize the home dialog, so we have to use: https://github.com/mui/material-ui/blob/3c445c68d6098841eff7c6b7b021965905d0b078/docs/src/modules/components/AppSearch.js#L391
to be able to render what we want. Because of the way Emotion works, this doesn't inject any styles.
The workaround I used is to redefine these styles, only using the SVG path.
In the future, the static extraction should provide stable CSS class names, and I also think that we should do #37599, removing the need to use `renderToStaticMarkup`.
Before: https://deploy-preview-40953--material-ui.netlify.app/blog/aggregation-functions/
After: https://deploy-preview-40957--material-ui.netlify.app/blog/aggregation-functions/
=> [docs-infra] Fix search icon issue

docs/data/material/components/buttons/InputFileUpload.js, docs/data/material/components/buttons/InputFileUpload.tsx, docs/data/material/components/buttons/InputFileUpload.tsx.preview
This is a follow-up on #38823. The demo in https://mui.com/material-ui/react-button/#file-upload has two bugs that https://mui.com/joy-ui/react-button/#file-upload doesn't, so copied the solution Jun used. The bugs:
- Double tab
- [Axe](https://chromewebstore.google.com/detail/axe-devtools-web-accessib/lhdoppojpmngadmnindnejefpokejbdd) complaining about nested 
I noticed this in #40446
=> [button][material-ui] Fix 'File upload' demo a11y

docs/data/material/getting-started/example-projects/example-projects.md, packages/markdown/parseMarkdown.js
cc @kriasoft
Preview: https://deploy-preview-40913--material-ui.netlify.app/material-ui/getting-started/example-projects/
=> [material-ui][docs] Remove outdated example projects link (it uses Joy UI now)

packages/mui-joy/src/Button/Button.tsx, packages/mui-joy/src/ButtonGroup/ButtonGroup.test.tsx
Fixed a bug in the Button component:
> <img width="859" alt="image" src="https://github.com/mui/material-ui/assets/1857117/92201fbf-b93e-4c03-b730-5fe5dd657319">
ButtonGroup's `disabled` prop wasn't overridden, because the first part of `(inProps.disabled || inProps.loading) ?? (buttonGroup.disabled || disabledProp || loading);` resulted in `(false || undefined)` which is `undefined`.
The correct order is `(inProps.loading || inProps.disabled)`, because if it's loading, we should always disable a button. If it's not (whether `false` or `undefined`), we should rely on `disabled` prop which could be `true`, `false` or `undefined` and make the whole construction work properly.
=> [joy-ui][Button] Fix `disabled` prop priority when inside button group

docs/data/material/components/masonry/Sequential.js, docs/data/material/components/masonry/Sequential.tsx, docs/data/material/components/masonry/Sequential.tsx.preview, docs/data/material/components/masonry/masonry.md, docs/pages/material-ui/api/masonry.json, docs/translations/api-docs/masonry/masonry.json, packages/mui-lab/src/Masonry/Masonry.d.ts, packages/mui-lab/src/Masonry/Masonry.js, packages/mui-lab/src/Masonry/Masonry.test.js
Resolves https://github.com/mui/material-ui/issues/36859. Allows sorting masonry from left to right with the `sequential` prop.
=> [lab][Masonry] Ability to sort elements from left to right

packages/zero-unplugin/src/index.ts
Wrong CSS order injection when nested components are used.
Consider Material UI Button > ButtonBase > TouchRipple
Before the change, the compiled CSS is imported at the top of the file like this:
```js
// compiled Button.js
import 'output.css'
import ButtonBase from '../ButtonBase';
// compiled ButtonBase.js
import 'output.css';
import TouchRipple from './TouchRipple;
```
This produces CSS is this order:
```css
// page.css
.hashed-button { … }
.hashed-button-base { … }
.hashed-touch-ripple { … }
```
Which causes the button styles to be overridden by button base and touch ripple
Just move CSS import to the last.
=> [zero] Fix wrong CSS order by moving import to last

docs/src/modules/components/ApiPage.js, docs/src/modules/components/ApiPage/sections/ClassesSection.tsx, docs/src/modules/components/ApiPage/sections/PropertiesSection.js, docs/src/modules/components/ApiPage/sections/SlotsSection.tsx, docs/src/modules/components/ApiPage/sections/ToggleDisplayOption.tsx, docs/src/modules/components/ComponentsApiContent.js, docs/src/modules/components/GoogleAnalytics.js, docs/src/modules/components/HooksApiContent.js
API page component can get props to:
- define what is the default layout
- define which localeStorage key is saving the layout
This should allow to have a specific layout for data grid and save it in distinct key/value. Plus it's flexible since you can customize that at the page level.
The GA behavior is also modified. We stop the experiement so no need to compare the default and current layout.
However it can be interesting in the future to know what people are using per page. So the toggle button send an event to google analytics to know when user modify the layout
See for why: https://groups.google.com/a/mui.com/g/docs-infra/c/bzqriS4u3_M/m/8Me75UBAAgAJ. The layout shifts, it's not a great page load experience.
Preview: https://deploy-preview-40862--material-ui.netlify.app/material-ui/a …
=> [docs-infra] Remove random layout assignment

packages/mui-base/src/Switch/Switch.tsx, packages/mui-base/src/useSwitch/useSwitch.test.tsx, packages/mui-base/src/useSwitch/useSwitch.ts, packages/mui-joy/src/Checkbox/Checkbox.tsx, packages/mui-joy/src/Radio/Radio.tsx, packages/mui-joy/src/Switch/Switch.test.tsx
Related to #40615
**Changes in this PR:**
Added the missing accessibility features for the `Switch` component and `useSwitch` hook:
- Root element's `role` should be `switch`
- Root element should have `aria-checked` attribute
=> [base-ui][Switch] Add missing role attribute

CHANGELOG.md
The @mui/system@5.15.10 was incorrectly mentioned in the changelog. The PR that was under the System section touched the docs only.
@mui/system@5.15.10 was not published as there were no changes.
=> [changelog] Remove @mui/system@5.15.10

docs/data/base/components/select/UnstyledSelectIntroduction/tailwind/index.js, docs/data/base/components/select/UnstyledSelectIntroduction/tailwind/index.tsx, docs/data/base/getting-started/accessibility/FocusRing.js, docs/data/base/getting-started/accessibility/FocusRing.tsx, docs/data/base/getting-started/accessibility/KeyboardNavigation.js, docs/data/base/getting-started/accessibility/KeyboardNavigation.tsx
Just a little bit of fine-tuning to these demos. What initially prompted me to open this PR was the Slider styles that are now outdated after we revised them a while back. I ended up adding some considerably small refinements to the Select and Menu button components there, too, but nothing crazy. Trying to keep it simple for now.
Preview: https://deploy-preview-40995--material-ui.netlify.app/base-ui/getting-started/accessibility/
=> [base-ui][docs] Update the Accessibility page demos design

packages/mui-material/src/Autocomplete/Autocomplete.js
The caret icon within the Autocomplete component was incorrectly positioned due to the following styles applied to the .css-1q60rmi-MuiAutocomplete-endAdornment class:
- top: calc(50% - 14px);
This caused the caret icon to be misaligned when the font size was adjusted. Additionally, the 'right: 0;' style was redundant and was overridden by another class, so I removed it..
**Bug Fix:**
1. Removed the 'top' style to ensure that the caret icon remains vertically centered regardless of the font size. The caret icon is now positioned correctly within the Autocomplete component.
2. Removed the 'right: 0;' style as it was overridden, because it is unnecessary and the code is cleaner. 
The caret icon's positioning is now consistent and follows the standard Material-UI styling.
Fix #40874
=> [material-ui][Autocomplete] Caret transformation issue with font size change

docs/pages/blog/base-ui-2024-plans.md
Updated the Base UI blog post with a link to the RFC.
=> [blog] Add link to Base UI API changes RFC

docs/next.config.mjs
Noticed netlify build errors started happening the day I moved to next.config.mjs.
This PR aligns the method of loading commonjs modules using `createRequire` with the way Toolpad does it instead of relying on esm/cjs interop.
=> [code-infra] Load commonjs files in next.config.mjs with require

README.md, docs/next.config.mjs
See https://github.com/mui/material-ui/pull/40302/files#r1492165714
=> [code-infra] Use `experimental.cpus` to control amount of export workers in Next.js

docs/src/modules/components/ApiPage/table/PropertiesTable.tsx
This bug has been visible for a while, e.g. in https://github.com/mui/material-ui/pull/39689#pullrequestreview-1709217787. It feels like there is a bug in the way the data is displayed, it doesn't feel like I can 100% trust what's shown on the API page. I saw this in https://github.com/mui/mui-x/pull/11996.
Before https://deploy-preview-41113--material-ui.netlify.app/material-ui/api/app-bar/#props
After https://deploy-preview-41114--material-ui.netlify.app/material-ui/api/app-bar/#props
=> [docs-infra] Fix display when the default props is undefined

docs/src/modules/components/MarkdownElement.js
closes #41072
**Out of scope**: determine which links should be external by updating the [list](https://github.com/mui/material-ui/blob/master/packages/markdown/parseMarkdown.js#L251).
Added arrow to external links using CSS to detect `target="_blank"`. 
https://github.com/mui/material-ui/assets/18292247/36d6ddf8-9386-4e57-8092-211e4f77f57d
=> [docs-infra] Add external link arrow

packages/mui-material-nextjs/package.json, pnpm-lock.yaml
=> [material-ui] Fix missing babel/runtime dependency in material-ui-nextjs

scripts/README.md
=> [core] Improve the release instructions

docs/data/material/guides/testing/testing.md
=> [material-ui][docs] Update the Testing page's Argos link

docs/src/modules/components/AppTableOfContents.js
I saw this done in Docusaurus https://github.com/facebookincubator/infima/blob/aa1eebd35cdaee3348eb47315774882464cb522f/packages/core/styles/utilities/custom-scrollbar.pcss#L17 while I was browsing a docs of another project. They also do it for the side nav tab, but this feels wrong. So I opened a PR, quick-win.
One step closer to address #38710. A previous iteration was done in #37770.
Before
After
Ideally, we could have used https://stackoverflow.com/a/68860350/2801714 but Chrome is so buggy with it, it's not ready yet.
=> [docs-infra] Reduce scrollbar width on ROC

docs/data/material/components/text-fields/text-fields.md, docs/data/material/migration/migration-v4/v5-component-changes.md
Discovered these broken links while working on https://github.com/mui/mui-x/pull/12135.
Didn't check, but it could be that the API table hash generation changed between the initial implementation and the current state. 🤔 
@alexfauquette Could be an interesting idea to automate the discovery of broken API/generated links based on our known preconditions:
- how do we generate the API table hash
- what sections are possible inside of an `API` page (slots, classes, etc.)
=> [docs] Update broken URL hashes

docs/data/material/components/table/CustomPaginationActionsTable.js, docs/data/material/components/table/CustomPaginationActionsTable.tsx
Closes https://github.com/mui/material-ui/issues/41062
Replace deprecated `SelectProps` property on `CustomPaginationActions` with `slotProps`
[Loom Video](https://www.loom.com/share/d9855748b9104cc4824193e69f11d22f)
---
This code was written and reviewed by GitStart Community. Growing great engineers, one PR at a time.
=> [material-ui][docs] Inform about deprecated TablePagination SelectProps usage

packages/mui-material/src/Tooltip/Tooltip.js
Small change. Found this incorrect code comment while investigating a tooltip issue. It appears that the comment was mistakenly relocated to the `pointerEvents` property in pull request #20745 in v4, which involved removing the `flip` property of the jss-rtl plugin.
=> [material-ui][Tooltip] Remove incorrect code comment

docs/data/material/getting-started/overview/overview.md, docs/src/modules/components/MaterialStartingLinksCollection.js
I was revisiting some pages on the Joy UI docs and came across the nice "Start now" section we added there. Thought about doing the same here for Material UI as a slightly more inviting shortcut for doc pages than the side nav. Also pushed in some additional changes along the way:
- Moved the "Material UI vs. Base UI" section to an h3 below the "Advantages" paragraph — felt fitting.
- Removed the "...is beautiful by design" part (😅) and glued that sentence with the one above.
https://deploy-preview-41137--material-ui.netlify.app/material-ui/getting-started/
=> [material-ui][docs] Add a "start now" section on the Overview page

docs/lib/sourcing.ts, docs/pages/blog.tsx, docs/pages/blog/2020-introducing-sketch.md, docs/pages/blog/2023-material-ui-v6-and-beyond.md, docs/pages/blog/build-layouts-faster-with-grid-v2.md, docs/pages/blog/callback-support-in-style-overrides.md, docs/pages/blog/first-look-at-joy.md, docs/pages/blog/making-customizable-components.md, docs/pages/blog/material-ui-is-now-mui.md, docs/pages/blog/material-ui-v1-is-out.md, docs/pages/blog/material-ui-v4-is-out.md, docs/pages/blog/mui-core-v5-migration-update.md, docs/src/modules/brandingTheme.ts
My main goal with this PR is to remove the "MUI Core" tag from blog posts, as we used it in many instances to refer to Material UI instead. Then, I added tags for Material UI + Joy UI and updated a few posts when they were more obvious. I also added a new tag called "Guides" for posts where it feels more like a "how-to" post style than anything else. Lastly, I'm wondering about whether we should keep the "News" tag — it feels too time-constrained... but maybe that's off-scope. 
Aside from all of this, added in some usual and minor design adjustments.
https://deploy-preview-41193--material-ui.netlify.app/blog/
=> [blog] Add new product tags and stray adjustments

packages/mui-material/src/Accordion/Accordion.js, packages/mui-material/src/Collapse/Collapse.js
Fix forwarded `ownerState` from Transition component overriding component own's `ownerState`
https://www.loom.com/share/96131abf63ba48878bf3e8d02856cce3
closes https://github.com/mui/material-ui/issues/40653
---
This code was written and reviewed by GitStart Community. Growing great engineers, one PR at a time.
=> [material-ui][Transitions] External ownerState is incorrectly forwarded to inner components

docs/data/material/migration/migrating-from-deprecated-apis/migrating-from-deprecated-apis.md, docs/translations/api-docs/pagination-item/pagination-item.json, packages/mui-codemod/README.md, packages/mui-codemod/src/deprecations/all/deprecations-all.js, packages/mui-codemod/src/deprecations/all/postcss.config.js, packages/mui-codemod/src/deprecations/pagination-item-classes/index.js, packages/mui-codemod/src/deprecations/pagination-item-classes/pagination-item-classes.js, packages/mui-codemod/src/deprecations/pagination-item-classes/pagination-item-classes.test.js, packages/mui-codemod/src/deprecations/pagination-item-classes/postcss-plugin.js, packages/mui-codemod/src/deprecations/pagination-item-classes/postcss.config.js, packages/mui-codemod/src/deprecations/pagination-item-classes/test-cases/actual.css, packages/mui-codemod/src/deprecations/pagination-item-classes/test-cases/actual.js, packages/mui-codemod/src/deprecations/pagination-item-classes/test-cases/expected.css, packages/mui-codemod/src/deprecations/pagination-item-classes/test-cases/expected.js, packages/mui-material/src/PaginationItem/paginationItemClasses.ts
part of https://github.com/mui/material-ui/issues/40417
preview: https://deploy-preview-41145--material-ui.netlify.app/material-ui/migration/migrating-from-deprecated-apis
=> [material-ui][PaginationItem] Add codemod for deprecated classes

docs/src/modules/utils/CodeCopy.tsx
This is a follow-up on #32390. That logic is weird. We support Alt + C as a shortcut but it doesn't make sense. Instead, I copied the copy logic from https://github.com/mui/mui-x/pull/12121. 
I noticed this from https://github.com/mui/mui-x/pull/11965
=> [docs-infra] Simplify copy logic

docs/data/joy/components/linear-progress/LinearProgressWithLabel.js, docs/data/joy/components/linear-progress/LinearProgressWithLabel.tsx
Closes [#40938](https://github.com/mui/material-ui/issues/40938) where a background is required for mixBlendMode to work properly.
Running the example code in StackBlitz or CodeSandbox should now match the behavior on the docs site.
https://deploy-preview-41194--material-ui.netlify.app/joy-ui/react-linear-progress/
=> [joy-ui][docs] Fix LinearProgressWithLabel example

packages/mui-base/package.json, pnpm-lock.yaml
Also saw this comment: https://github.com/mui/material-ui/pull/36287#discussion_r1440211795 but the tests do pass. Other workspaces also don't refer itself. Or am I missing something?
----
Also, while going through the [workspace documentation](https://pnpm.io/workspaces), I came across [this example](https://pnpm.io/workspaces#usage-examples):
Should it be named MUI?
=> [core][base-ui] Remove `@mui/base` dev dependency from Base UI workspace

package.json, packages-internal/scripts/package.json, packages/docs-utils/CHANGELOG.md, packages/docs-utils/package.json
During the last Core release, the @mui-internal/docs-utilities package has not been built before publishing. This PR adds steps to ensure internal packages are built.
It also bumps the faulty package version (it'll be released manually).
=> [code-infra] Build internal packages before publishing

packages/mui-base/src/Unstable_Popup/PopupContext.ts, packages/mui-base/src/useCompound/useCompoundParent.ts, packages/mui-base/src/useDropdown/DropdownContext.ts, packages/mui-base/src/useList/ListContext.ts, packages/mui-base/src/useTransition/TransitionContext.ts, packages/mui-base/src/utils/ClassNameConfigurator.tsx, packages/mui-joy/src/AvatarGroup/AvatarGroup.tsx, packages/mui-joy/src/Chip/ChipContext.ts, packages/mui-joy/src/FormControl/FormControlContext.ts, packages/mui-joy/src/List/ComponentListContext.ts, packages/mui-joy/src/List/GroupListContext.ts, packages/mui-joy/src/List/NestedListContext.ts, packages/mui-joy/src/List/RowListContext.ts, packages/mui-joy/src/List/WrapListContext.ts, packages/mui-joy/src/ListItem/ListItem.tsx, packages/mui-joy/src/ListItemButton/ListItemButtonOrientationContext.ts, packages/mui-joy/src/ListSubheader/ListSubheader.test.tsx, packages/mui-joy/src/ListSubheader/ListSubheader.tsx, packages/mui-joy/src/ListSubheader/ListSubheaderContext.ts, packages/mui-joy/src/Modal/CloseModalContext.ts, packages/mui-joy/src/ModalDialog/ModalDialogSizeContext.ts, packages/mui-joy/src/ModalDialog/ModalDialogVariantColorContext.ts, packages/mui-joy/src/Tabs/SizeTabsContext.ts, packages/mui-joy/src/ToggleButtonGroup/ToggleButtonGroupContext.tsx, packages/mui-joy/src/Typography/Typography.tsx, packages/mui-joy/src/styles/variantColorInheritance.tsx, packages/mui-material-next/src/Tabs/TabsListContext.js, packages/mui-system/src/Unstable_Grid/createGrid.tsx, packages/mui-system/src/cssVars/createCssVarsProvider.js
https://github.com/mui/material-ui/pull/18468 is still relevant today. Make this change to restore the previous DX we had.
Same as https://github.com/mui/mui-x/pull/12124. 
Before
After
=> [core] Fix missing context display names

docs/translations/translations.json, packages/mui-material-next/src/ButtonBase/Ripple.tsx, packages/mui-material-next/src/ButtonBase/TouchRipple.tsx, packages/mui-material-next/src/OutlinedInput/NotchedOutline.js, packages/mui-material-next/src/Select/SelectInput.js, packages/mui-material/src/ButtonBase/Ripple.js, packages/mui-material/src/ButtonBase/TouchRipple.js, packages/mui-material/src/NativeSelect/NativeSelectInput.js, packages/mui-material/src/OutlinedInput/NotchedOutline.js, packages/mui-material/src/Radio/RadioButtonIcon.js, packages/mui-material/src/Select/SelectInput.js, packages/mui-material/src/internal/SwitchBase.js
Open https://mui.com/material-ui/api/tooltip/#tooltip-prop-classes the link is broken. Same issue on https://next.mui.com/x/api/tree-view/tree-item/#tree-item-prop-classes.
Preview: https://deploy-preview-40908--material-ui.netlify.app/material-ui/api/tooltip/#tooltip-prop-classes
=> [docs-infra] Fix broken anchor links

packages/mui-system/src/createStyled.js, test/integration/mui-system/createStyled.test.js
Fixes https://github.com/mui/material-ui/issues/41220
Consolidate the arguments for the variants' props callback between the @mui/system and the zero-runtime. The argument is now merging props and `ownerState`, so that developers can do:
```
variants: [{
props: (props) => props.someState === 'some-value'
}]
```
instead of needing to do:
```
variants: [{
props: (props) => props.ownerState.someState === 'some-value'
}]
```
Zero-runtime related code: https://github.com/mui/material-ui/blob/master/packages/zero-runtime/src/styled.jsx#L9
=> [system] Merge props and ownerState in the variants props callback

packages/mui-system/src/createStyled.js
Leftover from https://github.com/mui/material-ui/pull/41219, I accidently reverted all changes when fixing an issue and only left the test.
=> [system][zero] Consolidate the variants props callback arguments

docs/lib/sourcing.ts, docs/pages/blog.tsx, docs/pages/blog/2023-toolpad-beta-announcement.md, docs/pages/blog/aggregation-functions.md, docs/pages/blog/date-pickers-stable-v5.md, docs/pages/blog/discord-announcement.md, docs/pages/blog/docs-restructure-2022.md, docs/pages/blog/introducing-the-row-grouping-feature.md, docs/pages/blog/lab-date-pickers-to-mui-x.md, docs/pages/blog/lab-tree-view-to-mui-x.md, docs/pages/blog/mui-core-v5.md, docs/pages/blog/mui-next-js-app-router.md, docs/pages/blog/mui-x-end-v6-features.md, docs/pages/blog/mui-x-mid-v6-features.md, docs/pages/blog/mui-x-v5.md, docs/pages/blog/mui-x-v6-alpha-zero.md, docs/pages/blog/mui-x-v6.md, docs/pages/blog/mui-x-v7-beta.md, docs/pages/blog/premium-plan-release.md, docs/pages/blog/v6-beta-pickers.md
This PR is a follow-up to another one of mine https://github.com/mui/material-ui/pull/41193. I'll quote @samuelsycamore here, as that's pretty much it :)
> Everything we post is "news" when it's "new" and then not news when it's older.
I added "Product" to most of the posts that were using it.
https://deploy-preview-41208--material-ui.netlify.app/blog/
=> [blog] Remove the "News" tag

packages/zero-next-plugin/src/index.ts, packages/zero-runtime/.gitignore, packages/zero-runtime/README.md, packages/zero-runtime/package.json, packages/zero-runtime/src/extendTheme.ts, packages/zero-runtime/src/index.ts, packages/zero-runtime/tsup.config.ts, packages/zero-unplugin/src/index.ts, packages/zero-vite-plugin/src/index.ts
fixing the size of runtime bundle
Context -
zero-runtime package has 2 different types of exports -
1. Package level, ie, `import {styled} from '@mui/zero-runtime';`
2. Subpaths, ie, `import {generateCss} from '@mui/zero-runtime/utils'`
package level exports should be what we want to end-up in the final bundle and subpaths is for sharing common logic across different bundle plugin implementation (ie, implement the common functionality in one place and import and use it it next/vite plugin).
When @siriwatknp implemented the `extendTheme` functionality, he added it directly to the package level export, ie, `import {extendTheme} from '@mui/zero-runtime';`. I think this was an oversight as without proper tree-shaking, `extendTheme` will also end-up being part of the bundle (which also …
=> [zero] Move extendTheme to its own subpath

docs/pages/blog.tsx, docs/pages/experiments/website/branding-theme-test.tsx, docs/src/layouts/AppFooter.tsx, docs/src/modules/brandingTheme.ts
Aside from what the title says, I also added a new page under the Experiments directory that we can fill up more over time to visualize the brand-themed components. It'll likely be easier to maintain them and make changes without getting to pages where they're available. We should've done this a long time ago 😅 
- https://deploy-preview-41209--material-ui.netlify.app/
- https://deploy-preview-41209--material-ui.netlify.app/experiments/website/branding-theme-test/
=> [website] Improve the footer's chip contrast

docs/data/material/getting-started/templates/dashboard/README.md
The provided dependency in the README for the Dashboard example/template is outdated, replaced with the correct one which is `@mui/x-charts`
=> [examples] Update dependency in the dashboard template

docs/pages/material-ui/api/chip.json, docs/translations/api-docs/chip/chip.json, packages/mui-material/src/Chip/chipClasses.ts
=> [material-ui][Chip] Correct `deleteIconColorPrimary` and `deleteIconColorSecondary` class descriptions

docs/src/modules/components/AppNavDrawer.js
fixes #41128
The issue arose from the fact that on route changes since the layout is not rendered but the content panel is, in some cases when previous route was cached the popper never closed on clicking a link in it. Now, we track for route changes in the component, another approach could've been to send `handleClose` through props but it would need special handling when new elements are added in the popper.
=> [docs-infra] Fix product selector popup not closing on route change

.codesandbox/ci.json, nx.json, packages/zero-next-plugin/.gitignore, packages/zero-next-plugin/package.json, packages/zero-runtime/.gitignore, packages/zero-runtime/package.json, packages/zero-unplugin/.gitignore, packages/zero-unplugin/package.json, packages/zero-unplugin/src/index.ts, packages/zero-vite-plugin/.gitignore, packages/zero-vite-plugin/package.json, pnpm-lock.yaml, scripts/zero-runtime-license.mjs, tsup.config.ts
Includes
* Updated metadata in package.json
* Added License banner to the output files
* Copy LICENSE file to the packages
=> [zero] Prepare zero-runtime packages for public release

packages/mui-lab/src/TimelineDot/color-palette-prop.spec.tsx, packages/mui-material/package.json, packages/mui-material/test/typescript/color-palette-prop.spec.tsx, pnpm-lock.yaml
=> [material] Remove unused dev dependency on @mui/lab

packages/zero-runtime/.gitignore, packages/zero-runtime/package.json, packages/zero-runtime/src/theme.ts, packages/zero-runtime/src/utils/cssFnValueToVariable.ts, packages/zero-runtime/src/utils/extendTheme.ts, packages/zero-runtime/src/utils/generateCss.ts, packages/zero-runtime/src/utils/index.ts, packages/zero-runtime/tsup.config.ts, packages/zero-unplugin/src/index.ts, packages/zero-vite-plugin/src/index.ts
path. Doesn't make sense to have so many export subpaths since these utils are mostly there to be consumed by bundler packages.
Also add the missing export to the vite plugin.
=> [zero] Move extendTheme to already existing @mui/zero-runtime/utils

docs/src/modules/components/MarkdownElement.js
I have just realized that as we go down in the heading hierarchy, the colors gradually fade (getting greyer). I'm unsure whether this is good — headings should always be more prominent than paragraphs, regardless of their level. So, this PR makes all headings in dark mode the same color. This will also be consistent with how light mode already works!
=> [docs-infra] Adjust headings dark mode color

docs/pages/experiments/docs/markdown.md, docs/src/modules/components/MarkdownElement.js
I've had this for a while in my mental backlog :) I think we can improve the native HTML disclosure styles a bit, even though we don't use them extensively throughout the docs. 
- https://deploy-preview-41285--material-ui.netlify.app/experiments/docs/markdown/#disclosure-element
- https://deploy-preview-41285--material-ui.netlify.app/joy-ui/migration/migrating-default-theme/#other-palettes
=> [docs-infra] Add design customizations to the disclosure element

docs/data/material/getting-started/templates/landing-page/LandingPage.js, docs/data/material/getting-started/templates/landing-page/LandingPage.tsx, docs/data/material/getting-started/templates/landing-page/components/Features.js, docs/data/material/getting-started/templates/landing-page/components/Features.tsx, docs/data/material/getting-started/templates/landing-page/components/Hero.js, docs/data/material/getting-started/templates/landing-page/components/Hero.tsx, docs/data/material/getting-started/templates/landing-page/components/Pricing.js, docs/data/material/getting-started/templates/landing-page/components/Pricing.tsx
This PR fixes a bug where dark mode didn't work with the default Material Design theme. It also includes minor fixes related to this issue.
https://deploy-preview-41293--material-ui.netlify.app/material-ui/getting-started/templates/landing-page/
=> [material-ui][docs] Fix color mode toggle of the landing page template

packages/zero-runtime/src/keyframes.d.ts, packages/zero-runtime/src/processors/styled.ts, packages/zero-runtime/src/styled.d.ts, packages/zero-runtime/tests/fixtures/styled.input.js, packages/zero-runtime/tests/fixtures/styled.output.css, packages/zero-runtime/tests/fixtures/styled.output.js, packages/zero-runtime/tests/zero-runtime.test.js
This PR brings support for:
```jsx
const cls1 = css`
color: ${({ theme }) => theme.palette.primary.main};
font-size: ${({ theme }) => theme.size.font.h1};
`;
```
```jsx
const SliderRail = styled('span')`
display: block;
position: absolute;
border-radius: inherit;
background-color: currentColor;
opacity: 0.38;
font-size: ${({ theme }) => theme.size.font.h1};
`;
```
=> [zero] Add support for styled tagged-template literals

packages/mui-system/src/createTheme/createSpacing.ts
PR  #23224 added the ability to pass string arguments to `theme.spacing`, but did not change the `Spacing` interface, which still expects the unary value argument to be a `number` rather than the `number | string`
=> [system] Fix createSpacing return type

apps/pigment-next-app/src/app/material-ui/react-switch/page.tsx, apps/pigment-vite-app/src/pages/material-ui/react-switch.tsx, apps/pnpm-lock.yaml, packages/mui-material/src/Switch/Switch.js
Part of #41273
The customization demo is broken, because styles does not apply on the root component.
For example in the ios switch example, the `width`, `height` and `padding` are not applied. But other classes are working fine 🤔
```jsx
const IOSSwitch = styled((props: SwitchProps) => (
<Switch focusVisibleClassName=".Mui-focusVisible" disableRipple {...props} />
))(({ theme }) => ({
width: 42,
height: 26,
padding: 0,
...
```
About the `overridesResolver` I'm not sure about how the new `styled` react to it. It's the first time I see it used with an array
```jsx
overridesResolver: (props, styles) => {
const { ownerState } = props;
return [
styles.switchBase,
{ [`& .${switchClasses.input}`]: styles.input },
ownerState.color !== 'default' && styles[`color${capitalize(ownerState.color)}`], …
```
=> [material-ui][Switch] Convert to support CSS extraction

package.json
This job regularly gets killed because OOM. e.g. in https://app.circleci.com/pipelines/github/mui/material-ui/123209/workflows/fc80066e-8f76-4a04-a1a6-e1d61730bb69/jobs/663886/resources
before:
after:
It doesn't seem to impact the runtime
=> [code-infra] Reduce concurrency for test_types ci job

package.json
We're still hitting [OOM issues](https://app.circleci.com/pipelines/github/mui/material-ui/123266/workflows/26ec58df-c569-47d3-ac60-07f55195b152/jobs/664207/resources) after https://github.com/mui/material-ui/pull/41385
perhaps a different permutation of nx jobs running simultaneously on each run? This PR reduces concurrency once more.
Still peaks at almost 100% but it got through.
We can merge and reduce even further if the problem persists.
=> [code-infra] Reduce concurrency of typescript:ci further

docs/notifications.json, docs/src/modules/components/Notifications.js
Looks like the `dangerouslySetInnerHTML` usage isn't necessary anymore now that the `<b>` tags wrap the entire title on all of the visible notifications. I'm assuming that removing the `<b>` from each title and instead wrapping the title in `<b>` tags in the JSX here will get rid of the `<b>` tags showing up in the v4 docs, as it looks like they are using the same `notifications.json` file to render the text for their notifications. If my assumption is incorrect, feel free to ignore my PR.
v5 docs
v4 docs
=> [docs] Fix v4 docs <b> appearing in notifications

packages/mui-codemod/src/deprecations/alert-props/alert-props.test.js, packages/mui-codemod/src/deprecations/alert-props/test-cases/actual.js, packages/mui-codemod/src/deprecations/alert-props/test-cases/expected.js, packages/mui-codemod/src/deprecations/alert-props/test-cases/theme.actual.js, packages/mui-codemod/src/deprecations/alert-props/test-cases/theme.expected.js, packages/mui-codemod/src/deprecations/slider-props/slider-props.test.js, packages/mui-codemod/src/deprecations/slider-props/test-cases/actual.js, packages/mui-codemod/src/deprecations/slider-props/test-cases/expected.js, packages/mui-codemod/src/deprecations/slider-props/test-cases/theme.actual.js, packages/mui-codemod/src/deprecations/slider-props/test-cases/theme.expected.js, packages/mui-codemod/src/deprecations/utils/replaceComponentsWithSlots.js
If same slot is present in `slotProps` and `componentProps`, i'd expect codemod to merge `componentProps` and `slotProps` with `slotProps` taking precedence but current codemod entirely removes `componentProps.slot`. This PR fixes this bug
=> [mui-codemod] Fix merging of slotProps and componentProps

docs/src/modules/components/ApiPage/table/ClassesTable.tsx, docs/src/modules/components/ApiPage/table/PropertiesTable.tsx
See the last issue in https://groups.google.com/a/mui.com/g/docs-infra/c/81eISb5eXmA. Once MUI X sync with these changes, we should be able to simplify the crawler config:
```jsx
const result = helpers.docsearch({
recordVersion: "v3",
recordProps: {
lvl0: {
selectors: ".this-selector-will-never-match",
defaultValue: $(".algolia-lvl0")
.map((index, element) => $(element).text())
.get()
.join(" > "),
},
lvl1: [".algolia-lvl1", ".markdown-body h1"],
lvl2: [".algolia-lvl2", ".markdown-body h2"],
lvl3: [
".algolia-lvl3",
".markdown-body h3",
".markdown-body td:first-of-type",
],
lvl4: [".algolia-lvl4", ".markdown-body h4"],
content:
".algolia-content, .markdown-body p, .markdown-body li, .markdown-body td:last-of-type",
},
});
```
Part of the value is to be able to change the DOM structure …
=> [docs-infra] Simplify Algolia crawler config

CHANGELOG.md, packages/pigment-nextjs-plugin/package.json, packages/pigment-react/package.json, packages/pigment-unplugin/package.json, packages/pigment-vite-plugin/package.json
=> [pigment] Make all Pigment CSS packages public

.circleci/config.yml
Hopefully bringing the next person to stumble upon this quicker up to speed
https://github.com/mui/material-ui/pull/40172#issuecomment-1970582089
=> [code-infra] Add short note about e2e-website workflow schedule

examples/pigment-css-nextjs-ts/README.md, examples/pigment-css-nextjs-ts/src/app/page.tsx, examples/pigment-css-vite-ts/index.html, examples/pigment-css-vite-ts/src/App.tsx, packages/pigment-react/README.md
This PR simplifies the examples a bit, particularly removing custom fonts and fixes places in the README files where we were still mentioning "Zero" or the previous package name.
=> [pigment-css] Tweak the examples and edit READMEs

packages/mui-base/src/TextareaAutosize/TextareaAutosize.test.tsx, packages/mui-base/src/TextareaAutosize/TextareaAutosize.tsx
Fix part of #41315 where style was not getting applied. It's a regression from #40789.
Before: https://codesandbox.io/p/sandbox/magical-fermi-nctqps
After: https://codesandbox.io/p/sandbox/compassionate-napier-7tnq6l
=> [base-ui][material-ui][TextareaAutosize] Fix inline style not getting applied

docs/data/joy/main-features/color-inversion/ColorInversionHeader.js, docs/data/joy/main-features/color-inversion/ColorInversionHeader.tsx
Changes were made to the “Beta” Chip to ensure it looks consistent and nice across various color schemes. Now, instead of using a fixed background color, we’re dynamically setting it based on the theme’s palette color.
Also increased the opacity value from 0.1 to 0.4. This change makes the background color more noticeable and prominent.
=> [joy-ui][docs] Update Case Studies Chip Background Color

docs/data/joy/main-features/color-inversion/ColorInversionFooter.js, docs/data/joy/main-features/color-inversion/ColorInversionFooter.tsx
To make it easier for future readers and reduce any potential confusion.
1. `--ListItem-gap`: Since every list item only has one child, the gap isn't needed at all.
2. `--ListItemDecorator-size`: got rid of this style because no decorator was used, and it’s not needed.
=> [docs][joy-ui] Remove unnecessary styles in color inversion footer demo

CHANGELOG.md, docs/writing-rules/BrandName.yml, examples/pigment-css-nextjs-ts/README.md, examples/pigment-css-nextjs-ts/src/app/page.tsx, examples/pigment-css-vite-ts/README.md, examples/pigment-css-vite-ts/index.html, examples/pigment-css-vite-ts/src/App.tsx, packages/pigment-nextjs-plugin/package.json, packages/pigment-react/README.md, packages/pigment-react/tests/README.md
Because it's a brand name. It's a follow up on #41317. 
For example, Apple cares about this type of details: https://www.apple.com/
=> [pigment-css][docs] Brand name nonbreaking space

examples/pigment-css-nextjs-ts/src/app/page.tsx, examples/pigment-css-vite-ts/src/App.tsx
=> [pigment-css] Example fix leading spaces

packages/pigment-react/src/processors/styled.ts, packages/pigment-react/src/processors/sx.ts, packages/pigment-react/tests/styled/fixtures/styled.input.js, packages/pigment-react/tests/styled/fixtures/styled.output.css
for composition. Now, you don't have to explicitly add a "." selector.
Fixes #41421
=> [pigment-css][react] Use class selector instead of class value

packages/mui-material/src/styles/CssVarsProvider.test.js, packages/mui-material/src/styles/experimental_extendTheme.d.ts, packages/mui-material/src/styles/experimental_extendTheme.js, packages/mui-material/src/styles/experimental_extendTheme.test.js
The upvotes in https://github.com/mui/material-ui/issues/39740 push me to open this PR. cc @DiegoAndai 
closes #39740
=> [material-ui] Add `paperChannel` token

docs/src/components/showcase/FolderTable.tsx, docs/src/components/showcase/NotificationCard.tsx, docs/src/components/showcase/ThemeDatePicker.tsx
Really looking to get a 100 in accessibility in Lighthouse — these are tiny improvement opportunities still left on the homepage.
=> [website] Improve color contrast on the homepage

packages/mui-joy/src/Tooltip/Tooltip.test.tsx, packages/mui-joy/src/Tooltip/Tooltip.tsx, packages/mui-material/src/Tooltip/Tooltip.js, packages/mui-material/src/Tooltip/Tooltip.test.js
Resolves the problem with not propagating additional parameters here: https://github.com/mui/mui-x/issues/12248#issuecomment-1971378206.
If you do not agree with the proposal—we'll need to go for a different approach on X side.
=> [material-ui][Tooltip] Support event handlers with extra parameters

packages/pigment-css-nextjs-plugin/src/index.ts, packages/pigment-css-react/README.md, packages/pigment-css-react/tsup.config.ts, tsup.config.ts
=> [pigment][next] Warn about unsupported turbo mode in Next.js

packages/mui-base/src/useSelect/useSelect.test.tsx, packages/mui-utils/src/visuallyHidden/visuallyHidden.ts
Added the `px` unit to the visuallyHidden styles margin definition, as per https://github.com/mui/base-ui/pull/135#issuecomment-1993956186
=> [utils] Fix visually hidden styles' margin unit

packages/api-docs-builder/ApiBuilders/ComponentApiBuilder.ts, packages/api-docs-builder/ProjectSettings.ts
I adapted the API docs generator to support new Base UI components — specifically, those without slots, classes, or own props.
=> [code-infra] Adapt API code generator to Base UI repo needs

CHANGELOG.md, package.json, packages-internal/scripts/package.json, packages/mui-babel-macros/package.json, packages/mui-base/package.json, packages/mui-codemod/package.json, packages/mui-core-downloads-tracker/package.json, packages/mui-docs/package.json, packages/mui-icons-material/package.json, packages/mui-joy/package.json, packages/mui-lab/package.json, packages/mui-material-next/package.json, packages/mui-material/package.json, packages/mui-private-theming/package.json, packages/mui-styles/package.json, packages/mui-system/package.json, packages/mui-utils/package.json, packages/pigment-css-nextjs-plugin/package.json, packages/pigment-css-react/package.json, packages/pigment-css-unplugin/package.json, packages/pigment-css-vite-plugin/package.json
=> [release] v5.15.13

packages/mui-docs/package.json, scripts/copyFiles.mjs, scripts/copyFilesUtils.mjs
Copy translation files into the build folder. These are unfortunately not automatically copied to the build folder as our build system only simply transpiles a set of source files and doesn't resolve imports correctly as a real bundler would.
Fixes https://github.com/mui/material-ui/pull/41246#issuecomment-1991571357
=> [code-infra] Copy translations.json to @mui/docs build folder

docs/data/joy/main-features/color-inversion/ColorInversionNavigation.js, docs/data/joy/main-features/color-inversion/ColorInversionNavigation.tsx
Several enhancements to the [side navigation](https://mui.com/joy-ui/main-features/color-inversion/#side-navigation) in this pull request. 
https://deploy-preview-41461--material-ui.netlify.app/joy-ui/main-features/color-inversion/#side-navigation
Here’s a concise overview:
+ Resolved issues related to light and dark mode interactions.
+ Improved consistency across both color schemes.
+ When an Avatar contains a picture, all icon button properties are now accessible.
+ Before the only remaining visual cue is the cursor pointer, which indicates that the avatar is clickable, now all iconbutton behaviour is inherited.
+ Corrected distortion in the plus icon button.
+ Enhanced visual separation between the right and left sidebars, especially noticeable when switching color schemes.
**Before** …
=> [joy-ui][docs] Add UI improvements to the side navigation demo

packages/pigment-css-unplugin/src/index.ts
Uses webpack's internal resolver to resolve aliased paths during WyW's evaluation phase.
This allows WyW to resolve aliased paths (through tsconfig) in Next.js to their actual paths.
Closes #41482
=> [pigment-css][nextjs-plugin] Fix alias resolver

packages/pigment-css-react/package.json, packages/pigment-css-react/src/Box.d.ts, packages/pigment-css-react/src/Box.jsx, packages/pigment-css-react/src/base.d.ts, packages/pigment-css-react/src/processors/sx.ts, packages/pigment-css-react/src/styled.d.ts, packages/pigment-css-react/tests/Box.spec.tsx, packages/pigment-css-react/tsup.config.ts
This is nothing but just a wrapper component with special handling for transformed sx prop.
=> [pigment-css] Add Box component

packages/pigment-css-react/README.md
The docs around theme typing have the import from `@pigment-css/react` when it's actually exported from `@pigment-css/react/theme`. Fixing the docs.
=> [docs][pigment-css] Fixing location of the ExtendTheme type in the docs

packages/pigment-css-nextjs-plugin/src/index.ts, packages/pigment-css-unplugin/src/index.ts
Resolve React and other related libraries to the actual ones in node_modules instead of Next.js' own version of React that will also include RSC related code that is not actually needed during WyW eval.
It also fixes the next.js demo app which broke after merging #41494
=> [pigment-css][nextjs-plugin] Follow-up to #41494

.circleci/config.yml
So we don't have to duplicate the same tokens in each GitHub repository configuration. Simpler for the code-infra to work on the codebase.
=> [core] Use Circle CI context

packages/pigment-css-react/README.md
=> [pigment-css][docs] Add media query guide

docs/data/material/getting-started/templates/landing-page/components/Hero.js, docs/data/material/getting-started/templates/landing-page/components/Hero.tsx
Added `clamp()` to the `h1` element in the landing page template to fix the massive layout shift on mobile when switching themes.
https://deploy-preview-41543--material-ui.netlify.app/material-ui/getting-started/templates/landing-page/
=> [material-ui][docs] Fix landing page template's h1 size

docs/src/modules/components/AppSearch.js
I don't think this label existed in the Algolia search input before or I just recently noticed it was visible, even though its class name is `DocSearch-VisuallyHiddenForAccessibility`. I guess we indeed don't want that to be visible as it overlaps with the input's placeholder, but it should still be there for accessibility. So, in this PR, I'm just using the available class to add CSS that will visually hide it, as the class name suggests it should be :)
| <img width="664" alt="Screenshot 2024-03-18 at 09 30 12" src="https://github.com/mui/material-ui/assets/67129314/a2e8b188-cf3d-4cfa-95be-8bb743641ebb"> | <img width="664" alt="Screenshot 2024-03-18 at 09 30 20" src="https://github.com/mui/material-ui/assets/67129314/dedd166a-9d15-4d55-8749-1eddcb9eb …
=> [docs-infra] Make the Algolia search input label invisible

apps/pigment-css-next-app/src/app/material-ui/react-breadcrumbs/page.tsx, apps/pigment-css-vite-app/src/pages/material-ui/react-breadcrumbs.tsx, apps/pnpm-lock.yaml, packages/mui-material/src/Breadcrumbs/Breadcrumbs.js
These steps were not needed for this component AFAIK, correct me if I'm wrong.
- **Move `ownerState` from the root style argument callback to variants**
- **Use `Object.entries(theme.palette)` to populate colors**
https://github.com/mui/material-ui/assets/44305048/6e15d842-add6-4303-93e5-fdff74d928fb
@siriwatknp
=> [material-ui][Breadcrumbs] Convert to support CSS extraction

docs/src/components/about/Team.tsx, docs/src/components/pricing/LicensingModelSwitch.tsx, docs/src/components/pricing/PricingTable.tsx, docs/src/components/productX/XHero.tsx, docs/src/components/showcase/FolderTable.tsx, docs/src/components/showcase/NotificationCard.tsx, docs/src/components/showcase/PlayerCard.tsx, docs/src/components/showcase/RealEstateCard.tsx, docs/src/components/showcase/TaskCard.tsx, docs/src/components/showcase/ThemeAccordion.tsx, docs/src/components/showcase/ThemeDatePicker.tsx, docs/src/components/showcase/ThemeSlider.tsx, docs/src/components/showcase/ThemeTabs.tsx, docs/src/components/showcase/ThemeTimeline.tsx, docs/src/components/showcase/ThemeToggleButton.tsx, docs/src/modules/brandingTheme.ts
Mostly color, spacing, and typography-related adjustments throughout some places of the website, but mostly in the homepage's hero components. Just housekeeping here, nothing too crazy.
=> [website] Add stray design adjustments throughout the site

docs/data/base/getting-started/quickstart/quickstart.md, docs/data/base/guides/working-with-tailwind-css/working-with-tailwind-css.md, docs/data/joy/getting-started/installation/installation.md, docs/data/joy/integrations/icon-libraries/icon-libraries.md, docs/data/material/components/about-the-lab/about-the-lab.md, docs/data/material/components/icons/icons.md, docs/data/material/components/material-icons/material-icons.md, docs/data/material/getting-started/installation/installation.md, docs/data/material/integrations/nextjs/nextjs.md, docs/data/styles/basics/basics.md, docs/data/system/getting-started/installation/installation.md, packages/mui-base/README.md, packages/mui-docs/README.md, packages/mui-joy/README.md, packages/mui-material/README.md, packages/mui-styles/README.md
I noticed that we were missing the `` statement on the installation guides. I've udpated the readmes and the docs and added the comment.
=> [docs] Update the installation guides to use the next tag
