mui/material-ui

- apps/pnpm-lock.yaml
- packages/mui-material/src/AvatarGroup/AvatarGroup.js
Part of https://github.com/mui/material-ui/issues/41273
> [material-ui][AvatarGroup] Convert to support CSS extraction

- apps/pigment-css-next-app/src/app/material-ui/react-popover/page.tsx
- packages/mui-material/src/Popover/Popover.js
The reason the hover popover isn't working is because due to the `sx` not working, since it needs `pointerEvents: 'none'` for it to work on hover.
https://github.com/mui/material-ui/assets/44305048/0ec85b95-6198-4a0d-aa6d-9746d868ff21
@siriwatknp
> [material-ui][Popover] Convert to support CSS extraction

- docs/pages/_app.js
We need to be able to link the next docs from the main one.
> [docs] Update the versions dropdown to show v6

- docs/data/material/components/slider/DiscreteSliderValues.js
- docs/data/material/components/slider/DiscreteSliderValues.tsx
- docs/data/material/components/slider/DiscreteSliderValues.tsx.preview
Preview: https://deploy-preview-41567--material-ui.netlify.app/material-ui/react-slider/#restricted-values
Going through the Slider documentation, for all code examples that have value labels and tooltip thumb labels, these values match (see Custom marks and Label always visible examples) except for the Restricted values example.
I'm proposing this change to have the tooltip thumb label match the value label by removing the `valueLabelFormat` prop from the example. Doing this will then make the example look like the below screenshot:
> [docs][material-ui][Slider] Remove `valueLabelFormat` from restricted values demo so that the tooltip thumb label displays the same as the value text

- packages/pigment-css-react/README.md
- packages/pigment-css-react/package.json
- packages/pigment-css-react/src/RtlProvider.tsx
- packages/pigment-css-react/src/utils/cssFnValueToVariable.ts
- packages/pigment-css-react/src/utils/preprocessor.ts
- packages/pigment-css-react/tests/styled/fixtures/styled-rtl.input.js
- packages/pigment-css-react/tests/styled/fixtures/styled-rtl.output.css
- packages/pigment-css-react/tests/styled/fixtures/styled-rtl.output.js
- packages/pigment-css-react/tests/styled/styled.test.ts
- packages/pigment-css-react/tests/testUtils.ts
- packages/pigment-css-react/tsconfig.json
- packages/pigment-css-react/tsup.config.ts
- packages/pigment-css-vite-plugin/src/index.ts
- packages/pigment-css-vite-plugin/src/vite-plugin.ts
- pnpm-lock.yaml
* Re-export `RtlProvider` from `@mui/system`
* Also implements built-in RTL support. See the added test files.
Note: There is one optimization that we can pick-up later is to only add properties that actually changed in the output from ltr to rtl, ie, for:
```css
.class {
display: block;
margin-left: 20px;
}
```
The output should not include the `display` property since it's common in both.
> [pigment-css][react] RTL Support

- apps/README.md
- apps/pigment-css-next-app/package.json
- apps/pigment-css-vite-app/package.json
- apps/pigment-css-vite-app/vite-env.d.ts
- apps/pigment-css-vite-app/vite.config.ts
- apps/pnpm-workspace.yaml
- nx.json
- packages-internal/scripts/package.json
- packages/pigment-css-nextjs-plugin/src/index.ts
- packages/pigment-css-react/package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
and revert to using project workspace.
Fix a minor typing issue in the Vite app.
Fixes - https://github.com/mui/material-ui/pull/41342
> [pigment-css][demo] Remove app specific pnpm workspace

- apps/pigment-css-next-app/src/app/material-ui/react-backdrop/page.tsx
- packages/mui-material/src/Backdrop/Backdrop.js
https://github.com/mui/material-ui/assets/44305048/48b19a8c-e504-4ec4-a0fa-bf3fe0ff45a8
@siriwatknp
> [material-ui][Backdrop] Convert to support CSS extraction

- apps/pigment-css-next-app/src/app/material-ui/react-card/page.tsx
- packages/mui-material/src/Card/Card.js
- packages/mui-material/src/CardActionArea/CardActionArea.js
- packages/mui-material/src/CardActions/CardActions.js
- packages/mui-material/src/CardContent/CardContent.js
- packages/mui-material/src/CardHeader/CardHeader.js
- packages/mui-material/src/CardMedia/CardMedia.js
Hey @siriwatknp, I see the assets have not been moved to the docs, should we update the script to do that as well?
https://github.com/mui/material-ui/assets/44305048/76bd5f63-b5a5-477e-902e-b693b25c3ea2
> [material-ui][Card] Convert to support CSS extraction

- apps/pigment-css-vite-app/package.json
- apps/pigment-css-vite-app/src/pages/material-ui/index.tsx
- apps/pigment-css-vite-app/src/pages/material-ui/react-breadcrumbs.tsx
- packages/pigment-css-nextjs-plugin/src/index.ts
- pnpm-lock.yaml
components, similar to the one we have in the next.js demo
> [pigment-css][demo] Add index page for material-ui

- scripts/README.md
Add instructions to the guide about deploying docs without a release to avoid the following pitfalls:
- The local `material-ui-docs/latest` branch isn't updated
- The cherry-picked commit doesn't exist on the local branch
> [core] Add instructions to deploying docs guide

- packages/pigment-css-react/README.md
Just a few writing tweaks:
- "RTL" might be a well-known acronym, but I don't think it hurts to start first with what it means and then introduce the acronym later on _after_ we have mentioned its meaning.
- Moving this section above the "How-to guides". It feels like a feature that'd be a sibling to "Theming"?
> [pigment-css][docs] Update the RTL section on the readme

- docs/src/components/pricing/PricingTable.tsx
Cherry-pick of https://github.com/mui/material-ui/pull/41595 to the `master` branch.
> [website] Update pricing table

- docs/data/material/pages.ts
- docs/translations/translations.json
This PR removes the now non-existing "Material Design 3 components" page from the list of pages. I'm assuming we'll want to cherry-pick this one into master as well?
> [material-ui][docs] Remove deleted page from the sidenav

- packages/mui-system/src/colorManipulator/colorManipulator.js
closes #41615 
the previous version cause infinite recursion
```tsx
export function private_safeEmphasize(color, coefficient, warning) {
try {
//    return private_safeEmphasize(color, coefficient);
return emphasize(color, coefficient);
} catch (error) {
if (warning && process.env.NODE_ENV !== 'production') {
console.warn(warning);
}
return color;
}
}
```
> [system] Fix typo to avoid infinite recursion in function call.

- apps/pigment-css-next-app/src/app/material-ui/react-bottom-navigation/page.tsx
- packages/mui-material/src/BottomNavigation/BottomNavigation.js
- packages/mui-material/src/BottomNavigationAction/BottomNavigationAction.js
- scripts/pigmentcss-render-mui-demos.mjs
https://github.com/mui/material-ui/assets/44305048/d3008ee1-b7a8-4f1c-8ce3-8d49d526584f
@siriwatknp there are some hydration errors in the demos, should I fix them as well?
Other than that, I updated the script to render demos since for components with two words we had a small issue:
>  [material-ui][BottomNavigation] Convert to support CSS extraction

- packages/mui-material/src/FormControl/FormControl.js
- packages/mui-material/src/FormControlLabel/FormControlLabel.js
https://github.com/mui/material-ui/assets/44305048/6b482cc0-13bc-44e9-b321-6f864a0847e7
@siriwatknp since Switch is one of the places the FormControl is used, I picked that page to showcase the demo video.
> [material-ui][FormControl] Convert to support CSS extraction

- packages/mui-material/src/FormGroup/FormGroup.js
https://github.com/mui/material-ui/assets/44305048/174d7913-06ec-4136-9d0d-1013d63ce952
@siriwatknp just like FormControl, I used the Switch demo to showcase the FormGroup.
> [material-ui][FormGroup] Convert to support CSS extraction

- docs/mui-vale/styles/MUI/MuiBrandName.yml
- packages/mui-codemod/src/deprecations/all/deprecations-all.js
- packages/mui-system/src/borders/index.ts
- packages/mui-system/src/breakpoints/index.ts
- packages/mui-system/src/colorManipulator/index.ts
- packages/mui-system/src/compose/index.ts
- packages/mui-system/src/createBox/index.ts
- packages/mui-system/src/createStyled/index.ts
- packages/mui-system/src/cssGrid/index.ts
- packages/mui-system/src/display/index.ts
- packages/mui-system/src/flexbox/index.ts
- packages/mui-system/src/getThemeValue/index.ts
- packages/mui-system/src/memoize/index.ts
- packages/mui-system/src/merge/index.ts
- packages/mui-system/src/palette/index.ts
- packages/mui-system/src/positions/index.ts
- packages/mui-system/src/propsToClassKey/index.ts
- packages/mui-system/src/responsivePropType/index.ts
- packages/mui-system/src/shadows/index.ts
- packages/mui-system/src/sizing/index.ts
- packages/mui-system/src/spacing/index.ts
- packages/mui-system/src/style/index.ts
- packages/mui-system/src/styled/index.ts
- packages/mui-system/src/typography/index.ts
- packages/mui-system/src/useTheme/index.ts
- packages/mui-system/src/useThemeWithoutDefault/index.ts
- pnpm-lock.yaml
> [core] Fix failing CI steps

- docs/pages/blog/mui-x-v7.md
Cherry-pick of https://github.com/mui/material-ui/pull/41640
> [blog] Link to Romain's blog post in MUI X v7 announcement post

- package.json
- packages/mui-joy/src/Input/Input.tsx
- packages/pigment-css-react/tests/styled/fixtures/styled-rtl.output.js
- packages/pigment-css-react/tests/styled/fixtures/styled-theme.output.js
- packages/pigment-css-react/tests/styled/fixtures/styled.output.js
- pnpm-lock.yaml
Ran `pnpm dedupe` to remove older versions of dependencies from the lockfile.
Pinned @types/react to 18.2.55 due to issues with proptypes generation and react-virtuoso types.
> [core] Run pnpm dedupe

- .circleci/config.yml
* compare against the `next` branch
* include package.json
* fix lock file name
Note: the check is passing in this CI run because we're not editing any of these files. But it's currently broken on CI. Will fix in a separate PR
> Fix dedupe check

- packages/mui-icons-material/package.json
- packages/mui-lab/package.json
- packages/mui-material-nextjs/package.json
- pnpm-lock.yaml
- Adds a missing @mui/material dev dependency to @mui/lab
- Updates peer dep version ranges in @mui/material-nextjs and @mui/lab
> [core] Update peerDependencies ranges to include v6 packages

- docs/data/material/migration/migrating-from-deprecated-apis/migrating-from-deprecated-apis.md
- docs/pages/material-ui/api/badge.json
- docs/translations/api-docs/badge/badge.json
- packages/mui-codemod/README.md
- packages/mui-codemod/src/deprecations/badge-props/badge-props.js
- packages/mui-codemod/src/deprecations/badge-props/badge-props.test.js
- packages/mui-codemod/src/deprecations/badge-props/index.js
- packages/mui-codemod/src/deprecations/badge-props/test-cases/actual.js
- packages/mui-codemod/src/deprecations/badge-props/test-cases/expected.js
- packages/mui-codemod/src/deprecations/badge-props/test-cases/theme.actual.js
- packages/mui-codemod/src/deprecations/badge-props/test-cases/theme.expected.js
- packages/mui-material/src/Badge/Badge.d.ts
- packages/mui-material/src/Badge/Badge.js
Hey @DiegoAndai  sorry for troubles due to lot of merge conflit i had to create new pr 🙏 .
part of #40417
> [material-ui][Badge] Deprecate components and componentsProps

- docs/src/modules/components/TopLayoutCareers.js
A continuation of #40793. The goal is for the subpages of https://mui.com/careers/ to have the same OG image. I needed this for https://twitter.com/olivtassinari/status/1772728620949139795. Instead, I had to add the image as an attachment but it's not a great UX, people can't click on the image, it's not a link.
Well, to be fair, ideally, it should be customized per role like in #41188. But this feels already a step forward, with less effort.
> [website] Improve job og image

- packages/mui-material/src/RadioGroup/RadioGroup.d.ts
- packages/mui-material/src/RadioGroup/RadioGroup.js
- packages/mui-material/src/RadioGroup/RadioGroup.test.js
- packages/mui-material/src/RadioGroup/index.d.ts
- packages/mui-material/src/RadioGroup/index.js
- packages/mui-material/src/RadioGroup/radioGroupClasses.ts
- packages/mui-material/src/styles/components.d.ts
- packages/mui-material/src/styles/createTheme.spec.ts
- packages/mui-material/src/styles/overrides.d.ts
Fixes #41076
Preview: https://deploy-preview-41610--material-ui.netlify.app/material-ui/react-radio-button/
Rather than modifying the radio group classnames in the API documentation, I think the correct fix is to apply those classnames to the Radio Group component. The API documentation for Radio button CSS classes is correct.
Having both `MuiFormGroup` and `MuiRadioGroup` classes might not seem ideal, but it's consistent with other components like the Outlined Input, which has both `MuiOutlinedInput` and `MuiInputBase` related classnames. However, this does lead to an increase in bundle size.
If we decide to retain only the radio group related classes, two things need consideration:
- Removing form group related classnames would constitute a breaking change, which might be acceptable for …
> [material-ui][RadioGroup] Apply classnames

- packages/mui-material/src/Autocomplete/Autocomplete.test.js
> [test] Add test to display options provided to the options prop even if loading is true.

- packages/mui-material/src/RadioGroup/RadioGroup.d.ts
- packages/mui-material/src/RadioGroup/RadioGroup.js
- packages/mui-material/src/RadioGroup/RadioGroup.test.js
- packages/mui-material/src/RadioGroup/index.d.ts
- packages/mui-material/src/RadioGroup/index.js
- packages/mui-material/src/RadioGroup/radioGroupClasses.ts
- packages/mui-material/src/styles/components.d.ts
- packages/mui-material/src/styles/createTheme.spec.ts
- packages/mui-material/src/styles/overrides.d.ts
Cherry-pick e85839fe8a8fb31a4c2e01e6d2b47ed398866257.
> [material-ui][RadioGroup] Apply classnames 

- docs/data/material/experimental-api/css-theme-variables/customization.md
Cherry-pick 0080b1bbeccf445962009e75a99df39c799e64ff.
> [docs][material-ui] Fix typo in CSS theme variables customization

- packages/pigment-css-react/package.json
- packages/pigment-css-react/src/utils/remove-prop-types-plugin.ts
- packages/pigment-css-react/tests/styled/fixtures/styled-theme.input.js
- packages/pigment-css-react/tests/styled/fixtures/styled-theme.output.js
- packages/pigment-css-react/tests/styled/fixtures/styled.input.js
- packages/pigment-css-react/tests/styled/fixtures/styled.output.js
- packages/pigment-css-react/tests/testUtils.ts
- pnpm-lock.yaml
Conditional assignment of propTypes was not handled resulting in error while using prod builds of material-ui.
> [pigment-css] Fix propTypes removal during eval stage

- docs/src/modules/components/EditPage.js
When documenting interfaces, their is no obvious file to point to, so the sourceCode is an empty string which will be supported by this PR
> [docs-infra] Allows to remove edit button

- apps/pigment-css-next-app/README.md
- apps/pigment-css-vite-app/README.md
Found these quick-win improvement opportunities as I was setting up a new test project. Not a super critical review, but I'm curious whether the command `pnpm build:zero` is still correct, though (after we changed the package's name)?
> [pigment-css][docs] Edit the example app's README files

- .github/workflows/cherry-pick-next-to-master.yml
As @oliviertassinari [suggested](https://github.com/mui/material-ui/pull/41736#issuecomment-2030383966), this PR adds a GitHub Action to automate cherry-picking PRs from `next` to `master` (see Olivier's comment to see how it works). The code is an exact copy from [MUI X](https://github.com/mui/mui-x/blob/master/.github/workflows/cherry-pick-next-to-master.yml) (thanks @MBilalShafi !).
cc @danilo-leal
> [core] Automate cherry-pick of PRs from `next` -> `master`

- apps/pigment-css-next-app/src/app/material-ui/page.tsx
- apps/pigment-css-vite-app/package.json
- apps/pigment-css-vite-app/src/main.tsx
- apps/pigment-css-vite-app/src/pages/material-ui/index.tsx
- packages/pigment-css-react/src/Box.d.ts
- packages/pigment-css-react/src/Box.jsx
- packages/pigment-css-react/src/processors/sx.ts
- packages/pigment-css-react/tests/Box/box.test.tsx
- packages/pigment-css-react/tests/Box/fixtures/box.input.js
- packages/pigment-css-react/tests/Box/fixtures/box.output.css
- packages/pigment-css-react/tests/Box/fixtures/box.output.js
This current fix is very crude and does not handle the case when a user might have their own wrapper component over Box and they'll be passing sx prop through the component. We need to have a better option to customize the condition.
Also made `Box` as a default import instead of name import.
Fixes #41704
> [pigment-css][react] Fix sx prop transformation on Box

- packages/mui-material/src/Slider/Slider.js
Issue: https://mui.com/material-ui/.
I don't have time to dig down to the root cause at the moment. This is a quick fix to get rid of the styles generation error.
**After**: https://deploy-preview-41676--material-ui.netlify.app/material-ui/
---
> [material-ui][slider] Move palette styles to the bottom

- packages/pigment-css-react/README.md
Little improvement opportunities I realized while testing Pigment CSS on a fresh new repo.
> [pigment-css][docs] Add small edits on the README

- packages/markdown/loader.js
- Skips extracting imports for modules which are not editable demos
- Relies on `hideToolbar` being `true` as the configuration property to detect the above
- Fixes #41585 
Before:
After:
> [docs-infra] Skip loading source for non-editable modules

- docs/src/modules/utils/getProductInfoFromUrl.ts
- Noticed as part of https://github.com/mui/material-ui/pull/41316#discussion_r1529470379
> [docs-infra] Add Toolpad product/category IDs to types

- packages/mui-material/src/Autocomplete/Autocomplete.js
- packages/mui-material/src/Autocomplete/Autocomplete.test.js
Cherry-pick 31d5291c7990b963e909868d0ebb3b870ac2baa2 and d5c16c101a18bc06f80a66a0f6d413e86476a7b2.
> [material-ui][Autocomplete] Display options provided to the `options` prop even if loading is true.

- docs/data/material/components/slider/DiscreteSliderValues.js
- docs/data/material/components/slider/DiscreteSliderValues.tsx
- docs/data/material/components/slider/DiscreteSliderValues.tsx.preview
Cherry-pick b96215e09b600b68a5c03821c83ef12c3095943c.
> [docs][material-ui][Slider] Remove valueLabelFormat from restricted values demo so that the tooltip thumb label displays the same as the value text

- packages/pigment-css-unplugin/src/index.ts
- packages/pigment-css-vite-plugin/src/index.ts
I missed this in the original PR
> [pigment-css][nextjs-plugin] Add missing RTL implementation

- docs/data/material/components/material-icons/material-icons.md
Noticed recently on the weekly algolia email report that "icons" is the top search term, by a large margin. I find myself using this term most often to get to the icons search interface. Yet, the experience is not clear, the search box shows two pages for the "icons" term.
Proposing to add a subtitle that can show up in this search box to help disambiguate which page contains the icon search experience.
> [material-ui][docs] Add subtitle to icons search UI

- .github/ISSUE_TEMPLATE/1.bug.yml
- .github/ISSUE_TEMPLATE/2.feature.yml
- .github/ISSUE_TEMPLATE/4.docs-feedback.yml
- .github/ISSUE_TEMPLATE/5.priority-support.yml
- .github/ISSUE_TEMPLATE/config.yml
This seems to make sense as we direct Base UI contributions to its own repo! Also, I have intentionally not added Pigment CSS yet, as we might also extract it to a dedicated repo.
> [core] Remove Base UI mentions from issues templates

- docs/data/material/components/app-bar/app-bar.md
- docs/data/material/components/cards/cards.md
- docs/data/material/components/lists/lists.md
- docs/data/material/components/progress/progress.md
- docs/data/material/components/slider/slider.md
- docs/data/material/components/table/table.md
- docs/data/material/getting-started/supported-platforms/supported-platforms.md
- docs/data/material/guides/minimizing-bundle-size/minimizing-bundle-size.md
- docs/data/material/migration/migration-v4/migration-v4.md
- docs/translations/api-docs-joy/table/table.json
- docs/translations/api-docs/table/table.json
- packages/mui-joy/src/Table/Table.tsx
- packages/mui-joy/src/Table/TableProps.ts
- packages/mui-material/src/Table/Table.d.ts
- packages/mui-material/src/Table/Table.js
This is the first step towards #14420. This PR official communicates that IE 11 is no longer supported. This is a breaking change.
More changes will be required to close the issue, but they won't be breaking changes in theory as IE 11 is no longer supported https://github.com/mui/material-ui/pull/41611#issuecomment-2027080816.
> [docs] Drop IE 11 official support

- docs/src/modules/components/Ad.js
- docs/src/modules/components/AdCarbon.js
- docs/src/modules/components/AdDisplay.js
- docs/src/modules/constants.js
Fix the data collection about the inline ads. Needed to collect statistics on to move on #39285
Current statistics can be seen here:
https://analytics.google.com/analytics/web/#/analysis/p353089763/edit/9w1vckV7T1umgP5PSvL3vw
The `display` and `click` action have both been tested with the Google tag assistant. They are correctly recognized :+1:
> [docs-infra] Fix analytics about inline ads

- CHANGELOG.md
- package.json
- packages-internal/docs-utils/package.json
- packages-internal/scripts/package.json
- packages/markdown/package.json
- packages/mui-babel-macros/package.json
- packages/mui-base/package.json
- packages/mui-codemod/package.json
- packages/mui-core-downloads-tracker/package.json
- packages/mui-docs/package.json
- packages/mui-envinfo/package.json
- packages/mui-icons-material/package.json
- packages/mui-joy/package.json
- packages/mui-lab/package.json
- packages/mui-material/package.json
- packages/mui-private-theming/package.json
- packages/mui-styled-engine-sc/package.json
- packages/mui-styled-engine/package.json
- packages/mui-styles/package.json
- packages/mui-system/package.json
- packages/mui-utils/package.json
- packages/pigment-css-nextjs-plugin/package.json
- packages/pigment-css-react/package.json
- packages/pigment-css-unplugin/package.json
- packages/pigment-css-vite-plugin/package.json
- pnpm-lock.yaml
> 6.0.0-alpha.1

- docs/src/modules/components/AppFrame.js
The useMemo was not working because `onClose` is an arrow function, so its ref is different each time
> [docs-infra] Fix drawer performances

- packages/pigment-css-react/src/utils/remove-prop-types-plugin.ts
- packages/pigment-css-react/tests/styled/fixtures/styled-theme.input.js
- packages/pigment-css-react/tests/styled/fixtures/styled-theme.output.js
- packages/pigment-css-react/tests/styled/fixtures/styled.input.js
- packages/pigment-css-react/tests/styled/fixtures/styled.output.js
> [pigment-css][core] Remove  during eval phase

- packages/pigment-css-unplugin/src/utils.ts
- packages/pigment-css-unplugin/tests/utils.test.ts
Followup PR to #41758 to handle file path passed to CSS after importing in source code
> [pigment-css][nextjs] Handle file references passed through imports

- docs/src/modules/components/Ad.js
- docs/src/modules/components/AdCarbon.js
- docs/src/modules/components/AdDisplay.js
- docs/src/modules/constants.js
Cherry picking of #41474
Done in duplicate to directly get the analytics without having to wait for the end of the unstable phase
> [docs-infra] Fix analytics about inline ads (#41474)

- packages/mui-codemod/src/deprecations/accordion-props/accordion-props.js
- packages/mui-codemod/src/deprecations/accordion-props/test-cases/actual.js
- packages/mui-codemod/src/deprecations/accordion-props/test-cases/expected.js
- packages/mui-codemod/src/deprecations/accordion-props/test-cases/theme.actual.js
- packages/mui-codemod/src/deprecations/accordion-props/test-cases/theme.expected.js
- packages/mui-codemod/src/deprecations/avatar-props/avatar-props.js
- packages/mui-codemod/src/deprecations/avatar-props/test-cases/actual.js
- packages/mui-codemod/src/deprecations/avatar-props/test-cases/expected.js
- packages/mui-codemod/src/deprecations/avatar-props/test-cases/theme.actual.js
- packages/mui-codemod/src/deprecations/avatar-props/test-cases/theme.expected.js
- packages/mui-codemod/src/deprecations/backdrop-props/backdrop-props.js
- packages/mui-codemod/src/deprecations/backdrop-props/backdrop-props.test.js
- packages/mui-codemod/src/deprecations/backdrop-props/test-cases/actual.js
- packages/mui-codemod/src/deprecations/backdrop-props/test-cases/expected.js
- packages/mui-codemod/src/deprecations/backdrop-props/test-cases/theme.actual.js
- packages/mui-codemod/src/deprecations/backdrop-props/test-cases/theme.expected.js
- packages/mui-codemod/src/deprecations/utils/movePropIntoSlotProps.js
- packages/mui-codemod/src/deprecations/utils/movePropIntoSlots.js
Part of https://github.com/mui/material-ui/issues/41281
Add `movePropIntoSlots` and `movePropIntoSlotProps` utils for creating codemods, simplifying the development of new codemods for the `*Component` and `*Props` props deprecations.
Use these new utils on the existing `*Component` and `*Props` props deprecations and add tests for edge cases.
> [codemod] Add utils for `*Component` and `*Props` props deprecations

- packages/mui-material/src/Typography/Typography.js
In https://github.com/mui/material-ui/pull/38123 the styles were supposed to be moved from the theme into the styled component but `lineHeight` and `letterSpacing` styles were missed and it caused regressions when using `button`.
Styles that were not moved over: https://github.com/mui/material-ui/pull/38123/files#diff-48a50468b17f36e83faa75d3f1a78ba450b0c78d0cdc6ebfbe1cb27ec5130e1aR80-R81
> [material-ui][Typography] Fix Typography inherit variant styles

- packages/api-docs-builder/ApiBuilders/HookApiBuilder.ts
- packages/api-docs-builder/ProjectSettings.ts
Makes hooks' import statements customizable, similarly to components. Keeps the previous logic as default if the corresponding option isn't set.
> [code-infra] Allow customizing hooks imports in API docs generator

- docs/data/material/migration/migrating-from-deprecated-apis/migrating-from-deprecated-apis.md
- docs/pages/material-ui/api/step-label.json
- docs/translations/api-docs/step-label/step-label.json
- packages/mui-codemod/README.md
- packages/mui-codemod/src/deprecations/step-label-props/step-label-props.js
- packages/mui-codemod/src/deprecations/step-label-props/test-cases/actual.js
- packages/mui-codemod/src/deprecations/step-label-props/test-cases/expected.js
- packages/mui-codemod/src/deprecations/step-label-props/test-cases/theme.actual.js
- packages/mui-codemod/src/deprecations/step-label-props/test-cases/theme.expected.js
- packages/mui-material/src/StepLabel/StepLabel.d.ts
- packages/mui-material/src/StepLabel/StepLabel.js
part of https://github.com/mui/material-ui/issues/41281
> [material-ui][StepLabel] Deprecate `StepIconComponent`, `StepIconProps`

- docs/pages/_app.js
Noticed while working on https://github.com/mui/mui-x/pull/12232
`require.context` returns [all possible requests](https://github.com/webpack/webpack/issues/12087#issuecomment-737532578) that can be made. `req.keys()` returns 
```tsx
[ './translations.json', 'docs/translations/translations.json' ]
```
after the change it returns
```tsx
[ './translations.json' ]
```
> [code-infra] Fix require.context with aliases

- apps/pigment-css-next-app/src/app/material-ui/react-floating-action-button/page.tsx
- apps/pigment-css-vite-app/src/pages/material-ui/react-floating-action-button.tsx
- packages/mui-material/src/Fab/Fab.js
Part of https://github.com/mui/material-ui/issues/41273
@siriwatknp 
I found 2 problems.
It seems the sx prop in the example doesn't work. I couldn't find how this should be fixed. This results in a gray left aligned Fab, instead of a right aligned green fab.
| Pigment | Current |
| <img width="808" alt="image" src="https://github.com/mui/material-ui/assets/7714133/ab0fcafa-be54-457b-b563-84a5fd8c09b1"> | <img width="652" alt="image" src="https://github.com/mui/material-ui/assets/7714133/3140c3ee-c8c5-4b48-b11e-f1f810a6d62e"> | 
In dark mode it also uses the css var for primary text to style the default button. This results in white text on the `grey[300]` background. without vars it uses the `getContrastText` function to determine a color.
```
color: theme.vars
? …
```
> [material-ui][FloatingActionButton] Convert to support CSS extraction

- docs/data/material/components/icons/CreateSvgIcon.js
- docs/data/material/components/icons/CreateSvgIcon.tsx
- docs/data/material/components/icons/SvgIconChildren.js
- docs/data/material/components/icons/SvgIconChildren.tsx
- docs/data/material/components/icons/SvgIconChildren.tsx.preview
Fixes a tiny typo in a credit comment. The icon is a `cog`, not a `plus`.
> [material-ui][docs] Fix credit comment typo

- docs/data/material/components/buttons/InputFileUpload.js
- docs/data/material/components/buttons/InputFileUpload.tsx
- docs/data/material/components/buttons/InputFileUpload.tsx.preview
Adding an `onChange` event handler to the "File upload" Button [example](https://mui.com/material-ui/react-button/#file-upload) after receiving this feedback:
> For file upload example, there is no code that handles the upload event (i.e. doing something with the file.) I'm stuck on this at the moment.
Also making the input `multiple`.
> [material-ui][Button] Add `onChange` event handler to file upload example

- docs/data/material/integrations/nextjs/nextjs.md
Fixing a quick regression from #41508. I couldn't find other bugs of this class in the codebase.
Before https://mui.com/material-ui/integrations/nextjs/#theming-2
After https://deploy-preview-41882--material-ui.netlify.app/material-ui/integrations/nextjs/#theming-2
> [docs] Fix format git diff regression

- netlify/edge-functions/og-image.tsx
Really just tiny tweaks. This is how it is supposed to be now: https://stackblitz.com/edit/vitejs-vite-ukeejd?file=src/App.tsx
> [docs-infra] Fine-tune the OG card image design

- CHANGELOG.md
- package.json
- packages-internal/docs-utils/package.json
- packages-internal/scripts/package.json
- packages/markdown/package.json
- packages/mui-babel-macros/package.json
- packages/mui-codemod/package.json
- packages/mui-core-downloads-tracker/package.json
- packages/mui-docs/package.json
- packages/mui-icons-material/package.json
- packages/mui-joy/package.json
- packages/mui-lab/package.json
- packages/mui-material/package.json
- packages/mui-private-theming/package.json
- packages/mui-styled-engine-sc/package.json
- packages/mui-styled-engine/package.json
- packages/mui-styles/package.json
- packages/mui-system/package.json
- packages/mui-utils/package.json
- packages/pigment-css-nextjs-plugin/package.json
- packages/pigment-css-react/package.json
- packages/pigment-css-unplugin/package.json
- packages/pigment-css-vite-plugin/package.json
> [release] v6.0.0-alpha.3

- docs/src/components/about/HowToSupport.tsx
- docs/src/components/action/NpmCopyButton.tsx
- docs/src/components/home/MaterialDesignDemo.tsx
- docs/src/components/home/ProductSuite.tsx
- docs/src/components/pricing/PricingFAQ.tsx
- docs/src/components/pricing/PricingList.tsx
- docs/src/components/pricing/PricingWhatToExpect.tsx
- docs/src/components/productMaterial/MaterialComponents.tsx
- docs/src/components/productMaterial/MaterialStyling.tsx
- docs/src/components/productMaterial/MaterialTemplates.tsx
- docs/src/components/productMaterial/MaterialTheming.tsx
- docs/src/components/productTemplate/TemplateDemo.tsx
- docs/src/components/productTemplate/TemplateHero.tsx
- docs/src/components/productX/XComponents.tsx
- docs/src/components/productX/XComponentsSwitcher.tsx
- docs/src/components/productX/XDataGrid.tsx
- docs/src/components/productX/XGridFullDemo.tsx
- docs/src/components/productX/XPlans.tsx
- docs/src/components/productX/XRoadmap.tsx
- docs/src/components/productX/XTheming.tsx
- packages/mui-docs/src/branding/brandingTheme.ts
This PR primarily switches the Grid usage to the Grid v2 as a bunch of sections relying on the v1 were broken for some reason. I'm not fully sure why; haven't dug deep. Aside from that, also added other varied improvements here and there throughout different pages and sections—housekeeping.
> [website] Fix grid usage and add stray improvements

- docs/src/modules/components/Demo.js
- docs/src/modules/components/DemoToolbar.js
- docs/src/modules/components/DemoToolbarRoot.ts
- docs/src/modules/components/HighlightedCodeWithTabs.tsx
Little tweaks to fine-tune the demo container even more. The primary change here is making the JS/TS toggle button look more like a pill rather than separate-looking buttons so there's no confusion with the code tabs that have been recently introduced.
https://deploy-preview-41948--material-ui.netlify.app/experiments/docs/demos/
> [docs-infra] Add demo container design refinements

- docs/src/modules/components/ApiPage.js
- docs/src/modules/components/ComponentsApiContent.js
- docs/src/modules/components/HooksApiContent.js
- docs/src/modules/sandbox/Dependencies.ts
- pnpm-lock.yaml
- Hid the "Learn about the difference by reading this guide on minimizing bundle size." text when there is just one export defined.
- Updated the demo sandbox dependencies to work with @base_ui/ and @pigment-css/ scoped packages (cc @mnajdova)
> [docs-infra] Adapt docs infra to Base UI docs needs

- docs/src/modules/components/AppLayoutDocs.js
Revert https://github.com/mui/material-ui/pull/32536, since we have #41188 now 👌. I wanted to tweet to celebrate this change as it's a nice DX improvement, but got blocked by this.
Before
> [docs-infra] Improve Twitter OG:image

- docs/next.config.mjs
- docs/nextConfigDocsInfra.js
I don't understand why we didn't make this a default in https://github.com/mui/material-ui/pull/41132 shared with the other docs. I'm trying this here.
> [docs-infra] Move CPU to shared config

- docs/data/docs-infra/pages.ts
- docs/pages/_document.js
- docs/pages/experiments/docs/og-card.md
I have noticed this small bug on the API pages of MUI X.
Before: https://mui.com/x/api/date-pickers/multi-input-date-time-range-field/
After: https://deploy-preview-41990--material-ui.netlify.app/experiments/docs/og-card/
I have also used the opportunity to improve https://master--material-ui.netlify.app/experiments/docs/og-card/ by isolating what's docs for docs-infra and test for sidenav, and by having more tests for sidenav. It looks like this now:
I'm unclear if we need both "Beta" and "Preview", it feels a bit like the same thing. I would remove Beta.
> [docs-infra] Fix flex-shrink pro-plan

- packages/mui-material/src/styles/experimental_extendTheme.test.js
- packages/mui-material/src/styles/getOverlayAlpha.ts
- getOverlayAlpha() is provided to alpha() who expects a number but it returns a string today
- getOverlayAlpha() return type is missing, breaking MUI's policy
- getOverlayAlpha() is not using a function(), breaking MUI's policy
- two digits seems a bit too light as an approximation, go for 3
> [material-ui] Fix getOverlayAlpha type

- packages/mui-material/src/Autocomplete/Autocomplete.test.js
- test/karma.conf.js
- test/karma.conf.profile.js
Similar to https://github.com/mui/base-ui/pull/179.
Since we've updated the list of supported browsers, we should also update the browser versions in the karma config for browser tests.
`browserstack-force` run : https://app.circleci.com/pipelines/github/mui/material-ui/127738/workflows/6dbb14d6-7afa-4d20-b0e5-f0cae483bcde/jobs/688724.
Also, resolved the `userEvent.setup()` TODO in the Autocomplete test since we now support the new Safari version. I considered refactoring other `userEvent.setup()` TODOs, but they all reside in Base UI, which is planned for removal in the near future.
> [test] Update browser versions in karma config

- docs/src/layouts/AppFooter.tsx
- packages/mui-joy/src/styles/defaultTheme.test.js
- packages/mui-joy/src/styles/extendTheme.test.js
- packages/mui-joy/src/styles/extendTheme.ts
- packages/mui-joy/src/styles/shouldSkipGeneratingVar.ts
- packages/mui-joy/src/styles/types/theme.ts
- packages/mui-material/src/styles/experimental_extendTheme.d.ts
- packages/mui-material/src/styles/experimental_extendTheme.js
- packages/mui-material/src/styles/experimental_extendTheme.test.js
- packages/mui-material/src/styles/shouldSkipGeneratingVar.ts
- packages/mui-system/src/cssVars/prepareTypographyVars.test.ts
- packages/mui-system/src/cssVars/prepareTypographyVars.ts
- packages/mui-system/src/styleFunctionSx/defaultSxConfig.js
Regression from #41703
Changes related to `typography` in #41703 have been reverted. A new field, `font`, is created to store typography token.
**usage**:
```js
<Box sx={{ font: 'h1' }} />
```
---
> [material-ui][joy-ui] Move typography CSS variables to `font`

- docs/pages/careers.tsx
> [website] Close the `Design Engineer - X` role

- docs/pages/_document.js
- packages/mui-docs/src/branding/brandingTheme.ts
As the title says, this PR adds just these two small things:
- adding line breaks in the @ font-face declaration on the `_document.js` file to improve readability.
- removing unnecessary pixel value comments on the branding theme
> [docs-infra] Clean up branding theme file and improve font-face readibility

- docs/src/components/home/AdvancedShowcase.tsx
- docs/src/components/home/CoreShowcase.tsx
- docs/src/components/productBaseUI/BaseUIComponents.tsx
- docs/src/components/productBaseUI/BaseUICustomization.tsx
- docs/src/components/productMaterial/MaterialComponents.tsx
- docs/src/components/productMaterial/MaterialStyling.tsx
- docs/src/components/productMaterial/MaterialTheming.tsx
- docs/src/components/productX/XChartsDemo.tsx
- docs/src/components/productX/XDataGrid.tsx
- docs/src/components/productX/XDateRangeDemo.tsx
- docs/src/components/productX/XTreeViewDemo.tsx
This PR fixes a bug that was introduced after https://github.com/mui/material-ui/pull/41859 where all `MarkdownElement` imports were replaced by the version of this component that now lives in the @mui/docs package. The marketing site pages should use a different version of this component, yet with the same name, which doesn't have some CSS properties from "the original" that mess up with the showcase section's design.
This PR is also a follow-up to a previous one (https://github.com/mui/material-ui/pull/42011), where I tried to fix this problem _and_ improve the whole thing by removing the duplicate `MarkdownElement` components. In there, we concluded that it was best to have two PRs rather than one doing two things. This is part one. The second part will follow right after.
- Before: …
> [website] Fix code block design by changing the `MarkdownElement` import

- docs/pages/careers.tsx
- docs/pages/careers/design-engineer-x-grid.js
- docs/pages/careers/design-engineer.js
- docs/pages/careers/product-marketing-manager.js
- docs/pages/careers/react-engineer-core.js
- docs/pages/careers/react-engineer-x.md
- docs/pages/careers/support-agent.md
A quick iteration to better sync career roles and Notion source of truth. There are a bunch of roles to add, but writing them will take time.
Preview: https://deploy-preview-42058--material-ui.netlify.app/careers/
> [website] Sync career roles

- .eslintrc.js
- apps/pigment-css-vite-app/src/Slider/ZeroSlider.tsx
- docs/src/pages/premium-themes/onepirate/modules/components/Snackbar.tsx
A step to fix https://github.com/mui/mui-toolpad/pull/3417/files#r1572992179 at the root.
https://eslint.org/docs/latest/rules/no-restricted-imports
> [core] Restrict import path with ESLint

- docs/data/material/design-resources/material-ui-sync/material-ui-sync.md
Just realized that the Canny.io link was with the old URL.
> [material-ui][docs] Fix link on the Sync page

- .circleci/config.yml
Bumping to use the latest LTS (v18.x) version to benefit from updates and security fixes.
https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V18.md
Replicate change done on https://github.com/mui/mui-x/pull/12961
> [code-infra] Bump node image used by CI in docker

- docs/src/components/banner/AppHeaderBanner.tsx
- docs/src/featureToggle.js
> [website] Remove Survey banner from website and Core docs

- docs/data/joy/components/autocomplete/CountrySelect.js
- docs/data/joy/components/autocomplete/CountrySelect.tsx
- docs/data/joy/components/autocomplete/CustomTags.js
- docs/data/joy/components/autocomplete/CustomTags.tsx
- docs/data/material/components/autocomplete/Asynchronous.js
- docs/data/material/components/autocomplete/Asynchronous.tsx
- docs/data/material/components/autocomplete/ComboBox.js
- docs/data/material/components/autocomplete/ComboBox.tsx
- docs/data/material/components/autocomplete/ComboBox.tsx.preview
- docs/data/material/components/autocomplete/DisabledOptions.js
- docs/data/material/components/autocomplete/DisabledOptions.tsx
- docs/data/material/components/autocomplete/DisabledOptions.tsx.preview
- docs/data/material/components/autocomplete/Filter.js
- docs/data/material/components/autocomplete/Filter.tsx
- docs/data/material/components/autocomplete/Filter.tsx.preview
- docs/data/material/components/autocomplete/GloballyCustomizedOptions.js
- docs/data/material/components/autocomplete/GloballyCustomizedOptions.tsx
- docs/data/material/components/autocomplete/GoogleMaps.js
- docs/data/material/components/autocomplete/GoogleMaps.tsx
- docs/data/material/components/autocomplete/Grouped.js
- docs/data/material/components/autocomplete/Grouped.tsx
- docs/data/material/components/autocomplete/Grouped.tsx.preview
- docs/data/material/components/autocomplete/Highlights.js
- docs/data/material/components/autocomplete/Highlights.tsx
- docs/data/material/components/autocomplete/RenderGroup.js
- docs/data/material/components/autocomplete/RenderGroup.tsx
- docs/data/material/components/autocomplete/RenderGroup.tsx.preview
- docs/data/material/components/autocomplete/Virtualize.js
- docs/data/material/components/autocomplete/Virtualize.tsx
- docs/data/material/components/autocomplete/Virtualize.tsx.preview
We can't have duplicated id on a page. I noticed this in #42085. Part of the value of solving these errors, the more we have, the harder its to quickly spot regressions
https://validator.w3.org/nu/?doc=https%3A%2F%2Fdeploy-preview-39603--material-ui.netlify.app%2Fmaterial-ui%2Freact-autocomplete%2F
A regression from #34066
After: https://deploy-preview-42086--material-ui.netlify.app/material-ui/react-autocomplete/
> [docs][autocomplete] Fix duplicate autocomplete id

- docs/data/material/design-resources/material-ui-for-figma/material-ui-for-figma.md
Although the link works on the [docs page](https://github.com/mui/material-ui/pull/42142), the links linter started to [fail](https://app.circleci.com/pipelines/github/mui/material-ui/128534/workflows/d58472c0-2995-4dba-9cbd-d6c69340e492/jobs/693026) due to the link missing "https://"
> [docs][material-ui] Fix broken link

- docs/src/components/showcase/ThemeSlider.tsx
It looks like https://github.com/mui/material-ui/pull/41547 introduced a small visual glitch on the home page slider because the slider track ends are not centered within the slider thumbs.
|before|after|
|---|---|
|<img width="362" alt="Screenshot 2024-05-06 at 10 03 19" src="https://github.com/mui/material-ui/assets/7225802/765f02fc-48f6-4fe0-8e50-28be4f2dda57">|<img width="360" alt="Screenshot 2024-05-06 at 10 16 34" src="https://github.com/mui/material-ui/assets/7225802/6fdfffa9-a29b-4a54-8978-398e5845c5a9">|
|<img width="364" alt="Screenshot 2024-05-06 at 10 03 37" src="https://github.com/mui/material-ui/assets/7225802/9e26608c-41d5-4822-9424-dc0f49a7b794">|<img width="360" alt="Screenshot 2024-05-06 at 10 16 24" src="https://github.com/mui/material-ui/assets/7225802/14c2503e-c7bb-441 …
> [website] Fix home page slider's track position

- docs/pages/careers.tsx
- docs/src/components/careers/CareersFaq.tsx
- docs/src/components/careers/PerksBenefits.tsx
- docs/src/components/careers/RoleEntry.tsx
- docs/src/modules/components/TopLayoutCareers.js
- packages/mui-docs/src/translations/translations.json
All of the Careers page sections were defined in the `careers.tsx` component/file. Given that we're somewhat frequently touching this page to add and remove roles, I figured we could simplify it by extracting a few sections to their own dedicated file. Aside from that, I also added small design improvements (e.g., we _can't_ use Unicode for icons as a UI-focused company 😅 we need to be polished).
https://deploy-preview-42102--material-ui.netlify.app/careers
> [website] Componentize a few Careers page sections

- packages/mui-codemod/src/deprecations/divider-props/divider-props.js
- packages/mui-codemod/src/deprecations/divider-props/test-cases/actual.js
- packages/mui-codemod/src/deprecations/divider-props/test-cases/expected.js
- packages/mui-codemod/src/deprecations/divider-props/test-cases/theme.actual.js
- packages/mui-codemod/src/deprecations/divider-props/test-cases/theme.expected.js
Opacity 0.6 was always being applied, but it should apply the opacity only if a `light` prop is present.
> [codemod][Divider] Only apply codemod if light prop is present

- docs/src/components/pricing/PricingTable.tsx
> [website] Fix pricing casing

- docs/notifications.json
Just realized this was still there. Not sure it makes sense to keep linking this blog post there with wording that could communicate that "Base is ready!" when we're in the midst of rewriting the whole thing and a few months away from being fully usable 😬
> [docs] Remove the Base notification

- docs/data/material/guides/composition/composition.md
"destined to the ~leave~ **leaf** element"
> [docs][material-ui] Fix typo in composition docs

- docs/data/material/migration/migrating-from-deprecated-apis/migrating-from-deprecated-apis.md
Wording tweaks in the "Migrating from deprecated APIs" [page](https://next.mui.com/material-ui/migration/migrating-from-deprecated-apis/).
> [material-ui][docs] Improve descriptions for deprecated props

- docs/src/modules/components/Demo.js
- docs/src/modules/components/DemoEditor.tsx
- docs/src/modules/components/DemoToolbar.js
- packages/markdown/parseMarkdown.js
- packages/mui-docs/src/CodeCopy/CodeCopyButton.tsx
- packages/mui-docs/src/MarkdownElement/MarkdownElement.tsx
<details>
<summary>Old description</summary>
This PR is a follow-up to https://github.com/mui/material-ui/pull/41827. What motivated this one is a reflection around multi-tab demos where I initially thought that the demo toolbar's copy button copying the content from both tabs was a valuable thing to support. However, in discussing it with @colmtuite & @zanivan, I realized this is actually a non-intuitive UX. Here's why that is:
1. The PR I linked above introduced somewhat of an inconsistency: if there's a demo toolbar, the copy button will appear on it. If there's not, the copy button is inside the code block. A better approach for managing the user's expectations is for this button to always be in the same place.
2. It seems way more intuitive to have the copy button closer to the …
> [docs-infra] Limit the copy button to the visible code block

- docs/data/material/migration/migrating-from-deprecated-apis/migrating-from-deprecated-apis.md
- docs/pages/material-ui/api/autocomplete.json
- packages/mui-codemod/README.md
- packages/mui-codemod/src/deprecations/autocomplete-props/autocomplete-props.js
- packages/mui-codemod/src/deprecations/autocomplete-props/test-cases/actual.js
- packages/mui-codemod/src/deprecations/autocomplete-props/test-cases/expected.js
- packages/mui-codemod/src/deprecations/autocomplete-props/test-cases/theme.actual.js
- packages/mui-codemod/src/deprecations/autocomplete-props/test-cases/theme.expected.js
- packages/mui-material/src/Autocomplete/Autocomplete.d.ts
- packages/mui-material/src/Autocomplete/Autocomplete.js
> [material-ui][Autocomplete] Deprecate `componentsProps` props

- docs/src/modules/components/ApiPage.js
- docs/src/modules/components/ApiPage/sections/ClassesSection.tsx
- docs/src/modules/components/ApiPage/sections/PropertiesSection.js
- docs/src/modules/components/ApiPage/sections/SlotsSection.tsx
- docs/src/modules/components/ComponentsApiContent.js
- docs/src/modules/components/HooksApiContent.js
- packages/mui-docs/src/SectionTitle/SectionTitle.tsx
- packages/mui-docs/src/SectionTitle/index.tsx
Export a component to render a section title.
Pages are still responsible for the definition of the translation since they have different approaches. But at least the classes and the DOM structure will be shared.
Not sure about the file position. I hesitated to put this component inside a folder containing small UI components, but did not find a name for it
> [docs-infra] Share code for section title

- docs/pages/material-ui/api/toggle-button-group.json
- docs/translations/api-docs/toggle-button-group/toggle-button-group.json
- packages/mui-material/src/ToggleButtonGroup/toggleButtonGroupClasses.ts
> [material-ui][ToggleButtonGroup] Add missing `selected` class in ToggleButtonGroupClasses type

- docs/data/material/migration/migration-v5/migration-v5.md
Added supported browsers section to v6's migration guide
> [docs][material-ui] Add supported browsers section to migration guide

- docs/src/components/pricing/PricingTable.tsx
I'm confused by:
1. Simple tree view and Rich tree view are the same components (not in the React sense but UI sense), so do we need to show them twice? It makes me think that there are two, which is not the case.
2. It feels like the page promise that all tree view features are open-source, but we have https://github.com/mui/mui-x/issues?q=is%3Aopen+is%3Aissue+label%3A%22component%3A+tree+view%22+sort%3Areactions-%2B1-desc+label%3A%22plan%3A+Pro%22.
So I'm going after 1 in this PR.
For point 2. I think https://github.com/mui/material-ui/pull/41595#discussion_r1535365315 makes sense, but I kept this PR more focused.
After: https://deploy-preview-42100--material-ui.netlify.app/pricing/
> [website] Avoid duplicate simple vs. rich

- README.md
I thought about waiting a bit longer to remove it since there's still Base UI code in this repo, but I guess removing confusion progressively is also a good move.
> [docs] Remove Base UI from the README

- docs/data/material/integrations/interoperability/interoperability.md
I found a typo in this section of the docs while investigating an issue.
Preview: https://deploy-preview-42279--material-ui.netlify.app/material-ui/integrations/interoperability/#tailwind-css
> [docs][material-ui] Fix typo in style interoperability with Tailwind CSS docs

- docs/src/modules/components/ComponentPageTabs.js
<details>
<summary>Old description</summary>
After multiple trials and errors + looking around, I realized that something (which I couldn't quite figure out) is preventing the `Link` component from `@mui/docs` from rendering with the `role="tab"` attribute. That's ultimately what's breaking the arrow keys keyboard navigation. My goal with this PR is purely to fix that rather than discuss just yet whether this is a desirable pattern (although I did find [a cool Ariakit example](https://ariakit.org/examples/tab-next-router) using it, which is reassuring!). 
So, just using the `Link` component straight from Next.js seems to nicely fix the issue — try focusing on the first active tab and pressing the right key to navigate; you should expect normal Tabs behavior now.
</details>
**Edit:** The …
> [docs-infra] Fix keyboard navigation on page tabs

- docs/data/material/components/autocomplete/CustomizedHook.js
- docs/data/material/components/autocomplete/CustomizedHook.tsx
- docs/data/material/components/autocomplete/Tags.js
- docs/data/material/components/autocomplete/Tags.tsx
- docs/pages/base-ui/api/use-autocomplete.json
- packages/mui-base/src/useAutocomplete/useAutocomplete.d.ts
- packages/mui-material/src/Autocomplete/Autocomplete.js
Iterate on #39833. There are a lot more issues that I didn't fix. We will need to cherry-pick to `master`.
> [core] Fix a few more key spread issues

- .circleci/config.yml
- package.json
Looks like circleci updated their images with pnpm 9. This seems to break the checkout as the lockfile changes:
* Run `corepack enable` every time
* Prevent installing with the wrong package manager
> [code-infra] Run corepack enable on all CI jobs

- docs/translations/api-docs/use-menu-item-context-stabilizer/use-menu-item-context-stabilizer.json
- docs/translations/api-docs/use-option-context-stabilizer/use-option-context-stabilizer.json
- packages/api-docs-builder/ApiBuilders/ComponentApiBuilder.ts
- packages/api-docs-builder/ApiBuilders/HookApiBuilder.ts
- packages/mui-base/src/useMenuItem/useMenuItemContextStabilizer.ts
- packages/mui-base/src/useOption/useOptionContextStabilizer.ts
- packages/mui-material/src/Hidden/Hidden.d.ts
- packages/mui-material/src/Hidden/Hidden.js
These changes allow JSDoc tags like `@deprecated` to be present in components and hook JSDoc comments without them being displayed in the docs. Before these changes, JSDoc tags would be displayed in the docs.
The benefits to allow JSDoc tags are:
- Consumers get the info right in their IDE e.g. strikethrough styles and info in the popover when using a `@deprecated` API.
- We'll be able to use JSDoc tags like `@deprecated` as the source of truth to display deprecation alerts in API pages. Further context [#42280](https://github.com/mui/material-ui/pull/42280)
- We'll be able to use standard JSDoc syntax for things like links to doc pages.
> [docs-infra] Allow JSDoc tags

- docs/src/modules/sandbox/Dependencies.ts
Avoid creating a `@types/toolpad__...` dependency
> [docs-infra] Add Toolpad to muiNpmOrgs for codesandbox demos

- docs/data/material/components/steppers/VerticalLinearStepper.js
- docs/data/material/components/steppers/VerticalLinearStepper.tsx
There is an example code in the 'Vertical stepper' section of the 'Stepper' menu within the documentation.
And I thought it would be better to fix some minor things.
1. Replaced the static condition `index === 2` with a dynamic condition `index === steps.length`  since people can just copy the example code to their project and edit or add new steps to make their component.
2. Deleted the `div` tag as it seemed unnecessary.
> [material-ui][docs] Add minor modifications to the Vertical stepper demo

- renovate.json
> [core] Remove `WyW-in-JS` from Renovate config

- package.json
- packages-internal/scripts/package.json
- pnpm-lock.yaml
Read [here](https://app.renovatebot.com/package-diff?name=@types%2fprettier&from=2.7.3&to=3.0.0) that prettier provides it's own type definitions in the new version.
Closes #42297
> [core] Remove `@types/prettier` package

- docs/src/layouts/HeroContainer.tsx
Looks like the min-height and padding-top were supposed to be applied at the `md` breakpoint instead of `sm`. 
| --- | --- |
| ![mui com_](https://github.com/mui/material-ui/assets/9557798/c414df45-9b21-4bde-b3ff-bed0aa0feb66) | ![localhost_3000_](https://github.com/mui/material-ui/assets/9557798/61d84527-805e-4578-bec4-b7395f4281cc) |
> [website] Fix hero spacing changes applying at the wrong breakpoint

- docs/data/material/migration/migrating-from-deprecated-apis/migrating-from-deprecated-apis.md
- packages/mui-material/src/ListItem/ListItem.js
- packages/mui-material/src/ListItemSecondaryAction/ListItemSecondaryAction.d.ts
- packages/mui-material/src/ListItemSecondaryAction/ListItemSecondaryAction.js
We intended to deprecate `ListItemSecondaryAction` in v5 in favor of the `secondaryAction` prop in `ListItem`, but we forgot to do it officially so we can't remove it in v6. This PR adds a new `ListItemSecondaryAction` deprecation entry in the docs for v6 so we can remove it in v7. See https://github.com/mui/material-ui/pull/26446 for context.
Preview link: https://deploy-preview-42251--material-ui.netlify.app/material-ui/migration/migrating-from-deprecated-apis/#listitemsecondaryaction
> [material-ui][ListItemSecondaryAction] Deprecate component

- packages/mui-base/src/useAutocomplete/useAutocomplete.test.js
- packages/mui-material/src/Autocomplete/Autocomplete.js
- packages/mui-material/src/Autocomplete/Autocomplete.test.js
Cherry-pick of https://github.com/mui/material-ui/pull/42099
> [core] Fix React 18.3 warnings about spreading keys in the Material UI `Autocomplete` component (#42099)

- docs/data/material/migration/migrating-from-deprecated-apis/migrating-from-deprecated-apis.md
- docs/pages/material-ui/api/list-item.json
- docs/translations/api-docs/list-item/list-item.json
- packages/mui-codemod/README.md
- packages/mui-codemod/src/deprecations/list-item-props/index.js
- packages/mui-codemod/src/deprecations/list-item-props/list-item-props.js
- packages/mui-codemod/src/deprecations/list-item-props/list-item-props.test.js
- packages/mui-codemod/src/deprecations/list-item-props/test-cases/actual.js
- packages/mui-codemod/src/deprecations/list-item-props/test-cases/expected.js
- packages/mui-codemod/src/deprecations/list-item-props/test-cases/theme.actual.js
- packages/mui-codemod/src/deprecations/list-item-props/test-cases/theme.expected.js
- packages/mui-material/src/ListItem/ListItem.d.ts
- packages/mui-material/src/ListItem/ListItem.js
Part of: https://github.com/mui/material-ui/issues/41279
Deprecate ListItem's `components` and `componentsProps` props in favor of `slots` and `slotProps` respectively. Includes the corresponding codemod and documentation updates.
> [material-ui][ListItem] Deprecate ListItem's components and componentsProps

- docs/data/material/migration/migrating-from-deprecated-apis/migrating-from-deprecated-apis.md
- docs/pages/material-ui/api/list-item.json
- packages/mui-material/src/ListItem/ListItem.d.ts
- packages/mui-material/src/ListItem/ListItem.js
`ListItem`'s `ContainerComponent` and `ContainerProps` props [were deprecated 3 years ago](https://github.com/mui/material-ui/pull/26446/files#diff-5698698594d052380d3b810071d671941c607258ee79027c74ed2844f127f3b6R33-R39), but not officially in the docs. This PR just makes the deprecation official adding it to the docs.
This deprecation goes hand in hand with `ListItemSecondaryAction` deprecation, so we should probably wait for https://github.com/mui/material-ui/pull/42251 to be merged first.
Preview link: https://deploy-preview-42263--material-ui.netlify.app/material-ui/migration/migrating-from-deprecated-apis/#listitem
> [material-ui][ListItem] Document `*Component` and `*Props` props deprecations

- packages/mui-material/src/Slider/Slider.js
Fixes https://github.com/mui/material-ui/issues/41753
[Codesandbox](https://codesandbox.io/p/sandbox/little-fire-zvtlhg?file=%2Fsrc%2FDemo.tsx%3A23%2C14) with the fix
> [material-ui][Slider] Fix wrong CSS value

- packages/markdown/prepareMarkdown.js
I just added automatic generation of API docs pages for the Toolpad Core components in https://github.com/mui/mui-toolpad/pull/3536.
I adapted the scripts that most of the MUI libraries are using for that, but the API links are broken. 
I guess we need to add this change to the `markdown` package to fix it?
> [docs-infra] Fix Toolpad Core API links

- packages/mui-utils/src/deepmerge/deepmerge.test.ts
- packages/mui-utils/src/deepmerge/deepmerge.ts
Added more checks for prototype pollution in `deepmerge` to abide by [GitHub's vulnerability report in another repo using MUI](https://github.com/paranext/paranext-core/security/code-scanning/41).
It was hard to figure out which library was contributing the code the reported vulnerability is in, but [this line](https://github.com/paranext/paranext-core/blob/ea96b20540f65c22e2ec32dec85e47ef599d001b/lib/platform-bible-react/dist/index.js#L1018) helped me to find `isPlainObject` exported from the same module which then led me to find `deepmerge`.
Thanks for all the hard work!
> [utils] Fix GitHub-reported prototype pollution vulnerability in `deepmerge`

- .stylelintrc.js
When running `pnpm stylelint` locally with Next.js having already done a build, it will crash with:
Annoying.
Instead, I'm reproducing the fix done in Base UI by @michaldudak https://github.com/mui/base-ui/blob/bf8fca5f2aac3d6d39d41496a20d722d67cc1fba/.stylelintrc.js#L7. 
I found this testing some stuff with Pigment CSS.
> [code-infra] Fix stylelint locally

- packages/mui-material/src/styles/responsiveFontSizes.js
- packages/mui-material/src/styles/responsiveFontSizes.test.js
We [ask](https://mui.com/material-ui/customization/typography/#adding-amp-disabling-variants) users to disable typography variants by setting them to undefined but this was not handled in the runtime code of `responsiveFontSizes`.
This change fixes that.
Fixes #42252
> [material-ui][responsiveFontSizes] Handled undefined variants

- docs/src/modules/components/ApiPage/sections/ToggleDisplayOption.tsx
- docs/src/modules/components/AppNavDrawer.js
- packages/mui-docs/src/branding/brandingTheme.ts
Run-down of the changes:
- If there's a check icon to illustrate which item is currently active, put the icons on the far right (the API page layout menu was inconsistent with the version menu in this regard)
- Tweak spacing between menu items so they don't collide (try hovering the menu item right below a selected one)
- Fix secondary button styles so that light (lightest inset box-shadow) comes from the top
- Make the Divider component color consistent in the branding theme
> [docs-infra] Make menu styles consistent

- CONTRIBUTING.md
Adds a link to the pnpm [installation guide](https://pnpm.io/installation) in CONTRIBUTING.md
Sparked from https://github.com/mui/material-ui/issues/42388
> [docs] Link to pnpm installation docs

- docs/data/joy/getting-started/templates/messages/components/ChatsPane.tsx
- docs/data/joy/getting-started/templates/messages/components/Header.tsx
- docs/data/joy/getting-started/templates/messages/components/MessagesPane.tsx
- docs/data/joy/getting-started/templates/messages/components/MyMessages.tsx
In the message template. Between screen widths 1200 and 600, there is a (black bar) below the MessagesPane and ChatsPane components, caused by the lack of configuration of the height break points, related to the header component. I corrected it, adding the correct height break points in the necessary components for better responsiveness.
> [joy-ui][docs] Fix template responsiveness

- docs/src/modules/components/AppLayoutDocsFooter.js
- docs/src/modules/utils/getProductInfoFromUrl.ts
- netlify/functions/feedback-management.mts
Fix https://github.com/mui/mui-public/issues/168
@mui/docs-infra Tested on `docs-feedback-material-ui` and `docs-feedback-base-ui`. Will need to be merge to test for X channels
> [docs-infra] Split feedback channels per product

- CHANGELOG.md
- package.json
- packages/mui-core-downloads-tracker/package.json
- packages/mui-docs/package.json
- packages/mui-icons-material/package.json
- packages/mui-material/package.json
- packages/mui-styles/package.json
> [release] v5.15.19

- packages/mui-system/src/Container/createContainer.tsx
MUI System portion of https://github.com/mui/material-ui/issues/14420
Remove the remaining IE11-related code from the MUI System package. There was only one.
> [mui-system] Remove IE11 code

- docs/data/system/getting-started/the-sx-prop/DynamicValues.js
- docs/data/system/getting-started/the-sx-prop/DynamicValues.tsx
- docs/data/system/getting-started/the-sx-prop/the-sx-prop.md
Resolves https://github.com/mui/material-ui/issues/42164
Adds a new "Dynamic values" section in the `sx` prop [docs page](https://mui.com/system/getting-started/the-sx-prop/) with guidance on how to leverage CSS variables to handle highly dynamic values to avoid polluting the DOM with unnecessary `style` tags.
_This PR will be cherry-picked to master._
Preview link: https://deploy-preview-42239--material-ui.netlify.app/system/getting-started/the-sx-prop/#dynamic-values
> [system][docs] Add "dynamic values" section to sx prop page

- docs/public/_redirects
Final item to fully deprecate the Notion docs (https://github.com/mui/mui-design-kits/issues/335).
> [material-ui][docs] Update Figma design kit doc redirect link

- docs/pages/material-ui/api/filled-input.json
- docs/translations/api-docs/filled-input/filled-input.json
- packages/mui-material/src/FilledInput/FilledInput.js
- packages/mui-material/src/FilledInput/FilledInput.test.js
- packages/mui-material/src/FilledInput/filledInputClasses.ts
[Documentation says](https://mui.com/material-ui/api/filled-input/#classes) following classes are applied when necessary conditions are met but actually none of the classes are applied. I've written test case to validate same [here](https://github.com/mui/material-ui/pull/42082/files#diff-0c29a4032ec827ace42291c4c833c034250496dce6d3ea013bdc484918be4d33)
1.  .MuiFilledInput-sizeSmall
2.   .MuiFilledInput-multiline
3.   .MuiFilledInput-adornedEnd
4.   .MuiFilledInput-adornedStart
5.   .MuiFilledInput-inputSizeSmall
6.   .MuiFilledInput-inputMultiline
7.   .MuiFilledInput-inputAdornedStart
8.   .MuiFilledInput-inputAdornedEnd
9.   .MuiFilledInput-inputTypeSearch
we can do either of the following
1. to remove above classes from filledInputClasses interface and from docs. that's what this PR …
> [material-ui][FilledInput] Remove unapplied classes from filledInputClasses interface and add missing classes to root

- docs/pages/experiments/website/branding-theme-test.tsx
- docs/src/modules/components/AppLayoutDocsFooter.js
- docs/src/modules/components/AppNavDrawerItem.js
- docs/src/modules/components/AppSettingsDrawer.js
- docs/src/modules/components/AppTableOfContents.js
- docs/src/modules/components/DiamondSponsors.js
- docs/src/modules/components/EditPage.js
- packages/mui-docs/src/MarkdownElement/MarkdownElement.tsx
- packages/mui-docs/src/branding/brandingTheme.ts
Some simple stuff on this PR — here's a run-down:
- Actually, maybe the most significant change of this PR is removing the logo and extra links from the docs footer. I had added that many months ago, but ultimately, I feel like they just clutter the docs without a great reason. Way cleaner without them!
- Swapping some semi-bold font-weight instances to medium to lighten things up a bit
- A bunch of color improvements, mostly on the icon button (improving shadows, border, and hover state styles)
Preview: https://deploy-preview-42455--material-ui.netlify.app/material-ui/migration/migration-v5/
> [docs-infra] Add small design polish

- packages/mui-material/src/styles/createTransitions.js
- packages/mui-material/src/styles/createTransitions.test.js
Based on https://x.com/aoeheals/status/1791855247846944772
> [Collapse] Bound max transition time

- packages/mui-material/src/useMediaQuery/useMediaQueryTheme.d.ts
- packages/mui-material/src/useMediaQuery/useMediaQueryTheme.js
Removes `useMediaQueryTheme` since it's not exported and is unused in the codebase. It was meant to be removed in v5.
> [material-ui][useMediaQuery] Remove unused useMediaQueryTheme

- docs/data/material/migration/migrating-from-deprecated-apis/migrating-from-deprecated-apis.md
- docs/pages/material-ui/api/backdrop.json
- docs/translations/api-docs/backdrop/backdrop.json
- packages/mui-codemod/README.md
- packages/mui-codemod/src/deprecations/backdrop-props/backdrop-props.js
- packages/mui-codemod/src/deprecations/backdrop-props/backdrop-props.test.js
- packages/mui-codemod/src/deprecations/backdrop-props/test-cases/actual.js
- packages/mui-codemod/src/deprecations/backdrop-props/test-cases/expected.js
- packages/mui-codemod/src/deprecations/backdrop-props/test-cases/theme.actual.js
- packages/mui-codemod/src/deprecations/backdrop-props/test-cases/theme.expected.js
- packages/mui-material/src/Backdrop/Backdrop.d.ts
- packages/mui-material/src/Backdrop/Backdrop.js
Part of https://github.com/mui/material-ui/issues/41279
Closes https://github.com/mui/material-ui/pull/42026
Deprecate `components` and `componentsProps` in the Backdrop component
> [material-ui][Backdrop] Deprecate `components` and `componentsProps`

- docs/data/material/migration/migrating-from-deprecated-apis/migrating-from-deprecated-apis.md
- docs/pages/material-ui/api/modal.json
- docs/translations/api-docs/modal/modal.json
- packages/mui-codemod/README.md
- packages/mui-codemod/src/deprecations/all/deprecations-all.js
- packages/mui-codemod/src/deprecations/modal-props/index.js
- packages/mui-codemod/src/deprecations/modal-props/modal-props.js
- packages/mui-codemod/src/deprecations/modal-props/modal-props.test.js
- packages/mui-codemod/src/deprecations/modal-props/test-cases/actual.js
- packages/mui-codemod/src/deprecations/modal-props/test-cases/expected.js
- packages/mui-codemod/src/deprecations/modal-props/test-cases/theme.actual.js
- packages/mui-codemod/src/deprecations/modal-props/test-cases/theme.expected.js
- packages/mui-material/src/Modal/Modal.d.ts
- packages/mui-material/src/Modal/Modal.js
Part of https://github.com/mui/material-ui/issues/41279
Deprecate `components` and `componentsProps` in the Modal component
> [material-ui][Modal] Deprecate `components` and `componentsProps`

- README.md
- docs/src/components/home/DiamondSponsors.tsx
- docs/src/modules/components/DiamondSponsors.js
This PR will update the description and link of DoiT in the diamond sponsor section
> [website] Update DoiT description and link in Sponsors section

- docs/data/joy/components/radio-button/radio-button.md
The tag was rendering as an actual radio button ([here](https://mui.com/joy-ui/react-radio-button/#basics))
(Resubmission of #42524 due to wrong branch/conflicts. I got a little confused by the branches, sorry)
> [joy-ui][docs] Fix HTML tag without preformatting

- package.json
The npm scripts responsible for starting tests do not include code within /packages-internal. This PR adds this directory and enables running unit tests for it.
> [test] Restore testing internal packages

- pnpm-lock.yaml
- test/package.json
- test/regressions/index.js
Should prevent that type of false positiv
I also noticed we do screenshot of the dashboard and each component individually. Which seems like waisting resources. So I only kept the dashboard screenshot and  remove all the subcomponents
> [core] Skip charts animation for visual regression test

- packages/mui-codemod/src/v6.0.0/sx-prop/sx-v6.js
- packages/mui-codemod/src/v6.0.0/sx-prop/sx-v6.test.js
- packages/mui-codemod/src/v6.0.0/sx-prop/test-cases/sx-line-break.actual.js
- packages/mui-codemod/src/v6.0.0/sx-prop/test-cases/sx-line-break.expected.js
- packages/mui-codemod/src/v6.0.0/sx-prop/test-cases/sx-value-callback.actual.js
- packages/mui-codemod/src/v6.0.0/sx-prop/test-cases/sx-value-callback.expected.js
Please review the test cases. Found the bugs from #42475.
**Summary of the fix is the support of**:
- Do remove line break that's not related to sx
- Hoist theme value callback to the top
```diff
sx={
- { color: theme => theme.palette.divider }  
+ theme => ({
+    color: theme.palette.divider,
+ })
}
```
---
> [codemod] Support more cases for sx-prop transformation

- packages/mui-material/src/useMediaQuery/useMediaQuery.test.js
- packages/mui-system/src/useMediaQuery/useMediaQuery.ts
Part of https://github.com/mui/material-ui/issues/42459
This PR stops using deprecated browser APIs:
- https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList/addListener
- https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList/removeListener
These were needed to support Safari 13 but we no longer support it so it's fine to use the recommended browser APIs.
> [system][useMediaQuery] Drop Safari < 14 support

- packages/mui-material/src/Chip/Chip.d.ts
- packages/mui-material/src/GlobalStyles/GlobalStyles.d.ts
- packages/mui-material/src/Modal/Modal.d.ts
- packages/mui-material/src/Slider/Slider.d.ts
- packages/mui-material/src/StepConnector/StepConnector.d.ts
- packages/mui-material/src/Tab/Tab.d.ts
part of https://github.com/mui/material-ui/issues/42380
since there was no activity in the issue, i went ahead and changed instances of `React.ReactElement<any>` to `React.ReactElement<unknown>`, There still 15+ instances of `React.ReactElement<any,any>` to be changed. i'll leave that up to other contributors
> [material-ui] Change React.ReactElement type from `any` to `unknown`

- packages/mui-material/src/Typography/Typography.js
- packages/mui-material/src/zero-styled/index.ts
closes #42261
This PR makes the `extendSxProp` replaceable by Pigment CSS. The [`extendSxProp`](https://github.com/mui/pigment-css/pull/112/files) from Pigment CSS is just a placeholder to remove the connection between Material UI and MUI System, thus reducing bundle size of the application.
> [material-ui][pigment-css] Integrate `extendSxProp` adapter

- .eslintrc.js
- package.json
- pnpm-lock.yaml
Part of https://github.com/mui/material-ui/issues/42548
Installing and configuring [eslint-plugin-react-compiler](https://react.dev/learn/react-compiler#installing-eslint-plugin-react-compiler). This will help use write code that follows the rules of React so:
- Our components and hooks can be optimized if we enable the React Compiler in the future.
- We distribute compliant React code in our demos.
For now, the plugin is disabled by default and needs to be enabled locally by setting `ENABLE_REACT_COMPILER_PLUGIN` to `true` in the root `.eslintrc.js`. Once the plugin is stable and we've fixed all reported issues (98 at the time of writing), we can consider enabling it by default.
> [core] Configure eslint-plugin-react-compiler

- docs/data/material/components/use-media-query/use-media-query.md
It's kinda redundant to see "Material UI" in the heading when we're in the Material UI docs.
Preview link: https://deploy-preview-42561--material-ui.netlify.app/material-ui/react-use-media-query/
|before|after|
|---|---|
|<img width="216" alt="Screenshot 2024-06-07 at 13 02 24" src="https://github.com/mui/material-ui/assets/7225802/8189fdc8-8dab-4463-a6e4-908c987cefb0">|<img width="196" alt="Screenshot 2024-06-07 at 13 02 34" src="https://github.com/mui/material-ui/assets/7225802/4477faa6-e560-4dad-9bd5-567af628f8ad">|
> [material-ui][docs] Shorten useMediaQuery subheading

- docs/data/material/components/steppers/HorizontalNonLinearStepper.js
- docs/data/material/components/steppers/HorizontalNonLinearStepper.tsx
Part of https://github.com/mui/material-ui/issues/42548
Fixing an error reported by `eslint-plugin-react-compiler` in a Stepper [demo](https://mui.com/material-ui/react-stepper/#non-linear):
```
/material-ui/docs/data/material/components/steppers/HorizontalNonLinearStepper.js
51:5  error  This mutates a variable that React considers immutable  react-compiler/react-compiler
/material-ui/docs/data/material/components/steppers/HorizontalNonLinearStepper.tsx
53:5  error  This mutates a variable that React considers immutable  react-compiler/react-compiler
```
- ESLint shouldn't report the error anymore (you need to set `ENABLE_REACT_COMPILER_PLUGIN` to `true` in `.eslintrc.js` locally)
- The demo should work as expected:
- Original: https://mui.com/material-ui/react-stepper/#non-linear
- PR: …
> [material-ui][docs] Fix ESLint error in Stepper demo

- .eslintrc.js
Part of https://github.com/mui/material-ui/issues/42548
Disabling the `eslint-plugin-react-compiler` rules in the `mui-base` folder because we don't want to invest time in fixing issues relative to Base UI because Base UI is moving to https://github.com/mui/base-ui in the future.
> [core] Disable eslint-plugin-react-compiler for Base

- packages/mui-material/src/Grid/Grid.js
- packages/mui-system/src/spacing/spacing.test.js
The Grid is broken when using CSS variables, the regression was introduced in #40224 (visible on the description of the PR).
https://next--material-ui.netlify.app/core/
https://deploy-preview-42574--material-ui.netlify.app/core/
Now, I imagine that during v6 lifecycle we will deprecate https://mui.com/material-ui/react-grid/ for https://mui.com/material-ui/react-grid2/. But first, we will need to migrate all our marketing pages to use the new grid. And even once we do, the deprecated version should continue to work with CSS variables so developers can migrate to it.
> [Grid] Fix support for CSS variables

- docs/data/material/components/grid2/grid2.md
The problem https://next--material-ui.netlify.app/material-ui/react-grid2/
---
I couldn't find any other page broken like this:
> [docs][Grid] Fix docs spacing

- docs/pages/_app.js
- docs/pages/_document.js
- docs/src/modules/components/Ad.js
- docs/src/modules/components/GoogleAnalytics.js
- docs/src/pages/components/material-icons/SearchIcons.js
Rollout #36123 to https://v4.mui.com/. For context: https://docs.google.com/presentation/d/1-nxGF1N_WepPmIZEu7Og7tQ1V6T5xPwiC-MBai0pvpM/edit?disco=AAABPstWhaA.
I'm curious to see how GA4 will handle these subdomains, we will need to make it work for https://www.notion.so/mui-org/docs-infra-Change-docs-domain-0ce329e7ebc34aba8fbf4f3c5e13eb5d. Apparently, it's messy. Another case where Google Universal was better than GA4: https://www.analyticsmania.com/post/subdomain-tracking-with-google-analytics-and-google-tag-manager/#full-urls
P.S. The CI is red, it's expected, it can't run anymore, the dependencies are gone.
> [docs] Migrate to GA4

- packages/mui-docs/src/MarkdownElement/MarkdownElement.tsx
A follow-up on #41994, trying to polish the edges.
Preview: https://deploy-preview-42593--material-ui.netlify.app/material-ui/getting-started/
> [docs-infra] Simplify click header

- docs/data/material/getting-started/templates/dashboard/components/MainGrid.js
- docs/data/material/getting-started/templates/dashboard/components/MainGrid.tsx
> [docs] Fix dashboard template console error

- docs/data/material/getting-started/templates/sign-in/SignIn.js
- docs/data/material/getting-started/templates/sign-in/SignIn.tsx
- docs/data/material/getting-started/templates/sign-up/SignUp.js
- docs/data/material/getting-started/templates/sign-up/SignUp.tsx
Fix typo (`padingBottom` to `paddingBottom`) on the sign-in and sign-up templates according to [this comment](https://github.com/mui/material-ui/pull/41845#discussion_r1633519740)
> [material-ui][docs] Fix typo on Sign-in/Sign-up templates

- .eslintrc.js
- docs/data/joy/customization/theme-colors/PaletteThemeViewer.js
- docs/data/joy/customization/theme-colors/PaletteThemeViewer.tsx
- package.json
- packages/api-docs-builder/utils/parseTest.ts
- packages/mui-base/scripts/testModuleAugmentation.js
- packages/mui-codemod/codemod.js
- packages/mui-joy/scripts/testModuleAugmentation.js
- packages/mui-material/scripts/testModuleAugmentation.js
- packages/mui-material/src/styles/createTheme.js
- packages/mui-styles/src/getThemeProps/getThemeProps.js
- packages/mui-system/scripts/testModuleAugmentation.js
- pnpm-lock.yaml
Removed the `eslint-config-airbnb-base` package. It is meant to be used in non-React apps.
The primary reason for its removal is to allow using iterators and the `for..of` loops, as the browser support is good (the spec is a part of ES2015).
Removal of this package also removes 3 additional no-restricted-syntax rules:
```js
{
selector: 'ForInStatement',
message: 'for..in loops iterate over the entire prototype chain, which is virtually never what you want. Use Object.{keys,values,entries}, and iterate over the resulting array.',
},
{
selector: 'LabeledStatement',
message: 'Labels are a form of GOTO; using them makes code confusing and hard to maintain and understand.',
},
{
selector: 'WithStatement',
message: '`with` is disallowed in strict mode because it makes code impossible to predict …
```
> [core] Allow `for..of` loops

- packages/mui-codemod/src/util/migrateToVariants.js
- packages/mui-codemod/src/v6.0.0/styled/test-cases/LogicalStyled.actual.js
- packages/mui-codemod/src/v6.0.0/styled/test-cases/LogicalStyled.expected.js
- packages/mui-codemod/src/v6.0.0/sx-prop/sx-v6.js
- packages/mui-codemod/src/v6.0.0/sx-prop/test-cases/sx-css-vars.actual.js
- packages/mui-codemod/src/v6.0.0/sx-prop/test-cases/sx-css-vars.expected.js
- packages/mui-codemod/src/v6.0.0/sx-prop/test-cases/sx-dynamic.actual.js
- packages/mui-codemod/src/v6.0.0/sx-prop/test-cases/sx-dynamic.expected.js
Please review the test cases
- Fix generated undefined CSS variable name https://github.com/mui/material-ui/pull/42498#discussion_r1628524256
- Fix spread with logical expression within object expression https://github.com/mui/material-ui/pull/42498#discussion_r1628524519
- Fix assignment pattern variable https://github.com/mui/material-ui/pull/42498#discussion_r1628525170
---
> [codemod] Improve styled and sx prop transformation

- packages/mui-utils/src/deepmerge/deepmerge.test.ts
- packages/mui-utils/src/deepmerge/deepmerge.ts
Closes https://github.com/mui/material-ui/issues/42607
Cherry-pick https://github.com/mui/material-ui/pull/41652 to master
> [cherry-pick][utils] Fix GitHub-reported prototype pollution vulnerability in `deepmerge` (#41652)

- packages/mui-private-theming/src/ThemeProvider/ThemeProvider.js
- packages/mui-private-theming/src/useTheme/useTheme.js
Part of https://github.com/mui/material-ui/issues/42564
> [material-ui][private-theming] Fix issues reported by react compiler in `mui-private-theming` components

- docs/pages/experiments/website/branding-theme-test.tsx
- packages/mui-docs/src/Link/Link.tsx
- packages/mui-docs/src/branding/brandingTheme.ts
I'm not sure why the docs-infra LInk component had the "Link don't have roles" rule, which seems like an incorrect thing according to the `<a>` tag specs ([see MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#technical_summary)). 
A use case for a custom `role` in links is when you have a menu, and you want each menu item rendered as an `a` tag instead of `button`. Still, you'd need to use the correct role assignment—and thus `role="menuitem"` should be there—regardless of the tag. That's exactly what I was trying to do in https://github.com/mui/material-ui/pull/42603 and couldn't with the docs-infra Link component.
Let me know if there's anything to do aside from just removing the prop there!
Preview: https://deploy-preview-42629--material-ui.netlify.app/experiments/websit …
> [docs-infra] Allow Link component to receive the `role` attribute

- docs/src/modules/components/DemoEditor.tsx
- docs/src/modules/components/ThemeViewer.tsx
- packages/markdown/parseMarkdown.js
- packages/mui-docs/src/MarkdownElement/MarkdownElement.tsx
Mosty refining the callout elements and some other details:
- Making the icon align better with the first line, given now the icon is inside a container that has the same height as the text's line height
- In consequence of the above, rounded up the markdown's text line height to 26px
- Desaturate the code block background color a bit (out of taste—it was feeling too blue)
- Fixed some CSS that wasn't being applied, as the the combinator was wrong
Before: https://deploy-preview-42623--material-ui.netlify.app/experiments/docs/callouts/
Preview: https://deploy-preview-42643--material-ui.netlify.app/experiments/docs/callouts
> [docs-infra] Fine tune markdown elements design

- docs/data/joy/customization/right-to-left/right-to-left.md
- docs/data/material/customization/right-to-left/right-to-left.md
Update docs on how to set `dir="rtl"`. Recommend using an HTML attribute instead of using a DOM property. This seems more correct per https://jakearchibald.com/2024/attributes-vs-properties.
Suggested by @oliviertassinari in https://github.com/mui/material-ui/pull/42566#discussion_r1631604244.
> [docs] Recommend setting HTML attribute instead of DOM property for RTL

- docs/data/material/components/buttons/LoadingButtonsTransition.js
- docs/data/material/components/buttons/LoadingButtonsTransition.tsx
- docs/data/material/components/buttons/buttons.md
- docs/data/material/migration/migrating-from-deprecated-apis/migrating-from-deprecated-apis.md
- docs/data/material/migration/migration-v5/migration-v5.md
- packages/mui-lab/src/LoadingButton/LoadingButton.js
Hey folks 👋 
I ran into this issue where some of our customers on our site were trapped by this react crashing loading button. I wanted to to invest some time to get it out of the package.
Using the LoadingButton while have Google translation (chrome feature) active on your site. 
Problem: Google modifies the button contents and React can't figure out its bindings anymore. Causes crash 💥
https://codesandbox.io/s/dry-water-eig2e7?file=/demo.tsx
**Steps:**
- Open sandbox in external browser
- Use google chrome's translate feature (see screenshot)
- Click the loading button 
- Notice crash 💥
I've implemented one of the suggestion in the issue, tested it locally and it seemed to work out perfectly.
😃 This is my first contribution to MUI, so if I need to change something, let me know.
Closes …
> [lab][LoadingButton] Apply wrapping element to prevent React crash on Google page translation

- docs/data/material/migration/migrating-from-deprecated-apis/migrating-from-deprecated-apis.md
- docs/data/material/migration/migration-v5/migration-v5.md
- packages/mui-system/src/useMediaQuery/useMediaQuery.ts
The types being removed were deprecated 3 years ago: https://github.com/mui/material-ui/pull/28413. It's a good opportunity to get rid of them for v6.
> [system][useMediaQuery] Remove deprecated types

- docs/src/modules/components/DemoToolbarRoot.ts
A regression from https://github.com/mui/material-ui/pull/42498
I think this case was my manual adjustment mistake. I missed the `theme.breakpoints.up`. The codemod improvement will come in a separate PR.
| <img width="832" alt="Screenshot 2024-06-18 at 08 43 48" src="https://github.com/mui/material-ui/assets/67129314/5cd44cbc-1848-4d1a-8344-27e576504581"> | <img width="832" alt="Screenshot 2024-06-18 at 08 43 41" src="https://github.com/mui/material-ui/assets/67129314/26a6bdcc-a9b0-4bf2-8af1-8156ff32d8e9"> |
> [docs-infra] Fix wrong migration

- packages/mui-codemod/src/deprecations/tab-classes/test-cases/actual.css
A failing test was introduced in https://github.com/mui/material-ui/pull/42647#issuecomment-2178551391 because we had a temporary bug that caused most unit test to not run in CI.
> [material-ui][Tab] Fix failing test

- docs/data/material/components/autocomplete/FixedTags.js
- docs/data/material/components/autocomplete/FixedTags.tsx
- docs/data/material/components/autocomplete/Sizes.js
- docs/data/material/components/autocomplete/Sizes.tsx
Part of https://github.com/mui/material-ui/issues/39833
Fixes some React warnings in Material UI Autocomplete demos when using React 18.3 or higher. React started to warn against spreading `key` props.
> [material-ui][Autocomplete] Fix React 18.3 key spread warnings in Autocomplete demos

- packages/mui-codemod/src/util/migrateToVariants.js
- packages/mui-codemod/src/v6.0.0/styled/styled-v6.test.js
- packages/mui-codemod/src/v6.0.0/styled/test-cases/ConditionalStyled.expected.js
- packages/mui-codemod/src/v6.0.0/styled/test-cases/DynamicPropsStyled.actual.js
- packages/mui-codemod/src/v6.0.0/styled/test-cases/DynamicPropsStyled.expected.js
- packages/mui-codemod/src/v6.0.0/styled/test-cases/NestedSpread.expected.js
An improvement to cover https://github.com/mui/material-ui/pull/42675
- dynamic props specified in the callback object (works with nested style)
```js
// before
const DemoToolbarRoot = styled('div', {
shouldForwardProp: (prop) => prop !== 'demoOptions' && prop !== 'openDemoSource',
})(({ theme, demoOptions, openDemoSource }) => [
{
[theme.breakpoints.up('sm')]: {
marginTop: demoOptions.bg === 'inline' ? theme.spacing(1) : -1,
// after
const DemoToolbarRoot = styled('div', {
shouldForwardProp: (prop) => prop !== 'demoOptions' && prop !== 'openDemoSource',
})(({ theme }) => [
{
[theme.breakpoints.up('sm')]: {
marginTop: -1,
},
variants: [
{
props: ({ demoOptions }) => demoOptions.bg === 'inline',
style: { marginTop: theme.spacing(1) }
},
]
```
- reduce the number of generated variants
```js …
```
> [codemod] Support dynamic props styled transformation

- docs/data/material/migration/migration-v5/migration-v5.md
- packages/mui-codemod/README.md
I have noticed those reading https://github.com/mui/material-ui/blob/next/packages/mui-codemod/README.md and https://next--material-ui.netlify.app/material-ui/migration/migration-v5/.
> [docs] Fix git diff format in migration to v6

- docs/src/modules/components/Ad.js
- docs/src/modules/components/AdDisplay.js
- packages/mui-docs/src/MarkdownElement/MarkdownElement.tsx
Fix regression introduced in #39603 and #42498.
#39603 introduced the broken anchor blue color
#42498 introduced the broken style rendering logic
Preview https://deploy-preview-42735--material-ui.netlify.app/material-ui/getting-started/
> [docs-infra] Fix visual look of in-house ad

- docs/src/modules/components/Demo.js
- docs/src/modules/components/DemoToolbar.js
- docs/src/modules/components/DemoToolbarRoot.ts
A small regression coming from #41948.
https://pagespeed.web.dev/analysis/https-next-mui-com-material-ui-getting-started-usage/slg9l5xc3c?form_factor=desktop
https://github.com/mui/material-ui/assets/3165635/758ffdfb-81fb-4801-b3e6-74052e7e7a05
The 2px layout shift is gone.
https://deploy-preview-42743--material-ui.netlify.app/material-ui/getting-started/usage/
> [docs-infra] Fix layout shift demo toolbar

- packages/mui-base/src/useAutocomplete/useAutocomplete.test.js
Fixes a React 18.3 warning in a `useAutocomplete` test:
```
A props object containing a "key" prop is being spread into JSX
```
> [base-ui] Fix React spread key warning in test

- packages/mui-styles/src/withStyles/withStyles.test.js
React 18.3.0 started to Warn for deprecated `defaultProps` for function components. See https://github.com/facebook/react/blob/main/CHANGELOG.md#1830-april-25-2024. Since `withStyles` reads `defaultProps` from components, there's a couple of React component using `defaultProps` in tests that fail because of the React warnings.
This PR updates the tests to expect such React warning when running the tests with React 18.3.x
Tests should pass in CI because we still use React 18.2 by default. I tried running CI with React 18.3 but it [failed](https://app.circleci.com/pipelines/github/mui/material-ui/132334/workflows/2d42af42-00d2-4cee-af45-c623602d358d/jobs/713668).
To test it locally, you should update React to 18.3.1 and run the related tests (`pnpm tc "withStyles"`) to verify everything …
> [styles][withStyles] Expect React defaultProps warning in test

- docs/data/material/components/autocomplete/CheckboxesTags.js
- docs/data/material/components/autocomplete/CheckboxesTags.tsx
- docs/data/material/components/autocomplete/CountrySelect.js
- docs/data/material/components/autocomplete/CountrySelect.tsx
- docs/data/material/components/autocomplete/FreeSoloCreateOption.js
- docs/data/material/components/autocomplete/FreeSoloCreateOption.tsx
- docs/data/material/components/autocomplete/FreeSoloCreateOptionDialog.js
- docs/data/material/components/autocomplete/FreeSoloCreateOptionDialog.tsx
- docs/data/material/components/autocomplete/GitHubLabel.js
- docs/data/material/components/autocomplete/GitHubLabel.tsx
- docs/data/material/components/autocomplete/GloballyCustomizedOptions.js
- docs/data/material/components/autocomplete/GloballyCustomizedOptions.tsx
- docs/data/material/components/autocomplete/GoogleMaps.js
- docs/data/material/components/autocomplete/GoogleMaps.tsx
- docs/data/material/components/autocomplete/Highlights.js
- docs/data/material/components/autocomplete/Highlights.tsx
- docs/data/material/components/autocomplete/UseAutocomplete.js
- docs/data/material/components/autocomplete/UseAutocomplete.tsx
- docs/data/material/components/autocomplete/UseAutocomplete.tsx.preview
- docs/data/material/components/autocomplete/Virtualize.js
- docs/data/material/components/autocomplete/Virtualize.tsx
Note: the PR has expanded to solve all errors in all Autocomplete demos, not only the Google Maps demo as the original PR description explained. 
---
When using the demo code for autocomplete with Google Maps, there is an error thrown which seems to be discussed in other issues with respect to other broken examples, but I don't see a solution in place yet.
This addresses the Google Maps example only.  There are probably other examples that should be updated too, but getting this merged seems like a positive step forward even if there are other positive steps forward that can follow.  
Examples of issues closed as incomplete without a solution that seem to be reporting a similar error, especially with NextJS and React 18.3+:
- https://github.com/mui/material-ui/issues/41486 
- …
> [material-ui][Autocomplete] Fix more React 18.3 key spread warnings in demos

- docs/data/material/components/table/ReactVirtualizedTable.js
- docs/data/material/components/table/ReactVirtualizedTable.tsx
Fixes a TypeScript error in the virtualized table demo. The error happened when trying `@types/react@18.3.3`.
https://app.circleci.com/pipelines/github/mui/material-ui/132266/workflows/3b0dfe5d-9138-4ccc-ba2d-7f55f0542eb9/jobs/713336?invite=true#step-108-176
> [material-ui][docs] Fix type error in virtualized table demo

- packages-internal/test-utils/src/createRenderer.tsx
- packages-internal/test-utils/src/flushMicrotasks.ts
- packages-internal/test-utils/tsconfig.json
- packages/mui-base/src/Select/Select.test.tsx
- Fixed the `flushMicrotasks` function as per https://floating-ui.com/docs/react#testing
- Exported types required to customize the createRenderer function in other repos
> [test-utils] Fix flushMicrotasks, export types

- packages/mui-joy/src/Autocomplete/Autocomplete.test.tsx
Fixes a React warning caused by `key` being spread. This only happens starting with React 18.3
> [joy-ui][Autocomplete] Fix spread key error in test

- packages/mui-material/src/Dialog/Dialog.js
In https://github.com/mui/material-ui/pull/42283, a `textAlign` style was incorrectly removed: https://github.com/mui/material-ui/pull/42283/files#r1610471431. This PR implements the correct style.
Before: https://next.mui.com/material-ui/react-dialog/#scrolling-long-content
After: https://deploy-preview-42778--material-ui.netlify.app/material-ui/react-dialog/#scrolling-long-content
> [material-ui][Dialog] Revert incorrect textAlign style removal

- docs/translations/api-docs/use-tab/use-tab.json
- packages/mui-base/src/useTab/useTab.types.ts
Fixes wrong comment & description for `useTab`'s `onChange` parameter, where it showed a wrong description on the [official doc](https://mui.com/base-ui/react-tabs/hooks-api/)
The new description is from [Tab API](https://mui.com/base-ui/react-tabs/components-api/#tab)
> [docs] Fix wrong description for `UseTabParameters.onChange`

- packages/eslint-plugin-material-ui/src/rules/mui-name-matches-component-name.js
- packages/eslint-plugin-material-ui/src/rules/mui-name-matches-component-name.test.js
> [core] Revert lint for `useThemeProps`

- .eslintrc.js
- docs/src/components/banner/AppFrameBanner.tsx
- docs/src/components/productMaterial/MaterialStyling.tsx
- docs/src/components/productX/XHero.tsx
- docs/src/components/productX/XPlans.tsx
- docs/src/modules/components/ApiPage/sections/ToggleDisplayOption.tsx
- docs/src/modules/components/AppNavDrawer.js
- docs/src/modules/components/DemoSandbox.js
- docs/src/modules/components/DemoToolbar.js
- docs/src/modules/components/ReactRunner.tsx
- docs/src/modules/components/ThemeContext.js
Part of https://github.com/mui/material-ui/issues/42564
Fixes or silences errors reported by `eslint-plugin-react-compiler` in the website components.
The silenced occurrences are prepended with a comment because we use the [--report-unused-disable-directives](https://eslint.org/docs/latest/use/command-line-interface) and we can't silence rules that are not configured, like the ones coming from `eslint-plugin-react-compiler`, which is disabled by default as of today.
```js
// TODO: uncomment once we enable eslint-plugin-react-compiler // eslint-disable-next-line react-compiler/react-compiler -- useEnhancedEffect uses useEffect under the hood
```
Apart from that, add a missing React key.
Make sure the parts of the docs that are affected by the changes work as expected. Half of the changes …
> [docs-infra] Fix React Compiler ESLint issues in website components

- docs/pages/experiments/docs/codeblock.md
- docs/src/modules/components/RichMarkdownElement.js
- packages/mui-docs/src/HighlightedCode/index.tsx
- packages/mui-docs/src/HighlightedCodeWithTabs/HighlightedCodeWithTabs.tsx
- packages/mui-docs/src/HighlightedCodeWithTabs/index.ts
Add a default export so it can be imported in markdown and reused in X
> [code-infra] Use @mui/docs/HighlightedCodeWithTabs in markdown

- .github/workflows/ci.yml
- docs/pages/_document.js
- packages/mui-joy/src/styles/CssVarsProvider.tsx
- packages/mui-material/src/styles/CssVarsProvider.tsx
\
From https://github.com/mui/material-ui/pull/42829#issuecomment-2206165783
Updated the docs to fallback to `getInitColorSchemeScript` in v5 (MUI X needs this).
> [material-ui][joy-ui] Remove warning from `getInitColorSchemeScript`

- docs/pages/joy-ui/api/tooltip.json
- docs/pages/material-ui/api/switch.json
- packages/mui-base/test/describeConformanceUnstyled.tsx
- packages/mui-joy/src/Autocomplete/Autocomplete.tsx
- packages/mui-joy/src/Menu/Menu.test.tsx
- packages/mui-joy/src/MenuButton/MenuButton.test.tsx
- packages/mui-joy/src/MenuItem/MenuItem.test.tsx
- packages/mui-joy/src/Tab/Tab.test.tsx
- packages/mui-joy/src/TabList/TabList.test.tsx
- packages/mui-joy/src/TabPanel/TabPanel.test.tsx
- packages/mui-joy/src/Tooltip/Tooltip.test.tsx
- packages/mui-lab/src/TabList/TabList.test.js
- packages/mui-lab/src/TabPanel/TabPanel.test.tsx
- packages/mui-material/src/Fade/Fade.test.js
- packages/mui-material/src/Grow/Grow.test.js
- packages/mui-material/src/MenuList/MenuList.test.js
- packages/mui-material/src/NativeSelect/NativeSelectInput.test.js
- packages/mui-material/src/RadioGroup/RadioGroup.test.js
- packages/mui-material/src/Slide/Slide.test.js
- packages/mui-material/src/StepContent/StepContent.test.js
- packages/mui-material/src/SwipeableDrawer/SwipeableDrawer.test.js
- packages/mui-material/src/Switch/Switch.test.js
- packages/mui-material/src/TableBody/TableBody.test.js
- packages/mui-material/src/TableCell/TableCell.test.js
- packages/mui-material/src/TableFooter/TableFooter.test.js
- packages/mui-material/src/TableHead/TableHead.test.js
- packages/mui-material/src/TablePagination/TablePagination.test.js
- packages/mui-material/src/TableRow/TableRow.test.js
- packages/mui-material/src/Zoom/Zoom.test.js
- packages/test-utils/src/describeConformance.tsx
Cherry-pick of https://github.com/mui/material-ui/pull/42447
To land support for React 18.3.1 in v5, we're backporting the changes we did on `next` (v6) to `master`.
> [core] Replace enzyme in describeConformance

- packages/mui-styles/src/withStyles/withStyles.test.js
Cherry-pick of https://github.com/mui/material-ui/pull/42752
To land support for React 18.3.1 in v5, we're backporting the changes we did on `next` (v6) to `master`.
> [styles][withStyles] Expect React defaultProps warning in test (#42752)

- docs/data/material/components/autocomplete/FixedTags.js
- docs/data/material/components/autocomplete/FixedTags.tsx
- docs/data/material/components/autocomplete/Sizes.js
- docs/data/material/components/autocomplete/Sizes.tsx
Cherry-pick of https://github.com/mui/material-ui/pull/42691
To land support for React 18.3.1 in v5, we're backporting the changes we did on `next` (v6) to `master`.
> [material-ui][docs] Fix React 18.3 key spread warnings in Autocomplete demos

- packages/mui-joy/src/Autocomplete/Autocomplete.tsx
Cherry-pick of https://github.com/mui/material-ui/pull/42741
To land support for React 18.3.1 in v5, we're backporting the changes we did on `next` (v6) to `master`.
> [joy-ui][Autocomplete] Fix React spread key warning

- packages/mui-docs/src/CodeCopy/CodeCopy.tsx
- packages/mui-docs/src/i18n/i18n.tsx
part of https://github.com/mui/material-ui/issues/42564
> [docs] Fix issues reported by react compiler in docs folder

- packages/mui-lab/src/Alert/Alert.js
- packages/mui-lab/src/AlertTitle/AlertTitle.js
- packages/mui-lab/src/Autocomplete/Autocomplete.js
- packages/mui-lab/src/AvatarGroup/AvatarGroup.js
- packages/mui-lab/src/Pagination/Pagination.js
- packages/mui-lab/src/PaginationItem/PaginationItem.js
- packages/mui-lab/src/Rating/Rating.js
- packages/mui-lab/src/Skeleton/Skeleton.js
- packages/mui-lab/src/SpeedDial/SpeedDial.js
- packages/mui-lab/src/SpeedDialAction/SpeedDialAction.js
- packages/mui-lab/src/SpeedDialIcon/SpeedDialIcon.js
- packages/mui-lab/src/TabContext/TabContext.test.js
- packages/mui-lab/src/ToggleButton/ToggleButton.js
- packages/mui-lab/src/ToggleButtonGroup/ToggleButtonGroup.js
part of https://github.com/mui/material-ui/issues/42564
implementation inspired from https://github.com/mui/material-ui/blob/987bb036905fdd4474ae5aaee7b2b5a3dc6b9315/packages/mui-lab/src/CalendarPicker/CalendarPicker.tsx#L7-L20
> [mui-lab] Fix issues reported by react-compiler in mui-lab

- docs/data/material/migration/migrating-to-v6/migrating-to-v6.md
- docs/data/system/migration/migrating-to-v6/migrating-to-v6.md
Replace v6 "alpha" mentions with "beta", preparing for the beta's release.
> [docs] Replace v6 "alpha" mentions with "beta"

- docs/data/material/migration/migrating-to-v6/migrating-to-v6.md
- docs/translations/api-docs-joy/autocomplete/autocomplete.json
- docs/translations/api-docs/autocomplete/autocomplete.json
- packages/mui-base/src/useAutocomplete/useAutocomplete.d.ts
- packages/mui-base/src/useAutocomplete/useAutocomplete.js
- packages/mui-joy/src/Autocomplete/Autocomplete.test.tsx
- packages/mui-joy/src/Autocomplete/Autocomplete.tsx
- packages/mui-material/src/Autocomplete/Autocomplete.js
- packages/mui-material/src/Autocomplete/Autocomplete.test.js
fixes: https://github.com/mui/material-ui/issues/36085
duplicate of https://github.com/mui/material-ui/pull/37013
> [Autocomplete] Add new AutocompleteInputChangeReason

- CHANGELOG.md
- package.json
- packages-internal/docs-utils/package.json
- packages-internal/scripts/package.json
- packages-internal/test-utils/package.json
- packages/markdown/package.json
- packages/mui-base/package.json
- packages/mui-codemod/package.json
- packages/mui-core-downloads-tracker/package.json
- packages/mui-docs/package.json
- packages/mui-icons-material/package.json
- packages/mui-lab/package.json
- packages/mui-material/package.json
- packages/mui-private-theming/package.json
- packages/mui-styled-engine-sc/package.json
- packages/mui-styled-engine/package.json
- packages/mui-styles/package.json
- packages/mui-system/package.json
- packages/mui-utils/package.json
- pnpm-lock.yaml
> [release] v6.0.0-beta.0

- packages/mui-material/src/Popover/Popover.d.ts
> [material] Fix wrong import in Popover types

- packages-internal/test-utils/src/createRenderer.tsx
I found myself missing [`screen.debug()`](https://testing-library.com/docs/dom-testing-library/api-debugging/#screendebug) and [`screen.logTestingPlaygroundURL()`](https://testing-library.com/docs/dom-testing-library/api-debugging/#screenlogtestingplaygroundurl) while writing tests using `@testing-library/react`. These methods are not available because we don't export the `screen` object from `@testing-library/react` in `packages-internal/test-utils`, we create our own `screen` object with queries bound to it. See https://github.com/mui/material-ui/blob/68381cf3b76d5752b5565e50be788dd912ee5a53/packages-internal/test-utils/src/createRenderer.tsx#L740
This PR exposes all original methods coming from the `screen` object from `@testing-library/react`.
This is useful so devs can write:
```js …
```
> [core] Expose missing screen methods from Testing Library

- packages/mui-codemod/src/deprecations/divider-props/divider-props.js
- packages/mui-codemod/src/deprecations/divider-props/test-cases/expected.js
- packages/mui-codemod/src/deprecations/divider-props/test-cases/theme.actual.js
- packages/mui-codemod/src/deprecations/divider-props/test-cases/theme.expected.js
The `divider-props` codemod (introduced in https://github.com/mui/material-ui/pull/40947) removes the `light` prop and adds `sx={{ opacity: 0.6 }}` if no `opacity` is already passed to the `sx` prop.
I noticed that the codemod adds the `opacity` even when `light={false}`, which seems wrong:
```js
// input
<Divider light={false} />;
// output
<Divider sx={{ opacity: "0.6" }} />;
```
The correct output should be:
```js
<Divider />;
```
This PR fixes the codemod and adds some tests cases to also cover the presence of `light: false` in the `MuiDivider.defaultProps` of the `theme` object.
---
@sai6855 let me know if my reasoning is correct.
> [codemod] Fix Divider props codemod

- packages/mui-docs/src/MarkdownElement/MarkdownElement.tsx
Created from: https://github.com/mui/mui-x/pull/13543#discussion_r1680797191
https://next.mui.com/material-ui/migration/v5-style-changes/#%E2%9C%85-update-makestyles-import
https://deploy-preview-42979--material-ui.netlify.app/material-ui/migration/v5-style-changes/#%E2%9C%85-update-makestyles-import
| --- | --- |
| <img width="312" alt="Screenshot 2024-07-17 at 13 40 32" src="https://github.com/user-attachments/assets/b6ae22fa-46a7-43df-8d7c-2eb9852aedc2"> | <img width="304" alt="Screenshot 2024-07-17 at 13 40 00" src="https://github.com/user-attachments/assets/683ad36b-1b1a-4dc6-b32e-d4fbb7b458d9"> |
> [docs-infra] Remove `display: flex` from `SectionTitle`

- docs/data/material/getting-started/templates/blog/Blog.js
- docs/data/material/getting-started/templates/blog/Blog.tsx
Fixes #42955
👉 https://deploy-preview-42969--material-ui.netlify.app/material-ui/getting-started/templates/blog/
> [material-ui][docs] Fix broken image links in blog template on master branch

- packages/mui-joy/src/MenuItem/MenuItem.test.tsx
- packages/mui-material/src/ButtonBase/ButtonBase.test.js
- packages/mui-material/src/ListItemButton/ListItemButton.test.js
- packages/mui-material/src/MenuItem/MenuItem.test.js
- packages/mui-material/src/Popper/Popper.test.js
- packages/mui-material/src/Select/Select.test.js
- packages/mui-material/src/SpeedDial/SpeedDial.test.js
- packages/mui-material/src/Tabs/Tabs.test.js
- packages/mui-material/src/Tooltip/Tooltip.test.js
- packages/mui-material/test/integration/Menu.test.js
We're working on adopting [`eslint-plugin-testing-library`](https://github.com/testing-library/eslint-plugin-testing-library/tree/main) ([issue](https://github.com/mui/mui-public/issues/173)) and it errors when it finds unnecessary `act` calls wrapping Testing Library helpers like `fireEvent`, because these helpers already call `act` for us.
This PR removes unnecessary `act` calls from several test suites, making the code follow the "rules" of Testing Library and thus removing the ESLint errors. Also adds `await` / `async` to `act` calls in the modified files as recommended in the React [docs](https://react.dev/reference/react/act#await-act-async-actfn).
Context: https://github.com/mui/material-ui/pull/41061#discussion_r1677741979
(Thanks @Janpot for the tip!)
> [test][material-ui] Remove unnecessary async act calls

- packages/mui-material/src/Fade/Fade.js
- packages/mui-material/src/Grow/Grow.js
- packages/mui-material/src/Slide/Slide.js
- packages/mui-material/src/Tooltip/Tooltip.js
- packages/mui-material/src/Zoom/Zoom.js
- packages/mui-material/src/utils/getChildRef.d.ts
- packages/mui-material/src/utils/getChildRef.js
closes #42604 
PS: tried to create a working sandbox but i guess sandboxes linked to PR commit is not working
> [material-ui] Fix Accessing element.ref

- docs/src/components/header/HeaderNavBar.tsx
Open https://next.mui.com/. 
https://github.com/user-attachments/assets/7f531d12-ee7b-44f0-a75e-848f857cc166
A regression from #42603.
I think the root of the bug is https://github.com/w3c/csswg-drafts/issues/5885.
The navigation menu logic itself on the website pages feels a bit broken. For example, I'm confused as for why one works with tabs and the other is a composite widget (works with arrows), it feels like this should truly be abstracted into a Base UI module but 🤷‍♂️ for now, no time. I have noticed this problem from #42767. @andy-hook this make me think of  https://github.com/radix-ui/primitives/pull/1172, and why it was a great move.
Preview: https://deploy-preview-42924--material-ui.netlify.app/
> [website] Fix strange focus-visible on hover

- packages/mui-envinfo/envinfo.js
See https://github.com/mui/material-ui/pull/41942#discussion_r1684519580. This will help support ticket for Base UI, Pigment CSS and downstream dependents.
_Aside: Any reason why `@base_ui` scope is with an underscore? Feels a bit unusual for npm package naming and different to what we've been doing before with no obvious benefit. I personally find it to work particularly badly with underlines in urls (github, npm, docs,...)_
> [core] Add pigment and base ui scopes to envinfo

- packages/mui-material-nextjs/src/v13-appRouter/appRouterV13.tsx
- pnpm-lock.yaml
We're seeing differences between running `pnpm dedupe` locally and on CI. I manually removed the two entries in the lock file that were disappearing on the CI and reran `dedupe`. This seems to fix the mismatch. But this introduced some breakage in the types of `@mui/material-ui-nextjs`. This was fixed by inverting negative condition to a positive one.
> [code-infra] Fix pnpm lock file

- docs/data/material/migration/migrating-to-v6/migrating-to-pigment-css.md
The `stringifyTheme` is used internally, I forgot to remove it from the docs.
> [docs] Remove stringify theme import

- docs/data/material/migration/migrating-to-v6/migrating-to-v6.md
- docs/pages/material-ui/api/rating.json
- packages/mui-material/src/Rating/Rating.d.ts
- packages/mui-material/src/Rating/Rating.js
- packages/mui-material/src/Rating/Rating.test.js
when I use Rating readOnly mode, I found there is a issue with the aria-label by default `defaultLabelText`
which will render like below `aria-label="null Hearts"`
- [ x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/material-ui/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).
> [material-ui][Rating] fix defaultLabelText a11y issue with undefine value input and hint

- packages/mui-material-nextjs/package.json
- pnpm-lock.yaml
> [nextjs] Remove @mui/material as peer dependency

- docs/src/modules/components/Demo.js
- docs/src/modules/components/DemoSandbox.js
Add `usesCssVarsTheme` to replace `productId` to avoid [the hack](https://github.com/mui/mui-toolpad/blob/9580e0b48fab49b509842efa5a17bbbc191af761/docs/src/components/landing-core/ToolpadDashboardLayout.tsx#L201) in https://github.com/mui/mui-toolpad/pull/3830
> [docs] Make `DemoSandbox` agnostic of `productId`

- apps/pigment-css-next-app/package.json
- apps/pigment-css-vite-app/package.json
- package.json
- packages/mui-material-pigment-css/package.json
- pnpm-lock.yaml
Bump Pigment CSS packages to `0.0.18`
Required for https://github.com/mui/material-ui/pull/42824#issuecomment-2249804721
> Bump Pigment CSS to 0.0.18

- docs/data/material/components/table/DataTable.js
- docs/data/material/components/table/DataTable.tsx
- docs/data/material/components/table/DataTable.tsx.preview
- docs/data/material/components/table/table.md
Found some [issues](https://github.com/mui/mui-x/issues/13981) earlier today with some `DataGrid` demos, and fixed it in Material UI. Basically changed the demo container and added `overflow:'clip'` to fix the cropped corners.
👉 https://deploy-preview-43072--material-ui.netlify.app/material-ui/react-table/#data-table
> [material-ui][docs] Polish out data table demo

- .github/workflows/publish-canaries.yml
Follow-up to https://github.com/mui/material-ui/pull/43066
Since the canary releases are triggered manually, there's no need to check for changes with the previous commit.
> [code-infra] Do not look for changes with previous commit when releasing a canary version

- docs/src/components/pricing/PricingTable.tsx
This PR is to add information about the 10 seat cap removal and early bird pricing after August. 
I added some tweaks to the text, and added a link to the blog post (TBD).
👉  https://deploy-preview-43123--material-ui.netlify.app/pricing/
> [website] Add blog link to pricing table

- docs/src/components/pricing/PricingTable.tsx
Adding the right links to pricing table to fix https://github.com/mui/material-ui/pull/43123
> [website] Fix wrong link in pricing table

- docs/data/material/migration/migrating-from-deprecated-apis/migrating-from-deprecated-apis.md
- docs/data/material/migration/migrating-to-v6/migrating-to-pigment-css.md
- docs/data/material/migration/migrating-to-v6/migrating-to-v6.md
- docs/data/system/migration/migrating-to-v6/migrating-to-v6.md
Small content formating issues I could spot on the page.
> [docs] Polish migration guide

- packages-internal/test-utils/src/createRenderer.tsx
Follow up on https://github.com/mui/material-ui/pull/42968.
Fix [issues](https://app.circleci.com/pipelines/github/mui/mui-x/63297/workflows/23210296-a30f-4dec-938d-9d49303d350c/jobs/361379) in: https://github.com/mui/mui-x/pull/14002.
P.S. Tested locally that a package built on this PR fixes the TS issue.
> [code-infra] Fix `@mui/internal-test-utils` `screen` export type

- packages-internal/test-utils/src/describeConformance.tsx
- packages-internal/test-utils/src/flushMicrotasks.ts
- packages/mui-base/src/Menu/Menu.test.tsx
- packages/mui-base/src/Select/Select.test.tsx
- packages/mui-base/test/describeConformanceUnstyled.tsx
The `flushMicrotasks` function was incorrectly skipped during browser (karma) tests. I initially thought that the errors it throws on this environment are caused by specifics of karma. However, it turns out these errors were valid and indicated a bigger problem - the lack of support for async render functions in conformance tests.
This PR fixes both the `flushMicrotasks` function, making it run regardless of the environment, and conformance tests, to support async render functions (required in Menu and Select tests, plus many more in the future once @base_ui/react is used).
> [test] Make conformance tests work with async render function

- docs/src/components/productCore/CoreProducts.tsx
Adding icons to the products on the core page of the website to ensure consistency across the website navigation. We already have them on the app bar menu and in the docs, so this will make the experience uniform throughout.
👉  https://deploy-preview-43151--material-ui.netlify.app/core/
> [website] Add icons to core page products

- docs/src/modules/components/Demo.js
- docs/src/modules/components/DemoEditor.tsx
- docs/src/modules/components/DiamondSponsors.js
`alpha()` will throw an error if the input is a CSS variable. The usage is incorrect and the reason that the code does not throw error is because the documentation pages are not using CSS variables yet.
> [docs] Fix alpha usage

- docs/.link-check-errors.txt
- docs/scripts/reportBrokenLinks.js
The issue came from the  `marked` package migration from v5 to v13.
The argument of the `link` callback was not correct.
> [docs] Fix the link test script

- packages/mui-base/src/useAutocomplete/useAutocomplete.js
- packages/mui-base/src/useAutocomplete/useAutocomplete.test.js
- packages/mui-material/src/useAutocomplete/useAutocomplete.js
- packages/mui-material/src/useAutocomplete/useAutocomplete.test.js
Part of: https://github.com/mui/material-ui/pull/42824
I couldn't find a reason in the [React 19 upgrade guide](https://react.dev/blog/2024/04/25/react-19-upgrade-guide) for why this change was necessary. What I understand is that because the array is being defined on every render, it's not stable. Users would have to change this as well when upgrading to React 19.
> [material-ui][Autocomplete] Fix default value for multiple mode getting redefined with React 19

- apps/pigment-css-vite-app/package.json
- pnpm-lock.yaml
This package isn't used and needed in `pigment-css-vite-app`. Only `react-router-dom` is needed.
Closes #43172
> [core] Remove `react-router` package from `pigment-css-vite-app`

- docs/data/base/components/select/select.md
- docs/src/components/animation/FlashCode.tsx
Part of https://github.com/mui/material-ui/issues/42381
Commit based on https://github.com/mui/material-ui/pull/42824
Replaces the latest occurrences of the `JSX` TypeScript namespace with `React.JSX`. More info in the [React 19 upgrade guide](https://react.dev/blog/2024/04/25/react-19-upgrade-guide#the-jsx-namespace-in-typescript).
> [core] Replace JSX namespace usages with React.JSX

- package.json
- patches/styled-components@6.1.12.patch
- pnpm-lock.yaml
Part of https://github.com/mui/material-ui/issues/42381
Commits cherry-picked/based on https://github.com/mui/material-ui/pull/42824
Patches `styled-components` to use the `React.JSX` TS namespace instead of `JSX`. More info in the [React 19 upgrade guide](https://react.dev/blog/2024/04/25/react-19-upgrade-guide#the-jsx-namespace-in-typescript).
> [core] Patch styled-components to use React.JSX namespace

- packages/mui-lab/src/Masonry/Masonry.test.js
Removes a prop type check in a test because it's already covered in another test in the same file. We forgot to fix this one in https://github.com/mui/material-ui/pull/43155.
Example of the test failure without this fix: https://app.circleci.com/pipelines/github/mui/material-ui/135461/workflows/b151718a-3164-404f-974a-3c13802fca53/jobs/730232?invite=true#step-111-171
Context: React 19 removed prop type checks so we need to skip them in prior versions. More info: https://react.dev/blog/2024/04/25/react-19-upgrade-guide#removed-proptypes-and-defaultprops
> [test] Remove unnecessary prop type check in test

- docs/README.md
Closes #43208
Adds a missing script: `pnpm install`.
Updates an incorrect script: `pnpm start` to `pnpm dev`
> fix(docs): missing and incorrect scripts

- babel.config.js
- package.json
- packages/mui-material/src/index.d.ts
- packages/mui-material/src/index.js
- packages/mui-material/src/index.test.js
- packages/mui-material/src/version/index.ts
- packages/mui-system/src/index.d.ts
- packages/mui-system/src/index.js
- packages/mui-system/src/version/index.ts
- pnpm-lock.yaml
- scripts/build.mjs
- scripts/utils.mjs
Cherry-pick #43190 to master, so the version consts are available in v5 as well
> [material-ui][mui-system] Cherry-pick: Add support for version runtime checks (#43190)

- examples/material-ui-vite-ts/src/main.tsx
> [examples] Replace wrong import with `@mui/material/styles`

- scripts/build.mjs
- scripts/utils.mjs
Use `fs` instead of `fs-extra` in utils to avoid [this pitfall](https://github.com/DiegoAndai/material-ui/blob/next/scripts/useReactVersion.mjs#L7). I'm not sure why it didn't fail in https://github.com/mui/material-ui/pull/43190 but it did in https://github.com/mui/material-ui/pull/43233.
> [core] Use fs instead of fs-extra in script utils

- docs/data/joy/components/grid/grid.md
address: https://mui-org.slack.com/archives/C050VE13HDL/p1723282242634159
preview: https://deploy-preview-43247--material-ui.netlify.app/joy-ui/react-grid/
> [docs][joy-ui] Fix data grid redirection

- docs/data/system/styled/styled.md
address: https://mui-org.slack.com/archives/C041SDSF32L/p1723047828638299
preview: https://deploy-preview-43223--material-ui.netlify.app/system/styled/#import-path
> [mui-system] Add import statement in docs

- packages/mui-material/src/styles/createGetSelector.ts
- packages/mui-material/src/styles/extendTheme.test.js
- packages/mui-system/src/cssVars/prepareCssVars.ts
> [material-ui][pigment-css] Fix `getSelector` prefers-color-scheme to be object

- packages/mui-material/src/useMediaQuery/useMediaQuery.test.js
While upgrading to React 19 ([PR](https://github.com/mui/material-ui/pull/42824)) a `useMediaQuery` test started to fail.
React 19 is calling `React.useMemo` and other hooks in a different way than React 18 and that is making our `fakeMatchMedia` test implementation to fail. This fake implementation keeps a list of `matchMedia` instances to later be able to assert things, but the list of instances has a different order in React 18 and React 19.
To solve it, I've added a `Map` of `matchMedia` instances so we only create one for a given `query`. This is closer to how the real `window.matchMedia` is used in `useMediaQuery`, because it's just a local variable ([see source code](https://github.com/mui/material-ui/blob/4c46022dc41281d20e6af26a32642ffef10839ee/packages/mui-system/src/useMediaQuer …
> [material-ui][useMediaQuery] Adapt test implementation for React 19

- packages/mui-material/src/IconButton/IconButton.js
- packages/mui-material/src/IconButton/IconButton.test.js
The hover behavior was broken on the IconButton component, as the styles are looking for `disabledRipple: false` (for e.g. check [this](https://github.com/mui/material-ui/blob/490abc4820ffe15d0c3c8143d4cde929405480b2/packages/mui-material/src/IconButton/IconButton.js#L56)), while there was no default value set in the component.
Preview: https://deploy-preview-43271--material-ui.netlify.app/material-ui/react-button/#icon-button
Previous behavior: https://next.mui.com/material-ui/react-button/#icon-button
> [IconButton] Fix hover background color behavior

- packages/mui-utils/src/getDisplayName/getDisplayName.test.tsx
Part of https://github.com/mui/material-ui/issues/42381
Extracted from https://github.com/mui/material-ui/pull/42824/files#r1715334482
> [utils][test] Remove unnecessary ref param

- docs/src/components/pricing/PricingTable.tsx
- docs/src/components/productMaterial/MaterialStyling.tsx
Extracted from https://github.com/mui/material-ui/pull/42824
Replacing a couple of instances of `React.MutableRefObject` with `React.RefObject`. `React.MutableRefObject` will be deprecated in React 19 types.
> [website] Replace React.MutableRefObject with React.RefObject

- docs/src/modules/components/ApiPage.tsx
- docs/src/modules/components/AppLayoutDocs.d.ts
Make some typing fixes that we need in X and Toolpad
* Add typings for `docs/src/modules/components/AppLayoutDocs.js`.  We can also migrate to TS, but this was quick and easy
* Some type issues in `docs/src/modules/components/ApiPage.tsx` that for some reason are not reported in the core repo. To investigate
See https://github.com/mui/mui-x/pull/14141
> [docs-infra] Fix some TS issues for X docs

- packages/mui-styles/src/StylesProvider/StylesProvider.js
- packages/mui-styles/src/makeStyles/makeStyles.js
- packages/mui-styles/src/makeStyles/makeStyles.spec.tsx
- packages/mui-styles/src/withStyles/withStyles.js
Part of https://github.com/mui/material-ui/issues/42564
FILES CHANGED:
StylesProvider.js: ESLint error: "Unexpected reassignment of a variable which was defined outside of the component. Components and hooks should be pure and side-effect free, but variable reassignment is a form of side-effect."  Line 87. Moved variable definition of 'injectFirstNode' inside of 'StylesProvider' function, fixing ESLint error
makeStyles.js: ESLint error: "Expected the dependency list for useMemo to be an array literal" Line 167. Changed 'useMemo' param "values" to "[values]", fixing ESLint error
makeStyles.spec.tsx: ESLint error: "Hooks must be the same function on every render but this value may change over time to a different function." Line 132. Moved definition of 'useStyles' outside of function …
> [styles] Fix issues reported by eslint-plugin-react-compiler

- docs/babel.config.js
- docs/nextConfigDocsInfra.js
Use this assumption to speed up the spread operator: https://babeljs.io/docs/assumptions#setspreadproperties
Our docs don't use the fast object spread operator, this babel assumption makes code that uses `const x = { ...y }` faster. This change is already done in X but I haven't had time to do it here as well.
The test case is: open the MUI material docs overview page, then click on the "Button" section. The following graphs show the performance of the first section of code that follows that click event. This section of code is the render functions, and shows an improvement of around 10%.
| before | after |
| --- | --- |
| ![spread-before](https://github.com/user-attachments/assets/c0bf30f6-c0dd-4d03-8f8e-ba7ca5b33f8b) | ![spread-after](https://github.com/user-attachments/assets/7e7afd94-6 …
> [docs/perf] Update babel config

- docs/data/material/components/popover/MouseHoverPopover.js
- docs/data/material/components/popover/MouseHoverPopover.tsx
- docs/data/material/components/popover/popover.md
While reviewing issue #43231, I noticed that `mouseover` was incorrectly mentioned instead of `mouseenter`. I also updated the section title and renamed the file/demo.
Preview: https://deploy-preview-43290--material-ui.netlify.app/material-ui/react-popover/#mouse-hover-interaction
> [docs][material-ui][Popover] Fix description and title of hover interaction section

- docs/data/material/components/dividers/VerticalDividerMiddle.js
- docs/data/material/components/dividers/VerticalDividerMiddle.tsx
- docs/data/material/components/dividers/VerticalDividers.js
- docs/data/material/components/dividers/VerticalDividers.tsx
- docs/data/material/components/dividers/dividers.md
- docs/data/material/migration/migrating-to-v6/migrating-to-v6.md
- packages/mui-material/src/Divider/Divider.js
- packages/mui-material/src/Divider/Divider.test.js
Resolves https://github.com/mui/material-ui/issues/43275
Modifies the [`Divider`](https://mui.com/material-ui/react-divider/) component to render a `<div role="separator" aria-orientation="vertical">` instead of `<hr>` when using vertical orientation to adhere to the [ARIA spec](https://www.w3.org/TR/wai-aria-1.2/#separator).
This can be considered a breaking change since consumers might be targeting `hr` elements for styling purposes.
**Benchmarks**
- https://www.w3.org/TR/wai-aria-1.2/#separator
- https://react-spectrum.adobe.com/react-spectrum/Divider.html#vertical
- https://www.radix-ui.com/primitives/docs/components/separator
> [material-ui][Divider] Add aria-orientation

- apps/pigment-css-next-app/src/app/material-ui/react-popover/page.tsx
For some reason this wrong import wasn't caught by the CI in https://github.com/mui/material-ui/pull/43290. The CI for the `next` branch is failing https://github.com/mui/material-ui/actions/runs/10403614737/job/28810870436#step:7:2434
> [examples] Fix import

- .github/workflows/ci.yml
- apps/pigment-css-next-app/src/app/material-ui/react-popover/page.tsx
- docs/data/material/getting-started/supported-platforms/supported-platforms.md
- packages/mui-material/package.json
- packages/mui-utils/package.json
It looks like these were forgotten in https://github.com/mui/material-ui/pull/42920? This would allow us to add package `"exports"` on a minor.
> [core] Update supported Node.js version to 14

- scripts/sizeSnapshot/webpack.config.js
Use an ESM entrypoint instead of a commonjs to get a more accurate depiction of reality. Also removing the alias as we can rely on pnpm package linking through the `publishConfig.directory` option.
We don't have this problem with other modules as they don't use the `esm/` layout. We'll unify the package layout as part of improved ESM support.
Noticed this in https://github.com/mui/material-ui/pull/43243
🤔 I was initially surprised by the large bundle size reduction. It looks like it now manages to aggressively tree-shake things such as the (in production) unused `chainProptypes` and the functions it's called with.
[bundles diff](https://www.diffchecker.com/92auTICh/)
> [code-infra] Fix utils bundle size entrypoint

- SECURITY.md
- docs/data/material/getting-started/support/support.md
Reproduce format used in the other repositories https://github.com/mui/mui-x/pull/14128.
> [docs] Update LTS to match format

- scripts/sizeSnapshot/webpack.config.js
Remove unneeded aliases from bundle size webpack config. We can rely on `pnpm` linked packages with the `publishConfig.directory` now. https://pnpm.io/package_json#publishconfigdirectory
> [code-infra] Remove unnecessary alias

- docs/src/components/home/ProductsSwitcher.tsx
- docs/src/components/home/ToolpadCoreShowcaseDemo.tsx
- docs/src/components/home/ToolpadShowcase.tsx
- docs/src/route.ts
- Update the Products switcher copy for Toolpad
- "Toolpad Studio" -> "Toolpad"
- "Self-hosted, low-code builder.." -> "Components and tools for building dashboards and internal apps"
- "Start using Toolpad" -> "Start using Toolpad Core/Studio"
- "Learn more about why to use Toolpad" -> "Learn more about Toolpad Core/Studio"
- Update the demo tabs
- Add the `<DashboardLayout />` as the demo for "Core"
- Merge the earlier demo tabs into one for "Studio"  
> "Use a drag-and-drop interface to build your app's configuration. Changes made in Studio are automatically synced to .yml files, and vice-versa. Bring your own components and data." 
as a single description
> [website] Update showcase to include Toolpad Core

- .browserslistrc
As pointed out in https://github.com/mui/material-ui/pull/42920#issuecomment-2292210011
> [core] Set Node 14 as minimum version in all browserslist envs

- docs/data/material/customization/theme-components/theme-components.md
- docs/data/material/getting-started/overview/overview.md
- examples/material-ui-cra-tailwind-ts/README.md
- examples/material-ui-cra-ts/README.md
- examples/material-ui-cra/README.md
- examples/material-ui-express-ssr/README.md
- examples/material-ui-gatsby/README.md
- examples/material-ui-nextjs-pages-router-ts/README.md
- examples/material-ui-nextjs-pages-router/README.md
- examples/material-ui-nextjs-ts-v4-v5-migration/README.md
- examples/material-ui-preact/README.md
- examples/material-ui-remix-ts/README.md
- examples/material-ui-vite-ts/README.md
- examples/material-ui-vite/README.md
I landed on the docs landing page of Material UI v6 that is closer to be stable https://next--material-ui.netlify.app/material-ui/getting-started/ and got confused:
This looks like a quick win.
> [docs] Fix outdated references to Materal UI version

- netlify.toml
Replicate the change in: https://github.com/mui/mui-x/pull/14182.
It looks like this setting was the culprit of sporadic Netlify behavior such as pulling a stale cache on some builds.
> [core] Fix Netlify build cache issue

- packages/mui-material/src/ListItem/ListItem.spec.tsx
Since `button` prop is removed from `ListItem`, i felt [this](https://github.com/mui/material-ui/pull/43359/files#diff-cc917c026400cc6bdef8fd581f8a4babe10b2659b6d88965806a4b781f4244f5) test is unnecessary
> [material-ui][ListItem] Remove unnecessary TypeScript test

- docs/src/modules/components/DemoSandbox.js
> [docs] Add cache to avoid unnecessary jsx dynamic import and theme getting

- packages/mui-codemod/src/v6.0.0/system-props/removeSystemProps.js
- packages/mui-codemod/src/v6.0.0/system-props/test-cases/system-props.actual.js
- packages/mui-codemod/src/v6.0.0/system-props/test-cases/system-props.expected.js
Follow up on https://github.com/mui/material-ui/pull/43054#discussion_r1693188940. Add `Grid2` to `removeSystemProps` codemod
> [codemod] Add Grid2 to removeSystemProps codemod

- .npmrc
[pnpm 9.7.0](https://github.com/pnpm/pnpm/releases/tag/v9.7.0) added a new flag: [`manage-package-manager-versions`](https://pnpm.io/npmrc#manage-package-manager-versions). Corepack will likely be removed from Node, so using this new flag seems like a win. Per https://github.com/mui/material-ui/pull/43344#issuecomment-2296250327, looks like we're keen on enabling `manage-package-manager-versions`.
> [core] Enable manage-package-manager-versions pnpm flag

- docs/data/material/migration/upgrade-to-v6/upgrade-to-v6.md
- docs/src/components/showcase/FolderTreeView.tsx
- packages/mui-system/src/Box/Box.d.ts
- packages/mui-system/src/Box/Box.spec.tsx
- packages/mui-system/test/typescript/moduleAugmentation/boxSx.spec.tsx
- packages/mui-system/test/typescript/moduleAugmentation/boxSx.tsconfig.json
Fixes https://github.com/mui/material-ui/issues/34068
When this was implemented initially (https://github.com/mui/material-ui/pull/38168), an error was reported (https://github.com/mui/material-ui/issues/38274), which prompted it to be reverted.
The issue was with `styled(Box)`, but since then, we've added the [`no-styled-box` rule](https://github.com/mui/material-ui/blob/next/packages/eslint-plugin-material-ui/src/rules/no-styled-box.js), so instead of the proposed workaround I added the following diff to the upgrade guide:
```diff
-const StyledBox = styled(Box)`
+const StyledDiv = styled('div')`
color: white;
`;
```
I also added [the type cast](https://github.com/mui/material-ui/issues/38274#issuecomment-1661805628), just in case.
> [material-ui][Box] Remove `component` from `BoxOwnProps`

- docs/data/material/discover-more/roadmap/roadmap.md
I got confused following the link in https://next.mui.com/material-ui/discover-more/roadmap/#milestones. It's not what the page says.
> [docs] Fix broken link to milestones

- docs/package.json
Change the production start command to statically serve the export folder. The `next start` command doesn't work with static export.
> [code-infra] Change docs:start script to serve the exports folder

- .circleci/config.yml
I noticed in #43384 that the test was added, but MUI System's TypeScript module augmentation tests weren't running in CI.
> [core] Run `@mui/system` TypeScript module augmentation tests in CI

- .circleci/config.yml
The `typescript-next` CircleCI workflow is failing due to a mismatch of the pnpm version installed vs the one defined in package.json engines. Example failure: https://app.circleci.com/pipelines/github/mui/material-ui/136842/workflows/2ee9d991-0807-4242-b5ae-f8911336ccb7/jobs/738034?invite=true#step-102-6
To solve the issue, we need to run corepack before pnpm gets used. Also modifying the typescript install script so we update all packages and not only the root package.json
> [core] Fix typescript-next CI workflow

- docs/pages/blog/introducing-pigment-css.md
- docs/pages/blog/material-ui-v4-is-out.md
Follow-up to #42198.
I have seen https://remix.run/blog/merging-remix-and-react-router add their React Conf talk after publishing their blog post. While in the case of MUI, I think we should have done this in the first place, before posting the blog post. But it's not too late. So I'm taking action. Can someone add this to https://github.com/mui/pigment-css/blob/master/README.md? Thanks
I also used the opportunity to change what I felt could be improved. Especially, I focused on the performance part of the blog post as I felt it wasn't something developers could take seriously. It feels like it missed the points. Hopefully, it's fixed now.
Preview: https://deploy-preview-42500--material-ui.netlify.app/blog/introducing-pigment-css/
---
On the announcement, it performed poorly …
> [blog] Add video to the Pigment CSS blog post

- docs/src/components/header/HeaderNavBar.tsx
- docs/src/components/header/HeaderNavDropdown.tsx
| Location | Before | After |
|--------|--------|--------|
| Mobile | <img width="353" alt="Screenshot 2024-08-21 at 7 25 53 PM" src="https://github.com/user-attachments/assets/a6380e5e-e2b8-4e30-8184-ff3bd34fa506">| <img width="361" alt="Screenshot 2024-08-21 at 7 24 21 PM" src="https://github.com/user-attachments/assets/15bc890a-df63-4483-abd0-f0f15df2b6d6">
| Web Product menu | <img width="489" alt="Screenshot 2024-08-21 at 7 31 24 PM" src="https://github.com/user-attachments/assets/7cb057d0-ea80-4e25-8292-910c55a7f8f6"> | <img width="489" alt="Screenshot 2024-08-21 at 7 29 59 PM" src="https://github.com/user-attachments/assets/31548874-fe00-4e11-ba66-e31d66e2c352"> |
> [website] Make beta chip consistent for Toolpad

- docs/data/material/pages.ts
- docs/scripts/i18n.ts
> [docs] Add two Toolpad Core components to Material UI sidebar

- docs/pages/material-ui/api/loading-button.json
- docs/translations/api-docs/loading-button/loading-button.json
- packages/mui-lab/src/LoadingButton/LoadingButton.d.ts
- packages/mui-lab/src/LoadingButton/LoadingButton.js
- packages/mui-lab/src/LoadingButton/loadingButtonClasses.ts
- packages/mui-material/src/utils/index.d.ts
- packages/mui-material/src/utils/index.js
The objective is to fix the regression introduced by #35198 that we noticed on the store: 
Origin: https://github.com/mui/mui-private/pull/511. Reproduction: https://codesandbox.io/p/sandbox/affectionate-night-64fljj?workspaceId=836800c1-9711-491c-a89b-3ac24cbd8cd8
I have tried in #43400 to remove the `<span>`, but it didn't work in production. Instead, we can use what Material UI v4 was using to make the span more transparent: https://github.com/mui/material-ui/blob/cd0884f9bdc53e535368c741c63479411a47cf0a/packages/material-ui/src/Button/Button.js#L37
Also, to note that this span should have had the API to customize it, I'm adding this at the same time.
> [button] Add missing customize points for span

- docs/data/material/integrations/nextjs/nextjs.md
> [docs] Fix CSS theme variables section

- docs/notifications.json
This should be the last PR to be merged for v6 stable.
> [docs] Add `Material UI v6 is out!` to the notifications

- packages/mui-docs/package.json
- pnpm-lock.yaml
Noticed this when testing `@mui/material@6` on the `mui-x` repo, which has a `@mui/docs` dependency.
Should be merged before the stable release.
> [core] Allow `^6.0.0` for `@mui/` dependencies in `@mui/docs`

- docs/package.json
- docs/public/_redirects
- docs/src/components/banner/AppFrameBanner.tsx
- docs/src/components/banner/AppHeaderBanner.tsx
- docs/src/featureToggle.js
- Turn on AppHeaderBanner and AppFrameBanner
- Update `docs:deploy` to publish v5 subdomain
---
> Prepare for moving to v5.x branch

- scripts/releaseChangelog.mjs
The next branch no longer exists, so this command is failing the CI on all new PRs.
> [ci] Fix the release:changelog cmd

- packages/mui-material/src/Accordion/Accordion.d.ts
- packages/mui-material/src/Backdrop/Backdrop.d.ts
- packages/mui-material/src/Dialog/Dialog.d.ts
- packages/mui-material/src/Fade/Fade.d.ts
- packages/mui-material/src/FormControlLabel/FormControlLabel.d.ts
- packages/mui-material/src/Grow/Grow.d.ts
- packages/mui-material/src/NativeSelect/NativeSelect.d.ts
- packages/mui-material/src/Popover/Popover.d.ts
- packages/mui-material/src/Select/Select.d.ts
- packages/mui-material/src/Slide/Slide.d.ts
- packages/mui-material/src/Snackbar/Snackbar.d.ts
- packages/mui-material/src/SpeedDial/SpeedDial.d.ts
- packages/mui-material/src/StepContent/StepContent.d.ts
- packages/mui-material/src/Stepper/Stepper.d.ts
- packages/mui-material/src/Tooltip/Tooltip.d.ts
- packages/mui-material/src/Zoom/Zoom.d.ts
Part of: https://github.com/mui/material-ui/issues/42380
since no one has taken up the issue since last 3 months, i opened PR fixed it
> [material-ui] Change React.ReactElement<any,any> type from any to unknown

- .github/workflows/closed-issue-message.yml
- .github/workflows/support-stackoverflow.yml
Adds the reusable workflow of adding a message on closed issues (like in thew x repo)
This is using a reusable workflow to decrease friction on changes.
> [infra] Add closing message workflow

- docs/pages/blog/mui-x-sep-2024-price-update.md
A continuation of #43061. I tweaked a bit the content, trying to anticipate what people could be confused about. I didn't look at the support tickets, there is likely more that we could learn to reflect on this blog post but 🤷‍♂️ no time. It looks solid otherwise.
Preview: https://deploy-preview-43438--material-ui.netlify.app/blog/mui-x-sep-2024-price-update/
---
In the email we sent, I wish we kept it shorter and linked the blog post, I think it's better because it helps people share the content with their team (rather than forwarding an email).
> [blog] Polish Upcoming changes to MUI X pricing in 2024

- docs/notifications.json
> [docs] Add Material UI v6 is out! to the notifications

- packages/netlify-plugin-cache-docs/index.js
- packages/netlify-plugin-cache-docs/package.json
Main changes:
- Cache only `docs/.next/cache` folder instead of the entire `docs/.next` folder
- We were previously caching some files that could get stale. This is in-line with the official plugin
https://github.com/netlify/next-runtime/blob/733a0219e5413aa1eea790af48c745322dbce917/src/build/cache.ts
- Remove `digest`
- providing a digest could make it worse, since it was meant for `node_modules`-like folders, which contain an ungodly amount of files
docs: https://github.com/netlify/build/blob/main/packages/cache-utils/README.md#digests
save/restore impl: https://github.com/netlify/build/blob/main/packages/cache-utils/src/main.ts
manifest impl: https://github.com/netlify/build/blob/main/packages/cache-utils/src/manifest.ts
- Move from `onPostBuild` to `onBuild` to be in par with the …
> [code-infra] Fix nextjs build cache

- docs/nextConfigDocsInfra.js
Next.js v15 drops support for the `optimizeFonts` option (see https://github.com/vercel/next.js/pull/69137) and warns about this option being invalid. I'm adding a comment so we don't forget about it.
Next.js v15 build time warning:
> [docs-infra] Add comment about removing optimizeFonts Next.js config

- docs/data/material/components/dialogs/dialogs.md
The commit modifies wording of the confirmation dialog by removing the option to close the dialog by pressing the "Back" button. This ensures that users can only cancel the action by touching the "Cancel" button.
Closes [41398](https://github.com/mui/material-ui/issues/41398)
> [docs][material-ui][Dialog] Update confirmation dialog description

- docs/src/modules/components/AppLayoutDocsFooter.js
That check looked wrong to me. We have an env variable for this, which is replaced at build-time, so less bundle size, and that is more predictable.
(Initially added by Matt)
> [docs-infra] Fix use of process.env.DEPLOY_ENV

- packages-internal/docs-utils/package.json
- packages-internal/test-utils/package.json
- packages/api-docs-builder/tsconfig.json
This came up on https://github.com/mui/material-ui/pull/43264, example: https://app.circleci.com/pipelines/github/mui/material-ui/137522/workflows/fa1c6a26-2bb8-4c47-a680-b33ce62c6a08/jobs/741391
* `@mui-internal/api-docs-builder` has the wrong path configured for `@mui/internal-docs-utils`. (Not sure why it's not extending from the global tsconfig like the other projects, but honestly, I think I prefer to do this on a per project basis) 
* `@mui/internal-docs-utils` and `@mui/internal-test-utils` are using the `-b` flag. Not sure why, they don't have project references and we don't do this anywhere yet.
> [code-infra] Fix typing issues with `@mui-internal/api-docs-builder`

- docs/data/material/components/table/DataTable.js
- docs/data/material/components/table/DataTable.tsx
- docs/data/material/components/table/DataTable.tsx.preview
- docs/data/material/components/table/table.md
I have seen a designer ask when to use a table vs. a data grid: https://discord.com/channels/1131323012554174485/1131329358062178324/1273813466347602082. I believe it should purely be a technical decision, so here is a continuation of #43072 to make the data grid blend in.
Before: https://mui.com/material-ui/react-table/#data-table
After: https://deploy-preview-43489--material-ui.netlify.app/material-ui/react-table/#data-table
> [docs][table] Make the data grid blend in

- docs/data/material/customization/shadow-dom/ShadowDOMDemoNoSnap.js
- docs/data/material/customization/shadow-dom/shadow-dom.md
- test/regressions/index.js
Part of https://github.com/mui/material-ui/issues/39766
Introducing the changes suggested in https://github.com/mui/material-ui/pull/42824#issuecomment-2313737544 to be able to skip certain demos regression tests and skipping the shadow DOM regression test.
> [docs-infra] Skip shadow DOM regression test

- CHANGELOG.md
Missed it in https://github.com/mui/material-ui/pull/43515.
> [core] Fix CHANGELOG `@mui/material@6.0.1` version

- docs/data/material/getting-started/templates/blog/TemplateFrame.js
- docs/data/material/getting-started/templates/blog/TemplateFrame.tsx
- docs/data/material/getting-started/templates/blog/theme/themePrimitives.js
- docs/data/material/getting-started/templates/blog/theme/themePrimitives.ts
- docs/data/material/getting-started/templates/checkout/TemplateFrame.js
- docs/data/material/getting-started/templates/checkout/TemplateFrame.tsx
- docs/data/material/getting-started/templates/checkout/theme/themePrimitives.js
- docs/data/material/getting-started/templates/checkout/theme/themePrimitives.ts
- docs/data/material/getting-started/templates/dashboard/TemplateFrame.js
- docs/data/material/getting-started/templates/dashboard/TemplateFrame.tsx
- docs/data/material/getting-started/templates/dashboard/theme/themePrimitives.js
- docs/data/material/getting-started/templates/dashboard/theme/themePrimitives.ts
- docs/data/material/getting-started/templates/marketing-page/TemplateFrame.js
- docs/data/material/getting-started/templates/marketing-page/TemplateFrame.tsx
- docs/data/material/getting-started/templates/marketing-page/theme/themePrimitives.js
- docs/data/material/getting-started/templates/marketing-page/theme/themePrimitives.ts
- docs/data/material/getting-started/templates/shared-theme/themePrimitives.js
- docs/data/material/getting-started/templates/shared-theme/themePrimitives.ts
- docs/data/material/getting-started/templates/sign-in-side/TemplateFrame.js
- docs/data/material/getting-started/templates/sign-in-side/TemplateFrame.tsx
- docs/data/material/getting-started/templates/sign-in-side/theme/themePrimitives.js
- docs/data/material/getting-started/templates/sign-in-side/theme/themePrimitives.ts
- docs/data/material/getting-started/templates/sign-in/TemplateFrame.js
- docs/data/material/getting-started/templates/sign-in/TemplateFrame.tsx
- docs/data/material/getting-started/templates/sign-in/theme/themePrimitives.js
- docs/data/material/getting-started/templates/sign-in/theme/themePrimitives.ts
- docs/data/material/getting-started/templates/sign-up/TemplateFrame.js
- docs/data/material/getting-started/templates/sign-up/TemplateFrame.tsx
- docs/data/material/getting-started/templates/sign-up/theme/themePrimitives.js
- docs/data/material/getting-started/templates/sign-up/theme/themePrimitives.ts
Fixes item 24 from #41469
Based on #43369 from @Andarist, this PR fixes the shadows in the custom theme of the templates and adds the 23 remaining shadow tokens from the default theme.
> [docs][material-ui] Fix template shadow tokens

- docs/pages/material-ui/api/popover.json
- docs/translations/api-docs/popover/popover.json
- packages/mui-material/src/Popover/Popover.d.ts
- packages/mui-material/src/Popover/Popover.js
fix: update popover component with deprecated props and types
Closes: [43222](https://github.com/mui/material-ui/issues/43222)
> [material-ui][Menu,Popover] Fix Backdrop props descriptions

- packages/mui-material/src/MenuList/MenuList.js
- packages/mui-material/test/integration/MenuList.test.js
> [material-ui][MenuList] Do not react to an event with modifier key pressed

- .github/workflows/publish-canaries.yml
It looks like this GitHub action doesn't need GITHUB_TOKEN with permissions to our GitHub repository APIs. Flagged in https://github.com/mui/material-ui/security/code-scanning/69.
> [code-infra] Remove permissions in publish-canaries.yml

- docs/pages/blog/material-ui-v6-is-out.md
fix: Update "What's next" link in material-ui-v6 blog post
Closes: #43525
Preview: https://deploy-preview-43535--material-ui.netlify.app/blog/material-ui-v6-is-out/
> [blog] Update Material UI v6 blog post link to reflect correct section title

- packages/mui-docs/src/ComponentLinkHeader/ComponentLinkHeader.tsx
This is a quick follow-up on #43387.
This link creates a 301, which slows the user experience by about 200ms:
I keep forgetting about tree (folder) vs. blob (file) in the URL to link in GitHub.
---
Also, none of the other chips have target blank, I got confused that it didn't open in the same window. I removed it for consistency of behavior. We could discuss adding to all the chips as well, but I think it's a bit beyond this scope.
Preview: https://deploy-preview-43534--material-ui.netlify.app/material-ui/react-alert/
> [docs-infra] Fix GitHub source link redirection

- packages/mui-material/src/styles/createTheme.test.js
- packages/mui-material/src/styles/createTheme.ts
> [material-ui] Fix `createTheme` with just color schemes

- docs/pages/experiments/docs/callouts.md
- packages/markdown/parseMarkdown.js
Crash if using an invalid callout type. I made this mistake in #43543.
Similar to https://github.com/mui/material-ui/blob/abbfbd5dff2cc741fe8d867e7139956874d65f81/packages/markdown/prism.js#L24-L26.
> [docs-infra] Crash on invalid callout type

- SECURITY.md
- docs/data/material/getting-started/support/support.md
We were missing this step in the guide https://www.notion.so/mui-org/Core-Major-version-release-process-7601e24709b84d5fa43f20a13f7526c6?pvs=4#8b9a7bcfbdb546699f497131aba1bfb6 added and PR done to illustrate it.
> [docs] Update version support range

- docs/pages/blog/material-ui-v6-is-out.md
- packages/markdown/prepareMarkdown.js
Enforce max length in code, from 170 down to 160. I suspect we should go as far as 150, but maybe for another time.
See https://www.reddit.com/r/SEO/comments/14rc47l/meta_description_too_long_advice/. Meta descriptions are not used for SEO, but to improve the CTR on the search result. So if they are truncated, it defeats their purpose; 
"nextjs 15 release", fits
"material ui v6 release", doesn't fit
I suspect that https://nextjs.org/blog/ are authors in the same underlying infra as https://vercel.com/blog/, but show in a different URL path. It's not a coincidence that all their posts's descriptions are short. This might look like a detail, but I think it's this kind of depth of execution difference that compounds and separates the great UX from the good ones.
Saw this from …
> [docs-infra] Reduce description max-length

- packages/mui-material/src/Popover/Popover.spec.tsx
- packages/mui-material/src/utils/types.ts
closes #43522
The `SxProps` is missing generic so it's not working with callback signature.
> [typescript] Fix missing `Theme` generic

- packages/mui-codemod/src/v6.0.0/list-item-button-prop/list-item-button-prop.js
- packages/mui-codemod/src/v6.0.0/list-item-button-prop/list-item-button-prop.test.js
- packages/mui-codemod/src/v6.0.0/list-item-button-prop/test-cases/not-related.actual.js
- packages/mui-codemod/src/v6.0.0/list-item-button-prop/test-cases/not-related.expected.js
> [codemod] Skip `ListItemButton` import for unrelated files

- docs/data/material/design-resources/material-ui-sync/material-ui-sync.md
I saw a couple of comments about this in https://www.figma.com/community/plugin/1336346114713490235/material-ui-sync, e.g. https://github.com/mui/mui-design-kits/issues/389 asking about
> why the theme only generates 3 components? 
A general thought, anytime we no a major, we should try to remove stuff aggressively: https://youtu.be/tRsxLLghL1k?si=sRhbVRHVLRR83pMX&t=574. This feature might be je trending toward being removed.
Before: https://mui.com/material-ui/design-resources/material-ui-sync/#customizing-components
After: https://deploy-preview-43543--material-ui.netlify.app/material-ui/design-resources/material-ui-sync/#customizing-components
> [docs][figma] Clarity state or Figma Plugin component export

- babel.config.js
- packages/mui-material-pigment-css/package.json
- pnpm-lock.yaml
- scripts/build.mjs
Discovered in https://github.com/mui/material-ui/pull/43264, where this was breaking a build. Took the opportunity to add a check for missing `@babel/runtime` dependencies. As suggested in https://github.com/mui/material-ui/pull/43243 I'm passing this version to babel config to be used in the build.
> [code-infra] Add missing @babel/runtime dependency to @mui/material-pigment-css

- packages/mui-utils/src/composeClasses/composeClasses.test.ts
- packages/mui-utils/src/composeClasses/composeClasses.ts
Fix the behavior change introduced in #43363. I worked on this PR because I was trying a button customize in the store and got frustrated in the DX to find the class names applied:
The performance win stays comparable as before https://jsben.ch/S3LCV
A related design principle: https://www.usertesting.com/blog/gestalt-principles#principle-#3:-proximity.
> [system] Fix composeClasses v6 behavior change

- docs/pages/experiments/website/branding-theme-test.tsx
- packages/mui-docs/src/branding/brandingTheme.ts
Add custom styles to disabled buttons on branding theme.
| Current | New |
| <img width="713" alt="Screenshot 2024-09-02 at 15 16 04" src="https://github.com/user-attachments/assets/da003864-99eb-4bdd-98d1-97049bc8486c"> | <img width="713" alt="Screenshot 2024-09-02 at 15 16 21" src="https://github.com/user-attachments/assets/6e382314-cfba-4a60-a481-26d242a4e75a"> | 
👉  https://deploy-preview-43577--material-ui.netlify.app/experiments/website/branding-theme-test/
> [website] Add disabled button styles to branding theme

- packages/mui-material/src/utils/memoTheme.ts
Fixes https://github.com/mui/material-ui/issues/43575
> [material] Fix wrong import to type

- docs/data/material/components/autocomplete/GitHubLabel.js
- docs/data/material/components/autocomplete/GitHubLabel.tsx
closes https://github.com/mui/material-ui/issues/43600
> [docs][material-ui][Autocomplete] Fix GitHubLabel demo input background color 

- docs/data/base/components/transitions/transitions.md
- docs/data/joy/components/alert/alert.md
- docs/data/joy/components/css-baseline/css-baseline.md
- docs/data/joy/components/radio-button/radio-button.md
- docs/data/material/components/alert/alert.md
- docs/data/material/components/dialogs/dialogs.md
- docs/data/material/components/rating/rating.md
- docs/data/material/design-resources/material-ui-for-figma/material-ui-for-figma.md
- docs/data/material/migration/migration-v3/migration-v3.md
- docs/data/system/experimental-api/css-theme-variables/css-theme-variables.md
Those went through the reviews. We should prefer to use relative URLs so that once we version the content, those links continue to work. 
I noticed those in #43435.
> [docs] Fix use of absolute URLs

- packages/markdown/parseMarkdown.js
In MUI X, we often have links in the header marking the Plan.
It turns out, the anchor button doesn't work if the header contains a link – see https://deploy-preview-14443--material-ui-x.netlify.app/x/react-data-grid/#commercial-licenses
This PR fixes the issue.
> [docs-infra] Fix broken anchor button when header has a link

- docs/src/modules/sandbox/CodeSandbox.ts
**Before**:
It opens a devbox experience. The loading time is longer than the embed version. It takes ~12sec to see the demo.
Note that the devbox cannot be open with an initial file.
https://github.com/user-attachments/assets/d95f88d9-1b43-444a-8094-d3b2861a29ee
**After**:
The embed version is editable and feels faster. It takes ~4sec to see the demo. By changing to embed mode, we can target the initial file to open.
https://github.com/user-attachments/assets/6c5f58ed-4e0f-489f-b588-a633800de1ad
> [docs-infra] Use embed as the default for opening CodeSandbox

- packages/mui-material/src/Dialog/Dialog.js
- packages/mui-material/src/Dialog/Dialog.test.js
- [] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/material-ui/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).
- From my POV I had fix the issue #43572. By Improving its css part.
- Changes made in Line Number:- 121, 196, 201. All Changes are done with their respective comments.
- Kindly @DiegoAndai review my code. And give me a possible feedback to fix it.
Fixes #43572
Fixes #43636
> [material-ui][Dialog] Fix broken scrolling in full screen mode

- docs/data/material/migration/upgrade-to-v6/migrating-to-pigment-css.md
> [docs] Add Next.js font optimization section to Pigment CSS migration

- docs/src/modules/components/AppSearch.js
- docs/src/modules/components/Head.tsx
I imagine we want the search to continue to work on v5, it will help the migration. e.g. it works in https://v2.tailwindcss.com/docs.
> [docs] Restore search on v5

- docs/data/material/customization/css-theme-variables/usage.md
`theme` variable was not used and there was a typo in the example for the basic theme implementation
> [docs][material-ui] Fix getting started with CSS variables in theme example

- packages/mui-material/src/Radio/Radio.js
- test/regressions/fixtures/Radio/RadioDisabledState.js
Fixes https://github.com/mui/material-ui/issues/43588
> [Radio] Fix disabled state styling regression

- examples/material-ui-via-cdn/README.md
https://github.com/mui/material-ui/blob/master/examples/material-ui-via-cdn/README.md preview is broken.
See https://raw.githack.com/faq#diff-between-rawgithack-and-cdn for why this fixes the problem. Since it's only for demo purposes, we don't care about having our demo production ready.
> Requests to CDN are routed through CloudFlare's content delivery network, and are **cached for an year** the first time they're loaded. This results in the best performance and reduces load on raw.githack.com and on underlying service, but it means that reloading won't fetch new changes
It's another follow-up on #42172. The problem got more visible with v6.x release. I noticed this trying some of the examples that we have (since it's a critical part of the user journey, wanted to experience it as a new …
> [examples] Fix CDN live preview demo

- CHANGELOG.old.md
- docs/data/system/experimental-api/css-theme-variables/css-theme-variables.md
- packages/mui-material/src/styles/ThemeProviderWithVars.tsx
Open https://mui.com/system/experimental-api/css-theme-variables/#demo and see the broken link. This was reported in 
https://app.ahrefs.com/site-audit/3524616/data-explorer?columns=pageRating%2Curl%2Ctraffic%2ChttpCode%2CcontentType%2Cdepth%2CincomingAllLinks&current=06-09-2024T022441&filterId=9b88587038fc9bb2e08e0ff143d5f328&issueId=c64d89a6-d0f4-11e7-8ed1-001e67ed4656&sorting=-pageRating
---
As a side note, I believe that we should move 80% of what's inside this `mui-material/styles` folder into MUI System #40594. The sooner, the better.
> [system][docs] Fix link to createCssVarsProvider

- docs/src/modules/components/AppLayoutDocs.js
A quick-win that I noticed. Opened a PR as seems more efficient than an issue. When running https://chromewebstore.google.com/detail/axe-devtools-web-accessib/lhdoppojpmngadmnindnejefpokejbdd?pli=1 on after scrolling a bit the page on https://mui.com/material-ui/react-button/ or any others. We get this:
which they explain in https://dequeuniversity.com/rules/axe/4.10/region?application=AxeChrome.
Related issue: https://www.drupal.org/project/back_to_top/issues/3254713. I think it matters because we want our component to have no error, so if the docs-infra has one, it creates noise.
Preview: https://deploy-preview-43663--material-ui.netlify.app/material-ui/react-button/
> [docs-infra] Fix axe issue scroll-to-top without landmark

- docs/data/system/styled/styled.md
- add @mui/material to @emotion/babel-plugin config
- add note about @emotion/babel-plugin and babel-plugin-direct-import order
Proof that it works: https://stackblitz.com/edit/vitejs-vite-t82o8s?file=vite.config.ts,src%2FApp.tsx&terminal=dev
> [docs][material-ui][system] Edit "How to use components selector API" section to add about direct import

- docs/data/material/integrations/nextjs/nextjs.md
> [docs][material-ui] Update Next.js font optimization guide

- docs/data/material/integrations/nextjs/nextjs.md
> [material-ui][docs] Update @mui/material-nextjs import examples to v14

- docs/src/modules/components/ApiPage/list/ExpandableApiItem.tsx
The change in #43292 breaks the search experience on the API pages that have the "View: Expanded" default layout, for example https://mui.com/x/api/data-grid/data-grid-pro/. Algolia returns URLs with the React useId, e.g. https://mui.com/x/api/data-grid/data-grid/#:R86ml5l6kud6:. I believe this will fix it.
Preview: https://deploy-preview-43662--material-ui.netlify.app/material-ui/api/button/#button-prop-color
> [docs-infra] Fix API search link regression

- docs/pages/experiments/docs/DemoMultiTabs.js
- docs/src/modules/sandbox/Dependencies.ts
Fixes https://github.com/mui/mui-x/pull/13695#issuecomment-2338738327
When multi-tab demos are opened in Stackblitz/Codesandbox, we need to extract imported dependencies from all the files, not only the main ones.
Before: https://deploy-preview-43696--material-ui-apps.netlify.app/experiments/docs/demos/#multiple-tabs-demo
After: https://deploy-preview-43713--material-ui-apps.netlify.app/experiments/docs/demos/#multiple-tabs-demo
> [docs-infra] Fix missing dependencies in multi-tab demos

- docs/data/material/experimental-api/pigment-css/pigment-css.md
- docs/data/material/migration/upgrade-to-v6/migrating-to-pigment-css.md
Add a callout in the "Getting started with Pigment CSS" and "Migrating to Pigment CSS" docs pages to clarify which phase Pigment CSS is in.
Preview:
- https://deploy-preview-43725--material-ui.netlify.app/material-ui/experimental-api/pigment-css/
- https://deploy-preview-43725--material-ui.netlify.app/material-ui/migration/migrating-to-pigment-css/
> [pigment-css][docs] Call out Pigment being in alpha

- packages/mui-material/src/Backdrop/Backdrop.js
- packages/mui-material/src/FormControl/FormControl.js
- packages/mui-material/src/Hidden/withWidth.js
- packages/mui-material/src/InputBase/InputBase.js
- packages/mui-material/src/InputBase/InputBase.test.js
- packages/mui-material/src/Popover/Popover.js
- packages/mui-material/src/Select/SelectInput.js
- packages/mui-material/src/Snackbar/Snackbar.test.js
- packages/mui-material/src/SwipeableDrawer/SwipeableDrawer.js
- packages/mui-material/src/Tooltip/Tooltip.js
- packages/mui-material/src/styles/useTheme.js
- packages/mui-material/src/usePagination/usePagination.test.js
- packages/mui-material/src/useScrollTrigger/useScrollTrigger.js
Part of #42564 
Sorry for being late to contribute. 
I changed the codes in these files to remove errors - 
- packages/mui-material/src/Backdrop/Backdrop.js
- packages/mui-material/src/usePagination/usePagination.test.js
- packages/mui-material/src/FormControl/FormControl.js
While rest of them I put eslint disable comments. Either difficult to change or could break something.
For this package there was two changes didn't realize that the change caused test to not work so undid the changes and added disabled comments
- packages/mui-material/src/useScrollTrigger/useScrollTrigger.js
> [core] Fix some issues reported by eslint-plugin-react-compiler

- packages-internal/test-utils/src/createRenderer.tsx
Improve the extensibility of the `useFakeTimers` function by allowing override of all options.
This might be most useful in providing a `toFake` ([doc](https://github.com/sinonjs/fake-timers?tab=readme-ov-file#var-clock--faketimersinstallconfig:~:text=specified%20unix%20epoch-,config.toFake,-String%5B%5D)) option to limit what is mocked.
> [code-infra] Allow overriding all `options` of `useFakeTimers` function

- docs/src/modules/components/DemoToolbar.js
The problem:
https://github.com/user-attachments/assets/b409c7ed-f8b4-42d1-9691-a00f8fe8b221
Source: https://deploy-preview-477--base-ui.netlify.app/base-ui/react-field/#labeling-and-descriptive-help-text. I broke this in #40832. It's a quick win, so I thought I might open a PR, faster than open an issue. The logic itself could likely be improved using Base UI components, but for now, we use what https://github.com/eps1lon setup.
@vladmoroz since you will help with the docs, I thought I would give you an easy PR to review, to give a bit of an introduction of the docs-infra that we have 😄
Preview: https://deploy-preview-43627--material-ui.netlify.app/material-ui/react-button/#basic-button
> [docs-infra] Fix toolbar arrow order

- packages/mui-material/src/Skeleton/Skeleton.js
closes #43611
The animation wrapped in `css` is used within an object. This is not allowed:
```js
style: {
'&::after': css`
animation: ${keyframe} …
`,
}
```
The fix is to move the `&::after` inside the `css`:
```js
const waveAnimation = css`
&::after {
animation: ${keyframe} …
}
`
style: waveAnimation
```
Note: I check the rest of the components that has animation, all of them are using the right approach.
> [Skeleton] Fix wave animation for styled-components

- packages/mui-material/src/Grid/Grid.d.ts
- packages/mui-material/src/index.d.ts
Fixes https://github.com/mui/material-ui/issues/43686.
This was an oversight of https://github.com/mui/material-ui/pull/43054. This only brings back the types requested in [the issue](https://github.com/mui/material-ui/issues/43686), as there are some naming conflicts between the `Grid` and `Grid2` other types exports (`GridDirection`, `GridSpacing`, `GridWrap` and `GridSize`), so adding those back would be opening a bigger can of worms. Hopefully, no one is using them, but if someone is and opens an issue, we can discuss possible solutions then.
> [material-ui] Bring back `GridProps` and `GridTypeMap`

- docs/data/material/components/slider/MusicPlayerSlider.js
- docs/data/material/components/slider/MusicPlayerSlider.tsx
- test/regressions/TestViewer.js
Follow up on https://github.com/mui/material-ui/pull/43656#discussion_r1758560024
> [test] Remove position:relative from regression container

- docs/data/joy/components/radio-button/ExampleAlignmentButtons.js
- docs/data/joy/components/radio-button/ExampleAlignmentButtons.tsx
- docs/data/joy/components/toggle-button-group/ToggleGroupToolbar.js
- docs/data/joy/components/toggle-button-group/ToggleGroupToolbar.tsx
- docs/data/material/components/dividers/FlexDivider.js
- docs/data/material/components/dividers/FlexDivider.tsx
Follow up on https://github.com/mui/material-ui/pull/43656#issuecomment-2348446752
Some demos were using `flex` instead of `inline-flex` in their top-level elements, causing them to look off when rendered inside a `block` element instead of a `flex` element. For context, our demo wrapper uses `flex` but our visual regression wrapper uses `block` since https://github.com/mui/material-ui/pull/43656.
> [test][docs] Improve demos for better regression screenshots

- docs/data/material/migration/migrating-from-deprecated-apis/migrating-from-deprecated-apis.md
- docs/data/material/migration/upgrade-to-v6/upgrade-to-v6.md
Resolves https://github.com/mui/material-ui/issues/43589
We documented the deprecation of system props in the v6 upgrade guide: https://mui.com/material-ui/migration/migrating-from-deprecated-apis/#system-props. But we introduced a breaking change in the `color` prop of the `Typography` component: it's not a system prop anymore, and thus it doesn't support callbacks to access the theme, responsive values, etc.
This PR documents the breaking change.
> [material-ui][docs] Document Typography color prop breaking change

- docs/data/material/components/slider/slider.md
A quick polish on #43743. I thought this would look better and be denser, using less vertical space:
Before
After
This docs option is not used so often on Material UI. We use it a lot with the MUI X Data Grid though, e.g. https://mui.com/x/react-data-grid/#mit-license-free-forever
> [slider][docs] Polish Music player demo

- docs/data/material/discover-more/related-projects/related-projects.md
It looks like this was broken in https://github.com/siriwatknp/mui-treasury/pull/1229.
> [docs] Fix MUI Treasury Layout broken links

- docs/data/material/components/table/table.md
Closes https://github.com/mui/material-ui/issues/42836
> [docs][material-ui] Add docs for complementary Table components

- test/regressions/index.js
Attempt at stabilizing the icons test. It looks like the referenced css has gone out of sync with the regression tests font loader.
Let's see if this does the trick.
Potentially closes https://github.com/mui/material-ui/pull/43684
> [test] Update font-awesome CSS file in regression tests fixture

- packages/mui-system/src/useMediaQuery/useMediaQuery.ts
- packages/mui-utils/src/useId/useId.test.js
- packages/mui-utils/src/useId/useId.ts
> [utils] Fix "useId" & "useSyncExternalStore" imports to not be statically analysable

- packages/mui-material/src/Modal/Modal.js
- packages/mui-material/src/Modal/Modal.test.js
closes https://github.com/mui/material-ui/issues/43738
regression was introduced in this PR https://github.com/mui/material-ui/pull/42150 (by me 😑)
> [material-ui][Modal] Fix event handlers overriding behaviour

- packages/mui-codemod/src/v6.0.0/grid-v2-props/grid-v2-props.js
- packages/mui-codemod/src/v6.0.0/grid-v2-props/test-cases/actual.js
- packages/mui-codemod/src/v6.0.0/grid-v2-props/test-cases/expected.js
closes https://github.com/mui/material-ui/issues/43621
> [Grid2] Add removal of item prop to grid-v2-props codemod

- packages/rsc-builder/buildRsc.ts
Fix https://github.com/mui/material-ui/pull/41956#discussion_r1752127870.
If from a server component, we import a hook, then different behaviors can happen:
- Next.js v15.0.0-rc.0
- hook with "use client" 🔴 (seems to be a recent regression) <img width="441" alt="SCR-20240915-czvu" src="https://github.com/user-attachments/assets/b9f48cac-0617-479f-ba82-9d017ea39a45">
- hook without "use client" 🟡 <img width="437" alt="SCR-20240915-daas" src="https://github.com/user-attachments/assets/d955e777-a1eb-4509-be77-ec7933e5ac60">
- Next.js (turbo pack) v15.0.0-rc.0
- hook with "use client" 🟢 <img width="445" alt="SCR-20240915-czqh" src="https://github.com/user-attachments/assets/3cf75933-fd90-4ba8-9292-79ed1b68b8ae">
- hook without "use client" 🟡 <img width="489" alt="SCR-20240915-cnjt" …
> [core] useAutocomplete should have 'use client'

- docs/data/joy/components/autocomplete/autocomplete.md
- docs/data/material/components/autocomplete/autocomplete.md
- docs/data/material/components/menus/menus.md
- docs/data/material/components/slider/slider.md
- packages-internal/test-utils/src/focusVisible.ts
- packages/mui-base/src/FocusTrap/FocusTrap.tsx
- packages/mui-base/src/Slider/Slider.test.tsx
- packages/mui-codemod/src/v6.0.0/styled/test-cases/ObjectMap.actual.js
- packages/mui-codemod/src/v6.0.0/styled/test-cases/ObjectMap.expected.js
- packages/mui-material/src/Icon/Icon.js
- packages/mui-material/src/Unstable_TrapFocus/FocusTrap.tsx
See https://www.chromium.org/for-testers/faq/ for what happened.
I have noticed this while I was browsing the docs and curious about what a Chromium bug about text ellipse with flexbox was about. A quick win.
> [docs] Fix 301 to chromium

- packages-internal/test-utils/src/reactMajor.ts
Match the rest of the codebase https://github.com/search?q=org%3Amui%20React.version&type=code. Seen in https://github.com/mui/material-ui/pull/43022#discussion_r1766689082.
> [test] Sync React.version parse logic with codebase

- packages/mui-material/src/Modal/ModalManager.ts
- packages/mui-utils/src/getScrollbarSize/getScrollbarSize.ts
Closes #43244
[preview](https://deploy-preview-43818--material-ui.netlify.app/material-ui/react-drawer/#responsive-drawer)
> [material-ui][Drawer] Fix issue with main window being used instead of iframe's window

- test/regressions/index.test.js
- test/regressions/template.html
Been debugging the flakyness of the dashboard screenshot. After throttling the playwright browser, it becomes apparent there is a horizontal layout shift while running the test:
https://github.com/user-attachments/assets/793e9a3e-4473-469a-9eff-5677fbdc0bd2
This shift doesn't happen when just visiting the page. Debugging further reveals that it is caused by the `page.screenshot` call. Apparently, playwright [hides scrollbars](https://github.com/microsoft/playwright/issues/30228) when taking the screenshot. It looks like there's a race condition between the responsive charts reacting to a width change and playwright capturing the page. This causes a flaky screenshot.
~It looks like we can remedy this by always hiding scrollbars, through the `--hide-scrollbars` flag.~
This causes every …
> [code-infra] Fix flaky dashboard screenshot

- packages/mui-base/src/Badge/Badge.types.ts
- packages/mui-base/src/Input/Input.types.ts
- packages/mui-base/src/MenuItem/MenuItem.types.ts
- packages/mui-base/src/Option/Option.types.ts
- packages/mui-base/src/OptionGroup/OptionGroup.types.ts
- packages/mui-base/src/Snackbar/Snackbar.types.ts
- packages/mui-base/src/Tab/Tab.types.ts
- packages/mui-base/src/useButton/useButton.types.ts
- packages/mui-base/src/useList/useList.types.ts
- packages/mui-base/src/useMenu/useMenu.types.ts
- packages/mui-base/src/useMenuItem/useMenuItem.types.ts
- packages/mui-base/src/useSelect/useSelect.types.ts
- packages/mui-base/src/useSlider/useSlider.types.ts
- packages/mui-base/src/useSwitch/useSwitch.types.ts
- packages/mui-base/src/useTab/useTab.types.ts
- packages/mui-base/src/useTabsList/useTabsList.types.ts
- packages/mui-lab/src/Timeline/Timeline.tsx
- packages/mui-utils/src/elementAcceptingRef/elementAcceptingRef.test.tsx
- packages/mui-utils/src/elementTypeAcceptingRef/elementTypeAcceptingRef.test.tsx
- pnpm-lock.yaml
Attempt at addressing issues in https://github.com/mui/material-ui/pull/43555
It seems to me like this should be optional, but I'm not quite sure if I'm creating some 2nd order effects. Putting it up on a separate PR for review.
> Make ref optional in @mui/base

- packages/mui-material/src/Button/Button.js
closes #43810
**Before**: https://stackblitz.com/edit/react-shtebo
**After**: https://codesandbox.io/p/sandbox/material-ui-cra-ts-forked-v3fqhn?file=%2Fsrc%2FApp.tsx%3A57%2C4
> [Button] ignore `dark` and `contrastText` if not provided in the theme

- packages/mui-material/src/Modal/ModalManager.ts
While reviewing a PR I noticed the parameter name `show` is confusing because `aria-hidden` should be set to true when `hide` is true, hiding the element from the accessibility tree. This PR renames the parameter from `show` to `hide` for clarity.
> [material-ui][Modal] Replace `show` parameter name with `hide` in modal manager

- docs/src/modules/sandbox/CodeSandbox.ts
The default font-size is too big
**Before**:
https://codesandbox.io/embed/gggjjd?module=/MarketingPage.tsx
**After**:
> [docs-infra] Open Codesandbox demo with fontsize=12

- docs/data/material/getting-started/templates/dashboard/Dashboard.js
- docs/data/material/getting-started/templates/dashboard/Dashboard.tsx
There is so much space for the footer in https://deploy-preview-43604--material-ui.netlify.app/material-ui/getting-started/templates/dashboard/, it's weird.
Preview: https://deploy-preview-43836--material-ui.netlify.app/material-ui/getting-started/templates/dashboard/
An iteration on #41469.
> [docs] Fix visual bug on dashboard template

- test/README.md
I was browisng through test ReadMe, found istanbul package url is wrong
previous url: https://istanbul-js.org (Site not found)
updated url: https://istanbul.js.org
Opened same PR in base-ui repo as well: https://github.com/mui/base-ui/pull/657
> [test] Point Istanbul to correct URL

- test/regressions/TestViewer.js
- test/regressions/index.js
- test/regressions/index.test.js
* Remove the need for 1300+ links to be rendered in the DOM while running regression tests
* Make it possible to scope a single test in running `test:regressions`. Just add `route = ['<path>']` at https://github.com/Janpot/material-ui/blob/632de3d7de97eadb3cc225aca5a3e3a4ba25fb10/test/regressions/index.test.js#L51
* Remove the links during running the tests (only render them once on initial render to determine which tests to run)
Results:
* On my local, about ~15s decrease in runtime (~11%)
* Gained possibility to scope one or more tests in the production run, very helpful for debugging https://github.com/mui/material-ui/pull/43890
> [code-infra] Optimize regression tests

- docs/data/material/components/material-icons/SearchIcons.js
Before
After
Not a big difference ~7% saving, but it helps, the page is big. This is flagged in https://app.ahrefs.com/site-audit/3992793/data-explorer?columns=pageRating%2Curl%2Ctraffic%2ChttpCode%2Csize%2CtimeToFirstByte%2CloadingTime%2Cdepth%2Ccompliant%2CincomingAllLinks%2Corigin&current=27-09-2024T024913&filterId=709f929d4b01712e0ab256af7bad8fea&issueId=c64da874-d0f4-11e7-8ed1-001e67ed4656&sorting=-pageRating. Since we compet for SEO for this page, it makes sense to me, it's a quick-win.
Preview https://deploy-preview-43911--material-ui.netlify.app/material-ui/material-icons/
> [icons] Reduce Material Icon page size

- .circleci/config.yml
- apps/pigment-css-vite-app/src/pages/fixtures/index.test.js
- test/regressions/index.test.js
- test/regressions/template.html
Still seeing flakyness after https://github.com/mui/material-ui/pull/43890. I could reproduce locally after switching the scrollbar visibility setting on my laptop. Just disabling overflow on the body seems to fix it reliably for any of the settings. There is now also a noticable difference in all screenshots of elements that overflow. Looks like this change is an improvement for those screenshots as well.
Doing the same for pigment regression tests.
Make sure to check out the [changed screenshots](https://app.argos-ci.com/mui/material-ui/builds/32503/111246087)
> [code-infra] Fix flaky dashboard screenshot - take 2

- docs/data/material/customization/shadow-dom/shadow-dom.md
- packages/mui-material/src/styles/createGetSelector.ts
- packages/mui-material/src/styles/createTheme.spec.ts
- packages/mui-material/src/styles/createTheme.ts
- packages/mui-material/src/styles/createThemeNoVars.d.ts
- packages/mui-material/src/styles/createThemeWithVars.d.ts
- packages/mui-material/src/styles/createThemeWithVars.js
- packages/mui-material/src/styles/extendTheme.test.js
- packages/mui-material/src/styles/shouldSkipGeneratingVar.ts
closes #43886 
**preview**: https://deploy-preview-43948--material-ui.netlify.app/material-ui/customization/shadow-dom/#3-css-theme-variables-optional
add new `rootSelector` field to the `cssVariables` config:
```diff
createTheme({
cssVariables: {
+    rootSelector: ':host',
},
})
```
**before**: https://codesandbox.io/p/sandbox/shadow-dom-forked-s6w62q?workspaceId=2128292f-fbb6-4239-87e8-fa24491716c6
**after**: https://codesandbox.io/p/sandbox/material-ui-cra-ts-forked-kdw59g?file=%2Fsrc%2Findex.tsx%3A22%2C30
> [material-ui] Support CSS variables with shadow DOM

- packages/mui-material/src/usePagination/usePagination.test.js
Fixed eslint issue with usePagination.test.js file by using React.useEffect hook to update hook after execution, error: Writing to a variable defined outside a component or hook is not allowed. Consider using an effecteslint(react-compiler/react-compiler).
Ran the test file and had 16 tests passed, so should work :) 
Fix for the  packages/mui-material/src/usePagination/usePagination.test.js file which the box was unchecked from issue #42564 , where issue #43117 still contained the eslint error.
> [core] Fix eslint-plugin-react-compiler issues in usePagination tests

- docs/data/material/getting-started/supported-platforms/supported-platforms.md
Working on resurrecting the bundling tests and noticed webpack 4 doesn't work anymore since latest browserslist update. 
Same as https://mui.com/x/migration/migration-charts-v6/#drop-webpack-4-support
> [docs] Add note about minimum required webpack version

- docs/data/material/customization/dark-mode/dark-mode.md
- packages/mui-material/src/styles/ThemeProvider.test.tsx
- packages/mui-material/src/styles/ThemeProvider.tsx
- packages/mui-system/src/cssVars/createCssVarsProvider.d.ts
- packages/mui-system/src/cssVars/createCssVarsProvider.js
closes #43622
The default mode can be controlled by a prop (see https://github.com/mui/material-ui/issues/43622 for use cases):
```js
<ThemeProvider defaultMode="dark | light | system">
```
> [ThemeProvider] Support setting default mode

- docs/data/material/customization/dark-mode/ToggleColorMode.js
- docs/data/material/customization/dark-mode/ToggleColorMode.tsx
Use radio buttons instead of select. Just to reduce the amount of clicks needed to operate the demo.
This was bugging me when writing a reproduction for https://github.com/mui/material-ui/issues/43952
Preview https://deploy-preview-43956--material-ui.netlify.app/material-ui/customization/dark-mode/#toggling-color-mode
> [docs] Update theme toggle demo

- apps/pigment-css-vite-app/src/pages/material-ui/react-progress.tsx
The CSS animations are disabled by playwright while taking the screenshot, but there is this one demo that animates the progressbar `value` property with Javascript. This sometimes results in flaky screenshots. Example: https://app.argos-ci.com/mui/material-ui/builds/32548/111399290
We could just remove this demo to solve the issue. 
Alternatives are:
* Mock `setTimeout`, but this seems to break too many other things
* Add a compile time flag in the demo to turn off animation
* Write a new test case specifically for the integration test
> [test] Fix flaky pigment-css screenshot

- CHANGELOG.md
Address comments from https://github.com/mui/material-ui/pull/43957#discussion_r1784746308
I'll update https://github.com/mui/material-ui/releases/tag/v6.1.2 once this is merged.
> [core] Amend changelog

- .eslintignore
- .eslintrc.js
- docs/src/modules/components/ApiPage/definitions/classes.ts
- packages-internal/test-utils/src/createRenderer.tsx
Noticed in https://github.com/mui/material-ui/pull/43904 that the error minification macro checks for this, but it would be better served by an eslint rule, so that more of our code base is covered.
Also removing an unused ignore line.
> [code-infra] Forbid calling `Error` without `new`

- docs/pages/experiments/docs/headers.md
- packages/markdown/parseMarkdown.js
I'm not sure when this got broken, but it's definitely a regression. I saw this in https://mui.com/legal/ while trying to make a quick PR https://github.com/mui/mui-private/pull/605.
- wrong spacing:
- wrong header label:
Preview: https://deploy-preview-43834--material-ui.netlify.app/experiments/docs/headers/
> [docs-infra] Fix link in header regression

- packages/eslint-plugin-material-ui/src/rules/disallow-active-elements-as-key-event-target.test.js
- packages/mui-material/src/Dialog/Dialog.test.js
`Esc` is legacy, e.g. https://github.com/facebook/react/blob/99c056abb0dac0e1a15b2c85b620b72c625e065b/packages/react-dom-bindings/src/events/SyntheticEvent.js#L313
> [test] Fix Escape event firing event

- docs/data/material/components/grid2/grid2.md
As reported in https://mui-org.slack.com/archives/C0757QYLK7V/p1727810980001529
> [docs][Grid] Fix Grid2 gap description

- packages/mui-system/src/createTheme/createTheme.d.ts
fix for #43855 to allow typescript module augmentation
> [system] Add empty interfaces to fix issue with typescript module augmentation 

- docs/src/modules/components/TemplateFrame.js
- docs/src/modules/utils/helpers.ts
Match with?
A continuation of #43604
Preview: https://deploy-preview-43835--material-ui.netlify.app/material-ui/getting-started/templates/dashboard/
> [docs] Fix Live edit copies

- docs/data/material/migration/migrating-from-deprecated-apis/migrating-from-deprecated-apis.md
The deprecation note about the `TextField` `FormHelperTextProps` is incorrect. It says to change to `slotProps.formHelper`, but it should be `slotProps.formHelperText` according to the [component documentation](https://mui.com/material-ui/api/text-field/#slots), [source code](https://github.com/mui/material-ui/blob/95fd6b5c97aca84f1f8b02bfeefddf4a55baea5c/packages/mui-material/src/TextField/TextField.js#L144-L151) and [codemod](https://github.com/mui/material-ui/blob/95fd6b5c97aca84f1f8b02bfeefddf4a55baea5c/packages/mui-codemod/src/deprecations/text-field-props/text-field-props.js#L40-L45).
> [docs][material-ui] Fix incorrect `slotProp` name in the `TextField` deprecation note.

- docs/data/material/components/material-icons/SearchIcons.js
See the time it takes to see the input updated with the search term "a". I have used this as a way to measure Time To Interactive.
Before: 6.2s https://deploy-preview-44000--material-ui.netlify.app/material-ui/material-icons/?query=a
After: 1.9s https://deploy-preview-44001--material-ui.netlify.app/material-ui/material-icons/?query=a
Help with #41126
With all the changes that we did, we are closer to the kind of performance that we had in https://v4.mui.com/components/material-icons/. We are not at v4 level yet (1.4s), but at least, it's not horrible like it was before (not sure where all the regressions on the icons page came from).
> [icons][docs] Index search synchronously

- docs/data/base/components/modal/UseModal.js
- docs/data/base/components/modal/UseModal.tsx
- packages/mui-base/src/Modal/Modal.tsx
- packages/mui-base/src/unstable_useModal/useModal.ts
- packages/mui-joy/src/Drawer/Drawer.tsx
- packages/mui-joy/src/Modal/Modal.tsx
- packages/mui-material/src/Modal/Modal.js
- packages/mui-material/src/Modal/useModal.ts
I was reading the source and saw this strange comment. It looks like this was lost during a code refactoring.
> [modal] Fix comment location

- packages/mui-system/src/styleFunctionSx/styleFunctionSx.d.ts
It does not make sense for CSS Properties to have value as `SystemStyleObject` like this:
```js
{
color: {
'&.selector': {
…
}
}
}
```
This might be a slightly typescript per improvement and it won't have any affect on the consumer side because the `sx` prop currently support nesting object with any keys (due to CSS selector)
---
> [typescript] `SystemCSSProperties` should not have `SystemStyleObject` as value

- packages/mui-material/src/Grid2/Grid2.tsx
Noticed warnings when running the docs
```
Warning: Failed prop type: The prop `size` of `Grid2` can only be used together with the `item` prop.
```
> [Grid2] Remove required `item` prop for `size` prop

- docs/data/material/components/material-icons/material-icons.md
- packages/mui-icons-material/README.md
I see two problems:
- Material Symbols is not an "alternative", it's the successor. Material Icons are deprecated: https://github.com/mui/material-ui/issues/32846#issuecomment-2296974762.
- As a user, I was confused reading "no plans", the thought I caught myself with: "How can there be no plans? Icons are outdated and have been stale for 2+ years. Surely, they plan to eventually support symbols."
It also looks like icons have no specific product owner: https://www.notion.so/mui-org/Icons-7ff27203df124147850ec3e26d04d517 so I imagine it's Material UI product owner defacto.
> [docs] Update Material Symbols plan to reflect Google development

- packages/mui-material-nextjs/package.json
- pnpm-lock.yaml
Noticed this morning that we had two Next.js versions in node_module (has been fixed by renovatebot now). This was caused by having all but one specifier marked with `^` and a lockfile maintenance cycle updating all but this one.
> [code-infra] Align `next` dependency specifier across project

- packages/mui-utils/src/getReactElementRef/getReactElementRef.test.tsx
- packages/mui-utils/src/getReactElementRef/getReactElementRef.ts
Extracted from https://github.com/mui/material-ui/pull/42824
> [utils] Make getReactElementRef React 19 compatible

- docs/data/material/components/toggle-button/StandaloneToggleButton.js
- docs/data/material/components/toggle-button/StandaloneToggleButton.tsx
- docs/data/material/components/toggle-button/StandaloneToggleButton.tsx.preview
- Fixes: https://github.com/mui/material-ui/issues/43986
> [docs][material-ui] Fix #43986: Incorrect React useState Example on Toggle Button

- packages/mui-base/src/Menu/Menu.test.tsx
- packages/mui-joy/src/MenuItem/MenuItem.test.tsx
Same as https://github.com/mui/base-ui/pull/706
> [test] Add missing async

- packages/mui-lab/src/Timeline/Timeline.tsx
- packages/mui-lab/src/Timeline/Timeline.types.ts
Extracted from https://github.com/mui/material-ui/pull/42824 to fix the following TS error in the `Timeline` component when using React 19 types:
> [lab][Timeline] Fix types for React 19

- packages/mui-material/src/styles/createPalette.js
- packages/mui-material/src/styles/createPalette.test.js
- packages/mui-material/src/styles/createTheme.test.js
The issue popup in #43708 when there are multiple calls from `createTheme`.
The root cause comes from the `palette.background` is not being recreated every time that the `createPalette` is called,
so if `palette.background.*` is mutated, it affect all of the instances.
The fix is to wrap the `light` and `dark` object in a function and call them inside the `createPalette`. Tests added.
---
> [material-ui] Make the palette always return new light and dark object

- CHANGELOG.md
- CHANGELOG.old.md
- scripts/releaseChangelog.mjs
This was added in https://github.com/mui/material-ui/pull/24614, I never understood the use case. In the latest releases https://github.com/mui/material-ui/issues?q=label%3Arelease+is%3Aclosed some remove them, some keep them. So it feels like we should drop this, it adds so much noise during the release PR review.
I'm also not sure about why we should sort alphabetically when we could use tag grouping. The rational we used was:
> Release are ordered in time so we might as well keep the order inside a release
but I'm not following why this is important. As a user, I care more about per component changes.
> [core] Remove <-- from changelog

- packages-internal/test-utils/src/mochaHooks.js
We don't use `ReactDOM.render` anymore anywhere.
> [test] Remove dead code

- .circleci/config.yml
See https://github.com/mui/material-ui/pull/44056#issuecomment-2405786299
> [code-infra] Disable cron job for React 17 tests

- packages/mui-material/src/styles/createPalette.js
Seen in https://github.com/mui/material-ui/pull/44059#discussion_r1797497864. The goal is to reduce the memory pressure.
> [core] Simplify createPalette

- CHANGELOG.md
- CHANGELOG.old.md
- scripts/releaseChangelog.mjs
Reading through https://github.com/mui/material-ui/pull/43957#discussion_r1782801456. It seems that this change can make sense, most of the time, website changes are noise;
I imagine that website changes are not something that developers should be concerned about. Long term, we would likely move pages out of this repository https://www.notion.so/mui-org/docs-infra-Marketing-site-code-location-70fa836aeb654e2eb429721706529e1d. 
Here is the difference of behavior with `pnpm release:changelog`.
Before
After
> [core] Remove [website] from changelog

- packages/mui-material/src/Checkbox/Checkbox.js
- packages/mui-material/src/Checkbox/Checkbox.test.js
closes #44063
Regression from https://github.com/mui/material-ui/pull/42001/files#diff-6de058f6e3971a3e878e9aae5dd64fb347e1a8de3f9f3964fd33b28e6ebe6370R130
Tests added (same pattern as the Button ripple tests).
> [Checkbox] Fix disableRipple regression

- dangerFileContent.ts
Saw this in #44075. We should be able to change hosting without breaking all the link history (when checking old PRs).
> [code-infra] Link to production app for bundle size

- CHANGELOG.md
- package.json
- packages-internal/babel-plugin-minify-errors/package.json
- packages-internal/scripts/package.json
- packages-internal/test-utils/package.json
- packages/markdown/package.json
- packages/mui-base/package.json
- packages/mui-codemod/package.json
- packages/mui-core-downloads-tracker/package.json
- packages/mui-docs/package.json
- packages/mui-icons-material/package.json
- packages/mui-lab/package.json
- packages/mui-material-nextjs/package.json
- packages/mui-material-pigment-css/package.json
- packages/mui-material/package.json
- packages/mui-private-theming/package.json
- packages/mui-styled-engine-sc/package.json
- packages/mui-styled-engine/package.json
- packages/mui-styles/package.json
- packages/mui-system/package.json
- packages/mui-utils/package.json
- pnpm-lock.yaml
Release v6.1.4
Fixes https://github.com/mui/material-ui/issues/44096 by releasing an updated `@mui/base` version.
> [release] v6.1.4

- docs/data/material/components/material-icons/synonyms.js
I noticed this quickly while working on https://github.com/mui/material-ui/issues/33746#issuecomment-2396709287. This should help tackle: #32846 (we would likely need to do this change anyway).
This is committing the output of `pnpm docs:mdicons:synonyms`.
> [docs][icons] Run pnpm docs:mdicons:synonyms

- scripts/releaseChangelog.mjs
I occasionally, or quite frequently, push commits on the master branch of Material UI, Base UI, MUI X, Pigment CSS, etc. anytime I see a change that:
- a. Has no knowledge-sharing needs, not much room to delegate it, or at least it doesn't feel like the added latency in the PR review time. I don't want to overwhelm the PR review capacity of the team, when it feels like it would overload it.
- b. Is trivial, no much value is having a second pair of eyes.
- c. Is safe, no much value in running the CI against it.
(I get this balance wrong sometimes, I should likely be more moderate with this). In any case, there are use cases, I think ones that could be open to more team members.
Here is the value of this change, better DX for developers in the GitHub release page:
```diff
- [code-infra] …
```
> [core] Reference commits in changelog when no PR

- docs/data/joy/getting-started/overview/overview.md
- update copy in the warning callout to match the text in the readme
- remove link to outdated blog post
- remove line in the description about being production-ready
> [docs][joy-ui] Update Overview copy to match Readme

- docs/data/material/customization/dark-mode/dark-mode.md
- packages/mui-system/src/InitColorSchemeScript/InitColorSchemeScript.tsx
closes #43972 
`InitColorSchemeScript` has a hard-coded default mode as `system` when the user first visit to the site, however this contradict the flow if the project has `<ThemeProvider defaultMode="light">` on user's dark environment.
- Add `defaultMode` to `InitColorSchemeScript`.
- Update docs to make sure that both places are defined for custom `defaultMode`.
---
> [system] Add `defaultMode` to `InitColorSchemeScript`

- packages/mui-material/src/styles/createTheme.test.js
- packages/mui-material/src/styles/createThemeNoVars.js
closes #43750
The `.toRuntimeSource` is required in the theme for some components that access runtime theme's transitions (e.g. Slide) but the property only exist when using CSS theme variables.
Pigment CSS should work with any theme, so the fix is to also add the property to the theme when CSS variables is not enabled.
---
> [material-ui][pigment-css] Support project without enabling CSS variables

- .eslintrc.js
- docs/data/base/components/modal/UseModal.js
- packages-internal/scripts/typescript-to-proptypes/src/generatePropTypes.ts
- packages-internal/scripts/typescript-to-proptypes/test/generator/html-elements/output.js
Widen javascript/typescript rules to all possible extensions. Avoids situations like https://github.com/mui/material-ui/pull/44143#discussion_r1804939744
Question for @mui/docs-infra: what with `material-ui/no-hardcoded-labels`, it applies only to js files and in many ts files there are violations. Should we fix those cases? Or remove the rule altogether?
> [code-infra] Widen eslint file patterns

- docs/pages/material-ui/api/dialog.json
- docs/translations/api-docs/dialog/dialog.json
- packages/mui-material/src/Dialog/Dialog.d.ts
- packages/mui-material/src/Dialog/Dialog.js
- packages/mui-material/src/Dialog/Dialog.test.js
The Dialog component is implemented as a modal dialog, but it was missing the aria-modal="true". This PR adds it by default, but also adds the option for people to remove it if for some reason they need to override it. This makes the component compatible with SC 4.1.2
> [Dialog] Add the aria-modal="true" by default

- examples/material-ui-pigment-css-vite-ts/README.md
I wanted to try Pigment CSS with Vite and this is the error I got. 
This has been broken with [v6.0.0 release](https://github.com/mui/material-ui/releases/tag/v6.0.0), so 6-7 weeks ago. I imagine the Pigment CSS team is responsible for this example.
I'm surprised I'm the first one to work on this. Like, how comes not even community's members faced this? It would mean that nobody uses this example, but then Vite is super popular, so it would mean nobody wants to try Pigment CSS which also doesn't make sense. I'm missing something. Maybe it's that +99% of the people are migrating applications, so nobody can use this example right away, only people who want to create bug reproductions use it today (until it's stable).
---
Side notes:
- The example doesn't work with pnpm (it works with npm): …
> [examples] Fix Pigment CSS Vite example

- packages/mui-system/src/InitColorSchemeScript/InitColorSchemeScript.tsx
> [docs] Follow types description convention

- apps/pigment-css-next-app/src/app/grid/demo3.tsx
- apps/pigment-css-next-app/src/app/grid/page.tsx
- apps/pigment-css-next-app/src/app/stack/page.tsx
- apps/pigment-css-vite-app/src/pages/fixtures/PigmentCssGrid.tsx
- apps/pigment-css-vite-app/src/pages/fixtures/PigmentCssStack.tsx
While reviewing https://github.com/mui/material-ui/issues/44042 I noticed we didn't have tests for these components. This PR adds them.
> [test][material-ui] Add tests for Pigment Grid and Stack

- docs/data/material/pages.ts
The Grid component had a nice deprecated label in the navigation drawer, while Hidden didn't despite being deprecated, so added it :)
Preview: https://deploy-preview-44068--material-ui.netlify.app/material-ui/react-hidden/
> [docs] Mark the Hidden component as deprecated in the sidenav

- docs/pages/material-ui/api/tab-panel.json
- packages/mui-lab/src/TabPanel/TabPanel.d.ts
- packages/mui-lab/src/TabPanel/TabPanel.js
change the value type of `TabPanel` component from `string` to `string | number`
> [material-ui][Tabs] Fix type of TabPanel component

- packages/mui-codemod/src/v6.0.0/system-props/removeSystemProps.js
- packages/mui-codemod/src/v6.0.0/system-props/test-cases/system-props.actual.js
- packages/mui-codemod/src/v6.0.0/system-props/test-cases/system-props.expected.js
closes #43983
The issue is about inconsistent transformation between default import and import specifier.
> [codemod] Fix system props default import specifier

- packages/mui-material/src/AvatarGroup/AvatarGroup.js
Fixes https://github.com/mui/material-ui/issues/44172
How to test
1. Go to https://deploy-preview-44208--material-ui.netlify.app/material-ui/react-avatar/#grouped
2. Change add the `spacing="small"` prop to the `AvatarGroup` component in the demo.
3. The spacing between all avatars now changes accordingly.
> [material-ui][Avatar] Fix AvatarGroup spacing

- packages/mui-utils/src/getReactNodeRef/getReactNodeRef.ts
- packages/mui-utils/src/getReactNodeRef/index.ts
- packages/mui-utils/src/index.ts
Fixes https://github.com/mui/material-ui/issues/44096
`getReactNodeRef` was modified and renamed to `getReactElementRef` in https://github.com/mui/material-ui/pull/43022 which caused issues described in https://github.com/mui/material-ui/issues/44096
> [utils] Bring back getReactNodeRef

- docs/data/material/components/avatars/Spacing.js
- docs/data/material/components/avatars/Spacing.tsx
- docs/data/material/components/avatars/Spacing.tsx.preview
- docs/data/material/components/avatars/avatars.md
We didn't have a spacing demo for the `AvatarGroup` component.
Preview: https://deploy-preview-44209--material-ui.netlify.app/material-ui/react-avatar/#spacing
> [material-ui][Avatar] Add AvatarGroup spacing demo

- packages-internal/test-utils/src/describeConformance.tsx
- packages/mui-material/src/Container/Container.js
- packages/mui-material/src/Grid/Grid.js
- packages/mui-material/src/Grid2/Grid2.tsx
- packages/mui-material/src/NativeSelect/NativeSelect.js
- packages/mui-material/src/Select/Select.js
- packages/mui-material/src/Stack/Stack.js
- packages/mui-material/test/describeConformance.ts
closes #44128
Several components still using `useThemeProps` instead of `useDefaultProps`. That's why using `DefaultPropsProvider` does not work for these components.
> [material-ui] Replace `useThemeProps` with `useDefaultProps`

- docs/pages/material-ui/api/rating.json
- docs/translations/api-docs/rating/rating.json
- packages/mui-material/src/Rating/Rating.d.ts
- packages/mui-material/src/Rating/Rating.js
- packages/mui-material/src/Rating/Rating.spec.tsx
- packages/mui-material/src/Rating/Rating.test.js
This PR adds `component` prop to `Rating` component, check https://github.com/mui/material-ui/pull/44181#issuecomment-2429371210 for the why
> [material-ui][Rating]  Add `component` prop 

- docs/data/material/discover-more/related-projects/related-projects.md
- docs/data/material/getting-started/example-projects/example-projects.md
- docs/pages/blog/mui-core-v5.md
- docs/src/modules/components/MaterialUIExampleCollection.js
part of #40062
To clarify the purpose of each of these pages so there's no confusion or overlap - move "Community Projects" from Example Projects to Related Projects and reorganize the lists accordingly.
Also removed several outdated community projects - those which have not been updated to v5+.
- list official (i.e. maintained by MUI) third-party integrations - minimal scaffolds and boilerplates
- link to (official) free and paid templates
- community developers should not be encouraged to open PRs to link their projects here
- list community-led projects and tools that incorporate or extend Material UI
- community developers can open PRs to link to their projects here
- live projects, products, and apps that use Material UI
> [docs] Revise Example Projects and Related Projects pages

- docs/src/modules/components/ApiPage/table/SlotsTable.tsx
> [docs] Add index to `key` to remove noise from console

- docs/data/material/integrations/nextjs/nextjs.md
- packages/markdown/prepareMarkdown.js
- packages/markdown/prepareMarkdown.test.js
I noticed this in: https://github.com/mui/toolpad/pull/4344/files#r1826369440.
I didn't look at how this can be replicated on the next docs-infra structure, but at least, in the meantime, we will make sure it's done right, less migration effort. I opened https://github.com/mui/toolpad/pull/4351 and https://github.com/mui/mui-x/pull/15229 to make it easier for those repositories to upgrade docs-infra with this PR in.
> [docs-infra] Enforce punctuation on descriptions

- docs/data/material/discover-more/backers/backers.md
Keep the sponsoring docs in sync with: https://www.notion.so/mui-org/sales-Introduce-backlink-sponsor-plan-49e70924423e462aad099df16273c094.
https://opencollective.com/mui-org Gold plan description already reflects this.
> [core] Update Gold sponsoring backlinks

- examples/material-ui-nextjs-pages-router-ts/package.json
- examples/material-ui-nextjs-pages-router/package.json
- examples/material-ui-nextjs-ts-v4-v5-migration/package.json
These examples have a `Link` component that uses `clsx` but the dependency is not defined.
Found while testing https://github.com/mui/material-ui/pull/43264
> [examples] Add missing `clsx` dependency

- docs/data/material/experimental-api/pigment-css/pigment-css.md
Same as https://github.com/mui/pigment-css/pull/292. There is no `next` tag on 
- https://www.npmjs.com/package/@pigment-css/react?activeTab=versions
- https://www.npmjs.com/package/@pigment-css/vite-plugin?activeTab=versions
so for sure it won't work.
---
A general rule of thumb I follow all the time:
1. Setup VS Code to have all the MUI org's codebase
2. Search the codebase for similar problems
I'm not super confident about those probabilities, but it feels like this: 90% of the time community contributor PR's authors don't do this. And 30% of the time we fix only part of the issue because if we did, we would have found more. So I now systematically do it, so I think it's a best practice for maintainers too.
> [docs] Fix Pigment CSS install

- docs/data/material/components/snackbars/snackbars.md
One title was missed in https://github.com/mui/material-ui/pull/43796
> [docs] Replace 'Experimental APIs - Toolpad' with 'Toolpad (Beta)'

- packages/mui-docs/src/Ad/ad.styles.ts
It's a regression, it was working fine in v4: https://v4.mui.com/getting-started/installation/. It's a quick win, to get us closer to peak execution. RTL docs needs to look correct to have credibility with RTL. I noticed this in https://github.com/mui/mui-x/pull/15072.
Regressions like https://github.com/mui/material-ui/issues/41239 are red flags for RTL users (I have seen a few more problems with icons and spacing).
Before: https://mui.com/material-ui/react-button/
After:
> [docs-infra] Fix ad in RTL

- packages/mui-material/src/Grid/Grid.js
- packages/mui-material/src/Grid/Grid.test.js
- packages/mui-system/src/createTheme/createSpacing.test.ts
closes #44321
Regression from #42574, test added.
> [material-ui][Grid v1] Fix regression spacing prop with string value

- packages/mui-styled-engine-sc/package.json
- pnpm-lock.yaml
I moved `@types/hoist-non-react-statics` from devDependencies to dependencies.
The type definitions for `styled-engine-sc` depend on `hoist-non-react-statics`.
https://github.com/mui/material-ui/blob/47326108836da30c36b6b63bf6413f936a1e71fb/packages/mui-styled-engine-sc/src/index.d.ts#L3
The `@types/hoist-non-react-statics` is not included in the dependencies, if this type definition is not installed, `styled` would return any.
I tried this in [Material UI + CRA + styled-components (TypeScript)](https://github.com/mui/material-ui/tree/47326108836da30c36b6b63bf6413f936a1e71fb/examples/material-ui-cra-styled-components-ts) repository.
---
I re-created this PR because the CI is stuck.
https://github.com/mui/material-ui/pull/43730#issuecomment-2468464758
> [styled-engine-sc] Fix missing `@types/hoist-non-react-statics` causing `styled` returns any

- packages/api-docs-builder/ApiBuilders/ComponentApiBuilder.ts
- packages/api-docs-builder/ApiBuilders/HookApiBuilder.ts
- packages/api-docs-builder/ProjectSettings.ts
- packages/api-docs-builder/buildApi.ts
- packages/api-docs-builder/utils/escapeEntities.ts
- packages/api-docs-builder/utils/generatePropDescription.ts
- packages/api-docs-builder/utils/generatePropTypeDescription.ts
- packages/api-docs-builder/utils/parseSlotsAndClasses.ts
- scripts/buidApiDocs/index.ts
Currently, `api-docs-builder` always renders JSDoc descriptions from markdown into HTML.
For the upcoming Base UI docs, we want the docs themselves to be responsible for rendering that so that component descriptions can be processed using the same MDX pipeline like the rest of the docs contents.
This PR adds a `rawDescriptions` option to `ProjectSettings`. When `true`:
- JSDoc is not rendered into HTML
- HTML entities aren’t escaped
No changes produced by `docs:api:build` in the current configs.
> [docs-infra] Add a `rawDescriptions` option

- packages-internal/test-utils/src/describeConformance.tsx
Use `this?.skip?.() ?? t?.skip();` so we can continue the vitest migration 😅
> [code-infra] Use vitest-compatible skip in `describeConformance`

- packages/mui-utils/src/useForkRef/useForkRef.ts
Add documentation to explain what the `useForkRef` actually does and is useful for.
> [utils] Add documentation to `useForkRef`

- packages/mui-material/src/Autocomplete/Autocomplete.js
- packages/mui-material/src/Autocomplete/Autocomplete.test.js
Closes https://github.com/mui/material-ui/issues/44264
The `ul` element was lost in this PR: https://github.com/mui/material-ui/pull/43994. **Previously, it was provided via the `as` prop**:
https://github.com/mui/material-ui/blob/15ea548de803e4602894cae6304a497d7ddaf09c/packages/mui-material/src/Autocomplete/Autocomplete.js#L560-L561
https://github.com/mui/material-ui/blob/15ea548de803e4602894cae6304a497d7ddaf09c/packages/mui-material/src/Autocomplete/Autocomplete.js#L685
But after https://github.com/mui/material-ui/pull/43994 fix, we failed to maintain it:
https://github.com/mui/material-ui/blob/01c5f344628bc66e16f86284ee0fc7107002a5ca/packages/mui-material/src/Autocomplete/Autocomplete.js#L329
https://github.com/mui/material-ui/blob/01c5f344628bc66e16f86284ee0fc7107002a5ca/packages/mui- …
> [material-ui][Autocomplete] Use `ul` element for the listbox 

- packages/mui-utils/src/useForkRef/useForkRef.ts
A quick follow-up on #44410
- Fix typo, and indentation
- Correct capitalization
- Fix the example to be valid. We don't allow to split refs in two DOM nodes 
Testing that it works: https://stackblitz.com/edit/vitejs-vite-9kvwdw?file=package.json,src%2FApp.tsx&terminal=dev
> [core] Polish useForkRef docs

- docs/data/material/components/dialogs/dialogs.md
- docs/data/material/components/menus/menus.md
- docs/data/material/components/popover/popover.md
- docs/data/material/components/popper/popper.md
- docs/data/material/components/snackbars/snackbars.md
- docs/data/material/components/text-fields/text-fields.md
- docs/data/material/discover-more/related-projects/related-projects.md
Iterate on #44191
Preview: https://deploy-preview-44315--material-ui.netlify.app/material-ui/discover-more/related-projects/#app-starters
> [docs] Add App starters in related-projects.md

- packages/mui-utils/src/deepmerge/deepmerge.test.ts
- packages/mui-utils/src/deepmerge/deepmerge.ts
closes #44278
Next.js 15 with Turbopack has a different signature for React element which cause the `@mui/utils/deepmerge` to recursively deepclone React element. More details on https://github.com/mui/material-ui/issues/44278
I think it does not make sense anyway for the deepmerge function to deepClone React elements.
So I added a check to deepmerge directly to avoid deepClone React elements.
Tested with https://github.com/nphmuller/mui-next-15_0_2_issue, this PR fixes the issue.
---
> [utils] skip deep clone React element

- test/regressions/fixtures/Autocomplete/Virtualize.js
An oversight of https://github.com/mui/material-ui/pull/44382. The regression test was not deterministic, so the screenshots were unstable. This fixes it by creating the options deterministically while maintaining a similar behavior from the demo.
> [test][Autocomplete] Make virtualize regression screenshots deterministic

- packages/mui-styled-engine-sc/src/index.d.ts
- packages/mui-styled-engine-sc/src/index.js
Fixes https://github.com/mui/material-ui/issues/44112
> [styled-engine] Add back removed internal function

- .github/workflows/cherry-pick-next-to-master.yml
- .github/workflows/create-cherry-pick-pr.yml
MUI X has built a workflow action to handle this, one that is more versatile. I believe we can simply adopt it. I only had to do https://github.com/mui/mui-public/pull/244 to support all the https://github.com/mui repositories. 
The initial version was #41742. More details on how this new one works: https://github.com/mui/mui-public/issues/221.
cc @aarongarciah for awareness.
> [infra] Upgrade Cherry-pick workflow to latest

- docs/data/material/migration/upgrade-to-v6/migrating-to-pigment-css.md
- examples/material-ui-pigment-css-nextjs-ts/package.json
- examples/material-ui-pigment-css-vite-ts/package.json
- packages/mui-material-pigment-css/package.json
This change helps in module resolution across different package
managers, especially pnpm, which expects the imports to be from direct
dependencies.
During sx prop transform, pigment-css plugin adds -
```js
import { sx } from '@pigment-css/react';
```
which would throw an error when using pnpm since @pigment-css/react was
not a direct dependency of the user's application.
Note: This is a breaking change.
> [pigment-css] Make @pigment-css/react as peer dependency

- docs/src/components/pricing/PricingTable.tsx
Go to https://mui.com/pricing/ and open the tree view:
I got frustrated with the speed of opening. This feels like a bug introduced in #43466. 
The fix is to rely on https://m1.material.io/motion/duration-easing.html#duration-easing-dynamic-durations.
---
A side note, the performance of this interaction is not production compatible, it takes 100ms to start the animation on a high-end laptop, too slow.
👉 https://deploy-preview-44490--material-ui.netlify.app/pricing/
> [website] Improve pricing page tree view animation

- docs/src/modules/components/DiamondSponsors.js
Fix a design regression that was introduced in #44474:
https://mui.com/material-ui/getting-started/.
See https://deploy-preview-44473--material-ui.netlify.app/material-ui/getting-started/ as an example of how it was correct before. I noticed this regression fixing that: https://github.com/mui/mui-x/pull/15574. 
After: https://deploy-preview-44515--material-ui.netlify.app/material-ui/getting-started/
> [docs-infra] Fix Sponsor design regression

- docs/src/modules/components/AppLayoutDocsFooter.js
This logic has been buggy for a long time, we were lucky up until now to not hit it, but with https://github.com/mui/mui-x/pull/15014, we started to see it:
- Go to https://next.mui.com/x/react-charts/#supported-features, see how the previous page "API reference" link is broken: 
- Go to https://next.mui.com/x/api/charts/bar-chart/ see how there is no prev/next links:
This happens because in MUI X v8, we added `subheader`, breaking the previous heuristic: if there is a single child, then this child is a leaf. Nop, not true ever since we support subheaders.
Preview: https://mui.com/material-ui/getting-started/. On Material UI, nothing should change.
> [docs-infra] Correctly flatten the pages tree

- .eslintrc.js
- dangerFileContent.ts
- docs/scripts/updateIconSynonyms.js
- docs/src/modules/components/ApiPage/list/ClassesList.tsx
- docs/src/modules/components/ApiPage/list/PropertiesList.tsx
- docs/src/modules/components/ApiPage/sections/ToggleDisplayOption.tsx
- docs/src/modules/components/ApiPage/table/ClassesTable.tsx
- docs/src/modules/components/ApiPage/table/PropertiesTable.tsx
- docs/src/modules/components/ApiPage/table/SlotsTable.tsx
- docs/src/modules/components/JoyThemeBuilder.tsx
- docs/src/modules/components/JoyUsageDemo.tsx
- docs/src/modules/components/JoyVariablesDemo.tsx
- docs/src/modules/components/MuiProductSelector.tsx
- docs/src/modules/components/ThemeViewer.tsx
- packages/rsc-builder/buildRsc.ts
Move https://github.com/mui/mui-x/pull/15437 from MUI X to code-infra.
This breaks in Base UI. Some are nice, they show cases where we import private APIs in the `app/experiments` some are weird, e.g. https://github.com/mui/base-ui/blob/d7809157ccc737608acc70a1ecbb42dfbca7ae78/packages/mui-base/vitest.config.ts#L2 seems fine. So I guess it makes sense to move forward.
> [core-infra] Add no-relative-packages

- docs/data/material/getting-started/templates/dashboard/components/AppNavbar.js
- docs/data/material/getting-started/templates/dashboard/components/AppNavbar.tsx
- docs/scripts/generateTemplateScreenshots.ts
A change in https://github.com/mui/material-ui/pull/44253#discussion_r1824662018 is a hack. This PR is better because it can locate the visible element without specifying empty `data-screenshot=""` to the element.
> [docs-infra] Improve locator finding using visible option

- docs/data/material/components/dialogs/SimpleDialogDemo.js
- docs/data/material/components/dialogs/SimpleDialogDemo.tsx
I noticed this by chance, it has been broken for a long time, broken in #33970 (the second regression of the PR, the first one was #38580), and it looked quick to fix, so I was compelled to go after it.
Was correct https://v5-0-6.mui.com/components/dialogs/
Before: https://mui.com/material-ui/react-dialog/#introduction
After: https://deploy-preview-44467--material-ui.netlify.app/material-ui/react-dialog/
For context, this demo is modeled after https://m1.material.io/components/dialogs.html#dialogs-simple-dialogs.
> [docs][dialog] Fix padding in SimpleDialog demo

- packages/mui-utils/src/deepmerge/deepmerge.test.ts
- packages/mui-utils/src/deepmerge/deepmerge.ts
Brings changes from #44400 to v5.x branch to fix #44278 also in v5.x.
---
> [utils] skip deep clone React element (v5.x)

- packages/mui-base/src/Unstable_NumberInput/NumberInput.test.tsx
- packages/mui-base/src/useAutocomplete/useAutocomplete.test.js
- packages/mui-joy/src/Autocomplete/Autocomplete.test.tsx
- packages/mui-lab/src/Masonry/Masonry.test.js
- packages/mui-material/src/Accordion/Accordion.test.js
- packages/mui-material/src/Autocomplete/Autocomplete.test.js
- packages/mui-material/src/Grid/Grid.test.js
- packages/mui-material/src/IconButton/IconButton.test.js
- packages/mui-material/src/InputBase/InputBase.test.js
- packages/mui-material/src/ListItem/ListItem.test.js
- packages/mui-material/src/Menu/Menu.test.js
- packages/mui-material/src/Popover/Popover.test.js
- packages/mui-material/src/Select/Select.test.js
- packages/mui-material/src/Tabs/Tabs.test.js
- packages/mui-material/src/Tooltip/Tooltip.test.js
- packages/mui-material/src/internal/SwitchBase.test.js
- packages/mui-material/src/useAutocomplete/useAutocomplete.test.js
- packages/mui-material/src/useMediaQuery/useMediaQuery.test.js
- packages/mui-styles/src/makeStyles/makeStyles.test.js
- packages/mui-utils/src/elementAcceptingRef/elementAcceptingRef.test.tsx
- packages/mui-utils/src/getDisplayName/getDisplayName.test.tsx
- packages/test-utils/src/createRenderer.tsx
- packages/test-utils/src/fireDiscreteEvent.ts
- packages/test-utils/src/index.ts
- packages/test-utils/src/reactMajor.ts
- packages/test-utils/src/userEvent.ts
Cherry-pick: https://github.com/mui/material-ui/pull/43155, https://github.com/mui/material-ui/pull/43211, https://github.com/mui/material-ui/pull/43269, https://github.com/mui/material-ui/pull/43282
All these PRs are related to fixing the testing changes in React 19.
> [test] Cherry-pick React 19-related test PRs

- packages/mui-base/src/useAutocomplete/useAutocomplete.js
- packages/mui-base/src/useAutocomplete/useAutocomplete.test.js
- packages/mui-material/src/useAutocomplete/useAutocomplete.js
- packages/mui-material/src/useAutocomplete/useAutocomplete.test.js
Cherry-pick: #43189 (Fix default value for multiple mode getting redefined with React 19)
Part of: https://github.com/mui/material-ui/issues/44413
> [material-ui][Autocomplete] Cherry-pick #43189

- packages/mui-docs/src/Ad/Ad.tsx
- packages/mui-docs/src/ComponentLinkHeader/ComponentLinkHeader.tsx
- packages/mui-docs/src/MarkdownElement/MarkdownElement.tsx
Since https://github.com/easylist/easylist/issues/20644 is live, e.g. with uBlock Origin, the docs look broken: 
https://mui.com/material-ui/react-alert/
Instead, we can add some margin, in case the block gets removed.
I also used the opportunity to make it harder to have selectors that reliably work for this block.
Preview: 
- https://deploy-preview-44567--material-ui.netlify.app/material-ui/react-toggle-button/
- https://deploy-preview-44567--material-ui.netlify.app/material-ui/react-alert/
> [docs-infra] Fix display when ad-block triggers

- packages/mui-material/src/FilledInput/FilledInput.js
We should not use deprecated API.
> [FilledInput] Use `slotProps` instead of `componentsProps`

- packages/mui-material/src/Tabs/ScrollbarSize.js
Closes: https://github.com/mui/material-ui/issues/41388
The explanation for the fix: https://github.com/mui/material-ui/issues/41388#issuecomment-2185339892
`ScrollbarSize` is an internal component, not exported, and we don't need to provide a ref, so there's no need for ref merging.
Before and after: https://github.com/DiegoAndai/material-ui-issue-41388-repro
Before is the [`main` branch](https://github.com/DiegoAndai/material-ui-issue-41388-repro/tree/main)
After is the [`with-fix` branch](https://github.com/DiegoAndai/material-ui-issue-41388-repro/tree/with-fix) that uses this PR's build
> [material-ui][Tabs] Fix `ScrollbarSize` ref being overriden

- packages/mui-material/src/Tabs/ScrollbarSize.js
Cherry-pick https://github.com/mui/material-ui/pull/44593
Part of https://github.com/mui/material-ui/issues/44413
> [material-ui][Tabs] Cherry pick `ScrollbarSize` ref being overriden fix

- .eslintrc.js
Extends the [eslint-config-airbnb-typescript](https://www.npmjs.com/package/eslint-config-airbnb-typescript)'s [rule](https://github.com/airbnb/javascript/blob/6499695ac11c4640ed0f77f8865a1adcb32d3239/packages/eslint-config-airbnb-base/rules/variables.js#L54) previously in action by adding an `argsIgnorePattern` for allowing `_` based unused variables.
Context: https://github.com/mui/mui-x/pull/15215/files#r1832690326
> [core] Update eslint config

- docs/data/material/getting-started/templates/shared-theme/AppTheme.js
- docs/data/material/getting-started/templates/shared-theme/AppTheme.tsx
- docs/pages/joy-ui/api/stack.json
- docs/pages/material-ui/api/container.json
- docs/pages/material-ui/api/grid-2.json
- docs/pages/material-ui/api/stack.json
- docs/pages/system/api/container.json
- docs/pages/system/api/grid.json
- docs/pages/system/api/stack.json
- packages/api-docs-builder/ApiBuilders/ComponentApiBuilder.ts
- packages/api-docs-builder/utils/defaultPropsHandler.ts
- packages/api-docs-builder/utils/getPropsFromComponentNode.ts
- packages/mui-base/src/ClickAwayListener/ClickAwayListener.tsx
- packages/mui-base/src/NoSsr/NoSsr.tsx
- packages/mui-base/src/Portal/Portal.tsx
- packages/mui-material/src/ClickAwayListener/ClickAwayListener.tsx
- packages/mui-material/src/Hidden/HiddenJs.js
- packages/mui-material/src/NoSsr/NoSsr.tsx
- packages/mui-material/src/Portal/Portal.tsx
I'm having some fun with the AST, allowing https://github.com/reactjs/react-docgen to extract props descriptions even when the component doesn't return a React element. We shouldn't be shipping dead code to developers, this PR avoids this. This should both improve bundle size and runtime.
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/65135 should help in the future.
> [core-infra] Remove useless fragments

- packages/mui-material/src/styles/ThemeProviderWithVars.test.js
- packages/mui-system/src/cssVars/createCssVarsProvider.js
closes #44555
`ThemeProvider` recompose the theme and pass it to React context. The current implementation is not optimized, so if the parent of `ThemeProvider` rerenders, the theme send to React context is a new object causing the component that get the theme through `useTheme` to rerender (or run effect) again.
---
> [ThemeProvider] Optimize `theme` changes when enabling CSS theme variables

- packages/mui-material/src/Grid2/Grid2.test.js
- packages/mui-material/src/Grid2/Grid2.tsx
address https://github.com/mui/material-ui/pull/44562#issuecomment-2506269961
Before: https://codesandbox.io/p/sandbox/snowy-browser-3pmlw9
After fix: https://codesandbox.io/p/sandbox/xenodochial-mestorf-pc2qjm?file=%2Fsrc%2FDemo.tsx%3A8%2C1
> [Grid2] Add container styles from styleOverrides

- docs/src/modules/components/AppTableOfContents.js
This fixes a regression introduced in #42498. This is broken in RTL since:
Before: https://deploy-preview-42498--material-ui.netlify.app/material-ui/react-button/
After: https://deploy-preview-44535--material-ui.netlify.app/material-ui/react-button/
**Off-topic**. Speaking of regressions, spending some time on this made me realize the dark mode and RTL toggle have an important performance regression: #44534.
> [docs-infra] Fix TOC RTL padding regression

- packages/mui-material/src/ButtonBase/ButtonBase.js
Suggested fix for #42564 with ButtonBase.js
This solves the invalid-hook-call-warning ESLint warning with the useRippleHandler hook. 
There are still ref.current ESLint warnings with the current version of eslint-plugin-react-compiler, but when eslint-plugin-react-compiler is updated to the newest version, these are gone. From our understanding of the ESLint warning, it is a false positive, so the newer version is correct while the current one is not.
> [core] Extract useRippleHandler outside of ButtonBase

- docs/data/material/migration/migrating-from-deprecated-apis/migrating-from-deprecated-apis.md
`testid` is not a valid prop in any of the components, i tried replacing `testid` with `data-testid` but faced typescript error. Hence at last went with `id` as it will be available in all components
> [material-ui][docs] Replace testid with id in migration guide

- packages/mui-material/src/Grid2/Grid2.test.js
- packages/mui-material/src/Grid2/Grid2.tsx
- packages/mui-system/src/Grid/createGrid.tsx
closes #44539
The Grid2 does not work properly when theme scoping is configure because it's using theme directly from `@mui/system`.
The fix is to pass `useTheme` from Material UI when creating Grid2 component.
Test added.
> [Grid2] Fix theme scoping error

- docs/src/components/banner/AppFrameBanner.tsx
- docs/src/modules/components/AppFrame.js
Fix https://github.com/mui/material-ui/pull/44630#discussion_r1866268176
---
While I was at it, I thought I would also do a quick cleanup for that: https://mui.com/material-ui/getting-started/
https://github.com/user-attachments/assets/f0946b67-e9a3-4a0e-95da-155ef88a0828
see how the search bar blinks, annoying. We should truly not remount the DOM between each page transition, so use a Layout #41117, but this change doesn't harm.
After: https://deploy-preview-44632--material-ui.netlify.app/material-ui/getting-started/
https://github.com/user-attachments/assets/15d2ac1e-d615-42be-9659-bace54379593
> [docs-infra] Fix Banner CLS

- packages-internal/test-utils/src/describeConformance.tsx
part of https://github.com/mui/material-ui/issues/42380
> [test-utils] Remove leftover React.ReactElement<any> from describeConformance.tsx

- packages/mui-base/src/Select/Select.tsx
- packages/mui-material/src/FormHelperText/FormHelperText.js
- packages/mui-material/src/InputAdornment/InputAdornment.js
- packages/mui-material/src/OutlinedInput/NotchedOutline.js
- packages/mui-material/src/Select/SelectInput.js
This PR fixes #41515 which causes the screen reader to read "zero width space" on select components
issue shown here:
Before: https://mui.com/material-ui/react-select/#basic-select
After: https://deploy-preview-44631--material-ui.netlify.app/material-ui/react-select/#basic-select
> [Select][TextField] Fix screen reader from saying `&ZeroWidthSpace`

- packages/mui-material/src/Box/Box.d.ts
- packages/mui-material/src/Box/Box.spec.tsx
Closes https://github.com/mui/material-ui/issues/43955
This was an oversight of https://github.com/mui/material-ui/pull/43384, as the System `BoxProps` had the `component` property, but Material UI's didn't. They should be equivalent. I added a test for it as well.
> [material-ui][Box] Add missing `component` to `BoxProps` type

- examples/material-ui-via-cdn/index.html
- pnpm-lock.yaml
The UMD examples pointed to React's latest version, but React 19 [removed their UMD builds](https://react.dev/blog/2024/04/25/react-19-upgrade-guide#umd-builds-removed). Because of this, once React 19 was stable, these examples (and the CI test, [example](https://app.circleci.com/jobs/github/mui/material-ui/777405)) started failing.
This PR pins the React version of the example to 18.
> [core] Fix UMD examples

- packages/api-docs-builder/ApiBuilders/ComponentApiBuilder.ts
- packages/api-docs-builder/ApiBuilders/HookApiBuilder.ts
- packages/api-docs-builder/types/ApiBuilder.types.ts
- packages/api-docs-builder/types/utils.types.ts
In Base UI docs, all component docs and its API reference are placed on the same page
This PR updates the docs builder so that instead of separate API and docs URLs...
...we can use custom annotations provided from where the docs builder script runs:
> [api-docs-builder] Allow custom annotations

- docs/src/components/markdown/MarkdownElement.tsx
- packages/mui-material/src/ClickAwayListener/ClickAwayListener.tsx
- packages/mui-material/src/NoSsr/NoSsr.tsx
- packages/mui-material/src/Unstable_TrapFocus/FocusTrap.tsx
- packages/mui-material/src/utils/PolymorphicComponent.ts
Some React 19 JSX backports were missed when we removed the mui-base dependency. For some reason, even though the original PR has `React.JSX.Element` ([example](https://github.com/mui/material-ui/pull/42907/files#diff-cee63db515126a4c1c9c392d0763d7a6931b45f079e3765aebb7bc9cc34bcc8aR13)), the backport had `JSX.Element` ([example](https://github.com/mui/material-ui/pull/42917/files#diff-cee63db515126a4c1c9c392d0763d7a6931b45f079e3765aebb7bc9cc34bcc8aR13)).
> [typescript] Rescue missing backports v5

- CHANGELOG.md
- package.json
- packages/mui-core-downloads-tracker/package.json
- packages/mui-docs/package.json
- packages/mui-icons-material/package.json
- packages/mui-material/package.json
- packages/mui-styles/package.json
- pnpm-lock.yaml
We forgot to bump the root `package.json` version in https://github.com/mui/material-ui/pull/44711/files , I didn't notice until I tried to tag the release
Let's do a fresh one just to be safe, luckily its the v5 branch
> [release] v5.16.11

- packages/mui-material/src/styles/useThemeProps.d.ts
- packages/mui-utils/src/composeClasses/composeClasses.ts
- packages/mui-utils/src/deepmerge/deepmerge.test.ts
- packages/mui-utils/src/deepmerge/deepmerge.ts
Add documentation to explain what the functions do and how to use them.
I've added examples to all of them, since understanding what they do required a by of code-digging before. 😅
> [core] Add documentation to `useThemeProps`, `deepmerge` and `composeClasses` functions

- packages/mui-joy/package.json
Release for React 19 support. Dev dependencies haven't been updated yet but that shouldn't impact end users.
I checked with `pnpm release:changelog` and there are no Joy-specific commits since the last release from this branch (which was [alongside 5.16.1](https://github.com/mui/material-ui/pull/42897))
> [release] MUI Joy `5.0.0-beta.50`

- packages/api-docs-builder/buildApi.ts
- packages/api-docs-builder/utils/generatePropDescription.ts
Make sure that multiline descriptions aren't collapsed when `rawDescriptions` option is on (used by Base UI docs)
> [api-docs-builder] Preserve multiline prop descriptions with `rawDescriptions` option

- docs/data/material/components/dialogs/DraggableDialog.js
- docs/data/material/components/dialogs/DraggableDialog.tsx
closes https://github.com/mui/material-ui/issues/44732
Error occurs because react-draggable is using the deprecated findDOMNode method. On updating code to use refs fixed the issue
before: https://mui.com/material-ui/react-dialog/#draggable-dialog
after: https://deploy-preview-44747--material-ui.netlify.app/material-ui/react-dialog/#draggable-dialog
> [material-ui][Dialog] Fix crashing of DraggableDialog demo

- docs/data/material/components/text-fields/FormattedInputs.js
- docs/data/material/components/text-fields/FormattedInputs.tsx
closes #19922 based on https://s-yadav.github.io/react-number-format/docs/props#custominput-reactcomponentany
> [docs] Update `react-number-format` demo to use the recommended prop

- packages/mui-material/src/Autocomplete/Autocomplete.js
- packages/mui-material/src/AvatarGroup/AvatarGroup.js
- packages/mui-material/src/CardHeader/CardHeader.js
- packages/mui-material/src/FormControl/FormControl.js
- packages/mui-material/src/FormLabel/FormLabel.js
- packages/mui-material/src/styles/styled.test.js
works to fix:  https://github.com/mui/material-ui/issues/44699
> [Material UI] Update `overridesResolver` return from object to array of styles

- packages/mui-material/src/Pagination/Pagination.test.js
- packages/mui-material/src/usePagination/usePagination.js
The current pagination mechanism in the docs reads the current page in the screen reader as "current item". By using `aria-current="page"` instead of `aria-current="true"`, the screen reader reads it more clearly as "current page".
This is correct property described in the [pagination w3c spec](https://design-system.w3.org/components/pagination.html).
> [material-ui][Pagination] Use correct `aria-current` value

- CHANGELOG.md
- package.json
- packages/mui-base/package.json
- packages/mui-core-downloads-tracker/package.json
- packages/mui-docs/package.json
- packages/mui-icons-material/package.json
- packages/mui-joy/package.json
- packages/mui-lab/package.json
- packages/mui-material-nextjs/package.json
- packages/mui-material/package.json
- packages/mui-private-theming/package.json
- packages/mui-styled-engine/package.json
- packages/mui-styles/package.json
- packages/mui-system/package.json
- packages/mui-utils/package.json
PR to release
- v5.16.12 packages
- `@mui/joy` version `5.0.0-beta.51` which updates peer dependencies to include React 19
- `@mui/lab` version `5.0.0-alpha.175` which updates peer dependencies to include React 19
- `@mui/base` version `5.0.0-beta.40-0`. This package is usually released from the `master` branch (latest is `5.0.0-beta.66`), but this is a special version with updated peer dependencies to include React 19, to be used by the `@mui/joy`, `@mui/lab`, and `@mui/docs` packages released with this PR
> [release] v5.16.12

- docs/data/material/components/text-fields/InputSuffixShrink.js
- docs/data/material/components/text-fields/InputSuffixShrink.tsx
- docs/data/material/components/text-fields/text-fields.md
closes #19792
preview: https://deploy-preview-44744--material-ui.netlify.app/material-ui/react-text-field/#visible-on-shrink
> [docs][TextField] Add suffix shrink demo

- docs/next-env.d.ts
- docs/nextConfigDocsInfra.js
Follow-up on https://github.com/mui/material-ui/pull/43469.
Noticed after bumping to Next@15 on mui-x.
> [docs-infra] Remove no longer support `optimizeFonts` Next.js option

- docs/data/about/teamMembers.json
- docs/scripts/reportBrokenLinks.js
- docs/src/components/about/OurValues.tsx
- docs/src/components/careers/CareersFaq.tsx
- docs/src/components/productDesignKit/DesignKitFAQ.tsx
- docs/src/components/typography/SectionHeadline.tsx
- packages/markdown/index.d.ts
- packages/markdown/parseMarkdown.js
Making a small step toward fixing https://www.notion.so/mui-org/people-Sync-hiring-FAQ-content-12bfa7c6cb42439296d0425e743c9f4b.
I saw this from the question asked in https://app.ashbyhq.com/home/upcoming/right-side/candidates/46022b97-5efc-4584-bb81-61cea92578e4/applications/0179f09d-0ee7-4ffb-acb4-d201a854cce5.
Preview: https://deploy-preview-44678--material-ui.netlify.app/careers/#faq
> [website] Sync career FAQ with Notion

- packages/mui-material/src/Tooltip/Tooltip.js
- packages/mui-material/src/Tooltip/Tooltip.test.js
closes https://github.com/mui/material-ui/issues/40355
> [material-ui][Tooltip] Warn instead of error when trigger is disabled

- docs/src/components/careers/PerksBenefits.tsx
https://mui.com/careers/
This is not true. The current budget is $2,750 for engineers and $1,750 for non-engineers, plus an extra budget for designers. It's too complex now to only list one number. People can find all the details in the public handbook https://www.notion.so/mui-org/Work-equipment-a2c2a3f1a5984bd8bdd4b698fa3f0a16.
I guess we can simply remove the hard-coded value, and emphasize that it's more free selection.
Preview: https://deploy-preview-44848--material-ui.netlify.app/careers/
> [website] Fix career equipment description

- docs/data/material/components/dialogs/DraggableDialog.js
- docs/data/material/components/dialogs/DraggableDialog.tsx
fixes https://github.com/mui/material-ui/issues/44810
Logic taken from https://github.com/mui/material-ui/pull/44747 applied to v5.x branch
working preview: https://deploy-preview-44811--material-ui.netlify.app/material-ui/react-dialog/#draggable-dialog
> [docs][material-ui] Fix crashing of DraggableDialog demo

- .eslintrc.js
- examples/material-ui-nextjs-pages-router-ts/README.md
- examples/material-ui-nextjs-pages-router-ts/package.json
- examples/material-ui-nextjs-pages-router-ts/pages/_app.tsx
- examples/material-ui-nextjs-pages-router-ts/pages/_document.tsx
- examples/material-ui-nextjs-pages-router/README.md
- examples/material-ui-nextjs-pages-router/package.json
- examples/material-ui-nextjs-pages-router/pages/_app.js
- examples/material-ui-nextjs-pages-router/pages/_document.js
- examples/material-ui-nextjs-pages-router/src/Link.js
- examples/material-ui-nextjs-ts/README.md
- examples/material-ui-nextjs-ts/next-env.d.ts
- examples/material-ui-nextjs-ts/package.json
- examples/material-ui-nextjs-ts/src/app/layout.tsx
- examples/material-ui-nextjs/README.md
- examples/material-ui-nextjs/package.json
- examples/material-ui-nextjs/src/app/layout.js
Follow up on the React upgrade. Upgrade the Next.js examples to the latest Next.js version, as well as the latest React version.
Also remove prop-types as they're deprecated in React 19.
> [examples] Update Next.js examples Next.js and React versions

- docs/data/material/components/selects/selects.md
Part of https://github.com/mui/material-ui/issues/44821
This PR adds a warning to the Select docs page to point out that the `placeholder` prop is not available in Select. The Select API page is not updated in this PR as it needs docs infra work to add such a one-off text.
> [docs][Select] Update docs to reflect the omission of placeholder prop

- docs/src/modules/components/JoyThemeBuilder.tsx
Error on the client-side when clicking the same color on the Theme builder [page](https://mui.com/joy-ui/customization/theme-builder/).
https://github.com/user-attachments/assets/e62f6d10-91b6-461e-9c10-b417984d84db
There is an error when clicking the same color on the Theme builder page.
https://github.com/user-attachments/assets/a6742a1f-8fef-4d6a-9588-8600ee50a91a
Set color mode only when `newValue` is not null.
https://github.com/user-attachments/assets/ad813d37-0353-435e-9725-fb73c5ab72d5
> [joy-ui][docs] Fix Color mode button on Theme builder

- .eslintrc.js
Reflect https://github.com/mui/base-ui/issues/488 and https://github.com/mui/base-ui/issues/805.
> [code-infra] Prevent wrong nested imports in Base UI

- .circleci/config.yml
Closes: https://github.com/mui/material-ui/issues/44793
> [core] Setup React 18 CI tests

- packages/mui-utils/src/deprecatedPropType/deprecatedPropType.test.js
Help with https://github.com/mui/mui-x/pull/16017
> [core] Update test to use public API

- CHANGELOG.md
- package.json
- packages-internal/scripts/package.json
- packages-internal/test-utils/package.json
- packages/markdown/package.json
- packages/mui-codemod/package.json
- packages/mui-core-downloads-tracker/package.json
- packages/mui-docs/package.json
- packages/mui-envinfo/package.json
- packages/mui-icons-material/package.json
- packages/mui-lab/package.json
- packages/mui-material-nextjs/package.json
- packages/mui-material-pigment-css/package.json
- packages/mui-material/package.json
- packages/mui-private-theming/package.json
- packages/mui-styled-engine-sc/package.json
- packages/mui-styled-engine/package.json
- packages/mui-styles/package.json
- packages/mui-system/package.json
- packages/mui-types/package.json
- packages/mui-utils/package.json
- pnpm-lock.yaml
> [release] v6.3.1

- docs/data/material/components/typography/typography.md
Adds missing backticks around the <head /> tag in the documentation to fix incorrect rendering.
> [docs] Fix incorrect rendering in Typography docs

- docs/data/material/guides/composition/composition.md
- packages/mui-material/src/utils/mergeSlotProps.test.ts
- packages/mui-material/src/utils/mergeSlotProps.ts
Continue from #44809, this PR merge the `style` instead of replacing between default slot props and external slot props.
I think it's more common from user perspective to have `style` merged rather than replace.
Some of the Material UI components, e.g. [SwipeableDrawer](https://github.com/mui/material-ui/blob/master/packages/mui-material/src/SwipeableDrawer/SwipeableDrawer.js#L607-L610), also merge the style. So this PR will benefit both internal and users.
If the user wants to remove some style from the default style, they can provide `null` as a value:
```js
// default `pointerEvents` is "none"
<CustomSwipeableDrawer slotProps={{ paper: { style: { pointerEvents: null } }}>
```
> [material-ui] Update `mergeSlotProps` to merge `style`

- docs/data/material/getting-started/overview/overview.md
- docs/src/components/productMaterial/MaterialEnd.tsx
> [docs] Remove misleading messaging on MD3 support

- docs/data/material/design-resources/material-ui-sync/material-ui-sync.md
- docs/data/material/pages.ts
Seeing https://github.com/mui/mui-design-kits/issues/435 makes me feel that it's not usable in real life, it's a technical preview, so better be clear about it. (the other issues point in the same direction)
I'm going ahead as it's unclear who was going to work on https://www.notion.so/mui-org/core-General-meeting-2024-12-23-165cbfe7b660800b8535eea8f63052ec?pvs=4#165cbfe7b6608148b580d1ea2b0d75b3 and I was directly in the context looking at that GitHub issue.
> [figma] Clarify that Material UI Sync plugin is experimental

- apps/pigment-css-vite-app/src/pages/material-ui/react-progress.tsx
Revert and inline https://github.com/mui/material-ui/pull/43959, stabilize other progress indicaters that are JS animated. we can just inline the demos end set static values for the props.
> [code-infra] Stabilize flaky pigment progressbar tests

- docs/pages/material-ui/api/alert.json
- docs/translations/api-docs/alert/alert.json
- packages-internal/test-utils/src/describeConformance.tsx
- packages/mui-material/src/Alert/Alert.d.ts
- packages/mui-material/src/Alert/Alert.js
- packages/mui-material/src/Alert/Alert.spec.tsx
- packages/mui-material/src/Alert/Alert.test.js
- packages/mui-material/src/utils/useSlot.ts
Added missing slots: `root`, `icon`, `message` and `action.
---
> [material-ui][Alert] complete `slots` and `slotProps`

- packages/mui-material/src/StepLabel/StepLabel.d.ts
- packages/mui-material/src/StepLabel/StepLabel.spec.tsx
- packages/mui-material/src/Tooltip/Tooltip.d.ts
- packages/mui-material/src/Tooltip/Tooltip.spec.tsx
closes https://github.com/mui/material-ui/issues/44952
The previous slots types is too narrow
```js
export interface StepLabelSlots {
/**
* The component to render in place of the [`StepIcon`](https://mui.com/material-ui/api/step-icon/).
*/
stepIcon: React.ElementType<StepIconProps>;
}
```
It's specific to `StepIconProps`, meaning using plain HTML like `"div"` or a custom component won't work.
```js
<StepLabel
slots={{
stepIcon: 'div', // ❌ type error
}}
>
Step One
</StepLabel>;
```
Widening the types to just `React.ElementType` to include plain HTML and any custom React component.
---
> [material-ui] Fix slots typing for Tooltip and StepLabel

- docs/data/material/getting-started/templates/dashboard/components/CardAlert.js
- docs/data/material/getting-started/templates/dashboard/components/CardAlert.tsx
- docs/data/material/getting-started/templates/dashboard/components/CustomizedDataGrid.js
- docs/data/material/getting-started/templates/dashboard/components/CustomizedDataGrid.tsx
- docs/data/material/getting-started/templates/dashboard/components/MenuContent.js
- docs/data/material/getting-started/templates/dashboard/components/MenuContent.tsx
- docs/data/material/getting-started/templates/dashboard/components/SideMenu.js
- docs/data/material/getting-started/templates/dashboard/components/SideMenu.tsx
- docs/data/material/getting-started/templates/dashboard/components/SideMenuMobile.js
- docs/data/material/getting-started/templates/dashboard/components/SideMenuMobile.tsx
A small fix while I was looking at why the INP on the dashboard page [is poor](https://app.ahrefs.com/site-audit/3524616/data-explorer?columns=pageRating%2Curl%2Ctraffic%2ChttpCode%2Cpsi_request_status%2Cpsi_crux_cls_percentile%2Cpsi_crux_cls_category%2Cpsi_crux_fid_percentile%2Cpsi_crux_fid_category%2Cpsi_crux_lcp_percentile%2Cpsi_crux_lcp_category%2Cpsi_crux_inp_percentile%2Cpsi_crux_inp_category%2Cpsi_lighthouse_score%2Cpsi_lighthouse_cls_value%2Cpsi_lighthouse_tbt_value%2Cpsi_lighthouse_lcp_value%2Cdepth%2Ccompliant%2CincomingLinks%2Corigin&current=25-12-2024T023056&filterId=803558da95d9c83d362ecca5192ca260&issueId=85c01513-d747-49f5-8235-2b356bb4c686&sorting=-pageRating),
Reported in https://github.com/mui/mui-x/issues/16018.
---
Before: …
> [docs] Fix Dashboard sidenav sroll

- packages/mui-material/src/ButtonBase/ButtonBase.d.ts
Allows X to avoid deeply nested imports in X https://github.com/mui/mui-x/blob/1a9426021bd72b5a1cc18e2c78a5a063d27be541/docs/data/data-grid/column-definition/RenderCellGrid.tsx#L4
In fact it would make sense to export all types that are referenced by public API. But that's another story 🙂 
These imports will break once we put a hard limit on what is exported from the package
> [ButtonBase] Export types used in ButtonBase props

- packages/mui-system/src/cssVars/createCssVarsProvider.js
This is a bug on client-side apps only.
For server-side apps, the `mode` is correctly set before the app render by `InitColorSchemeScript` component.
The logic of updating the html's class attribute lives within `useEffect` instead of `useLayoutEffect`.
Even though, the first render has mode `dark` based on `noSsr` prop, the `class="dark"` applied to `<html>` happens after Browser has painted the first render.
The fix is to use `useEnhancedEffect` (a wrapper of `useLayoutEffect` for client-side) to attach `class="dark"` before browser paint.
**Before**:
The right button renders with default blue before turning red.
https://github.com/user-attachments/assets/56cb8009-9ae9-43af-accb-bcd37385fee8
**After**:
https://github.com/user-attachments/assets/f7a4e8a2-bca0-4f05-a68e-af0f1ecb0527
> [system] Fix dark mode flicker using `useEnhancedEffect`

- docs/public/_redirects
Part of https://github.com/mui/material-ui/issues/44910
> [docs] 301 redirect `/base-ui` to `base-ui.com`

- docs/data/base/components/accordion/accordion.md
- docs/data/base/components/checkbox/checkbox.md
- docs/data/base/components/radio-group/radio-group.md
- docs/data/base/components/toggle-button-group/toggle-button-group.md
- docs/data/base/components/tooltip/tooltip.md
- docs/src/components/productBaseUI/MuiBaseDeprecation.tsx
Fixes https://github.com/mui/material-ui/pull/45030#issuecomment-2601847079
> [docs] Update @mui/base deprecation message

- docs/pages/material-ui/api/icon-button.json
- docs/translations/api-docs/icon-button/icon-button.json
- packages/mui-material/src/IconButton/IconButton.d.ts
- packages/mui-material/src/IconButton/IconButton.js
- packages/mui-material/src/IconButton/IconButton.test.js
- packages/mui-material/src/IconButton/iconButtonClasses.ts
> [material-ui][IconButton] Set default loading to `null`

- packages/mui-utils/src/deepmerge/deepmerge.test.ts
- packages/mui-utils/src/deepmerge/deepmerge.ts
closes #45052
`deepmerge` currently iterate a React component that's wrapped with `forwardRef` or `memo`. The issue arise when using Link from nextjs (contains recursive render) because `deepmerge` will iterate infinitely causing maximum callstack error from the usage below:
```js
import { createTheme } from '@mui/material/styles';
import Link from 'next/link';
components: {
MuiLink: {
defaultProps: {
component: Link,
},
},
},
});
```
It does not make sense anyway to iterate fields inside a React component, so a side benefit of this PR is the performance improvement.
---
> [utils] Do not deep merge React component

- CHANGELOG.md
- package.json
- packages/mui-base/package.json
- packages/mui-codemod/package.json
- packages/mui-core-downloads-tracker/package.json
- packages/mui-docs/package.json
- packages/mui-icons-material/package.json
- packages/mui-lab/package.json
- packages/mui-material-pigment-css/package.json
- packages/mui-material/package.json
- packages/mui-material/src/Avatar/Avatar.js
- packages/mui-private-theming/package.json
- packages/mui-styles/package.json
- packages/mui-system/package.json
- packages/mui-utils/package.json
- pnpm-lock.yaml
> [release] v6.4.1

- packages/mui-material/src/TextareaAutosize/TextareaAutosize.tsx
Fixes https://github.com/mui/material-ui/issues/43718
Fixes https://github.com/mui/material-ui/issues/44140
Demo: https://codesandbox.io/p/sandbox/immutable-architecture-nslxvr?file=%2Fsrc%2FApp.js%3A33%2C1 (forked from the [original repro](https://github.com/mui/material-ui/issues/43718#issue-2520950148))
This was very hard to repro locally, but I believe the "loop" is caused when we change the height of the element in the RO callback, while it is still being observed, which fires the callback again (and again…)
The fix is to un-observe the element, manipulate the height then re-observe one frame later, instead of manipulating the height one frame later suggested [here](https://github.com/mui/material-ui/blob/master/packages/mui-material/src/TextareaAutosize/TextareaAutosize.tsx#L146-L156 …
> [material-ui][TextareaAutosize] Temporarily disconnect ResizeObserver to avoid loop error

- docs/src/components/banner/TableOfContentsBanner.tsx
- docs/src/featureToggle.js
- docs/src/modules/components/AppTableOfContents.js
- docs/src/modules/components/DiamondSponsors.js
A continuation of #34795. From https://github.com/mui/material-ui/pull/34795#issuecomment-1281365092, it seems that all the projects that are still maintained and that used to show a banner removed it. This change should help a bit with #40977 and the UX, reducing the visual distraction. At this stage, most people are pretty much aware of how we stand.
Related to #39495.
Preview: https://deploy-preview-45135--material-ui.netlify.app/material-ui/react-button-group/
Context, I noticed this, because I was engaging with https://mui.zendesk.com/agent/tickets/25472.
> [docs-infra] Move Ukraine banner to the bottom

- docs/data/material/migration/upgrade-to-v7/upgrade-to-v7.md
- docs/data/material/pages.ts
- docs/data/system/migration/upgrade-to-v7/upgrade-to-v7.md
- docs/data/system/pages.ts
- docs/pages/material-ui/migration/upgrade-to-v7.js
- docs/pages/system/migration/upgrade-to-v7.js
- docs/translations/translations.json
Add migration guide from v6 to v7 for Material UI and MUI System. They're empty now, but adding them allows everyone to add breaking changes on each PR.
Preview: https://deploy-preview-45143--material-ui.netlify.app/material-ui/migration/upgrade-to-v7/
> [docs] Add v6 to v7 migration guide

- CHANGELOG.md
- packages-internal/babel-plugin-minify-errors/package.json
- packages-internal/babel-plugin-resolve-imports/package.json
- packages-internal/docs-utils/package.json
- packages-internal/scripts/package.json
- packages-internal/test-utils/package.json
- packages/markdown/package.json
Bump the internal packages major so we can have them be released from either `master` or `v6.x`:
- If released from `master`, they would be `2.x`
- If released from `v6.x`, they would be `1.x`
This allows us to have breaking changes on `master` released under `2.x` without blocking non-breaking changes in `v6.x`, as those could be released under `1.x`. This is important as MUI X will be targeting v6.x for a while.
> [release][core] Bump internal packages major

- .circleci/config.yml
Fixes failing CI pipelines, e.g. https://app.circleci.com/pipelines/github/mui/material-ui/147263/workflows/c200ca76-d4b0-48f4-896f-9717bbdfcec0
It was caused by an upstream issue with corepack: https://github.com/nodejs/corepack/issues/612
See https://github.com/mui/base-ui/pull/1405 for more details, it's the same fix ~
> [core] Fix corepack and pnpm installation in CircleCI

- docs/data/joy/integrations/material-ui/material-ui.md
Closes #45134
- Updated the description and code example in the **"Set up providers"** section of the `docs/data/joy/integrations/material-ui/material-ui.md` documentation file.
> [joy-ui][docs] Update "Set up providers" section of integration with Material UI

- packages/mui-material/src/CircularProgress/CircularProgress.d.ts
- packages/mui-material/src/LinearProgress/LinearProgress.d.ts
- packages/mui-material/test/typescript/moduleAugmentation/progressProps.spec.tsx
Cherry-pick commit d580b43a48cedee8afdc11f130297dbf12b45b20. I forgot to add labels in #45163 for auto cherry-picking.
> [material-ui][LinearProgress][CircularProgress] Add variant overrides for module augmentation

- examples/material-ui-nextjs-pages-router-ts/src/Link.tsx
- examples/material-ui-nextjs-pages-router/src/Link.js
- packages/mui-docs/src/Link/Link.tsx
Fix this warning (only visible on local):
To repro, simply checkout master, run docs and visit the homepage.
Remove the usage of `legacyBehavior` on the docs' `Link` component ([source](https://github.com/mui/material-ui/blob/master/packages/mui-docs/src/Link/Link.tsx#L52)). This legacy behavior relies on accessing the child ref, causing the warning:
https://github.com/vercel/next.js/blob/38a6d0177eced9b56dfcc58f83662a659195af15/packages/next/src/client/link.tsx#L461
Here's the guide on removing this prop: https://github.com/vercel/next.js/commit/489e65ed98544e69b0afd7e0cfc3f9f6c2b803b7.
I think we can remove it as the only thing we're doing on `NextLinkComposed` is adding an empty styled anchor, which Next's `Link` now does by default: …
> [docs] Fix `element.ref` accessing warning on docs

- docs/public/_redirects
Since the `master` branch of this repo is now deployed under `next.mui.com`, we need to point to MUI X next docs.
Currently, https://next.mui.com/x/react-data-grid/ points to https://material-ui-x.netlify.app/x/introduction/, while it should point to https://docs-next--material-ui-x.netlify.app/
Preview: https://deploy-preview-45207--material-ui.netlify.app/x/react-data-grid/
> [docs-infra] Point to MUI X next docs

- CONTRIBUTING.md
Fix two links in CONTRIBUTING.md:
1. The "Checks and how to fix them" section seems to have been renamed to "CI checks and how to fix them", which broke the link in the markdown file;
2. [The link](https://github.community/t/branch-10-commits-behind/2403) that "behind its target branch" points to seems to have disappeared and now redirects to  GitHub's Community Discussions. In this case, I've opted to link to GitHub's docs about [keeping a PR in sync with its base branch](https://docs.github.com/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/keeping-your-pull-request-in-sync-with-the-base-branch). Feel free to suggest a better link if you know one
---
> [docs] Fix links in CONTRIBUTING.md

- docs/data/material/components/autocomplete/GitHubLabel.js
- docs/data/material/components/autocomplete/GitHubLabel.tsx
- docs/data/material/components/autocomplete/GoogleMaps.js
- docs/data/material/components/autocomplete/GoogleMaps.tsx
- docs/data/material/components/autocomplete/autocomplete.md
- packages/mui-docs/src/Ad/AdCarbon.tsx
- packages/mui-docs/src/utils/loadScript.ts
Initially, I thought I could quickly handle https://developers.google.com/maps/documentation/javascript/places-migration-autocomplete. It was much harder than expected 😅
Preview: https://deploy-preview-44708--material-ui.netlify.app/material-ui/react-autocomplete/#google-maps-place
I have tried to make the demo crash, like in #35391 but couldn't find a way.
We can use https://console.cloud.google.com/google/maps-apis/metrics?hl=en&inv=1&invt=Abjs3A&project=material-ui-docs to keep track of the API usage, make sure it's still OK.
---
As for why work on this, see https://github.com/NiazMorshed2007/shadcn-address-autocomplete/, unless the community builds this, we need to stay up to date to stay relevant.
---
Side note, we are supposed to give logo attribution: …
> [autocomplete][docs] Improve Google Maps search example

- packages/mui-material/src/Alert/Alert.d.ts
- packages/mui-material/src/CardHeader/CardHeader.d.ts
The `DetailsHTMLAttributes` is the HTML `details` element, not the `div`.
> [material-ui] Fix wrong `slotProps` of `DetailsHTMLAttributes` types

- docs/data/base/guides/working-with-tailwind-css/working-with-tailwind-css.md
- docs/data/material/guides/localization/localization.md
- docs/data/material/integrations/interoperability/interoperability.md
- docs/src/modules/sandbox/CreateReactApp.ts
We have a bunch of docs to update for Tailwind v4 #45220. Doing a quick first update to help.
> [docs] A quick first step to update docs for Tailwind v4

- docs/data/material/customization/color/ColorTool.js
Small tweak I added in https://github.com/mui/mui-toolpad/pull/2260
Moving fast over the grid sometimes gets you on top of the tooltip, and blocks hovering the color panel underneath. We can disable interaction to avoid that situation.
https://deploy-preview-37800--material-ui.netlify.app/material-ui/customization/color/#playground
Before:
https://github.com/mui/material-ui/assets/2109932/814d6e69-48f9-4c4e-b8e3-86ac8d309b42
After:
https://github.com/mui/material-ui/assets/2109932/a7f04553-fedf-46e5-be89-81b66c42f298
> [docs][material] Add disableInteractive on colorTool grid Tooltips

- scripts/useReactVersion.mjs
Currently it only updates the top-level dependency but there's a nested one in `@mui/internal-test-utils`. Makes the unit tests run (but not pass) for react 17.
Won't allocate more time to fixing these tests for now, but we may as well get this fix in.
> [code-infra] Fix testing library resolution with custom react

- CHANGELOG.md
- package.json
- packages/mui-codemod/package.json
- packages/mui-core-downloads-tracker/package.json
- packages/mui-docs/package.json
- packages/mui-icons-material/package.json
- packages/mui-lab/package.json
- packages/mui-material/package.json
- packages/mui-styles/package.json
- pnpm-lock.yaml
> [release] v6.4.4

- scripts/README.md
Follow-up on https://github.com/mui/material-ui/pull/45286#issuecomment-2650941715.
> [core] Update release guide to specify package bumping rules

- docs/data/material/migration/migrating-from-deprecated-apis/migrating-from-deprecated-apis.md
- docs/pages/material-ui/api/input-base.json
- docs/translations/api-docs/input-base/input-base.json
- packages/mui-codemod/README.md
- packages/mui-codemod/src/deprecations/all/deprecations-all.js
- packages/mui-codemod/src/deprecations/all/postcss.config.js
- packages/mui-codemod/src/deprecations/input-base-classes/index.js
- packages/mui-codemod/src/deprecations/input-base-classes/input-base-classes.js
- packages/mui-codemod/src/deprecations/input-base-classes/input-base-classes.test.js
- packages/mui-codemod/src/deprecations/input-base-classes/postcss-plugin.js
- packages/mui-codemod/src/deprecations/input-base-classes/postcss.config.js
- packages/mui-codemod/src/deprecations/input-base-classes/test-cases/actual.css
- packages/mui-codemod/src/deprecations/input-base-classes/test-cases/actual.js
- packages/mui-codemod/src/deprecations/input-base-classes/test-cases/expected.css
- packages/mui-codemod/src/deprecations/input-base-classes/test-cases/expected.js
- packages/mui-material/src/InputBase/inputBaseClasses.ts
part of https://github.com/mui/material-ui/issues/41282
> [material-ui][InputBase] Deprecate composed classes

- docs/data/material/components/material-icons/material-icons.md
Should be 'is no support' rather than 'are no support'.
This PR replaces https://github.com/mui/material-ui/pull/45310 as it was not specified correctly.
> [docs][icons] Fix typo in material-icons.md

- packages/mui-material/src/Button/Button.js
- packages/mui-material/src/Button/Button.test.js
- packages/mui-material/src/IconButton/IconButton.js
- packages/mui-material/src/IconButton/IconButton.test.js
We introduced an `id` attribute in all buttons when we introduced the `loading` prop in the `Button` component (https://github.com/mui/material-ui/pull/44637). We've got a couple of reports that some tests were broken because of this: https://github.com/mui/material-ui/pull/44637#issuecomment-2631635116
This PR changes the logic so the `id` attribute is only added when the loading indicator is present.
> [material-ui][Button] Apply id only if loading indicator is present

- packages/mui-icons-material/package.json
- scripts/copyFilesUtils.mjs
* Disallow access to `./esm/index.js` and `./modern/index.js` through `@mui/xyz/esm` and `@mui/xyz/modern`
* Disallow access to `@mui/icons-material/utils/createSvgIcon`
> Disallow access to esm/modern barrel files

- docs/public/static/error-codes.json
- packages/mui-material/src/styles/createTheme.test.js
- packages/mui-material/src/styles/createThemeNoVars.js
closes #44429
closes #34278
If the theme is already created with CSS theme variables, don't throw the error.
Next step (separate PR), create a documentation for recommended approach of the nested theme with CSS variables.
> [material-ui] Allow nested theme creation with `vars`

- packages/mui-material/src/internal/SwitchBase.d.ts
- packages/mui-material/src/internal/SwitchBase.js
- packages/mui-material/src/internal/SwitchBase.test.js
> [material-ui][SwitchBase] Deprecate `inputProps` and complete slots, slotProps

- docs/data/material/components/snackbars/ConsecutiveSnackbars.js
- docs/data/material/components/snackbars/ConsecutiveSnackbars.tsx
- docs/data/material/components/snackbars/DirectionSnackbar.js
- docs/data/material/components/snackbars/DirectionSnackbar.tsx
- docs/data/material/components/snackbars/TransitionsSnackbar.js
- docs/data/material/components/snackbars/TransitionsSnackbar.tsx
- docs/data/material/components/snackbars/TransitionsSnackbar.tsx.preview
- docs/pages/material-ui/api/snackbar.json
- docs/translations/api-docs/snackbar/snackbar.json
- packages/mui-codemod/README.md
- packages/mui-codemod/src/deprecations/all/deprecations-all.js
- packages/mui-codemod/src/deprecations/snackbar-props/index.js
- packages/mui-codemod/src/deprecations/snackbar-props/snackbar-props.js
- packages/mui-codemod/src/deprecations/snackbar-props/snackbar-props.test.js
- packages/mui-codemod/src/deprecations/snackbar-props/test-cases/actual.js
- packages/mui-codemod/src/deprecations/snackbar-props/test-cases/expected.js
- packages/mui-codemod/src/deprecations/snackbar-props/test-cases/theme.actual.js
- packages/mui-codemod/src/deprecations/snackbar-props/test-cases/theme.expected.js
- packages/mui-material/src/Snackbar/Snackbar.d.ts
- packages/mui-material/src/Snackbar/Snackbar.js
- packages/mui-material/src/Snackbar/Snackbar.spec.tsx
- packages/mui-material/src/Snackbar/Snackbar.test.js
> [material-ui][Snackbar] Add Slots and SlotProps (#45103)

- test/e2e/TestViewer.js
- test/regressions/TestViewer.js
Cherry-pick #44935
We need to cherry-pick it to avoid the increased regression-test times in the `v5.x` branch.
> [v5.x][core] Remove Suspense and clock mocking from regressions and e2e tests (#44935)

- packages/mui-material/src/Alert/Alert.d.ts
- packages/mui-material/src/CardHeader/CardHeader.d.ts
> [material-ui] Fix wrong slotProps of DetailsHTMLAttributes types

- docs/pages/material-ui/api/checkbox.json
- docs/pages/material-ui/api/radio.json
- docs/pages/material-ui/api/switch.json
- docs/translations/api-docs/checkbox/checkbox.json
- packages/mui-material/src/Checkbox/Checkbox.d.ts
- packages/mui-material/src/Checkbox/Checkbox.js
- packages/mui-material/src/Checkbox/Checkbox.spec.tsx
- packages/mui-material/src/Checkbox/Checkbox.test.js
- packages/mui-material/src/Radio/Radio.js
- packages/mui-material/src/Switch/Switch.js
- packages/mui-material/src/internal/SwitchBase.d.ts
> [material-ui][Checkbox] Add slots and slotProps

- docs/data/material/migration/migrating-from-deprecated-apis/migrating-from-deprecated-apis.md
- docs/pages/material-ui/api/speed-dial-action.json
- docs/translations/api-docs/speed-dial-action/speed-dial-action.json
- packages/mui-codemod/src/deprecations/speed-dial-action-props/index.js
- packages/mui-codemod/src/deprecations/speed-dial-action-props/speed-dial-action-props.js
- packages/mui-codemod/src/deprecations/speed-dial-action-props/speed-dial-action-props.test.js
- packages/mui-codemod/src/deprecations/speed-dial-action-props/test-cases/actual.js
- packages/mui-codemod/src/deprecations/speed-dial-action-props/test-cases/expected.js
- packages/mui-codemod/src/deprecations/speed-dial-action-props/test-cases/theme.actual.js
- packages/mui-codemod/src/deprecations/speed-dial-action-props/test-cases/theme.expected.js
- packages/mui-codemod/src/deprecations/utils/movePropIntoSlotProps.js
- packages/mui-material/src/SpeedDialAction/SpeedDialAction.d.ts
- packages/mui-material/src/SpeedDialAction/SpeedDialAction.js
- packages/mui-material/src/SpeedDialAction/SpeedDialAction.test.js
> [material-ui][SpeedDialAction] Add slots and slotProps

- docs/pages/material-ui/api/speed-dial.json
- packages/mui-material/src/Accordion/Accordion.d.ts
- packages/mui-material/src/Accordion/Accordion.spec.tsx
- packages/mui-material/src/Backdrop/Backdrop.d.ts
- packages/mui-material/src/Dialog/Dialog.d.ts
- packages/mui-material/src/Dialog/Dialog.spec.tsx
- packages/mui-material/src/Popover/Popover.d.ts
- packages/mui-material/src/Popover/Popover.spec.tsx
- packages/mui-material/src/Snackbar/Snackbar.d.ts
- packages/mui-material/src/Snackbar/Snackbar.spec.tsx
- packages/mui-material/src/SpeedDial/SpeedDial.d.ts
- packages/mui-material/src/StepContent/StepContent.d.ts
- packages/mui-material/src/StepContent/StepContent.spec.tsx
- packages/mui-material/src/Tooltip/Tooltip.d.ts
- packages/mui-material/src/Tooltip/Tooltip.spec.tsx
> [material-ui] Fix `slotProps.transition` types

- docs/data/material/components/drawers/ResponsiveDrawer.js
- docs/data/material/components/drawers/ResponsiveDrawer.tsx
- docs/data/material/components/drawers/SwipeableEdgeDrawer.js
- docs/data/material/components/drawers/SwipeableEdgeDrawer.tsx
- docs/data/material/migration/migrating-from-deprecated-apis/migrating-from-deprecated-apis.md
- docs/pages/material-ui/api/drawer.json
- docs/pages/material-ui/api/swipeable-drawer.json
- docs/translations/api-docs/drawer/drawer.json
- docs/translations/api-docs/swipeable-drawer/swipeable-drawer.json
- packages-internal/test-utils/src/describeConformance.tsx
- packages/mui-codemod/src/deprecations/all/deprecations-all.js
- packages/mui-codemod/src/deprecations/drawer-props/drawer-props.js
- packages/mui-codemod/src/deprecations/drawer-props/drawer-props.test.js
- packages/mui-codemod/src/deprecations/drawer-props/index.js
- packages/mui-codemod/src/deprecations/drawer-props/test-cases/actual.js
- packages/mui-codemod/src/deprecations/drawer-props/test-cases/expected.js
- packages/mui-codemod/src/deprecations/drawer-props/test-cases/theme.actual.js
- packages/mui-codemod/src/deprecations/drawer-props/test-cases/theme.expected.js
- packages/mui-material/src/Drawer/Drawer.d.ts
- packages/mui-material/src/Drawer/Drawer.js
- packages/mui-material/src/Drawer/Drawer.spec.tsx
- packages/mui-material/src/Drawer/Drawer.test.js
- packages/mui-material/src/SwipeableDrawer/SwipeableDrawer.d.ts
- packages/mui-material/src/SwipeableDrawer/SwipeableDrawer.js
- packages/mui-material/src/SwipeableDrawer/SwipeableDrawer.test.js
> [material-ui][Drawer] Deprecate *Props and complete `slots`, `slotProps`

- docs/data/material/components/autocomplete/Sizes.js
- docs/data/material/components/autocomplete/Sizes.tsx
If you're not using `multiple`, there's no need to pass the `renderTags` prop because it is only used when multiple selections are allowed.
Preview: https://deploy-preview-45401--material-ui.netlify.app/material-ui/react-autocomplete/#sizes
> [docs][Autocomplete] Remove unnecessary renderTags prop from Sizes demo

- docs/data/material/migration/upgrade-to-v7/upgrade-to-v7.md
- packages/mui-material/src/StepButton/StepButton.d.ts
This type has been deprecated since https://github.com/mui/material-ui/pull/20342.
The migration is manageable through search and replace, so I'm not currently adding a codemod. We can add one in the future if users report issues.
> [StepButton] Remove StepIconButton type

- docs/data/material/components/grid-legacy/ResponsiveGrid.js
- docs/data/material/components/grid-legacy/ResponsiveGrid.tsx
- docs/data/material/components/grid/ResponsiveGrid.js
- docs/data/material/components/grid/ResponsiveGrid.tsx
- docs/data/material/migration/upgrade-to-v7/upgrade-to-v7.md
- docs/src/pages/premium-themes/onepirate/modules/components/Button.js
- docs/src/pages/premium-themes/onepirate/modules/components/Button.tsx
- docs/src/pages/premium-themes/onepirate/modules/form/FormFeedback.js
- docs/src/pages/premium-themes/onepirate/modules/form/FormFeedback.tsx
- packages/mui-material/src/StyledEngineProvider/index.d.ts
- packages/mui-material/src/StyledEngineProvider/index.js
- packages/mui-material/src/index.d.ts
- packages/mui-material/src/styles/createTheme.ts
- packages/mui-material/src/styles/createThemeNoVars.d.ts
- packages/mui-material/src/styles/createThemeNoVars.js
- packages/mui-material/src/styles/index.d.ts
- packages/mui-material/src/styles/index.js
The following exports have been deprecated since v5:
- `createMuiTheme`
- `experimentalStyled`
- `StyledEngineProvider` from `@mui/material`
We can safely remove them, all have updated exports to replace them. The migration is manageable through search and replace, so I'm not currently adding a codemod. We can add one in the future if users report issues.
> [material-ui][styles] Remove deprecated exports

- docs/data/material/components/menus/ContextMenu.js
- docs/data/material/components/menus/ContextMenu.tsx
> [fix] Fix Context Menu selection lost on Safari

- docs/src/modules/components/DemoSandbox.js
Originally reported [here](https://mui-org.slack.com/archives/C05SBSU8NPR/p1740007650950449).
When dark mode is enabled and we have scrollable demos displayed in an iframe, users see the following:
Adding the `color-scheme` to the document element:
---
Can be tested locally by making the following changes:
```diff
diff --git a/docs/data/material/components/buttons/BasicButtons.tsx b/docs/data/material/components/buttons/BasicButtons.tsx
index 60eb1dfe1e..253383b5b6 100644
--- a/docs/data/material/components/buttons/BasicButtons.tsx
+++ b/docs/data/material/components/buttons/BasicButtons.tsx
@@ -4,7 +4,13 @@ import Button from '@mui/material/Button';
export default function BasicButtons() {
return (
-    <Stack spacing={2} direction="row">
+    <Stack spacing={2} direction="column" sx={{ …
```
> [docs-infra] Add `color-scheme` to document in iframe demos

- docs/src/modules/components/AppSettingsDrawer.js
https://github.com/user-attachments/assets/0b34c6a4-e5a7-4499-8cfa-fa236c2db063
Bug from https://github.com/mui/material-ui/pull/45354.
The `onChange` call should receive 2 arguments `event, paletteMode`.
> [docs-infra] Fix theme toggle call

- packages/mui-private-theming/package.json
- packages/mui-styled-engine-sc/package.json
- packages/mui-styled-engine/package.json
Needed to bump these to `beta.0` as well after https://github.com/mui/material-ui/pull/45413 was merged
> [release] Fix versions

- scripts/buildTypes.mts
Uncovered when someone tried to publish from a project folder named `material-ui.git`
This function was copied from the base ui codebase. Checking for non-existence of a dot is a poor way of detecting folders. We can't build this without actually checking whether `src` is a folder.
> [code-infra] Fix build:types script omitting folders with a dot in their name

- docs/data/material/migration/migrating-from-deprecated-apis/migrating-from-deprecated-apis.md
- docs/pages/material-ui/api/rating.json
- docs/translations/api-docs/rating/rating.json
- packages/mui-codemod/README.md
- packages/mui-codemod/src/deprecations/all/deprecations-all.js
- packages/mui-codemod/src/deprecations/rating-props/index.js
- packages/mui-codemod/src/deprecations/rating-props/rating-props.js
- packages/mui-codemod/src/deprecations/rating-props/rating-props.test.js
- packages/mui-codemod/src/deprecations/rating-props/test-cases/actual.js
- packages/mui-codemod/src/deprecations/rating-props/test-cases/expected.js
- packages/mui-codemod/src/deprecations/rating-props/test-cases/theme.actual.js
- packages/mui-codemod/src/deprecations/rating-props/test-cases/theme.expected.js
- packages/mui-material/src/Rating/Rating.d.ts
- packages/mui-material/src/Rating/Rating.js
- packages/mui-material/src/Rating/Rating.test.js
> [material-ui][Rating] Deprecate *Props and complete slots, slotProps (#45295)

- CHANGELOG.md
- package.json
- packages/mui-core-downloads-tracker/package.json
- packages/mui-docs/package.json
- packages/mui-icons-material/package.json
- packages/mui-lab/package.json
- packages/mui-material-nextjs/package.json
- packages/mui-material-pigment-css/package.json
- packages/mui-material/package.json
- packages/mui-private-theming/package.json
- packages/mui-styles/package.json
- packages/mui-system/package.json
- packages/mui-utils/package.json
- pnpm-lock.yaml
Discovered in https://github.com/mui/mui-x/pull/16684
We need to manually update the `@mui/utils` and `@mui/material-nextjs` packages to support range dependencies (e.g., `^7.0.0-beta`). They weren't updated on beta.1 as they didn't have any changes.
Also includes https://github.com/mui/material-ui/pull/45433
We need a new release of all packages that have dependencies on these.
> [release] 7.0.0-beta.2

- packages/mui-codemod/codemod.js
Fixes https://github.com/mui/material-ui/issues/45445
After https://github.com/mui/material-ui/pull/43264, the codemod package no longer packages the codemods inside the `./node` folder, but in the root (`./`). We have to update the codemod script to search in `./` instead of `./node`.
Layout before: https://unpkg.com/browse/@mui/codemod@6.4.6/
Layout after: https://unpkg.com/browse/@mui/codemod@7.0.0-beta.1/
> [codemod] Fix codemods not found

- .circleci/config.yml
- package.json
- packages/mui-icons-material/package.json
- packages/mui-material-nextjs/package.json
- packages/mui-material/package.json
- pnpm-lock.yaml
Fix "moduleResolution: node" for the icons package as per https://github.com/mui/material-ui/issues/43938#issuecomment-2691053800
We moved to a single declaration file for all icons but this breaks under classic module resolution. This can be fixed using `typesVersions`.
I'm also adding `attw` checks in CI to avoid this from regression again. (Opening https://github.com/arethetypeswrong/arethetypeswrong.github.io/issues/242 along the way)
> Fix moduleResolution:node for icons

- packages/mui-material/src/Radio/Radio.js
- packages/mui-material/src/Radio/Radio.test.js
closes #45447
The `slotProps.input` is explicitly passed to SwitchBase which always override `inputProps`.
Did the same as the Checkbox by fallback the `slotProps.input` to `inputProps`.
> [Radio] Fix `inputProps` not forwarded

- packages/mui-utils/package.json
I had the issue that generating an SBOM with https://github.com/CycloneDX/cyclonedx-node-npm#readme created invalid sboms since the homepage had an invalid iri-reference 
Do I need to create a PR for the 5.x and 6.x branches as well?
> [material-ui][utils] use correct iri-reference homepage format [NOTICKET]

- packages/mui-material/src/TextareaAutosize/TextareaAutosize.test.tsx
- packages/mui-material/src/TextareaAutosize/TextareaAutosize.tsx
- pnpm-lock.yaml
Cherry-pick #44540
Cherry-pick #45351
Cherry-picking this as it fixes a regression, which is covered in LTS.
> [material-ui][TextareaAutosize] Temporarily disconnect ResizeObserver to avoid loop error (#44540)

- docs/pages/material-ui/api/speed-dial.json
- docs/translations/api-docs/speed-dial/speed-dial.json
- packages/mui-material/src/SpeedDial/SpeedDial.d.ts
- packages/mui-material/src/SpeedDial/SpeedDial.js
- packages/mui-material/src/SpeedDial/SpeedDial.test.js
This PR #40698 missed adding root slot, I've added it to make it consistent across components
> [material-ui][SpeedDial] Add missing `root` slot

- docs/pages/material-ui/api/list-item-text.json
- docs/translations/api-docs/list-item-text/list-item-text.json
- packages/mui-material/src/ListItemText/ListItemText.d.ts
- packages/mui-material/src/ListItemText/ListItemText.js
- packages/mui-material/src/ListItemText/ListItemText.test.js
This PR #44571 missed adding root slot, I've added it to make it consistent across components
> [material-ui][ListItemText] Add missing `root` slot

- packages/mui-material/src/styles/createTheme.test.js
- packages/mui-system/src/spacing/spacing.js
- packages/mui-system/src/spacing/spacing.test.js
closes #45500 
Using negative spacing input does not work
```js
const theme =createTheme({ cssVariables: true, spacing: [0, 4, 8] });
theme.spacing(-2) // ❌ does not work, it should produce `calc(-1 * var(--mui-spacing-2))`
```
The logic does not handle the negative input, e.g. `theme.spacing(-2)` when the spacing input is an array and CSS variables enabled.
Please see the tests.
This PR also include improvements for input value as `0` and `1` to save some bytes.
**Before**:
```js
theme.spacing(0); // calc(0 * var(--mui-spacing))
theme.spacing(1); // calc(1 * var(--mui-spacing))
```
**After**:
```js
theme.spacing(0); // 0
theme.spacing(1); // var(--mui-spacing)
```
---
> [material-ui] Fix negative input for CSS variables spacing array

- packages/mui-material/src/Typography/Typography.d.ts
- packages/mui-material/src/styles/adaptV4Theme.d.ts
- packages/mui-material/src/styles/createThemeNoVars.d.ts
- packages/mui-material/src/styles/createTypography.d.ts
- packages/mui-material/src/styles/index.d.ts
- packages/mui-material/src/styles/responsiveFontSizes.d.ts
Rename some interfaces to match the publicly exported ones. `@mui/material/styles/createTypography` is not exported and these are aliased and publicly exported in `@mui/material/styles`. this way we can remove the alias, there is no need to have an internal name that is different from the public one.
https://github.com/mui/material-ui/blob/9ab5dcf63fabfd70243a4ac1486f659793b79e7f/packages/mui-material/src/styles/index.d.ts#L27-L32
=>
https://github.com/mui/material-ui/blob/a867bfcbd3136820b69ad09a6284d24fdc978c0c/packages/mui-material/src/styles/index.d.ts#L27-L32
This is not a breaking change if you're importing from `@mui/material/styles`, if you're importing from `@mui/material/styles/createTheme` then it will already break due to the subpath not being exported.
> [core] Rename some `@mui/material/styles/createTypography` exports

- docs/pages/blog/material-ui-2024-updates.md
- docs/src/modules/components/TopLayoutBlog.js
It looks like https://github.com/mui/material-ui/pull/44722 was largely contributed by Ale, so would make sense to have it listed.
> [blog] Fix author end-of-year updates

- CHANGELOG.md
- package.json
- packages-internal/scripts/package.json
- packages/mui-base/package.json
- packages/mui-codemod/package.json
- packages/mui-core-downloads-tracker/package.json
- packages/mui-docs/package.json
- packages/mui-icons-material/package.json
- packages/mui-lab/package.json
- packages/mui-material-nextjs/package.json
- packages/mui-material-pigment-css/package.json
- packages/mui-material/package.json
- packages/mui-private-theming/package.json
- packages/mui-styled-engine/package.json
- packages/mui-styles/package.json
- packages/mui-system/package.json
- packages/mui-types/package.json
- packages/mui-utils/package.json
Release v7.0.0-beta.4.
- We’ll include `@mui/base` in this release, as we need a version with the package layout updates because `@mui/lab` depends on it
- We will release two versions of `@mui/types`: `7.3.0` for v7 and `7.2.24` for v5 and v6. This PR includes `7.3.0`. The `7.2.24` release will be made from the `v6.x` branch.
> [release] v7.0.0-beta.4

- scripts/build.mjs
- scripts/utils.mjs
For https://github.com/mui/mui-x/pull/16931
Also to avoid hitting the filesystem twice to read package.json
> [code-infra] Make `getVersionEnvVariables` reusable for other repos

- apps/pigment-css-next-app/package.json
- apps/pigment-css-vite-app/package.json
- docs/package.json
- package.json
- packages-internal/scripts/package.json
- packages-internal/test-utils/package.json
- packages/mui-base/package.json
- packages/mui-docs/package.json
- packages/mui-envinfo/test/package.json
- packages/mui-icons-material/package.json
- packages/mui-joy/package.json
- packages/mui-lab/package.json
- packages/mui-material-nextjs/package.json
- packages/mui-material/package.json
- packages/mui-private-theming/package.json
- packages/mui-styled-engine-sc/package.json
- packages/mui-styled-engine/package.json
- packages/mui-styles/package.json
- packages/mui-system/package.json
- packages/mui-types/package.json
- packages/mui-utils/package.json
- pnpm-lock.yaml
- test/package.json
We will start releasing `@mui/types` `7.2.x` from this branch. This PR cherry picks all the changes already in `7.2.23` (last released from master) so we don't introduce any regressions. The only changes to the types package since the `v6.x` branch split are `@types/react` updates: https://github.com/mui/material-ui/commits/260ed53760f179e3bb4f1f43e2f2712ecbf9fdd7/packages/mui-types
> [v6.x] Bump @types/react to ^19.0.10

- packages/mui-material/src/styles/ThemeProvider.js
- packages/mui-material/src/styles/ThemeProvider.test.tsx
- packages/mui-material/src/styles/createTheme.js
- packages/mui-material/src/styles/createTheme.test.js
- pnpm-lock.yaml
Cherry pick from https://github.com/mui/material-ui/pull/45545 and https://github.com/mui/material-ui/pull/45368
Need this PR to release on v5 because MUI X docs depends on this version. To unblock #45386 so that the docs (both core and x) can migrate to CSS variables to fix the dark mode flicker issue.
> [material-ui] Support nested theme when upper theme is CSS vars theme

- docs/package.json
- packages/mui-base/package.json
- packages/mui-joy/package.json
- packages/mui-lab/package.json
- packages/mui-material/package.json
- packages/mui-private-theming/package.json
- packages/mui-styles/package.json
- packages/mui-system/package.json
- packages/mui-utils/package.json
- pnpm-lock.yaml
Use`~` instead of `^` for `@mui/types` dependency, so v5 packages don't resolve to `7.3.0` or higher
> [v5.x][core] Fix types version

- CHANGELOG.md
- package.json
- packages/mui-base/package.json
- packages/mui-core-downloads-tracker/package.json
- packages/mui-docs/package.json
- packages/mui-icons-material/package.json
- packages/mui-joy/package.json
- packages/mui-lab/package.json
- packages/mui-material/package.json
- packages/mui-private-theming/package.json
- packages/mui-styles/package.json
- packages/mui-system/package.json
- packages/mui-utils/package.json
- scripts/releaseChangelog.mjs
Release version 5.17.1.
We need this to update the `@mui/types` dependencies to not use `7.3.0`, due to https://github.com/mui/material-ui/issues/45510
> [release] v5.17.1

- docs/src/components/home/ToolpadCoreShowcaseDemo.tsx
- docs/src/components/home/ToolpadShowcase.tsx
- docs/src/modules/components/MuiProductSelector.tsx
* Remove Toolpad Studio from the homepage showcases
* Remove Toolpad Studio from the docs menu
> [docs] Deprecate Toolpad Studio

- docs/pages/material-ui/api/switch.json
- docs/translations/api-docs/switch/switch.json
- packages/mui-material/src/Switch/Switch.d.ts
- packages/mui-material/src/Switch/Switch.js
- packages/mui-material/src/Switch/Switch.test.js
> [material-ui][Switch] Add slots and slotProps (#45595)

- docs/data/material/integrations/nextjs/nextjs.md
Updated line 106 and 107 as per https://github.com/mui/material-ui/issues/45537#issuecomment-2727831866
Fixes the issue of --font-[variant] CSS custom property not computing the value correctly when next js font is applied to `<body>` instead of `<html/>`
> [docs] Update nextjs font optimization guide

- packages/mui-docs/package.json
- packages/mui-docs/src/translations/index.ts
Fixes: https://mui-org.slack.com/archives/C042YB5RB3N/p1742407588778789
Related question: do we need the node build, which does not look like it works..? 🤔 🤷
> [code-infra] Ensure `translations.json` is present in all `@mui/docs` package builds

- packages/mui-material/src/styles/ThemeProviderWithVars.test.js
- packages/mui-system/src/cssVars/createCssVarsProvider.js
Regression from https://github.com/mui/material-ui/pull/45405
Found this issue while updating the MUI X docs.
If light and dark color schemes are used without CSS variables, the `theme.palette.mode` does not update correctly.
The `theme.palette.mode` should change when light and dark color schemes are used without CSS variables
Test added.
---
> [system] Fix palette mode does not change when not use CSS vars

- docs/src/modules/components/AppNavDrawerItem.tsx
Bring back the export that was removed in https://github.com/mui/material-ui/pull/45548/. Toolpad docs are relying on it
> [docs] export `sxChip` again from `AppNavDrawerItem`

- docs/data/material/components/breadcrumbs/CustomizedBreadcrumbs.js
- docs/data/material/components/breadcrumbs/CustomizedBreadcrumbs.tsx
- docs/data/material/components/breadcrumbs/PageContainerBasic.js
- docs/data/material/components/breadcrumbs/PageContainerBasic.tsx
- docs/data/material/components/breadcrumbs/breadcrumbs.md
- docs/data/material/components/dividers/DividerText.js
- docs/data/material/components/dividers/DividerText.tsx
- docs/data/material/components/lists/InteractiveList.js
- docs/data/material/components/lists/InteractiveList.tsx
- docs/data/material/components/typography/TypographyTheme.js
- docs/data/material/components/typography/TypographyTheme.tsx
> [docs] Fix `Breadcrumbs`, `List`, `Divider`, and `Typography` dark mode demos

- packages/mui-material/src/Fab/Fab.js
Fixes https://github.com/mui/material-ui/issues/45712
|before|after|
|---|---|
|<img width="379" alt="Screenshot 2025-03-27 at 15 20 24" src="https://github.com/user-attachments/assets/7c8e7aaa-a292-4d81-8371-7edcb1455cbf" />|<img width="382" alt="Screenshot 2025-03-27 at 15 21 38" src="https://github.com/user-attachments/assets/3388cd80-e4a3-4465-891b-fad6cbf283cf" />|
|<img width="384" alt="Screenshot 2025-03-27 at 15 20 16" src="https://github.com/user-attachments/assets/139f930c-d568-4e4a-b8ad-e64da477fdb4" />|<img width="393" alt="Screenshot 2025-03-27 at 15 21 44" src="https://github.com/user-attachments/assets/506feda6-f603-45ac-906b-44934c38a47b" />|
> [material-ui][Fab] Fix default variant text color when using CSS vars

- packages/mui-docs/src/NProgressBar/NProgressBar.js
Fixes https://github.com/mui/material-ui/issues/45707
Currently, all [joy templates](https://mui.com/joy-ui/getting-started/templates/) throw error.
The `NProgressBar` is used in all of the joy templates. It try to access `theme.applyDarkStyles` but the branding theme was removed from the global `_app.js` so the error appear.
Fixed by replacing `applyDarkStyles` (was internal for docs) with official `applyStyles` that comes with the default theme. 
~I took an extra step to replace all occurrences of `applyDarkStyles` because it's no longer needed.~ (split to another PR)
Next step:
- create another PR to replace all occurrences and do the same for MUI X repo
- remove `applyDarkStyles` from the core docs
---
> [docs] Fix joy templates error

- docs/src/modules/components/AppLayoutDocs.js
Before this change, "undefined" was showing up in the versions docs page title https://mui.com/versions/
> [docs] Avoid unwanted undefined in page title

- docs/data/material/getting-started/overview/overview.md
- docs/data/material/migration/upgrade-to-v6/migrating-to-pigment-css.md
- docs/src/pages/versions/versions.md
- examples/material-ui-cra-tailwind-ts/README.md
- examples/material-ui-cra-ts/README.md
- examples/material-ui-cra/README.md
- examples/material-ui-express-ssr/README.md
- examples/material-ui-gatsby/README.md
- examples/material-ui-nextjs-pages-router-ts/README.md
- examples/material-ui-nextjs-pages-router/README.md
- examples/material-ui-nextjs-ts-v4-v5-migration/README.md
- examples/material-ui-preact/README.md
- examples/material-ui-remix-ts/README.md
- examples/material-ui-vite-ts/README.md
- examples/material-ui-vite/README.md
- Updates some outdated copy after the v7 release.
- Updates v7 to "released" in https://mui.com/versions/
> [docs] Update v7 related copy

- docs/data/material/components/breadcrumbs/PageContainerBasic.js
- docs/data/material/components/breadcrumbs/PageContainerBasic.tsx
- docs/data/material/components/masonry/BasicMasonry.js
- docs/data/material/components/masonry/BasicMasonry.tsx
- docs/data/material/components/masonry/FixedColumns.js
- docs/data/material/components/masonry/FixedColumns.tsx
- docs/data/material/components/masonry/FixedSpacing.js
- docs/data/material/components/masonry/FixedSpacing.tsx
- docs/data/material/components/masonry/ImageMasonry.js
- docs/data/material/components/masonry/ImageMasonry.tsx
- docs/data/material/components/masonry/MasonryWithVariableHeightItems.js
- docs/data/material/components/masonry/MasonryWithVariableHeightItems.tsx
- docs/data/material/components/masonry/ResponsiveColumns.js
- docs/data/material/components/masonry/ResponsiveColumns.tsx
- docs/data/material/components/masonry/ResponsiveSpacing.js
- docs/data/material/components/masonry/ResponsiveSpacing.tsx
- docs/data/material/components/masonry/SSRMasonry.js
- docs/data/material/components/masonry/SSRMasonry.tsx
- docs/data/material/components/masonry/Sequential.js
- docs/data/material/components/masonry/Sequential.tsx
- Masonry demos does not appear correctly on dark mode
- On dark mode, navigating to Container or Breadcrumbs page instantly switched to light mode.
- Masonry: the demos are not using CSS variables.
- For breadcrumbs and container page, the issue comes from the Toolpad demo (the bottom of the page). Toolpad uses different key for storing mode in the local storage, so when landing on those pages Toolpad will start as `system` mode (resulted as `light` in daylight environment).
- Masonry: apply `(theme.vars || theme)` to colors
- Toolpad: remove CSS variables from the theme, so that Toolpad uses the same context from the page level and mode is synchronized.
---
> [docs] Fix Masonry and Toolpad dark mode demos 

- packages/mui-utils/src/useForkRef/useForkRef.test.js
- packages/mui-utils/src/useForkRef/useForkRef.ts
Fixes https://github.com/mui/material-ui/issues/45538#issuecomment-2718840105
Same as https://github.com/mui/base-ui/pull/1553
Before: https://codesandbox.io/p/devbox/material-ui-cra-ts-forked-8rrpf7?workspaceId=ws_HE9JRzFW36Y2kpBoSwdvZ5
After: https://codesandbox.io/p/sandbox/material-ui-cra-ts-forked-thfy25
> [utils] Support cleanup callbacks in useForkRef

- .github/workflows/closed-issue-message.yml
See https://docs.github.com/en/actions/sharing-automations/reusing-workflows#creating-a-reusable-workflow for what `workflow_call:` is for. Since we don't plan on reusing this workflow, It looks like we should remove this, to not create confusion.
> [support-infra] Remove dead 'workflow_call:'

- docs/data/docs-infra/pages.ts
- docs/pages/_document.js
- docs/pages/experiments/docs/pro-feature.js
- docs/pages/experiments/docs/pro-feature.md
I was annoyed by this when browsing the docs. See how the layout of the page changes when you move from an MIT to a commercial feature https://mui.com/x/react-data-grid/tree-data/. I have created a simpler reproduction in:
https://github.com/user-attachments/assets/d90e3156-8c8e-427b-8373-bb1d65590dcc
After: https://deploy-preview-45760--material-ui.netlify.app/experiments/docs/pro-feature/
> [docs-infra] Fix layout shift between MIT and commercial pages

- packages/mui-material-nextjs/src/nextCompatRouter.cjs
- packages/mui-material-nextjs/src/v13-appRouter/appRouterV13.tsx
- packages/mui-material-nextjs/src/v13-appRouter/nextNavigation.cjs
- packages/mui-material-nextjs/src/v13-pagesRouter/pagesRouterV13App.tsx
Closes https://github.com/mui/material-ui/issues/45731#issuecomment-2767119561
* Make sure `next/navigation` can be imported correctly under ESM.
* Add warnings to `@mui/material-ui-nextjs` when used under the wrong router implementation.
> [nextjs] Add warnings to nextjs router integration

- .eslintrc.js
- package.json
- pnpm-lock.yaml
- scripts/build.mjs
- scripts/buildTypes.mts
- scripts/utils.mjs
Some of the notable changes -
* Updated `getWorkspaceRoot` function to get the root directory relative to the current working directory. This would allow us to use this function across other repos as well. Without this change, it would return a directory inside `node_modules` when used in other repos.
* Updated the build script to customize the cjs output. Default continues to be the root of the `build` directory. This allows us to use this in `base-ui` repo to override this to `cjs` directory inside `build`.
* Updated `buildTypes.mts` script to optionally accept a list of directories to copy the emitted types to (from the default `esm` directory). The default has been set to `['build', 'build/modern']` to cater to core repo.
The scripts have been tested in both `base-ui` and `mui-next` …
> [core] Update scripts to support base-ui

- package.json
- pnpm-lock.yaml
- scripts/releaseTag.mjs
This will help in reusing this script across repos
> [core] Allow repo to be accepted as an argument for releaseTag

- packages/mui-material-nextjs/src/v13-pagesRouter/createCache.ts
- packages/mui-material-nextjs/src/v13-pagesRouter/index.ts
- packages/mui-material-nextjs/src/v13-pagesRouter/pagesRouterV13Document.tsx
Fixes https://github.com/mui/material-ui/issues/45774
* Add nonce to critical css style tags.
* Make `createEmotionCache` available to users and allow passing options.
This makes the [pages router example](https://github.com/mui/material-ui/tree/11f7526210f2ec6b27a20d7620c8020731cb0704/examples/material-ui-nextjs-pages-router-ts) work with strict CSP when making the following alterations:
```tsx
// ./middleware.ts
import { NextResponse } from "next/server";
import type { NextRequest } from "next/server";
import { generateNonce } from "./src/nonce";
export function middleware(request: NextRequest) {
// Generate unique nonce for each request
const nonce = generateNonce();
// Important: Store nonce in headers to access it throughout the request lifecycle
const requestHeaders = new …
```
> [nextjs] Fix nonce issues

- packages/mui-system/tsconfig.json
- packages/mui-types/src/index.spec.ts
- patches/styled-components.patch
- pnpm-lock.yaml
- pnpm-workspace.yaml
- tsconfig.json
It doesn't make sense to be able to resolve from the monorepo root everywhere in the project. Ideally these paths are defined on the package level, and mimic the workspace dependencies of that specific package only. 
Also removing skipLibCheck in @mui/system
> Remove baseUrl and skipLibCheck

- docs/data/material/migration/migrating-from-deprecated-apis/migrating-from-deprecated-apis.md
- packages/mui-codemod/README.md
The changes aim to improve the clarity and accuracy of migration instructions for various components.
Updates to migration documentation:
docs/data/material/migration/migrating-from-deprecated-apis/migrating-from-deprecated-apis.md: Updated migration instructions to include additional codemods for InputBase, Slider, and Tabs components. 
docs/data/material/migration/migrating-from-deprecated-apis/migrating-from-deprecated-apis.md: Corrected the codemod reference for the Rating component.
Updates to codemod references:
packages/mui-codemod/README.md: Added missing codemod command for avatar-props.
packages/mui-codemod/README.md: Corrected codemod commands for rating-props. 
packages/mui-codemod/README.md: Moved CSS transforms for step-connector-classes to an appropriate section.
> [docs] Update migration instructions and codemod references for deprecated APIs

- scripts/buildTypes.mts
This will be required later in the `mui-next` repo to remove all the import/export statements trying to import/export from '.css' files.
I have tested it locally in `mui-next` repo.
> [core] Update buildTypes script to optionally remove css imports

- docs/src/components/banner/AppFrameBanner.tsx
Follow up of https://github.com/mui/material-ui/pull/45838, it was missing the docs banner.
Preview: https://deploy-preview-45842--material-ui.netlify.app/material-ui/
> [docs] Add missing v7 docs banner

- docs/public/_redirects
Currently, open https://mui.com/system/styles/basics/ redirects to https://mui.com/system/system/styles/basics/ (not-found page).
Fixed by specific the i18n path.
---
> [docs-infra] Fix redirect styles pages

- docs/data/material/getting-started/installation/installation.md
Copy/pasting the command to install mui/icons-material fails because it tries and installs latest which needs material v7.x, but we explicitly are using v6.x. Updated the script to request v6 like the other install snippets on this page.
> [docs] Update `@mui/icons-material` install command to use 6.x version

- .mocharc.js
- package.json
- packages-internal/test-utils/src/createRenderer.tsx
- packages-internal/test-utils/src/setupBabel.js
- packages/mui-base/src/FocusTrap/FocusTrap.test.tsx
- packages/mui-base/src/Input/Input.test.tsx
- packages/mui-base/src/Portal/Portal.test.tsx
- packages/mui-base/src/useAutocomplete/useAutocomplete.test.js
- packages/mui-joy/src/Autocomplete/Autocomplete.test.tsx
- packages/mui-material/src/InputBase/InputBase.test.js
- packages/mui-material/src/Portal/Portal.test.tsx
- packages/mui-material/src/Select/Select.test.js
- packages/mui-material/src/Tabs/Tabs.test.js
- packages/mui-material/src/Unstable_TrapFocus/FocusTrap.test.tsx
- packages/mui-material/src/styles/ThemeProviderWithVars.test.js
- packages/mui-material/src/useAutocomplete/useAutocomplete.test.js
- packages/mui-system/src/cssVars/useCurrentColorScheme.test.js
- packages/mui-utils/src/useForkRef/useForkRef.test.tsx
- pnpm-lock.yaml
Related to https://github.com/testing-library/react-testing-library/pull/1390.
In React 19, `StrictMode` won't double-call effects on initial mount unless `StrictMode` is at the root of the app. Our previous way of enabling `StrictMode` created a `Wrapper`, meaning that the `Wrapper` component was at the root of the app, resulting in the double calling of effects not happening in initial mount in React 19.
This PR uses the new property `reactStrictMode` from `@testing-library/react` to enable double-calling on initial mount in React 19 tests.
This option was introduced in [this PR](https://github.com/testing-library/react-testing-library/pull/1390), that's why I also upgraded the dependency.
This PR also changes some tests. In the ones I was most confident, I actually updated the …
> [code-infra] Fix `StrictMode` effects not being called twice in React 19 tests

- docs/data/material/customization/overriding-component-structure/overriding-component-structure.md
- docs/pages/material-ui/api/avatar.json
- docs/translations/api-docs/avatar/avatar.json
- packages/mui-material/src/Avatar/Avatar.d.ts
- packages/mui-material/src/Avatar/Avatar.js
- packages/mui-material/src/Avatar/Avatar.spec.tsx
- packages/mui-material/src/Avatar/Avatar.test.js
closes #45443
This PR follows the option (2) solution explained in https://github.com/mui/material-ui/issues/45443#issuecomment-2709244574
The types of `slots.img` is too strict, not able to provide a custom component, .e.g. Next.js Image.
Change the slot type to `React.ElementType` which accept any React component or string. Please see the added spec.
I also use this opportunity to add missing slots (`root` and `fallback`) in this PR.
> [Avatar] Fix img slot types and add missing slots

- package.json
- packages/mui-docs/package.json
- packages/mui-icons-material/package.json
- scripts/buildTypes.mts
Forgot this in https://github.com/mui/material-ui/pull/45784
> [code-infra] Remove type generation of modern build

- docs/data/material/getting-started/templates/templates.md
There is a typo in documentation! Let's fix it :) 
Introduced in #45273
> [docs] Fix markdown typo in templates.md

- apps/pigment-css-vite-app/src/pages/fixtures/index.test.js
- package.json
- scripts/pushArgos.mjs
Remove the pigment logic form argos push script, just generate the screenshots in the same screenshots dir as core, it's the same outcome. (which was not ideal in the first place because it may overwrite but ok, will be fixed once pigment regression tests are moved to the pigment project)
Make the folder for argos push script configurable so we can reuse it more easily
> [code-infra] Make Argos upload script reusable

- docs/notifications.json
> [docs] Add notification for MUI X v8 announcement

- docs/data/joy/getting-started/installation/installation.md
- docs/data/material/components/about-the-lab/about-the-lab.md
- docs/data/material/components/icons/icons.md
- docs/data/material/components/material-icons/material-icons.md
- docs/data/material/getting-started/installation/installation.md
- docs/data/material/integrations/nextjs/nextjs.md
- docs/data/material/migration/migration-v4/migration-v4.md
- docs/data/system/getting-started/installation/installation.md
https://mui-org.slack.com/archives/C041SDSF32L/p1745416149123639
Reproduce: https://v6.mui.com/material-ui/getting-started/installation/
In HEAD, we should be good: https://github.com/mui/material-ui/blob/4a9d277e94c540daaed7466c4d821ff72f6b9b41/docs/data/material/getting-started/installation/installation.md?plain=1#L9
Preview: https://deploy-preview-45991--material-ui.netlify.app/material-ui/getting-started/installation/
> [docs] Ease migration to v5

- packages/mui-material/src/Chip/Chip.js
- packages/mui-material/src/Dialog/Dialog.js
- packages/mui-material/src/Slider/SliderValueLabel.tsx
This pull request simplifies the codebase by removing unnecessary uses of the `clsx` utility in several components within the `material-ui` package
> [material-ui] Remove unnecessary clsx usages

- packages/mui-styled-engine/src/index.d.ts
- packages/mui-system/src/styled/styled.spec.ts
There is a bug from https://github.com/mui/material-ui/pull/45478.
The props is not inferred from the `ownerState` values
```js
type OwnerState = {
variant?: 'success' | 'error' | 'processing';
showChanges: boolean;
};
const VariantObjects = styled('div')<{ ownerState: OwnerState } & OwnerState>({
font: 'inherit',
color: 'inherit',
variants: [
{
props: { variant: 'success' }, // ❌ variant is not inferred from the `ownerState`
style: {
color: 'red',
},
},
],
});
```
Found this when trying the master build on MUI X.
> [styled-engine] Infer `ownerState` from props in `styled`

- docs/src/modules/components/AppLayoutDocsFooter.js
- packages/feedback/package.json
- pnpm-lock.yaml
Similar to https://github.com/mui/mui-private/pull/858. Required for https://groups.google.com/a/mui.com/g/back-infra/c/t3EhZ2ssR0Q.
But actually, this feels quite outdated logic, https://www.notion.so/mui-org/docs-infra-Add-docs-page-feedback-rating-v2-1e8cbfe7b6608030ac27edc8c272ff83 created for the future.
> [docs-infra] Update feedback Node.js to v22

- packages/mui-lab/package.json
I don't know what happened, but the lab should be in the "alpha" per https://www.notion.so/mui-org/React-Major-version-release-process-0178410ef26941e6a4f333f80ded127a?pvs=4#76b607ce98cf45a49730f2af04e18dd3. It's not the case https://www.npmjs.com/package/@mui/lab?activeTab=versions. Adding a comment for Material UI v8. 
(The // is from https://stackoverflow.com/questions/14221579/how-do-i-add-comments-to-package-json-for-npm-install)
A bit related to #40662.
> [core] Add comment that lab should be in alpha

- docs/data/material/migration/upgrade-to-v6/upgrade-to-v6.md
- docs/data/material/migration/upgrade-to-v7/upgrade-to-v7.md
closes https://github.com/mui/material-ui/issues/45432
As discussed in the [slack channel](https://mui-org.slack.com/archives/C011VC970AW/p1745487685016599), updating the docs should be the first step because it's the lowest effort and will not impact MUI X.
Tested the resolution locally using this [repro](https://github.com/mui/material-ui/issues/45432#issuecomment-2693546206), it works.
---
> [docs] Update upgrade guide for resolution of `react-is`

- docs/data/material/components/grid/InteractiveGrid.js
- docs/data/material/components/grid/InteractiveGrid.tsx
> [docs][Grid] Remove direction `column` and `column-reverse` from the demo

- docs/data/material/migration/upgrade-to-v6/upgrade-to-v6.md
related to https://github.com/mui/material-ui/issues/44201#issuecomment-2844946485
This PR updates the migration guide to version 6 (`upgrade-to-v6.md`) by adding details about changes to the default behavior of the Grid component.
* **Grid Component Behavior**: Added a new section explaining that the updated Grid component no longer grows to the full width of the container by default. 
Above section is already present in https://mui.com/material-ui/migration/upgrade-to-grid-v2/#container-width but missing in https://mui.com/material-ui/migration/upgrade-to-v6/#grid2
preview: https://deploy-preview-46057--material-ui.netlify.app/material-ui/migration/upgrade-to-v6/#grid2
> [docs][material-ui][Grid] Update grid migration guide

- packages/mui-docs/src/HighlightedCode/HighlightedCode.tsx
Fixes this warning in development mode:
When `plainStyle` is true, the root becomes `React.Fragment`, which doesn't support the `ref` prop. 
Since no parent component uses a ref on `HighlightedCode`, I removed `forwardRef`. I also checked this in MUI X and Toolpad.
Also made sure `other` is spread only when using `MarkdownElement`.
> [code-infra] Remove unnecessary ref from `HighlightedCode` component

- packages/mui-material/src/styles/createTheme.spec.ts
- packages/mui-system/src/borders/borders.test.js
- packages/mui-system/src/createTheme/shape.d.ts
> [system] Update the type for borderRadius

- docs/data/material/components/dialogs/FullScreenDialog.js
- docs/data/material/components/dialogs/FullScreenDialog.tsx
address feedback from slack https://mui-org.slack.com/archives/C0757QYLK7V/p1747584742023829
> [docs][material-ui][Dialog] Remove deprecated TransitionComponent from demo

- packages/mui-material/src/SnackbarContent/SnackbarContent.js
- packages/mui-material/src/SnackbarContent/SnackbarContent.test.js
This PR fixes #46192 by the SnackbarContentRoot from applying the emphasize color function to `theme.palette.background.default`, ensuring correct theming behavior when using background defaults. Also added a test case to verify correct application of the CSS variable
> [SnackbarContent] Fix error when theme value is CSS variable

- packages-internal/test-utils/package.json
- packages-internal/test-utils/src/chaiPlugin.ts
- pnpm-lock.yaml
This would allow X to move to chai v5 https://github.com/mui/mui-x/pull/17575
It is probably a more sane approach too
> [code-infra] Move `chai` to peerDep

- packages/mui-material/src/styles/styled.spec.tsx
- packages/mui-styled-engine/src/index.d.ts
- packages/mui-system/src/styled/styled.spec.ts
The pattern below is logically correct based on the [implementation](https://github.com/mui/material-ui/blob/master/packages/mui-system/src/createStyled/createStyled.js#L73) but failed on type check.
```js
const DateTimePickerToolbarTimeContainer = styled('div', {
name: 'MuiDateTimePickerToolbar',
slot: 'TimeContainer',
shouldForwardProp: (prop) => shouldForwardProp(prop) && prop !== 'toolbarVariant',
})<{ ownerState: { pickerOrientation: 'landscape' | 'portrait'; toolbarVariant: PickerVariant }>({
display: 'flex',
flexDirection: 'row',
variants: [
{
// ❌ error
props: ({ pickerOrientation, toolbarVariant }) =>
pickerOrientation === 'landscape' && toolbarVariant !== 'desktop',
style: {
flexDirection: 'column',
},
},
],
});
```
This PR fixes the issue above. A test (using MUI X pickers …
> [types] Fix variant props callback type to spread `ownerState`

- packages/mui-material/src/Backdrop/Backdrop.js
- packages/mui-material/src/Backdrop/Backdrop.test.js
closes https://github.com/mui/material-ui/issues/46264
> [material-ui][Backdrop] Fix handling of `component` prop

- docs/data/material/components/rating/rating.md
This PR adds a new "Testing" section to the Rating component documentation.
Closes #38828 
When testing the Rating component in environments like Jest + jsdom, certain user interactions (e.g., hover-based selection) may not behave as expected. This is due to `getBoundingClientRect()` returning `0` values by default in jsdom, which can cause issues such as `NaN` being passed to the `onChange` handler.
- A warning about the limitation in test environments that do not fully implement layout behavior.
- A recommended test pattern using `fireEvent` instead of `userEvent`.
- A note on potential pitfalls when using `userEvent.click()` in such contexts.
```tsx
fireEvent.click(screen.getByLabelText("2 Stars"));
```
> [docs] Add Testing section to Rating component doc

- docs/data/material/components/dialogs/FormDialog.js
- docs/data/material/components/dialogs/FormDialog.tsx
Closes #46279 
Closes #41100
The `form` element was incorrectly added as a `Paper` component which has `role="dialog"` in #40470. This violates accessibility rules, as `form` elements can't have ARIA roles like `dialog` ([W3C spec](https://www.w3.org/TR/html-aria/#docconformance), [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/form#technical_summary)).
This fix removes the accessibility error from #46279 and #41100:
> Uses ARIA roles on incompatible elements
**Before:** https://mui.com/material-ui/react-dialog/#form-dialogs
**After:** https://deploy-preview-46307--material-ui.netlify.app/material-ui/react-dialog/#form-dialogs
> [docs][Dialog] Fix form dialog uses ARIA roles on incompatible elements

- docs/data/material/components/text-fields/FormPropsTextFields.js
- docs/data/material/components/text-fields/FormPropsTextFields.tsx
- docs/data/material/components/text-fields/text-fields.md
> [docs][TextField] Removed type="number" demos 

- packages/mui-material/src/styles/extendTheme.test.js
- packages/mui-material/src/styles/shouldSkipGeneratingVar.ts
The `modularCssLayers` can be a string, so it should be skipped from generating var because it cannot be used as a CSS variable else where.
Note: The `modularCssLayers` feature has not been released yet.
> [material-ui] Skip generating `modularCssLayers` CSS var

- renovate.json
* Track the canary release of internal packages.
* Canary releases are now published on every push to master of mui-public.
* Merge the renovate branch at your discretion
We can decide to follow this up with auto merging, but we'll probably have to tweak branch rules for that.
open questions:
* what about the notifications noise this will create?
* auto merge once per day?
> [infra] Create update PR on every canary publish for internal packages

- packages/mui-material/src/locale/index.ts
Correct "more than" labelDisplayedRows translation for Romanian.
> [l10] Enable `labelDisplayedRows` translation for Romanian

- scripts/copyFiles.mjs
If a package contains its own CHANGELOG.md, it'll be copied across to the build directory.
This is required for https://github.com/mui/base-ui/pull/2167.
> [infra] Support project-specific changelog in build scripts

- docs/public/_redirects
- packages/markdown/prepareMarkdown.mjs
- test/e2e-website/material-docs.spec.ts
- Noticed that the API docs link on https://mui.com/material-ui/react-no-ssr/ leads to https://v6.mui.com/base-ui/react-no-ssr/components-api/#no-ssr. We should navigate to https://mui.com/material-ui/api/no-ssr/ instead, and remove the legacy redirect
> [docs] Change API docs to stay inside Material UI

- scripts/README.md
> [infra] Add instructions for patch release

- .github/workflows/ci.yml
This should fix https://securityscorecards.dev/viewer/?uri=github.com%2Fmui%2Fmaterial-ui, back to 10/10.
Preview: https://deploy-preview-46438--material-ui.netlify.app/material-ui/react-alert/#introduction. I have tested the pkg.pr.new output with the code demos, it seems to work just fine. So https://github.com/mui/material-ui/pull/42984#discussion_r1691950071, considering that the rest of our codebase doesn't has this, I don't buy it.
---
A quick win, while I had a quick look at https://mui.zendesk.com/agent/tickets/28723.
As a side note, the way pkg-pr-new is configured in the codebase (base ui, joy ui, material ui, mui x) is so different. Can we please make it the same everywhere? no reason to be different. It makes it so hard to propagate fixes like this everywhere.
> [core] Fix unpinned version regression

- docs/data/material/components/switches/switches.md
- packages/mui-material/src/Switch/Switch.js
- packages/mui-material/src/Switch/Switch.test.js
Closes #23216
Adds `role="switch"` to the input element to improve accessibility.
Tested with NVDA—now announces "on/off" instead of "checked/unchecked".
> [Switch] Add role="switch"

- packages-internal/scripts/generate-llms-txt/src/processComponent.ts
- packages-internal/scripts/generate-llms-txt/test/processComponent.test.ts
Feedback from https://github.com/mui/mui-x/pull/18595
- To handle `{{ "demo": "…" }}` (with white spaces inside)
- Generate either TS or JS demo (before contains both snippet for each demo "```js" and "```ts")
---
> [docs-infra] Handle white spaces and generate either TS or JS demo for llms files

- scripts/build.mjs
- scripts/copyFiles.mjs
* Allow passing of extra flags to the babel-cli (temporarily)
* Check existence of package files (like license, changelogs etc) before
copying them.
This change will allow us to reuse the build and copyFiles script on `mui-x`.
Followup on mui-x - https://github.com/mui/mui-x/pull/18832
> [code-infra] Accomodate build requirements from mui-x

- packages/mui-codemod/package.json
- packages/mui-envinfo/package.json
- packages/mui-envinfo/scripts/build.js
- pnpm-lock.yaml
- scripts/copyFilesUtils.mjs
It is not required within the `build` directory and also helps with pkg.pr.new publishing so that we are able to use `pnpm pack` instead of `npm pack`.
I don't see any downsides of this but please let me know if there can be any other major repercussions that I might not have though of.
Here's the output in mui-x - https://publint.dev/pkg.pr.new/mui/mui-x/@mui/x-charts-pro@890bc9d
> [infra] Update scripts to delete publishConfig.directory

- docs/data/material/guides/minimizing-bundle-size/minimizing-bundle-size.md
- scripts/copyFilesUtils.mjs
Fix codesandbox and parcel without `packageExports` enabled. The issue is caused by top-level imprts having a cjs and esm variant through main/module fields but the subpath exports only having a cjs  export through file system resolution. We can simply remove the module field to have both resolve to the cjs variant. this only applies on runtimes where the exports field is not supported (codesandbox, parcel, webpack@<=4,...).
[docs](https://deploy-preview-46620--material-ui.netlify.app/material-ui/guides/minimizing-bundle-size/#using-parcel)
> [infra] Remove package.json `module` field

- docs/data/material/customization/typography/typography.md
Updated the Typography `h3` override example to define styles inside `createTheme`, as suggested in [this comment](https://github.com/mui/material-ui/issues/46498#issuecomment-3082743270)
This ensures media queries and CSS variable overrides are properly applied.
Fixes #46498
> [docs] Fix incorrect Typography override example for responsive styles

- docs/data/material/getting-started/mcp/mcp.md
Resolves #46471
This pull request adds MCP server installation details for Claude Code to the documentation to provide clearer setup instructions for users integrating Claude Code with the MCP server.
> [docs] Add MCP server installation details for Claude Code

- .circleci/config.yml
These seem to now consistently break on browserstack timeouts. Trying out the hypothesis that this happens when too many jobs run in parallel.
> [infra] Stagger daily cron jobs to avoid browserstack timeouts

- docs/data/material/migration/upgrade-to-v7/upgrade-to-v7.md
docs: add note about removal of MuiInputLabel‑sizeMedium class in upgrade guide
Closes #46684
> [docs][TextField] Add note about removal of `sizeMedium` class from InputLabel in v7 upgrade guide

- packages/netlify-plugin-cache-docs/index.js
Part of https://github.com/mui/mui-public/issues/481.
Should allow removing `fs-extra` from MUI X's repo, which failed due to this dependency ([revert PR](https://github.com/mui/mui-x/pull/19176)).
The actual fix would be to move `fs-extra` to the dependencies of the monorepo, but if we can get rid of better it would be better. 
[The run was successful](https://app.netlify.com/projects/material-ui/deploys/689cab40a2599300080e1acc)
> [infra] Remove `fs-extra` from `netlify-plugin-cache-docs`

- .circleci/config.yml
This needs to run in a job where we are actually running a production build
> [infra] move testBuiltTypes step

- packages/api-docs-builder/buildApi.ts
- packages/api-docs-builder/package.json
- packages/api-docs-builder/utils/findApiPages.ts
- packages/api-docs-builder/utils/parseTest.ts
- pnpm-lock.yaml
Part of https://github.com/mui/mui-public/issues/481.
Remove `api-docs-builder` dependency on `fs-extra`.
> [infra] Remove `api-docs-builder` dependency on `fs-extra`

- docs/package.json
- pnpm-lock.yaml
As explained in the [README](https://www.npmjs.com/package/react-spring), we should install React Spring according to the target platform. 
> ```
>  # Install the entire library
>  npm install react-spring
>  # or just install your specific target (recommended)
>  npm install @react-spring/web
>  ```
Since we're only targeting the web, there's no need to install `react-spring`, which was bringing in dependencies such as `react-native`, `react-konva`, `zdog`, etc. 
```
❯ pnpm why react-native react-konva zdog three
Legend: production dependency, optional only, dev only
@mui/monorepo@7.3.1 /Users/belchior/Documents/mui/material-ui (PRIVATE)
devDependencies:
@mui-internal/api-docs-builder-core link:packages/api-docs-builder-core
└─┬ docs link:docs
└─┬ react-spring 10.0.1
├─┬ …
```
> [infra] Remove dependency on `react-spring` (but keep `@react-spring/web`)

- babel.config.mjs
Test scripts are failing in Windows OS. Suggested solution is based on discussion in Slack.
> [code-infra] Remove `@mui/internal-babel-plugin-resolve-imports` override config

- netlify/functions/feedback-management.mts
> [core] Fix typos in `netlify` folder

- renovate.json
Since #46483 we have the setting shared, but I think we are better of making the schedule specific to each repository
Looking at the history, we haven't been consistent enough to run this update: https://github.com/mui/material-ui/pulls?q=is%3Apr+%22Lock+file+maintenance%22+is%3Aclosed. Which seems to be why we have so many of those: https://github.com/mui/material-ui/security/dependabot.
> [internal] Polish renovate schedule

- docs/data/material/components/autocomplete/autocomplete.md
I noticed this in #46804. Those docs are not sticking to https://www.notion.so/mui-org/Writing-style-guide-2a957a4168a54d47b14bae026d06a24b.
Preview: https://deploy-preview-46805--material-ui.netlify.app/material-ui/react-autocomplete/.
> [docs][autocomplete] Fix header sentence case

- packages/mui-docs/src/ComponentLinkHeader/ComponentLinkHeader.tsx
**Preview**: https://deploy-preview-46835--material-ui.netlify.app/material-ui/react-button/
Ref: https://base-ui.com/react/overview/quick-start
The markdown files are generated with the `llm.txt`, so this PR is just adding a link to those files.
> [docs] Add `View as Markdown` to component link header

- .circleci/config.yml
- test/karma.conf.js
Untangling all the flakeyness in circleci. This PR disables browserstack for anyting except for the main pipeline on production branches. We don't need it on the daily react 18/next jobs.
From circleci
* **react-18-cron**
This got mostly fixed on my last effort a month ogo
Flakeynes caused by too many concurrent browserstack sessions. this PR disables browserstack for react 18 cron job
* **react-next-cron**
This got mostly fixed on my last effort a month ogo
Flakeynes caused by too many concurrent browserstack sessions. this PR disables browserstack for react next cron job
* **typescript-next**
This is being run daily for the v6 branch for some reason. To be disabled in follow-up:
* **typescript-next-cron**
Caused by:
```
tsconfig.json(3,3): error TS5107: Option 'moduleResolution=node10' …
```
> [code-infra] Disable browserstack on circleci cron jobs

- docs/config.ts
- docs/next-env.d.ts
- docs/package.json
- docs/scripts/reportBrokenLinks.ts
- docs/scripts/reportBrokenLinksLib.ts
This also reverts config.js back to config.ts to fix issue with
https://github.com/mui/mui-x/pull/19468
> [code-infra] Convert reportBrokenLink script to ts

- packages/mui-material/src/styles/createTheme.ts
- packages/mui-material/src/styles/createThemeFoundation.ts
- packages/mui-material/src/styles/createThemeNoVars.d.ts
- packages/mui-material/src/styles/createThemeWithVars.d.ts
closes #46908
The root cause the the options type of the `createTheme` is mixing between `createThemeNoVars` and `createThemeWithVars` options causing complex type inferences for webpack as demonstrated by https://github.com/nvrtmd/mui-v7-memory-issue-repro
- remove cyclic dependency between both internal createTheme files by introduce a new file to store shared types.
- simplify the `ThemeOptions` by relying on the `createThemeWithVars` options (already extending the `createThemeNoVars`).
The fix also enhancing the `ThemeOptions` to be a complete version for users who import the type to build up theme options outside of the `createTheme`.
1. Clone
2. Replace package.json with
```json
"@mui/material": "https://pkg.pr.new/mui/material-ui/@mui/material@3e539c5",
"@mui/system": …
```
> [material-ui] Fix `ThemeOptions` and `createTheme*` cyclic dependency
