mui/material-ui

- src/GridList/GridList.js
> [GridList] Add momentum scrolling

- docs/src/pages/guides/comparison.md
Visual regressions tests rock 💃 .
> [docs] Add a tests section in the Comparison page

- src/Input/Input.js
- src/Input/Input.spec.js
- src/Input/Textarea.js
I have removed the intermediary function as it was preventing flow from checking anything and was bad for perf.
Closes #8554
> [Input] Fix Textarea regression handling

- src/IconButton/IconButton.js
> [IconButton] Take advantage of the CSS inheritance

- docs/src/pages/demos/selects/NativeSelect.js
- docs/src/pages/demos/selects/SimpleSelect.js
- pages/api/select.md
- src/Select/Select.js
- src/Select/SelectInput.js
- src/Select/SelectInput.spec.js
I'm not 100% happy with the empty value handling of the Select component.
At least this PR is an improvement, we might have to do more to reach a nice equilibrium.
Closes #8581
> [Select] Add a displayEmpty property

- docs/src/app/components/Carbon.js
- docs/src/app/components/Master.js
> [docs] Small fixes

- examples/nextjs/package.json
This time, it's using react@16.
Closes #8609
> [examples] Everything is back to normal with next.js

- src/index.d.ts
- src/index.js
> [withWidth] Export the module in index.js

- packages/material-ui-icons/copy-files.js
- packages/material-ui-icons/package.json
> [icons] Change homepage

- .eslintrc.js
- package.json
- prettier.config.js
Improve the submitting PRs experience and remove duplicated configuration.
> [core] Add global prettier config

- docs/src/pages/demos/autocomplete/autocomplete.md
'autosuggest-highlight' should be installed in order to import 'match' and 'parse'
> Added link for autosuggest-highlight installation

- pages/api/grid.md
- src/Grid/Grid.js
> [docs] Fix typo in item description

- src/Stepper/Stepper.js
- src/Stepper/Stepper.spec.js
Closes https://github.com/callemall/material-ui/issues/8633
> [Stepper] Allow invalid children

- src/test-utils/until.js
- src/test-utils/until.spec.js
> [core] Fix more warnings with enzyme@3 and react@16

- docs/src/pages/style/icons.md
> [docs] Improve SVG icons wordings

- src/Input/Input.js
- src/Select/Select.js
> [Input] Fix hover style on mobile

- docs/src/modules/components/MarkdownDocs.js
- docs/src/pages/guides/testing.md
- src/test-utils/createMount.js
- src/test-utils/createRender.js
- src/test-utils/createShallow.js
- Broken edit link
- Out-of-date API
- Closes #8508 as the enzyme adapter is out of the scope of the test helpers
> [docs] Fix test page

- .circleci/config.yml
Use @stipsan tip https://github.com/react-toolbox/react-toolbox/pull/1713/files#diff-1d37e48f9ceff6d8030570cd36286a61R17 for greater safety.
> [core] Safer CI on circle-ci with yarn

- CHANGELOG.md
- docs/src/pages/style/icons.md
- flow-typed/npm/enzyme_v2.3.x.js
- src/Menu/MenuList.spec.js
- src/Tabs/Tab.spec.js
- test/integration/Menu.spec.js
> [core] Prepare upgrade toward v3

- docs/src/pages/discover-more/showcase.md
> add Venuemob to v1 showcase

- docs/src/pages/demos/badges/SimpleBadge.js
- docs/src/pages/demos/badges/badges.md
- src/Badge/Badge.js
> [Badge] Add an example with a IconButton

- src/Button/Button.js
- test/regressions/tests/Button/MultilineButton.js
> [Button] Better render multilines button

- docs/src/pages/demos/progress/CircularIndeterminate.js
- docs/src/pages/demos/progress/CircularIntegration.js
- pages/api/circular-progress.md
- src/Progress/CircularProgress.js
- src/Progress/CircularProgress.spec.js
- Add a new thickness property.
- Cleaner animation
Closes #5524 (this issue is 1 year old! 😱)
Closes #8663
> [CircularProgress] Fix non Chrome rendering

- src/BottomNavigation/BottomNavigationButton.d.ts
- src/BottomNavigation/BottomNavigationButton.js
- src/Chip/Chip.d.ts
- src/Chip/Chip.js
- src/GridList/GridListTileBar.d.ts
- src/GridList/GridListTileBar.js
- src/Tabs/Tab.d.ts
The TypeScript definition for the Chip component was missing the deleteIcon property.
> [typing] Chip definition was missing deleteIcon & more

- pages/api/tabs.md
- src/Tabs/Tabs.d.ts
- src/Tabs/Tabs.js
> [Tabs] Add a TabScrollButton property

- src/Tooltip/Tooltip.d.ts
> [Tooltip] Improve typescript definition

- src/Input/Input.js
confusion -> confusing
You can learn about it with this article -> You can learn more about it in this article
> [Input] Fix grammar in documentation

- docs/src/pages/style/TypographyTheme.js
Its just a minor update correcting some typos in the class name for TypographyTheme
> [docs] Correct some typos in name 'TypographyTheme'

- docs/src/modules/components/GitHub.js
- docs/src/modules/components/Twitter.js
- docs/src/pages/discover-more/Team.js
- examples/create-react-app-with-flow/src/pages/index.js
- examples/create-react-app/src/pages/index.js
- examples/nextjs/pages/index.js
- src/IconButton/IconButton.js
- src/Popover/Popover.js
> [docs] Responsive team page

- docs/src/pages/demos/selection-controls/RadioButtonsGroup.js
- src/ButtonBase/ButtonBase.js
- src/utils/keyboardFocus.js
> [RadioGroup] Better keyboard focus logic

- docs/src/modules/components/AppFrame.js
This PR is basically about saving ink!
> [docs] Better display for print

- docs/src/pages/customization/ReactJss.js
- docs/src/pages/customization/css-in-js.md
- pages/customization/css-in-js.js
- src/styles/createGenerateClassName.js
- src/styles/themeListener.js
- src/styles/themeListener.spec.js
- src/styles/withStyles.js
> [docs] Interoperability with react-jss

- README.md
https://bestpractices.coreinfrastructure.org/projects/1320
> [docs] Add CII Best Practices

- .eslintrc.js
- docs/src/pages/demos/tables/BasicTable.js
- docs/src/pages/demos/tables/EnhancedTable.js
> [misc] Minor fixes

- docs/src/pages/getting-started/frequently-asked-questions.md
> [docs] FAQ disable ripple

- src/Select/Select.d.ts
Select component was missing definition for displayEmpty
> [Select] Add missing definition for displayEmpty

- docs/src/pages/getting-started/frequently-asked-questions.md
> [docs] Add FAQ inline-style vs withStyles()

- src/ButtonBase/ButtonBase.spec.js
- src/styles/getStylesCreator.js
- src/styles/getStylesCreator.spec.js
Further amends to #8759
Closes #8759
> [docs] Better warning description

- docs/src/modules/utils/parseMarkdown.js
> [docs] Fix the docs support on windows

- src/styles/createMuiTheme.js
- src/styles/createMuiTheme.spec.js
> [theme] Support overriding the shadows key

- docs/src/pages/getting-started/supported-components.md
Just noticed a minor typo. Figured I'd send a PR to fix it.
> [docs] Correct a typo (occurence -> occurrence)

- src/styles/index.d.ts
> [core] Remove erroneous exports from styles/index.d.ts

- src/List/ListItem.js
> [ListItem] Disable hover effect on touch devices

- docs/src/pages/demos/pickers/pickers.md
- docs/src/pages/guides/comparison.md
> [docs] Add promising pickers lib

- docs/src/pages/guides/server-rendering.md
Fixed incorrect path to import the createPalette module in the SSR docs. 
Closes #8743
> [docs] Fix wrong SSR path location (#8743)

- docs/src/pages/demos/popovers/AnchorPlayground.js
- docs/src/pages/demos/tables/BasicTable.js
- docs/src/pages/discover-more/Team.js
- docs/src/pages/discover-more/related-projects.md
> [docs] Fix some issues I have noticed

- docs/src/pages/demos/text-fields/InputAdornments.js
> [docs] Fix typos in input adornments example.

- src/styles/createBreakpoints.js
- src/styles/createBreakpoints.spec.js
> [breakpoints] Increase step to 5, fix media query matching on Safari

- src/Input/Input.js
- src/Input/Input.spec.js
> [Input] Fix disabled state

- docs/src/pages/customization/ReactJss.js
- docs/src/pages/getting-started/Usage.js
- docs/src/pages/getting-started/frequently-asked-questions.md
- docs/src/pages/getting-started/usage.md
- pages/getting-started/usage.js
- test/regressions/index.js
> [docs] Better onboarding experience

- docs/src/pages/demos/menus/SimpleListMenu.js
As per oliviertassinari's recommendations, adding disabled props to MenuItem component in the demo
Closes #8844
> [docs] Show disabled MenuItem

- src/Tooltip/Tooltip.js
- src/Tooltip/Tooltip.spec.js
> [Tooltip] Fix resize issue

- docs/src/pages/demos/popovers/popovers.md
> update Popover component readme

- src/Dialog/Dialog.js
> [Dialog] Fix IE11 overflow bug

- docs/src/pages/demos/text-fields/CustomizedInputs.js
- docs/src/pages/demos/text-fields/text-fields.md
- pages/api/select.md
- pages/demos/text-fields.js
Fix https://github.com/callemall/material-ui/issues/8224#issuecomment-339720277.
> [docs] Show how to change the color of the TextField

- src/Progress/CircularProgress.d.ts
> [CircularProgress] adding thickness property to .t.ds file

- docs/src/pages/demos/menus/LongMenu.js
> [docs] Simpler IconMenu example

- src/transitions/Collapse.js
> [Collapse] Fix height computation

- src/styles/withStyles.js
- src/styles/withStyles.spec.js
- src/transitions/Collapse.spec.js
Closes #8821
Thanks @rrousselGit for the reproduction example. It was very useful!
> [withStyles] Better handle react-hot-loader

- docs/src/modules/components/NoSSR.js
- docs/src/pages/demos/dialogs/AlertDialogSlide.js
- src/transitions/Slide.js
> [docs] Temporary fix for SSR issue with Portal

- CONTRIBUTING.md
- SUPPORT.md
Implements: https://github.com/blog/2400-support-file-support
> [docs] Split support content of CONTRIBUTING.md into SUPPORT.md

- src/Menu/MenuList.js
- test/integration/MenuList.spec.js
> [MenuList] Increase test coverage and fix an exception in an edge case

- docs/src/pages/guides/migration-v0.x.md
> [docs] Fix broken link

- src/GridList/GridList.d.ts
- src/GridList/GridListTile.d.ts
- test/typescript/components.spec.tsx
> [typescript] Add missing base props

- src/Form/FormControlLabel.js
- src/Form/FormControlLabel.spec.js
- src/Input/Input.js
- src/internal/SwitchBase.js
- src/internal/SwitchBase.spec.js
Pull disabled property from muiFormControl conrtext allowing to disabled status to be inherited from FormControl
Closes #8901
> [SwitchBase] Inherit `disabled` from FormControl

- docs/src/modules/components/AppDrawerNavItem.js
- docs/src/modules/components/MarkdownElement.js
- docs/src/modules/utils/prism.js
- docs/src/pages/customization/FontSizeTheme.js
- docs/src/pages/customization/themes.md
- pages/customization/themes.js
- src/Avatar/Avatar.js
- src/Badge/Badge.js
- src/BottomNavigation/BottomNavigationButton.js
- src/Button/Button.js
- src/Chip/Chip.js
- src/Form/FormHelperText.js
- src/Form/FormLabel.js
- src/GridList/GridListTileBar.js
- src/IconButton/IconButton.js
- src/Input/Input.js
- src/List/ListItemAvatar.js
- src/List/ListItemText.js
- src/List/ListSubheader.js
- src/Select/Select.js
- src/Table/TableBody.js
- src/Table/TableFooter.js
- src/Table/TableHead.js
- src/Table/TablePagination.js
- src/Tabs/Tab.js
- src/Tooltip/Tooltip.js
- src/styles/createTypography.js
Closes #8926
Closes #8903
The `Input` and `FormLabel` component do no longer inherit the font-size. You might have to override them explicitly.
> [style] Improve the font-size situation

- docs/src/pages/demos/menus/MenuListComposition.js
- docs/src/pages/demos/menus/menus.md
- pages/demos/menus.js
> [docs] Add more information around the MenuList component

- pages/api/collapse.md
- pages/api/form-control-label.md
- pages/api/menu.md
- pages/api/mui-theme-provider.md
- pages/api/popover.md
- pages/api/select.md
- pages/api/table-pagination.md
- src/Popover/Popover.js
> [Popover] Improve the warning message

- docs/src/pages/demos/dialogs/AlertDialogSlide.js
- docs/src/pages/demos/dialogs/ResponsiveDialog.js
- docs/src/pages/demos/dialogs/dialogs.md
- pages/demos/dialogs.js
- src/Dialog/index.d.ts
- src/Dialog/index.js
- src/Dialog/withMobileDialog.d.ts
- src/Dialog/withMobileDialog.js
- src/Dialog/withMobileDialog.spec.js
- src/index.js
- test/typescript/components.spec.tsx
```diff
-import { withResponsiveFullScreen } from 'material-ui/Dialog';
+import { withMobileDialog } from 'material-ui/Dialog';
```
Closes #8753
> [Dialog] Rename withResponsiveFullScreen

- src/internal/SwitchBase.d.ts
Addressing further comments in #8927.
> [typescript] Add missing base props, continued

- docs/src/pages/getting-started/installation.md
> [docs] Add --save parameter

- CONTRIBUTING.md
- docs/README.md
So that future contributors who would like to contribute to the demo/docs of this project would not have to go through what I had gone through personally : 
1. Search for contribution guideline.
2. Search for where the docs file are located. 
3. Trial and error to get the demo works with my new file.
Future contributors (e.g. myself) will have less frustration and more happiness. :smile:
> [docs] Add guideline for docs/demo contribution 

- docs/src/pages/demos/lists/CheckboxListSecondary.js
- docs/src/pages/demos/lists/SwitchListSecondary.js
> [docs] Use onChange instead of onClick for switch-like examples

- src/List/ListItem.js
> [Select] Menu Items centered in IE 11

- pages/api/icon-button.md
- src/IconButton/IconButton.js
- src/IconButton/IconButton.spec.js
> [IconButton] Add buttonRef property

- src/Select/Select.js
> [Select] Fix width on Safari

- docs/src/pages/layout/grid.md
> [Grid] Document a limitation

- README.md
> [readme] Use next tag for the npm version badge

- src/Popover/Popover.js
> [Popover] Add max-width

- docs/src/pages/customization/JssRegistry.js
- docs/src/pages/customization/css-in-js.md
- docs/src/pages/customization/overrides.md
I hope those two new documentation sections will help people understand how things work.
I would rather reboot the discussion we have had in the past in new issues. As we have more hindsight, we should be able to take new and better decisions now.
Closes #8872
Closes #7944
> [docs] Add a JssProvider and CSS injection order section

- src/Select/Select.js
> [Select] Fix width v2

- docs/src/pages/demos/drawers/PermanentDrawer.js
- docs/src/pages/demos/drawers/PersistentDrawer.js
- src/Drawer/Drawer.js
> [Drawer] Better support different anchor values

- docs/src/pages/customization/css-in-js.md
- pages/api/checkbox.md
- pages/api/collapse.md
- pages/api/list-subheader.md
- pages/api/radio.md
- pages/api/switch.md
- src/Checkbox/Checkbox.js
- src/Radio/Radio.js
- src/Switch/Switch.js
- src/internal/SwitchBase.js
- src/internal/SwitchBase.spec.js
Remove some "dead code".
`SwitchBase` can be a `Checkbox` a `Radio` or a `Switch`. 
```diff
-<SwitchBase disabled disabledClassName={disabledClassName} />;
+<SwitchBase disabled classes={{ disabled: disabledClassName }} />;
```
> [SwitchBase] Remove legacy properties

- src/internal/modalManager.spec.js
> [Modal] 100% coverage for modalManager.js

- src/Input/Input.js
I have discovered this issue digging into #9034.
> [Input] Remove grey highlight on iOS

- docs/src/pages/getting-started/frequently-asked-questions.md
> [docs] Add composed withStyles & withTheme HOCs to the FAQ

- src/Table/TablePagination.js
- closes #9037
- apply oliviers suggestion to change value to sth ie11 respects
> [TablePagination] Fix IE11 colSpan issue

- docs/src/pages/demos/menus/MenuListComposition.js
> [Menu] Fix MenuList integration demo

- docs/src/pages/demos/buttons/IconButtons.js
- docs/src/pages/demos/buttons/RaisedButtons.js
Might help those interested in displaying icons instead of buttons for file upload
> [docs] Add file upload examples with the icon buttons

- src/Input/Input.js
- src/Input/Input.spec.js
> [Input] Fix inputProps.ref support

- src/transitions/Slide.js
- src/transitions/Slide.spec.js
Small refactor. See [this comment](https://github.com/callemall/material-ui/pull/9055/files#r150246207) for more info.
> [Slide] Refactor lifecycle logics

- src/utils/withWidth.d.ts
> [typescript] Fix screenWidth type and added is WidthDown

- pages/api/tooltip.md
- src/Tooltip/Tooltip.js
Noticed a typo on the tooltip page. First PR, let me know if I need to do anything else.
> [Tooltip] Fix typo in API page

- docs/src/pages/demos/menus/ListItemComposition.js
- docs/src/pages/demos/menus/menus.md
- pages/demos/menus.js
I saw nobody was taking this issue, and decided to give it a try. It's my first contribution, so please let me know if something is wrong on the code or the PR.
Closes #3472
Closes #9134
> [docs] Improved documentation for Menu style overrides

- src/Drawer/Drawer.d.ts
> [Drawer] Fix classes in typescript definition

- src/Dialog/Dialog.js
- src/styles/createBreakpoints.js
- src/styles/createBreakpoints.spec.js
> [Dialog] Fix maxWidth=xs

- docs/src/modules/components/MarkdownElement.js
The anchor height was way too high.
It's also reducing the injected CSS payload.
> [docs] Fix display on IE11

- README.md
Fix broken link, minor thing 😉
> [docs] Fix broken link in README.md

- docs/scripts/buildApi.js
- pages/api/table-pagination.md
- src/Table/TablePagination.js
> [TablePagination] Improve the API docs page

- pages/api/input.md
- src/Input/Input.js
- src/Input/InputAdornment.js
I have reset the height on the input, we follow the same approach used for the textarea. It's simpler.
Closes #9163
> [Input] Fix input height on Firefox

- src/Drawer/Drawer.js
> [Drawer] Fix typo @ignore for theme prop

- src/Table/TableCell.js
I'm not sure yet it's the best tradeoff, but given Bootstrap uses the same, I'm more confident going into this direction.
Closes #9149
> [Table] Transparency less border color

- docs/src/pages/demos/buttons/IconLabelButtons.js
> [docs] Clean up code in IconLabelButton example

- .size-limit
> [core] Increase the size-limit

- docs/src/pages/demos/selects/SimpleSelect.js
- src/Select/SelectInput.js
- src/Select/SelectInput.spec.js
> [Select] Add name to the target

- pages/api/table-pagination.md
- src/Table/TablePagination.js
- src/Table/TablePagination.spec.js
> [TablePagination] Hide the rows per page selector if there are less than two options

- docs/src/modules/components/AppWrapper.js
- docs/src/modules/components/withRoot.js
- docs/src/pages/guides/interoperability.md
- pages/guides/interoperability.js
Hello everyone,
This was an original idea from @oliviertassinari which came out from [this issue discussion](https://github.com/paypal/glamorous/issues/354). The first scope of this guide was to write a little help guide to use Glamorous and Glamor with MUI components but I see possible to enlarge this in the future with not only Style libraries.
Waiting to read your comments to enhance this guide all I can.
> [Guide] Add Interoperability guide

- src/ButtonBase/ButtonBase.js
- src/ButtonBase/ButtonBase.spec.js
> [ButtonBase] Bookkeep the disable state

- src/Table/TableCell.js
> [Table] Update comment for Chrome rendering bug workaround

- README.md
This fixes dead links and missing images (once the cache refreshes).
> [docs] Update organization in readme

- docs/src/pages/demos/cards/RecipeReviewCard.js
- docs/src/pages/demos/lists/NestedList.js
- src/Table/TablePagination.d.ts
> Fix TablePaginationClassKey and change transitionDuration to timeout in demos using Collapse

- src/colors/common.d.ts
- src/styles/createBreakpoints.d.ts
- src/styles/createMuiTheme.d.ts
- src/styles/createPalette.d.ts
- src/styles/spacing.d.ts
- src/styles/zIndex.d.ts
> A few Typescript fixes (zIndex, spacing, Theme)

- examples/create-react-app-with-flow/README.md
- examples/create-react-app-with-typescript/README.md
- examples/create-react-app/README.md
- examples/nextjs/README.md
The Readme files in the example directories needed their organization name changed...
> [examples] rename organization to mui-org

- src/styles/createMixins.d.ts
- src/styles/withStyles.d.ts
> Fix some types that should be using React.CSSProperties

- src/TextField/TextField.d.ts
- test/typescript/components.spec.tsx
> Use correct types for TextFieldProps['inputProps'] and TextFieldProps['SelectProps']

- src/Switch/Switch.js
- src/Switch/Switch.spec.js
Missed a div in previous PR. Updated to span.
> [Switch] Update missed div to span for valid HTML

- src/Drawer/Drawer.d.ts
> Missing ModalProps on drawer

- src/styles/MuiThemeProvider.d.ts
> Allow function to be passed as MuiThemeProvider theme prop

- src/styles/createMuiTheme.d.ts
- src/styles/createPalette.d.ts
- test/typescript/styles.spec.tsx
> [styles][Closes #9333] Bug Fixed: createMuiTheme should accept a deep partial of a pallete

- examples/create-react-app-with-typescript/tslint.json
Updated in https://palantir.github.io/tslint/rules/member-ordering/
> Update `tslint.json` "member-ordering" definition

- src/styles/withTheme.d.ts
- test/typescript/styles.spec.tsx
> withTheme parameter on wrong function

- src/styles/createBreakpoints.d.ts
- src/styles/createMixins.d.ts
- src/styles/createMuiTheme.d.ts
- src/styles/spacing.d.ts
- src/styles/transitions.d.ts
- src/styles/zIndex.d.ts
- test/typescript/styles.spec.tsx
Fix the rest of the `ThemeOptions` types similarly to #9364 and #9368.
> Fix and standardize remaining ThemeOptions typings

- docs/src/pages/guides/typescript.md
> Simplify TypeScript custom theme example

- src/Table/Table.d.ts
- src/Table/TableBody.d.ts
- src/Table/TableCell.d.ts
- src/Table/TableFooter.d.ts
- src/Table/TableHead.d.ts
- src/Table/TablePagination.d.ts
- src/Table/TableRow.d.ts
> [Table] Add missing component props

- docs/src/pages/demos/buttons/FloatingActionButtons.js
- pages/api/button.md
- src/Button/Button.d.ts
- src/Button/Button.js
- src/Button/Button.spec.js
- src/styles/MuiThemeProvider.spec.js
> [Button] Add a mini FAB variant

- docs/README.md
- docs/gh-pages-build.js
> [docs] Update build-script & document docs publishing process

- CHANGELOG.md
> [CHANGELOG] Prepare v0.20.0

- docs/src/pages/discover-more/showcase.md
> [docs] Add project to showcase

- docs/src/pages/style/SvgIcons.js
- docs/src/pages/style/icons.md
- pages/api/svg-icon.md
- src/SvgIcon/SvgIcon.d.ts
- src/SvgIcon/SvgIcon.js
- src/SvgIcon/SvgIcon.spec.js
Closes #9269 
I saw what was not progress this issue and make pr, sorry :(
> [SvgIcon] Add color property

- src/Popover/Popover.d.ts
- src/Snackbar/Snackbar.d.ts
- src/styles/shadows.d.ts
- src/styles/transitions.d.ts
similar to https://github.com/mui-org/material-ui/pull/9245
Thanks for approving :-)
> [Typescript]: wrong default export in shadows.d.ts and transitions.d.ts 

- docs/src/pages/customization/css-in-js.md
Closes #9335
Closes #9342
Closes #9369
> [docs] Add a Plugins paragraph

- test/karma.conf.js
… I have forgotten to add them back after the React@16 migration.
> [test] Add missing platforms

- src/Tabs/TabIndicator.js
- src/Tabs/Tabs.js
- src/Tabs/Tabs.spec.js
The regression was introduced in #8419
> [Tabs] Fix SSR regression

- .eslintrc.js
- docs/src/modules/utils/generateMarkdown.js
- yarn.lock
> [core] Upgrade dependencies

- docs/.eslintrc.js
- docs/src/modules/components/Demo.js
- docs/src/modules/components/MarkdownElement.js
- docs/src/pages/customization/css-in-js.md
- docs/src/pages/guides/server-rendering.md
- docs/src/pages/guides/testing.md
So we always have the right CSS applied. I have noticed the issue when seeing the code markdown background not being white.
> [docs] Fix code formatting

- docs/src/modules/components/Demo.js
- package.json
- yarn.lock
We have to consider adding stackblitz too.
> [docs] Add codesandbox edit button

- src/ButtonBase/ButtonBase.js
- src/ButtonBase/Ripple.js
- src/ButtonBase/TouchRipple.js
> [ButtonBase] Remove some code

- docs/src/pages/layout/hidden.md
- src/utils/withWidth.js
Solving #9405 should be trivial now.
> [Hidden] Improve the docs

- src/Popover/Popover.d.ts
> [TypeScript] Add anchorPosition and anchorReference to PopoverProps

- docs/src/modules/utils/generateMarkdown.js
- pages/api/step-button.md
- pages/api/step-content.md
- pages/api/step-label.md
- pages/api/step.md
- pages/api/stepper.md
- src/Stepper/Step.js
- src/Stepper/StepButton.js
- src/Stepper/StepConnector.js
- src/Stepper/StepContent.js
- src/Stepper/StepIcon.js
- src/Stepper/StepLabel.js
- src/Stepper/StepPositionIcon.js
- src/Stepper/Stepper.js
Fix https://github.com/mui-org/material-ui/issues/9325#issuecomment-350177723
> [Stepper] Add missing names

- src/index.d.ts
- src/styles/createPalette.d.ts
- src/styles/createTypography.d.ts
- src/styles/spacing.d.ts
- src/styles/transitions.d.ts
- src/styles/zIndex.d.ts
> [TypeScript] Remove DeepPartial

- examples/create-react-app/src/index.js
- examples/nextjs/pages/_document.js
- examples/nextjs/styles/getContext.js
Since we are in the flow of removing flow --- I thought I would remove flow
from all of the examples except the flow example.
> [examples] remove flow from the examples

- src/Hidden/HiddenCss.js
- src/Hidden/HiddenCss.spec.js
> [Hidden] Add `only` array support in the CSS implementation 

- pages/api/list-subheader.md
- src/List/ListSubheader.js
Minor correct and updates toward `[ListSubheader]`, `[ListItem]`, `[List]` documents.
> [docs] Correct list API default value

- pages/api/input.md
- src/Input/Input.js
- src/Input/Input.spec.js
- I have forgotten to handle the context disabled update in a previous PR. This should add the missing logic.
- Closes #9463
> [TextField] Fix disabled logic handling

- docs/src/pages/demos/dialogs/AlertDialog.js
- docs/src/pages/demos/dialogs/AlertDialogSlide.js
- docs/src/pages/demos/dialogs/ConfirmationDialog.js
- docs/src/pages/demos/dialogs/FormDialog.js
- docs/src/pages/demos/dialogs/ResponsiveDialog.js
- docs/src/pages/demos/dialogs/SimpleDialog.js
- docs/src/pages/demos/dialogs/dialogs.md
- src/Dialog/Dialog.js
@oliviertassinari i'm not confident in the potential SSR implications of this (don't have much experience on that side of things).
Screen reader output before improvements
Screen reader output after improvements
DOM output after improvements
Closes #9158
> [Dialog] Improve accessibility

- docs/src/modules/components/Demo.js
This is a follow-on for #9466  for Broken codesandbox link
**Edited File**
material-ui/docs/src/modules/components/Demo.js
> [docs] Fix broken sandbox in docs

- docs/src/pages/discover-more/showcase.md
> [docs] Add new showcase

- src/Table/TablePagination.js
> [TableFooter] Fix text overlapping pagination drop-down

- docs/src/modules/components/Demo.js
- docs/src/modules/components/MarkdownDocs.js
- pages/discover-more/roadmap.js
> [docs] Add see source button

- src/ButtonBase/ButtonBase.js
> [ButtonBase] Avoid unnecessary rerender

- BACKERS.md
- README.md
- docs/src/modules/components/AppFooter.js
- docs/src/modules/components/AppFrame.js
- docs/src/modules/components/withRoot.js
- pages/discover-more/backers.js
- pages/index.js
@mui-org/core-contributors Let me know what you think about it :)
> [docs] Add a BACKERS.md

- .size-limit
- docs/src/modules/components/withRoot.js
- pages/discover-more/governance.js
> [docs] Add Governance page

- yarn.lock
periodic `yarn upgrade-interative`
> [core] Upgrade the dependencies

- docs/src/pages/customization/TypographyTheme.js
- src/styles/MuiThemeProvider.js
- src/styles/MuiThemeProvider.spec.js
> [MuiThemeProvider] Add a new warning

- docs/src/pages/demos/grid-list/AdvancedGridList.js
- docs/src/pages/demos/grid-list/TitlebarGridList.js
- docs/src/pages/demos/lists/PinnedSubheaderList.js
- pages/api/list.md
- src/List/List.js
- src/Stepper/StepContent.js
The recent addition of runtime checks surface different issues.
> [core] Fix wrong usage of the API

- docs/src/pages/demos/chips/ChipsArray.js
> [docs] Remove unused styes object from ChipsArray demo

- docs/src/pages/discover-more/Team.js
I'm not sure about the flags. We can update them later.
> [docs] Add two new members

- src/Select/Select.js
> [Select] - Typo fix

- docs/src/pages/guides/migration-v0.x.md
Added a step for running both MuiThemeProviders alongside eachother.
> [docs] Improve migration guide

- .editorconfig
> [.editorconfig] add max_line_length

- .size-limit
- src/utils/withWidth.js
- src/utils/withWidth.spec.js
> [withWith] Add withTheme option

- docs/src/pages/demos/tooltips/SimpleTooltips.js
> [docs] Fix basic typos in copy text

- src/Modal/Modal.spec.js
This adds 3 new unit tests for `Modal` to bump its coverage to :100: 
Closes #9527 
Edit: `codecov/project — 100% (+0.11%) compared to 6f5037b` :tada:
> [Modal] Increase test coverage

- src/Tabs/Tabs.js
> [Tabs] Add support for inline style override for parent container of InkBar

- test/README.md
> [tests] Document the ImageMagick / GraphicsMagick dependancy

- docs/src/modules/components/AppFrame.js
- docs/src/modules/components/Demo.js
Fixes a ouple of labeling issues I noticed while testing SpeedDial screen-reader support.
I also tried adding an aria-label to the search input, but it seems to get removed...
> [docs] Fix AppBar and Demo button labels

- pages/api/typography.md
- src/Typography/Typography.js
Remove required children constraint from Typography
Closes #9629
> [Typography] Remove children required constraint

- pages/api/card-header.md
- pages/api/card-media.md
- pages/api/collapse.md
- pages/api/grid-list.md
- src/Card/CardHeader.d.ts
- src/Card/CardHeader.js
- src/Card/CardMedia.js
- src/GridList/GridList.js
- src/transitions/Collapse.js
Same pattern as everywhere else.
Closes #9115
> [CardHeader] Add component property

- docs/src/modules/components/Demo.js
We have done quite some iteration on this issue.
We should be in a good shape now.
I think that it would be good in the future to add a link
toward a different online editor.
@lukePeavey I haven't ported your image replacement logic.
I couldn't find it. Feel free to submit a pull-request
to add it in the future :).
Closes #9474
> [docs] Fix 414 HTTP issue

- docs/src/modules/utils/generateMarkdown.js
- pages/api/snackbar.md
- src/Snackbar/Snackbar.js
> [Snackbar] Clarify that autoHideDuration calls onClose

- BACKERS.md
> [docs] Update backers.md

- docs/src/pages/demos/tables/EnhancedTable.js
- pages/api/table-pagination.md
- src/Table/TablePagination.d.ts
- src/Table/TablePagination.js
This will take care of the accessibility error of:
"Ensures buttons have discernible text"
By just placing aria-label's 
Closes #9621
> [Table] Add aria-label's to pagination left/right arrows

- docs/src/pages/guides/interoperability.md
> [docs] Add a missing codesandbox demo

- docs/src/modules/components/withRoot.js
- docs/src/pages/guides/interoperability.md
- Expand intro
- Add TOC
- Move CSS to the top
-  Use more explicit name in the Drawer
> [docs] Interoperability guide: Fix grammar and rework structure

- docs/src/modules/utils/generateMarkdown.js
> [docs] Remove dead code in generateMarkdown

- src/Tabs/Tabs.d.ts
> [typescript] Make Tabs onChange prop optional

- CHANGELOG.md
> [CHANGELOG] Prepare v1.0.0-beta.26

- docs/src/pages/layout/portal.md
> [Portal] Fix typo

- examples/nextjs/package.json
Address https://github.com/mui-org/material-ui/issues/9687#issuecomment-354667202
> [examples] Keep working on the Next.js example

- .size-limit
- docs/src/pages/demos/buttons/FloatingActionButtonZoom.js
- docs/src/pages/demos/buttons/buttons.md
- pages/api/zoom.js
- pages/api/zoom.md
- pages/demos/buttons.js
- src/index.js
- src/transitions/Fade.js
- src/transitions/Fade.spec.js
- src/transitions/Slide.js
- src/transitions/Slide.spec.js
- src/transitions/Zoom.d.ts
- src/transitions/Zoom.js
- src/transitions/Zoom.spec.js
- src/transitions/index.d.ts
- src/transitions/index.js
- test/utils/mockPortal.js
This PR provides the transition required to animate the FAB on and off the screen when it first appears, changes, or when transitioning between views,
> [Zoom] New transition component

- package.json
- src/Avatar/Avatar.d.ts
- src/Input/InputLabel.d.ts
- src/Modal/Modal.d.ts
- src/Popover/Popover.d.ts
- src/Portal/Portal.d.ts
- src/Radio/Radio.d.ts
- src/Select/Select.d.ts
- src/Select/SelectInput.d.ts
- src/Snackbar/Snackbar.d.ts
- src/Stepper/StepContent.d.ts
- src/Table/TablePagination.d.ts
- src/styles/MuiThemeProvider.d.ts
- src/styles/withStyles.d.ts
- yarn.lock
Update `Object` and `Function` type mentioned in #9430.
Updated component:
- Radio
- Popover
- InputLabel
- TablePagination
- Avatar
- Modal
- SelectInput
- Select
- StepContent
- Portal
Other: MuiThemeProvider.
> [typescript] Style/replace object and function in typedef

- src/styles/zIndex.d.ts
> [typescript] Update zIndex props to latest changes

- .size-limit
- docs/src/modules/components/AppSearch.js
- docs/src/pages/demos/buttons/IconLabelButtons.js
- docs/src/pages/demos/buttons/buttons.md
- src/Badge/Badge.js
- src/ButtonBase/ButtonBase.js
- src/Card/CardActions.js
- src/Form/FormControlLabel.js
- src/Input/InputAdornment.js
- src/Switch/Switch.js
- test/README.md
- test/regressions/TestViewer.js
- test/regressions/index.js
- test/regressions/tests/Switch/DisabledSwitch.js
Add missing `vertical-align` to our components so they are correctly vertically aligned when displayed *inline*.
Closes #9620
> [style] Add vertical-align: middle

- docs/src/app/components/Master.js
Reinforces the message recently added to the README.
> [docs] Add v1 recommendation to home page

- pages/api/dialog.md
- src/Dialog/Dialog.js
https://github.com/mui-org/material-ui/pull/9724#pullrequestreview-86624156
> [docs] Tweak Dialog maxWidth prop description

- package.json
> [core] Fix typo in size:overhead:why script

- docs/src/pages/getting-started/usage.md
> [docs] Fix link of "How to override the look and feel of the components."

- docs/src/pages/demos/chips/chips.md
> [docs] Fix Chip onDelete property

- docs/src/pages/customization/overrides.md
- docs/src/pages/customization/themes.md
- docs/src/pages/getting-started/usage.md
- docs/src/pages/guides/api.md
- docs/src/pages/guides/interoperability.md
- docs/src/pages/layout/css-in-js.md
- docs/src/pages/style/TypographyTheme.js
- docs/src/pages/style/reboot.md
> [docs] Misc docs fixes

- docs/src/modules/components/AppDrawer.js
- docs/src/modules/components/AppFrame.js
- docs/src/modules/components/withRoot.js
- docs/src/modules/styles/getPageContext.js
> [docs] Fix two small regressions

- docs/src/pages/customization/ThemeDefault.js
> [docs] Add Expand All switch to default theme tree

- src/colors/amber.js
- src/colors/blueGrey.js
- src/colors/brown.js
- src/colors/cyan.js
- src/colors/deepOrange.js
- src/colors/deepPurple.js
- src/colors/green.js
- src/colors/grey.js
- src/colors/indigo.js
- src/colors/lightBlue.js
- src/colors/lightGreen.js
- src/colors/lime.js
- src/colors/orange.js
- src/colors/pink.js
- src/colors/purple.js
- src/colors/red.js
- src/colors/teal.js
- src/colors/yellow.js
> [core] Remove contastDefaultColor

- src/transitions/Slide.js
- src/transitions/Slide.spec.js
Fix a regression I have introduced in https://github.com/mui-org/material-ui/commit/416db6f28c#diff-0ea64d17e9e0664286a7bd65c56ba40aR190.
Oops.
> [Slide] Fix an animation regression

- docs/src/pages/customization/themes.md
- docs/src/pages/style/color.md
Clarify hue, shade, etc.
Extracted from #9769
> [docs] Improve color / theme docs

- pages/api/tabs.md
- src/Popover/Popover.d.ts
- src/Popover/Popover.js
- src/Tabs/Tabs.d.ts
- src/Tabs/Tabs.js
- src/Tabs/Tabs.spec.js
I tried my best to match up what should be there for Typescript (although I never use it, so not 100% sure) 
Closes #9337
> [Tabs] Add action property

- pages/api/card-content.md
- src/Card/CardContent.d.ts
- src/Card/CardContent.js
wonder if it's really worth though
> [CardContent] Add component property

- .size-limit
- docs/src/pages/demos/tables/CustomPaginationActionsTable.js
- docs/src/pages/demos/tables/EnhancedTable.js
- docs/src/pages/demos/tables/tables.md
- pages/api/table-pagination.md
- pages/demos/tables.js
- src/Drawer/Drawer.js
- src/Menu/Menu.js
- src/Table/TablePagination.d.ts
- src/Table/TablePagination.js
- src/Table/TablePaginationActions.d.ts
- src/Table/TablePaginationActions.js
- src/Tabs/Tabs.js
- src/Tooltip/Tooltip.js
This pull request contains "go to first page button" and "go to last page button" for the Table Pagination component, which my customers highly appreciate.
They said, if they don't get the buttons, they have to die.
Thanks!
> [TablePagination] Add an Actions property

- package.json
- src/ButtonBase/TouchRipple.d.ts
- src/styles/overrides.d.ts
- yarn.lock
> [typescript] Add TouchRipple typings

- docs/src/pages/getting-started/example-projects.md
https://twitter.com/olivtassinari/status/950647902204039168
> [docs] Alternatives to CRA

- src/internal/SwitchBase.js
- src/internal/SwitchBase.spec.js
> [SwitchBase] Enable React input warning

- src/Radio/Radio.d.ts
- src/Switch/Switch.d.ts
Remove duplicate prop definitions from SwitchBase.
> Remove duplicate typescript definitions inherited from SwitchBase

- pages/api/fade.md
- pages/api/grow.md
- pages/api/slide.md
- pages/api/zoom.md
- src/internal/transition.d.ts
- src/transitions/Fade.js
- src/transitions/Grow.js
- src/transitions/Slide.js
- src/transitions/Zoom.js
> [Transition] Extend children propTypes

- src/Table/TablePagination.js
This removes dead code introduced by #9785 and brings back the coverage to :100: 
I was wrong yesterday, there was no regression introduced by the PR, the new actions are great! :+1: 
Edit: @oliviertassinari This issue perfectly matches your recent tweet!
> Having 100% test coverage ensure you have no dead code. By definition, the unreachable code can't be tested and will be marked as non covered.
> [TablePagination] Remove dead code

- docs/src/pages/demos/chips/Chips.js
- docs/src/pages/demos/chips/ChipsArray.js
- src/Avatar/Avatar.js
- src/Chip/Chip.js
- src/styles/createPalette.js
Fix @MaximKudriavtsev concern in https://github.com/mui-org/material-ui/issues/9407#issuecomment-356216445.
> [theme] Polish background scale

- src/ExpansionPanel/ExpansionPanel.d.ts
- test/typescript/components.spec.tsx
- yarn.lock
> [ExpansionPanel] Fix typescript definitions of onChange event

- .circleci/config.yml
- .size-limit
- next.config.js
- package.json
Primarily task toward investigating https://github.com/NervJS/nerv.
> [docs] Track the bundle size

- docs/src/pages/customization/ThemeDefault.js
> [docs] Display the default theme

- .size-limit
- BACKERS.md
- README.md
- pages/index.js
- Take https://github.com/ai/size-limit/issues/39 into account.
- Take Matt spacing feedback https://github.com/mui-org/material-ui/pull/9863#issuecomment-357476991
- Fix some W3C warnings #9867
> [core] Misc effort

- pages/api/input.md
- pages/api/text-field.md
- src/Input/Input.js
- src/TextField/TextField.js
> [TextField] Fix typo in JSDoc docs

- pages/_document.js
- pages/index.js
- src/ButtonBase/ButtonBase.js
- src/ButtonBase/ButtonBase.spec.js
- src/ButtonBase/TouchRipple.js
- src/Hidden/HiddenCss.js
- src/Hidden/HiddenCss.spec.js
Help toward #9867. It's solving 60% of the warnings on the home page.
> [core] Fix some w3c issues

- examples/create-react-app-with-flow/src/withRoot.js
- examples/create-react-app-with-jss/src/withRoot.js
- examples/create-react-app-with-typescript/src/withRoot.tsx
- examples/create-react-app/src/withRoot.js
- examples/nextjs/src/getPageContext.js
> [examples] Update for revised theme approach

- docs/src/pages/customization/themes.md
- src/styles/createPalette.js
> [docs] Additional corrections to palette code sample

- src/TextField/TextField.js
- src/TextField/TextField.spec.js
This basically fixes #9879 - see the issue for more information.
> [TextField] Add fullWidth propagation to Input

- .size-limit
- docs/src/modules/styles/getPageContext.js
- docs/src/pages/customization/themes.md
- pages/index.js
- src/styles/createPalette.js
- src/styles/createPalette.spec.js
- test/regressions/tests/Tabs/AdvancedTabs.js
- test/regressions/tests/Tabs/SimpleTabs.js
> [core] Make palette change non-breaking

- docs/src/pages/discover-more/showcase.md
> [docs] Update showcase.md

- examples/create-react-app-with-typescript/typings/misc.d.ts
> [typescript] Remove JSS stub module declaration

- examples/create-react-app-with-typescript/src/pages/index.tsx
- package.json
- src/index.d.ts
- src/styles/createPalette.d.ts
- src/styles/createPalette.js
- src/utils/withWidth.spec.tsx
- test/typescript/colors.spec.ts
- test/typescript/components.spec.tsx
- test/typescript/styles.spec.tsx
- test/typescript/styling-comparison.spec.tsx
Closes #9874 
I will cut a release once the TypeScript aspect is fixed.
>  [palette] Update the TypeScript definitions

- docs/src/pages/demos/buttons/ButtonBases.js
- docs/src/pages/demos/tables/CustomPaginationActionsTable.js
- docs/src/pages/demos/tables/EnhancedTable.js
- src/Badge/Badge.js
- src/Badge/Badge.spec.js
- src/Progress/CircularProgress.js
- src/Stepper/StepLabel.js
- src/Stepper/StepLabel.spec.js
Fixes the issues mentioned in the list in https://github.com/mui-org/material-ui/issues/9867#issuecomment-357800864 
related to #9867
> [core] fix w3c validation errors

- pages/api/collapse.md
- src/Popover/Popover.d.ts
- src/Snackbar/Snackbar.d.ts
- src/Tabs/Tab.d.ts
- src/Tabs/Tabs.d.ts
- src/Tooltip/Tooltip.d.ts
- src/styles/createGenerateClassName.d.ts
- src/styles/jssPreset.d.ts
- src/styles/themeListener.d.ts
- src/test-utils/createMount.d.ts
- src/test-utils/createRender.d.ts
- src/test-utils/createShallow.d.ts
- src/test-utils/until.d.ts
- src/transitions/Collapse.d.ts
- src/transitions/Collapse.js
- src/utils/helpers.d.ts
- src/utils/keyboardFocus.d.ts
- test/typescript/components.spec.tsx
> [typescript] Remove generic object and function types

- pages/api/form-helper-text.md
- src/Form/FormHelperText.js
- src/Form/FormHelperText.spec.js
I picked this up as it had the good--first-issue label. Simple change. 
Fixes #9823
> [FormTextHelper] Add component prop

- src/Progress/CircularProgress.js
Closes #9921 
The solution was posted in https://github.com/MicrosoftEdge/Status/issues/117#issuecomment-177585291.
> [CircularProgress] Fix animation on Edge 16 and below

- docs/src/pages/customization/css-in-js.md
- docs/src/pages/guides/ReactJss.js
- docs/src/pages/guides/interoperability.md
- docs/src/pages/style/color.md
- Add two alternatives to the HTML comment approach
- Update the dependencies of the codesandbox examples
- Normalize the examples
Closes #9931
> [docs] Style Library Interoperability v2

- docs/src/pages/getting-started/frequently-asked-questions.md
> [docs] Fix markdown list

- src/styles/createPalette.d.ts
Open on behalf of @daniel-rabe.
Closes #9954
> [palette] ShadeBackground interface updated

- docs/src/pages/demos/cards/RecipeReviewCard.js
Remove the spacer div
Use flexbox only to style the Cards action
> [docs] Remove one DOM element in the Card actions

- docs/src/pages/customization/theme-default.md
- docs/src/pages/customization/themes.md
- docs/src/pages/layout/basics.md
- docs/src/pages/layout/css-in-js.md
- src/styles/createPalette.js
Related to #9949, by @mbrookes.
> [docs] Apply Matt's requested changes

- src/Select/Select.js
> [Select] Fix a small vertical alignement issue

- src/styles/createPalette.d.ts
- src/styles/createPalette.js
- src/styles/createPalette.spec.js
- test/typescript/components.spec.tsx
- test/typescript/styles.spec.tsx
> [typescript] Palette typing fixes and error augmentation

- docs/src/pages/customization/css-in-js.md
Edit for https://github.com/mui-org/material-ui/pull/9939#issuecomment-358914913
Make sense to you guys like this?
> [docs] Edit css injection order docs for create-react-app users

- docs/src/pages/customization/RenderProps.js
- docs/src/pages/customization/StyledComponents.js
- docs/src/pages/customization/css-in-js.md
- docs/src/pages/customization/themes.md
- docs/src/pages/guides/flow.md
- docs/src/pages/layout/hidden.md
- examples/create-react-app-with-flow/README.md
- pages/customization/css-in-js.js
cc @rosskevin @pelotom @Bnaya @kof @ndelangen
Closes #9272
> [docs] withStyles alternative APIs

- src/Input/Input.js
> [Input] Make sure our previous or updated context is available

- .size-limit
- pages/api/dialog.md
- src/Dialog/Dialog.js
> [Dialog] Add PaperProps property

- docs/src/modules/components/AppFrame.js
- docs/src/modules/components/LightbublFull.js
Inspired by @deannad comment https://github.com/mui-org/material-ui/issues/9922#issuecomment-359529301
> [docs] Switch the Lightbulb UI

- src/ButtonBase/ButtonBase.js
- src/ButtonBase/ButtonBase.spec.js
- src/Form/FormControl.js
- src/Form/FormControl.spec.js
Fix one part of #9867 
> Error: Attribute required not allowed on element fieldset at this point.
> Error: Attribute disabled not allowed on element span at this point.
> [FormControl] Fix w3c issue

- src/styles/createPalette.d.ts
> [typescript] Add divider to palette type defs

- docs/src/pages/demos/tables/SimpleTable.js
- docs/src/pages/demos/tables/tables.md
- docs/src/pages/demos/tabs/SimpleTabs.js
- docs/src/pages/demos/tabs/TabsWrappedLabel.js
- docs/src/pages/demos/tabs/tabs.md
- pages/demos/tables.js
- pages/demos/tabs.js
We use "Simple" everywhere else. The majority rule.
> [docs] Use Simple over Basic

- docs/src/pages/demos/modals/SimpleModal.js
- src/styles/createPalette.js
**Before**
**After**
I have discovered the issue on @nareshbhatia's app: https://test.app.slidesup.com/confs/boston-conference-2017/agenda
> [Menu] Fix dark selected color

- src/Snackbar/SnackbarContent.js
Not sure we strictly need this now that we're not removing types from the theme, but as I'd already done the work, and as it removes the single use of types in a component, I thought I'd submit it anyway.
> [SnackbarContent] Change backgroundColor approach

- docs/src/pages/style/typography.md
Solve @grigored concerns https://github.com/mui-org/material-ui/issues/6256#issuecomment-357281838.
> [docs] Improve the typeface-roboto npm instructions

- docs/scripts/buildApi.js
- package.json
- src/Modal/Modal.js
- yarn.lock
> [core] Use the official react-docgen package

- CONTRIBUTING.md
- docs/src/pages/customization/css-in-js.md
- docs/src/pages/customization/overrides.md
- docs/src/pages/guides/typescript.md
- docs/src/pages/layout/basics.md
- docs/src/pages/layout/grid.md
- docs/src/pages/style/icons.md
- pages/api/portal.md
- pages/api/tabs.md
- src/Portal/Portal.js
- src/Tabs/Tabs.js
- src/styles/colorManipulator.spec.js
A random selection of docs fixes I've been collecting for an opportunity to address.
> [docs] Misc fixes

- docs/src/pages/customization/themes.md
- src/styles/createPalette.js
- src/styles/createPalette.spec.js
> [palette] Fix error color defaults

- src/Modal/Modal.js
It should help a bit with the performance.
> [Modal] Remove dead logic

- .size-limit
- docs/src/pages/demos/progress/LinearDeterminate.js
- pages/api/linear-progress.md
- src/Progress/LinearProgress.js
- src/Progress/LinearProgress.spec.js
> [LinearProgress] Add ARIA role & fix bugs

- docs/src/modules/components/withRoot.js
- docs/src/pages/guides/csp.md
- pages/guides/csp.js
[JSS now supports CSP](https://github.com/cssinjs/jss/blob/master/docs/csp.md) and this should be easy information to find on Material UI's site.
> Add CSP Guide

- src/AppBar/AppBar.js
> [AppBar] Remove one dead CSS property

- docs/src/pages/demos/progress/CircularDeterminate.js
- pages/api/circular-progress.md
- pages/api/linear-progress.md
- src/Progress/CircularProgress.js
- src/Progress/CircularProgress.spec.js
- src/Progress/LinearProgress.js
Actually, before, the docs example was static, and I can see why! 😄 This is the reason I said on the LinearProgress PR I didn't think anyone was using this component - if they were we would have had issues raised.
(Ignore the glitch, it's just the gif looping.)
> [CircularProgress] Improve animation & update example

- docs/src/pages/customization/themes.md
- docs/src/pages/demos/progress/LinearBuffer.js
- docs/src/pages/demos/progress/LinearDeterminate.js
- docs/src/pages/guides/typescript.md
> [docs] Remove last flow annotations

- docs/src/pages/demos/buttons/ButtonSizes.js
- docs/src/pages/demos/buttons/FloatingActionButtonZoom.js
- docs/src/pages/demos/buttons/FloatingActionButtons.js
- docs/src/pages/demos/buttons/IconLabelButtons.js
- docs/src/pages/demos/buttons/RaisedButtons.js
- docs/src/pages/demos/popovers/AnchorPlayground.js
- docs/src/pages/demos/progress/CircularIntegration.js
- docs/src/pages/demos/stepper/HorizontalLinearAlternativeLabelStepper.js
- docs/src/pages/demos/stepper/HorizontalLinearStepper.js
- docs/src/pages/demos/stepper/HorizontalNonLinearAlternativeLabelStepper.js
- docs/src/pages/demos/stepper/HorizontalNonLinearStepper.js
- docs/src/pages/demos/stepper/VerticalLinearStepper.js
- docs/src/pages/demos/tooltips/SimpleTooltips.js
- docs/src/pages/getting-started/usage.md
- docs/src/pages/guides/migration-v0.x.md
- pages/api/button.md
- src/Button/Button.d.ts
- src/Button/Button.js
- src/Button/Button.spec.js
- test/regressions/tests/Button/MultilineButton.js
- test/typescript/components.spec.tsx
> [Button] Move bool props to variant

- docs/src/pages/demos/progress/CircularDeterminate.js
- docs/src/pages/demos/progress/LinearBuffer.js
- docs/src/pages/demos/progress/LinearDeterminate.js
- docs/src/pages/demos/progress/LinearQuery.js
- pages/api/circular-progress.md
- pages/api/linear-progress.md
- src/Progress/CircularProgress.d.ts
- src/Progress/CircularProgress.js
- src/Progress/CircularProgress.spec.js
- src/Progress/LinearProgress.d.ts
- src/Progress/LinearProgress.js
- src/Progress/LinearProgress.spec.js
- test/regressions/tests/LinearProgress/BufferLinearProgress.js
- test/regressions/tests/LinearProgress/DeterminateLinearProgress.js
- test/typescript/components.spec.tsx
For consistency with the planned `type` -> `variant` prop change on other components.
> [CircularProgress][LinearProgress] Rename mode prop to variant

- docs/src/pages/customization/StyledComponents.js
- docs/src/pages/customization/css-in-js.md
Solve @danielkarlsson concern in #10098.
> [docs] Alternative APIs theme

- .size-limit
- docs/src/modules/components/AppDrawerNavItem.js
- docs/src/pages/demos/buttons/buttons.md
- docs/src/pages/getting-started/frequently-asked-questions.md
- pages/index.js
- src/Button/Button.d.ts
> [docs] Add How do I use react-router? in FAQ

- src/AppBar/AppBar.spec.js
Just noticed that assert messages do not match test itself
> [test] Fix AppBar test assert messages

- docs/src/pages/demos/badges/SimpleBadge.js
- docs/src/pages/demos/badges/badges.md
- yarn.lock
> [docs] Add more examples for the Badge

- pages/api/app-bar.md
- pages/api/badge.md
- pages/api/button.md
- pages/api/circular-progress.md
- pages/api/icon-button.md
- pages/api/icon.md
- pages/api/linear-progress.md
- pages/api/list-subheader.md
- pages/api/svg-icon.md
- pages/api/typography.md
- src/AppBar/AppBar.js
- src/Badge/Badge.js
- src/Button/Button.js
- src/Icon/Icon.js
- src/IconButton/IconButton.js
- src/List/ListSubheader.js
- src/Progress/CircularProgress.js
- src/Progress/LinearProgress.js
- src/SvgIcon/SvgIcon.js
- src/Typography/Typography.js
> [docs] Better color prop description

- docs/src/modules/components/MarkdownElement.js
- yarn.lock
It's a tradeoff.
Fix https://validator.w3.org/nu/?doc=https%3A%2F%2Fmaterial-ui-next.com%2Fcustomization%2Fthemes%2F
> [docs] Fix duplicated id issue

- src/ButtonBase/ButtonBase.js
- src/ButtonBase/ButtonBase.spec.js
> [ButtonBase] Fix keyDown handled

- src/transitions/Fade.js
- src/transitions/Fade.spec.js
- src/transitions/Zoom.js
- src/transitions/Zoom.spec.js
> [Fade] Simplify implementation

- docs/src/pages/demos/progress/DelayingAppearance.js
- docs/src/pages/demos/progress/progress.md
- package.json
- pages/demos/progress.js
- yarn.lock
> [docs] Document approach for progress indicator delay

- docs/src/pages/demos/progress/DelayingAppearance.js
- docs/src/pages/demos/progress/progress.md
- pages/api/fade.md
- pages/api/zoom.md
- src/transitions/Fade.js
- src/transitions/Zoom.js
#10145 was merged before this was ready
> [docs] Simplify delayed progress indicator example

- docs/src/modules/components/Demo.js
> [docs] Allow Demo to specify only required deps

- src/Input/Input.js
- src/Input/InputAdornment.js
> [InputAdornment] Remove hack

- docs/src/pages/discover-more/related-projects.md
> [docs] Add mui-downshift

- src/Hidden/HiddenCss.js
- src/Hidden/HiddenCss.spec.js
Add support for provided className on Hidden component when implementation is css
Closes #10161
> [Hidden] css implementation handle custom className

- docs/src/pages/demos/badges/SimpleBadge.js
- src/Hidden/HiddenJs.js
- Remove code from HiddenJs.
- Fix Badge alignment issue
> [HiddenJs] Remove some code

- .size-limit
- next.config.js
- package.json
- yarn.lock
> [core] Upgrade Next.js

- docs/src/pages/demos/popovers/MouseOverPopover.js
> [docs] Fix the restore focus logic of the Popover demo

- docs/src/pages/demos/autocomplete/IntegrationReactSelect.js
- src/Chip/Chip.js
- src/utils/reactHelpers.js
> [docs] Fix react-select chip on mobile

- docs/src/pages/demos/snackbars/FabIntegrationSnackbar.js
- docs/src/pages/demos/snackbars/snackbars.md
- pages/demos/snackbars.js
> [docs] Add Snackbar / FAB animation integration example

- src/MobileStepper/MobileStepper.js
I stumbled upon this when upgrading to Beta 32. I tested it within my project and it works as expected now.
Closes #10178
> [Stepper] Mobile Stepper variant determinate

- docs/src/pages/discover-more/showcase.md
Also reordered the list to highlight highest quality examples.
> [docs] Add LocalMonero to showcase

- docs/src/pages/getting-started/supported-components.md
> [docs] Fix typo `Selet` to `Select`

- docs/src/pages/demos/selects/ControlledOpenSelect.js
- docs/src/pages/demos/selects/MultipleSelect.js
- docs/src/pages/demos/selects/NativeSelect.js
- docs/src/pages/demos/selects/SimpleSelect.js
- docs/src/pages/demos/selects/selects.md
- pages/demos/selects.js
- src/Select/SelectInput.js
- src/Select/SelectInput.spec.js
> [Select] Simpler controlled open property

- docs/src/pages/customization/themes.md
I have imagination, but sometimes it needs additional inspiration. :)
> [docs] Change negative to positive

- src/index.d.ts
- src/styles/index.d.ts
- test/typescript/components.spec.tsx
> [typescript] Export WithTheme from index

- docs/src/pages/discover-more/showcase.md
> [docs] Update links on showcase.md

- src/Form/FormControl.js
- src/Input/Input.js
> [Input] Fix infinite loop

- docs/src/pages/demos/drawers/MiniDrawer.js
- docs/src/pages/demos/drawers/PersistentDrawer.js
> [docs] Remove dead code in Drawers

- src/transitions/Collapse.js
- src/transitions/Grow.js
Add the missing teardown logic.
> [Transition] Add the missing teardown logic

- docs/src/pages/utils/modals/modals.md
- docs/src/pages/utils/portal.md
- docs/src/pages/utils/transitions/SimpleGrow.js
- docs/src/pages/utils/transitions/transitions.md
& fix up a couple of  utils links
> [docs] Add transform-origin and timeout to Grow demo

- docs/src/pages/discover-more/showcase.md
Add modole to list of sites using materia-ui-next
> [docs] Add modole.io to showcase

- docs/scripts/buildApi.js
- docs/src/modules/utils/generateMarkdown.js
- pages/api/collapse.md
- pages/api/grid-list.md
- pages/api/grow.md
- pages/api/hidden.md
- pages/api/input.md
- pages/api/menu.md
- pages/api/popover.md
- pages/api/select.md
- pages/api/snackbar.md
- pages/api/step-content.md
- pages/api/tabs.md
- pages/api/text-field.md
We were missing the recursion:
Closes #10242
> [docs] Better API generator

- README.md
`raised` is no longer a valid prop. It's `variant="raised"` since `v1.0.0-beta.32`
> [docs] Update example in README.md

- docs/src/pages/demos/buttons/buttons.md
> [docs] Fix typo in button component demo

- pages/api/input-label.md
- src/Input/InputLabel.js
> [InputLabel] Add inheritance docs

- docs/src/pages/guides/interoperability.md
> [docs] styled components non-root components

- src/ExpansionPanel/ExpansionPanel.js
- src/ExpansionPanel/ExpansionPanelSummary.js
- src/Input/Input.js
> [Input][ExpansionPane] Remove the use of legacy easing-curve

- .eslintrc.js
- src/Drawer/Drawer.d.ts
- src/Snackbar/Snackbar.d.ts
- src/Stepper/Stepper.d.ts
- src/index.d.ts
- src/styles/index.d.ts
- src/transitions/Collapse.d.ts
- src/transitions/transition.d.ts
- test/typescript/components.spec.tsx
> [typescript] Add missing exports in index.d.ts

- .size-limit
- package.json
- yarn.lock
A classic issue with `ref`we have already faced: https://github.com/souporserious/react-popper/issues/81 🎉.
Closes #10298
> [core] Upgrade react-popper

- .size-limit
- BACKERS.md
- README.md
- pages/index.js
Improve the good practices score on lighthouse.
Waiting for https://github.com/PrismJS/prism/pull/1296 to be merged too.
> [docs] Add missing rel=noopener

- README.md
- pages/index.js
To give some perspective:
| Project        | Average response time           |
| ------------- |:-------------:|
| Vue      | [![Average time to resolve an issue](http://isitmaintained.com/badge/resolution/vuejs/vue.svg)](http://isitmaintained.com/project/vuejs/vue "Average time to resolve an issue") |
| Ant design      | [![Average time to resolve an issue](http://isitmaintained.com/badge/resolution/ant-design/ant-design.svg)](http://isitmaintained.com/project/ant-design/ant-design "Average time to resolve an issue") |
| Material-UI | [![Average time to resolve an issue](http://isitmaintained.com/badge/resolution/mui-org/material-ui.svg)](http://isitmaintained.com/project/mui-org/material-ui "Average time to resolve an issue") |
| React | [![Average time to resolve an …
> [docs] Add the average response time

- src/ExpansionPanel/ExpansionPanel.js
- src/ExpansionPanel/ExpansionPanelSummary.js
- src/Input/Textarea.js
- src/Input/Textarea.spec.js
Small fixes I could do digging into the IE 11 issue.
> [core] Fix IE 11 issues

- docs/src/modules/components/AppWrapper.js
- src/transitions/Slide.js
Follow the same pattern as #10318
> [Slide] Work with SVG too

- docs/src/pages/demos/badges/badges.md
- docs/src/pages/style/icons.md
> [docs] Add an example with Google Web Fonts

- docs/src/pages/demos/drawers/ClippedDrawer.js
- docs/src/pages/demos/drawers/MiniDrawer.js
- docs/src/pages/demos/drawers/PermanentDrawer.js
- docs/src/pages/demos/drawers/PersistentDrawer.js
- docs/src/pages/demos/drawers/ResponsiveDrawer.js
- docs/src/pages/demos/drawers/TemporaryDrawer.js
- docs/src/pages/demos/drawers/drawers.md
- pages/demos/drawers.js
- src/List/List.js
> [Drawer] Add clipped navigation drawer demo

- .size-limit
- yarn.lock
> [core] Upgrade some dependency to start looking into React 16.3

- docs/src/pages/discover-more/related-projects/related-projects.md
Sorry, I always forget that github doesn't create the branch on your fork when you're a collaborator, but now that it's here...
> [docs] Add react-final-form to Related Projects

- docs/src/pages/lab/speed-dial/OpenIconSpeedDial.js
- docs/src/pages/lab/speed-dial/SpeedDials.js
- packages/material-ui-lab/src/SpeedDial/SpeedDial.js
> [lab][SpeedDial] Fix onClick target element

- src/IconButton/IconButton.d.ts
Fix typings related to this change: https://github.com/mui-org/material-ui/commit/e6175ea8c2a98c4a25b8ef6bb9a045ffd0001800#diff-f56b3fb13dcefe4310855decef01b95e
> [IconButton] Fix class key types

- src/Card/CardHeader.d.ts
> [CardHeader] Add missing "action" classes key definition

- pages/api/dialog.md
- src/Dialog/Dialog.js
- test/regressions/index.js
> [Dialog] Consistent description

- src/Select/SelectInput.js
- src/Select/SelectInput.spec.js
I can't think of a better solution.
**Before**
**After**
Closes #10365.
> [Select] Fix the vertical-align

- docs/src/pages/getting-started/installation/installation.md
- docs/src/pages/style/icons/icons.md
- docs/src/pages/style/typography/typography.md
- package.json
- yarn.lock
Closes #10342 with https://github.com/zeit/next.js/pull/3758
Closes #9867 with https://github.com/zeit/next.js/pull/3572
> [docs] Fix IE 11 and W3C warnings

- docs/src/pages/guides/migration-v0.x/migration-v0.x.md
> [docs] Autocomplete migration

- ROADMAP.md
- docs/notifications.json
> [docs] Breaking changes feedback notification

- docs/src/pages/discover-more/related-projects/related-projects.md
> [docs] Add material-ui-autosuggest to related projects

- docs/notifications.json
> [Docs] fix minor typo in breaking-changes notification

- src/Select/Select.js
- src/Select/SelectInput.js
- src/Select/SelectInput.spec.js
> [Select] Make 'type' prop able to be overwritten

- docs/src/pages/guides/composition/composition.md
The react-final-form description helps a lot understanding how the properties are used:
https://github.com/final-form/react-final-form#rendering
> [docs] Description of how component will render

- src/internal/SwitchBase.js
> [SwitchBase] Fix defaultChecked issue

- src/internal/SwitchBase.spec.js
Add a test case for #10444. It's failing on the latest release.
> [SwitchBase] Prevent defaultChecked regression

- pages/api/collapse.md
- src/transitions/Collapse.js
just a typo vetical => vertical
> [Collapse] Fix description

- .size-limit
- package.json
- yarn.lock
> [core] Upgrade the dev dependencies

- docs/src/pages/demos/drawers/MiniDrawer.js
- src/Card/CardActions.js
- src/Card/CardContent.js
- src/Card/CardHeader.js
- src/GridList/GridListTileBar.js
- src/List/ListItem.js
- src/List/ListSubheader.js
- src/Menu/MenuItem.js
- src/Toolbar/Toolbar.js
- src/styles/createMixins.js
> [Card][List] Implement responsive gutters 

- src/Input/Textarea.js
[What’s new in React 16.3(.0-alpha)](https://medium.com/@baphemot/whats-new-in-react-16-3-d2c9b7b6193b)
Closes #10464
> [Textarea] Prepare React 16.3.0

- ROADMAP.md
https://material-ui-next.com/discover-more/roadmap/
> [docs] Fix Roadmap docs formatting

- docs/src/pages/discover-more/showcase/showcase.md
Game I'm developing that using Material UI Next.
> [docs] Add new Showcase project

- src/ButtonBase/Ripple.js
- src/ButtonBase/Ripple.spec.js
- src/ButtonBase/TouchRipple.js
**Before 😱**
**After 💚**
Closes #10503
> [ButtonBase] Fix the ripple on Edge

- pages/api/select.md
- src/Select/Select.js
- src/Select/SelectInput.js
> [Select] Document when the value is required

- docs/scripts/buildApi.js
- docs/src/modules/utils/generateMarkdown.js
- pages/api/select.md
- src/Select/Select.js
- src/Select/SelectInput.js
> [Select] Document the renderValue signature

- src/Modal/ModalManager.js
> [Modal] Use prototype functions in ModalManager

- src/Input/Input.js
- src/Input/Input.spec.js
- src/Select/SelectInput.js
> [Select] Fix wrong onBlur onFocus logic

- docs/src/pages/discover-more/showcase/showcase.md
Hello, I would like to add my project to this amazing library. Componofy is a web app that allows users to merge or create their playlists out of many, personal or public, playlists. It also allows users to re-order tracks in playlist with drag and drop and upload custom playlist cover images.
Please see a 2-minute demo for more details: https://www.youtube.com/watch?v=t5whFTIieHU
It uses `material-ui` from top to bottom with themes and measurement units applied for each component. For more code details you can see the source code:
https://github.com/DalerAsrorov/componofy
I believe this project is great and will be a good asset to your showcase! Thanks a lot for this amazing UI library. 
Link: http://componofy.herokuapp.com/
> [docs] Add showcase to readme - componofy

- docs/src/pages/discover-more/showcase/showcase.md
This adds Cryptoverview, our latest Material-UI project, to the showcase.
> Cryptoverview is a responsive webapp that displays a user's Bittrex portfolio, trending currencies and market caps. It provides some fancy charts, news related to cryptocurrencies, and more.
If you want, I can provide some demo credentials. It uses (or will use) almost everything I contributed to Material-UI 1.0 (e.g. table pagination was implemented for Cryptoverview's order tables), so there will be a lot to see and there is still a lot yet to come. :sunglasses:
> [docs] Add Cryptoverview to the showcase

- src/ExpansionPanel/ExpansionPanel.js
- src/ExpansionPanel/ExpansionPanel.spec.js
> [ExpansionPanel] Fix controlled behavior

- docs/src/pages/demos/menus/MenuListComposition.js
- Show how simple the Portal can be used
- Remove the setTimeout hack with a cleaner solution
- Add a collapse variation
Closes #10539, all the credits goes to @bennidhamma
> [docs] Add menu Collapse example

- docs/src/pages/discover-more/showcase/showcase.md
The starter itself uses only some elements of the library: Buttons, Menus, Avatars, TextFields and Icons.
> [docs] Add PersonalBlog Gatsby starter to Showcase

- docs/src/pages/demos/autocomplete/IntegrationDownshift.js
- src/Drawer/Drawer.js
- src/Select/SelectInput.js
The issue was raised by @caub: https://caniuse.com/#search=includes.
> [core] Improve IE11 support

- docs/src/pages/demos/text-fields/CustomizedInputs.js
- docs/src/pages/demos/text-fields/FormattedInputs.js
- docs/src/pages/demos/text-fields/InputAdornments.js
- docs/src/pages/demos/text-fields/TextFields.js
- docs/src/pages/demos/text-fields/text-fields.md
- Shows how the `inputComponent` can be used with the TextField
- Fix a bunch of accessibility issue on the page
Closes #10559
> [TextField] Better inputComponent demo

- examples/parcel/.babelrc
- examples/parcel/.gitignore
- examples/parcel/README.md
- examples/parcel/package.json
- examples/parcel/src/index.html
- examples/parcel/src/index.js
- examples/parcel/src/pages/index.js
- examples/parcel/src/withRoot.js
> [docs] Add parcel example

- CONTRIBUTING.md
> [docs] Fix typo in contributing readme

- pages/api/list-item-icon.md
- src/List/ListItemIcon.d.ts
- src/List/ListItemIcon.js
- test/typescript/components.spec.tsx
> [typescript] Add a test case for ListItemIcon

- pages/api/button.md
- src/Button/Button.js
Closes #10574
Updating the documentation on the Button component's variant prop.
> [Button] Fix Button variant prop description

- src/Icon/Icon.js
> [Icon] Fix a bug in Chrome 64.0

- src/List/ListItemText.js
> [List] use theme for margin in ListItemText

- BACKERS.md
Your contribution is appreciated! ❤️
> [docs] Add the latest backers

- docs/src/pages/discover-more/showcase/showcase.md
I've added a new app I've been working on, Planalyze :)
> [docs] Add Planalyze to Showcase

- pages/api/tooltip.md
- src/GridList/GridListTile.js
- src/Input/Textarea.js
- src/Popover/Popover.js
- src/Tabs/Tabs.js
- src/Tooltip/Tooltip.d.ts
- src/Tooltip/Tooltip.js
- src/Tooltip/Tooltip.spec.js
- src/transitions/Slide.js
> [Tooltip] Add enterTouchDelay and leaveTouchDelay props

- .size-limit
- src/styles/getStylesCreator.js
- src/styles/getStylesCreator.spec.js
- yarn.lock
The issue was raised by @eigood
> [core] Better overrides merge support

- docs/src/pages/customization/themes/FontSizeTheme.js
- docs/src/pages/customization/themes/TypographyTheme.js
- docs/src/pages/customization/themes/themes.md
- src/styles/createTypography.js
> [docs] Improve the htmlFontSize documentation

- .size-limit
- src/Select/Select.js
> [Select] Fix chip alignment

- src/List/ListItemSecondaryAction.js
> [ListItemSecondaryAction] Vertically center

- docs/src/pages/demos/autocomplete/IntegrationDownshift.js
- docs/src/pages/demos/autocomplete/IntegrationReactSelect.js
- src/Input/Input.js
- src/Select/Select.js
- src/Select/SelectInput.js
> [docs] Better support of multiline for downshift

- docs/src/pages/demos/menus/LongMenu.js
> [docs] Update LongMenu.js

- src/Popover/Popover.d.ts
> [Popover] Update anchorEl type

- examples/cdn/index.html
> [docs] Fix usage of CssBaseline/Reboot in the CDN example

- docs/src/pages/getting-started/usage/usage.md
> [docs] Fix reference to CssBaseline component

- docs/src/pages/guides/api/api.md
> [docs] Fix reference to FAQ

- pages/api/grow.md
- src/transitions/Grow.js
> [docs] Fix reference to Popover demo

- pages/api/fade.md
- src/transitions/Fade.js
> [docs] Fix reference to Modal demo

- src/ButtonBase/ButtonBase.d.ts
- src/TextField/TextField.d.ts
> [typescript] Update class keys

- src/Form/FormHelperText.d.ts
Closes #10657 
Please take a look. @oliviertassinari @pelotom 
Thanks!
> [typescript] Add component prop under FromHelperTextProps

- docs/src/pages/discover-more/showcase/showcase.md
We love the material-ui library so I thought I'd share the project we built with it.
Thank you for your all work!
> [docs] Add Rung to showcase

- src/styles/createTypography.js
While the negative margin is allowing us to follow the specification a bit closer, it comes with limitations. Ideally, I would rather not have to use this style. It might not play nicely with different fonts and might cause layout issue.
> [theme] Reduce the negative margin

- docs/src/pages/discover-more/showcase/showcase.md
> [docs] Add Team SC into showcase

- src/Dialog/DialogActions.d.ts
> [DialogActions] Add missing TypeScript property

- src/GridList/GridList.js
- src/GridList/GridList.spec.js
> [GridList] should allow optional children

- src/Switch/Switch.d.ts
- src/internal/SwitchBase.d.ts
> [Switch] Add missing TypeScript class keys

- docs/src/pages/demos/selection-controls/Checkboxes.js
- docs/src/pages/demos/selection-controls/RadioButtons.js
- docs/src/pages/demos/selection-controls/Switches.js
- pages/api/checkbox.md
- pages/api/radio.md
- pages/api/switch.md
- src/Checkbox/Checkbox.d.ts
- src/Checkbox/Checkbox.js
- src/Radio/Radio.d.ts
- src/Radio/Radio.js
- src/Switch/Switch.d.ts
- src/Switch/Switch.js
> [Switch] Add default color

- pages/api/text-field.md
- src/TextField/TextField.js
> [TextField] Update prop types

- src/Form/FormControl.js
- src/Input/Input.js
- src/Input/Input.spec.js
- src/Select/SelectInput.js
The *dirty* wording is often used to describe a field that initial value differs from the current value. For instance with [final-form](https://github.com/final-form/final-form#dirty-boolean).
Closes #9249
> [Input] Rename isDirty to isEmpty

- src/Select/SelectInput.js
- src/Select/SelectInput.spec.js
> [Select] Perfom the layout computation as soon as possible

- docs/src/pages/utils/popovers/AnchorPlayground.js
> [docs] Use buttonRef instead of ref in anchor playground example

- docs/src/pages/demos/steppers/HorizontalNonLinearStepperWithError.js
- docs/src/pages/demos/steppers/steppers.md
- pages/api/step-button.md
- pages/api/step-content.md
- pages/api/step-icon.md
- pages/api/step-label.md
- pages/api/step.md
- pages/demos/steppers.js
- src/Stepper/Step.js
- src/Stepper/StepButton.js
- src/Stepper/StepConnector.js
- src/Stepper/StepContent.js
- src/Stepper/StepIcon.d.ts
- src/Stepper/StepIcon.js
- src/Stepper/StepIcon.spec.js
- src/Stepper/StepLabel.d.ts
- src/Stepper/StepLabel.js
- src/Stepper/StepLabel.spec.js
- src/Stepper/StepPositionIcon.js
- src/internal/svg-icons/ErrorTriangle.js
- src/internal/svg-icons/Warning.js
Added error prop to StepIcon and StepLabel components. Also added one example in to docs. Please, check if it's right solution.
Closes #10619
> [Stepper] Add error prop to StepIcon and StepLabel

- src/Select/SelectInput.js
- src/Select/SelectInput.spec.js
> [Select] Fix data-value value

- pages/api/input-label.md
- src/Input/InputLabel.js
- src/Input/InputLabel.spec.js
> [TextField] Remove dead code

- .size-limit
- docs/src/modules/components/Demo.js
- docs/src/pages/utils/popovers/AnchorPlayground.js
- package.json
- packages/material-ui-docs/package.json
- yarn.lock
> [docs] Add StackBlitz demo link

- docs/src/pages/demos/text-fields/InputAdornments.js
> [docs] Fix typo TextField demo

- src/Input/Input.d.ts
> [typescript] Relax inputProps and inputComponent

- docs/src/pages/layout/grid/grid.md
- docs/src/pages/style/css-baseline/css-baseline.md
> [docs] Better CssBaseline documentation

- docs/src/pages/discover-more/showcase/showcase.md
Added showcase for Johnny Metrics. The site is done entirely in Material-UI. Looks really cool - thanks for a superb project!
> [docs] Add showcase for Johnny Metrics

- docs/src/pages/guides/flow/flow.md
> [docs] Remove flow warning

- docs/src/pages/getting-started/comparison/comparison.md
`Star` would infer it clickable
> Minor typographical fix

- src/Select/SelectInput.js
- src/Select/SelectInput.spec.js
- src/Tabs/Tabs.js
- src/Tabs/Tabs.spec.js
> [Tabs] Warn on invalid combination

- src/Select/SelectInput.d.ts
- src/Select/SelectInput.js
- src/Select/SelectInput.spec.js
> [Select] Add autoFocus prop to SelectInput

- docs/src/modules/components/AppDrawer.js
- docs/src/pages/demos/drawers/drawers.md
- src/SwipeableDrawer/SwipeableDrawer.js
- src/SwipeableDrawer/SwipeableDrawer.spec.js
- src/transitions/Fade.js
- src/transitions/Slide.js
- src/transitions/Slide.spec.js
- src/transitions/Zoom.js
- Fix the initial animation with the discoverable area
- Fix the translate position on iOS
- Fix the scrolling issue on iOS
- Fix the jump in the translate
- Tweak the documentation applied properties for a first-class experience on iOS and Android
> [SwipeableDrawer] Batch of fixes

- docs/src/modules/components/Demo.js
> [docs] Take the hideEditButton into account

- docs/src/pages/demos/drawers/drawers.md
- pages/api/swipeable-drawer.md
> [SwipeableDrawer] Add to API components list

- src/SwipeableDrawer/SwipeableDrawer.js
- src/SwipeableDrawer/SwipeableDrawer.spec.js
This fixes the drawer getting stuck when swiping a second time with a unmount/re-mounted component.
> [SwipeableDrawer] Fix consecutive usage

- docs/src/pages/premium-themes/PremiumThemes.js
- test/regressions/index.js
> [docs] Material Dashboard Pro React

- docs/src/pages/demos/progress/progress.md
> [docs] typo: reponse => response

- docs/src/modules/components/AppDrawer.js
- docs/src/modules/components/HomeFooter.js
- docs/webpackBaseConfig.js
- next.config.js
> [docs] Remove dead code

- docs/src/modules/components/AppDrawerNavItem.js
- docs/src/modules/components/MarkdownDocs.js
- pages/premium-themes/list.js
> [docs] Much better navigation experience

- src/Input/Input.js
- src/Select/SelectInput.js
Solve https://github.com/mui-org/material-ui/issues/9717#issuecomment-376372736
> [Select] Throw when the non native select is not controlled

- src/SwipeableDrawer/SwipeableDrawer.test.js
> [Drawer] Back to 100% test coverage

- .size-limit
- docs/src/modules/components/withRoot.js
- docs/src/pages/demos/text-fields/CustomizedInputs.js
- src/ButtonBase/ButtonBase.js
- src/Input/Input.js
- src/Modal/Modal.js
- src/Portal/LegacyPortal.js
- src/Portal/Portal.js
- src/Table/TablePagination.js
- src/styles/MuiThemeProvider.js
- src/styles/MuiThemeProvider.test.js
- src/styles/withStyles.js
- src/styles/withStyles.test.js
- src/styles/withTheme.js
- yarn.lock
> [core] Work on React 16.3.0 support

- examples/cdn/index.html
> [examples] Demonstrate how to use the icons CDN

- docs/src/modules/components/Demo.js
- docs/src/pages/discover-more/team/team.md
- docs/src/pages/getting-started/usage/usage.md
- docs/src/pages/premium-themes/premium-themes.md
- docs/src/pages/style/color/color.md
> [docs] Add hideHeader option to Demo component

- docs/src/modules/components/AppWrapper.js
- docs/src/modules/utils/find.js
- next.config.js
- yarn.lock
> [docs] Dodge issue with hoist-non-react-statics

- src/index.d.ts
> [Zoom] Export Zoom in the TypeScript definitions

- src/SwipeableDrawer/SwipeableDrawer.js
- src/SwipeableDrawer/SwipeableDrawer.test.js
Closes #10863, but at least it adds a test to reproduce the issue. :wink:
> [SwipeableDrawer] Fix crash when swiping during an update

- docs/src/modules/components/AppContent.js
- docs/src/pages/premium-themes/PremiumThemes.js
> [docs] Improve the layout for premium themes

- docs/src/pages/guides/typescript/typescript.md
> [docs] Fix example in TypeScript docs

- docs/src/pages/demos/steppers/TextMobileStepper.js
> [docs] Atomic state update in the Stepper demo

- README.md
- docs/src/pages/getting-started/installation/installation.md
Closes #10846, I have updated the urls.
This is my first pull request, if there are anything else, please guide.
Thanks
> [docs] Fix npm urls

- src/styles/MuiThemeProvider.js
> [styles] Add a warning to prevent a memory leak

- docs/src/pages/getting-started/faq/faq.md
> [docs] Add "Do I have to use JSS?" to FAQ

- .size-limit
- src/Select/SelectInput.js
- src/Select/SelectInput.test.js
> [Select] Fix width update

- docs/src/modules/components/AppWrapper.js
- package.json
- src/ButtonBase/ButtonBase.js
- src/Modal/Modal.js
- src/Snackbar/Snackbar.js
- src/SwipeableDrawer/SwipeableDrawer.js
- src/transitions/Slide.js
- yarn.lock
> [core] Upgrade dev dependencies

- src/Tooltip/Tooltip.js
> [Tooltip] Remove title from chldrenProps

- packages/material-ui-lab/package.json
> [lab] Bump version for @material-ui/icons dependency

- docs/src/pages/demos/drawers/MiniDrawer.js
- src/Drawer/Drawer.js
> [Drawer] Improve the "Mini variant drawer" demo

- src/index.d.ts
- src/index.js
> [core] Export all the style modules

- pages/api/grid.md
- src/Grid/Grid.js
- src/Grid/Grid.test.js
Support dynamic `xs`/`sm`/`md`/… values:
```jsx
<Grid item xs={Boolean(foo)} />
```
> [Grid] Update propTypes to accept false

- docs/src/pages/guides/minimizing-bundle-size/minimizing-bundle-size.md
> [docs] Better private/public API description

- pages/api/collapse.md
- src/transitions/Collapse.js
It think the title is descriptive enough. :)
> [Collapse] Fix typo in comment

- packages/material-ui/src/Dialog/Dialog.js
- packages/material-ui/src/Dialog/DialogContent.js
> [Dialog] Fix iOS momentum scroll

- .size-limit
- BACKERS.md
- docs/src/pages/demos/expansion-panels/ControlledExpansionPanels.js
- docs/src/pages/demos/expansion-panels/DetailedExpansionPanel.js
- docs/src/pages/demos/expansion-panels/SimpleExpansionPanel.js
- packages/material-ui/src/ExpansionPanel/ExpansionPanel.js
- packages/material-ui/src/ExpansionPanel/ExpansionPanelDetails.js
> [ExpansionPanel] Fix display on IE11 and Edge

- packages/material-ui/src/Icon/Icon.js
> [Icon] Prevent shrinking when inside a flex container

- docs/src/pages/customization/themes/TypographyTheme.js
- docs/src/pages/demos/buttons/CustomizedButtons.js
- docs/src/pages/demos/tabs/CustomizedTabs.js
- docs/src/pages/demos/tabs/tabs.md
- docs/src/pages/demos/text-fields/CustomizedInputs.js
> [Tabs] Better Ant Design demo

- docs/src/pages/discover-more/showcase/showcase.md
https://topheman.github.io/npm-registry-browser
> [docs] Add npm-registry-browser into showcase

- examples/create-react-app-with-flow/flow-typed/npm/material-ui_v1.x.x.js
> [docs] Fix the flow example

- docs/src/pages/discover-more/showcase/showcase.md
Would like to add our app, [Local Insights](https://localinsights.io), to your showcase. We **_love_** MUI, and we stand on the shoulders of you giants.
> [docs] Add showcase for Local Insights

- packages/material-ui/src/Card/CardMedia.js
- packages/material-ui/src/Card/CardMedia.test.js
Closes https://github.com/mui-org/material-ui/issues/11125
> [CardMedia] Escape background image url

- packages/material-ui-docs/src/MarkdownElement/MarkdownElement.js
Add ios momentum scrolling to `table` and `pre` elements
> [docs] Add iOS momentum scrolling

- docs/src/pages/customization/themes/themes.md
> [docs] Fix typo in themes.md

- .babelrc
Fix @phallguy's feedback in https://github.com/mui-org/material-ui/pull/10144#issuecomment-384326406
> [lab] Fix the tests

- docs/src/modules/components/AppFrame.js
- docs/src/pages/guides/interoperability/interoperability.md
> [docs] Add a CSS modules example

- package.json
> Add sideEffects: false for webpack 4

- docs/src/pages/utils/popovers/AnchorPlayground.js
- docs/src/pages/utils/popovers/SimplePopover.js
- docs/src/pages/utils/popovers/popovers.md
- pages/utils/popovers.js
- Add a simple demo so people can copy&paste it
- Add a code output of the anchor playground demo so people can copy&paste it
- Add a visual code color to group the anchor and transform (Prägnanz)
- Add a visual dot so people better understand what the anchor is for
> [Popover] Improve the demos

- docs/src/pages/demos/dialogs/FormDialog.js
> [docs] Correct spelling error in FormDialog.js example

- yarn.lock
> [test] Fix the CI

- packages/material-ui/src/ButtonBase/ButtonBase.d.ts
> [ButtonBase] Update TypeScript to sync with the implementation

- examples/create-react-app-with-flow/flow-typed/npm/material-ui_v1.x.x.js
Fix @lucaas feedback https://github.com/mui-org/material-ui/pull/11188/files#r185181810.
> [example] Revert wrong change

- packages/material-ui/src/ButtonBase/ButtonBase.js
- packages/material-ui/src/Chip/Chip.js
- packages/material-ui/src/Dialog/Dialog.js
- packages/material-ui/src/Drawer/Drawer.js
- packages/material-ui/src/Popover/Popover.js
- packages/material-ui/src/Table/TableRow.js
This change should make the outline customization easier. It's also a bit less code :).
> [styles] Simpler outline reset

- packages/material-ui-lab/src/SpeedDial/SpeedDial.js
- packages/material-ui/src/Dialog/Dialog.js
- packages/material-ui/src/Popover/Popover.js
- packages/material-ui/src/Snackbar/Snackbar.js
- packages/material-ui/src/Stepper/StepContent.js
- pages/api/dialog.md
- pages/api/popover.md
- pages/api/snackbar.md
- pages/api/step-content.md
- pages/lab/api/speed-dial.md
Add extra customization points.
> [Transition] Add a TransitionProps

- packages/material-ui/src/Table/TablePagination.d.ts
- packages/material-ui/src/Table/TablePagination.js
- pages/api/table-pagination.md
> [TablePagination] Allow the MenuItem customization

- docs/notifications.json
Change version to v1.0.0-beta.44
> [docs] Update notification

- docs/src/pages/guides/testing/testing.md
It should help people decide wheater they should use our testing helper or not. Most of them shouldn't.
Closes #11183.
> [docs] Clarify the difference with enzyme

- docs/src/pages/customization/overrides/ClassesNesting.js
- docs/src/pages/customization/overrides/ClassesState.js
- docs/src/pages/customization/overrides/overrides.md
- pages/customization/overrides.js
This topic hasn't been covered yet in the documentation.
Closes #11223
> [docs] Add a note on the override of internal states

- .size-limit
- packages/material-ui/src/styles/withStyles.js
- packages/material-ui/src/styles/withStyles.test.js
> [withStyles] Memoization the classes property

- docs/src/pages/customization/themes/OverridesCss.js
- docs/src/pages/customization/themes/OverridesProperties.js
- docs/src/pages/customization/themes/themes.md
- pages/customization/themes.js
> [docs] Document the theme.props feature

- packages/material-ui-docs/src/NProgressBar/NProgressBar.js
- Fix RTL display
- Follow the YouTube implementation more closely
> [NProgress] Better RTL support and closer to YouTube version

- docs/src/pages/demos/tables/CustomPaginationActionsTable.js
- docs/src/pages/demos/tables/CustomizedTable.js
- docs/src/pages/demos/tables/EnhancedTable.js
- docs/src/pages/demos/tables/SimpleTable.js
- docs/src/pages/demos/tables/tables.md
- packages/material-ui/src/Table/TableCell.js
I don't think this is the whole story, but it's a small improvement.
> [docs] Improve the table examples' accessibility

- packages/material-ui/package.json
- yarn.lock
> [core] npm shouldn't be a dependency

- packages/material-ui/src/Progress/CircularProgress.d.ts
- packages/material-ui/src/Snackbar/Snackbar.d.ts
Fix type defintions for #11211 and #11204
> [typescript] Fix type defintions for #11211 and #11204

- docs/src/pages/discover-more/showcase/showcase.md
I have added Pilcro to showcase app. Thanks.
> [docs] Add Pilcro to showcase apps

- docs/src/app/components/pages/discover-more/Showcase.js
I'm the owner of www.brainbok.com and would like to remove the site from the showcase of 0.x branch. We'll add it to the 1.x branch after migration.
> [docs] Remove BrainBOK from showcase

- .babelrc
- packages/material-ui/package.json
- yarn.lock
- Closes #11285 
- Address @NMinhNguyen's concern in the umd/dev module
> [core] Add @babel/runtime as a dependency

- .size-limit
- docs/src/pages/demos/progress/CircularDeterminate.js
- docs/src/pages/demos/progress/CircularStatic.js
- packages/material-ui/src/Progress/CircularProgress.js
- packages/material-ui/src/Progress/CircularProgress.test.js
- packages/material-ui/src/Progress/LinearProgress.js
- pages/api/circular-progress.md
> [CircularProgress] Add transition for static variant

- packages/material-ui/src/styles/createTypography.js
Consistency improvement
resolves #11315
> [createTypography] Add primary text color to 'button' typography variant

- docs/src/pages/discover-more/showcase/showcase.md
We have finished converting our production site from Foundation to Material UI. So happy with the process and result. Thx material-ui team!
> [docs] Add HIJUP.com to the showcase site

- docs/src/pages/layout/grid/SpacingGrid.js
- docs/src/pages/layout/grid/grid.md
- packages/material-ui/src/Grid/Grid.d.ts
- packages/material-ui/src/Grid/Grid.js
- pages/api/grid.md
The issue #11332 bring the question about 32 pixels was not listed as a space option.
Linking the right resources and with @oliviertassinari approval, I send this PR to add *32px* spacing.
Closes #11332
> [Grid] Add 32px gutter to grid spacing

- docs/src/pages/demos/buttons/FlatButtons.js
- docs/src/pages/demos/buttons/OutlinedButtons.js
- docs/src/pages/demos/buttons/RaisedButtons.js
> [docs] Make the button examples consistent

- README.md
Updated the installation instructions to include yarn package manager.
> [docs] Install with yarn

- docs/notifications.json
To merge once v1.0.0-rc.0 is released.
> [docs] Update notifications for v1.0.0-rc.0

- packages/material-ui-codemod/src/v1.0.0/import-path.test/actual.js
- packages/material-ui-codemod/src/v1.0.0/import-path.test/expected.js
The codemod was applied on the test case. Not good!
> [codemod] Revert the codemod inception on the tests

- .size-limit.js
- docs/src/pages/demos/selects/NativeSelects.js
- docs/src/pages/demos/selects/selects.md
- packages/material-ui/src/FormControl/FormControl.js
- packages/material-ui/src/NativeSelect/NativeSelect.d.ts
- packages/material-ui/src/NativeSelect/NativeSelect.js
- packages/material-ui/src/NativeSelect/NativeSelect.test.js
- packages/material-ui/src/NativeSelect/NativeSelectInput.d.ts
- packages/material-ui/src/NativeSelect/NativeSelectInput.js
- packages/material-ui/src/NativeSelect/NativeSelectInput.test.js
- packages/material-ui/src/NativeSelect/index.d.ts
- packages/material-ui/src/NativeSelect/index.js
- packages/material-ui/src/Select/Select.js
- packages/material-ui/src/Select/SelectInput.d.ts
- packages/material-ui/src/Select/SelectInput.js
- packages/material-ui/src/Select/SelectInput.test.js
- packages/material-ui/src/index.d.ts
- packages/material-ui/src/index.js
- packages/material-ui/src/styles/overrides.d.ts
- packages/material-ui/src/styles/props.d.ts
- pages/api/native-select.js
- pages/api/native-select.md
- pages/demos/selects.js
Save 15 kB gzipped for someone who only wants to use the NativeSelect component over the Select component.
- Select package size: 46.55 KB
- NativeSelect package size: 32.43 KB
Closes #10335
> [NativeSelect] New component

- docs/_headers
- package.json
- pages/_document.js
- yarn.lock
https://www.netlify.com/docs/headers-and-basic-auth/
> [docs] Better netlify cache control

- packages/material-ui/src/StepLabel/StepLabel.js
- packages/material-ui/src/Tooltip/Tooltip.js
- packages/material-ui/src/Tooltip/Tooltip.test.js
- pages/api/tooltip.md
> [core] Remove some dead code

- README.md
> [docs] Update docs links in README.md

- docs/src/pages/versions/LatestVersion.js
- docs/src/pages/versions/StableVersions.js
> [docs] Link most recent version to main docs site

- docs/notifications.json
> [docs] Fixed notification releases message

- docs/src/pages/demos/lists/NestedList.js
> [ListSubheader] Fix demo import path

- examples/create-react-app-with-typescript/src/pages/index.tsx
> [examples] Fix imports for Dialog

- docs/_headers
> [docs] Add HSTS header

- examples/create-react-app-with-jss/src/withRoot.js
> [examples] Fix create-react-app-with-jss theme object

- pages/index.js
How I probably should have dome in in the first place!
> [docs] Fix hyphen for iOS

- .github/ISSUE_TEMPLATE.md
> [github] Update the issue template

- packages/material-ui-lab/src/SpeedDialIcon/SpeedDialIcon.js
> [SpeedDial] Clean up SpeedDialIcon transition

- docs/src/pages/demos/selection-controls/CustomizedSwitches.js
- docs/src/pages/demos/selection-controls/RadioButtonsGroup.js
- docs/src/pages/demos/selection-controls/SwitchLabels.js
- docs/src/pages/demos/selection-controls/selection-controls.md
- pages/demos/selection-controls.js
> [docs] Add Customized Switches section

- packages/material-ui/src/ListItemText/ListItemText.js
> [ListItemText] Shouldn't be a heading by default

- packages/material-ui/src/GridListTileBar/GridListTileBar.d.ts
> [GridListTileBar] Add missing title and subtitle keys

- docs/src/pages/style/typography/Types.js
> [docs] Remove background grid from Typography variants demo

- packages/material-ui/src/TableCell/TableCell.js
> [TableCell] Fix padding for last TableCell if checkbox

- docs/src/pages/demos/buttons/ButtonSizes.js
- docs/src/pages/demos/buttons/buttons.md
> [docs] Add outlined buttons to ButtonSizes  demo

- packages/material-ui/src/Button/Button.js
- packages/material-ui/src/ButtonBase/ButtonBase.js
- pages/api/button-base.md
- pages/api/button.md
> [Button][ButtonBase] Take advantage of defaultProps for component prop

- docs/src/pages/customization/css-in-js/css-in-js.md
- docs/src/pages/guides/minimizing-bundle-size/minimizing-bundle-size.md
- docs/src/pages/guides/server-rendering/server-rendering.md
- packages/material-ui/package.json
- yarn.lock
Closes #11569
The next step is to improve the troubleshooting section and to look into a debug mode for a faster debug experience.
> [docs] Add a Troubleshooting section for SSR

- docs/src/pages/guides/typescript/typescript.md
> [docs] Fix a little typo in typescript docs

- docs/src/pages/lab/slider/DisabledSlider.js
- docs/src/pages/lab/slider/ReverseSlider.js
- docs/src/pages/lab/slider/SimpleSlider.js
- docs/src/pages/lab/slider/StepSlider.js
- docs/src/pages/lab/slider/VerticalSlider.js
Imports fixed, but docs error for me...
> [docs] Fix Slider demo imports

- packages/material-ui-lab/src/SpeedDial/SpeedDial.js
- pages/lab/api/speed-dial.md
> [SpeedDial] Fix classes prop description

- docs/src/pages/customization/overrides/overrides.md
Update component names referenced in descriptions to match component names in code samples.
> [docs] Update overrides.md

- packages/material-ui/package.json
> [core] Add cross-env back

- packages/material-ui/src/ListItem/ListItem.d.ts
> [ListItem] Fix typings for ListItem

- docs/src/modules/redux/initRedux.js
- packages/material-ui/src/Tab/Tab.js
- packages/material-ui/src/Tab/Tab.test.js
- One step closer to have IE11 run in dev mode
- Same state wording than the class.
> [core] Some fixes looking into issues

- .size-limit.js
- docs/src/pages/getting-started/faq/faq.md
- docs/src/pages/guides/server-rendering/server-rendering.md
- packages/material-ui/src/styles/createGenerateClassName.js
> [styles] Better class name conflict warning

- docs/src/modules/components/AppWrapper.js
- docs/src/pages/demos/selects/ControlledOpenSelect.js
- docs/src/pages/demos/selects/NativeSelects.js
- docs/src/pages/demos/selects/SimpleSelect.js
- packages/material-ui-lab/src/Slider/Slider.js
- packages/material-ui/src/ButtonBase/ButtonBase.js
- packages/material-ui/src/Modal/Modal.js
- packages/material-ui/src/Select/SelectInput.js
- packages/material-ui/src/Snackbar/Snackbar.js
- packages/material-ui/src/SwipeableDrawer/SwipeableDrawer.js
- yarn.lock
- Add a placeholder demo
- Fix some W3C issues, but it's not over.
Closes #8813
> [docs] Add a placeholder demo

- packages/material-ui/src/RootRef/RootRef.d.ts
Update RootRef.d.ts to reflect the implementation change.
fixes https://github.com/mui-org/material-ui/pull/11681
> [RootRef] Update RootRef.d.ts

- packages/material-ui/src/styles/transitions.js
> [transition] Fix IE11 issue in dev mode

- packages/material-ui/src/Tab/Tab.js
> [Tabs] Better flex layout

- docs/src/pages/getting-started/usage/usage.md
Since the first exemple we see is a button, I propose to follow this by switching the link to the button's demo.
> [docs] Change app bar to button on the getting started

- docs/src/pages/discover-more/related-projects/related-projects.md
React Most Wanted uses 100% Material-UI v1 and only Material-UI :)
> [docs] Add React Most Wanted to related projects

- docs/src/pages/customization/themes/themes.md
Change `calculate` to `calculated`.
> Simple Grammar Fix

- docs/src/pages/guides/server-rendering/server-rendering.md
> [docs] Better troubleshooting action for the hydration mismatch

- packages/material-ui-lab/src/SpeedDial/SpeedDial.js
- packages/material-ui-lab/src/SpeedDial/SpeedDial.test.js
- packages/material-ui/src/Dialog/Dialog.js
- packages/material-ui/src/DialogTitle/DialogTitle.js
- packages/material-ui/src/MenuList/MenuList.js
- packages/material-ui/src/RadioGroup/RadioGroup.js
- packages/material-ui/src/internal/SwitchBase.js
- packages/material-ui/test/integration/fixtures/menus/SimpleMenu.js
> [core] Remove dead code

- pages/index.js
> [docs] Add structured data

- packages/material-ui/src/Grid/Grid.js
- packages/material-ui/src/Grid/Grid.test.js
- pages/api/grid.md
Thanks @neoziro for raising the issue! The use case:
```jsx
<Grid item xs sm="auto" md={6}>
```
> [Grid] Add support a auto value

- packages/material-ui/src/index.d.ts
- packages/material-ui/src/index.js
I have included RootRef as an export for the main index.js so imports should now work.  Fixes #11815.
> [RootRef] Updated main index.js to include RootRef export

- packages/material-ui/src/Tabs/Tabs.js
> [Tabs] Fix IE11 support

- docs/src/pages/layout/breakpoints/breakpoints.md
- packages/material-ui/src/withWidth/withWidth.js
- packages/material-ui/src/withWidth/withWidth.test.js
This new property intent to set the initialWidth value globally using a theme custom prop, making this an easy way to use an initial with when we are doing SSR.
P.S: My first PR here, let me know how I can improve or fix any error.
> [withWidth] Reading initialWidth from the theme

- docs/src/pages/demos/selects/NativeSelects.js
- docs/src/pages/demos/selects/SimpleSelect.js
> [docs] Add a Select required example

- docs/src/pages/customization/css-in-js/css-in-js.md
- docs/src/pages/getting-started/faq/faq.md
> [docs] Better class names conflict FAQ

- docs/src/pages/discover-more/related-projects/related-projects.md
> [docs] Add a link toward dx-react-chart-material-ui

- packages/material-ui/src/Dialog/Dialog.js
- packages/material-ui/src/GridListTile/GridListTile.js
- packages/material-ui/src/Select/Select.js
> [core] Remove some unneeded code

- examples/cdn/README.md
- package.json
- packages/material-ui/.size-snapshot.json
- packages/material-ui/package.json
- packages/material-ui/scripts/rollup.config.js
- yarn.lock
> [core] Fix the UMD release

- docs/src/pages/guides/server-rendering/server-rendering.md
- examples/parcel/package.json
- examples/ssr/.babelrc
- examples/ssr/.gitignore
- examples/ssr/App.js
- examples/ssr/README.md
- examples/ssr/client.js
- examples/ssr/package.json
- examples/ssr/server.js
- examples/ssr/webpack.config.js
Provide something low level (Next.js and Gatsby are working at a higher level of abstraction, they also address much more problem), the main advantage of the `ssr` example is its simplicity.
Closes #11410
> [examples] Add Server Rendering implementation

- CHANGELOG.md
- packages/material-ui/src/Select/SelectInput.js
- packages/material-ui/src/Select/SelectInput.test.js
It's the third try after #10706 and #10956. If it fails again, we might just leave the bug present and let people use the `autoWidth` property to get around the issue.
Closes #10643
> [Select] Fix reflow in render

- docs/src/pages/customization/overrides/DynamicCSSVariables.js
- docs/src/pages/customization/overrides/DynamicClassName.js
- docs/src/pages/customization/overrides/DynamicThemeNesting.js
- docs/src/pages/customization/overrides/overrides.md
- packages/material-ui-docs/src/NoSSR/NoSSR.js
- packages/material-ui/src/GridListTile/GridListTile.js
Using the React suspense API as inspiration:
https://medium.com/@baphemot/understanding-react-suspense-1c73b4b0b1e6
> [NoSSR] Add a fallback property

- packages/material-ui/src/Dialog/Dialog.js
Fix the regression.
Closes #11909
> [Dialog] Add max-height back

- packages/material-ui/src/FormControl/FormControl.js
- pages/api/form-control.md
> [FormControl] Correct minor typo in text

- packages/material-ui/src/ButtonBase/ButtonBase.d.ts
- packages/material-ui/src/styles/createTypography.d.ts
Fixes typings for PR #11820 and PR #11802
> [typescript] Fix Typings for disableTouchRipple and allVariants

- packages/material-ui-icons/README.md
> [docs] Add Outline docs

- docs/src/pages/customization/css-in-js/css-in-js.md
- packages/material-ui/src/Input/Input.js
- packages/material-ui/src/RadioGroup/RadioGroup.js
- packages/material-ui/src/Select/SelectInput.js
> [Select] Fix some W3C issues

- packages/material-ui/src/GridList/GridList.js
- packages/material-ui/src/GridListTile/GridListTile.js
- packages/material-ui/src/GridListTile/GridListTile.test.js
> [GridList] Clean the rendering logic

- .size-limit.js
- docs/src/modules/components/Link.js
- docs/src/pages/demos/tabs/tabs.md
- docs/src/pages/style/icons/FontAwesome.js
- docs/src/pages/style/icons/icons.md
- pages/style/icons.js
- yarn.lock
> [docs] Add a demo with Font Awesome

- docs/src/pages/style/icons/icons.md
> Fix wrong icon names

- examples/ssr/package.json
- examples/ssr/webpack.config.js
> [docs] Fix example code to accept production mode rendering

- packages/material-ui/src/Popover/Popover.js
Sorry for being a grammar nazi
> [core] Error typo fix

- test/regressions/TestViewer.js
- test/regressions/index.js
Wait for Font Awesome to be loaded.
> [test] Fix Argos-CI flakyness

- docs/src/pages/guides/migration-v0x/migration-v0x.md
> [docs] Add Subheader to v0.x migration guide

- docs/src/pages/getting-started/installation/installation.md
> [docs] Add a comment that React 16.3.0 is a peer dependency

- packages/material-ui/src/styles/createTypography.js
> [Typography] Fix display2 cuts off the bottom of a 'g'

- docs/src/pages/guides/migration-v0x/migration-v0x.md
> [docs] Add Toggle Selection Control to 'Migration From v0.x' Document

- docs/src/pages/guides/migration-v0x/migration-v0x.md
> [docs] Add Menu Item to 'Migration From v0.x' Document

- docs/src/pages/guides/migration-v0x/migration-v0x.md
> [docs] Add Font Icon to 'Migration From v0.x' Document

- packages/material-ui/src/ButtonBase/createRippleHandler.js
- packages/material-ui/src/Modal/Modal.js
- packages/material-ui/src/Modal/Modal.test.js
> [Modal] Ignore if the event prevent default is called

- .babelrc
> [core] Fix babel plugin name

- docs/src/pages/utils/popper/PositionedPopper.js
- packages/material-ui/src/Popper/Popper.js
- packages/material-ui/src/Popper/Popper.test.js
> [Popper] Fix update logic

- BACKERS.md
- docs/src/pages/demos/badges/CustomizedBadge.js
- docs/src/pages/demos/badges/SimpleBadge.js
- docs/src/pages/demos/badges/badges.md
- packages/material-ui/src/Badge/Badge.js
- pages/demos/badges.js
Use https://store.google.com/cart as reference:
> [Badge] Increase readability

- packages/material-ui/src/styles/createGenerateClassName.js
Fix @jmcpeak concern in https://github.com/mui-org/material-ui/pull/11943#issuecomment-403094794
> [styles] Increase the class name lenght limit before raising

- packages/material-ui/package.json
- yarn.lock
> [Popper] Increase the minimal required version of popper.js

- packages/material-ui/src/TablePagination/TablePagination.d.ts
> [TablePagination] Add missing selectIcon ClassKey definition

- packages/material-ui/src/Button/Button.js
> [Button] Fix icon positioning on Safari iOS

- docs/src/pages/customization/css-in-js/css-in-js.md
> [docs] Add a note on the name option and dangerouslyUseGlobalCSS

- packages/material-ui/src/Modal/Modal.d.ts
> [Modal] Add onRendered to ModalProps

- docs/src/pages/demos/cards/RecipeReviewCard.js
- packages/material-ui/src/CardHeader/CardHeader.js
> [Card] Align icons with ListItem

- CONTRIBUTING.md
- packages/material-ui/src/BottomNavigationAction/BottomNavigationAction.js
- packages/material-ui/src/ListItem/ListItem.js
- pages/api/bottom-navigation-action.md
- pages/api/list-item.md
Improve documentation for:
* `ListItem` `disabled` property
* `BottomNavigationAction` `showLabel` property
> [docs] Improve ListItem and BottomNavigationAction docs

- packages/material-ui/src/LinearProgress/LinearProgress.js
> [LinearProgress] Fix wrong style rule usage

- packages/material-ui/src/Popper/Popper.js
> [Popper] Fix modifiers appearing as attribute of div

- packages/material-ui-lab/src/ToggleButton/ToggleButton.d.ts
- packages/material-ui-lab/src/ToggleButton/ToggleButtonGroup.d.ts
> [ToggleButton] Fix TypeScript definition

- packages/material-ui/src/styles/createGenerateClassName.js
- packages/material-ui/src/styles/createGenerateClassName.test.js
> [styles] Improve the dangerouslyUseGlobalCSS story

- docs/src/pages/demos/chips/ChipsPlayground.js
> [docs] Fix ChipPlayground generated code

- packages/material-ui/src/styles/createPalette.js
- packages/material-ui/src/styles/createPalette.test.js
> [palette] Better defensive logic

- docs/src/pages/customization/themes/themes.md
> [docs] Improve the withTheme example

- docs/src/pages/demos/autocomplete/IntegrationAutosuggest.js
- docs/src/pages/demos/autocomplete/IntegrationDownshift.js
- docs/src/pages/demos/autocomplete/IntegrationReactSelect.js
- docs/src/pages/demos/autocomplete/autocomplete.md
> [docs] Better autocomplete docs

- packages/material-ui/src/Input/Input.js
> [Input] Use the color from the theme

- BACKERS.md
- README.md
- docs/src/modules/components/HomeBackers.js
> [README] New iteration on the backers

- docs/src/pages/style/icons/icons.md
Added some reasoning on which approach to use. Feel free to criticize or add any comment 😉
> [docs] Font vs SVG. Which approach to use?

- GOVERNANCE.md
Was pointing to twitter notifications instead of actual account :)
> [docs] Fix link to twitter account

- packages/material-ui/src/TextField/TextField.js
> [TextField] Fix disabled prop only affecting the Input component

- docs/src/pages/utils/modal/modal.md
Fixing minor typo:
"Adds the appropriate ARIA roles ~~are~~ automatically."
> [docs] Fix a typo in the Modal page

- .eslintrc.js
- docs/src/modules/components/CodeFund.js
- yarn.lock
Update some dev dependencies too.
> [docs] Don't load the ad on mobile

- docs/src/pages/page-layout-examples/dashboard/README.md
> [docs] Fix typo (suot to suit)

- docs/src/pages/utils/popper/popper.md
- packages/material-ui/src/Checkbox/Checkbox.js
- packages/material-ui/src/Switch/Switch.js
- packages/material-ui/src/internal/SwitchBase.js
- packages/material-ui/src/internal/SwitchBase.test.js
> [docs] Increase SEO potential

- packages/material-ui/src/LinearProgress/LinearProgress.js
- pages/api/linear-progress.md
for consistency with other descriptions
> [docs] "codestyle" comment typo fix

- docs/src/pages/demos/tables/EnhancedTable.js
> [docs] Fix the broken Table sorting logic

- docs/src/pages/page-layout-examples/PageLayoutExamples.js
- docs/src/pages/page-layout-examples/sign-in/SignIn.js
Also, sort the demos by page layout examples popularity.
Closes #12586
> [docs] Fix a display issue on IE11

- .circleci/config.yml
> [test] Fix the missing libxcursor1 binary

- .size-limit.js
- babel.config.js
- packages/material-ui/src/ListSubheader/ListSubheader.d.ts
- packages/material-ui/src/test-utils/createShallow.js
> [core] Let's see if the CI catch the issue

- docs/src/pages/layout/breakpoints/breakpoints.md
Changed the xlarge: on line 13 to extra-large, to be consistent with extra-small on line 13
> [docs] xlarge = extra-large

- packages/material-ui/src/TableSortLabel/TableSortLabel.d.ts
- packages/material-ui/src/TableSortLabel/TableSortLabel.js
- packages/material-ui/src/TableSortLabel/TableSortLabel.test.js
- pages/api/table-sort-label.md
adding custom IconComponent prop to TableSortLabel, test for presence…and ts type
Closes #12618
> [TableSortLabel] Support custom icon component

- packages/material-ui/src/Collapse/Collapse.js
- pages/api/collapse.md
Fix a small copy-paste error in the doc.
> [Collapse] Fix document for style wrapperInner.

- docs/src/pages/getting-started/usage/usage.md
> [docs] Fix typo in usage.md

- CHANGELOG.md
> [docs] Typo

- packages/material-ui/src/Checkbox/Checkbox.js
- packages/material-ui/src/Checkbox/Checkbox.test.js
React is not supporting input indeterminate property, and not sure if they have plans to do it ([react issue](https://github.com/facebook/react/issues/1798#issuecomment-333414857)), so i added their proposed solution inside mui component.
> [Checkbox] Improve indeterminate status

- examples/create-react-app-with-flow/package.json
- packages/material-ui-docs/package.json
- packages/material-ui-icons/package.json
- packages/material-ui-lab/package.json
> [core] Fix for incorrect peer dependency version warning

- packages/material-ui/src/StepLabel/StepLabel.js
> [StepLabel] Fix custom icon spacing

- packages/material-ui/src/Stepper/Stepper.js
- packages/material-ui/src/Stepper/Stepper.test.js
> [Stepper] Add a new test case

- docs/src/pages/demos/autocomplete/IntegrationDownshift.js
> [docs] Improve the Downshift demo

- packages/material-ui/src/Tab/Tab.js
> [Tab] Ability change font size of tab

- examples/create-react-app-with-typescript/src/withRoot.tsx
See https://stackoverflow.com/questions/51993988.
> [examples] Fix typing of `withRoot` to accept props

- packages/material-ui/src/Dialog/Dialog.js
> [Dialog] Remove dialog margin when fullScreen=true and scroll=body

- docs/src/pages/demos/tables/EnhancedTable.js
Improved table sorting logic in demo based on https://medium.com/@fsufitch/is-javascript-array-sort-stable-46b90822543f
Reference https://github.com/mui-org/material-ui/issues/12648#issuecomment-415867344
Closes #12648
> [Table] Improved sorting in table for demo EnhancedTable

- packages/material-ui/src/styles/getThemeProps.js
- packages/material-ui/src/styles/getThemeProps.test.js
- packages/material-ui/src/styles/withStyles.js
- packages/material-ui/src/styles/withStyles.test.js
- packages/material-ui/src/withWidth/withWidth.js
> [withStyles] Better theme.props support

- CHANGELOG.md
- ROADMAP.md
- docs/src/pages/versions/StableVersions.js
- docs/src/pages/versions/versions.md
> [docs] More transparency around the release strategy

- examples/create-react-app/src/index.js
- examples/create-react-app/src/registerServiceWorker.js
Should I also apply this change to `create-react-app-with-flow`, `create-react-app-with-typescript` and `create-react-app-with-jss` for consistency?
> [docs] Enable service worker by default as the latest CRA

- docs/src/pages/discover-more/related-projects/related-projects.md
New DataTable based on table component with additional features like search, filtering, sorting and much more.
> New DataTable component

- packages/material-ui/src/Checkbox/Checkbox.d.ts
- packages/material-ui/src/Checkbox/Checkbox.js
- packages/material-ui/src/internal/SwitchBase.d.ts
- packages/material-ui/src/internal/SwitchBase.js
- pages/api/checkbox.md
I'm pushing #12804 a bit further. I hope people now have enough flexibility to truly take advantage of the indeterminate state, both with e2e tests and style customization.
> [Checkbox] Indeterminate CSS & DOM helpers

- packages/material-ui/src/Checkbox/Checkbox.d.ts
> [Checkbox] Add indeterminateIcon type definition

- examples/gatsby/gatsby-ssr.js
- examples/gatsby/package.json
- examples/gatsby/src/withRoot.js
- packages/material-ui/src/styles/withStyles.js
> [docs] Fix the gatsby example

- packages/material-ui/src/Popover/Popover.js
- packages/material-ui/src/Popover/Popover.test.js
> [Popover] Change to offsetWidth and offsetHeight

- docs/src/pages/page-layout-examples/pricing/Pricing.js
> [docs] Fix Typo in Pricing.js

- docs/src/pages/page-layout-examples/checkout/Checkout.js
> [docs] Fix Typo in Checkout.js

- packages/material-ui/src/styles/createGenerateClassName.d.ts
> [typescript] Update createGenerateClassName.d.ts

- packages/material-ui/src/styles/withStyles.js
- packages/material-ui/src/utils/getDisplayName.js
- packages/material-ui/src/utils/getDisplayName.test.js
Fixes #12744
@oliviertassinari Hoping that's what you meant by simplified polyfill, not sure if i stripped away too much, but loads fine in IE11 and passes all tests, so 🤞
> [withStyles] Fix JSS issues in IE11 in development

- packages/material-ui/src/Hidden/HiddenJs.test.js
- packages/material-ui/src/withMobileDialog/withMobileDialog.test.js
- packages/material-ui/src/withWidth/withWidth.js
- packages/material-ui/src/withWidth/withWidth.test.js
Closes #12798.
Thank you @oliviertassinari for the example!
> [withWidth] Prevent Rerendering

- .github/ISSUE_TEMPLATE/1.bug.md
- .github/ISSUE_TEMPLATE/2.feature.md
> [github] Make issue templates version agnostic

- docs/src/pages/lab/toggle-button/ToggleButtons.js
> [docs] Fix ToggleButtons example typography variant

- packages/material-ui/src/SvgIcon/SvgIcon.js
- pages/api/svg-icon.md
> [SvgIcon] Fix minor typo in docs

- docs/src/pages/lab/speed-dial/SpeedDialTooltipOpen.js
- packages/material-ui-lab/src/SpeedDial/SpeedDial.js
> [SpeedDial] Fix ARIA & fix duplicate id in docs example

- packages/material-ui-lab/src/SpeedDialAction/SpeedDialAction.js
This is now handled by Tooltip
> [SpeedDial] Remove redundant aria-labelledby

- docs/src/pages/page-layout-examples/blog/README.md
> [docs] Fix typo in blog page layout README

- docs/src/pages/getting-started/comparison/comparison.md
> [docs] Update comparison.md

- docs/src/modules/components/Ad.js
- docs/src/modules/components/AppTableOfContents.js
- docs/src/modules/components/Carbon.js
- docs/src/modules/components/CarbonAds.js
- docs/src/modules/components/CodeFund.js
> [docs] Split test ad networks

- docs/src/pages/customization/css-in-js/css-in-js.md
> [docs] Make jss insertion point reference the same as html comment

- docs/src/pages/discover-more/related-projects/related-projects.md
- docs/src/pages/style/color/color.md
> [docs] Add reference to material-ui-theme-editor

- docs/src/pages/guides/server-rendering/server-rendering.md
It's not the first time I see someone facing this issue. Let's document it.
Closes #12894
> [docs] Add another case to check when SSR fails

- docs/src/pages/guides/right-to-left/Direction.js
- packages/material-ui/src/FormControl/FormControl.js
- packages/material-ui/src/InputBase/InputBase.js
> [TextField] Fix alignment bug in Safari

- docs/src/modules/components/GoogleTag.js
- packages/material-ui/src/Tooltip/Tooltip.js
- packages/material-ui/src/Tooltip/Tooltip.test.js
> [Tooltip] Fix unwanted tooltip opening

- packages/material-ui/src/OutlinedInput/NotchedOutline.js
> [TextField] Fix RTL support of outlined

- docs/src/pages/customization/themes/themes.md
Customize Material-UI with "your" theme
> [docs] Update themes.md

- BACKERS.md
- packages/material-ui/src/FilledInput/FilledInput.js
- packages/material-ui/src/Input/Input.js
- packages/material-ui/src/OutlinedInput/OutlinedInput.js
- pages/api/filled-input.md
- pages/api/input.md
- pages/api/outlined-input.md
> [docs] Fix documentation error in <Input />

- packages/material-ui-lab/src/SpeedDialAction/SpeedDialAction.d.ts
> [SpeedDialAction] Add missing TypeScript property

- docs/src/pages/demos/tabs/IconLabelTabs.js
- docs/src/pages/demos/tabs/IconTabs.js
> [docs] Minor style update of the tabs demos

- docs/src/pages/page-layout-examples/checkout/PaymentForm.js
> [docs] Fix Typo in PaymentForm.js

- docs/src/pages/page-layout-examples/PageLayoutExamples.js
- docs/src/pages/page-layout-examples/album/README.md
- docs/src/pages/page-layout-examples/blog/README.md
- docs/src/pages/page-layout-examples/blog/blog-post.1.md
> [docs] Fix Typo in page-layout-examples

- packages/material-ui/src/ListItem/ListItem.js
> [ListItem] Fix background color bug on mobile

- docs/src/pages/layout/grid/grid.md
> [docs] Fix typo in grid.md

- packages/material-ui/src/FormControlLabel/FormControlLabel.js
> [FormControlLabel] Reverse margins values when labelPlacement="start"
